### PR TITLE
renamed `Basic Features` to `Foundations`

### LINKED ISSUE #29853: Rename "Basic features" to "Foundations"
### Describe the feature you'd like to request

Rename "Basic features" to "Foundations". The connotations that come with the word "Basic", implies that these feature sets are not worthy of "advanced" users.

### Describe the solution you'd like

Rename "Basic feature" to "Foundations". 

**Must also fix redirects**

### Describe alternatives you've considered

N/A

### PR DESCRIPTION
**Pull request by codematrixaditya**
- fixes #29853

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Deferring to @molebox 

https://github.com/vercel/next.js/issues/29853#issuecomment-942023198

**Comment by adityatheoctocatdev** [comment]
> Deferring to @molebox 
> 
> https://github.com/vercel/next.js/issues/29853#issuecomment-942023198

I am working on the routes

**Comment by adityatheoctocatdev** [comment]
> #29853 (comment)

Hey @styfle 
i am working on the routes.

**Comment by molebox** [comment]
Hey @adityatheoctocatdev thanks for taking the time to create this PR! We are in the process of redesigning our docs structure and as such I don't think this PR will be applicable. Because of this, I'll be closing the PR.

**Pull request closed without merging**
