### PR TITLE
Examples:  Updated the example of headers to utilize the App Router

### PR DESCRIPTION
**Pull request by Sam-Phillemon9493**
This PR updates the headers example to use the App Router. Here are the changes that have been made:

- Renamed the "pages" folder to the "app" folder.
- Updated the routing for `/`, `/about`, and `/news/[...slug]` files to align with the App Router.
- Added the layout.tsx file as part of the App Router.
- Updated the `package.json` file.
- Updated the Readme file.

cc @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2ce10c6952b162d3175ed5f746775ccc178bc852

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Sam-Phillemon9493 I'm not seeing the updates made to the `package.json`?

**Comment by Sam-Phillemon9493** [comment]
> @Sam-Phillemon9493 I'm not seeing the updates made to the `package.json`?

@samcx Apologies! `package.json` was already up to date. I have removed that point from the comments above.

**Comment by samcx** [comment]
```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^18.11.5",
    "@types/react": "^18.0.23",
    "@types/react-dom": "^18.0.7",
    "typescript": "^4.8.4"
  }
}
```

@Sam-Phillemon9493 These are not the latest (e.g., `react` should be on `18.3.1`, etc.)

**Comment by Sam-Phillemon9493** [comment]
> ```
> {
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start"
>   },
>   "dependencies": {
>     "next": "latest",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0"
>   },
>   "devDependencies": {
>     "@types/node": "^18.11.5",
>     "@types/react": "^18.0.23",
>     "@types/react-dom": "^18.0.7",
>     "typescript": "^4.8.4"
>   }
> }
> ```
> 
> @Sam-Phillemon9493 These are not the latest (e.g., `react` should be on `18.3.1`, etc.)

@samcx I've updated the `react` and `react-dom` to version `18.3.1` .

**Comment by samcx** [comment]
@Sam-Phillemon9493 Don't forget the `devDependencies` as well next time!

**Review by samcx — APPROVED** [review]

**Pull request merged**
