### PR TITLE
Fix examples using __NEXT_DATA__

### LINKED ISSUE #4883: Alternative to using __NEXT_DATA__ in examples
# Usage of `__NEXT_DATA__` in examples.

## Example name
https://github.com/zeit/next.js/tree/canary/examples/with-glamor
https://github.com/zeit/next.js/tree/canary/examples/with-glamorous
https://github.com/zeit/next.js/tree/canary/examples/with-emotion
https://github.com/zeit/next.js/tree/canary/examples/with-emotion-fiber
https://github.com/zeit/next.js/tree/canary/examples/with-aphrodite
https://github.com/zeit/next.js/tree/canary/examples/with-react-with-styles
https://github.com/zeit/next.js/tree/canary/examples/with-react-intl

## Describe the bug
There are a number of examples that utilize `__NEXT_DATA__`. As I understand it, thats an internal variable that should probably not be used in the implementation of an application.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Just search GitHub : https://github.com/zeit/next.js/search?p=1&q=__NEXT_DATA__&unscoped_q=__NEXT_DATA__

## Expected behavior
It seems that in each of these cases it's just used to add `ids` to the data object. If there is another, safer way to do this, we should show that way instead.

## System information
 - Version of Next.js: Canary

### PR DESCRIPTION
**Pull request by martinbavio**
This PR fixes https://github.com/vercel/next.js/issues/4883.

It introduces a new global variable (`window.__REHYDRATE_IDS`) only when necessary.

In the case of the `with-react-with-styles` example, rehydration isn't happening, so I removed the creation of the variable. 

In the case of the `with-react-intl` example, the information doesn't seem to be set anymore on `__NEXT_DATA__`, so I just removed the default reference to it.

### CODE REVIEW

**Review by Timer — APPROVED** [review]
Thanks!

**Comment by josebrito** [comment]
I can confirm @sergonius comment. When running `getInitialProps` client-side, the messages object will be undefined.

**Comment by lfades** [comment]
A PR to fix it is very welcome 🙏

**Comment by josebrito** [comment]
@lfades for now we just kept `__NEXT_DATA__` as before.

```
const { messages } = req || (window.__NEXT_DATA__.props && window.__NEXT_DATA__.props.initialProps);
```

**Pull request merged**
