### PR TITLE
Add 'Create Server' API doc

### PR DESCRIPTION
**Pull request by stefee**
See #35377, #32562

[View Rendered](https://github.com/stefee/next.js/blob/custom-server-docs/docs/api-reference/create-server.md)

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by stefee** [comment]
@leerob I would appreciate a review!

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
As we generally don't recommend Custom Server setups due to it disabling some important optimizations, I don't think we need a separate page for this. Some of the changes in this PR is already documented in https://nextjs.org/docs/advanced-features/custom-server so let's iterate on that page instead. :+1:

**Comment by balazsorban44** [comment]
Sounds good to me.

**Comment by leerob** [comment]
> I think the key thing that's missing is the instance methods on app and the caveat around response.sent / response.end. Shall I add these to the existing docs page?

Going to close this out for now, happy to re-open and revisit after ^ has been addressed 😄 Thank you!

**Pull request closed without merging**
