### PR TITLE
enable more test cases for turbopack

### PR DESCRIPTION
**Pull request by sokra**
### What?

Enable more test cases to run with turbopack

### Why?

These test suites are passing and are not flaky.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cb427cca684569c767447d24ec7910f781eeb513

`pnpm testheadless test/e2e/middleware-fetches-with-body/index.test.ts` 
- Middleware fetches with body > with custom bodyParser sizeLimit (5mb) > should return 413 for body equal to 10mb

<details>
<summary>Expand output</summary>

  ● Middleware fetches with body › with custom bodyParser sizeLimit (5mb) › should return 413 for body equal to 10mb

    expect(received).toBe(expected) // Object.is equality

    Expected: 413
    Received: 500

      177 |       )
      178 |
    > 179 |       expect(res.status).toBe(413)
          |                          ^
      180 |
      181 |       if (!(global as any).isNextDeploy) {
      182 |         expect(res.statusText).toBe('Body exceeded 5mb limit')

      at Object.<anonymous> (e2e/middleware-fetches-with-body/index.test.ts:179:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by kwonoj** [comment]
Maybe we can consolidate with https://github.com/vercel/next.js/pull/50172 altogether?

**Comment by kwonoj** [comment]
Failures in newly enabled tests? https://github.com/vercel/next.js/actions/runs/5055328229/jobs/9081323212?pr=50154

Probably upstream flaky, not sure if we want to enable those flaky tests or not.

**Review by kwonoj — APPROVED** [review]
Pre-approving so we can ship if test passes, Othewise I'll peek later once again.

**Pull request merged**
