### PR TITLE
fixes a few inconsistencies in server routes

### PR DESCRIPTION
**Pull request by vgrafe**
I spotted a few typos in the server files, that might confuse new/unexperienced users. I hope I did catch them all!

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
This was actually done on purpose I think to show that you can render a different route. However the example is sort of obscure in doing so. So this change seems reasonable to me.

**Comment by vgrafe** [comment]
I figured after submitting, while going through the docs... I think I'd have pushed this fix over comments explaining this design choice anyway.

**Comment by timneutkens** [comment]
👍  agreed

**Comment by NeatNit** [comment]
Will anyone notice if I post here?

The way the examples are pointless as they are right now is pretty bad. I suggest changing it so that `/a` points to `apples.js` and `/b` points to `bananas.js`, and obviously rename the two files and change their contents accordingly. This way it actually demonstrates something, *and* it's not confusing (a -> **a**pples, b -> **b**ananas).

Bonus: you can add emojis 🍌🍎

**Comment by Timer** [comment]
@NeatNit feel free to send a PR improving our examples.

**Pull request merged**
