### PR TITLE
Serverless asset compatibility (e.g. Firebase)

### LINKED ISSUE #6655: Error when building with firebase
Running `npm run build` or deploying to now generates the error below
I made a small [repo here](https://github.com/billcastillo/next-firebase)

To replicate issue:

1. npm install
2. npm run build

Additional notes:
* `npm run dev` works fine, locally. I can't deploy due to error.
* Removing `target: 'serverless'` removes the error on build but I can't deploy it without the serverless config
* I am using [rebase](https://github.com/tylermcginnis/re-base) from @tylermcginnis

```
Failed to compile.

./node_modules/@firebase/database/dist/index.node.cjs.js
Module not found: Can't resolve 'request' in '/Users/next -firebase/node_modules/@firebase/database/dist'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/Users/next-firebase/node_modules/next/dist/build/index.js:99:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-next-example-app@ build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-next-example-app@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### LINKED ISSUE #7391: Cannot build next with firebase when serverless mode selected in next.config.js
# Bug report
Cannot build next with firebase when serverless mode selected in next.config.js

## Describe the bug
While building we get this error if we try to use firebase and serverless mode is turned on.

Error: package.json does not exist at /package.json

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install firebase in your project
2. Set mode:'serverless' in next.config.js
3. Do 'import * as firebase from "firebase/app"' and 'import firebase/firestore' in any page
4. do next build
5. Result: Error: package.json does not exist at /package.json

## Expected behavior
I'm expecting this to build. And since Zeit Now 2.0 only allows serverless next deployment this error makes it impossible to use now2.0

## System information
 - OS: [Windows]
 - Version of Next.js: [8.1.0]

### LINKED ISSUE #7512: How to deploy Next.js serverless on Now v2 using firebase realtime database?
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.

when deploying to now next.config.js takes forever and I am unable to deploy it.
I am using firebase realtime database.

### LINKED ISSUE #7821: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
# Bug report

## Describe the bug

Hello, I'm getting this error trying run **yarn build**. I want to deploy to now.sh my ssr app with firebase and antd. I tried **npm i && npm rebuild && npm run build** but it didn't work. 

Solutions to another issues have not working.

> gitpod /workspace/shopping $ yarn build
> yarn run v1.16.0
> warning package.json: No license field
> $ next build
> Creating an optimized production build ...
> 
>  Using external babel configuration
>  Location: "/workspace/shopping/.babelrc"
> Compiled with warnings.
> 
> ./node_modules/bytebuffer/dist/bytebuffer-node.js
> Module not found: Can't resolve 'memcpy' in '/workspace/shopping/node_modules/bytebuffer/dist'
> 
>  Build error occurred
> { Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
> Original error: Cannot find module './assets/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
>     at Object.L/Cg (/workspace/shopping/.next/serverless/pages/index.js:48582:17)
>     at __webpack_require__ (/workspace/shopping/.next/serverless/pages/index.js:23:31)
>     at Object.7noQ (/workspace/shopping/.next/serverless/pages/index.js:7759:12)
>     at __webpack_require__ (/workspace/shopping/.next/serverless/pages/index.js:23:31)
>     at Object.cJE4 (/workspace/shopping/.next/serverless/pages/index.js:62556:27)
>     at __webpack_require__ (/workspace/shopping/.next/serverless/pages/index.js:23:31)
>     at Object.z77n (/workspace/shopping/.next/serverless/pages/index.js:75069:14)
>     at __webpack_require__ (/workspace/shopping/.next/serverless/pages/index.js:23:31)
>     at Object.BYZf (/workspace/shopping/.next/serverless/pages/index.js:12181:12)
>     at __webpack_require__ (/workspace/shopping/.next/serverless/pages/index.js:23:31) code: 'MODULE_NOT_FOUND' }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone this [repo](https://github.com/skaptox/grpc-issue)
2. yarn && yarn build
3. See error

## System information

- OS: [e.g. Linux]
- Version of Next.js: 9.0.0
- Node v10.15.3

### LINKED ISSUE #7933: TypeError: require is not a function when importing an npm module in a file within the `api` folder
# Bug report

## Describe the bug

When deployed I get a TypeError: require is not a function error when importing npm module in api/allMovies.js. It works locally but not when deployed.

## To Reproduce

1. clone https://github.com/tenjojeremy/test-nextjs-simple
2. run `yarn`
3. run `yarn start`
4. open localhost: 3000
5. You should see movie posters as expected
6. Deploy site 
7. open deployed site url
8. you will see `Internal Server Error`
9. logs will show error log:

Screen Shot 2019-07-11 at 10 31 52 AM

## Expected behavior

On prod site, movies should be fetched and appear on screen on initial load 

## Additional context

Related to https://github.com/zeit/next.js/issues/7850

Thank you

### PR DESCRIPTION
**Pull request by Timer**
This pull request integrates a few weeks worth of work on `@zeit/webpack-asset-relocator-loader` to get it ready for usage in Next.js. 🙏 

Notably, this pull request allows Firebase to work **out of the box** with Serverless!

This will likely be landed after Next.js `9.0.0` is released. It's missing its companion [`@now/next`](https://github.com/zeit/now-builders/tree/canary/packages/now-next) PR.

---

Closes #7512
Closes #7391 
Closes #6655 
Closes #7821
Closes #7933
Supersedes #6073

### CODE REVIEW

**Comment by skaptox** [comment]
Hello, Will it solve this issue?

https://github.com/zeit/next.js/issues/7821

**Comment by thonydraner** [comment]
Hello, someone have an idea when this will be released ? :-)

**Comment by Ciberusps** [comment]
👀

**Comment by Pushplaybang** [comment]
as per #8052  this seems to relate to issues loading `jimp` as well as `react-ssr-prepass`

**Comment by Pushplaybang** [comment]
I hate to be that guy, but I have a client with his hair on fire because I can't deploy, is there ANYTHING I can do to help this along? 

- testing?
- merge conflict?
- backrub?

**Comment by Ciberusps** [comment]
@Pushplaybang u can implement same by your own just check how this PR works in [files](https://github.com/zeit/next.js/pull/7758/files)
U will need [zeit/webpack-asset-relocator-loader](https://github.com/zeit/webpack-asset-relocator-loader)

**Comment by Timer** [comment]
@Pushplaybang you can follow these instructions for the time being: https://github.com/zeit/next.js/issues/6073#issuecomment-467589586

**Comment by Pushplaybang** [comment]
@Timer the workaround in #6073 does not fix the issue mentioned in #8052 which is what led me here,   Once thats applied it fixes the grpc issue, and then I receive the following:

```
Jul 23 2019 09:33:28:793 | ...package.json | Module not found: Can't resolve 'iconv' in '/tmp/6c75a54f/node_modules/encoding/lib'
-- | -- | --
Jul 23 2019 09:33:29:413 | ...package.json | Warning: You have opted-out of Automatic Prerendering due to `getInitialProps` in `pages/_app`.
Jul 23 2019 09:33:29:413 | ...package.json | Read more: https://err.sh/next.js/opt-out-automatic-prerendering
Jul 23 2019 09:33:30:462 | ...package.json | > Build error occurred
Jul 23 2019 09:33:30:464 | ...package.json | { Error: Failed to load /tmp/6c75a54f/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node. Module did not self-register.
Jul 23 2019 09:33:30:464 | ...package.json | at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
Jul 23 2019 09:33:30:464 | ...package.json | at Module.load (internal/modules/cjs/loader.js:600:32)
Jul 23 2019 09:33:30:464 | ...package.json | at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Jul 23 2019 09:33:30:464 | ...package.json | at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Jul 23 2019 09:33:30:464 | ...package.json | at Module.require (internal/modules/cjs/loader.js:637:17)
Jul 23 2019 09:33:30:464 | ...package.json | at require (internal/modules/cjs/helpers.js:22:18)
Jul 23 2019 09:33:30:464 | ...package.json | at Object.<anonymous> (/tmp/6c75a54f/node_modules/grpc/src/grpc_extension.js:32:13)
Jul 23 2019 09:33:30:464 | ...package.json | at Module._compile (internal/modules/cjs/loader.js:701:30)
Jul 23 2019 09:33:30:464 | ...package.json | at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Jul 23 2019 09:33:30:464 | ...package.json | at Module.load (internal/modules/cjs/loader.js:600:32) type: 'Error', '$error': '$error' }
```

I have tried with both the specified version of the asset relocator, and the latest version

**Comment by Timer** [comment]
@Pushplaybang I don't think it's worth tracking these individually -- the latest version of these plugins have better static analysis capability (which should fix cases like `iconv`).

However, only versions `0.5.x` are compatible with Next.js at the moment -- we're working on integrating the latest version in this PR.

**Comment by Pushplaybang** [comment]
@Timer great, having applied the fix mentioned  with the asset relocator is what I've been using for some time, though I'm still blocked on deployment having upgraded to v9.  As you;ve  closed one issue, and marked another comment as spam, could you please advise:

- is there a current workaround, 
- should I attempt to use this branch
- should I open another separate issue regarding iconv? 

just to reiterate, I was able to deploy prior to v9.  Please tell me how I can either assist, or get help with this issue.

**Comment by Vista1nik** [comment]
Hello. Any progress on this?

**Comment by Timer** [comment]
No progress to report. It has been prioritized to be done soon, however.

**Comment by Timer** [comment]
The latest Next.js canary should now work with Firebase when deployed to Now with the `@now/next@canary` builder! 😄

**Comment by antonnyman** [comment]
I'm still getting the error
```sh
Module not found: Can't resolve 'request' in '/tmp/e991867/node_modules/@firebase/database/dist'
```
on `@now/next@canary` with `"firebase": "^6.2.4"`

**Comment by Timer** [comment]
@antonmoiseev you have not provided any information for us to help diagnose this issue. We have integration tests ensuring firebase works, so we need to see your specific setup. Please open a new issue with a reproduction.

**Pull request closed without merging**
