### PR TITLE
Allow Duplicate Open Graph Image Tags

### PR DESCRIPTION
**Pull request by garmeeh**
This PR adds the Open Graph image tag to the allowed duplicates. It also adds it's supporting tags that normally appear with an image tag. 

Normally you can/would add multiple `og:image` tags to your page. An example use case for this is when sharing on Facebook the user will have a choice of the cover photo.

### CODE REVIEW

**Comment by garmeeh** [comment]
Hey @timneutkens, added some tests as suggested 😄

**Review by timneutkens — APPROVED** [review]

**Comment by joncursi** [comment]
@timneutkens @garmeeh has this been bundled into any of the recent versions of next? I'm still seeing the same issue on `7.0.2` and `7.0.3-alpha.5`.

**Comment by timneutkens** [comment]
The correct fix for this issue is #5800, and that is out on `next@canary` right now.

**Comment by joncursi** [comment]
@timneutkens got it. I updated to `@canary` but seem to be hitting a separate issue now:

```sh
> @cheddur/web@3.34.1 dev /Users/joncursi/Sites/cheddur/web
> dotenv node server.js

/Users/joncursi/Sites/cheddur/web/node_modules/next/dist/client/link.js:2
import { resolve, format, parse } from 'url';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Looks like there's a breaking change inside `canary`, but I'm not sure what. Could you help point me to the change I need to make to migrate from `7.0.2` --> `canary`, or would you be able to pluck these commits into a `7.0.2` canary release so I could have access to it?

Currently battling `og:image` duplication issues in production so that's why I'm pressing for it. Thank you!

**Comment by timneutkens** [comment]
It means you're doing something you shouldn't be doing in the first place, eg importing `next/link` in a custom server.

**Comment by timneutkens** [comment]
I'll fix it on the Next.js side, but this is really just wrong usage of next/link.

**Pull request merged**
