### PR TITLE
example: with-apollo-unstated

### PR DESCRIPTION
**Pull request by tylim88**
This simple example shows you how to:   
1. How to Apollo in Next.
2. How to SSR Apollo in Next.
3. How to use Unstated to share state across pages.

### CODE REVIEW

**Comment by timneutkens** [comment]
I think the scope of this example is too broad 🤔 Like it's a combination of the Apollo and Unstated example.

**Comment by timneutkens** [comment]
I guess it would be better to only update the unstated example then 🤔

**Comment by tylim88** [comment]
ok then, I will submit another pull request for existing Unstated example

**Comment by timneutkens** [comment]
Thanks!

**Pull request closed without merging**
