### PR TITLE
Added GTM server side container support to @third-parties/google/gtm

### PR DESCRIPTION
**Pull request by guybinya**
### What?
Added support for server side container to GTM third parties script

### Why?
Allows users to take advantage of the @third-parties library when using a gtm server side container for tracking.

### How?
Added a new prop to GTMParams called serverSideContainerUrl with a default url for the regular tag manager.

New usage will look like:
```typescript
<GoogleTagManager gtmId={gtmId} serverSideContainerUrl={GOOGLE_TAG_MANAGER_URL}/>
```

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 85e942c509874c892dfd15eecf9b737c24e5bda3

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by guybinya** [comment]
First PR for me, let me know if I need to add anything :)

**Comment by Axxoul** [comment]
great PR! Please merge ASAP

**Comment by amjedidiah** [comment]
@leerob 
Some questions:

- Has this been merged into Next.js in some other PR?
- If not, is this ignored because it's not following the guidelines for contributing?

**Comment by amjedidiah** [comment]
@ijjk  @timneutkens @Timer @huozhi

**Comment by guybinya** [comment]
> @leerob

Let me know if I need to make any changes, the "third party cookie" age is almost over.

**Comment by amjedidiah** [comment]
@guybinya 
Can you please follow the guidelines for contributing and make sure your PR passes the failing tests so it can be merged

**Comment by tuffstuff9** [comment]
@guybinya 

Thanks for this! Is there any way to make this work with using nextjs built in server side code, or do we need to deploy a new server elsewhere?

**Comment by guybinya** [comment]
> @guybinya
> 
> Thanks for this! Is there any way to make this work with using nextjs built in server side code, or do we need to deploy a new server elsewhere?

I assume you can make nextjs server side act as a reverse proxy for gtm, but I never tried it. I did use nextjs as a reverse proxy for other analytics tools (using vercel). 
Reverse proxy allows you to re-route all requests from your server endpoint to a remote server (GTM for example), so it’s basically solving the third party cookies problem. 
In my case I self-hosted the GTM server side container using GCP, the deployment is automatic and quick but you need to pay for the server’s resources.

**Pull request closed without merging**
