### PR TITLE
form handler example: Update deps and fix build from dep update

### PR DESCRIPTION
**Pull request by crutchcorn**
Updates packages for form handler example. The major update to `next-redux-wrapper` included a breaking change that required a tiny bit of work to fix up

### CODE REVIEW

**Review by kheruc — APPROVED** [review]

**Comment by timneutkens** [comment]
Looks like the tests are failing, can you run `yarn lint-fix`?

**Comment by crutchcorn** [comment]
I noticed there were more than a few issues with the linting when I tried to commit, so apologies for the big diff. (the first commit 
1d24bdf was what `yarn lint-fix` gave me, the second 7a09301 was what occured post `git commit -m`).

I also rebased on latest canary to make sure to reduce the number of potential conflicts

**Comment by crutchcorn** [comment]
Sorry, misread some of the diff and it spooked me into thinking that there was something I did terrible wrong. 

The examples directory seemed to have a lot more linting errors than just my code. Running `lint-fix` gave me 1d24bdf whereareas `git commit` gave me the next commit 7a09301.

I rebased with `canary` in order to make sure I was on the most-up-to-date examples for these.

Holding off on other PRs until this is merged in to avoid conflicts.

So so sorry about spamming anyone following along with notifications - absolute boneheaded move on my part

**Comment by timneutkens** [comment]
Could you fix the merge conflicts, then I'll merge!

**Comment by crutchcorn** [comment]
Should be fixed @timneutkens

**Review by Timer — APPROVED** [review]

**Pull request merged**
