### PR TITLE
Create separate Apollo example without Redux integration

### PR DESCRIPTION
**Pull request by adamsoffer**
I've heard from some members in the community that they'd like to see an Apollo example without the Redux integration since not everyone integrates their own Redux store with Apollo, so I've split the Apollo example in two: `with-apollo` and `with-apollo-and-redux`. 

The `with-apollo` example becomes less complex without the redux integration which will make it easier for people to understand what's going on inside `./lib`. If you want to integrate your own Redux store you can still look inside `with-apollo-and-redux` to see how it's done.

As part of this pull request I also fixed an issue with the pagination not working (I think this originally broke when we updated apollo-client to the release candidate).

### CODE REVIEW

**Comment by jaydenseric** [comment]
This is great!

You can delete the `redux` dependency in `with-apollo/package.json`.

**Review by sedubois — CHANGES_REQUESTED** [review]
How about sharing code between both examples instead of copy-pasting? Considering that the vast majority is just the same. Should be much more maintainable

**Comment by ads1018** [comment]
@sedubois good point although it's a small example so I'm not too worried about maintainability. I think all that might ever really change is what's inside `./lib`. Also, might be confusing for people who download one of the examples (following the README instructions) if the two are coupled since one then wouldn't work without the other.

**Comment by jaydenseric** [comment]
Most people will download the relevant example as a boilerplate, and will not want unrelated code or complexity in there. I like that the two examples are seperate.

**Comment by ads1018** [comment]
Cool. @timneutkens unless anyone has any other suggestions I think we're looking pretty good here!

**Comment by rauchg** [comment]
Brilliant stuff.

**Pull request merged**
