### PR TITLE
[docs] Clarify "When does getStaticProps run" note

### LINKED ISSUE #37288: Docs: getStaticPaths "When does getStaticPaths run" error
### What is the improvement or update you wish to see?

The [When does getStaticPaths run](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths#when-does-getstaticpaths-run) section in the docs lists bullet points for getStaticProps instead of getStaticPaths.

### Is there any context that might help us understand?

See https://nextjs.org/docs/basic-features/data-fetching/get-static-paths#when-does-getstaticpaths-run

"getStaticPaths will only run during build in production, it will not be called during runtime.
You can validate code written inside getStaticPaths is removed from the client-side bundle with this tool.

- **getStaticProps** runs during next build for any paths returned during build
- **getStaticProps** runs in the background when using fallback: true
- **getStaticProps** is called before initial render when using fallback: blocking"

### Does the docs page already exist? Please link to it.

 https://nextjs.org/docs/basic-features/data-fetching/get-static-paths#when-does-getstaticpaths-run

### PR DESCRIPTION
**Pull request by Clariity**
Changed bullet points to say "getStaticPaths" instead of "getStaticProps".

Fixes https://github.com/vercel/next.js/issues/37288 

## Feature

- [x] Related issues linked using `fixes #number`
- [x] Documentation added

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Hi, this is correct as is x-ref: https://github.com/vercel/next.js/pull/36722 is there something here that we could re-word to make this more clear?

**Comment by Clariity** [comment]
@ijjk I think it could be clearer if put in a sub section titled something like "How does getStaticProps run with regards to getStaticPaths" so we know we are definitely talking about getStaticProps.

**Comment by ijjk** [comment]
That sounds like a good update, wanna apply that on this branch?

**Comment by Clariity** [comment]
sure, I'll do that now

**Review by ijjk — APPROVED** [review]
Thanks!

**Pull request merged**
