### PR TITLE
Add Material-UI example

### PR DESCRIPTION
**Pull request by palafoxernesto**
This example features how you use Material-UI with Next.js.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Neat!

**Comment by davidascher** [comment]
@palafoxernesto have you explored how to put all of the muiTheme stuff in _document.js?  I'm running into some weird issues, curious if you'd explored it.

**Comment by davidascher** [comment]
Never mind, saw: https://github.com/zeit/next.js/issues/873 which has some details on the topic.

**Comment by themalis** [comment]
@palafoxernesto have you been able to effectively add the "className" property to any material-ui components with styled-jsx? In your example I wrapped <MuiThemeProvider> in a <div>, added <style jsx> and a className to the <RaisedButton>. The className appears on the element but the associated styled is absent.

**Pull request merged**
