### PR TITLE
Remove `licence` from all `example/package.json` that has them

### PR DESCRIPTION
**Pull request by oBusk**
As [mentioned](https://github.com/vercel/next.js/pull/27121#discussion_r668177450) in #27121, the `package.json` in the examples should not have `license field`. However in that PR it looks like this particular cleanup was lost in the merge.

This PR

* Updates the `scripts/check-examples.sh` script to remove the `license` field from any example that has it. (https://github.com/vercel/next.js/pull/28007/commits/3eb57a3c610ec786606b94294a41eb59c2716d91)
* Removes the license field from all examples that currently has it (https://github.com/vercel/next.js/pull/28007/commits/aa83a340636a2e7229259953fb69dd033aeda2ae)

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Per https://github.com/vercel/next.js/pull/27121 it looks like we want to remove the license field instead of adding it, can we update this to remove it from the examples that do have it?

**Comment by oBusk** [comment]
@ijjk Cool! I [updated](https://github.com/vercel/next.js/pull/28007/commits/3eb57a3c610ec786606b94294a41eb59c2716d91) the [`check-examples.sh`](https://github.com/vercel/next.js/blob/3eb57a3c610ec786606b94294a41eb59c2716d91/scripts/check-examples.sh) to remove the license field. A check like this was [mentioned](https://github.com/vercel/next.js/pull/27121#pullrequestreview-704443433) as a nice to have, but I don't think there is any that I risk conflicting with right now?

Then I also removed all license from the files that had it (https://github.com/vercel/next.js/pull/28007/commits/aa83a340636a2e7229259953fb69dd033aeda2ae).
Looks like there was a [commit](https://github.com/vercel/next.js/commit/3dcb42878b6cf4d5d9a55d3a0936f34d498e4365) in #27121 to remove license, but looks like it was lost in the merge?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | ⚠️ +18ms |
| buildDurationCached | 3.7s | 3.7s | -49ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | -2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.135 | 3.02 | -0.11 |
| / avg req/sec | 797.34 | 827.78 | +30.44 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.9 | 1.879 | -0.02 |
| /error-in-render avg req/sec | 1315.9 | 1330.45 | +14.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.1 kB | 23.1 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 67 kB | 67 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _app-HASH.js gzip | 980 B | 980 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.64 kB | 2.64 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 904 B | 904 B | ✓ |
| image-HASH.js gzip | 4.13 kB | 4.13 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.4s | ⚠️ +306ms |
| buildDurationCached | 5.1s | 4.9s | -265ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | -2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.134 | 3.058 | -0.08 |
| / avg req/sec | 797.63 | 817.55 | +19.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.951 | 1.821 | -0.13 |
| /error-in-render avg req/sec | 1281.58 | 1373.2 | +91.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14 kB | 14 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.6 kB | 10.6 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.9 kB | 67.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _app-HASH.js gzip | 965 B | 965 B | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.83 kB | 2.83 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 2.95 kB | 2.95 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.8 kB | 17.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _buildManifest.js gzip | 497 B | 497 B | ✓ |
| Overall change | 497 B | 497 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 598 B | 598 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: aa83a340636a2e7229259953fb69dd033aeda2ae

**Comment by ijjk** [comment]
> A check like this was mentioned as a nice to have, but I don't think there is any that I risk conflicting with right now?

There is not currently a check for this yet so this looks good 👍

**Review by ijjk — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
## Failing test suites 
Commit: dc609399d114d15c7720b0c8dadc9648262ae823

**test/integration/build-indicator/test/index.test.js** 
- Build Activity Indicator > Enabled > Shows build indicator when page is built from modifying

<details>
<summary>Expand output</summary>

  ● Build Activity Indicator › Enabled › Shows build indicator when page is built from modifying

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: null

      62 |       const wasVisible = await browser.eval('window.showedBuilder')
      63 |
    > 64 |       expect(wasVisible).toBe(true)
         |                          ^
      65 |       await fs.writeFile(pagePath, origContent, 'utf8')
      66 |       await browser.close()
      67 |     })

      at Object.<anonymous> (integration/build-indicator/test/index.test.js:64:26)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| buildDuration | 14.4s | 15.2s | ⚠️ +816ms |
| buildDurationCached | 3.6s | 3.6s | -59ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.799 | 2.865 | ⚠️ +0.07 |
| / avg req/sec | 893.07 | 872.49 | ⚠️ -20.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.603 | 1.818 | ⚠️ +0.22 |
| /error-in-render avg req/sec | 1559.39 | 1374.95 | ⚠️ -184.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.1 kB | 23.1 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 67 kB | 67 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _app-HASH.js gzip | 980 B | 980 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.64 kB | 2.64 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 904 B | 904 B | ✓ |
| image-HASH.js gzip | 4.13 kB | 4.13 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| buildDuration | 12.2s | 11.8s | -444ms |
| buildDurationCached | 5.2s | 4.9s | -308ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.903 | 2.825 | -0.08 |
| / avg req/sec | 861.15 | 884.82 | +23.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.885 | 1.71 | -0.18 |
| /error-in-render avg req/sec | 1326.15 | 1461.61 | +135.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14 kB | 14 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.6 kB | 10.6 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.9 kB | 67.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _app-HASH.js gzip | 965 B | 965 B | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.83 kB | 2.83 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 2.95 kB | 2.95 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.8 kB | 17.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| _buildManifest.js gzip | 497 B | 497 B | ✓ |
| Overall change | 497 B | 497 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | oBusk/next.js add-licenses-to-examples | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 598 B | 598 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: dc609399d114d15c7720b0c8dadc9648262ae823

**Pull request merged**
