### PR TITLE
Fix/upgrade examples with zustand 30 sep 23

### PR DESCRIPTION
**Pull request by mayank1513**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 50e3c67c02fa771b046458a77d32cf1917655a64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 50e3c67c02fa771b046458a77d32cf1917655a64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 50e3c67c02fa771b046458a77d32cf1917655a64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 50e3c67c02fa771b046458a77d32cf1917655a64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Replaced by https://github.com/vercel/next.js/pull/58042

**Pull request closed without merging**
