### PR TITLE
Tweak ReasonML example

### PR DESCRIPTION
**Pull request by sync**
Fixed:
- [x] we can now return a promise from `getInitialProps`. (trick was to ask bucklescript to output es6 and not commonjs)
- [x] fix `inject` typing (we no longer get a warning from it)
- [x] reason language server was having issues with latest bucklescript (so lock it down to 5.0.3)

And a couple of minor cleanups like code reformatting from a more recent refmt.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by Enalmada** [comment]
@sync In the Next.re binding, href is hard coded to a string:  `~href: string=?`

Is it possible to allow the binding to also support  URL object?
`<Link href={{ pathname: '/about', query: { name: 'Zeit' } }}>`
https://github.com/zeit/next.js/blob/canary/examples/with-url-object-routing/pages/index.js#L4-L7

**Comment by sync** [comment]
The binding is in no way complete and is just an example. Feel free to create your own binding and build on top of it.

**Comment by sync** [comment]
Also worth having a look at this: https://redex.github.io/package/bs-next/

**Comment by Enalmada** [comment]
I can't thank you enough @sync for the work you have done on this example to get it working again!  

The author of the original bs-next bindings linked above is no longer supporting it so I copied that code into this example and updated it here to support the current version of next link api both for string and URL Object with the hope that it would be easier to keep that binding up to date here.  

I believe the jsx2 version of the binding in this example worked with URL object as a parameter because the original binding was generic:  `~href=?`.  The pull request converting this example to jsx3 broke that api support by hardcoding href to only a string `~href: string=?`.  If I try and remove ": string" I get a syntax error...I suspected it wouldn't be that easy. Unfortunately I am too new to jsx3 to know how to best update the new jsx3 binding to fix it.   Would you know if jsx3 can support multiple parameter types like the jsx2 version did?

**Comment by sync** [comment]
@benatkin are you on the Reason Discord channel, we can take it from there. I am happy to help.

**Pull request merged**
