### PR TITLE
docs: fix several typos

### PR DESCRIPTION
**Pull request by suravshrestha**
`Enviroment -> Environment`

### CODE REVIEW

**Comment by timneutkens** [comment]
@suravshrestha can you just put these in a single PR?

**Comment by suravshrestha** [comment]
> @suravshrestha can you just put these in a single PR?

Please merge the PRs this time. In the future, I will combine commits of this type into a single PR. Thank you!

**Comment by balazsorban44** [comment]
Since these are just general typo fixes, you don't need to group them into anything specific.

**Review by balazsorban44 — DISMISSED** [review]
Let's address https://github.com/vercel/next.js/pull/56788#issuecomment-1761387221 then we can merge this. Thanks! :green_heart:

**Comment by suravshrestha** [comment]
> Let's address [#56788 (comment)](https://github.com/vercel/next.js/pull/56788#issuecomment-1761387221) then we can merge this. Thanks! 💚

@balazsorban44, I've included the changes from those PRs in this one. Could you please review and merge? Thank you!

**Review by styfle — APPROVED** [review]

**Pull request merged**
