### PR TITLE
with-mongodb update to add both App and Pages Router examples

### PR DESCRIPTION
**Pull request by codeSTACKr**
Updated all dependencies and added an app route to demonstrate both pages an app directories.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 733224585ebff2662c6cb835378e218ed82a4d30

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]

**Comment by samcx** [comment]
@codeSTACKr ok I see what's up, the `check-examples` lint check is affecting `examples/with-mongodb/next-env.d.ts` (removes a reference type)

**Comment by samcx** [comment]
@codeSTACKr I'll fix the `check-examples` script in a separate PR! For now, we'll just commit without one of the reference types, which automatically fixes itself anyways when you run the example with `next dev`.

**Comment by codeSTACKr** [comment]
@samcx thank you!

**Pull request merged**
