### PR TITLE
Add key to fela SSR example

### PR DESCRIPTION
**Pull request by AugustinLF**
The style element missed a key, which produces a warning. Indexes are not the optimal keys, but here, I'm note sure there's much better.

### CODE REVIEW

**Comment by steida** [comment]
Hmm, it does not produce warnings for me. cc @rofrischmann

**Comment by rofrischmann** [comment]
Oh, but that‘s true. According to React you‘d need to use em here. btw: type + media should produce a unqiue key which is better than the index :p

**Comment by AugustinLF** [comment]
@steida interesting, because I did get server-side warnings on two different projects :/

@rofrischmann Thanks for the tip, I did make the update!

**Comment by steida** [comment]
@AugustinLF You can close it. I made bigger PR.

**Pull request closed without merging**
