### PR TITLE
Add with-global-stylesheet-simple

### PR DESCRIPTION
**Pull request by chibicode**
- This is an example of importing a CSS file located inside `node_modules` (ones you downloaded using `npm` or `yarn`).
- This would be useful for importing CSS libraries such as [`normalize.css`](https://necolas.github.io/normalize.css/).
- This is simpler than the [with-global-stylesheet](https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet) example.
- Credit: @stovmascript (https://github.com/zeit/next.js/issues/544#issuecomment-325512576)

### CODE REVIEW

**Review by sergiodxa — APPROVED** [review]

**Comment by timneutkens** [comment]
@chibicode can you run `npm run lint -- --fix` 🙌 then I'll merge

**Comment by chibicode** [comment]
@timneutkens done, sorry about that.

**Comment by timneutkens** [comment]
Awesome, thank you very much @chibicode ❤️ No worries about the linting, it's fixed easily 😉

**Comment by chibicode** [comment]
@timneutkens Thanks! I just found one concerning thing which has to do with `styled-jsx`, so I wrote a comment over there: https://github.com/zeit/styled-jsx/issues/322#issuecomment-338755975 - I'll open another PR if I hear back.

**Comment by laurajuliette** [comment]
Hmmm I tried doing this and it works well if I paste the css in simple style tag 
```
import semanticcss from "semantic-ui-css/semantic.min.css";
<style>{semanticcss}</style>
```

This however, breaks it:
```
import semanticcss from "semantic-ui-css/semantic.min.css";
<style jsx global>{semanticcss}</style>
```

the error I get is:

```
500
Internal Server Error.
Error in ../components/MyLayout.js
Module build failed: TypeError: /Users/laurapretot/LocalDev/codechallenge-edenspiekermann/components/MyLayout.js: Invalid attempt to destructure non-iterable instance
    at /Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at PluginPass.exit (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/styled-jsx/dist/babel.js:250:66)
    at newFn (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/laurapretot/LocalDev/codechallenge-edenspiekermann/node_modules/babel-traverse/lib/index.js:114:17)
```

Am I doing smth wrong?

**Comment by laurajuliette** [comment]
The issue here is that in this case:
```
<style>{semanticcss}</style>
    <style jsx global>{`
      body {
        margin: 0;
        padding: 0;
        padding-bottom: 100px;
        background-color: #faf0e8;
        color: #191b45;
      }
    `}</style>
```

the style tag overwrites the following jsx global style tag.

**Comment by mkozhukharenko** [comment]
this example does not work for me in Production mode. jsx-undefind error

**Pull request merged**
