### PR TITLE
Adds example with Redux Persist

### PR DESCRIPTION
**Pull request by ashwamegh**
The pull request has been made to add the example of Next.js app where you can use `Redux` provider with `redux-persist` #6852  to persist the global state.

### CODE REVIEW

**Comment by ashwamegh** [comment]
@lfades Can you please review this?

**Comment by jrusso1020** [comment]
I was actually about to setup a next.js app with redux-persist and came across this, so I would love to see this get merged in so I can use it! 🚀 @ashwamegh

**Review by lfades — CHANGES_REQUESTED** [review]
Hi @ashwamegh thank you for the PR, I cloned the example and noticed the following:

- if the idea of the example is to save my store in localStorage so it's available after a reload, then that wasn't happening.
- I was also getting this error: `Expected server HTML to contain a matching <div> in <div>`

Why is the persisted store not created alongside the store ? like in the [basic example](https://github.com/rt2zz/redux-persist/blob/master/README.md#basic-usage) of redux persist, I also noticed that `<PersistGate />` is used inside `_document.js` and not in `_app.js`, why is that ?.

Please update the PR and then I'll merge 🙏

**Comment by ashwamegh** [comment]
> Hi @ashwamegh thank you for the PR, I cloned the example and noticed the following:
> 
>     * if the idea of the example is to save my store in localStorage so it's available after a reload, then that wasn't happening.
> 
>     * I was also getting this error: `Expected server HTML to contain a matching <div> in <div>`
> 
> 
> Why is the persisted store not created alongside the store? like in the [basic example](https://github.com/rt2zz/redux-persist/blob/master/README.md#basic-usage) of redux persist, I also noticed that `<PersistGate />` is used inside `_document.js` and not in `_app.js`, why is that ?.
> 
> Please update the PR and then I'll merge 🙏

Thanks, @lfades for reviewing my PR. And thanks for suggesting the changes too, it quite simplify the way of understanding this example.
- I have not included the global redux state to be persisted in local storage while you'll see `exampleData` state getting persisted in the storage.
- The error has been resolved with the changes pushed

**Comment by lfades** [comment]
Hi @ashwamegh thank you for the update, I did a review of the example again and now I have mixed feelings about this example:

- The page is empty until persist is ready, if you go to network and use a slow connection, the page will look empty for a while and then have content, I was expecting to see the page and then having the data loaded right after from localStorage.
- After reading [this example](https://github.com/kirill-konshin/next-redux-wrapper#usage-with-redux-persist) I don't know if this is the right way of implementing it, I would prefer that redux persist does its job after the initial render, which means having it completely disabled in SSR.

Let me know what you think 🙌

**Comment by jrusso1020** [comment]
> Hi @ashwamegh thank you for the update, I did a review of the example again and now I have mixed feelings about this example:
> 
> * The page is empty until persist is ready, if you go to network and use a slow connection, the page will look empty for a while and then have content, I was expecting to see the page and then having the data loaded right after from localStorage.
> * After reading [this example](https://github.com/kirill-konshin/next-redux-wrapper#usage-with-redux-persist) I don't know if this is the right way of implementing it, I would prefer that redux persist does its job after the initial render, which means having it completely disabled in SSR.
> 
> Let me know what you think 🙌

I agree with this as well, I'd like to be able to interact with the site while the persisted dataStore is loading in SSR(Possibly with some default values that will be updated when the store is updated). Would it be possible https://github.com/zeit/next.js/pull/6932/files#diff-81c517774dcbd1359a968b4bcc05547bR19 on this line for us to pass in the regular app component `<Component />` to the `loading` prop of the `<PersistGate />` component and see something on the web page while we are loading in the persisted store? @ashwamegh

**Comment by timneutkens** [comment]
Thanks so much for your contribution 🙏

**Pull request closed without merging**
