### PR TITLE
Make styles compatible in AMP mode

### LINKED ISSUE #7057: Next.js 8.1 AMP + Styled Components example does not work
## Overview
Using the [with-styled-components](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) example running Next `v8.1.0`, it does not work using `withAmp`. Here is the error:

```
TypeError: styles.map is not a function
    at Head.render (/Users/lrobinson/Developer/personal/with-styled-components-app/.next/server/static/development/pages/_document.js:1174:26)
    at processChild (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
    at resolve (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at Object.renderToStaticMarkup (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at renderDocument (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/next-server/dist/server/render.js:95:18)
    at Object.renderToHTML (/Users/lrobinson/Developer/personal/with-styled-components-app/node_modules/next-server/dist/server/render.js:238:16)
    at <anonymous>
```

Which is from overriding `_document.js` to make styled-components work: 
```js
import Document from 'next/document'
import { ServerStyleSheet } from 'styled-components'

export default class MyDocument extends Document {
  static async getInitialProps (ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        })

      const initialProps = await Document.getInitialProps(ctx)
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        )
      }
    } finally {
      sheet.seal()
    }
  }
}

```
## To Reproduce

```
npx create-next-app --example with-styled-components with-styled-components-app
```

**Modify index.js**
```js
import React from 'react'
import styled from 'styled-components'
import {withAmp} from 'next/amp';

const StyledTitle = styled.h1`
  color: red;
  font-size: 50px;
`;

const Title = () => <StyledTitle>My page</StyledTitle>;

export default withAmp(Title);
```

Then, run `yarn dev` and you will see the error. 

## System Information
 - OS: macOS
 - Version of Next.js: `v8.1.0`

### PR DESCRIPTION
**Pull request by ijjk**
Make previous styles set up in `_document` compatible in AMP mode 

Closes: #7057

### CODE REVIEW

**Review by timneutkens — COMMENTED** [review]
This actually doesn't make styles coming from styled-components work in amp right, because amp-custom will be missing.

**Comment by ijjk** [comment]
Right, it's updated to be inserted into the `style[amp-custom]` we create now.

**Review by timneutkens — CHANGES_REQUESTED** [review]
Could you add a test for it.

**Comment by ijjk** [comment]
Yup, added

**Review by timneutkens — APPROVED** [review]
Should we add a test for direct styled-components too?

**Pull request merged**
