### PR TITLE
update .babelrc to fix with-jest example

### PR DESCRIPTION
**Pull request by mckernanin**

### CODE REVIEW

**Comment by mckernanin** [comment]
Fixes #5563

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/canary/packages/next/build/babel/preset.js#L36

I'm guessing `jest` doesn't force `NODE_ENV=test`, as the babelrc is correct, you just have to set `NODE_ENV`:

https://github.com/zeit/next.js/blob/011f6cef70d5fa5f8cfaf5ccf7cad422e2a20019/examples/with-jest/package.json#L20

**Comment by lucleray** [comment]
@timneutkens 

jest does automatically set `NODE_ENV=test`, see here : https://jestjs.io/docs/en/getting-started#using-babel

> Note: If you are using a more complicated Babel configuration, using Babel's env option, keep in mind that Jest will automatically define NODE_ENV as test. It will not use development section like Babel does by default when no NODE_ENV is set.

**Comment by lucleray** [comment]
I just tested `with-jest` and it's working fine :
- works with npm (6.2)
- works with yarn (1.9.2)

@mckernanin 
Make sure you installed `@babel/core`, I don't see it here : https://github.com/mckernanin/Syntax/blob/master/package.json

It's necessary when you use `babel-jest`, see here : https://github.com/facebook/jest/tree/master/packages/babel-jest

**Comment by timneutkens** [comment]
Then I'm really not sure what's going on here, are you sure you're using Next 7+?

**Comment by timneutkens** [comment]
As per https://github.com/zeit/next.js/issues/5563#issuecomment-435277653, the babelrc should be correct here.

**Pull request closed without merging**
