### PR TITLE
Updated TS example to highlight how to output  and run JS from seperate directory

### PR DESCRIPTION
**Pull request by timReynolds**
**Problem**
The simplicity of the existing TypeScript example is enough to get people of the ground.

In practise however most users will want to exclude the JS outputted by the complier from version control. Doing so while outputting .js files next to their .ts makes is possible and included however would also exclude any config or other .js files that might reside in the repository. 

This has been raised as a question at least [once](https://github.com/zeit/next.js/issues/2202).

**Solution**
Update the example so that TypeScripts outputs JS into a bin directory which is then used by next.js by providing the bin directory as a command line argument. 

**Considerations before merging**
Additional complexity in example

### CODE REVIEW

**Comment by KraigWalker** [comment]
This is a great improvement to the TS development experience, but the one thing it's missing before it's perfect* is support for the `/static` folder. I have small project based off of the TS example, and when trying out your fix, I discovered the `/static` folder doesn't get carried over into bin like everything else.

**Comment by dillonraphael** [comment]
@KraigWalker Same issue. Have you found a solution?

**Comment by timReynolds** [comment]
I was looking into this today. You can’t configure the static folder in next from what I can see nor is getting  tsc an option. 

I’d started looking at configuring somethig in package.json to move the contents of static into the bin.

**Comment by dillonraphael** [comment]
@timneutkens hmm other people having the same issue

**Comment by timneutkens** [comment]
This PR seems out of date, could you make a new one against the `canary` branch, thanks!

**Pull request closed without merging**
