### PR TITLE
(chore) Add with-goober as an example

### PR DESCRIPTION
**Pull request by cristianbote**
This PR creates an example for [🥜 goober](https://github.com/cristianbote/goober). Let me know if there's something else I need to create. Locally I can run it and everything is as it should be.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.2s | ⚠️ +118ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.675 | 1.65 | -0.03 |
| / avg req/sec | 1492.76 | 1515.12 | +22.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1 | 1.025 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2498.85 | 2438.83 | ⚠️ -60.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..e4a8.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 961 B | 961 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.1s | -196ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..e4a8.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 916 kB | 916 kB | ✓ |
| routerDirect.js | 910 kB | 910 kB | ✓ |
| withRouter.js | 910 kB | 910 kB | ✓ |
| Overall change | 4.5 MB | 4.5 MB | ✓ |

</details>

</details>
Commit: 97f82f8bad84d3b60aba308ea72dcf3a05ddacc0

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 97f82f8bad84d3b60aba308ea72dcf3a05ddacc0

**test/integration/dynamic-routing/test/index.test.js** 
- Dynamic Routing > dev mode > should scroll to a hash on client-side navigation

<details>
<summary>Expand output</summary>

  ● Dynamic Routing › dev mode › should scroll to a hash on client-side navigation

    expect(received).toMatch(expected)

    Expected pattern: /onmpost:.*test-w-hash/
    Received string:  "[]"

      426 | 
      427 |     const text = await browser.elementByCss('p').text()
    > 428 |     expect(text).toMatch(/onmpost:.*test-w-hash/)
          |                  ^
      429 | 
      430 |     const scrollPosition = await browser.eval('window.pageYOffset')
      431 |     expect(scrollPosition).toBe(7232)

      at Object.<anonymous> (integration/dynamic-routing/test/index.test.js:428:18)
          at runMicrotasks (<anonymous>)

</details>

**Review by lfades — APPROVED** [review]
@cristianbote Thank you!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.4s | -287ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.177 | 2.046 | -0.13 |
| / avg req/sec | 1148.26 | 1221.91 | +73.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.392 | 1.409 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1796.3 | 1773.77 | ⚠️ -22.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..e4a8.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 961 B | 961 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -263ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..e4a8.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | cristianbote/next.js chore/add-example-with-goober | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 916 kB | 916 kB | ✓ |
| routerDirect.js | 910 kB | 910 kB | ✓ |
| withRouter.js | 910 kB | 910 kB | ✓ |
| Overall change | 4.5 MB | 4.5 MB | ✓ |

</details>

</details>
Commit: b9cc5a04669291c1463c9a2af4a674a55ca7aae2

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b9cc5a04669291c1463c9a2af4a674a55ca7aae2

**test/integration/dynamic-routing/test/index.test.js** 
- Dynamic Routing > dev mode > should navigate to a nested dynamic page successfully

<details>
<summary>Expand output</summary>

  ● Dynamic Routing › dev mode › should navigate to a nested dynamic page successfully

    expect(received).toMatch(expected)

    Expected pattern: /i am.*comment-1.*on.*post-1/i
    Received string:  "[]"

      139 | 
      140 |       const text = await browser.elementByCss('p').text()
    > 141 |       expect(text).toMatch(/i am.*comment-1.*on.*post-1/i)
          |                    ^
      142 |     } finally {
      143 |       if (browser) await browser.close()
      144 |     }

      at Object.<anonymous> (integration/dynamic-routing/test/index.test.js:141:20)

</details>

**Comment by lfades** [comment]
Tests are failing for unrelated reasons, going to merge manually.

**Comment by andreipfeiffer** [comment]
@lfades I have a question and can't seem to find an answer.

When you build this example, you **don't get a separate `chunk` for the library**, instead it's bundled inside each page.
The **same applies for** the examples for [Fela](https://github.com/vercel/next.js/tree/canary/examples/with-fela) and [JSS](https://github.com/vercel/next.js/tree/canary/examples/with-react-jss).

However, for other **CSS-in-JS** solutions like [Styled Components](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components), [Emotion](https://github.com/vercel/next.js/tree/canary/examples/with-emotion), [Stitches](https://github.com/vercel/next.js/tree/canary/examples/with-stitches) or [TypeStyle](https://github.com/vercel/next.js/tree/canary/examples/with-typestyle) you **get a separate `chunk` of the lib**, that is shared across all pages.

So, the questions are:
- why is this difference? is there a reason for getting handled differently?
- is there a way to control what gets to common chunks, and what not? (I've searched all the docs, without any luck)

I would really appreciate if you could shed some light.

I'm working on a [thorough analysis of all CSS-in-JS](https://github.com/andreipfeiffer/css-in-js) solutions with Next.js, and can't get my head around this tiny bit.

**Comment by timuster** [comment]
@cristianbote Any thoughts on Andrei's last comment about the library being bundled inside each page?

**Pull request merged**
