### PR TITLE
docs(internalization): add typescript examples and fix params as promise

### PR DESCRIPTION
**Pull request by devpla**
Hi Team.
This PR enhances the internalization documentation by adding TypeScript examples and updating the handling of params as a Promise.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 3cd56692a1dad26a6f244e5c3742c44493615faf

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Could you address the merge conflicts please?

**Comment by devpla** [comment]
@leerob Thank you! I’ve resolved the merge conflicts, and the branch is now up to date.

**Review by leerob — APPROVED** [review]
Thank you!

**Pull request merged**
