### PR TITLE
docs: updates generateMetadata function signature

### PR DESCRIPTION
**Pull request by emiliosheinz**
Change optional arg to non-optional arg of `parent` in the `generateMetadata` API function example in oder to avoid the error shown below.
 
Screenshot 2023-08-27 at 15 23 02

### CODE REVIEW

**Review by huozhi — COMMENTED** [review]
parent is always passed as a promise, the right signature should be

```tsx
export async function generateMetadata(
  { params, searchParams }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
```
You can remove the `?` for the 2nd arg `parent`, and  revert the change in the function body

**Comment by emiliosheinz** [comment]
> parent is always passed as a promise, the right signature should be
> 
> ```tsx
> export async function generateMetadata(
>   { params, searchParams }: Props,
>   parent: ResolvingMetadata
> ): Promise<Metadata> {
> ```
> 
> You can remove the `?` for the 2nd arg `parent`, and revert the change in the function body

Thank you for the heads up. I just updated the code!

**Review by huozhi — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 30e75b55f788ecfcaf3d1d499c37fb4bdeeb4fc2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 30e75b55f788ecfcaf3d1d499c37fb4bdeeb4fc2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
