### PR TITLE
remove curly brackets

### PR DESCRIPTION
**Pull request by bjarneo**

### CODE REVIEW

**Comment by nkzawa** [comment]
Any reasons why we should remove them ?

**Comment by arunoda** [comment]
I don't have anything against this PR. But I like this code block with curly brackets.

**Comment by bjarneo** [comment]
@nkzawa only reason is that they're superfluous. Personal preference I guess.

**Review by hernang87 — COMMENTED** [review]
I think curly braces should be there for extensibility and to prevent conflicts down the line.

**Comment by bjarneo** [comment]
@hernang87 If it's going to be extended in the future, it's no problem for anyone to add the curly brackets. Not sure what conflicts by having the brackets will prevent.

**Comment by jonaswindey** [comment]
While we're at it, we might as well use template literals instead of `%d`

```
console.log('> Ready on http://localhost:%d', argv.port)
```
to
```
console.log(`> Ready on http://localhost:${arg.port})`
```

**Comment by rauchg** [comment]
Thanks @jonaswindey

**Comment by nkzawa** [comment]
Fixed to use template literals https://github.com/zeit/next.js/commit/6ca52f3ee22173606131cbdbab50252b3868680b

Closed since it'd be about personal preference.

**Pull request closed without merging**
