### PR TITLE
Re-add prefetch prop type with deprecated

### PR DESCRIPTION
**Pull request by ijjk**
Can help explain type errors for people who upgraded

### CODE REVIEW

**Review by Timer — APPROVED** [review]
Let's mentally note to remove this in the next major version.

**Comment by ijjk** [comment]
ended up deciding against this

**Review by Timer — APPROVED** [review]

**Comment by kachkaev** [comment]
It'd be useful to see a link to an alternative in `@deprecated` block 🙂

**Comment by Timer** [comment]
@kachkaev there is no alternative -- Next.js now prefetches everything in view by default. 😄

**Comment by exogen** [comment]
"Deprecated" implies to me that it still actually works, not just that the propType is defined. I would expect `prefetch` to still function while deprecated, then removed in a later release.

**Pull request merged**
