### PR TITLE
Response polyfill: ensure rewrite URL provided is absolute

### LINKED ISSUE #31208: Edge function / middleware error: "TypeError: Unable to parse URL" when deployed to Vercel
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

v16.10.0 (local) 

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When testing locally, the following `_middleware.ts` works perfectly:

```
export async function middleware(req: NextRequest) {
  const { pathname: redirectUrl } = req.nextUrl;
  const {  userTypeId } = req.cookies;

  if (!userTypeId || Number(userTypeId) !== UserTypeEnum.FIRST_TIME) {
    return Response.redirect("/play");
  }
  return NextResponse.next();
}
```
However, when deployed to Vercel I get the following error in my function logs:
```
TypeError: Unable to parse URL: /play
at Object.d [as handler]
at t.V
at Object.a
```

### Expected Behavior

I would expect the page to redirect or continue without the error occuring.

### To Reproduce

Create `_middleware` like above and deploy to vercel and try hit a route that the middleware is linked to

### PR DESCRIPTION
**Pull request by Kikobeats**
This PR ensures `Response.rewrite` is used with an absolute URL, that is the expected way.

Closes https://github.com/vercel/next.js/issues/31208

Related:

- https://github.com/node-fetch/node-fetch/blob/main/src/response.js#L115

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e63da9ebebc13945d73d23d4bffd697076a57e72

**test/integration/middleware/core/test/index.test.js** 
- Middleware base tests > dev mode >  should redirect (infinite-loop)
- Middleware base tests > dev mode > /fr should redirect (infinite-loop)
- Middleware base tests > production mode >  should redirect (infinite-loop)
- Middleware base tests > production mode > /fr should redirect (infinite-loop)

<details>
<summary>Expand output</summary>

  ● Middleware base tests › dev mode ›  should redirect (infinite-loop)

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: {"size": 0, "timeout": 0, Symbol(Body internals): {"body": {"_chunkSize": 16384, "_defaultFlushFlag": 2, "_defaultFullFlushFlag": 3, "_events": {"close": [Function bound onceWrapper], "error": [[Function onerror], [Function anonymous]], "finish": [Function bound onceWrapper], "prefinish": [Function prefinish], "unpipe": [Function onunpipe]}, "_eventsCount": 5, "_finishFlushFlag": 2, "_handle": {"availInBefore": 10, "availOutBefore": 16384, "buffer": [Object], "cb": [Function bound afterTransform], "flushFlag": 2, "inOff": 0, "onerror": [Function zlibOnError], Symbol(owner_symbol): [Circular]}, "_info": undefined, "_level": -1, "_maxListeners": undefined, "_maxOutputLength": 4294967295, "_outBuffer": {"data": [Array], "type": "Buffer"}, "_outOffset": 0, "_readableState": {"autoDestroy": true, "awaitDrainWriters": null, "buffer": {"head": null, "length": 0, "tail": null}, "closeEmitted": false, "closed": false, "dataEmitted": false, "decoder": null, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "emittedReadable": false, "encoding": null, "endEmitted": false, "ended": false, "errorEmitted": false, "errored": null, "flowing": null, "highWaterMark": 16384, "length": 0, "multiAwaitDrain": false, "needReadable": false, "objectMode": false, "pipes": [], "readableListening": false, "reading": false, "readingMore": false, "resumeScheduled": false, "sync": false, Symbol(kPaused): null}, "_strategy": 0, "_writableState": {"afterWriteTickInfo": null, "allBuffers": true, "allNoop": true, "autoDestroy": true, "bufferProcessing": false, "buffered": [], "bufferedIndex": 0, "closed": false, "corked": 0, "decodeStrings": true, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "ended": false, "ending": false, "errorEmitted": false, "errored": null, "finalCalled": false, "finished": false, "highWaterMark": 16384, "length": 10, "needDrain": false, "objectMode": false, "onwrite": [Function bound onwrite], "pendingcb": 1, "prefinished": false, "sync": false, "writecb": [Function nop], "writelen": 10, "writing": true}, "_writeState": [0, 0], "allowHalfOpen": true, "bytesWritten": 0, Symbol(kCapture): false, Symbol(kTransformState): {"afterTransform": [Function bound afterTransform], "needTransform": false, "transforming": true, "writecb": [Function bound onwrite], "writechunk": [Object], "writeencoding": "buffer"}, Symbol(kError): null}, "disturbed": false, "error": null}, Symbol(Response internals): {"counter": 1, "headers": {Symbol(map): {"cache-control": ["no-store, must-revalidate"], "connection": ["close"], "content-encoding": ["gzip"], "content-type": ["text/html; charset=utf-8"], "date": ["Tue, 21 Dec 2021 11:04:16 GMT"], "etag": ["\"a53-Vk2xOBKZ3I45tm56GnsQmBTGe1g\""], "transfer-encoding": ["chunked"], "vary": ["Accept-Encoding"], "x-powered-by": ["Next.js"]}}, "status": 200, "statusText": "OK", "url": "http://localhost:32821/redirects/infinite-loop-1"}}

      191 |   })
      192 |
    > 193 |   it(`${locale} should rewrite to Vercel`, async () => {
          |               ^
      194 |     const res = await fetchViaHTTP(
      195 |       context.appPort,
      196 |       `${locale}/rewrites/rewrite-me-to-vercel`

      at expect (../node_modules/expect/build/index.js:178:15)
      at Object.<anonymous> (integration/middleware/core/test/index.test.js:193:15)
          at runMicrotasks (<anonymous>)

  ● Middleware base tests › dev mode › /fr should redirect (infinite-loop)

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: {"size": 0, "timeout": 0, Symbol(Body internals): {"body": {"_chunkSize": 16384, "_defaultFlushFlag": 2, "_defaultFullFlushFlag": 3, "_events": {"close": [Function bound onceWrapper], "error": [[Function onerror], [Function anonymous]], "finish": [Function bound onceWrapper], "prefinish": [Function prefinish], "unpipe": [Function onunpipe]}, "_eventsCount": 5, "_finishFlushFlag": 2, "_handle": {"availInBefore": 10, "availOutBefore": 16384, "buffer": [Object], "cb": [Function bound afterTransform], "flushFlag": 2, "inOff": 0, "onerror": [Function zlibOnError], Symbol(owner_symbol): [Circular]}, "_info": undefined, "_level": -1, "_maxListeners": undefined, "_maxOutputLength": 4294967295, "_outBuffer": {"data": [Array], "type": "Buffer"}, "_outOffset": 0, "_readableState": {"autoDestroy": true, "awaitDrainWriters": null, "buffer": {"head": null, "length": 0, "tail": null}, "closeEmitted": false, "closed": false, "dataEmitted": false, "decoder": null, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "emittedReadable": false, "encoding": null, "endEmitted": false, "ended": false, "errorEmitted": false, "errored": null, "flowing": null, "highWaterMark": 16384, "length": 0, "multiAwaitDrain": false, "needReadable": false, "objectMode": false, "pipes": [], "readableListening": false, "reading": false, "readingMore": false, "resumeScheduled": false, "sync": false, Symbol(kPaused): null}, "_strategy": 0, "_writableState": {"afterWriteTickInfo": null, "allBuffers": true, "allNoop": true, "autoDestroy": true, "bufferProcessing": false, "buffered": [], "bufferedIndex": 0, "closed": false, "corked": 0, "decodeStrings": true, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "ended": false, "ending": false, "errorEmitted": false, "errored": null, "finalCalled": false, "finished": false, "highWaterMark": 16384, "length": 10, "needDrain": false, "objectMode": false, "onwrite": [Function bound onwrite], "pendingcb": 1, "prefinished": false, "sync": false, "writecb": [Function nop], "writelen": 10, "writing": true}, "_writeState": [0, 0], "allowHalfOpen": true, "bytesWritten": 0, Symbol(kCapture): false, Symbol(kTransformState): {"afterTransform": [Function bound afterTransform], "needTransform": false, "transforming": true, "writecb": [Function bound onwrite], "writechunk": [Object], "writeencoding": "buffer"}, Symbol(kError): null}, "disturbed": false, "error": null}, Symbol(Response internals): {"counter": 1, "headers": {Symbol(map): {"cache-control": ["no-store, must-revalidate"], "connection": ["close"], "content-encoding": ["gzip"], "content-type": ["text/html; charset=utf-8"], "date": ["Tue, 21 Dec 2021 11:04:18 GMT"], "etag": ["\"a53-B/Rpyn3P7yNlxaWeVsbrhoBRrgg\""], "transfer-encoding": ["chunked"], "vary": ["Accept-Encoding"], "x-powered-by": ["Next.js"]}}, "status": 200, "statusText": "OK", "url": "http://localhost:32821/fr/redirects/infinite-loop-1"}}

      191 |   })
      192 |
    > 193 |   it(`${locale} should rewrite to Vercel`, async () => {
          |               ^
      194 |     const res = await fetchViaHTTP(
      195 |       context.appPort,
      196 |       `${locale}/rewrites/rewrite-me-to-vercel`

      at expect (../node_modules/expect/build/index.js:178:15)
      at Object.<anonymous> (integration/middleware/core/test/index.test.js:193:15)
          at runMicrotasks (<anonymous>)

  ● Middleware base tests › production mode ›  should redirect (infinite-loop)

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: {"size": 0, "timeout": 0, Symbol(Body internals): {"body": {"_chunkSize": 16384, "_defaultFlushFlag": 2, "_defaultFullFlushFlag": 3, "_events": {"close": [Function bound onceWrapper], "error": [[Function onerror], [Function anonymous]], "finish": [Function bound onceWrapper], "prefinish": [Function prefinish], "unpipe": [Function onunpipe]}, "_eventsCount": 5, "_finishFlushFlag": 2, "_handle": {"availInBefore": 10, "availOutBefore": 16384, "buffer": [Object], "cb": [Function bound afterTransform], "flushFlag": 2, "inOff": 0, "onerror": [Function zlibOnError], Symbol(owner_symbol): [Circular]}, "_info": undefined, "_level": -1, "_maxListeners": undefined, "_maxOutputLength": 4294967295, "_outBuffer": {"data": [Array], "type": "Buffer"}, "_outOffset": 0, "_readableState": {"autoDestroy": true, "awaitDrainWriters": null, "buffer": {"head": null, "length": 0, "tail": null}, "closeEmitted": false, "closed": false, "dataEmitted": false, "decoder": null, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "emittedReadable": false, "encoding": null, "endEmitted": false, "ended": false, "errorEmitted": false, "errored": null, "flowing": null, "highWaterMark": 16384, "length": 0, "multiAwaitDrain": false, "needReadable": false, "objectMode": false, "pipes": [], "readableListening": false, "reading": false, "readingMore": false, "resumeScheduled": false, "sync": false, Symbol(kPaused): null}, "_strategy": 0, "_writableState": {"afterWriteTickInfo": null, "allBuffers": true, "allNoop": true, "autoDestroy": true, "bufferProcessing": false, "buffered": [], "bufferedIndex": 0, "closed": false, "corked": 0, "decodeStrings": true, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "ended": false, "ending": false, "errorEmitted": false, "errored": null, "finalCalled": false, "finished": false, "highWaterMark": 16384, "length": 10, "needDrain": false, "objectMode": false, "onwrite": [Function bound onwrite], "pendingcb": 1, "prefinished": false, "sync": false, "writecb": [Function nop], "writelen": 10, "writing": true}, "_writeState": [0, 0], "allowHalfOpen": true, "bytesWritten": 0, Symbol(kCapture): false, Symbol(kTransformState): {"afterTransform": [Function bound afterTransform], "needTransform": false, "transforming": true, "writecb": [Function bound onwrite], "writechunk": [Object], "writeencoding": "buffer"}, Symbol(kError): null}, "disturbed": false, "error": null}, Symbol(Response internals): {"counter": 1, "headers": {Symbol(map): {"cache-control": ["no-cache, no-store, max-age=0, must-revalidate"], "connection": ["close"], "content-encoding": ["gzip"], "content-type": ["text/html; charset=utf-8"], "date": ["Tue, 21 Dec 2021 11:04:35 GMT"], "etag": ["\"87f-Q1ZiufjaOjrzz72QcMYfgkL2PRM\""], "transfer-encoding": ["chunked"], "vary": ["Accept-Encoding"], "x-powered-by": ["Next.js"]}}, "status": 500, "statusText": "Internal Server Error", "url": "http://localhost:38011/redirects/infinite-loop-1"}}

      191 |   })
      192 |
    > 193 |   it(`${locale} should rewrite to Vercel`, async () => {
          |               ^
      194 |     const res = await fetchViaHTTP(
      195 |       context.appPort,
      196 |       `${locale}/rewrites/rewrite-me-to-vercel`

      at expect (../node_modules/expect/build/index.js:178:15)
      at Object.<anonymous> (integration/middleware/core/test/index.test.js:193:15)
          at runMicrotasks (<anonymous>)

  ● Middleware base tests › production mode › /fr should redirect (infinite-loop)

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: {"size": 0, "timeout": 0, Symbol(Body internals): {"body": {"_chunkSize": 16384, "_defaultFlushFlag": 2, "_defaultFullFlushFlag": 3, "_events": {"close": [Function bound onceWrapper], "error": [[Function onerror], [Function anonymous]], "finish": [Function bound onceWrapper], "prefinish": [Function prefinish], "unpipe": [Function onunpipe]}, "_eventsCount": 5, "_finishFlushFlag": 2, "_handle": {"availInBefore": 10, "availOutBefore": 16384, "buffer": [Object], "cb": [Function bound afterTransform], "flushFlag": 2, "inOff": 0, "onerror": [Function zlibOnError], Symbol(owner_symbol): [Circular]}, "_info": undefined, "_level": -1, "_maxListeners": undefined, "_maxOutputLength": 4294967295, "_outBuffer": {"data": [Array], "type": "Buffer"}, "_outOffset": 0, "_readableState": {"autoDestroy": true, "awaitDrainWriters": null, "buffer": {"head": null, "length": 0, "tail": null}, "closeEmitted": false, "closed": false, "dataEmitted": false, "decoder": null, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "emittedReadable": false, "encoding": null, "endEmitted": false, "ended": false, "errorEmitted": false, "errored": null, "flowing": null, "highWaterMark": 16384, "length": 0, "multiAwaitDrain": false, "needReadable": false, "objectMode": false, "pipes": [], "readableListening": false, "reading": false, "readingMore": false, "resumeScheduled": false, "sync": false, Symbol(kPaused): null}, "_strategy": 0, "_writableState": {"afterWriteTickInfo": null, "allBuffers": true, "allNoop": true, "autoDestroy": true, "bufferProcessing": false, "buffered": [[Object]], "bufferedIndex": 0, "closed": false, "corked": 0, "decodeStrings": true, "defaultEncoding": "utf8", "destroyed": false, "emitClose": true, "ended": true, "ending": true, "errorEmitted": false, "errored": null, "finalCalled": false, "finished": false, "highWaterMark": 16384, "length": 981, "needDrain": false, "objectMode": false, "onwrite": [Function bound onwrite], "pendingcb": 2, "prefinished": false, "sync": false, "writecb": [Function nop], "writelen": 10, "writing": true}, "_writeState": [0, 0], "allowHalfOpen": true, "bytesWritten": 0, Symbol(kCapture): false, Symbol(kTransformState): {"afterTransform": [Function bound afterTransform], "needTransform": false, "transforming": true, "writecb": [Function bound onwrite], "writechunk": [Object], "writeencoding": "buffer"}, Symbol(kError): null}, "disturbed": false, "error": null}, Symbol(Response internals): {"counter": 1, "headers": {Symbol(map): {"cache-control": ["no-cache, no-store, max-age=0, must-revalidate"], "connection": ["close"], "content-encoding": ["gzip"], "content-type": ["text/html; charset=utf-8"], "date": ["Tue, 21 Dec 2021 11:04:36 GMT"], "etag": ["\"87f-Q1ZiufjaOjrzz72QcMYfgkL2PRM\""], "transfer-encoding": ["chunked"], "vary": ["Accept-Encoding"], "x-powered-by": ["Next.js"]}}, "status": 500, "statusText": "Internal Server Error", "url": "http://localhost:38011/fr/redirects/infinite-loop-1"}}

      191 |   })
      192 |
    > 193 |   it(`${locale} should rewrite to Vercel`, async () => {
          |               ^
      194 |     const res = await fetchViaHTTP(
      195 |       context.appPort,
      196 |       `${locale}/rewrites/rewrite-me-to-vercel`

      at expect (../node_modules/expect/build/index.js:178:15)
      at Object.<anonymous> (integration/middleware/core/test/index.test.js:193:15)
          at runMicrotasks (<anonymous>)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| buildDuration | 17.6s | 17.5s | -164ms |
| buildDurationCached | 3.4s | 3.4s | -47ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.881 | 2.91 | ⚠️ +0.03 |
| / avg req/sec | 867.79 | 859.08 | ⚠️ -8.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.348 | 1.387 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1854.95 | 1802.93 | ⚠️ -52.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 30.3 kB | 30.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 74.1 kB | 74.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| buildDuration | 18.9s | 18.8s | -61ms |
| buildDurationCached | 3.4s | 3.4s | -7ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.976 | 2.934 | -0.04 |
| / avg req/sec | 840.08 | 851.98 | +11.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.391 | 1.372 | -0.02 |
| /error-in-render avg req/sec | 1796.84 | 1821.58 | +24.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 30.4 kB | 30.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 74.3 kB | 74.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.75 kB | 4.75 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: e63da9ebebc13945d73d23d4bffd697076a57e72

**Review by javivelasco — APPROVED** [review]

**Review by javivelasco — COMMENTED** [review]
Actually let's hold on to define the general desired behaviour

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| buildDuration | 21.1s | 21.1s | ⚠️ +1ms |
| buildDurationCached | 4.2s | 4.2s | -15ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +47 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.788 | 3.799 | ⚠️ +0.01 |
| / avg req/sec | 659.98 | 658.07 | ⚠️ -1.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.11 | 2.07 | -0.04 |
| /error-in-render avg req/sec | 1184.85 | 1207.49 | +22.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 30.3 kB | 30.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 74.1 kB | 74.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| buildDuration | 23.5s | 23.5s | ⚠️ +83ms |
| buildDurationCached | 4.2s | 4.2s | ⚠️ +56ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +47 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.78 | 3.779 | 0 |
| / avg req/sec | 661.33 | 661.62 | +0.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.178 | 2.089 | -0.09 |
| /error-in-render avg req/sec | 1147.84 | 1196.6 | +48.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 30.4 kB | 30.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 74.3 kB | 74.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.75 kB | 4.75 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Kikobeats/next.js rewrite | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 18717d0a772e432151d8dd94a7bebe208f222360

**Pull request closed without merging**
