### PR TITLE
fix: Prevent MongoDB client promise being cached

### PR DESCRIPTION
**Pull request by aldosch**
### What?
Update to [examples/with-mongodb](https://github.com/vercel/next.js/tree/canary/examples/with-mongodb) to incorporate fix from the MongoDB team. This should prevent intermittent serverless function timeouts due to cached promise. 

### Why?

Vercel users reported intermittent 500 errors when connecting to their MongoDB Atlas clusters in production environments.

Full bug report: [NODE-6179](https://jira.mongodb.org/browse/NODE-6179)

Related issues:
- [10671](https://github.com/vercel/vercel/issues/10671)
- [5708](https://github.com/orgs/vercel/discussions/5708)
- [4297](https://github.com/orgs/vercel/discussions/4297)

### How?

Solution by @baileympearson – thank you 🖤

[View commit](https://github.com/mongodb-developer/nextjs-with-mongodb/commit/c08bc96353f3d921766ece2ab2e9c4c647e398c7) in `mongodb-developer/nextjs-with-mongodb`

---

- [x] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)
- [x] Make sure the linting passes by running `pnpm build && pnpm lint`. [See linting docs](https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md).

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: b53775306d3e895aa57d254e3b680276385b5aea

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: b53775306d3e895aa57d254e3b680276385b5aea

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by aldosch** [comment]
This change also needs to be applied to [vercel/mongodb-starter](https://github.com/vercel/mongodb-starter). Although there may be an issue due to Auth.js (or NextAuth in this case) where `MongoDBAdapter` expects `client: Promise<MongoClient>` rather than `client: MongoClient`. 

More context in [this work in progress commit](https://github.com/aldosch/mongodb-starter/commit/08c04d47f7eeab3a8f83183c44a207f740ec05ea#diff-81bbae584d6e4013646bc9157027ef5f1be981ea6f3ea39869c7c4a4cbdb3997R7-R11).

**Comment by aldosch** [comment]
Also, if there is a [more appropriate comment to add here](https://github.com/vercel/next.js/pull/66977/commits/b53775306d3e895aa57d254e3b680276385b5aea#diff-03958d0b5cb13b5668b5e07ec2f8d9865a8508aded1d93b0546910e6f9db21bcL14-L21) please feel free to adjust. I removed it as I was unsure whether its still possible to use another database in a similar way.

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
