### PR TITLE
Simplify with-redux example

### PR DESCRIPTION
**Pull request by HaNdTriX**
## Changes

- [x] Remove `_app.js` usage
- [x] Migrate withRedux HOC to functional component
- [x] Add correct display name to wrapped component
- [x] Remove abstractions/boilerplate from example
- [x] Add `useInterval` HOC from Dan
- [x] Move Redux `Provider` to `withRedux` HOC
- [x] Update Readme
- [x] Add `withRedux(IndexPage, { ssr: false })` option to allow [automatic static optimization](https://nextjs.org/blog/next-9#automatic-static-optimization)

### CODE REVIEW

**Review by lfades — APPROVED** [review]
@HaNdTriX Thank you 💯

**Comment by lww** [comment]
@HaNdTriX Awesome, thank you! Could you show how to add redux-persist?

**Comment by frnk94** [comment]
@lww Why would you want something like Redux-persist ? It defeat the purpose of next. Make you data available to your pages on the server-side rendering rather than caching it in the client browser. Redux-persist will block the rendering of your app until hydratation which will cause the app to render a blank page or the loading state on the server

**Comment by lww** [comment]
@frnk94 you are right, I already hacked something together and it is of course blocking the rendering of the page.
So how do I "persist" data over page changes, except for using cookies or query params, or a DB?

**Comment by imagine10255** [comment]
Hi, I also need a case to be persistent.

**Pull request merged**
