### PR TITLE
Feature proposal - Add `render` option to `exportPathMap`

### PR DESCRIPTION
**Pull request by digigarlab**
This would add the ability to pass a custom render function to the `exportPathMap`. It is useful to render things other than html files, for example sitemaps or json files.

### CODE REVIEW

**Comment by timneutkens** [comment]
At the point you want to do this with `exportPathMap` all you'd have to do is create a script that reads the config value right 🤔 

```
const {exportPathMap} = require('./next.config.js')

function render(page, query) {
  return `something ${page} ${JSON.stringify(query)}`
}

async function run() {
  const map = await exportPathMap()
  for(const key in map) {
    const {page, query = {}} = map[key]
    const output = render(page, query)
  }
}
```

I don't think this has to be a feature of `next export` for above reason.

**Comment by digigarlab** [comment]
But doing so, all the pages would be rendered with that `render` method, when I only want a few of them to be. I am currently doing something like that for one of my projects:

```js
// next.config.js
module.exports = {
  async exportPathMap(defaultMap) {
    const sitemap = createSitemap()
    const slugs = await getSlugsFromCMS()

    slugs.forEach(slug => {
      const url = `/foo/${slug}`
      defaultMap[url] = { page: `/foo`, query: { slug } }
      sitemap.add({ url })
    })

    // Persist sitemap
    const xml = await generateSitemap()
    writeFileSync('./out/sitemap.xml', xml, 'utf8')
  }
}
```

As you can see I am using the command `next export` to generate the static website, where I want most of the page to not have any custom render passed. But the last bit (the sitemap generation) is annoying, because I have to call `writeFileSync` which is not nice and fragile (could break if the internals of `export` are changed, for example is `exportPathMap` is called before the `out` folder is cleared).

What I would like to be able to do instead is this:

```js
     defaultMap[`/sitemap.xml`] = { render: generateSitemap }
```

That way, the actual call to render is managed by the export function and there is no risk of overwriting. This would also be better than having the sitemap generation in a post-export script, because it uses the same data, thus it is more likely to be consistent with the pages.

What do you think?

**Comment by digigarlab** [comment]
Yes, there definitively are workarounds, including to use `writeFileSync` inside the `exportPathMap` like in my example above, or to run a post-export script that generates those files (like suggested in #3668 for a different use-case). I requested the feature because it seems to be a fairly common usage (to generate robots.txt, sitemap.xml etc) and it would be more handy to have a way to do that with just configuration.

In the case of the sitemap in particular, since the page urls can be generated from the result of an external API (in my case a headless CMS), having it in a different script would require to fetch this API again and apply almost the exact same logic I am doing to populate the map in `exportPathMap`, that's why I wasn't satisfied of the post-script solution. Also, I was previously running this project with express routes, and the route and sitemap logics were handled in the same place there.

**Comment by timneutkens** [comment]
I don't know if this was already the case, but since your comment the flow is:

1. flush out dir
2. create out dir
3. copy static dir contents
4. copy .next contents
5. run exportPathMap
6. loop over all pages and render them to out dir

`exportPathMap` is an `async` function meaning you don't have to use the `sync` version of `fs` methods. This means that adding the copy/write in `exportPathMap` is the right way to go and we don't have to introduce any new features for what you're trying to achieve. Maybe documenting this would make sense.

**Comment by timneutkens** [comment]
Created an alternative for your use case: #5089

**Pull request closed without merging**
