### PR TITLE
support `bun.lock` as package manager lockfile

### LINKED ISSUE #74082: `next dev --turbo` error when using `bun.lock` text lockfile
### Link to the code that reproduces this issue

https://github.com/matallui/bug-next-bun-text-lockfile

### To Reproduce

1. Create a new turborepo monorepo with `bun create turbo@latest`
2. Delete `bun.lockb` lockfile
3. Run `bun i --save-text-lockfile` in the root of the monorepo
4. `cd` into `apps/web` and run `bun run dev`

OR

1. Clone repo above
2. Install dependencies with `bun i`
3. `cd apps/web && bun run dev`

### Expected

Next dev server to start and be accessible on `localhost:3000`

### Current

```
   ▲ Next.js 15.1.1 (Turbopack)
   - Local:        http://localhost:3000
   - Network:      http://127.0.2.2:3000
   - Environments: .env

 ✓ Starting...
FATAL: An unexpected Turbopack error occurred. Please report the content of /var/folders/ks/8zn35t35521c9xvbtl9xt_7c0000gn/T/next-panic-18ab5faad2f00c774e96d73fa060eb8.log, along with a description of what you were doing when the error occurred, to https://github.com/vercel/next.js/issues/new
[Error [TurbopackInternalError]: Next.js package not found

Debug info:
- Execution of get_entrypoints_with_issues failed
- Execution of Project::entrypoints failed
- Execution of AppProject::routes failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_loader_tree failed
- Execution of *FileSystemPath::join failed
- Execution of get_next_package failed
- Next.js package not found]
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 19:02:41 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 20.18.1
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.15.0
Relevant Packages:
  next: 15.1.1
  eslint-config-next: 15.1.1
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
Next.js Config:
  output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

- If I run `next dev` without using Turbopack, it all seems to work fine
- Bun's text lockfile (bun.lock) was introduced a day or two ago with bun v1.1.39

### PR DESCRIPTION
**Pull request by RiskyMH**
Bun added support for a new lockfile format called `bun.lock` , this pr updates next.js so it can identify it.
https://bun.sh/blog/bun-lock-text-lockfile

There was also a problem that I had with standalone export and monorepo where it was getting so confused with where to place items (after I migrated to bun.lock), and it was fixed once I added empty `bun.lockb` file. I believe this PR should fix that issue and fixes #74082

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: acce12dfcb7538a9c56e4b1d470b0a6f5dfb1891

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — APPROVED** [review]
Thank you

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| buildDuration | 19.1s | 17.3s | N/A |
| buildDurationCached | 16.4s | 13.9s | N/A |
| nodeModulesSize | 416 MB | 416 MB | ⚠️ +148 B |
| nextStartRea..uration (ms) | 480ms | 478ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| index.html gzip | 522 B | 523 B | N/A |
| link.html gzip | 538 B | 537 B | N/A |
| withRouter.html gzip | 519 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 205 kB | 205 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 672 B | 667 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 356 kB | 356 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 346 kB | 346 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| app-route.ru...dev.js gzip | 39.1 kB | 39.1 kB | ✓ |
| app-route.ru..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.43 MB | 2.43 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | The-Fiery-Fire/next.js bun | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | N/A |
| index.pack gzip | 74 kB | 74.4 kB | ⚠️ +397 B |
| Overall change | 74 kB | 74.4 kB | ⚠️ +397 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: acce12dfcb7538a9c56e4b1d470b0a6f5dfb1891

**Comment by eps1lon** [comment]
Files need to be formatted. I can't do that for you since you disallowed maintainers to edit your PRs.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: acce12dfcb7538a9c56e4b1d470b0a6f5dfb1891

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/actions/app-action.test.ts` (PPR)
- app-dir action handling > should forward action request to a worker that contains the action handler (node)
- app-dir action handling > should forward action request to a worker that contains the action handler (edge)
- app-dir action handling > should not error when a forwarded action triggers a redirect (node)
- app-dir action handling > fetch actions > should handle redirects to routes that provide an invalid RSC response

<details>
<summary>Expand output</summary>

  ● app-dir action handling › should forward action request to a worker that contains the action handler (node)

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#other-page')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)
      at e2e/app-dir/actions/app-action.test.ts:862:7

  ● app-dir action handling › should forward action request to a worker that contains the action handler (edge)

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#other-page')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)
      at e2e/app-dir/actions/app-action.test.ts:862:7

  ● app-dir action handling › should not error when a forwarded action triggers a redirect (node)

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#other-page')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)
      at e2e/app-dir/actions/app-action.test.ts:905:7

  ● app-dir action handling › fetch actions › should handle redirects to routes that provide an invalid RSC response

    expect(received).toContain(expected) // indexOf

    Expected substring: "Hello from a pages route"
    Received string:    "0.9336823374616681
    Client
    Server
    Client and Server
    0
    +1+1 (Slow)-1*2
    redirect to a pages route
    submit
    test"

      1269 |
      1270 |       await retry(async () => {
    > 1271 |         expect(await browser.elementByCss('body').text()).toContain(
           |                                                           ^
      1272 |           'Hello from a pages route'
      1273 |         )
      1274 |         expect(await browser.url()).toBe(`${next.url}/pages-dir`)

      at toContain (e2e/app-dir/actions/app-action.test.ts:1271:59)
      at retry (lib/next-test-utils.ts:806:14)
      at Object.<anonymous> (e2e/app-dir/actions/app-action.test.ts:1270:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by RiskyMH** [comment]
> Files need to be formatted. I can't do that for you since you disallowed maintainers to edit your PRs.

oh i thought its enabled as every other time i have done PR it has worked, i cant seem to even find option anymore now.

anyway i have ran format

> Files need to be formatted. I can't do that for you since you disallowed maintainers to edit your PRs.

Oh sorry, I thought it is always enabled (like the many times I have done it before) but I can't seem to find setting anymore.

Anyway, I have linted it now (again sorry that I forgot to run lint here).

**Review by Netail — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]
Thank you!

**Pull request merged**
