### PR TITLE
implement persist for router state _idx

### LINKED ISSUE #36662: router state idx is not persist after user manually refresh the page
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.0
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

The idx router state is a very useful feature to have a unique id for the current page in the browser navigation stack. It is very useful in case you need to have more control on the website navigation and deal with it like a native app. The idx feature has been provided via the feature request #34980.  

The idx is working perfectly as long as the user navigate from one page to another using push, replace or pop actions. However if the user refresh the page by click F5 or using the address bar, the idx counter is reset to zero.

That cause any logic based on the idx value to be collapsed. 

Please refer to the feature request #34980 for more discussion about that issue

### Expected Behavior

The idx should be unique and persist in the session storage to avoid the idx counter value from reset to zero after page refresh

### To Reproduce

- Create a nextjs website with some different pages and add links to them in the main navigation menu.
- Run the app and in the developer tool console check the idx value. use `window.history.state.idx` in the console for that
- Navigate between the different pages either by push or replace or back and observe the value of the idx with every navigate
- Hit F5 from keyboard to refresh the page. 
- Check the idx value again, it will be zero

### PR DESCRIPTION
**Pull request by mramadanahmed**
## Bug

- [X] Related issues linked using `fixes #36662 `
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by mramadanahmed** [comment]
Hi @timneutkens, @ijjk, @shuding and @huozhi

I wondering when I can receive updates for that PR? I have a production issue related to that fix and I need to know if that PR will be merged or I have to find another workaround 

Thanks

**Comment by mramadanahmed** [comment]
Also I think it will fix the issue mentioned in the non merged PR #35770, kindly check

**Comment by mramadanahmed** [comment]
Hi @timneutkens, @ijjk, @shuding and @huozhi 

Any updates for that PR?

**Review by ijjk — COMMENTED** [review]
Hi, I don't think storing the index to session storage alone resolves the issue mentioned, I'm gonna close this for now, we can continue investigation on the linked issue

**Pull request closed without merging**
