### PR TITLE
Add static-no-js site example

### PR DESCRIPTION
**Pull request by giuseppeg**
Add an example of static site that doesn't use JS.

### CODE REVIEW

**Review by kheruc — APPROVED** [review]

**Review by timneutkens — CHANGES_REQUESTED** [review]
We shouldn't document it like this, it's guaranteed to break in the future because `<Head>` and `<NextScripts>` are removed.

**Comment by giuseppeg** [comment]
@timneutkens `<NextScripts>` is not used in this example. As for `Head` uhm it is the de facto component to inject stuff in the head right now right? Do you have a future proof alternative already?

**Comment by timneutkens** [comment]
@giuseppeg `Head` is the `next/document` `Head` component, removing it will break eg AMP even when not rendering scripts. We should figure out a way to do no-js pages instead I think, as when not using `<Head>` we don't have control over the app anymore, meaning that we can't guarantee it won't break in future releases as we simply don't test for it.

Issue for tracking full static export: https://github.com/zeit/next.js/issues/5054

**Comment by giuseppeg** [comment]
ok that's fairly trivial but not a priority. Since that's is the case though would it make sense to throw an error when `Head` or `NextScripts` are not used? I can submit a PR if you want

**Pull request merged**
