### PR TITLE
update default page generated by `next init`

### PR DESCRIPTION
**Pull request by stephensauceda**
In the interest of #354 and eventually documenting `next init` I thought a slightly nicer generated default page might be cool 😃 

screen shot 2016-12-10 at 11 45 35 am

I base64'd the logo from the readme rather than add a static file that would need to be copied over to `static` during the init process but maybe that would actually be preferred (both to cut down on noise in the generated `index.js` and to demonstrate using static files in general)?

### CODE REVIEW

**Comment by rauchg** [comment]
wow this is so beautiful… maybe we source from the cdn though?

**Comment by stephensauceda** [comment]
I originally did but then thought that would fail if someone were developing offline. But a broken image on a placeholder page might not be the end of the world :) Will update. Thanks!

**Comment by stephensauceda** [comment]
Updated. :)

**Comment by rauchg** [comment]
So beautiful. Thanks @stephensauceda <3

**Pull request merged**
