### PR TITLE
(Example) Add example `with-shadcn-ui`

### PR DESCRIPTION
**Pull request by vinaykulk621**
This PR adds example on how to build a next.js app with shadcn ui.

Preview-->[https://with-shadcn-ui.vercel.app/](https://with-shadcn-ui.vercel.app/)
Repo  -->[https://github.com/vinaykulk621/with-shadcn-ui](https://github.com/vinaykulk621/with-shadcn-ui)
shadcn-ui-->[https://ui.shadcn.com/](https://ui.shadcn.com/)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: b884b27be90acbb879d289e56f645798eb7ca9f5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by kachkaev** [comment]
Isn’t https://ui.shadcn.com & https://github.com/shadcn-ui/ui an example by itself? That project has no libraries to install, it’s using Next.js and Radix UI.

**Comment by vinaykulk621** [comment]
This example will serve as a starter template using next.js.

**Comment by vinaykulk621** [comment]
@kachkaev This example will serve as a starter template using next.js.

**Comment by kachkaev** [comment]
The example will get out of date very quickly. All one needs is to follow https://ui.shadcn.com/docs/installation/next.

**Comment by vinaykulk621** [comment]
@kachkaev If you look at it that way, almost every other example on this repo will get out of date at some point.
For now this will be a starter template just like other examples.

**Comment by kachkaev** [comment]
Other examples include packages marching example names. This new example does not contain a dependency named `chadcn` in package.json, which is by design.

**Pull request closed without merging**
