### PR TITLE
[create-next-app] remove "text-balance" custom class

### PR DESCRIPTION
**Pull request by ryota-murakami**
### What?
Remove  "text-balance" custom class from create-next-app tailwindCSS templates.
### Why?
TailwindCSS has exact same class since v3.4.0.
https://tailwindcss.com/docs/text-wrap

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 00ab0206233527074da1aaa763fefa1a331deb38

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@ryota-murakami Can you make sure the `text-balance` class gets updated to `text-wrap` in the templates as well?

E.g., https://github.com/vercel/next.js/blob/canary/packages/create-next-app/templates/app-tw/ts/app/page.tsx

**Comment by ryota-murakami** [comment]
@samcx Before tailwindCSS@3.4.0, they have no class name 'text-balance' so next templetes defined `text-balance` class as `text-wrap: balance;` rule.  
But now,  tailwindCSS has 'text-balance' classname as a exact same rule `text-wrap: balance;` .

I recorded that ensure  TailwindCSS native `text-balance` applied  `text-wrap: balance;` rule without custom defined `text-balance` in `@layer`.


https://github.com/vercel/next.js/assets/5501268/5843ac26-55f2-4b45-bbd8-b606d8eb3faf

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| buildDuration | 19.8s | 17.6s | N/A |
| buildDurationCached | 10.4s | 9.2s | N/A |
| nodeModulesSize | 360 MB | 360 MB | ✓ |
| nextStartRea..uration (ms) | 462ms | 484ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| 1103-HASH.js gzip | 31.9 kB | 31.9 kB | N/A |
| 1a9f679d-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 335-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| 7953.HASH.js gzip | 169 B | 169 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 230 B | 229 B | N/A |
| main-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | N/A |
| Overall change | 50.4 kB | 50.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 193 B | N/A |
| _error-HASH.js gzip | 192 B | 193 B | N/A |
| amp-HASH.js gzip | 507 B | 511 B | N/A |
| css-HASH.js gzip | 341 B | 343 B | N/A |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| edge-ssr-HASH.js gzip | 266 B | 265 B | N/A |
| head-HASH.js gzip | 362 B | 365 B | N/A |
| hooks-HASH.js gzip | 392 B | 392 B | ✓ |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | ✓ |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 329 B | 328 B | N/A |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 324 B | 324 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 8.27 kB | 8.27 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 542 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.7 kB | 94.7 kB | N/A |
| page.js gzip | 182 kB | 182 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 622 B | 622 B | ✓ |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 25.7 kB | 25.7 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 98.7 kB | 98.7 kB | ✓ |
| app-page-tur..prod.js gzip | 100 kB | 100 kB | ✓ |
| app-page-tur..prod.js gzip | 94.5 kB | 94.5 kB | ✓ |
| app-page.run...dev.js gzip | 157 kB | 157 kB | ✓ |
| app-page.run..prod.js gzip | 93.2 kB | 93.2 kB | ✓ |
| app-route-ex...dev.js gzip | 21.5 kB | 21.5 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route.ru...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route.ru..prod.js gzip | 15 kB | 15 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 51.6 kB | 51.6 kB | ✓ |
| Overall change | 963 kB | 963 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ryota-murakami/next.js feat/cna/remove-custom-class-that-include-tailwind-buint-in | Change |
| - | - | - | - |
| 0.pack gzip | 1.62 MB | 1.62 MB | ⚠️ +1.03 kB |
| index.pack gzip | 113 kB | 113 kB | ⚠️ +668 B |
| Overall change | 1.73 MB | 1.73 MB | ⚠️ +1.7 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 78da0c92a3a8d0e658bf2c1b022b0e34f397320c

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 78da0c92a3a8d0e658bf2c1b022b0e34f397320c

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts` (PPR)
- app-dir action allowed origins > should pass if localhost is set as a safe origin

<details>
<summary>Expand output</summary>

  ● app-dir action allowed origins › should pass if localhost is set as a safe origin

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      252 |   let next: NextInstance | undefined
      253 |   if (!skipped) {
    > 254 |     beforeAll(async () => {
          |     ^
      255 |       next = await createNext(options)
      256 |     })
      257 |     afterAll(async () => {

      at beforeAll (lib/e2e-utils.ts:254:5)
      at e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts:6:42
      at Object.describe (e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts:5:1)


  ● Test suite failed to run

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      131 |
      132 | if (typeof afterAll === 'function') {
    > 133 |   afterAll(async () => {
          |   ^
      134 |     if (nextInstance) {
      135 |       await nextInstance.destroy()
      136 |       throw new Error(

      at Object.afterAll (lib/e2e-utils.ts:133:3)
      at Object.<anonymous> (e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts:5:19)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
