### PR TITLE
Introduce unit (integration) tests for next-server

### PR DESCRIPTION
**Pull request by sheerun**
Hello,

I wanted to improve next-server code a bit but it turned out it doesn't have enough tests. This pull request introduces framework for adding very fast unit tests for each of packages and adds example unit tests (just for public interface, i.e. `constructor`, `getRequestHandler`, and in the future `render`) for `next-server`.

The test code for next-server uses nice fetch-like interface and real http server instead of req/res mocks so we can be confident that tests are correct. Server instance is reused for great performance (most tests take less than 10ms).

I've also added `yarn unitonly` and `yarn unitonly --watch` for running just "unit" tests (really these are fast integration tests as opposed to e2e tests that you named integration tests).

I hope this setup suits you, if you merge this I can contribute additional tests.

### CODE REVIEW

**Comment by timneutkens** [comment]
What isn't tested exactly? As far as I'm aware the server with pretty much all possible public options is tested, including usage of public methods 🤔

**Comment by sheerun** [comment]
Hmm, I couldn't find tests in next-server so I assumed it doesn't have any..

I think one thing that could be adapted from this PR is ability to put fast tests that reside inside  `packages`, and leave slow integration tests at root directory. Tenths of headless browsers for running tests is not fun and they take very long to run locally. Currently it's not really possible to just run fast tests and skip slow ones.

**Comment by timneutkens** [comment]
You can actually run single tests out of the test suite, that's documented in contributing.md: https://github.com/zeit/next.js/blob/canary/contributing.md#to-run-tests

**Comment by sheerun** [comment]
I know but it's hard to pick correct single tests. It would be better if I could run all fast tests for the component I'm working on. For example in this PR next-server contained all fast (unit) tests and I could execute all of them easilty by running yarn testonly packages/next-server

**Pull request closed without merging**
