### PR TITLE
[Examples] chore:with-sentry-update-dependencies

### LINKED ISSUE #37870: Upgrade with-sentry example to NextJs v12 and sentry-javascript V7
### Describe the feature you'd like to request

Want to be able to create NextJs v12.x application, instrumented with sentry-javascript v7.x on Vercel. With all the new features of both respectively. Including new features and fixes, listed in both release notes respectively.

### Describe the solution you'd like

The with-sentry example application should be default latest version of NextJs v12, and latest version of the sentry-javascript SDK

### Describe alternatives you've considered

The example code could just continue to have the outdated framework and SDK versions, but then users would have extra steps to use the current versions.

Today the deploy is also simply broken due to outdated dependencies

> 09:59:20.019] Cloning github.com/smeubank/nextjs-sentry-example (Branch: smeubank-v7, Commit: 7a6096a)
> [09:59:20.559] Cloning completed: 539.03ms
> [09:59:21.475] Looking up build cache...
> [09:59:21.942] Build Cache not found
> [09:59:22.236] Running "vercel build"
> [09:59:22.880] Vercel CLI 25.1.1-canary.3 build (beta) — https://vercel.com/feedback
> [09:59:23.231] Installing dependencies...
> [09:59:23.708] yarn install v1.22.17
> [09:59:23.741] info No lockfile found.
> [09:59:23.750] [1/4] Resolving packages...
> [09:59:25.415] warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> [09:59:25.438] warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> [09:59:26.230] [2/4] Fetching packages...
> [09:59:34.939] [3/4] Linking dependencies...
> [09:59:34.943] warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> [09:59:37.216] [4/4] Building fresh packages...
> [09:59:37.985] success Saved lockfile.
> [09:59:37.991] Done in 14.29s.
> [09:59:38.030] Detected Next.js version: 11.1.4
> [09:59:38.031] Running "yarn run build"
> [09:59:38.391] yarn run v1.22.17
> [09:59:38.429] $ next build
> [09:59:39.565] info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
> [09:59:39.832] Attention: Next.js now collects completely anonymous telemetry regarding usage.
> [09:59:39.832] This information is used to shape Next.js' roadmap and prioritize features.
> [09:59:39.833] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> [09:59:39.833] https://nextjs.org/telemetry
> [09:59:39.833] 
> [09:59:39.889] info  - Checking validity of types...
> [09:59:40.052] warn  - No ESLint configuration detected. Run next lint to begin setup
> [09:59:40.055] info  - Creating an optimized production build...
> [09:59:52.805] Failed to compile.
> [09:59:52.805] 
> [09:59:52.805] Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new 7a6096ad8027f8c66dcb77c6eec2c744c537548c
> [09:59:52.806] error: An organization slug is required (provide with --org)
> [09:59:52.806] 
> [09:59:52.806] Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
> [09:59:52.806] Please attach the full debug log to all bug reports.
> [09:59:52.806] 
> [09:59:52.806] 
> [09:59:52.807] > Build error occurred
> [09:59:52.807] Error: > Build failed because of webpack errors
> [09:59:52.807]     at /vercel/path0/node_modules/next/dist/build/index.js:397:19
> [09:59:52.807]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
> [09:59:52.808]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
> [09:59:52.837] error Command failed with exit code 1.
> [09:59:52.837] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> [09:59:52.866] Error! Command "yarn run build" exited with 1
> [09:59:52.978] Error: Command "vercel build" exited with 1

### PR DESCRIPTION
**Pull request by chaiwattsw**
## Bug

- [x] Fixes #37870

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Could you verify that you have tested this? Since this is a major upgrade, I wonder if the breaking changes should be addressed: https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0

**Comment by chaiwattsw** [comment]
> Could you verify that you have tested this? Since this is a major upgrade, I wonder if the breaking changes should be addressed: https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0

As I read from releases 7.0.0 note there is no affect from this breaking changes to examples/with-sentry since we didn't use BrowerTracing api?

> Removed Integrations.BrowserTracing export from @sentry/nextjs. Please import BrowserTracing from @sentry/nextjs directly. from [https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0](url)

However this is result of my tests! So first I config my personal SENTRY_DSN from .env.local then use
`pnpm build` 
> ```
> PS F:\next.js\examples\with-sentry> pnpm build
> 
> @ build F:\next.js\examples\with-sentry
> next build
> 
> info  - Loaded env from F:\next.js\examples\with-sentry\.env.local
> info  - Checking validity of types
> warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
> info  - Creating an optimized production build  
> info  - Compiled successfully
> info  - Collecting page data ..This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
>     at doAsyncWork (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:18:40)
>     at Object.5142 (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:20:1)
>     at __webpack_require__ (F:\next.js\examples\with-sentry\.next\server\webpack-runtime.js:25:42)
>     at __webpack_exec__ (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:43:39)
>     at F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:44:28
>     at Object.<anonymous> (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:47:3)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> info  - Collecting page data
> [    ] info  - Generating static pages (0/7)This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:  
> Error: Client Test 1
>     at doAsyncWork (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:18:40)
>     at Object.5142 (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:20:1)
>     at __webpack_require__ (F:\next.js\examples\with-sentry\.next\server\webpack-runtime.js:25:42)
>     at __webpack_exec__ (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:43:39)
>     at F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:44:28
>     at Object.<anonymous> (F:\next.js\examples\with-sentry\.next\server\pages\client\test1.js:47:3)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> info  - Generating static pages (7/7)
> info  - Finalizing page optimization
> 
> Page                                       Size     First Load JS
> ┌ ○ /                                      4.06 kB         107 kB
> ├   /_app                                  0 B             103 kB
> ├ ○ /404                                   286 B           103 kB
> ├ λ /api/test1                             0 B             103 kB
> ├ λ /api/test2                             0 B             103 kB
> ├ λ /api/test3                             0 B             103 kB
> ├ λ /api/test4                             0 B             103 kB
> ├ ○ /client/test1                          285 B           103 kB
> ├ ○ /client/test2                          312 B           103 kB
> ├ ○ /client/test3                          305 B           103 kB
> ├ ○ /client/test4                          577 B           103 kB
> ├ ○ /client/test5                          425 B           103 kB
> ├ λ /ssr/test1                             285 B           103 kB
> ├ λ /ssr/test2                             283 B           103 kB
> ├ λ /ssr/test3                             285 B           103 kB
> └ λ /ssr/test4                             284 B           103 kB
> + First Load JS shared by all              103 kB
>   ├ chunks/framework-e7c5d3df9e4c3a47.js   42 kB
>   ├ chunks/main-a20af9dac47ec8e8.js        28.6 kB
>   ├ chunks/pages/_app-6218892f6a47a9a8.js  31 kB
>   └ chunks/webpack-8eba2abae80223bc.js     971 B
> 
> λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
> ○  (Static)  automatically rendered as static HTML (uses no initial props)
> ```

and test with `pnpm start`
API test
- [x] test1.js [https://sentry.io/share/issue/84a927e377de44fba5c803e50b1745fa/](url)
- [x] test2.js [https://sentry.io/share/issue/d1efbc2d6388452dad52a98145a9391e/](url)
- [x] test3.js [https://sentry.io/share/issue/37d360e44e7f4837ba31df3435742d35/](url)
- [x] test4.js [https://sentry.io/share/issue/61fb4f6dfe4d40faa33fa9be22aa9847/](url)

Client test
- [x] test1.js [https://sentry.io/share/issue/055516af36e44101995511a531b1b9a6/](url)
- [] test2.js error not report to sentry
- [] test3.js error not report to sentry
- [] test4.js error not report to sentry
- [] test5.js error not report to sentry

SSR test
- [x] test1.js [https://sentry.io/share/issue/6ddfc8712c424178bda294f95462b310/](url)
- [x] test2.js [https://sentry.io/share/issue/3f4d0150a1864f11b5b0fb1dd955588f/](url)
- [x] test3.js [https://sentry.io/share/issue/ef9d489f2ed9443fb86069f4a3da020c/](url)
- [x] test4.js [https://sentry.io/share/issue/750c5396dc3243ca926ec1aea3654b26/](url)

**Comment by chaiwattsw** [comment]
Let me know if you need anything else @balazsorban44

**Comment by lobsterkatie** [comment]
@chaiwattsw - Thanks for doing this! I need to do the `package.json` bit in https://github.com/vercel/next.js/pull/37866. Would you like me to just do the rest while I'm at it, or would you rather keep those changes in this PR? I'm fine with either.

**Comment by chaiwattsw** [comment]
> @chaiwattsw - Thanks for doing this! I need to do the `package.json` bit in #37866. Would you like me to just do the rest while I'm at it, or would you rather keep those changes in this PR? I'm fine with either.

You're welcome! I'm fine with it, feel free to do the rest.
So I just need to close this PR right?

**Comment by lobsterkatie** [comment]
> So I just need to close this PR right?

Yes, please.

In porting over your changes, I took a closer look and realized that not all of them actually should come over. As far as `next.config.js` goes, switching it back to the docs version undoes the change in https://github.com/vercel/next.js/pull/28726. (If anything, we might consider making the docs match the example here, rather than vice-versa, though in that case I like the clarity of giving `sentryWebpackPluginOptions` a name, so will probably leave that one be.) And I'm leaving the note off of `tracesSampleRate` because we're currently doing some work on improving sampling and the advice may or may not apply anymore after we do. But I'm keeping the typo fix!  🙂

**Pull request closed without merging**
