### PR TITLE
Create with-redux-persist example

### PR DESCRIPTION
**Pull request by jrusso1020**
#### What does this PR do
This commit will add in an example using redux persist so that you
can persist redux state in your next app. We pass in the app component
to the loading `PersistGate` value, so that we can render our page
on initial render and then redux persist will kick in and rehydrate
afterwards.

This was based on an example started by https://github.com/ashwamegh https://github.com/zeit/next.js/pull/6932 and addresses this issue https://github.com/zeit/next.js/issues/6852

but that PR was never updated and merged in so I thought I would take a stab at making the change myself. If there is a better way of going about this let me know

### CODE REVIEW

**Comment by jrusso1020** [comment]
@lfades when you get a chance if you could let me know what you think that would be great!

**Comment by lfades** [comment]
👋  @jrusso1020 thank your for the PR , I ran the example locally, and I don't know what should I expect, Once the page was ready I activated `offline` mode in devtools, the page just shows the usual "no connection dinosaur", then I switched to slow 3G, and I was expecting the page to use the data from `localStorage` while the 10s request ends, but this is what I saw instead:
image

**Comment by jrusso1020** [comment]
@lfades This is more just to have the infrastructure of redux-persist in the application and have the application still rendered our while you're waiting for the whole request to complete. If you wanted to you could retrieve the information from local storage yourself and use it right away(instead of waiting for it to be in redux and getting it from there), but redux-persist won't kick in and rehydrate the redux state until the initial request for the next application is complete.

 If that makes sense.

An example of this that we are using currently is that we have an ecommerce shop that was originally written as a client side react.js application. We have now since started a Next.js application to SSR parts of our eccomerce shop to increase SEO and page load speeds. We have to do this in pieces though as it is a big project. The two applications need to be able to share state between them so that if you navigate between them we don't have to make more requests to get the current state we can just pass it through local storage persisted redux state. (the applications live on the same domain behind a HTTP Proxy)

**Review by lfades — APPROVED** [review]
@jrusso1020 Makes sense, thank you for the PR 💯

**Pull request merged**
