### PR TITLE
Replace extra div with React fragment.

### PR DESCRIPTION
**Pull request by segfaultmedaddy**
Fix to #2708 #3095

### CODE REVIEW

**Review by sergiodxa — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]
Thanks! I'll merge this soon. It's a semi-breaking change cause it can seriously mess up people's layout 
once we remove this 😅

**Comment by liweinan0423** [comment]
Will this be merged in next major release?

**Comment by pruhstal** [comment]
Can't wait.

**Comment by vanesyan** [comment]
It seems React add first-class support to Fragment component (i.e. React.Fragment) which is now behind the flag in the v16.1-beta version.

**Comment by designspin** [comment]
Hi, guys, great work. When can we expect this to be resolved and merged?

I really want to do away with those extra divs on a new project!

**Comment by timneutkens** [comment]
@vanesyan could you resolve the conflicts and create a new PR against the canary branch? Thanks!

**Pull request closed without merging**
