### PR TITLE
Fix: requirements for babel options in Typescript writeConfigurationDefaults

### PR DESCRIPTION
**Pull request by nnnnoel**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 236515a223fb08bf7154d18f6020d1cf12a5b381

**test/integration/app-tree/test/index.test.js** 
- AppTree > dev mode > should provide router context in AppTree on SSR
- AppTree > dev mode > should provide router context in AppTree on CSR
- AppTree > dev mode > should pass AppTree to NextPageContext
- AppTree > production mode > should provide router context in AppTree on SSR
- AppTree > production mode > should provide router context in AppTree on CSR
- AppTree > production mode > should pass AppTree to NextPageContext
- AppTree > serverless mode > should provide router context in AppTree on SSR
- AppTree > serverless mode > should provide router context in AppTree on CSR
- AppTree > serverless mode > should pass AppTree to NextPageContext

<details>
<summary>Expand output</summary>

  ● AppTree › dev mode › should provide router context in AppTree on SSR

    FetchError: request to http://localhost:46189/ failed, reason: connect ECONNREFUSED 127.0.0.1:46189

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● AppTree › dev mode › should provide router context in AppTree on CSR

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=89.0.4389.90)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at Object.<anonymous> (integration/app-tree/test/index.test.js:33:21)

  ● AppTree › dev mode › should pass AppTree to NextPageContext

    FetchError: request to http://localhost:46189/hello failed, reason: connect ECONNREFUSED 127.0.0.1:46189

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● AppTree › production mode › should provide router context in AppTree on SSR

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● AppTree › production mode › should provide router context in AppTree on CSR

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● AppTree › production mode › should pass AppTree to NextPageContext

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● AppTree › serverless mode › should provide router context in AppTree on SSR

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● AppTree › serverless mode › should provide router context in AppTree on CSR

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● AppTree › serverless mode › should pass AppTree to NextPageContext

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      283 | export async function killApp(instance) {
      284 |   await new Promise((resolve, reject) => {
    > 285 |     treeKill(instance.pid, (err) => {
          |                       ^
      286 |       if (err) {
      287 |         if (
      288 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:285:23
      at killApp (lib/next-test-utils.js:284:9)
      at integration/app-tree/test/index.test.js:60:20

  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      283 | export async function killApp(instance) {
      284 |   await new Promise((resolve, reject) => {
    > 285 |     treeKill(instance.pid, (err) => {
          |                       ^
      286 |       if (err) {
      287 |         if (
      288 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:285:23
      at killApp (lib/next-test-utils.js:284:9)
      at integration/app-tree/test/index.test.js:70:20

  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      283 | export async function killApp(instance) {
      284 |   await new Promise((resolve, reject) => {
    > 285 |     treeKill(instance.pid, (err) => {
          |                       ^
      286 |       if (err) {
      287 |         if (
      288 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:285:23
      at killApp (lib/next-test-utils.js:284:9)
      at integration/app-tree/test/index.test.js:85:13

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.3s | -34ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +3.73 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.086 | 2.09 | 0 |
| / avg req/sec | 1198.19 | 1196.24 | ⚠️ -1.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.331 | 1.294 | -0.04 |
| /error-in-render avg req/sec | 1878.59 | 1932.21 | +53.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.1s | -210ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +3.73 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.6 kB | 10.6 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.5s | ⚠️ +300ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +3.73 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.09 | 2.062 | -0.03 |
| / avg req/sec | 1196.01 | 1212.38 | +16.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.305 | 1.284 | -0.02 |
| /error-in-render avg req/sec | 1915.48 | 1946.86 | +31.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| 597-12fee761..569d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 7.1 kB | 7.1 kB | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.7 kB | 60.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _app-d0eb668..79ef.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d12ff..6063.js gzip | 3.4 kB | 3.4 kB | ✓ |
| amp-127483e4..9cd8.js gzip | 560 B | 560 B | ✓ |
| hooks-75994b..62d3.js gzip | 924 B | 924 B | ✓ |
| index-ac1ee6..819e.js gzip | 243 B | 243 B | ✓ |
| link-1cd4709..71e5.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..4d90.js gzip | 333 B | 333 B | ✓ |
| withRouter-0..60b0.js gzip | 329 B | 329 B | ✓ |
| Overall change | 8.72 kB | 8.72 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 324 B | 324 B | ✓ |
| Overall change | 324 B | 324 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nnnnoel/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "Kzzp1MXjoALsvU2X55uGC",
+        "buildId": "khkAm2p0OYJr3UAbWUOxV",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_buildManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_ssgManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "Kzzp1MXjoALsvU2X55uGC",
+        "buildId": "khkAm2p0OYJr3UAbWUOxV",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_buildManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_ssgManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "Kzzp1MXjoALsvU2X55uGC",
+        "buildId": "khkAm2p0OYJr3UAbWUOxV",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_buildManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Kzzp1MXjoALsvU2X55uGC/_ssgManifest.js"
+      src="/_next/static/khkAm2p0OYJr3UAbWUOxV/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 236515a223fb08bf7154d18f6020d1cf12a5b381

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 76184ab0cac021edea020c767a3a84e8d2bdf272

**test/integration/app-document/test/index.test.js** 
- Document and App > With CSP enabled > should load inline script by nonce

<details>
<summary>Expand output</summary>

  ● Document and App › With CSP enabled › should load inline script by nonce

    WebDriverError: unknown error: session deleted because of page crash
    from tab crashed
      (Session info: headless chrome=89.0.4389.114)

      151 |   allWindows = await browser.getAllWindowHandles()
      152 |   const newWindow = allWindows.find((win) => win !== initialWindow)
    > 153 |   await browser.switchTo().window(newWindow)
          |   ^
      154 | }
      155 |
      156 | export default async (

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at freshWindow (lib/next-webdriver.js:153:3)
      at _default (lib/next-webdriver.js:172:5)
      at Object.<anonymous> (integration/app-document/test/csp.js:16:23)

</details>

**Comment by timneutkens** [comment]
Going to close this PR as there is no associated issue and the description is empty.

**Pull request closed without merging**
