### PR TITLE
Place children before styles in head

### LINKED ISSUE #3575: <Head> content rendered in reverse order than declared
When rendering content to the `<Head>` component, I found out the order of the Head content is actually reverse than what I expected.

## Expected Behavior

I'd assume when declaring a `<Head>` inside the `_document.js` file, this content would show before content declared inside components further in the page lifecycle.

## Current Behavior

Right now it seems `<Head>` content is being shifted. So tags declared later are being rendered first in the head.

## Context

This can cause issues when trying to define resources to preload if scripts like GA or GTM are being executed first by the browser.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   ^4.1.4      |
| node    |  6 and 8       |
| OS      |   Ubuntu      |
| browser |   chrome      |

### PR DESCRIPTION
**Pull request by kachkaev**
Fixes #3575

### CODE REVIEW

**Comment by kachkaev** [comment]
Yeah, I guess you're right, however this is what folks in #3575 are asking for.

In addition to styles, another problem with the current order of children is to do with custom preconnect / preload links. Imagine I want to `<link rel="preconnect" href="https://www.google-analytics.com" />` and also ``<link rel="preload" href={`${assetPrefix}/_next/${customFontPath}`} as="font" />`` to make pages load faster. Adding these links into `<Head>` renders them at the very end of it, which makes preloading less efficient. The output of `{this.getCssLinks()}` can be tens of kilobytes when styles are rendered inline (https://github.com/zeit/next-plugins/issues/238#issuecomment-432211871).

**Comment by Enalmada** [comment]
What about allowing multiple head with some annotation letting users control where things end up:
```
<head dataBefore>
{ custom styles in next/head, preconnect/preload } 
</head>

<head dataAfter>
{ default behavior }
</head
```

**Comment by sheerun** [comment]
I think next.js could swtich this default behavior to what's this PR wants to do (doing this this way prevents issues e.g. with injecting extracted critical css because of wrong order of css) and leave old behavior with deprecation warning that asks to add to this element `dataAfter` like @Enalmada 

So in short I agree with @Enalmada but please don't leave it the default behavior.

**Comment by timneutkens** [comment]
This PR actually doesn't solve #3575 as it's asking for _document `<Head>` content to go before the `next/head` content. Basically meaning `{children}` before `{head}` in the component.

**Comment by timneutkens** [comment]
I've moved the discussion here: https://github.com/zeit/next.js/pull/3831#discussion_r240273980

**Comment by kachkaev** [comment]
Superseded by https://github.com/zeit/next.js/pull/5852

**Review by wbinnssmith — APPROVED** [review]

**Pull request closed without merging**
