### PR TITLE
Migrate the with-jotai example from page router to app router

### PR DESCRIPTION
**Pull request by ariannargesi**
## Migrate the with-jotai example from page router to app router

Please if it needs further updates, Let me know!
Happy to contribute

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 69112490d933944ad99885104b17d42b505ed4fd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ariannargesi** [comment]
Any updates on this one?

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture> @

**Comment by samcx** [comment]
@ariannargesi Looks we need to prettier the files correctly <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:">:frog-eyes:</picture>

**Comment by ariannargesi** [comment]
> Thank you for submitting a :pr:!
> 
> :lgtm: @

There is no prettier config in the example. How should I config the project in order to be aligned with standards?

**Comment by ariannargesi** [comment]
@samcx 
There is no prettier config in the example. How should I config the project in order to be aligned with standards?

**Comment by samcx** [comment]
@ariannargesi It's to align with the repositories standards—no prettier config is necessary in the example. You can simple run `pnpm prettier --write <relative-path-to-files-edited>` to make sure they're prettiered correctly.

**Comment by ariannargesi** [comment]
@samcx Done

**Pull request merged**
