### PR TITLE
feat: export `AppType` from `next/app`

### LINKED ISSUE #17407: [typescript] `AppType` is not exported from `next` entry
# Feature request

## Is your feature request related to a problem? Please describe.

I have to write like following now:

```ts
import type { AppType } from 'next/dist/next-server/lib/utils'
```

## Describe the solution you'd like

export `AppType` same as `NextPage` at https://github.com/vercel/next.js/blob/canary/packages/next/types/index.d.ts#L67-L73

```ts
import type { AppType } from 'next'
```

## Describe alternatives you've considered

It should be very easy, or

```ts
import type { AppType } from 'next/app'
```

## Additional context

N/A

### PR DESCRIPTION
**Pull request by JounQin**
close #17407

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.4s | ⚠️ +103ms |
| nodeModulesSize | 62.9 MB | 62.9 MB | ⚠️ +70 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.704 | 2.739 | ⚠️ +0.03 |
| / avg req/sec | 924.43 | 912.81 | ⚠️ -11.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.624 | 1.529 | -0.1 |
| /error-in-render avg req/sec | 1539.71 | 1634.84 | +95.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e3dd5fc..bc67.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f4d7a25..dule.js gzip | 6.23 kB | 6.23 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.29 kB | ⚠️ +7 B |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 634 B | ⚠️ +9 B |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | -2 B |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 996 B | 996 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_app-7512045..d9376e2ca.js</strong></summary>

```diff
@@ -91,6 +91,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       var _utils = __webpack_require__("g/15");
 
       exports.AppInitialProps = _utils.AppInitialProps;
+      exports.AppType = _utils.AppType;
       exports.NextWebVitalsMetric = _utils.NextWebVitalsMetric;
       /**
        * `App` component is used for initialize of pages. It allows for overwriting and full control of the `page` initialization.
```
</details>
<details>
<summary>Diff for <strong>_app-9a0d200..cd.module.js</strong></summary>

```diff
@@ -23,6 +23,7 @@
       var _utils = __webpack_require__("g/15");
 
       exports.AppInitialProps = _utils.AppInitialProps;
+      exports.AppType = _utils.AppType;
       exports.NextWebVitalsMetric = _utils.NextWebVitalsMetric;
       /**
        * `App` component is used for initialize of pages. It allows for overwriting and full control of the `page` initialization.
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      href="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-7512045a5b3d9376e2ca.js"
+      src="/_next/static/chunks/pages/_app-ce15ec81296ad313ef85.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      src="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      href="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -138,13 +138,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-7512045a5b3d9376e2ca.js"
+      src="/_next/static/chunks/pages/_app-ce15ec81296ad313ef85.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      src="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -30,7 +30,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      href="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -133,13 +133,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-7512045a5b3d9376e2ca.js"
+      src="/_next/static/chunks/pages/_app-ce15ec81296ad313ef85.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-9a0d2000fa07f32084cd.module.js"
+      src="/_next/static/chunks/pages/_app-460eed91d416e263bf67.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.7s | ⚠️ +478ms |
| nodeModulesSize | 62.9 MB | 62.9 MB | ⚠️ +70 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e3dd5fc..bc67.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f4d7a25..dule.js gzip | 6.23 kB | 6.23 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | N/A | N/A |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| _app-9017ec3..0f9f.js gzip | N/A | 1.29 kB | N/A |
| Overall change | 7.71 kB | 7.71 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | N/A | N/A |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| _app-73f6609..dule.js gzip | N/A | 634 B | N/A |
| Overall change | 5.36 kB | 5.36 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | JounQin/next.js patch-1 | Change |
| - | - | - | - |
| _error.js | 1.05 MB | 1.05 MB | ⚠️ +34 B |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.05 MB | 1.05 MB | ⚠️ +34 B |
| link.js | 1.1 MB | 1.1 MB | ⚠️ +34 B |
| routerDirect.js | 1.09 MB | 1.09 MB | ⚠️ +34 B |
| withRouter.js | 1.09 MB | 1.09 MB | ⚠️ +34 B |
| Overall change | 5.4 MB | 5.4 MB | ⚠️ +170 B |

</details>

</details>
Commit: a76d41de6e8ac9432216cfeba4547963c169fd2e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a76d41de6e8ac9432216cfeba4547963c169fd2e

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 1.01

      109 | 
      110 |       if (_appSize.endsWith('kB')) {
    > 111 |         expect(parseFloat(_appSize)).toBe(1)
          |                                      ^
      112 |         expect(_appSize.endsWith('kB')).toBe(true)
      113 |       } else {
      114 |         expect(parseFloat(_appSize) - 1000).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:111:38)

</details>

**Comment by JounQin** [comment]
Well the output bundler is a bit bigger than before (1KB -> 1.01KB)... 😂
Should I change the test case?

**Review by lfades — COMMENTED** [review]
@JounQin What's the use case here, why do you need `AppType`?

**Comment by JounQin** [comment]
@lfades I want to add `getInitialProps` to `App` component like `NextPage`.

```tsx
const App: AppType = () => {}

App.getInitialProps = () => {
  return {}
}

export default App
```

**Comment by lfades** [comment]
@JounQin That case is already covered by:

```tsx
import { AppContext, AppInitialProps } from 'next/app'

function App () {
  // ...
}

App.getInitialProps = async ({ Component, ctx }: AppContext): Promise<AppInitialProps> => {
  // ...
}
```

It's actually better to do it that way because you can add your own types to the returned props (`Promise<AppInitialProps>`), meanwhile, `AppType` is internal and you're not allowed to extend it.

I'm going to close this PR based on my feedback above.

**Comment by JounQin** [comment]
@lfades Thanks for your response, but it will not emit error if I write `getInitialProps` wrongly and there will be no autocompletion. Why `NextPage` is exported but `AppType` not?

**Comment by lfades** [comment]
@JounQin `NextPage` was an error from my past that haunts me every night.

We don't want people to use `NextPage` or `AppType` because `getInitialProps` isn't a requirement, and they don't provide more value other than defining `getInitialProps` (you don't need `NextPage` to define a page, it's just a function component). And `AppType` is worse because its props aren't extendable like with `NextPage`

**Comment by JounQin** [comment]
`getInitialProps` is always not required in `NextPage` and `AppType`. And I imagined my question was about `better and correct typescript type definition`, although `getInitialProps` is not recommended to use, but there has been a warning on build time. And we lost the ability to prevent simple typo in `.ts`, what a pity.

> it will not emit error if I write `getInitialProps` wrongly and there will be no autocompletion

**Pull request closed without merging**
