### PR TITLE
docs: add algolia-react-instantsearch example

### PR DESCRIPTION
**Pull request by mthuret**
The goal of this example is to illustrate how you can use [Algolia React InstantSearch](https://community.algolia.com/react-instantsearch/) to perform your search with a Server-rendered application developed with Next.js. It also illustrates how you can keep in sync the Url with the search.

cc @timneutkens

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
This is really cool @mthuret!

**Comment by timneutkens** [comment]
@mthuret seems the build failed. could you run `npm run lint -- --fix`

**Comment by mthuret** [comment]
@timneutkens yep, this is fixed, thanks!

**Comment by timneutkens** [comment]
Thanks!

**Comment by matheuss** [comment]
Algolia 😻

**Pull request merged**
