### PR TITLE
Update Ant Design example

### PR DESCRIPTION
**Pull request by yesmeck**
Upgrade `antd@2` to `antd@3`.

### CODE REVIEW

**Comment by 1kohei1** [comment]
Hi, I'm also using `antd@3` and trying to load css by module instead of loading them over CDN. Do you have any idea how to load css by module?

**Comment by timneutkens** [comment]
@1kohei1 Next v5 will support that.

**Review by timneutkens — APPROVED** [review]
Thanks!

**Comment by 1kohei1** [comment]
This is how I ended up loading css module per components and deploy to now. I hope this helps someone. [Load ant.design css by module in Next app](https://medium.com/@koheiarai94/load-ant-design-css-by-module-in-next-app-21c8c2c8c248)

**Pull request merged**
