### PR TITLE
Remove dynamic arrow binding in Link

### PR DESCRIPTION
**Pull request by ku8ar**
better performance

### CODE REVIEW

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | ku8ar/next.js canary | Change |
| - | - | - | - |
| Build Duration | 23.5s | 22.8s | -665ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +504 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.32 kB | ⚠️  +138 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.86 kB | ⚠️  +33 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.97 kB | ⚠️  +163 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.76 kB | ⚠️  +34 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.43 MB | 1.43 MB | ⚠️  +1.6 kB |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | ku8ar/next.js canary | Change |
| - | - | - | - |
| Build Duration | 25.2s | 24.8s | -312ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +504 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.32 kB | ⚠️  +138 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.86 kB | ⚠️  +33 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.97 kB | ⚠️  +163 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.76 kB | ⚠️  +34 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ⚠️  +224 B |
| Serverless `pages/link` gzip Size | 68.7 kB | 68.7 kB | ⚠️  +26 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +2 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.2 kB | 66.2 kB | ⚠️  +2 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +1 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.5 kB | 66.5 kB | ⚠️  +1 B |
| Build Dir Size | 2.64 MB | 2.64 MB | ⚠️  +1.6 kB |

</details>

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | ku8ar/next.js canary | Change |
| - | - | - | - |
| Build Duration | 23.7s | 23.1s | -572ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +504 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.32 kB | ⚠️  +138 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.86 kB | ⚠️  +33 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.97 kB | ⚠️  +163 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.76 kB | ⚠️  +34 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.43 MB | 1.43 MB | ⚠️  +1.6 kB |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | ku8ar/next.js canary | Change |
| - | - | - | - |
| Build Duration | 24.8s | 25.8s | ⚠️  +937ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +504 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ⚠️  +2 B |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ⚠️  +1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.32 kB | ⚠️  +138 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.86 kB | ⚠️  +33 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.97 kB | ⚠️  +163 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.76 kB | ⚠️  +35 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ⚠️  +1 B |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ⚠️  +224 B |
| Serverless `pages/link` gzip Size | 68.7 kB | 68.7 kB | ⚠️  +23 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | -2 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.2 kB | 66.2 kB | -1 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.4 kB | 66.4 kB | ✓ |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.5 kB | 66.5 kB | -1 B |
| Build Dir Size | 2.64 MB | 2.64 MB | ⚠️  +1.6 kB |

</details>

**Comment by timneutkens** [comment]
It's breaking the tests.

**Comment by ku8ar** [comment]
Tests failed because of my mistake?

**Comment by ku8ar** [comment]
@timneutkens can you give me any advice how to run this tests locally?
Right now im' trying to run by `yarn testonly --testPathPattern "client-navigation"`, but every time it shows an error (with or without my changes)...

**Comment by timneutkens** [comment]
Check https://github.com/zeit/next.js/blob/canary/contributing.md

**Comment by timneutkens** [comment]
I'm going to close this as it currently breaks the tests, we'd be happy to merge an update when the tests pass though 💯 Thanks so much for your contribution!

**Pull request closed without merging**
