### PR TITLE
Run fly in production

### PR DESCRIPTION
**Pull request by timneutkens**
As talked about with @lukeed

### CODE REVIEW

**Comment by nkzawa** [comment]
I wonder why we need 🤔

**Comment by lukeed** [comment]
We actually don't. Still having the conversation. It's nothing to do with Fly itself. @timneutkens wants to compile the Babel scripts & inject a `NODE_ENV` value while doing so.

**Comment by lukeed** [comment]
I think you need [this](https://www.npmjs.com/package/babel-plugin-transform-inline-environment-variables). And then I would introduce an `uglify()` step (within `release` task), which would drop the dead code blocks.

Eg; `'development' === 'production'`, `'production' === 'production'`

**Comment by timneutkens** [comment]
Actually it has no relation to dead code removal. Webpack handles that. The only reason I want to do this is to keep the environment consistent with the way we're building (for production). If we don't pass it through babel will default to development.

**Comment by rauchg** [comment]
+1 that this is very strange

**Comment by timneutkens** [comment]
@lukeed if it's not needed at all we could close it though.

**Comment by lukeed** [comment]
If I'm understanding you correctly, then the current behavior makes perfect sense. It's doing all that it is configured to do.

Right now, the only bundle that gets injected with a production environment is the prefetcher script, because it's the only entry that webpack is aware of.

While setting the environment here _might_ work, I don't think it's a very consistent way of doing it, iirc. This is why bundlers like rollup & webpack rely on replace-text plugins, --environment flags, cross-env, or a combo of the three.

And personally, I would still worry about dead codeblocks. Once you inject an environment value, react has so many block statements that can be cleaned up or removed, which removes the need for a simple parts and a simple execution. Without it, you still technically don't have a production-ready react bundle. 

Sorry to go on about it, but I know Dan Abramov has spoken a lot about this.

**Comment by timneutkens** [comment]
Closing this after discussing with @lukeed. He's going to check the dead code removal.

**Pull request closed without merging**
