### PR TITLE
docs: fix code block language in images-and-fonts docs

### PR DESCRIPTION
**Pull request by JamBalaya56562**
## Summary
Update incorrect code block languages at [Images and Fonts](https://nextjs.org/docs/canary/app/getting-started/images-and-fonts) docs.

### Improving Documentation

- [x] Run `pnpm prettier-fix` to fix formatting issues before opening the PR.
- [x] Read the Docs Contribution Guide to ensure your contribution follows the docs guidelines: https://nextjs.org/docs/community/contribution-guide

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ff453907d4d7c14d608e65d5c1c119f58ccd57cb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ff453907d4d7c14d608e65d5c1c119f58ccd57cb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ff453907d4d7c14d608e65d5c1c119f58ccd57cb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by delbaoliveira — APPROVED** [review]
Thank you!

**Review by ijjk — APPROVED** [review]

**Pull request merged**
