### PR TITLE
example: fix example error

### PR DESCRIPTION
**Pull request by li-jia-nan**
example: fix example error

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e571e90d489c5c835ff43b3b1a15bb02c45421ec

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — DISMISSED** [review]
Could you explain what's the error being addressed here?

I see you opened this on the Ant Design repo too, but there was no reasoning: https://github.com/ant-design/ant-design/pull/44440

**Comment by li-jia-nan** [comment]
> Could you explain what's the error being addressed here?
> 
> I see you opened this on the Ant Design repo too, but there was no reasoning: [ant-design/ant-design#44440](https://github.com/ant-design/ant-design/pull/44440)

Hello, The client's cache should not be recreated

- https://github.com/ant-design/ant-design/issues/44364#issuecomment-1689249300

**Comment by li-jia-nan** [comment]
image

**Comment by li-jia-nan** [comment]
@balazsorban44 @leerob @huozhi @timneutkens @styfle Can someone review this for me? thank you

**Review by styfle — DISMISSED** [review]
I agree with @balazsorban44 

This PR doesn't explain what the bug is or why this PR would fix it.

Furthermore, I can't find any documentation on this function besides https://ant-design.github.io/cssinjs#createcache

image
 
So asking for a review here is nearly impossible.

That said, since https://github.com/ant-design/ant-design/pull/44440 was merged upstream then perhaps we should merge this too.

**Comment by li-jia-nan** [comment]
@styfle  I'm sorry that I didn't explain the reason. My English is not good. In some special scenarios, the cache changes, leading to unexpected situations. For example, when the layout switches pages, the cache is not uninstalled, but the cache is re-created. , resulting in a miss when obtaining the component's style cache. To sum up, the cache should only be created once.

**Review by styfle — COMMENTED** [review]
Thanks!

Looks like we can't merge because lint is failing

```
warning  React Hook React.useMemo has an unnecessary dependency: 'createCache'. Either exclude it or remove the dependency array. Outer scope values like 'createCache' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps
```

**Comment by li-jia-nan** [comment]
I have removed unnecessary dependencies, please check again, thank you

**Review by styfle — APPROVED** [review]

**Pull request merged**
