### PR TITLE
Add a class to the error-debug screen

### PR DESCRIPTION
**Pull request by aesopwolf**
This allows developers to easily target the div and take actions on it (override styles, for example).

### CODE REVIEW

**Comment by rauchg** [comment]
I think this is better done by defining your own error component?

**Comment by aesopwolf** [comment]
I defined my own `_error.js` file, but the `ErrorDebug` component still gets injected during development (NODE_ENV !== 'production').

The reason I ran into this situation is because I'm trying to show a login page if the user visits a protected route. Everything works fine in production, and mostly fine during dev except my login form is being hidden because `ErrorDebug` has a z-index of 9999.

Here's some sample code:

```jsx
import React from 'react';
import circular from 'circular';
import LoginPage from './_login';

export default class Error extends React.Component {
  static getInitialProps({ pathname, query, res, xhr, err }) {
    let statusCode = null;

    if (res) {
      statusCode = res.statusCode;
    } else if (xhr) {
      statusCode = xhr.status;
    }

    const error = JSON.parse(JSON.stringify(err, circular()));
    return { statusCode, pathname, query, error };
  }

  componentDidMount() {
    window.Raven.captureMessage(this.props.statusCode ? 'Server Error' : 'Client Error', {
      extra: {
        pathname: this.props.pathname,
        query: this.props.query,
        error: this.props.error,
      },
    });
  }

  render() {
    return (
      <div>{
        <Choose>
          <When condition={this.props.error.response.status === 401}>
            <LoginPage />
          </When>
          <Otherwise>
            <p>{this.props.statusCode
            ? `A ${this.props.statusCode} error occurred on server`
            : 'An error occurred on client'}</p>
          </Otherwise>
        </Choose>
      }</div>
    );
  }
}

Error.propTypes = {
  statusCode: React.PropTypes.number,
  pathname: React.PropTypes.string,
  query: React.PropTypes.obj,
  error: React.PropTypes.obj,
};
```

and the DOM output:

image


Where my div with "data-reactid=2" is my login form, but I can't see it due to the ErrorDebug z-index :/

**Comment by nkzawa** [comment]
>  I'm trying to show a login page if the user visits a protected route

@aesopwolf `ErrorDebug` component should not be injected if it's not an error. How do you implement this ?

**Comment by aesopwolf** [comment]
Like so:

```jsx
static async getInitialProps(ctx) {
  const user = await http.get('v1/user');

  return {
    user: user.data.user,
  };
}
```

However, if the user isn't authenticated then an error will bubble up (since I'm not using try/catch). The error is then exposed to me in `_error.js` where I proceed to use `this.props.error.response.status === 401` to conditionally display a login screen.

I don't want to get sidetracked here though. The real goal of this PR is to simply add a class name to the div.

**Comment by nkzawa** [comment]
Makes sense but that is not something we recommend. I'd like to support displaying these errors in another way and think we should not add a class to the component for this purpose.

Instead you can use `#__next > div > div:nth-child(2)` as the css selector for now. 

Related: https://github.com/zeit/next.js/issues/746

**Comment by timneutkens** [comment]
Closing in favor of what @nkzawa said.

This might help https://github.com/zeit/next.js/pull/1040

**Pull request closed without merging**
