### PR TITLE
fix: Scroll restoration bug caused by `idx` reset to 0 on reload

### PR DESCRIPTION
**Pull request by AkifumiSato**
If `experimental.scrollRestoration = true`, reloading resets the value of Router's `_idx` to 0, so the scroll position cannot be restored correctly between pages.
Since this is stored in session storage, the scroll position may be restored with incorrect values.

1. Load `/person/1`
```
+-----------+
| /person/1 |
| idx: 0    |
+-----------+
```
2. Move to `/person/2`
```
+-----------+-----------+
| /person/1 | /person/2 |
| idx: 0    | idx: 1    |
+-----------+-----------+
```
3. Reload `/person/2`
```
+-----------+-----------+
| /person/1 | /person/2 |
| idx: 0    | idx: 0    |
+-----------+-----------+
``` 

This modification restores the position of the browser back after reloading.
At the end of the first video, the scroll is not restored on browser back after reloading and is set to 0.
In the second video, the position is restored correctly.

https://user-images.githubusercontent.com/25711332/161005840-821f4811-067f-4cd3-8355-abfe8f065574.mov

https://user-images.githubusercontent.com/25711332/161005887-9a2fdaef-b3ca-460a-9e03-fee45e7a8ea2.mov

I made a similar correction in the following PR, but I had to make a new one because I had included other correction.
https://github.com/vercel/next.js/pull/35770

## Bug

- [ ] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by mikestead** [comment]
Thanks for doing this work @AkifumiSato , I've been running into a related issue. Worked around my one partially by accessing `idx` inside `history.state` but that's obv not ideal at all, and fundamentally using index numbering causes restore bugs. 

As you've addressed, a unique key is needed... you can see the same approach used if you check history.state of sites like twitter and instagram.

I would ask that you ideally make the `key` public. This allows developers to write their own page restoration logic if they need to, as I'm needing to currently (using idx hack). Otherwise I'll just have to access via history.state again, not ideal.

**Comment by mikestead** [comment]
I wanted to add a little more detail of why I believe it's important to expose `key` for custom page restoration wiring. 

Window scroll position is only a single restore state to factor in, but there can be things like carousel horizontal scroll positions inside of a page, or a ui component that's been expanded and then a link clicked. These are states that are not ideally stored as query parameters, but do need to be unique to the history position as the same page may be seen multiple times in history and have different internal restore state.

**Comment by AkifumiSato** [comment]
I have the same problem and once created a PR to publish the `key`.
https://github.com/vercel/next.js/pull/35770
Remix has a similar feature, and the WICG is considering a similar policy.
https://github.com/remix-run/history/blob/main/docs/api-reference.md#locationkey
https://github.com/WICG/navigation-api#the-current-entry
If the maintainer allows, I would like to publish the key as well.

**Comment by AkifumiSato** [comment]
The test is failing, but it appears to be unrelated to my fix.
https://github.com/vercel/next.js/runs/6424377024?check_suite_focus=true

**Review by ijjk — APPROVED** [review]
Thanks!

**Comment by AkifumiSato** [comment]
@mikestead New pull request created.
https://github.com/vercel/next.js/pull/37192

**Pull request merged**
