### PR TITLE
Throw error for direct public imports

### PR DESCRIPTION
**Pull request by mattcarlotta**
Assets placed within the `public` folder should be considered external assets. As such, directly importing a public asset from any file within the root directory should throw an error. See [public-assets-npm error](https://github.com/mattcarlotta/next.js/blob/public-import-error/errors/public-assets-npm.md) for more information.

This is similar functionality to the `create-react-app` implementation of not allowing developers to import from outside of `src` -- where an error would be thrown if a file from within `src` tries to directly import from `public`. See [issue #834](https://github.com/facebook/create-react-app/issues/834) for more information.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/config/test/index.test.js** 
- Configuration > Configuration > should have config available on the client
- Configuration > Configuration > should update css styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › Configuration › should have config available on the client

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#server-only"}
      (Session info: headless chrome=80.0.3987.163)

      10 |       const browser = await webdriver(context.appPort, '/next-config')
      11 | 
    > 12 |       const serverText = await browser.elementByCss('#server-only').text()
         |                          ^
      13 |       const serverClientText = await browser
      14 |         .elementByCss('#server-and-client')
      15 |         .text()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:12:26)

  ● Configuration › Configuration › should update css styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=80.0.3987.163)

      26 |       try {
      27 |         browser = await webdriver(context.appPort, '/webpack-css')
    > 28 |         const pTag = await browser.elementByCss('.hello-world')
         |                      ^
      29 |         const initialFontSize = await pTag.getComputedCss('font-size')
      30 | 
      31 |         expect(initialFontSize).toBe('100px')

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:28:22)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/config/test/index.test.js** 
- Configuration > Configuration > should have config available on the client
- Configuration > Configuration > should update css styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › Configuration › should have config available on the client

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#server-only"}
      (Session info: headless chrome=80.0.3987.163)

      10 |       const browser = await webdriver(context.appPort, '/next-config')
      11 | 
    > 12 |       const serverText = await browser.elementByCss('#server-only').text()
         |                          ^
      13 |       const serverClientText = await browser
      14 |         .elementByCss('#server-and-client')
      15 |         .text()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:12:26)

  ● Configuration › Configuration › should update css styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=80.0.3987.163)

      26 |       try {
      27 |         browser = await webdriver(context.appPort, '/webpack-css')
    > 28 |         const pTag = await browser.elementByCss('.hello-world')
         |                      ^
      29 |         const initialFontSize = await pTag.getComputedCss('font-size')
      30 | 
      31 |         expect(initialFontSize).toBe('100px')

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:28:22)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/config/test/index.test.js** 
- Configuration > Configuration > should have config available on the client
- Configuration > Configuration > should update css styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › Configuration › should have config available on the client

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#server-only"}
      (Session info: headless chrome=80.0.3987.163)

      10 |       const browser = await webdriver(context.appPort, '/next-config')
      11 | 
    > 12 |       const serverText = await browser.elementByCss('#server-only').text()
         |                          ^
      13 |       const serverClientText = await browser
      14 |         .elementByCss('#server-and-client')
      15 |         .text()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:12:26)

  ● Configuration › Configuration › should update css styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=80.0.3987.163)

      26 |       try {
      27 |         browser = await webdriver(context.appPort, '/webpack-css')
    > 28 |         const pTag = await browser.elementByCss('.hello-world')
         |                      ^
      29 |         const initialFontSize = await pTag.getComputedCss('font-size')
      30 | 
      31 |         expect(initialFontSize).toBe('100px')

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:28:22)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    1076

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 257 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/config/test/index.test.js** 
- Configuration > Configuration > should have config available on the client
- Configuration > Configuration > should update css styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › Configuration › should have config available on the client

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#server-only"}
      (Session info: headless chrome=80.0.3987.163)

      10 |       const browser = await webdriver(context.appPort, '/next-config')
      11 | 
    > 12 |       const serverText = await browser.elementByCss('#server-only').text()
         |                          ^
      13 |       const serverClientText = await browser
      14 |         .elementByCss('#server-and-client')
      15 |         .text()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:12:26)

  ● Configuration › Configuration › should update css styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=80.0.3987.163)

      26 |       try {
      27 |         browser = await webdriver(context.appPort, '/webpack-css')
    > 28 |         const pTag = await browser.elementByCss('.hello-world')
         |                      ^
      29 |         const initialFontSize = await pTag.getComputedCss('font-size')
      30 | 
      31 |         expect(initialFontSize).toBe('100px')

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/config/test/client.js:28:22)

</details>

**Comment by mattcarlotta** [comment]
Hmm, can't pinpoint why some of the tests are failing. I'm only adding a precursory check to make sure assets weren't imported from the `public` directory. I ran local dev and production builds and I didn't run into any issues. I'm assuming the tests are importing assets from the public directory? 🤔

**Comment by timneutkens** [comment]
This change doesn't seem needed 🤔 It would also break existing applications it seems

**Pull request closed without merging**
