### PR TITLE
Add handling for custom cache handlers

### PR DESCRIPTION
**Pull request by ijjk**
Follow-up to https://github.com/vercel/next.js/pull/71455 this adds wiring up for the cache handlers config and exposing it to use-cache-wrapper. Also adds mapping of remote -> default cache handler for dev.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 20350a54ffa0bee397c57de7dbf756d3383148b1

`pnpm test test/integration/app-dir-export/test/dev-custom-dist-dir.test.ts`
- app dir - with output export and custom distDir (next dev) > should render properly

<details>
<summary>Expand output</summary>

  ● app dir - with output export and custom distDir (next dev) › should render properly

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      31 |   it('should render properly', async () => {
      32 |     const res = await fetchViaHTTP(appPort, '/')
    > 33 |     expect(res.status).toBe(200)
         |                        ^
      34 |     expect(await res.text()).toContain('Home')
      35 |   })
      36 | })

      at Object.toBe (integration/app-dir-export/test/dev-custom-dist-dir.test.ts:33:24)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by sebmarkbage — APPROVED** [review]
I don't love the globalThis.nextCacheHandlers leaking to the global.

Seems like we should be able to put that in an internal module with shared state. E.g. using the `.external` convention.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 872631c6b8a914bfa3e8ba36adc10daae529831d

`pnpm test-start test/e2e/app-dir/use-cache/use-cache.test.ts`
- use-cache > should cache results

<details>
<summary>Expand output</summary>

  ● use-cache › should cache results

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#x')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 77d18fac3118c1cdd47d0f68d653ac3f80e9c6d2

`pnpm test-start test/e2e/app-dir/use-cache/use-cache.test.ts`
- use-cache > should cache results

<details>
<summary>Expand output</summary>

  ● use-cache › should cache results

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#x')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| buildDuration | 18.9s | 16.2s | N/A |
| buildDurationCached | 15.3s | 13.1s | N/A |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +38.9 kB |
| nextStartRea..uration (ms) | 434ms | 437ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| 1193.HASH.js gzip | 168 B | 168 B | ✓ |
| 1495-HASH.js gzip | 5.27 kB | 5.27 kB | N/A |
| 9073-HASH.js gzip | 44.2 kB | 44.2 kB | N/A |
| d4c1d954-HASH.js gzip | 52.6 kB | 52.6 kB | N/A |
| framework-HASH.js gzip | 57.4 kB | 57.4 kB | N/A |
| main-app-HASH.js gzip | 237 B | 236 B | N/A |
| main-HASH.js gzip | 32.8 kB | 32.8 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 168 B | 168 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 193 B | N/A |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 511 B | 510 B | N/A |
| css-HASH.js gzip | 341 B | 343 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 266 B | 266 B | ✓ |
| head-HASH.js gzip | 364 B | 364 B | ✓ |
| hooks-HASH.js gzip | 391 B | 391 B | ✓ |
| image-HASH.js gzip | 4.41 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 269 B | 268 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 327 B | N/A |
| script-HASH.js gzip | 397 B | 395 B | N/A |
| withRouter-HASH.js gzip | 324 B | 322 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.32 kB | 1.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 749 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| index.html gzip | 522 B | 523 B | N/A |
| link.html gzip | 535 B | 536 B | N/A |
| withRouter.html gzip | 518 B | 519 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 187 kB | 187 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 666 B | 671 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 31 kB | 31 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 1 kB | 1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 314 kB | 314 kB | ✓ |
| app-page-exp..prod.js gzip | 121 kB | 121 kB | ✓ |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | ✓ |
| app-page-tur..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page.run...dev.js gzip | 304 kB | 304 kB | ✓ |
| app-page.run..prod.js gzip | 116 kB | 116 kB | ✓ |
| app-route-ex...dev.js gzip | 35.9 kB | 35.9 kB | ✓ |
| app-route-ex..prod.js gzip | 24.4 kB | 24.4 kB | ✓ |
| app-route-tu..prod.js gzip | 24.4 kB | 24.4 kB | ✓ |
| app-route-tu..prod.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route.ru...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route.ru..prod.js gzip | 24.2 kB | 24.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| pages.runtim...dev.js gzip | 26.5 kB | 26.5 kB | ✓ |
| pages.runtim..prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| server.runti..prod.js gzip | 58.1 kB | 58.2 kB | N/A |
| Overall change | 1.39 MB | 1.39 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js ijjk/custom-cache-handlers | Change |
| - | - | - | - |
| 0.pack gzip | 1.84 MB | 1.84 MB | ⚠️ +846 B |
| index.pack gzip | 143 kB | 143 kB | N/A |
| Overall change | 1.84 MB | 1.84 MB | ⚠️ +846 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [8358],
   {
-    /***/ 771: /***/ (
+    /***/ 2258: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(5653);
+          return __webpack_require__(142);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 5267: /***/ (module, exports, __webpack_require__) => {
+    /***/ 9936: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,17 +40,17 @@
         __webpack_require__(755)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3489)
+        __webpack_require__(2183)
       );
-      const _getimgprops = __webpack_require__(5537);
-      const _imageconfig = __webpack_require__(8868);
-      const _imageconfigcontextsharedruntime = __webpack_require__(7610);
-      const _warnonce = __webpack_require__(2332);
-      const _routercontextsharedruntime = __webpack_require__(3445);
+      const _getimgprops = __webpack_require__(6561);
+      const _imageconfig = __webpack_require__(9706);
+      const _imageconfigcontextsharedruntime = __webpack_require__(3188);
+      const _warnonce = __webpack_require__(5157);
+      const _routercontextsharedruntime = __webpack_require__(1511);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6376)
+        __webpack_require__(320)
       );
-      const _usemergedref = __webpack_require__(3768);
+      const _usemergedref = __webpack_require__(8118);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
@@ -371,7 +371,7 @@
       /***/
     },
 
-    /***/ 3768: /***/ (module, exports, __webpack_require__) => {
+    /***/ 8118: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -432,7 +432,7 @@
       /***/
     },
 
-    /***/ 5537: /***/ (
+    /***/ 6561: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -448,9 +448,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(2332);
-      const _imageblursvg = __webpack_require__(7988);
-      const _imageconfig = __webpack_require__(8868);
+      const _warnonce = __webpack_require__(5157);
+      const _imageblursvg = __webpack_require__(9002);
+      const _imageconfig = __webpack_require__(9706);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -824,7 +824,7 @@
       /***/
     },
 
-    /***/ 7988: /***/ (__unused_webpack_module, exports) => {
+    /***/ 9002: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -879,7 +879,7 @@
       /***/
     },
 
-    /***/ 8208: /***/ (
+    /***/ 6821: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -906,10 +906,10 @@
         },
       });
       const _interop_require_default = __webpack_require__(9608);
-      const _getimgprops = __webpack_require__(5537);
-      const _imagecomponent = __webpack_require__(5267);
+      const _getimgprops = __webpack_require__(6561);
+      const _imagecomponent = __webpack_require__(9936);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6376)
+        __webpack_require__(320)
       );
       function getImageProps(imgProps) {
         const { props } = (0, _getimgprops.getImgProps)(imgProps, {
@@ -941,7 +941,7 @@
       /***/
     },
 
-    /***/ 6376: /***/ (__unused_webpack_module, exports) => {
+    /***/ 320: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -976,7 +976,7 @@
       /***/
     },
 
-    /***/ 5653: /***/ (
+    /***/ 142: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -993,8 +993,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.0.0-rc-bf7e210c-20241017/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(9166);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-bf7e210c-20241017_re_s3utpgylidq4iuqtuhvaikn7r4/node_modules/next/image.js
-      var next_image = __webpack_require__(6812);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-bf7e210c-20241017_re_z36suzq4wvowgbcnr6zytfoqpy/node_modules/next/image.js
+      var next_image = __webpack_require__(9101);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ const nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -1024,12 +1024,12 @@
       /***/
     },
 
-    /***/ 6812: /***/ (
+    /***/ 9101: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(8208);
+      module.exports = __webpack_require__(6821);
 
       /***/
     },
@@ -1039,7 +1039,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [2888, 9774, 179], () =>
-      __webpack_exec__(771)
+      __webpack_exec__(2258)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 77d18fac3118c1cdd47d0f68d653ac3f80e9c6d2

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1e9749788dce610e8698627492b35acbbca73070

`pnpm test-start-turbo test/e2e/app-dir/use-cache/use-cache.test.ts` (turbopack)
- use-cache > should cache results custom handler

<details>
<summary>Expand output</summary>

  ● use-cache › should cache results custom handler

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#x')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5d957588477b600a9032a5a6b2bbac2b38b41e0f

`pnpm test-dev test/development/acceptance/server-component-compiler-errors-in-pages.test.ts`
- Error Overlay for server components compiler errors in pages > importing 'server-only' in pages
- Error Overlay for server components compiler errors in pages > importing unstable_after from 'next/server' in pages

<details>
<summary>Expand output</summary>

  ● Error Overlay for server components compiler errors in pages › importing 'server-only' in pages

    Expected Redbox but found none

      103 |     )
      104 |
    > 105 |     await session.assertHasRedbox()
          |     ^
      106 |     await check(
      107 |       () => session.getRedboxSource(),
      108 |       /That only works in a Server Component/

      at Object.<anonymous> (development/acceptance/server-component-compiler-errors-in-pages.test.ts:105:5)

  ● Error Overlay for server components compiler errors in pages › importing unstable_after from 'next/server' in pages

    Expected Redbox but found none

      160 |     )
      161 |
    > 162 |     await session.assertHasRedbox()
          |     ^
      163 |     await check(
      164 |       () => session.getRedboxSource(),
      165 |       /That only works in a Server Component/

      at Object.<anonymous> (development/acceptance/server-component-compiler-errors-in-pages.test.ts:162:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
