### PR TITLE
fix(docs): fix onClick function example

### PR DESCRIPTION
**Pull request by Ubinquitous**
### What?
I found an example where the return from onClick wraps a function of type () => void back into a function of type () => void.

### How?
I assigned the function directly to onClick.

### CODE REVIEW

**Comment by delbaoliveira** [comment]
Thank you @Ubinquitous 🙏🏼 To keep the examples consistent, could you please update the other instances of `() => reset()`?

**Review by delbaoliveira — CHANGES_REQUESTED** [review]
Thank you @Ubinquitous 🙏🏼 To keep the examples consistent, could you please update the other instances of `() => reset()`?

**Comment by Ubinquitous** [comment]
Thanks for your response, @delbaoliveira !
Additionally, reset functions that use () => void have been changed!

**Comment by Ubinquitous** [comment]
For functions that return void, I thought it would be a reasonable example to explicitly declare the function in the onClick event! I know everyone is busy, but I dare to ask for your review!

**Comment by balazsorban44** [comment]
See https://github.com/vercel/next.js/pull/62629#issuecomment-1969238227

**Pull request closed without merging**
