### PR TITLE
fix crash on older browsers

### PR DESCRIPTION
**Pull request by philipheinser**

### CODE REVIEW

**Review by vankatadam — APPROVED** [review]

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Can you specify which older browsers? Do you have a reproduction for this?

https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure#browser_compatibility shows that we should be covered in all browsers that Next.js supports by default.

https://nextjs.org/docs/architecture/supported-browsers

If you need to support something older, you can check out https://nextjs.org/docs/architecture/supported-browsers#browserslist

Let's open an issue for this first, with a reproduction so we can investigate

**Comment by philipheinser** [comment]
Screenshot 2023-08-31 at 11 07 47


@balazsorban44 the docs say `Safari 12+` is supported you are using not only measure but also `Returns PerformanceMeasure` from the table you linked and it says `14.5 (Released 2021-04-26)`

**Comment by philipheinser** [comment]
@balazsorban44 `beforeHydrationMeasure` is `undefined` in browsers `Safari 12+` that you support. I don't get why the pr is closed.

**Comment by philipheinser** [comment]
@balazsorban44 Everywhere else in the file messument results are read with  `performance.getEntriesByName` for the reason that it returns `undefined` in browsers like Safari 13 for example.

**Comment by balazsorban44** [comment]
My bad! Looks like one of my colleagues came to the same conclusion, here is their PR #54808

**Pull request closed without merging**
