### PR TITLE
Add Cerebral example

### PR DESCRIPTION
**Pull request by christianalfoni**
This adds an example of Next.js used with the Cerebral project. www.cerebraljs.com.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Looks good!

**Comment by timneutkens** [comment]
Could you check the linting? ❤️

**Comment by christianalfoni** [comment]
@timneutkens Oh! For sure, should be okay now :) Thanks!

**Comment by timneutkens** [comment]
🙌 👌 Thanks!!!

**Comment by christianalfoni** [comment]
Thank you! :)

**Comment by edgesoft** [comment]
👍

**Pull request merged**
