### PR TITLE
examples: remove `app-dir` in `i18n-routing` directory name

### PR DESCRIPTION
**Pull request by JamBalaya56562**
### What?

1. Rename [`app-dir-i18n-routing`](https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing) example `i18n-routing`.
2. Rename [`i18n-routing`](https://github.com/vercel/next.js/tree/canary/examples/i18n-routing) example `i18n-routing-pages`.
3. Update the docs mentions i18n-routing examples.
4. Update the test includes i18n-routing examples.

### Why?

The default has already been App Router anyways and a lot of examples have migrated over.
x-ref: https://github.com/vercel/next.js/pull/72642#issuecomment-2474415343

### How?

Change them as in [reproduction-template](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template) and [reproduction-template-pages](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-pages) examples.

### Improving Documentation

- [x] Run `pnpm prettier-fix` to fix formatting issues before opening the PR.
- [x] Read the Docs Contribution Guide to ensure your contribution follows the docs guidelines: https://nextjs.org/docs/community/contribution-guide

### Adding or Updating Examples

- [x] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- [x] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 41c60605a46073dce111c5891fa87149cb5a496a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by delbaoliveira — APPROVED** [review]
Ty! FYI @samcx

**Comment by MonstraG** [comment]
Forgot to update docs:
https://nextjs.org/docs/app/building-your-application/routing/internationalization

still links to `app-dir-i18n-routing`

**Comment by JamBalaya56562** [comment]
> Forgot to update docs: https://nextjs.org/docs/app/building-your-application/routing/internationalization
> 
> still links to `app-dir-i18n-routing`

Thank you for your checking!
Yeah, v15.0.4 stable document has an old link.

However, the canary documentation shows [the correct new link](https://nextjs.org/docs/canary/app/building-your-application/routing/internationalization#resources).

In conclusion, I didn't forget to update the [internationalization document](https://github.com/vercel/next.js/blob/canary/docs/01-app/02-building-your-application/01-routing/15-internationalization.mdx).

**Pull request merged**
