### PR TITLE
React 16 (fiber)

### PR DESCRIPTION
**Pull request by kjs3**
This updates to React 16 and uses `ReactDOM.hydrate()` on the client as opposed to `render()`.

Notes: 

* This does not include SSR streaming.
* React no longer seems to be making `charSet` in meta tags lowercase. This made some tests fail and I played with manually doing this but that caused React to throw warnings. It's technically [in spec](https://www.w3.org/TR/html5/syntax.html#attributes-0) so I guess it's fine.

### CODE REVIEW

**Comment by timneutkens** [comment]
Might be good to keep https://github.com/zeit/next.js/pull/2659 in mind 👌 Can you add it as comment there?

**Comment by pruhstal** [comment]
thank you @kjs3

**Comment by msand** [comment]
Can this be installed from npm and used currently?

**Comment by kjs3** [comment]
@msand, I published it to npm under `next-react-16` but that's a hassle to use. You need `module-alias` for the node side, an alias in webpack, and you need to change .babelrc to use `next-react-16/babel` instead of `next/babel`.

Instead of all that I just pushed up a branch so you can install from github. Change the `next` line in your package.json to this:

```
"next": "https://github.com/kjs3/next.js.git#next-react-16",
```

This `next-react-16` branch is the same as the branch for this PR accept it includes `dist/`. I'll keep it up to date with any changes.

**Comment by kulshekhar** [comment]
fwiw, I've tested this PR with a small app and it worked without issues :+1:

**Review by timneutkens — APPROVED** [review]
Looks good! @arunoda has to review this too though, cause we need to decide what versioning we're going to use for this 👍

**Comment by kjs3** [comment]
@timneutkens: Yeah, I was wondering about that. I guess you could publish this under a tag like `fiber` if it needs some more vetting before going out under the `next` tag.

**Comment by timneutkens** [comment]
Merged 👍

**Comment by arunoda** [comment]
Thanks @kjs3 and @timneutkens.
But I had to revert this for few reasons.

I'll continue this PR and do a release soon.

1) We need to do this PR with backward compatibility. (Or simply do a major release) - Reason is we asked to users to use React 16 with this. If users forcefully go back to React 15 they lost dev time error tracking.

2) We need to make sure it's better to use `React. hydrate` even for normal rendering.

**Comment by kjs3** [comment]
@arunoda, you're right that this is a hard break to React 16. Are you wanting to maybe check for `ReactReconciler` and setup error handling with it if it exists?

As far as being better, SSR is more than 2x faster on the [doorsteps.com](https://www.doorsteps.com) codebase. I can't say I had problems with the client side `render()` when hydrating but `hydrate()` should be a little more flexible.

Let me know if there's specific work you'd like to see done?

**Comment by arunoda** [comment]
@kjs3 It's not a problem with this PR.
But we need to figure out a way to solve my point mentioned as 1) above or do a major release.

And this: https://twitter.com/arunoda/status/913442183243497473

**Comment by arunoda** [comment]
Actually I reverted my revert :D 
Since @timneutkens already released a major version, we are good to go.

**Comment by timneutkens** [comment]
👍 👍 👍 👌

**Comment by timneutkens** [comment]
Talked about it with rauchg yesterday, major release is not a problem. Will be a beta for now 😄

**Comment by kjs3** [comment]
@arunoda: Ok cool. I’m following your tweet and will keep an eye out for an issue on the React repo about whether we should keep using hydrate for all renders client side.

**Comment by timneutkens** [comment]
👌

**Comment by cloudle** [comment]
@arunoda: I've tried, and our latest **next.js** `npm` still not happy with React 16 now

Using "next": "https://github.com/kjs3/next.js.git#next-react-16" .. can't wait to see this really **merged** to master.

@timneutkens thanks for your great work 👍

**Comment by kjs3** [comment]
@arunoda: 😬  I guess I shouldn't delete that branch then. 

Please don't go to production with that. Or, if you do, fork it so I'm not the lynchpin in your setup. 😀

**Comment by cloudle** [comment]
oops, @kjs3 thanks for it.. I'll keep sync and move back to **next.js master** as soon as it ready.

**Comment by timneutkens** [comment]
@cloudle you can just use `next@beta` at this very moment @cloudle 👍

**Pull request merged**
