### PR TITLE
Update 10-parallel-routes.mdx

### PR DESCRIPTION
**Pull request by Fortivera**
Repeat of the image, in the Conditional Routes section. I deleted the second occurrence of the image in the section.

### CODE REVIEW

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: b0528fa687ab668ba58185c5b470a1e572e5c55a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Fortivera I think this is already being handled here, so we can close this!

https://github.com/vercel/next.js/pull/60981

**Comment by Fortivera** [comment]
Alright, sounds good!

**Pull request closed without merging**
