### PR TITLE
automatically enable managed paths for all node_modules

### PR DESCRIPTION
**Pull request by sokra**
This improves caching performance in monorepos where there are multiple node_modules folders
Automatically enable immutable paths for Yarn PnP

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +82ms |
| buildDurationCached | 2.8s | 2.8s | ⚠️ +6ms |
| nodeModulesSize | 195 MB | 195 MB | -1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.898 | 2.913 | ⚠️ +0.01 |
| / avg req/sec | 862.58 | 858.08 | ⚠️ -4.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.371 | 1.349 | -0.02 |
| /error-in-render avg req/sec | 1823.93 | 1853.41 | +29.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 6s | 5.8s | -262ms |
| buildDurationCached | 2.8s | 2.8s | -3ms |
| nodeModulesSize | 195 MB | 195 MB | -1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.853 | 2.748 | -0.1 |
| / avg req/sec | 876.14 | 909.79 | +33.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.368 | 1.273 | -0.1 |
| /error-in-render avg req/sec | 1828.07 | 1963.2 | +135.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 806a8b6685e6d2fda870ae9de3f2b5c5e4ec9819

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.7s | -176ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +62ms |
| nodeModulesSize | 195 MB | 195 MB | -1.27 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.316 | 3.31 | -0.01 |
| / avg req/sec | 754.02 | 755.36 | +1.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.516 | 1.561 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1649.07 | 1601.52 | ⚠️ -47.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 6.7s | 6.8s | ⚠️ +132ms |
| buildDurationCached | 3s | 3.2s | ⚠️ +153ms |
| nodeModulesSize | 195 MB | 195 MB | -1.27 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.177 | 3.349 | ⚠️ +0.17 |
| / avg req/sec | 786.89 | 746.44 | ⚠️ -40.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.488 | 1.51 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1679.81 | 1655.87 | ⚠️ -23.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 806a8b6685e6d2fda870ae9de3f2b5c5e4ec9819

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cfe1a30296b08282dca7cba8f53fe97f166ee7ff

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should recover after a bad return from the render function
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:561:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:617:8)

</details>

**Review by styfle — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 090bb4d43fab30a8baae00c894da44710b26421f

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should recover from errors in the render function
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after a bad return from the render function

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover from errors in the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:458:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after exporting an invalid page 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about5"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      491 |
      492 |         expect(await hasRedbox(browser)).toBe(true)
    > 493 |         expect(await getRedboxHeader(browser)).toMatchInlineSnapshot(`
          |                                                ^
      494 |           " 1 of 1 unhandled error
      495 |           Server Error
      496 |

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:493:48)

  ● basic HMR › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:561:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16s | -296ms |
| buildDurationCached | 3.5s | 3.5s | -31ms |
| nodeModulesSize | 195 MB | 195 MB | -1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.812 | 3.778 | -0.03 |
| / avg req/sec | 655.77 | 661.67 | +5.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.039 | 2.021 | -0.02 |
| /error-in-render avg req/sec | 1226.21 | 1237.22 | +11.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| buildDuration | 7.7s | 7.9s | ⚠️ +198ms |
| buildDurationCached | 4s | 3.7s | -309ms |
| nodeModulesSize | 195 MB | 195 MB | -1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.903 | 3.841 | -0.06 |
| / avg req/sec | 640.53 | 650.93 | +10.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.023 | 2.002 | -0.02 |
| /error-in-render avg req/sec | 1235.59 | 1248.95 | +13.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feature/monorepo-managed | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 69dccb3b14e9e93a18b67af7e88829bad6504d6d

**Pull request merged**
