### PR TITLE
Add `module` as server fallback main field

### LINKED ISSUE #6246: v8 server build error
# Bug report

With next.js 8, I get this unhelpful message and a 404 error on a page of my app:

```
✖ Server
  Compiled with some errors in 5.02s
```

When running a production build the error is more detailed and it seems that for the **server build**, next.js can't resolve a dependency's entrypoint if the `main` property is missing from package.json but the `module` property is specified.

The culprit seems to be this line:

https://github.com/zeit/next.js/blob/80cb91ec87f6d193899c19faaa89f3cddd87da85/packages/next/build/webpack-config.js#L192

## To Reproduce

One example of a package which defines `module` but not `main`: https://github.com/wereHamster/valde/blob/master/packages/iconography/package.json

## Expected behavior

In next.js 7 this worked, and I presume that using `module` as a main field in addition to `main` would also work in next.js 8, since the server part is also compiled with webpack.

## System information
 - OS: macOS 10.14.3
 - Version of Next.js: 8.0.0

### PR DESCRIPTION
**Pull request by Timer**
There are some packages in the ecosystem that only ship `module` versions of their packages (see #6246).

See prior art:
(1) [_Delivering untranspiled source code via npm_](http://2ality.com/2017/06/pkg-esnext.html)
(2) [_In Defense of .js_](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md)

Unfortunately, other users may use the `module` key to ship `browser`-like code (so we can't prefer it). Allowing the `module` field to be used as a fallback should remediate these situations.

---
Fixes #6246

### CODE REVIEW

**Comment by timneutkens** [comment]
Could you add a test for this behavior so that we don't break it in the future 🙏

**Review by timneutkens — APPROVED** [review]

**Comment by rashidul0405** [comment]
@Timer Glad to see you here, Man ;)

**Comment by Timer** [comment]
Just warming up, @rashidul0405 😄 !

**Comment by sheerun** [comment]
Maybe it should be primary field? As far as I know, it can reduce application size? No?

**Comment by sheerun** [comment]
OK I saw the comment. Maybe a flag to prefer this field?

**Comment by Timer** [comment]
@sheerun if you feel strongly you can override it in `next.config.js`. Thanks!

**Pull request merged**
