### PR TITLE
lint: use const instead of let

### PR DESCRIPTION
**Pull request by andreipfeiffer**

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Thanks! 👍

**Comment by impronunciable** [comment]
@andreipfeiffer could you merge with v3-beta so we can approve this?

thank you!

**Comment by impronunciable** [comment]
@andreipfeiffer could you merge with v3-beta so we can approve this?

thank you!

**Comment by timneutkens** [comment]
@impronunciable just clicked the update button 👍

**Comment by andreipfeiffer** [comment]
@impronunciable updated branch

**Comment by timneutkens** [comment]
Thank you very much @andreipfeiffer

**Comment by andreipfeiffer** [comment]
No no no ... thank YOU (:

**Pull request merged**
