### PR TITLE
Fix : when link child is react componet will cause warning #20434 #7915

### PR DESCRIPTION
**Pull request by jjlstruggle**
## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

**Comment by jjlstruggle** [comment]
When the child node of the link tag is a component，we can not observe it anyway

**Review by ijjk — COMMENTED** [review]
Hi, can we add a test case that fails without this change?

**Comment by jjlstruggle** [comment]
> Hi, can we add a test case that fails without this change?

just like this

```jsx
const Test = <div>this is a test</div>

function App(){
    return <Link><Test/></Link>
}
```

* you will receive a warning : Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? 
* because by when clone a function component will add a ref attribute to it props

```jsx
class Test extends React.Component {
  render() {
    return <div></div>;
  }
}

function App(){
    return <Link><Test/></Link>
}
```

* and when you use class components, ref gets an instance of the component instead of the root element

**Review by ijjk — COMMENTED** [review]
Could we add one of those cases to a page file in a test suite and then ensure the error isn't showing in the logs similar to this test? https://github.com/vercel/next.js/blob/6b49d4744c204d9d572ef2540f092c6195a56bb2/test/integration/client-navigation/test/index.test.js#L566

**Pull request closed without merging**
