### PR TITLE
chore(github): update comments stale period

### PR DESCRIPTION
**Pull request by samcx**
## Why?

Since we updated the stale waiting period in https://github.com/vercel/next.js/pull/73709, we need to update these comments as well.

### CODE REVIEW

**Comment by samcx** [comment]
* **#74291** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74291?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/74291?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| buildDuration | 18.8s | 15.9s | N/A |
| buildDurationCached | 15.1s | 12.9s | N/A |
| nodeModulesSize | 416 MB | 416 MB | ✓ |
| nextStartRea..uration (ms) | 483ms | 478ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 52.8 kB | 52.8 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 325 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 745 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| index.html gzip | 522 B | 524 B | N/A |
| link.html gzip | 537 B | 538 B | N/A |
| withRouter.html gzip | 518 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 206 kB | 206 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 669 B | 666 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 359 kB | 359 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 347 kB | 347 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route.ru...dev.js gzip | 39.2 kB | 39.2 kB | ✓ |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.44 MB | 2.44 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sam/github/comments | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | ⚠️ +2.89 kB |
| index.pack gzip | 73.4 kB | 73.9 kB | ⚠️ +538 B |
| Overall change | 2.15 MB | 2.16 MB | ⚠️ +3.42 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: c59a43b863ea7b97e20843d6ea70d2779a3d0f1e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c59a43b863ea7b97e20843d6ea70d2779a3d0f1e

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/next-after-app-api-usage/index.test.ts` (PPR)
- nextjs APIs in after() > request APIs inside after() > cannot be called in a dynamic page
- nextjs APIs in after() > request APIs inside after() > cannot be called in a prerendered page > with `dynamic = "error"`
- nextjs APIs in after() > request APIs inside after() > cannot be called in a prerendered page > with `dynamic = "force-static"`

<details>
<summary>Expand output</summary>

  ● nextjs APIs in after() › request APIs inside after() › cannot be called in a dynamic page

    expect(received).toContain(expected) // indexOf

    Expected substring: "[/request-apis/page-dynamic] nested cookies(): error: Error: Route /request-apis/page-dynamic used \"cookies\" inside \"after(...)\". This is not supported."
    Received string:    " ○ Compiling /request-apis/page-dynamic ...
     ✓ Compiled /request-apis/page-dynamic in 13.9s (700 modules)
     GET /request-apis/page-dynamic 200 in 14708ms
    [/request-apis/page-dynamic] headers(): error: Error: Route /request-apis/page-dynamic used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after

      at eval (../app/request-apis/helpers.js:7:19)
         5 |   after(async () => {
         6 |     try {
      >  7 |       await headers()
           |                   ^
         8 |       console.log(`[${route}] headers(): ok`)
         9 |     } catch (err) {
        10 |       console.error(`[${route}] headers(): error:`, err)
      [/request-apis/page-dynamic] cookies(): error: Error: Route /request-apis/page-dynamic used \"cookies\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"cookies\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:27:19)
      at eval (../app/request-apis/helpers.js:15:10)
        25 |   after(async () => {
        26 |     try {
      > 27 |       await cookies()
           |                   ^
        28 |       console.log(`[${route}] cookies(): ok`)
        29 |     } catch (err) {
        30 |       console.error(`[${route}] cookies(): error:`, err)
      [/request-apis/page-dynamic] connection(): error: Error: Route /request-apis/page-dynamic used \"connection\" inside \"after(...)\". The `connection()` function is used to indicate the subsequent code must only run when there is an actual Request, but \"after(...)\" executes after the request, so this function is not allowed in this scope. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:47:22)
      at eval (../app/request-apis/helpers.js:35:10)
        45 |   after(async () => {
        46 |     try {
      > 47 |       await connection()
           |                      ^
        48 |       console.log(`[${route}] connection(): ok`)
        49 |     } catch (err) {
        50 |       console.error(`[${route}] connection(): error:`, err)
      [/request-apis/page-dynamic] nested headers(): error: Error: Route /request-apis/page-dynamic used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:17:21)
      at eval (../app/request-apis/helpers.js:55:10)
        15 |     after(async () => {
        16 |       try {
      > 17 |         await headers()
           |                     ^
        18 |         console.log(`[${route}] nested headers(): ok`)
        19 |       } catch (err) {
        20 |         console.error(`[${route}] nested headers(): error:`, err)
      "
      at toContain (e2e/app-dir/next-after-app-api-usage/index.test.ts:72:22)
      at fn (lib/next-test-utils.ts:806:20)
      at Object.<anonymous> (e2e/app-dir/next-after-app-api-usage/index.test.ts:53:7)

  ● nextjs APIs in after() › request APIs inside after() › cannot be called in a prerendered page › with `dynamic = "error"`

    expect(received).toContain(expected) // indexOf

    Expected substring: "[/request-apis/page-dynamic-error] nested headers(): error: Error: Route /request-apis/page-dynamic-error used \"headers\" inside \"after(...)\". This is not supported."
    Received string:    "[/request-apis/page-dynamic] nested cookies(): error: Error: Route /request-apis/page-dynamic used \"cookies\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"cookies\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after

      at eval (../app/request-apis/helpers.js:37:21)
        35 |     after(async () => {
        36 |       try {
      > 37 |         await cookies()
           |                     ^
        38 |         console.log(`[${route}] nested cookies(): ok`)
        39 |       } catch (err) {
        40 |         console.error(`[${route}] nested cookies(): error:`, err)
      [/request-apis/page-dynamic] nested connection(): error: Error: Route /request-apis/page-dynamic used \"connection\" inside \"after(...)\". The `connection()` function is used to indicate the subsequent code must only run when there is an actual Request, but \"after(...)\" executes after the request, so this function is not allowed in this scope. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:57:24)
        55 |     after(async () => {
        56 |       try {
      > 57 |         await connection()
           |                        ^
        58 |         console.log(`[${route}] nested connection(): ok`)
        59 |       } catch (err) {
        60 |         console.error(`[${route}] nested connection(): error:`, err)
       ○ Compiling /request-apis/page-dynamic-error ...
       ✓ Compiled /request-apis/page-dynamic-error in 2.5s (702 modules)
       GET /request-apis/page-dynamic-error 200 in 3784ms
      [/request-apis/page-dynamic-error] headers(): error: Error: Route /request-apis/page-dynamic-error used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:7:19)
         5 |   after(async () => {
         6 |     try {
      >  7 |       await headers()
           |                   ^
         8 |       console.log(`[${route}] headers(): ok`)
         9 |     } catch (err) {
        10 |       console.error(`[${route}] headers(): error:`, err)
      [/request-apis/page-dynamic-error] cookies(): error: Error: Route /request-apis/page-dynamic-error used \"cookies\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"cookies\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:27:19)
      at eval (../app/request-apis/helpers.js:15:10)
        25 |   after(async () => {
        26 |     try {
      > 27 |       await cookies()
           |                   ^
        28 |       console.log(`[${route}] cookies(): ok`)
        29 |     } catch (err) {
        30 |       console.error(`[${route}] cookies(): error:`, err)
      [/request-apis/page-dynamic-error] connection(): error: Error: Route /request-apis/page-dynamic-error used \"connection\" inside \"after(...)\". The `connection()` function is used to indicate the subsequent code must only run when there is an actual Request, but \"after(...)\" executes after the request, so this function is not allowed in this scope. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:47:22)
      at eval (../app/request-apis/helpers.js:35:10)
        45 |   after(async () => {
        46 |     try {
      > 47 |       await connection()
           |                      ^
        48 |       console.log(`[${route}] connection(): ok`)
        49 |     } catch (err) {
        50 |       console.error(`[${route}] connection(): error:`, err)
      "
      at toContain (e2e/app-dir/next-after-app-api-usage/index.test.ts:109:24)
      at fn (lib/next-test-utils.ts:806:20)
      at e2e/app-dir/next-after-app-api-usage/index.test.ts:100:9

  ● nextjs APIs in after() › request APIs inside after() › cannot be called in a prerendered page › with `dynamic = "force-static"`

    expect(received).toContain(expected) // indexOf

    Expected substring: "[/request-apis/page-force-static] nested cookies(): error: Error: Route /request-apis/page-force-static used \"cookies\" inside \"after(...)\". This is not supported."
    Received string:    "[/request-apis/page-dynamic-error] nested headers(): error: Error: Route /request-apis/page-dynamic-error used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after

      at eval (../app/request-apis/helpers.js:17:21)
      at eval (../app/request-apis/helpers.js:55:10)
        15 |     after(async () => {
        16 |       try {
      > 17 |         await headers()
           |                     ^
        18 |         console.log(`[${route}] nested headers(): ok`)
        19 |       } catch (err) {
        20 |         console.error(`[${route}] nested headers(): error:`, err)
      [/request-apis/page-dynamic-error] nested cookies(): error: Error: Route /request-apis/page-dynamic-error used \"cookies\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"cookies\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:37:21)
        35 |     after(async () => {
        36 |       try {
      > 37 |         await cookies()
           |                     ^
        38 |         console.log(`[${route}] nested cookies(): ok`)
        39 |       } catch (err) {
        40 |         console.error(`[${route}] nested cookies(): error:`, err)
      [/request-apis/page-dynamic-error] nested connection(): error: Error: Route /request-apis/page-dynamic-error used \"connection\" inside \"after(...)\". The `connection()` function is used to indicate the subsequent code must only run when there is an actual Request, but \"after(...)\" executes after the request, so this function is not allowed in this scope. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:57:24)
        55 |     after(async () => {
        56 |       try {
      > 57 |         await connection()
           |                        ^
        58 |         console.log(`[${route}] nested connection(): ok`)
        59 |       } catch (err) {
        60 |         console.error(`[${route}] nested connection(): error:`, err)
       ○ Compiling /request-apis/page-force-static ...
       ✓ Compiled /request-apis/page-force-static in 805ms (704 modules)
       GET /request-apis/page-force-static 200 in 1068ms
      [/request-apis/page-force-static] headers(): error: Error: Route /request-apis/page-force-static used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:7:19)
         5 |   after(async () => {
         6 |     try {
      >  7 |       await headers()
           |                   ^
         8 |       console.log(`[${route}] headers(): ok`)
         9 |     } catch (err) {
        10 |       console.error(`[${route}] headers(): error:`, err)
      [/request-apis/page-force-static] cookies(): error: Error: Route /request-apis/page-force-static used \"cookies\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"cookies\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:27:19)
      at eval (../app/request-apis/helpers.js:15:10)
        25 |   after(async () => {
        26 |     try {
      > 27 |       await cookies()
           |                   ^
        28 |       console.log(`[${route}] cookies(): ok`)
        29 |     } catch (err) {
        30 |       console.error(`[${route}] cookies(): error:`, err)
      [/request-apis/page-force-static] connection(): error: Error: Route /request-apis/page-force-static used \"connection\" inside \"after(...)\". The `connection()` function is used to indicate the subsequent code must only run when there is an actual Request, but \"after(...)\" executes after the request, so this function is not allowed in this scope. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:47:22)
      at eval (../app/request-apis/helpers.js:35:10)
        45 |   after(async () => {
        46 |     try {
      > 47 |       await connection()
           |                      ^
        48 |       console.log(`[${route}] connection(): ok`)
        49 |     } catch (err) {
        50 |       console.error(`[${route}] connection(): error:`, err)
      [/request-apis/page-force-static] nested headers(): error: Error: Route /request-apis/page-force-static used \"headers\" inside \"after(...)\". This is not supported. If you need this data inside an \"after\" callback, use \"headers\" outside of the callback. See more info here: https://nextjs.org/docs/canary/app/api-reference/functions/after
      at eval (../app/request-apis/helpers.js:17:21)
      at eval (../app/request-apis/helpers.js:55:10)
        15 |     after(async () => {
        16 |       try {
      > 17 |         await headers()
           |                     ^
        18 |         console.log(`[${route}] nested headers(): ok`)
        19 |       } catch (err) {
        20 |         console.error(`[${route}] nested headers(): error:`, err)
      "
      at toContain (e2e/app-dir/next-after-app-api-usage/index.test.ts:119:24)
      at fn (lib/next-test-utils.ts:806:20)
      at e2e/app-dir/next-after-app-api-usage/index.test.ts:100:9

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by gaojude — APPROVED** [review]

**Comment by samcx** [comment]
### Merge activity

* **Dec 26, 6:08 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/74291).

**Pull request merged**
