### PR TITLE
chore(turbopack): Delete to-resolved-in-loop lint (too low signal)

### PR DESCRIPTION
**Pull request by bgw**
Had a discussion with @sokra about this during office hours. We were in agreement to delete this, not because it's usually wrong, but just because it's not high-signal enough:

- Many instances of `to_resolved().await` are on simple constructor calls, so it doesn't really matter if they're sequential. We could add some heuristics for this, but they'd be imperfect.
- `to_resolved().await` isn't actually what drives the work forward, it's the function call that schedules the work, so in some cases this isn't accurate (and you can't know without type information).
- This would make more sense if we were typically starved for work, but usually we have more tokio tasks than we can process anyways, so increasing parallelism is unlikely to help in most cases.
- Some code isn't performance sensitive (e.g. internal CLI utilities, tests), so this is just noise in those places.

Closes PACK-3678

### CODE REVIEW

**Comment by bgw** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/74113?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#74113** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74113?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/74113?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#74112** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74112?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#74110** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74110?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#74108** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74108?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| buildDuration | 20.2s | 17.9s | N/A |
| buildDurationCached | 16.8s | 14.4s | N/A |
| nodeModulesSize | 416 MB | 416 MB | N/A |
| nextStartRea..uration (ms) | 488ms | 494ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 539 B | 537 B | N/A |
| withRouter.html gzip | 520 B | 521 B | N/A |
| Overall change | 524 B | 524 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 205 kB | 205 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 670 B | 668 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 356 kB | 356 kB | ✓ |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 347 kB | 347 kB | ✓ |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| app-route.ru...dev.js gzip | 39.1 kB | 39.1 kB | ✓ |
| app-route.ru..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.43 MB | 2.43 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bgw/rm-to-resolved-in-loop-lint | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | N/A |
| index.pack gzip | 74.5 kB | 73 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: cd88f0f92e3d34d21474e2827dc45593930ac6a7

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cd88f0f92e3d34d21474e2827dc45593930ac6a7

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/actions/app-action.test.ts` (PPR)
- app-dir action handling > should forward action request to a worker that contains the action handler (node)
- app-dir action handling > fetch actions > should handle redirects to routes that provide an invalid RSC response

<details>
<summary>Expand output</summary>

  ● app-dir action handling › should forward action request to a worker that contains the action handler (node)

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#other-page')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)
      at e2e/app-dir/actions/app-action.test.ts:862:7

  ● app-dir action handling › fetch actions › should handle redirects to routes that provide an invalid RSC response

    expect(received).toContain(expected) // indexOf

    Expected substring: "Hello from a pages route"
    Received string:    "0.9361837851311594
    Client
    Server
    Client and Server
    0
    +1+1 (Slow)-1*2
    redirect to a pages route
    submit
    test"

      1269 |
      1270 |       await retry(async () => {
    > 1271 |         expect(await browser.elementByCss('body').text()).toContain(
           |                                                           ^
      1272 |           'Hello from a pages route'
      1273 |         )
      1274 |         expect(await browser.url()).toBe(`${next.url}/pages-dir`)

      at toContain (e2e/app-dir/actions/app-action.test.ts:1271:59)
      at retry (lib/next-test-utils.ts:806:14)
      at Object.<anonymous> (e2e/app-dir/actions/app-action.test.ts:1270:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by kdy1 — APPROVED** [review]

**Review by sokra — APPROVED** [review]

**Comment by bgw** [comment]
### Merge activity

* **Dec 19, 11:23 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/74113).

**Pull request merged**
