### PR TITLE
Separate `next init` (#531)

### LINKED ISSUE #531: `next init` as a separate module?
I don't want `next init` to stagnate, be opinionated, etc. The solution is perhaps to remove it.

How would you all feel about making `next init` an optional, installable command that comes from a different package?

```
npm install -g next-init
```

It would expose a global bin `next-init`. The cool thing about making it a separate module is that we can iterate on it independently, and add more features frequently.

Some ideas for the future.

```
next-init --preact --glamor
```

```
next-init --inferno --styletron
```

If anyone would be interested in leading this project, please let me know as well

Another discussion I'll open later is to take the same approach for compiling a next app into static files, via `next-export`.

### PR DESCRIPTION
**Pull request by ragingwind**
Fixes #531 
use [next-init](https://github.com/next-init/next-init) instead of

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
I'd like this to be less breaking. Lets add a `console.log` saying you can use `next-init` or `create-next-app` 👌

**Comment by ragingwind** [comment]
@timneutkens Would you check out the message below. Feel free to update it

```
console.log(`
    'next init' does not support any more. Please try next-init or create-next-app instead of

    $ npm i -g next-init or create-next-app
`)
```

and the build failed on appveyor, I have no idea about that. Please let me know what happened

**Comment by timneutkens** [comment]
```
console.log(`
    'next init' is not supported anymore. These community projects provide the same functionality as 'next init' with additional features: http://npmjs.com/next-init and http://npmjs.com/create-next-app.
`)
```

I guess it'd be best to just link to the packages and let the user figure out how they work from their docs 👌

**Comment by ragingwind** [comment]
@timneutkens updated

**Comment by timneutkens** [comment]
@ragingwind could you update it to my message?

**Comment by ragingwind** [comment]
oh my bad. I didn't see the rest of message. I will

**Review by timneutkens — APPROVED** [review]
Looks great 👌

**Comment by timneutkens** [comment]
Fixes #531

**Pull request merged**
