### PR TITLE
Support adding CSP nonce with `content-security-policy-report-only` header

### LINKED ISSUE #48966: Content Security Policy nonce support doesn't support `content-security-policy-report-only`
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.19.1
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.23.0
    Relevant packages:
      next: 13.3.2-canary.12
      eslint-config-next: 13.3.2-canary.12
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Sprokets/nextjs-csp-report-only

### To Reproduce

Go to https://nextjs-csp-report-only.vercel.app/csp, view the page source, and see that `nonce` is applied to (some) scripts.

Then go to https://nextjs-csp-report-only.vercel.app/csp-report-only, view the page source, and see that there are no scripts with `nonce` attribute.

**Note:** There is an existing issue #43743 where `nonce` attributes aren't being properly included. This issue is _not_ related to that. However, because of that issue, browsers will be blocking most of the runtime js on the page with the `content-security-policy` applied. This can be ignored for the purposes of this issue.

### Describe the Bug

Currently, `renderToHTMLOrFlight` in `app-render` pulls out a nonce value from a `content-security-policy` header for use in generating script tags:

https://github.com/vercel/next.js/blob/e7c9d3c051e6027cf187e0d70565417d6037e37c/packages/next/src/server/app-render/app-render.tsx#L1204

This is missing the ability to use a [`content-security-policy-report-only` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only). Many times this is a required step to enabling a CSP - by shipping a CSP with report-only and collecting reports before actually blocking resources.

### Expected Behavior

NextJS renders a site implementing a `content-security-policy-report-only` in the same way it does for sites using a `content-security-policy` header (ie reads and applies the nonce value).

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

All platforms

### PR DESCRIPTION
**Pull request by danieltott**
### Checklist:
- fixes #48966
- Tests added to `test/e2e/app-dir/app/index.test.ts`

### Description:
Currently, `renderToHTMLOrFlight` in `app-render` pulls out a nonce value from a `content-security-policy` header for use in generating script tags:

https://github.com/vercel/next.js/blob/e7c9d3c051e6027cf187e0d70565417d6037e37c/packages/next/src/server/app-render/app-render.tsx#L1204

This is missing the ability to use a [`content-security-policy-report-only` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only). Many times this is a required step to enabling a CSP - by shipping a CSP with report-only and collecting reports before actually blocking resources.

### Changes:
- Added ability to check `content-security-policy-report-only` header in `renderToHTMLOrFlight()`
- Added test to verify `nonce` is correctly applied when `content-security-policy-report-only` header exists

### CODE REVIEW

**Comment by danieltott** [comment]
@shuding if you have time to review this one, it would be very excellent to get this one merged along with #54059

**Comment by christianvuerings** [comment]
@timneutkens @ijjk @shuding @leerob could either one of you take a look at this PR? It blocks us from launching CSP on our website.

Also created an updated #59071 which fixes the merge conflicts in this PR

**Comment by ztanner** [comment]
Closed in favor of https://github.com/vercel/next.js/pull/59071 -- applied you as a co-author on the PR, thank you!

**Comment by danieltott** [comment]
Thanks @ztanner 🙌

**Pull request closed without merging**
