### PR TITLE
Update React 18 overview.md

### PR DESCRIPTION
**Pull request by AndrewVetovitz**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by huozhi** [comment]
If you're using react rc this step is not required cause nextjs is detecting react 18 and try to enable it for you. Did you have encountered problem with the latest canary?

**Comment by AndrewVetovitz** [comment]
next 12.1 - I did not use the canary. React 18 works with 12.1, for those not using the canary this is something worth adding to the docs because it does not work without this field. If this is not intended then 12.1 is not properly finding react 18, otherwise I think the docs should mention this outright.

**Comment by huozhi** [comment]
@AndrewVetovitz Yeah there was a bug #34500 that reactRoot is not properly enabled in 12.1.0 and fixed in the canary. Can you check if you're seeing the same error?

We still want to keep the doc simple to make configuration less and simple. You can definitely keet it as a workaround in your app. And once the patch is out you can still have the react 18 auto-detection with it.

**Comment by AndrewVetovitz** [comment]
I don't plan on checking out canary. I'll close this then since it will be fixed on the next minor release and just keep what I have.

**Pull request closed without merging**
