### PR TITLE
feat(cms-sanity): Add `NEXT_PUBLIC_` to env variables

### PR DESCRIPTION
**Pull request by Maybach91**
**Issue Description:**
>[Step 4](https://github.com/vercel/next.js/tree/canary/examples/cms-sanity#step-4-set-up-environment-variables) of the [readme](https://github.com/vercel/next.js/blob/canary/examples/cms-sanity/README.md) says, i have to create a env variable named `SANITY_PROJECT_ID` but to work locally with `yarn dev` it has to be `NEXT_PUBLIC_SANITY_PROJECT_ID` (as well?) 

**Tasks**
- [x] Added `NEXT_PUBLIC` variable to env and add it to the `README.md` [reference](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser)
- [x] Change example schema file to make it clear, thats only a example and its not needed for the deployment

**Issue:**
https://github.com/vercel/next.js/issues/14792

**@ Reviewers:**

- [ ] Please check, if referencing `SANITY_PROJECT_ID ` within the `.env.local` file is a good way to achieve this.
- [ ] Check, if the `process.env.NODE_ENV` variable a good way to check, if its run locally (since i don’t know how this is exactly handled on netlify/heroku environments etc.)

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| buildDuration | 13.8s | 12.9s | -942ms |
| nodeModulesSize | 66 MB | 66 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.226 | 2.283 | ⚠️ +0.06 |
| / avg req/sec | 1123.11 | 1095.04 | ⚠️ -28.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.509 | 1.526 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1656.93 | 1638.71 | ⚠️ -18.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| index.html gzip | 955 B | 955 B | ✓ |
| link.html gzip | 961 B | 961 B | ✓ |
| withRouter.html gzip | 948 B | 948 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.8s | ⚠️ +155ms |
| nodeModulesSize | 66 MB | 66 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | Maybach91/next.js feature/cms-sanity-env-variables | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ✓ |
| routerDirect.js | 908 kB | 908 kB | ✓ |
| withRouter.js | 908 kB | 908 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>
Commit: af4bda11e1e339a70a77b043b367a3c835d44c72

**Comment by Maybach91** [comment]
Why is the `Generate Pull Request Stats` failing now? :(

**Review by lfades — CHANGES_REQUESTED** [review]
This change shouldn't be required because `lib/sanity.js` is only being used in Node.js, there are no imports to it added to the browser build 🤔 

The change should be to rename the current project id key (`SANITY_PROJECT_ID`) instead of adding a new one, but I don't see why is that needed. Are you using the client directly in a React component?

**Comment by Maybach91** [comment]
> This change shouldn't be required because `lib/sanity.js` is only being used in Node.js, there are no imports to it added to the browser build 🤔
> 
> The change should be to rename the current project id key (`SANITY_PROJECT_ID`) instead of adding a new one, but I don't see why is that needed. Are you using the client directly in a React component?

Hej @lfades 
thanks for your changes. As mentioned in the Issue #14792  and in the commits, i cannot run the example locally via `yarn dev` since, i have no access to the env variable.
I’m not very familiar with sanity and nextjs yet, so thats the only fix i came up with to run the example locally. 
Do you have a different solution the the Issue #14792? Or is it working for you in general? I’m happy to learn from you. :)

Thanks for your time as well to review my PR. I appreciate it.

**Pull request closed without merging**
