### PR TITLE
Use https to prevent mixed content when served over https

### PR DESCRIPTION
**Pull request by brikou**

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Cool! Thanks 🙌 🙏

**Comment by timneutkens** [comment]
@arunoda can you merge this?

**Comment by brikou** [comment]
@timneutkens I don't have any clue why this PR is still yellow, is it blocking?

**Comment by arunoda** [comment]
I think something with appveyor. No issues.

**Comment by brikou** [comment]
Thank you @arunoda for being so reactive!

**Pull request merged**
