### PR TITLE
feat(with-apollo): Add `try {} catch {}` to `getStaticProps()`

### PR DESCRIPTION
**Pull request by ScottAgirs**
## About

If this is merged, it will add `try {} catch (error) {}` to the `examples/with-apollo`.

## The problem

When cloning/running the `with-apollo` example using any other GraphQL server than that which is provided, the example fails and it's very unclear why, especially, for someone who's not used to working with GraphQL/Apollo/Next.js.

To make it much more clearer and obvious as well as to more gracefully handle a failed network request, this PR adds the above mentioned and displays `ErrorMessage message={error.message} />` on the client.

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, when an error occurs in getStaticProps you typically don't want to catch the error so that the previous successful cache will be used instead of caching an error when leveraging revalidate. You also don't normally want to expose internal errors to the client like this.

Seems better to leave this example as is.

**Comment by yordis** [comment]
> You also don't normally want to expose internal errors to the client like this.

It depends, in that particular example, you are exposing GraphQL Errors that are meant to be in the client anyway, so such a statement absolutely applies, but context matters.

I haven't tested it (I was the original author of the improvement done to that example), but it seems a good addon.

I am not sure about the cache situation, and why you would fall back to the previous one I would like to understand bit more the reasoning there.

**Comment by ScottAgirs** [comment]
Hey folks, I would also love to learn more about the potential issues.
Or perhaps to discuss the potential pros/cons of adding it, or if it's an edge-case (dependant on a specific use-case), maybe a note in form of a comment could be an option?

Either way, thank you both for looking into this! 🙌🏼

**Review by ijjk — COMMENTED** [review]
I'm gonna close this per the above comment, feel free to open a fresh PR adding any helpful information to the readme for this example!

**Pull request closed without merging**
