### PR TITLE
Fix React channel env missing in custom server

### LINKED ISSUE #48948: Package subpath './server.edge' is not defined by "exports"
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.12
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/medonat/nextjs-revalidate-test

### To Reproduce

1. Clone the repository
2. npm install
3. npm run build
4. npm run start
5. Open localhost:3000
6. The cat fact shouldn't change onreload
7. Make a POST request: localhost:3000/api/revalidate
8. There should be an error 500 and no update if you reload localhost:3000 
9. Checkout branch 13.3.0 - and repeat the procedure to see that it worked in 13.3.0

### Describe the Bug

ISR does not work. Stale data is displayed after calling revalidate.

Error in console:
`TypeError: Cannot set properties of undefined (setting 'current')
    at ue (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:113:42)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:151:127
    at new Promise (<anonymous>)
    at Object.exports.renderToReadableStream (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:151:53)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\lib\trace\tracer.js:86:20)     
    at renderToInitialStream (C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\node-web-streams-helper.js:195:37)
    at C:\Users\daniel.hufler\Documents\code\revalidatetest\node_modules\next\dist\server\app-render\app-render.js:918:92`

### Expected Behavior

Revalidate should work like it did in previous versions (e.g. 13.3.0)

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

next start

### LINKED ISSUE #49169: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports"
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.5-canary.6
      eslint-config-next: 13.3.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue

sorry i can't upload because my project contains localhost database connections

### To Reproduce

On my own server.js file, every page of my application in development mode gets the same error, while on my own server.js file in localhost in production mode, I get this error on the pages under [slug]! When I run this with my server.js file I get this error. While it then worked on 13.3.1, it's now broken!

What am I missing in my server.js file or what should I do? I got this error in the last 13.3.2-canary.7 and it continued in later versions! Normally, I get this error when I refresh the pages under news-media/[slug] and other pages under news-media/[slug] while opening in production mode. I get this error on every page in development mode!"dev": "next dev",
"build": "next build",
While "start": "next start" was OK, as I mentioned above on my server.js file, after the "next 13.3.1" version, errors started on server.js both in development and production mode!

Here's my run npm commands for my own server.js:
     "httpsDevelopment": "node --max_old_space_size=8192 server/server.js",
     "httpsProduction": "next build && node server/server.js production",
     
My server.js file looks like this:

Screenshot_20

```
const { createServer } = require('https')
const { parse } = require('url')
const next = require('next')
const fs = require('fs')
const dev = process.argv[2] !== 'production'
const serverProduct = process.argv[3] === 'server' || undefined

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
const hostname = 'localhost'
const port = 443
// when using middleware hostname and port must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()
const httpsOptions = {
key: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.key' : 'server.key'}),
cert: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.pem' : 'server.crt'}),
}
app.prepare().then(() => {
createServer(httpsOptions, async (req, res) => {
try {
const parsedUrl = parse(req.url, true)
await handle(req, res, parsedUrl).then(null)
} catch (err) {
console.error('Error occurred handling', req.url, err)
res.statusCode = 500
res.end('internal server error')
}
})
.once('error', (err) => {
console.error(err)
process.exit(1)
})
.listen(port, () => {
console.log(> Ready on https://${hostname})
})
})
```

### Describe the Bug

What am I missing in my server.js file or what should I do? I got this error in the last 13.3.2-canary.7 and it continued in later versions! Normally, I get this error when I refresh the pages under news-media/[slug] and other pages under news-media/[slug] while opening in production mode. I get this error on every page in development mode!"dev": "next dev",
"build": "next build",
While "start": "next start" was OK, as I mentioned above on my server.js file, after the "next 13.3.1" version, errors started on server.js both in development and production mode!

While in development:
dev1
dev2

While in production:
prod1
prod2

### Expected Behavior

I expect it to run smoothly on my own server.js file, both in development and production mode. I have 2 similar tickets closed. But the problem persists in a similar way!

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

on my localhost with the command "next build && node server/server.js production". or "node --max_old_space_size=8192 server/server.js"

<sub>[NEXT-1413](https://linear.app/vercel/issue/NEXT-1413/error-[err-package-path-not-exported]-package-subpath-serveredge-is)</sub>

### PR DESCRIPTION
**Pull request by shuding**
Fixes #48948 ([repro](https://github.com/vercel/next.js/issues/48948#issuecomment-1533542001)). When running inside a custom server with app dir, we should always opt into the prebundled React with correct channels.

Thanks @karlhorky for help testing it!

Fixes #49169 too.

### CODE REVIEW

**Review by huozhi — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2a3b8b276a3b21fe79ecec6c748387ad00459adb

`pnpm testheadless test/e2e/app-dir/rsc-basic/rsc-basic.test.ts` 
- app dir - rsc basics > should use stable react for pages

<details>
<summary>Expand output</summary>

  ● app dir - rsc basics › should use stable react for pages

    expect(received).not.toInclude(expected)

    Expected string to not include:
      "-next-"
    Received:
      "18.3.0-next-6eadbe0c4-20230425"

      445 |     )?.[1]
      446 |
    > 447 |     expect(versionPages).not.toInclude('-next-')
          |                              ^
      448 |     expect(versionApp).toInclude('-next-')
      449 |   })
      450 |

      at Object.<anonymous> (e2e/app-dir/rsc-basic/rsc-basic.test.ts:447:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — DISMISSED** [review]

**Comment by sophiebits** [comment]
(You wrote "Fixes https://github.com/vercel/next.js/pull/49168" but that's a link to this PR.)

**Comment by shuding** [comment]
Thanks @sophiebits, fixed. My clipboard is too slow.

**Review by ijjk — DISMISSED** [review]

**Comment by shuding** [comment]
The failing test is strange, can't reproduce it locally with both dev and prod. Will take a look later.

**Comment by shuding** [comment]
@sophiebits I saw your comments

```
// Not actually sure why this is '2' in dev. Possibly something
// related to an update triggered by <HotReload>?
'navigate-https://example.vercel.sh/': isNextDev ? '2' : '1',
```

and it's now always `'1'` with this change so tests are failing (I haven't looked into it), and hopefully that's not a bad thing? Can I just update the test?

**Comment by sophiebits** [comment]
sure! seems fine

**Pull request merged**
