### PR TITLE
Docs: Sub bullet point rendering incorrectly as numbered list #61838

### PR DESCRIPTION
**Pull request by SaiGanesh21**
### What?
Resolves issue #61838
By adding one more space to each bullet point in authentication docs eradicated numbered list to bullet points.

### Why?
In the authentication docs under the Authorization section, there is a numbered list where each item should have bullet points underneath. Oddly, it's rendered as more numbers in the list but, shaded to be darker.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f763ce33c3c5ed0e5c912259f6ce31aab610e777

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f763ce33c3c5ed0e5c912259f6ce31aab610e777

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f763ce33c3c5ed0e5c912259f6ce31aab610e777

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by SaiGanesh21** [comment]
The build is failing. Can someone help me with it?

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by samcx** [comment]
Looks like another <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture> merged before this now!

**Pull request closed without merging**
