### PR TITLE
Docs: Note `$ACTION_` formData properties

### PR DESCRIPTION
**Pull request by karlhorky**
### What?

Make a note about the new `$ACTION_` properties in the `formData`

### Why?

Since `next@14.1.3`, some new `$ACTION_` properties have appeared in the `formData` in development mode, which cause validation errors when used with a strict validation with a library such as Zod or Yup:

```tsx
// Form Client Component
export default function Form() {
  const [state, formAction] = useFormState(action, {
    type: 'initial',
  });

  return (
    <form action={action}>
      {/* ... */}
    </form>
  );
}

// Server Action
export async function action(
  prevState: ServerActionReturnValue,
  formData: FormData,
): Promise<ServerActionReturnValue> {
  const validationResult = await schema.validate(
    Object.fromEntries(formData.entries()),
  );
```

The errors from Yup:

```
Errors:

- this field has unspecified keys: $ACTION_REF_1, $ACTION_1:0, $ACTION_1:1, $ACTION_KEY
```

The data in the `formData.entries()`

```js
{
  '$ACTION_REF_1': '',
  '$ACTION_1:0': '{"id":"59f475b...","bound":"$@1"}',
  '$ACTION_1:1': '[{"type":"initial"}]',
  '$ACTION_KEY': 'k187677481',
  // Real form data starts here:
  year: '2024',
```

### How?

Document additional properties with keys starting with the prefix `$ACTION_`

### Alternatives Considered

Maybe these `$ACTION_` properties are not intended to be exposed to users, and should be stripped before the `formData` reaches the Server Action.

### Related

The documentation was originally introduced in commit [`687239c`](https://github.com/vercel/next.js/pull/59080/commits/687239ce761bb8f2c4d8055b4f612dbd4c0d59bc), which was a part of this PR:

- https://github.com/vercel/next.js/pull/59080

cc @delbaoliveira

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5fd7a5f48216725ab87164d3a3d3c826c747e9d5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by karlhorky** [comment]
## Workaround

Instead of `Object.fromEntries(formData.entries())`, filter out the `formData` properties that start with `$ACTION_`:

```ts
Object.fromEntries(
  [...formData.entries()].filter(([key]) => !key.startsWith('$ACTION_')),
)
```

**Comment by samcx** [comment]
@karlhorky Taking a look! <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:">:frog-eyes:</picture>

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by karlhorky** [comment]
Thanks for the review and merge @samcx 🙌

**Pull request merged**
