### PR TITLE
Remove usage of `process.browser`

### PR DESCRIPTION
**Pull request by Timer**
This removes the use of a legacy `process.browser` field in favor of `typeof window`.

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

**Comment by StarpTech** [comment]
Hi, why is `process.browser` marked as legacy? From my experience it is heavily used in the community and communicated as good practice.

**Comment by timneutkens** [comment]
Because `typeof window` is more correct and applies the same optimization. `process.browser` is not a standard, it was added by webpack.

**Comment by jth0024** [comment]
Does `typeof window` actually allow for dead code elimination the way that `process.browser` does? I don't think I was ever able to `typeof window` to work.

**Comment by timneutkens** [comment]
Yep because of https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.ts#L456-L458

**Comment by StarpTech** [comment]
Thanks for clarification.

**Comment by kachkaev** [comment]
@Timer would you recommend Next.js plugins to use `process.browser` or `typeof window`, given that https://github.com/zeit/next.js/pull/8355 landed canary recently?

Asking for a friend 😅 https://github.com/isaachinman/next-i18next/pull/451#discussion_r313974882

**Comment by Timer** [comment]
`typeof window`, still. We don't have any immediate plans to remove `process.browser`, however.

**Comment by StarpTech** [comment]
@timneutkens according docs of https://webpack.js.org/plugins/define-plugin/

> Note that because the plugin does a direct text replacement, the value given to it must include actual quotes inside of the string itself. Typically, this is done either with alternate quotes, such as '"production"', or by using JSON.stringify('production').

This means it can happen `typeof <spaces>  window` will not be replaced?

**Comment by IanPhilips** [comment]
Using this code: ` if (typeof window === 'undefined') { let secret = "exposed" }`
Indeed the secret is "exposed" on the client side. 

Using `process.browser` however, doesn't not expose my secret on the client side and is only built on the server side. Should I file a new issue or am I using the wrong `typeof` code?

**Comment by felixmosh** [comment]
Pay attention, if you are writing next specific libs (like next-i18next), checking for `typeof window` won't work since it was implemented in `next-babel` plugin, which doesn't run on `node_modules`.

`process.browser` is works using `WebpackDefinePlugin` which is on the webpack level, therefore, it will work on `node_modules` as well.

**Pull request merged**
