### PR TITLE
Fix: Throw an error for empty array return in `generateStaticParams` with `output:export`

### LINKED ISSUE #57038: Error with `generateStaticParams` function despite its existence
### Link to the code that reproduces this issue

https://github.com/k-taro56/next-bug-report

### To Reproduce

Set up Next.js.
Add `output: 'export'` to `next.config.js` to enable static output.
Create a page that allows dynamic routing.
Create the `generateStaticParams` function and make it return an empty array.
Run `next build`.

Error Message:
`Error: Page "/[slug]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.`

### Current vs. Expected behavior

Current behavior:
An error is raised indicating that the generateStaticParams function does not exist.

Expected Behavior:
The generateStaticParams function should return an array with at least one element.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 18.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6-canary.7
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Static HTML Export (output: "export")

### Additional context

_No response_

<sub>[NEXT-1951](https://linear.app/vercel/issue/NEXT-1951/error-with-generatestaticparams-function-despite-its-existence)</sub>

### PR DESCRIPTION
**Pull request by k-taro56**
Fixes #57038

# What?
Added an error message when `generateStaticParams` returns an empty array with `output:export`.

# Why?
To provide developers with clear feedback when `generateStaticParams` is not used correctly.

# How?
Modified the condition checks around the use of `generateStaticParams` to include a check for an empty array and added a corresponding error message.

### CODE REVIEW

**Comment by dobrakmato** [comment]
Hey @timneutkens is there anything that needs to be done, before this can be merged? The error message is currently confusing. Also do you accept PRs implementing this functionality?

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 225709830f55fa58a3d68368cca36c14537e4fa7

`pnpm test test/integration/app-dir-export/test/dynamic-missing-gsp-dev.test.ts` 
-  > should error when generateStaticParams returns an empty array

<details>
<summary>Expand output</summary>

  ● should error when generateStaticParams returns an empty array

    expect(received).toContain(expected) // indexOf

    Expected substring: "Page \"/another/[slug]/page\"'s \"generateStaticParams()\" returned an empty array, which is not allowed with \"output: export\" config."
    Received string:    " 1 of 1 unhandled error
    Server Error·
    Error: Page \"/another/[slug]/page\" is missing param \"/another/first\" in \"generateStaticParams()\", which is required with \"output: export\" config.·
    This error happened while generating the page. Any console logs will be displayed in the terminal window."

      160 |         const browser = await webdriver(port, url)
      161 |         expect(await hasRedbox(browser, true)).toBe(true)
    > 162 |         expect(await getRedboxHeader(browser)).toContain(expectedErrMsg)
          |                                                ^
      163 |       } else {
      164 |         await check(() => result.stderr, /error/i)
      165 |       }

      at toContain (integration/app-dir-export/test/utils.ts:162:48)
      at Object.<anonymous> (integration/app-dir-export/test/dynamic-missing-gsp-dev.test.ts:28:3)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| buildDuration | 14s | 14s | N/A |
| buildDurationCached | 7.8s | 6.8s | N/A |
| nodeModulesSize | 202 MB | 202 MB | ⚠️ +3.46 kB |
| nextStartRea..uration (ms) | 436ms | 445ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.3 kB | 28.4 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| index.html gzip | 527 B | 527 B | ✓ |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 523 B | 521 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.8 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 624 B | ✓ |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.7 kB | 2.7 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | k-taro56/next.js fix-empty-gsp-return | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

</details>
Commit: 225709830f55fa58a3d68368cca36c14537e4fa7

**Review by styfle — APPROVED** [review]
Thanks!

I pushed a change to fix it in `next dev` too

**Comment by barroudjo** [comment]
I think it's not a good idea to throw an error when `generateStaticParams` returns an empty array with `output: export`, maybe a warning, but it shouldn't crash.
For example when working with a CMS with a preview mode, we want to be able to preview the page in SSR, and build the site  with `output: export` when that same page `generateStaticParams` returns an empty array (because the documents accessed in the page are not published yet, but are available in the preview mode).

**Comment by styfle** [comment]
@barroudjo Good point, the existing behavior doesn't account for dynamic data from a CMS.

I'll revert in PR #60831.

Instead of erroring, we should warn (and only in dev mode). Anyone want to create a new PR?

**Pull request merged**
