### PR TITLE
chore: upgrade PostCSS dependencies

### PR DESCRIPTION
**Pull request by balazsorban44**
Fixes #34336

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.4s | ⚠️ +145ms |
| buildDurationCached | 6.3s | 6.3s | ⚠️ +4ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +50.9 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.272 | 3.305 | ⚠️ +0.03 |
| / avg req/sec | 764.01 | 756.48 | ⚠️ -7.53 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.434 | 1.427 | -0.01 |
| /error-in-render avg req/sec | 1743.47 | 1751.71 | +8.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 5.01 kB | 5.01 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| buildDuration | 19.8s | 20.4s | ⚠️ +580ms |
| buildDurationCached | 6.3s | 6.2s | -84ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +50.9 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.423 | 3.334 | -0.09 |
| / avg req/sec | 730.36 | 749.87 | +19.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.513 | 1.584 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1652.63 | 1578.31 | ⚠️ -74.32 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.1 kB | 42.1 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 0c083484f7f4dffef1528b3fc8ca812f8b0b509d

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 0c083484f7f4dffef1528b3fc8ca812f8b0b509d

`yarn testheadless test/integration/typescript/test/index.test.js` 
- TypeScript Features > should build the app
- TypeScript Features > default behavior > should render the page
- TypeScript Features > default behavior > should render the cookies page
- TypeScript Features > default behavior > should render the generics page
- TypeScript Features > default behavior > should render the angle bracket type assertions page
- TypeScript Features > default behavior > should resolve files in correct order
- TypeScript Features > default behavior > should respond to sync API route correctly
- TypeScript Features > default behavior > should respond to async API route correctly
- TypeScript Features > default behavior > should not fail to render when an inactive page has an error
- TypeScript Features > should compile with different types > should compile async getInitialProps for _error
- TypeScript Features > should compile with different types > should compile sync getStaticPaths & getStaticProps

<details>
<summary>Expand output</summary>

  ● TypeScript Features › default behavior › should render the page

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      39 |     afterAll(() => killApp(app))
      40 |
    > 41 |     it('should render the page', async () => {
         |     ^
      42 |       const $ = await get$('/hello')
      43 |       expect($('body').text()).toMatch(/Hello World/)
      44 |       expect($('body').text()).toMatch(/1000000000000/)

      at integration/typescript/test/index.test.js:41:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should render the cookies page

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      45 |     })
      46 |
    > 47 |     it('should render the cookies page', async () => {
         |     ^
      48 |       const $ = await get$('/ssr/cookies')
      49 |       expect($('#cookies').text()).toBe('{}')
      50 |     })

      at integration/typescript/test/index.test.js:47:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should render the generics page

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      50 |     })
      51 |
    > 52 |     it('should render the generics page', async () => {
         |     ^
      53 |       const $ = await get$('/generics')
      54 |       expect($('#value').text()).toBe('Hello World from Generic')
      55 |     })

      at integration/typescript/test/index.test.js:52:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should render the angle bracket type assertions page

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      55 |     })
      56 |
    > 57 |     it('should render the angle bracket type assertions page', async () => {
         |     ^
      58 |       const $ = await get$('/angle-bracket-type-assertions')
      59 |       expect($('#value').text()).toBe('test')
      60 |     })

      at integration/typescript/test/index.test.js:57:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should resolve files in correct order

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      60 |     })
      61 |
    > 62 |     it('should resolve files in correct order', async () => {
         |     ^
      63 |       const $ = await get$('/hello')
      64 |       expect($('#imported-value').text()).toBe('OK')
      65 |     })

      at integration/typescript/test/index.test.js:62:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should respond to sync API route correctly

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      70 |     })
      71 |
    > 72 |     it('should respond to sync API route correctly', async () => {
         |     ^
      73 |       const data = JSON.parse(await renderViaHTTP(appPort, '/api/sync'))
      74 |       expect(data).toEqual({ code: 'ok' })
      75 |     })

      at integration/typescript/test/index.test.js:72:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should respond to async API route correctly

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      75 |     })
      76 |
    > 77 |     it('should respond to async API route correctly', async () => {
         |     ^
      78 |       const data = JSON.parse(await renderViaHTTP(appPort, '/api/async'))
      79 |       expect(data).toEqual({ code: 'ok' })
      80 |     })

      at integration/typescript/test/index.test.js:77:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › default behavior › should not fail to render when an inactive page has an error

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      80 |     })
      81 |
    > 82 |     it('should not fail to render when an inactive page has an error', async () => {
         |     ^
      83 |       await killApp(app)
      84 |       let evilFile = join(appDir, 'pages', 'evil.tsx')
      85 |       try {

      at integration/typescript/test/index.test.js:82:5
      at integration/typescript/test/index.test.js:30:3
      at Object.<anonymous> (integration/typescript/test/index.test.js:29:1)

  ● TypeScript Features › should build the app

    expect(received).toMatch(expected)

    Expected pattern: /Compiled successfully/
    Received string:  "info  - Checking validity of types...
    info  - Creating an optimized production build...
    info  - Using locally built binary of @next/swc
    "

      105 |   it('should build the app', async () => {
      106 |     const output = await nextBuild(appDir, [], { stdout: true })
    > 107 |     expect(output.stdout).toMatch(/Compiled successfully/)
          |                           ^
      108 |     expect(output.code).toBe(0)
      109 |   })
      110 |

      at Object.<anonymous> (integration/typescript/test/index.test.js:107:27)

  ● TypeScript Features › should compile with different types › should compile async getInitialProps for _error

    expect(received).toMatch(expected)

    Expected pattern: /Compiled successfully/
    Received string:  "info  - Checking validity of types...
    info  - Creating an optimized production build...
    info  - Using locally built binary of @next/swc
    "

      120 |         errorPage.replace('static ', 'static async ')
      121 |         const output = await nextBuild(appDir, [], { stdout: true })
    > 122 |         expect(output.stdout).toMatch(/Compiled successfully/)
          |                               ^
      123 |       } finally {
      124 |         errorPage.restore()
      125 |       }

      at Object.<anonymous> (integration/typescript/test/index.test.js:122:31)

  ● TypeScript Features › should compile with different types › should compile sync getStaticPaths & getStaticProps

    expect(received).toMatch(expected)

    Expected pattern: /Compiled successfully/
    Received string:  "info  - Checking validity of types...
    info  - Creating an optimized production build...
    info  - Using locally built binary of @next/swc
    "

      131 |         page.replace(/async \(/g, '(')
      132 |         const output = await nextBuild(appDir, [], { stdout: true })
    > 133 |         expect(output.stdout).toMatch(/Compiled successfully/)
          |                               ^
      134 |       } finally {
      135 |         page.restore()
      136 |       }

      at Object.<anonymous> (integration/typescript/test/index.test.js:133:31)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 37763c6ed1e1f23078c6bb4633718d03dc9f710c

`yarn testheadless test/integration/css-minify/test/index.test.js` 
- css-minify > should minify correctly by removing whitespace

<details>
<summary>Expand output</summary>

  ● css-minify › should minify correctly by removing whitespace

    command failed with code 1
    info  - Checking validity of types...
    warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
    info  - Creating an optimized production build...
    Failed to compile.

    ./styles/global.css.webpack[javascript/auto]!=!../../../packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!../../../packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/global.css
    Error: Cannot find module 'caniuse-lite/data/features/css-file-selector-button'
    Require stack:
    - /home/runner/work/next.js/next.js/packages/next/dist/compiled/postcss-preset-env/index.cjs
    - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/plugins.js
    - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/index.js
    - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/index.js
    - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack-config.js
    - /home/runner/work/next.js/next.js/packages/next/dist/build/index.js
    - /home/runner/work/next.js/next.js/packages/next/dist/cli/next-build.js
    - /home/runner/work/next.js/next.js/packages/next/dist/bin/next

      181 |     const hookResolved = hookPropertyMap.get(request);
      182 |     if (hookResolved) request = hookResolved;
    > 183 |     return resolveFilename.call(mod, request, parent, isMain, options);
          |                            ^
      184 | };
      185 |
      186 | //# sourceMappingURL=require-hook.js.map

      at Function.mod._resolveFilename (../packages/next/dist/build/webpack/require-hook.js:183:28)
      at Object.2416 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:10:74889)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.989 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:147625)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.6867 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:154201)
      Import trace for requested module:
      ./styles/global.css
      ./pages/_app.js
      ./styles/global.css
      Error: Cannot find module 'caniuse-lite/data/features/css-file-selector-button'
      Require stack:
      - /home/runner/work/next.js/next.js/packages/next/dist/compiled/postcss-preset-env/index.cjs
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/plugins.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack-config.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/cli/next-build.js
      - /home/runner/work/next.js/next.js/packages/next/dist/bin/next
      at Function.mod._resolveFilename (../packages/next/dist/build/webpack/require-hook.js:183:28)
      at Object.2416 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:10:74889)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.989 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:147625)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.6867 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:154201)
      at tryRunOrWebpackError (../packages/next/dist/compiled/webpack/bundle5.js:41703:9)
      at __webpack_require_module__ (../packages/next/dist/compiled/webpack/bundle5.js:27320:12)
      at __nested_webpack_require_152290__ (../packages/next/dist/compiled/webpack/bundle5.js:27277:18)
      at ../packages/next/dist/compiled/webpack/bundle5.js:27348:20
      at symbolIterator (../packages/next/dist/compiled/neo-async/async.js:1:14443)
      at done (../packages/next/dist/compiled/neo-async/async.js:1:14823)
      at Hook.eval [as callAsync] (eval at create (../packages/next/dist/compiled/webpack/bundle5.js:140117:10), <anonymous>:15:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (../packages/next/dist/compiled/webpack/bundle5.js:139919:14)
      at ../packages/next/dist/compiled/webpack/bundle5.js:27255:43
      at symbolIterator (../packages/next/dist/compiled/neo-async/async.js:1:14401)
      -- inner error --
      Error: Cannot find module 'caniuse-lite/data/features/css-file-selector-button'
      Require stack:
      - /home/runner/work/next.js/next.js/packages/next/dist/compiled/postcss-preset-env/index.cjs
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/plugins.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/blocks/css/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/config/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/webpack-config.js
      - /home/runner/work/next.js/next.js/packages/next/dist/build/index.js
      - /home/runner/work/next.js/next.js/packages/next/dist/cli/next-build.js
      - /home/runner/work/next.js/next.js/packages/next/dist/bin/next
      at Function.mod._resolveFilename (../packages/next/dist/build/webpack/require-hook.js:183:28)
      at Object.2416 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:10:74889)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.989 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:147625)
      at __nccwpck_require__ (../packages/next/dist/compiled/postcss-preset-env/index.cjs:38:92408)
      at Object.6867 (../packages/next/dist/compiled/postcss-preset-env/index.cjs:2:154201)
      at Object.<anonymous> (../packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/home/runner/work/next.js/next.js/packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/home/runner/work/next.js/next.js/test/integration/css-minify/styles/global.css:1:7)
      at ../packages/next/dist/compiled/webpack/bundle5.js:90178:11
      at Hook.eval [as call] (eval at create (../packages/next/dist/compiled/webpack/bundle5.js:140103:10), <anonymous>:7:1)
      at Hook.CALL_DELEGATE [as _call] (../packages/next/dist/compiled/webpack/bundle5.js:139915:14)
      at ../packages/next/dist/compiled/webpack/bundle5.js:27322:39
      at tryRunOrWebpackError (../packages/next/dist/compiled/webpack/bundle5.js:41698:7)
      at __webpack_require_module__ (../packages/next/dist/compiled/webpack/bundle5.js:27320:12)
      at __nested_webpack_require_152290__ (../packages/next/dist/compiled/webpack/bundle5.js:27277:18)
      at ../packages/next/dist/compiled/webpack/bundle5.js:27348:20
      at symbolIterator (../packages/next/dist/compiled/neo-async/async.js:1:14443)
      Generated code for /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/home/runner/work/next.js/next.js/packages/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/home/runner/work/next.js/next.js/test/integration/css-minify/styles/global.css
      Import trace for requested module:
      ./pages/_app.js
      > Build failed because of webpack errors
      at ChildProcess.<anonymous> (lib/next-test-utils.js:201:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      379 | // Kill a launched app
      380 | export async function killApp(instance) {
    > 381 |   await killProcess(instance.pid)
          |                              ^
      382 | }
      383 |
      384 | export async function startApp(app) {

      at Object.killApp (lib/next-test-utils.js:381:30)
      at integration/css-minify/test/index.test.js:37:18

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| buildDuration | 20.9s | 20.7s | -185ms |
| buildDurationCached | 8s | 7.9s | -99ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +50.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.501 | 4.564 | ⚠️ +0.06 |
| / avg req/sec | 555.45 | 547.73 | ⚠️ -7.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.195 | 2.149 | -0.05 |
| /error-in-render avg req/sec | 1138.89 | 1163.36 | +24.47 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 5.01 kB | 5.01 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| buildDuration | 25.2s | 26.1s | ⚠️ +857ms |
| buildDurationCached | 8s | 7.8s | -273ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +50.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.643 | 4.684 | ⚠️ +0.04 |
| / avg req/sec | 538.39 | 533.75 | ⚠️ -4.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.307 | 2.296 | -0.01 |
| /error-in-render avg req/sec | 1083.52 | 1088.97 | +5.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.1 kB | 42.1 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js chore/upgrade-postcss-dependencies | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 37763c6ed1e1f23078c6bb4633718d03dc9f710c

**Comment by szympajka** [comment]
Hey all! Thank you for your great work put into creating Next.js!

Looks like this PR is in progress, what is the estimated time for this hitting prod release? I do experience this issue related to `autoprefixer` - https://github.com/postcss/autoprefixer/issues/1391

It was fixed in the next major version of `postcss-preset-env` - https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/CHANGELOG.md#700-november-16-2021, so this PR will fix my issue.

Until that time, I need to apply `postcss-preset-env@7` myself :)

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
