### PR TITLE
Make styled-jsx configurable

### PR DESCRIPTION
**Pull request by timneutkens**
For the upcoming plugins in v2 zeit/styled-jsx#291. Continuation of #2991

### CODE REVIEW

**Comment by giuseppeg** [comment]
@timneutkens ok I looked into this and unfortunately we need to resolve the plugins paths:

```js
function styledJsxOptions(opts) {
  if (!opts) return {}
  if (!Array.isArray(opts.plugins)) return opts
  opts.plugins = opts.plugins.map(plugin => {
    if (Array.isArray(plugin)) {
      return [
        require.resolve(plugin[0]),
        plugin[1]
      ]
    }
    return require.resolve(plugin)
  })
  return opts
}
```

```js
[require.resolve('styled-jsx/babel'), styledJsxOptions(opts['styled-jsx'])]
```

**Comment by timneutkens** [comment]
Okay, lets move it to next.config.js then 👍

**Comment by giuseppeg** [comment]
@timneutkens your call, my example would work in `server/build/babel/preset.js`

**Comment by timneutkens** [comment]
@giuseppeg oh right, can simply use that and allow the user to use pretty names 😄 👍

**Comment by giuseppeg** [comment]
@timneutkens if you want I can add the changes to this branch

**Comment by timneutkens** [comment]
@giuseppeg no worries I'll add them 👍

**Review by giuseppeg — APPROVED** [review]

**Pull request merged**
