### PR TITLE
Print error when `images.loader` is assigned but `images.path` is not

### LINKED ISSUE #29744: Configuring `next.config.js` with images.loader should error if missing images.path
When a user configures `next.config.js` with the `images.loader` prop such as `cloudinary`, next should error if the `images.path` property is missing.

The error message should guide the user to the correct value.

https://nextjs.org/docs/api-reference/next/image#loader-configuration

### PR DESCRIPTION
**Pull request by styfle**
Fixes #29744

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

**Comment by dbismut** [comment]
Hello, I'm not sure why this has been merged. I'm using the CMS prismic.io that uses `imgix` which returns absolute imgix image url. I used to have `path=""` in `next.config.js` and it used to work fine, but now with next 12 I get an error. I believe this should be reverted and left to userland.

EDIT: related discussions.

- https://github.com/vercel/next.js/discussions/18390#discussioncomment-115313
- https://stackoverflow.com/questions/68557303/how-can-i-configure-an-external-image-loader-in-next-js-properly

**Comment by styfle** [comment]
@dbismut If you're using absolute URLs then you shouldn't need to use `loader=imgix`. If you were using an empty path then it wasn't using the imgix loader at all, that was a bug.

Some possible solutions:

- You can use default loader with absolute URLs, no configuration needed.
- You can use `loader=custom` and implement the `loader` prop to write your own loader
- You can use `unoptimized` prop if you want to use the absolute URL as-is

**Comment by dbismut** [comment]
@styfle thanks for the answer. However it looks like this solution (ie empty path) worked in at least two related questions.

Here's the srcset generated by the imgix loader with empty path.

```bash
# src
https://images.prismic.io/flyaway/b32112c6-e150-40ba-bee8-fea1a841f2b1_DSC_1346_by_%40alyasmusic.jpg?auto=compress%2Cformat&fit=max&w=3840

# srcset
https://images.prismic.io/flyaway/b32112c6-e150-40ba-bee8-fea1a841f2b1_DSC_1346_by_%40alyasmusic.jpg?auto=compress%2Cformat&fit=max&w=256 256w
https://images.prismic.io/flyaway/b32112c6-e150-40ba-bee8-fea1a841f2b1_DSC_1346_by_%40alyasmusic.jpg?auto=compress%2Cformat&fit=max&w=384 384w
https://images.prismic.io/flyaway/b32112c6-e150-40ba-bee8-fea1a841f2b1_DSC_1346_by_%40alyasmusic.jpg?auto=compress%2Cformat&fit=max&w=640 640w
...
```

To me it looks perfectly legit, and well, it works.

Without the loader, here's one image url from srcset to avoid being too verbose:

```bash
http://localhost:3000/_next/image?url=https%3A%2F%2Fimages.prismic.io%2Fflyaway%2Fb32112c6-e150-40ba-bee8-fea1a841f2b1_DSC_1346_by_%2540alyasmusic.jpg%3Fauto%3Dcompress%2Cformat&w=640&q=75 640w
```

I'm not familiar with what this means although I guess that this is using Next Js own image transform engine, which I don't need.

Therefore I'd like to reiterate my request to leave this to userland, as this is fixing something that isn't broken as far as I'm concerned.

**Comment by styfle** [comment]
> to leave this to userland

That's actually then end goal here 👍 

Eventually, we plan to leave all loaders to userland via the `loader` prop and deprecate the `loader` config in next.config.js

Did you try any of the 3 solutions suggested above?

**Comment by dbismut** [comment]
Yes of course I could use a custom loader and pass it to *every* `Image` component. And that custom loader would be precisely the *same* imgix loader that is sitting inside Next Js source code, that I would need to copy paste. 

But what I really don't understand is why `path` needs to be mandatory in the first place, especially since it used to work before!

Why can't you revert that PR?

**Comment by styfle** [comment]
> are your saying that the built-in imgix loader is going to be removed eventually then

Yes because Next.js is currently shipping additionally client-side JS for several loaders, even if you aren't using them.

I think we can relax this error for now since these loaders aren't deprecated yet https://github.com/vercel/next.js/pull/30741

**Comment by dbismut** [comment]
Thanks a lot, much appreciated.

**Pull request merged**
