### PR TITLE
build: Update `swc_core` to `v0.102.0`

### PR DESCRIPTION
**Pull request by kdy1**
### What?

Update `swc_core`.

### Why?

This update is required to use the name mangler cache, which was recently implemented in SWC.

### How?

Closes PACK-3222

### CODE REVIEW

**Review by bgw — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: abe31a6613ce49b9859043c0f5b4d2f0f07cc687

`TURBOPACK=1 pnpm test test/integration/amp-export-validation/test/index.test.js` (turbopack)
- AMP Validation on Export > production mode > should have shown errors during build

<details>
<summary>Expand output</summary>

  ● AMP Validation on Export › production mode › should have shown errors during build

    expect(received).toMatch(expected)

    Expected pattern: /error.*The mandatory attribute 'height' is missing in tag 'amp-video'\./
    Received string:  "  ▲ Next.js 15.0.0-canary.133 (turbo)
      - Experiments (use with caution):
        · amp·
       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/7) ...
       Building (1/7)··
       Building (3/7)··
       Building (5/7)··
     ✓ Building (7/7)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/8) ...
       Generating static pages (2/8)··
    Failed to build /dog after 1 attempts.
       Generating static pages (4/8)··
       Generating static pages (6/8)··
     ⚠ Linting is disabled.·
    Error occurred prerendering page \"/dog\". Read more: https://nextjs.org/docs/messages/prerender-error·
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:106:13)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)·
      > Build error occurred
      Error: Export encountered an error on /dog, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      "
      at Object.toMatch (integration/amp-export-validation/test/index.test.js:28:29)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by kdy1** [comment]
@tonyabracadabra Did you patch the js code? This PR does not activate the minifier's mangle name cache.

**Comment by kdy1** [comment]
@tonyabracadabra It sounds like https://github.com/swc-project/swc/issues/9523

**Comment by kdy1** [comment]
I'll create an update PR once https://github.com/wooorm/mdxjs-rs/pull/53 is merged

**Pull request merged**
