### PR TITLE
Update edge-dynamic-code-evaluation.mdx

### PR DESCRIPTION
**Pull request by paul-vd**
Following the [`MiddlewareConfig`](https://github.com/vercel/next.js/blob/f09650b7b449caf8b22f367511e197034b209185/packages/next/src/build/analysis/get-page-static-info.ts#L43) typings, this is now named as `unstable_allowDynamicGlobs`

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 49aeae2388219dcde115ee630887a801db5997ab

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — CHANGES_REQUESTED** [review]
We still parse it as `unstable_allowDynamic ` not `unstable_allowDynamicGlobs`: https://github.com/vercel/next.js/blob/1e3a1cbaab2a6fc3e10ceba7c27d3172579af972/packages/next/src/build/analysis/get-page-static-info.ts#L404-L421

Our tests also use `unstable_allowDynamic` not `unstable_allowDynamicGlobs`: https://github.com/vercel/next.js/blob/1e710ab73ce6b6ee896535ef0962956aac2e9649/test/integration/edge-runtime-configurable-guards/test/index.test.js

Is the `MiddlewareConfig` you linked reachable from usercode or do we document that this is the type you should export your `config` as?

**Review by leerob — DISMISSED** [review]
Edit: nevermind

**Comment by jerome-quere** [comment]
> Is the MiddlewareConfig you linked reachable from usercode or do we document that this is the type you should export your config as?

Not documented but reachable from usercode

```
import { MiddlewareConfig, NextRequest, NextResponse } from 'next/server'
```

```
"next": "14.2.2",
```

**Comment by leerob** [comment]
@elartix That appears to be solved with https://github.com/vercel/next.js/pull/73732.

As mentioned above, the config option is still `unstable_allowDynamic` – we do not document the type referenced here, which is used internally in Next.js. If we do end up exposing this type in the documentation as something you should use, we can revisit the naming here.

**Pull request closed without merging**
