### PR TITLE
fix(docs): broken links

### PR DESCRIPTION
**Pull request by okisdev**
This PR fix those broken links when the docs was updated but related links still not be changed.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a648e5b0d825dd047622246881ba3b6a14e3bec0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by delbaoliveira** [comment]
Thank you @okisdev. 

The docs in the Next.js repo reflect the latest **canary** version where the file path was changed, hence the updated links. 

If you access the links from the **stable** version, it'll still take users to the old URL path, which is still valid for that version. And if you access the links from the **canary**, it'll take users to the new URL path. 

It's a little confusing, but what this means is that we don't have to change back the links as they are working as expected. 

Have you come across any 404s while navigating the docs?

**Comment by okisdev** [comment]
Hi @delbaoliveira. Thanks for reaching back.

Let's do a simple validation for the diff in this PR.

CleanShot 2024-12-03 at 20 17 14@2x

file `errors/built-in-css-disabled.mdx` points to https://nextjs.org/docs/messages/built-in-css-disabled, but if you go to this page at **Useful Links** Section, the **Custom webpack config docs** will redirect to a 404 pages.

CleanShot 2024-12-03 at 20 19 34@2x

Also, if you go to

- https://nextjs.org/docs/messages/deprecated-target-config
- https://nextjs.org/docs/messages/empty-configuration
- ...

They are facing the same issue.

Can you reproduce this from your perspective?

**Comment by delbaoliveira** [comment]
I see, thank you. 

The error messages are outside docs "versioning" which would explain why the links are 404. 

Since we can't change the links as this would break the version of the canary docs ([link validation is failing for his PR](https://github.com/vercel/next.js/actions/runs/12131299255/job/33823185067?pr=73400)), a quick fix would be to have temporary redirects in place, but this can quickly get messy as pages move around.

A better, long-term solution would be to improve the flow between canary and stable docs. I've talked to my team about it, and we have a solution. 

I'll be closing this PR and work on that in the next few days, but appreciate you raising this as it helped us talk through it 🙏🏼

**Pull request closed without merging**
