### PR TITLE
(Example) Update `with-opentelemetry` example.

### PR DESCRIPTION
**Pull request by vinaykulk621**
Updated with new `Metadata` API.

Here in this example there is `legacy.tsx` in `/pages`  folder should i remove it or retain it??
Also in `/pages/legacy.tsx` we have defined `/preact-stars` route but we don't have the corresponding file. 
I have remove `/preact-stars` from `/app/page.tsx` as there is no `/app/preact-stars/page.tsx` in this example.
And `/shared/fetch-github-stars.ts` is fetching only `next.js` stars.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 954f0d8ebc1149eea01f121f3e7c1eb7039b20fc

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — DISMISSED** [review]

**Review by leerob — DISMISSED** [review]

**Review by leerob — APPROVED** [review]

**Comment by vinaykulk621** [comment]
> Updated with new `Metadata` API.
> 
> Here in this example there is `legacy.tsx` in `/pages` folder should i remove it or retain it?? Also in `/pages/legacy.tsx` we have defined `/preact-stars` route but we don't have the corresponding file. I have remove `/preact-stars` from `/app/page.tsx` as there is no `/app/preact-stars/page.tsx` in this example. And `/shared/fetch-github-stars.ts` is fetching only `next.js` stars.

Any update on this??

**Comment by leerob** [comment]
It's fine to keep that route, we can get this through as-is 👍

**Review by leerob — DISMISSED** [review]

**Comment by leerob** [comment]
Looks like lint in failing, could you fix please?

**Review by leerob — APPROVED** [review]

**Pull request merged**
