### PR TITLE
report pageview in reportWebVitals in Google Tag Manager example

### LINKED ISSUE #21037: with-google-tag-manager: `pageview` event doesn't fire on initial page load
**What example does this report relate to?**

with-google-tag-manager

**What version of Next.js are you using?**

10.0.3

**What version of Node.js are you using?**

10.0.3

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

`pageview` event doesn't fire on initial page load, only routchange

**Expected Behavior**

to be able set up a single tag in GTM to use the "pageview" dataLayer event, however the `routeChangeComplete` only fires on subsequent page views.

**To Reproduce**

- start with-google-tag-manager up the example
- add `console.log("pageview");` inside the exported page view function
- note in the console that it only appears on subsequent pageviews

We're going with a slight adaptation from the example, using a hook instead of a regular component. Either way, I think the addition of a call to `gtm.pageview` on initialPage would be a nice addition to `with-google-tag-manager`.

```tsx
export default function useGTM() {
  const router = useRouter();

  React.useEffect(() => {
    const handleRouteChange = (url: string) => {
      // Wrap it in a rAF to ensure the correct data is sent
      // https://github.com/zeit/next.js/issues/6025
      requestAnimationFrame(() => gtm.pageview(url));
    }
    router.events.on('routeChangeComplete', handleRouteChange);
    return () => router.events.off('routeChangeComplete', handleRouteChange);
  }, [router.events]);
}

```

### PR DESCRIPTION
**Pull request by balazsorban44**
From what I understand about it, I think the `reportWebVitals` is the best place to report to analytics services since it will be called when the main thread is idle.

It is also the recommended place, judging from the documentation https://nextjs.org/docs/advanced-features/measuring-performance#sending-results-to-analytics

Therefore I moved the `pageview` call from a `React.useEffect()` to inside `reportWebVitals`.

The `pageview` function is called in two cases (but not twice at the same time):

1. when reporting the `Next.js-hydration` metric: This will report the pageview right after page hydration. This occurs when the user visits the site for the first time, eg. coming from another page, or clicking on a link from their browser's bookmarks.

2. when reporting `Next.js-route-change-to-render` metric: This will report the pageview right after a client-side page transition has happened (eg. the route has changed).

These two metrics will not cause double reporting, since they don't occur together.

The reasoning behind this PR is that we tried using the `useEffect` way (current solution) first, but noticed that while dynamic catch-all routes (like `[...slug].js`) will fire the `routeChangeComplete` event both on the first render (after hydration) and client-side transition, static pages only fired the `routeChangeComplete` event on client-side transition, and not on hydration.

In any case, the `reportWebVitals` just seemed a better place for this anyway. I am curious about your feedback!

Fixes #21037

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 55365268264ca1e40733248ede4da9d3c91ccb16

**test/integration/script-loader/test/index.test.js** 
- Script Loader > priority lazy

<details>
<summary>Expand output</summary>

  ● Script Loader › priority lazy

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      66 |   })
      67 | 
    > 68 |   it('priority lazy', async () => {
         |   ^
      69 |     let browser
      70 |     try {
      71 |       browser = await webdriver(appPort, '/page3')

      at integration/script-loader/test/index.test.js:68:3
      at Object.<anonymous> (integration/script-loader/test/index.test.js:21:1)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5fff814ca1e7f78b50535a55d6f99bd842c4e049

**test/integration/script-loader/test/index.test.js** 
- Script Loader > priority lazy

<details>
<summary>Expand output</summary>

  ● Script Loader › priority lazy

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      66 |   })
      67 | 
    > 68 |   it('priority lazy', async () => {
         |   ^
      69 |     let browser
      70 |     try {
      71 |       browser = await webdriver(appPort, '/page3')

      at integration/script-loader/test/index.test.js:68:3
      at Object.<anonymous> (integration/script-loader/test/index.test.js:21:1)

</details>

**Comment by TommySorensen** [comment]
@balazsorban44 The issue with the `routeChangeComplete` can be avoiding like this
```js
if (!router.asPath.includes('?')) {
  logPageView()
}
```
Its the same method used in the react-ga example
https://github.com/vercel/next.js/blob/27691d58827e9c0df158c29dbd986d97e0268320/examples/with-react-ga/pages/_app.js

**Comment by balazsorban44** [comment]
@TommySorensen as said, it still feels much cleaner to do all the analytics in one single location (reportWebVitas) as I assume it is invoked in the most optimal place, I don't need any modifications on the App component, it is less code, and you method doesn't seem to work for us even if we don't have a `? ` in the page urls. So I'm still curious about what the Next.js have to say about this PR, but thanks anyway! 🙂

**Comment by dsbrianwebster** [comment]
I'm in agreement @balazsorban44. Waiting on Next team feedback too.

**Comment by balazsorban44** [comment]
@TommySorensen by the way, do you know if there is any advantage of the [`with-react-ga`](https://github.com/vercel/next.js/blob/canary/examples/with-react-ga) example over [`with-google-analytics`](https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics)?

Seems like they achieve the same thing, but `with-google-analytics` does that without any dependencies.

(I would still update `with-google-analytics` as well if this PR gets merged.)

**Comment by codyburleson** [comment]
For me, this approach works only when you enter a URL directly into the browser and press ENTER. After subsequent navigations within the app, nothing is registered in Google Analytics. I can use use console.log to show that the different cases are being fired within the reportWebVitals() method. However, if you watch the Google Analytics Realtime > Overview, you will not see the page is being viewed. Please throw me a bone if you know what I am doing wrong, but I'm just concerned you may not have tested this all the way to the Google Analytics interface. It's still, for me, just working the same as the old example code was: it tracks on an initial load when you hit ENTER after a URL in the address bar, but not on subsequent loads caused by navigating in the app. YES, the change is registered in reportWebVitals(), but it's not making it to Google Analytics.

**Comment by balazsorban44** [comment]
Interesting, might be something how you send analytics from GTM to GA. I believe we used a custom page view

**Comment by ddzieduch** [comment]
Have you looked at this pull request? [#27674](https://github.com/vercel/next.js/pull/27674)
@smakosh has switched Google Analytics example to a script component.

**Comment by leerob** [comment]
As ^ mentioned, that is now the most up to date and recommended way 😄 Closing this in favor of that PR.

**Comment by balazsorban44** [comment]
I am not sure that this PR had a crash with #27674. That only changed the way how the script is initialized, not how the pageviews were actually reported @leerob

**Comment by leerob** [comment]
Ahh, gotcha. My bad! Reopening.

**Comment by KnowIsPow** [comment]
@balazsorban44 have you modified your approach since this pull request? The asPath method that @TommySorensen mentioned currently used within the Google Analytics example does not account for the necessity of landing pages with query parameters. I'm thinking of paid search (e.g UTM parameters) as the most common example, and also product search landing pages that canonicalize on query parameters (e.g ?color=x ).

Your approach seems to work, however, it also now conflicts with the latest next/script initialization approach recommended in the GTM example. The dataLayer object for GTM isn't initialized for the reportWebVitals() "Next.js-hydration" case.

Would love to find a broader resolution to incorporating GA and GTM into Next.JS effectively.

**Comment by TommySorensen** [comment]
@KnowIsPow If you want to delay your code until the query param is ready on static pages you can use the `isReady` prop on `useRouter()`. Maybe you can try something with that?
Documentation: https://nextjs.org/docs/api-reference/next/router#router-object

**Comment by balazsorban44** [comment]
I am not planning to work on this PR, so please feel free to open your own and reuse anything from this if useful. :+1:

**Pull request closed without merging**
