### PR TITLE
fix(next-typescript-plugin): allow call expression for server actions

### LINKED ISSUE #63743: typescript plugin regarding async actions not accurate
### Link to the code that reproduces this issue

https://github.com/juliusmarminge/next-ts-plugin-async-serveraction

### To Reproduce

Run `npm i`, then open `app/_action.ts`. See error: 
CleanShot 2024-03-27 at 00 42 11@2x

### Current vs. Expected behavior

The introduction of checking that actions are async functions seems to be quite inaccurate. As seen in the example above, both the exports are async functions, yet the TS plugin complains.

I'd expect both these exports to be valid. Afterall, they both do work runtime:

CleanShot 2024-03-27 at 00 41 45@2x

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.13.1
Relevant Packages:
  next: 14.2.0-canary.44 // Latest available version is detected (14.2.0-canary.44).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

TypeScript (plugin, built-in types)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The rule testing for this was introduced in `14.2.0-canary.43` by this PR https://github.com/vercel/next.js/pull/63667

### PR DESCRIPTION
**Pull request by devjiwonchoi**
cc @shuding

### Why?

The typescript plugin in #63667 does not target the call expression or assigned actions.

```ts
'use server'

function action() {
  return async function() {
    return 'foo'
  }
}

async function action2() {
  return 'foo'
}

export const callAction = action() // call expression
export const assignedAction = action2 // assigned
```

### Current

Screenshot 2024-03-27 at 2 29 04 PM

### Fixed

Screenshot 2024-03-27 at 2 29 41 PM

x-ref: https://github.com/vercel/next.js/pull/63667
Closes #63743

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a602ff7c74b308847048db080e35950773eaf379

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by shuding — APPROVED** [review]
Thanks!

**Comment by devjiwonchoi** [comment]
Thank you for reviewing!

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e78cc9223526d22906a4f876b4e792e4b9ac6839

`pnpm test test/integration/amphtml/test/index.test.js`
- AMP Usage > production mode > should have amp optimizer in trace
- AMP Usage > production mode > With AMP context > should render the normal page that uses the AMP hook
- AMP Usage > production mode > With AMP context > should render the AMP page that uses the AMP hook
- AMP Usage > production mode > With AMP context > should render nested normal page with AMP hook
- AMP Usage > production mode > With AMP context > should render nested AMP page with AMP hook
- AMP Usage > production mode > With basic AMP usage > should render the page as valid AMP
- AMP Usage > production mode > With basic AMP usage > should render the page without leaving render target
- AMP Usage > production mode > With basic AMP usage > should not output client pages for AMP only
- AMP Usage > production mode > With basic AMP usage > should not output client pages for AMP only with config exported after declaration
- AMP Usage > production mode > With basic AMP usage > should drop custom scripts
- AMP Usage > production mode > With basic AMP usage > should not drop custom amp scripts
- AMP Usage > production mode > With basic AMP usage > should optimize clean
- AMP Usage > production mode > With basic AMP usage > should auto import extensions
- AMP Usage > production mode > With basic usage > should render the page
- AMP Usage > production mode > canonical amphtml > should render link rel amphtml
- AMP Usage > production mode > canonical amphtml > should render amphtml from provided rel link
- AMP Usage > production mode > canonical amphtml > should render link rel amphtml with existing query
- AMP Usage > production mode > canonical amphtml > should render the AMP page that uses the AMP hook
- AMP Usage > production mode > canonical amphtml > should render a canonical regardless of amp-only status (explicit)
- AMP Usage > production mode > canonical amphtml > should not render amphtml link tag with no AMP page
- AMP Usage > production mode > canonical amphtml > should remove conflicting amp tags
- AMP Usage > production mode > canonical amphtml > should allow manually setting canonical
- AMP Usage > production mode > canonical amphtml > should allow manually setting amphtml rel
- AMP Usage > production mode > combined styles > should combine style tags
- AMP Usage > production mode > combined styles > should remove sourceMaps from styles

<details>
<summary>Expand output</summary>

  ● AMP Usage › production mode › should have amp optimizer in trace

    ENOENT: no such file or directory, open '/root/actions-runner/_work/next.js/next.js/test/integration/amphtml/.next/next-server.js.nft.json'

      56 |       it('should have amp optimizer in trace', async () => {
      57 |         const trace = JSON.parse(
    > 58 |           readFileSync(join(appDir, '.next/next-server.js.nft.json'), 'utf8')
         |                       ^
      59 |         )
      60 |         expect(
      61 |           trace.files.some((file) =>

      at Object.<anonymous> (integration/amphtml/test/index.test.js:58:23)

  ● AMP Usage › production mode › With basic usage › should render the page

    FetchError: request to http://localhost:36961/ failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should render the page as valid AMP

    FetchError: request to http://localhost:36961/?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should render the page without leaving render target

    FetchError: request to http://localhost:36961/special-chars failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should not output client pages for AMP only

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:36961/nav
    Call log:
      - navigating to "http://localhost:36961/nav", waiting until "load"

      274 |     opts?.beforePageLoad?.(page)
      275 |
    > 276 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      277 |   }
      278 |
      279 |   back(options): BrowserInterface {

      at BrowserInterface.goto (lib/browsers/playwright.ts:276:16)
      at webdriver (lib/next-webdriver.ts:129:3)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:96:27)

  ● AMP Usage › production mode › With basic AMP usage › should not output client pages for AMP only with config exported after declaration

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:36961/nav
    Call log:
      - navigating to "http://localhost:36961/nav", waiting until "load"

      274 |     opts?.beforePageLoad?.(page)
      275 |
    > 276 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      277 |   }
      278 |
      279 |   back(options): BrowserInterface {

      at BrowserInterface.goto (lib/browsers/playwright.ts:276:16)
      at webdriver (lib/next-webdriver.ts:129:3)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:105:27)

  ● AMP Usage › production mode › With basic AMP usage › should drop custom scripts

    FetchError: request to http://localhost:36961/custom-scripts failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should not drop custom amp scripts

    FetchError: request to http://localhost:36961/amp-script?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should optimize clean

    FetchError: request to http://localhost:36961/only-amp failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With basic AMP usage › should auto import extensions

    FetchError: request to http://localhost:36961/auto-import failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With AMP context › should render the normal page that uses the AMP hook

    FetchError: request to http://localhost:36961/use-amp-hook failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With AMP context › should render the AMP page that uses the AMP hook

    FetchError: request to http://localhost:36961/use-amp-hook?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With AMP context › should render nested normal page with AMP hook

    FetchError: request to http://localhost:36961/nested failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › With AMP context › should render nested AMP page with AMP hook

    FetchError: request to http://localhost:36961/nested?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should render link rel amphtml

    FetchError: request to http://localhost:36961/use-amp-hook failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should render amphtml from provided rel link

    FetchError: request to http://localhost:36961/use-amp-hook.amp failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should render link rel amphtml with existing query

    FetchError: request to http://localhost:36961/use-amp-hook?hello=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should render the AMP page that uses the AMP hook

    FetchError: request to http://localhost:36961/use-amp-hook?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should render a canonical regardless of amp-only status (explicit)

    FetchError: request to http://localhost:36961/only-amp failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should not render amphtml link tag with no AMP page

    FetchError: request to http://localhost:36961/normal failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should remove conflicting amp tags

    FetchError: request to http://localhost:36961/conflicting-tag?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should allow manually setting canonical

    FetchError: request to http://localhost:36961/manual-rels?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › canonical amphtml › should allow manually setting amphtml rel

    FetchError: request to http://localhost:36961/manual-rels failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › combined styles › should combine style tags

    FetchError: request to http://localhost:36961/styled?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● AMP Usage › production mode › combined styles › should remove sourceMaps from styles

    FetchError: request to http://localhost:36961/styled?amp=1 failed, reason: connect ECONNREFUSED 127.0.0.1:36961

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f0a315f124eca14d5f72dc49e047e1a7cab2cd96

`pnpm test-dev test/e2e/app-dir/metadata/metadata.test.ts` (PPR)
- app dir - metadata > react cache > should have same title and page value when navigating

<details>
<summary>Expand output</summary>

  ● app dir - metadata › react cache › should have same title and page value when navigating

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.6470844164215845"
    Received: "0.5692508773302181"

      1003 |         const obj = JSON.parse(title)
      1004 |         // Check `cache()`
    > 1005 |         expect(obj.val.toString()).toBe(value)
           |                                    ^
      1006 |         // Check `fetch()`
      1007 |         // TODO-APP: Investigate why fetch deduping doesn't apply but cache() does.
      1008 |         if (!isNextDev) {

      at Object.toBe (e2e/app-dir/metadata/metadata.test.ts:1005:36)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +193ms |
| buildDurationCached | 8.7s | 6.5s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +728 B |
| nextStartRea..uration (ms) | 403ms | 405ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99.3 kB | 99.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| index.html gzip | 530 B | 529 B | N/A |
| link.html gzip | 542 B | 542 B | ✓ |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 542 B | 542 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.3 kB | 95.3 kB | N/A |
| page.js gzip | 3.04 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 627 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51 kB | 51 kB | ✓ |
| Overall change | 944 kB | 944 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | devjiwonchoi/next.js fix/ts-plugin-server-actions | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | ⚠️ +1.22 kB |
| index.pack gzip | 106 kB | 106 kB | ⚠️ +393 B |
| Overall change | 1.68 MB | 1.68 MB | ⚠️ +1.61 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: f0a315f124eca14d5f72dc49e047e1a7cab2cd96

**Pull request merged**
