### PR TITLE
Optimize Images by 13% 

### PR DESCRIPTION
**Pull request by Zaid-maker**
### What?

I saw a very cool bot called `imgbot` which optimized the images and reduce their sizes

### How?

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 45bc1ce31cef30cbf085d2f0591c25a174c90a27

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4bfcdf579479dec851fe6796558ff5b7b14b7e3f

`pnpm test test/integration/image-optimizer/test/content-disposition-type.test.ts`
- with contentDispositionType inline > Production Mode Server support with next.config.js > should set cache-control to immutable for static images

<details>
<summary>Expand output</summary>

  ● with contentDispositionType inline › Production Mode Server support with next.config.js › should set cache-control to immutable for static images

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 400

      1312 |
      1313 |       const res1 = await fetchViaHTTP(ctx.appPort, '/_next/image', query, opts)
    > 1314 |       expect(res1.status).toBe(200)
           |                           ^
      1315 |       expect(res1.headers.get('Cache-Control')).toBe(
      1316 |         'public, max-age=315360000, immutable'
      1317 |       )

      at Object.toBe (integration/image-optimizer/test/util.ts:1314:27)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4bfcdf579479dec851fe6796558ff5b7b14b7e3f

`pnpm test test/integration/next-image-legacy/base-path/test/static.test.ts`
- Static Image Component Tests for basePath > development mode > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests for basePath > production mode > Should add a blur placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests for basePath › production mode › Should add a blur placeholder to statically imported png

    expect(received).toContain(expected) // indexOf

    Expected substring: "style=\"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;background-size:cover;background-position:0% 0%;filter:blur(20px);background-image:url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAICAMAAAALMbVOAAAAFVBMVEUBAQEtLS1CQkIHBwf9/f21tbWurq5/IXexAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAHElEQVR4nGNggAJmJmYGJhYmBlYWNgZGRkaYMAACTwAjtdG5RQAAAABJRU5ErkJggg==&quot;)"
    Received string:    "<!DOCTYPE html><html><head><meta charSet=\"utf-8\" data-next-head=\"\"/><meta name=\"viewport\" content=\"width=device-width\" data-next-head=\"\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" noModule=\"\" src=\"/docs/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js\"></script><script src=\"/docs/_next/static/chunks/webpack-4ef550747e11d93b.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/framework-1bd4a445914c8848.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/main-e3b7b5acac1ab38a.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/pages/_app-27ff185a3a5f182e.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/500-fa3aa38276367043.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/pages/static-img-2e45518e169ff25f.js\" defer=\"\"></script><script src=\"/docs/_next/static/QI5lFH98imM4aiuDwGszf/_buildManifest.js\" defer=\"\"></script><script src=\"/docs/_next/static/QI5lFH98imM4aiuDwGszf/_ssgManifest.js\" defer=\"\"></script></head><body><div id=\"__next\"><div><h1 id=\"page-header\">Static Image</h1><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:400px;height:300px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><noscript></noscript></span><div><h1 id=\"page-header\">Static Image</h1><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:160px;height:394px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><img id=\"basic-static\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" decoding=\"async\" data-nimg=\"fixed\" style=\"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;background-size:cover;background-position:0% 0%;filter:blur(20px);background-image:url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAICAMAAAALMbVOAAAAFVBMVEUBAQEtLS1CQkIHBwf9/f21tbWurq5/IXexAAAACXBIWXMAAAsTAAALEwEAmpwYAAACoXRFWHRSYXcACnhtcAogICAgIDMyMwozYzc4M2E3ODZkNzA2ZDY1NzQ2MTIwNzg2ZDZjNmU3MzNhNzgzZDIyNjE2NDZmNjI2NTNhNmU3MzNhNmQ2NTc0NjEyZjIyMjAKNzgzYTc4NmQ3MDc0NmIzZDIyNTg0ZDUwMjA0MzZmNzI2NTIwMzYyZTMwMmUzMDIyM2UwYTIwMjAyMDNjNzI2NDY2M2E1MjQ0CjQ2MjA3ODZkNmM2ZTczM2E3MjY0NjYzZDIyNjg3NDc0NzAzYTJmMmY3Nzc3NzcyZTc3MzMyZTZmNzI2NzJmMzEzOTM5MzkyZgozMDMyMmYzMjMyMmQ3MjY0NjYyZDczNzk2ZTc0NjE3ODJkNmU3MzIzMjIzZTBhMjAyMDIwMjAyMDIwM2M3MjY0NjYzYTQ0NjUKNzM2MzcyNjk3MDc0Njk2ZjZlMjA3MjY0NjYzYTYxNjI2Zjc1NzQzZDIyMjIwYTIwMjAyMDIwMjAyMDIwMjAyMDIwMjAyMDc4CjZkNmM2ZTczM2E3NDY5NjY2NjNkMjI2ODc0NzQ3MDNhMmYyZjZlNzMyZTYxNjQ2ZjYyNjUyZTYzNmY2ZDJmNzQ2OTY2NjYyZgozMTJlMzAyZjIyM2UwYTIwMjAyMDIwMjAyMDIwMjAyMDNjNzQ2OTY2NjYzYTRmNzI2OTY1NmU3NDYxNzQ2OTZmNmUzZTMxM2MKMmY3NDY5NjY2NjNhNGY3MjY5NjU2ZTc0NjE3NDY5NmY2ZTNlMGEyMDIwMjAyMDIwMjAzYzJmNzI2NDY2M2E0NDY1NzM2MzcyCjY5NzA3NDY5NmY2ZTNlMGEyMDIwMjAzYzJmNzI2NDY2M2E1MjQ0NDYzZTBhM2MyZjc4M2E3ODZkNzA2ZDY1NzQ2MTNlMGEKtyuPbQAAD9p0RVh0UmF3AAppY2MKICAgIDE5OTIKMDAwMDA3Yzg2MTcwNzA2YzAyMjAwMDAwNmQ2ZTc0NzI1MjQ3NDIyMDU4NTk1YTIwMDdkOTAwMDIwMDE5MDAwYjAwMWEwMDBiCjYxNjM3MzcwNDE1MDUwNGMwMDAwMDAwMDYxNzA3MDZjMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjZkNgowMDAxMDAwMDAwMDBkMzJkNjE3MDcwNmMwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBiNjQ2NTczNjMwMDAwMDEwODAwMDAwMDZmCjY0NzM2MzZkMDAwMDAxNzgwMDAwMDU4YTYzNzA3Mjc0MDAwMDA3MDQwMDAwMDAzODc3NzQ3MDc0MDAwMDA3M2MwMDAwMDAxNAo3MjU4NTk1YTAwMDAwNzUwMDAwMDAwMTQ2NzU4NTk1YTAwMDAwNzY0MDAwMDAwMTQ2MjU4NTk1YTAwMDAwNzc4MDAwMDAwMTQKNzI1NDUyNDMwMDAwMDc4YzAwMDAwMDBlNjM2ODYxNjQwMDAwMDc5YzAwMDAwMDJjNjI1NDUyNDMwMDAwMDc4YzAwMDAwMDBlCjY3NTQ1MjQzMDAwMDA3OGMwMDAwMDAwZTY0NjU3MzYzMDAwMDAwMDAwMDAwMDAxNDQ3NjU2ZTY1NzI2OTYzMjA1MjQ3NDIyMAo1MDcyNmY2NjY5NmM2NTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxNDQ3NjU2ZTY1NzI2OTYzMjA1MjQ3NDIyMDUwNzI2ZjY2NjkKNmM2NTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNmQ2Yzc1NjMwMDAwMDAwMDAwMDAwMDFmMDAwMDAwMGM3MzZiNTM0YgowMDAwMDAyODAwMDAwMTg0NjQ2MTQ0NGIwMDAwMDAyNDAwMDAwMWFjNjM2MTQ1NTMwMDAwMDAyNDAwMDAwMWQwNzY2OTU2NGUKMDAwMDAwMjQwMDAwMDFmNDcwNzQ0MjUyMDAwMDAwMjYwMDAwMDIxODc1NmI1NTQxMDAwMDAwMmEwMDAwMDIzZTY2NzI0NjU1CjAwMDAwMDI4MDAwMDAyNjg2ODc1NDg1NTAwMDAwMDI4MDAwMDAyOTA3YTY4NTQ1NzAwMDAwMDEyMDAwMDAyYjg2YjZmNGI1MgowMDAwMDAxNjAwMDAwMmNhNmU2MjRlNGYwMDAwMDAyNjAwMDAwMmUwNjM3MzQzNWEwMDAwMDAyMjAwMDAwMzA2Njg2NTQ5NGMKMDAwMDAwMWUwMDAwMDMyODcyNmY1MjRmMDAwMDAwMjQwMDAwMDM0NjY0NjU0NDQ1MDAwMDAwMmMwMDAwMDM2YTY5NzQ0OTU0CjAwMDAwMDI4MDAwMDAzOTY3Mzc2NTM0NTAwMDAwMDI2MDAwMDAyZTA3YTY4NDM0ZTAwMDAwMDEyMDAwMDAzYmU2YTYxNGE1MAowMDAwMDAxYTAwMDAwM2QwNjU2YzQ3NTIwMDAwMDAyMjAwMDAwM2VhNzA3NDUwNGYwMDAwMDAyNjAwMDAwNDBjNmU2YzRlNGMKMDAwMDAwMjgwMDAwMDQzMjY1NzM0NTUzMDAwMDAwMjYwMDAwMDQwYzc0Njg1NDQ4MDAwMDAwMjQwMDAwMDQ1YTc0NzI1NDUyCjAwMDAwMDIyMDAwMDA0N2U2NjY5NDY0OTAwMDAwMDI4MDAwMDA0YTA2ODcyNDg1MjAwMDAwMDI4MDAwMDA0Yzg3MDZjNTA0YwowMDAwMDAyYzAwMDAwNGYwNzI3NTUyNTUwMDAwMDAyMjAwMDAwNTFjNjU2ZTU1NTMwMDAwMDAyNjAwMDAwNTNlNjE3MjQ1NDcKMDAwMDAwMjYwMDAwMDU2NDAwNTYwMTYxMDA2NTAwNmYwMDYyMDA2NTAwNjMwMDZlMDBmZDAwMjAwMDUyMDA0NzAwNDIwMDIwCjAwNzAwMDcyMDA2ZjAwNjYwMDY5MDA2YzAwNDcwMDY1MDA2ZTAwNjUwMDcyMDA2NTAwNmMwMDIwMDA1MjAwNDcwMDQyMDAyZAowMDcwMDA3MjAwNmYwMDY2MDA2OTAwNmMwMDUwMDA2NTAwNzIwMDY2MDA2OTAwNmMwMDIwMDA1MjAwNDcwMDQyMDAyMDAwNjcKMDA2NTAwNmUwMGU4MDA3MjAwNjkwMDYzMDA0MzFlYTUwMDc1MDAyMDAwNjgwMGVjMDA2ZTAwNjgwMDIwMDA1MjAwNDcwMDQyCjAwMjAwMDQzMDA2ODAwNzUwMDZlMDA2NzAwNTAwMDY1MDA3MjAwNjYwMDY5MDA2YzAwMjAwMDUyMDA0NzAwNDIwMDIwMDA0NwowMDY1MDA2ZTAwZTkwMDcyMDA2OTAwNjMwMDZmMDQxNzA0MzAwNDMzMDQzMDA0M2IwNDRjMDQzZDA0MzgwNDM5MDAyMDA0M2YKMDQ0MDA0M2UwNDQ0MDQzMDA0MzkwNDNiMDAyMDAwNTIwMDQ3MDA0MjAwNTAwMDcyMDA2ZjAwNjYwMDY5MDA2YzAwMjAwMDY3CjAwZTkwMDZlMDBlOTAwNzIwMDY5MDA3MTAwNzUwMDY1MDAyMDAwNTIwMDU2MDA0MjAwYzEwMDZjMDA3NDAwNjEwMDZjMDBlMQowMDZlMDA2ZjAwNzMwMDIwMDA1MjAwNDcwMDQyMDAyMDAwNzAwMDcyMDA2ZjAwNjYwMDY5MDA2YzkwMWE3NTI4MDA1MjAwNDcKMDA0MjgyNzI1ZjY5NjNjZjhmZjBjNzdjYmMxODAwMjAwMDUyMDA0NzAwNDIwMDIwZDUwNGI4NWNkMzBjYzc3YzAwNDcwMDY1CjAwNmUwMDY1MDA3MjAwNjkwMDczMDA2YjAwMjAwMDUyMDA0NzAwNDIwMDJkMDA3MDAwNzIwMDZmMDA2NjAwNjkwMDZjMDA0ZgowMDYyMDA2NTAwNjMwMDZlMDBmZDAwMjAwMDUyMDA0NzAwNDIwMDIwMDA3MDAwNzIwMDZmMDA2NjAwNjkwMDZjMDVlNDA1ZTgKMDVkNTA1ZTQwNWQ5MDVkYzAwMjAwMDUyMDA0NzAwNDIwMDIwMDVkYjA1ZGMwNWRjMDVkOTAwNTAwMDcyMDA2ZjAwNjYwMDY5CjAwNmMwMDIwMDA1MjAwNDcwMDQyMDAyMDAwNjcwMDY1MDA2ZTAwNjUwMDcyMDA2OTAwNjMwMDQxMDA2YzAwNmMwMDY3MDA2NQowMDZkMDA2NTAwNjkwMDZlMDA2NTAwNzMwMDIwMDA1MjAwNDcwMDQyMDAyZDAwNTAwMDcyMDA2ZjAwNjYwMDY5MDA2YzAwNTAKMDA3MjAwNmYwMDY2MDA2OTAwNmMwMDZmMDAyMDAwNTIwMDQ3MDA0MjAwMjAwMDY3MDA2NTAwNmUwMDY1MDA3MjAwNjkwMDYzCjAwNmY2NjZlOTAxYTAwNTIwMDQ3MDA0MjYzY2Y4ZmYwNjU4NzRlZjY0ZTAwODIyYzAwMjAwMDUyMDA0NzAwNDIwMDIwMzBkNwozMGVkMzBkNTMwYTEzMGE0MzBlYjAzOTMwM2I1MDNiZDAzYjkwM2JhMDNjYzAwMjAwM2MwMDNjMTAzYmYwM2M2MDNhZjAzYmIKMDAyMDAwNTIwMDQ3MDA0MjAwNTAwMDY1MDA3MjAwNjYwMDY5MDA2YzAwMjAwMDUyMDA0NzAwNDIwMDIwMDA2NzAwNjUwMDZlCjAwZTkwMDcyMDA2OTAwNjMwMDZmMDA0MTAwNmMwMDY3MDA2NTAwNmQwMDY1MDA2NTAwNmUwMDIwMDA1MjAwNDcwMDQyMDAyZAowMDcwMDA3MjAwNmYwMDY2MDA2OTAwNjUwMDZjMGU0MjBlMWIwZTIzMGU0NDBlMWYwZTI1MGU0YzAwMjAwMDUyMDA0NzAwNDIKMDAyMDBlMTcwZTMxMGU0ODBlMjcwZTQ0MGUxYjAwNDcwMDY1MDA2ZTAwNjUwMDZjMDAyMDAwNTIwMDQ3MDA0MjAwMjAwMDUwCjAwNzIwMDZmMDA2NjAwNjkwMDZjMDA2OTAwNTkwMDZjMDA2NTAwNjkwMDZlMDA2NTAwNmUwMDIwMDA1MjAwNDcwMDQyMDAyZAowMDcwMDA3MjAwNmYwMDY2MDA2OTAwNjkwMDZjMDA2OTAwNDcwMDY1MDA2ZTAwNjUwMDcyMDA2OTAxMGQwMDZiMDA2OTAwMjAKMDA1MjAwNDcwMDQyMDAyMDAwNzAwMDcyMDA2ZjAwNjYwMDY5MDA2YzAwNTUwMDZlMDA2OTAwNzcwMDY1MDA3MjAwNzMwMDYxCjAwNmMwMDZlMDA3OTAwMjAwMDcwMDA3MjAwNmYwMDY2MDA2OTAwNmMwMDIwMDA1MjAwNDcwMDQyMDQxZTA0MzEwNDQ5MDQzOAowNDM5MDAyMDA0M2YwNDQwMDQzZTA0NDQwNDM4MDQzYjA0NGMwMDIwMDA1MjAwNDcwMDQyMDA0NzAwNjUwMDZlMDA2NTAwNzIKMDA2OTAwNjMwMDIwMDA1MjAwNDcwMDQyMDAyMDAwNTAwMDcyMDA2ZjAwNjYwMDY5MDA2YzAwNjUwNjQ1MDY0NDA2NDEwMDIwCjA2MmEwNjM5MDYzMTA2NGEwNjQxMDAyMDAwNTIwMDQ3MDA0MjAwMjAwNjI3MDY0NDA2MzkwNjI3MDY0NTAwMDA3NDY1Nzg3NAowMDAwMDAwMDQzNmY3MDc5NzI2OTY3Njg3NDIwMzIzMDMwMzcyMDQxNzA3MDZjNjUyMDQ5NmU2MzJlMmMyMDYxNmM2YzIwNzIKNjk2NzY4NzQ3MzIwNzI2NTczNjU3Mjc2NjU2NDJlMDA1ODU5NWEyMDAwMDAwMDAwMDAwMGYzNTIwMDAxMDAwMDAwMDExNmNmCjU4NTk1YTIwMDAwMDAwMDAwMDAwNzQ0ZDAwMDAzZGVlMDAwMDAzZDA1ODU5NWEyMDAwMDAwMDAwMDAwMDVhNzUwMDAwYWM3MwowMDAwMTczNDU4NTk1YTIwMDAwMDAwMDAwMDAwMjgxYTAwMDAxNTlmMDAwMGI4MzY2Mzc1NzI3NjAwMDAwMDAwMDAwMDAwMDEKMDFjZDAwMDA3MzY2MzMzMjAwMDAwMDAwMDAwMTBjNDIwMDAwMDVkZWZmZmZmMzI2MDAwMDA3OTIwMDAwZmQ5MWZmZmZmYmEyCmZmZmZmZGEzMDAwMDAzZGMwMDAwYzA2Ywr/keSiAAAAHElEQVR4nGNggAJmJmYGJhYmBlYWNgZGRkaYMAACTwAjtdG5RQAAAABJRU5ErkJggg==&quot;)\"/><noscript></noscript></span></div><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:200px;height:200px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><br/><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><br/><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/static-img\",\"query\":{},\"buildId\":\"QI5lFH98imM4aiuDwGszf\",\"assetPrefix\":\"/docs\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      90 |       )
      91 |     } else {
    > 92 |       expect(html).toContain(
         |                    ^
      93 |         `style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;background-size:cover;background-position:0% 0%;filter:blur(20px);background-image:url(${
      94 |           isDev
      95 |             ? '&quot;/docs/_next/image?url=%2Fdocs%2F_next%2Fstatic%2Fmedia%2Ftest.3f1a293b.png&amp;w=8&amp;q=70&quot;'

      at Object.toContain (integration/next-image-legacy/base-path/test/static.test.ts:92:20)

  ● Static Image Component Tests for basePath › development mode › Should add a blur placeholder to statically imported jpg

    expect(received).toContain(expected) // indexOf

    Expected substring: "style=\"position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;background-size:cover;background-position:0% 0%;filter:blur(20px);background-image:url(&quot;/docs/_next/image?url=%2Fdocs%2F_next%2Fstatic%2Fmedia%2Ftest.fab2915d.jpg&amp;w=8&amp;q=70&quot;)"
    Received string:    "<!DOCTYPE html><html><head><meta charSet=\"utf-8\" data-next-head=\"\"/><meta name=\"viewport\" content=\"width=device-width\" data-next-head=\"\"/><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><noscript data-n-css=\"\"></noscript><script defer=\"\" noModule=\"\" src=\"/docs/_next/static/chunks/polyfills.js\"></script><script src=\"/docs/_next/static/chunks/webpack.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/main.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/pages/_app.js\" defer=\"\"></script><script src=\"/docs/_next/static/chunks/pages/static-img.js\" defer=\"\"></script><script src=\"/docs/_next/static/development/_buildManifest.js\" defer=\"\"></script><script src=\"/docs/_next/static/development/_ssgManifest.js\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"><div><h1 id=\"page-header\">Static Image</h1><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:400px;height:300px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><noscript></noscript></span><div><h1 id=\"page-header\">Static Image</h1><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:160px;height:394px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><noscript></noscript></span></div><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:200px;height:200px;background:none;opacity:1;border:0;margin:0;padding:0;position:relative\"><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><br/><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span><br/><span style=\"box-sizing:border-box;display:inline-block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative;max-width:100%\"><span style=\"box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;max-width:100%\"></span><noscript></noscript></span></div></div><script src=\"/docs/_next/static/chunks/react-refresh.js\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/static-img\",\"query\":{},\"buildId\":\"development\",\"assetPrefix\":\"/docs\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      75 |       )
      76 |     } else {
    > 77 |       expect(html).toContain(
         |                    ^
      78 |         `style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;background-size:cover;background-position:0% 0%;filter:blur(20px);background-image:url(${
      79 |           isDev
      80 |             ? '&quot;/docs/_next/image?url=%2Fdocs%2F_next%2Fstatic%2Fmedia%2Ftest.fab2915d.jpg&amp;w=8&amp;q=70&quot;'

      at Object.toContain (integration/next-image-legacy/base-path/test/static.test.ts:77:20)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by samcx** [comment]
@Zaid-maker This likely isn't worth the work to fix the tests—with `next/image`, you'll be optimizing the images already.

**Comment by Zaid-maker** [comment]
> @Zaid-maker This likely isn't worth the work to fix the tests—with `next/image`, you'll be optimizing the images already.



> @Zaid-maker This likely isn't worth the work to fix the tests—with `next/image`, you'll be optimizing the images already.

Hmmm!

**Comment by samcx** [comment]
@Zaid-maker Let me know if that makes sense! If yes, we can proceed with closing the issue.

**Review by ijjk — CHANGES_REQUESTED** [review]
Closing as un-necessary as pointed out above, thanks tho!

**Pull request closed without merging**
