### PR TITLE
fix(blog-starter-typescript): update to PostCSS 8

### LINKED ISSUE #20812: blog-starter-typescript: PostCSS plugin postcss-nested requires PostCSS 8
**What example does this report relate to?**

blog-starter-typescript

**What version of Next.js are you using?**

10.0.4

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next build / next dev

**Describe the Bug**

```
➜  blog-starter-typescript-app git:(main) yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build
Failed to compile.

./styles/index.css
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/stanislas/lab/blog-starter-typescript-app/node_modules/next/dist/build/index.js:15:918
    at async /Users/stanislas/lab/blog-starter-typescript-app/node_modules/next/dist/build/tracer.js:1:525
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected Behavior**

Working example

**To Reproduce**

```
npx create-next-app --example blog-starter-typescript blog-starter-typescript-app
cd blog-starter-typescript-app
yarn build
```

### PR DESCRIPTION
**Pull request by angristan**
Fix https://github.com/vercel/next.js/issues/20812.

Probably a side effect of https://github.com/vercel/next.js/pull/20664.

Resolution process:

```
➜  blog-starter-typescript git:(fix/blog-starter-typescript-postcss) yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build
Failed to compile.

./styles/index.css
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/stanislas/lab/next.js/examples/blog-starter-typescript/node_modules/next/dist/build/index.js:15:918
    at async /Users/stanislas/lab/next.js/examples/blog-starter-typescript/node_modules/next/dist/build/tracer.js:1:525
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

➜  blog-starter-typescript git:(fix/blog-starter-typescript-postcss) yarn add postcss@latest
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["postcss@8.2.2"] is trying to unpack in the same destination "/Users/stanislas/Library/Caches/Yarn/v6/npm-postcss-8.2.2-60613b62297005084fd21024a68637798864fe26-integrity/node_modules/postcss" as pattern ["postcss@^8.1.6","postcss@^8.2.1"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > tailwindcss@2.0.2" has unmet peer dependency "autoprefixer@^10.0.2".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ postcss@8.2.2
info All dependencies
└─ postcss@8.2.2
✨  Done in 2.75s.

➜  blog-starter-typescript git:(fix/blog-starter-typescript-postcss) ✗ yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (5/5)
info  - Finalizing page optimization

Page                                Size     First Load JS
┌ ● /                               1.14 kB        72.6 kB
├   /_app                           0 B            60.2 kB
├ ○ /404                            2.75 kB        62.9 kB
└ ● /posts/[slug]                   2.04 kB        73.5 kB
    └ css/b35764b19b26c09ce0d6.css  175 B
    ├ /posts/dynamic-routing
    ├ /posts/hello-world
    └ /posts/preview
+ First Load JS shared by all       60.2 kB
  ├ chunks/commons.286c5a.js        13 kB
  ├ chunks/framework.76fac1.js      39.9 kB
  ├ chunks/main.f094e2.js           6.24 kB
  ├ chunks/pages/_app.ee24bc.js     293 B
  ├ chunks/webpack.95c2b2.js        751 B
  └ css/3e8f4558884e709902cc.css    2.51 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✨  Done in 16.35s.
```

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.6s | ⚠️ +68ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.208 | 2.216 | ⚠️ +0.01 |
| / avg req/sec | 1132.29 | 1128.02 | ⚠️ -4.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.543 | 1.56 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1619.93 | 1602.58 | ⚠️ -17.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.4s | -328ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 8f0de3f0a437e23892c3a68117cf5f6bf136821b

**Review by lfades — APPROVED** [review]
Good catch. Thank you!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| buildDuration | 9.1s | 9s | -62ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.788 | 1.799 | ⚠️ +0.01 |
| / avg req/sec | 1398.2 | 1389.53 | ⚠️ -8.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.156 | 1.14 | -0.02 |
| /error-in-render avg req/sec | 2162.93 | 2193.66 | +30.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8b99f8a..8ccf.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 618 B | 618 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.8s | ⚠️ +21ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8b99f8a..8ccf.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | angristan/next.js fix/blog-starter-typescript-postcss | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: a4502de77763e8bc443c95d04839cf6b22bfde44

**Comment by timneutkens** [comment]
Looks like we recently upgraded postcss already. Thanks for this PR!

**Pull request closed without merging**
