### PR TITLE
Change page export validity check on client and server in development

### LINKED ISSUE #4055: Home-rolled "is Component?" test is throwing false negatives for React 16.3.0 features
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Overview

React 16.3 will include a utility for ref forwarding called `React.forwardRef`. [Its RFC](https://github.com/reactjs/rfcs/pull/30) has been ratified and the initial implementation is available in alpha builds of 16.3.

The `typeof` objects returned by `forwardRef` happens to be `"object"`, not `"function"`, which means that if you wrap your Page component in a HOC that uses `forwardRef`, it will fail the overly-aggressive [test here](https://github.com/zeit/next.js/blob/01f05d8cbc0333dd629f3c6bb180d73c41fed968/lib/app.js#L36-L40).

## Expected Behavior

If I wrap a top-level Page component with `React.forwardRef`, I expect Next.js to render it without issue.

## Current Behavior

If I wrap a top-level Page component with `React.forwardRef`, Next.js throws the following error:

```
Error: The default export is not a React Component in page: ...
```

## Steps to Reproduce (for bugs)

For any Page component in a Next.js app, add the following lines:

```js
// ...
const MyPage = () => (...);
export default React.forwardRef((props, ref) => <MyPage {...props} forwardedRef={ref} />);
```

## Context

As soon as the `forwardRef` API is released, library that expose HOCs are going to start using it to provide a standard way of accessing the ref of the wrapped component. (Prior to this, each HOC library would take a slightly different approach.)

As more libraries and apps are updated, the number of people impacted will grow. I expect this to happen fairly rapidly, at least for actively-maintained libraries.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  5.0.1-canary.17       |

### PR DESCRIPTION
**Pull request by kylemh**
Resolves #4055 

Credit: https://github.com/zeit/next.js/pull/5095

I didn't use the ignore webpack plugin from the original PR and tested bundle size with https://github.com/zeit/next.js/pull/5339 - seems to be safe on that front.

Was able to get tests to pass locally, unsure of what goes wrong in CI 🤷‍♂️ 

**Questions**
1) The initial PR didn't include changes to `next-server/lib/router` in `getRouteInfo()`. Should the same changes be made within?

2) Should we add a test for rendering a component created via `forwardRef()`?

`component-with-forwardedRef`:
```javascript
export default React.forwardRef((props, ref) => <span {...props} forwardedRef={ref}>This is a component with a forwarded ref</span>);
```

some test:
```javascript
test('renders from forwardRef', async () => {
  const $ = await get$('/component-with-forwardedRef')
  const span = $('span')
  expect(span.text()).toMatch(/This is a component with a forwarded ref/)
})
```

### CODE REVIEW

**Comment by timneutkens** [comment]
Yes we should definitely add that test. Also a test for `memo(` would make sense

**Comment by timneutkens** [comment]
So these two fail:

```
✕ should recover after exporting an invalid page (30575ms)
✕ should recover after a bad return from the render function (30526ms)
```

You can run them using:

```
yarn testonly --testPathPattern="basic" -t "should recover after exporting an invalid page"
```

**Comment by elliottsj** [comment]
Thanks for this 👍 

I think we also need to update _lib/router/router.js_: https://github.com/zeit/next.js/blob/82c5cc38d59e65d98c74f5012c3780e2832880c6/packages/next-server/lib/router/router.js#L263-L265

**Comment by kylemh** [comment]
-_-

the tests are failing, but the error is firing correctly?

**Comment by timneutkens** [comment]
I just investigated why the tests failed and realized that you had changed the value of `export default "something"` to `export default undefined` incidentally this exposed a bug in HMR where if `undefined` is the component being exported we don't apply the changes. It might be interesting to investigate this further, but for the current PR I've changed `undefined` to `{}`

**Comment by Enalmada** [comment]
I am trying to upgrade my reason-react project from 7.0.2 to latest canary and getting `The default export is not a React Component in page: "/"`.  The error seems related to things talked about in this ticket...if that is true, could you give me your advice on this issue:
https://github.com/zeit/next.js/issues/5929

**Pull request merged**
