### PR TITLE
Updates dependencies for with-supertokens example

### PR DESCRIPTION
**Pull request by rishabhpoddar**
Updating dependencies for supertokens-node and supertokens-auth-react + changing function name usage as per new SDKs

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Hey! Any updates on this please? Thanks

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Thanks, sorry for the delay!

**Comment by rishabhpoddar** [comment]
@leerob some of the automated actions are failing. I'm not sure why. Any advice please?

**Review by leerob — APPROVED** [review]

**Comment by rishabhpoddar** [comment]
Thanks @leerob

**Pull request merged**
