### PR TITLE
Show component stack in error overlay on hydration error

### PR DESCRIPTION
**Pull request by hanneslund**
Saves the component stack with the patched `console.error` just like the hydration warning. It's added to the corresponding hydration error in the event handler and then parsed and displayed in the overlay.

<details>
    <summary>Before</summary>

CleanShot 2023-02-11 at 18 57 07@2x

</details>

<details>
    <summary>After</summary>

CleanShot 2023-02-11 at 18 55 26@2x

</details>

Component stack frames from Next.js are hidden. If preferable they could be collapsed like call stack frames in a folllow up PR.
Collapsed call stacks:
image

<details>
    <summary>Show hidden component stack frames</summary>
    
image

</details>

Fixes NEXT-123

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e357203367db9b014f38db79c97dbfb2f7b6f010

`pnpm testheadless test/integration/api-support/test/index.test.js` 
- API routes > Server support > should warn with configured size if response body is larger than configured size
- API routes > dev support > should not warn if response body is larger than 4MB with responseLimit config = false
- API routes > dev support > should warn with configured size if response body is larger than configured size

<details>
<summary>Expand output</summary>

  ● API routes › dev support › should not warn if response body is larger than 4MB with responseLimit config = false

    FetchError: request to http://localhost:35533/api/large-response-with-config failed, reason: read ECONNRESET

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● API routes › dev support › should warn with configured size if response body is larger than configured size

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      493 |   })
      494 |
    > 495 |   it('should warn with configured size if response body is larger than configured size', async () => {
          |   ^
      496 |     let res = await fetchViaHTTP(
      497 |       appPort,
      498 |       '/api/large-response-with-config-size'

      at runTests (integration/api-support/test/index.test.js:495:3)
      at integration/api-support/test/index.test.js:607:5
      at integration/api-support/test/index.test.js:595:3
      at Object.<anonymous> (integration/api-support/test/index.test.js:594:1)

  ● API routes › Server support › should warn with configured size if response body is larger than configured size

    expect(received).toContain(expected) // indexOf

    Expected substring: "API response for /api/large-response-with-config-size exceeds 5MB. API Routes are meant to respond quickly."
    Received string:    "A body was attempted to be set with a 204 statusCode for /api/status-204?invalid=1, this is invalid and the body was ignored.
    See more info here https://nextjs.org/docs/messages/invalid-api-status-body
    error - Error: User error

      17 | });
      18 |
    > 19 |
         | ^
      20 | /***/ })
      21 |
      22 | };

      at __WEBPACK_DEFAULT_EXPORT__ (integration/api-support/.next/server/pages/api/user-error.js:19:11)
      at Object.apiResolver (../packages/next/dist/server/api-utils/node.js:372:15)
      at async DevServer.runApi (../packages/next/dist/server/next-server.js:488:9)
      at async Object.fn (../packages/next/dist/server/next-server.js:751:37)
      at async Router.execute (../packages/next/dist/server/router.js:253:36)
      at async DevServer.run (../packages/next/dist/server/base-server.js:384:29)
      at async DevServer.run (../packages/next/dist/server/dev/next-dev-server.js:741:20)
      at async DevServer.handleRequest (../packages/next/dist/server/base-server.js:322:20) {
        page: '/api/user-error'
      }
      error - Error: User error
      at __WEBPACK_DEFAULT_EXPORT__ (integration/api-support/.next/server/pages/api/user-error-async.js:19:11)
      at Object.apiResolver (../packages/next/dist/server/api-utils/node.js:372:15)
      at async DevServer.runApi (../packages/next/dist/server/next-server.js:488:9)
      at async Object.fn (../packages/next/dist/server/next-server.js:751:37)
      at async Router.execute (../packages/next/dist/server/router.js:253:36)
      at async DevServer.run (../packages/next/dist/server/base-server.js:384:29)
      at async DevServer.run (../packages/next/dist/server/dev/next-dev-server.js:741:20)
      at async DevServer.handleRequest (../packages/next/dist/server/base-server.js:322:20) {
        page: '/api/user-error-async'
      }
      error - Error: Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').
      at Object.redirect (../packages/next/dist/server/api-utils/index.js:33:15)
      at ServerResponse.apiRes.redirect (../packages/next/dist/server/api-utils/node.js:361:59)
      at __WEBPACK_DEFAULT_EXPORT__ (integration/api-support/.next/server/pages/api/redirect-error.js:19:9)
      at Object.apiResolver (../packages/next/dist/server/api-utils/node.js:372:15)
      at async DevServer.runApi (../packages/next/dist/server/next-server.js:488:9)
      at async Object.fn (../packages/next/dist/server/next-server.js:751:37)
      at async Router.execute (../packages/next/dist/server/router.js:253:36)
      at async DevServer.run (../packages/next/dist/server/base-server.js:384:29)
      at async DevServer.run (../packages/next/dist/server/dev/next-dev-server.js:741:20)
      at async DevServer.handleRequest (../packages/next/dist/server/base-server.js:322:20) {
        page: '/api/redirect-error'
      }
      error - Error: Invalid redirect arguments. Please use a single argument URL, e.g. res.redirect('/destination') or use a status code and URL, e.g. res.redirect(307, '/destination').
      at Object.redirect (../packages/next/dist/server/api-utils/index.js:33:15)
      at ServerResponse.apiRes.redirect (../packages/next/dist/server/api-utils/node.js:361:59)
      at __WEBPACK_DEFAULT_EXPORT__ (integration/api-support/.next/server/pages/api/redirect-null.js:19:9)
      at Object.apiResolver (../packages/next/dist/server/api-utils/node.js:372:15)
      at async DevServer.runApi (../packages/next/dist/server/next-server.js:488:9)
      at async Object.fn (../packages/next/dist/server/next-server.js:751:37)
      at async Router.execute (../packages/next/dist/server/router.js:253:36)
      at async DevServer.run (../packages/next/dist/server/base-server.js:384:29)
      at async DevServer.run (../packages/next/dist/server/dev/next-dev-server.js:741:20)
      at async DevServer.handleRequest (../packages/next/dist/server/base-server.js:322:20) {
        page: '/api/redirect-null'
      }
      API response for /api/large-response exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
      API response for /api/large-chunked-response exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
      API resolved without sending a response for /api/test-no-end, this may result in stalled requests.
      API resolved without sending a response for /api/external-resolver-false-positive, this may result in stalled requests.
      "
      at Object.<anonymous> (integration/api-support/test/index.test.js:501:20)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by timneutkens** [comment]
CleanShot 2023-01-24 at 10 36 13@2x

The items feel too far apart from eachother given that there's no additional metadata.

**Review by timneutkens — APPROVED** [review]

**Comment by karlhorky** [comment]
Glad there is some work being done here! It may be a bit nicer to have the full diff in these hydration errors, as Dan and I were discussing:

- https://github.com/vercel/next.js/issues/37847

**Comment by karlhorky** [comment]
Glad there is some work being done here! It may be a bit nicer to have the full diff in these hydration errors, as Dan and I were discussing:

- https://github.com/vercel/next.js/issues/37847

**Pull request merged**
