### PR TITLE
Add persistent layout support

### PR DESCRIPTION
**Pull request by clemencov**
Persistent layout implementation, inspired by closed PR #2440.

### CODE REVIEW

**Comment by frol** [comment]
To be honest, I don't see any value in the implementation. How exactly does this help given there is a natural way of compositing React components: https://github.com/zeit/next.js/tree/canary/examples/layout-component ?

**Comment by clemencov** [comment]
State persistence over page transitions (media players, notifications, chat scroll positions).

**Comment by clemencov** [comment]
Few discussions in: #3200, #88

**Comment by frol** [comment]
@clemencov 

> This actually won't fix #88 since ReactDOM.render is still called on page changes.

(c) @timneutkens  (https://github.com/zeit/next.js/pull/2440#issuecomment-312504214)

**Comment by clemencov** [comment]
Yes, it doesn't much help with animations, but until `renderReactElement` function is not calling ReactDOM's `unmountComponentAtNode`, React will not unmount the Layout component and relying to this we can use it as a persistent top-level component.

**Comment by rauchg** [comment]
I definitely want this, but I don't think we need the concept of a single global layout. One of the ideas I had was that we could put a key or attribute on the top level component. If it matches the one of the next page, we retain that top level component.

**Comment by tz5514** [comment]
@rauchg Is there any schedule for this important feature?
Lots of developer want this https://github.com/zeit/next.js/issues/88. 
We really really hope that this feature can be implemented as soon.
Thanks!

**Comment by timneutkens** [comment]
Closing in favor of #4129

**Pull request closed without merging**
