### PR TITLE
feat: prepend backslash to pathMap keys if needed

### PR DESCRIPTION
**Pull request by maciej-ka**
Hi!

Closes: https://github.com/zeit/next.js/issues/2826

### CODE REVIEW

**Comment by arunoda** [comment]
@maciej-ka this is great.
But some tests are failing related to next-export.

It could be a regression or we need to update tests as this feature.
Could you run tests locally(npm run test) and see what's going on.

**Comment by timneutkens** [comment]
Isn't it better to throw a meaningful error here and let the user fix it?

**Comment by maciej-ka** [comment]
Thanks for fast reply!

As for failing tests, they are failing on current `canary` branch, you can easily see this by looking at other pending PR) I added a PR that should turn them green again (and fix some behavior): https://github.com/zeit/next.js/pull/3455

@timneutkens I let you decide:
- for an auto prefixing pick this PR
- for displaying an error, pick https://github.com/zeit/next.js/pull/3456

**Comment by arunoda** [comment]
Closing instead of this: https://github.com/zeit/next.js/pull/3456

**Pull request closed without merging**
