### PR TITLE
[RSC Bugfix] Include charset=utf-8 with x-component Content-Type header

### PR DESCRIPTION
**Pull request by hex2f**
This PR updates [RSC_CONTENT_TYPE_HEADER ](https://github.com/vercel/next.js/blob/448b74291e40f888bfc82ebd9d306c08d67e98f2/packages/next/src/client/components/app-router-headers.ts#LL8C18-L8C18) to also include a charset tag set to utf-8.

While trying out RSCs for a new app we're building, we ran into a lot of weird and nonsensical bugs such as `Expected ',' or ']' after array element in JSON at position 45908` and just flat out `Connection closed`. After some days of debugging, we're quite confident that we've narrowed down the issue to no charset being sent with the x-component Content-Type in the response for RSCs. This has been validated by using [Proxyman](https://proxyman.io/) to intercept the network calls where we inject the charset tag ourselves, like so:

```js
if (response.headers["Content-Type"] == "text/x-component") {
  response.headers["Content-Type"] = "text/x-component; charset=utf-8"
}
```

which completely fixed all of the issues we we're having. My assumption is that the browser interprets the response body with the latin charset if none is provided for an unknown Content-Type (`text/x-component`).

This PR should fix these issues but I didn't manage to set up a proper testing environment, so hoping that the maintainers can validate themselves.

### CODE REVIEW

**Comment by IanMitchell** [comment]
As a repro case, sending content with the trans flag emoji seems to frequently break RSC components

**Review by ijjk — COMMENTED** [review]
Hi, this change seems good to me as it seems best to explicitly include the charset when we can to avoid mis-detection especially since `text/x-component` doesn't have official defaults in mime-dbs it seems. 

Looks like this PR is locked to contributions from maintainers so going to land this in https://github.com/vercel/next.js/pull/50314

Thanks for digging into this/opening the PR!

**Comment by sebmarkbage** [comment]
This won’t really be a sufficient change because RSC is technically a binary format. On the client parts of the payload may be parsed as utf-8 but if it’s treated by an intermediate as utf-8 it’ll break any binary parts of the protocol.

The headers shouldn’t be needed because the client we use to parse it isn’t the built in browser. We use TextDecoder explicitly. So it couldn’t do anything. It must be another issue if this fixes something. We’ll need a repro.

**Comment by IanMitchell** [comment]
It looks like there's an update in flight for this - happy to give it a go once it lands in a canary version and report back with results. We can share a (rather complex) repro at that point if we are still encountering it too!

**Comment by ijjk** [comment]
@IanMitchell could you give this tarball a try it includes the changes referenced in the other PR:
```sh
pnpm i next@https://files-ectwoh7mr-vtest314-ijjk-testing.vercel.app/next-v13.4.4-canary.11.tgz
```

**Comment by hex2f** [comment]
@ijjk it should be live on ramble.pub now, seems to still be happening. want me to give you access to the repo as a reprod case?

**Comment by ijjk** [comment]
@hex2f that would be awesome yeah and also @sebmarkbage if possible 🙏

**Comment by hex2f** [comment]
@ijjk @sebmarkbage [invited](https://github.com/hex57/ramble/invitations), also fyi I think I've only seen this issue when deployed to vercel, not when running the local dev server

**Comment by ijjk** [comment]
Hi, circling back here a fix has been landed in react itself (related PR https://github.com/facebook/react/pull/26871) for this and has now been applied in the latest version of Next.js (related PR https://github.com/vercel/next.js/pull/50604)

Checking the provided reproduction looks like you are already updated but just want to confirm the issue is mitigated for you there?

**Comment by IanMitchell** [comment]
I believe we have seen it clear up, yeah! If we encounter the issue again I'll report back here 👍. Thank you all!

**Pull request closed without merging**
