### PR TITLE
add next.config.js for v3 next export example with-dynamic-import

### PR DESCRIPTION
**Pull request by johhansantana**
Added working v3-beta version in package.json.

Also, example [here](https://zeit.co/blog/next3-preview#how-to-use) has syntax error.

This is my first pull request here, I'm not sure if I'm doing the right way :l

### CODE REVIEW

**Comment by vinaypuppal** [comment]
@johhansantana Could you also fix this in Readme
from
```
curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/shared-modules
cd shared-modules
```
to
```
curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/with-dynamic-import
cd with-dynamic-import
```

**Comment by johhansantana** [comment]
@vinaypuppal done :D

**Comment by arunoda** [comment]
Guys thanks for this. 
But for the dynamic import example we should add the next export settings. 
Could you remove the stuff from the next config file.

**Comment by johhansantana** [comment]
Sorry for my ignorance but what is the `next export settings` ?

**Comment by vinaypuppal** [comment]
@johhansantana No need of this file  `examples/with-dynamic-import/next.config.js` for this example as its only needed if we want to use `next export`. So @arunoda asked you to remove it.

**Comment by johhansantana** [comment]
ah! @vinaypuppal I think I was confused that this was the example for `next export` as it's at the end of the [blog post](https://zeit.co/blog/next3-preview#get-it-now)

**Comment by arunoda** [comment]
This is great. 
Thanks.

**Pull request merged**
