### PR TITLE
Adds jest configuration to examples

### PR DESCRIPTION
**Pull request by pksjce**
With ref to #19

### CODE REVIEW

**Comment by nkzawa** [comment]
Looks awesome, thank you!

**Comment by impronunciable** [comment]
@nkzawa on my phone but I think that is not standardjs compatible

**Comment by pksjce** [comment]
@impronunciable - It wouldn't let me commit without `standardjs` passing. What fixes would you want. I can have another PR for it.

**Comment by nkzawa** [comment]
@impronunciable @pksjce I'm fixing

**Comment by nkzawa** [comment]
Fixed 9a78dd8d1c32ca4dbfef166e91d172ebe7708c4b

**Comment by impronunciable** [comment]
Oh probably you have warnings but no errors. We are not using semicolons
but it's not a big deal

**Comment by impronunciable** [comment]
And thanks for contributing!

**Pull request merged**
