### PR TITLE
(examples/with-i18n-next-intl): fixes warning 

### PR DESCRIPTION
**Pull request by akellbl4**
### Documentation / Examples

Fixed one of the items from #25854

- Fixes warning from `next-intl`
- Hides locale selector in case if no other location
- Fixes path `next/router` import 
- Removes unused variable

---

- [x] Add the StackBlitz button in README.md
- [x] Make sure the linting passes

[Live demo on StackBlitz](https://stackblitz.com/github/akellbl4/next.js/tree/fix/example-with-i18n-next-intl-missing-other/examples/with-i18n-next-intl)

### CODE REVIEW

**Comment by d3lm** [comment]
@akellbl4 Can you also add the StackBlitz button to the `README.md` if it works? Here's the snippet you can add:
```md
## Preview

Preview the example live on [StackBlitz](http://stackblitz.com/):

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-i18n-next-intl)
```

I have tested it on [your fork](https://stackblitz.com/github/akellbl4/next.js/tree/fix/example-with-i18n-next-intl-missing-other/examples/with-i18n-next-intl).

**Comment by akellbl4** [comment]
@d3lm as I can see this example already has the StackBlitz button.
https://github.com/vercel/next.js/tree/8347f77f008e2173967303e2b3ae0807a9d475b2/examples/with-i18n-next-intl

**Comment by d3lm** [comment]
Ohhh, good catch. Then forget what I said! 😂

**Review by ijjk — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
