### PR TITLE
Support `events` emitter for router

### LINKED ISSUE #4679: Document events interface for router?
# Feature request
Officially support & document `router.events`.

## Is your feature request related to a problem? Please describe.
I am creating a component that needs visibility into router events. There are some awkward global functions you can set, like `onRouteChangeComplete`, but it's difficult to use this interface in the case where that property is already set. There's no documented way to attach to and detach from events. However, it appears that there's an `EventEmitter` under an `events` property that is available and would be perfect for this scenario:

```jsx
import * as React from 'react';

class MyComponent extends React.Component {
  // ...

  componentDidMount() {
    this.props.router.events.on('routeChangeComplete', this.handleRouteChange);
  }

  componentWillUnmount() {
    this.props.router.events.off('routeChangeComplete', this.handleRouteChange);
  }
}
```

## Describe the solution you'd like
Is this `events` interface officially supported? If so, should that be added to the documentation? My fear for using any undocumented feature is that it may go away at any time.

## Describe alternatives you've considered
I briefly considered inspecting `Router.onRouteChangeComplete` functions to try to "add" a listener, but that is extremely hacky and doesn't lend itself well to multiple components subscribing/unsubscribing to events:

```js
const originalFn = Router.onRouteChangeComplete;
Router.onRouteChangeComplete = url => {
  originalFn(url);
  // The rest of the functionality
};

// Then later
Router.onRouteChangeComplete = originalFn; // Not really safe
```

### PR DESCRIPTION
**Pull request by DullReferenceException**
Fixes #4679 
* Document usage of `events` router property
* Expose `events` in the `router` context object

### CODE REVIEW

**Comment by timneutkens** [comment]
@DullReferenceException I've updated the PR description to have `Fixes #4679` so that GitHub will automatically close the issue on merge

**Comment by timneutkens** [comment]
Looks like this test is failing: https://github.com/zeit/next.js/pull/4726/files#diff-6c4702c4813088d1cc384a686e8543ecR33

**Comment by DullReferenceException** [comment]
@timneutkens: Fixed it (was a dumb usage of `Object.entries` which worked on my machine but not everywhere). Some remnants of speculative fixes are still here which I think make things a bit more resilient, but I can eject those if needed.

**Review by timneutkens — APPROVED** [review]
Looks great!

**Comment by jakemmarsh** [comment]
Any estimate as to when this change will be published @timneutkens?

**Comment by timneutkens** [comment]
Out on `next@canary` now 🙏

**Pull request merged**
