### PR TITLE
Upgrade amp optimizer to v2.8.0

### PR DESCRIPTION
**Pull request by sebastianbenz**
See [changelog](https://github.com/ampproject/amp-toolbox/releases/tag/v2.8.0).

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ac6d4550a73a9846afccf6897957e2ff965a3fa7

**test/integration/amphtml-custom-optimizer/test/index.test.js** 
- AMP Custom Optimizer > should build and start for static page
- AMP Custom Optimizer > should build and start for dynamic page

<details>
<summary>Expand output</summary>

  ● AMP Custom Optimizer › should build and start for static page

    command failed with code 1

      147 |         code !== 0
      148 |       ) {
    > 149 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      150 |       }
      151 |
      152 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:149:23)

  ● AMP Custom Optimizer › should build and start for dynamic page

    command failed with code 1

      147 |         code !== 0
      148 |       ) {
    > 149 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      150 |       }
      151 |
      152 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:149:23)

</details>

**Comment by sebastianbenz** [comment]
Not sure what's causing the test failures here. I get the same failures with the old version.

**Comment by sebastianbenz** [comment]
Ignore my previous comment, the old version works for me. I can reproduce this now locally. I get an error during compilation when running the tests:

```
wait  - compiling...
TypeError: Cannot read property 'call' of undefined
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704419)
    at Object.2043 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704049)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704419)
    at Object.3228 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:327368)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704419)
    at Object.2041 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:334361)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704419)
    at Object.4351 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:667316)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704419)
    at /Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704667
    at Object.1860 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704694)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:858294)
    at Object.5275 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:704737)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:858294)
    at Object.1053 (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:108455)
    at __nccwpck_require__ (/Users/sbenz/Projects/next.js/packages/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:858294)
event - compiled successfully
```

**Review by ijjk — COMMENTED** [review]
Closing in favor of the newer PR here https://github.com/vercel/next.js/pull/27106

**Pull request closed without merging**
