### PR TITLE
fix: function component type wrong

### PR DESCRIPTION
**Pull request by SyMind**
## Bug

function component `head` type wrong.

image

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5c329a12892e1735121c831dc5868b18fe4e6ef2

**test/integration/absolute-assetprefix/test/index.test.js** 
- absolute assetPrefix with path prefix > should not fetch static data from a CDN
- absolute assetPrefix with path prefix > should fetch from cache correctly
- absolute assetPrefix with path prefix > should work with getStaticPaths prerendered
- absolute assetPrefix with path prefix > should work with getStaticPaths fallback
- absolute assetPrefix with path prefix > should work with getServerSideProps

<details>
<summary>Expand output</summary>

  ● absolute assetPrefix with path prefix › should not fetch static data from a CDN

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should fetch from cache correctly

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths prerendered

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths fallback

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getServerSideProps

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      283 | export async function killApp(instance) {
      284 |   await new Promise((resolve, reject) => {
    > 285 |     treeKill(instance.pid, (err) => {
          |                       ^
      286 |       if (err) {
      287 |         if (
      288 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:285:23
      at killApp (lib/next-test-utils.js:284:9)
      at integration/absolute-assetprefix/test/index.test.js:65:18

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 54ed6826e850bffe08ae033e8bc2bee349d2b981

**test/integration/absolute-assetprefix/test/index.test.js** 
- absolute assetPrefix with path prefix > should not fetch static data from a CDN
- absolute assetPrefix with path prefix > should fetch from cache correctly
- absolute assetPrefix with path prefix > should work with getStaticPaths prerendered
- absolute assetPrefix with path prefix > should work with getStaticPaths fallback
- absolute assetPrefix with path prefix > should work with getServerSideProps

<details>
<summary>Expand output</summary>

  ● absolute assetPrefix with path prefix › should not fetch static data from a CDN

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should fetch from cache correctly

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths prerendered

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getStaticPaths fallback

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)

  ● absolute assetPrefix with path prefix › should work with getServerSideProps

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      283 | export async function killApp(instance) {
      284 |   await new Promise((resolve, reject) => {
    > 285 |     treeKill(instance.pid, (err) => {
          |                       ^
      286 |       if (err) {
      287 |         if (
      288 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:285:23
      at killApp (lib/next-test-utils.js:284:9)
      at integration/absolute-assetprefix/test/index.test.js:65:18

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9c4e7ddc578cc180a88778961310c59011bee30c

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    command failed with code 1

      139 |         code !== 0
      140 |       ) {
    > 141 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      142 |       }
      143 |
      144 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:141:23)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      317 |
      318 | export async function stopApp(server) {
    > 319 |   if (server.__app) {
          |              ^
      320 |     await server.__app.close()
      321 |   }
      322 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:319:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2bb18742f752132d60ca6918c59f88063e7b199f

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    command failed with code 1

      147 |         code !== 0
      148 |       ) {
    > 149 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      150 |       }
      151 |
      152 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:149:23)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      325 |
      326 | export async function stopApp(server) {
    > 327 |   if (server.__app) {
          |              ^
      328 |     await server.__app.close()
      329 |   }
      330 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:327:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2bb18742f752132d60ca6918c59f88063e7b199f

**test/integration/auto-export-error-bail/test/index.test.js** 
- Auto Export _error bail > server mode > should not opt-out of auto static optimization from invalid _error
- Auto Export _error bail > serverless mode > should not opt-out of auto static optimization from invalid _error

<details>
<summary>Expand output</summary>

  ● Auto Export _error bail › server mode › should not opt-out of auto static optimization from invalid _error

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      22 |     const combinedOutput = output.stderr + output.stdout
      23 |
    > 24 |     expect(output.code).toBe(0)
         |                         ^
      25 |     expect(combinedOutput).not.toContain(
      26 |       'You have opted-out of Automatic Static Optimization due to'
      27 |     )

      at Object.<anonymous> (integration/auto-export-error-bail/test/index.test.js:24:25)

  ● Auto Export _error bail › serverless mode › should not opt-out of auto static optimization from invalid _error

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      22 |     const combinedOutput = output.stderr + output.stdout
      23 |
    > 24 |     expect(output.code).toBe(0)
         |                         ^
      25 |     expect(combinedOutput).not.toContain(
      26 |       'You have opted-out of Automatic Static Optimization due to'
      27 |     )

      at Object.<anonymous> (integration/auto-export-error-bail/test/index.test.js:24:25)

</details>

**Comment by SyMind** [comment]
@divmain @lfades Someone can give me a help?

**Comment by lfades** [comment]
@SyMind Do you have an issue that's linked to this PR or an use case example? The error looks fine to me, you can't use `<Head></Head>` without providing children

**Comment by ijjk** [comment]
I'm gonna close this as it appears to not be an issue, if you are still running into problems with this feel free to reply with additional info and we can investigate this further!

**Pull request closed without merging**
