### PR TITLE
Update examples to use React 18

### PR DESCRIPTION
**Pull request by buzuosheng**
Update repo to use react 18 by default: https://github.com/vercel/next.js/pull/35888

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]
Thanks!

**Review by balazsorban44 — DISMISSED** [review]
Thanks!

**Comment by shfshanyue** [comment]
Thanks，it's helpful to me, and when to merge it.

**Comment by balazsorban44** [comment]
There is a new version (`18.1.0`) out, could you update to that and fix the merge conflicts? I can re-approve after that. :+1:

**Comment by buzuosheng** [comment]
I've done this

**Comment by balazsorban44** [comment]
@buzuosheng `18.2.0` is out now, could you update again and resolve merge conflicts, and ping me, and I'll try to merge this as quickly as possible to avoid conflicts with other PRs changing the examples folder?

**Comment by balazsorban44** [comment]
Given the high likelihood of merge conflicts, let's address this gradually rather than in one PR. Examples should ideally be tested when these dependencies are updated. :+1: Thanks for working on this anyway! :pray: :green_heart:

**Pull request closed without merging**
