### PR TITLE
Update json5 dependency to latest

### PR DESCRIPTION
**Pull request by ijjk**
Updates to latest version of the dependency.

### CODE REVIEW

**Comment by eastwood** [comment]
Legend, came here to do this!

**Comment by eastwood** [comment]
Potentially still have issues via sub dependencies though:

image

**Comment by ijjk** [comment]
That will need to be addressed upstream in https://github.com/import-js/eslint-plugin-import although isn't high urgency as the files it's loading are from the local filesystem and should not be from an untrusted source.

**Comment by eastwood** [comment]
Agreed :) Leaving the breadcrumb for others to follow :) Thanks mate

**Pull request merged**
