### PR TITLE
Update CNA build target in tsconfig

### PR DESCRIPTION
**Pull request by matamatanot**
## Feature

- [ ] Telemetry added. In case of a feature if it's used or not.

### Change `compilerOptions.target` "es2015" to "es2019"

You can update the target as Next.js is now only supported in Node 12 or later. This is expected to reduce the build size and improve performance.

The official TypeScript wiki is as follows.
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-12

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.9s | ⚠️ +85ms |
| buildDurationCached | 2.7s | 2.7s | -15ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.172 | 2.211 | ⚠️ +0.04 |
| / avg req/sec | 1150.76 | 1130.54 | ⚠️ -20.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.108 | 1.095 | -0.01 |
| /error-in-render avg req/sec | 2256.45 | 2283.2 | +26.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| index.html gzip | 571 B | 571 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 567 B | 567 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.4s | -72ms |
| buildDurationCached | 3.7s | 3.7s | ⚠️ +30ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | -4 B |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | -2 B |
| withRouter.js | 17.4 kB | 17.4 kB | ⚠️ +2 B |
| Overall change | 107 kB | 107 kB | -4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.6s | ⚠️ +18ms |
| buildDurationCached | 3.9s | 3.9s | -56ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.216 | 2.261 | ⚠️ +0.04 |
| / avg req/sec | 1128.34 | 1105.86 | ⚠️ -22.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.135 | 1.146 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2202.1 | 2182.4 | ⚠️ -19.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.16 kB | 9.16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| index.html gzip | 626 B | 626 B | ✓ |
| link.html gzip | 632 B | 632 B | ✓ |
| withRouter.html gzip | 620 B | 620 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: fcac8f00677c2243af363301c75579bf15f22151

**Comment by ijjk** [comment]
## Failing test suites 
Commit: fcac8f00677c2243af363301c75579bf15f22151

**test/integration/rewrite-with-browser-history/test/index.test.js** 
- rewrites persist with browser history actions > dev mode > back-button should go back to rewritten path successfully

<details>
<summary>Expand output</summary>

  ● rewrites persist with browser history actions › dev mode › back-button should go back to rewritten path successfully

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#another"}
      (Session info: headless chrome=91.0.4472.77)

      33 |     await browser.back()
      34 |
    > 35 |     expect(await browser.elementByCss('#another').text()).toBe('another page')
         |            ^
      36 |
      37 |     expect(await browser.eval('window.beforeNav')).toBe(1)
      38 |   })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/rewrite-with-browser-history/test/index.test.js:35:12)

</details>

**Review by timneutkens — CHANGES_REQUESTED** [review]
This is es2015 because Next.js outputs JS compatible with IE11 currently. It can be changed in the near future but it'll require more work than just changing this target. The target is not used by Next.js btw, it's only there to ensure your editor knows what the output is like.

**Comment by matamatanot** [comment]
@timneutkens 
It is `create-next-app`, not `next`, and it seems that the build target of the cli tool does not need to cover IE11.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +28ms |
| buildDurationCached | 3.6s | 3.3s | -323ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.995 | 2.844 | -0.15 |
| / avg req/sec | 834.76 | 879.05 | +44.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.703 | 1.648 | -0.06 |
| /error-in-render avg req/sec | 1467.7 | 1516.76 | +49.06 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| index.html gzip | 572 B | 572 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 567 B | 567 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 16s | 15.4s | -680ms |
| buildDurationCached | 4.3s | 4.4s | ⚠️ +66ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ⚠️ +2 B |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ⚠️ +2 B |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ⚠️ +4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.2s | -338ms |
| buildDurationCached | 4.8s | 4.7s | -108ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.884 | 2.865 | -0.02 |
| / avg req/sec | 866.84 | 872.5 | +5.66 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.619 | 1.703 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1544.13 | 1467.73 | ⚠️ -76.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.16 kB | 9.16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js update-CNA-tsconfig-build-target | Change |
| - | - | - | - |
| index.html gzip | 627 B | 627 B | ✓ |
| link.html gzip | 633 B | 633 B | ✓ |
| withRouter.html gzip | 620 B | 620 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: 1a0d66943058f527c288d7a126f326e0c3caa00a

**Comment by timneutkens** [comment]
Ah yeah you're right, sorry I missed that it's not the template but the root tsconfig.

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
