### PR TITLE
Added side note about enabling gzip on Koa

### PR DESCRIPTION
**Pull request by mmazzarolo**
I'll share this small snippet here, it might be useful.

### CODE REVIEW

**Comment by ilionic** [comment]
Thanks! Spend so much time trying to figure it out. Ended up using compression on CDN

**Comment by ilionic** [comment]
Same here, though ended up using CloudFront as didn't require DNS re-configuration and changing nameservers.

**Review by timneutkens — APPROVED** [review]
Nice!

**Comment by jaydenseric** [comment]
I think if you deploy with Zeit Now you do not need to manage compression manually. I just checked and all requests have `content-encoding:br`.

**Comment by timneutkens** [comment]
@jaydenseric indeed

**Comment by ilionic** [comment]
Not on Now, but on Heroku extra trickery required.

**Pull request merged**
