### PR TITLE
Pulled encoding to top of head

### LINKED ISSUE #3210: <link rel='preload' ..> before <meta charset="utf-8">
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
`<meta charset="utf-8">` should be the first element in the `<head>`

## Current Behavior
`<NextScript />` prepends the preloadDynamicChunks in the head.
https://github.com/zeit/next.js/blob/canary/server/document.js#L87

## Context
https://sonarwhal.com/docs/user-guide/rules/meta-charset-utf-8/

## Your Environment
| Tech    | Version |
|---------|---------|
| next    |    4.1.3    |
| node    |   8.4.0   |

### PR DESCRIPTION
**Pull request by yashha**
Moves `<meta charset="utf-8">` to top of head
Closes #3210

### CODE REVIEW

**Comment by timneutkens** [comment]
This will pull all `next/head` items to the top of the `<head>` I'm not sure if that affects the preload tags. cc @arunoda

**Comment by arunoda** [comment]
@timneutkens I don't think that affects. It only affects when the user has defined some scripts/css via head.

But if we can only pick meta tags from the head and move it to the top, that'll be the ideal.

**Comment by yashha** [comment]
@arunoda true, that would be better

**Comment by yashha** [comment]
Closed for new pr asp

**Review by timneutkens — COMMENTED** [review]
Lets get this in 👍 We can change this around later if needed.

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
