### PR TITLE
fix: avoid race condition when download swc wasm

### PR DESCRIPTION
**Pull request by d3lm**
### What?

I noticed that code that was responsible for download the SWC Wasm fallback wasn't bullet proof and there was a chance for a race condition. The reason was that both `write` and `close` from a write stream are async operations and it's best to wait for them to complete, otherwise the promise returned from `body.pipeTo` could resolve before all data has been written and the stream was closed. Right after that it calls `rename` and it could happen that, at that point, `tempFile` doesn't contain all the data yet which means an empty file may be renamed into another file ending up with `path.join(cacheDirectory, tarFileName)` being empty as well.

The fix is to wait for both `write` and `close` to be completed which eliminates the potential race condition between the fetch and the rename.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 13af30b355d7e639d84680af61bf50d2df779f64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 13af30b355d7e639d84680af61bf50d2df779f64

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.1s | N/A |
| buildDurationCached | 5.9s | 5.9s | N/A |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 418ms | 418ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| 199-HASH.js gzip | 28.8 kB | 28.8 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | N/A |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 46.9 kB | 46.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 506 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.3 kB | 4.3 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.63 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| index.html gzip | 528 B | 526 B | N/A |
| link.html gzip | 539 B | 539 B | ✓ |
| withRouter.html gzip | 525 B | 521 B | N/A |
| Overall change | 539 B | 539 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.6 kB | 92.6 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | ✓ |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 26.7 kB | 26.7 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | d3lm/next.js delm/fix/downloading-of-wasm | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | N/A |
| app-page-exp..prod.js gzip | 93.4 kB | 93.3 kB | N/A |
| app-page-tur..prod.js gzip | 94.1 kB | 94.1 kB | N/A |
| app-page-tur..prod.js gzip | 88.7 kB | 88.7 kB | N/A |
| app-page.run...dev.js gzip | 137 kB | 137 kB | N/A |
| app-page.run..prod.js gzip | 88 kB | 88 kB | N/A |
| app-route-ex...dev.js gzip | 23.8 kB | 23.8 kB | N/A |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | N/A |
| app-route-tu..prod.js gzip | 16.5 kB | 16.4 kB | N/A |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | N/A |
| app-route.ru...dev.js gzip | 23.2 kB | 23.2 kB | N/A |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | N/A |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| server.runti..prod.js gzip | 49.1 kB | 49 kB | N/A |
| Overall change | 94.6 kB | 94.6 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>199-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 13af30b355d7e639d84680af61bf50d2df779f64

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 13af30b355d7e639d84680af61bf50d2df779f64

`pnpm test-dev test/e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts` 
- app-dir action allowed origins > should pass if localhost is set as a safe origin

<details>
<summary>Expand output</summary>

  ● app-dir action allowed origins › should pass if localhost is set as a safe origin

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      240 |   let next: NextInstance
      241 |   if (!skipped) {
    > 242 |     beforeAll(async () => {
          |     ^
      243 |       next = await createNext(options)
      244 |     })
      245 |     afterAll(async () => {

      at beforeAll (lib/e2e-utils.ts:242:5)
      at nextTestSetup (lib/e2e-utils.ts:302:21)
      at describe (lib/e2e-utils.ts:301:3)
      at Object.<anonymous> (e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts:5:19)


  ● Test suite failed to run

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      115 |
      116 | if (typeof afterAll === 'function') {
    > 117 |   afterAll(async () => {
          |   ^
      118 |     if (nextInstance) {
      119 |       await nextInstance.destroy()
      120 |       throw new Error(

      at Object.afterAll (lib/e2e-utils.ts:117:3)
      at Object.<anonymous> (e2e/app-dir/actions-allowed-origins/app-action-allowed-origins.test.ts:5:19)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ForsakenHarmony — APPROVED** [review]
LGTM

probably a better way to convert the streams with `Writable.toWeb` or `Readable.fromWeb`, but this should work and I don't think it matters

**Pull request merged**
