### PR TITLE
update storybook example (copy from vercel/vercel)

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Updates the `with-storybook` example to be the example located in [`vercel/vercel`](https://github.com/vercel/vercel/tree/main/examples/storybook). 

The motivation for this change is that we now have better support for storybook. It is now treated as its own framework and so users can specify the `storybook` framework as well as custom build command `build-storybook` in order to get near zero-config support 🌟

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
If we're wanting to keep these examples in sync we should probably link one to other so there's a single source of truth

**Comment by Ethan-Arrowood** [comment]
Which should be source? I like that you can use this with `create-next-app`.  So we should make this one the source?

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 49cd139018c22fbfc5df00094037f9f9c6f416a1

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 49cd139018c22fbfc5df00094037f9f9c6f416a1

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
This one being source of truth sounds good to me

**Review by ijjk — DISMISSED** [review]

**Review by ijjk — APPROVED** [review]

**Pull request merged**
