### PR TITLE
move static worker IPC server behind experimental flag

### LINKED ISSUE #53695: build will yield "Failed to set fetch cache"
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.0
      npm: 9.8.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/

### To Reproduce

"npm run build" with 13.4.13 will yield "Failed to set fetch cache" for some fetch calls.
the same code works fine in 13.4.12.

### Describe the Bug

"npm run build" with 13.4.13 will yield "Failed to set fetch cache" for some fetch calls.
the same code works fine in 13.4.12.

### Expected Behavior

should be the same as in 13.4.12

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ztanner**
A shared incremental cache IPC server was introduced for build-time static workers as an optimization to dedupe fetch requests, however this can cause fetch-related flakiness to builds under certain conditions (e.g., large payloads).

This moves the optimization behind an experimental flag to unblock those running into IPC-related build time errors while we work on an alternative solution for the underlying issue

Fixes #53695

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 21f682097004fad7620c22d0bf6a297e0e0b9602

`pnpm test-start test/e2e/config-schema-check/index.test.ts` 
- next.config.js schema validating - defaultConfig > should validate against defaultConfig

<details>
<summary>Expand output</summary>

  ● next.config.js schema validating - defaultConfig › should validate against defaultConfig

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "Invalid next.config.js options detected"
    Received string:        "yarn run v1.22.19
    $ /tmp/next-install-d55017509c2c4f36dd37b9d75766794855ffc34a92787dab432f29a86e0f2bad/node_modules/.bin/next build
     ⚠ Invalid next.config.js options detected: 
     ⚠     Unrecognized key(s) in object: 'staticWorkerRequestDeduping' at \"experimental\"
     ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
       Linting and checking validity of types ...
       ▲ Next.js 14.0.2-canary.6

       Creating an optimized production build ...
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/3) ...

     ✓ Generating static pages (3/3) 
       Finalizing page optimization ...
       Collecting build traces ...

    Route (pages)                              Size     First Load JS
    ┌ ○ /                                      261 B          79.8 kB
    └ ○ /404                                   182 B          79.7 kB
    + First Load JS shared by all              79.5 kB
      ├ chunks/framework-f4c775695db2e078.js   45.5 kB
      ├ chunks/main-917c3d3c1f17b185.js        33.1 kB
      ├ chunks/pages/_app-0cdded4608fb797f.js  205 B
      └ chunks/webpack-7d45971437c161ca.js     728 B

    ○  (Static)  prerendered as static content

    Done in 11.68s.
    yarn run v1.22.19
    $ /tmp/next-install-d55017509c2c4f36dd37b9d75766794855ffc34a92787dab432f29a86e0f2bad/node_modules/.bin/next start
       ▲ Next.js 14.0.2-canary.6
       - Local:        http://localhost:37809

    "

      24 |       const output = stripAnsi(next.cliOutput)
      25 |
    > 26 |       expect(output).not.toContain('Invalid next.config.js options detected')
         |                          ^
      27 |     })
      28 |   }
      29 | )

      at Object.toContain (e2e/config-schema-check/index.test.ts:26:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.5s | ⚠️ +102ms |
| buildDurationCached | 6.7s | 7.3s | ⚠️ +679ms |
| nodeModulesSize | 175 MB | 175 MB | ⚠️ +3.23 kB |
| nextStartRea..uration (ms) | 429ms | 430ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33.1 kB | 33.1 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.71 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.06 kB | 1.06 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.4 kB | 96.4 kB | N/A |
| page.js gzip | 141 kB | 141 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/static-ipc-experimental | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 626 B | ✓ |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | ✓ |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 27.4 kB | 27.4 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 21f682097004fad7620c22d0bf6a297e0e0b9602

**Review by ijjk — APPROVED** [review]

**Review by feedthejim — APPROVED** [review]

**Comment by franky47** [comment]
Thanks for this fix!

Regarding the underlying issue, could it help to use a POST endpoint to set the cache instead of the current GET with payload in the URL, as shown in this [comment](https://github.com/vercel/next.js/issues/53695#issuecomment-1745613090)?

**Comment by telackey** [comment]
There is another issue about experimental-generate and the incremental-cache-server here: https://discord.com/channels/752553802359505017/1172259310290612384

It isn't a true fix, so much as a workaround, since if the cache server is not started it cannot hang.  The true fix would be to call ipcServer.close() when the build is done.  I may open a PR, but it was worth mentioning here.

**Pull request merged**
