### PR TITLE
Guard useSwr() to avoid sending invalid request

### PR DESCRIPTION
**Pull request by michael**
Took me a while to figure out why the combination of useRouter and useSwr creates an unnecessary request, due to the router not being initialised. I think applying this patch would save new Next.js users (like me) running into this problem, and understand the nature of hooks better.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.5s | -46ms |
| nodeModulesSize | 83 MB | 83 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.339 | 2.315 | -0.02 |
| / avg req/sec | 1068.77 | 1079.91 | +11.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.645 | 1.685 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1519.97 | 1483.62 | ⚠️ -36.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dbe2.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-212f85f..f23b.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-b862cd7..dba8.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 610 B | 610 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.7s | ⚠️ +86ms |
| nodeModulesSize | 83 MB | 83 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dbe2.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-212f85f..f23b.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-b862cd7..dba8.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: 6f51d0bf527d89e20555281e07348403bbce6aea

**Comment by michael** [comment]
In that context, what is the reasoning behind favoring useRouter over props.url? That problem I had wouldn't exist if the the `id` of the route would be available immediately.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 9.1s | 8.9s | -213ms |
| nodeModulesSize | 83 MB | 83 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.794 | 1.758 | -0.04 |
| / avg req/sec | 1393.15 | 1421.96 | +28.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.155 | 1.131 | -0.02 |
| /error-in-render avg req/sec | 2165.21 | 2210.44 | +45.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dbe2.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-212f85f..f23b.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-b862cd7..dba8.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 610 B | 610 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.8s | ⚠️ +307ms |
| nodeModulesSize | 83 MB | 83 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..dbe2.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-212f85f..f23b.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-b862cd7..dba8.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | michael/next.js patch-1 | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: b8d54d6bd6d3d1cd4e3620cc60b9c96eecc6f3b2

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 9.1s | 9.1s | ⚠️ +5ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.792 | 1.783 | -0.01 |
| / avg req/sec | 1394.92 | 1402.42 | +7.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.131 | 1.174 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2209.5 | 2129.5 | ⚠️ -80 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..396f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-d74fce9..a1a1.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.9s | ⚠️ +144ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..396f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-d74fce9..a1a1.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | c316/next.js patch-1 | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: 16b574be35ea8b99aa5b60b4d630ee7723fbf8ce

**Review by Timer — APPROVED** [review]

**Pull request merged**
