### PR TITLE
Rename more references to "use client"

### PR DESCRIPTION
**Pull request by sebmarkbage**
I found a number of references to the old `"client"` directive name. Should these be updated?

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
Looks like the branch here is behind and these are already updated in latest canary x-ref: https://github.com/vercel/next.js/blob/7be2ef0fcf920fccd28f05effa8075dcbdc8896d/packages/next-swc/crates/core/src/react_server_components.rs#L97

**Comment by huozhi** [comment]
I have updated them in https://github.com/vercel/next.js/pull/41333

**Review by shuding — APPROVED** [review]
~@huozhi did you do global search and replace?~

Just saw your comment above

**Comment by sebmarkbage** [comment]
Hm. Nvm. Something going on with my local branch failing to fetch.

**Pull request closed without merging**
