### PR TITLE
examples: replaced GTM component with GA in Google Analytics example

### PR DESCRIPTION
**Pull request by suu3**
### What?
Replaced the `GoogleTagManager` component with `GoogleAnalytics` in the `with-google-analytics` example.

### Why?
The current implementation does not align with the [docs](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-analytics), and a separate GTM example already exists.

### How?
Replaced the `GoogleTagManager` component with `GoogleAnalytics`.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: cbe962875c027fdf0b82fe8ef307f9cd7a09ed9b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by suu3** [comment]
@samcx Hello, would you mind reviewing this PR if you have a moment?

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by suu3** [comment]
Thank you!

**Pull request merged**
