### PR TITLE
Make sure to handle improperly encoded URLs

### PR DESCRIPTION
**Pull request by ijjk**
When an improperly encoded URL is visited such as `http://localhost:3000/%` it causes an error to be thrown from failing to decode the URL params. 

```sh
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /Users/jj/dev/zeit/next.js/test/integration/dynamic-routing/.next/serverless/pages/[name].js:776:114
    at Array.forEach (<anonymous>)
    at /Users/jj/dev/zeit/next.js/test/integration/dynamic-routing/.next/serverless/pages/[name].js:771:25
    at renderReqToHTML (/Users/jj/dev/zeit/next.js/test/integration/dynamic-routing/.next/serverless/pages/[name].js:4184:84)
    at Module.render (/Users/jj/dev/zeit/next.js/test/integration/dynamic-routing/.next/serverless/pages/[name].js:4265:28)
```

To handle this gracefully this implements the [safe-decode-uri-component](https://www.npmjs.com/package/safe-decode-uri-component) package. I added the initial URL that showed this behavior as a test in the dynamic-routing suite, if there are others that should be added let me know and we can get them tested also

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build
- Production response size > should not increase the overall response size of modern build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    2192

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 257 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

  ● Production response size › should not increase the overall response size of modern build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    2297

      102 |     // These numbers are without gzip compression!
      103 |     const delta = responseSizesBytes - 165 * 1024
    > 104 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
          |                   ^
      105 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      106 |   })
      107 | })

      at Object.<anonymous> (integration/size-limit/test/index.test.js:104:19)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build
- Production response size > should not increase the overall response size of modern build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    2192

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 257 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

  ● Production response size › should not increase the overall response size of modern build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    2297

      102 |     // These numbers are without gzip compression!
      103 |     const delta = responseSizesBytes - 165 * 1024
    > 104 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
          |                   ^
      105 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      106 |   })
      107 | })

      at Object.<anonymous> (integration/size-limit/test/index.test.js:104:19)

</details>

**Review by timneutkens — CHANGES_REQUESTED** [review]
We should just render a 404 when that particular error happens instead of introducing another package.

**Review by Timer — CHANGES_REQUESTED** [review]
Let's leave this a 400 and fix for serverless. Please remove this additional dep.

**Comment by ijjk** [comment]
Closing in favor of new PR

**Pull request closed without merging**
