### PR TITLE
Update middleware.md

### PR DESCRIPTION
**Pull request by hamatoyogi**
use correct filename (`_middleware`)

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Hi, this is correct as is and the filename should be `middleware.ts`

**Comment by hamatoyogi** [comment]
> Hi, this is correct as is and the filename should be `middleware.ts`

Could be my mistake... But got this warning:
image

**Comment by ijjk** [comment]
Hmm it looks like you may need to update your `eslint-config-next` as that rule has been updated

**Comment by hamatoyogi** [comment]
Still getting it after update @ijjk ...

**Comment by ijjk** [comment]
It may require restarting any lint services after updating, the rule was removed in https://github.com/vercel/next.js/pull/38028

**Pull request closed without merging**
