### PR TITLE
Create example using custom charset

### PR DESCRIPTION
**Pull request by goldensunliu**
https://github.com/zeit/next.js/issues/3401

### CODE REVIEW

**Comment by goldensunliu** [comment]
the most minimal server example that sets a custom charset.

**Review by arunoda — APPROVED** [review]
This is great.

**Comment by goldensunliu** [comment]
@arunoda shall we close https://github.com/zeit/next.js/issues/3401?

**Comment by arunoda** [comment]
Yes sure.

**Pull request merged**
