### PR TITLE
Examples/payload cms 2.0

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
### Adding or Updating Examples

This PR updates the examples/cms-payload to use Payload 2.0. Also removes the need for [this PR](https://github.com/vercel/next.js/pull/56590) as this was fixed in a later version of Payload internally.

- [x] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- [x] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### CODE REVIEW

**Review by leerob — APPROVED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d8eb42b20579d3eb97643e35218ffc3a43893ab4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d8eb42b20579d3eb97643e35218ffc3a43893ab4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Looks like linting is failing here 🙏

**Comment by JarrodMFlesch** [comment]
@leerob pushed the lint fixes 👍

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Closing this is stale since there's merge conflicts. If you want to open a new PR, please let me know! Maybe for Payload 3 👀

**Pull request closed without merging**
