### PR TITLE
Handle BUILD_ID mismatch error

### PR DESCRIPTION
**Pull request by arunoda**
Provide a hook to handle the BuildID Mismatch error.
If the hook is not provided we'll throw an error like below.

screen shot 2017-02-21 at 3 23 51 am

It'll ask to visit [this wiki page](https://github.com/zeit/next.js/wiki/Handle-BUILD_ID-Mismatch-Error) for more information.

### CODE REVIEW

**Comment by nkzawa** [comment]
I think we can navigate pages with normal browser transition as default instead of `pushState` in this case. This wouldn't trigger Infinite loop.

Additionally, we can provide a way to replace this behavior like `onBuildIDMismatch((e) => e.preventDefault())`.

**Comment by arunoda** [comment]
@nkzawa That's something pretty cool.

**Comment by arunoda** [comment]
Anyway, again it's the same as writing `location.reload()` in the `onBuildIdMismatch()` hook.
@rauchg what do you think?

**Comment by nkzawa** [comment]
@arunoda It looks `location.reload()` is not the same since `onBuildIdMismatch` is called before url change on `push`.

**Comment by arunoda** [comment]
@nkzawa yep. I mentioned it on the comment. 

May be we could pass the next page URL to the hook.
Why we go with this approach is this might reset the client state of the app.
So, it's a user's responsibility.

**Comment by nkzawa** [comment]
btw `onBuildIdMismatch`  can be `onAppUpdateDetected` or something ? I think users don't need to know what `BuildID` is.

**Comment by rauchg** [comment]
@nkzawa the only issue with that is that it implies _new_ code, while we can't really guarantee that. You could have rolled back to an old version for example

**Comment by arunoda** [comment]
> You could have rolled back to an old version for example

I'm quite not sure about this.
User need to only intervene to perisist and restore the client state.

**Pull request merged**
