### PR TITLE
Updates with-supertokens example app

### PR DESCRIPTION
**Pull request by rishabhpoddar**
Change with-supertokens example app to use app dir.

### CODE REVIEW

**Review by leerob — DISMISSED** [review]

**Comment by rishabhpoddar** [comment]
@leerob thanks for pointing those issues out. I have pushed a fix.

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Now needs Prettier ran...

**Comment by rishabhpoddar** [comment]
I had run `pnpm lint-fix && pnpm prettier-fix` and there were no file changes. Plus the pre commit hook passed all checks. Is there another command I missed?

**Comment by rishabhpoddar** [comment]
Any updates on this please? Thanks.

**Pull request merged**
