### PR TITLE
Fix Script beforeInteractive on navigation

### LINKED ISSUE #26342: next/script is not loading when navigating between pages
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

`next/script` is not loading when navigating between pages with `next/link`, only if you load or reload the page outside of the SPA

### Expected Behavior

the `next/script` load normally

### To Reproduce

1. `npx create-next-app`
2. create any page, put a script url to load
3. create a navigation (next/link) to the created page
4. navigate to the page

**index.js:**
```
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Link href="/script" passHref><a>navigate to script</a></Link>
    </div>
  )
}
```
**script.js:**
```
import React from "react";
import Script from "next/script";

export default function script() {
  return (
    <>
      <Script key="script_from_url" id="script_from_url" src="http://localhost:3000/script.js" strategy="beforeInteractive" onLoad={() => console.log("script loaded")} />
      <div>script</div>
    </>
  );
}
```

Notes:
1. `onLoad` is not being activated at any time with strategy `beforeInteractive`
2. I am getting this error on the console when the script is first loaded (even though I put key and id in the `Script` props):

**Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.**

### PR DESCRIPTION
**Pull request by janicklas-ralph**
## Bug

- [x] fixes #26342 
- [x] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.5s | ⚠️ +385ms |
| buildDurationCached | 3.6s | 3.6s | -7ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +107 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.392 | 2.499 | ⚠️ +0.11 |
| / avg req/sec | 1045.14 | 1000.56 | ⚠️ -44.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.384 | 1.348 | -0.04 |
| /error-in-render avg req/sec | 1806.93 | 1854.61 | +47.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.6 kB | 20.6 kB | ⚠️ +4 B |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14 kB | 14 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 531 B | 530 B | -1 B |
| link.html gzip | 544 B | 543 B | -1 B |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3184,6 +3184,8 @@
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-fe07bb49b17c0e304399.js"
+      src="/_next/static/chunks/main-059b24d7c5abea7a799b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-fe07bb49b17c0e304399.js"
+      src="/_next/static/chunks/main-059b24d7c5abea7a799b.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-fe07bb49b17c0e304399.js"
+      src="/_next/static/chunks/main-059b24d7c5abea7a799b.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +124ms |
| buildDurationCached | 4.9s | 4.8s | -167ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +107 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.504 | 2.468 | -0.04 |
| / avg req/sec | 998.22 | 1012.87 | +14.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.409 | 1.366 | -0.04 |
| /error-in-render avg req/sec | 1774.78 | 1830.45 | +55.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.81 kB | 7.81 kB | ⚠️ +4 B |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.8 kB | 67.8 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.98 kB | 8.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 575 B | 576 B | ⚠️ +1 B |
| link.html gzip | 586 B | 587 B | ⚠️ +1 B |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -261,6 +261,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-7f22b8d0bd46af702624.js"
+      src="/_next/static/chunks/main-a9fe097496b4fb7121d9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-7f22b8d0bd46af702624.js"
+      src="/_next/static/chunks/main-a9fe097496b4fb7121d9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-7f22b8d0bd46af702624.js"
+      src="/_next/static/chunks/main-a9fe097496b4fb7121d9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 1a7a9830f34e015cb26683e43c3a9e538f3244e6

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1a7a9830f34e015cb26683e43c3a9e538f3244e6

**test/integration/script-loader/test/index.test.js** 
- Script Loader > priority afterInteractive

<details>
<summary>Expand output</summary>

  ● Script Loader › priority afterInteractive

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      50 |         expect(script).toBeDefined()
      51 |         // Script is inserted at the end
    > 52 |         expect(endScripts.length).toBe(0)
         |                                   ^
      53 |       }
      54 |
      55 |       // afterInteractive script in page

      at test (integration/script-loader/test/index.test.js:52:35)
      at Object.<anonymous> (integration/script-loader/test/index.test.js:56:7)

</details>

**Review by timneutkens — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 16.8s | 16.4s | -324ms |
| buildDurationCached | 3.8s | 3.7s | -88ms |
| nodeModulesSize | 49.4 MB | 49.4 MB | ⚠️ +105 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.992 | 2.836 | -0.16 |
| / avg req/sec | 835.52 | 881.51 | +45.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.748 | 1.757 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1430.12 | 1422.48 | ⚠️ -7.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ⚠️ +4 B |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13.9 kB | 13.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 417 B | 417 B | ✓ |
| Overall change | 417 B | 417 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 526 B | 524 B | -2 B |
| Overall change | 1.6 kB | 1.6 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3251,6 +3251,8 @@
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-73bef1d47947e4269935.js"
+      src="/_next/static/chunks/main-ecdf9f1243947a1527f5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-73bef1d47947e4269935.js"
+      src="/_next/static/chunks/main-ecdf9f1243947a1527f5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-73bef1d47947e4269935.js"
+      src="/_next/static/chunks/main-ecdf9f1243947a1527f5.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.9s | -204ms |
| buildDurationCached | 5.2s | 5.1s | -102ms |
| nodeModulesSize | 49.4 MB | 49.4 MB | ⚠️ +105 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.846 | 2.79 | -0.06 |
| / avg req/sec | 878.5 | 896.18 | +17.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.702 | 1.679 | -0.02 |
| /error-in-render avg req/sec | 1468.44 | 1488.82 | +20.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 14.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.39 kB | 8.39 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68 kB | 68 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.93 kB | 8.93 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 574 B | 576 B | ⚠️ +2 B |
| link.html gzip | 588 B | 589 B | ⚠️ +1 B |
| withRouter.html gzip | 568 B | 569 B | ⚠️ +1 B |
| Overall change | 1.73 kB | 1.73 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -648,6 +648,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8468fd79d73f63828ca8.js"
+      src="/_next/static/chunks/main-2ac34bc6e4d7741a2daf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8468fd79d73f63828ca8.js"
+      src="/_next/static/chunks/main-2ac34bc6e4d7741a2daf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8468fd79d73f63828ca8.js"
+      src="/_next/static/chunks/main-2ac34bc6e4d7741a2daf.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 0088def77f4071a4f353d529e77a78fc13f46569

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 15.7s | 16.2s | ⚠️ +539ms |
| buildDurationCached | 3.7s | 3.4s | -228ms |
| nodeModulesSize | 49.4 MB | 49.4 MB | ⚠️ +105 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.817 | 2.79 | -0.03 |
| / avg req/sec | 887.5 | 895.96 | +8.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.64 | 1.605 | -0.03 |
| /error-in-render avg req/sec | 1524.24 | 1557.57 | +33.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.9 kB | 20.9 kB | ⚠️ +4 B |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.6 kB | 5.6 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13.9 kB | 13.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 417 B | 417 B | ✓ |
| Overall change | 417 B | 417 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 531 B | 529 B | -2 B |
| link.html gzip | 545 B | 543 B | -2 B |
| withRouter.html gzip | 526 B | 523 B | -3 B |
| Overall change | 1.6 kB | 1.59 kB | -7 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3251,6 +3251,8 @@
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-97d1ae727580da3f23c3.js"
+      src="/_next/static/chunks/main-3c34c120970fcdede460.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-97d1ae727580da3f23c3.js"
+      src="/_next/static/chunks/main-3c34c120970fcdede460.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-97d1ae727580da3f23c3.js"
+      src="/_next/static/chunks/main-3c34c120970fcdede460.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.3s | -26ms |
| buildDurationCached | 5s | 4.8s | -259ms |
| nodeModulesSize | 49.4 MB | 49.4 MB | ⚠️ +105 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.793 | 2.7 | -0.09 |
| / avg req/sec | 894.95 | 925.77 | +30.82 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.635 | 1.668 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1529.16 | 1498.97 | ⚠️ -30.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| 14.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.39 kB | 8.39 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68 kB | 68 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 230 B | 230 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 297 B | 297 B | ✓ |
| withRouter-HASH.js gzip | 293 B | 293 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.93 kB | 8.93 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js script | Change |
| - | - | - | - |
| index.html gzip | 576 B | 576 B | ✓ |
| link.html gzip | 590 B | 590 B | ✓ |
| withRouter.html gzip | 568 B | 569 B | ⚠️ +1 B |
| Overall change | 1.73 kB | 1.74 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -648,6 +648,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               )
             ]);
             updateScripts(scripts);
+          } else {
+            loadScript(props);
           }
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8fbd1c5f9ebeff7969a4.js"
+      src="/_next/static/chunks/main-e23273667ac2b2f248c1.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8fbd1c5f9ebeff7969a4.js"
+      src="/_next/static/chunks/main-e23273667ac2b2f248c1.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -23,7 +23,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-8fbd1c5f9ebeff7969a4.js"
+      src="/_next/static/chunks/main-e23273667ac2b2f248c1.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 173a1d164468378acf84beba89ce1005fee79e84

**Pull request merged**
