### PR TITLE
Add image loader prop

### LINKED ISSUE #18606: Custom Image Loaders
# Feature request

The next image component should allow for custom image loaders.

Currently only [a few are supported](https://github.com/vercel/next.js/blob/v10.0.0/docs/basic-features/image-optimization.md#loader) with no way to add a custom one in userland.

## Is your feature request related to a problem? Please describe.

In the headless CMS space, there are a good amount of providers that include an image service that transforms images on the fly.

- [Sanity](https://www.sanity.io/docs/image-urls) (with [auto WebP support](https://www.sanity.io/docs/image-urls#auto-777d41f23d56) too!)
- [Storyblok](https://www.storyblok.com/docs/image-service)
- [Contentful](https://www.contentful.com/developers/docs/references/images-api/)

(These [were all sponsors](https://nextjs.org/conf/expo) of next conf too lol)

## Describe the solution you'd like

**Edit:** I no longer think this is the right solution. See here instead https://github.com/vercel/next.js/issues/18606#issuecomment-720149156

<strike>Something like this:</strike>

```ts
// my-image-service.ts
import { ImageLoader } from 'next';

const imageLoader: ImageLoader = ({ root, src, width, quality }) => {
  // ...
}

export default imageLoader;
```

```js
// next.config.js
module.exports = {
  // ...
  images: {
    loader: require.resolve('./my-image-service'),
    path: 'https://example.com/myaccount/',
  },
}
```

## Describe alternatives you've considered

I could PR the service I want to be added but I don't think that will scale well. Also adding this feature can make it so y'all can remove the built-in loaders from the image component and reduce bundle size a bit.

### PR DESCRIPTION
**Pull request by ricokahler**
This PR demonstrates the idea from https://github.com/vercel/next.js/issues/18606#issuecomment-720149156 and https://github.com/vercel/next.js/pull/19325#issuecomment-745547880

Note: the purpose of this PR is to demonstrate the idea but I did not fully vet it and test it.

Let me know what you think!

cc: @styfle @Timer @timneutkens @atcastle

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| buildDuration | 9.2s | 9.1s | -80ms |
| nodeModulesSize | 82.4 MB | 82.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.115 | 2.1 | -0.02 |
| / avg req/sec | 1182.2 | 1190.25 | +8.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.123 | 1.117 | -0.01 |
| /error-in-render avg req/sec | 2227.03 | 2238.58 | +11.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| 677f882d2ed8..0679.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b992ce4..2479.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-2cf0e..a0a0.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.8s | ⚠️ +53ms |
| nodeModulesSize | 82.4 MB | 82.4 MB | ⚠️ +627 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| 677f882d2ed8..0679.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b992ce4..2479.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-2cf0e..a0a0.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ricokahler/next.js image-loader-prop | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: 600dee756d3d2c8f0bcad6b5760db026500f9eb2

**Comment by ricokahler** [comment]
Some ideas/thoughts about this approach:

- it allows for multiple image loads on the same site inherently
- it enables for other image loaders to be written in a separate code-splittable entry point and imported
 
E.g.

```js
// sanity-image.js
import { sanityImageLoader } from 'next/image-loaders';
import Image from 'next/image';

function SanityImage(props) {
  return <Image imageLoader={sanityImageLoader} {...props} />;
}

export default SanityImage;
```

```js
// contentful-image.js
import { contentfulImageLoader } from 'next/image-loaders';
import Image from 'next/image';

function ContentfulImage(props) {
  return <Image imageLoader={contentfulImageLoader} {...props} />;
}

export default ContentfulImage;
```

**Comment by styfle** [comment]
I like it! I think @atcastle is working on something similar 👍

**Comment by atcastle** [comment]
Thanks for exploring this approach, I agree that it's the right way to go. @Timer had actually proposed this exact approach to me last week, and I had it kicking around in my local branch, so I went ahead and PRed that version at #20216, just to be able to take advantage of the tests that I'd already written for the version of loader support in #18606.

Could you take a look at that PR and let me know if you see any issue with it?

**Comment by ricokahler** [comment]
@atcastle sounds great! 🚀🚀🚀

I'll close this in favor of that. I just quickly put this is up to demo the idea but I have no intention of merging it. Feel free to use this as inspo if you want. I'll check out your PR too.

**Pull request closed without merging**
