### PR TITLE
Update graphql example

### PR DESCRIPTION
**Pull request by m-abdelwahab**
## Documentation / Examples

This is an update to the [GraphQL example](https://github.com/vercel/next.js/tree/canary/examples/api-routes-graphql) to use [apollo server 3](https://www.apollographql.com/docs/apollo-server). This example works with Apollo Studio

### CODE REVIEW

**Review by leerob — DISMISSED** [review]
Might need to run `lint`, but code LGTM!

**Review by ijjk — APPROVED** [review]

**Comment by fredrik-sogaard** [comment]
This is not working for me. Tried both a local version with `yarn create next-app --example api-routes-graphql api-routes-graphql-app` and the StackBlitz version, but I'm getting CORS errors from Apple Studio.

**Comment by fredrik-sogaard** [comment]
I managed to get it working by changing to this:
```js
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Credentials', 'true')
  res.setHeader(
    'Access-Control-Allow-Origin',
    'https://studio.apollographql.com'
  )
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Origin, X-Requested-With, Content-Type, Accept'
  )
  if (req.method === 'OPTIONS') {
    res.end()
    return false
  }

  await startServer
  await apolloServer.createHandler({
    path: '/api/graphql',
  })(req, res)
}
```

Not sure if this is the correct way of doing it?

**Comment by nosovandrew** [comment]
@fredrik-sogaard With apollo-server v3 we need to use apolloServer.start() in contrast to how it was in the v2. Is it correct approach? As I understand Next.JS runs its own server and we don't need to run another one. Please explain me if I'm wrong.

**Pull request merged**
