### PR TITLE
fix `default` handling in route groups that handle interception

### LINKED ISSUE #59279: Next.js gives 404 on Intercepting Routes with nested route groups
### Link to the code that reproduces this issue

https://github.com/fedetorre/nextgram

### To Reproduce

I have a complex nextjs project with the same problem, I tried to reproduce my project structure with the nextgram demo for debugging purpuse.

Steps to reproduce:
1. Checkout the project
2. yarn install
3. yarn dev
4. Open the browser on [localhost:3000](http://localhost:3000)
5. Click to an image, the url change but renders the 404 page, in the [original nextgram demo](https://github.com/vercel-labs/nextgram) a modal will be open with the clicked image
6. If you refresh the page the image appear and the server does not give 404

### Current vs. Expected behavior

I'm expecting that the modal opens with the image and the 404 page will not be rendered.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.40
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Additional context

This is the current behaviour
[Screencast from 05-12-2023 10:19:44.webm](https://github.com/vercel/next.js/assets/2004681/f4174d32-5e99-441e-ac8e-cfe34c9b813c).

My production application is deployed on vercel but the problem also exists on local development environment.

<sub>[NEXT-1813](https://linear.app/vercel/issue/NEXT-1813/nextjs-gives-404-on-intercepting-routes-with-nested-route-groups)</sub>

### PR DESCRIPTION
**Pull request by ztanner**
### What?
Navigating to a layout that is part of a route group that uses route interception currently will trigger a 404 error if the route group doesn't define a `default` segment.

### Why?
When `next-app-loader` injects fallback defaults into the loader tree, it does so by first seeing if a default already exists. However it does this without ignoring route groups, meaning if you have a `/app/default.tsx` and your interception route is at `/app/(level1)/(level2)`, it will look for the default at `/app/(level1)/(level2)/default.tsx`. 

When a `default` isn't found, the fallback behavior is to trigger a `notFound()` error. This means navigating to the intercepting route that has no `default` for the `children` segment will 404.

### How?
This adjusts the fallback behavior by attempting to find the `default` by normalizing the segment path, which will ignore route groups. That way `/app/(level1)/(level2)/default` will first check `/app/default.tsx` before falling back to `notFound` behavior.

Fixes #59279
Closes NEXT-1813

### CODE REVIEW

**Comment by ztanner** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #59752** <a href="https://app.graphite.dev/github/pr/vercel/next.js/59752?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/59752?utm_source=stack-comment).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.9s | ⚠️ +151ms |
| buildDurationCached | 7.1s | 6.2s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +3.96 kB |
| nextStartRea..uration (ms) | 427ms | 422ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.9 kB | 26.9 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| index.html gzip | 530 B | 527 B | N/A |
| link.html gzip | 542 B | 540 B | N/A |
| withRouter.html gzip | 525 B | 523 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 627 B | 621 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-18-fix_intercepting_route_behavior_in_route_groups | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page-tur..prod.js gzip | 94.8 kB | 94.8 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 931 kB | 931 kB | ✓ |

</details>

</details>
Commit: c8515e97e3a03a098bf66d997cc86b50cf391e96

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c8515e97e3a03a098bf66d997cc86b50cf391e96

`pnpm test-start test/e2e/app-dir/interception-route-groups/interception-route-groups.test.ts` 
- interception-route-groups > without a default route > should fallback to a 404 if there is no default

<details>
<summary>Expand output</summary>

  ● interception-route-groups › without a default route › should fallback to a 404 if there is no default

    TIMED OUT: /404/

    Photo Page (non-intercepted) 1 Back Home

    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/interception-route-groups/interception-route-groups.test.ts:65:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by loicnestler** [comment]
Any details on this PR will get merged and/or published to NPM? Is there a workaround for https://github.com/vercel/next.js/issues/59279 in the mean-time?

**Comment by ztanner** [comment]
@loicnestler you should be able to work around the issue in your reproduction by adding a `default.tsx` to your `(level1)/(level2)/(level3)` segment. This PR is essentially making sure that happens in case you have a root level `default.tsx` but not one defined in the route group.

**Review by feedthejim — APPROVED** [review]

**Pull request merged**
