### PR TITLE
Fix: Server actions standalone CSRF issue

### LINKED ISSUE #58295: `x-forwarded-host` header does not match `origin`
### Link to the code that reproduces this issue

https://github.com/lewisnewson/nextjs-14.0.2-bug-report

### To Reproduce

1. Clone the attached git repo
2. Deploy the `main` branch onto a basic Heroku dyno
3. Open the application in a new browser window
4. Observe the error printed in the Heroku server logs

### Current vs. Expected behavior

Currently:

1. Server action called
2. Fails on the server with the error "`x-forwarded-host` header with value `localhost:23380` does not match `origin` header with value `nextjs-14-0-2-bug-report-4ea064a57303.herokuapp.com` from a forwarded Server Actions request. Aborting the action. -- Error: Invalid Server Actions request."

What should happen:

1. Server action called
2. Executed correctly server-side (prints example todos)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Since upgrading from 14.0.1 to 14.0.2, deployments into a Heroku environment have now seen issues arise with the use of server actions. This can be shown in the example provided, when deployed to Heroku, loading the application prints the error message into the console of the dyno.

This issue does not happen when running `next dev` on a local machine, instead it only seems to appear when the application is deployed into production.

### PR DESCRIPTION
**Pull request by eyn**
### Fixing a bug

- Related issues linked using:
fixes: #58295 

- Tests added. See: https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs
Not sure quite how to write a test for this - can someone point me to an example of how to test standalone and server actions?

### What?
When using `standalone` mode (i.e. workers) and Server Actions without `process.env.HOSTNAME` set then `x-forward-host` is set to `${this.hostname}:${this.port}`. When using Server Actions the CSRF check fails if x-forwarded-hostname is not set as https://github.com/vercel/next.js/blob/1eee93cc94255ed17d853f64904752d4c840a9b1/packages/next/src/server/app-render/action-handler.ts#L291-L345 picks up the value set here which is incorrect.

### Why?
I'm not 100% sure that this is the correct fix as not sure why `x-forwarded-host` is being set to a default value however reverting to the behaviour that was present in determining this header before #57815 should fix at least some of the issues in #58295 

### How?

Closes NEXT-
Fixes  N/A

### CODE REVIEW

**Comment by controversial** [comment]
The new behavior breaks running server actions from subdomains of locahost (e.g. abc.localhost:3000) and also breaks the x-forwarded-host header for this use case.

I use a wildcard subdomain on Vercel, and I use “subdomains” of localhost in order to match that logic in my local dev environment.

**Review by shuding — COMMENTED** [review]
This change makes sense, thanks! Do you think if it's easy to have a test for it?

**Comment by eyn** [comment]
> This change makes sense, thanks! Do you think if it's easy to have a test for it?

I don't think its particularly easy to test for but I'm not that familiar with the next.js test suite. A unit test around action-handler would be possible to check how headers are treated but I'm not sure that would do anything more than check the implementation. 

I'm not sure what the underlying reason for setting `x-forwarded-host` here if its not set? That might be worth putting a test case together for? The other thing we could test would be the CSRF checks if x-forwarded-host is not set on req and if it is set. Would be good if you can point me in right direction if you feel these tests are required. 

It feels odd to me that we are setting this in the first place. Having said that this behaviour is probably not something we should/can change in a minor release.

**Comment by eyn** [comment]
Closing in favour of #58500

**Pull request closed without merging**
