### PR TITLE
Allow use of filenames in exportPathMap

### PR DESCRIPTION
**Pull request by jesseditson**
I was working on a docs site that mirrored the content from a github repo, and decided to use the new `next export` to build the static site.

However, I expected that I could put any valid file path in `exportPathMap` as keys and it would render to that path. I was disappointed to find that a path of `foo/bar.html` would actually render as `foo/bar.html/index.html`, which would break links in my case (I'm wrapping content with plain anchors that I don't want to transform to dynamic links).

This PR changes the output (and any links to it) to be the path specified (without adding `index.html`) if `path.extname(key)` is not empty.

### CODE REVIEW

**Comment by langri-sha** [comment]
Would this not fit as a better solution https://github.com/zeit/next.js/pull/2699 🙈?

**Comment by jesseditson** [comment]
After reading #2699 it looks like this may be helpful for solving that PR breaking export, but otherwise unrelated - does that sound right? If so, this one could land before that one and it would be easy to test. Could integrate on another branch if that would speed up one or both of these PRs.

**Comment by jesseditson** [comment]
Also @arunoda LMK when I should rebase this, I'll hold off until I hear from ya.

**Comment by nelak** [comment]
@jesseditson The export issue mentioned in #2699 is unrelated to this.
That issue relates only to exporting when using typescript and it is fixed by modifying `tsconfig.json` as explained in the PR.

**Comment by timneutkens** [comment]
@jesseditson PR looks 👌
Just to verify:
This will be the possible cases right? 😄 
`/` => `/index.html`
'/abc` => `/abc/index.html`
`/abc.html` => `/abc.html`
`/abc.md`=> `/abc.md`

**Comment by jesseditson** [comment]
@timneutkens cool, added a small note to the readme - to me this change is intuitive so I assume that's enough, but happy to add more docs if you'd like! The tests should be helpful for curious folks too.

Let me know if there's anything else you'd like me to update!

**Comment by jesseditson** [comment]
Oh and yes, those possible cases look correct to me!

**Review by timneutkens — APPROVED** [review]
Awesomeness, just my curiosity, you're really exporting a Next app to markdown 😲

**Comment by jesseditson** [comment]
Hehe still exporting html, but I'm exporting docs from a GitHub repo to an s3 static site, and wanted the paths to match so the links would work both on GitHub and the website. Content-Type sent by s3 is text/html though!

**Comment by timneutkens** [comment]
😄 Nice, this was released in latest beta 🙌

**Comment by jesseditson** [comment]
Amazing, thanks again!

**Pull request merged**
