### PR TITLE
docs(pages): update slug value for optional catch all routes

### PR DESCRIPTION
**Pull request by hungdoansy**
## Why?

When you do, →

```
  const router = useRouter()
  console.log('[test] router =', router.query.slug)
 ```
 
 the value of `router.query.slug` should be undefined in this instance.
 
 (screenshot from current docs)
CleanShot 2024-04-13 at 00 18 14@2x

it should be `slug: undefined`.

### CODE REVIEW

**Comment by samcx** [comment]
@hungdoansy Can you clarify how you came to this conclusion in the description of the <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>?

**Comment by hungdoansy** [comment]
> @hungdoansy Can you clarify how you came to this conclusion in the description of the :pr:?

Hi, please check out my preview link here: 
https://next-router-ashen.vercel.app/route
https://next-router-ashen.vercel.app/route/a
https://next-router-ashen.vercel.app/route/a/b/c/d/

Source code is here: https://github.com/hungdoansy/next-router

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7cea8293f5fce9292c91a9e55bd52328777a65ad

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by hungdoansy** [comment]
Thanks @samcx.

**Pull request merged**
