### PR TITLE
docs: move `exportPathMap` to legacy-api

### PR DESCRIPTION
**Pull request by JamBalaya56562**
## Description
At #71812, [Legacy APIs](https://nextjs.org/docs/app/api-reference/legacy-apis) section was created.
It's useful to gather deprecated apis and add `exportPathMap` docs.

In addition, remove [Static Export](https://github.com/vercel/next.js/tree/canary/examples/with-static-export) example because it's no more use `exportPathMap`.

### Improving Documentation

- [x] Run `pnpm prettier-fix` to fix formatting issues before opening the PR.
- [x] Read the Docs Contribution Guide to ensure your contribution follows the docs guidelines: https://nextjs.org/docs/community/contribution-guide

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 9527db3908b2efe5b1262ff604bd819ede8392bd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 9527db3908b2efe5b1262ff604bd819ede8392bd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — DISMISSED** [review]

**Review by ijjk — COMMENTED** [review]
After taking another look I don't think we want to move this to that legacy APIs folder as it is easier to find under the more specific `next-config` section.

**Comment by JamBalaya56562** [comment]
> After taking another look I don't think we want to move this to that legacy APIs folder as it is easier to find under the more specific `next-config` section.

Thank you for a nice review!
I recreate the similar PR #72302 which doesn't move file.

**Pull request closed without merging**
