### PR TITLE
Update debug error colors

### PR DESCRIPTION
**Pull request by chrispuska**
Replaces the current error-debug bright fuschia colors with darker, more readable colors. #2100

next-error-colors

### CODE REVIEW

**Comment by timneutkens** [comment]
Cool!

**Comment by arunoda** [comment]
I'd like to have these changes:

```patch
diff --git a/lib/error-debug.js b/lib/error-debug.js
index 0d065e3..298dacd 100644
--- a/lib/error-debug.js
+++ b/lib/error-debug.js
@@ -43,7 +43,7 @@ const styles = {
     fontFamily: '"SF Mono", "Roboto Mono", "Fira Mono", consolas, menlo-regular, monospace',
     fontSize: '13px',
     lineHeight: '18px',
-    color: '#6F6767',
+    color: '#8b8b8b',
     margin: 0,
     whiteSpace: 'pre-wrap',
     wordWrap: 'break-word',
@@ -53,9 +53,9 @@ const styles = {
   heading: {
     fontFamily: '-apple-system, system-ui, BlinkMacSystemFont, Roboto, "Segoe UI", "Fira Sans", Avenir, "Helvetica Neue", "Lucida Grande", sans-serif',
     fontSize: '20px',
-    fontWeight: 'bold',
+    fontWeight: '400',
     lineHeight: '28px',
-    color: '#ebe7e5',
+    color: '#ff85af',
     marginBottom: '0px',
     marginTop: '0px'
   }
```

screen shot 2017-06-07 at 2 25 49 pm

Update it (with your changes) and let me know. I'll take this.

**Comment by krisztianpuska** [comment]
@arunoda Fine by me, it's better with a lighter first line. Changed your colors slightly to match with my initial background.

screenshot 2017-06-07 11 29 29

**Review by timneutkens — APPROVED** [review]
This looks cool 👌 
cc @evilrabbit could you take a peek to confirm 😄

**Comment by evilrabbit** [comment]
Guys maybe we should try our red for the title: #FF001F
But I really like it!

**Comment by krisztianpuska** [comment]
@evilrabbit Red or white header? I prefer the white, more readable, the screen itself already indicates that you have an error.

zeit-red

**Comment by timneutkens** [comment]
IMO the white header. But lets wait for evilrabbit.

**Comment by arunoda** [comment]
Pure red is basically hard for the eyes. That's why I went for pink.
Anyway, I'm fine with white color with `font-weight: 400` for the heading.

**Comment by arunoda** [comment]
This is great.
Let's take this in.

**Comment by timneutkens** [comment]
Amazing work! 😍

**Pull request merged**
