### PR TITLE
Updated the example of with-styled-jsx-scss to utilize the App Router.

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-styled-jsx-scss example for using the App Router. 
Here are the changes that have been made:

- Renamed the "pages" folder to the "app" folder.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4a4e7a04c7db05207ba6ac48b4801261b749bc39

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@PapatMayuri 

For the future, please double check these examples are working when testing (test `next dev`, `next build`, and deploying).

Let's go ahead and remove these Babel `style-jsx-...` examples. It's getting an error, and it's likely not worth the effort to fix/keep around as an example.

**Comment by PapatMayuri** [comment]
Sure @samcx Will check and update.

**Comment by PapatMayuri** [comment]
@samcx  PR is Updated please check.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
