### PR TITLE
Update warning for rewriting to auto-export dynamic pages

### LINKED ISSUE #14736: We should not warn for doing a no-op rewrite for auto-exported dynamic pages
Our current example for proxying non-existing pages/assets to an upstream site leverages a no-op rewrite to trigger checking all pages/assets in the application before applying the final rewrite, this incorrectly triggers the rewriting to auto-exported dynamic pages warning

### PR DESCRIPTION
**Pull request by ijjk**
Since the no-op rewrite is a valid rewrite used to check pages/assets before adding a 404-rewrite this makes sure we don't show the rewriting to auto-export dynamic pages warning from it

Closes: https://github.com/vercel/next.js/issues/14736

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 520b5abd531b29eaef5e43acf5a9a4d9e7548430

**test/integration/catches-missing-getStaticProps/test/index.test.js** 
- Catches Missing getStaticProps > should catch it in dev mode

<details>
<summary>Expand output</summary>

  ● Catches Missing getStaticProps › should catch it in dev mode

    expect(received).toMatch(expected)

    Expected pattern: /getStaticPaths was added without a getStaticProps in/
    Received string:  "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><link rel=\"preload\" href=\"/_next/static/runtime/main.js?ts=1593555949723\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack.js?ts=1593555949723\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/pages/_app.js?ts=1593555949723\" as=\"script\"/><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/runtime/react-refresh.js?ts=1593555949723\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"message\":\"Rewrites don't support auto-exported dynamic pages yet.\\nUsing this will cause the page to fail to parse the params on the client\\nSee more info: https://err.sh/next.js/rewrite-auto-export-fallback\",\"stack\":\"Error: Rewrites don't support auto-exported dynamic pages yet.\\nUsing this will cause the page to fail to parse the params on the client\\nSee more info: https://err.sh/next.js/rewrite-auto-export-fallback\\n    at renderToHTML (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/render.js:19:7)\\n    at /home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:73:314\\n    at /home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:72:148\\n    at DevServer.renderToHTMLWithComponents (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:96:272)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at async DevServer.renderToHTML (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:97:656)\\n    at async DevServer.renderToHTML (/home/runner/work/next.js/next.js/packages/next/dist/server/next-dev-server.js:24:578)\\n    at async DevServer.render (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:50:236)\\n    at async Object.fn (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/next-server.js:35:306)\\n    at async Router.execute (/home/runner/work/next.js/next.js/packages/next/dist/next-server/server/router.js:28:28)\"},\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills.js?ts=1593555949723\"></script><script src=\"/_next/static/runtime/main.js?ts=1593555949723\"></script><script src=\"/_next/static/runtime/webpack.js?ts=1593555949723\"></script><script src=\"/_next/static/pages/_app.js?ts=1593555949723\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1593555949723\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1593555949723\"></script></body></html>"

      26 |     await killApp(app)
      27 | 
    > 28 |     expect(html).toMatch(errorRegex)
         |                  ^
      29 |   })
      30 | 
      31 |   it('should catch it in server build mode', async () => {

      at Object.<anonymous> (integration/catches-missing-getStaticProps/test/index.test.js:28:18)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.3s | ⚠️ +82ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +52 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.178 | 2.131 | -0.05 |
| / avg req/sec | 1147.91 | 1173.16 | +25.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.497 | 1.365 | -0.13 |
| /error-in-render avg req/sec | 1670.5 | 1831.45 | +160.95 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..769f.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| index.html gzip | 952 B | 952 B | ✓ |
| link.html gzip | 961 B | 961 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 14s | 13.7s | -323ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +52 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..769f.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ⚠️ +10 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ⚠️ +10 B |
| link.js | 915 kB | 915 kB | ⚠️ +10 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +10 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +10 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +50 B |

</details>

</details>
Commit: 520b5abd531b29eaef5e43acf5a9a4d9e7548430

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.2s | -120ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.154 | 2.089 | -0.06 |
| / avg req/sec | 1160.9 | 1196.89 | +35.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.344 | 1.405 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1859.84 | 1779.26 | ⚠️ -80.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..769f.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 962 B | 962 B | ✓ |
| withRouter.html gzip | 946 B | 946 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.9s | ⚠️ +801ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..769f.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ⚠️ +31 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ⚠️ +31 B |
| link.js | 915 kB | 915 kB | ⚠️ +31 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +31 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +31 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +155 B |

</details>

</details>
Commit: 8b914fe693299823244bc5cdcb0f1ac3acda96d9

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +77ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.377 | 2.304 | -0.07 |
| / avg req/sec | 1051.71 | 1084.86 | +33.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.451 | 1.43 | -0.02 |
| /error-in-render avg req/sec | 1722.43 | 1748.48 | +26.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..b4c5.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| index.html gzip | 952 B | 952 B | ✓ |
| link.html gzip | 958 B | 958 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.85 kB | 2.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.7s | -6ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +154 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..b4c5.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.68 kB | 5.68 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/rewrite-auto-export-warning | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ⚠️ +31 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ⚠️ +31 B |
| link.js | 916 kB | 916 kB | ⚠️ +31 B |
| routerDirect.js | 908 kB | 908 kB | ⚠️ +31 B |
| withRouter.js | 908 kB | 908 kB | ⚠️ +31 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +155 B |

</details>

</details>
Commit: 486ff255b5ee2da8515cc94ef390bc7d026b83b7

**Pull request merged**
