### PR TITLE
Fix barrel optimization to ignore layers

### LINKED ISSUE #57624: `optimizePackageImports` no longer functional in v14
### Link to the code that reproduces this issue

https://github.com/mwskwong/optimize-package-imports-bug

### To Reproduce

1. Create a Next.js project
2. Import any MUI component (`Button` in the example) using named import to `page.tsx`
3. Observe the bundle size

### Current vs. Expected behavior

**Current**
The entire `@mui/material` is included in the client bundle, despite this package is by default included in `optimizePackageImports`.

**Expect**
Only `Button` and its dependencies are included in the client bundle.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.3
  eslint-config-next: 14.0.1-canary.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Downgrade to Next.js 13.5 to observe the expected behavior.

<sub>[NEXT-1713](https://linear.app/vercel/issue/NEXT-1713/optimizepackageimports-no-longer-functional-in-v14)</sub>

### PR DESCRIPTION
**Pull request by shuding**
Fixes #57624. The recent issue was an unexpected side effect caused by https://github.com/vercel/next.js/commit/305bb015060e82be3e6ae59a3d063c11a3e207f9, which only affects specific packages like `@mui/material`. 

The problem was that the entry file of `@mui/material` has `"use client"` at top, which affects the compilation result to output reference info only (when on the RSC layer), instead of keeping the original export statements. And the fix here is to ignore all layer info and React specific transforms here, as barrel optimization isn't related to all these framework features at all. To keep all directives unchanged, the SWC transform needs to parse and pass that info to the Webpack loader.

This PR adds a test to ensure that `@mui/material` is working as expected (less than 1500 modules compiled). Without this feature it'll be ~2400 modules.

Closes NEXT-1793, closes NEXT-1762.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 64c2f1d0ddf500508b65ad3f494aaed64393d143

`pnpm test-dev test/development/basic/barrel-optimization/barrel-optimization.test.ts` 
- optimizePackageImports > should support MUI

<details>
<summary>Expand output</summary>

  ● optimizePackageImports › should support MUI

    expect(received).toBeGreaterThanOrEqual(expected)

    Expected: >= 1
    Received:    0

      147 |       ]
      148 |
    > 149 |       expect(modules.length).toBeGreaterThanOrEqual(1)
          |                              ^
      150 |       for (const [, , , , moduleCount] of modules) {
      151 |         // Ensure that the number of modules is less than 1000 - otherwise we're
      152 |         // importing the entire library.

      at Object.toBeGreaterThanOrEqual (development/basic/barrel-optimization/barrel-optimization.test.ts:149:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.6s | N/A |
| buildDurationCached | 5.9s | 6.7s | ⚠️ +794ms |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 421ms | 419ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.7 kB | 30.7 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 501 B | 503 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 538 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.6 kB | 92.7 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 628 B | 626 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 35.7 kB | 35.7 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/14f6 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 93.8 kB | 93.8 kB | ✓ |
| app-page-tur..prod.js gzip | 94.5 kB | 94.5 kB | ✓ |
| app-page-tur..prod.js gzip | 89.1 kB | 89.1 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.4 kB | 88.4 kB | ✓ |
| app-route-ex...dev.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route-ex..prod.js gzip | 16.8 kB | 16.8 kB | ✓ |
| app-route-tu..prod.js gzip | 16.9 kB | 16.9 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route.ru...dev.js gzip | 23.6 kB | 23.6 kB | ✓ |
| app-route.ru..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.3 kB | 49.3 kB | ✓ |
| Overall change | 930 kB | 930 kB | ✓ |

</details>

</details>
Commit: 64c2f1d0ddf500508b65ad3f494aaed64393d143

**Review by huozhi — APPROVED** [review]

**Comment by shuding** [comment]
This change is more tricky than I thought — will probably a bit take more time.

**Review by huozhi — APPROVED** [review]
Nice PR!

**Comment by mwskwong** [comment]
@shuding FYR, this PR seems to introduce a new issue. Under certain condition, the following error is thrown when using `optimizePackageImports`. I'm unable to find a reliable way to reproduce it just yet, but I will create an issue once I'm able to do so.

```
Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by Talent30** [comment]
> @shudingFYR，此 PR 似乎引入了一个新问题。 在某些情况下，使用时会抛出以下错误 `optimizePackageImports`。 我还无法找到可靠的方法来重现它，但一旦我能够这样做，我就会创建一个问题。
> 
> ```
> Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> ```

I have encountered the same issue, can't find a way to reproduce it...

**Comment by HristoHentov** [comment]
+1, also facing the Element type is invalid issue
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at nP (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:59156)
    at nP (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:59120)
    at n$ (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:61978)
    at nj (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64628)
    at nO (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64035)
    at n$ (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:62224)
    at nj (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64628)
    at nO (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64035)
    at n$ (E:\Projects\PillarPerch\client\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:62224)
```

**Comment by cysp** [comment]
Adding to the chorus, I just finished bisecting this same error in a project I'm working on to https://github.com/vercel/next.js/releases/tag/v14.0.4-canary.42, and this change is the most likely candidate in my mind. 🙂 

My project does use `@mui/material`.
I've tried to find if any specific component or import triggers reproduction but I have not been able to consistently reduce the reproduction to anything in particular.

**Comment by mwskwong** [comment]
> [edit:] Interestingly, I appear to be able to squash the error with judicious placement of `'use client'` in my components that themselves _use_ `@mui/material` components.

Because when using client components, this config doesn't take effect and the Webpack tree shaking takes over

**Comment by infodusha** [comment]
Thank comments above I did manage to solve the issue.

In my case it was `<App />` import from `antd` in root layout that is a server component

**Pull request merged**
