### PR TITLE
docs: Add media example for icon metadata

### PR DESCRIPTION
**Pull request by RiskyMH**
### What?
Adds an example of the ability to add media attributes to icons in metadata.

### Why?
I have seen a few people ask in the Discord server about the ability to have icons that are for dark mode, and linking to the [code](<https://github.com/vercel/next.js/blob/cd70065bad00cb9d3b0e7c9a94ee9241e3c5f5d8/packages/next/src/lib/metadata/types/metadata-types.ts#L106>) didn't feel as nice as the docs.

### How?
Modifies the large example of icon options to include one with the media attribute. I also made a [codesandbox](https://25mlgn-3000.csb.app/) to prove that it works like this.

### CODE REVIEW

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Looks like Prettier failed here 🙏

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 492d7f9c0b47a4c31a9f182c04ed0c7f25bf300f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 492d7f9c0b47a4c31a9f182c04ed0c7f25bf300f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 492d7f9c0b47a4c31a9f182c04ed0c7f25bf300f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
