### PR TITLE
Fix Preview Mode in `<iframe>`

### PR DESCRIPTION
**Pull request by Timer**
Chrome now requires you use `SameSite=None` for a cookie to be present in an `<iframe>`.

Source: https://web.dev/samesite-cookies-explained/

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.9s | ⚠️ +78ms |
| nodeModulesSize | 47.7 MB | 47.7 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5272.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.75 kB | 6.75 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| index.html gzip | 917 B | 917 B | ✓ |
| link.html gzip | 926 B | 926 B | ✓ |
| withRouter.html gzip | 915 B | 915 B | ✓ |
| Overall change | 2.76 kB | 2.76 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.7s | ⚠️ +176ms |
| nodeModulesSize | 47.7 MB | 47.7 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5272.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.75 kB | 6.75 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js hotfix/allow-iframe | Change |
| - | - | - | - |
| _error.js gzip | 233 kB | 232 kB | -390 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 956 B | 956 B | ✓ |
| index.js gzip | 233 kB | 233 kB | -42 B |
| link.js gzip | 243 kB | 243 kB | ⚠️ +118 B |
| routerDirect.js gzip | 241 kB | 241 kB | ⚠️ +54 B |
| withRouter.js gzip | 241 kB | 241 kB | ⚠️ +40 B |
| Overall change | 1.19 MB | 1.19 MB | -220 B |

</details>

</details>

**Review by ijjk — APPROVED** [review]
LGTM, seems a couple of the windows tests had unrelated install fails

**Comment by bzin** [comment]
Hi @Timer, just wanna let you know that I tested this out within Craft CMS  live preview and the cookies are still not set.

Let me know if I can help debugging this.

**Comment by dohomi** [comment]
@Timer same counts for Storyblok CMS. The preview data is not set after upgrading to `NextJS 9.3.5`with the previewMode

**Comment by jecassis** [comment]
Hello @Timer, also tested using Prismic in 9.3.5 by attempting to enter Preview Mode in development.

It is attempting to set the cookies. Works in Firefox 73, but Chrome 83 blocks them with this Tooltip error:
This Set-Cookie was blocked because it had the "Secure" attribute but was not received over a secure connection.

Managed to get the cookies out:
Set-Cookie: __prerender_bypass=b3b0ec4be899f2a69a; Path=/; HttpOnly; Secure; SameSite=None
Set-Cookie: __next_preview_data=eyJhbGciOiJIUzI1NiJ9; Path=/; HttpOnly; Secure; SameSite=None

The cookies are set to "Secure" and if using an HTTP server on localhost it fails. Using an HTTPS server works.

I added a printout inside the `setPreviewData` function (directly in `node_modules/`) and process.env.NODE_ENV returns **undefined** however it prints `development` inside `api/preview.js` right after returning. I assume the intention of `api-utils.ts` in development is that "SameSite" should be `lax` and "Secure" should not be present. And yet, I am unsure of how or where NODE_ENV was unset and reset.

**Comment by dohomi** [comment]
@Timer is there any news on this issue? I tried to check out the most recent 9.5.0 but the example with Storyblok as CMS and the iframe is still not working. 
The current example of https://github.com/vercel/next.js/tree/canary/examples/cms-storyblok does actually not show the power of the visual composer.
With the preview the props of getStaticProps still will be undefined for preview/previewData

**Comment by dohomi** [comment]
The issue only remains on localhost, deployed via Vercel everything seems fine

**Comment by damianfrizzi** [comment]
We're also experiencing issues with the preview mode with Prismic since this change. Preview mode works fine with `9.3.5-canary.0` and breaks with `9.3.5-canary.1`. Preview mode doesn't work in Chrome production mode following the [Prismic example](https://github.com/vercel/next.js/tree/canary/examples/cms-prismic). @Timer Would it help to create a new issue with a minimal repro?

**Pull request merged**
