### PR TITLE
Add/custom error mapper

### PR DESCRIPTION
**Pull request by timbielawski**
Add a errorCodeMapper for the handleRequest and renderToHTML functions.
The purpose is allow the rendered app to throw errors which can be mapped to http error codes, which then results in the correct error html being rendered in Nextjs

Currently Nextjs will render a 500 for any error thrown in the rendered app

I will add tests if this is seen as a viable solution, if not is there another solution?

Implemented code in App

`const nextLoader = next({ dev, quiet, errorCodeMapper });`

errorCodeMapper function

`const { CONTENT_404, THEME_404, SERVER_500 } = require("../constants/errors");`

`const errorCodeMapper = err => { switch (err) { case CONTENT_404: case THEME_404: return 404; default: return 500; } }`

### CODE REVIEW

**Comment by timneutkens** [comment]
> The purpose is allow the rendered app to throw errors which can be mapped to http error codes, which then results in the correct error html being rendered in Nextjs

Can you give an example of this? It sounds like what you're trying to do doesn't require this PR.

**Comment by timneutkens** [comment]
I'm going to close this PR as I'm not sure what it solves exactly. Feel free to provide an example or create a detailed feature request so that we can properly consider your proposal. Thanks for creating this PR 🙏

**Comment by timbielawski** [comment]
Hi,

Thanks for taking the time look at this, let see if I can explain myself and if there is a better solution please let me know, as I am running off my fork and that is less than ideal :)

When my Nextjs app is rendered server side, there is a possibility that I want to throw my own errors, so if I cannot find some content I want to throw a 404.

From what I can see from the NextJs code it will always throw a 500, if an error is thrown during this render process.

`res.statusCode = 500
  return this.renderErrorToHTML(err, req, res, pathname, query)`

This is an issue for me as I my server will complain if a threshold of 500s is reached.
Due to the nature of my app / platform there is a high likelihood that we will get a number of 404s

I need to ensure that NextJs throws the 404 and not 500 to stop the noise on my notifications.

so the PR tries to address this by mapping errors thrown in my App during SSR and then letting NextJs throw the correct error from the SSR.

doe that make sense?

thanks again
Tim

**Comment by timbielawski** [comment]
oki thanks I will take a look

**Pull request closed without merging**
