### PR TITLE
docs(cookies): fix link to Dynamic Function

### PR DESCRIPTION
**Pull request by Juneezee**
image

There is an invalid link on the cookies page (https://nextjs.org/docs/app/api-reference/functions/cookies). Currently it links to the incorrect section. The correct link should be https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-functions

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8cc2712a65cf0db36c19ad99e0dc7e7d96284a6c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8cc2712a65cf0db36c19ad99e0dc7e7d96284a6c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Juneezee** [comment]
friendly ping @delbaoliveira

**Comment by Juneezee** [comment]
friendly ping @delbaoliveira

cc @leerob

**Review by leerob — APPROVED** [review]

**Pull request merged**
