### PR TITLE
docs: fix 10-dynamic-routes.mdx

### LINKED ISSUE #70124: Docs: The explanation for "Dynamic Routes" is incorrect.
### What is the documentation issue?

In the "Optional Catch-all Segments", if params is `{}`, can't reach `/shop`. The correct value should be `{ slug: undefined }`.

### Is there any context that might help us understand?

Just need to change the params from `{}` to `{ slug: undefined }`.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#optional-catch-all-segments

### PR DESCRIPTION
**Pull request by hirotomoyamada**
params from `{}` to `{ slug: undefined }`.

Fixes #70124

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d72f7fcddce53b8c0bfed66516fc28f8af333ce8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — CHANGES_REQUESTED** [review]
This is correct as is since `undefined` is equivalent to omitted in this case.

**Comment by hirotomoyamada** [comment]
@ijjk 

Hi, thanks for the comment!

If omitted, no path is generated.

**Comment by ijjk** [comment]
Ah I see you're stressing it for `generateStaticParams` and similar. I think this note should live there https://nextjs.org/docs/app/api-reference/functions/generate-static-params#catch-all-dynamic-segment

**Comment by hirotomoyamada** [comment]
Hi, [Page router](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#optional-catch-all-segments) describes is as `{ slug: undefined}`. I think it should match.

**Review by ijjk — APPROVED** [review]
This seems better for clarity especially since we've already documented it this way in pages.

**Pull request merged**
