### PR TITLE
Server authentication using JWT

### PR DESCRIPTION
**Pull request by estrada9166**
The main idea behind this example is to handle the sessions on the server, letting you
validate if the user is logged before the view is rendered, as you know or now you know to access to local storage on server render you must do `componenDidMount` so this example prevent the render before the validation.

I think it can be related with the issue #153

### CODE REVIEW

**Comment by timneutkens** [comment]
@estrada9166 we're planning to release an official auth example soon, could you release this as separate repository? Thaaaanks! 👍

**Comment by estrada9166** [comment]
@timneutkens Sure, I have it here https://github.com/estrada9166/server-authentication-next.js

**Comment by timneutkens** [comment]
Cool! Thanks ❤️ you could add it to https://github.com/unicodeveloper/awesome-nextjs

**Comment by estrada9166** [comment]
@timneutkens Done! Thanks! 👍

**Comment by estrada9166** [comment]
@timneutkens How about opening it again? This could be useful....

**Pull request closed without merging**
