### PR TITLE
chore(next/image)!: mark `onLoadingComplete` as deprecated in favor of `onLoad`

### PR DESCRIPTION
**Pull request by styfle**
## History

We used to pass `onLoad` through directly to the underlying img so `onLoadingComplete` was introduced in order to handle the case when `placeholder="blur"` was used and `onLoad` would trigger before the placeholder was removed.

We have since changed the behavior of `onLoad` so that it acts the same as `onLoadingComplete` and therefore `onLoadingComplete` is no longer needed.

## What is this PR doing?

This PR marks `onLoadingComplete` as deprecated in favor of `onLoad`. In the future, we may remove `onLoadingComplete`.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | N/A |
| buildDurationCached | 6.3s | 6.3s | N/A |
| nodeModulesSize | 174 MB | 174 MB | ⚠️ +1.26 kB |
| nextStartRea..uration (ms) | 516ms | 515ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.5 kB | 27.5 kB | ✓ |
| 3f784ff6-HASH.js gzip | 53.1 kB | 53.1 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 126 kB | 126 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.35 kB | 4.35 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 541 B | 543 B | N/A |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 524 B | 524 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | ✓ |
| page.js gzip | 154 kB | 154 kB | N/A |
| Overall change | 93.7 kB | 93.7 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js styfle/next-1688-mark-onloadingcomplete-as-deprecated | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 622 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.5 kB | 22.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 15b463b697349de3da9884d95a26dbecb495b585

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 15b463b697349de3da9884d95a26dbecb495b585

`pnpm test test/integration/next-image-new/app-dir/test/index.test.ts` 
- Image Component Default Tests > production mode > should callback onLoadingComplete when image is fully loaded

<details>
<summary>Expand output</summary>

  ● Image Component Default Tests › production mode › should callback onLoadingComplete when image is fully loaded

    expect(received).toMatch(expected)

    Expected pattern: /Image with src "\/test\.jpg" is using deprecated "onLoadingComplete" property. Please use the "onLoad" property instead./gm
    Received string:  "Next.js page already hydrated"

      362 |       .map((log) => log.message)
      363 |       .join('\n')
    > 364 |     expect(warnings).toMatch(
          |                      ^
      365 |       /Image with src "\/test\.jpg" is using deprecated "onLoadingComplete" property. Please use the "onLoad" property instead./gm
      366 |     )
      367 |   })

      at Object.<anonymous> (integration/next-image-new/app-dir/test/index.test.ts:364:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by jh3y — DISMISSED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 704d54d8395332466063510b0fa936d7b40154b2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 704d54d8395332466063510b0fa936d7b40154b2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — APPROVED** [review]

**Pull request merged**
