### PR TITLE
Introduce dynamic(() => import())

### LINKED ISSUE #5208: The `dynamic imports` modules function no longer receive props in next7
# Bug report

## Describe the bug

With Next6 the modules function for dynamic imports received props, but in Next7 it does not receive any props.

## To Reproduce

```
import dynamic from 'next/dynamic'
const DynamicBundle = dynamic({
  modules: ({ name }) => {
    const comp = {}
    switch (name) {
      case 'facebook':
        comp.Danamic = import('./icons/Facebook')
        break
      case 'twitter':
        comp.Danamic = import('./icons/Twitter')
        break
      case 'github':
        comp.Danamic = import('./icons/Github')
        break
      default:
        comp.Danamic = import('./icons/Awesome')
        break
    }
    return comp
  },
  render: (props, { Danamic }) => {
    return (
       <Danamic {...props} />
    )
  }
})

export default DynamicBundle
```
Gives this error `Unhandled Rejection (TypeError): Cannot read property 'name' of undefined`

## Expected behavior
Since the the blog post said dynamic imports are fully backwards-compatible, I expect to receive props in the modules function.

## System information
 - OS: macOs
 - Version of Next.js: 7.0.0

### LINKED ISSUE #5213: Dynamic chunks not created when running next build twice
# Bug report

## Describe the bug

Running `next build` twice will somehow not create the dynamic chunks on the 2nd run. Instead, the pages using the dynamic components (loaded using `dynamic(import(…))`) will all contain what should be included in the dynamic chunks.

Running a 3rd time makes the build fail.

## To Reproduce

The issue is easily reproducible with the following repository: https://github.com/tusbar/next-js-dynamic-issue

1. `rm -rf node_modules/.cache`
2. `next build`, everything runs smoothly, generated bundles are correct.
3. `next build` again. The build runs faster thanks to hardsource, but the dynamic chunks are not created, the code from the dynamically imported components is moved to each of the pages using them.
4. `next build` again. The build errors with stuff like:

```
[hardsource:5dfb5712] Could not freeze ./components/dynamic-message.js: Cannot read property 'hash' of undefined
```

## Expected behavior
2 sequential build should create the same bundles.

## System information
 - OS: macOs
 - Version of Next.js: 7.0.0

### LINKED ISSUE #5221: Dynamic import is loading all dependency even it's lazy loaded. Next 7.0.0
# Bug report

## Describe the bug

on "next": "^7.0.0", dynamic import is importing ALL of the module that is supposed to lazy loaded. unlike "next": "^6.1.2", the module is correctly loaded on demand.

## To Reproduce

```
import dynamic from "next/dynamic";
const TextSideSlider: any = dynamic(
    import(/* webpackChunkName: 'TextSideSlider' */"./TextSideSlider") as any,
);
```

this component is used only on route /b. But, on route /a it's already loaded.

## Expected behavior
Dynamic imported module loaded when it's needed. like on next 6.1.2.

## Screenshots
"next": "^6.1.2"
on route /a
TextSideSlider component is not loaded.
screen shot 2018-09-20 at 14 25 08

on route /b
TextSideSlider component is loaded correctly on demand.
screen shot 2018-09-20 at 14 25 41

"next": "^7.0.0",
on route /a
TextSideSlider component is already loaded
screen shot 2018-09-20 at 14 28 30

on route /b
nothing changed
screen shot 2018-09-20 at 14 28 42

## System information
 - OS: macOS
 - Browser chrome
 - Version of Next.js: 6.1.2 & 7.0.0

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #5221
Fixes #5208
Fixes #5213

Bringing back some old non-standard behavior:

```js
import dynamic from 'next/dynamic'

const HelloWorld = dynamic(import('../components/hello-world'))

export default () => <HelloWorld />
```

Will compile to:

```js
import dynamic from 'next/dynamic'

const HelloWorld = dynamic(() => import('../components/hello-world'))

export default () => <HelloWorld />
```

- `next/dynamic` accepts a loader function as first argument
- `next/dynamic` usage with just `dynamic(import())` is transpiled to a loader function, 

The reason for these changes is that calling `import()` will immediately load the module when the code is executed, which is what most users don't want. This is to mirror Next 6 and below behavior around this syntax. Do note that it's non-standard and has to be deprecated. We can easily write a codemod to change this usage to the new loader function syntax.

- We now send the webpack moduleIds to the client side so that the `preloadReady` react-loadable function can filter out only the modules needed for hydration, instead of loading everything and waiting for that. This will introduce a performance boost when you *are* using `next/dynamic` but also make sure that modules aren't loaded when you don't render them.

### TODO v7.1

- Make the transpiled function log a warning with an err.sh link that explains how to run the codemod
- Write codemod

### CODE REVIEW

**Comment by tusbar** [comment]
Partly fixes #5213 as well.

**Comment by timneutkens** [comment]
@tusbar I've spent this morning testing against your reproduction and it seems like my patch https://github.com/mzgoddard/hard-source-webpack-plugin/pull/446 fixes the wrong assignment of bundles too, I'm going to temporarily release the package under a prefix so that we can get rid of these issues 👍

**Comment by Fumler** [comment]
Been testing this branch a bit since we are also doing something similar to #5208 (we get the page composition from an API and dynamically load components based on if the page needs them) and we want the benefits of webpack 4 (great job, btw).

In ProfChaos' example repo https://github.com/ProfChaos/nexttest

The original page 
```javascript
import Icon from '../components/Icon'

export default () => {
	return (
		<div>
			<h1>Only load "one"</h1>
			<Icon name="one" />
		</div>
	)
}
```

This now works, the extra chunks are not loaded.

But if I do this 

```javascript
import Icon from '../components/Icon'

export default () => {
	return (
		<div>
			<h1>Only load "one"</h1>
			<Icon name="one" />
			<Icon name="one" />
		</div>
	)
}
```

Now the "one" chunk loads twice, but if you add e.g. 15 `<Icon name="one" />` it still only loads twice.

**Comment by timneutkens** [comment]
Re: https://github.com/zeit/next.js/pull/5249#issuecomment-423928418

Looks like it still doesn't work, spent most of the day debugging.

**Comment by timneutkens** [comment]
@Fumler great catch, I've fixed it and added a test for it. 👍

**Comment by arthens** [comment]
@timneutkens I think this might be causing a different bug with dynamic imports, see https://github.com/zeit/next.js/issues/5305

**Pull request merged**
