### PR TITLE
Update Babel dependencies

### LINKED ISSUE #43799: Babel TypeScript transformer does not support satisfies operator
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Wed Dec 07 2022 11:10:08 GMT+0300 (Москва, стандартное время)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-pa3kjy?file=pages%2Findex.tsx

### To Reproduce

`npm run dev`

### Describe the Bug

```
./pages/index.tsx:10:20
Syntax error: Missing semicolon.

   8 | }
   9 |
> 10 | const user = {id: 1} satisfies User
```

### Expected Behavior

No error

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by Andarist**
### What?

Update Babel packages across the board

### Why?

Since you ship vendored presets and plugins it's impossible for people to update this stuff at their own pace - independently from Next. So users of `next/babel` are currently stuck with old versions and, for example, they might not be able to use the TS `satisfies` operator.

### How?

I just updated ranges (to pinned ones) where I could find them, run `corepack pnpm i` and re-run build scripts in the `packages/next`.

Fixes #43799

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 77ff70a4e9cb15d1e8f6f3edcda7a612c2c83a77

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by jrolfs** [comment]
We've since moved on to the SWC-based toolchain, but I'm still pretty curious about this:

> Since you ship vendored presets and plugins

I'm sure there's a good reason, but I am curious why. What all is vendored?

**Comment by codinsonn** [comment]
Can confirm this would help solve my (and others still stuck with the babel approach) issues with supporting the `satisfies` operator

**Comment by ryota-murakami** [comment]
When can this PR be reviewed?

**Comment by p-iknow** [comment]
Dear esteemed next maintainers. @timneutkens  @ijjk  

Please review this PR quickly, there are many type issues that can be solved with the satisfy operator. However, [typescript satisfy operator issue](https://github.com/vercel/next.js/issues/43799) currently prevents us from using the satisfy operator in next. 

Please help me out of pain of issue

**Comment by timneutkens** [comment]
> Please review this PR quickly

The PR is failing tests as you can see, so it can't be merged.

**Comment by Andarist** [comment]
@timneutkens I'm not sure if those are really failing here - the jobs are stuck on the lack of approval of a Next.js team member. cc @huozhi - maybe you could approve those runs?

**Comment by huozhi** [comment]
`CI approved` label is added, should be able to do the full run everytime from now 🙏

**Comment by tebuevd** [comment]
Would love for this to get merged 🙏

**Comment by 7iomka** [comment]
Any news on this?
Please don't ignore the large number of users that is locked to used babel instead of swc due to current limitations and unstable swc api.

**Comment by timneutkens** [comment]
@7iomka we'd be happy to merge this but this PR is still not passing tests yet so it can't be landed.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5252a913996337ce0af95a22e43b9d993eea8bb2

`pnpm test-dev test/development/acceptance/ReactRefreshLogBox-builtins.test.ts` 
- ReactRefreshLogBox default > Module not found
- ReactRefreshLogBox default > Module not found (empty import trace)
- ReactRefreshLogBox default > Module not found (missing global CSS)

<details>
<summary>Expand output</summary>

  ● ReactRefreshLogBox default › Module not found

    expect(received).toMatchSnapshot()

    Snapshot name: `ReactRefreshLogBox default Module not found 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,9 +1,9 @@
      ./index.js:1:0
      Module not found: Can't resolve 'b'
      > 1 | import Comp from 'b'
    -   2 | 
    +   2 |
        3 | export default function Oops() {
        4 |   return (

      https://nextjs.org/docs/messages/module-not-found
      ↵

      72 |
      73 |     const source = await session.getRedboxSource()
    > 74 |     expect(source).toMatchSnapshot()
         |                    ^
      75 |
      76 |     await cleanup()
      77 |   })

      at Object.<anonymous> (development/acceptance/ReactRefreshLogBox-builtins.test.ts:74:20)

  ● ReactRefreshLogBox default › Module not found (empty import trace)

    expect(received).toMatchSnapshot()

    Snapshot name: `ReactRefreshLogBox default Module not found (empty import trace) 1`

    - Snapshot  - 1
    + Received  + 1

      ./pages/index.js:1:0
      Module not found: Can't resolve 'b'
      > 1 | import Comp from 'b'
    -   2 | 
    +   2 |
        3 | export default function Oops() {
        4 |   return (

      https://nextjs.org/docs/messages/module-not-found

       98 |
       99 |     const source = await session.getRedboxSource()
    > 100 |     expect(source).toMatchSnapshot()
          |                    ^
      101 |
      102 |     await cleanup()
      103 |   })

      at Object.<anonymous> (development/acceptance/ReactRefreshLogBox-builtins.test.ts:100:20)

  ● ReactRefreshLogBox default › Module not found (missing global CSS)

    expect(received).toMatchSnapshot()

    Snapshot name: `ReactRefreshLogBox default Module not found (missing global CSS) 1`

    - Snapshot  - 1
    + Received  + 1

      ./pages/_app.js:1:0
      Module not found: Can't resolve './non-existent.css'
      > 1 | import './non-existent.css'
    -   2 | 
    +   2 |
        3 | export default function App({ Component, pageProps }) {
        4 |   return <Component {...pageProps} />

      https://nextjs.org/docs/messages/module-not-found

      130 |
      131 |     const source = await session.getRedboxSource()
    > 132 |     expect(source).toMatchSnapshot()
          |                    ^
      133 |
      134 |     await session.patch(
      135 |       'pages/_app.js',

      at Object.<anonymous> (development/acceptance/ReactRefreshLogBox-builtins.test.ts:132:20)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.2s | N/A |
| buildDurationCached | 6.2s | 6.5s | ⚠️ +255ms |
| nodeModulesSize | 172 MB | 173 MB | ⚠️ +372 kB |
| nextStartRea..uration (ms) | 524ms | 524ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.5 kB | 27.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 50.9 kB | 50.9 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 251 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 96.4 kB | 96.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.35 kB | 4.35 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | N/A |
| page.js gzip | 152 kB | 152 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | Andarist/next.js update-babel-deps | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.9 kB | 22.9 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 5252a913996337ce0af95a22e43b9d993eea8bb2

**Comment by Andarist** [comment]
@timneutkens @huozhi the CI is green so it should be mergeable now 😉 Note though that this commit shows that you had some pretty big type issues there (I'm not sure how this has typechecked before, perhaps some `any`s leaked into all of this?): https://github.com/vercel/next.js/pull/51962/commits/5252a913996337ce0af95a22e43b9d993eea8bb2 I also added a TODO comment about the cast that I added at one place. I think that this is kinda outside of the scope of this PR and I would prefer not to deal with this - unless u decide to block this PR before this gets resolved

**Review by styfle — DISMISSED** [review]
Great, thanks! 🎉

**Review by huozhi — APPROVED** [review]

**Comment by timneutkens** [comment]
Thank you for the effort @Andarist 🙏

**Pull request merged**
