### PR TITLE
remove unnecessary <a> tag ahead of next.js 13 update

### PR DESCRIPTION
**Pull request by DevEsteves**
I removed the `<a>` tag nested in a `<Link>` tag, ahead of next.js 13 update. `<a>` tags used to be necessary for `<Link>` tags, otherwise it would be excluded.

### CODE REVIEW

**Comment by DevEsteves** [comment]
Does someone know why the prettier test is failing?

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, this error message only shows with the `legacyBehavior` enabled or older Next.js versions which does require the `a` tag wrapping so I think we should leave this as is.

**Comment by ijjk** [comment]
Closing per above

**Pull request closed without merging**
