### PR TITLE
Update router.md

### PR DESCRIPTION
**Pull request by melono6**
include scroll option documentation for router.push

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Thanks!

**Comment by jesstelford** [comment]
The option is already described on line 75 (2 lines above).

**Comment by melono6** [comment]
seems it was added after I made the PR: https://github.com/vercel/next.js/commit/1c3ac0e3eb3d366a043c0848566447cee4df7cc7#diff-129f17bae1a499f319a70b9e5821656cbe48f7b66363d653ab2bfa18e210bdce

**Comment by jesstelford** [comment]
Oh wow, that's interesting! Is GitHub's UI just playing up then!?

Sorry for the false alarm

**Pull request merged**
