### PR TITLE
Fix ESLint TypeScript 4.6 Warning

### LINKED ISSUE #35784: [Regression] TypeScript 4.6 ESLint Warning
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

Due to #34823, `@typescript-eslint/parser` version is now locked (canary currently at 5.10.1) by `eslint-config-next`. For TypeScript 4.6 support, a minimum version of 5.14.0 is required which would have been installed prior to the version being locked. Now for projects using TypeScript 4.6, ESLint displays the following message:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.6.3

Please only submit bug reports when using the officially supported version.

=============
```

### Expected Behavior

The warning message should not be displayed.

### To Reproduce

1. Use `npx create-next-app --typescript` to create a project.
2. Update `typescript` to version 4.6.2 or newer, if necessary.
3. Use `npm run lint`.

### PR DESCRIPTION
**Pull request by jonathanpotts**
Fixes #35784

### CODE REVIEW

**Comment by ytkg** [comment]
Why did you decide to close it?

**Comment by jonathanpotts** [comment]
I deleted the fork to clean up my profile and didn't realize it would close the PR.

**Comment by ytkg** [comment]
I see! Do you plan to reopen?

**Comment by jonathanpotts** [comment]
My understanding is someone at Vercel needs to re-open it.

**Comment by ytkg** [comment]
Maybe you can't re-open it, so you need to fork it again and make a new one.

**Pull request closed without merging**
