### PR TITLE
Golf page-loader

### PR DESCRIPTION
**Pull request by Timer**
- `clearCache` is an unused function
- `try`/`catch` can be used for safe property access
- trim some bytes off 2g check

👋 1.11 kB

### CODE REVIEW

**Comment by Janpot** [comment]
@Timer Just something to keep in mind with this sort of optimizations, while it may result in less bytes over the wire, this `try`/`catch` construct is slower than property undefined checking when it comes to execution speed.
So it's basically a trade-off between the speed of initial page load, and the speed of subsequent executions (which may or may not turn out to be negligible, I haven't measured this).

**Comment by Timer** [comment]
@Janpot I believe you're referring to v8 engine deoptimizing `try`/`catch` blocks.
I'm aware of this legacy-concern &mdash; v8 no longer deoptimizes try/catch.

While this may "deoptimize" the code in legacy browsers, it only has a measurable effect on code with high cyclomatic complexity.

In this specific case, "execution speed" is irrelevant because this code path is not in the hot-path (to hydration).

**Review by ijjk — APPROVED** [review]
Nice bundle savings 👍 

Note: CI failures are un-related to this PR, confirmed locally

**Comment by Janpot** [comment]
@Timer I didn't mean the deoptimization, throwing and catching exceptions is [generally slower](https://jsperf.com/property-access-cdhjsg) than testing properties. But as you said, execution speed is irrelevant in this context, and as I said before, the impact is probably negligible.
👍 Good point about the double dom access

**Comment by Timer** [comment]
Ah, @Janpot this code *must* be wrapped in a `try`/`catch` because `support` throws an error in browsers that don't support it.

**Comment by Janpot** [comment]
Yes, but I'm specifically talking about the case where the property access is throwing the error. There, when you check for property existence first, the try/catch becomes a no-op. In case the property exists, then the performance of both versions will be similar.

**Comment by Janpot** [comment]
The bad performance code path would only happen on outdated browsers anyway. So nothing to worry about on the end I think.

**Comment by Timer** [comment]
Yeah, I checked the perf for curiosity -- only a 4% +- 2% difference on modern browsers.

**Pull request merged**
