### PR TITLE
Don't rely on Content-Type header for Image optimization

### LINKED ISSUE #23523: Signed images from S3 no longer working with next/image
### EDIT
~It seems to only be an issue with certain images (these images worked in the prior version of Next.js and still do). These images that error tend to also be the ones which are frequently loaded because of the pages I use to test my platform. Is there a chance something changed with the caching I need to clear (have already wiped `.next` a few times to no avail). As far as I can tell, the images which are erroring are the ones I loaded from the external domain prior to upgrading. One's I did not load prior to upgrading still worked. I have tested in multiple browsers and in incognito to make sure there isn't a browser cache issue, and haven't been able to resolve the issue.~ See comment [here](https://github.com/vercel/next.js/issues/23523#issuecomment-810608683)

### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Not currently deployed

### Describe the Bug

Previously, pulling signed images from my S3 bucket worked fine with `next/image`. In fact, if I do a normal `` it still works. Since 10.1.1 however, `next/image` is now reporting `The requested resource isn't a valid image.` when I pass it the same url which worked fine previously, and still works fine in a native image tag. I have downgraded to verify that it is in fact a new behavior since the latest version of next.js@10.0.x

### Expected Behavior

The image would return and display

### To Reproduce

Pass `next/image` a signed url from an Amazon S3 Bucket

### PR DESCRIPTION
**Pull request by nring**
## Bug

- [x] Related issues linked using `fixes #23523 `
- [ ] Integration tests added

Images served from S3 won't always have the correct Content-Type header set. This causes Next's image optimizer to dismiss the request and return a 400 even if the requested resource is a valid image. 

I looked into adding an integration test but was unable to figure out how to manually mock the Next server's `Content-Type` response header to `application/octet-stream`.

### CODE REVIEW

**Comment by nring** [comment]
> I think this looks good, tho I would probably check that filename ends with `.${fileType}` to exclude any filename without extension and the actual filename ends with string same as one of the values in FILE_TYPES -array.
> 
> Other than that, great work I think.

Good catch, updated PR.

**Comment by prarabdhb** [comment]
For the integration test, maybe you can add a test bely using a similar function
https://github.com/vercel/next.js/blob/54ff3223b402b963baa189334587e2e590054276/test/integration/api-body-parser/test/index.test.js#L60

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| buildDuration | 14.8s | 15.1s | ⚠️ +342ms |
| buildDurationCached | 4.7s | 4.4s | -328ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +1.06 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.489 | 2.528 | ⚠️ +0.04 |
| / avg req/sec | 1004.48 | 988.96 | ⚠️ -15.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.604 | 1.536 | -0.07 |
| /error-in-render avg req/sec | 1558.48 | 1627.48 | +69 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| index.html gzip | 560 B | 560 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 557 B | 557 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| buildDuration | 17.7s | 17.6s | -113ms |
| buildDurationCached | 6.5s | 6.3s | -168ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +1.06 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.3 kB | 19.3 kB | ✓ |
| webpack-HASH.js gzip | 996 B | 996 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.52 kB | 8.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _buildManifest.js gzip | 394 B | 394 B | ✓ |
| Overall change | 394 B | 394 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _error.js | 1.34 MB | 1.34 MB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | ✓ |
| link.js | 1.4 MB | 1.4 MB | -2 B |
| routerDirect.js | 1.39 MB | 1.39 MB | ✓ |
| withRouter.js | 1.39 MB | 1.39 MB | ✓ |
| Overall change | 6.9 MB | 6.9 MB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| buildDuration | 12s | 12s | -3ms |
| buildDurationCached | 4.9s | 4.9s | ⚠️ +48ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +1.06 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.604 | 2.489 | -0.12 |
| / avg req/sec | 960.23 | 1004.45 | +44.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.456 | 1.437 | -0.02 |
| /error-in-render avg req/sec | 1717.59 | 1740.12 | +22.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.72 kB | 3.72 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.37 kB | 9.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nring/next.js 23523_S3_IMAGES | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: 43a4afc6d01862136e9ab46e30b0464ddb158912

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 43a4afc6d01862136e9ab46e30b0464ddb158912

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > server-side only compilation errors

<details>
<summary>Expand output</summary>

  ● server-side only compilation errors

    ScriptTimeoutError: script timeout
      (Session info: headless chrome=90.0.4430.93)

      72 |
      73 |             // Wait for application to re-hydrate:
    > 74 |             await browser.executeAsyncScript(function () {
         |             ^
      75 |               var callback = arguments[arguments.length - 1]
      76 |               if (window.__NEXT_HYDRATED) {
      77 |                 callback()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
          at runMicrotasks (<anonymous>)
      at Proxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.patch (acceptance/helpers.js:74:13)
      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:1387:3)

</details>

**Comment by nring** [comment]
> For the integration test, maybe you can add a test by using a similar function
> https://github.com/vercel/next.js/blob/54ff3223b402b963baa189334587e2e590054276/test/integration/api-body-parser/test/index.test.js#L60
> 
> You would have to update the following test case, as it shouldn't return 400 when Content Type is not one of image types.
> https://github.com/vercel/next.js/blob/9fcfce3463095af63e93251ae12f5cac8344aa7f/test/integration/image-optimizer/test/index.test.js#L506

@prarabdhb I don't think that would work because I can't control what the response headers will look like. That function only allows me to set the request headers.

**Comment by alexvilchis** [comment]
What else is still pending? Are any tests failing?

**Comment by nring** [comment]
@alexvilchis No tests were failing when I first opened the PR but I wasn't able to add a new test to mock the "incorrect' Content Type header. Feel free to run with this if you're able.

**Review by ijjk — COMMENTED** [review]
Hi, it looks like this should be solved now from https://github.com/vercel/next.js/pull/26705 so I'm gonna close this, thanks for taking the time to open the PR! If you're still having trouble with this in the latest canary of Next.js `v11.0.2-canary.17` feel free to re-open with additional info!

**Pull request closed without merging**
