### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by matiastucci**

### CODE REVIEW

**Comment by leo** [comment]
Thanks!

**Comment by basedjux** [comment]
@kamisamamizu would it be possible for you to get me info about your Windows build, hyper version, npm, hyper config, etc?

**Comment by basedjux** [comment]
You’re the first person I’ve seen that it’s worked for

**Comment by basedjux** [comment]
*worked perfectly

**Comment by kamisamamizu** [comment]
Well, not perfectly, like I said in the post, the network info doesn't work, but everything else does, like you can see in the screenshot.
image

- Windows 10 v. 1703 (build 15063.540)
- Hyper 1.3.3
- Using Bash on Windows, but it automatically starts fish. Doesn't matter, it also works with cmd.
- Result of `npm version`:
`{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.2',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.103',
  zlib: '1.2.11' }
`
- Hyper config: https://pastebin.com/D7MtsNYM

If you need anything else, tell me.
Also, why is this conversation in here? Shouldn't it be in https://github.com/Hyperline/hyperline/issues/57#issuecomment-324336456 ?

**Comment by basedjux** [comment]
Uhhhh that's a good question 🤔 
When I replied to you I was looking at [Hyperline/hyperline#57](https://github.com/Hyperline/hyperline/issues/57#issuecomment-324336456)

I'm so confused right now...

**Pull request merged**
