### PR TITLE
sitemap.xml and robots.txt example

### PR DESCRIPTION
**Pull request by klyburke**
This example app shows you how to set up sitemap.xml and robots.txt files for proper indexing by search engine bots.

### CODE REVIEW

**Comment by sergiodxa** [comment]
Thanks for the example, just a question, how is this different to https://github.com/zeit/next.js/tree/canary/examples/root-static-files? Could we improve the already existent example instead of creating a new one?

**Comment by brikou** [comment]
Why not just do something like this within your package.json?

```json
postbuild: "cp robots.txt sitemap.xml .next",
```

**Review by timneutkens — APPROVED** [review]
Seems fine to me

**Comment by klyburke** [comment]
Thanks @timneutkens !

**Comment by kachkaev** [comment]
@klyburke just curious: how do you make sure that when posts update, sitemap is updated too? Looks like at the momemt sitemap is generated on server launch only.

**Comment by klyburke** [comment]
@kachkaev good question. I've updated the example and added a description to the README to address it.

The current example does not automatically update sitemap when the posts are changed (by changing `n=5` in [posts.js](https://github.com/zeit/next.js/blob/canary/examples/with-sitemap-and-robots-express-server/server/posts.js)).

[This app](https://github.com/builderbook/builderbook/blob/5f33772b8896d646cff89493853f34e61de6179a/server/sitemapAndRobots.js#L11), in which posts are fetched from a database, does update sitemap after the `cacheTime`.

**Comment by spencersmb** [comment]
Just installed this and everything is working locally except for the robots.txt doesn't seem to be getting generated. I can console.log the path and it's displaying the correct path in the static folder, but the .get Route is not writing the file. Please advise if you can, thanks!

**Pull request merged**
