### PR TITLE
Fix #7167: React Context Consumer value

### LINKED ISSUE #7167: 8.1.0 Context.Consumer value is undefined
# Bug report

## Describe the bug

In Next.js 8.1.0 React Context.Consumer receives value of undefined

Only on server side

UPDATE: Only in production, not in `npm run dev`

## To Reproduce

Reproduce repository - [link](https://github.com/zpnester/next-consumer-issue)

```js
const MyContext = React.createContext();

function Home() {

    return <MyContext.Provider value={{ x: "123" }}>
        <MyContext.Consumer>
            {value => value.x}
        </MyContext.Consumer>
    </MyContext.Provider>
}

export default Home;
```

## Expected behavior
MyContext.Consumer value should receive object from MyContext.Provider

## System information
 - Version of Next.js: 8.1.0

## Additional context

Also an issue for many Antd components

### PR DESCRIPTION
**Pull request by nblthree**
fix https://github.com/zeit/next.js/issues/7167 this PR check the version of React only when running `next build` and `next dev`

### CODE REVIEW

**Comment by timneutkens** [comment]
I'd like to figure out what happens here. Moving it to `next start` is definitely not the way to go. I guess the check has to be `React.hasOwnProperty('Suspense')`

**Comment by MarchWorks** [comment]
@timneutkens I will give it a try

**Comment by MarchWorks** [comment]
@timneutkens it doesn't have anything to do with the check itself the problem is caused by `const React = require('react') ` when running `npm start`

**Comment by timneutkens** [comment]
But why, it's literally requiring React 🤔

**Comment by MarchWorks** [comment]
@timneutkens maybe something happen here https://github.com/zeit/next.js/blob/canary/packages/next-server/server/render.tsx with that imported react
https://github.com/zeit/next.js/blob/6a5c39deaab2760d44fa29f7b3d9e981f123da37/packages/next-server/server/render.tsx#L94-L108

**Comment by MarchWorks** [comment]
@timneutkens I tried going from an `about` page to the `index` page where `Consumer` is used and it worked without problem but when ssr `index` the problem happen

**Pull request closed without merging**
