### PR TITLE
Update environment-variables.md

### PR DESCRIPTION
**Pull request by oitan**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by leerob** [comment]
This is correct. `.env.*.local` is saying that `.env.production.local` is valid https://stackoverflow.com/questions/55690143/what-is-the-difference-between-env-local-and-env-development-local

**Comment by oitan** [comment]
@leerob if you look to docs (https://nextjs.org/docs/basic-features/environment-variables) you can see 

> Note: similar to Default Environment Variables, .env.test file should be included in your repository, but .env.test.local shouldn't, as .env*.local are intended to be ignored through .gitignore.

So the change I am proposing is inclusive for both of the cases. WDYT?

**Comment by leerob** [comment]
I would say that version should also use `.env.*.local` 👍

**Comment by oitan** [comment]
What about `.env.local`? Should it be ignored too? It doesn't match the `.env.*.local` however the doc says it's for secrets. I'm just curious.

**Pull request closed without merging**
