### PR TITLE
Upgrade styled-jsx to v2.2.1

### PR DESCRIPTION
**Pull request by giuseppeg**
Includes some bug fixes. Do you guys update the lockfiles before releasing or per PR?

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
💯

**Comment by timneutkens** [comment]
Merged master with canary. After tests are successful I'll merge

**Comment by giuseppeg** [comment]
@timneutkens did you read my comment about `yarn.lock` and `package-lock.json`? 
We need to update them too.

**Comment by timneutkens** [comment]
@giuseppeg I'll do it before releasing 👍

**Pull request merged**
