### PR TITLE
Use consistent resolve extensions alias for compiler

### PR DESCRIPTION
**Pull request by timneutkens**
## What?

Changes the default resolve extensions to be consistent between server/client compilation.

Currently browser prefers `.mjs` then `.js` and the server compiler prefers `.js` then `.mjs`.

I added that behavior back in 2018 before mjs/cjs extensions were fully baked and many npm libraries had incorrect usage of it (PR: #5898).

In the new setup with ESM resolving in Node.js writing out the full extension is required for `.mjs` files, meaning this "magic resolving" of a file to `.mjs` is no longer correct. In the future we'll likely want to remove `.mjs` from the default list of resolve extensions to align with the Node.js ESM resolver a bit more.

For now we have to keep it in order to not break existing applications that rely on that behavior, an example of that seems to be contentlayer.

## How?

Removed the condition and aligned it on a single list instead of separate lists.

### CODE REVIEW

**Comment by timneutkens** [comment]
Current dependencies on/for this PR:
* canary
  * **PR #58725** <a href="https://app.graphite.dev/github/pr/vercel/next.js/58725?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/58725?utm_source=stack-comment).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ab457da3f148881825783cd77f2d21823a735890

`pnpm test-dev test/development/acceptance/ReactRefreshRequire.test.ts` 
- ReactRefreshRequire > propagates a module that stops accepting in next version

<details>
<summary>Expand output</summary>

  ● ReactRefreshRequire › propagates a module that stops accepting in next version

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 1

      Array [
    +   "init FooV1",
        "init BarV2",
        "init FooV1",
      ]

      442 |     // Since the export list changed, we have to re-run both the parent
      443 |     // and the child.
    > 444 |     expect(await session.evaluate(() => (window as any).log)).toEqual([
          |                                                               ^
      445 |       'init BarV2',
      446 |       'init FooV1',
      447 |     ])

      at Object.toEqual (development/acceptance/ReactRefreshRequire.test.ts:444:63)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.3s | ⚠️ +202ms |
| buildDurationCached | 5.8s | 5.8s | N/A |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 424ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| 199-HASH.js gzip | 28.7 kB | 28.7 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 501 B | 503 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.28 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| index.html gzip | 528 B | 526 B | N/A |
| link.html gzip | 538 B | 540 B | N/A |
| withRouter.html gzip | 522 B | 522 B | ✓ |
| Overall change | 522 B | 522 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.4 kB | 92.4 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 625 B | ✓ |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | ✓ |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 27.4 kB | 27.4 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 11-21-Use_consistent_resolve_extensions_alias_for_compiler | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | ✓ |
| app-page-exp..prod.js gzip | 93.4 kB | 93.4 kB | ✓ |
| app-page-tur..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page-tur..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-page.run...dev.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run..prod.js gzip | 88 kB | 88 kB | ✓ |
| app-route-ex...dev.js gzip | 23.8 kB | 23.8 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.5 kB | 16.5 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| server.runti..prod.js gzip | 49.1 kB | 49.1 kB | ✓ |
| Overall change | 924 kB | 924 kB | ✓ |

</details>

</details>
Commit: ab457da3f148881825783cd77f2d21823a735890

**Review by sokra — APPROVED** [review]
This might be a breaking change in some cases.

**Review by feedthejim — APPROVED** [review]

**Pull request merged**
