### PR TITLE
Improve data fetching documentation

### PR DESCRIPTION
**Pull request by Nutlope**
This is a PR to improve the Next.js data fetching docs. Here is a summary of the changes for each page:

### `Pages` page
- Linked to react beta docs instead of old react docs
- Made format of summary cards match
- Minor grammatical fixes

### `Overview` page
- Added missing example
- Mentioned CSR in summary sentence

### getStaticProps
- Added examples
- Added more detail to "When should I use getStaticProps?" section
- Moved ISR sentences to one paragraph at the end
- Moved order of this page to be before getStaticProps in sidebar

### ISR
- Added "When should I use ISR?" section and populated info from Vercel docs
- Moved "Version history" to the bottom as it's not likely relevant for most people
- Expanded on examples in more detail

### getServerSideProps & getStaticPaths
- basic formatting

### CODE REVIEW

**Review by leerob — CHANGES_REQUESTED** [review]
Will be pushing some updates here later this week so let's hold until then

**Comment by molebox** [comment]
Whats the status of this @Nutlope @leerob ?

**Comment by Nutlope** [comment]
@molebox Just need to clean up merge conflicts and it'll be ready for review. Will do later today – appreciate the reminder!

**Comment by Nutlope** [comment]
Actually, I need to go through the new changes to the data fetching docs and submit a new PR with the changes I requested if they weren't already applied. Closing this one for now.

**Pull request closed without merging**
