### PR TITLE
Prettier standard

### PR DESCRIPTION
**Pull request by bensalilijames**
Supercedes #5528.

This PR adds `prettier-standard` to the `lint-staged` step, but only to the `examples` folder.

The only real change in this PR is in `package.json`; the rest of the changes are a result of running `yarn prettier-standard "examples/**/*.js"` (and for `.ts` too)

Once we're happy with this for `examples`, I'd suggest expanding `prettier-standard` to the wider `next.js` codebase. Then we can start looking at incrementally moving towards `eslint`! :tada:

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Review by timneutkens — CHANGES_REQUESTED** [review]
I think the `lint` script also has to be updated.

**Comment by timneutkens** [comment]
@benhjames when you add the lint script I'll merge this 💯

**Comment by benhjames** [comment]
Now added to both the `lint` and (new?) `lint-fix` scripts. 👍 

Notably, `prettier-standard` doesn't expose a `--check` option (it always fixes in-place), but since it returns a non-zero exit code if there are some files that need to be formatted, then it will [function as a CI lint check](https://github.com/sheerun/prettier-standard/issues/17#issuecomment-445372076).

**Comment by timneutkens** [comment]
I wonder if instead of prettier-standard we could use eslint + eslint-config-standard + eslint-config-prettier and then use `prettier` itself.

**Comment by sheerun** [comment]
@timneutkens I tried this approach in prettier-standard but it doesn't work as `standard` has some whitespacing formatting rules that cannot be configured in prettier, notably: https://github.com/prettier/prettier/issues/3845 and https://github.com/prettier/prettier/issues/3847 and people kept complaining: https://github.com/sheerun/prettier-standard/issues/12

So until prettier implements parenthesis config matching standard, the only way is to run code through prettier first and standard after that.

**Comment by sheerun** [comment]
Honestly what would be really perfect if prettier implemented `--standard` flag I could just switch to using it in `prettier-standard` instead of passing through prettier and then eslint just for formatting. I think only theoretical `--check` flag should invoke eslint there.

**Comment by timneutkens** [comment]
I mean I guess it'd be fine to run prettier first and then standard --fix right 🤔 As standard doesn't really change multi-line rules 🤔

**Comment by sheerun** [comment]
That's pretty much what prettier-standard does

**Pull request closed without merging**
