### PR TITLE
Prevent hot-reload crashes.

### PR DESCRIPTION
**Pull request by fubhy**
In case of resource paths outside of the page dir, hot-reload currently fails and breaks because "dir" is undefined in this case.

This affects scenarios in which someone (e.g. me) would use external / linked npm packages in there.

### CODE REVIEW

**Comment by timneutkens** [comment]
@fubhy can you provide an example of when this is the case (like a github repo with a minimal reproduction).

**Comment by fubhy** [comment]
Hi @timneutkens!

I created https://github.com/fubhy/next-hot-reload-broken as a quick demo. I am not sure if it is caused by my compination of next, lerna and typescript or if this bug also affects non-typescript builds.

**Comment by fubhy** [comment]
@timneutkens Hai there. Is there anything else I can do to get this merged?

**Comment by fubhy** [comment]
Friendly ping  (:

**Comment by timneutkens** [comment]
I'm pretty sure this will break something, haven't had time to check it out yet.

**Comment by timneutkens** [comment]
Spent a few hours debugging but it was definitely in your code. Not sure why you're looping over all rules without any checks 🤔 https://github.com/fubhy/next-hot-reload-broken/pull/1

In the process of debugging this I found something else though, which I've fixed #4092.

**Comment by fubhy** [comment]
Thanks for checking!

**Pull request closed without merging**
