### PR TITLE
refactor(codemod): replace chalk with picocolors

### PR DESCRIPTION
**Pull request by SukkaW**
The PR replaces `chalk` inside `@next/codemod` with `picocolors`.

Generally, `@next/codemod` is used through `npx`/`pnpx` as it serves as a sort of "one-time fix". By replacing `chalk` with the `picocolors` (which is 14 times smaller and 2 times faster), we can speed up the installation process of `npx @next/codemod`.

Currently, `@next/codemod` has about 10k downloads per week, so I guess this PR is worth it:

image

In my next PR, I will replace `chalk` inside `create-next-app` with `picocolors` as well.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ac8603cf9d1cfb77885cfd6ed4efeff7f03cb98a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by styfle — COMMENTED** [review]
Thanks!

We could also probably replace `meow` with `arg`.

Or we could even use the native [`util.parseArgs()`](https://nodejs.org/api/util.html#utilparseargsconfig) if we set engines to `>=16.17.0`.

**Review by styfle — APPROVED** [review]

**Review by huozhi — APPROVED** [review]

**Comment by gruckion** [comment]
> Thanks!
> 
> We could also probably replace `meow` with `arg`.
> 
> Or we could even use the native [`util.parseArgs()`](https://nodejs.org/api/util.html#utilparseargsconfig) if we set engines to `>=16.17.0`.

TODO action needed here?

**Comment by gruckion** [comment]
> The PR replaces `chalk` inside `@next/codemod` with `picocolors`.
> 
> Generally, `@next/codemod` is used through `npx`/`pnpx` as it serves as a sort of "one-time fix". By replacing `chalk` with the `picocolors` (which is 14 times smaller and 2 times faster), we can speed up the installation process of `npx @next/codemod`.
> 
> Currently, `@next/codemod` has about 10k downloads per week, so I guess this PR is worth it:
> 
> image
> In my next PR, I will replace `chalk` inside `create-next-app` with `picocolors` as well.

States on two times faster?

**Pull request merged**
