### PR TITLE
Replace `CLIEngine` with `ESLint`

### PR DESCRIPTION
**Pull request by matamatanot**
## Refactor

> The CLIEngine class has been deprecated

https://eslint.org/docs/user-guide/migrating-to-7.0.0#the-cliengine-class-has-been-deprecated

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 13.5s | 14.2s | ⚠️ +676ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +30ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.773 | 2.832 | ⚠️ +0.06 |
| / avg req/sec | 901.42 | 882.86 | ⚠️ -18.56 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.533 | 1.682 | ⚠️ +0.15 |
| /error-in-render avg req/sec | 1631.05 | 1486.6 | ⚠️ -144.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| index.html gzip | 572 B | 572 B | ✓ |
| link.html gzip | 581 B | 581 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.2s | ⚠️ +145ms |
| buildDurationCached | 4.7s | 4.3s | -305ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 12s | 11.8s | -247ms |
| buildDurationCached | 4.7s | 5.1s | ⚠️ +377ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.752 | 2.78 | ⚠️ +0.03 |
| / avg req/sec | 908.41 | 899.33 | ⚠️ -9.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.528 | 1.62 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1636.15 | 1543.67 | ⚠️ -92.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.17 kB | 9.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| index.html gzip | 626 B | 626 B | ✓ |
| link.html gzip | 632 B | 632 B | ✓ |
| withRouter.html gzip | 619 B | 619 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: 12d71893f13d31222d872df5e88ca49aa095b025

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 10.6s | 11.1s | ⚠️ +421ms |
| buildDurationCached | 2.6s | 2.6s | -2ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.205 | 2.184 | -0.02 |
| / avg req/sec | 1133.94 | 1144.53 | +10.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.114 | 1.125 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2243.27 | 2222.01 | ⚠️ -21.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| index.html gzip | 572 B | 572 B | ✓ |
| link.html gzip | 581 B | 581 B | ✓ |
| withRouter.html gzip | 568 B | 568 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 12.2s | 11.9s | -242ms |
| buildDurationCached | 3.5s | 3.5s | ⚠️ +51ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.5s | -61ms |
| buildDurationCached | 3.8s | 3.9s | ⚠️ +58ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.176 | 2.207 | ⚠️ +0.03 |
| / avg req/sec | 1148.79 | 1132.71 | ⚠️ -16.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.102 | 1.144 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2267.95 | 2184.73 | ⚠️ -83.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.17 kB | 9.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-CLIEngine-with-ESLint-because-of-deprecated | Change |
| - | - | - | - |
| index.html gzip | 626 B | 626 B | ✓ |
| link.html gzip | 632 B | 632 B | ✓ |
| withRouter.html gzip | 619 B | 619 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: 42e4a6d888cf38a76930668a20f6c4622af0fe51

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 42e4a6d888cf38a76930668a20f6c4622af0fe51

**test/integration/basic/test/index.test.js** 
- Basic Features > Hot Module Reloading > editing a page > should update styles correctly

<details>
<summary>Expand output</summary>

  ● Basic Features › Hot Module Reloading › editing a page › should update styles correctly

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hmr-style-page p"}
      (Session info: headless chrome=91.0.4472.77)

      149 |         try {
      150 |           browser = await webdriver(context.appPort, '/hmr/style')
    > 151 |           const pTag = await browser.elementByCss('.hmr-style-page p')
          |                        ^
      152 |           const initialFontSize = await pTag.getComputedCss('font-size')
      153 |
      154 |           expect(initialFontSize).toBe('100px')

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/basic/test/hmr.js:151:24)

</details>

**Pull request merged**
