### PR TITLE
issue #254 vertically center default error

### PR DESCRIPTION
**Pull request by mattcass**

### CODE REVIEW

**Comment by rauchg** [comment]
Amazing, thank you. By the way, do you happen to know if we could include some sort of "fallback properties" so that it doesn't look _bad_ in non-flexbox browsers? since this is a core thing, it'd be nice to contemplate those.

**Comment by rauchg** [comment]
In other words, I wonder what this would look like on browserstack using IE8 let's say, as-is. Maybe it doesn't look bad. It doesn't even need to look centered, just functional

**Comment by mattcass** [comment]
Sure, the flexbox approach keeps the error message centered down to IE10. For IE9/8 the message is still functional, it displays in the upper left and the text wraps on smaller screens down to IE8.

**Comment by rauchg** [comment]
This is amazing. Thank you so much @mattcass

**Pull request merged**
