### PR TITLE
mobx-state-tree examples should use _app

### PR DESCRIPTION
**Pull request by yoDon**
The mobx-state-tree examples (with and without typescript) pre-dated the next _app class and needed to be updated to use _app for persisting state across client-side navigation transitions. Also removed unneeded custom server class to better keep with the "show one feature per example" style of the next examples folder

### CODE REVIEW

**Comment by yoDon** [comment]
Making use of _app allowed for a significant reduction in the amount of copy-and-pasted boilerplate state management code shared between pages/index.js and pages/other.js

**Comment by timneutkens** [comment]
This PR looks great, just had 2 comments 👍

**Comment by yoDon** [comment]
The two issues you spotted in reviewing the PR should be fixed

**Comment by yoDon** [comment]
@timneutkens I think the two issues you called out on this PR are resolved. OK to merge into canary?

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
