### PR TITLE
Adding section-blog-theme in example folder

### PR DESCRIPTION
**Pull request by officialrajdeepsingh**
### Adding a new example

Adding new [section blog theme](https://section-blog-theme-docs.vercel.app) in next.js example folder.

The section blog theme based on nextra, nextjs, tailwind CSS, shadcn UI and typescript.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 919f713a88e1cca63760a71041df6ec0226e7479

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 919f713a88e1cca63760a71041df6ec0226e7479

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 919f713a88e1cca63760a71041df6ec0226e7479

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@officialrajdeepsingh Unfortunately, we already have a [Nextra example](https://github.com/vercel/next.js/tree/canary/examples/blog). I would look to just update that one, but also be using App Router instead.

**Comment by officialrajdeepsingh** [comment]
> @officialrajdeepsingh Unfortunately, we already have a [Nextra example](https://github.com/vercel/next.js/tree/canary/examples/blog). I would look to just update that one, but also be using App Router instead.

Both examples use Nextra, but the Nextra theme is different. I built my theme based on Nextra and used some modern tools. 
The section blog theme has more features than the nextra blog theme. This is a difference.
Lastly, nextra does not support app router fully.

**Comment by leerob** [comment]
Thanks for the suggestion! Let's publish this as a separate repo since there's something similar here. Thank you regardless 🙏

**Pull request closed without merging**
