### PR TITLE
types: try resolving the real types instead of aliasing

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
### What?

By using `paths` in `tsconfig.json` we can tell typescript where it can find the types for our compiled packages.

Closes PACK-2029

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c523e44420c59bcedbb85fa2c38a10fcfda13f67

`pnpm test test/integration/compression/test/index.test.js` 
- Compression > should compress responses by default

<details>
<summary>Expand output</summary>

  ● Compression › should compress responses by default

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      13 |
      14 | describe('Compression', () => {
    > 15 |   beforeAll(async () => {
         |   ^
      16 |     context.appPort = await findPort()
      17 |     context.server = await launchApp(join(__dirname, '../'), context.appPort)
      18 |

      at beforeAll (integration/compression/test/index.test.js:15:3)
      at Object.describe (integration/compression/test/index.test.js:14:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c523e44420c59bcedbb85fa2c38a10fcfda13f67

`pnpm test test/integration/client-navigation-a11y/test/index.test.js` 
- Client Navigation accessibility > <RouteAnnouncer /> > should not have the initial route announced
- Client Navigation accessibility > <RouteAnnouncer /> > has aria-live="assertive" and role="alert"
- Client Navigation accessibility > <RouteAnnouncer /> > There is a title and a h1 tag > has the innerText equal to the value of h1
- Client Navigation accessibility > <RouteAnnouncer /> > There is a title but no h1 tag > has the innerText equal to the value of document.title
- Client Navigation accessibility > <RouteAnnouncer /> > There is no title and no h1 tag > has the innerText equal to the value of the pathname
- Client Navigation accessibility > <RouteAnnouncer /> > There is no title but a h1 tag > has the innerText equal to the value of h1

<details>
<summary>Expand output</summary>

  ● Client Navigation accessibility › <RouteAnnouncer /> › should not have the initial route announced

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

  ● Client Navigation accessibility › <RouteAnnouncer /> › has aria-live="assertive" and role="alert"

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

  ● Client Navigation accessibility › <RouteAnnouncer /> › There is a title but no h1 tag › has the innerText equal to the value of document.title

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

  ● Client Navigation accessibility › <RouteAnnouncer /> › There is no title but a h1 tag › has the innerText equal to the value of h1

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

  ● Client Navigation accessibility › <RouteAnnouncer /> › There is a title and a h1 tag › has the innerText equal to the value of h1

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

  ● Client Navigation accessibility › <RouteAnnouncer /> › There is no title and no h1 tag › has the innerText equal to the value of the pathname

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      28 |
      29 | describe('Client Navigation accessibility', () => {
    > 30 |   beforeAll(async () => {
         |   ^
      31 |     context.appPort = await findPort()
      32 |     context.server = await launchApp(appDir, context.appPort, {
      33 |       env: { __NEXT_TEST_WITH_DEVTOOL: 1 },

      at beforeAll (integration/client-navigation-a11y/test/index.test.js:30:3)
      at Object.describe (integration/client-navigation-a11y/test/index.test.js:29:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

`pnpm test test/integration/app-aspath/test/index.test.js` 
- App asPath > should not have any changes in asPath after a bundle rebuild

<details>
<summary>Expand output</summary>

  ● App asPath › should not have any changes in asPath after a bundle rebuild

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      16 |
      17 | describe('App asPath', () => {
    > 18 |   beforeAll(async () => {
         |   ^
      19 |     appPort = await findPort()
      20 |     server = await launchApp(join(__dirname, '../'), appPort)
      21 |

      at beforeAll (integration/app-aspath/test/index.test.js:18:3)
      at Object.describe (integration/app-aspath/test/index.test.js:17:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.7s | ⚠️ +122ms |
| buildDurationCached | 6.1s | 5.9s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +8.03 kB |
| nextStartRea..uration (ms) | 427ms | 421ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.7 kB | 26.7 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| index.html gzip | 529 B | 525 B | N/A |
| link.html gzip | 542 B | 538 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 627 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hrmny/avoid-pkg-types-aliases | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 93.9 kB | 93.9 kB | ✓ |
| app-page-tur..prod.js gzip | 94.7 kB | 94.7 kB | ✓ |
| app-page-tur..prod.js gzip | 89.2 kB | 89.2 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.5 kB | 88.5 kB | ✓ |
| app-route-ex...dev.js gzip | 23.9 kB | 23.9 kB | ✓ |
| app-route-ex..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.6 kB | 16.6 kB | ✓ |
| app-route-tu..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.2 kB | 16.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 929 kB | 929 kB | ✓ |

</details>

</details>
Commit: c523e44420c59bcedbb85fa2c38a10fcfda13f67

**Comment by ForsakenHarmony** [comment]
<b>In this stack:</b> <code>🔧 Resolve real types instead of aliasing</code><a href="https://withgraphite.notion.site/Graphite-beta-features-EXTERNAL-496843566b204c7a97a2a21f8dea5434">(?)</a>

* `canary`
  * **#58841** <a href="https://app.graphite.dev/github/pr/vercel/next.js/58841?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ForsakenHarmony and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ForsakenHarmony** [comment]
Blocked because turbopack resolves all `tsconfig.json` files it finds instead of just the one for the app

**Pull request closed without merging**
