### PR TITLE
Use right next.js version for with-dynamic-import

### LINKED ISSUE #2416: example with-dynamic-import doesn't work
TypeError: promise.then is not a function

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #2416

### CODE REVIEW

**Comment by supra28** [comment]
I think this should be "next": "latest" to keep it consistent across all examples.

**Comment by timneutkens** [comment]
@supra28 dynamic imports are new and only released as part of the beta. I'll update the example when we release v3.

**Comment by supra28** [comment]
@timneutkens ooh thankyou, i was confused.

**Comment by timneutkens** [comment]
:ok_hand:

**Pull request merged**
