### PR TITLE
CSS Hooks example project

### PR DESCRIPTION
**Pull request by nsaunders**
Hi, following up on #57067 in which @balazsorban44 kindly invited me to add an example project to demonstrate CSS Hooks within a Next.js app.

Thank you for considering my submission, and please let me know if there are any thoughts, questions, or concerns I can answer.

### Adding or Updating Examples

[x] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
[x] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### CODE REVIEW

**Comment by nsaunders** [comment]
Hi @balazsorban44, wondering if you have had a chance to review this? Please let me know if there's anything I can do to improve this submission.

**Review by leerob — DISMISSED** [review]

**Comment by leerob** [comment]
Looks like linting is failing here 🙏

**Comment by nsaunders** [comment]
Hi @leerob, thanks so much for taking a look. I've formatted the four files that had issues using the `prettier-fix` script.

**Comment by nsaunders** [comment]
People can go to https://css-hooks.com for an up-to-date example. Thanks.

**Pull request closed without merging**
