### PR TITLE
Remove mz

### PR DESCRIPTION
**Pull request by timneutkens**
Removes `mz` as per #3977

### CODE REVIEW

**Comment by timneutkens** [comment]
Node.js's util.promisify, refactored to work without Node.
```
const kCustomPromisifyArgsSymbol = Symbol("customPromisifyArgs");
module.exports = function promisify(original) {
  // Names to create an object from in case the callback receives multiple
  // arguments, e.g. ['stdout', 'stderr'] for child_process.exec.
  const argumentNames = original[kCustomPromisifyArgsSymbol];

  return function fn(...args) {
    return new Promise((resolve, reject) => {
      try {
        original.call(this, ...args, (err, ...values) => {
          if (err) {
            reject(err);
          } else if (argumentNames !== undefined && values.length > 1) {
            const obj = {};
            for (var i = 0; i < argumentNames.length; i++)
              obj[argumentNames[i]] = values[i];
            resolve(obj);
          } else {
            resolve(values[0]);
          }
        });
      } catch (err) {
        reject(err);
      }
    })
  }
}
```

to test
```
const cbFn = (glob, fn) => {
  fn(null, glob);
};

const pr = promisify(cbFn)

pr("test").then(console.log)
```

**Comment by arunoda** [comment]
@timneutkens changes looks fine by me. But, need to know why the tests are failing?

**Comment by timneutkens** [comment]
@arunoda it's broken, will check why.

**Comment by timneutkens** [comment]
PR is broken, going to close for now.

**Pull request closed without merging**
