### PR TITLE
Updated the example of with-vercel-fetch to utilize the App Router.

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-vercel-fetch example for using the App Router.
Here are the changes that have been made:

- Renamed the "pages" folder to the "app" folder.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: edfbbf5e615057721338e3fb5f133a825f69dde0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by darthmaim** [comment]
https://github.com/vercel/fetch is archived, so it might make more sense to just get rid of this example.

**Comment by PapatMayuri** [comment]
@samcx  Any change needed for this PR?

**Comment by samcx** [comment]
@PapatMayuri Let's get rid of this example! I don't think it's necessary to have an example just for fetch.

**Comment by PapatMayuri** [comment]
Okay, @samcx  should I close the PR?

**Comment by PapatMayuri** [comment]
https://github.com/vercel/fetch is archived, so closing the PR.

**Comment by samcx** [comment]
@PapatMayuri We should to delete the example, not close this PR.

**Review by samcx — APPROVED** [review]

**Pull request merged**
