### PR TITLE
bug (#21943): remove incorrect rewrite of parsedUrl.pathname in serverless handler

### LINKED ISSUE #21943: [i18n] non-default locale root level routes (i.e. /fr /es) get 307 redirects to themselves?
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

14.12.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Other platform

**Describe the Bug**

i18n + target: serverless

[this line](https://github.com/vercel/next.js/blob/8f21c283b27357dbb2aebe94587901b6c7f4fe64/packages/next/next-server/server/next-server.ts#L505) is true _only_ for non-default locale **root** routes (aka `/pl` or `/fr` etc). when `shouldAddLocalePrefix` is true, it [passes this condition](https://github.com/vercel/next.js/blob/8f21c283b27357dbb2aebe94587901b6c7f4fe64/packages/next/next-server/server/next-server.ts#L513) (which therefore fails for non-root routes like `/pl/static`) and [sets up a 307](https://github.com/vercel/next.js/blob/8f21c283b27357dbb2aebe94587901b6c7f4fe64/packages/next/next-server/server/next-server.ts#L538) to `/pl`, which can cause infinite redirects.

i'm looking to better understand why this logic exists for root non-default locale pages in i18n. specifically, this line:

`const shouldAddLocalePrefix = !detectedDefaultLocale && denormalizedPagePath === '/'`

what is the purpose of this condition? `denormalizedPagePath` becomes `/` when req.url is `/fr` or `/pl`. so like i said, it will eventually get to the res.setHeader and formatUrl using this value `${basePath || ''}/${detectedLocale}` which becomes `/fr` or `/pl`. the problem with this is if you're serving next page (`.next/serverless/pages/index.js`) for `/${locale}`, the 307 will hit `/${locale}` again, reprocess the next page, re-hit the 307, etc etc.

i traced this work back to @ijjk so i assume they'll have the most insight :) 

**Expected Behavior**

no 307s from `/${locale}` to `/${locale}`

**To Reproduce**

this is mainly just a question to understand so no need to repro. as answered previously though, yes, this is observed on a platform that is not vercel. my hope is that next maintainers are still diligent about helping those who don't or can't host on vercel! :pray:

thanks so much for your time and help! really appreciate it <3

### PR DESCRIPTION
**Pull request by lindsaylevine**
Fixes https://github.com/vercel/next.js/issues/21943

i confirmed in a personal test repo that this solves the issue of infinite 307s on root level non-default locales :)  let me know what else this needs if anything! thanks for the time/help @ijjk ❤️

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 9s | 9.8s | ⚠️ +858ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | -151 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.858 | 1.893 | ⚠️ +0.03 |
| / avg req/sec | 1345.35 | 1320.99 | ⚠️ -24.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.127 | 1.105 | -0.02 |
| /error-in-render avg req/sec | 2218.39 | 2262.03 | +43.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.9s | ⚠️ +27ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | -151 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _error.js | 1.01 MB | 1.01 MB | -45 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.01 MB | 1.01 MB | -45 B |
| link.js | 1.06 MB | 1.06 MB | -45 B |
| routerDirect.js | 1.06 MB | 1.06 MB | -45 B |
| withRouter.js | 1.06 MB | 1.06 MB | -45 B |
| Overall change | 5.21 MB | 5.21 MB | -225 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 11.8s | 10.9s | -848ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | -151 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.76 | 1.673 | -0.09 |
| / avg req/sec | 1420.68 | 1494.49 | +73.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.049 | 1.075 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2383.07 | 2326.25 | ⚠️ -56.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 597-dc8125e2..ef24.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60 kB | 60 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "Q7w4QHRjFx6S4rlbfIpbT",
+        "buildId": "z25h5B46n6CRzr1FPjrpc",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_buildManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_ssgManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "Q7w4QHRjFx6S4rlbfIpbT",
+        "buildId": "z25h5B46n6CRzr1FPjrpc",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_buildManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_ssgManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "Q7w4QHRjFx6S4rlbfIpbT",
+        "buildId": "z25h5B46n6CRzr1FPjrpc",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_buildManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/Q7w4QHRjFx6S4rlbfIpbT/_ssgManifest.js"
+      src="/_next/static/z25h5B46n6CRzr1FPjrpc/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: ce648e85818a36fab4a58aa83e35affe0f3417d2

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ce648e85818a36fab4a58aa83e35affe0f3417d2

**test/integration/i18n-support-catchall/test/index.test.js** 
- i18n Support Root Catch-all > serverless mode > should normalize locale items in route-matches
- i18n Support Root Catch-all > serverless mode > should navigate to other locale index and back
- i18n Support Root Catch-all > serverless mode > should navigate to other locale page and back

<details>
<summary>Expand output</summary>

  ● i18n Support Root Catch-all › serverless mode › should normalize locale items in route-matches

    expect(received).toBe(expected) // Object.is equality

    Expected: "/hello"
    Received: "/fr/[[...slug]]"

      354 |       expect($3('#router-locale').text()).toBe('fr')
      355 |       expect($3('#router-pathname').text()).toBe('/[[...slug]]')
    > 356 |       expect($3('#router-as-path').text()).toBe('/hello')
          |                                            ^
      357 |       expect($3('#router-default-locale').text()).toBe('en-US')
      358 |       expect(JSON.parse($3('#router-query').text())).toEqual({
      359 |         slug: ['hello'],

      at Object.<anonymous> (integration/i18n-support-catchall/test/index.test.js:356:44)

  ● i18n Support Root Catch-all › serverless mode › should navigate to other locale index and back

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 5

    @@ -8,7 +8,11 @@
          "nl",
          "fr-BE",
          "fr",
          "en",
        ],
    -   "params": Object {},
    +   "params": Object {
    +     "slug": Array [
    +       "nl-NL",
    +     ],
    +   },
      }

      105 |       JSON.parse(await browser.elementByCss('#router-locales').text())
      106 |     ).toEqual(locales)
    > 107 |     expect(JSON.parse(await browser.elementByCss('#props').text())).toEqual({
          |                                                                     ^
      108 |       params: {},
      109 |       locale: 'nl-NL',
      110 |       locales,

      at Object.<anonymous> (integration/i18n-support-catchall/test/index.test.js:107:69)

  ● i18n Support Root Catch-all › serverless mode › should navigate to other locale page and back

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 1

    @@ -10,9 +10,10 @@
          "fr",
          "en",
        ],
        "params": Object {
          "slug": Array [
    +       "nl-NL",
            "another",
          ],
        },
      }

      158 |       JSON.parse(await browser.elementByCss('#router-locales').text())
      159 |     ).toEqual(locales)
    > 160 |     expect(JSON.parse(await browser.elementByCss('#props').text())).toEqual({
          |                                                                     ^
      161 |       params: {
      162 |         slug: ['another'],
      163 |       },

      at Object.<anonymous> (integration/i18n-support-catchall/test/index.test.js:160:69)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.9s | ⚠️ +38ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +37 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.428 | 2.46 | ⚠️ +0.03 |
| / avg req/sec | 1029.63 | 1016.44 | ⚠️ -13.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.828 | 1.747 | -0.08 |
| /error-in-render avg req/sec | 1367.51 | 1430.64 | +63.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.3s | -161ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +37 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _error.js | 1.01 MB | 1.01 MB | ⚠️ +14 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.01 MB | 1.01 MB | ⚠️ +14 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +14 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +14 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +14 B |
| Overall change | 5.21 MB | 5.21 MB | ⚠️ +70 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.5s | ⚠️ +293ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +37 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.355 | 2.359 | 0 |
| / avg req/sec | 1061.37 | 1059.56 | ⚠️ -1.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.638 | 1.642 | 0 |
| /error-in-render avg req/sec | 1525.87 | 1522.86 | ⚠️ -3.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| 597-74632e79..1d47.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60.1 kB | 60.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | lindsaylevine/next.js bug/i18n-root-307-redirects | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "ev7UCuU924PIWjZcR7eJM",
+        "buildId": "2V5IjhEjYBhZK5tAPakeM",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_buildManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_ssgManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "ev7UCuU924PIWjZcR7eJM",
+        "buildId": "2V5IjhEjYBhZK5tAPakeM",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_buildManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_ssgManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "ev7UCuU924PIWjZcR7eJM",
+        "buildId": "2V5IjhEjYBhZK5tAPakeM",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_buildManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/ev7UCuU924PIWjZcR7eJM/_ssgManifest.js"
+      src="/_next/static/2V5IjhEjYBhZK5tAPakeM/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: a4eb56aaff4812fc1528d1c2a3a3e382c71bbf87

**Review by ijjk — APPROVED** [review]
Thanks for the PR! I went ahead and added a test case for this as well to ensure we don't regress on it.

**Comment by lindsaylevine** [comment]
@ijjk haha dont thank me, thank YOU! after the tests failed i was gonna circle back and try to figure out what the actual change should be (and then maybe add a test) but i'm thankful you took care of it for me/us 🙏 . much appreciated!

**Pull request merged**
