### PR TITLE
updated with-orbit-components example to utilize the App Router.

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-orbit-components example for using the App Router.
Here are the changes that have been made:

- I renamed the `pages` folder and moved it to the `app` folder.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f7319cffb52f1c9a7fd725edd0cc659953ee7d0d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@PapatMayuri Let me know when this is ready (it's marked as a draft)!

**Comment by PapatMayuri** [comment]
@samcx it's ready for review please check.

**Comment by samcx** [comment]
@PapatMayuri This example should be re-done using the Tailwind preset with orbit components.

**Comment by PapatMayuri** [comment]
@samcx  I have updated PR please check and let me know if required any changes.

**Comment by samcx** [comment]
@PapatMayuri Can you make sure to remove Babel and everything related to Style Components?

**Comment by PapatMayuri** [comment]
@samcx  updated PR please check.

**Comment by samcx** [comment]
@PapatMayuri Style Components are still in your code → https://github.com/vercel/next.js/blob/cad5d36c6803e7ecf3c4e16b600c1178654bb999/examples/with-orbit-components/app/layout.tsx.

**Comment by PapatMayuri** [comment]
@samcx i have updated the PR please check

**Comment by PapatMayuri** [comment]
@samcx  I have removed the .babel.rc file.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
