### PR TITLE
Add "Vary: Accept" header to /_next/image responses

### PR DESCRIPTION
**Pull request by jviide**
This pull request adds "Vary: Accept" header to responses from the image optimizer (i.e. the /_next/image endpoint).

The image optimizer prefers re-encoding JPG files to WebP, but some browsers (such as Safari 14 on Catalina) do not yet support WebP. In such cases the optimizer uses the Accept header sent by the browser to send out a JPG response. Thus the optimizer's response may depend on the Accept header.

Potential caching proxies can be informed of this fact by adding "Vary: Accept" to the response headers. Otherwise WebP data may be served to browsers that do not support it, for example in the following scenario:
 * A browser that supports WebP requests the JPG. The optimizer re-encodes it to WebP. The proxy caches the WebP data.
 * After this another browser that doesn't support WebP requests the JPG. The proxy sends the WebP data to the browser.

- [x] Integration tests added
- [x] Make sure the linting passes

### CODE REVIEW

**Review by styfle — DISMISSED** [review]
Great work, thanks! 🎉

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.2s | ⚠️ +27ms |
| buildDurationCached | 3.4s | 3.4s | -34ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +112 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.594 | 2.592 | 0 |
| / avg req/sec | 963.76 | 964.33 | +0.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.615 | 1.675 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1547.77 | 1492.56 | ⚠️ -55.21 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 66.9 kB | 66.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +87ms |
| buildDurationCached | 5.2s | 4.9s | -283ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +112 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.604 | 2.618 | ⚠️ +0.01 |
| / avg req/sec | 959.99 | 954.96 | ⚠️ -5.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.657 | 1.619 | -0.04 |
| /error-in-render avg req/sec | 1508.31 | 1543.93 | +35.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.07 kB | 8.07 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.26 kB | 9.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| index.html gzip | 566 B | 566 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 559 B | 559 B | ✓ |
| Overall change | 1.7 kB | 1.7 kB | ✓ |

</details>

</details>
Commit: b62ee67247ada381f4b01e6f0cb97251974b3d9f

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b62ee67247ada381f4b01e6f0cb97251974b3d9f

**test/integration/image-optimizer/test/index.test.js** 
- Image Optimizer > Server support w/o next.config.js > should proxy-pass unsupported image types and should not cache file
- Image Optimizer > Server support with next.config.js > should proxy-pass unsupported image types and should not cache file
- Image Optimizer > dev support w/o next.config.js > should proxy-pass unsupported image types and should not cache file
- Image Optimizer > dev support with next.config.js > should proxy-pass unsupported image types and should not cache file

<details>
<summary>Expand output</summary>

  ● Image Optimizer › dev support w/o next.config.js › should proxy-pass unsupported image types and should not cache file

    expect(received).toBe(expected) // Object.is equality

    Expected: "Accept"
    Received: "Accept, Accept-Encoding"

      505 |       `public, max-age=${isDev ? 0 : 60}, must-revalidate`
      506 |     )
    > 507 |     expect(res.headers.get('Vary')).toBe('Accept')
          |                                     ^
      508 |     expect(res.headers.get('etag')).toBeTruthy()
      509 |
      510 |     const json2 = await fsToJson(imagesDir)

      at Object.<anonymous> (integration/image-optimizer/test/index.test.js:507:37)

  ● Image Optimizer › dev support with next.config.js › should proxy-pass unsupported image types and should not cache file

    expect(received).toBe(expected) // Object.is equality

    Expected: "Accept"
    Received: "Accept, Accept-Encoding"

      505 |       `public, max-age=${isDev ? 0 : 60}, must-revalidate`
      506 |     )
    > 507 |     expect(res.headers.get('Vary')).toBe('Accept')
          |                                     ^
      508 |     expect(res.headers.get('etag')).toBeTruthy()
      509 |
      510 |     const json2 = await fsToJson(imagesDir)

      at Object.<anonymous> (integration/image-optimizer/test/index.test.js:507:37)

  ● Image Optimizer › Server support w/o next.config.js › should proxy-pass unsupported image types and should not cache file

    expect(received).toBe(expected) // Object.is equality

    Expected: "Accept"
    Received: "Accept, Accept-Encoding"

      505 |       `public, max-age=${isDev ? 0 : 60}, must-revalidate`
      506 |     )
    > 507 |     expect(res.headers.get('Vary')).toBe('Accept')
          |                                     ^
      508 |     expect(res.headers.get('etag')).toBeTruthy()
      509 |
      510 |     const json2 = await fsToJson(imagesDir)

      at Object.<anonymous> (integration/image-optimizer/test/index.test.js:507:37)

  ● Image Optimizer › Server support with next.config.js › should proxy-pass unsupported image types and should not cache file

    expect(received).toBe(expected) // Object.is equality

    Expected: "Accept"
    Received: "Accept, Accept-Encoding"

      505 |       `public, max-age=${isDev ? 0 : 60}, must-revalidate`
      506 |     )
    > 507 |     expect(res.headers.get('Vary')).toBe('Accept')
          |                                     ^
      508 |     expect(res.headers.get('etag')).toBeTruthy()
      509 |
      510 |     const json2 = await fsToJson(imagesDir)

      at Object.<anonymous> (integration/image-optimizer/test/index.test.js:507:37)
          at runMicrotasks (<anonymous>)

</details>

**Comment by styfle** [comment]
```
Expected: "Accept"
Received: "Accept, Accept-Encoding"

  at Object.<anonymous> (integration/image-optimizer/test/index.test.js:507:37)
```

Looks like the `Vary` header is adding `Accept-Encoding`, probably from the compression middleware. Although it doesn't look like its actually compressing the response so we can probably remove that part of `Vary`.

**Comment by jviide** [comment]
If I'm reading the compression middleware code correctly it seems that the middleware adds Accept-Encoding to the Vary header for all compressible MIME types. This happens even for files that are smaller than the compression size threshold.

Should I modify the failing test to accept Vary headers that also contain Accept-Encoding headers? The ["should maintain vector svg"](https://github.com/vercel/next.js/pull/26788/files#diff-1890717f6402a731fae651e8b3de439ee96a06aae4b28db9612b4960f0d41fa0R101) test already does that.

**Comment by styfle** [comment]
> Should I modify the failing test to accept Vary headers that also contain Accept-Encoding

Yep let's update the "should proxy-pass unsupported" test to use the same regex, thanks!

**Review by styfle — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.4s | ⚠️ +177ms |
| buildDurationCached | 2.7s | 2.8s | ⚠️ +46ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +112 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.011 | 2.07 | ⚠️ +0.06 |
| / avg req/sec | 1243.31 | 1207.52 | ⚠️ -35.79 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.103 | 1.142 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2265.53 | 2188.62 | ⚠️ -76.91 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| 359.HASH.js gzip | 3.09 kB | 3.09 kB | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 66.9 kB | 66.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.18 kB | 3.18 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.3s | -64ms |
| buildDurationCached | 4.1s | 4s | -79ms |
| nodeModulesSize | 49.3 MB | 49.3 MB | ⚠️ +112 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.129 | 2.131 | 0 |
| / avg req/sec | 1174.24 | 1173.21 | ⚠️ -1.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.155 | 1.214 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 2163.63 | 2059.85 | ⚠️ -103.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| 14.HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 8.07 kB | 8.07 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.26 kB | 9.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| _buildManifest.js gzip | 418 B | 418 B | ✓ |
| Overall change | 418 B | 418 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jviide/next.js vary-accept | Change |
| - | - | - | - |
| index.html gzip | 566 B | 566 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 559 B | 559 B | ✓ |
| Overall change | 1.7 kB | 1.7 kB | ✓ |

</details>

</details>
Commit: 4a2e62ffd8bd18fac67e385781758ff3baff983d

**Comment by styfle** [comment]
This fix is available in [next@11.0.2-canary.4](https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.4), thanks!

**Comment by jviide** [comment]
Awesome, thank you! 🙂

**Pull request merged**
