### PR TITLE
[Beta] Switch from Fly to Taskr

### PR DESCRIPTION
**Pull request by lukeed**
To go along with #2306 🙇 and save you guys the trouble of a rebase/merge commit.

/cc @rauchg @timneutkens

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
@arunoda you can merge 👌

**Comment by lukeed** [comment]
Do you guys need anything from me for these?

Looks like an unlucky merge happened, but isn't to do with the Taskr setup itself.

**Review by timneutkens — APPROVED** [review]

**Comment by lukeed** [comment]
Thanks 😃

**Comment by timneutkens** [comment]
👍

**Pull request merged**
