### PR TITLE
A11y: Set focus back to body after link was clicked 

### PR DESCRIPTION
**Pull request by connor-baer**
Solves #2768.

When navigating from one page to another using `next/link`, set the focus on the `<body>` on the new page as the document root. This reflects the behavior when navigating with a normal `<a>` link.

### CODE REVIEW

**Comment by connor-baer** [comment]
@timneutkens @sergiodxa, would you mind reviewing this this PR, please? 🙂

**Review by timneutkens — APPROVED** [review]
Looks alright 👍 Sorry it took a while, we're working on shipping v5 which involves a lot of internal changes to Next.js. We also always thoroughly review pull requests by running them ourselves and adding tests for them 👍

**Comment by timneutkens** [comment]
Thanks for your contribution 🙏

**Comment by connor-baer** [comment]
Thank you @timneutkens! 😊 

I applaud your thoroughness. 👏

**Pull request merged**
