### PR TITLE
remove `content-encoding` from fetch res headers

### PR DESCRIPTION
**Pull request by smaeda-ks**
for internal: https://vercel.slack.com/archives/C0289CGVAR2/p1688570010400989

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d71dc959f5295d48c88a8886cb9d611600ab682a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d71dc959f5295d48c88a8886cb9d611600ab682a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by timneutkens — CHANGES_REQUESTED** [review]
Could you add a test for this change? Thanks!

**Comment by smaeda-ks** [comment]
@timneutkens Added test.

I also made some changes in next-server in this commit: https://github.com/vercel/next.js/pull/52346/commits/882debc108099f8d81b4abe9bb7660f911223304
This is to address another issue so we can test that in `next dev` instead of production: https://github.com/vercel/next.js/issues/49081

As far as I checked, it's caused by this line of code:
https://github.com/vercel/next.js/blob/6527d29c8a1b5f7f497107bb39a46025e4459318/packages/next/src/server/next-server.ts#L1513

I don't think we need to remove `content-encoding` res header in there (i.e., the use of `filterReqHeaders` for "res" headers).

**Pull request closed without merging**
