### PR TITLE
provide revalidateReason to getStaticProps

### PR DESCRIPTION
**Pull request by ztanner**
Provides a `revalidateReason` argument to `getStaticProps` ("stale" | "on-demand" | "build").

- Build indicates it was run at build time
- On-demand indicates it was run as a side effect of [on-demand revalidation](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#on-demand-revalidation)
- Stale indicates the resource was considered stale (either due to being in dev mode, or an expired revalidate period)

This will allow changing behavior based on the context in which it's called.

Closes NEXT-1900

### CODE REVIEW

**Comment by ztanner** [comment]
* **#64258** <a href="https://app.graphite.dev/github/pr/vercel/next.js/64258?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b57931e92f8b2f3766925e6802d4975939cb52cf

`TURBOPACK=1 pnpm test-start test/e2e/revalidate-reason/revalidate-reason.test.ts` (turbopack)
- revalidate-reason > should support revalidateReason: "stale"

<details>
<summary>Expand output</summary>

  ● revalidate-reason › should support revalidateReason: "stale"

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "revalidate-reason/pages/stale.tsx revalidateReason: stale"
    Received string:        "  ▲ Next.js 14.2.0-canary.63 (turbo)

       Linting and checking validity of types ...

       We detected TypeScript in your project and created a tsconfig.json file for you.
       Creating an optimized production build ...
       Building (0/4) ...
       Building (1/4) 
       Building (2/4) 
       Building (3/4) 
     ✓ Building (4/4)
       Collecting page data ...
       Generating static pages (0/4) ...
    revalidate-reason/pages/stale.tsx revalidateReason: build
    revalidate-reason/pages/index.tsx revalidateReason: build
       Generating static pages (1/4) 
       Generating static pages (2/4) 
       Generating static pages (3/4) 
     ✓ Generating static pages (4/4)
       Finalizing page optimization ...
       Collecting build traces ...

    Route (pages)                                 Size     First Load JS
    ┌ ● /                                         10.4 kB         240 kB
    ├ ○ /404                                      96 kB           240 kB
    ├ ƒ /api/revalidate                           0 B             144 kB
    └ ● /stale (ISR: 5 Seconds)                   10.5 kB         240 kB
    + First Load JS shared by all                 144 kB
      ├ chunks/4e99c_react-dom_58158d._.js        41.8 kB
      ├ chunks/[root of the server]__9cb058._.js  86.6 kB
      └ other shared chunks (total)               15.1 kB

    ○  (Static)   prerendered as static content
    ●  (SSG)      prerendered as static HTML (uses getStaticProps)
       (ISR)      incremental static regeneration (uses revalidate in getStaticProps)
    ƒ  (Dynamic)  server-rendered on demand

      ▲ Next.js 14.2.0-canary.63 (turbo)
      - Local:        http://localhost:35299

     ✓ Starting...
     ✓ Ready in 353ms
    revalidate-reason/pages/index.tsx revalidateReason: on-demand
    revalidate-reason/pages/stale.tsx revalidateReason: stale
    "

      49 |     expect(res.status).toBe(200)
      50 |
    > 51 |     expect(next.cliOutput).not.toContain(
         |                                ^
      52 |       'revalidate-reason/pages/stale.tsx revalidateReason: stale'
      53 |     )
      54 |

      at Object.toContain (e2e/revalidate-reason/revalidate-reason.test.ts:51:32)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| buildDuration | 14s | 14s | N/A |
| buildDurationCached | 8.4s | 6.4s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +2.68 kB |
| nextStartRea..uration (ms) | 408ms | 412ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.05 kB | 5.05 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 241 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.22 kB | 4.22 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 2.36 kB | 2.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 542 B | 541 B | N/A |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 529 B | 529 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97.3 kB | 97.3 kB | ✓ |
| app-page-tur..prod.js gzip | 99.1 kB | 99.1 kB | ✓ |
| app-page-tur..prod.js gzip | 93.3 kB | 93.3 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.8 kB | 91.8 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | N/A |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | N/A |
| pages.runtim..prod.js gzip | 22.4 kB | 22.5 kB | N/A |
| server.runti..prod.js gzip | 51.1 kB | 51.1 kB | ✓ |
| Overall change | 879 kB | 879 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 04-09-provide_revalidateReason_to_getStaticProps | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | ⚠️ +1.45 kB |
| index.pack gzip | 106 kB | 107 kB | N/A |
| Overall change | 1.58 MB | 1.58 MB | ⚠️ +1.45 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b57931e92f8b2f3766925e6802d4975939cb52cf

**Review by ijjk — APPROVED** [review]
Thanks!

**Pull request merged**
