### PR TITLE
Prepare for easier shadcn ui install

### PR DESCRIPTION
**Pull request by saltcod**
### What?
Installing shadcn/ui after installing this example was a bad experience. 
Running `npx shadcn-ui@latest init` overwrites existing files causing errors and a confusing start.
 
This allows a installing shadcn/ui without these issues.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c240fe599020205454836613274575eb7c596089

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@saltcod Can you clarify why changing styles would prevent `shadcn-ui` from overriding (not completely familiar with shadcn-ui myself)?

**Comment by saltcod** [comment]
I missed this comment @samcx sorry!
When you install shadcn/ui, it comes with its own globals.css file and overwrites the existing one. 
Currently, the site looks broken while that happens.

This PR just makes sure that things still look not-broken if you install shadcn/ui and have your globals.css file overwritten.

No underlying changes.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
