### PR TITLE
updated with-styletron example to utilize the app router.

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-styletron  example for using the App Router.
Here are the changes that have been made:

- I renamed the `pages` folder and moved it to the `app` folder.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1fd9f743ff2b13f0a99443b93c02c0636764c7b9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1fd9f743ff2b13f0a99443b93c02c0636764c7b9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by samcx** [comment]
@PapatMayuri No need to merge the latest canary—the last commit needs to be done somebody on the team so it can pass CI.

**Pull request merged**
