### PR TITLE
[Bug?] componentDidMount does not execute on client on nested pages

### PR DESCRIPTION
**Pull request by tvararu**
I have a feeling this is a known behaviour / limitation. Please close this PR if that's the case.

Adding `componentDidMount` on a nested `index.js` page will not be executed on the client. I thought a PR with a failing test is a better demo than an issue.

Happy to clean this and go spelunking for a solution if this is a real bug. :+1:

```bash
$ yarn test
# snip
 FAIL  test/integration/basic/test/index.test.js (62.625s)
  ● Basic Features › componentDidMount › on nested-cdm/index.js page

    expect(received).toBe(expected)

    Expected value to be (using ===):
      "ComponentDidMount executed on client."
    Received:
      "ComponentDidMount not executed."
# snip
    componentDidMount
      ✓ on normal page (1482ms)
      ✕ on nested-cdm/index.js page (1702ms)
```

### CODE REVIEW

**Comment by arunoda** [comment]
This is pretty weird. Let me check.

**Comment by arunoda** [comment]
Here you need to use `/nested-cdm` instead `/nested-cdm/index`

**Comment by arunoda** [comment]
Closing in favor of https://github.com/zeit/next.js/pull/1844
Thanks @tvararu for the investigation.

**Comment by tvararu** [comment]
@arunoda thanks for giving this a look! I've added more tests, and indeed as you point out the `/nested-cdm` page does execute `componentDidMount`:

```bash
  Basic Features
    componentDidMount
      ✓ on normal page (1788ms)
      ✓ on /nested-cdm page (1520ms)
      ✕ on /nested-cdm/ page (1527ms)
      ✕ on /nested-cdm/index page (1588ms)
```

I assume `/nested-cdm/` and `/nested-cdm/index` are the one and the same, however, it doesn't explain why `componentDidMount` is not triggered on either of them, while it is on `/nested-cdm`. Is this a bug?

Edit: just saw you opened a separate PR, thanks! 👍

**Pull request closed without merging**
