### PR TITLE
Add property to list of deduped tags

### LINKED ISSUE #2438: Open graph meta tags duplication in <head />
Right now [facebook Open Graph meta tags](https://developers.facebook.com/docs/sharing/webmasters#markup) gets duplicated in head if several next `<Head />` components used in one page.
```html
<head>
  <meta property="og:title" content="Default Page Title" />
  <meta property="og:title" content="Current Page Title" />
</head>
```
This happens because `property` prop doesn't considered in head [`METATYPE`s](https://github.com/zeit/next.js/blob/v3-beta/lib/head.js#L45).
It should be super easy to fix.

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #2438

### CODE REVIEW

**Review by arunoda — COMMENTED** [review]
Thanks.

**Comment by paulobarcelos** [comment]
But this blocks the possibility of having duplicated tags when that is the desired behaviour...
For example you are allowed to have multiple og:image tags (https://developers.facebook.com/docs/sharing/opengraph/object-properties), but right now I can't do that as they will removed...

Is there a possibility of adding some sort of prop that would escape the dedupe process?

**Comment by ilionic** [comment]
Can you please revert it or make exception for `og:image` ? It's common practise to use multiple `og:image`

**Comment by gbiryukov** [comment]
so looks like some `<meta property="..." />` should be unique and other can be included multiple times. 

Reverting this PR will not help a lot because page may have 2 default `og:image` and 2 custom, defined in some page component.
So user will see 4 images in facebook share dialog but only 2 custom images expected.

Looks like such tags should have some sort of `key`-s like React uses on components to define unique tags. Solution with predefined keys-like attributes ([METATYPES](https://github.com/zeit/next.js/pull/2439/commits/a9666d7ee4875f8d28c1d2ef7420e1166b0b12a0#diff-c989d849ae82663d1426e049e2f5cb57R45)) doesn't work well in such cases

**Comment by vuldin** [comment]
A solution would be to pass the meta tags into the layout.js as a prop, and then ensure it is set to a default value that works for any page that doesn't send the props. So:
```javascript
render() {
  const { meta = [
    {name: 'description', content: 'some short description'},
    {property: 'og:image', content: 'https://link/to/first/img.png'},
    {property: 'og:image', content: 'https://link/to/second/img.png'},
  ] } = this.props
  const metas = meta.map((m, i) => {
    m.key = i
    return React.createElement('meta', m, null)
  })
  return <div>
    <Head>
      {metas}
    </Head>
  </div>
}
```
Reverting this PR would solve the issue by allowing the developer to determine what meta tags appear on which page. Then we can ensure we don't send duplicate meta tags in our code.

With this PR, it makes it impossible to send multiple tags with a specific property.

**Comment by gbiryukov** [comment]
nextjs `<Head />` component doesn't limited to single usage in page components tree. So when someone will use it multiple times it will cause duplication regardless of defaults

**Comment by Irrelon** [comment]
Do you know if this will be reverted or fixed in an upcoming release? Right now it is not possible to use multiple og:image meta tags which is fairly bad!

**Pull request merged**
