### PR TITLE
updated the example of api-routes to utilize the App Router

### PR DESCRIPTION
**Pull request by Sam-Phillemon9493**
This PR updates the api-routes example to use the App Router. Here are the changes that have been made:

- Renamed the "pages" folder to the "app" folder.
- Updated the routing for /, &  /person/[id] files to align with the App Router.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1c57c434b72699a22592e353b875a518457a86bc

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Sam-Phillemon9493 Let's rename `examples/api-routes` to `examples/route-handlers`, since technically we call this [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers).

**Comment by Sam-Phillemon9493** [comment]
> @Sam-Phillemon9493 Let's rename `examples/api-routes` to `examples/route-handlers`, since technically we call this [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) with App Router.

@samcx renamed the example.

**Review by samcx — APPROVED** [review]

**Comment by samcx** [comment]
@Sam-Phillemon9493 Make sure to always work with the latest canary, or you may run into issues. Specifically, this change → https://github.com/vercel/next.js/pull/68534 caused this to have a merge conflict.

**Comment by Sam-Phillemon9493** [comment]
> @Sam-Phillemon9493 Make sure to always work with the latest canary, or you may run into issues. Specifically, this change → #68534 caused this to have a merge conflict.

Thank You, @samcx. Got it, I’ll use the latest canary to avoid issues. Thanks for pointing out the conflict with #68534!

**Pull request merged**
