### PR TITLE
upgrade next-transpile-modules to latest everywhere

### PR DESCRIPTION
**Pull request by vvo**
Following #10492 and comment from @timneutkens I went ahead and updated all
examples relying on next-transpile-modules.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| buildDuration | 9.1s | 9.2s | ⚠️ +92ms |
| nodeModulesSize | 54.5 MB | 54.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9ee3.js gzip | 12.2 kB | 12.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.14 kB | 4.14 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 9.2 kB | 9.2 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 20.3 kB | 20.3 kB | ✓ |
| Overall change | 20.3 kB | 20.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.js gzip | 1.06 kB | 1.06 kB | ✓ |
| _error.js gzip | 2.98 kB | 2.98 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.module.js gzip | 577 B | 577 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| index.html gzip | 925 B | 925 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| buildDuration | 10s | 9.9s | -76ms |
| nodeModulesSize | 54.5 MB | 54.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9ee3.js gzip | 12.2 kB | 12.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.14 kB | 4.14 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 9.2 kB | 9.2 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 20.3 kB | 20.3 kB | ✓ |
| Overall change | 20.3 kB | 20.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.js gzip | 1.06 kB | 1.06 kB | ✓ |
| _error.js gzip | 2.98 kB | 2.98 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.module.js gzip | 577 B | 577 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _error.js gzip | 290 kB | 289 kB | -489 B |
| 404.html gzip | 1.33 kB | 1.33 kB | ✓ |
| hooks.html gzip | 964 B | 964 B | ✓ |
| index.js gzip | 290 kB | 289 kB | -686 B |
| link.js gzip | 297 kB | 298 kB | ⚠️ +786 B |
| routerDirect.js gzip | 297 kB | 296 kB | -707 B |
| withRouter.js gzip | 296 kB | 298 kB | ⚠️ +1.51 kB |
| Overall change | 1.47 MB | 1.47 MB | ⚠️ +416 B |

</details>

</details>


Commit: 5c2a97fa2e50a4c58285d356382df19bc81aca08

**Comment by timneutkens** [comment]
```
yarn run v1.21.1
$ run-p lint-typescript prettier-check lint-eslint
$ eslint . --ext js,jsx,ts,tsx --max-warnings=0
$ lerna run typescript
$ prettier --check "**/*.{js,jsx,json,ts,tsx,md,mdx,css,html,yml,yaml,scss}"
Checking formatting...
lerna notice cli v3.14.1
lerna info Executing command in 1 package: "yarn run typescript"
errors/invalid-getstaticpaths-value.md
lerna info run Ran npm script 'typescript' in 'next' in 27.4s:
lerna success run Ran npm script 'typescript' in 1 package in 27.4s:
lerna success - next
$ tsc --noEmit --declaration
Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "prettier-check" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

Looks like the pre-commit hook didn't run 🤔

**Comment by vvo** [comment]
@timneutkens I dunno what's wrong actually, this is what I get when I run `yarn lint` on the PR locally:

```
> yarn lint
yarn run v1.22.0
$ run-p lint-typescript prettier-check lint-eslint
$ prettier --check "**/*.{js,jsx,json,ts,tsx,md,mdx,css,html,yml,yaml,scss}"
$ lerna run typescript
$ eslint . --ext js,jsx,ts,tsx --max-warnings=0
Checking formatting...
lerna notice cli v3.14.1
lerna info Executing command in 1 package: "yarn run typescript"
errors/invalid-getstaticpaths-value.md
examples/form-handler/components/Social.jslerna ERR! yarn run typescript exited 1 in 'next'
lerna ERR! yarn run typescript stdout:
$ tsc --noEmit --declaration
next-server/server/api-utils.ts(305,65): error TS2307: Cannot find module 'jsonwebtoken'.
next-server/server/api-utils.ts(363,65): error TS2307: Cannot find module 'jsonwebtoken'.
types/index.d.ts(12,3): error TS2305: Module '"../../../../../../../Users/vvo/Dev/next.js/packages/next/dist/next-server/lib/utils"' has no exported member 'NextApiHandler'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run typescript stderr:
error Command failed with exit code 1.

lerna ERR! yarn run typescript exited 1 in 'next'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
examples/form-handler/handlers/Input.jsERROR: "lint-typescript" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

1. I wonder why we're linting the dist build?
2. there's no change to next-server/server/api-utils.ts in this PR
3. the current canary build has the same linting error it seems, see https://github.com/zeit/next.js/commit/db445db790a9a7038025a6847fc61cde9e977610 and its build: https://github.com/zeit/next.js/runs/457307215

Let me know if I need to change something still!

**Comment by vvo** [comment]
Just updated the PR with latest canary changes, I guess this should pass now

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| buildDuration | 9s | 10.8s | ⚠️ +1.8s |
| nodeModulesSize | 54.5 MB | 54.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9ee3.js gzip | 12.2 kB | 12.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.14 kB | 4.14 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 9.2 kB | 9.2 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 20.3 kB | 20.3 kB | ✓ |
| Overall change | 20.3 kB | 20.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.js gzip | 1.06 kB | 1.06 kB | ✓ |
| _error.js gzip | 2.98 kB | 2.98 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.module.js gzip | 577 B | 577 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| index.html gzip | 925 B | 925 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.3s | -286ms |
| nodeModulesSize | 54.5 MB | 54.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9ee3.js gzip | 12.2 kB | 12.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.14 kB | 4.14 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 9.2 kB | 9.2 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 53.2 kB | 53.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 20.3 kB | 20.3 kB | ✓ |
| Overall change | 20.3 kB | 20.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.js gzip | 1.06 kB | 1.06 kB | ✓ |
| _error.js gzip | 2.98 kB | 2.98 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _app.module.js gzip | 577 B | 577 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | vvo/next.js upgrade-next-transpile-modules-to-3.0.2-everywhere | Change |
| - | - | - | - |
| _error.js gzip | 290 kB | 289 kB | -742 B |
| 404.html gzip | 1.33 kB | 1.33 kB | ✓ |
| hooks.html gzip | 964 B | 964 B | ✓ |
| index.js gzip | 290 kB | 290 kB | ⚠️ +180 B |
| link.js gzip | 298 kB | 297 kB | -611 B |
| routerDirect.js gzip | 296 kB | 298 kB | ⚠️ +1.73 kB |
| withRouter.js gzip | 296 kB | 298 kB | ⚠️ +1.38 kB |
| Overall change | 1.47 MB | 1.47 MB | ⚠️ +1.94 kB |

</details>

</details>


Commit: 7007fdd5a4db5a5696b9354b50aaf4d28deb50c4

**Comment by timneutkens** [comment]
Thanks @vvo! This was my fault as explained on the commit message 🙈

**Pull request merged**
