### PR TITLE
add babel-macros example

### PR DESCRIPTION
**Pull request by kentcdodds**
screen shot 2017-07-14 at 12 09 29 pm

:smile:

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
This is so cool 😲 👍 💯 💯 💯

**Comment by cncolder** [comment]
Is this example resolve any problem? Integrate `babel-macros` into `next.js` is zero config.

Yes cool idea. Example not cool.

**Comment by arunoda** [comment]
@cncolder example doesn't need to solve any real problem. It just need to show the capabilities and how to use it.

Since this demonstrates, how to access the underline OS specific information while the app is building. And it can be exposed as a constant and used in the app.

**Comment by cncolder** [comment]
Thank you for your fast answer. I understand this. But it's not ability of `next.js`. I think examples/with-custom-babel-config has cover all babel usage.

I think user explore examples folder for find how to config `next.js` or best practice.

**Pull request merged**
