### PR TITLE
Move swcMinify out of experimental

### PR DESCRIPTION
**Pull request by timneutkens**
- Move `swcMinify` to the top level of `next.config.js`
- Added test for `swcMinify` enabled
- Remove `swcLoader` option as it's stable now, apps with `.babelrc` opt-out automatically

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 729f2f07b5cfe33160438e236561262abbb78c32

**test/production/required-server-files.test.ts** 
- should set-up next > should bubble error correctly for gip page
- should set-up next > should bubble error correctly for gssp page

<details>
<summary>Expand output</summary>

  ● should set-up next › should bubble error correctly for gip page

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      580 |     const res = await fetchViaHTTP(appPort, '/api/error')
      581 |     expect(res.status).toBe(500)
    > 582 |     expect(await res.text()).toBe('error')
          |                          ^
      583 |     expect(errors.length).toBe(1)
      584 |     expect(errors[0]).toContain('some error from /api/error')
      585 |   })

      at Object.<anonymous> (production/required-server-files.test.ts:582:26)

  ● should set-up next › should bubble error correctly for gssp page

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      592 |       {
      593 |         headers: {
    > 594 |           'x-matched-path': '/optional-ssp/[[...rest]]',
          |           ^
      595 |         },
      596 |       }
      597 |     )

      at Object.<anonymous> (production/required-server-files.test.ts:594:11)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| buildDuration | 14.9s | 11.6s | -3.3s |
| buildDurationCached | 3.5s | 3.6s | ⚠️ +116ms |
| nodeModulesSize | 200 MB | 200 MB | -2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.378 | 3.451 | ⚠️ +0.07 |
| / avg req/sec | 739.97 | 724.4 | ⚠️ -15.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.578 | 1.636 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1584.63 | 1528.02 | ⚠️ -56.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 50.7 kB | ⚠️ +8.5 kB |
| main-HASH.js gzip | 27 kB | 34.3 kB | ⚠️ +7.26 kB |
| webpack-HASH.js gzip | 1.45 kB | 1.57 kB | ⚠️ +120 B |
| Overall change | 70.9 kB | 86.7 kB | ⚠️ +15.9 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 1.04 kB | ⚠️ +63 B |
| _error-HASH.js gzip | 194 B | 180 B | -14 B |
| amp-HASH.js gzip | 311 B | 313 B | ⚠️ +2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.67 kB | 3.06 kB | ⚠️ +394 B |
| head-HASH.js gzip | 351 B | 356 B | ⚠️ +5 B |
| hooks-HASH.js gzip | 918 B | 937 B | ⚠️ +19 B |
| image-HASH.js gzip | 4.14 kB | 4.63 kB | ⚠️ +490 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.84 kB | ⚠️ +181 B |
| routerDirect..HASH.js gzip | 320 B | 324 B | ⚠️ +4 B |
| script-HASH.js gzip | 386 B | 392 B | ⚠️ +6 B |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 14.1 kB | ⚠️ +1.15 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _buildManifest.js gzip | 493 B | 491 B | -2 B |
| Overall change | 493 B | 491 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 553 B | ⚠️ +2 B |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.63 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| buildDuration | 7.6s | 7.4s | -173ms |
| buildDurationCached | 3.5s | 3.5s | ⚠️ +23ms |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.39 | 3.308 | -0.08 |
| / avg req/sec | 737.44 | 755.81 | +18.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.556 | 1.638 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1606.5 | 1526.61 | ⚠️ -79.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 35 kB | 35 kB | ✓ |
| webpack-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| Overall change | 101 kB | 101 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-HASH.js gzip | 355 B | 355 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 555 B | 555 B | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 531 B | 531 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: 729f2f07b5cfe33160438e236561262abbb78c32

**Review by styfle — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c21e912d3fcb72c0faa4f98873fab94636720fa7

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:425:9)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    TIMED OUT: /Hello/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:489:17)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| buildDuration | 14.1s | 11.2s | -2.9s |
| buildDurationCached | 3.3s | 3.4s | ⚠️ +130ms |
| nodeModulesSize | 194 MB | 194 MB | -8 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.142 | 3.26 | ⚠️ +0.12 |
| / avg req/sec | 795.74 | 766.91 | ⚠️ -28.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.45 | 1.514 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1724.35 | 1650.82 | ⚠️ -73.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 3.56 kB | ⚠️ +539 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 50.8 kB | ⚠️ +8.53 kB |
| main-HASH.js gzip | 25 kB | 31.4 kB | ⚠️ +6.47 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.61 kB | ⚠️ +123 B |
| Overall change | 71.9 kB | 87.5 kB | ⚠️ +15.7 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 1.04 kB | ⚠️ +63 B |
| _error-HASH.js gzip | 3.11 kB | 3.65 kB | ⚠️ +542 B |
| amp-HASH.js gzip | 553 B | 578 B | ⚠️ +25 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 3.14 kB | ⚠️ +415 B |
| head-HASH.js gzip | 2.37 kB | 2.8 kB | ⚠️ +430 B |
| hooks-HASH.js gzip | 918 B | 937 B | ⚠️ +19 B |
| image-HASH.js gzip | 5.86 kB | 6.93 kB | ⚠️ +1.07 kB |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.84 kB | ⚠️ +181 B |
| routerDirect..HASH.js gzip | 320 B | 324 B | ⚠️ +4 B |
| script-HASH.js gzip | 386 B | 392 B | ⚠️ +6 B |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 22.7 kB | ⚠️ +2.75 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _buildManifest.js gzip | 490 B | 490 B | ✓ |
| Overall change | 490 B | 490 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| index.html gzip | 539 B | 536 B | -3 B |
| link.html gzip | 551 B | 549 B | -2 B |
| withRouter.html gzip | 533 B | 531 B | -2 B |
| Overall change | 1.62 kB | 1.62 kB | -7 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| buildDuration | 7.3s | 7.1s | -179ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +1ms |
| nodeModulesSize | 194 MB | 194 MB | -8 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.247 | 3.221 | -0.03 |
| / avg req/sec | 769.89 | 776.19 | +6.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.555 | 1.436 | -0.12 |
| /error-in-render avg req/sec | 1608.1 | 1741.18 | +133.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-HASH.js gzip | 35.2 kB | 35.2 kB | ✓ |
| webpack-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| Overall change | 102 kB | 102 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-HASH.js gzip | 355 B | 355 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 555 B | 555 B | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| _buildManifest.js gzip | 510 B | 510 B | ✓ |
| Overall change | 510 B | 510 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcminify | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 531 B | 531 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: c21e912d3fcb72c0faa4f98873fab94636720fa7

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 762b11ffc80c89fc1106b8b65dfc46c8b77c10fb

**test/integration/pnpm-support/test/index.test.js** 
- pnpm support > should build with dependencies installed via pnpm

<details>
<summary>Expand output</summary>

  ● pnpm support › should build with dependencies installed via pnpm

    Command failed with exit code 1 (EPERM): /home/runner/work/next.js/next.js/node_modules/.bin/pnpm run build

      21 | const runPnpm = async (cwd, ...args) => {
      22 |   try {
    > 23 |     await execa(pnpmExecutable, [...args], { cwd })
         |     ^
      24 |   } catch (err) {
      25 |     console.log({ stdout: err.stdout, stderr: err.stderr })
      26 |     throw err

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
          at runMicrotasks (<anonymous>)
      at runPnpm (integration/pnpm-support/test/index.test.js:23:5)
      at integration/pnpm-support/test/index.test.js:139:34
      at usingTempDir (integration/pnpm-support/test/index.test.js:34:12)
      at Object.<anonymous> (integration/pnpm-support/test/index.test.js:96:5)

</details>

**Pull request merged**
