### PR TITLE
More elegant application of antd

### PR DESCRIPTION
**Pull request by starriv**

### CODE REVIEW

**Comment by ernestofreyreg** [comment]
Ant Design is really nice, a very comprehensible collections of components, styles, grids, etc. 

The only problem I am seeing is the big >400Kb of css styling the example is downloading from a CDN. 

There should be a way to only include in the CSS those styles we need.  They recommend using `babel-plugin-import`

**Review by timneutkens — APPROVED** [review]
👍

**Comment by ernestofreyreg** [comment]
This demo is failing due to `transform-decorators-legacy` is not found.

**Comment by BafS** [comment]
Me too, for the moment I just import the CSS as a string and add it to the JSX.

```js
import antdStyles from 'antd/lib/style/index.css';
import datePickerStyle from 'antd/lib/date-picker/style/index.css';

// ...

<style jsx global>{`
    ${antdStyles}  
    ${datePickerStyle}
    ...
`}</style>
```

**Comment by 1kohei1** [comment]
This is how I ended up loading css module per components and deploy to now. I hope this helps someone. [Load ant.design css by module in Next app](https://medium.com/@koheiarai94/load-ant-design-css-by-module-in-next-app-21c8c2c8c248)

**Pull request merged**
