### PR TITLE
docs: add Logto authentication guide link

### PR DESCRIPTION
**Pull request by wangsijie**
### What?

Add links of Logto's guide to "Authentication" page.

Logto is an Auth0 alternative designed for modern apps and SaaS products, and it has Next.js SDKs and guides for both app router and pages router.

### CODE REVIEW

**Review by devjiwonchoi — APPROVED** [review]

**Comment by devjiwonchoi** [comment]
Is there a reason why one is `https://docs.logto.io/sdk/next` and the other `https://docs.logto.io/sdk/next-app-router`?

**Comment by wangsijie** [comment]
@devjiwonchoi For app router and pages router.

**Comment by devjiwonchoi** [comment]
Yeah, but they display on Pages and App altogether, I propose to choose either one or use the `AppOnly` tag for consistency.

**Comment by samcx** [comment]
@wangsijie Thank you for the <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

Let's wait on adding this option until we it gains more traction! We can re-open a new <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture> once it gains more traction.

**Comment by wangsijie** [comment]
@samcx Can you be a little more specific about the traction? We have quite a few users who are using Logto with Next.js/Vercel. If you can point out some actionable items, that would be helpful!

**Comment by samcx** [comment]
@wangsijie We don't have rigid guidelines, but in general, the a new option should be comparable in downloads per week to the rest that are shown on that list (https://www.npmjs.com/package/@logto/next).

**Pull request closed without merging**
