### PR TITLE
updated documentation to add more deployments

### PR DESCRIPTION
**Pull request by danaiszuul**
I have updated the docs to add more ways to deploy Next.js.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by danaiszuul — COMMENTED** [review]
cleaned up my markdown, had a couple of ugly links

**Comment by leerob** [comment]
Hey! Thanks for the suggestion. I’m going to be overhauling the deployment docs soon and will reference this.

**Comment by danaiszuul** [comment]
> Hey! Thanks for the suggestion. I’m going to be overhauling the deployment docs soon and will reference this.

@leerob thanks for the update! So this work doesn't get lost (it took a hot min to write all this up) is there a WIP PR for this docs overhaul that I or others out there could help contribute to? I want to earn my git commit! Also would be cool if @jhuleatt or some peep at Firebase could confirm the instructions I whipped up.

**Comment by leerob** [comment]
No ETA at the moment but will keep you posted!

**Comment by philhawksworth** [comment]
Curious if there are any updates on this from the last couple of months, @leerob? 

If it helps, I'm also happy to volunteer to garden this PR a little if it has now become a little divergent from the main branch. Just say the word :)

**Comment by philhawksworth** [comment]
Just checking in again to see if I can help with this PR to the Next.js docs. 

@leerob mentioned back in February that a docs overhaul was shipping soon and I wanted to make sure that this contribution lands in the right place and doesn't get lost along the way. Is that work still in progress and if so is there are different branch or PR I should work in to instead?

Happy to follow up @danaiszuul 's work and to reach out for fresh input from the various deployment targets if that helps this land with the updated latest info after all the great developments in Next.js.

Just say the word.

**Comment by leerob** [comment]
Apologies for the slow response here :pray:  [Finally got a PR up](https://github.com/vercel/next.js/pull/37571) as mentioned in my previous comment.

It replaces this PR and includes Netlify, Firebase, as well as 11 other options. Thanks for your help :smile:

**Pull request closed without merging**
