### PR TITLE
[Docs][Fix] Broken Link to API Reference

### PR DESCRIPTION
**Pull request by imabp**
## Documentation / Examples
- [x] Make sure the linting passes by running `yarn lint`

## Steps to Reproduce

1. Go to https://nextjs.org/docs/advanced-features/debugging#debugging-with-vs-code

2. Click on the link as shown in red underlined in below image.
image

3. Ending up with the **404 Error** screen
image

## Fixing Steps

Replace the broken link with correct one.

### CODE REVIEW

**Comment by imabp** [comment]
Hey @leerob you inspired me during your sessions at NextJS Conference.. This is my first contribution to NextJS, and I am trying to understand the codebase. Also, this makes an entry point for me. :)

**Review by timneutkens — APPROVED** [review]
Great catch 👍

**Comment by imabp** [comment]
Hey @timneutkens , I want to be part of contributors list 🥺... If there is anything like that, please do add me :)

**Comment by leerob** [comment]
@imabp Thank you for your contribution! When we cut the next stable release, you will be shown in the contributors list 😁

**Comment by imabp** [comment]
Thank you @leerob . I was looking for more ways to contribute to the core part, or at least getting started. If there are any pointers or resources that can help me to contribute. Please do share here 😄. Also we are connected on twitter: https://twitter.com/imabptweets .. Really like what you do and showcase so many things like new NextJS Rust Performance. So glad.

**Pull request merged**
