### PR TITLE
Router: Add `options.state` to enable custom `history.state`

### PR DESCRIPTION
**Pull request by thomaslindstrom**
I've been searching the docs for something that would help me set `history.state` in the browser to be retrieved when the user does `window.history.back()`, expecting to return to their previous context. Turns out `Router` replaces this state altogether in `Router.changeState`. 

The PR proposes a new `option.state`. This allows for updating the state object as the current app view context changes. For example, updating the `history.state` when the currently visible items are changing.  

```
function onVisibleItemsChange() {
	Router.replace(
		Router.route,
		Router.asPath,
		{
			state: {currentlyVisibleItems: [1, 2, 3]}
		}
	);
}
```

Imagine the user doing a `window.history.back()` after, eg., going into a detail view of one of the items: Reading `history.state` on render will enable me to reset to what the user was seeing before changing views.

### CODE REVIEW

**Comment by timneutkens** [comment]
I need to discuss this further as this might/will lead to abuse of state that can't be retained when server rendering / refreshing the page etc, causing inconsistencies in your application. This might be a tradeoff worth making, however we should extensively document it in that case. I'll get back to your on this 👍

**Comment by thomaslindstrom** [comment]
@timneutkens Maybe, but as of now, there is no other way to solve this issue with existing features. `history.state` isn't available on the server side.

**Comment by developit** [comment]
Hi @thomaslindstrom! I just wanted to drop a suggestion here since I've run into this problem in the past built a solution for it that works pretty well. It's called [histore](https://github.com/developit/histore), and it's a tiny little module that lets you address history state as a key-value database, independent of the router you happen to be using (in this case, Next's).

Here's your example modified to use Histore:
https://gist.github.com/developit/16c35f159dd797cd31945a96e2ba94bc

The nice thing is that it's nice and easy to sub in a server-side or in-memory version of this:

```js
// histore-server.js
export default () => ({ get() {}, set () {} })
```

```js
// histore-memory.js
export default (state = {}) => ({
  get(k) { return state[k] },
  set(k, v) { state[k] = v }
})
```

```diff
// next.config.js
module.exports = function(nextConfig) {
  return Object.assign({}, nextConfig, {
    webpack(config, opts) {
+      const aliases = config.module.alias || (config.module.alias = {});
+      if (opts.isServer) {
+        aliases.histore = path.resolve(__dirname, 'src/libs/histore-server.js')
+      }
      return nextConfig.webpack && nextConfig.webpack(config, opts) || config;
    }
  };
};
```

Depending on your environment and preferences, swapping between store implementations like this can be pretty handy.

**Comment by timneutkens** [comment]
I still have the concern it leads to misusage / using it over addressable urls. Histore helps in this case, so I'll close this PR for now as it also hasn't gotten very strong community traction (one other user upvoting it).

**Comment by robinvdvleuten** [comment]
@developit the example you've provided does not work anymore, as the dependencies are not bundled when building;

```js
/***/ "zZKO":
/***/ (function(module, exports) {

module.exports = require("histore");
```

**Comment by sever1an** [comment]
> I still have the concern it leads to misusage / using it over addressable urls. Histore helps in this case, so I'll close this PR for now as it also hasn't gotten very strong community traction (one other user upvoting it).

This is a pretty universal feature in other SPA frameworks, and it is actually really frustrating that Next.js does not have it. Of course, we can hack stuff into history state ourselves, but that is worse than the hypothetical misuse of the feature described above. I hope this is something that might be revisited later.

**Pull request closed without merging**
