### PR TITLE
fix(next): copy unfetch sourcemap

### LINKED ISSUE #12861: Copy polyfills source maps
# Feature request

I would like to request a feature to copy source maps from polyfills to next build. Currently, the source maps are skipped but js file still contains a reference to it.

This request is very related to https://github.com/zeit/next.js/issues/7579 but I decided to report it separately since it probably requires a different bunch of work. Feel free to close if you find it duplicate.

## Is your feature request related to a problem? Please describe.
We use [source map loader](https://webpack.js.org/loaders/source-map-loader/) in our app which allows us to include third-party source maps in our build. It is extremely helpful especially in conjunction with [Sentry](https://sentry.io/welcome/). It helps us track down bugs easily and eventually if it is not a bug on our side then report it to correct package maintainers.

I prepared [MWE for you](https://github.com/Joozty/next-source-maps) when you run the app and open chrome console you will see something like:

```
Can't resolve './unfetch.js.map' in '/mnt/c/Users/joozty/Documents/next-source-maps/node_modules/next/dist/build/polyfills'
```

sm

it happens because unfetch.js file [copied here](https://github.com/zeit/next.js/blob/canary/packages/next/taskfile.js#L23) contains a reference to a source map which is not copied. (It's probably the same for other polyfills too.)

## Describe the solution you'd like

I would like to have these source maps included. It's not a big deal and this warning can be ignored but as I mentioned earlier it's a nice feature for having bug free JS ecosystem. :)

### PR DESCRIPTION
**Pull request by maxigimenez**
Closes #12861

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/app-document-import-order/test/index.test.js** 
- Root components import order > on dev server > root components should be imported in this order _document > _app > page in order to respect side effects
- Root components import order > on dev server > _app chunks should be attached to de dom before page chunks

<details>
<summary>Expand output</summary>

  ● Root components import order › on dev server › root components should be imported in this order _document > _app > page in order to respect side effects

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      80 | 
      81 |   describe('on dev server', () => {
    > 82 |     beforeAll(async () => {
         |     ^
      83 |       appPort = await findPort()
      84 |       app = await launchApp(join(__dirname, '../'), appPort)
      85 |     })

      at integration/app-document-import-order/test/index.test.js:82:5
      at integration/app-document-import-order/test/index.test.js:81:3
      at Object.<anonymous> (integration/app-document-import-order/test/index.test.js:22:1)

  ● Root components import order › on dev server › _app chunks should be attached to de dom before page chunks

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      80 | 
      81 |   describe('on dev server', () => {
    > 82 |     beforeAll(async () => {
         |     ^
      83 |       appPort = await findPort()
      84 |       app = await launchApp(join(__dirname, '../'), appPort)
      85 |     })

      at integration/app-document-import-order/test/index.test.js:82:5
      at integration/app-document-import-order/test/index.test.js:81:3
      at Object.<anonymous> (integration/app-document-import-order/test/index.test.js:22:1)


  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "pid" argument must be of type number. Received type number (NaN)

      at killPid (../node_modules/tree-kill/index.js:73:17)
      at ../node_modules/tree-kill/index.js:55:17
          at Array.forEach (<anonymous>)
      at killAll (../node_modules/tree-kill/index.js:47:27)
      at ../node_modules/tree-kill/index.js:38:13
      at ChildProcess.onClose (../node_modules/tree-kill/index.js:94:17)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| buildDuration | 14.1s | 13.5s | -563ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +1.92 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.504 | 2.355 | -0.15 |
| / avg req/sec | 998.57 | 1061.67 | ⚠️ +63.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.601 | 1.572 | -0.03 |
| /error-in-render avg req/sec | 1561.8 | 1590.29 | ⚠️ +28.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| index.html gzip | 928 B | 928 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.2s | -372ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +1.92 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | maxigimenez/next.js fix/12861-unfetch-source-map | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

**Comment by timneutkens** [comment]
This doesn't seem to be related to #12861, which asks for a sourcemap for `@next/polyfill-nomodule`

**Comment by maxigimenez** [comment]
> This doesn't seem to be related to #12861, which asks for a sourcemap for `@next/polyfill-nomodule`

Ah ok, I miss understanding the issue. Still I can see that `unfetch.js` contains the "sourceMappingURL"  and has warnings, I was able to reproduce it on the provided repo on the ticket.

**Pull request closed without merging**
