### PR TITLE
docs: update static-tweet to react-tweet

### PR DESCRIPTION
**Pull request by JamBalaya56562**
## Description

Now that next-tweet has been renamed [react-tweet](https://github.com/vercel/react-tweet), [Static Tweet (Demo)](https://static-tweet.vercel.app/) navigates https://react-tweet.vercel.app.
So updated the link.

### Adding or Updating Examples

- [x] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- [x] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a6454ecab772122fcf78ebc6582dadcbefc17206

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a6454ecab772122fcf78ebc6582dadcbefc17206

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a6454ecab772122fcf78ebc6582dadcbefc17206

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by delbaoliveira — APPROVED** [review]
Thank you!

**Pull request merged**
