### PR TITLE
Update cms-contentful example with new Live Preview Integration

### PR DESCRIPTION
**Pull request by malewis5**
**Scope**
Update the cms-contentful example to use the new Live Preview integration provided by the `@contentful/vercel-nextjs-toolkit` package.

**Changes**
* Update the `/api/draft` route to use the handler provided by Contentful
* Add a section to the README.md for Draft Mode with Live Preview
* Edit previous Draft Mode section so users understand both are an option.
* Add `@contentful/vercel-nextjs-toolkit` package

**Resources**
[Contentful Integration Docs](https://www.contentful.com/developers/docs/tools/vercel-nextjs/vercel-nextjs-toolkit/)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 80a5bbe1fbf7242ac77a3d14d56492721f42bdab

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by malewis5** [comment]
@delbaoliveira bumping this, let me know how I can help.

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
Is this a duplicate of https://github.com/vercel/next.js/pull/67233?

**Comment by malewis5** [comment]
> Is this a duplicate of #67233?

Yes, that's from the Contentful team. I was holding off on adding the inspector tool since until Content Link is finished. Their PR also changes the `<Post />` component from RSC to client component. I can talk with Contentful.

**Comment by leerob** [comment]
Going to close this as stale, let's combine into one PR?

**Pull request closed without merging**
