### PR TITLE
Enable typechecking on config

### PR DESCRIPTION
**Pull request by karlhorky**
### What?

Enable TS type-checking on config for reproduction templates

### Why?

Using JSDoc type on `module.exports` doesn't work in TypeScript currently:

- https://github.com/microsoft/TypeScript/issues/51819
- https://github.com/microsoft/TypeScript/issues/47107

`create-next-app` already fixed this:

- commit by @ijjk https://github.com/vercel/next.js/pull/34029/commits/41512831e7ed0003a03b5b8b1b4ba0aae670bcd9 (part of PR https://github.com/vercel/next.js/pull/34029)

### How?

Create intermediate `nextConfig` variable and annotate that with JSDoc type

### Prior Art

Also done in `rspack-website` over here:

- https://github.com/web-infra-dev/rspack-website/pull/286
- https://github.com/web-infra-dev/rspack/pull/2965

cc @balazsorban44

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 524b24f9d3051ed259c3a1e7123a2d7d5e71c113

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 524b24f9d3051ed259c3a1e7123a2d7d5e71c113

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — DISMISSED** [review]

**Comment by karlhorky** [comment]
@balazsorban44 thanks for the approval. I guess CI is currently broken in `canary`, can we merge this as-is?

**Comment by balazsorban44** [comment]
The merging process is automatic. It might take a bit but will be merged.

**Comment by karlhorky** [comment]
> The merging process is automatic

ah nice, fancy. I hope I didn't break that automatic process by hitting the "Update branch" button to merge from `canary` (which created a new merge commit after your approval)

**Comment by karlhorky** [comment]
@balazsorban44 it seems this still hasn't been automatically merged.

Should I do something? Or can you, from your side?

**Review by balazsorban44 — APPROVED** [review]

**Comment by karlhorky** [comment]
@balazsorban44 Seems like the only thing that is failing now is the Datadog failure, seemingly unrelated to this PR:

```
Run actions/download-artifact@v3
Starting download for test-reports
Error: Unable to find an artifact with the name: test-reports
```

What do you think of ignoring the CI error and merging as is?

**Comment by karlhorky** [comment]
Thanks for the review and merge @balazsorban44 @huozhi 🙌

**Pull request merged**
