### PR TITLE
Update styled-components example README

### PR DESCRIPTION
**Pull request by silvenon**
v2 is no longer in beta.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
We should update the package.json too then 👍

**Comment by silvenon** [comment]
@timneutkens not sure if you noticed, but I pushed the commit where I updated `package.json` too…

**Comment by timneutkens** [comment]
Oh sorry! 😄

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Has been fixed already as far as I can see, not sure where we did 😅

**Pull request closed without merging**
