### PR TITLE
Ignore link behavior for links with target

### PR DESCRIPTION
**Pull request by khankuan**
Example:
```
<Link href="google.com">
  <a target="_blank">google.com</a>
</Link>
```

### CODE REVIEW

**Comment by sergiodxa** [comment]
Why use `next/link` anyway if you know it's going to be open in a new tab? You can just use an `<a />`.

**Comment by khankuan** [comment]
Take an example where the `target` prop is dynamic:
```
renderLink() {
  if (newTab) {
    return <a href={url}>Click me</a>
  }
  return <Link href={url}><a>Click me</a><Link>
}
```
vs
```
renderLink() {
  return <Link href={url}><a target={newTab}>Click me</a><Link>
}
```

**Comment by arunoda** [comment]
@khankuan this is something like a rare use.
Simply use `next/router` to do you routing with a regular `<a>` tag.

**Comment by khankuan** [comment]
I think it will be nice to have the framework handle the differences between `<Link>` and `<a>` as much as possible. My intention is to avoid confusion in implementation whether to use Link or not. Is there other cases where Link cannot be used and we should use the anchor tag?

Also, we can find similar logic in alternative routers such as https://github.com/ReactTraining/react-router/blame/master/packages/react-router-dom/modules/Link.js#L42

**Comment by sergiodxa** [comment]
@khankuan but React Router link component it's supposed to be used as a replacement for `<a>` tags,  the `next/link` component it's just a wrapper around the `<a>` to use a declarative approach for internal routing, if you need a custom logic you can use `next/router` as @arunoda said, you can also create your own Link component to handle this.

**Comment by khankuan** [comment]
Ok thanks for your explanation.

**Comment by bryandowning** [comment]
So, setting ` target="_blank"` on the child `<a>` seems to work for me (which makes sense due to the use of `React.cloneElement`: https://github.com/zeit/next.js/blob/master/lib/link.js#L145). Is this unexpected?

**Comment by tomsoderlund** [comment]
I see inconsistent behaviour when using `target="_top"` with Link/a inside an IFrame. Sometimes it opens the link _inside_ the IFrame, sometimes _outside_ (as it should).

e.g.

`<Link href="https://foo.com"><a target="_top">My link</a></Link>`

**Pull request closed without merging**
