### PR TITLE
Example: Next.js with CoffeeScript 2.0 (with-coffee2)

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Review by sergiodxa — CHANGES_REQUESTED** [review]
The transpiled JS files shouldn't be in the repo. Usually you never commit built files to avoid unnecessary diff issues.

**Comment by stevefan1999** [comment]
Whoops, it was midnight in Hong Kong when I've made this pull request, then I prompted to sleep. I've removed the files. It's done now.

**Review by stevefan1999-personal — COMMENTED** [review]
i wonder why was this frozen, turns out i forgot ti submit a review

**Review by stevefan1999-personal — COMMENTED** [review]
this is confusing...what should i do now?

**Comment by timneutkens** [comment]
@stevefan1999 you'll just have to wait till I merge 👍

**Comment by stevefan1999** [comment]
I need to reset my fork for multiple pull request (3 if you want to know). I'm not a Git expert. Closing this first,

**Pull request closed without merging**
