### PR TITLE
Support webpack harmony modules in self accept

### PR DESCRIPTION
**Pull request by kpdecker**

### CODE REVIEW

**Comment by arunoda** [comment]
Could you add more info about this PR.

**Comment by kpdecker** [comment]
This is one of the changes needed to support #2478. Allows the hot reload to target webpacks "classical" output or their newer "harmony module" output.

**Comment by arunoda** [comment]
Okay. Makes sense.

**Comment by chuyik** [comment]
@kpdecker So should #2478 comes back?

**Comment by kpdecker** [comment]
@chuyik requires more testing. There were a number of issues that I found, some webpack related even, so I've backed off of this for now. Will revamp after we get the phase of our Next rollout out.

**Pull request merged**
