### PR TITLE
Use react-is to check component validity

### LINKED ISSUE #4055: Home-rolled "is Component?" test is throwing false negatives for React 16.3.0 features
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Overview

React 16.3 will include a utility for ref forwarding called `React.forwardRef`. [Its RFC](https://github.com/reactjs/rfcs/pull/30) has been ratified and the initial implementation is available in alpha builds of 16.3.

The `typeof` objects returned by `forwardRef` happens to be `"object"`, not `"function"`, which means that if you wrap your Page component in a HOC that uses `forwardRef`, it will fail the overly-aggressive [test here](https://github.com/zeit/next.js/blob/01f05d8cbc0333dd629f3c6bb180d73c41fed968/lib/app.js#L36-L40).

## Expected Behavior

If I wrap a top-level Page component with `React.forwardRef`, I expect Next.js to render it without issue.

## Current Behavior

If I wrap a top-level Page component with `React.forwardRef`, Next.js throws the following error:

```
Error: The default export is not a React Component in page: ...
```

## Steps to Reproduce (for bugs)

For any Page component in a Next.js app, add the following lines:

```js
// ...
const MyPage = () => (...);
export default React.forwardRef((props, ref) => <MyPage {...props} forwardedRef={ref} />);
```

## Context

As soon as the `forwardRef` API is released, library that expose HOCs are going to start using it to provide a standard way of accessing the ref of the wrapped component. (Prior to this, each HOC library would take a slightly different approach.)

As more libraries and apps are updated, the number of people impacted will grow. I expect this to happen fairly rapidly, at least for actively-maintained libraries.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  5.0.1-canary.17       |

### PR DESCRIPTION
**Pull request by elliottsj**
Fixes #4055

To try this out, check out my branch, then:

```
npm install
npm link
cd examples/hello-world/
npm install
npm link next
npm run dev
```

Then edit `examples/hello-world/pages/index.js`:
```jsx
export default React.forwardRef((props, ref) => (
  <div ref={ref}>
    Hello World. <Link href='/about'><a>About</a></Link>
  </div>
));
```

Visit http://localhost:3000 and the example should render without error.

### CODE REVIEW

**Comment by timneutkens** [comment]
Looks like the tests failed

**Comment by timneutkens** [comment]
I wonder if we can make this check development only, and only load react-is in that case to save bundle size

**Comment by elliottsj** [comment]
That sounds like a good idea. Does Next.js have an existing pattern to do that?

One way is to add a NODE_ENV check before the `isValidElementType` check, and rely on webpack's dead code elimination to omit the react-is module when it detects that its exports aren't used:
```js
if (process.env.NODE_ENV === 'development' && !isValidElementType(Component)) {
  throw new Error(`The default export is not a React Component in page: "${pathname}"`)
}
```

I'm trying this out, adding this to `rules` in `build/webpack.js`:
```js
{
  include: /react-is/,
  sideEffects: false,
},
```

But `react-is` still seems to be included in the production bundle in the hello-world example.

**Comment by timneutkens** [comment]
I guess something like this should work:

```
if (process.env.NODE_ENV === 'development') {
  const {isValidElementType} = require('react-is')
  if(!isValidElementType(Component)) {
	throw new Error(`The default export is not a React Component in page: "${pathname}"`)
  }
}
```

**Comment by elliottsj** [comment]
Trying it out now, and it appears that react-is is still included in the production bundle even with the suggested outer `if` statement.

I've pushed my changes to this branch, and you can verify with:
```
npm install
npm link
cd examples/hello-world/
npm install
npm link next

# Build for production:
npm run build
npm start
```

Open http://localhost:3000 and look at the commons JS asset (mine is http://localhost:3000/_next/static/chunks/commons.792d7d9de2a7d11ba82f.js). You'll find the minified source of react-is in here.

**Comment by timneutkens** [comment]
I wonder if it’s shipped with React?

**Comment by timneutkens** [comment]
I’ll have a look tomorrow 👍🏻

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/pull/5095/commits/5ddd91c07d00fa9cd80cbfc85c8dc1e917a875b1

I had to add IgnorePlugin for that specific file. Apparently webpack still bundles the require otherwise 🙏

**Comment by elliottsj** [comment]
Awesome, thanks 🙏

**Comment by timneutkens** [comment]
Looks like the tests are failing though.

**Comment by elliottsj** [comment]
Looks like the `should recover after exporting an invalid page` test is failing again, now due to the fact that the `isValidElementType` check doesn't occur on production:
```
  ● Basic Features › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatch(expected)

    Expected value to match:
      /The default export is not a React Component/
    Received:
      "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

The test suite doesn't enter the `if (process.env.NODE_ENV === 'development') {}` block, so React's own error is raised instead upon render.

Should I update the test to expect React's error instead? Or maybe change the test suite so specific tests are executed using `process.env.NODE_ENV === 'development'`

**Comment by nassimbenkirane** [comment]
Hello 😄This PR seems great 👍

Do you think we could consider having react-is in the production bundle if/when the tree-shakeable version is merged and released https://github.com/facebook/react/pull/13321

Or is it better to keep react-is outside of the production bundle and we should rather change the tests ?

**Comment by timneutkens** [comment]
I'm going to close this PR as it has merge conflicts and the test was breaking, but I'll add good first issue / help wanted labels to the original issue and post that you already implement most here so that someone can take a look 💯

**Pull request closed without merging**
