### PR TITLE
Adding Example: with-cookie-auth-fauna-apollo-server

### PR DESCRIPTION
**Pull request by fev4**
Hello!

First PR here! Made a mistake in the last PR with the same name, now this is from a proper (different) branch.

The following example explains how to setup FaunaDB & Next.js in order to have a simple httpOnly cookie auth flow, using Apollo Server and react-query/graphql-request on the front-end, while being deployed to Vercel.

These are some of the features that this setup provides:

An auth flow with httpOnly cookies.
Token validation on refresh and window focus.
A local GraphQL server between the client and Fauna's GraphQL. This proxy is used to create a validCookie function that verifies if the httpOnly cookie is valid or not, before delegating to the remote schema.
Demo link: https://with-graphql-faunadb-cookie-auth.now.sh/

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11s | -246ms |
| nodeModulesSize | 66 MB | 66 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.878 | 1.876 | 0 |
| / avg req/sec | 1331.36 | 1332.36 | ⚠️ +1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.046 | 1.116 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 2389.31 | 2239.35 | -149.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.61 kB | 6.61 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9545.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.69 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.9s | ⚠️ +40ms |
| nodeModulesSize | 66 MB | 66 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.61 kB | 6.61 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..9545.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.69 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | fillipvt/next.js with-cookie-auth-fauna-apollo-server | Change |
| - | - | - | - |
| _error.js | 878 kB | 878 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 878 kB | 878 kB | ✓ |
| link.js | 916 kB | 916 kB | ✓ |
| routerDirect.js | 909 kB | 909 kB | ✓ |
| withRouter.js | 909 kB | 909 kB | ✓ |
| Overall change | 4.5 MB | 4.5 MB | ✓ |

</details>

</details>

**Comment by fauna-brecht** [comment]
Hey Filip, 

that's some great work. 
Would you think it to be a good idea to provide a script to simplify setting up User Defined Functions / Roles for this approach sine the example might seem daunting for users that get started with FaunaDB for the first time.

**Comment by fillipvt** [comment]
hey @fauna-brecht it would be great! Not sure where to begin with  that though. Let me see

**Comment by lfades** [comment]
@fillipvt The current state of the example is quite complicated, and not easy to get started with, we usually don't have this level of complexity on examples. Try to simplify the complicated tasks (an script would be a huge help). For example, compare the instructions in this example with the one in the other example with (almost) the same name: https://github.com/vercel/next.js/tree/canary/examples/with-cookie-auth-fauna

**Comment by timneutkens** [comment]
Will close this for now, feel free to ping @lfades when the suggested changes are made for a re-review.

**Comment by fillipvt** [comment]
Hey @lfades, @fauna-brecht,

I've updated the branch on my end. Let me know what you think about the latest commits. I've tried to simplify the process as much as possible while providing a bit of flexibility in the scripts.

@lfades please let me know if, with the latest changes, it's possible to re-open the PR.

Thank you

**Comment by lfades** [comment]
@fillipvt The readme is a lot better now, the code is still complicated and that may be because it's doing some advanced stuff that I don't understand. Can you please update the readme and provide more details on what is it doing and why is that important? - Maybe even compare it with the `with-cookie-auth-fauna` example that has almost the exact same name and right now they both seem to be doing the same thing, except this one has way more code.

For example: "The authentication in this example uses the following strategies: ..." - "And it's better than `with-cookie-auth-fauna` because of X and X. You should use this example if X and X, etc". Also feel free to link to external resources if any.

The example will be read by humans looking to build authentication with FaunaDB. Compare the example to a real app, you want them to understand the app, and if they're interested, they won't be surprised of what they see in the code.

**Comment by fillipvt** [comment]
@lfades Thank you for the detailed comments!

I've updated the readme and added more comments throughout the example. In the readme, I'm now highlighting the main features the example has while pointing to `with-cookie-auth-fauna` in case a person is looking for something simpler.

Let me know what you think when you get the chance.

**Comment by lfades** [comment]
@fillipvt The readme looks good now, thank you! I don't know how Fauna works but now I know what the app is exactly for 👌 

Feel free to open a new PR, then I'll follow the instructions in the readme and merge it if it works 😌

**Comment by fauna-brecht** [comment]
Hi @fillipvt, 

Great work, README looks much better!
I took a quick look, it's indeed an advanced example so it's also for me hard to verify :).
There are a few minor comments at a first glance: 

- In the README it says UDFs UDRs are the most flexible medium, could you change this to 'are a flexible' so it doesn't sound like it's the only option. At this point, it could be interpreted as: "this is the best you will get when using FaunaDB and I don't think that was the intention :)'. 

- In the cookie config it seems strange to me to define a function 'faunaClient' and import it later on. 
`import faunadb from 'faunadb'

export const SECRET_COOKIE_NAME = 'custom_cookie'

// Used for any authed requests.
export const faunaClient = (secret) =>
  new faunadb.Client({
    secret,
  })|
`
For people who are used to FaunaDB they would be searching for the driver import and expect you do something more advanced than simply create the client, it's probably adding more confusing. 

- I can see how you log in, register, log out. However, I don't think you defined any data right? As a user I would wonder how to use this cookie now to connect with FaunaDB to fetch data? Is the intention to always go through the backend, retrieve the token from the httpOnly cookie and only then call FaunaDB?

**Comment by fillipvt** [comment]
Hey @fauna-brecht @lfades 

I've updated the PR a bit while ago but life happened and couldn't update with a comment here. Here's where the code lives:

https://github.com/fillipvt/with-graphql-faunadb-cookie-auth/

And here's the updated demo: https://with-graphql-faunadb-cookie-auth.now.sh/

I've reworked the main logic behind the token validation and it is way simpler now. I've added bunch of comments through out all the code and I've implemented a full CRUD.

Hopefully this solves all the points above. Please let me know what you think.

I'd appreciate it very much.

**Comment by lfades** [comment]
@fillipvt Feel free to create a PR and I'll do another review 👍

**Pull request closed without merging**
