### PR TITLE
Add empty yarn.lock to prevent caching

### PR DESCRIPTION
**Pull request by karlhorky**
Closes #57895
Closes #63038

### What?

Add an empty Yarn v1 lockfile for CodeSandbox to prevent caching of the outdated `yarn.lock` file that CodeSandbox saves between sandbox starts

### Why?

As confirmed with @CompuIves, CodeSandbox caches the `yarn.lock` file generated after the first start + `yarn install` of a GitHub template (Yarn v1) - this saves old versions of Next.js (not the latest canary) in the lockfile and causes old versions of Next.js to be installed when users click on the CodeSandbox Reproduction link during issue creation.

This leads to the CodeSandbox reproduction link leading to a broken state, where Next.js actually cannot even start the dev server in the reproduction sandbox:

1. Start creating a new GitHub issue on the `vercel/next` GitHub repo
2. Open [the CodeSandbox reproduction link](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template) linked in the **Link to the code that reproduces this issue** section
3. Observe the error message below in the `dev` task started below (`experimental.appDir: true` was required in the `13.0.8-canary.0` version of Next.js in the cached `yarn.lock` file, but the `next.config.js` file no longer includes this config)

```bash
$ yarn dev
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: > The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
    at Object.findPagesDir (/project/sandbox/node_modules/next/dist/lib/find-pages-dir.js:80:19)
    at new DevServer (/project/sandbox/node_modules/next/dist/server/dev/next-dev-server.js:110:59)
    at NextServer.createServer (/project/sandbox/node_modules/next/dist/server/next.js:140:20)
    at /project/sandbox/node_modules/next/dist/server/next.js:155:42
    at async NextServer.prepare (/project/sandbox/node_modules/next/dist/server/next.js:130:24)
    at async /project/sandbox/node_modules/next/dist/cli/next-dev.js:344:17
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Sandbox demo: https://codesandbox.io/p/sandbox/quirky-pascal-n32xk2?file=%2Fnext.config.js%3A5%2C1

Screenshot 2023-11-01 at 16 09 59

### How?

Add an empty Yarn v1 lockfile to prevent creation and caching of an outdated `yarn.lock` file

(confirmed with @CompuIves to be a valid strategy)

### Caveats

It's kind of unusual to see this empty Yarn v1 lockfile here (and also, it's only Yarn v1 because of CodeSandbox, so it's an implementation detail)

I added a comment in the `yarn.lock` file to point back at this PR, if that would be desirable to avoid people deleting it in future.

### Alternatives considered

- Delete the outdated `yarn.lock` file on setup of the sandbox, PR open here: https://github.com/vercel/next.js/pull/57895
- Switch Yarn v1 to pnpm in repros: #63038

cc @balazsorban44 @CompuIves

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c134ffbd06f2391c790bbb22cc432ef6582b2d2b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@karlhorky Does this also get fixed if you add an empty `pnpm-lock.yaml` file?

**Comment by karlhorky** [comment]
@samcx no I don't think so, last I checked CodeSandbox uses Yarn v1 by default

**Comment by karlhorky** [comment]
@samcx btw I also added more context, reasoning and background above in the original PR description, because it was lacking (this context was lost because it was discussed with Balázs and Ives personally offline)

**Comment by karlhorky** [comment]
@samcx I confirmed now that adding an empty `pnpm-lock.yaml` does not cause the CodeSandbox cached `yarn.lock` file to be ignored:

1. Go to my CodeSandbox reproduction link https://codesandbox.io/p/sandbox/github/karlhorky/next.js/tree/canary/examples/reproduction-template
2. Observe that in the `dev` tab below, no pnpm installation step takes place (the existing cached `yarn.lock` file + `node_modules` are used)

Screenshot 2024-03-08 at 10 10 20

Note: There is no dev server breakage in my version because the cached `yarn.lock` file was just generated today, so it has the latest canary still. It would break in the future any time that a breaking change would be introduced (eg. a config change requiring a change to `next.config.js` or anything else that would be a breaking change between versions).

cc @CompuIves

**Comment by karlhorky** [comment]
@samcx I also opened another PR to switch the CodeSandbox repros from Yarn v1 to `pnpm` instead, not 100% sure if this always works or the implications of this:

- #63038

**Pull request closed without merging**
