### PR TITLE
Upgrade Babel to 7.0.0-rc.1 (major)

### LINKED ISSUE #4614: Flow Type Error with Next.js 6
# Bug report
## Describe the bug
When components with flow types are used the pages using those components throw an "Unexpected token" error due to `type`.

### Packages:
* babel/preset-flow
* flow-bin

### .babelrc
* *babel/preset-flow* in in `presets`
* *babel/plugin-transform-flow-strip-types* in `plugins`.

## To Reproduce
1. `git clone git@github.com:bryanterrell/hello-next-flow.git`
2. `cd hello-next-flow`
3. `npm i`
4. `npm run dev`
5. Open http://localhost:3000 in browser & click *Go to About Page*
6. Error is produced:
```
Syntax Error: Unexpected token, expected ";" (3:5)

  1 | import * as React from "react";
  2 |
> 3 | type Props = {
    |      ^
  4 |   foo: number,
  5 |   bar?: string
  6 | };
```

## Expected behavior
Flow types should be stripped out so component / page can be rendered.

## System information
 - OS: macOS
 - Next.js version: 6.0.3

### LINKED ISSUE #4691: Next 6 with Babel 7 beta
Hi,

This is more a general question than an issue, apologies.

I run next with typescript (I honestly don’t think that this is far fetched or even an exotic combination) and since the dependency bump to Babel 7 beta, some of the typescript features my project depends on don’t work anymore. Some of the Babel language plugins just aren’t there yet and it is confusing. 

Don’t take this the wrong way, but why do you guys depend on a beta version (outdated at that) for one of the key components?

I love how you keep the pace up with canary releases et al, but I don’t think Babel 7 is ready yet for prime time, especially in regards to certain TS language features. 

The “with-typescript” example works fine, but it’s also super trivial. This shouldn’t be a measurement to determine the level of stability.

By hey, just my five cents. :-)

Oliver

### PR DESCRIPTION
**Pull request by kachkaev**
Fixes #4691
Fixes #4614

This PR gives path to https://github.com/zeit/next-plugins/pull/242

I did not add or remove `^` near dependency versions in package.json files. However, I don't exclude that some changes can be made given that rc is more stable than beta.

### CODE REVIEW

**Comment by benhjames** [comment]
This should fix #4614 too! 🙌

**Comment by kachkaev** [comment]
@timneutkens 7.0.0-rc.2 [is out](https://github.com/babel/babel/releases/tag/v7.0.0-rc.2) and I will be happy to submit a new PR to this repo and to next-plugins. Do you pre-approve? I'm also wondering if we can simply specify `^7.0.0-rc.2` for all babel stuff given that RCs are usually more stable than beta. This will remove a need to bump next canary every time a new RC is out. WDYT?

**Comment by timneutkens** [comment]
From earlier tweets babel 7 will be out this week

**Comment by kachkaev** [comment]
👍 great, let's wait!

**Comment by schoenwaldnils** [comment]
Babel 7.0.0 is out 🎉

**Comment by kachkaev** [comment]
@timneutkens will you be happy to accept a simple PR? Does anything need changing apart from the version bump?

**Comment by kachkaev** [comment]
Ah, it's already done! https://github.com/zeit/next.js/pull/5042

**Pull request merged**
