### PR TITLE
Add alt for image

### PR DESCRIPTION
**Pull request by LorhanSohaky**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Review by styfle — CHANGES_REQUESTED** [review]
This is a sizer so it shouldn't be described by the real image's `alt`

**Comment by LorhanSohaky** [comment]
> This is a sizer so it shouldn't be described by the real image's `alt`

I used the w3 validator and it complained about alt [link](https://validator.w3.org/nu/?doc=https%3A%2F%2Fbrasilapi-git-feature-improve-seo-lorhansohaky.vercel.app%2F)

**Comment by styfle** [comment]
Looks like you're using Next.js 10.

Please update to Next.js 11 with `yarn add next@latest`

**Review by styfle — CHANGES_REQUESTED** [review]
Looks like you're using Next.js 10.

Please update to Next.js 11 with `yarn add next@latest`

**Comment by ijjk** [comment]
Closing per above comment as this should be resolved after updating

**Pull request closed without merging**
