### PR TITLE
feat(_app): Auto patch legacy Next.js App `getInitialProps` opt-out [14773]

### PR DESCRIPTION
**Pull request by moh12594**
Hi 👋

This PR aims to remove legacy `getInitialProps` from _app file using a new babel plugin according to the issue #14773

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9d490f98fba6db6f3f90f820864c7fd38a386f97

**test/integration/app-document/test/index.test.js** 
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

<details>
<summary>Expand output</summary>

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhancer correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      54 |         const $ = await get$('/?withEnhancer=true')
      55 |         const nonce = 'RENDERED'
    > 56 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      57 |           true
      58 |         )
      59 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:56:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      62 |         const $ = await get$('/?withEnhanceComponent=true')
      63 |         const nonce = 'RENDERED'
    > 64 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      65 |           true
      66 |         )
      67 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:64:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      70 |         const $ = await get$('/?withEnhanceApp=true')
      71 |         const nonce = 'RENDERED'
    > 72 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      73 |       })
      74 | 
      75 |       test('It renders ctx.renderPage with enhanceApp and enhanceComponent correctly', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:72:70)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      76 |         const $ = await get$('/?withEnhanceComponent=true&withEnhanceApp=true')
      77 |         const nonce = 'RENDERED'
    > 78 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      79 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
      80 |           true
      81 |         )

      at Object.<anonymous> (integration/app-document/test/rendering.js:78:70)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e5a09d27f00e10a06e36a357e3656d9fe991e9a3

**test/integration/app-document/test/index.test.js** 
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

<details>
<summary>Expand output</summary>

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhancer correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      54 |         const $ = await get$('/?withEnhancer=true')
      55 |         const nonce = 'RENDERED'
    > 56 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      57 |           true
      58 |         )
      59 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:56:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      62 |         const $ = await get$('/?withEnhanceComponent=true')
      63 |         const nonce = 'RENDERED'
    > 64 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      65 |           true
      66 |         )
      67 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:64:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      70 |         const $ = await get$('/?withEnhanceApp=true')
      71 |         const nonce = 'RENDERED'
    > 72 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      73 |       })
      74 | 
      75 |       test('It renders ctx.renderPage with enhanceApp and enhanceComponent correctly', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:72:70)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      76 |         const $ = await get$('/?withEnhanceComponent=true&withEnhanceApp=true')
      77 |         const nonce = 'RENDERED'
    > 78 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      79 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
      80 |           true
      81 |         )

      at Object.<anonymous> (integration/app-document/test/rendering.js:78:70)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 12s | 11.7s | -328ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +7.23 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.91 | 1.943 | ⚠️ +0.03 |
| / avg req/sec | 1309.24 | 1286.4 | ⚠️ -22.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.184 | 1.158 | -0.03 |
| /error-in-render avg req/sec | 2110.71 | 2158.57 | +47.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 959 B | 959 B | ✓ |
| withRouter.html gzip | 946 B | 946 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | ⚠️ +12ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +7.23 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 908 kB | 908 kB | ✓ |
| withRouter.js | 908 kB | 908 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>
Commit: 9d490f98fba6db6f3f90f820864c7fd38a386f97

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.4s | -92ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +7.16 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.004 | 1.991 | -0.01 |
| / avg req/sec | 1247.41 | 1255.71 | +8.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.235 | 1.195 | -0.04 |
| /error-in-render avg req/sec | 2023.9 | 2091.52 | +67.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 959 B | 959 B | ✓ |
| withRouter.html gzip | 946 B | 946 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.4s | -186ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +7.16 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 908 kB | 908 kB | ✓ |
| withRouter.js | 908 kB | 908 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>
Commit: e5a09d27f00e10a06e36a357e3656d9fe991e9a3

**Comment by moh12594** [comment]
> ## Failing test suites
> Commit: [e5a09d2](https://github.com/vercel/next.js/commit/e5a09d27f00e10a06e36a357e3656d9fe991e9a3)
> 
> **test/integration/app-document/test/index.test.js**
> 
> * Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
> * Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
> * Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
> * Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly
> 
> Expand output
> **test/integration/no-override-next-props/test/index.test.js**
> 
> * Dynamic require > should show error when a Next prop is returned in _app.getInitialProps
> 
> Expand output

@Timer @timneutkens Any Idea, why removing legacy getInitialProps from _app page fails those test ? 🤔

**Comment by ijjk** [comment]
## Failing test suites 
Commit: bd48fcfcdc8e470b3bb9fed14eca78579c5b8d00

**test/integration/app-document/test/index.test.js** 
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

<details>
<summary>Expand output</summary>

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhancer correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      54 |         const $ = await get$('/?withEnhancer=true')
      55 |         const nonce = 'RENDERED'
    > 56 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      57 |           true
      58 |         )
      59 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:56:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      62 |         const $ = await get$('/?withEnhanceComponent=true')
      63 |         const nonce = 'RENDERED'
    > 64 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
         |                                                                            ^
      65 |           true
      66 |         )
      67 |       })

      at Object.<anonymous> (integration/app-document/test/rendering.js:64:76)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      70 |         const $ = await get$('/?withEnhanceApp=true')
      71 |         const nonce = 'RENDERED'
    > 72 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      73 |       })
      74 | 
      75 |       test('It renders ctx.renderPage with enhanceApp and enhanceComponent correctly', async () => {

      at Object.<anonymous> (integration/app-document/test/rendering.js:72:70)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      76 |         const $ = await get$('/?withEnhanceComponent=true&withEnhanceApp=true')
      77 |         const nonce = 'RENDERED'
    > 78 |         expect($('#render-page-enhance-app').text().includes(nonce)).toBe(true)
         |                                                                      ^
      79 |         expect($('#render-page-enhance-component').text().includes(nonce)).toBe(
      80 |           true
      81 |         )

      at Object.<anonymous> (integration/app-document/test/rendering.js:78:70)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.8s | ⚠️ +663ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ⚠️ +7.16 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.335 | 2.298 | -0.04 |
| / avg req/sec | 1070.74 | 1087.68 | +16.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.478 | 1.526 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1690.99 | 1638 | ⚠️ -52.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| 677f882d2ed8..5755.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| main-d8a3f1c..06ea.js gzip | 6.72 kB | 6.72 kB | ✓ |
| polyfills-05..1236.js gzip | 30.8 kB | 30.8 kB | ✓ |
| webpack-488d..c0e7.js gzip | 751 B | 751 B | ✓ |
| Overall change | 87.5 kB | 87.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.1 kB | 6.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| main-e63c4e5..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| polyfills-05..dule.js gzip | 30.8 kB | 30.8 kB | ✓ |
| webpack-4f62..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 82.6 kB | 82.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _app-8f5f611..1f7b.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8e69b..8695.js gzip | 3.41 kB | 3.41 kB | ✓ |
| hooks-f7f3d0..7465.js gzip | 887 B | 887 B | ✓ |
| index-08fb3f..c0e9.js gzip | 227 B | 227 B | ✓ |
| link-ddd176e..5566.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..8aa1.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..e777.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.66 kB | 7.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _app-669dbe5..dule.js gzip | 626 B | 626 B | ✓ |
| _error-663e6..dule.js gzip | 2.24 kB | 2.24 kB | ✓ |
| hooks-805c40..dule.js gzip | 387 B | 387 B | ✓ |
| index-6ba5a4..dule.js gzip | 226 B | 226 B | ✓ |
| link-69bc264..dule.js gzip | 1.25 kB | 1.25 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-d..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.29 kB | 5.29 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 275 B | 275 B | ✓ |
| _buildManife..dule.js gzip | 281 B | 281 B | ✓ |
| Overall change | 556 B | 556 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| index.html gzip | 948 B | 948 B | ✓ |
| link.html gzip | 954 B | 954 B | ✓ |
| withRouter.html gzip | 940 B | 940 B | ✓ |
| Overall change | 2.84 kB | 2.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.7s | -223ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ⚠️ +7.16 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| 677f882d2ed8..5755.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| main-d8a3f1c..06ea.js gzip | 6.72 kB | 6.72 kB | ✓ |
| polyfills-05..1236.js gzip | 30.8 kB | 30.8 kB | ✓ |
| webpack-488d..c0e7.js gzip | 751 B | 751 B | ✓ |
| Overall change | 87.5 kB | 87.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.1 kB | 6.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| main-e63c4e5..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| polyfills-05..dule.js gzip | 30.8 kB | 30.8 kB | ✓ |
| webpack-4f62..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 82.6 kB | 82.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _app-8f5f611..1f7b.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8e69b..8695.js gzip | 3.41 kB | 3.41 kB | ✓ |
| hooks-f7f3d0..7465.js gzip | 887 B | 887 B | ✓ |
| index-08fb3f..c0e9.js gzip | 227 B | 227 B | ✓ |
| link-ddd176e..5566.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..8aa1.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..e777.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.66 kB | 7.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _app-669dbe5..dule.js gzip | 626 B | 626 B | ✓ |
| _error-663e6..dule.js gzip | 2.24 kB | 2.24 kB | ✓ |
| hooks-805c40..dule.js gzip | 387 B | 387 B | ✓ |
| index-6ba5a4..dule.js gzip | 226 B | 226 B | ✓ |
| link-69bc264..dule.js gzip | 1.25 kB | 1.25 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-d..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.29 kB | 5.29 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 275 B | 275 B | ✓ |
| _buildManife..dule.js gzip | 281 B | 281 B | ✓ |
| Overall change | 556 B | 556 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | moh12594/next.js feat/14773 | Change |
| - | - | - | - |
| _error.js | 881 kB | 881 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 881 kB | 881 kB | ✓ |
| link.js | 922 kB | 922 kB | ✓ |
| routerDirect.js | 916 kB | 916 kB | ✓ |
| withRouter.js | 916 kB | 916 kB | ✓ |
| Overall change | 4.52 MB | 4.52 MB | ✓ |

</details>

</details>
Commit: bd48fcfcdc8e470b3bb9fed14eca78579c5b8d00

**Comment by timneutkens** [comment]
I'm going to close this PR as there's a lot less _app getInitialProps usage nowadays.

**Pull request closed without merging**
