### PR TITLE
docs: update route handler documentation on how to set cookies

### PR DESCRIPTION
**Pull request by joulev**
### Why?

The [route handler documentation](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#cookies) currently still says the recommended way to set cookies is by manually constructing a `Set-Cookie` header. It used to be necessary, but that is no longer the case since `cookies()` mutation methods work in route handlers now.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ae1a9d41dd7966e20ec362bddbde1a4ffabb147a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ae1a9d41dd7966e20ec362bddbde1a4ffabb147a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ae1a9d41dd7966e20ec362bddbde1a4ffabb147a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Replaced with https://github.com/vercel/next.js/pull/59915

**Pull request closed without merging**
