### PR TITLE
doc(deployment): improve performance of docker

### PR DESCRIPTION
**Pull request by alikazemkhanloo**
* custom cache folder for yarn to avoid downloading packages again
* COPY . . after moving node_modules to take advantage of docker's cache

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [x] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Comment by leerob** [comment]
Could you share some before / after results of this to validate it's faster? 😄 

And could you also update the `with-docker` example? Thank you!

**Comment by alikazemkhanloo** [comment]
Being faster depends on the network speed. But moving yarn's cache dir to `builder` is necessary for the flag `--prefer-offline` to make sense which is already in the doc.

**Comment by alikazemkhanloo** [comment]
Also moving `COPY . .` after copying node_modules and cache folder prevents copying them again when there is no changes in dependencies.

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, it looks like we can remove the second `yarn instal --production` step now since we no longer need to copy all of `node_modules` as the example is now leveraging the standalone output mode in Next.js which only includes necessary files. I opened a PR updating this [here](https://github.com/vercel/next.js/pull/32934)

**Pull request closed without merging**
