### PR TITLE
Add FusionAuth to list of authentication examples

### PR DESCRIPTION
**Pull request by codercatdev**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c4de2a565215c42705b630fd90b473a2461bb68a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@codercatdev It is probably better we do not include this since it's a part of `next-auth`, which is mentioned (we would have to include all the providers with `next-auth` then).

**Comment by codercatdev** [comment]
@samcx that is fine but you should remove [auth0](https://next-auth.js.org/providers/auth0) from this list then.

image

**Comment by samcx** [comment]
@codercatdev Not following, I believe they have their own npm package → https://github.com/auth0/nextjs-auth0.

**Comment by codercatdev** [comment]
@samcx gotcha! I didn't realize this tutorial used their own. I will take this back to the team to see if we need one specific for Next.js.

**Comment by samcx** [comment]
@codercatdev No worries. Let us know how that goes!

**Pull request closed without merging**
