### PR TITLE
Add note about standalone mode not working for app router

### PR DESCRIPTION
**Pull request by bjornarhagen**

### CODE REVIEW

**Comment by HamAndRock** [comment]
We are using standalone mode with appDirectory without any issues on 2 prod projects, as far as I know. The only issue we have is the server dying after some time due to OOM issues, but that's I think unrelated to standalone: https://github.com/vercel/next.js/issues/45508

But please correct me if I am wrong and we should get rid of output: standalone

**Comment by Innei** [comment]
It seems that this isn't just a problem with appDir, my project uses pageDir, but it's also has this problem

**Comment by HamAndRock** [comment]
Yeah, I know. Just wanted to say that we use standalone mode without any problems with appDirectory. The OOM/crashes are not related to this issue.

**Comment by bjornarhagen** [comment]
Sorry if this is actually no longer the case, and standalone mode should work fine with the App router. I just ran into this when trying to use standalone mode for this template https://github.com/medusajs/nextjs-starter-medusa. I also tried to install `next@canary` and build, but get the same error.

So without standalone mode it works fine, but when I turn it on, I get this build error
```
> Build error occurred
[Error: ENOENT: no such file or directory, lstat '/Users/USERNAME/dev/nextjs-starter-medusa/.next/server/app'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/USERNAME/dev/nextjs-starter-medusa/.next/server/app'
}
```

**Comment by HamAndRock** [comment]
Well I am just unsure, you get some weird errors on start but seems like it works fine in prod,

**Review by leerob — CHANGES_REQUESTED** [review]
Blocking because I'd like to get some clarity here first before this gets merged.

**Comment by DuCanhGH** [comment]
@bjornarhagen if you are using the `pages/` directory only, perhaps you can try setting `experimental.appDir` to false? Thanks!

[I added App Router support for `output: "standalone"` months ago](https://github.com/vercel/next.js/issues/43367#issuecomment-1327960598), so the note added in this PR is not correct :)

**Comment by bjornarhagen** [comment]
@DuCanhGH I see, must be something https://github.com/medusajs/nextjs-starter-medusa is doing that is causing the standalone build to fail then. Setting `experimental.appDir` to `false` does fix the issue.

Thank you so much! 😄

**Comment by leerob** [comment]
Note that the experimental flag is not needed with v13.4+.

**Pull request closed without merging**
