### PR TITLE
Add link to .env variables guide in readme recipes

### PR DESCRIPTION
**Pull request by patrickgwsmith**
The guide covers using .env variables on both the client and the server using dotenv and Webpack.

### CODE REVIEW

**Comment by timneutkens** [comment]
Few questions:
1. Have you seen:
https://github.com/zeit/next.js/tree/v3-beta/examples/with-dotenv
https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration

2. Have you tried `next build` `next start`? From checking your code it might not work in prod mode. I've seen someone else try it this way, but it failed in production mode, since the next.config.js is not loaded in production mode. Only during `next build`.

Thanks for taking the time to create such a detailed article 👌 ❤️

**Comment by timneutkens** [comment]
Okay just checked it out. This does work in production (compiled at build time). The only (major) drawback is that the client side variables are decided when `next build`ing and the server side variables are decided at runtime. You can reproduce this by using `TEST=abc next build` and then running that build with `TEST=abcdef next build`. It would render `abcdef` server side and the immediately override it on the client side when rehydrating React. Due to this drawback, and cause we have examples that don't have this drawback. I'm going to close the PR. Thank you very much for creating this PR, learned a few things 🤗 ❤️ 💯

**Comment by thearegee** [comment]
@timneutkens I'm also having issues with this. 

I have a .env with multiple env vars which works fine for dev, however when I build and start the values in either `.env.production` or if I set `process.env` don't pull through.

The only difference I have is I'm not using `next start` as I'm running my application though express for dynamic routing, so using standard `node server.js` commend.

I might be doing something stupid but I've tried this and `with-universal-configuration` in multiple different ways and `process.env.VAR` always returns undefined on the server and client.

Any ideas would be awesome! 

Thanks,
Rob

**Comment by timneutkens** [comment]
Hey @thearegee lets talk on https://zeit.chat 👌

**Comment by xedef** [comment]
@thearegee I have your exact problem. How did you solve it?

**Comment by mgiraldo** [comment]
@thearegee @xedef same here... i have tried many many many different variants and still cannot get the env vars to show up after “hydration”. am using a docker image in elasticbeanstalk with the env vars set in the eb console.

**Comment by timneutkens** [comment]
Try using the `with-universal-configuration-runtime` example, it'll use runtime env vars instead of compile time.

**Comment by mgiraldo** [comment]
@timneutkens would this require adding `const {API_URL} = env` to every page in the site? is this value accessible to child components the same way?

**Comment by mgiraldo** [comment]
we ended up adding a file on the jenkins deploy process with `export const MY_ENV = "MYVAL";` and any component that need it has `import { MY_ENV } from "/constants/env.js";`

**Pull request closed without merging**
