### PR TITLE
Prevent flooding when an error occurs

### PR DESCRIPTION
**Pull request by oliviertassinari**
Errors bubbles up, to reproduce the issue throw an error deep in a render method. You will see the `console.error` hit **many times**.

### CODE REVIEW

**Comment by timneutkens** [comment]
@arunoda can you check this out?

**Comment by arunoda** [comment]
@oliviertassinari could you send me a way to test this out?
What's the use case which this applies?
Basically, I need a way to test this locally.

**Comment by oliviertassinari** [comment]
Here is it:
https://github.com/oliviertassinari/next.js/commits/reproduction-example
capture d ecran 2017-06-27 a 10 16 43

**Comment by arunoda** [comment]
Thanks. This looks great.

**Comment by timneutkens** [comment]
👍

**Pull request merged**
