### PR TITLE
Support for wasm

### LINKED ISSUE #5277: Cannot load wasm files; compiling stucks at 98%
# Bug report

## Describe the bug
I tried to load a wasm module with a dynamic import.
The module was created with `wasm-bindgen` and works when used with webpack alone.
[Here is the wasm-bindgen example](https://rustwasm.github.io/wasm-bindgen/whirlwind-tour/basic-usage.html)

## To Reproduce
The included zipfile contains the precompiled wasm file from the wasm-bindgen example.
It should be enough to run `npm i`, `npm run dev` and then open `localhost:3000` in the browser.

[next-wasm.zip](https://github.com/zeit/next.js/files/2415158/next-wasm.zip)

## Expected behavior
The wasm module should be loaded dynamically and return an object with the function `greet`.

## Error
Here is the terminal output.
It will just stay at 98%.
The error message came only after waiting for some minutes and then hitting Ctrl+C,
if you don't wait and just hit Ctrl+C it, it won't show anything.

```bash
WAIT  Compiling...                                                                                  
[hardsource:e5a00840] Using 4 MB of disk space.


Compiling

● client █████████████████████████ after emitting (98%) write-file-webpack-plugin


● server █████████████████████████ after emitting (98%) write-file-webpack-plugin


^CError: Invalid arguments
    at filesize (/home/andy/projects/web/next-wasm/node_modules/filesize/lib/filesize.js:57:10)
    at /home/andy/projects/web/next-wasm/node_modules/write-file-webpack-plugin/dist/WriteFileWebpackPlugin.js:198:132
    at /home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:2996:24)
    at /home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:9344:14)
    at handleAfterEmit (/home/andy/projects/web/next-wasm/node_modules/write-file-webpack-plugin/dist/WriteFileWebpackPlugin.js:160:24)
    at _err1 (eval at create (/home/andy/projects/web/next-wasm/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:26:1)
    at /home/andy/projects/web/next-wasm/node_modules/next/dist/build/webpack/plugins/unlink-file-plugin.js:100:18
Error: Invalid arguments
    at filesize (/home/andy/projects/web/next-wasm/node_modules/filesize/lib/filesize.js:57:10)
    at /home/andy/projects/web/next-wasm/node_modules/write-file-webpack-plugin/dist/WriteFileWebpackPlugin.js:198:132
    at /home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:2996:24)
    at /home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/home/andy/projects/web/next-wasm/node_modules/lodash/lodash.js:9344:14)
    at handleAfterEmit (/home/andy/projects/web/next-wasm/node_modules/write-file-webpack-plugin/dist/WriteFileWebpackPlugin.js:160:24)
    at _err1 (eval at create (/home/andy/projects/web/next-wasm/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:26:1)
    at /home/andy/projects/web/next-wasm/node_modules/next/dist/build/webpack/plugins/unlink-file-plugin.js:100:18
got signal SIGINT, exiting
```

## System information
 - OS: macOS and Bash on Windows
 - Version of Next.js: 7.0.0

## Additional context
Building and exporting seem to work, however, if it tries to load the wasm file it will return a 404 response.

### PR DESCRIPTION
**Pull request by AndyBitz**
Together with webpack/webpack-sources#42 and gajus/write-file-webpack-plugin#71 it fixes #5277 

It sets the default wasm module name to `static/wasm/[modulehash].wasm` and adds the mime type `application/wasm`.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Awesome 🙌 we should also upgrade the write-file-webpack-plugin right? As you made a PR to that?

**Comment by AndyBitz** [comment]
Yes, but it isn't published to npm yet.

**Comment by gajus** [comment]
> @gajus sorry for pinging you out of nowhere, but could you do a new release of write-file-webpack-plugin? Then we can fix webassembly support in development with Next.js 👍🙌 Thank you very much in advance ❤️

Done.

**Comment by timneutkens** [comment]
Awesome! Thanks 🙌

**Comment by timneutkens** [comment]
Hmm interestingly appveyor is failing

**Comment by AndyBitz** [comment]
Hmm, the previous merge worked

Maybe it has something to do with this: `Build execution time has reached the maximum allowed time for your plan (60 minutes).`?

**Comment by timneutkens** [comment]
Merged this, but I think we still have to upgrade write-file-webpack-plugin

**Pull request merged**
