### PR TITLE
Removes webpack conformance plugin

### PR DESCRIPTION
**Pull request by housseindjirdeh**
Early on, `WebpackConformancePlugin` was created to provide conformance checks at the bundler level. This PR removes it for the following reasons:

* It isn't compatible with webpack v5
* Conformance with ESLint has landed in Next.js 11. Most rules currently within the webpack conformance plugin is unecessary: 
  * "Duplicate Polyfills" and "Sync script" rules are already present in `eslint-plugin-next`
  * Granular chunking is a first-class feature in webpack v5, which makes "GranularChunksConformanceCheck" redundant

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c27a6543bebb2cade48738f92e45c122bad97ebc

**test/acceptance/ReactRefresh.dev.test.js** 
-  > can edit a component without losing state
-  > cyclic dependencies

<details>
<summary>Expand output</summary>

  ● can edit a component without losing state

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefresh.dev.test.js:7:30)

  ● cyclic dependencies

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefresh.dev.test.js:62:30)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ee50d50b1bc74027420a3452323c3616f7e42718

**test/acceptance/ReactRefreshRequire.dev.test.js** 
-  > re-runs accepted modules
-  > propagates a hot update to closest accepted module
-  > propagates hot update to all inverse dependencies
-  > propagates a module that stops accepting in next version

<details>
<summary>Expand output</summary>

  ● re-runs accepted modules

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefreshRequire.dev.test.js:8:30)

  ● propagates a hot update to closest accepted module

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefreshRequire.dev.test.js:61:30)

  ● propagates hot update to all inverse dependencies

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefreshRequire.dev.test.js:163:30)

  ● propagates a module that stops accepting in next version

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefreshRequire.dev.test.js:348:30)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ee50d50b1bc74027420a3452323c3616f7e42718

**test/acceptance/ReactRefresh.dev.test.js** 
-  > can edit a component without losing state
-  > cyclic dependencies

<details>
<summary>Expand output</summary>

  ● can edit a component without losing state

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefresh.dev.test.js:7:30)

  ● cyclic dependencies

    WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
      (Session info: headless chrome=91.0.4472.101)

      177 |   console.log(`\n> Loading browser with ${url}\n`)
      178 |
    > 179 |   await browser.get(url)
          |   ^
      180 |   console.log(`\n> Loaded browser with ${url}\n`)
      181 |
      182 |   // Wait for application to hydrate

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at _default (lib/next-webdriver.js:179:3)
      at sandbox (acceptance/helpers.js:41:19)
      at Object.<anonymous> (acceptance/ReactRefresh.dev.test.js:62:30)

</details>

**Comment by housseindjirdeh** [comment]
Already being removed in #26915 for the next major version. Closing this!

**Pull request closed without merging**
