### PR TITLE
Upgrading with-flow example to the latest flow-bin ver. 0.59.0

### PR DESCRIPTION
**Pull request by davscro**
Upgrading with-flow example to the latest flow-bin ver. 0.59.0 which contains some breaking changes.
For upgrading I used flow-upgrade module by https://yarnpkg.com/en/package/flow-upgrade

### CODE REVIEW

**Comment by mattbrunetti** [comment]
Thanks for submitting this @davscro, I am looking at integrating Flow into our app very soon.

Any idea why the CI checks are failing? I could not fathom why, since your changes are only in the `examples/with-flow` directory, yet there are failing tests in e.g. `test/integration/production/test/index.test.js`....

**Comment by mattbrunetti** [comment]
CI checks are failing simply because the build in the main branch (`canary`) is failing

**Comment by davscro** [comment]
hey @mattbrunetti, aha ok. Thanks for the info.

**Comment by davscro** [comment]
hei @timneutkens, could you please review this changes?
thanks

**Review by timneutkens — APPROVED** [review]
Cool!

**Pull request merged**
