### PR TITLE
[errors/no-cache] Prevent GitHub Actions cache from going stale

### LINKED ISSUE #27129: Suggested GitHub Actions caching gets stale
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start in a Docker container

### Describe the Bug

When using GitHub actions, `/.next/cache` is generated once, and then remains stale until you update your npm packages. If you don't update your packages, your cache will never be updated, even as your app grows, new pages are added, etc.

### Expected Behavior

The CI cache should be updated whenever `/.next/cache` is updated.

### To Reproduce

The docs for `no-cache` give the following snippet on how to configure NextJS build caches with GitHub actions:

```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
```

Using that is enough to reproduce. More details:

The cache generated by that snippet is keyed on `package-lock.json`. Now, from the GitHub Actions docs:

> When the action finds a cache, the action restores the cached files to the path you configure. If [and only if] there is no exact match, the action creates a new cache entry if the job completes successfully.
https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

So as long as you are not updating `package-lock.json`, `/.next/cache` will never be updated again. As you keep developing your app, the cache gets more stale. I'm not sure what the consequences for this are on bundle caching, but at a minimum it increases build times significantly (on my app, builds were 30% slower than they should be).

An idea to fix this is to use `restore-keys`:

> The cache action first searches for cache hits for `key` and `restore-keys` in the branch containing the workflow run. If there are no hits in the current branch, the cache action searches for `key` and `restore-keys` in the parent branch and upstream branches.

```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]sx?') }}
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

With this configuration, an exact cache hit will only happen if files on `**/*.js` didn't change. If any of those files change, we have a cache miss and GitHub will generate a new, updated cache. *However*, GitHub will still restore the most recently generated cache from either the current or parent branch (as long as it was built with the same `package-lock.json`).

Unfortunately, the second hash (`**/*.[jt]sx?`) has to be customized to each use case. However, I think that one will work for 95% of use cases, and for the other ones it'll just cache a bit less than ideal (but still much better than the current suggestion).

A caveat here is that the cache will keep growing over time with stale data, until a package-lock update happens. There's no ideal solution to this until cache prunes are available in NextJS builds. If this is a big problem to anyone, you can add the current week of the year to the cache key, so your cache is regenerated from scratch once a week. In our own repo, we do that at Sunday morning and follow it with a clean build to regenerate the cache while we're all enjoying our extended Sunday sleep.

### PR DESCRIPTION
**Pull request by roim**
Closes: https://github.com/vercel/next.js/issues/27129

This configuration is similar to what we've been using at Statsig, and it's the best general purpose config I could think of.

At Statsig we also invalidate our caches weekly, since sometimes we spend weeks without updating dependencies for some of our NextJS apps, and the artifact bloat means GitHub starts invalidating other caches in our repo. I could add that step to this diff as well, but I think that's a bit too specific (likely only a problem in monorepos with several caches). In any case, the previous example also has this problem.

## Documentation / Examples

- [x] Make sure the linting passes

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Invalidating when any source file changes seems a little too eager to invalidate the cache as the `.next/cache` folder is meant to speed up build times significantly. 

When leveraging webpack 5 the `.next/cache` folder shouldn't grow too fast and should automatically invalidate. Are you seeing certain cached assets not be invalidated correctly?

**Comment by roim** [comment]
> Invalidating when any source file changes seems a little too eager to invalidate the cache as the `.next/cache` folder is meant to speed up build times significantly.
> 
> When leveraging webpack 5 the `.next/cache` folder shouldn't grow too fast and should automatically invalidate. Are you seeing certain cached assets not be invalidated correctly?

@ijjk 

This isn't invalidating any cache. The GitHub cache action works a bit differently than other CIs--it doesn't support cache invalidation to begin with (yes, that is a bit confusing and is why the mistake here is fairly common).

This diff simply ensures that new caches are generated--the old ones are still available and in fact are used to generate the new ones (the `restore-keys` piece). With the current configuration, a cache is generated when `package-lock.json` changes, and then it never is updated until that file changes again.

There are other alternatives for when to update the cache. I wouldn't mind doing it every couple hours, or every n commits, etc. Do you think some other strategy is better? The tradeoff is that until the cache is updated, new builds will keep using the stale one (+ build time), but they also won't have to post the updated cache which takes a few seconds for every couple MB (- build time).

**Review by ijjk — APPROVED** [review]
Ah I see, thanks for clearing that up! I missed that the cache wasn't updated here unless the key varied, we definitely want to be able to update the cache and fallback to previous ones when not available so this change does look good.

**Comment by belgattitude** [comment]
@roim 

```yaml
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

Just wondering, in the key part would it make sense to add ie: json, svg... files as well when we import them in the code ?

**Comment by roim** [comment]
@belgattitude I'm not sure. I looked briefly into what was on `.next/cache` in my projects and I think it's just transpiled, minified js keyed by md5. If so, only files that would change your produced js would be relevant--hopefully someone more experienced can confirm.

Regardless, the updated config here will be strictly better if you have json/svg files imported.

I thought about a comment for yarn/pnpn, but none of the other CI configs have it either. I don't think it's a big deal--most people using either are already used to swapping `package-lock.json` in their configs.

**Comment by belgattitude** [comment]
> Note that you can add extra files in the same hashFiles call, like ${{ hashFiles('**/package-lock.json', 'extra-glob-*) }}. You can merge the last 2 calls in your sample (but not the first one since you need it separately for restore-keys).

Thanks for this tip :smile: 

> I thought about a comment for yarn/pnpn, but none of the other CI configs have it either. I don't think it's a big deal--most people using either are already used to swapping package-lock.json in their configs.

Agree.

**Pull request merged**
