### PR TITLE
example: add styled reset with next example

### PR DESCRIPTION
**Pull request by bysxx**

### CODE REVIEW

**Comment by leerob** [comment]
Closing as stale, but happy to review a new PR if you are still interested in contributing here!

**Comment by bysxx** [comment]
Should I apply this new content and make a pr?

**Comment by leerob** [comment]
Yes, the new example should use the App Router 👍

**Comment by bysxx** [comment]
Thank you! I'll prepare for the promotion and send it to you! Thank
you for checking


2023년 6월 15일 (목) 오후 1:05, Lee Robinson ***@***.***>님이 작성:

**Pull request closed without merging**
