### PR TITLE
chore: update turbopack document path in the warning message

### PR DESCRIPTION
**Pull request by JamBalaya56562**
## Description

The page which provided [link](https://nextjs.link/with-turbopack) goes to has [a different URL](https://nextjs.org/docs/architecture/turbopack).
It's inconvenience and I update the path.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8f90dcdf48d0d222b60b086099a94fb1f36ab3b7

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: fdfcdeae65a33dbc37ec565a71563b37fe6a18a8

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/development/app-hmr/hmr.test.ts` (PPR)
- app-dir-hmr > filesystem changes > should update server components after navigating to a page with a different runtime

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should update server components after navigating to a page with a different runtime

    expect(received).toBe(expected) // Object.is equality

    Expected: "ipad"
    Received: "mac"

      69 |
      70 |         await retry(async () => {
    > 71 |           expect(await browser.elementByCss('p').text()).toBe('ipad')
         |                                                          ^
      72 |         })
      73 |
      74 |         const logs = await browser.log()

      at toBe (development/app-hmr/hmr.test.ts:71:58)
      at retry (lib/next-test-utils.ts:806:14)
      at development/app-hmr/hmr.test.ts:70:9
      at NextDevInstance.patchFile (lib/next-modes/base.ts:531:9)
      at NextDevInstance.patchFile (lib/next-modes/next-dev.ts:195:16)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:67:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| buildDuration | 21s | 17.7s | N/A |
| buildDurationCached | 16.8s | 14.9s | N/A |
| nodeModulesSize | 409 MB | 409 MB | N/A |
| nextStartRea..uration (ms) | 472ms | 466ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 50.2 kB | 50.2 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.3 kB | 5.3 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 233 B | 235 B | N/A |
| main-HASH.js gzip | 33.8 kB | 33.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.44 kB | 4.43 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| _buildManifest.js gzip | 747 B | 745 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 538 B | 538 B | ✓ |
| withRouter.html gzip | 520 B | 520 B | ✓ |
| Overall change | 1.06 kB | 1.06 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 203 kB | 203 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 667 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31 kB | 31 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| 523-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 523.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 322 kB | 322 kB | ✓ |
| app-page-exp..prod.js gzip | 127 kB | 127 kB | ✓ |
| app-page-tur..prod.js gzip | 140 kB | 140 kB | ✓ |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run...dev.js gzip | 312 kB | 312 kB | ✓ |
| app-page.run..prod.js gzip | 122 kB | 122 kB | ✓ |
| app-route-ex...dev.js gzip | 37.1 kB | 37.1 kB | ✓ |
| app-route-ex..prod.js gzip | 25.1 kB | 25.1 kB | ✓ |
| app-route-tu..prod.js gzip | 25.1 kB | 25.1 kB | ✓ |
| app-route-tu..prod.js gzip | 24.9 kB | 24.9 kB | ✓ |
| app-route.ru...dev.js gzip | 38.7 kB | 38.7 kB | ✓ |
| app-route.ru..prod.js gzip | 24.9 kB | 24.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-turbo...prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| pages.runtim...dev.js gzip | 27 kB | 27 kB | ✓ |
| pages.runtim..prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.35 MB | 2.35 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | JamBalaya56562/next.js turbopack | Change |
| - | - | - | - |
| 0.pack gzip | 2.03 MB | 2.03 MB | N/A |
| index.pack gzip | 146 kB | 144 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: fdfcdeae65a33dbc37ec565a71563b37fe6a18a8

**Comment by JamBalaya56562** [comment]
Thank you for checking this PR!
I have tested some failed tests, but it worked on my local PC.
Could you rerun CI?

**Pull request merged**
