### PR TITLE
Use `renderToStream` with React 18

### LINKED ISSUE #33879: React.lazy() content HTML does not get included in SSG output
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.0
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 0.0.0-experimental-fa816be7f-20220128
      react-dom: 0.0.0-experimental-fa816be7f-20220128

### What version of Next.js are you using?

 12.0.10

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

@devknoll asked me to file an issue for this. Basically, I'm observing that with React experimental versions, SSG doesn't wait for `lazy()` to be resolved and outputs the Suspense fallback HTML. Whereas I would've expected it to include content in SSG.

I'm not sure if this means `import()` needs to be compiled differently, or something.

A similar issue is that in SSR mode, the first hit will get fallback HTML and the next hits will get content HTML. Because the module is cached now.

### Expected Behavior

HTML output of SSG includes the SSR content of the lazy child.

### To Reproduce

Create a new clean project.

Add experimental React versions to it.

Page code:

```js
import {lazy, Suspense} from 'react'
import Head from 'next/head'

const Child = lazy(() => import('../components/Child'))

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Suspense fallback={<p style={{ color: 'red' }}>Loading...</p>}>
          <Child />
        </Suspense>
      </main>
    </div>
  )
}
```

Component code:

```js
// Some heavy lib to simulate loading a large chunk
import {marked} from 'marked'

export default function Child() {
  return <div dangerouslySetInnerHTML={{
    __html: marked(`# hello, world!`)
  }} />
}
```

Run `yarn build` and then `yarn start`.

Observe that the served HTML does **not** include `hello, world!` but does include `Loading...`.

### PR DESCRIPTION
**Pull request by devknoll**
As per React 18 recommendation, we should use e.g. `renderToReadableStream` whenever we use `createRoot`. This is particularly important for currently supported suspense features like `React.lazy` to work properly during SSR.

However, unless you have opted in to streaming support (via [the `runtime` flag](https://github.com/vercel/next.js/pull/34068)), we will wait until `onCompleteAll` before sending it (via the `generateStaticHTML` flag).

---

Fixes #33879

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| buildDuration | 17.2s | 16s | -1.2s |
| buildDurationCached | 5.9s | 5.6s | -295ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +655 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.018 | 5.917 | ⚠️ +2.9 |
| / avg req/sec | 828.44 | 422.54 | ⚠️ -405.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.254 | 1.883 | ⚠️ +0.63 |
| /error-in-render avg req/sec | 1993.86 | 1327.52 | ⚠️ -666.34 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.5 kB | 27.5 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 5.01 kB | 5.01 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.2s | -159ms |
| buildDurationCached | 5.8s | 5.5s | -286ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +655 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.96 | 3.058 | ⚠️ +0.1 |
| / avg req/sec | 844.64 | 817.61 | ⚠️ -27.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.243 | 1.204 | -0.04 |
| /error-in-render avg req/sec | 2011.22 | 2075.72 | +64.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.1 kB | 42.1 kB | ✓ |
| main-HASH.js gzip | 27.5 kB | 27.5 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-use-stream-with-react-root | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 692390988f797e9fc2704cb39c5428ab68d6e069

**Review by ijjk — APPROVED** [review]

**Review by huozhi — APPROVED** [review]

**Comment by gaearon** [comment]
I'm getting

```
TypeError: ReactDOMServer.renderToReadableStream is not a function
--
04:08:38.682 | at /vercel/path0/beta/node_modules/next/dist/server/render.js:1098:39
04:08:38.682 | at new Promise (<anonymous>)
04:08:38.682 | at renderToStream (/vercel/path0/beta/node_modules/next/dist/server/render.js:1079:12)
04:08:38.682 | at Object.bodyResult (/vercel/path0/beta/node_modules/next/dist/server/render.js:797:34)
04:08:38.682 | at renderToHTML (/vercel/path0/beta/node_modules/next/dist/server/render.js:935:30)
04:08:38.682 | at async /vercel/path0/beta/node_modules/next/dist/export/worker.js:275:36
04:08:38.682 | at async Span.traceAsyncFn (/vercel/path0/beta/node_modules/next/dist/trace/trace.js:75:20)
```

I'm a bit surprised by the code:

https://github.com/vercel/next.js/blob/f589fa2b609aa20d9feb684a5affa898baf295ef/packages/next/server/render.tsx#L1695

Isn't this supposed to be called `renderToPipeableStream`? That's what ReactDOMServer API is called:

https://github.com/facebook/react/blob/64223fed82414ee41839e95ebc97df330b2b71ca/packages/react-dom/server.node.js#L39-L44

**Comment by gaearon** [comment]
>We've decided to use just renderToReadableStream (the browser/Web Streams API) for both Node.js and the Edge runtime since ReadableStream is available (or polyfillable) on recent Node versions

Do you have concerns about this:

>In Node.js WritableStreams (and in many other platforms before it), there's a flush() method that React calls to force a signal to any GZIP middleware that it now has to flush its buffer even if it's not yet full. This doesn't exist on https://github.com/reactwg/react-18/discussions/66s and that's why we don't support ReadableStream. Web Streams primarily use ReadableStreams as the return value of things like responseWith. You can use WritableStreams (but not in Firefox). However, there's https://github.com/whatwg/streams/issues/960 even in a WritableStream. I'm sure there will be solution eventually. However, if you're trying to build a production server on top of WebStreams with compression support, you'll need to invent an API convention for this that we can add support for.

?

**Comment by devknoll** [comment]
Yes, that's why we would love to have a more generic stream interface :)

For now, we just buffer everything React writes during a macro task and manually flush() it at the start of the next one. Not great, but good enough for now.

**Comment by gaearon** [comment]
Hmm, canary.10 fixes the crash but the static build times out now:

https://vercel.com/fbopensource/beta-reactjs-org/E1KYDNrqyisLTfXRRtTGDJTfTVva

What can we check?

**Comment by gaearon** [comment]
Note the latest React now returns a Promise and onCompleteShell is gone.

https://github.com/facebook/react/pull/23247/files

But I'm running an older version so that shouldn't be the reason..

**Comment by devknoll** [comment]
Taking a look now

**Comment by gaearon** [comment]
12.0.10 worked for us but 12.1.0 hangs again. https://github.com/reactjs/reactjs.org/pull/4354

**Comment by devknoll** [comment]
@gaearon Sorry for the delay here. This should be fixed after this change in React: https://github.com/facebook/react/pull/23387

**Pull request merged**
