### PR TITLE
Fixed the example with-react-intl, cannot read property 'locale' of undefined

### PR DESCRIPTION
**Pull request by soulmachine**
In line 26 of `examples/with-react-intl/components/PageWithIntl.js`:

    const {locale, messages} = req || window.__NEXT_DATA__.props.initialProps

Actuall the field `initialProps` doesn't exist, instead, `locale` and `messages` are in `window.__NEXT_DATA__.props`, so the solution is quite simple, just remove `initialProps`:

    const {locale, messages} = req || window.__NEXT_DATA__.props

## My Environment

| Tech    | Version |
|---------|---------|
| next    |   4.1.4  |
| node    |   v8.9.1      |
| OS      |   macOS High Sierra      |
| browser |    Chrome Version 62.0.3202.94 (Official Build) (64-bit)    |

### CODE REVIEW

**Comment by ptomasroos** [comment]
I find this quite strange, do you run dev or production build since I actually added it in there in order to get it work in production mode. Just curious. I dont mind the change in anyway!

**Comment by soulmachine** [comment]
@ptomasroos Yeah,  I see your commit here <https://github.com/zeit/next.js/commit/629d0a261b2957daaf72bbb5ef308d5d81366cc0> that specifically adds `initialProps`.

But I tried to run the example  a few times, still the same error.

* `npm run build` then `npm run start`, go to <http://localhost:3000> and click either link, will get an error `An unexpected error has occurred.` and the console throws out red error `TypeError: Cannot read property 'locale' of undefined`

* `npm run dev`, go to <http://localhost:3000> and click either link then the page will crash with stack trace.

**Comment by julmot** [comment]
What's the status here?

**Comment by timneutkens** [comment]
Thanks @soulmachine

**Comment by soulmachine** [comment]
@timneutkens No problem

**Comment by FrencisAlreadyInUse** [comment]
It should be ⬇️ for now. 
`const {locale, messages} = req || window.__NEXT_DATA__.props.pageProps`

**Pull request merged**
