### PR TITLE
fix(build-log): clarify static Route Handler behavior

### LINKED ISSUE #59208: Missing console logs in api routes in production mode
### Link to the code that reproduces this issue

https://github.com/rawi96/missing-console-logs-in-api-routes

### To Reproduce

1. create a  new Next App with `npx create-next-app@latest`
2. Create a new api route in `/src/app/api/test/route.ts`
3. Add this Code to the route.ts

```
export async function GET() {
  console.log(
    "I can see this log ONLY in development mode, not in production mode"
  );
  console.error(
    "I can see this error ONLY in development mode, not in production mode"
  );

  return Response.json({ message: "Hello Next JS" });
}
```
4. npm run build
5. npm start
6. Go to localhost:3000/api/test
7. You can see "Hello Next JS" but there are NO logs in the terminal
8. When I start the app with `npm run dev` I can see the logs

How can I see the console logs in my production env?
(I need this because I have an issue which only appears in prod mode.)

### Current vs. Expected behavior

Current behaviour:
- I can not see any logs in the api route in production mode. Only in the dev mode

Expected behaviour:
- See all logs in prod and dev mode

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: N/A
  pnpm: 7.0.0
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by balazsorban44**
### What?

Clarify the log messages what happens when a `GET` Route Handler is statically pre-rendered

### Why?

`GET` Route Handlers that do not call dynamic functions are [cached by default](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#caching) and their result won't change during runtime (the method's output is saved and served back from cache, so for example `console.log` will only show up during build.)

### How?

Introducing a new category, similar to the existing `○   (Static)` legend type.

`◎` will get its description, with a link to the [relevant documentation](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching).

Example output:
```
Route (app)                              Size     First Load JS
┌ ○ /                                    5.02 kB        89.7 kB
├ ○ /_not-found                          864 B          85.5 kB
└ ◎ /foo                                 0 B                0 B
+ First Load JS shared by all            84.6 kB
  ├ chunks/main-app-631469d1fde5cd2d.js  83 kB
  └ other shared chunks (total)          1.64 kB


○   (Static)  Prerendered as static content
◎   (Static)  Route Handler without dynamic API usage. Won't be re-evaluated at runtime.
              Read more: https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching
```

---

**Note**: I tried `○*` as an alternative symbol, but that shifts the `/foo` path as such:

```
├ ○ /_not-found                          864 B          85.5 kB
└ ○* /foo                                0 B                0 B
```

which would require additional logic to append an extra ` ` between every other symbol <-> path when this category is present, making the path positions variable. (This could for example be an issue if somebody relies on the format of our build logs)

- Additionally, renamed the internal `isAppRouteRoute` to `isRouteHandler` for clarity. (`Route` is the name of the primitive for both Route Handlers and pages inside the App Router. This should make it a bit clearer what this function asserts.)

- Also capitalized the legend descriptions, to be consistent, as most of the text is capitalized elsewhere too.

Closes NEXT-2368
Closes #59208

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a004f5a2e67ebeca857219b769ecc3d832c650e9

`pnpm test-start test/production/app-dir/build-output/index.test.ts`
- production - app dir - build output > should match the expected output format

<details>
<summary>Expand output</summary>

  ● production - app dir - build output › should match the expected output format

    expect(received).toContain(expected) // indexOf

    Expected substring: "○  (Static)  prerendered as static content"
    Received string:    "yarn run v1.22.19
    $ /tmp/next-install-cd381585cd683f305fe962f0c185482060b2c0131681e71e69f6badd79c15880/node_modules/.bin/next build
       ▲ Next.js 14.1.1-canary.54·
       Creating an optimized production build ...
     ✓ Compiled successfully
       Linting and checking validity of types ...·
       We detected TypeScript in your project and created a tsconfig.json file for you.
       Collecting page data ...
       Generating static pages (0/4) ...·
       Generating static pages (1/4)···
       Generating static pages (2/4)···
       Generating static pages (3/4)···
     ✓ Generating static pages (4/4)·
       Finalizing page optimization ...
       Collecting build traces ...·
    Route (app)                              Size     First Load JS
    ┌ ○ /                                    141 B          85.7 kB
    └ ○ /_not-found                          873 B          86.5 kB
    + First Load JS shared by all            85.6 kB
      ├ chunks/12ae0fd1-409658194299d522.js  53.5 kB
      ├ chunks/430-41e9d2a01968a276.js       30.2 kB
      └ other shared chunks (total)          1.83 kB··
    ○  (Static)  Prerendered as static content·
    Done in 14.66s.
    yarn run v1.22.19
    $ /tmp/next-install-cd381585cd683f305fe962f0c185482060b2c0131681e71e69f6badd79c15880/node_modules/.bin/next start
       ▲ Next.js 14.1.1-canary.54
       - Local:        http://localhost:45041·
    "

      45 |
      46 |       // output type
    > 47 |       expect(output).toContain('○  (Static)  prerendered as static content')
         |                      ^
      48 |     })
      49 |   }
      50 | )

      at Object.toContain (production/app-dir/build-output/index.test.ts:47:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| buildDuration | 19.9s | 19.8s | N/A |
| buildDurationCached | 8.5s | 6.7s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +2.91 kB |
| nextStartRea..uration (ms) | 424ms | 426ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.2 kB | 30.2 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.4 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.4 kB | 44.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | ✓ |
| app-page-tur..prod.js gzip | 97.3 kB | 97.3 kB | ✓ |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 50 kB | 50 kB | ✓ |
| Overall change | 925 kB | 925 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/clarify-static-route-handler | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | N/A |
| index.pack gzip | 104 kB | 104 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: d5fcb751462039828b25fb9d29b7b8414cc42399

**Comment by BoreasMun** [comment]
what happened to this PR? All checks passed, can someone resolve merge conflicts?

**Comment by balazsorban44** [comment]
We decided to pursue a different resolution to this problem. Will revisit in the future!

**Pull request closed without merging**
