### PR TITLE
fix(types): allow other attributes on script component

### LINKED ISSUE #26236: Custom attributes like `repo` on Next/Script for using Utterances gives TypeScript error
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.1.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I am using Utterances → https://utteranc.es/ to display comments on my blog & thought of using the new `Script` tag as follows:

```tsx
import Head from 'next/head'
import Script from 'next/script'

export const Comments = () => {
	return (
		<Head>
			<Script
				src="https://utteranc.es/client.js"
				strategy="lazyOnload"
				repo="deadcoder0904/comments.akshaykadam.com"
				issue-term="pathname"
				theme="photon-dark"
				crossorigin="anonymous"
			/>
		</Head>
	)
}
```

I plan to include this `Comments` component under my blog post but it gives **red-squiggly lines** on `repo`.

Idk how to use `Script` tag but the above code seems okay.

The TS error I get in VSCode is:

> Type '{ src: string; strategy: "lazyOnload"; repo: string; "issue-term": string; theme: string; crossorigin: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'repo' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)

How do I get it working?

### Expected Behavior

It should work.

### To Reproduce

Just try pasting the above code in a Next.js app :)

### PR DESCRIPTION
**Pull request by advaiyalad**
This allows for other attributes on the script component (as the docs say) to exist.

NOTE: This is my first PR, so I hope I didn't do anything wrong in the contrib process... I didn't add integration tests, because this is a types-only change, but could add one if required (I would need help though).

fixes #26236

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added

### CODE REVIEW

**Comment by deadcoder0904** [comment]
Thank you. Looks good to me!

**Comment by deadcoder0904** [comment]
This one can be merged :)

**Review by styfle — COMMENTED** [review]
The current `<script>` and `<Script>` have the same properties due to the `extends ScriptHTMLAttributes` here.

So if you were setting unknown props on `<script>` you would get the same TS error as `<Script>`.

Similarly, this is the same error you would get for `<Image>` with unknown props.

If for some reason there are props missing, its best to get this changed upstream in the `ScriptHTMLAttributes` interface via `@types/react`

**Comment by deadcoder0904** [comment]
@styfle So is there no fix to this? I am assuming what you are saying essentially doesn't allow me to use the custom attributes on `Script` tag that Utterances needs to use.

Any way to work around that as I feel this isn't going to be merged? Or do I need to send a PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/940da08892fbe5eb07b964ffeb3c1276f7ed5c6a/types/react/index.d.ts#L2325-L2337) but don't know if it'll be accepted either?

**Comment by styfle** [comment]
Yep, DefinitelyTyped is the correct repo 👍

**Comment by deadcoder0904** [comment]
Confused 🤔 

Do I send this PR there?

**Comment by styfle** [comment]
Yes if there is a prop missing from the `<script>` types but are available in the DOM, you can add it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

If you want to define custom types, you can extend the internal Next.js type

```ts
declare module "next/script" {
  interface Props {
    someNewProp?: string
  }
}
```

Although now that I see this, we need to fix the interface name in PR #26990 so it will become:

```ts
declare module "next/script" {
  interface ScriptProps {
    someNewProp?: string
  }
}
```

**Pull request closed without merging**
