### PR TITLE
Fix: Build time error for with-mysql example #19635

### LINKED ISSUE #19635: Example with-mysql build bug
# Bug report

## Describe the bug

I was trying out this new example from `examples/with-mysql` works fine locally but when I try to build it using `yarn build` it throws a build time error.

Its related to this: https://github.com/vercel/next.js/pull/19452

Link to the example: https://github.com/vercel/next.js/tree/canary/examples/with-mysql

## To Reproduce

1. `yarn build`

## Expected behavior
Build to succeed eg.
```
yarn build
yarn run v1.22.5
$ next build
Loaded env from D:\dev-stuff\next.js\examples\with-mysql\.env.local
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (5/5)
info  - Finalizing page optimization
...
```

## Screenshots

image

```
$ yarn build
yarn run v1.22.5
$ next build
Loaded env from D:\dev-stuff\next.js\examples\with-mysql\.env.local
Failed to compile.

./pages/api\get-entry.ts:10:25
Type error: Argument of type 'string | string[]' is not assignable to parameter
of type 'string'.
  Type 'string[]' is not assignable to type 'string'.

   8 |       return res.status(400).json({ message: '`id` required' })
   9 |     }
> 10 |     if (typeof parseInt(id) !== 'number') {
     |                         ^
  11 |       return res.status(400).json({ message: '`id` must be a number' })
  12 |     }
  13 |     const results = await query(
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

```

## System information

- OS: Windows 10
- Browser: Chrome 86.0.4240.198 (Official Build) (64-bit)
- Version of Next.js: 10.17.0
- Deployment: yarn build

### PR DESCRIPTION
**Pull request by farhankk360**
Closes #19635

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.6s | ⚠️ +192ms |
| nodeModulesSize | 85 MB | 85 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.457 | 2.52 | ⚠️ +0.06 |
| / avg req/sec | 1017.65 | 991.87 | ⚠️ -25.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.566 | 1.586 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1596.47 | 1576.59 | ⚠️ -19.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-90b3d5a..55ad.js gzip | 6.54 kB | 6.54 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12s | ⚠️ +268ms |
| nodeModulesSize | 85 MB | 85 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-90b3d5a..55ad.js gzip | 6.54 kB | 6.54 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | farhankk360/next.js examples-with-mysql-build-fix | Change |
| - | - | - | - |
| _error.js | 996 kB | 996 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 996 kB | 996 kB | ✓ |
| link.js | 1.05 MB | 1.05 MB | ✓ |
| routerDirect.js | 1.04 MB | 1.04 MB | ✓ |
| withRouter.js | 1.04 MB | 1.04 MB | ✓ |
| Overall change | 5.13 MB | 5.13 MB | ✓ |

</details>

</details>
Commit: b1104c3eac691936f981693b4c5d72e1295ad6a0

**Comment by gelbartj** [comment]
Is coercing the input to string the best way to handle this, or would it be better to use `if (Array.isArray(id) || typeof parseInt(id) !== 'number') { /* error */ }` if only one number is the desired input?

**Comment by farhankk360** [comment]
@gelbartj Correct.
I was keeping it consistent with the rest of the code, eg if you look into `delete-entry.ts`:
```
    if (typeof parseInt(id.toString()) !== 'number') {
      return res.status(400).json({ message: '`id` must be a number' })
    }
```

**Review by Timer — APPROVED** [review]
Seems good. Thanks!

**Pull request merged**
