### PR TITLE
Fix edge case in fetch polyfill

### LINKED ISSUE #12794: Build error occurred: fetch is not found globally and no fetcher passed
I was reading through the Next.js 9.4 changelog and noticed "[Improved Built-in Fetch Support](https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support)". So I got rid of my `isomorphic-unfetch` package but now I can't build anymore as `apollo-link-http` complains about fetch missing.

```ts
const httpLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_API_URL,
});
```

```
> Build error occurred
Invariant Violation: 
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';
```

In dev mode this works (fetch is not imported, using built-in one):
```ts
const httpLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_API_URL,
  fetch,
});
```

But during building I end up with the following error:
```
> Build error occurred
ReferenceError: fetch is not defined
    at NetworkService.createApolloClient
```

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #12794

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| buildDuration | 12s | 11.7s | -355ms |
| nodeModulesSize | 58.7 MB | 58.7 MB | ⚠️ +210 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.917 | 1.882 | -0.04 |
| / avg req/sec | 1304.11 | 1328.5 | ⚠️ +24.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.191 | 1.136 | -0.06 |
| /error-in-render avg req/sec | 2099.38 | 2201.06 | ⚠️ +101.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.29 kB | 3.29 kB | ✓ |
| hooks.js gzip | 880 B | 880 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 280 B | 280 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.module.js gzip | 599 B | 599 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 279 B | 279 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.37 kB | 5.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.3s | -244ms |
| nodeModulesSize | 58.7 MB | 58.7 MB | ⚠️ +210 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.29 kB | 3.29 kB | ✓ |
| hooks.js gzip | 880 B | 880 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 280 B | 280 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.module.js gzip | 599 B | 599 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 279 B | 279 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.37 kB | 5.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _error.js | 850 kB | 850 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 851 kB | 851 kB | ✓ |
| link.js | 888 kB | 888 kB | ✓ |
| routerDirect.js | 880 kB | 880 kB | ✓ |
| withRouter.js | 880 kB | 880 kB | ✓ |
| Overall change | 4.36 MB | 4.36 MB | ✓ |

</details>

</details>

**Review by wouterds — APPROVED** [review]
🚀

**Comment by tusbar** [comment]
I was about to create almost exactly this PR. :tada:

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/fetch-polyfill/test/index.test.js** 
- Fetch polyfill > Server support > includes polyfilled fetch when using getStaticPaths
- Fetch polyfill > Serverless support > includes polyfilled fetch when using getStaticPaths
- Fetch polyfill > dev support > includes polyfilled fetch when using getStaticPaths

<details>
<summary>Expand output</summary>

  ● Fetch polyfill › dev support › includes polyfilled fetch when using getStaticPaths

    expect(received).toBe(expected) // Object.is equality

    Expected: "a"
    Received: {"0": {"attribs": {"id": "username"}, "children": [{"data": "a", "next": null, "parent": [Circular], "prev": null, "type": "text"}], "name": "div", "next": null, "parent": {"attribs": {"id": "__next"}, "children": [[Circular]], "name": "div", "next": {"attribs": {"src": "/_next/static/runtime/react-refresh.js?ts=1589365046342"}, "children": [], "name": "script", "next": {"attribs": [Object], "children": [Array], "name": "script", "next": [Object], "parent": [Object], "prev": [Circular], "type": "script"}, "parent": {"attribs": [Object], "children": [Array], "name": "body", "next": null, "parent": [Object], "prev": [Object], "type": "tag"}, "prev": [Circular], "type": "script"}, "parent": {"attribs": {}, "children": [[Circular], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]], "name": "body", "next": null, "parent": {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Object], "type": "tag"}, "prev": {"attribs": [Object], "children": [Array], "name": "head", "next": [Circular], "parent": [Object], "prev": null, "type": "tag"}, "type": "tag"}, "prev": null, "type": "tag"}, "prev": null, "type": "tag"}, "_root": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}, "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}, "prevObject": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}}

      86 |     const htmlA = await renderViaHTTP(appPort, '/user/a')
      87 |     const $a = cheerio.load(htmlA)
    > 88 |     expect($a('#username')).toBe('a')
         |                             ^
      89 | 
      90 |     const htmlB = await renderViaHTTP(appPort, '/user/b')
      91 |     const $b = cheerio.load(htmlB)

      at Object.<anonymous> (integration/fetch-polyfill/test/index.test.js:88:29)

  ● Fetch polyfill › Server support › includes polyfilled fetch when using getStaticPaths

    expect(received).toBe(expected) // Object.is equality

    Expected: "a"
    Received: {"0": {"attribs": {"id": "username"}, "children": [{"data": "a", "next": null, "parent": [Circular], "prev": null, "type": "text"}], "name": "div", "next": null, "parent": {"attribs": {"id": "__next"}, "children": [[Circular]], "name": "div", "next": {"attribs": {"id": "__NEXT_DATA__", "type": "application/json"}, "children": [[Object]], "name": "script", "next": {"attribs": [Object], "children": [Array], "name": "script", "next": [Object], "parent": [Object], "prev": [Circular], "type": "script"}, "parent": {"attribs": [Object], "children": [Array], "name": "body", "next": null, "parent": [Object], "prev": [Object], "type": "tag"}, "prev": [Circular], "type": "script"}, "parent": {"attribs": {}, "children": [[Circular], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]], "name": "body", "next": null, "parent": {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Object], "type": "tag"}, "prev": {"attribs": [Object], "children": [Array], "name": "head", "next": [Circular], "parent": [Object], "prev": null, "type": "tag"}, "type": "tag"}, "prev": null, "type": "tag"}, "prev": null, "type": "tag"}, "_root": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}, "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}, "prevObject": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}}

      86 |     const htmlA = await renderViaHTTP(appPort, '/user/a')
      87 |     const $a = cheerio.load(htmlA)
    > 88 |     expect($a('#username')).toBe('a')
         |                             ^
      89 | 
      90 |     const htmlB = await renderViaHTTP(appPort, '/user/b')
      91 |     const $b = cheerio.load(htmlB)

      at Object.<anonymous> (integration/fetch-polyfill/test/index.test.js:88:29)

  ● Fetch polyfill › Serverless support › includes polyfilled fetch when using getStaticPaths

    expect(received).toBe(expected) // Object.is equality

    Expected: "a"
    Received: {"0": {"attribs": {"id": "username"}, "children": [{"data": "a", "next": null, "parent": [Circular], "prev": null, "type": "text"}], "name": "div", "next": null, "parent": {"attribs": {"id": "__next"}, "children": [[Circular]], "name": "div", "next": {"attribs": {"id": "__NEXT_DATA__", "type": "application/json"}, "children": [[Object]], "name": "script", "next": {"attribs": [Object], "children": [Array], "name": "script", "next": [Object], "parent": [Object], "prev": [Circular], "type": "script"}, "parent": {"attribs": [Object], "children": [Array], "name": "body", "next": null, "parent": [Object], "prev": [Object], "type": "tag"}, "prev": [Circular], "type": "script"}, "parent": {"attribs": {}, "children": [[Circular], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]], "name": "body", "next": null, "parent": {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Object], "type": "tag"}, "prev": {"attribs": [Object], "children": [Array], "name": "head", "next": [Circular], "parent": [Object], "prev": null, "type": "tag"}, "type": "tag"}, "prev": null, "type": "tag"}, "prev": null, "type": "tag"}, "_root": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}, "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}, "prevObject": {"0": {"attribs": {}, "children": [{"data": "!DOCTYPE html", "name": "!doctype", "next": [Object], "parent": null, "prev": null, "root": [Circular], "type": "directive"}, {"attribs": [Object], "children": [Array], "name": "html", "next": null, "parent": null, "prev": [Object], "root": [Circular], "type": "tag"}], "name": "root", "next": null, "parent": null, "prev": null, "type": "root"}, "_root": [Circular], "length": 1, "options": {"decodeEntities": true, "normalizeWhitespace": false, "withDomLvl1": true, "xmlMode": false}}}

      86 |     const htmlA = await renderViaHTTP(appPort, '/user/a')
      87 |     const $a = cheerio.load(htmlA)
    > 88 |     expect($a('#username')).toBe('a')
         |                             ^
      89 | 
      90 |     const htmlB = await renderViaHTTP(appPort, '/user/b')
      91 |     const $b = cheerio.load(htmlB)

      at Object.<anonymous> (integration/fetch-polyfill/test/index.test.js:88:29)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.9s | ⚠️ +285ms |
| nodeModulesSize | 58.7 MB | 58.7 MB | ⚠️ +210 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.078 | 2.029 | -0.05 |
| / avg req/sec | 1203.08 | 1232.24 | ⚠️ +29.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.307 | 1.32 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1912.18 | 1893.89 | -18.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.29 kB | 3.29 kB | ✓ |
| hooks.js gzip | 880 B | 880 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 280 B | 280 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.module.js gzip | 599 B | 599 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 279 B | 279 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.37 kB | 5.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.7s | ⚠️ +203ms |
| nodeModulesSize | 58.7 MB | 58.7 MB | ⚠️ +210 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.29 kB | 3.29 kB | ✓ |
| hooks.js gzip | 880 B | 880 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 280 B | 280 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _app.module.js gzip | 599 B | 599 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 279 B | 279 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.37 kB | 5.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | timneutkens/next.js add/getstaticprops-fetch-test | Change |
| - | - | - | - |
| _error.js | 850 kB | 850 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 851 kB | 851 kB | ✓ |
| link.js | 888 kB | 888 kB | ✓ |
| routerDirect.js | 880 kB | 880 kB | ✓ |
| withRouter.js | 880 kB | 880 kB | ✓ |
| Overall change | 4.36 MB | 4.36 MB | ✓ |

</details>

</details>

**Pull request merged**
