### PR TITLE
Fix express paths in custom-server-express

### PR DESCRIPTION
**Pull request by Hurtak**

### CODE REVIEW

**Comment by lfades** [comment]
The example is trying to illustrate how a page `/a` can render the `/b` and viceversa using a custom server and links, like here too: https://github.com/zeit/next.js/blob/canary/examples/custom-server-express/pages/index.js

**Comment by timneutkens** [comment]
💯 explanation @lfades maybe you could send a PR with a comment explaining this really is the expected behaviour 🙏

**Comment by Hurtak** [comment]
Ah I see, maybe the best place to explain that information would be right inside the html? Sometimes I use the examples folder as boilerplate projects so I do not have to setup the project manually and this confused me.

**Comment by timneutkens** [comment]
Yeah it should be added as comment in the server file 👍

**Pull request closed without merging**
