### PR TITLE
pass old route to onRouteChangeStart

### PR DESCRIPTION
**Pull request by Msea**
Added the previous url as a second parameter to the onRouteChangeStart hook, so that you can specify behavior based on which page you are coming from as well as which page you are going to.

### CODE REVIEW

**Comment by timneutkens** [comment]
What's the proper use case for this? 🤔 I can't think of one right now.

**Comment by Msea** [comment]
My use case is that there are some things I want to do to cleanup my route on navigate away. Ordinarily I'd use componentWillUnmount for that, but that doesn't trigger when server side rendering.

I am hoping to use onRouteChangeStart in the event that 1. I am server side rendering and 2. I navigate away using the next.js router. However, I only need to do cleanup for one of my application routes. Having access to the route we're coming from, enables me to specify what cleanup to do when.

**Comment by timneutkens** [comment]
Router events are not emitted at all when doing server-side rendering though, they're only emitted on client navigation, and with client navigation `componentWillUnmount` does work. So this feature is not needed based on what you're saying 🤔

**Comment by Msea** [comment]
O damn my bad. Thank you. I suppose you can delete this then.

**Pull request closed without merging**
