### PR TITLE
Improve the transform and re-enable optimizeServerReact 

### PR DESCRIPTION
**Pull request by huozhi**
### What

Revert the temporary disabling of #69788, use a different transform that using an process env variable as condition to `&&` with react hooks in SSR layer, and remove drop the call by DCE during minification phase.

Introduce a new internal env `process.env.__NEXT_PRIVATE_MINIMIZE_MARCO_FALSE` as a condition in the SWC transform of `optimizeServerReact` and then it will be replaced as `false` in minification, minifier can identify it as a condition that able to be dropped. The react hook call after it will also get dropped. This is similar to the swc transform erasing but just a bit late : )

### Why

We originally disable the config in #69788 because react actions are dropped too early along with the react hooks useEffect on server side transform. Since we still need to go through the module graph to collect action modules and imported exports, they still need to be present but we can still remove them later.

#### Solution Evaluation Phases

During compilation phase, most simple env replacement and literals can be optimized by SWC (compiler) and webpack (bundler). Using anything like numbers (`1`, `0`), booleans or `process.env.NODE_ENV` will get early optimized.

```js
process.env.NODE_ENV !== 'production' && useEffect(() => { ... })
```

Will be instantly transpiled to `false` during bundling as the optimization can be applied before the module graph is created.

Hence I switched to a new transform below, ensure that `useEffect` and its callback body are still presented while gathering modules.

```js
process.env.__NEXT_PRIVATE_MINIMIZE_MARCO_FALSE && useEffect(() => { ... })
```

Then minifier will replace the env var as `false`, also drop the following hook call with DCE.

### CODE REVIEW

**Comment by huozhi** [comment]
* **#70101** <a href="https://app.graphite.dev/github/pr/vercel/next.js/70101?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @huozhi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8d764fac224239ef255d1622dab02a9443c362de

`TURBOPACK=1 pnpm test test/integration/export-default-map/test/index.test.js` (turbopack)
- Export with default map > production mode > should export with folder that has dot in name
- Export with default map > production mode > should export an amp only page to clean path
- Export with default map > production mode > should export hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly with folder
- Export with default map > production mode > should export hybrid index amp page correctly

<details>
<summary>Expand output</summary>

  ● Export with default map › production mode › should export with folder that has dot in name

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export an amp only page to clean path

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly with folder

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid index amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
      ▲ Next.js 15.0.0-canary.155 (turbo)
      - Experiments (use with caution):
        · amp

       Checking validity of types ...
       Creating an optimized production build ...
       Building (0/8) ...
       Building (2/8) 
       Building (4/8) 
       Building (6/8) 
     ✓ Building (8/8)
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 

    Error occurred prerendering page "/docs". Read more: https://nextjs.org/docs/messages/prerender-error

    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:103:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:104:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:105:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2245:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:17:2057)
      at validateAmp (../packages/next/dist/export/routes/pages.js:89:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:123:17)
      at async exportPageImpl (../packages/next/dist/export/worker.js:202:16)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:157:20)
      Failed to build /docs after 1 attempts.
      > Build error occurred
      Error: Export encountered an error on /docs, exiting the build.
      at exportPageWithRetry (../packages/next/dist/export/worker.js:291:31)
          at async Promise.all (index 4)
      at async Object.exportPages (../packages/next/dist/export/worker.js:315:31) {
        type: 'ExportPageError',
        code: 'NEXT_EXPORT_PAGE_ERROR'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| buildDuration | 17.2s | 15.9s | N/A |
| buildDurationCached | 8.5s | 7.3s | N/A |
| nodeModulesSize | 358 MB | 358 MB | N/A |
| nextStartRea..uration (ms) | 426ms | 433ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| 6784.HASH.js gzip | 169 B | 168 B | N/A |
| 69c16c59-HASH.js gzip | 52.8 kB | 52.8 kB | N/A |
| 8954-HASH.js gzip | 42.5 kB | 42.5 kB | N/A |
| 8966-HASH.js gzip | 5.26 kB | 5.25 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 225 B | 223 B | N/A |
| main-HASH.js gzip | 32.6 kB | 32.6 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 512 B | 512 B | ✓ |
| css-HASH.js gzip | 343 B | 343 B | ✓ |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 266 B | N/A |
| head-HASH.js gzip | 365 B | 365 B | ✓ |
| hooks-HASH.js gzip | 391 B | 391 B | ✓ |
| image-HASH.js gzip | 4.4 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.81 kB | 2.81 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 396 B | N/A |
| withRouter-HASH.js gzip | 322 B | 324 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 4.54 kB | 4.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 750 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| index.html gzip | 523 B | 522 B | N/A |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 518 B | 519 B | N/A |
| Overall change | 537 B | 537 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 180 kB | 179 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 669 B | 671 B | N/A |
| middleware-r..fest.js gzip | 156 B | 157 B | N/A |
| middleware.js gzip | 29.8 kB | 29.8 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 317 kB | 317 kB | ✓ |
| app-page-exp..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-page-tur..prod.js gzip | 139 kB | 139 kB | ✓ |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | ✓ |
| app-page.run...dev.js gzip | 308 kB | 308 kB | ✓ |
| app-page.run..prod.js gzip | 121 kB | 121 kB | ✓ |
| app-route-ex...dev.js gzip | 31.3 kB | 31.3 kB | ✓ |
| app-route-ex..prod.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route-tu..prod.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route-tu..prod.js gzip | 21 kB | 21 kB | ✓ |
| app-route.ru...dev.js gzip | 32.9 kB | 32.9 kB | ✓ |
| app-route.ru..prod.js gzip | 21 kB | 21 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.62 kB | 9.62 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.5 kB | 11.5 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 20.8 kB | 20.8 kB | ✓ |
| pages.runtim...dev.js gzip | 26.4 kB | 26.4 kB | ✓ |
| pages.runtim..prod.js gzip | 20.8 kB | 20.8 kB | ✓ |
| server.runti..prod.js gzip | 57.7 kB | 57.7 kB | ✓ |
| Overall change | 1.45 MB | 1.45 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 09-14-transform_object_server_react | Change |
| - | - | - | - |
| 0.pack gzip | 1.65 MB | 1.65 MB | N/A |
| index.pack gzip | 131 kB | 131 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [8358],
   {
-    /***/ 8696: /***/ (
+    /***/ 2121: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(4129);
+          return __webpack_require__(2990);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 4979: /***/ (module, exports, __webpack_require__) => {
+    /***/ 2994: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,17 +40,17 @@
         __webpack_require__(6663)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(9845)
+        __webpack_require__(3411)
       );
-      const _getimgprops = __webpack_require__(5864);
-      const _imageconfig = __webpack_require__(947);
-      const _imageconfigcontextsharedruntime = __webpack_require__(5048);
-      const _warnonce = __webpack_require__(1022);
-      const _routercontextsharedruntime = __webpack_require__(8261);
+      const _getimgprops = __webpack_require__(7181);
+      const _imageconfig = __webpack_require__(7872);
+      const _imageconfigcontextsharedruntime = __webpack_require__(3853);
+      const _warnonce = __webpack_require__(4374);
+      const _routercontextsharedruntime = __webpack_require__(5198);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1914)
+        __webpack_require__(3470)
       );
-      const _usemergedref = __webpack_require__(7856);
+      const _usemergedref = __webpack_require__(6612);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
@@ -371,7 +371,7 @@
       /***/
     },
 
-    /***/ 7856: /***/ (module, exports, __webpack_require__) => {
+    /***/ 6612: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -440,7 +440,7 @@
       /***/
     },
 
-    /***/ 5864: /***/ (
+    /***/ 7181: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -456,9 +456,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(1022);
-      const _imageblursvg = __webpack_require__(1009);
-      const _imageconfig = __webpack_require__(947);
+      const _warnonce = __webpack_require__(4374);
+      const _imageblursvg = __webpack_require__(3452);
+      const _imageconfig = __webpack_require__(7872);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -830,7 +830,7 @@
       /***/
     },
 
-    /***/ 1009: /***/ (__unused_webpack_module, exports) => {
+    /***/ 3452: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -885,7 +885,7 @@
       /***/
     },
 
-    /***/ 8900: /***/ (
+    /***/ 4150: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -912,10 +912,10 @@
         },
       });
       const _interop_require_default = __webpack_require__(9608);
-      const _getimgprops = __webpack_require__(5864);
-      const _imagecomponent = __webpack_require__(4979);
+      const _getimgprops = __webpack_require__(7181);
+      const _imagecomponent = __webpack_require__(2994);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1914)
+        __webpack_require__(3470)
       );
       function getImageProps(imgProps) {
         const { props } = (0, _getimgprops.getImgProps)(imgProps, {
@@ -947,7 +947,7 @@
       /***/
     },
 
-    /***/ 1914: /***/ (__unused_webpack_module, exports) => {
+    /***/ 3470: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -982,7 +982,7 @@
       /***/
     },
 
-    /***/ 4129: /***/ (
+    /***/ 2990: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -999,8 +999,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@19.0.0-rc-206df66e-20240912/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(1143);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-206df66e-20240912_re_7unepphpsfbl5ofsayom3m6uma/node_modules/next/image.js
-      var next_image = __webpack_require__(5618);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-206df66e-20240912_re_mm6spwxwvmn7da4aknn66l2fta/node_modules/next/image.js
+      var next_image = __webpack_require__(4243);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ const nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -1030,12 +1030,12 @@
       /***/
     },
 
-    /***/ 5618: /***/ (
+    /***/ 4243: /***/ (
       module,
       __unused_webpack_exports,
       __webpack_require__
     ) => {
-      module.exports = __webpack_require__(8900);
+      module.exports = __webpack_require__(4150);
 
       /***/
     },
@@ -1045,7 +1045,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [2888, 9774, 179], () =>
-      __webpack_exec__(8696)
+      __webpack_exec__(2121)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>

</details>

</details>
Commit: 8d764fac224239ef255d1622dab02a9443c362de

**Review by shuding — APPROVED** [review]
LGTM! Can we find a better name for the env that's more explicit?

**Review by kdy1 — APPROVED** [review]
Same 👍

**Comment by huozhi** [comment]
renamed to `__NEXT_PRIVATE_MINIMIZE_MARCO_FALSE`
- `__NEXT` and `_PRIVATE` represents "internal"
- `MINIMIZE` represents which phase to replace
- `MARCO` for functionality
- `FALSE` for value

**Pull request merged**
