### PR TITLE
fix: clone response in first handler to prevent race (#70082)

### PR DESCRIPTION
**Pull request by ijjk**
This fixes a race where if the body was resolved before the clone operation, it would clone later, resulting in an error being thrown due to the body already being consumed.

backports #70082

### CODE REVIEW

**Review by ztanner — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| buildDuration | 16.5s | 15.1s | N/A |
| buildDurationCached | 7.8s | 7s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +12.8 kB |
| nextStartRea..uration (ms) | 406ms | 406ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| 1103-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| 1a9f679d-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 335-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| 7953.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 44.9 kB | 44.9 kB | ✓ |
| main-app-HASH.js gzip | 244 B | 244 B | ✓ |
| main-HASH.js gzip | 32.3 kB | 32.3 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 50.3 kB | 50.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 501 B | 506 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 1.82 kB | 1.82 kB | N/A |
| edge-ssr-HASH.js gzip | 259 B | 258 B | N/A |
| head-HASH.js gzip | 350 B | 352 B | N/A |
| hooks-HASH.js gzip | 372 B | 371 B | N/A |
| image-HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| index-HASH.js gzip | 259 B | 258 B | N/A |
| link-HASH.js gzip | 2.68 kB | 2.68 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 315 B | N/A |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 311 B | 310 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 4.9 kB | 4.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 542 B | 541 B | N/A |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 525 B | 525 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 658 B | 659 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 995 B | 995 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 98.1 kB | 98.1 kB | ✓ |
| app-page-tur..prod.js gzip | 99.8 kB | 99.8 kB | ✓ |
| app-page-tur..prod.js gzip | 94.1 kB | 94.1 kB | ✓ |
| app-page.run...dev.js gzip | 145 kB | 145 kB | ✓ |
| app-page.run..prod.js gzip | 92.6 kB | 92.6 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22.1 kB | N/A |
| app-route-ex..prod.js gzip | 15.5 kB | 15.5 kB | N/A |
| app-route-tu..prod.js gzip | 15.5 kB | 15.5 kB | N/A |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | N/A |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | N/A |
| app-route.ru..prod.js gzip | 15.2 kB | 15.2 kB | N/A |
| pages-api-tu..prod.js gzip | 9.58 kB | 9.58 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.85 kB | 9.85 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.57 kB | 9.57 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| pages.runtim..prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| server.runti..prod.js gzip | 51.5 kB | 51.5 kB | ✓ |
| Overall change | 850 kB | 850 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-fix-res-clone | Change |
| - | - | - | - |
| 0.pack gzip | 1.6 MB | 1.61 MB | ⚠️ +801 B |
| index.pack gzip | 113 kB | 114 kB | ⚠️ +868 B |
| Overall change | 1.72 MB | 1.72 MB | ⚠️ +1.67 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b9f6e3e468099e8230d2210f5a35a786380562bc

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b9f6e3e468099e8230d2210f5a35a786380562bc

`pnpm test-start test/e2e/app-dir/app-static/app-static-custom-handler.test.ts`
- app-dir static/dynamic handling > should not throw Dynamic Server Usage error when using generateStaticParams with draftMode
- app-dir static/dynamic handling > should not error with generateStaticParams and authed data on revalidate

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should not throw Dynamic Server Usage error when using generateStaticParams with draftMode

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#draft-mode')

      425 |     return this.chain(() => {
      426 |       return page
    > 427 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      428 |         .then(async (el) => {
      429 |           // it seems selenium waits longer and tests rely on this behavior
      430 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:427:10)

  ● app-dir static/dynamic handling › should not error with generateStaticParams and authed data on revalidate

    TIMED OUT: success

    undefined

    Error: expect(received).not.toBe(expected) // Object.is equality

    Expected: not "0.1370792810567638"

      663 |
      664 |   if (hardError) {
    > 665 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      666 |   }
      667 |   return false
      668 | }

      at check (lib/next-test-utils.ts:665:11)
      at Object.<anonymous> (e2e/app-dir/app-static/app-static.test.ts:2809:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9ad74fac87db6adbf3edd449f6700250b3d8e76a

`pnpm test-start test/e2e/app-dir/app-static/app-static-custom-handler.test.ts`
- app-dir static/dynamic handling > should not throw Dynamic Server Usage error when using generateStaticParams with draftMode
- app-dir static/dynamic handling > should not error with generateStaticParams and authed data on revalidate

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should not throw Dynamic Server Usage error when using generateStaticParams with draftMode

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#draft-mode')

      425 |     return this.chain(() => {
      426 |       return page
    > 427 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      428 |         .then(async (el) => {
      429 |           // it seems selenium waits longer and tests rely on this behavior
      430 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:427:10)

  ● app-dir static/dynamic handling › should not error with generateStaticParams and authed data on revalidate

    TIMED OUT: success

    undefined

    Error: expect(received).not.toBe(expected) // Object.is equality

    Expected: not "0.6688191570062674"

      663 |
      664 |   if (hardError) {
    > 665 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      666 |   }
      667 |   return false
      668 | }

      at check (lib/next-test-utils.ts:665:11)
      at Object.<anonymous> (e2e/app-dir/app-static/app-static.test.ts:2809:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by mogzol** [comment]
Still seeing the error even after this backport, running version 14.2.15

**Comment by mogzol** [comment]
Looking at where the error is happening, it looks like it is actually occurring on the `res.clone()` line above where these changes were made, line 738 in the diff

**Comment by ijjk** [comment]
Hi, could you share the error you're seeing on latest version?

**Comment by mattandre** [comment]
I am seeing the following error on v14.2.15
TypeError: Response.clone: Body has already been consumed.
  at webidl.errors.exception (node:internal/deps/undici/undici:3384:14)
  at _Response.clone (node:internal/deps/undici/undici:8883:31)
  at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:181023

**Comment by mogzol** [comment]
Yes, that's the same error I'm seeing:

```
TypeError: Response.clone: Body has already been consumed.
at webidl.errors.exception (node:internal/deps/undici/undici:3384:14)
at _Response.clone (node:internal/deps/undici/undici:8883:31)
at /app/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.79.4/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:181023
```

**Comment by zsoltiii** [comment]
As previous comments, we are still seeing the following error on v14.2.14 on Vercel
```
TypeError: Response.clone: Body has already been consumed.
    at i.errors.exception (/opt/rust/undici.js:1:198719)
    at lA.clone (/opt/rust/undici.js:39:21106)
    at /var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:181023
```

**Comment by ijjk** [comment]
Thanks for the additional information follow-up fix opened in https://github.com/vercel/next.js/pull/71115

**Pull request merged**
