### PR TITLE
Nonce support next third parties

### PR DESCRIPTION
**Pull request by naveen-bharathi**
### Adding a feature

- Implements a `nonce` prop in the `GoogleAnalytics` and `GoogleTagManager` components exported from `@next/third-parties` package

### What?

- Implements a `nonce` prop in the `GoogleAnalytics` and `GoogleTagManager` components

### Why?

Enabling Content-Security-Policy using nonces requires the nonce to be passed to the Script element. Ref: https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy#reading-the-nonce

Since the GoogleTagManager and GoogleAnalytics components exported from @next/third-parties package do not have a nonce part, using these Components with Content-Security-Policy using nonces becomes impossible as the script inside these components won't be loaded.

### How?

Adds a `nonce` prop to the `GoogleAnalytics` and `GoogleTagManager` components which passes it to the `Script` tag inside them

Fixes #65452

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1dfcf3e11a734cb0937e2e4ff6fa5e425df783df

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1dfcf3e11a734cb0937e2e4ff6fa5e425df783df

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1dfcf3e11a734cb0937e2e4ff6fa5e425df783df

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi this looks like a duplicate of https://github.com/vercel/next.js/pull/61820

**Comment by naveen-bharathi** [comment]
> Hi this looks like a duplicate of #61820

#61820 looks sufficient. Is there a specific reason it is still not merged? Is there something I could help with?

**Pull request closed without merging**
