### PR TITLE
Fix/upgrade examples with apivideo 22 sep 23

### PR DESCRIPTION
**Pull request by mayank1513**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e2f7ec66694ee780280b21dc2373787c656fe94e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e2f7ec66694ee780280b21dc2373787c656fe94e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e2f7ec66694ee780280b21dc2373787c656fe94e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by balazsorban44** [comment]
@mayank1513 I kindly ask you to batch up your PRs if they only include bumping example dependency versions. 🙏

**Pull request closed without merging**
