### PR TITLE
[Traces] Serialize trace info across workers to preserve .next/trace with webpackBuildWorker

### PR DESCRIPTION
**Pull request by mknichel**
This PR sets up the webpack build workers (`webpackBuildWorker: true`) to serialize debug trace information across the worker boundary so that it can appear in the final `.next/trace` file at the end of the build.

Currently, when `webpackBuildWorker` is turned on, all traces that appear under the webpack compilation are lost. After this PR, they will appear in the trace file just like when the workers are not enabled.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: fce6fe5eb8e630481e3a4b9a86745f0c1f617f36

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: fce6fe5eb8e630481e3a4b9a86745f0c1f617f36

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by khuezy** [comment]
Do you think this webpack fix would fix https://github.com/vercel/next.js/issues/57622?

**Comment by mknichel** [comment]
> Do you think this webpack fix would fix #57622?

@khuezy Unfortunately, I don't think so. This PR only affects the debug `.next/trace` file.

**Pull request closed without merging**
