### PR TITLE
Fix Improve "pages/ not found error"

### LINKED ISSUE #591: Improve "pages/ not found error"
Right now upon a quick look it kinda looks like success:

image

No need to start compilation, the server, etc, if that directory doesn't exist.

### PR DESCRIPTION
**Pull request by aranajhonny**
fixes #591 

It is not to start the compilation, the server, etc, if that directory `pages` does not exist.

### CODE REVIEW

**Comment by rauchg** [comment]
Screenshots please?

**Comment by aranajhonny** [comment]
captura de pantalla 2017-01-02 a las 13 58 13

**Comment by aranajhonny** [comment]
with pages directory. 
captura de pantalla 2017-01-02 a las 13 59 29

**Comment by rauchg** [comment]
Do you think it would look cool to introduce a `[ ERROR ]` message styled the same way as `[ DONE ]` ?

**Comment by aranajhonny** [comment]
if it would be a good idea because when you use npm, the error is ugly.
captura de pantalla 2017-01-02 a las 15 44 56

**Comment by aranajhonny** [comment]
@rauchg  if process.exit(0) result.

**Comment by rauchg** [comment]
`process.exit(1)` would be better right ?

**Comment by aranajhonny** [comment]
process.exit(1) it would be better but always will come out the error ugly above.

**Comment by rauchg** [comment]
Yeah, it's ugly but it's the right contract :(

**Comment by aranajhonny** [comment]
there is a library when it detects that type of error will drive the output in some nice way. ?

**Pull request merged**
