### PR TITLE
Adding passwordless demo using Passage

### PR DESCRIPTION
**Pull request by PassageNick**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm build && pnpm lint`
- [x] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

**Comment by guilhermefront** [comment]
@PassageNick can you run `pnpm lint-fix` on your example folder? Prettier wasn't applied on a few occasions there

**Comment by PassageNick** [comment]
Okay -- I think I have this right. Thanks for your consideration.

**Comment by PassageNick** [comment]
Apparently I do not --  grr.  Working on it...

**Comment by PassageNick** [comment]
@guilhermefront 

Sir -- I'm struggling with this.  Is there some documentation that I'm missing on how to properly set up my system to properly lint the code?

**Comment by JanKaifer** [comment]
running `pnpm lint-fix` should be enough

**Comment by PassageNick** [comment]
@JanKaifer  Thanks for jumping in....

I can't seem to get lint-fix running, and there doesn't appear to be any resource that is googlable to get it going. 

First, I get:

```
$ pnpm lint-fix
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'source-map-support'
```
So I install source-map-support

and then I get

```
$ pnpm lint-fix
Error: Module build failed: TypeError: /home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/lib/bin.js: Duplicate declaration "b" (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
```

at which point I am lost.  Google is zero help, alas.

**Comment by JanKaifer** [comment]
Have you ran pnpm install?

**Comment by PassageNick** [comment]
No -- I did that (which was quite a "shaving the yak" experience, I'm not a Python guy!) I get this when it runs:

PS C:\code\next.js\examples\auth-passage-passwordless> pnpm lint-fix
Error: Module build failed: TypeError: /home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/lib/bin.js: Duplicate declaration "b" (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
    at Scope.checkBlockScopedCollisions (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/scope/index.js:303:27)
    at Scope.registerBinding (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/scope/index.js:485:16)
    at Scope.registerDeclaration (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/scope/index.js:404:14)
    at Object.BlockScoped (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/scope/index.js:146:28)
    at Object.newFn (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:266:17)
    at NodePath._call (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:34:14)
    at NodePath.visit (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/home/gitlab-runner/builds/8a39c300/0/pr/lint-fix/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:139:18)
    at Object.<anonymous> (C:\code\next.js\examples\auth-passage-passwordless\node_modules\lint-fix\dist\bin.js:71:7)
    at __webpack_require__ (C:\code\next.js\examples\auth-passage-passwordless\node_modules\lint-fix\dist\bin.js:21:30)
    at C:\code\next.js\examples\auth-passage-passwordless\node_modules\lint-fix\dist\bin.js:64:18
    at Object.<anonymous> (C:\code\next.js\examples\auth-passage-passwordless\node_modules\lint-fix\dist\bin.js:67:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by PassageNick** [comment]
... and I am trying to do my due diligence here, but there is nothing on the web that I can find about getting this all set up properly. :-(

**Comment by PassageNick** [comment]
For what it's worth, I asked on StackOverflow...

https://stackoverflow.com/questions/75302503/running-pnpm-lint-fix-on-a-nextjs-repository

**Comment by leerob** [comment]
Hey there, thank you for this suggestion! We'd love to see this example as a community repository.

**Pull request closed without merging**
