### PR TITLE
820 firebase

### PR DESCRIPTION
**Pull request by captDaylight**
Using firebase on the client and server to authenticate users and save their auth token in sessions. Logged in users can post messages.

apr-18-2017 23-44-37

Ref #820

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Awesome!

**Comment by Ehesp** [comment]
@captDaylight @timneutkens I could be wrong here, but looking at the example it's doing an import of the client credentials from `firebaseCredentials.js`. This would also bundle up the serverCredentials, which you'd technically be able to find in the client bundle.

**Comment by captDaylight** [comment]
@Ehesp I think you're right, maybe it should be just import from two separate files.

**Comment by Ehesp** [comment]
Added a PR https://github.com/zeit/next.js/pull/1875 to address it

**Pull request merged**
