### PR TITLE
test: ability to use node debugger

### LINKED ISSUE #55862: Node inspector stopped working on v13.5.x
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/sweet-lumiere-xtd4sp

### To Reproduce

1. Start the application with `NODE_OPTIONS='--inspect' next dev`

### Current vs. Expected behavior

Current behaviour:
Next attempts to start inspector processes on the same port for app/pages
```
Debugger listening on ws://127.0.0.1:9229/ad4c68d8-17a0-4a19-8eef-xxxxxxxx
For help, see: https://nodejs.org/en/docs/inspector
Starting inspector on 127.0.0.1:9229 failed: address already in use
   the --inspect option was detected, the Next.js router server should be inspected at port 9229.
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

Expected behaviour:
```
Debugger listening on ws://127.0.0.1:9229/289f58ca-1415-44d8-ba9d-xxxxxxx
For help, see: https://nodejs.org/en/docs/inspector
- info Loaded env from /home/user/next/.env.local
...
Debugger listening on ws://127.0.0.1:9230/30db6056-c4af-49ec-af1d-xxxxxx
For help, see: https://nodejs.org/en/docs/inspector
- info the --inspect option was detected, the Next.js router server should be inspected at port 9230.
- ready started server on [::]:3000, url: http://localhost:3000
- info the --inspect option was detected, the Next.js server for app should be inspected at port 9232.
- info the --inspect option was detected, the Next.js server for pages should be inspected at port 9231.
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: 3.6.3
  pnpm: N/A
Relevant Packages:
  next: 13.5.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, CLI (create-next-app)

### Additional context

Reverting to v13.4.19 works.

### PR DESCRIPTION
**Pull request by tomfa**
Fixes ability to run `NODE_OPTIONS='--inspect' next dev` as described in [docs](https://nextjs.org/docs/pages/building-your-application/configuring/debugging), by removing inspect option from NODE_OPTIONS arg passed to worker process.

This bug seem to have been introduced in 7d93808c435d6d74f93e045711b1639dc1fc05b3 as a part of a some refactoring. See how `getNodeOptionsWithoutInspect` is no longer used.

Fixes #55862

### CODE REVIEW

**Comment by escherstair** [comment]
Hi, is there a roadmap for merging this PR?
Issue #55862 broke [this PR](https://github.com/toradex/vscode-torizon-templates/pull/127)

Thanks

**Comment by feedthejim** [comment]
@escherstair I think I fixed it in #57159

**Comment by escherstair** [comment]
> @escherstair I think I fixed it in #57159

And so this PR is not necessary anymore?

**Comment by escherstair** [comment]
Hi @feedthejim 
it seems that the original issue #55862 is present in `14.0.0` [https://github.com/vercel/next.js/issues/55862#issuecomment-1813479700](https://github.com/vercel/next.js/issues/55862#issuecomment-1813479700)

**Comment by kylemh** [comment]
@feedthejim still not working in v14, right?

**Review by huozhi — APPROVED** [review]

**Pull request merged**
