### PR TITLE
Updated with-apollo example.

### PR DESCRIPTION
**Pull request by jaydenseric**
- Deleted several unused dependencies.
- Updated dependencies.
- Simplified Apollo related imports thanks to react-apollo exporting apollo-client and graphql-tag since [v0.13.2](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#0132).
- Tidied the readme and added a link to the Apollo docs.

### CODE REVIEW

**Review by sedubois — APPROVED** [review]
Nice 👍

**Review by timneutkens — APPROVED** [review]
👍

**Comment by ads1018** [comment]
Awesome sauce 👍

**Comment by Geczy** [comment]
Why was the `graphql` dependency added? I don't see it used anywhere 

@jaydenseric

**Comment by jaydenseric** [comment]
@Geczy this PR didn't add it, it updated it.

These days, depending on your setup you likely don't need to explicitly install `qraphql` in a client app.

**Pull request merged**
