### PR TITLE
Example app: fb-like chat tabs (#245)

### PR DESCRIPTION
**Pull request by chandrajob365**
Here is my example app as per issue #245 , which uses Next `<Link>` `(next\link)` and a **global store** to store the states of component across Links

### CODE REVIEW

**Comment by chandrajob365** [comment]
@timneutkens @arunoda  "CoverageAll"is failing but in package.json I just changed "license": "ISC" -> "license": "MIT" ?

**Comment by timneutkens** [comment]
@chandrajob365 most likely cause you added a lot of code to the codebase which is untested, no worries there 😄

**Comment by chandrajob365** [comment]
Thanks @timneutkens

**Comment by timneutkens** [comment]
@rauchg since I know you've been working on a messenger app, could you check this out?

**Pull request closed without merging**
