### PR TITLE
Add Alex to lint documentation

### PR DESCRIPTION
**Pull request by petermekhaeil**
This Pull Request adds [Alex](https://alexjs.com/) to our documentation. It catches insensitive, inconsiderate writing. I have gone through all our documentations and chosen alternative wording. If anyone sees I have made an error, or have suggestions for better wording - please let me know!

## Sections affected: 

- `docs/`
- `errors/`
- `examples/`

## More Information on Alex:
- https://alexjs.com/
- https://github.com/get-alex/alex

## Documentation / Examples

- [x] Make sure the linting passes

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| buildDuration | 11s | 11.1s | ⚠️ +86ms |
| buildDurationCached | 2.8s | 2.7s | -78ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.186 | 2.282 | ⚠️ +0.1 |
| / avg req/sec | 1143.86 | 1095.39 | ⚠️ -48.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.172 | 1.139 | -0.03 |
| /error-in-render avg req/sec | 2133.87 | 2194.14 | +60.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| index.html gzip | 574 B | 574 B | ✓ |
| link.html gzip | 581 B | 581 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.5s | -230ms |
| buildDurationCached | 3.6s | 3.7s | ⚠️ +1ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| buildDuration | 9.8s | 9.7s | -44ms |
| buildDurationCached | 4s | 4s | -7ms |
| nodeModulesSize | 46.5 MB | 46.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.272 | 2.286 | ⚠️ +0.01 |
| / avg req/sec | 1100.25 | 1093.45 | ⚠️ -6.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.144 | 1.12 | -0.02 |
| /error-in-render avg req/sec | 2186.02 | 2231.69 | +45.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 61.1 kB | 61.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.17 kB | 9.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | petermekhaeil/next.js alex-language | Change |
| - | - | - | - |
| index.html gzip | 627 B | 627 B | ✓ |
| link.html gzip | 633 B | 633 B | ✓ |
| withRouter.html gzip | 619 B | 619 B | ✓ |
| Overall change | 1.88 kB | 1.88 kB | ✓ |

</details>

</details>
Commit: 8854ddded845841c6031bd996a1ec0d75373beef

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8854ddded845841c6031bd996a1ec0d75373beef

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules
- Basic Features > Hot Module Reloading > editing a page > should update styles in a stateful component correctly

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

  ● Basic Features › Hot Module Reloading › editing a page › should update styles in a stateful component correctly

    TIMED OUT: /200px/

    100px

      399 |
      400 |   if (hardError) {
    > 401 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      402 |   }
      403 |   return false
      404 | }

      at check (lib/next-test-utils.js:401:11)
      at Object.<anonymous> (integration/basic/test/hmr.js:209:11)

</details>

**Comment by petermekhaeil** [comment]
I'm not quite sure why the tests keep failing. Looks like a flakey test? I've double checked the files changed and they are all documents and example markdowns.

**Comment by petermekhaeil** [comment]
Closing in favour of smaller PRs

**Pull request closed without merging**
