### PR TITLE
Add custom-server-typescript example (see #3694)

### PR DESCRIPTION
**Pull request by retrixe**
Requested in #2744 as well.

### CODE REVIEW

**Comment by khuezy** [comment]
I'm unable to use typecript syntax w/ any `ts` files under `server`:

`SyntaxError: Unexpected token import`

**Comment by retrixe** [comment]
@khuezy just edited the example, hope it works now, was a mistake on my side with `ts-node` configuration.

**Comment by khuezy** [comment]
@retrixe Thanks for getting this out! 

I had to escape the `"` in the the `nodemon.json` file:
"ts": "ts-node --compilerOptions '{\"module\":\"commonjs\"}'"

**Comment by retrixe** [comment]
@khuezy Fixed all issues with linting and the escaping issue, :sweat_smile: everything works now, thanks for the feedback :)

**Comment by khuezy** [comment]
@retrixe I'm having trouble building.

I had to change the build script to:
`"build": "next build && tsc server/**/*.ts --module commonjs --outDir lib"`

w/o the `outDir` it would compile the`.js` files in the `server` folder. It looks like it's not reading the `tsconfig.json` file.

**Comment by retrixe** [comment]
Huh, I am unable to replicate on my side.

**Comment by khuezy** [comment]
in `nodemon.json`, I think you wanted to watch the `.ts` files instead of the `.js`?

**Comment by retrixe** [comment]
Just fixed that, but it still doesn't seem that that is the issue.

**Comment by khuezy** [comment]
@retrixe I finally figured out why my build was busted. For some reason, npm installed a really old version of `chalk`, which caused typescript to explode.

Everything is 👍 now. Thanks for adding this customer server ts support.

**Review by timneutkens — APPROVED** [review]

**Comment by kachkaev** [comment]
I just tried your example and it really helped me get a custom ts server! Two questions:

* Do we need `"jsx": "preserve",` in `tsconfig.json` like in https://github.com/zeit/next.js/commit/97aef52defea2cd497353734d2ee4319fd74dd63?

* Would not it be better to use `production-server` dir instead of `lib`? People may be using this directory for storing shared modules and this can create a glitch.

**Comment by retrixe** [comment]
@kachkaev 
1. By default, the jsx value is preserve, so I do not believe we need to?.. I did not experience an issue with this myself when using VSCode so I cannot say.

2. We can do this, but this can be individually customized as per people's needs and I think as an example we do not need to implement a different directory.

**Comment by kachkaev** [comment]
@retrixe 

1. I'm not sure why, but I [had problems](https://github.com/zeit/next.js/pull/3698#issuecomment-366442816) until I added `preserve`. Official docs in https://github.com/zeit/next-plugins/tree/master/packages/next-typescript#usage also mention `jsx` parameter.

2. Some other Next.js examples do use `lib` for source files and it is often the case that people start new projects by combining a few examples together (that's what I was doing when I found your PR). I've already renamed `lib` to `production-server` in `package.json` and `tsconfig.json` in my new project – no big deal. However, this took some time and brain effort. People who are just starting with Next.js or TypeScript may get a bit confused and forget to rename something and then spend an hour on catching a bug they do not understand.

I'll be happy to submit a PR that renames `lib` to `production-server` and also adds `"jsx": "preserve"`. WDYT?

**Comment by retrixe** [comment]
@kachkaev no problemo :)

**Comment by kachkaev** [comment]
One more tiny improvement: https://github.com/zeit/next.js/pull/3963

**Pull request merged**
