### PR TITLE
Browserstack optimisations

### PR DESCRIPTION
**Pull request by nimit95**
So actually there problems was as follows - 
The driver was not being stopped, so it kept the test in running state until the BrowserStack 90 seconds Timeout and the BrowserStack Binary was being killed before the drive was being quit. Hence, some of the requests in the test were failing.

Sometimes, in case of sessions running in parallel with same key, it cannot spawn two different binaries with only ``` key ``` parameter, user needs to use ``` local-identifier ``` for each instance of binary.

### CODE REVIEW

**Review by ijjk — APPROVED** [review]
Awesome, thanks for the PR!

**Comment by nimit95** [comment]
Hey, no problem :)

**Comment by nimit95** [comment]
But I still see firefox 66.0 tests failing, can someone verify the same test working on their local machine nerxt-webdriver setup? :)

**Comment by ijjk** [comment]
The firefox tests failing looks like a bug that was breaking `next/dynamic`, I just submitted a PR [here](https://github.com/zeit/next.js/pull/7203) that should address it.

**Comment by nimit95** [comment]
Oh okay, thanks

**Pull request merged**
