### PR TITLE
Temporarily only do one pass

### PR DESCRIPTION
**Pull request by timneutkens**
Still under experimental flag, but this changes the catching approach to prepass.

### CODE REVIEW

**Review by Timer — APPROVED** [review]
LGTM if tests pass

**Review by ijjk — APPROVED** [review]

**Comment by sarkistlt** [comment]
after upgrading from canary.14 to canary.15 and above (which includes only this patch), start getting this error:

```cli
TypeError: Cannot read property 'current' of undefined
    at Object.<anonymous> (/***/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:842:45)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/***/node_modules/react-ssr-prepass/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by kitten** [comment]
@sarkistlt Hiya, maintainer of `react-ssr-prepass` here; The lines in question seem to be these:

https://github.com/FormidableLabs/react-ssr-prepass/blob/v1.0.2/src/index.js#L20-L24

`ReactCurrentDispatcher` being `undefined` hints at a React version that's older than `16.8.0`, so maybe something went wrong when you upgraded? Maybe try to upgrade at least to `16.8.0` or even better as bumped in this PR to `16.8.6`.

I probably will also need to update `react-ssr-prepass`' peer dependencies to reflect this. I've added `16.6.0` as a minimal version before and clearly this would need some changes to support the `ReactCurrentDispatcher` change that I was previously unaware of.

**Comment by sarkistlt** [comment]
@kitten upgrading React helped, thanks!

**Comment by timneutkens** [comment]
@sarkistlt note that you're using an experimental API that is guaranteed to break in your application between any releases.

**Pull request merged**
