### PR TITLE
update zustand example

### PR DESCRIPTION
**Pull request by Munawwar**
Made SSG and SSR code similar. Comments and variable renames on store.js

Checklist:

## Documentation / Examples

- [✓] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by Munawwar** [comment]
@leerob Requesting to merge PR. I wrote the initial example some months ago. This PR is just cleanup + comments.

**Comment by Munawwar** [comment]
rebased branch

**Comment by Munawwar** [comment]
^ last force push was just rebasing branch again.

**Review by ijjk — APPROVED** [review]

**Comment by premier213** [comment]
how to add multi-state to this example?
`store = store ?? initializeStore(serverInitialState)`

**Pull request merged**
