### PR TITLE
Allow static exports without trailing slashes

### PR DESCRIPTION
**Pull request by NathanielHill**
This should expose an option in `next.config.js` to keep the router from added trailing slashes.

Fixes: #3283, #2944 
Related: #3876, #1189

@timneutkens

### CODE REVIEW

**Comment by NathanielHill** [comment]
Right now I have a guard in place as it appears that somehow in the testing environment the `weback.DefinePlugin` does not run. It would be helpful if someone could figure out why this is.

**Comment by NathanielHill** [comment]
Not sure why this broke when I merged this upstream. I should have created a separate branch for this PR :man_shrugging: Still need to figure out why `webpack` doesn't seem to run the `DefinePlugin` in the test environment :thinking: Will add a new test once I figure that out.

**Comment by NathanielHill** [comment]
This is fixed :tada:
https://zeit.co/blog/new-static-deployments

**Comment by timneutkens** [comment]
I'm confused, this is still an issue in Next.js 🤔

**Comment by NathanielHill** [comment]
Is it? I've never had trailing slash problems with dynamic deployments :man_shrugging:
I only had problems when I did a `next export`. Which frustratingly meant deploying the same code as dynamic vs static gave different urls. I no longer have any issues. If other people do, perhaps they can open a new pr/issue or use an existing one?

**Comment by Soundvessel** [comment]
This appears to still be an issue with 8.0.3. You can check my export settings on https://github.com/zeit/next.js/issues/2944#issuecomment-467530067

**Pull request closed without merging**
