### PR TITLE
use pathToFileUrl to make esm import()s work with absolute windows paths

### LINKED ISSUE #63359: Problems with PostCSS (ESM, URL-SCHEME and so on)
### Link to the code that reproduces this issue

https://github.com/MrOxMasTer/shopco

### To Reproduce

1. Try to build a package using "pnpm run build"

OR to check for another error:

1. Upgrade to the latest version of next.js canary 
2.  see that the project just doesn't start

### Current vs. Expected behavior

complete project

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16320
  Available CPU cores: 6
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.2-canary.3 // There is a newer canary version (14.2.0-canary.24) available, please upgrade!
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, CLI (create-next-app), Font optimization (next/font), Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

The first problem: 
the project is not going to be built on version 14.1.2-canary.3. With "type": "module" in package.json

src\app\layout.tsx
An error occurred in next/font.

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\postcss.config.js from C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js not supported.
Instead change the require of postcss.config.js in C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js to a dynamic import() which is available in all CommonJS modules.
at mod.require (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\require-hook.js:65:28)
at findConfig (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\find-config.js:58:20)
at async getPostCssPlugins (C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\config\blocks\css\plugins.js:89:18)
at async C:\Users\Алексей\OneDrive\Рабочий стол\PetProjects\shopco\node_modules.pnpm\next@14.1.2-canary.3_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\config\blocks\css\index.js:124:36

image

### LINKED ISSUE #64371: create-next-app: Build Error using `next dev` v14.2 (`ERR_UNSUPPORTED_ESM_URL_SCHEME`)
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/falling-morning-j32gvz

### To Reproduce

1. Create a next project using `create-next-app` CLI with v14.2
2. Run in development (`next dev`)
3. Error will show up like this:

image

### Current vs. Expected behavior

Currently, when creating an app using `create-next-app` (default options selected), the build error shows up and throws `ERR_UNSUPPORTED_ESM_URL_SCHEME`

The new project should work as expected.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 32385
  Available CPU cores: 12
Binaries:
  Node: 21.3.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I believe the issue is specific to Windows and I unfortunately cannot reproduce it on CodeSandbox.

### PR DESCRIPTION
**Pull request by sokra**
### What?

Fixes #64371
Fixes #63359

Closes PACK-2946

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e5eff37fd8776bc2ae38e0ffac0c3aa10f7d3163

`pnpm test-dev packages/next/src/lib/find-config.test.ts`
- findConfig() > should load config properly from *.config.* file (type: "module", config: awsome.config.js)
- findConfig() > should load config properly from *.config.* file (type: "module", config: awsome.config.mjs)
- findConfig() > should load config properly from *.config.* file (type: "commonjs", config: awsome.config.mjs)

<details>
<summary>Expand output</summary>

  ● findConfig() › should load config properly from *.config.* file (type: "module", config: awsome.config.js)

    Cannot find module 'file:///tmp/nextjs-test-3bR3PK/awsome.config.js' from '../packages/next/src/lib/find-config.ts'

      70 |       if (isESM) {
      71 |         const fileUrl = pathToFileURL(filePath).toString()
    > 72 |         return (await import(fileUrl)).default
         |                       ^
      73 |       } else {
      74 |         return require(filePath)
      75 |       }

      at Resolver._throwModNotFoundError (../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
      at ../packages/next/src/lib/find-config.ts:72:23
      at findConfig (../packages/next/src/lib/find-config.ts:72:17)
      at Object.<anonymous> (../packages/next/src/lib/find-config.test.ts:55:30)

  ● findConfig() › should load config properly from *.config.* file (type: "module", config: awsome.config.mjs)

    Cannot find module 'file:///tmp/nextjs-test-v8ICsf/awsome.config.mjs' from '../packages/next/src/lib/find-config.ts'

      76 |     } else if (filePath.endsWith('.mjs')) {
      77 |       const fileUrl = pathToFileURL(filePath).toString()
    > 78 |       return (await import(fileUrl)).default
         |                     ^
      79 |     } else if (filePath.endsWith('.cjs')) {
      80 |       return require(filePath)
      81 |     }

      at Resolver._throwModNotFoundError (../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
      at ../packages/next/src/lib/find-config.ts:78:21
      at findConfig (../packages/next/src/lib/find-config.ts:78:15)
      at Object.<anonymous> (../packages/next/src/lib/find-config.test.ts:55:30)

  ● findConfig() › should load config properly from *.config.* file (type: "commonjs", config: awsome.config.mjs)

    Cannot find module 'file:///tmp/nextjs-test-2wZASm/awsome.config.mjs' from '../packages/next/src/lib/find-config.ts'

      76 |     } else if (filePath.endsWith('.mjs')) {
      77 |       const fileUrl = pathToFileURL(filePath).toString()
    > 78 |       return (await import(fileUrl)).default
         |                     ^
      79 |     } else if (filePath.endsWith('.cjs')) {
      80 |       return require(filePath)
      81 |     }

      at Resolver._throwModNotFoundError (../node_modules/.pnpm/jest-resolve@29.7.0/node_modules/jest-resolve/build/resolver.js:427:11)
      at ../packages/next/src/lib/find-config.ts:78:21
      at findConfig (../packages/next/src/lib/find-config.ts:78:15)
      at Object.<anonymous> (../packages/next/src/lib/find-config.test.ts:55:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.9s | N/A |
| buildDurationCached | 7.5s | 6.2s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +1.91 kB |
| nextStartRea..uration (ms) | 411ms | 383ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.1 kB | 5.1 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.63 kB | 6.63 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 525 B | 524 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.6 kB | 95.6 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 625 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 839 B | 839 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 97.4 kB | 97.4 kB | ✓ |
| app-page-tur..prod.js gzip | 99.2 kB | 99.2 kB | ✓ |
| app-page-tur..prod.js gzip | 93.4 kB | 93.4 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.9 kB | 91.9 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| server.runti..prod.js gzip | 51.3 kB | 51.3 kB | ✓ |
| Overall change | 948 kB | 948 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/use-url-for-esm-import | Change |
| - | - | - | - |
| 0.pack gzip | 1.59 MB | 1.58 MB | N/A |
| index.pack gzip | 107 kB | 106 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: e5eff37fd8776bc2ae38e0ffac0c3aa10f7d3163

**Comment by timneutkens** [comment]
* **#64386** <a href="https://app.graphite.dev/github/pr/vercel/next.js/64386?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sokra and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by huozhi — APPROVED** [review]

**Comment by gerardoluisbv** [comment]
I change postcss.config.js to postcss.config.cjs and this work for me

**Pull request merged**
