### PR TITLE
docs: document cache tagging mechanism

### PR DESCRIPTION
**Pull request by lucasconstantino**
This PR document the cache tagging semantics in Next.js, and how to benefit from it during cache revalidation.

### CODE REVIEW

**Review by leerob — APPROVED** [review]
Good update - thank you!

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c97fb99754cd8ca5575656ae9351cc4a1610fc5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c97fb99754cd8ca5575656ae9351cc4a1610fc5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c97fb99754cd8ca5575656ae9351cc4a1610fc5

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
