### PR TITLE
fixed error #52486  fetchUsers to fetchUser

### PR DESCRIPTION
**Pull request by darshanjain-entrepreneur**
#52486 

Here I fixed the typo error of fetchUsers to fetchUser in   docs/api-reference/04-functions/not-found.mdx

async function fetchUser(id) { // Here instead of fetchUsers i changed it to  fetchUser
const res = await fetch('https://...')
if (!res.ok) return undefined
return res.json()
}

export default async function Profile({ params }) {
const user = await fetchUser(params.id)

if (!user) {
notFound()
}

// ...
}

https://nextjs.org/docs/app/api-reference/functions/not-found

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Thanks!

**Comment by darshanjain-entrepreneur** [comment]
I always want to contribute to open source  and thanks for accepting my  pull request

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 75ed80b6002d47cd9423d379cfd3bf361ab21d12

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by darshanjain-entrepreneur** [comment]
Cn you tell me why the pull request was rejected

**Pull request merged**
