### PR TITLE
update devdDependencies @types/react and @types/react-dom  

### LINKED ISSUE #37421: TypeError : 'Component' cannot be used as JSX component
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
    Binaries:
      Node: 14.18.2
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

with-redux

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

I am using nextjs example [with-redux](https://github.com/vercel/next.js/tree/canary/examples/with-redux) . The current version of devDependencies `@types/react` and `@types/react-dom` gives type error ` Type Error 'Component' cannot be used as a JSX component.`  
Below is screenshot showing error 

Screenshot (19)

The problem can be solved by upgrading the `@types/react` and `@types/react-dom`  dependencies

### Expected Behavior

TypeError should not occur 

### To Reproduce

If you do not see the typeError after cloning this example repository run next build to see typeError while build process .

### PR DESCRIPTION
**Pull request by saurabhmehta1601**
fixes #37421

### CODE REVIEW

**Comment by codemile** [comment]
You can't install React 18 defs if the project is using React 17.

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks, could we upgrade all other dependencies as well? :+1:

**Comment by balazsorban44** [comment]
@saurabhmehta1601 please address my comment here, so we can merge it: https://github.com/vercel/next.js/pull/37423#pullrequestreview-996481320

**Comment by saurabhmehta1601** [comment]
Thanks @balazsorban44  for the correction in package versions . I am new to contributing to large codebases . Sorry I have unknowingly caused any convenience in the process .

**Comment by balazsorban44** [comment]
No problem @saurabhmehta1601! I'm happy to help your first PR merged to the Next.js repo!

What I meant is this:
https://github.com/vercel/next.js/blob/756dc8f2189fc4f0722ab460d5b69ebbfc4b42eb/examples/with-redux/package.json#L13-L14

At the least, these should be upgraded as well so the `@types/react` and `@types/react-dom` dependencies correlate to the correct React version.

**Review by balazsorban44 — APPROVED** [review]
Thank you!

**Pull request merged**
