### PR TITLE
example: update with latest example from @neshca/cache-handler

### PR DESCRIPTION
**Pull request by sensecodevalue**
### What?
Apply the cache-handler.mjs from the latest example at example/cache-handler-redis.

### Why?
[The example provided](https://caching-tools.github.io/next-shared-cache/redis) has changed as the package @neshca/cache-handler has been updated from ^0.6 to ^1.3.1.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 92587316815b3767f6a937d15cdf64ba0ed9c2de

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 92587316815b3767f6a937d15cdf64ba0ed9c2de

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by sensecodevalue** [comment]
I have tested the changes in my local environment.

|Web UI | Redis |
|----------|----------|
| 스크린샷 2024-07-03 오후 7 41 32 | 스크린샷 2024-07-03 오후 7 59 29 |

**Comment by sensecodevalue** [comment]
I have identified a duplicate of this PR. Therefore, I am closing it. #67350

**Pull request closed without merging**
