### PR TITLE
refactor: removes 'version' attribute post deprecation

### PR DESCRIPTION
**Pull request by khawajaJunaid**
### What?
removes 'version' attribute post deprecation from all compose files related to dev, staging and prod env

### Why?
latest updates in docker compose no longer requires 'version' attribute

### How?
remove the version field in the compose files to remove the warning that one may get during builds

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8cef068e04d8ec70ff3344cfbbe5f13f08be1f7e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by eps1lon** [comment]
> latest updates in docker compose no longer requires 'version' attribute

Which update?

**Comment by khawajaJunaid** [comment]
> > latest updates in docker compose no longer requires 'version' attribute
> 
> Which update?

In the docker compose yml format, it mentions that the version attribute has been deprecated

**Comment by leerob** [comment]
Please include more details, including the release notes + version where the attribute was removed, in a new PR 🙏

**Pull request closed without merging**
