### PR TITLE
docs: Update link to `next-intl` in internationalization docs

### PR DESCRIPTION
**Pull request by amannn**
I've just moved the domain to [next-intl.dev](https://next-intl.dev), would be cool to update this in the Next.js docs!

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c5a012ce402764005b1ab5aff96ba40f94057597

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c5a012ce402764005b1ab5aff96ba40f94057597

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
There are merge conflicts and I can't push to your fork.

Addressing in https://github.com/vercel/next.js/pull/73955.

**Comment by amannn** [comment]
Many thanks @leerob! 🙌 Must have forgotten checking the allow edits box …

Any chance you could help with https://github.com/vercel/next.js/pull/73431 getting merged? This has been a bug since Next.js 15 has been released and I notice users keep running into it …

**Pull request closed without merging**
