### PR TITLE
I think these example links are backwards

### PR DESCRIPTION
**Pull request by bleonard**

### CODE REVIEW

**Comment by timneutkens** [comment]
Hmm same thing is on the express example. @nkzawa could you verify if this is correct >.<

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/blob/master/examples/custom-server-express/pages/index.js

**Comment by bleonard** [comment]
i fixed that one too. seems likely whoever made the first one of these mixed them up and it was copied to the other 3.

**Comment by bleonard** [comment]
maybe i don't understand what's going on but these server thinks looked misaligned too.

**Comment by bleonard** [comment]
hmmmm, maybe it's like that to prove they can be sent in non-defualt directions.

**Comment by bleonard** [comment]
Yeah, nevermind. I think it's all on purpose. Yt could probably be clearer, but it's proving/illuatrating the point.

**Pull request closed without merging**
