### PR TITLE
Short circuit custom logger

### PR DESCRIPTION
**Pull request by SagnikPradhan**
Temporary fix for #4808

Custom logger or unified logging will require comprehensive work, looking at the number of issues I felt this would be on the back burner for a while, this pull request should be a short and quick fix.

Critiques are welcome, needed this for me.

BTW, Great work on NEXT.js 🙏🏻

### CODE REVIEW

**Comment by SagnikPradhan** [comment]
image

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| buildDuration | 9.1s | 8.8s | -242ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.04 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.941 | 1.766 | -0.18 |
| / avg req/sec | 1288.08 | 1415.77 | +127.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.125 | 1.137 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2221.53 | 2198.88 | ⚠️ -22.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| 677f882d2ed8..0acf.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-29e0222..8425.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| buildDuration | 10.7s | 11.2s | ⚠️ +460ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.04 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| 677f882d2ed8..0acf.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-29e0222..8425.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +71 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +71 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +71 B |
| routerDirect.js | 1.05 MB | 1.05 MB | ⚠️ +71 B |
| withRouter.js | 1.05 MB | 1.05 MB | ⚠️ +71 B |
| Overall change | 5.17 MB | 5.17 MB | ⚠️ +355 B |

</details>

</details>
Commit: 9e5fe825debb4872106901707d1e257ed1b906b5

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11s | -76ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +1.04 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.177 | 2.279 | ⚠️ +0.1 |
| / avg req/sec | 1148.14 | 1096.82 | ⚠️ -51.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.317 | 1.409 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1898.95 | 1774.57 | ⚠️ -124.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| 677f882d2ed8..42af.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a9a6f0d..a96d.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-cfcb6..fe1c.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.6s | ⚠️ +439ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +1.04 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| 677f882d2ed8..42af.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a9a6f0d..a96d.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.3 kB | 59.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-cfcb6..fe1c.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.08 kB | 8.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SagnikPradhan/next.js feat/custom-logger | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +71 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +71 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +71 B |
| routerDirect.js | 1.05 MB | 1.05 MB | ⚠️ +71 B |
| withRouter.js | 1.05 MB | 1.05 MB | ⚠️ +71 B |
| Overall change | 5.17 MB | 5.17 MB | ⚠️ +355 B |

</details>

</details>
Commit: 9217a3ec3194ee771b057b8aea3486a0274a04db

**Review by Timer — CHANGES_REQUESTED** [review]
Please open a formal RFC before adding new features to Next.js.

**Pull request closed without merging**
