### PR TITLE
fixes #56958

### LINKED ISSUE #56958: Missing of `.replaceAll()` polyfill
### Link to the code that reproduces this issue

https://github.com/An-Cu/replace-all-next-polyfill

### To Reproduce

1. Use one of [browser which is not supporting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility) `.replaceAll()`, but it's mentioned as [supported by default by next.js ](https://nextjs.org/docs/architecture/supported-browsers) e.g. Firefox v67-76 or Chrome v 64-84
2. Use the `.replaceAll()`  in you next page component. Try [supported-browsers page](https://nextjs.org/docs/architecture/supported-browsers) fro example.
3. Check console for app crash.

### Current vs. Expected behavior

The supported by default by next.js browsers which does not have replaceAll feature should work without app crash in places where replaceAll is used.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:               
  Platform: win32               
  Arch: x64                     
  Version: Windows 10 Enterprise
Binaries:                       
  Node: 18.16.1                 
  npm: N/A                      
  Yarn: N/A                     
  pnpm: N/A                     
Relevant Packages:              
  next: 13.5.6-canary.2         
  eslint-config-next: 13.5.4    
  react: 18.2.0                 
  react-dom: 18.2.0             
  typescript: 5.2.2             
Next.js Config:                 
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by An-Cu**
Extended the polyfill set by replaceAll()

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
`next-polyfill-nomodule` only serves as a fallback for browsers that don't support the ES module and **will only be loaded on the following browsers**:

- Chrome < 61
- Edge < 16
- Safari <= 11
- Firefox < 60
- Opera < 48
- IE
- Opera Mini

**Comment by childrentime** [comment]
image
JavaScript built-in: Array: at, is not supported in safari version below 15.4, why nextjs don't loaded next-polyfill-nomodule for it?

**Comment by timneutkens** [comment]
As per what Sukka said I'm going to close this PR. Polyfills are added only if they're unavailable in browsers that don't support esmodules but are supported in esmodules supporting browsers. It uses esmodules support as a cutoff point to do differential loading.

The polyfills for esmodules browsers are kept minimal because those are always loaded by all browsers.

**Comment by An-Cu** [comment]
@SukkaW @timneutkens I agree with closure of this PR and argument about fallback should not be used for browsers which support es-modules. 
Anyway the problem is that in browsers which supports es-modules there is no polyfill for `.replaceAll`, `.at` and more methods which regarding documentation are supported by next.js. The [issue](https://github.com/vercel/next.js/issues/56958) is still exists.

**Pull request closed without merging**
