### PR TITLE
Make `antd.css` become an internal stylesheet to avoid the the CSS flickering issue in the `with-ant-design` example

### LINKED ISSUE #22819: Antd example css problem in Prod mode
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

12.15.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When using antd example, during development everything works fine but when I run it through npm start (next start) and on vercel, the website loads the css a second later and you can see the elements transitioning from not having css to the antd css.

### Expected Behavior

It should load css before rendering the components

### To Reproduce

clone the nextjs antd example https://github.com/vercel/next.js/tree/canary/examples/with-ant-design and then run npm install, npm run build, npm start

### PR DESCRIPTION
**Pull request by evanxd**
Make `antd.css` become an internal stylesheet to ensure that the stylesheet will be loaded before the page rendering and avoid the CSS flickering issue.

Fixes #22819.

### CODE REVIEW

**Review by leerob — COMMENTED** [review]
Hmm, I don't think this is the best idea. Is there another solution?

**Comment by evanxd** [comment]
Hi @leerob 

The next.js example in `material-ui` reop basically do the same approach to avoid the CSS flickering issue, make the `material-ui` styles as an internal stylesheet, like below:
https://github.com/mui-org/material-ui/blob/next/examples/nextjs/pages/_document.js#L74-L79
```js
<style
  key="emotion-style-tag"
  data-emotion={`css ${styles.ids.join(' ')}`}
  // eslint-disable-next-line react/no-danger
  dangerouslySetInnerHTML={{ __html: styles.css }}
/>,
```

I have another idea to solve the CSS flickering issue, but I'm not sure it's a better solution. We can hide the page until the external `antd` CSS file is loaded, and then display the page, which means we can do something like below:
```html
<head>
  <link rel="preload" href="antd.min.css" as="style" onload="this.rel = stylesheet; document.querySelector('body').setAttribute('style', 'visibility: visible');" />
</head>
<body style="visibility: hidden">
</body>
```
But the cons of the `hiding body element` approach are:
* It doesn't work when users disable JavaScript
* It doesn't work if the URI of the CSS file is broken

To be honest, compare to the `hiding body element` approach, I more prefer the `internal CSS` approach, it more clear and easier. Does anyone have other better ideas?

**Comment by evanxd** [comment]
Ah! If we can handle the JavaScript disability situation for the `hiding body element` approach, we can make the page visible in the `<noscript />` element. So we can do something like below to fix the problem.
```html
<head>
  <link rel="preload" href="antd.min.css" as="style" onload="this.rel = stylesheet; document.querySelector('body').setAttribute('style', 'visibility: visible');" />
  <noscript><style>body { visibility: visible }</style></noscript>
</head>
<body style="visibility: hidden">
</body>
```
Does this make the `hiding body element` approach become a better solution?

**Comment by dryleaf** [comment]
I also think this solution is not ideal. Perhaps a solution which does not involve using `_app.js` and `_document.js` would be the best one.

**Comment by ClearSeve** [comment]
Whether this problem has not been solved, the latest official example still has this problem

**Comment by leerob** [comment]
Closing as stale – if you would like to continue this, please open a new PR and we can take a look. Thank you so much! 🙏

**Pull request closed without merging**
