### PR TITLE
[doc] Hint for shallow routing in getInitialProps

### PR DESCRIPTION
**Pull request by azizhk**

### CODE REVIEW

**Comment by lfades** [comment]
@azizhk I find it confusing, what are you trying to explain ?

**Comment by azizhk** [comment]
I'll explain with an example.
Lets say the user is on /routeA and then clicks on a link to /routeB.
`next/link` would internally call:
```js
import Router from "next/router";
Router.push("/routeB", "/routeB")
```

Now let's say in routeB's component's getInitialProps you realize you want to shallow redirect:

```js
// pages/routeB.js
export default class RouteB extends React.Component {
  static async getInitialProps () {
    const slug = await fetch("/some-data");
    Router.replace(
      `/routeB?slug=${slug}`,
      `/routeB/${slug}`,
      { shallow: true }
    )
    return { slug }
  }
}
```

Now one might assume that because we are shallow routing, `getInitialProps` would not get called.
But shallow redirect compares the url with the previous route, in this case it should have been /routeB as we have started rendering it, but it actually compares with /routeA and this `getInitialProps` gets called twice.

A solution to this would be to shallow redirect in `componentDidMount` and `componentDidUpdate`

**Comment by lfades** [comment]
@azizhk I think there are better ways to do the same, instead of calling `Router.replace` inside `getInitialProps`, in your example it's unnecessary.

>Now one might assume that because we are shallow routing, getInitialProps would not get called.
But shallow redirect compares the url with the previous route, in this case it should have been /routeB as we have started rendering it, but it actually compares with /routeA and this getInitialProps gets called twice.

We haven't started rendering the route when `getInitialProps` is called, that's after it has resolved the initial props.

I'm going to close this for now as I think this is a bad practice.

**Comment by azizhk** [comment]
Then probably we should change wording.
"Don't call Router.replace from getInitialProps"

**Pull request closed without merging**
