### PR TITLE
Typescript option `enableDevErrorsCheck`

### PR DESCRIPTION
**Pull request by OlehDutchenko**
Since NextJS,  by default, removed Typescript errors check in dev mode,
this PR add new Typescript option that allows you to enable error checking in development mode if needed

```js
// next.config.js
module.exports = {
  typescript: {
    enableDevErrorsCheck: true,
  },
}
```

### CODE REVIEW

**Comment by dutchenkoOleg** [comment]
Resolves #12735

**Comment by timneutkens** [comment]
Since compilation time increases around 10x when using this plugin in development I'd like to fix that first before introducing any type of enable flag. Can you investigate that?

**Comment by dutchenkoOleg** [comment]
> Since compilation time increases around 10x when using this plugin in development I'd like to fix that first before introducing any type of enable flag. Can you investigate that?

But is it my personal decision to enable the plugin or not? If I turn it on, I’ll understand that the compilation time will be longer. I accept this and agree to this, if not, I do not enable this option.

You are making a good product for developers and this is great. I am very grateful to you for this. But do not limit people without a choice.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.9s | ⚠️ +481ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +268 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.224 | 2.246 | ⚠️ +0.02 |
| / avg req/sec | 1124.18 | 1113.26 | -10.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.435 | 1.474 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1742.46 | 1695.75 | -46.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.8s | ⚠️ +5ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +268 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 907 kB | 907 kB | ✓ |
| withRouter.js | 907 kB | 907 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| buildDuration | 13.2s | 12.8s | -328ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +268 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.436 | 2.335 | -0.1 |
| / avg req/sec | 1026.3 | 1070.65 | ⚠️ +44.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.589 | 1.555 | -0.03 |
| /error-in-render avg req/sec | 1573.36 | 1607.46 | ⚠️ +34.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| buildDuration | 13.4s | 12.9s | -504ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +268 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | dutchenkoOleg/next.js typescript-enableDevErrorsCheck | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 907 kB | 907 kB | ✓ |
| withRouter.js | 907 kB | 907 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>

**Comment by timneutkens** [comment]
> > Since compilation time increases around 10x when using this plugin in development I'd like to fix that first before introducing any type of enable flag. Can you investigate that?
> 
> But is it my personal decision to enable the plugin or not? If I turn it on, I’ll understand that the compilation time will be longer. I accept this and agree to this, if not, I do not enable this option.
> 
> You are making a good product for developers and this is great. I am very grateful to you for this. But do not limit people without a choice.

If you want to make that trade-off you can customize the webpack config in your next.config.js right 🤔

**Comment by dutchenkoOleg** [comment]
@timneutkens Of course I can do it. 
But what's the point then in the NextJS as Product?

Then you can just tell everyone: "- why do you need a convenient product with the possibility of customization? People, use yourselves own personal webpack build and forget about Next"
Right?

I chose your product because it is universal and ideal for my tasks. It worked perfectly with the Typescript, and this allowed me to conveniently configure the work of my team. Until you removed type checking, being guided by the opinion that it would be better for your users. 

Damn it, it's your right as mainteriners!
But give the opportunity to control this behavior at my own risk.

**Comment by timneutkens** [comment]
As said we'd be super happy to re-enable the behavior if it's not taking 10x the compilation time. Until then you can add the plugin (which is incredibly slow as said) through pushing it into the plugins object using a the custom webpack config.

**Comment by dutchenkoOleg** [comment]
Compilation speed is purely my problem. Even if there is a 20-fold slowdown - I do not care!
I need type checking in dev mode, which I can turn on or off with a single flag.

@timneutkens Can you understand this? No need to worry about the speed of my project compilation. I’m talking to you as if with a wall. Maybe someone else from your team is more intelligible.

/cc @Timer @lfades

**Comment by Timer** [comment]
Enabling this behavior would have a very detrimental effect on the Fast Refresh experience, and is not something we consider to be up to standard.

I'm going to close this pull request per comments from @timneutkens above.

If you really want to slow down your development experience, you must do it via custom configuration.

---

If you feel strongly about getting this behavior back into Next.js, please help by contributing a new solution does not slow down the development time experience.

We need a solution that:

- Runs completely separate from the webpack build (not a webpack plugin or loader)
- Runs on a separate thread (`jest-worker` or similar)
- Reports errors in a toast in the browser, instead of full screen overlay

**Comment by nynevi** [comment]
hello, thanks for the changes but unfortunately please keep in mind below:
- the compilation times are increased for me on a very fast SSD, visible to the eye (maybe logs happen on a different timing) 2-3 times, I'd be happy to provide benchmarks if I'm shown the way how to
- it was compiling then doing typechecks so you'd get the page refreshed then you'd get type errors on the console and the browser, not sure how this would affect compilation performance, just development UX was different
- yarn build prints one error at a time therefore a need to do subsequent yarn builds is a pain to go through
- the linting done by the editors are sometimes incorrect (webstorm caches errors between branch switches when server is running) therefore unless you open the file, correct linting does not reset. this is a problem on the editor level that I'd need to fix which is ok but did not need to do before.
- we had to change our tsconfig to make yarn build fail on deployments
- people don't do yarn build locally, push code then create an PR and forget about PR and the deployment pipeline. the code gets reviewed, and has to be rereviewed after build problems are fixed OR they push, wait for pipeline to finish then recommit with messages like "fix build problems"

the UX was:
- fix TS error, save, fix another TS error, repeat
- continue development
- no need for yarn build after development finishes
now it is:
- do development without caring for TS, up to your eye to catch linting errors on editor
- fix errors at the end by several yarn builds locally

so the errors are not cared for but the continuous development without distractions is cared by your opinion.

so we've had errors fixed before they were commited, no one from our team was complaining about how bad the performance was. so I don't know why this PR was closed so harshly. so I'm more amazed by the fact that with the above statement, you admittedly say nextjs up until 30 days ago were not up to the standards?

the above comment states that you want a solution that does not affect performance but also states a toast will show the error so good luck showing a long nested TS error in a snack on top right corner (imagine mobile in browser emulator...), this basically makes the task undoable.

there will always be some people complaining for stuff that they aren't used to but please give it a second look as we'd highly appreciate the option to turn on the console TS errors even if it affects performance which we did not need and does not seem to be better either, it just does not refresh the page, and often times you need to refresh anyway to get to initial state

**Comment by Jaikant** [comment]
> If you want to make that trade-off you can customize the webpack config in your next.config.js right 🤔

@timneutkens  Is there an example for the webpack config (next.config.js) to enable typescript errors in dev mode?

**Comment by dutchenkoOleg** [comment]
@Jaikant 
here is my `next.config.js`

```js
// -----------------------------------------------------------------------------
// Deps
// -----------------------------------------------------------------------------

const fromCWD = require('from-cwd');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const PnpWebpackPlugin = require('pnp-webpack-plugin');
const { PHASE_DEVELOPMENT_SERVER } = require('next/constants');

// -----------------------------------------------------------------------------
// Next.js config
// @see {@link https://nextjs.org/docs/api-reference/next.config.js/introduction}
// -----------------------------------------------------------------------------

module.exports = (phase, { defaultConfig }) => ({
    webpack(config, { isServer }) {
        if (phase === PHASE_DEVELOPMENT_SERVER && !isServer) {
            config.plugins.push(
                new ForkTsCheckerWebpackPlugin(
                    PnpWebpackPlugin.forkTsCheckerOptions({
                        async: false,
                        useTypescriptIncrementalApi: true,
                        checkSyntacticErrors: true,
                        tsconfig: fromCWD('./tsconfig.json'),
                        reportFiles: ['**', '!**/__tests__/**', '!**/?(*.)(spec|test).*'],
                        compilerOptions: { isolatedModules: true, noEmit: true },
                        silent: true,
                        formatter: 'codeframe'
                    })
                )
            );
        }
        return config;
    }
});
```

**Pull request closed without merging**
