### PR TITLE
Change experimental `layout=raw` to use native img lazy loading

### PR DESCRIPTION
**Pull request by styfle**
This PR changes the experimental `layout=raw` images to use the native lazy loading behavior (as opposed to the IntersectionObserver).

This will (eventually) lead to smaller client bundles and faster image loading since there is no JS needed to load the image.

However, we'll lose the `lazyRoot` and `lazyBoundary` behavior since those are specific to the IntersectionObserver implementation.

### CODE REVIEW

**Review by atcastle — DISMISSED** [review]
Looks good

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ee1d56cf2c4a6cb23ce5239688425ae72a51dc6f

`yarn testheadless test/integration/image-component/default/test/index.test.js` 
- Image Component Tests > dev mode > should lazy load layout=raw and placeholder=blur
- Image Component Tests > server mode > should lazy load layout=raw and placeholder=blur
- Image Component Tests > serverless mode > should lazy load layout=raw and placeholder=blur

<details>
<summary>Expand output</summary>

  ● Image Component Tests › dev mode › should lazy load layout=raw and placeholder=blur

    expect(received).toMatch(expected)

    Expected substring: "data:image/"
    Received string:    "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ftest.fab2915d.jpg&w=828&q=75"

      761 |
      762 |     // raw1
    > 763 |     expect(await browser.elementById('raw1').getAttribute('src')).toMatch(
          |                                                                   ^
      764 |       'data:image/'
      765 |     )
      766 |     expect(await browser.elementById('raw1').getAttribute('srcset')).toBeNull()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:763:67)
          at runMicrotasks (<anonymous>)

  ● Image Component Tests › server mode › should lazy load layout=raw and placeholder=blur

    expect(received).toMatch(expected)

    Expected substring: "data:image/"
    Received string:    "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ftest.fab2915d.jpg&w=828&q=75"

      761 |
      762 |     // raw1
    > 763 |     expect(await browser.elementById('raw1').getAttribute('src')).toMatch(
          |                                                                   ^
      764 |       'data:image/'
      765 |     )
      766 |     expect(await browser.elementById('raw1').getAttribute('srcset')).toBeNull()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:763:67)

  ● Image Component Tests › serverless mode › should lazy load layout=raw and placeholder=blur

    expect(received).toMatch(expected)

    Expected substring: "data:image/"
    Received string:    "/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ftest.fab2915d.jpg&w=828&q=75"

      761 |
      762 |     // raw1
    > 763 |     expect(await browser.elementById('raw1').getAttribute('src')).toMatch(
          |                                                                   ^
      764 |       'data:image/'
      765 |     )
      766 |     expect(await browser.elementById('raw1').getAttribute('srcset')).toBeNull()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:763:67)
          at runMicrotasks (<anonymous>)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]
Looks good!

**Comment by jakejarvis** [comment]
@styfle, with this addition, will it be possible to set `priority={true}` on these at some point as well?

Completely agree with setting `loading=lazy` by default, but omitting this in specific cases would still be helpful, and having consistency with the existing `<head>` preloading behavior of the "classic" layouts would be great too! Looks like the raw image element is currently returned before reaching this priority condition:

https://github.com/vercel/next.js/blob/18b7b27fe1fc94a87ee7bd3eb754f0a331c6fed1/packages/next/client/image.tsx#L866-L886

...but feel free to ignore if there's a reason for this :)

**Comment by atcastle** [comment]
@jakejarvis Could you clarify what you mean about the image element returning before reaching the priority condition? That's part of the JSX so it should get rendered any time the `priority` attribute is set to true on the image component. Or are you asking for setting priority = true by default? That wouldn't work super well with lazy loading on by default, because `priority` deactivates lazy loading. 
The main idea behind `priority` is that you should use it on images which you think are likely to be prominent in the viewport when the page loads, in order to improve performance on metrics like [LCP](https://web.dev/lcp/)

**Comment by jakejarvis** [comment]
@atcastle Sorry, I see why that was confusing! Agree with you about the default, and I completely misread the ternaries in the snippet I linked to, so that part can be ignored -- the preload tag is indeed in the head! But `loading="lazy"` is still set on the img tag even when `priority` is present, unless I'm missing something.

Here's a quick snippet from `12.1.7-canary.8` but let me know if a whole repro and a new issue would be helpful:

JSX:
```jsx
<NextImage src={selfieJpg} layout="raw" width={50} height={50} priority />
```

HTML (note the very end):
```html
<img srcset="/_next/image/?url=%2F_next%2Fstatic%2Fmedia%2Fselfie.7d009bf4.jpg&amp;w=64&amp;q=60 1x, /_next/image/?url=%2F_next%2Fstatic%2Fmedia%2Fselfie.7d009bf4.jpg&amp;w=128&amp;q=60 2x" src="/_next/image/?url=%2F_next%2Fstatic%2Fmedia%2Fselfie.7d009bf4.jpg&amp;w=128&amp;q=60" height="50" width="50" decoding="async" data-nimg="raw" loading="lazy">
```

**Comment by styfle** [comment]
@jakejarvis Thanks for pointing this out! I created PR #37381 with the fix 👍

**Comment by jakejarvis** [comment]
Thanks so much @styfle!!

**Pull request merged**
