### PR TITLE
Add `PageNotFoundError`

### PR DESCRIPTION
**Pull request by devknoll**
Replace `err.code` checks for a `PageNotFoundError` type.

### CODE REVIEW

**Comment by kachkaev** [comment]
How about `PageNotFoundError` to reduce ambiguity? Ignore me if I misunderstood the intent of the change 🙂

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.8s | ⚠️ +104ms |
| buildDurationCached | 3.9s | 3.9s | -20ms |
| nodeModulesSize | 47 MB | 47 MB | -1.07 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.394 | 3.471 | ⚠️ +0.08 |
| / avg req/sec | 736.66 | 720.28 | ⚠️ -16.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.897 | 1.873 | -0.02 |
| /error-in-render avg req/sec | 1317.8 | 1334.76 | +16.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 26.6 kB | 26.6 kB | ⚠️ +15 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.4 kB | 70.4 kB | ⚠️ +15 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| index.html gzip | 539 B | 540 B | ⚠️ +1 B |
| link.html gzip | 552 B | 553 B | ⚠️ +1 B |
| withRouter.html gzip | 533 B | 534 B | ⚠️ +1 B |
| Overall change | 1.62 kB | 1.63 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -7267,6 +7267,22 @@
       })(/*#__PURE__*/ _wrapNativeSuper(Error));
 
       exports.DecodeError = DecodeError;
+
+      var NotFoundError = /*#__PURE__*/ (function(_Error2) {
+        _inherits(NotFoundError, _Error2);
+
+        var _super2 = _createSuper(NotFoundError);
+
+        function NotFoundError() {
+          _classCallCheck(this, NotFoundError);
+
+          return _super2.apply(this, arguments);
+        }
+
+        return NotFoundError;
+      })(/*#__PURE__*/ _wrapNativeSuper(Error));
+
+      exports.NotFoundError = NotFoundError;
       var HtmlContext = (0, _react).createContext(null);
       exports.HtmlContext = HtmlContext;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-ad70cac21e92ee5ec4ef.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-ad70cac21e92ee5ec4ef.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-ad70cac21e92ee5ec4ef.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.5s | -124ms |
| buildDurationCached | 5.3s | 5.1s | -230ms |
| nodeModulesSize | 47 MB | 47 MB | -1.07 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.365 | 3.303 | -0.06 |
| / avg req/sec | 743.03 | 756.88 | +13.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.913 | 1.869 | -0.04 |
| /error-in-render avg req/sec | 1306.65 | 1337.59 | +30.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ⚠️ +19 B |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| index.html gzip | 585 B | 586 B | ⚠️ +1 B |
| link.html gzip | 597 B | 599 B | ⚠️ +2 B |
| withRouter.html gzip | 578 B | 579 B | ⚠️ +1 B |
| Overall change | 1.76 kB | 1.76 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..c4df.HASH.js</strong></summary>

```diff
@@ -396,6 +396,22 @@
       })(/*#__PURE__*/ _wrapNativeSuper(Error));
 
       exports.DecodeError = DecodeError;
+
+      var NotFoundError = /*#__PURE__*/ (function(_Error2) {
+        _inherits(NotFoundError, _Error2);
+
+        var _super2 = _createSuper(NotFoundError);
+
+        function NotFoundError() {
+          _classCallCheck(this, NotFoundError);
+
+          return _super2.apply(this, arguments);
+        }
+
+        return NotFoundError;
+      })(/*#__PURE__*/ _wrapNativeSuper(Error));
+
+      exports.NotFoundError = NotFoundError;
       var HtmlContext = (0, _react).createContext(null);
       exports.HtmlContext = HtmlContext;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.2b97395b3bf121b2e5ed.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.2b97395b3bf121b2e5ed.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.2b97395b3bf121b2e5ed.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 669f225a74089d87b0043ffd4778e5f73cf9aff4

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 669f225a74089d87b0043ffd4778e5f73cf9aff4

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > _app syntax error shows logbox

<details>
<summary>Expand output</summary>

  ● _app syntax error shows logbox

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      1167 |     'index.js',
      1168 |     `
    > 1169 |       import Link from 'next/link'
           |                                   ^
      1170 |
      1171 |       export default function Hello() {
      1172 |         return <Link href="/">Abc</Link>

      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:1169:39)

</details>

**Comment by devknoll** [comment]
> How about `PageNotFoundError` to reduce ambiguity? Ignore me if I misunderstood the intent of the change 🙂

Yeah that makes sense. Might also keep folks from trying to reuse it for other non-page cases in the future. I'll make that change.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.8s | -174ms |
| buildDurationCached | 3.7s | 3.6s | -128ms |
| nodeModulesSize | 47 MB | 47 MB | -980 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.092 | 3.05 | -0.04 |
| / avg req/sec | 808.61 | 819.59 | +10.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.549 | 1.502 | -0.05 |
| /error-in-render avg req/sec | 1613.52 | 1664.15 | +50.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 26.6 kB | 26.6 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.4 kB | 70.4 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| index.html gzip | 539 B | 540 B | ⚠️ +1 B |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.63 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -7267,6 +7267,22 @@
       })(/*#__PURE__*/ _wrapNativeSuper(Error));
 
       exports.DecodeError = DecodeError;
+
+      var PageNotFoundError = /*#__PURE__*/ (function(_Error2) {
+        _inherits(PageNotFoundError, _Error2);
+
+        var _super2 = _createSuper(PageNotFoundError);
+
+        function PageNotFoundError() {
+          _classCallCheck(this, PageNotFoundError);
+
+          return _super2.apply(this, arguments);
+        }
+
+        return PageNotFoundError;
+      })(/*#__PURE__*/ _wrapNativeSuper(Error));
+
+      exports.PageNotFoundError = PageNotFoundError;
       var HtmlContext = (0, _react).createContext(null);
       exports.HtmlContext = HtmlContext;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-67cbc9249b07f761eca9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-67cbc9249b07f761eca9.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2b9c54dd1abc782a5acd.js"
+      src="/_next/static/chunks/main-67cbc9249b07f761eca9.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| buildDuration | 11.9s | 12.1s | ⚠️ +227ms |
| buildDurationCached | 4.9s | 4.9s | ⚠️ +34ms |
| nodeModulesSize | 47 MB | 47 MB | -980 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.202 | 3.073 | -0.13 |
| / avg req/sec | 780.67 | 813.56 | +32.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.53 | 1.574 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1634.4 | 1588.52 | ⚠️ -45.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ⚠️ +22 B |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-add-not-found-err | Change |
| - | - | - | - |
| index.html gzip | 585 B | 586 B | ⚠️ +1 B |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..c4df.HASH.js</strong></summary>

```diff
@@ -396,6 +396,22 @@
       })(/*#__PURE__*/ _wrapNativeSuper(Error));
 
       exports.DecodeError = DecodeError;
+
+      var PageNotFoundError = /*#__PURE__*/ (function(_Error2) {
+        _inherits(PageNotFoundError, _Error2);
+
+        var _super2 = _createSuper(PageNotFoundError);
+
+        function PageNotFoundError() {
+          _classCallCheck(this, PageNotFoundError);
+
+          return _super2.apply(this, arguments);
+        }
+
+        return PageNotFoundError;
+      })(/*#__PURE__*/ _wrapNativeSuper(Error));
+
+      exports.PageNotFoundError = PageNotFoundError;
       var HtmlContext = (0, _react).createContext(null);
       exports.HtmlContext = HtmlContext;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8f3ea0a0fd684024b370.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8f3ea0a0fd684024b370.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.73e10c58e501d11f73de.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8f3ea0a0fd684024b370.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: bcc250c4d1e059bd7c60d698a2cc73c48e1855a6

**Review by ijjk — APPROVED** [review]

**Pull request closed without merging**
