### PR TITLE
Update with-apollo example with next-apollo package.

### PR DESCRIPTION
**Pull request by adamsoffer**
I've abstracted the `withData` higher order component into [its own package](https://www.npmjs.com/package/next-apollo). This pull request removes the boilerplate inside the `with-apollo` example lib directory in favor of this package.

Feedback welcome.

Note: I left the other two apollo examples as is (`with-apollo-and-redux` and `with-apollo-auth`), but I'd love to see those examples get updated to Apollo Client 2.0 and using the same abstraction if someone wants to submit a pull request for those as well 🙂

### CODE REVIEW

**Comment by flipxfx** [comment]
I think there's a whole lot of use cases to not use a package for something like this and I'm not sure it should be the example. Having the boilerplate code allows the user to learn more about what's going on, setup custom auth in the wrapper, customize redux further, and add hooks to apollo. I think the example should learn more towards teaching how something works rather than "install this".

I think keeping the current example with a note in the README about this package would make more sense.

**Comment by jthegedus** [comment]
@ads1018  With a `with-next-apollo` example you could explain to users under which use cases this would be more beneficial to use. As @flipxfx pointed out there are certainly times in which you would not want to use `next-apollo`.

**Comment by ads1018** [comment]
This is a good debate. I can see both sides. The goal is for the package to eventually support those use cases (custom auth, redux integration). Until it supports them, I agree that mentioning it in the README is probably a good idea for now. I do think, ultimately, the community would benefit greatly if we showcase a robust integration package since it's much more user friendly. There's a lot of heavy lifting going on in this boilerplate and perhaps the teaching moment should happen at the package level.

**Comment by ads1018** [comment]
Closing until next-apollo package covers all use cases.

**Pull request closed without merging**
