### PR TITLE
Simplify code examples for dynamic API routes

### PR DESCRIPTION
**Pull request by devuxer**
Deep matching destructuring syntax is hard to understand and read vs. `const { ... } = req.query`.

### CODE REVIEW

**Review by leerob — DISMISSED** [review]

**Comment by timneutkens** [comment]
Linting failed on this PR.

**Review by ijjk — APPROVED** [review]

**Comment by devuxer** [comment]
@timneutkens ,

Ugh, sorry about that. I didn't realize docs get linted. I don't see any style issues with my changes, and the linting error is rather vague.

Is the problem that the whole file is being linted? I do see some code samples elsewhere in the file with double quotes (which violates `"semi": false` in the .pretterrc.json), so that could explain.

Do I need to run prettier on the whole file to submit a pull request, even if my edits are okay?

**Comment by ijjk** [comment]
Hi @devuxer if you run `yarn install` from the repo root it should set-up a pre-commit hook that takes care of this automatically. It can also be run manually from the repo root with `yarn lint-fix` if you see this step fail in CI.

**Comment by devuxer** [comment]
@ijjk, Given this was just a simple docs edit, I just used the online editor on GitHub. Is there any way to submit a docs pull request without having to leave GitHub?

**Pull request merged**
