### PR TITLE
Update 03-environment-variables.mdx

### PR DESCRIPTION
**Pull request by mltsy**
Add details about how to use loadEnvConfig correctly outside of the test env, along with examples of when this might apply.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 080525274268fd8f9d93568c3f7ff88c6e270c1c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by leerob — CHANGES_REQUESTED** [review]
This should only be added to the custom server docs. We do not recommend using an "ejected" server.

**Comment by mltsy** [comment]
@leerob - This is also relevant in next.config.js, and npm scripts that don't use next (would it be better to remove the mention of the custom server, or move it to the end of the parentheses?)

**Comment by leerob** [comment]
Could you explain more some use cases for this?

**Comment by mltsy** [comment]
Sure!  I can describe 2 specific cases I have in mind (for which we use this):

1. We have some npm scripts that just run, for instance, `sequelize db:migrate`.  This relies on at least one environment variable to specify the correct database name.  Since we generally rely on next's environment loading, we've already specified these variables in `.env.test` and `.env.development` and it's nice to just "know" those will be loaded consistently, regardless of whether we're running the next server or one of these other scripts.  More complex apps would potentially have more scripts outside of Next's control (if they use background workers, serverless jobs, etc.).

2. We use a couple environment variables in `next.config.js` - our specific use case may be controversial (we still use the legacy publicRuntimeConfig to pass env vars to the client), but regardless of that, I think it's not hard to imagine a case where someone may want to use an environment variable value somewhere in next.config.js.  Since this does not run within the context of a next server, the environment variable files are not loaded automatically.  So this case can also be accommodated by using `loadEnvConfig`.

**Pull request closed without merging**
