### PR TITLE
Examples: updated the example of head-elements to utilize the App Router

### PR DESCRIPTION
**Pull request by Sam-Phillemon9493**
This PR updates the head-elements example to use the App Router. Here are the changes that have been made:

- Renamed the "pages" folder to "app" folder.
- Updated the file `index.tsx` to `page.tsx` to align with App Router
- Added the layout.tsx file as part of the App Router.

cc @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2541681805ec753d4c8f7cc7d81503e0662ac7f2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Sam-Phillemon9493 Let me know when this is ready!

**Comment by Sam-Phillemon9493** [comment]
> @Sam-Phillemon9493 Let me know when this is ready!

@samcx PR is now ready for review. Thank You!

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
