### PR TITLE
Add `isRedirectError` export in `navigation`

### PR DESCRIPTION
**Pull request by IanMitchell**
## What

This PR adds the `isRedirectError` utility to the navigation exports. 

## Why

For API routes or Actions that rely on errors for control flow, it's difficult to handle Next.js's internal errors that come from `redirect`.

As an example, imagine you have a login API route. If the form body doesn't have a username or password, you might throw an error that indicates a bad request. If there is a user already logged in, you might want to `redirect` them to their home page. But differentiating between the two errors right now is difficult outside of importing this helper via:

```tsx
import { isRedirectError } from "next/dist/client/components/redirect";
```

Lifting the export into `next/navigation` allows for a more stable import.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0b2936c63140d2265126fcb0861b778f28fd90c0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0b2936c63140d2265126fcb0861b778f28fd90c0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by webdevcody — APPROVED** [review]

**Review by odysseaspapadimas — APPROVED** [review]

**Review by joulev — COMMENTED** [review]
If we are doing this, I suggest exporting `isNotFoundError` too.

**Comment by alvarlagerlof** [comment]
> If we are doing this, I suggest exporting `isNotFoundError` too.

Maybe `isPermanentRedirect` too if that is a thing.

**Comment by joulev** [comment]
@alvarlagerlof `permanentRedirect` also throws a `NEXT_REDIRECT` (whether it is permanent or not is stored in `error.digest`) so it is handled by `isRedirectError`.

**Comment by IanMitchell** [comment]
Hoping I can get eyes on this! It's a small quality of life thing, but I have to use this pattern a lot in my codebase and I would love to feel more confident that it will continue to work while updating Next.js versions.

```ts
"use server";

import { isRedirectError } from "next/dist/client/components/redirect";
import { redirect } from "next/navigation";

export async function create(
	formData,
) {
	const { userId } = await getSession();

	if (userId == null) {
		redirect("/login");
	}

	await database.insert(/*...*/)
	redirect(`/workspaces/${publicId}`);
	} catch (err) {
		if (isRedirectError(err)) {
			throw err;
		}

		console.error(err);
		return err.message;
	}
}
```

**Comment by lubieowoce** [comment]
We have an (unstable) function that should hopefully fulfill the same needs: https://nextjs.org/docs/app/api-reference/functions/unstable_rethrow

**Comment by IanMitchell** [comment]
Yeah, it's been a much better solution!

**Pull request closed without merging**
