### PR TITLE
Prevent caching page with 304 status

### LINKED ISSUE #56580: App router time base revalidation failure
### Link to the code that reproduces this issue

https://github.com/ehsmsh/nextjs-app-router-time-revalidation-bug

### To Reproduce

1. Build the application (yarn build)
2. Start the production server (yarn start)
3. Refresh the page a bunch of times
4. Open a private tab or a new browser (bypass cache)
5. Check the result

### Current vs. Expected behavior

The result should be revalidated based on:
```
export const revalidate = 1
```
but after some refreshes, it stops updating and returns a totally empty page. If it is stale in your current tab, try it in another browser or a private tab to bypass the browser cache and you'll see the empty page rather than the stale not revalidated data.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.17.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gffuma**
I think that sometimes when a revalidation happens from a request with caching headers this causing the 304 status to be cached.

This PR ensures the 304 from an initial response doesn't affect a background revalidation. 

Fixes: https://github.com/vercel/next.js/issues/56580

### CODE REVIEW

**Comment by gffuma** [comment]
@ijjk i understand that is not a super elegant solution, an alternative could be strip all client caching headers ex `If-None-Match` before render the request used to fill the response cache. I don't have enought confidence of the codebase to implement it but could be an idea.
BTW This is a seriois problem that prevent using static rendering in production.

**Review by ijjk — COMMENTED** [review]
Hi could we add a failing test case for this showing this resolves the issue properly?

**Comment by gffuma** [comment]
@ijjk i added a test that match the original issue race condition. It's a little bit complicated but i can't find a more clear way to emulate the race condition. Let me known if it's ok 😄

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f305ddca86e47c7fc0236115e00247158eb8ef84

`pnpm test-start test/e2e/app-dir/front-redirect-issue/front-redirect-issue.test.ts` 
- app dir - front redirect issue > should redirect

<details>
<summary>Expand output</summary>

  ● app dir - front redirect issue › should redirect

    expect(received).toBe(expected) // Object.is equality

    Expected: "http://localhost:43863/vercel-user"
    Received: "http://localhost:43863/"

      15 |           .text()
      16 |       ).toBe('Hello!')
    > 17 |       expect(await browser.url()).toBe(`${next.url}/vercel-user`)
         |                                   ^
      18 |     })
      19 |   }
      20 | )

      at Object.toBe (e2e/app-dir/front-redirect-issue/front-redirect-issue.test.ts:17:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.6s | N/A |
| buildDurationCached | 6s | 6.8s | ⚠️ +786ms |
| nodeModulesSize | 175 MB | 175 MB | ⚠️ +6.64 kB |
| nextStartRea..uration (ms) | 403ms | 401ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30 kB | 30 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33.1 kB | 33.1 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| index.html gzip | 527 B | 529 B | N/A |
| link.html gzip | 540 B | 543 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.1 kB | 96.1 kB | N/A |
| page.js gzip | 140 kB | 140 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | gffuma/next.js fix-304-cache | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 23 kB | 23 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: f305ddca86e47c7fc0236115e00247158eb8ef84

**Review by ijjk — APPROVED** [review]
Thanks for adding that, reworked the fix to handle more cases but should be good now as your added test is passing!

**Comment by mario-mestrovic** [comment]
> Thanks for adding that, reworked the fix to handle more cases but should be good now as your added test is passing!

Just thanks? You had this issue for almost 2 months now and completely ignored it not even acknowledge it exists and even issued a new 'major' along the way.
Sorry but Vercel engineering obviously has ridiculous priorities.

Thanks @gffuma you kinda saved us! You deserve 10 beers at least for this :)

**Comment by Emiliano-Bucci** [comment]
@gffuma @mario-mestrovic @ijjk Sorry guys, I've just updated next to latest version (14.0.2) which contains this fix but **it seems** that the issue is still here; could you please verify if you can reproduce?

**Comment by smuk3c** [comment]
Still broken for me as well

**Pull request merged**
