### PR TITLE
fix: grammatical error in examples readme

### PR DESCRIPTION
**Pull request by mertcanaltin**
hello I tried to solve issue #54919

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0fb0fe63c2589f654562f2597b99dc09aada73aa

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by okoyecharles** [comment]
@mertcanaltin, Thanks so much for the quick response. But I had already made a [pull request resolving this issue](https://github.com/vercel/next.js/pull/54921).

**Comment by mertcanaltin** [comment]
> @mertcanaltinHızlı yanıtınız için çok teşekkür ederiz. [Ancak bu sorunu çözmek için](https://github.com/vercel/next.js/pull/54921) zaten bir çekme isteğinde bulunmuştum .

this is great we are really really fast your hands health I'm turning off this pull request

**Comment by mertcanaltin** [comment]
> @mertcanaltin, Thanks so much for the quick response. But I had already made a [pull request resolving this issue](https://github.com/vercel/next.js/pull/54921).

this is great we are really really fast your hands health I'm turning off this pull request

**Pull request closed without merging**
