### PR TITLE
Remove ignore for anonymous stack frame

### PR DESCRIPTION
**Pull request by huozhi**
### What

We previously filter out the stack frame where the location is `<anonymous>`. Since the new ignored-list concept introduced, we don't want to filter it out by default as it's also useful in some case. At least we don't hide them for now.

This PR removes the special handling and formatting on error overlay for `<anonymous>` stack frames.

Closes NDX-544

### CODE REVIEW

**Comment by huozhi** [comment]
* **#73610** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73610?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/73610?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 60ab5fbc6e4440db2127a47c0d09eea4833e95de

`pnpm test packages/next/src/client/components/react-dev-overlay/internal/helpers/webpack-module-path.test.ts`
- webpack-module-path > formatFrameSourceFile > should return an empty string for <anonymous> file paths

<details>
<summary>Expand output</summary>

  ● webpack-module-path › formatFrameSourceFile › should return an empty string for <anonymous> file paths

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "<anonymous>"

      85 |
      86 |     it('should return an empty string for <anonymous> file paths', () => {
    > 87 |       expect(formatFrameSourceFile('<anonymous>')).toBe('')
         |                                                    ^
      88 |     })
      89 |   })
      90 | })

      at Object.toBe (../packages/next/src/client/components/react-dev-overlay/internal/helpers/webpack-module-path.test.ts:87:52)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 60ab5fbc6e4440db2127a47c0d09eea4833e95de

`pnpm test packages/next/src/client/components/react-dev-overlay/internal/helpers/webpack-module-path.test.ts`
- webpack-module-path > formatFrameSourceFile > should return an empty string for <anonymous> file paths

<details>
<summary>Expand output</summary>

  ● webpack-module-path › formatFrameSourceFile › should return an empty string for <anonymous> file paths

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "<anonymous>"

      85 |
      86 |     it('should return an empty string for <anonymous> file paths', () => {
    > 87 |       expect(formatFrameSourceFile('<anonymous>')).toBe('')
         |                                                    ^
      88 |     })
      89 |   })
      90 | })

      at Object.toBe (../packages/next/src/client/components/react-dev-overlay/internal/helpers/webpack-module-path.test.ts:87:52)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| buildDuration | 23.8s | 20.7s | N/A |
| buildDurationCached | 19.7s | 17.1s | N/A |
| nodeModulesSize | 409 MB | 409 MB | N/A |
| nextStartRea..uration (ms) | 513ms | 519ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 49.6 kB | 49.6 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.3 kB | 5.3 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 233 B | 235 B | N/A |
| main-HASH.js gzip | 33.7 kB | 33.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 513 B | 511 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.44 kB | 4.43 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| index.html gzip | 523 B | 524 B | N/A |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 519 B | 521 B | N/A |
| Overall change | 537 B | 537 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 200 kB | 200 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 666 B | 663 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.1 kB | 31.1 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| 797-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 797.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 321 kB | 321 kB | N/A |
| app-page-exp..prod.js gzip | 126 kB | 126 kB | ✓ |
| app-page-tur..prod.js gzip | 139 kB | 139 kB | ✓ |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | ✓ |
| app-page.run...dev.js gzip | 312 kB | 312 kB | N/A |
| app-page.run..prod.js gzip | 122 kB | 122 kB | ✓ |
| app-route-ex...dev.js gzip | 36.8 kB | 36.8 kB | ✓ |
| app-route-ex..prod.js gzip | 25 kB | 25 kB | ✓ |
| app-route-tu..prod.js gzip | 25 kB | 25 kB | ✓ |
| app-route-tu..prod.js gzip | 24.8 kB | 24.8 kB | ✓ |
| app-route.ru...dev.js gzip | 38.5 kB | 38.5 kB | ✓ |
| app-route.ru..prod.js gzip | 24.8 kB | 24.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-turbo...prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| pages.runtim...dev.js gzip | 27 kB | 27 kB | ✓ |
| pages.runtim..prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 1.71 MB | 1.71 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-06-remove_filter_of_anonymous | Change |
| - | - | - | - |
| 0.pack gzip | 2.04 MB | 2.04 MB | ⚠️ +2.46 kB |
| index.pack gzip | 144 kB | 145 kB | ⚠️ +1.06 kB |
| Overall change | 2.18 MB | 2.18 MB | ⚠️ +3.52 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 48e97f02d3152d19e1d4197fa7d5bdeb36e01337

**Review by eps1lon — APPROVED** [review]

**Pull request merged**
