### PR TITLE
update react remove properties to support app route

### PR DESCRIPTION
**Pull request by niketchandivade**
This PR updates the react-remove-properties example to use the App Router. Here are the changes that have been made:

Renamed the "pages" folder to the "app" folder.
Updated the routing for / files to align with the App Router.
Added the layout.tsx file as part of the App Router.
CC @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d64cffdf8d48646290c4a5c3181db4e26c998311

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@niketchandivade Let's make sure to bump packages next time!

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by niketchandivade** [comment]
> @niketchandivade Let's make sure to bump packages next time!

sure

**Pull request merged**
