### PR TITLE
README: improve getting started & contributing

### PR DESCRIPTION
**Pull request by flybayer**
This addresses some things I was first confused by and some common confusions like the `.next` directory.

It also adds a `Contributing` and `Background & Design Philosophy` section.

### CODE REVIEW

**Comment by rauchg** [comment]
Needs rebase since we improved the first section already. The rest should be interesting though!

**Comment by flybayer** [comment]
@rauchg rebased!

As you can see, I propose abandoning `npm run dev` in favor of using `npm start` for development (same as Hyper.app, create-react-app, etc.). Then use `scripts.now-start` for production. I've found I really like using `scripts.now-start` because it's very clear what it's for.

**Comment by sedubois** [comment]
Shouldn't `scripts.start` be reserved for the production start? Like mentioned here: https://zeit.co/blog/now-static#single-page-applications

**Comment by flybayer** [comment]
@sedubois, see the `*Side Note:*` right below that blog post section. As [documented here](https://zeit.co/now#how-does-my-app-detect-now), `now` will first use `now-start` and `now-build` if they're available.

**Comment by zpnk** [comment]
@flybayer `now-start` as the production start command may not make sense here given that `next` can be deployed to any platform.

**Comment by rauchg** [comment]
Honestly I like the idea of being _explicit_ about development. We routinely get error reports from people trying to launch dev environments to production (not just to now, but really we've seen every PaaS).

This problem is similarly experienced with React, where the default is _dev_, and production is `.min.js`, which leads to a lot of people deploying dev code to production or inaccurate benchmarks.

**Comment by flybayer** [comment]
Ok, I've updated this PR to use `scripts.dev` for development instead of `scripts.start`.

**Review by rauchg — CHANGES_REQUESTED** [review]
We can still improve the 1,2,3 I think

**Comment by flybayer** [comment]
@rauchg I reworked the beginning a bit. Do you like this better?

**Comment by rauchg** [comment]
I believe we've improved this now. A better Contributing section in a different PR would be sweet though

**Pull request closed without merging**
