### PR TITLE
Add decoratorMetadata flag if enabled by tsconfig

### LINKED ISSUE #32913: Missing `"decoratorMetadata": true` in swc config causes metadata based libraries to fail.
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The flag `"decoratorMetadata": true` is not enabled thus SWC does not emit Typescript decorator metadata which causes libraries like [next-api-decorators](https://next-api-decorators.vercel.app/) and `class-validator` to fail trying to look for metadata like `Reflect.getMetadata("design:type")`.

### Expected Behavior

SWC config should be configured to support decorator metadata. 

At the very least this support should be enabled automatically when tsconfig includes the flag `"emitDecoratorMetadata": true`

### To Reproduce

1. Clone: https://github.com/sannajammeh/decorator-metadata-fail
2. Start the dev server
3. Navigate to /api/something in the browser
4. Watch it fail due to an internal issue in the handler which directly comes from a Reflect.getMetadata call at [this line](https://github.com/storyofams/next-api-decorators/blob/ed21529abc8194f6dabfee1d3fcf187f1dc55993/lib/internals/handler.ts#L70)
5. Remove the _ from `.babelrc_`.
6. Restart the dev server
7. Repeat step 3 and watch it work

### PR DESCRIPTION
**Pull request by sannajammeh**
fixes #32913
Adds support for decorator metadata in SWC when enabled through ts/jsconfig.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by lucalves — DISMISSED** [review]

**Comment by egoist** [comment]
Maybe also add a `keepClassNames` option? It's often used with decorator metadata: https://github.com/swc-project/swc/issues/1656

**Comment by sannajammeh** [comment]
> Maybe also add a `keepClassNames` option? It's often used with decorator metadata: [swc-project/swc#1656](https://github.com/swc-project/swc/issues/1656)

I agree, enabling `keepClassNames` would be ideal. However, according to SWC, this requires the target to be ES2016 or upper.

**Comment by abriginets** [comment]
Is there any chance to get this accross the line soon?

**Review by timneutkens — CHANGES_REQUESTED** [review]
This is missing an integration test to verify that the change works.

**Comment by abriginets** [comment]
@sannajammeh I've prepared integration tests for you but for some reason I can't push my changes to your PR here. Will you be so kind and add them to this PR?
<details> 
  <summary>test/development/basic/emit-decorator-metadata.test.ts</summary>

```ts
import { join } from 'path'
import webdriver from 'next-webdriver'
import { createNext, FileRef } from 'e2e-utils'
import { NextInstance } from 'test/lib/next-modes/base'
import { BrowserInterface } from 'test/lib/browsers/base'

describe('emitDecoratorMetadata SWC option', () => {
  let next: NextInstance

  beforeAll(async () => {
    next = await createNext({
      files: {
        'jsconfig.json': new FileRef(
          join(__dirname, 'emit-decorator-metadata/jsconfig.json')
        ),
        pages: new FileRef(join(__dirname, 'emit-decorator-metadata/pages')),
      },
    })
  })

  afterAll(() => next.destroy())

  it('should compile with emitDecoratorMetadata enabled', async () => {
    let browser: BrowserInterface;
    try {
      browser = await webdriver(next.appPort, '/')
      const message = await browser.elementByCss('#message').text()

      expect(message).toBe('Hello, world!')
    } finally {
      if (browser) {
        await browser.close()
      }
    }
  })
})
```
</details>
<details>
<summary>test/development/basic/emit-decorator-metadata/jsconfig.json</summary>

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "jsx":"preserve"
    },
}
```
</details>
<details>
<summary>test/development/basic/emit-decorator-metadata/pages/index.tsx</summary>

```tsx
import React from 'react';
import 'reflect-metadata';
import { container, singleton } from 'tsyringe';

@singleton()
export class HelloService {
    getHello() {
        return 'Hello, world!';
    }
}

const helloService = container.resolve(HelloService);

export default function Home() {
    const message = helloService.getHello();
    
    return <p id="message">{message}</p>;
}
```
</details>

Also you need to add tsyringe and reflect-metadata as dev dependencies with the following command:
```bash
yarn add reflect-metadata tsyringe -D -W
```

**Comment by edw19** [comment]
how's it going ? is it already possible to use emitDecoratorMetadata in nextjs 12 ?

**Comment by edw19** [comment]
how's it going ? is it already possible to use emitDecoratorMetadata in nextjs 12 ?

**Comment by edw19** [comment]
asdfasdf

**Comment by boredland** [comment]
this would be quite awesome when added! thank for for your work!

**Comment by sannajammeh** [comment]
@abriginets Appreciate these you adding these tests! I have added them to this PR.

**Review by timneutkens — DISMISSED** [review]
Looks fine to land now if it passes the tests, thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.5s | ⚠️ +116ms |
| buildDurationCached | 3.2s | 3.2s | -13ms |
| nodeModulesSize | 355 MB | 355 MB | ⚠️ +544 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.982 | 2.96 | -0.02 |
| / avg req/sec | 838.23 | 844.55 | +6.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.338 | 1.384 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1867.89 | 1806.02 | ⚠️ -61.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.7 kB | 4.7 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| buildDuration | 17.6s | 17.6s | -20ms |
| buildDurationCached | 3.2s | 3.1s | -64ms |
| nodeModulesSize | 355 MB | 355 MB | ⚠️ +544 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.911 | 2.926 | ⚠️ +0.02 |
| / avg req/sec | 858.75 | 854.47 | ⚠️ -4.28 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.363 | 1.368 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1834.1 | 1828.01 | ⚠️ -6.09 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 67c83c09b011e64fecf36173d7ddf1a833ef5abe

**Comment by sannajammeh** [comment]
```
Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (5:0)
```
This seems to be the only issue currently. Not sure what is causing it as the legacy-decorators test uses the same method without presenting a parser issue.

**Comment by timneutkens** [comment]
> ```
> Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (5:0)
> ```
> 
> This seems to be the only issue currently. Not sure what is causing it as the legacy-decorators test uses the same method without presenting a parser issue.

I'm assuming it's Eslint

**Comment by boredland** [comment]
> > This seems to be the only issue currently. Not sure what is causing it as the legacy-decorators test uses the same method without presenting a parser issue.
> 
> I'm assuming it's Eslint

I guess this is due to eslint using babel under the hood, isn't it? shouldn't we then be able to add sth like along the lines of this to the eslint config?

```
"parserOptions": {
    ...
    "babelOptions": {
      "plugins":  ["@babel/plugin-proposal-decorators", { "legacy": true }],
    },
  },
```

**Comment by abriginets** [comment]
> ```
> Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (5:0)
> ```
> 
> This seems to be the only issue currently. Not sure what is causing it as the legacy-decorators test uses the same method without presenting a parser issue.

If it's eslint that is not satisfied with the code you should just add a comment to eslint-ignore it. I'm not sure what Next.js team's opinion is about ignoring linter issues but we do it all the time as long those issues occurs in test files and not in the actual runtime codebase.

**Comment by timneutkens** [comment]
The particular file can be eslint ignored as it's a test file. Main question this raises for me is if the eslint integration in Next.js will error on this as well 🤔

**Comment by sannajammeh** [comment]
> The particular file can be eslint ignored as it's a test file. Main question this raises for me is if the eslint integration in Next.js will error on this as well 🤔

Not sure. I have been running decorators with Next JS 12 without SWC and faced no linter issues. 
Should be ok to just ignore the file.

**Comment by boredland** [comment]
> Not sure. I have been running decorators with Next JS 12 without SWC and faced no linter issues.
> Should be ok to just ignore the file.

I can confirm this. Using decorators with a custom babel config rn without an eslint issue (or any special config there).

**Comment by sannajammeh** [comment]
Is any movement possible here?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.5s | ⚠️ +131ms |
| buildDurationCached | 6s | 6s | -20ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +543 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.179 | 3.222 | ⚠️ +0.04 |
| / avg req/sec | 786.3 | 775.82 | ⚠️ -10.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.328 | 1.353 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1881.83 | 1847.93 | ⚠️ -33.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| buildDuration | 18.7s | 19s | ⚠️ +241ms |
| buildDurationCached | 6s | 6s | -14ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +543 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.174 | 3.172 | 0 |
| / avg req/sec | 787.6 | 788.19 | +0.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.324 | 1.315 | -0.01 |
| /error-in-render avg req/sec | 1888.56 | 1900.5 | +11.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sannajammeh/next.js add/emit-decorator-metadata | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 9b9190a1df7fb7caa966caf3368cfc0923b6be08

**Review by ijjk — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
