### PR TITLE
Repair the development mode to judge that the internal directory is not rigorous

### PR DESCRIPTION
**Pull request by sbfkcel**
Repair the development mode to judge that the internal directory is not rigorous https://github.com/vercel/next.js/issues/53837

### CODE REVIEW

**Comment by sbfkcel** [comment]
Adjustment instructions

**Comment by u1x30** [comment]
Thank you for working on this, can you please provide a NextJS version we can use while we wait for the fix to be available? This issue is causing requests to fail which is impacting development progress.  Any insight on what version of NextJS to revert to would be greatly appreciated.

**Comment by sbfkcel** [comment]
> #53837


It is possible to revert the version to 13.4.12

**Comment by u1x30** [comment]
Thank you sbfkcel.

Updated to 13.4.12, deleted npm_modules, cleared caches, deleted .next directory, and rebuilt npm_modules from scratch.

package.json:
    "next": "^13.4.12",

Unfortunately, the issue is not resolved.

This issue is becoming a blocking issue for us and starting to impact development/QA testing timelines.  As indicated, it causing requests to fail which causes tests cases to fail and impeding delivery.

If you can please get this blocking issue available soon, would be helpful.

Thank you for all of your efforts to resolve this issue. It is appreciated.

**Comment by u1x30** [comment]
Hi sbfkcel - Please give us a build number that works 100% or release this fix. This is costing our project thousands of dollars and counting. We are dead in the water here, for example, our redux AsyncThunks are failing to load, other API calls are failing. Our application is unusable as it happens when user logs in, and continues through the app.

We trust Next to be a stable product. What app does not use GET API calls? It's core functionality and puzzled how Next can release builds that breaks simple GET API calls. 

We are exhausted and all we need to do is an API call to fetch data for the UI but unfortunately Next cannot handle it :-(.

Update would be greatly appreciated.

Please help us.

**Comment by sbfkcel** [comment]
`"next": "13.2.4"` instead of `"next": "^13.2.4"`

Note, delete your `package-lock.json`

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for these changes and comments as to what you're checking? This change is quite hard to understand as you're reusing a variable called `isInsideAppDir` that also checks `pages/api` and is true for `pages/api` 🤔

**Review by sbfkcel — COMMENTED** [review]
`isInsideAppDir` refers to the directory with automatic routing function in the `next` project.
In the new version of `next`, the `pages/api` and `app` directories are all effective automatic routing function directories.

**Comment by u1x30** [comment]
Hi - is this going to get fixed, or are we have not choice but to use app/api directory after 13.2.4? Do not see fix in 13.5.1.

**Pull request closed without merging**
