### PR TITLE
Remove flow types

### PR DESCRIPTION
**Pull request by timneutkens**
Will be replaced by Typescript soon.

### CODE REVIEW

**Comment by romainquellec** [comment]
oh nice !

**Comment by yury** [comment]
Just curious, why TS?

**Comment by timneutkens** [comment]
It has typings for nearly all modules we use, webpack is typed in typescript, meaning it'll quite literally be faster to develop using typescript. I still like Flow, it's type system is 💯 It's just way less convenient in this case.

**Comment by YUFENGWANG** [comment]
TS, YES!

**Comment by dmytro-lymarenko** [comment]
TS ;)

**Comment by codinronan** [comment]
@timneutkens 💯 awesome news.

Yeah TS is kinda viral in that way, if your upstream packages are using them, your dev pace is much faster if you use them too, much less referring back to documentation...

**Pull request merged**
