### PR TITLE
Add ant design example

### PR DESCRIPTION
**Pull request by afc163**
Ant Design of React is a set of great React UI components.

- https://github.com/ant-design/ant-design/
- https://ant.design/
- https://ant.design/docs/react/introduce

### CODE REVIEW

**Comment by lednhatkhanh** [comment]
Wow, tks for the example

**Comment by sorin-davidoi** [comment]
`app.js` is `1.5MB` in the production build - I guess this imports the entire library. Might be worth a try using [the modularized version](https://ant.design/docs/react/introduce#Use-modularized-antd) to reduce the payload size.

**Comment by sorin-davidoi** [comment]
Switching to explicit imports cuts the size in half (`804KB`). While more verbose, I think we should encourage this, since the bundle reduction is significant.

```js
import Form from "antd/lib/form";
import Select from "antd/lib/select";
import InputNumber from "antd/lib/input-number";
import DatePicker from "antd/lib/date-picker";
import Switch from "antd/lib/switch";
import Slider from "antd/lib/slider";
import Button from "antd/lib/button";

import LocaleProvider from "antd/lib/locale-provider";
import enUS from "antd/lib/locale-provider/en_US";
```

**Comment by afc163** [comment]
@sorin-davidoi I just added https://github.com/ant-design/babel-plugin-import

**Comment by ugiacoman** [comment]
@afc163 Thank you for this!

**Comment by lednhatkhanh** [comment]
Hello, I got this warning when trying to run the example: `Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by afc163** [comment]
It is still working in progress: https://github.com/ant-design/ant-design/issues/5678

I just lock react to `15.4` for now.

**Comment by afc163** [comment]
ping~

**Review by timneutkens — APPROVED** [review]
Thanks! ❤️

**Pull request merged**
