### PR TITLE
Update tsconfig of example to be consistent with default output of next.js

### PR DESCRIPTION
**Pull request by daku10**
remove `alwaysStrict: true` rule from tsconfig.json in with-typescript example, because the rule is included in `strict: true` has been already written in tsconfig.json and other included rules such as `noImplicitAny: true` have not been written.  

[tsconfig documentation link](https://www.typescriptlang.org/tsconfig#alwaysStrict)

## Documentation / Examples

- [x] Make sure the linting passes

### CODE REVIEW

**Review by leerob — CHANGES_REQUESTED** [review]
Has this been removed from the default TypeScript setup as well? It seems so. We should probably update these ones too: https://github.com/vercel/next.js/search?q=alwaysStrict

**Comment by daku10** [comment]
Thanks for reviewing!
I'm not sure what is `the default TypeScript setup` but probably you are right.
This tsconfig is different from [one of current next.js created](https://nextjs.org/learn/excel/typescript/create-tsconfig) and also one of `tsc --init` of Typescript@4.0.
This tsconfig is similar to one of the next.js official, but it is stricter than the official one.
What should I do?

Below is a sample of next.js 10.2.3 created
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by daku10** [comment]
I am not sure what is the best tsconfig for examples, but all of tsconfig of examples you suggested has the redundant rule.
Therefore I pushed a commit to remove them.
I can squash commits, if this pull request is approved.

**Comment by leerob** [comment]
Let's be consistent with the default output of new Next.js projects 😄

**Comment by daku10** [comment]
Thank you for replying!
I updated tsconfig of examples [you suggested](https://github.com/vercel/next.js/pull/25581#pullrequestreview-671897800) to be consistent with the default output except `with-electron-typescript/electron-src/tsconfig.json`, because it is not next.js project. 
p.s. `with-electron-typescript/renderer/tsconfig` is a next.js project and updated.

**Review by leerob — DISMISSED** [review]
Awesome, thank you!

**Comment by daku10** [comment]
Sorry to bother you, I forgot to apply format
Finally I understand meaning  of `Make sure the linting passes` in the pull request format.

**Review by leerob — APPROVED** [review]

**Pull request merged**
