### PR TITLE
Only ignore `sharp` if it's installed

### LINKED ISSUE #20456: sharp no longer optional since 10.0.4-canary.7
# Bug report

## Describe the bug

Next.js has an optional dependency on sharp. This means that it should run without sharp present in node_modules.

PR #20035 broke this by adding `require.resolve('sharp')` without a try/catch to catch `MODULE_NOT_FOUND`.

I discovered this because sharp no longer installs with NPM 7 (see #20432).

## To Reproduce

npm i next@10.0.4-canary.7
rimraf node_modules/sharp
npm run build

> > Build error occurred
> Error: Cannot find module 'sharp'
> Require stack:
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\build\index.js
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\cli\next-build.js
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\bin\next
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
>     at build (C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\build\index.js:11:794) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\build\\index.js',
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\cli\\next-build.js',
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\bin\\next'
>   ]
> }

## Expected behavior

The site builds OK.

- OS: Windows or Linux (alpine in docker)
- Version of Next.js: 10.0.4-canary.7 and up
- Version of Node.js: 14 (latest)
- Deployment: fails on build

### PR DESCRIPTION
**Pull request by valenfys**
Fixes #20456

PR #20738 should probably be preferred, which I didn't spot before opening this PR

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 8.7s | 8.6s | -63ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.723 | 1.791 | ⚠️ +0.07 |
| / avg req/sec | 1450.7 | 1395.57 | ⚠️ -55.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.06 | 1.077 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2357.46 | 2321.57 | ⚠️ -35.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.4s | ⚠️ +139ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.5s | -314ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.814 | 1.707 | -0.11 |
| / avg req/sec | 1378.53 | 1464.87 | +86.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.123 | 1.083 | -0.04 |
| /error-in-render avg req/sec | 2226.68 | 2307.53 | +80.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "4NqfZXIvJK2cpZv5uw_rO",
+        "buildId": "LnuwP_kr5rQynNqfRoqBz",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_buildManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_ssgManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "4NqfZXIvJK2cpZv5uw_rO",
+        "buildId": "LnuwP_kr5rQynNqfRoqBz",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_buildManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_ssgManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "4NqfZXIvJK2cpZv5uw_rO",
+        "buildId": "LnuwP_kr5rQynNqfRoqBz",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_buildManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4NqfZXIvJK2cpZv5uw_rO/_ssgManifest.js"
+      src="/_next/static/LnuwP_kr5rQynNqfRoqBz/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 850219e72bc0ec818d3989704819fd89cfd49f50

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 10s | 10.2s | ⚠️ +251ms |
| nodeModulesSize | 75.1 MB | 75.1 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.008 | 1.973 | -0.03 |
| / avg req/sec | 1245.28 | 1267.11 | +21.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.231 | 1.241 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2030.59 | 2013.72 | ⚠️ -16.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 12s | 11.8s | -111ms |
| nodeModulesSize | 75.1 MB | 75.1 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.4s | ⚠️ +393ms |
| nodeModulesSize | 75.1 MB | 75.1 MB | ⚠️ +297 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.036 | 1.985 | -0.05 |
| / avg req/sec | 1227.83 | 1259.54 | +31.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.303 | 1.271 | -0.03 |
| /error-in-render avg req/sec | 1919.28 | 1967.3 | +48.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | davidbailey00/next.js fix-sharp-require | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 590 B | 590 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "6lyMVZ8MNggdP8_ImLudK",
+        "buildId": "JKwPrnswN6UfKJEhfJPZx",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_buildManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_ssgManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "6lyMVZ8MNggdP8_ImLudK",
+        "buildId": "JKwPrnswN6UfKJEhfJPZx",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_buildManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_ssgManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "6lyMVZ8MNggdP8_ImLudK",
+        "buildId": "JKwPrnswN6UfKJEhfJPZx",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_buildManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/6lyMVZ8MNggdP8_ImLudK/_ssgManifest.js"
+      src="/_next/static/JKwPrnswN6UfKJEhfJPZx/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 1081c0b632278dcecccecfa5e08f0865518cee9b

**Comment by jorrit** [comment]
Duplicate of #20738, but your solution is fine too.

**Comment by davidbailey00** [comment]
@jorrit ah thanks for pointing out - I'll leave you to decide which to merge, although it looks like the other PR may be the better choice seeing as it has a test 👍🏻

**Comment by jorrit** [comment]
I'm not a maintainer, I'll leave it to them. The reason my PR was ignored (I think) was because I forgot to un-draft it.

**Comment by davidbailey00** [comment]
Closing due to lack of response from maintainers and I think #20738 should be preferred due to tests - feel free to reopen if this PR is helpful :)

**Pull request closed without merging**
