### PR TITLE
Fixes issue with makeStylesheetInert

### LINKED ISSUE #32024: Font optimization can result in error: "TypeError: Cannot read property 'type' of null"
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

12.22.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When a child element or fragment of the `Head` component contains a falsely value in its children then the following build/runtime error will surface,`"TypeError: Cannot read property 'type' of null"`. This error can surface at runtime or at build time depending on the build method being used. The SWC build system will surface the error at build time while the legacy build methodology will result in a runtime error. 

### Expected Behavior

Falsey child elements of elements contained within the `Head` component should not result in a build/runtime error. 

### To Reproduce

1. Place the following snippet of code in your`_document.js`.

```
<Head>
    <>
        {/* falsy child elements are not removed. This will result in 'null' when makeStylesheetInert is called recursively. */}
        {null}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" />
   </>
 </Head>
 ```
2. Run `yarn build`.  
_*Note: If you are using SWC the error will surface on step here._
3. Run `yarn start`.
4. Visit any page.

Please see the following [repo](https://github.com/dm430/next-bug-repro) for reproduction.

### PR DESCRIPTION
**Pull request by dm430**
Fixes https://github.com/vercel/next.js/issues/32024

Fixing makeStylesheetInert.
Fixes log import.

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, could you add a test for this to ensure we don't regress on this? We could potentially add this case to the `_document` in the font-optimization test [here](https://github.com/vercel/next.js/blob/12597f282205889ee023b2b5d5f7df6d099c6551/test/integration/font-optimization/fixtures/with-google/pages/_document.js)

**Comment by DevinWallKcl** [comment]
> Hi, could you add a test for this to ensure we don't regress on this? We could potentially add this case to the `_document` in the font-optimization test [here](https://github.com/vercel/next.js/blob/12597f282205889ee023b2b5d5f7df6d099c6551/test/integration/font-optimization/fixtures/with-google/pages/_document.js)

I can take a look at adding something tomorrow if I get some time. If not then I will have some time to address this over the weekend.

**Comment by DevinWallKcl** [comment]
@ijjk Ive added a regression test. Let me know if you need anything else, or need me to change anything about the test.

**Review by ijjk — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +147ms |
| buildDurationCached | 3.2s | 3.2s | -17ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.873 | 2.888 | ⚠️ +0.01 |
| / avg req/sec | 870.07 | 865.58 | ⚠️ -4.49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.338 | 1.315 | -0.02 |
| /error-in-render avg req/sec | 1867.8 | 1900.65 | +32.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.1 kB | 27.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.9 kB | 70.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.74 kB | 4.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.5s | -6ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +31ms |
| nodeModulesSize | 348 MB | 348 MB | ⚠️ +1.26 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.916 | 2.901 | -0.02 |
| / avg req/sec | 857.27 | 861.81 | +4.54 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.343 | 1.346 | 0 |
| /error-in-render avg req/sec | 1861.37 | 1858.04 | ⚠️ -3.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.1 kB | 71.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | dm430/next.js dm430/fix-32024 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 7d832229cab8156050505b507f351d3abc2dde91

**Pull request merged**
