### PR TITLE
Add monaco-editor example

### PR DESCRIPTION
**Pull request by Ehesp**
Example shows how to add the Monaco Editor to a NextJS project.

### CODE REVIEW

**Comment by Ehesp** [comment]
Not sure if the failing CI is an issue on my end?

**Review by lfades — APPROVED** [review]
Tested and it works, the build time is quite slow, 58s for the first build, 14s for a second build, but I don't see how to improve that :thinking:. It's most likely the webpack config for monaco-editor.

@Timer I'll let you do a final review and merge it if the webpack config looks okay to you :pray:. It's using `@zeit/next-css` which is not ideal, but it doesn't work without it

**Comment by Janpot** [comment]
@Ehesp FYI: Using
```js
   config.module.rules.push({
      include: path.resolve('./node_modules/monaco-editor'),
      test: /\.ttf$/,
      use: [{
        loader: 'file-loader',
        options: {
          outputPath: 'static/',
        }
      }]
    })
```
to load the fonts instead of `next-fonts` made it unnecessary for me to patch `getWorkerUrl`. There's probably cleaner ways, but with these slow build times I'm gonna explore alternatives before picking this back up.

**Review by Timer — APPROVED** [review]
Looks fine to me for now. Thanks!

**Pull request merged**
