### PR TITLE
add firebase example

### PR DESCRIPTION
**Pull request by captDaylight**
Quickly set up authentication and a real time database via firebase.

mar-21-2017 22-13-00

Ref #820

### CODE REVIEW

**Comment by tezhub** [comment]
@captDaylight Thanks for the example, is it possible to have next.js hook up with Firebase and have the data rendered server side with auth and private routes ?

**Comment by captDaylight** [comment]
@tezhub I'm new to Firebase, but having a look around it seems it can be [hooked](https://firebase.google.com/docs/admin/setup) [up](https://firebase.googleblog.com/2016/11/bringing-firebase-to-your-server.html). However, since firebase is run generally on the client maybe it's best to keep this example on the client. I can imagine firebase-server being a separate example but I'm open to hearing what others think!

**Comment by lukeed** [comment]
>  is it possible to have next.js hook up with Firebase

@tezhub @captDaylight Yes, you can. Start from the `custom-server` example and work Firebase into that. Your main decisions will be: 

1. Do I need `firebase-admin` or `firebase`? 
2. Am I going to use Firebase's built-in Auth systems, or generate custom JWT tokens?
3. With either package, how will I want to store the Auth token/session & pass that info along to my database?

If you're going to use Firebase's done-for-you authentication, then you'll need a minimum of `firebase-app` and `firebase-auth` on the client. That's enough to give you what you need, as well as the tools to send the server what _it_ needs to figure out who's who. Everything else can be done server-side.

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/1756

**Pull request closed without merging**
