### PR TITLE
with apollo and redux example: Update deps and fix build

### PR DESCRIPTION
**Pull request by crutchcorn**
Bumps dependencies for `apollo-and-redux` example. `next-redux-wrapper` major bump introduced breaking changes, which this merge fixes

### CODE REVIEW

**Review by lfades — CHANGES_REQUESTED** [review]
Hi @crutchcorn Thank you for the PR, LGTM, can you run the linter please ? 💯

**Comment by crutchcorn** [comment]
I'm waiting on !6732 before doing so @lfades, that way the potential for merge conflicts is lowered. Once that is merged, I'll fix this up with linter fixes

**Comment by crutchcorn** [comment]
Linting ran 🧼 Should be ready to roll @lfades 🙇‍♂️

**Review by lfades — APPROVED** [review]

**Comment by lfades** [comment]
@crutchcorn Thank you 💯

**Pull request merged**
