### PR TITLE
Fix app ISR error handling

### LINKED ISSUE #53195: Server Error leaks into Client on revalidation
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.33.0
    Relevant Packages:
      next: 13.4.13-canary.3
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/basementstudio/app-dir-example/tree/canary

### To Reproduce

In the index page, we perform a `fetch` to get a list of Pokemons. We set the revalidate for the `fetch` to `1`, for us to see the issue more frequently. The catch here is that we are randomly `throw`ing an error. Preview is [here](https://app-dir-example-git-canary-basement.vercel.app/).

Steps to reproduce:

1. Start session in https://app-dir-example-git-canary-basement.vercel.app/example#with-hash
2. Navigate to the home page (”Home” link in header)
3. If you don’t yet see the Application Error, go back to Example (”Go to title in content” link) and click Refresh
4. Repeat steps 2 and 3 until you see the Application Error

### Describe the Bug

When any error is thrown server-side, the client shows an application exception on navigation.

Screenshot 2023-07-26 at 01 42 29

### Expected Behavior

After a failure during revalidation, the app should display the data from the last successful revalidation.
From Next.js Docs:

> If an error is thrown while attempting to revalidate data, the last successfully generated data will continue to be served from the cache. On the next subsequent request, Next.js will retry revalidating the data.

### Which browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Vercel

### PR DESCRIPTION
**Pull request by ijjk**
This ensures when an error occurs during a revalidate in app router that properly throw the error fully and don't store the error page in the cache which matches the expected behavior for full route ISR as errors are not meant to update the cache so that the last successful cache entry can continue being served. 

Fix was tested against the provided reproduction here https://app-dir-example-ghl01cxtn-basement.vercel.app/

Fixes: https://github.com/vercel/next.js/issues/53195

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.4s | N/A |
| buildDurationCached | 6s | 6s | N/A |
| nodeModulesSize | 175 MB | 175 MB | ⚠️ +5.6 kB |
| nextStartRea..uration (ms) | 399ms | 401ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| 199-HASH.js gzip | 29.8 kB | 29.9 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | N/A |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33 kB | 33 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 45.7 kB | 45.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | ✓ |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 318 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.99 kB | 3.99 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.6 kB | 95.6 kB | N/A |
| page.js gzip | 138 kB | 138 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-revalidate-error-handling | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 624 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.9 kB | 22.9 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>199-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 260b80bad8d55d0af396e01b98163b090590beb2

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 260b80bad8d55d0af396e01b98163b090590beb2

`pnpm test-start test/e2e/app-dir/app-static/app-static-custom-handler.test.ts` 
- app-dir static/dynamic handling > should output HTML/RSC files for static paths
- app-dir static/dynamic handling > should have correct prerender-manifest entries
- app-dir static/dynamic handling > should correctly error and not update cache for ISR

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should output HTML/RSC files for static paths

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 4

    @@ -93,10 +93,14 @@
        "hooks/use-search-params/with-suspense.rsc",
        "hooks/use-search-params/with-suspense/page.js",
        "hooks/use-search-params/with-suspense/page_client-reference-manifest.js",
        "index.html",
        "index.rsc",
    +   "isr-error-handling.html",
    +   "isr-error-handling.rsc",
    +   "isr-error-handling/page.js",
    +   "isr-error-handling/page_client-reference-manifest.js",
        "no-store/dynamic/page.js",
        "no-store/dynamic/page_client-reference-manifest.js",
        "no-store/static.html",
        "no-store/static.rsc",
        "no-store/static/page.js",

      487 |           })
      488 |
    > 489 |         expect(files.sort()).toEqual(
          |                              ^
      490 |           [
      491 |             '_not-found.html',
      492 |             '_not-found.js',

      at Object.toEqual (e2e/app-dir/app-static/app-static.test.ts:489:30)

  ● app-dir static/dynamic handling › should have correct prerender-manifest entries

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `app-dir static/dynamic handling should have correct prerender-manifest entries 1`

    - Snapshot  -  0
    + Received  + 16

    @@ -269,10 +269,26 @@
            },
          ],
          "initialRevalidateSeconds": false,
          "srcRoute": "/hooks/use-search-params/with-suspense",
        },
    +   "/isr-error-handling": {
    +     "dataRoute": "/isr-error-handling.rsc",
    +     "experimentalBypassFor": [
    +       {
    +         "key": "Next-Action",
    +         "type": "header",
    +       },
    +       {
    +         "key": "content-type",
    +         "type": "header",
    +         "value": "multipart/form-data",
    +       },
    +     ],
    +     "initialRevalidateSeconds": 3,
    +     "srcRoute": "/isr-error-handling",
    +   },
        "/no-store/static": {
          "dataRoute": "/no-store/static.rsc",
          "experimentalBypassFor": [
            {
              "key": "Next-Action",

      754 |
      755 |         expect(curManifest.version).toBe(4)
    > 756 |         expect(curManifest.routes).toMatchInlineSnapshot(`
          |                                    ^
      757 |           {
      758 |             "/": {
      759 |               "dataRoute": "/index.rsc",

      at Object.toMatchInlineSnapshot (e2e/app-dir/app-static/app-static.test.ts:756:36)

  ● app-dir static/dynamic handling › should correctly error and not update cache for ISR

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      1667 |           const now = $('#now').text()
      1668 |
    > 1669 |           expect(res.status).toBe(200)
           |                              ^
      1670 |           expect(now).toBeTruthy()
      1671 |
      1672 |           // wait revalidate period

      at Object.toBe (e2e/app-dir/app-static/app-static.test.ts:1669:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 07b098c0e2fb296ff2b914d74aa664d1467d69d2

`pnpm test-start test/e2e/app-dir/app-static/app-static-custom-handler.test.ts` 
- app-dir static/dynamic handling > should correctly error and not update cache for ISR

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should correctly error and not update cache for ISR

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      1687 |           const now = $('#now').text()
      1688 |
    > 1689 |           expect(res.status).toBe(200)
           |                              ^
      1690 |           expect(now).toBeTruthy()
      1691 |
      1692 |           // wait revalidate period

      at Object.toBe (e2e/app-dir/app-static/app-static.test.ts:1689:30)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 409c2f0f37a9cb2789235754161faffaa92ba5a6

`pnpm test test/integration/create-next-app/index.test.ts` 
- create next app > valid example without package.json

<details>
<summary>Expand output</summary>

  ● create next app › valid example without package.json

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      148 |   })
      149 |
    > 150 |   it('valid example without package.json', async () => {
          |   ^
      151 |     await useTempDir(async (cwd) => {
      152 |       const projectName = 'valid-example-without-package-json'
      153 |       const res = await run(

      at it (integration/create-next-app/index.test.ts:150:3)
      at Object.describe (integration/create-next-app/index.test.ts:40:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ztanner — APPROVED** [review]

**Pull request merged**
