### PR TITLE
Fix for index.js pages inside a folder named 'index'

### LINKED ISSUE #6285: Index routes won't be executed in client when index.js is located in /index/index.js
# Bug report

When you build next.js when the index page is located in `/index/index.js` instead of `/index.js` The client side script will not be executed when you access `http://localhost/`.

The built index page will register with `/index` (as shown below)

```js
(window.__NEXT_P = window.__NEXT_P || []).push(["/index", function () {
  var e = n("gDgk");
  return {
    page: e.default || e
  }
}])
```

Moving the index.js to the pages root will restore the wanted behaviour.
It took a while for me to figure out what the actual issue is as it's working just fine in dev mode. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Check out https://github.com/adlk/nextjs-index-issue
2. Run `npm install && npm run build && npm start`
3. Check in DevTools if you have a log with `Home: component did mount`

## System information
 - Version of Next.js: 8.0.0

### LINKED ISSUE #6380: index page subdirectory event listeners broken in production mode
# Bug report

## Describe the bug

An index page implemented within a subdirectory behaves differently between development and production modes.

When the next server is started in dev mode everything seems to work as expected. When running in "production" mode via `next build` and `next start` the event listeners on page do not fire. 

## To Reproduce

I created a minimal example here: https://github.com/hoffrocket/next8bug

## Expected behavior

I'd expect the same behavior in production as in dev. The event listeners should fire.

## System information
 - OS: macOS
 - chrome, safari
 - Version of Next.js: 8.0.1
 - Version of node: 8.14.0

### PR DESCRIPTION
**Pull request by Janpot**
Don't normalize the pagePath twice.

Fixes https://github.com/zeit/next.js/issues/6285
Fixes https://github.com/zeit/next.js/issues/6380

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
I read over this 3 times, but it seems like there is no fix here, just a passing test 🤔 I'd be happy to take in the test though.

**Review by timneutkens — CHANGES_REQUESTED** [review]
Meant to use the comment button. Not approve

**Comment by Janpot** [comment]
@timneutkens the fix is that `normalizePage` doesn't mutate `page` anymore, so that `normalizePagePath` gets the original `page` as well. The test won't pass without this change

**Comment by dav-is** [comment]
@Janpot What do you think about mirroring the variable names from https://github.com/zeit/next.js/blob/canary/packages/next/server/on-demand-entry-handler.js#L163

**Comment by Janpot** [comment]
@dav-is @timneutkens Updated the variable names.

**Review by dav-is — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]
@Janpot I've updated the PR as I realized why the page was actually being normalized, so I've moved the normalize down too, since it's unrelated to matching the server require.

**Comment by Janpot** [comment]
Even better 🙂

**Pull request merged**
