### PR TITLE
Update Redux example to use Toolkit + update dependencies.

### PR DESCRIPTION
**Pull request by leerob**
After talking with markerikson, I've made some updates to the Redux examples:

- Updated the `with-redux` example to use the Redux Toolkit + TypeScript example
- Updated dependencies of `with-redux` to work with latest testing setup
- Removed `with-redux-toolkit` in favor of `with-redux`
- Removed `with-redux-toolkit-typescript` in favor of `with-redux`
- Removed `with-redux-code-splitting` in favor of `with-redux`

### CODE REVIEW

**Comment by markerikson** [comment]
Looks great! (my only concern, tbh, is that by pinging me in your comment it might end up as part of the commit message when squashed, and that's what led to me getting a bunch of random notifications when people cloned another example earlier.)

**Comment by ijjk** [comment]
I removed the `@` from the PR description to avoid you being pinged like you mentioned.

**Review by ijjk — COMMENTED** [review]
Looks good, seems `lint-fix` might need to be run though

**Comment by leerob** [comment]
Sorry about that, Mark! Thank you @styfle 😄

**Comment by leerob** [comment]
Hmm, running `lint-fix` or `prettier-fix` is changing a bunch of unrelated files.
CleanShot 2021-09-15 at 10 22 32@2x

**Comment by ijjk** [comment]
Your local `prettier` version might be out of date since it was bumped recently, I went ahead and ran it here

**Comment by leerob** [comment]
Interesting, shouldn't it use the version in `package.json` though?

**Comment by ijjk** [comment]
Yeah, is it not updating after running `yarn` in the monorepo root?

**Comment by leerob** [comment]
🤕 I need to update the packages first, good point 😆

**Review by ijjk — APPROVED** [review]

**Comment by CristianCiubancan** [comment]
Hi, as the main distinctive feature of next js (at least for me) is the ability to use ssr and ssg, there really is no point in using next with redux without being able to use ssr and ssg. Using this example I am able to fetch data and store it into redux on the server side but it does not hydrate on the client side, can you do another example or update this one to enable the ability to use ssr and ssg peoperly with redux toolkit?


Thank you for the great work done so far, and I hope you can do this as it will surely be appreciated by many people.

**Pull request merged**
