### PR TITLE
Updates Apollo Server Examples to use Apollo Server 4 & @as-integrations/next

### LINKED ISSUE #10413: Demonstrate Apollo-Server context usage with-apollo-xxx examples
# Feature request

Current `with-apollo-` examples do not demonstrate how to use Apollo-Server with `context` resolver. It doesn't work out of the box and it's not at all straightforward for Apollo newbies (like myself) how to enable it.

Note: this is a request for help/consulting for Apollo experts.

### 1. `createIsomorphLink`

`createIsomorphLink` implementations recommended by Apollo Team imply the use of 
`SchemaLink` on server and `HttpLink` on client. `SchemaLink` is said to be more performant
because it avoids HTTP layer alltogether:

```js
function createIsomorphLink(ctx) {
  if (typeof window == 'undefined') {
    // !!! Server side
    let {SchemaLink} = require('apollo-link-schema')
    let {schema, context} = require('./schema')
    return new SchemaLink({schema, context : ctx}) 
  } else {
    // !!! Browser side
    let {HttpLink} = require('apollo-link-http')
    return new HttpLink({ 
      uri: '/api/graphql',
      credentials: 'same-origin',
    })
  }
}
```

### 2. `SchemaLink`

`SchemaLink` does not initiate an HTTP request. The side effect is that Apollo-Server `context` function is never called. This function is **crucial** as it usually fetches or polyfills all common resolver's data including current user/visitor, etc. Current `with-apollo-` examples demonstrate how to read user data in local (leaf) resolvers which is not production-like. 

Luckily, `SchemaLink` accepts a `context` argument where we can provide the same `context` resolver as to the `new ApolloServer({context: ...})`.

### 3. Two calls

Now the tricky part is that `createIsomorphLink` is called twice. Once with `{req, res}` context data (coming from `getInitialProps`) and another – with no context (coming from these:

```js
 const WithApollo = ({ apolloClient, apolloState, ...pageProps }) => {
    const client = apolloClient || initApolloClient(undefined, apolloState) // !!!
```

lines).

`context` function of Apollo-Server must not be called with empty context as it, in most cases, reads `ctx.req`.

The second invocation of Apollo-Client will reuse cache so resolvers, including `context` won't be called. It seems to me that an update like:

```diff
function createIsomorphLink(ctx) {
  ...
-  let {schema} = require('./schema') 
-  return new SchemaLink({schema, context: ctx)
+  let {schema, context} = require('./schema') 
+  return new SchemaLink({schema, context : isEmpty(ctx) ? context(ctx) : ctx})
}
```

should be enough to enable Server's `context` usage. Given that `apollo/schema.js` exports standalone `context` function of course.

I can make a PR but, before that, it would be great to get a feedback from someone more experienced with Apollo and NextJS. 

Are my reasoning correct? Is my proposal valid?

Another option it to always use `HttpLink` like it's done in https://github.com/adamsoffer/next-apollo and https://github.com/lfades/next-with-apollo For some reason the authors of both packages decided to not rely on `SchemaLink`...

### LINKED ISSUE #21984: Improve with-apollo example to more closely align to Next.js standards
**What example does this report relate to?**

with-apollo

**What version of Next.js are you using?**

latest

**What version of Node.js are you using?**

latest

**What browser are you using?**

any

**What operating system are you using?**

any

**How are you deploying your application?**

any

**Describe the Bug**

The current `with-apollo` example fetches data and adds it to the cache, but never returns that data inside `getStaticPaths` / `getSeverSideProps`. 

```js
await apolloClient.query({
  query: ALL_POSTS_QUERY,
  variables: allPostsQueryVars
})
```

**Expected Behavior**

All other usage of `getStaticProps` / `getServerSideProps` show forwarded the data to the component via props (hence the names). This seems really confusing to me. I think we should use props here instead.

**To Reproduce**

View the `with-apollo` example

### LINKED ISSUE #42769: Update Apollo Server examples to use Apollo Server 4 & @as-integrations/next
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

N/A 

### Which example does this report relate to?

api-routes-apollo-server, api-routes-apollo-server-and-client, and api-routes-apollo-server-and-client-auth

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

The current examples for Next + Apollo Server use Apollo Server 3 but Apollo Server 4 is now [generally available](https://github.com/apollographql/apollo-server/blob/da548aa1fed02f1c13983c0b4bd782c171b4ccc2/docs/source/migration.mdx?plain=1#L7). For Apollo Server 4, the Apollo team removed the [apollo-server-micro](https://www.npmjs.com/package/apollo-server-micro) package which the Apollo Server examples use. They also created a process for [the open source community to maintain integration specific packages](https://github.com/apollographql/apollo-server/blob/da548aa1fed02f1c13983c0b4bd782c171b4ccc2/docs/source/migration.mdx?plain=1#L36). As a result of this change, the [@as-integrations/next package](https://github.com/apollo-server-integrations/apollo-server-integration-next) was created and is now available and is [officially listed in the Apollo Server docs](https://www.apollographql.com/docs/apollo-server/integrations/integration-index/). 

The following examples should be updated to help users use the latest versions of Apollo Server and Next:
 - [api-routes-apollo-server-and-client-auth](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client-auth/pages/api/graphql.js)
 - [api-routes-apollo-server-and-client](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server-and-client/pages/api/graphql.js)
 - [api-routes-apollo-server](https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server/pages/api/graphql.js)

### Expected Behavior

N/A

### To Reproduce

N/A

### PR DESCRIPTION
**Pull request by idoob**
Closes https://github.com/vercel/next.js/issues/42769

## Description 

This PR address https://github.com/vercel/next.js/issues/42769 by updating the `api-routes-apollo-server`, `api-routes-apollo-server-and-client` and `api-routes-apollo-server-and-client-auth` examples to use Apollo Server 4 and [@as-integrations/next](https://github.com/apollo-server-integrations/apollo-server-integration-next), which is the Apollo Server Next integration package. The PR also updates the three examples to use Typescript. The functionality of the examples is the same.

## Documentation / Examples
- [X] Make sure the linting passes by running `pnpm build && pnpm lint`
- [X] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

closes https://github.com/vercel/next.js/pull/33545
closes https://github.com/vercel/next.js/pull/30082
closes https://github.com/vercel/next.js/issues/21984
closes #10413

### CODE REVIEW

**Comment by balazsorban44** [comment]
Looks like this would also close these:

#33545
#30082
#21984

**Comment by leerob** [comment]
Code seems okay, but yeah agree on merging into one.

**Comment by idoob** [comment]
The `api-routes-apollo-server-and-client` and `api-routes-apollo-server-and-client-auth` are very similar with the only major difference being the inclusion of auth. They both focus on supporting the Apollo Client with SSR and Apollo Client rehydration. On the other hand, the `api-routes-apollo-server`, is a barebones example that only uses Apollo Server and not the client. This is also an example for building static pages. 

Would it be prefered to have a single Apollo Server + Apollo Client example? Based on the content of the examples, maybe only the `api-routes-apollo-server-and-client` and `api-routes-apollo-server-and-client-auth` examples should be merged?

**Review by balazsorban44 — APPROVED** [review]
Next.js apps are usually hybrid (meaning they have both static and dynamic pages), so I think we could really merge everything into a single example, showcasing anything we need in one project. For now, I think we can merge this PR, as it resolves a bunch of issues, thank you! :green_heart:

If you are interested in helping out with the merging of the examples, you can open a new PR with your suggested changes and we can continue the discussion there. :+1:

**Comment by glasser** [comment]
Thanks @kodiakhq!

**Comment by glasser** [comment]
FWIW it looks like there's still an Apollo Server 2 example in `examples/with-apollo-neo4j-graphql` (which also uses `neo4j-graphql-js` which *also* appears to be deprecated).  Maybe it would be reasonable to just delete that one?

**Comment by leerob** [comment]
+1 I would just delete it if deprecated.

**Pull request merged**
