### PR TITLE
Removes perf metrics for concurrent and blocking modes

### PR DESCRIPTION
**Pull request by housseindjirdeh**
Introducing concurrent (or blocking) mode changes how React hydrates on page load/navigations. This PR removes measures and marks that already present to measure hydration and render times to only fire if React is in legacy mode. 

CC @spanicker

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.9s | ⚠️ +301ms |
| nodeModulesSize | 49 MB | 49 MB | -147 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -855,15 +855,14 @@
       var reactRoot = null
 
       function renderReactElement(reactEl, domEl) {
-        // mark start of hydrate/render
-        if (_utils.ST) {
-          performance.mark('beforeRender')
-        }
-
         if (false) {
-          var opts, callback
+          var opts
         } else {
-          // The check for `.hydrate` is there to support React alternatives like preact
+          // mark start of hydrate/render
+          if (_utils.ST) {
+            performance.mark('beforeRender')
+          } // The check for `.hydrate` is there to support React alternatives like preact
+
           if (isInitialRender) {
             _reactDom['default'].hydrate(reactEl, domEl, markHydrateComplete)
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -569,15 +569,14 @@
       var reactRoot = null
 
       function renderReactElement(reactEl, domEl) {
-        // mark start of hydrate/render
-        if (_utils.ST) {
-          performance.mark('beforeRender')
-        }
-
         if (false) {
-          var opts, callback
+          var opts
         } else {
-          // The check for `.hydrate` is there to support React alternatives like preact
+          // mark start of hydrate/render
+          if (_utils.ST) {
+            performance.mark('beforeRender')
+          } // The check for `.hydrate` is there to support React alternatives like preact
+
           if (isInitialRender) {
             _reactDom.default.hydrate(reactEl, domEl, markHydrateComplete)
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.3s | -167ms |
| nodeModulesSize | 49 MB | 49 MB | -147 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ⚠️ +2 B |
| index.js gzip | 78 kB | 78 kB | ✓ |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| Overall change | 393 kB | 393 kB | ⚠️ +8 B |

</details>

</details>


Commit: 2138cf630684a592bc00a0ce2111c582c5e793ea

**Review by Timer — COMMENTED** [review]
What effect does this have on all of the other locations that use `beforeRender`?

e.g.:
```js
  performance.measure(
    'Next.js-route-change-to-render',
    navStartEntries[0].name,
    'beforeRender'
  )
  performance.measure('Next.js-render', 'beforeRender', 'afterRender')
```

**Comment by housseindjirdeh** [comment]
`beforeRender` is only referenced in the callbacks that fire after ReactDOM hydrates or renders (`markHydrateComplete`/`markRenderComplete`). I removed both these callbacks from firing during blocking or concurrent mode so there are no areas where it's being referenced and not instantiated.

**Review by Timer — APPROVED** [review]
Good call. Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| buildDuration | 14s | 13.8s | -143ms |
| nodeModulesSize | 49 MB | 49 MB | -147 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -855,15 +855,14 @@
       var reactRoot = null
 
       function renderReactElement(reactEl, domEl) {
-        // mark start of hydrate/render
-        if (_utils.ST) {
-          performance.mark('beforeRender')
-        }
-
         if (false) {
-          var opts, callback
+          var opts
         } else {
-          // The check for `.hydrate` is there to support React alternatives like preact
+          // mark start of hydrate/render
+          if (_utils.ST) {
+            performance.mark('beforeRender')
+          } // The check for `.hydrate` is there to support React alternatives like preact
+
           if (isInitialRender) {
             _reactDom['default'].hydrate(reactEl, domEl, markHydrateComplete)
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -569,15 +569,14 @@
       var reactRoot = null
 
       function renderReactElement(reactEl, domEl) {
-        // mark start of hydrate/render
-        if (_utils.ST) {
-          performance.mark('beforeRender')
-        }
-
         if (false) {
-          var opts, callback
+          var opts
         } else {
-          // The check for `.hydrate` is there to support React alternatives like preact
+          // mark start of hydrate/render
+          if (_utils.ST) {
+            performance.mark('beforeRender')
+          } // The check for `.hydrate` is there to support React alternatives like preact
+
           if (isInitialRender) {
             _reactDom.default.hydrate(reactEl, domEl, markHydrateComplete)
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-78b2a56dbccd45cda1d4.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-ec225f89ff10c0da79a6.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.5s | -30ms |
| nodeModulesSize | 49 MB | 49 MB | -147 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js remove-hydration-measure-concurrent | Change |
| - | - | - | - |
| _error.js gzip | 77.8 kB | 77.8 kB | ⚠️ +1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ⚠️ +2 B |
| index.js gzip | 78 kB | 78 kB | ✓ |
| link.js gzip | 80.4 kB | 80.4 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| withRouter.js gzip | 78.1 kB | 78.1 kB | ⚠️ +2 B |
| Overall change | 393 kB | 393 kB | ⚠️ +8 B |

</details>

</details>


Commit: d8d6dc8456fcf2b8630a4d5d30cc629b66296364

**Pull request merged**
