### PR TITLE
Describe solution to centralized routing

### PR DESCRIPTION
**Pull request by ldthorne**
Add a section to the README with a solution to the issue surrounding separated routing that arises when using Next.js' static export for a site.

Adding per #2823.

cc @timneutkens

### CODE REVIEW

**Comment by timneutkens** [comment]
Hey @ldthorne I'm thinking we'd best add this to the wiki here: https://github.com/zeit/next.js/wiki and then link to it from the readme. Since it's not a super common use case 👌

**Review by timneutkens — APPROVED** [review]
Awesome ❤️ Thanks!

**Comment by timneutkens** [comment]
@arunoda can you merge this?

**Comment by arunoda** [comment]
Looks fine for me.

**Pull request merged**
