### PR TITLE
Examples: updated the example of analyze-bundles to utilize the App Router

### PR DESCRIPTION
**Pull request by archanaagivale30**
This PR updates the analyze-bundles example to use the App Router. Here are the changes that have been made:

- Renamed the "pages" folder to "app" folder.
- Updated the file index.tsx to page.tsx to align with App Router
- Change contact.tsx and about.tsx in to folder structure
- Added the layout.tsx file as part of the App Router.

cc @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d9c2eeef6147497e7087e462cefab1b3e0b20d8e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@archanaagivale30 If you can update the packages in the `package.json`, that will be great!

**Comment by archanaagivale30** [comment]
@samcx Updated package.json for @next/bundle-analyzer package. anything specific need to update let me know

**Comment by samcx** [comment]
@archanaagivale30 all the packages! E.g., `react` → `18.3.1`

**Comment by archanaagivale30** [comment]
> @archanaagivale30 all the packages! E.g., `react` → `18.3.1`

@samcx All the package versions have been updated to the latest.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
