### PR TITLE
Updated radix-ui example to use App Router

### PR DESCRIPTION
**Pull request by Shruthireddy04**
This PR updates the radix-ui example to use the App Router. Here are the changes that have been made:

Renamed the "pages" folder to "app" folder.
Updated the file index.tsx to page.tsx to align with App Router.
Added the layout.tsx file as part of the App Router.
Updated the paths to the files that will use Tailwind CSS class names as per "app" folder in tailwind config file
Updated package.json to use the latest version.

cc: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 194e456b0699bfd938b03730e8c554dd9a7ee0cb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Shruthireddy04 Can you make sure the other packages are upgraded as well (e.g., radix ones, tailwind)?

**Comment by Shruthireddy04** [comment]
@samcx  Upgraded other packages as well.

**Comment by samcx** [comment]
@Shruthireddy04 Please make sure _every_ package is bumped! You can check with https://www.npmjs.com/.

**Review by samcx — APPROVED** [review]

**Pull request merged**
