### PR TITLE
Support for cxs rehydration and removal of duplicate styles.

### PR DESCRIPTION
**Pull request by aranajhonny**
Before.
captura de pantalla 2017-05-04 a las 2 42 50

After.
captura de pantalla 2017-05-04 a las 2 41 52

### CODE REVIEW

**Comment by spencersmb** [comment]
I was looking at this yesterday and my one question is that if we use csx lite, the docs say that it doesn't support nested selectors. Is that correct? For me that would be a deal breaker in terms of choosing a css compiler. Anyways just curious on what you think...

**Comment by sergiodxa** [comment]
@spencersmb I think if you style each component separately you aren't going to need nested selectors most of the time

**Comment by spencersmb** [comment]
Ok thanks for advising - I guess moving from scss to this new style takes a slightly different approach to styling components.

**Review by timneutkens — APPROVED** [review]
💯

**Pull request merged**
