### PR TITLE
Fix Babel ignore does not work with Next11 and Webpack 5 (#27557)

### LINKED ISSUE #27557: Babel ignore does not work with Next11 and Webpack 5
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next export

### Describe the Bug

When using a custom babelrc config and the `ignore` property, directories are correctly ignored when using webpack 4 but when using webpack 5 they are still processed by Babel.

### Expected Behavior

Files/directories/globs added to the `ignore` array in `.babelrc` are correctly ignored by Babel.

### To Reproduce

Reproduction repo: https://github.com/williamtetlow/nextjs-babel-ignore-webpack5

This repo has the following `.babelrc`

```js
{
  "presets": ["next/babel"],
  "plugins": [],
  "ignore": ["testing"] // <-- ignoring the testing directory
}

```

1. Run `yarn build`
2. Inspect log output and you should see the warning `The code generator has deoptimised styling...` indicating that the directory ignored in `.babelrc` is still being processed by Babel

Screenshot 2021-07-28 at 12 29 39

3. Go to `next.config.js` and set `webpack5: false`
4. Run `yarn build` again
5. ignore property in `.babelrc` is correctly ignored

### PR DESCRIPTION
**Pull request by jacargentina**
Fixes: https://github.com/vercel/next.js/issues/27557

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Hi, can we add a test case for this?

**Comment by andreyvolokitin** [comment]
This issue is still relevant...

**Comment by andreyvolokitin** [comment]
Also this change doesn't appear to fix the issue. When `loadedOptions` is constructed by `loadOptions` in `dist/build/babel/loader/get-config.ts` it runs compiled babel core from `dist/compiled/babel/bundle.js`, which in turn runs  `loadFullConfig`. It gets run twice, the first time with `ignore` properly present, but `ignore` is somehow `undefined` on a second run. In the end `loadedOptions` doesn't contain `ignore`, as well as final config.

There's also no way to fix this issue by disabling `webpack5` as this flag was removed since `next@12`

**Review by ijjk — COMMENTED** [review]
Going to close this as it doesn't appear to resolve the issue and is quite stale

**Pull request closed without merging**
