### PR TITLE
fixes #48794 : When using pageExtensions like "page.jsx", global css import not working

### LINKED ISSUE #48794: When using pageExtensions like "page.jsx", global css import not working
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 12.22.8
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.3
      eslint-config-next: 13.3.2-canary.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/serene-meninsky-spizhp

### To Reproduce

Steps to reproduce:
1. Open codesandbox: https://codesandbox.io/p/sandbox/serene-meninsky-spizhp
2. Go to `/test` path
3. Notice that color of text is BLACK
4. Now go to next.config.js and comment line 5 like  `//   pageExtensions: ["page.jsx", "page.js"],`
6. Restart next server in codesandbox and go again to '/test' path
7. The color of text is RED

### Describe the Bug

When using pageExtensions in next@latest like:
```
pageExtensions: ["page.jsx", "page.js"],
```

Then in app directory, importing CSS does not work:
``` 
// File path: app/layout.page.tsx
import "../styles/globals.css";   // DOES NOT WORK

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

```

Hence no CSS is loaded while running server.

### Expected Behavior

When using `pageExtensions`, importing of CSS in app directory should work normally.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by sagarpreet-xflowpay**
fixes #48794

### CODE REVIEW

**Comment by feedthejim** [comment]
@sagarpreet-xflowpay thanks for looking into it, do you mind adding a test to it?

**Comment by sagarpreet-chadha** [comment]
Hey @feedthejim - can you review again?  :)

**Review by feedthejim — DISMISSED** [review]

**Comment by sagarpreet-xflowpay** [comment]
@feedthejim - thanks for running the tests. All are passing now!

**Comment by sagarpreet-chadha** [comment]
Please review again @feedthejim

**Comment by feedthejim** [comment]
can you explain the change in the regex? @sagarpreet-chadha. Please do not ping maintainers.

**Comment by sagarpreet-chadha** [comment]
Apologies! Was not aware as this is my first contribution here 😅
The earlier regex was only removing `.tsx` from let’s say `layout.page.tsx` due to which the css link tag was not getting injected. The new regex makes sure `.page.tsx` is removed (basically pageExtension).

Also in case of create-next-app tests failing (as mentioned in earlier comment) - was because of special characters. The new regex handles it.

**Pull request merged**
