### PR TITLE
Add next-i18next as the solution to integrate i18next into next.js

### PR DESCRIPTION
**Pull request by jamuhl**
@timneutkens we just finished the next-i18next module (https://github.com/isaachinman/next-i18next) a few weeks ago and think it's ready to replace the old ways to integrate react-i18next / i18next.

So we think it's a good time to route people there for information on next.js with-i18next and also for easier handling upcoming issues.

### CODE REVIEW

**Comment by timneutkens** [comment]
Sounds good to me 👍

**Comment by jaqua** [comment]
@jamuhl @timneutkens Seriously? --> https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L10

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/eval#Don't_use_eval_needlessly!

Also the `backend.loadPath` is missing to handle correct locals for SSR.

**Comment by jamuhl** [comment]
@jaqua please address your concerns on the next-i18next repo!!!

**Comment by jaqua** [comment]
I don't think it is a good idea to remove the example and replace it with an external one. Users should decide on their own if they want to use another package. Should we replace also other examples by external packages? I don't think that is a good idea - just my opinion...

Just for that example: I think there is a missing SSR support in your code. Now I can't use that package but also the previous example - which I can improve like I need - is gone.

**Comment by jamuhl** [comment]
@jaqua the sample was always external...it was maintained external...so this change makes it easier for us to get focused feedback without polluting the next.js issues. That package is a improvement done by the same people done the sample - so we try just to help and improve.

the old sample...are both in the commit history of this repo and react-i18next.

**Comment by jaqua** [comment]
> without polluting the next.js issues

That's a good point....

**Comment by kachkaev** [comment]
@jaqua here is the last version of the example before it was deleted: https://github.com/zeit/next.js/tree/c5630d3bc5f739208193fa35a4461830f29d1ace/examples/with-react-i18next

I also find that `next-i18next` is not a full replacement of what the example could do, which confuses me a little. However, I do believe that after some improvements, `next-i18next` will be the way to go for everyone who want to use `i18next` and this will be great! Feel free to join the discussions in [open issues](https://github.com/isaachinman/next-i18next/issues) and help out 😉

**Pull request merged**
