### PR TITLE
(fix) Link to API routes docs

### PR DESCRIPTION
**Pull request by vinaykulk621**
from 
[https://nextjs.org/docs/api-routes/introduction](https://nextjs.org/docs/api-routes/introduction)

to 
[https://nextjs.org/docs/pages/building-your-application/routing/api-routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1edba350100bc5c2fa164f212515c0a18fbfd6eb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1edba350100bc5c2fa164f212515c0a18fbfd6eb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1edba350100bc5c2fa164f212515c0a18fbfd6eb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
This correct redirects, so I don't think we need to do the find all + replace here. Instead, we should update links as we're updating examples. Thank you anyway!

**Pull request closed without merging**
