### PR TITLE
docs: pass base headers while setting nonce

### PR DESCRIPTION
**Pull request by martyanovandrey**
Example for setting "nonce", when created, clears the passed headers

### CODE REVIEW

**Review by timneutkens — DISMISSED** [review]
This looks good 👍

**Review by leerob — COMMENTED** [review]
Could we ensure the examples are updated as well here? If you search for parts of the code snippet here, you'll see it's in three places I believe.

**Comment by leerob** [comment]
@martyanovandrey did you want to make that change here? 🙏

**Comment by martyanovandrey** [comment]
added changes, thanks for noticing !

**Review by leerob — APPROVED** [review]

**Pull request merged**
