### PR TITLE
Add rehydration to example/aphrodite

### PR DESCRIPTION
**Pull request by Grokling**
Enhanced example with style rehydration, and additional attribute in the style tag.
This prevents duplication of tags, or styles within the tags.
Also added comments to explain each piece.

### CODE REVIEW

**Comment by aranajhonny** [comment]
@Grokling  test failed. please check. 
captura de pantalla 2017-05-04 a las 1 28 47

**Comment by Grokling** [comment]
@aranajhonny All passing now - sorry for the messiness!

**Comment by timneutkens** [comment]
@Grokling could you check the yarn.lock. It includes aphrodite related packages, those shouldn't be there 😄

**Comment by Grokling** [comment]
@timneutkens said: 
> @grokling ahh I think the github merge resolver got to me
> Let me fix the merge conflict and I'll merge

I've commited a merge with master, so yarn.lock should not have any conflicts.

**Pull request merged**
