### PR TITLE
[#1301] Remove eval, Load initial component async 

### PR DESCRIPTION
**Pull request by bringking**
## Subtasks
- [x] Save pages as plain JS
- [ ] Fetch JS pages from the router
- [ ] Handle 404 pages
- [ ] Handle status codes
- [ ] Send the initial JS/JSON with the `__NEXT_DATA__` payload
- [ ] Optional async loading of initial component 

## Related Issue
https://github.com/zeit/next.js/issues/1301

### CODE REVIEW

**Comment by ide** [comment]
Two questions/ideas that might be helpful:
- Could the dehydrated components be sent down at the end of the page payload? That way the browser could render the initial markup and styles and respond to some input events (scrolling, navigation) while it's still downloading the dehydrated components. Or perhaps emitting `<script defer>` tags in the document head so that the browser can start downloading cacheable JS early on?
- How much of the payload is due to unused styles? Having looked closely at a couple of styling libraries, one thing I like about Aphrodite with regard to SSR is that it sends down only the styles that are actually used.

**Comment by bringking** [comment]
@ide Thanks for questions/ideas! 

* Caching / preloading the components early on is a great idea. I will investigate to see if there is something we can do to start the browser fetching them right away. As far as putting them at the bottom of the payload, they currently already are, and that would provide a good user experience if we could do something use something like - https://github.com/aickin/react-dom-stream to stream the HTML to the user, but as it stands, the user is waiting to download the full HTML before it can begin rendering
* Re - unused styles, our solution works very similar to https://github.com/kriasoft/isomorphic-style-loader so we are only "flushing" the exact styles for each view into the head. I have thought about a possible babel/webpack plugin to essentially strip the css content from any "flushed" module, but that would have to happen at runtime, and would be clunky/hacky I think..

**Comment by arunoda** [comment]
@bringking I like the idea of this PR.
The only problem I see it this will delay the JS app invocation.
I'd like to find a way to preload these script via a script tag. Of course we can't do this with JSON pages.

We've to do a big change with  #1301.

---

Here's what we can do.
I'll try to work #1301 soon, so with that we may have a better loading system for these pages.

**Comment by bringking** [comment]
@arunoda thanks, I do agree that the delay of the execution is not preferred, however if #1301 switches the page outputs to JS, we can use `<link rel="preload"/>` on the pages to minimize the delay. Also, making it opt-in would be great, since many sites won't have this issue if they don't have larger component payloads. 

Like you stated, it sounds like this exploration should wait until after #1301. I am happy to help out, is there anything I can do to help or has that work already been started? Thanks again for this great project!

**Comment by arunoda** [comment]
@bringking I agree.

We haven't started #1301 but here's the outline.

* Get rid of .json pages and just use simple .js pages.
* Create a page loader which support loading via something like `JSONP` (or similar). But no eval. Just load the script and execute.
* We maintain a global browser cache on these pages. And something like an event emitter to get notified when the page is loaded.

**Comment by bringking** [comment]
@arunoda I would love to take a stab it this, or do you think this is something the core team should be working on?

**Comment by rauchg** [comment]
@ide to answer your second point, only the styles included with each component on the page would show up. Not with the level of granularity of Aphrodite, only at component level, but in practice that's not an issue since component CSS tends to be granular to begin with

**Comment by arunoda** [comment]
@bringking if you work on this. That's great.
Allow us to change the branch. So, we could collaborate :)

**Comment by bringking** [comment]
@arunoda, great thanks! I will dive in

**Comment by arunoda** [comment]
@bringking I'd like to see eval removal in a separate PR.

**Comment by bringking** [comment]
@arunoda Actually can you explain your thinking a bit more? I am thinking we still need a `page-loader` abstraction to do #1301 since the expectation of JSON is baked into the router and the server. I could separate the the dynamic component bundles, by having their contents sent as an inline script tag. e.g. 

```
<script>
// ErrorComponent 
</script>
<script>
// Component
</script>
<script src="/next/-/app.js"></script>
```

This would allow the bootup behavior to continue to be synchronous. However, there will still need to be a way to mount and manage prefetching new route bundles etc.

**Comment by bringking** [comment]
Closing this to split the async component work from the JS/eval work. JS/eval work here - https://github.com/zeit/next.js/pull/1608

**Pull request closed without merging**
