### PR TITLE
Fix typo in MDX documentation

### PR DESCRIPTION
**Pull request by ManuLpz4**
I was reading the documentation related to MDX and noticed a typo in some articles, so I fixed them.

Although I read the [Contribution Guidelines](https://github.com/vercel/next.js/blob/canary/contributing.md) this is my first contribution so feel free to comment if I can do better.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5c633b9ff0500589dcc271e9a1900659c9c7cf54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Netail** [comment]
I believe the a/an refers to file, so `a file` should be correct

**Comment by ManuLpz4** [comment]
> I believe the a/an in this case refers to file, so `a file` should be correct



> I believe the article (`a` or `an`) in this case refers to the word `file`, so `a file` (the current way) should be correct

Hey, @Netail! Thank you for helping me on my first PR. I'm looking for official recommendations on it and I only found that the preceding word is the part the defines if it should be an `a` or an `an`.

Do you have some article talking about the principle noun? I'm not a native speaker so maybe it is something that is not written but commonly used :)

Some links:
- [Chicago Manual Of Style](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Usage/faq0068.html#:~:text=Please%20see%20CMOS%205.74%3A%20%E2%80%9CWith,%7D%20%7Ba%20onetime%20pass%7D.)
- [Purdue University](https://owl.purdue.edu/owl/general_writing/grammar/articles_a_versus_an.html#:~:text=If%20the%20first%20letter%20makes,words%20that%20begin%20with%20consonants.)

**Comment by devjiwonchoi** [comment]
@Netail Thank you for helping out! As we are going to read as `an MDX components dot tsx file`, I also agree that it can be written with `an`.

x-ref: https://www.britannica.com/dictionary/eb/qa/how-do-you-know-whether-to-use-a-or-an

**Review by devjiwonchoi — APPROVED** [review]
Thank you for the PR! Great catch :)

**Pull request merged**
