### PR TITLE
[DO NOT MERGE] chore(precompile): reduce the size of precompiled dependencies

### PR DESCRIPTION
**Pull request by SukkaW**
The PR addresses https://twitter.com/hazae41/status/1720557445678858248.

Currently, The installation size of the `next` package is at 73.6 MiB. Among 53 MiB of them are precompiled dependencies.

The PR attempts to reduce that size by removing unused ones:

- ~~Remove `find-cache-dir`~~ https://github.com/vercel/next.js/pull/60316
  - The usage of `find-cache-dir` was removed **4 years ago** (https://github.com/vercel/next.js/pull/7013) but the dist and the build script were never removed.
- ~~Remove `@segment/ajv-human-errors`~~ https://github.com/vercel/next.js/pull/60316
  - The usage of `@segment/ajv-human-errors` was removed in https://github.com/vercel/next.js/pull/56383 by me. Though the build script was also removed in that PR, the dist never got removed.
- ~~Remove Re-add precompile `watchpack`~~ https://github.com/vercel/next.js/pull/60309
  - Next.js has stopped bundling the `watchpack` since https://github.com/vercel/next.js/pull/50792. Currently, `watchpack` is a direct dependency of Next.js, ~~but the type never got updated and the pre-compiled dist never got removed.~~ the PR adds the pre-compile back.
- ~~Enable minification of `@next/font`~~ https://github.com/vercel/next.js/pull/60319
  - Currently, the un-minified `@next/font` is bundled with Next.js.
- ~~Remove `chalk` inside `@next/react-dev-overlay`~~ https://github.com/vercel/next.js/pull/60317
  - `@next/react-dev-overlay` is bundled with Next.js. The usage of `chalk` inside `@next/react-dev-overlay` was not removed in https://github.com/vercel/next.js/pull/55992, thus the `chalk` is still being shipped.
- Remove `schema-utils2` and `webpack-sources1`
  - `schema-utils@2` and `webpack-sources@1` were only used in webpack 4. After webpack 4 was dropped, they were no longer necessary.
- Remove `loader-utils2`
  - `saas-loader` no longer uses `loader-utils` while `resolve-url-loader` only uses `loader-utils.isUrlRequest`. So it is safe to remove `loader-utils2` and replace its usage with `loader-utils3`.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 476df3dbd88c80c835fec9ecd21364db6b4845be

`pnpm test-dev test/e2e/app-dir/app-compilation/index.test.ts` 
- app dir > HMR > should not cause error when removing loading.js

<details>
<summary>Expand output</summary>

  ● app dir › HMR › should not cause error when removing loading.js

    TIMED OUT: hello from new page

    hello from slow page

    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/app-compilation/index.test.ts:44:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| buildDuration | 15s | 14.7s | N/A |
| buildDurationCached | 8.5s | 9.5s | ⚠️ +1s |
| nodeModulesSize | 175 MB | 175 MB | N/A |
| nextStartRea..uration (ms) | 504ms | 508ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.4 kB | 30.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33 kB | 33 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.71 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| index.html gzip | 526 B | 528 B | N/A |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 522 B | 523 B | N/A |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.7 kB | 96.7 kB | N/A |
| page.js gzip | 141 kB | 141 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 626 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js remove-unused-precompile | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | ✓ |
| app-page-exp..prod.js gzip | 94.5 kB | 94.5 kB | ✓ |
| app-page-tur..prod.js gzip | 95.2 kB | 95.2 kB | ✓ |
| app-page-tur..prod.js gzip | 89.9 kB | 89.9 kB | ✓ |
| app-page.run...dev.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run..prod.js gzip | 89.2 kB | 89.2 kB | ✓ |
| app-route-ex...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 22.9 kB | 22.9 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 48.5 kB | 48.5 kB | ✓ |
| Overall change | 926 kB | 926 kB | ✓ |

</details>

</details>
Commit: 476df3dbd88c80c835fec9ecd21364db6b4845be

**Comment by feedthejim** [comment]
What's the after size?

I think the watch pack one might be an oversight and we should re use the pre compiled one

**Comment by SukkaW** [comment]
> What's the after size?

The final installation size reduction can be seen from the PR stats, `nodeModulesSize`. Currently, I've only reduced from 175 MiB to 172 MiB.

> I think the watch pack one might be an oversight and we should re-use the pre-compiled one

I can bring it up in the PR. This should help reduce the installation size further.

**Comment by SukkaW** [comment]
It seems that somehow `sass-loader` test failed after the changes. I will look into this when I get time.

**Comment by styfle** [comment]
@SukkaW If its easier - you could split this up into a few PRs:

- minify font
- remove chalk
- remove unused precompiled deps
- compile watchpack

**Comment by SukkaW** [comment]
All the subsequent PRs has been merged. The PR can be closed.

**Pull request closed without merging**
