### PR TITLE
Prevent an error when the first argument of import is a template

### PR DESCRIPTION
**Pull request by fatfisz**
Fixes one of the problems described in #4433.

The handle-import plugin can't deal with [webpack's dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports). Before this change an unhelpful error was appearing in the console and the build was broken. The change ignores such imports altogether, resulting in no error.

Handling template literals by Next.js can be added later on, but maybe it would be better done through a webpack plugin instead of a babel one.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
Should this actually throw a helpful error then 🤔

Besides that, it looks good 🙏

**Comment by timneutkens** [comment]
What I'm not following is why'd you want to make something that doesn't function work without compilation errors 🤔 Wouldn't that make it even worse for people that don't know it doesn't work use it 🤔

**Comment by fatfisz** [comment]
Ok, fair point. While I made it work somehow and it *almost* works out of the box, it might not be a good user experience. I'll disable the plugin for now and maybe come back to this later (though in a Webpack plugins incarnation).

**Comment by morgs32** [comment]
@fatfisz you break ground on the webpack plugin? Interested in helping.

**Comment by fatfisz** [comment]
I've actually managed to do what I needed, you can explore the results here: https://github.com/fatfisz/burdoc/tree/master/src/BurdocWebpackPlugin.

In a nutshell, I disable the `handle-imports` Next.js Babel plugin entirely, and instead I patch Webpack internals.

The `handle-imports` plugin in particular can almost be replaced by this:
- [patchImportParserPlugin](https://github.com/fatfisz/burdoc/blob/0665b14c10a69c9a80c8cb9918947605e3cf25e4/src/BurdocWebpackPlugin/patchImportParserPlugin.js), which takes care of providing chunk names for imports
- [patchImportDependencyTemplate](https://github.com/fatfisz/burdoc/blob/0665b14c10a69c9a80c8cb9918947605e3cf25e4/src/BurdocWebpackPlugin/patchImportDependencyTemplate.js), which takes care of patching the import template so that `__webpackChunkName` is attached to modules.

**Pull request closed without merging**
