### PR TITLE
Opt-into worker mode when appDir is enabled

### PR DESCRIPTION
**Pull request by shuding**
This unblocks further optimization opportunities as well as fixes for systematic problems such as NEXT-227. After this PR, only production mode of non-app projects will be running on the legacy main process mode.

### CODE REVIEW

**Review by feedthejim — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2267a080f0a6ec4ccb6aa272e81b331604304408

`pnpm testheadless test/e2e/app-dir/app-static/app-static-custom-handler.test.ts` 
- app-dir static/dynamic handling > should revalidate all fetches during on-demand revalidate

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should revalidate all fetches during on-demand revalidate

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not "revalidate 10: 0.30884734612075926"

      102 |         expect(newLayoutData).toBeTruthy()
      103 |         expect(newPageData).toBeTruthy()
    > 104 |         expect(newLayoutData).not.toBe(initLayoutData)
          |                                   ^
      105 |         expect(newPageData).not.toBe(initPageData)
      106 |       })
      107 |     }

      at Object.<anonymous> (e2e/app-dir/app-static/app-static.test.ts:104:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c8eceb96bf0b2c04dd73ed16be790be21c5c1865

`pnpm testheadless test/e2e/app-dir/app-static/app-static-custom-handler.test.ts` 
- app-dir static/dynamic handling > should revalidate all fetches during on-demand revalidate

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should revalidate all fetches during on-demand revalidate

    TIMED OUT: success

    undefined

    Error: expect(received).not.toBe(expected) // Object.is equality

    Expected: not "revalidate 360: 0.6327127027832915"

      569 |
      570 |   if (hardError) {
    > 571 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      572 |   }
      573 |   return false
      574 | }

      at check (lib/next-test-utils.js:571:11)
      at Object.<anonymous> (e2e/app-dir/app-static/app-static.test.ts:96:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a82e93f0f95be4cf221ab974645f2d8663fdeb57

`pnpm testheadless test/e2e/opentelemetry/opentelemetry.test.ts` 
- opentelemetry > app router > should handle RSC with fetch
- opentelemetry > app router > should handle route handlers in app router
- opentelemetry > pages > should handle getServerSideProps
- opentelemetry > pages > should handle getStaticProps when fallback: 'blocking'
- opentelemetry > pages > should handle api routes in pages

<details>
<summary>Expand output</summary>

  ● opentelemetry › app router › should handle RSC with fetch

    TIMED OUT: 1

    2

    undefined

      569 |
      570 |   if (hardError) {
    > 571 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      572 |   }
      573 |   return false
      574 | }

      at check (lib/next-test-utils.js:571:11)
      at getSanitizedTraces (e2e/opentelemetry/opentelemetry.test.ts:52:7)
      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:73:16)

  ● opentelemetry › app router › should handle route handlers in app router

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `opentelemetry app router should handle route handlers in app router 1`

    - Snapshot  - 12
    + Received  +  0

    @@ -1,20 +1,8 @@
      Array [
        Object {
          "attributes": Object {
    -       "next.span_name": "executing api route (app) /api/app/[param]/data/route",
    -       "next.span_type": "AppRouteRouteHandlers.runHandler",
    -     },
    -     "kind": 0,
    -     "name": "executing api route (app) /api/app/[param]/data/route",
    -     "parentId": "[parent-id]",
    -     "status": Object {
    -       "code": 0,
    -     },
    -   },
    -   Object {
    -     "attributes": Object {
            "http.method": "GET",
            "http.status_code": 200,
            "http.target": "/api/app/param/data",
            "next.span_name": "GET /api/app/param/data",
            "next.span_type": "BaseServer.handleRequest",

      150 |         await next.fetch('/api/app/param/data')
      151 |
    > 152 |         expect(await getSanitizedTraces(1)).toMatchInlineSnapshot(`
          |                                             ^
      153 |           Array [
      154 |             Object {
      155 |               "attributes": Object {

      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:152:45)

  ● opentelemetry › pages › should handle getServerSideProps

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `opentelemetry pages should handle getServerSideProps 1`

    - Snapshot  - 28
    + Received  +  2

      Array [
        Object {
          "attributes": Object {
            "http.method": "GET",
    -       "http.route": "/pages/[param]/getServerSideProps",
            "http.status_code": 200,
            "http.target": "/pages/param/getServerSideProps",
    -       "next.route": "/pages/[param]/getServerSideProps",
    -       "next.span_name": "GET /pages/[param]/getServerSideProps",
    +       "next.span_name": "GET /pages/param/getServerSideProps",
            "next.span_type": "BaseServer.handleRequest",
          },
          "kind": 1,
    -     "name": "GET /pages/[param]/getServerSideProps",
    +     "name": "GET /pages/param/getServerSideProps",
          "parentId": undefined,
    -     "status": Object {
    -       "code": 0,
    -     },
    -   },
    -   Object {
    -     "attributes": Object {
    -       "next.span_name": "getServerSideProps /pages/[param]/getServerSideProps",
    -       "next.span_type": "Render.getServerSideProps",
    -     },
    -     "kind": 0,
    -     "name": "getServerSideProps /pages/[param]/getServerSideProps",
    -     "parentId": "[parent-id]",
    -     "status": Object {
    -       "code": 0,
    -     },
    -   },
    -   Object {
    -     "attributes": Object {
    -       "next.span_name": "render route (pages) /pages/[param]/getServerSideProps",
    -       "next.span_type": "Render.renderDocument",
    -     },
    -     "kind": 0,
    -     "name": "render route (pages) /pages/[param]/getServerSideProps",
    -     "parentId": "[parent-id]",
          "status": Object {
            "code": 0,
          },
        },
      ]

      188 |         await next.fetch('/pages/param/getServerSideProps')
      189 |
    > 190 |         expect(await getSanitizedTraces(1)).toMatchInlineSnapshot(`
          |                                             ^
      191 |           Array [
      192 |             Object {
      193 |               "attributes": Object {

      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:190:45)

  ● opentelemetry › pages › should handle getStaticProps when fallback: 'blocking'

    TIMED OUT: 1

    3

    undefined

      569 |
      570 |   if (hardError) {
    > 571 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      572 |   }
      573 |   return false
      574 | }

      at check (lib/next-test-utils.js:571:11)
      at getSanitizedTraces (e2e/opentelemetry/opentelemetry.test.ts:52:7)
      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:240:16)

  ● opentelemetry › pages › should handle api routes in pages

    TIMED OUT: 1

    2

    undefined

      569 |
      570 |   if (hardError) {
    > 571 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      572 |   }
      573 |   return false
      574 | }

      at check (lib/next-test-utils.js:571:11)
      at getSanitizedTraces (e2e/opentelemetry/opentelemetry.test.ts:52:7)
      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:290:16)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f64d827d6a9fcb0373b8ddbce652f6ca14959814

`pnpm testheadless test/e2e/opentelemetry/opentelemetry.test.ts` 
- opentelemetry > pages > should handle getStaticProps when fallback: 'blocking'

<details>
<summary>Expand output</summary>

  ● opentelemetry › pages › should handle getStaticProps when fallback: 'blocking'

    TIMED OUT: succes

    success

    undefined

      569 |
      570 |   if (hardError) {
    > 571 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      572 |   }
      573 |   return false
      574 | }

      at check (lib/next-test-utils.js:571:11)
      at Object.<anonymous> (e2e/opentelemetry/opentelemetry.test.ts:249:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by feedthejim — APPROVED** [review]

**Pull request merged**
