### PR TITLE
example data-fetch project refactored

### PR DESCRIPTION
**Pull request by mertcanaltin**
I specified the type of getStaticProps function and the type of value it returned and defined the function as async 🎸

### CODE REVIEW

**Comment by maxproske** [comment]
(Community contributor) I think `function` is preferred over `const` for page components and `getStaticProps`.

https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md?plain=1#L12

_Originally posted by @huozhi in https://github.com/vercel/next.js/pull/38091#discussion_r911320691_

**Comment by mertcanaltin** [comment]
> (Community contributor) I think `function` is preferred over `const` for page components and `getStaticProps`.
> 
> https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md?plain=1#L12
> 
> _Originally posted by huozhi in [#38091 (comment)](https://github.com/vercel/next.js/pull/38091#discussion_r911320691)_

I didn't know that, thank you very much
I made a small change in the getStaticProps function, can you check it, thank you very much in advance @maxproske

**Comment by maxproske** [comment]
(Community contributor) Adding error handling is great, but I think the page component expects to receive the `stars` prop, and does not expect to receive the `error` prop.

Also if you're editting `index.tsx`, the same changes should probably be applied to `preact-stars.tsx`.

**Comment by mertcanaltin** [comment]
> (Community contributor) Adding error handling is great, but I think the page component expects to receive the `stars` prop, and does not expect to receive the `error` prop.
> 
> Also if you're editting `index.tsx`, the same changes should probably be applied to `preact-stars.tsx`.

I also implemented it in preact-stars @maxproske

**Comment by maxproske** [comment]
I'm just a community contributor like you, so you'll have to wait for a Next.js maintainer to review it.

**Comment by mertcanaltin** [comment]
> I'm just a community contributor like you, so you'll have to wait for a Next.js maintainer to review it.


sure thank you for answer

**Comment by mertcanaltin** [comment]
Greetings,  I'm so sorry to bother you, do you have a chance to review my code? @timneutkens

**Review by ijjk — COMMENTED** [review]
Hi, the errors here are purposefully not caught in `getStaticProps` as that prevents the cache from being updated on failure. To prevent users from starting with the wrong pattern I don't think we want to make this change, thanks though!

**Pull request closed without merging**
