### PR TITLE
[examples] Update styled-components to use Babel and Typescript

### LINKED ISSUE #36008: Custom _document file example for styled-components throws a TS bug after updating @types/react to ^18.0.0
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

I'm not entirely sure if it should be posted here or as an issue in the types/SC repo, so sorry if it shouldn't be here.
After updating @types/react to 18.0.0, I started noticing an error in the _documents.tsx file when using [this approach for styled components.](https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.js). I now get an error which says 
```
Class static side 'typeof MyDocument' incorrectly extends base class static side 'typeof Document'.
  The types returned by 'getInitialProps(...)' are incompatible between these types.
    Type 'Promise<{ styles: Element; html: string; head?: (Element | null)[] | undefined; }>' is not assignable to type 'Promise<DocumentInitialProps>'.
      Type '{ styles: JSX.Element; html: string; head?: (JSX.Element | null)[] | undefined; }' is not assignable to type 'DocumentInitialProps'.
        Type '{ styles: JSX.Element; html: string; head?: (JSX.Element | null)[] | undefined; }' is not assignable to type '{ styles?: ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[] | undefined; }'.
          Types of property 'styles' are incompatible.
            Type 'Element' is not assignable to type 'ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[] | undefined'.
              Type 'ReactElement<any, any>' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>[]': length, pop, push, concat, and 29 more.ts(2417)
```
Upon further investigation I discovered that in this part: 
```
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
```
the overwrite of styles seems to be causing trouble. `styles` are of type `styles?: ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[] | undefined` instead of `JSX.Element`. If we downgrade types back to "[^17.0.43](https://npmjs.com/package/@types/react)", it doesn't seem to be a problem anymore.

### Expected Behavior

Types should work correctly if the example made by SC is still relevant.

### To Reproduce

You can create a new project with `create next-app --typescript` and add the document from the file I linked above, you should see the error immediately.

### PR DESCRIPTION
**Pull request by rafae2k**
This PR is looking forward to improve documentation exemples about usage of Next.js with Typescript and Styled-components. 

I added Typescript types to the original exemple [Example app with styled-components using babel
](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components-babel)

## Feature

- [x] Related issues linked using 
- [x] Documentation added

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

fixes #36008

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Feel free to convert https://github.com/vercel/next.js/tree/canary/examples/with-styled-components-babel instead. Let's not add another example for this.

We prefer using TypeScript only, as it eliminates a category of issues and we believe it makes developers more productive.

**Comment by rafae2k** [comment]
> Feel free to convert https://github.com/vercel/next.js/tree/canary/examples/with-styled-components-babel instead. Let's not add another example for this.
> 
> We prefer using TypeScript only, as it eliminates a category of issues and we believe it makes developers more productive.

Hello @balazsorban44, how you doing? 

Great! Do you think it's best to quote the addition of TS in Docs or I just add the types to the code?

**Comment by balazsorban44** [comment]
No need to document anything, you can just convert the files. :+1:

**Comment by rafae2k** [comment]
> No need to document anything, you can just convert the files. 👍

Hello @balazsorban44, I created a new PR with the changes, so I'll close this one! 

[PR #36125](https://github.com/vercel/next.js/pull/36125)

**Pull request closed without merging**
