### PR TITLE
Using new `useInsertionEffect`.

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hi,
I thought to use new [`useInsertionEffect`](https://reactjs.org/docs/hooks-reference.html#useinsertioneffect) for `<Head  />` component hence it used to toggle CSS efficiently where previously we used `useLayoutEffect`.

```jsx
// Dummy component that we render as a child of Root so that we can
// toggle the correct styles before the page is rendered.
function Head({ callback }: { callback: () => void }): null {
  // We use `useInsertionEffect` to guarantee the callback is executed
  // as soon as React flushes the update.
  React.useInsertionEffect?.(() => callback(), [callback])
  return null
}
```

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by SukkaW** [comment]
> Hi, I thought to use new [`useInsertionEffect`](https://reactjs.org/docs/hooks-reference.html#useinsertioneffect) for `<Head />` component hence it used to toggle CSS efficiently where previously we used `useLayoutEffect`.
> 
> ```js
> // Dummy component that we render as a child of Root so that we can
> // toggle the correct styles before the page is rendered.
> function Head({ callback }: { callback: () => void }): null {
>   // We use `useInsertionEffect` to guarantee the callback is executed
>   // as soon as React flushes the update.
>   React.useInsertionEffect?.(() => callback(), [callback])
>   return null
> }
> ```
> 
> _Sorry if I made any mistakes :(_

`useInsertionEffect` should only be used in the CSS-in-JS libraries, as the insertion effect commits before Virtual DOM is committed to the "real" DOM, thus preventing the "flash of the screen".

And IMHO `<Head />` shouldn't be used to toggle the CSS (The existing codebase should switch to `useInsertionEffect` instead of relying on `<Head />`), thus the `useInsertionEffect` shouldn't be used here.

**Comment by sanjaiyan-dev** [comment]
> 

Sorry,
I thought this component used to toggle only CSS as it was described in comments 🤔

**Comment by sanjaiyan-dev** [comment]
> > Hi, I thought to use new [`useInsertionEffect`](https://reactjs.org/docs/hooks-reference.html#useinsertioneffect) for `<Head />` component hence it used to toggle CSS efficiently where previously we used `useLayoutEffect`.
> > ```js
> > // Dummy component that we render as a child of Root so that we can
> > // toggle the correct styles before the page is rendered.
> > function Head({ callback }: { callback: () => void }): null {
> >   // We use `useInsertionEffect` to guarantee the callback is executed
> >   // as soon as React flushes the update.
> >   React.useInsertionEffect?.(() => callback(), [callback])
> >   return null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Sorry if I made any mistakes :(_
> 
> `useInsertionEffect` should only be used in the CSS-in-JS libraries, as the insertion effect commits before Virtual DOM is committed to the "real" DOM, thus preventing the "flash of the screen".
> 
> And IMHO `<Head />` shouldn't be used to toggle the CSS (The existing codebase should switch to `useInsertionEffect` instead of relying on `<Head />`), thus the `useInsertionEffect` doesn't fit here.
> 
> The common usage of `<Head />` would be updating `title`, OpenGraph, and other meta tags (which `useEffect` should be used instead).

Sorry,
I thought this component used to toggle only CSS as it was described in comments 🤔

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/53617#issuecomment-1666610953

**Pull request closed without merging**
