### PR TITLE
Add with-ethers-hardhat example

### PR DESCRIPTION
**Pull request by silentlight**
## Examples

- Add with-ethers-hardhat example

### CODE REVIEW

**Comment by awareness481** [comment]
With the current state of web3 I really think it would be detrimental to allow this kind of content in the Next.js repo.

**Comment by silentlight** [comment]
Thank you for your feedback @awareness481. Can you elaborate a little bit more on saying "this kind of content"?

**Comment by guillaumegaluz** [comment]
@awareness481 Vercel seems to be looking into expanding support for crypto/Web3 https://vercel.com/docs/concepts/functions/edge-functions#crypto.

**Comment by leerob** [comment]
@awareness481 could you expand on why?

@guillaumegaluz note that’s for the cryptography web APIs, which are related, but not exactly the same 😁

**Comment by awareness481** [comment]
@leerob Above framework can be used auto mine ETH blocks. As you certainly know that is disallowed from most hosts, including Vercel. With Next.js being primarily a web framework I certainly disagree with adding an example with behavior that is not allowed in most server hosts.

**Comment by leerob** [comment]
@silentlight could you clarify the intent of the example? @awareness481 looking at the code, it doesn't seem like it's set up for that, but I could be missing something.

**Comment by awareness481** [comment]
> @silentlight could you clarify the intent of the example? @awareness481 looking at the code, it doesn't seem like it's set up for that, but I could be missing something.

Not the code above but the framework itself https://hardhat.org/hardhat-network/explanation/mining-modes.html#mining-modes

**Comment by leerob** [comment]
Closing as stale – if you would like to continue this, please open a new PR and we can take a look. Thank you so much! 🙏

**Pull request closed without merging**
