### PR TITLE
Adds a link to CSP where it's first referenced in the headers docs

### PR DESCRIPTION
**Pull request by liamlaverty**
### What?
Adds a link to CSP documentation the first time it's mentioned in the headers page here: https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy

### Why?
Convenience for users, as it's unclear at that point in the document that `CSP` is discussing `Content-Security-Policy`, and the first reference to its docs are at the end of the page. 

### How?
Added a link to the CSP doc here https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy

### CODE REVIEW

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 929d212502f55591227ea0f6cb41c5f53e1dc431

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 929d212502f55591227ea0f6cb41c5f53e1dc431

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 929d212502f55591227ea0f6cb41c5f53e1dc431

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
