### PR TITLE
[DRAFT] ci(workflow): run all of turbopack tests from manifest

### PR DESCRIPTION
**Pull request by kwonoj**
### What?
WEB-1169.

This PR updates workflow to let turbopack test runs all of the tests under its test manifest.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: be38b5f411e19f97f5e1759adb25f54912b61767

`pnpm testheadless test/e2e/app-dir/app/index.test.ts` 
- app dir > known bugs > should support React fetch instrumentation > server component client-navigation

<details>
<summary>Expand output</summary>

  ● app dir › known bugs › should support React fetch instrumentation › server component client-navigation

    page.waitForSelector: Timeout 10000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#value-1')
    ============================================================

      350 |     return this.chain(() => {
      351 |       return page
    > 352 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      353 |         .then(async (el) => {
      354 |           // it seems selenium waits longer and tests rely on this behavior
      355 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:352:10
      at Object.<anonymous> (e2e/app-dir/app/index.test.ts:1677:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — COMMENTED** [review]
It looks like production tests are slipping through again, can we clean up the enabled list to not include these?

```sh
 test/integration/prerender-invalid-catchall-params/test/index.test.js
 test/integration/prerender-legacy/test/index.test.js
 test/integration/prerender-no-revalidate/test/index.test.js
 test/integration/production-browser-sourcemaps/test/index.test.js
 test/integration/production-nav/test/index.test.js
 test/integration/query-with-encoding/test/index.test.js
 test/integration/react-profiling-mode/test/index.test.js
```

**Comment by kwonoj** [comment]
@ijjk Thanks, updated manifest with a comment.

**Comment by kwonoj** [comment]
Changing back to draft, as may need additional change to support new flag based test runner.

**Pull request closed without merging**
