### PR TITLE
Update example with firebase auth

### PR DESCRIPTION
**Pull request by 0x80**
- Update readme to reflect changes in Firebase console and fix any outdated instructions.
- Remove references to obsolete database url for Firebase client config
- Add sessions folder to prevent errors on first run

### CODE REVIEW

**Comment by 0x80** [comment]
By using the default file location for `session-file-store` the sessions are stored in the locally in the project's `sessions` subfolder. I've added that folder using `.gitkeep` to avoid the server printing errors when first started.

**Review by lfades — APPROVED** [review]
@0x80 Thank you 💯

**Comment by lfades** [comment]
@technoplato I personally haven't run this example in my environment, examples are mainly developed by the community. If it doesn't work open up an issue or a PR to fix it 🙏

**Comment by technoplato** [comment]
@lfades I am doing just that. Just having to learn a little bit as I was trying to use this as a basis for learning in itself. I'll keep working on will post any relevant PRs, certainly.

**Comment by 0x80** [comment]
@technoplato 	@lfades 	I think I had it working with 2.0 but I'm not 100% sure since I moved away from this approach shortly after. 

I moved to using firebase session cookies after this, which seems to be a better solution, but also ditched that after realizing that the server side auth related things were unnecessary for my app. I remember I also had trouble deploying to Now.sh because of incompatibilities between SSR and the firebase web SDK, so eventually I gave up and went with the most basic solution of not using server side auth at all. But that might not be an option for you...

Below you'll find the code I used for the server using firebase session cookies before I ditched server side auth all together. Hope it's helpful to someone.

```ts
import express from "express";
import bodyParser from "body-parser";
import cookieParser from "cookie-parser";
import next from "next";
import admin from "firebase-admin";

require("dotenv").config();

const port = parseInt(process.env.PORT || "3000", 10);
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

const firebase = admin.initializeApp();

app
  .prepare()
  .then(() => {
    const server = express();

    server.use(bodyParser.json());
    server.use(cookieParser());

    server.post("/api/sessionLogin", async (req, res) => {
      if (!req.body) return res.sendStatus(400);

      const idToken = req.body.idToken.toString();

      // @TODO add CSRF token check
      // https://firebase.google.com/docs/auth/admin/manage-cookies

      const expiresIn = 604800000; // week
      try {
        const sessionCookie = await firebase
          .auth()
          .createSessionCookie(idToken, { expiresIn });

        // Set cookie policy for session cookie.
        const options = {
          maxAge: expiresIn,
          httpOnly: true,
          secure: true
        };
        res.cookie("session", sessionCookie, options);
        res.json({ status: "success" });
      } catch (err) {
        res.status(401).send("UNAUTHORIZED REQUEST!");
      }
    });

    server.post("/api/sessionLogout", (req, res) => {
      res.clearCookie("session");
      res.json({ status: "success" });
    });

    /**
     * First handle the public routes that do not require auth session check
     */
    server.get("/", (req, res) => {
      return handle(req, res);
    });

    server.get("/login", (req, res) => {
      return handle(req, res);
    });

    server.get("/_next/*", (req, res) => {
      return handle(req, res);
    });

    /**
     * Then a catch all for the remaining routes which all require auth
     */
    server.get("*", (req, res) => {
      const sessionCookie = req.cookies.session || "";

      admin
        .auth()
        .verifySessionCookie(sessionCookie, true)
        .then(decodedClaims => {
          console.log("decodedClaims", decodedClaims);
          /**
           * @TODO check if user is admin using claims
           */
          return handle(req, res);
        })
        .catch(() => {
          // console.error(error.message);
          console.log("Failed to verify session cookie, redirect to login");
          // Session cookie is unavailable or invalid. Force user to login.
          res.redirect("/login");
        });
    });

    server.listen(port, err => {
      if (err) throw err;
      console.log(`> Ready on http://localhost:${port}`);
    });
  })
  .catch(err => console.error(err));
```

**Pull request merged**
