### PR TITLE
Add _document and _app pre-import

### PR DESCRIPTION
**Pull request by gwer**
This is an alternative to #23196 without pages pre-warm.

At #23187 @timneutkens disagreed with the need to warm up the pages. I think this issue requires additional discussion, but _app and _document can be warmed up right now.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.4s | -224ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +752 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.128 | 2.132 | 0 |
| / avg req/sec | 1174.9 | 1172.8 | ⚠️ -2.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.323 | 1.319 | 0 |
| /error-in-render avg req/sec | 1890.04 | 1894.8 | +4.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.6s | ⚠️ +228ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +752 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.6 kB | 10.6 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.27 MB | 5.27 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.6s | -103ms |
| nodeModulesSize | 43.6 MB | 43.6 MB | ⚠️ +752 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.135 | 2.168 | ⚠️ +0.03 |
| / avg req/sec | 1171.13 | 1153.07 | ⚠️ -18.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.316 | 1.331 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1899.16 | 1877.62 | ⚠️ -21.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| 597-12fee761..569d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 7.1 kB | 7.1 kB | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.7 kB | 60.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _app-d0eb668..79ef.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-d12ff..6063.js gzip | 3.4 kB | 3.4 kB | ✓ |
| amp-127483e4..9cd8.js gzip | 560 B | 560 B | ✓ |
| hooks-75994b..62d3.js gzip | 924 B | 924 B | ✓ |
| index-ac1ee6..819e.js gzip | 243 B | 243 B | ✓ |
| link-1cd4709..71e5.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..4d90.js gzip | 333 B | 333 B | ✓ |
| withRouter-0..60b0.js gzip | 329 B | 329 B | ✓ |
| Overall change | 8.72 kB | 8.72 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 324 B | 324 B | ✓ |
| Overall change | 324 B | 324 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "0VrlT9XEsNcu_q5zuYQis",
+        "buildId": "Ew47suhVgKDaxJOwm8plb",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_buildManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_ssgManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "0VrlT9XEsNcu_q5zuYQis",
+        "buildId": "Ew47suhVgKDaxJOwm8plb",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_buildManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_ssgManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "0VrlT9XEsNcu_q5zuYQis",
+        "buildId": "Ew47suhVgKDaxJOwm8plb",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_buildManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/0VrlT9XEsNcu_q5zuYQis/_ssgManifest.js"
+      src="/_next/static/Ew47suhVgKDaxJOwm8plb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 926c1683d8173955fee75e5cd989c1e49820f6e4

**Review by ijjk — COMMENTED** [review]
Hi, I'm gonna close this as it seems like further is discussion is needed/benchmarking done to see if this has any impact. Please open a discussion to continue investigation!

**Comment by gwer** [comment]
I don't think we need further discussion on this issue. There is no slowdown because _app and _document are loaded for every page.

**Comment by ijjk** [comment]
There is the case of API routes which have no need for `_app` and `_document` being loaded, also automatically statically optimized pages and prerendered pages don't need it to be loaded before they can be served, will re-open but continue discussion on the issue as we usually discuss changes like this before a PR to prevent the PR author from having to keep up with canary

**Comment by abriginets** [comment]
I think the bigger question here is should I get billed on Vercel for NextJS wasting 10 seconds to additionaly compile `_app` and `_document` for pages I defined to be SSR. From my perspective as an everyday NextJS user I should not deal with framework issues and focus on building things I want. I should not waste my time reading issues, pull requests and source code just to know why I'm paying more than I have to. I'm really surprised and shocked honestly that NextJS compiles additional code in production runtime causing very long TTFB. That hurts my SEO and UX. Is that possible to make `_app` and `_document` pre-import mandatory for pages where `getServerSideProps` is exported?

**Comment by gwer** [comment]
Oh, sorry @abriginets for long time without answer.

An opt-in configuration option has been added in this PR to allow developers to make decisions about whether to pre-import or not. And it's not enough to minimize TTFB, because there are only `_app` and `_documents` imported before server starts listening. For better optimization you need pre-import pages modules too. Something like this :: https://github.com/gwer/next-js-initial-freeze-workaround/blob/master/pages-preimport.js. 

But such a workaround is slow down the whole server start. And I see the only one way to get a fast start for statically optimized pages and slow start for low TTFB with SSR. This way is to use two different servers: one for statically optimized pages and other for SSR.

But you should keep in mind that all my decisions and suggestions are about standalone deployment, not in Vercel. I can contribute only to free open source part. Not to a third-party cloud platform.

**Comment by timneutkens** [comment]
> I think the bigger question here is should I get billed on Vercel for NextJS wasting 10 seconds to additionaly compile _app and _document for pages I defined to be SSR. From my perspective as an everyday NextJS user I should not deal with framework issues and focus on building things I want. I should not waste my time reading issues, pull requests and source code just to know why I'm paying more than I have to. I'm really surprised and shocked honestly that NextJS compiles additional code in production runtime causing very long TTFB. 

Just to be clear, Next.js does not ship the compilation to production, there is no bundling or anything you see in dev to compile code on the fly. The only thing that happens is that `_app` and `_document` are `require()`ed at runtime, same as page code, same as node_modules. There is no "10 seconds additional compile", that can only be caused by having top-level module code in your application that takes extremely long to run.

**Review by timneutkens — CHANGES_REQUESTED** [review]
pre-`require`ing the _app and _document is probably fine for the standalone mode @ijjk. I think this PR is fine to land without experimental opt-in if it checks for `minimalMode`, especially now that the `target` option is deprecated we can make improvements like these.

Just to be clear to future readers: "precompiling" here refers to requiring the code early which runs the top-level module code for _app and _document. It has nothing to do with compiling/bundling the files (e.g. through webpack).

**Comment by abriginets** [comment]
> > I think the bigger question here is should I get billed on Vercel for NextJS wasting 10 seconds to additionaly compile _app and _document for pages I defined to be SSR. From my perspective as an everyday NextJS user I should not deal with framework issues and focus on building things I want. I should not waste my time reading issues, pull requests and source code just to know why I'm paying more than I have to. I'm really surprised and shocked honestly that NextJS compiles additional code in production runtime causing very long TTFB.
> 
> Just to be clear, Next.js does not ship the compilation to production, there is no bundling or anything you see in dev to compile code on the fly. The only thing that happens is that `_app` and `_document` are `require()`ed at runtime, same as page code, same as node_modules. There is no "10 seconds additional compile", that can only be caused by having top-level module code in your application that takes extremely long to run.

@timneutkens for some reason Next.js deployed to Vercel was rendering every SSR page in my project for 10-15 seconds each time lambda was getting cold. I decided to move my project to Heroku (non-serverless env) and all those long cold starts stopped. If I redeploy my app to Heroku (which mean purging all Next.js cache) right now and try to hit any of the SSR page it would load for 2-3 seconds for the first time and then there will be no delays whatsoever for any subsequent request. I figured out that serverless container cold starts was not an issue (been monitoring logs for quite some time) as it always took no more than 400ms. For me it looks like Next.js is missing something in serverless env (something that is being persisted at the filesystem on Heroku or any other traditional hosting) and it needs to generate some data, or some cache, etc. before it could execute backend logic and serve html to users. I've been trying to dig up at least something but I couldn't find anything so I assumed that it might be dynamic imports, requires, etc.

**Comment by leerob** [comment]
> Next.js deployed to Vercel was rendering every SSR page in my project for 10-15 seconds each time lambda was getting cold.

Without a reproducible URL, it's hard to validate or verify this - but 10-15 is definitely not a lambda cold start IMO.

> I figured out that serverless container cold starts was not an issue (been monitoring logs for quite some time) as it always took no more than 400ms.

This sounds more in line with cold start times I've seen (400ms).

> This leads me into thinking that Vercel is not an option for hosting SSR/ISR-based Next.js apps at least for now.

One of the difficult parts about being a hosting platform is that there's only so much optimization you can do for user code. So in some instances, if code is written that takes 10s to fetch from an external API, there's not much you can do about it from the Vercel side.

There are many, many SSR / ISR Next.js applications on Vercel. Almost all of these: https://vercel.com/customers

**Comment by gwer** [comment]
@timneutkens 
> pre-requireing the _app and _document is probably fine for the standalone mode @ijjk. I think this PR is fine to land without experimental opt-in if it checks for minimalMode, especially now that the target option is deprecated we can make improvements like these.

Do you mean that we should check only `minimalMode` instead of new experimental option? Sounds good. But I still think that it's not enough to preimport only `_app` and `_document`. Pages import can take a long time too. And it would be useful to be able to enable pages preimport like [here](https://github.com/vercel/next.js/pull/23196). This will provide an opportunity to improve performance when stable TTFB is more important than server startup speed.

I see two options:
1. Pre-import `_app` and `_document` with `!minimalMode` and preimport pages with `!minimalMode && nextConfig.experimental.pagesPreimport`. It will make some speed-up for all by default. 
2. Pre-import `_app`, and `_document`, and pages with `nextConfig.experimental.pagesPreimport`. This solution will keep default behavior.

We can also make more complex and flexible configuration.
- If someone has only static optimized pages or they want to startup server ASAP (in dev environment for example), they don't need pre-import at all.
- If someone cares about TTFB, they need full pre-import.
- If someone has many instances of server with route-based balancer or with multi zones, they may need to pre-import only `_app` and `_documents`. This configuration will slow down the first requests, but will help to avoid overhead. But if requests time is more important for you then some extra memory consumption and server startup speed you may still need to enable all pages pre-import even in this case. Until it becomes possible to pre-import only the necessary pages.

**Comment by abriginets** [comment]
@leerob is there a chance that those customers host their backends somewhere else instead of storing all the codebase in Next.js as monorepo? Maybe my issue with Next.js lies in extensive backend codebase leading Next.js to struggle with it at the runtime?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19.4s | -286ms |
| buildDurationCached | 7.4s | 7.5s | ⚠️ +33ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +705 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.235 | 4.177 | -0.06 |
| / avg req/sec | 590.33 | 598.45 | +8.12 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.173 | 2.116 | -0.06 |
| /error-in-render avg req/sec | 1150.49 | 1181.39 | +30.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 5.01 kB | 5.01 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| buildDuration | 23.7s | 23.9s | ⚠️ +180ms |
| buildDurationCached | 7.4s | 7.6s | ⚠️ +253ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +705 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.391 | 4.232 | -0.16 |
| / avg req/sec | 569.36 | 590.72 | +21.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.079 | 2.172 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1202.22 | 1151.24 | ⚠️ -50.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.1 kB | 42.1 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | gwer/next.js app_document_pre_warm | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: e503c9ac4277b68b48373c37cd019d8c9f1dfaeb

**Review by ijjk — APPROVED** [review]

**Pull request merged**
