### PR TITLE
Use custom Babel loader to avoid using separate Babel copies for loader and loader options

### PR DESCRIPTION
**Pull request by loganfsmyth**
This resolves the

> .value is not a valid Plugin property

error showing up for people in https://github.com/zeit/next.js/issues/4227

cc @timneutkens

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thank you for helping pave the path for next.js' babel setup @loganfsmyth! Is there a defined pattern you'd want next.js users to do when [we have some additional changes](https://github.com/nteract/nteract/blob/e91ef568625c7d16f8a86f275c1c59ad0eb68e1f/packages/webpack-configurator/index.js#L58) to how babel and webpack are used?

**Comment by loganfsmyth** [comment]
@rgbkrk I think it depends on what your goal is for the additional changes.

If you want to be able to add additional plugins and such, I'd personally say it would be up to Next to expose a `config.babel` handler could either

* Be called for every file, and passed into the loader implemented in this PR
* Be called once up front to provide extra config values to merge into Next's config.

However, since your changes seem more focused on your specific usecase of compiling a specific set of `node_modules`, what you have isn't _too_ bad. My main concern however is that your logic there relies on the using having configured a `.babelrc`, since your logic on its own will compile those modules, but not enable any plugins/presets on its own.

**Comment by rgbkrk** [comment]
> I'd personally say it would be up to Next to expose a config.babel handler could either

That seems like a really smart idea so that it remains consistent like this PR.

> However, since your changes seem more focused on your specific usecase of compiling a specific set of `node_modules`, what you have isn't too bad. My main concern however is that your logic there relies on the using having configured a `.babelrc`, since your logic on its own will compile those modules, but not enable any plugins/presets on its own.

I'd love to ask you more questions in the nteract monorepo if it's alright so I don't end up derailing your PR within next.js. As long as you've got the cycles, I'd love to figure out an ideal setup since I'm also [transitioning us to babel 7 right now](https://github.com/nteract/nteract/pull/2888). Really happy to outline what we're doing and ensure we help others with monorepo + next + custom babel. It's ok if not, I'm sure you're plenty busy with lots of projects.

**Comment by loganfsmyth** [comment]
@rgbkrk No problem, happy to try to answer any questions you have over there. Babel's Slack is also public if chat would be easier for quick back-and-forth discussions.

**Review by timneutkens — APPROVED** [review]
I really like this solution 👍 Thanks @loganfsmyth  😌

**Comment by timneutkens** [comment]
Apparently we didn't have a test for compiling with a custom `.babelrc` so I've added one.

**Comment by timneutkens** [comment]
Thank you very much @loganfsmyth 🙌

**Pull request merged**
