### PR TITLE
Include create-next-app in the readme

### PR DESCRIPTION
**Pull request by jxom**
Hey!

So I noticed that `create-next-app` is scattered in all the examples, however I found it surprising that there was no mention of it in the readme. I decided to include instructions to how to quickly set up a Next.js app with Create Next App. If you'd rather include this in another section however, let me know!

Cheers :)

### CODE REVIEW

**Comment by timneutkens** [comment]
This is actually on purpose, since the introduction introduces you to code concepts.
I'd like to keep it out of the main readme since it might lead to confusion. It serves great for the examples though, since it can automatically set up the example 👌

**Comment by jxom** [comment]
Fair enough!

**Comment by timneutkens** [comment]
And I just saw you made #4000 😄

**Pull request closed without merging**
