### PR TITLE
docs: Add 'DO NOT EDIT' comment

### PR DESCRIPTION
**Pull request by ghost**
### What?

Adds missing "DO NOT EDIT" comment to some of the shared documentation pages"

### Why?

A few of the shared documentation files didn't have the comment to not edit them.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: db70a92b178642e39854b1b848f0d57726dc1bd2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: db70a92b178642e39854b1b848f0d57726dc1bd2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: db70a92b178642e39854b1b848f0d57726dc1bd2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by delbaoliveira — APPROVED** [review]
Thank you!

**Pull request merged**
