### PR TITLE
Add next/error

### PR DESCRIPTION
**Pull request by nkzawa**
This PR enables to import default error page component with `next/error`.
It's intended to be used for displaying errors occurred on `getInitialProps` like https://github.com/zeit/next.js/issues/746#issuecomment-274850407, thanks to @dizlexik for sharing his workaround ! 

Fixes https://github.com/zeit/next.js/issues/746

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Looks good!

**Comment by sedubois** [comment]
@nkzawa Is there any recommendation on how to display this error page, in case it's not triggered in `getInitialProps`? 

For example with Apollo client:
- the `render` method might receive a `data.error` parameter in case of some generic issue
- or simply, we may issue a GraphQL query which doesn't give any result, in which case `render` will receive empty data. In this case I'd like to display the error page you provide with a status of 404.

**Comment by nkzawa** [comment]
@sedubois You mean to render the error page on custom server ? It would be something like this.

```js
res.statusCode = 404
app.renderError(err, req, res, pathname, query)
```

But basically, I think you should use `getInitialProps` rather than fetching data on custom server.

**Comment by sedubois** [comment]
@nkzawa I don't mean custom server, but simply rendering the error page from within a component  Not from `getInitialProps` but instead from e.g `componentWillMount`. 

```js
  componentWillMount() {
    if (this.props.XXX === YYY) {
      // render error page
    }
  }
```

**Comment by nkzawa** [comment]
@sedubois I think you can just do that on `render` ?

```js
render () {
  if (this.props.XXX === YYY) {
     return <ErrorPage statusCode={500} />
  }
  ...
}
```

But I think it's weird you do this on `componentWill`

**Comment by sedubois** [comment]
Thanks, that works. I was rather wondering how to render _only_ that component. But that will do for now.

**Pull request merged**
