### PR TITLE
fix: infinite redirection loop when accessing user's preferred locale-prefixed path with middleware present

### LINKED ISSUE #55648: 307 redirect loop when using locale together with middleware in 13.5.1
### Link to the code that reproduces this issue

https://github.com/c0per/307-loop-i18n-middleware

### To Reproduce

1. set `defaultLocale` to something different than `preferredLocale` (from header `accept-language`)
2. npm run dev
3. access `http://localhost:3000/en` or `http://localhost:3000/fr` or `http://localhost:3000` or with trailing slash

### Current vs. Expected behavior

image

Currently, Next.js 13.5.1 will stuck in 307 loop if:
- turn on `localeDetection` (which is enabled by default)
- set `defaultLocale` different from user's `preferredLocale`
- use a middleware

Expected behavior:

It doesn't stuck.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Internationalization (i18n)

### Additional context

_No response_

<sub>[NEXT-2627](https://linear.app/vercel/issue/NEXT-2627/307-redirect-loop-when-using-locale-together-with-middleware-in-1351)</sub>

### PR DESCRIPTION
**Pull request by masnormen**
# What? / Why?

This PR will fix #55648.

When the `defaultLocale` of a Nextjs project is different than the user's `preferredLocale`, and user accesses that locale path, Next js somehow will infinitely redirect to the same page.

1. Say the `defaultLocale` of Nextjs project is 'en'. And the project has other locale 'id'
2. User's `preferredLocale` (Accept-Language header) is 'id'
3. User access /id
4. User gets redirected to /id again infinitely

image

This happens only when using a middleware.

# How?

The function `getLocaleRedirect` seems to be called twice when we fetch `GET /id`. One triggered somewhere when handling the middleware call (?), and one triggered somewhere in `invokeRender` in router-server.

The first call correctly detect that the user is already on the right URL ('/id', as in the `preferredLocale`). But the second call somehow fails to determine it.

I've noticed that only this second call of `getLocaleRedirect` is problematic, and the second call can be distinguished by the header `x-invoke-path`. Infinite redirect is solved by detecting if the invoke path is the same as current locale.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6d6cec73f894cfe688f074d9a27c51d9eb16612c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 63814a8e91d219ba43d7a6a4299c73c1fd8b121d

`pnpm test-start test/e2e/app-dir/navigation/navigation.test.ts`
- app dir - navigation > navigation between pages and app > should not continously initiate a mpa navigation to the same URL when router state changes

<details>
<summary>Expand output</summary>

  ● app dir - navigation › navigation between pages and app › should not continously initiate a mpa navigation to the same URL when router state changes

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#link-to-slow-page')
      -   locator resolved to visible <a href="/slow-page" id="link-to-slow-page">To /slow-page</a>

      421 |     return this.chain(() => {
      422 |       return page
    > 423 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      424 |         .then(async (el) => {
      425 |           // it seems selenium waits longer and tests rely on this behavior
      426 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:423:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by masnormen** [comment]
is it possible that the test is flaky? it seems that the test gives different results everytime I run it locally. even when i removed my modification.

**Comment by samcx** [comment]
@masnormen That one is indeed a flaky test! Taking a look at your <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>.

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, we shouldn't be relying on `x-invoke-path` here as that is a local `router-server` implementation detail that we want to eventually get rid of, I opened https://github.com/vercel/next.js/pull/62606 which has an alternative fix for this carrying over your test as well.

**Comment by masnormen** [comment]
> Hi, we shouldn't be relying on `x-invoke-path` here as that is a local `router-server` implementation detail that we want to eventually get rid of, I opened https://github.com/vercel/next.js/pull/62606 which has an alternative fix for this carrying over your test as well. 

Hi. Yeah that's great too. Using headers directly does feel too hacky.

**Pull request closed without merging**
