### PR TITLE
fixes the logging by showing full URLs only on demand

### LINKED ISSUE #58087: [next 14] logging.fetches.fullUrl condition is inverted: everyone has full logs ON (a PR to fix it is linked)
### Link to the code that reproduces this issue

https://github.com/raphaelbadia/nextjs-appdir-truncates-logs

### To Reproduce

1. start the application
2. open http://localhost:3000
3. look at the terminal: URLs are truncated anyway

### Current vs. Expected behavior

I expect the URLs to be fully shown, not truncated.

The condition is currently inverted : everyone using nextjs 14 has full URLs logged.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.18.2
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: 8.9.2
    Relevant Packages:
      next: 13.4.9-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.9-canary.1", newest: "14.0.2-canary.13".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
✨  Done in 2.38s.
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I read nextjs's source and realised the condition in `packages/next/src/server/next-server.ts` is wrong. I've inverted it in this PR : #58088

### PR DESCRIPTION
**Pull request by raphaelbadia**
fixes #58087

Currently in Next 14, everyone has fullURL flag turned to true, this PR reverts the condition.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for this change to make sure it doesn't regress in the future?

**Comment by raphaelbadia** [comment]
> Can you add a test for this change to make sure it doesn't regress in the future?

Sure, but never contributed to next before so that's probably going to take a while 😅

**Comment by raphaelbadia** [comment]
@timneutkens any clue on how to test `next-server` file, please? I couldn't find an example of testing with it.
I modified the e2e test a bit to make sure that the logs contains `..` or not depending on the setting in package.json, but it seems that they do not call next-server.ts. So it's a coverage improvement, but doesn't protect against the bug I found in the first place

**Comment by jordanpurinton** [comment]
Good find. This was confusing me a bunch.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.7s | N/A |
| buildDurationCached | 6s | 6.2s | ⚠️ +117ms |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 422ms | 422ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| 170-HASH.js gzip | 26.7 kB | 26.7 kB | N/A |
| 199.HASH.js gzip | 181 B | 185 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 240 B | 241 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 194 B | N/A |
| _error-HASH.js gzip | 183 B | 182 B | N/A |
| amp-HASH.js gzip | 501 B | 501 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 349 B | 350 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.6 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 309 B | N/A |
| script-HASH.js gzip | 384 B | 384 B | ✓ |
| withRouter-HASH.js gzip | 307 B | 306 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| index.html gzip | 527 B | 530 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 523 B | 525 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.5 kB | 93.5 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 622 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | raphaelbadia/next.js raphaelbadia/fix-logging-verbose-condition | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 93.9 kB | 93.9 kB | ✓ |
| app-page-tur..prod.js gzip | 94.7 kB | 94.7 kB | ✓ |
| app-page-tur..prod.js gzip | 89.2 kB | 89.2 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.6 kB | 88.6 kB | ✓ |
| app-route-ex...dev.js gzip | 24 kB | 24 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 930 kB | 930 kB | ✓ |

</details>

</details>
Commit: 8c3d2fe16d120facbdb017e1c97c62135b9fc5f3

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8c3d2fe16d120facbdb017e1c97c62135b9fc5f3

`pnpm test-dev test/e2e/app-dir/logging/fetch-logging.test.ts` 
- app-dir - logging > with fetches default logging > should not contain metadata internal segments for dynamic metadata routes
- app-dir - logging > with fetches verbose logging > should not contain metadata internal segments for dynamic metadata routes

<details>
<summary>Expand output</summary>

  ● app-dir - logging › with fetches verbose logging › should not contain metadata internal segments for dynamic metadata routes

    TIMED OUT: /success/

    undefined

    Error: expect(received).not.toContain(expected) // indexOf

    Expected substring: not "[[...__metadata_id__]]"
    Received string:        " GET / 200 in 121ms
     ✓ Compiled /dynamic/[slug]/icon/[[...__metadata_id__]] in 301ms
     GET /dynamic/big/icon 200 in 547ms
    "

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:184:11)

  ● app-dir - logging › with fetches default logging › should not contain metadata internal segments for dynamic metadata routes

    TIMED OUT: /success/

    undefined

    Error: expect(received).not.toContain(expected) // indexOf

    Expected substring: not "[[...__metadata_id__]]"
    Received string:        " GET / 200 in 124ms
     ✓ Compiled /dynamic/[slug]/icon/[[...__metadata_id__]] in 285ms
     GET /dynamic/big/icon 200 in 506ms
    "

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/logging/fetch-logging.test.ts:184:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]
Thanks!

**Pull request merged**
