### PR TITLE
fix: Enable SearchParams to be displayed after redirect in Server Action

### LINKED ISSUE #62525: `redirect(...)` with search params doesn't work in 14.1.1
### Link to the code that reproduces this issue

https://github.com/chungweileong94/next-bug-redirect-with-search-params

### To Reproduce

1. Start the application with `next dev`
2. Click the "Add some search params" button

### Current vs. Expected behavior

Expected: 
- It should display the current search parameters on the page.
- The middleware `req.nextUrl` should contain search params

Current:
- It didn't show any search params on the page until we refreshed the page manually. 
- The middleware `req.nextUrl` doesn't contains any search params

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.14.0
Relevant Packages:
  next: 14.1.1-canary.72 // Latest available version is detected (14.1.1-canary.72).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

It was working before in 14.1 and prior to that version. 
Note that the "Clear search params" link on the page also doesn't work as expected, if you click on the "Add some search params" button and click the link afterward.

<sub>[NEXT-2620](https://linear.app/vercel/issue/NEXT-2620/redirect-with-search-params-doesnt-work-in-1411)</sub>

### PR DESCRIPTION
**Pull request by coffeecupjapan**
### What?
Fixes https://github.com/vercel/next.js/issues/62525
Closes NEXT-2620

Since codes below do not consider searchParams, `redirect` in server action removes all searchParams passed from client side.
 https://github.com/vercel/next.js/commit/93e4bb823ccb6452ba591e29a3ec0b258b3a9b5c#diff-c809d50461027cdba7c092e564818b1172133d337abc5c513f829c94c8483dc6R186

So I just add conditional branch for searchParams.

---

lint, prettier was applied.
Also I have done tests by commands below. and it was all passed.

```
pnpm testonly --testPathPattern "integration" -t "redirect"
```

### CODE REVIEW

**Review by shuding — COMMENTED** [review]
Thanks for fixing! I think we need a test case for this. You can refer to https://github.com/vercel/next.js/tree/canary/test/e2e/app-dir/actions to see how you can add one.

**Comment by coffeecupjapan** [comment]
@shuding 
OK. I added a test. Thank you for your advise.
But it's weird that it always throw timeout error when I test for 

```
pnpm test-dev test/e2e/app-dir/actions/app-action.test.ts -t "displays searchParams correctly when redirecting with SearchParams"
```

command. 
Since that I cannot test for my test code in my local environment.
Can you check for my test codes ?

**Comment by chungweileong94** [comment]
> Since that I cannot test for my test code in my local environment.
> Can you check for my test codes ?

Just ran the test from my local env, LGTM!

**Comment by coffeecupjapan** [comment]
@chungweileong94 
Thank you for testing!

**Comment by chungweileong94** [comment]
@coffeecupjapan Now that I look at the test that you wrote, I don't think this fixes the #62525. 

In the test, you redirect to `/redirects/action-redirect/redirect-target?baz=1`, which wasn't really a problem before (at least based on my testing, correct me if I'm wrong). However, if you try to redirect to `/redirects/action-redirect?baz=1`, it will not work, basically, it won't work if you try to redirect to the same pathname with different search params.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5da904fe2e043e52e78ec08e0ea2cc3ccad4b218

`pnpm test test/integration/edge-runtime-module-errors/test/module-imports.test.js`
- Edge runtime code with imports > Edge API statically importing node.js module > throws unsupported module error in dev at runtime and highlights the faulty line

<details>
<summary>Expand output</summary>

  ● Edge runtime code with imports › Edge API statically importing node.js module › throws unsupported module error in dev at runtime and highlights the faulty line

    expect(received).toBe(expected) // Object.is equality

    Expected: 500
    Received: 404

      86 |       context.app = await launchApp(context.appDir, context.appPort, appOption)
      87 |       const res = await fetchViaHTTP(context.appPort, url)
    > 88 |       expect(res.status).toBe(500)
         |                          ^
      89 |       await check(async () => {
      90 |         expectUnsupportedModuleDevError(
      91 |           moduleName,

      at Object.toBe (integration/edge-runtime-module-errors/test/module-imports.test.js:88:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ztanner — APPROVED** [review]
@coffeecupjapan thanks for the PR & test-case!

**Review by ijjk — APPROVED** [review]

**Pull request merged**
