### PR TITLE
Set cache-control public

### PR DESCRIPTION
**Pull request by jonespen**
Google Cloud CDN will automatically [cache responses with `Cache-Control: public`](https://cloud.google.com/cdn/docs/caching). Seems like [this is the way Cloudflare works as well](https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache-). Not sure if this has any undesired consequences, but according to the [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives), `public` "Indicates that the response may be cached by any cache." Afaik the files behind `BUILD_ID` are completely static and could/should be cached anyway. 

Someone who knows more about caching then me should probably review this. If it's a breaking change, perhaps it could make it configurable from next.config.js?

Edit: I just saw https://github.com/zeit/next.js/issues/4105, perhaps a config variable would more suitable? Something like `cacheControlHeader`, which defaults to `max-age=31536000, immutable`

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
The change itself looks alright to me!

**Review by timneutkens — CHANGES_REQUESTED** [review]
@jonespen could you add an integration test for this? There's a few looking up headers already, so you can most likely copy from there

**Comment by jonespen** [comment]
Oh man, I still stink at git. Shout if you want me to start from scratch.

Anyway, added integration tests checking the Cache-Control header for _next/ resources. Also, added a fix (and test) for #4250.

**Comment by timneutkens** [comment]
Ehm, not sure what you did there 😅, could you create a new PR with just the change + tests, that'd be awesome ❤️

**Pull request closed without merging**
