### PR TITLE
fix: upgrade commander from 2.20.0 to 2.20.3

### PR DESCRIPTION
**Pull request by mayank1513**
upgrade commander from 2.20.0 to 2.20.3.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 002cbd69918601e5efa866b569ebf3da91f2bc11

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 002cbd69918601e5efa866b569ebf3da91f2bc11

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 002cbd69918601e5efa866b569ebf3da91f2bc11

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 002cbd69918601e5efa866b569ebf3da91f2bc11

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
see https://github.com/vercel/next.js/pull/55793#issuecomment-1731313327

**Pull request closed without merging**
