### PR TITLE
Add with-react-ga example

### PR DESCRIPTION
**Pull request by vinaypuppal**
Based on some suggestions from #160 
This example shows the most basic way to use [react-ga](https://github.com/react-ga/react-ga) with NextJs.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Awesome Vinay ❤️

**Comment by exogenesys** [comment]
Hi, I am implemented everything using this example. Put in my tracking ID in `analytics.js`. Everything is getting logged perfectly but there is no response from Google Analytics. 

I put in the code in a component called `TopBar.js` component which is present on every page. I use the same page for implementing NProgress. 

If you guys could help me out, that'd be awesome. Thanks a lot. :)

**Comment by vinaypuppal** [comment]
@exogenesys Are you using any AdBlockers in your browser? They might block GA. Try to check in incognito mode with all browser extensions disabled.

**Comment by exogenesys** [comment]
@vinaypuppal Someone helped me out over [here](https://github.com/zeit/next.js/issues/160). It's working now. Thanks a lot. :)

**Comment by mattfysh** [comment]
@vinaypuppal thanks for the example. Do the logged page views work only because upon nav the entire user-defined Component tree gets unmounted and remounted (in this case, the `<Layout>` component)?

Any concerns that this example will break if the zeit team fix this in future (e.g. to support page transitions, or to maintain state in header or footer between pages)?

**Comment by timneutkens** [comment]
@mattfysh by that time the example will be updated 👌 No worries there 😄

**Comment by mattfysh** [comment]
cool, thanks @timneutkens - one more thing, I noticed the title being sent to GA is for the page before the one being logged, to fix this in componentDidMount I used `setTimeout(logPageView)`

**Comment by mattfysh** [comment]
@timneutkens @vinaypuppal  - I believe you now have to eat your hat.

Just upgraded to next v4 and this example no longer works... any ideas how to fix?

**Pull request merged**
