### PR TITLE
Improved "Network" url in cli

### LINKED ISSUE #11367: View the app "On Your Network"
### View the app "On Your Network"

By default create-react-app make the app live on `localhost` as well as your network.
This would make it easier to test on mobile devices. Also the current way has the text mixing in with all the other details and becomes harder to find. I would be better to highlight somehow, maybe draw a box around it.
```sh
[ info ]  ready on http://localhost:3000
```

react

### PR DESCRIPTION
**Pull request by kletse**
### What?
Fix an old feature request to show the current ip address in the cli 

### Why?
Improve DX

### How?
Look at the actual available network interfaces and use the first relevant IP.
Picks an IPv4 or IPv6 hostname based on the hostname used to show the url for 'Local:', so both are of the same IP version.

fixes #11367 
related to PR #22352

Example output:
image

### CODE REVIEW

**Review by leerob — CHANGES_REQUESTED** [review]
Could you add tests please?

**Comment by kletse** [comment]
@leerob Should be doable to actually unit test the function I added. Give me some time to figure this out over the weekend. 😀

**Comment by BlankParticle** [comment]
This is a feature that would make my life so much easier.
Is there anyway I could help?

> Could you add tests please?
I can't think of any way how the function in question can be tested as I have little to no experince in testing. Can you please tell how it should be tested, then I will try to add a test based on the requirement.

Thanks

**Comment by SrPatinhas** [comment]
@kletse were you able to add some tests? This would be a nice feature for the devs

**Review by ijjk — APPROVED** [review]
Hi, thanks for the PR! Sorry for the lag here, went ahead and added a test case for this in https://github.com/vercel/next.js/pull/72634 and got it up to date with canary

**Pull request closed without merging**
