### PR TITLE
parallel routes: fix catch all route support

### LINKED ISSUE #48719: Parallel routes do not clear slot with [...catchAll]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: N/A
  pnpm: 8.8.0
Relevant Packages:
  next: 13.5.4-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/Yukioru/next-parallel-routes-bug
https://codesandbox.io/p/github/Yukioru/next-parallel-routes-bug/main
https://next-parallel-routes-bug.vercel.app

### To Reproduce

You have to use soft navigation

1. Click "To /overview" page
2. Slot displays correctly with contents of the "Overview Extension"
3. Click "To /demo" page
4. The slot has not cleared

image

### Describe the Bug

Once the slot is shown, it is not cleared if the URL does not match.
A similar bug has already been described in Issue: https://github.com/vercel/next.js/issues/48124, but the solution with `[...catchAll]` route did not help. The route is not called.

If you do a hard navigation, you will see that the `/demo` slot segment corresponds to the default.js route, but it does not show up.

### Expected Behavior

Using soft navigation (next/link) the slot should be cleared by the `[...catchAll]` route (or the `default.js` route if possible).

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

Vercel, CodeSandbox

<sub>[NEXT-1394](https://linear.app/vercel/issue/NEXT-1394/parallel-routes-do-not-clear-slot-with-[catchall])</sub>

### LINKED ISSUE #49662: [NEXT-1160] Clicking Links in intercepted routes does not unmount the interceptor route
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/mkarajohn/nextgram/draft/restless-leftpad?file=/components/frame/index.js

### To Reproduce

1. Open the codesandbox in a new separate tab in order to be able to see the actual browser URL
2. Click on a photo in order to intercept the route and open the modal with the photo details.
3. Instead of clicking on the overlay click the "go back" link instead, located just below the photo

### Describe the Bug

When you click the `Link` and the URL changes to `/` the interceptor route remains mounted and does not go away. 

### Expected Behavior

I would expect that since the route was changed (via `Link` no less) the interceptor page should disappear once the route that it was intercepting was changed. 

[Screencast from 11-05-2023 04:23:04 ΜΜ.webm](https://github.com/vercel/next.js/assets/3789226/1e82fc92-9801-4b57-a7d8-d34c56078391)

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1160](https://linear.app/vercel/issue/NEXT-1160/clicking-links-in-intercepted-routes-does-not-unmount-the-interceptor)</sub>

### PR DESCRIPTION
**Pull request by feedthejim**
This PR fixes a bug where parallel routes would not apply appropriately on navigation when used within slots.

The following scenarios:
```
/foo
   /bar
   /@slot
     /[...catchAll]
```

or 

```
/foo
  /[...catchAll]
  /@slot
     /bar
```

will now function correctly when accessing /foo/bar, and Next.js will render both /bar and the catchall slots.

The issue was that the tree constructed by `next-app-loader` for a given path, /foo/bar in the example, would not include the paths for the catch-all files at build time. The routing was done 1-1 when compiling files, where a path would only match one file, with parallel routes, a path could hit a defined path but also a catch all route at the same time in a different slot.

The fix consists of adding another normalisation layer that will look for all catch-all in `appPaths` and iterate over the other paths and add the relevant information when needed.

The tricky part was making sure that we only included the relevant paths to the loader: we don't want to overwrite a slot with a catch all if there's already a more specific subpath in that slot, i.e. if there's /foo/@slot/bar/page.js, no need to inject /foo/@slot/bar/[...catchAll]. 

One thing that is not supported right now is optional catch all routes, will add later.

fixes #48719
fixes #49662

### CODE REVIEW

**Comment by feedthejim** [comment]
Current dependencies on/for this PR:
* canary
  * **PR #58198** <a href="https://app.graphite.dev/github/pr/vercel/next.js/58198" target="_blank">Graphite</a> 
    * **PR #58215** <a href="https://app.graphite.dev/github/pr/vercel/next.js/58215" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/58215?utm_source=stack-comment).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 78936ff79e069610c6a71c1f4ffa0421dd473269

`pnpm test-start test/e2e/app-dir/parallel-routes-and-interception/parallel-routes-and-interception.test.ts` 
- parallel-routes-and-interception > parallel routes > should throw an error when a route groups causes a conflict with a parallel segment

<details>
<summary>Expand output</summary>

  ● parallel-routes-and-interception › parallel routes › should throw an error when a route groups causes a conflict with a parallel segment

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: undefined

      208 |           )
      209 |         } else {
    > 210 |           await expect(next.start()).rejects.toThrow('next build failed')
          |                 ^
      211 |
      212 |           await check(
      213 |             () => next.cliOutput,

      at expect (../node_modules/.pnpm/expect@29.7.0/node_modules/expect/build/index.js:113:15)
      at Object.expect (e2e/app-dir/parallel-routes-and-interception/parallel-routes-and-interception.test.ts:210:17)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Comment by wlechowicz** [comment]
@feedthejim with this change, on canary.27, the "dismiss a modal with a catchAll" from [the docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal) gives me:
```
app\page.tsx
You cannot have two parallel pages that resolve to the same path. Please check /page and /[brand]/@modal/[...catchAll]/page. Refer to the route group docs for more information: https://nextjs.org/docs/app/building-your-application/routing/route-groups
```
Note that it's highlighting a conflict between the root page and a route nested under a dynamic segment, so clearly not two parallel pages that resolve to the same path.

**Comment by feedthejim** [comment]
Oh! I hadn't considered this use case. Mind sending me a repro?

**Comment by wlechowicz** [comment]
@feedthejim there you go: #58272

**Comment by RootedXpert** [comment]
Facing 404 issue while using route intercepting along with generateStaticParams function
image

With generateStaticParams 

https://user-images.githubusercontent.com/52459940/279181846-d0d1d0dd-f9c9-4f30-824d-803659b776e1.png

Without generateStaticParams 
image

**Comment by phxgg** [comment]
My modals in 14.0.2 display `[locale]/[...catchAll]/page.tsx` in the background (which just returns `notFound()`)

Next.js 14.0.1

https://github.com/vercel/next.js/assets/45177754/0747268e-b8d5-41e2-ab85-86712d442463

Next.js 14.0.2

https://github.com/vercel/next.js/assets/45177754/84ae492e-a505-4fce-a39d-864c28c8d93c

This is my folder structure. Also, not using `generateStaticParams()`

image

**Pull request merged**
