### PR TITLE
Add SRI support for Node.js Runtime 

### LINKED ISSUE #66901: Subresource Integrity (SRI) not working
### Link to the code that reproduces this issue

https://github.com/darthmaim-reproductions/vercel-next.js-66901

### To Reproduce

1. run `npm run build && npm run start`
2. Open http://localhost:3000 in a browser and inspect the source code	

### Current vs. Expected behavior

**Current**
No `integrity` attribute present on any `<script>`

**Expected**
`integrity` attribute added to `<script>`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Jan 11 04:09:03 UTC 2024
  Available memory (MB): 15953
  Available CPU cores: 8
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 6.11.0
Relevant Packages:
  next: 15.0.0-canary.32 // Latest available version is detected (15.0.0-canary.32).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next start (local), Other (Deployed)

### Additional context

The only change to the reproduction template was adding this config to `next.config.mjs`:
```js
  experimental: {
    sri: { algorithm: 'sha256' }
  }
```

There is a test (https://github.com/vercel/next.js/tree/canary/test/production/app-dir/subresource-integrity) that is supposed to test this, which has the same config as my reproduction repository, but I was not able to get SRI working.

There is a `.next/server/subresource-integrity-manifest.json` file generated which contains all the correct hashes.

### PR DESCRIPTION
**Pull request by unstubbable**
> [!NOTE]  
> This PR is best reviewed with hidden whitespace changes.

Support for setting [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attributes on app router scripts was added in https://github.com/vercel/next.js/pull/39729. But this only covered pages using the Edge Runtime.

With this PR, we're adding support for app pages using the Node.js Runtime. The only change that's needed for that, and which was probably just an oversight in the original PR, is reading the generated manifest file in `loadComponents`.

In a follow-up we should also add support for adding the `integrity` attribute to client component chunks that are injected into the head during server-side rendering, but that needs a change in React first.

fixes #66901

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a3d27b2b65f31371027f1dd254dbe0b88324c2fe

`pnpm test test/integration/export-default-map/test/index.test.js`
- Export with default map > production mode > should export with folder that has dot in name
- Export with default map > production mode > should export an amp only page to clean path
- Export with default map > production mode > should export hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly
- Export with default map > production mode > should export nested hybrid amp page correctly with folder
- Export with default map > production mode > should export hybrid index amp page correctly

<details>
<summary>Expand output</summary>

  ● Export with default map › production mode › should export with folder that has dot in name

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export an amp only page to clean path

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export nested hybrid amp page correctly with folder

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

  ● Export with default map › production mode › should export hybrid index amp page correctly

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       ▲ Next.js 15.1.1-canary.2

       Checking validity of types ...
       Creating an optimized production build ...
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
       Loading config from /root/actions-runner/_work/next.js/next.js/test/integration/export-default-map/next.config.js
     ✓ Compiled successfully
       Collecting page data ...
       Generating static pages (0/9) ...
       Generating static pages (2/9) 
    Error occurred prerendering page "/some". Read more: https://nextjs.org/docs/messages/prerender-error
    AssertionError: Assertion failed: WebAssembly is uninitialized

      at new module$contents$goog$asserts_AssertionError (../evalmachine.<anonymous>:102:1441)
      at module$contents$goog$asserts_doAssertFailure (../evalmachine.<anonymous>:103:354)
      at goog.asserts.assertExists (../evalmachine.<anonymous>:104:374)
      at Object.module$contents$amp$validator_validateString [as validateString] (../evalmachine.<anonymous>:2238:108)
      at Validator.validateString (../packages/next/dist/compiled/amphtml-validator/index.js:1:20650)
      at validateAmp (../packages/next/dist/export/routes/pages.js:106:34)
      at async exportPagesPage (../packages/next/dist/export/routes/pages.js:140:17)
      at async Span.traceAsyncFn (../packages/next/dist/trace/trace.js:156:20)
      at async exportPage (../packages/next/dist/export/worker.js:334:18)
      Export encountered an error on /some, exiting the build.
       ⨯ Static worker exited with code: 1 and signal: null
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| buildDuration | 33.8s | 30.7s | N/A |
| buildDurationCached | 28.8s | 25.7s | N/A |
| nodeModulesSize | 410 MB | 410 MB | ⚠️ +3.8 kB |
| nextStartRea..uration (ms) | 770ms | 765ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 50.8 kB | 50.8 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34 kB | 34 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| index.html gzip | 525 B | 523 B | N/A |
| link.html gzip | 539 B | 537 B | N/A |
| withRouter.html gzip | 520 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 203 kB | 203 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 672 B | 667 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| 523-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 523.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 323 kB | 323 kB | ✓ |
| app-page-exp..prod.js gzip | 127 kB | 127 kB | ✓ |
| app-page-tur..prod.js gzip | 140 kB | 140 kB | ✓ |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run...dev.js gzip | 313 kB | 313 kB | ✓ |
| app-page.run..prod.js gzip | 123 kB | 123 kB | ✓ |
| app-route-ex...dev.js gzip | 37.3 kB | 37.3 kB | ✓ |
| app-route-ex..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | ✓ |
| app-route-tu..prod.js gzip | 25.2 kB | 25.2 kB | ✓ |
| app-route.ru...dev.js gzip | 38.9 kB | 38.9 kB | ✓ |
| app-route.ru..prod.js gzip | 25.2 kB | 25.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.67 kB | 9.67 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.67 kB | 9.67 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.4 kB | 27.4 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | N/A |
| Overall change | 1.44 MB | 1.44 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js hl/sri-node | Change |
| - | - | - | - |
| 0.pack gzip | 2.05 MB | 2.05 MB | N/A |
| index.pack gzip | 72.8 kB | 71.7 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: a3d27b2b65f31371027f1dd254dbe0b88324c2fe

**Comment by darthmaim** [comment]
This will fix
- #66901

**Review by wyattjoh — APPROVED** [review]

**Comment by lilong7676** [comment]
That's great. Good work 🫶
Just one question, does Nextjs SRI only support app router mode?  Will you support it in the future? @unstubbable

**Pull request merged**
