### PR TITLE
Use ReactDom.hydrate just for initial renderer.

### PR DESCRIPTION
**Pull request by arunoda**
Use `ReactDom.hydrate()` just for initial renderer. For other cases just use `ReactDom.render()`

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Cool! Is there any confirmation about the difference between the two?

**Comment by arunoda** [comment]
@timneutkens I asked a question. Let's see the response.

**Comment by arunoda** [comment]
It seems like we should use this: https://github.com/facebook/react/issues/10934#issuecomment-332939928

**Comment by timneutkens** [comment]
Okay, cool! Feel free to merge once tests pass 👌

**Comment by timneutkens** [comment]
And lets do a new beta release afterwards

**Comment by arunoda** [comment]
Done: `next@4.0.0-beta.2`

**Pull request merged**
