### PR TITLE
Remove the parameterized-routing example

### PR DESCRIPTION
**Pull request by lfades**
No longer needed because of dynamic routes

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.5s | ⚠️ +272ms |
| nodeModulesSize | 48.6 MB | 48.6 MB | -81 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.87 kB | 5.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.29 kB | 5.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.03 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.11 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.7s | -156ms |
| nodeModulesSize | 48.6 MB | 48.6 MB | -81 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.87 kB | 5.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.29 kB | 5.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ✓ |
| _error.js gzip | 65.6 kB | 65.6 kB | ✓ |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | ✓ |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 65.8 kB | 65.8 kB | ✓ |
| link.js | 280 kB | 280 kB | ✓ |
| link.js gzip | 74.7 kB | 74.7 kB | ✓ |
| routerDirect.js | 273 kB | 273 kB | ✓ |
| routerDirect.js gzip | 72.8 kB | 72.8 kB | ✓ |
| withRouter.js | 273 kB | 273 kB | ✓ |
| withRouter.js gzip | 72.9 kB | 72.9 kB | ✓ |
| Overall change | 1.33 MB | 1.33 MB | ✓ |

</details>

</details>


Commit: cbd4bb386999d4f36a756fe4775fae5f17c4a6a4

**Review by timneutkens — CHANGES_REQUESTED** [review]
The readme should link to the alternative

**Comment by lfades** [comment]
@timneutkens it already does, but not in the examples of custom server

**Comment by timneutkens** [comment]
@lfades I meant the example readme, it shouldn't be removed as there's links going towards it.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.7s | ⚠️ +626ms |
| nodeModulesSize | 48.6 MB | 48.6 MB | ⚠️ +13.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | -18 B |
| main-HASH.js gzip | 5.89 kB | 5.87 kB | -16 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | -18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | -18 B |
| main-HASH.module.js gzip | 5.31 kB | 5.29 kB | -17 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | -18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.03 kB | -2 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.11 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -342,7 +342,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.3-canary.2";
+var version = "9.1.3-canary.1";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -1347,7 +1347,7 @@ function () {
           if (true) {
             _this3.getDependencies(route).then(function (deps) {
               deps.forEach(function (d) {
-                if (/\.js$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
+                if (!document.querySelector("script[src^=\"" + d + "\"]")) {
                   _this3.loadScript(d, route, false);
                 }
               });
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -341,7 +341,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.3-canary.2";
+var version = "9.1.3-canary.1";
 exports.version = version;
 var {
   props,
@@ -1177,7 +1177,7 @@ class PageLoader {
         if (true) {
           this.getDependencies(route).then(deps => {
             deps.forEach(d => {
-              if (/\.js$/.test(d) && !document.querySelector("script[src^=\"" + d + "\"]")) {
+              if (!document.querySelector("script[src^=\"" + d + "\"]")) {
                 this.loadScript(d, route, false);
               }
             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -44,9 +44,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-44f5b3a294fbc49824cf.js"
+        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.219514909c9db8a9ff76.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -67,9 +67,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-44f5b3a294fbc49824cf.js"
+        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -20,7 +20,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -65,9 +65,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-44f5b3a294fbc49824cf.js"
+        <script src="/_next/static/runtime/main-108e86883c2fd794bd5c.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-f0273520bbdb916796e0.module.js"
+        <script src="/_next/static/runtime/main-6664b64e499fca4460ff.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.5s | -230ms |
| nodeModulesSize | 48.6 MB | 48.6 MB | ⚠️ +13.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | -18 B |
| main-HASH.js gzip | 5.89 kB | 5.87 kB | -16 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | -18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | -18 B |
| main-HASH.module.js gzip | 5.31 kB | 5.29 kB | -17 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | -18 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | lfades/next.js r/parameterized-routing | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ✓ |
| _error.js gzip | 65.6 kB | 65.6 kB | -1 B |
| hooks.html | 4.19 kB | 4.19 kB | ✓ |
| hooks.html gzip | 1.07 kB | 1.07 kB | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 65.8 kB | 65.8 kB | ✓ |
| link.js | 280 kB | 280 kB | ✓ |
| link.js gzip | 74.7 kB | 74.7 kB | ✓ |
| routerDirect.js | 273 kB | 273 kB | ✓ |
| routerDirect.js gzip | 72.8 kB | 72.8 kB | ✓ |
| withRouter.js | 273 kB | 273 kB | ✓ |
| withRouter.js gzip | 72.9 kB | 72.9 kB | -1 B |
| Overall change | 1.33 MB | 1.33 MB | ✓ |

</details>

</details>


Commit: 60edc2c393806129199c8b0f6370fc712943539d

**Review by timneutkens — APPROVED** [review]

**Pull request merged**
