### PR TITLE
Add deploy now button to the top of all example READMEs

### LINKED ISSUE #1621: Deploy all the examples to now.sh
The links to the deployments can be added to the README.

Alternatively, only add a "Deploy with Now" button to all the READMEs.

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This adds a Deploy Now button to the top of all the READMEs in the `examples` directory. This way it's easy for someone to deploy the examples.

Closes #1621.

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
screen shot 2017-04-19 at 10 19 16 pm

**Comment by paulmolluzzo** [comment]
🎉

**Comment by timneutkens** [comment]
@paulmolluzzo there are a few new ones I just merged though 😅

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo there are a few new ones I just merged though 😅

I can sort that out in another PR.

**Comment by paulmolluzzo** [comment]
@timneutkens See #1779.

**Pull request merged**
