### PR TITLE
remove comments from production minified output

### PR DESCRIPTION
**Pull request by rashidul0405**
remove comments from production output through terser plugin
- using terserOptions for terser plugin
we can remove comments from dev as well? what do you think?

### CODE REVIEW

**Review by HaNdTriX — APPROVED** [review]

**Comment by timneutkens** [comment]
```
    --comments [filter]         Preserve copyright comments in the output. By
                                default this works like Google Closure, keeping
                                JSDoc-style comments that contain "@license" or
                                "@preserve". You can optionally pass one of the
                                following arguments to this flag:
                                - "all" to keep all comments
                                - a valid JS RegExp like `/foo/` or `/^!/` to
                                keep only matching comments.
                                Note that currently not *all* comments can be
                                kept when compression is on, because of dead
                                code removal or cascading statements into
                                sequences.
```

Are you disabling this? This is a potential legal issue for Next.js users as you are required to include the licenses somewhere.

**Comment by rashidul0405** [comment]
@timneutkens This was actually inspired by [CRA](https://github.com/facebook/create-react-app/blob/9fd98447d8afeef90efc669040b52fc65bc06484/packages/react-scripts/config/webpack.config.prod.js#L165) and, also I see that I can get rid of few KBs from production bundle.

By default, terser-webpack-plugin [removes comments except license, preserve, cc_on](https://github.com/webpack-contrib/terser-webpack-plugin/blob/abf1a4d2fe5a36108807df8326c0882bc0c7a627/src/index.js#L49).

If we need to keep the licensing kinds of stuff, then we can disregard this PR.

**Comment by rashidul0405** [comment]
@timneutkens do you really need those licensing info? Can we take inspiration from CRA?

**Comment by timneutkens** [comment]
I'm going to check this at a later point, as per my concerns I have to verify it.

**Comment by timneutkens** [comment]
I'm going to close this PR as the reduction would be minimal compared to the potential legal issues.

**Pull request closed without merging**
