### PR TITLE
Fix shallow routing with rewrites/middleware

### LINKED ISSUE #31680: Unable to disable prefetch on `Router.push()`
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

next start

### Describe the Bug

Calling `Router.push()` is triggering a prefetch request but the downstream service does not allow HEAD requests and is returning 405.

Similar to the `prefetch={false}` prop on the `<Link />` component, would it be possible to disable prefetching when using `Router.push()`?

### Expected Behavior

I can disable prefetching on `push()`

### To Reproduce

```ts
// Bring in routing functionality from next router hook
	const { push } = useRouter();

	// Create a function to handle logging out through Ory
	const handleLogOut = useCallback(async () => {
		const logoutUrl = await axios({
			url: `${API_URL}/self-service/logout/browser`,
			method: "get",
			headers: {
				"content-type": "application/json",
				accept: "application/json",
			},
			withCredentials: true,
		});

		push(logoutUrl.data.logout_url);
	}, [push]);
```

### LINKED ISSUE #37072: Using `shallow` routing and a `rewrite` middleware fails for dynamic segments (`/[dynamic]`)
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.10
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.64

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

Using a middleware that performs a path rewrite like the following

`middleware.ts`:

```ts
// eslint-disable-next-line @next/next/no-server-import-in-page
import { NextRequest, NextResponse } from 'next/server'

// RegExp for public files
const PUBLIC_FILE = /\.(.*)$/


export function middleware(req: NextRequest) {
  const url = req.nextUrl.clone()

  // Skip public files and API routes
  if (PUBLIC_FILE.test(url.pathname) || url.pathname.startsWith('/api')) {
    return
  }

  url.pathname = `/desktop${url.pathname}` // simplified here for the test case, the middleware will determine the right user agent here

  return NextResponse.rewrite(url)
}

```

Will cause an error (404) and reload the page on the `Link` component for `/` urls when used with `shallow`

Example

```tsx
const Example = () => (
<>
  <Link href="/" shallow>Home</Link> {/* this will fail to resolve and reload the page */}
  <Link href="/?query=myQuery" shallow>Home</Link> {/* this will fail to resolve and reload the page */}
  <Link href="/">Home</Link> {/* this is working */}
  <Link href="/another-page" shallow>Another page</Link> {/* this is also working */}
</>
)
```

The same error happens with `router.push`.

A different error happens also for `router.push`, when used like so:

```ts
  const onClick = useCallback(() => {
    push('/[device]', '/', { shallow: true })
  }, [push])
```
```
Error: The provided `as` value (/) is incompatible with the `href` value (/[device]). Read more: https://nextjs.org/docs/messages/incompatible-href-as
```

The error exists (as far as I can tell) since next `12.1.1`. It works correct in `12.1.0`.

### Expected Behavior

It should not fail with a `404` and reload the page but just route correctly.

### To Reproduce

I created a reproducible case here:
https://stackblitz.com/edit/nextjs-xljvem?file=pages/[device]/index.js

And here a fork with `12.1.0`:

https://stackblitz.com/edit/nextjs-5qakb4?file=_middleware.js

### PR DESCRIPTION
**Pull request by Schniz**
Shallow route changes did not work for rewritten pages when Middleware
was used, and made hard refreshes, although it was possible with static rewrites.

This happened because the router has a manifest of the static rewrites,
allowing static rewrites to map the route before comparing with the
local cache.

Middleware rewrites are dynamic and happening on the server, so we
can't send a manifest easily. This means that we need to propagate
the rewrites from the data requests into the components cache in
the router to make sure we have cache hits and don't miss.

This commit does exactly that and adds a test to verify that it works.

This fixes #37072 and fixes #31680

_Note:_ there's one thing that is somewhat an issue though: if the first
page the user lands on is a rewritten page, and will try to make a
shallow navigation to the same page--we will make a `fetch` request.
This is because we don't have any client cache of the `rewrite` we just
had.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5b9ba41a1684328e1ed3e5ee6c2b046ed2f1be72

`pnpm testheadless test/integration/amphtml/test/index.test.js` 
- AMP Usage > AMP dev mode > should detect changes to component and refresh an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect changes to component and refresh an AMP page

    TIMED OUT: /hello/

    hi

      498 |
      499 |   if (hardError) {
    > 500 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      501 |   }
      502 |   return false
      503 | }

      at Object.check (lib/next-test-utils.js:500:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:388:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]
Thanks!

**Comment by hariombalhara** [comment]
I seem to be still able to see this issue with v12.2.2. When middleware is present, shallow routing doesn't work. Anyone else seeing the same issue?
I will work on a minimal MRE.

**Comment by zackify** [comment]
yup... exact same thing here. Our app is broken when i have middleware enabled since the update and try to use shallow routing.

**Comment by eposha** [comment]
I have same issue

**Pull request merged**
