### PR TITLE
[WIP] Add passEnv config option

### PR DESCRIPTION
**Pull request by dav-is**
Adds config option:
```js
// next.config.js
module.exports = {
  passEnv: [
    'dockerHost',
    'apiEndpoint'
  ]
}
```

Will add support for reading dynamic `process.env.apiEndpoint` on both the server and the client at runtime.

Will also block build time `env` being set to something set in `passEnv`

TODO
---
- [ ] `process.env.__NEXT_ENV_PASS` only seems to be replaced when running serverless :thinking: 
- [x] serverless tests
- [ ] other tests

Note: this PR depends on https://github.com/zeit/next.js/pull/6260 so there are some diffs from that PR in this one (that will disappear once it's merged).

### CODE REVIEW

**Comment by Janpot** [comment]
How do you see the following use-cases?

I want to access `process.env.apiEndpoint` both on server and client. But on server I want it to contain `http://localhost:3000/` and on client I want it to contain `/` (or `https://example.com/`)

And by extension: take the previous use-case, but now I want to pass it through from the environment (docker), but only on the server.

Reason is that I'd like to do somethings like:
```js
await fetch(new URL('/my/path', process.env.apiEndpoint));
```
But on the server, I just want it to access localhost, or an internal endpoint. On the client I want it to access the origin it is deployed behind.

**Comment by dav-is** [comment]
@Janpot
```
await fetch(new URL('/my/path', window ? process.env.apiEndpoint : 'http://localhost:3000/'));
```
Note: using `window` might not always be the best option

`apiEndpoint` would need to be in the `passEnv` to pass it to the client.

**Comment by Janpot** [comment]
Thanks for your answer, but to be honest, I wasn't really looking for a solution. Since you seem to be working on configuration of apps, I thought I'd present a use-case which seems to be quite common, but that can't be solved by using _just_ your configuration solution. While it's definitely useful already, it seems a bit too limited to me.

I'd like the app to be as agnostic as possible of where it's running. That maximises the portability. My app doesn't need t know and act differently whether it's running on the server or in the browser (or electron, cloudflare worker, statically exported,...). I want to configure it externally, and it should just follow along.

**Comment by Janpot** [comment]
But if I understand correctly, even with serverless, there will still be two bundles generated, one for the client, one for the "server"? (In case I'm misunderstanding how it works, you can dismiss the following)
In the ideal case I'd be able to somehow "mark" certain variables from `env` as "client only", "server only" or "shared". And same with `passEnv` "pass only to client", "pass only to server", "pass to both"

**Comment by dav-is** [comment]
It's got to be passed to the server to be passed to the client. If it's server only, just use regular env variables without using `envPass`. This is for dynamic runtime values only. Use `next.config.js`'s `env` for build time (which should be most cases).

**Comment by Janpot** [comment]
> It's got to be passed to the server to be passed to the client.

It passes through server, but that doesn't mean it has to populate `process.env` there.

> Use `next.config.js`'s `env` for build time (which should be most cases).

Which is exactly what I'm proposing to make configurable for server and client separately. I mean something along the lines of:

```js
// next.config.js
module.exports = {
  env: {
    // available on server and client under process.env.var1
    var1: 'some value',
    // available on server and client as process.env.var2 but a different value on each
    var2: { server: 'some value', client: 'another value' }
  }
}
```
similarly, something could be set up for `passEnv`
```js
// next.config.js
module.exports = {
  passEnv: {
    // passed through on server and client under process.env.var1
    var1: true,
    // only passed through on the server
    var2: 'server',
    // only passed through on the client (this is a bit more tricky but should be doable)
    var3: 'client'
  }
}
```
In this last example you'd probably only use the second and third form when there's also a value provided in `env` for the other environment.

**Comment by dav-is** [comment]
@Janpot `passEnv` is only for passing env variables to the client. They're always going to be available on the server.

> doesn't mean it has to populate `process.env` there

`process.env` is populated by Nodejs

As for differing `client` and `server` values for `env`, I'll need to look into that one more.

**Comment by Janpot** [comment]
> They're always going to be available on the server.

Oh sure, makes sense. Was assuming something like DefinePlugin would take over.

**Comment by timneutkens** [comment]
Going to close this as talked about with @dav-is. Having runtime configuration in a serverless environment generally ends up in behavior you don't want. If you do really need it there are ways to do it in userland using `pages/_document` and then hydrating the value on the client side, which is equivalent to what this PR would do.

**Comment by Janpot** [comment]
Makes sense. Any love for compiling different values for the same `process.env`  variable depending on the environment (client, server)? I mean, that's exactly the original purpose of the concept of "environment variables", right?

**Pull request closed without merging**
