### PR TITLE
[Fast Refresh] Redesigned Runtime Error Experience

### PR DESCRIPTION
**Pull request by Timer**
This pull request introduces a redesigned runtime error experience for users who are opted-into the Fast Refresh experiment.

Notable changes:

- Uses `eval-source-map` instead of `cheap-module-source-map`
  - Faster recompiles in development
  - Column mappings
  - Original variable names in browser debugger
- Does not reload entire page after a runtime error (to retain application state)
  - Runtime errors are automatically cleared after a Fast Refresh successfully completes
- New overlay is clearly minimizable (modal design)
  - Old overlay looked like a compile error, was not obvious your app was still underneath

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build
- Production response size > should not increase the overall response size of modern build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    68734

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 258 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

  ● Production response size › should not increase the overall response size of modern build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    69110

      102 |     // These numbers are without gzip compression!
      103 |     const delta = responseSizesBytes - 166 * 1024
    > 104 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
          |                   ^
      105 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      106 |   })
      107 | })

      at Object.<anonymous> (integration/size-limit/test/index.test.js:104:19)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build
- Production response size > should not increase the overall response size of modern build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    68776

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 258 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

  ● Production response size › should not increase the overall response size of modern build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    69152

      102 |     // These numbers are without gzip compression!
      103 |     const delta = responseSizesBytes - 166 * 1024
    > 104 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
          |                   ^
      105 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      106 |   })
      107 | })

      at Object.<anonymous> (integration/size-limit/test/index.test.js:104:19)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/app-aspath/test/index.test.js** 
- App asPath > should not have any changes in asPath after a bundle rebuild

<details>
<summary>Expand output</summary>

  ● App asPath › should not have any changes in asPath after a bundle rebuild

    expect(received).toBe(expected) // Object.is equality

    Expected: "{ \"url\": { \"query\": {}, \"pathname\": \"/\", \"asPath\": \"/\" } }"
    Received: ""

      32 | 
      33 |     const text = await browser.elementByCss('body').text()
    > 34 |     expect(text).toBe(
         |                  ^
      35 |       '{ "url": { "query": {}, "pathname": "/", "asPath": "/" } }'
      36 |     )
      37 | 

      at Object.<anonymous> (integration/app-aspath/test/index.test.js:34:18)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/basic/test/index.test.js** 
- Basic Features > Error Recovery > should recover after exporting an invalid page
- Basic Features > Error Recovery > should recover after a bad return from the render function
- Basic Features > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● Basic Features › Error Recovery › should recover after exporting an invalid page

    TIMED OUT: /This is the about page/

    The default export is not a React Component in page: "/hmr/about5"
    Error: The default export is not a React Component in page: "/hmr/about5"

      204 |         const { isValidElementType } = require('react-is');
      205 |         if (!isValidElementType(Component)) {
    > 206 |             throw new Error(`The default export is not a React Component in page: "${pathname}"`);
          |                   ^
      207 |         }
      208 |         if (!isValidElementType(App)) {
      209 |             throw new Error(`The default export is not a React Component in page: "/_app"`);

      at Object.renderToHTML (../packages/next/dist/next-server/server/render.js:206:19)
      at DevServer.renderToHTMLWithComponents (../packages/next/dist/next-server/server/next-server.js:649:41)
      at DevServer.renderToHTML (../packages/next/dist/next-server/server/next-server.js:796:39)
      at async DevServer.renderToHTML (../packages/next/dist/server/next-dev-server.js:19:539)
      at async DevServer.render (../packages/next/dist/next-server/server/next-server.js:538:22)
      at async Object.fn (../packages/next/dist/next-server/server/next-server.js:388:17)
      at async Router.execute (../packages/next/dist/next-server/server/router.js:134:32)
      at async DevServer.run (../packages/next/dist/next-server/server/next-server.js:503:29)
      at async DevServer.handleRequest (../packages/next/dist/next-server/server/next-server.js:147:20)
      at Timeout._onTimeout (lib/next-test-utils.js:348:11)
          at runMicrotasks (<anonymous>)

  ● Basic Features › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

    Objects are not valid as a React child (found: /search/). If you meant to render a collection of children, use an array instead. in Unknown in App in Unknown in Context.Provider in Context.Provider in Context.Provider in AppContainer
    Error: Objects are not valid as a React child (found: /search/). If you meant to render a collection of children, use an array instead.
        in Unknown
        in App
        in Unknown
        in Context.Provider
        in Context.Provider
        in Context.Provider
        in AppContainer

      81 |     let head;
      82 |     try {
    > 83 |         html = renderElementToString(element);
         |                ^
      84 |     }
      85 |     finally {
      86 |         head = head_1.default.rewind() || head_1.defaultHead(amp_1.isInAmpMode(ampMode));

      at traverseAllChildrenImpl (../node_modules/react/cjs/react.development.js:1195:17)
      at traverseAllChildren (../node_modules/react/cjs/react.development.js:1226:10)
      at mapIntoWithKeyPrefixInternal (../node_modules/react/cjs/react.development.js:1308:3)
      at toArray (../node_modules/react/cjs/react.development.js:1361:3)
      at ReactDOMServerRenderer.render (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3624:28)
      at ReactDOMServerRenderer.read (../node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
      at renderToString (../node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
      at render (../packages/next/dist/next-server/server/render.js:83:16)
      at Object.renderPage (../packages/next/dist/next-server/server/render.js:416:16)
      at Function.getInitialProps (integration/basic/.next/server/static/development/pages/_document.js:238:19)
      at Object.loadGetInitialProps (../packages/next/dist/next-server/lib/utils.js:59:29)
      at Object.renderToHTML (../packages/next/dist/next-server/server/render.js:420:36)
      at async DevServer.renderToHTMLWithComponents (../packages/next/dist/next-server/server/next-server.js:649:26)
      at async DevServer.renderToHTML (../packages/next/dist/next-server/server/next-server.js:796:28)
      at async DevServer.renderToHTML (../packages/next/dist/server/next-dev-server.js:19:539)
      at async DevServer.render (../packages/next/dist/next-server/server/next-server.js:538:22)
      at Timeout._onTimeout (lib/next-test-utils.js:348:11)
          at runMicrotasks (<anonymous>)

  ● Basic Features › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

    The default export is not a React Component in page: "/hmr/about7"
    Error: The default export is not a React Component in page: "/hmr/about7"

      204 |         const { isValidElementType } = require('react-is');
      205 |         if (!isValidElementType(Component)) {
    > 206 |             throw new Error(`The default export is not a React Component in page: "${pathname}"`);
          |                   ^
      207 |         }
      208 |         if (!isValidElementType(App)) {
      209 |             throw new Error(`The default export is not a React Component in page: "/_app"`);

      at Object.renderToHTML (../packages/next/dist/next-server/server/render.js:206:19)
      at DevServer.renderToHTMLWithComponents (../packages/next/dist/next-server/server/next-server.js:649:41)
      at DevServer.renderToHTML (../packages/next/dist/next-server/server/next-server.js:796:39)
      at async DevServer.renderToHTML (../packages/next/dist/server/next-dev-server.js:19:539)
      at async DevServer.render (../packages/next/dist/next-server/server/next-server.js:538:22)
      at async Object.fn (../packages/next/dist/next-server/server/next-server.js:388:17)
      at async Router.execute (../packages/next/dist/next-server/server/router.js:134:32)
      at async DevServer.run (../packages/next/dist/next-server/server/next-server.js:503:29)
      at async DevServer.handleRequest (../packages/next/dist/next-server/server/next-server.js:147:20)
      at Timeout._onTimeout (lib/next-test-utils.js:348:11)
          at runMicrotasks (<anonymous>)

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/acceptance/ReactRefresh.test.js** 
-  > logbox: can recover from a event handler error
-  > logbox: can recover from a component error

<details>
<summary>Expand output</summary>

  ● logbox: can recover from a event handler error

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      305 |   ).toBe('1')
      306 | 
    > 307 |   expect(await session.hasRedbox()).toBe(true)
          |                                     ^
      308 |   expect(await session.getRedboxSource()).toMatchInlineSnapshot(`
      309 |     "index.js (8:16) @ eval
      310 | 

      at Object.<anonymous> (acceptance/ReactRefresh.test.js:307:37)

  ● logbox: can recover from a component error

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `logbox: can recover from a component error 1`

    - Snapshot
    + Received

    - child.js (4:14) @ Child
    -
    -   2 |   // hello
    -   3 |   export default function Child() {
    - > 4 |     throw new Error('oops')
    -     |          ^
    + ../../../../packages/react-refresh-utils/internal/helpers.js (113:0) @ eval
    +
    +   111 |     // Only trigger refresh if the webpack HMR state is idle
    +   112 |     if (canApplyUpdate()) {
    + > 113 |         return runtime_1["default"].performReactRefresh();
    +   114 |     }
    -   5 |   }
    +   115 |     return scheduleUpdate();
    -   6 |·
    +   116 | }, 30);

      393 | 
      394 |   expect(await session.hasRedbox()).toBe(true)
    > 395 |   expect(await session.getRedboxSource()).toMatchInlineSnapshot(`
          |                                           ^
      396 |     "child.js (4:14) @ Child
      397 | 
      398 |       2 |   // hello

      at Object.<anonymous> (acceptance/ReactRefresh.test.js:395:43)

</details>

**Review by timneutkens — APPROVED** [review]
Looks great 💯

**Pull request merged**
