### PR TITLE
Add 'unified' SSR compilation target

### PR DESCRIPTION
**Pull request by terribleplan**
Consider this a strawman proposal for some sort of 'unified' SSR target.

The characteristics of this target are:
1. It accepts simple arguments and returns a simple response. It does not assume node-style http interfaces to allow for more easy integration via simple adapters.
2. It exports to a single file and as such
   1. Includes all files and libraries necessary to run every page in a single bundle
   2. Includes url routing capabilities

I was originally looking to make this address all of the issues I had in #6282, but it makes more sense to let something else handle resolving the builtin problem with something like as second pass of webpack.

I would appreciate some guidance as to what needs to improve this to a point it could be merged. On my mind right now is:

- [ ] testing (what if anything, is important to test, and what tests would you like to see)
- [ ] code style (I couldn't really determine a consistent code style, but did my best to mimic it in the places I was working)
- [ ] routing (is the current implementation ok? is there some file/package I didn't find that would work better? should the router bit be pulled into some other file so it could be tested? if so should any other things use it as a base?)
- [ ] interface (not expecting req and res methods is important, but is there any other standard that would make sense to use? if no standard are there any strong opinions on a different but still generic API?)

### CODE REVIEW

**Comment by timneutkens** [comment]
Just fyi we're not planning to add another target at this point in time.

**Comment by terribleplan** [comment]
One of the big issues with the serverless target given the use case of Cloudflare Workers is that it builds a different bundle for each page, and bundling them together manually makes an output that is larger than the allowed size since you're bundling isolated dependencies for every route.

I think that the way it works now has benefits in some scenarios, and it certainly reduces the amount of code shipped to any given endpoint if your runtime works in that way. I'd welcome thoughts as to some path forward that can achieve both goals and not add an additional target.

**Comment by timneutkens** [comment]
> One of the big issues with the serverless target given the use case of Cloudflare Workers is that it builds a different bundle for each page, and bundling those together manually makes an output that is larger than the allowed size since you're bundling a 250KB+ file with isolated dependencies for each route.

It sounds like you're creating 1 server that holds all serverless functions 🤔

**Comment by terribleplan** [comment]
> It sounds like you're creating 1 server that holds all serverless functions thinking

That is (sadly) how cloudflare functions work, unless you want to pony up thousands of dollars a month for an enterprise plan. You get one function per domain, and that function has to be <= 1mb (seemingly compressed as I uploaded up to about 1.4mb without problems). That single function has to handle any routes you want to add, which can be as simple as '*'.

**Comment by timneutkens** [comment]
Sounds to me like a platform issue, not a Next.js issue. There is no way you're going to be able to fit hundreds of pages into a single function.

**Comment by terribleplan** [comment]
1. I don't disagree that the implementation of cloudflare workers is less than ideal.
2. I do have about 30 pages + styled-components + redux fitting into <600k and it seems to be running well on workers, so I do beg to differ on your second point. I don't know how widespread the use case for several hundreds of unique pages in next is, but I could see this solution scaling to at least 100+.
3. Moving on from that, and since you have already said you don't want to add another target at this point, is there some way to make targets plugable? That would let me implement this in a way better than trying to maintain a fork, but not include it as part of the core code.

**Comment by kentonv** [comment]
> Sounds to me like a platform issue, not a Next.js issue.

The issue is that Cloudflare Workers distributes code to 165+ locations, whereas other serverless platforms will typically send it to only one. Shipping hundreds of megabytes of code to one location is no big deal; sending it to 165 becomes a problem. This isn't a "platform issue" that can be fixed -- any provider which runs code in 165 locations for $5/mo will have this problem.

To that end, Workers currently enforces a limit of 1MB of code per site.

> There is no way you're going to be able to fit hundreds of pages into a single function.

Workers aren't really organized into "functions" like other serverless providers. You have an event handler which receives all HTTP traffic for your site (at least, for the route patterns that you've configured to go to the worker). In the event handler, you can implement your own routing in order to support multiple "functions".

I'm not very familiar with next.js, but it sounds like currently each "page" is shipped as a completely independent piece of code, despite having many dependencies that are common between pages. This doesn't map well to CF Workers. If somehow the common dependencies could be shared, then perhaps it would be possible to use next.js on Cloudflare and other platforms that distribute code across a wide network.

Entirely up to you if you want to support that, of course -- I just wanted to provide some context here.

**Comment by timneutkens** [comment]
I'm going to close this PR as we won't be adding another target in the short term to cover just one use case that overlaps a lot with serverless. 

Feel free to write up a RFC explaining exactly the changes you'd need and we can see if there is a good solution using the existing serverless target.

**Pull request closed without merging**
