### PR TITLE
Update dependencies in examples 

### PR DESCRIPTION
**Pull request by mayank1513**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1094eeed9382c64eb06a5b339d49e3e11728052f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1094eeed9382c64eb06a5b339d49e3e11728052f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1094eeed9382c64eb06a5b339d49e3e11728052f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 1094eeed9382c64eb06a5b339d49e3e11728052f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
This appears to be an accident. Please open specific PRs for updating examples, scoped to that example. If you are wanting to upgrade dependencies, it would be best to upgrade all the deps for that example, and validate that it's still working by including a deployed example. Thanks!

**Comment by mayank1513** [comment]
Thanks for the comment. First I created PR for individual examples but it was rejected. This, I clubbed into one PR

**Comment by mayank1513** [comment]
Going forward, I will create PRs scooped to the example as I did earlier. Hope this will work well.

**Comment by styfle** [comment]
I think the confusion is over the title (which I updated) as well as the large number of commits

**Review by styfle — APPROVED** [review]

**Pull request merged**
