### PR TITLE
eslint-config-next: allow typescript eslint v7

### LINKED ISSUE #62138: Compatibility issue with typescript eslint v7
### Link to the code that reproduces this issue

https://github.com/belgattitude/shared-dx/pull/546 - might be fixed by https://github.com/vercel/next.js/pull/62137

### To Reproduce

Clone the pr: https://github.com/belgattitude/shared-dx/pull/546 and run

```
yarn install
yarn g:lint
```

### Current vs. Expected behavior

lint should work instead the following error is displayed:

```
Oops! Something went wrong! :(

ESLint: 8.56.0

ESLint couldn't determine the plugin "import" uniquely.

- /home/sebastien/github/shared-dx/node_modules/eslint-config-next/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.cjs » eslint-config-next/core-web-vitals » /home/sebastien/github/shared-dx/node_modules/eslint-config-next/index.js")
- /home/sebastien/github/shared-dx/node_modules/eslint-plugin-import/lib/index.js (loaded in ".eslintrc.cjs » @belgattitude/eslint-config-bases/simple-import-sort")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 4.1.0
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

ESLint (eslint-config-next)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

```
 yarn why @typescript-eslint/parser
├─ @belgattitude/eslint-config-bases@workspace:packages/eslint-config-bases [4609b]
│  └─ @typescript-eslint/parser@npm:7.0.1 [f2e9b] (via npm:^7.0.1 [f2e9b])
│
├─ @belgattitude/eslint-config-bases@workspace:packages/eslint-config-bases [ad616]
│  └─ @typescript-eslint/parser@npm:7.0.1 [f2e9b] (via npm:^7.0.1 [f2e9b])
│
├─ @belgattitude/eslint-config-bases@workspace:packages/eslint-config-bases
│  └─ @typescript-eslint/parser@npm:7.0.1 [f2e9b] (via npm:^7.0.1 [f2e9b])
│
├─ eslint-config-next@npm:14.1.0
│  └─ @typescript-eslint/parser@npm:6.21.0 (via npm:^5.4.2 || ^6.0.0)
│
└─ eslint-config-next@npm:14.1.0 [ad616]
   └─ @typescript-eslint/parser@npm:6.21.0 [315f5] (via npm:^5.4.2 || ^6.0.0 [315f5])

```

### PR DESCRIPTION
**Pull request by belgattitude**
### What?

Allow [typescript-eslint v7](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7) support

### Why?

Allow compatibility with typescript eslint v7, pave the way to support eslint flat config and possibly typescript 5.4 

### How?

Add a v7 to the allowed versions in eslint-config-next dependencies and regenerate the lock with pnpm install. Be aware that some eslint peer dev deps have been updated in the process. See the lock

Tested with pnpm build && ppm lint

## Close

- Closes https://github.com/vercel/next.js/issues/62138

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8888d8ba5d1dce8ac1322fa4073353c93248cfb8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c7c217c9c93f62628a84db1d18686123212d7d1b

`pnpm test-dev test/e2e/app-dir/metadata/metadata.test.ts` (PPR)
- app dir - metadata > react cache > should have same title and page value when navigating

<details>
<summary>Expand output</summary>

  ● app dir - metadata › react cache › should have same title and page value when navigating

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.056225933070521705"
    Received: "0.8446129896808672"

      973 |         const obj = JSON.parse(title)
      974 |         // Check `cache()`
    > 975 |         expect(obj.val.toString()).toBe(value)
          |                                    ^
      976 |         // Check `fetch()`
      977 |         // TODO-APP: Investigate why fetch deduping doesn't apply but cache() does.
      978 |         if (!isNextDev) {

      at Object.toBe (e2e/app-dir/metadata/metadata.test.ts:975:36)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

`pnpm test-start test/e2e/app-dir/navigation/navigation.test.ts`
- app dir - navigation > query string > should handle unicode search params

<details>
<summary>Expand output</summary>

  ● app dir - navigation › query string › should handle unicode search params

    request.response: Target page, context or browser has been closed

      37 |         const browser = await next.browser('/search-params?name=名')
      38 |         async function requestHandler(req: Request) {
    > 39 |           const res = await req.response()
         |                                 ^
      40 |           if (!res) return
      41 |
      42 |           requests.push({

      at response (e2e/app-dir/navigation/navigation.test.ts:39:33)
      at cb (lib/browsers/playwright.ts:234:51)
      at Page.forEach (lib/browsers/playwright.ts:234:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| buildDuration | 19.8s | 20s | ⚠️ +220ms |
| buildDurationCached | 7.7s | 7.8s | ⚠️ +110ms |
| nodeModulesSize | 196 MB | 196 MB | ✓ |
| nextStartRea..uration (ms) | 424ms | 432ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.3 kB | 30.3 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| index.html gzip | 530 B | 529 B | N/A |
| link.html gzip | 542 B | 539 B | N/A |
| withRouter.html gzip | 525 B | 523 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.5 kB | 94.5 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.6 kB | 44.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.9 kB | 95.9 kB | ✓ |
| app-page-tur..prod.js gzip | 97.6 kB | 97.6 kB | ✓ |
| app-page-tur..prod.js gzip | 92 kB | 92 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.6 kB | 90.6 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.74 kB | 9.74 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.47 kB | 9.47 kB | ✓ |
| pages-turbo...prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22.1 kB | 22.1 kB | ✓ |
| server.runti..prod.js gzip | 50.1 kB | 50.1 kB | ✓ |
| Overall change | 927 kB | 927 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | belgattitude/next.js eslint-config-allow-typescript-eslint-v7 | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | N/A |
| index.pack gzip | 103 kB | 104 kB | ⚠️ +901 B |
| Overall change | 103 kB | 104 kB | ⚠️ +901 B |

</details>

</details>
Commit: c7c217c9c93f62628a84db1d18686123212d7d1b

**Comment by belgattitude** [comment]
The CI failures seems unrelated … let me know if I can help.

there’s a small size increase in next cache too

**Review by styfle — APPROVED** [review]
Thanks!

Also see related PR #52845

**Pull request merged**
