### PR TITLE
Refactor with-apollo example

### PR DESCRIPTION
**Pull request by todortotev**
Related to [11014](https://github.com/vercel/next.js/issues/11014)

The example opts out of getInitialProps and the implementation is adjusted in favor of SSG as discussed with @lfades

I'm unsure If I implemented everything exactly as requested, so please let me know if changes are required.
Maybe it can be handy if we add SSR to the example, though it's quite straight-forward what one should do.

### CODE REVIEW

**Comment by balazsorban44** [comment]
I am no authority on this, just stumbled upon, but shouldn't the README also be updated? If I understand the intent, getInitialProps is removed in this PR? but the README still talks about it.

Also, out of curiosity (and because I am using it), is this approach better/comparable to [next-with-apollo](https://github.com/lfades/next-with-apollo) by @lfades? If there are differences, could someone explain? 🙏

**Comment by lfades** [comment]
> I am no authority on this, just stumbled upon, but shouldn't the README also be updated? If I understand the intent, getInitialProps is removed in this PR? but the README still talks about it.

YES cc @TodorTotev 

> Also, out of curiosity (and because I am using it), is this approach better/comparable to next-with-apollo by @lfades? Do they solve different things? If there are differences, could someone explain? 🙏

It's better, once the changes here are added to all Apollo examples I'll update `next-with-apollo` to not mention `getInitialProps` anymore, and to recommend the examples instead 😌 

Overall you don't need an Apollo wrapper, it provided value in another time, but the current implementations are not what we want: Very fast and reliable apps

**Comment by hoangvvo** [comment]
@lfades I'm wondering if it is a good idea to remove `getInitialProps` altogether. I do use `ctx.apolloClient.query` there, and it allows me to avoid redundant request on page visit (after the first query)

I mentioned it briefly in this closed PR: https://github.com/lfades/next-with-apollo/pull/127

**Comment by lfades** [comment]
@hoangvvo The implementation for SSG with `getStaticProps` can be used for `SSR` with `getServerSideProps` too, and there you have access to the query.

Closing in favor of https://github.com/vercel/next.js/pull/13742

**Pull request closed without merging**
