### PR TITLE
Convert `custom-server-express` example to TypeScript

### PR DESCRIPTION
**Pull request by maxproske**
Converted Express example to TypeScript to match Contribution docs.

- Added `nodemon` to match the `custom-server` example, and allow live reloading of `server.ts`
- Updated README with explainer for non-standard `<Link href="/a" as="/b">` routing

## Documentation / Examples

- [X] Make sure the linting passes by running `pnpm build && pnpm lint`
- [X] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
https://github.com/vercel/next.js/pull/33128#issuecomment-1009456136

**Comment by maxproske** [comment]
> [#33128 (comment)](https://github.com/vercel/next.js/pull/33128#issuecomment-1009456136)

Good catch! I think this example should be maintained as long as it's referenced by the [Next.js custom server docs](https://nextjs.org/docs/advanced-features/custom-server).

However, if the current example doesn't match contribution guidelines, and can't be updated, should I deprecate it in favour of `custom-server`?

**Comment by maxproske** [comment]
@leerob What do you think we should do with the following JavaScript examples? 

I think they should be maintained and converted to TypeScript, however based on your comment [#33128 (comment)](https://github.com/vercel/next.js/pull/33128#issuecomment-1009456136), it sounds like custom servers aren't recommended, and therefore the examples can't be updated. If this is the case, it might make sense to deprecate them in favour of the main `custom-server` example?

- custom-server-actionhero
- custom-server-express
- custom-server-fastify
- custom-server-hapi
- custom-server-koa
- custom-server-polka

**Comment by leerob** [comment]
I think we can remove them in favor of the custom server example 👍

**Review by leerob — APPROVED** [review]
Nice change 👍

**Pull request merged**
