### PR TITLE
Convert `next-offline` example to TypeScript

### PR DESCRIPTION
**Pull request by maxproske**
Converted example to TypeScript to match Contribution docs.

- Deprecated `with-next-offline` example

## Documentation / Examples

- [X] Make sure the linting passes by running `pnpm lint`
- [X] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

**Comment by timneutkens** [comment]
@maxproske please stop opening spam PRs *immediately*. You've opened 30 PRs in less than 5 minutes.

**Comment by timneutkens** [comment]
Closed all of them because it's spam as-is. If you're going to make a change like this it should be in a single PR, it seems you've automated this but it's severely spamming notifications.

**Comment by timneutkens** [comment]
You've caused actions to be completely swamped with no way to cancel the runs... I'm assuming that wasn't the intention but please don't open further PRs at this point as otherwise we'll have to ban your account temporarily to stop the automated PRs from being opened.

**Comment by maxproske** [comment]
Very sorry @timneutkens. For what it's worth they are all legitimate, thoughtful pull requests that took 1-3 hours each, nothing automated whatsoever. I thought it would be humorous to save them up, but I'm definitely not looking to get banned from the repo.

**Comment by timneutkens** [comment]
@maxproske thanks for getting back here 🙏 Generally it's best to either open them as you finish them or create one larger pull request with the changes to individual examples as separate commits. Basically what happened now is that we got 30 notifications in quick succession with changes to examples which made it seem automated and it kicked off a CI schedule to run those 30 PRs one by one swamping the CI pool, no other PRs will get run until this is done as it's first-come first-serve currently. Given that actions has no way to reliably cancel runs (they stay in the UI as scheduled so I'm assuming it doesn't stop unfortunately) this means we won't be able to land important changes to the core codebase.

Could you open a new PR that holds all the changes as separate commits? Will make sure someone on the team reviews it 🙏
That way CI runs in one pass against all your changes 🚀

Thanks!

**Comment by balazsorban44** [comment]
@maxproske, first of all, thank you for the contributions so far, they are all appreciated :green_heart:! To make this process easier for everyone though, I recommend you reach out to me on Twitter/email to collaborate on this so we can strategize better. We can discuss the review steps beforehand so it won't create extra notifications to the other maintainers either. As suggested above, the most important step will probably be to do this in a single PR instead.

**Comment by maxproske** [comment]
Thanks @timneutkens, that is an extremely kind response for what was basically spam. Sorry again.

**Pull request closed without merging**
