### PR TITLE
Account push error while using Link w/ SB

### PR DESCRIPTION
**Pull request by NathanTrost**
Per #22302

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.8s | ⚠️ +291ms |
| nodeModulesSize | 42.5 MB | 42.5 MB | ⚠️ +167 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.38 | 2.432 | ⚠️ +0.05 |
| / avg req/sec | 1050.54 | 1028.13 | ⚠️ -22.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.584 | 1.659 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1578.05 | 1507.12 | ⚠️ -70.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ⚠️ +1 B |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -8,7 +8,7 @@ self.__BUILD_MANIFEST = {
   "/hooks": [
     "static\u002Fchunks\u002Fpages\u002Fhooks-e732be88e7750c8b99f5.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-1758aa74927b71637af8.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-1731d43987109c491632.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-b3467c130a6d01a76dae.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-1758aa7..b71637af8.js</strong></summary>

```diff
@@ -125,6 +125,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         scroll,
         locale
       ) {
+        if (false || !router) return;
         var nodeName = e.currentTarget.nodeName;
 
         if (
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -32,7 +32,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-1758aa74927b71637af8.js"
+      href="/_next/static/chunks/pages/link-1731d43987109c491632.js"
       as="script"
     />
   </head>
@@ -78,7 +78,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-1758aa74927b71637af8.js"
+      src="/_next/static/chunks/pages/link-1731d43987109c491632.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15s | -281ms |
| nodeModulesSize | 42.5 MB | 42.5 MB | ⚠️ +167 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | N/A | N/A |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| link-dc7672e..9eca.js gzip | N/A | 1.67 kB | N/A |
| Overall change | 8.66 kB | 8.66 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _error.js | 1.01 MB | 1.01 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.01 MB | 1.01 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +20 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.2 MB | 5.2 MB | ⚠️ +20 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| buildDuration | 15s | 15.3s | ⚠️ +287ms |
| nodeModulesSize | 42.5 MB | 42.5 MB | ⚠️ +167 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.292 | 2.405 | ⚠️ +0.11 |
| / avg req/sec | 1090.91 | 1039.32 | ⚠️ -51.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.613 | 1.691 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1550.26 | 1478.58 | ⚠️ -71.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| 597-d08f5fe5..d690.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-9e190..f9d6.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-7fd79cc4..99ee.js gzip | 538 B | 538 B | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-7cc9e62..ef27.js gzip | 1.66 kB | 1.66 kB | ⚠️ +4 B |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.59 kB | 8.59 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 323 B | ⚠️ +1 B |
| Overall change | 322 B | 323 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| index.html gzip | 585 B | 586 B | ⚠️ +1 B |
| link.html gzip | 592 B | 593 B | ⚠️ +1 B |
| withRouter.html gzip | 579 B | 580 B | ⚠️ +1 B |
| Overall change | 1.76 kB | 1.76 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -8,7 +8,7 @@ self.__BUILD_MANIFEST = {
   "/hooks": [
     "static\u002Fchunks\u002Fpages\u002Fhooks-5023ef2ff38488073670.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-177412b8418bdebf043e.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-dc7672e0b6a2e9859eca.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-73e91dc4f2667a6a1a66.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-177412b..bdebf043e.js</strong></summary>

```diff
@@ -111,19 +111,20 @@ _N_E = (window.webpackJsonp_N_E = window.webpackJsonp_N_E || []).push([
               _.props.onClick(e),
               e.defaultPrevented ||
                 (function(e, n, t, r, o, a, u, i) {
-                  ("A" !== e.currentTarget.nodeName ||
-                    (!(function(e) {
-                      var n = e.currentTarget.target;
-                      return (
-                        (n && "_self" !== n) ||
-                        e.metaKey ||
-                        e.ctrlKey ||
-                        e.shiftKey ||
-                        e.altKey ||
-                        (e.nativeEvent && 2 === e.nativeEvent.which)
-                      );
-                    })(e) &&
-                      (0, c.isLocalURL)(t))) &&
+                  n &&
+                    ("A" !== e.currentTarget.nodeName ||
+                      (!(function(e) {
+                        var n = e.currentTarget.target;
+                        return (
+                          (n && "_self" !== n) ||
+                          e.metaKey ||
+                          e.ctrlKey ||
+                          e.shiftKey ||
+                          e.altKey ||
+                          (e.nativeEvent && 2 === e.nativeEvent.which)
+                        );
+                      })(e) &&
+                        (0, c.isLocalURL)(t))) &&
                     (e.preventDefault(),
                     null == u && (u = r.indexOf("#") < 0),
                     n[o ? "replace" : "push"](t, r, {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "4XbjC0WJ9aE3oOgiwGM69",
+        "buildId": "oncaM4G8Oypz1Brsx6wjm",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_buildManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_ssgManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -32,7 +32,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-177412b8418bdebf043e.js"
+      href="/_next/static/chunks/pages/link-dc7672e0b6a2e9859eca.js"
       as="script"
     />
   </head>
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "4XbjC0WJ9aE3oOgiwGM69",
+        "buildId": "oncaM4G8Oypz1Brsx6wjm",
         "isFallback": false,
         "gip": true
       }
@@ -78,15 +78,15 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-177412b8418bdebf043e.js"
+      src="/_next/static/chunks/pages/link-dc7672e0b6a2e9859eca.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_buildManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_ssgManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "4XbjC0WJ9aE3oOgiwGM69",
+        "buildId": "oncaM4G8Oypz1Brsx6wjm",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_buildManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/4XbjC0WJ9aE3oOgiwGM69/_ssgManifest.js"
+      src="/_next/static/oncaM4G8Oypz1Brsx6wjm/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: db8eebe0fde65b1902b44c096b61e3aba2436570

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for this change?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| buildDuration | 18.2s | 18.2s | ⚠️ +40ms |
| buildDurationCached | 3.4s | 3.4s | -6ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +127 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.927 | 2.909 | -0.02 |
| / avg req/sec | 854.26 | 859.35 | +5.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.369 | 1.412 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1826.37 | 1770.71 | ⚠️ -55.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ⚠️ +1 B |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -13,7 +13,7 @@ self.__BUILD_MANIFEST = {
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b57fa5abc6a43d15.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b702533c8c936a81.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -129,6 +129,7 @@
         scroll,
         locale
       ) {
+        if (false || !router) return;
         var nodeName = e.currentTarget.nodeName;
         if (
           nodeName === "A" &&
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-b57fa5abc6a43d15.js"
+      src="/_next/static/chunks/pages/link-b702533c8c936a81.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| buildDuration | 19.6s | 19.4s | -205ms |
| buildDurationCached | 3.4s | 3.4s | ⚠️ +6ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +127 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.941 | 2.944 | 0 |
| / avg req/sec | 849.97 | 849.06 | ⚠️ -0.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.374 | 1.397 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1818.87 | 1789.14 | ⚠️ -29.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.89 kB | -12 B |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | -12 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | NathanTrost/next.js Link-storybook-push-error | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -13,7 +13,7 @@ self.__BUILD_MANIFEST = {
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b57fa5abc6a43d15.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b702533c8c936a81.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -129,6 +129,7 @@
         scroll,
         locale
       ) {
+        if (false || !router) return;
         var nodeName = e.currentTarget.nodeName;
         if (
           nodeName === "A" &&
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-b57fa5abc6a43d15.js"
+      src="/_next/static/chunks/pages/link-b702533c8c936a81.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
Commit: b76bc6473d70ceb546c0c5fdba596425136e4d73

**Comment by balazsorban44** [comment]
See my comment at https://github.com/vercel/next.js/issues/22302#issuecomment-1023260998

**Pull request closed without merging**
