### PR TITLE
Fix prefetch example

### PR DESCRIPTION
**Pull request by thoragio**

### CODE REVIEW

**Comment by arunoda** [comment]
Actually, this is correct since it'll prefetch as soon as the component is rendered.

**Comment by thoragio** [comment]
Hmm, OK. When I run it without the function I get a ton of errors and the app doesn't start (see error screenshot below). But when I run it with the function it all works fine.

It's running on next v2.2.0.

Here's the code that works (literally removing just the `() => ` from the prefetch line causes the error):
```
      <div className="status">
        <div onClick={() => Router.push('/about')}>
          <header>
            <span className="title-foo">Foo</span>
            {' '}
            &
            <br />
            the
            {' '}
            <span className="title-bar">Bar</span>
          </header>
        </div>
        {() => Router.prefetch('/about')}
        <img
          role="button"
          src="/static/icons/foo-play512.svg"
          alt="Play example"
          className="play-btn"
          onClick={playExample}
        />
      </div>
```

Am I missing something?

image

**Comment by oliviertassinari** [comment]
Same issue
> Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `SearchBar`.

**Comment by oliviertassinari** [comment]
I think that we are better of by moving the prefetch call to the `componentDidMount` hook to prevent putting to much pressure on the rendering

**Pull request closed without merging**
