### PR TITLE
JSON.stringify generic errors

### LINKED ISSUE #31670: Custom error object appears as [Object object]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next

### Describe the Bug

I'm using supabase with nextjs, a postgres error thrown is reported as "[object Object]" instead of the contents.

The issue originates in `next-server.js` and `next-dev-server.js` from:
```const err = (0, _isError).default(error) ? error : error ? new Error(error + '') : null;```

```
> error
{hint: 'If a new foreign key between these entities wa…the database, try reloading the schema cache.', message: 'Could not find a relationship between products and prices in the schema cache'}

> error + ''
'[object Object]'
```

### Expected Behavior

To treat print the object as is instead of converting to a string.

### To Reproduce

1. From the example `npx create-next-app -e https://github.com/vercel/nextjs-subscription-payments nextjs-subscription-payments`
2. Set the `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY` in the .env.local
3. `npm run dev`

The error is reproduced assuming the database isn't setup and causes the postgres error.

### PR DESCRIPTION
**Pull request by mozeryansky**
fixes #31670

Use `JSON.stringify` instead of creating a string from an unknown error using `error + ''`.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| buildDuration | 17.7s | 18.1s | ⚠️ +318ms |
| buildDurationCached | 3.3s | 3.3s | -1ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +196 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.946 | 2.994 | ⚠️ +0.05 |
| / avg req/sec | 848.66 | 834.9 | ⚠️ -13.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.313 | 1.396 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1903.67 | 1791.29 | ⚠️ -112.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -895,7 +895,7 @@
                       // This catches errors like throwing in the top level of a module
                       initialErr = (0, _isError).default(_ctx.t1)
                         ? _ctx.t1
-                        : new Error(_ctx.t1 + "");
+                        : new Error(JSON.stringify(_ctx.t1));
                     case 33:
                       if (false) {
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| buildDuration | 19.2s | 19.1s | -149ms |
| buildDurationCached | 3.3s | 3.4s | ⚠️ +24ms |
| nodeModulesSize | 346 MB | 346 MB | ⚠️ +196 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.774 | 2.825 | ⚠️ +0.05 |
| / avg req/sec | 901.21 | 884.91 | ⚠️ -16.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.353 | 1.306 | -0.05 |
| /error-in-render avg req/sec | 1847.57 | 1914.81 | +67.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 544 B | 545 B | ⚠️ +1 B |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -895,7 +895,7 @@
                       // This catches errors like throwing in the top level of a module
                       initialErr = (0, _isError).default(_ctx.t1)
                         ? _ctx.t1
-                        : new Error(_ctx.t1 + "");
+                        : new Error(JSON.stringify(_ctx.t1));
                     case 33:
                       if (false) {
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6d578880106ad8e2.js"
+      src="/_next/static/chunks/main-1f34bcc49b3be5da.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: a0e364cc9df579f28bbd7b1729498309cfaf396e

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for this change?

**Comment by mozeryansky** [comment]
Took a while to get the tests to work on a clean clone, but I got that going. I don't know what snapshot comparison requires slashes, but here's a screenshot of the test as expected.

Screen Shot 2021-12-02 at 6 03 05 PM
.

**Comment by mozeryansky** [comment]
@timneutkens The test said it failed on the CI but when I run it locally it passes. I've rebased to the top of canary and pushed again, but I don't see any reason the test would have failed.

They all reported timeouts on the CI run:
```
...
thrown: "Exceeded timeout of 90000 ms for a hook.
 Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
...
Test Suites: 1 failed, 1 total
Tests:       102 failed, 102 total
Snapshots:   0 total
Time:        91.992 s, estimated 92 s
Ran all test suites matching /test\\integration\\production\\test\\index.test.js/i.
```

Passes for me:
```
Test Suites: 1 passed, 1 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        81.307 s, estimated 97 s
Ran all test suites matching /test\/integration\/production\/test\/index.test.js/i.
```

**Comment by mozeryansky** [comment]
I see the latest merges into canary are also failing the same azure tests.

**Comment by mozeryansky** [comment]
@timneutkens I've rebased but I see the tests are still failing the same way as other PRs. Could you help me with the next steps for this PR?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| buildDuration | 16.9s | 16.9s | ⚠️ +12ms |
| buildDurationCached | 3.8s | 3.7s | -111ms |
| nodeModulesSize | 355 MB | 355 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.407 | 3.448 | ⚠️ +0.04 |
| / avg req/sec | 733.85 | 725.11 | ⚠️ -8.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.606 | 1.579 | -0.03 |
| /error-in-render avg req/sec | 1556.61 | 1583.03 | +26.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.1 kB | 27.1 kB | ⚠️ +6 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.9 kB | 70.9 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.74 kB | 4.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 547 B | ⚠️ +1 B |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -918,7 +918,7 @@
                       // This catches errors like throwing in the top level of a module
                       initialErr = (0, _isError).default(_ctx.t1)
                         ? _ctx.t1
-                        : new Error(_ctx.t1 + "");
+                        : new Error(JSON.stringify(_ctx.t1));
                     case 33:
                       if (false) {
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| buildDuration | 18.4s | 18.6s | ⚠️ +202ms |
| buildDurationCached | 3.8s | 3.7s | -97ms |
| nodeModulesSize | 355 MB | 355 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.386 | 3.461 | ⚠️ +0.07 |
| / avg req/sec | 738.41 | 722.33 | ⚠️ -16.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.528 | 1.571 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1636.21 | 1590.9 | ⚠️ -45.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.1 kB | 71.1 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mozeryansky/next.js michael/error | Change |
| - | - | - | - |
| index.html gzip | 532 B | 530 B | -2 B |
| link.html gzip | 546 B | 544 B | -2 B |
| withRouter.html gzip | 526 B | 525 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -918,7 +918,7 @@
                       // This catches errors like throwing in the top level of a module
                       initialErr = (0, _isError).default(_ctx.t1)
                         ? _ctx.t1
-                        : new Error(_ctx.t1 + "");
+                        : new Error(JSON.stringify(_ctx.t1));
                     case 33:
                       if (false) {
                       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-65c45d624fc47f18.js"
+      src="/_next/static/chunks/main-c192afff05800900.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 34b2ebcad99cc3912a102701470539e0e3a52136

**Review by ijjk — COMMENTED** [review]
Hi, I opened an alternative/continuation of this PR [here](https://github.com/vercel/next.js/pull/33159) which adds a shared util for this and updates all cases to use this so we can change this easier. I copied over your commits so you're marked as a co-contributor on that PR. Thanks for taking a look at this!

**Comment by mozeryansky** [comment]
> Hi, I opened an alternative/continuation of this PR [here](https://github.com/vercel/next.js/pull/33159)

Thanks! I had originally done a helper function in the exact same spot, but I reverted to changing each line when I was trying to figure out how the tests worked. Should I close this PR?

**Comment by ijjk** [comment]
I see, yeah we can close this one and continue in the other PR

**Pull request closed without merging**
