### PR TITLE
fix(create-next-app): validate --import-alias value

### LINKED ISSUE #63854: Invalid import alias being used in CLI (create-next-app)
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/naughty-sinoussi-2cz5ks

### To Reproduce

- Use the `create-next-app` passing the flag `--import-alias` with a invalid path. Example: `pnpx create-next-app --import-alias invalid-path`
- Use the `create-next-app` with a invalid path. Example: `pnpx create-next-app` and defining a custom import alias as "pre>fix/*"

### Current vs. Expected behavior

Following the steps in the previous section, I expected the CLI to validate the import alias, but instead I observed that the CLI did not check the import alias when using the --import-alias flag and did not check for invalid characters when entering a custom path in the interactive mode

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.20.0
  npm: N/A
  Yarn: N/A
  pnpm: 7.25.0
Relevant Packages:
  next: 14.1.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fellipeutaka**
Fixes #63854

Previously, there was no check when a path was passed with the --import-alias flag. Furthermore, the regex used before did not check for possible invalid paths.

The current regex checks the following conditions:
- It must follow the pattern `<prefix>/*`
- The prefix cannot contain invalid characters for folders, such as: (whitespaces, /, <, >, :, ", /, \, |, ? and *)

### CODE REVIEW

**Comment by devjiwonchoi** [comment]
Technically, we can allow most characters except for folders and JSON rules.

For prefix:
- path separators
- asterisk
- double quotes (JSON)

**Comment by fellipeutaka** [comment]
> Technically, we can allow most characters from the current PR. I propose checking for asterisks `*` and double quotes `"` only.
> 
> It is because:
> 
> * asterisks: Pattern for paths can have at most one '*' character.
> * double quotes: breaks JSON format

What about now? I updated the regex to check asterisks, double quotes and whitespace.
https://regexr.com/7u6ih

**Comment by devjiwonchoi** [comment]
Thank you for taking my proposal. IMHO, white spaces can be allowed, too!

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +115ms |
| buildDurationCached | 8.4s | 6.1s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ✓ |
| nextStartRea..uration (ms) | 399ms | 396ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 243 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.3 kB | 95.3 kB | N/A |
| page.js gzip | 3.04 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51 kB | 51 kB | ✓ |
| Overall change | 945 kB | 945 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | fellipeutaka/next.js fix/create-next-app-import-alias | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | ⚠️ +266 B |
| index.pack gzip | 106 kB | 106 kB | N/A |
| Overall change | 1.58 MB | 1.58 MB | ⚠️ +266 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 7d9d741a4cc22639ccc411e7289c36846b8fdc8e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7d9d741a4cc22639ccc411e7289c36846b8fdc8e

`TURBOPACK=1 pnpm test-start test/e2e/prerender.test.ts` (turbopack)
- Prerender > should on-demand revalidate for fallback: blocking with onlyGenerated if generated

<details>
<summary>Expand output</summary>

  ● Prerender › should on-demand revalidate for fallback: blocking with onlyGenerated if generated

    expect(received).toMatch(expected)

    Expected pattern: /(HIT|STALE)/
    Received string:  "MISS"

      2294 |
      2295 |         expect(initialTime).toBe($2('#time').text())
    > 2296 |         expect(res2.headers.get('x-nextjs-cache')).toMatch(/(HIT|STALE)/)
           |                                                    ^
      2297 |
      2298 |         const res3 = await fetchViaHTTP(
      2299 |           next.url,

      at Object.toMatch (e2e/prerender.test.ts:2296:52)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Pull request merged**
