### PR TITLE
docs: fix 'WebVitals' cannot be used as a JSX component.   Its type …

### PR DESCRIPTION
**Pull request by aj-2000**
…'() => void' is not a valid JSX element type.

### CODE REVIEW

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: bb78e505033a264cdae6c5f0983c09562fd4faec

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — CHANGES_REQUESTED** [review]
If you can also add a Typescript example to this, that will be great!

**Comment by aj-2000** [comment]
Thanks for the quick reply. made the required changes.

**Review by samcx — CHANGES_REQUESTED** [review]
@aj-2000 I think the `## Build Your Own` section is missing TypeScript examples as well! <picture data-single-emoji=":ty:" title=":ty:">:ty:</picture>

**Pull request closed without merging**
