### PR TITLE
fix: preconnect to asset-prefix

### PR DESCRIPTION
**Pull request by Netail**
preconnect to assetPrefix, even when preloadedFontFiles is not defined

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2bb0fc21c1c4f4657a107f6460e57b04be5e95b8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — COMMENTED** [review]
Hi, could we add a test case for this?

**Comment by Netail** [comment]
> Hi, could we add a test case for this?

Hi, I honestly have no idea how to write tests for this part. react-dom handles the preconnect, nothing gets added to the dom and preconnects are not shown in DevTools :(

**Comment by Netail** [comment]
It does seem to reduce fetching by a few ms

**Pull request closed without merging**
