### PR TITLE
Improve error message on `next/future/image` when `objectFit` or `objectPosition`

### PR DESCRIPTION
**Pull request by styfle**
Improve PR improves the error message on `next/future/image` when `objectFit` or `objectPosition` is provided and suggests using `style` instead. It also prints the stack trace so its clear where the error came from.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2b75dccd028a89d5a1cf45c92024aafe3db17b5a

`pnpm testheadless test/integration/image-future/base-path/test/index.test.js` 
- Image Component basePath Tests > dev mode > should update the image on src change

<details>
<summary>Expand output</summary>

  ● Image Component basePath Tests › dev mode › should update the image on src change

    TIMED OUT: /test\.png/

    null

      499 |
      500 |   if (hardError) {
    > 501 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      502 |   }
      503 |   return false
      504 | }

      at check (lib/next-test-utils.js:501:11)
      at Object.<anonymous> (integration/image-future/base-path/test/index.test.js:97:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — DISMISSED** [review]
Looks good besides conflicts, is there more tweaking wanted here?

**Comment by styfle** [comment]
I was considering rewriting all of the errors to work this way, perhaps storing with `const [errors, setErrors] = useState([])` and deferring the error logs until mount. Although we probably only want the delayed error in `next dev` since `next build` should error immediately.

I can do that in a follow up PR though 🙂

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cb98497cd89e95e71bded0837ada0a9a59bb9fb0

`pnpm testheadless test/e2e/app-dir/index.test.ts` 
- app dir > without assetPrefix > <Link /> > should respect rewrites

<details>
<summary>Expand output</summary>

  ● app dir › without assetPrefix › <Link /> › should respect rewrites

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#from-dashboard"
    ============================================================

      322 |     return this.chain(() => {
      323 |       return page
    > 324 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      325 |         .then(async (el) => {
      326 |           // it seems selenium waits longer and tests rely on this behavior
      327 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:324:10

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Pull request merged**
