### PR TITLE
[WIP] Introduce an alternative manifest builder

### PR DESCRIPTION
**Pull request by Timer**
This manifest builder uses `chunkGroups` to reduce the amount of data we add to the bundle. It also chooses the smallest number of `chunks` required to satisfy a request, though we should probably make it operate on size instead. 🤔 

I'm going to 🛌, I'm handing this off ➡️ @timneutkens. 

We need to verify this works and potentially crawl `_parents` of the `chunkGroup` until we hit an `isInitial()`.

### CODE REVIEW

**Comment by timneutkens** [comment]
Wouldn't this work fine 🤔 

```
chunks.forEach((chunk) => {
            // If chunk is not an entry point skip them
            if (chunk.hasEntryModule()) {
              const dynamicChunks = chunk.getAllAsyncChunks()
              if (dynamicChunks.size !== 0) {
                for (const dynamicChunk of dynamicChunks) {
                  for (const module of dynamicChunk.modulesIterable) {
                    GraphHelpers.connectChunkAndModule(chunk, module)
                  }
                }
              }
            }
          })
```

**Review by timneutkens — CHANGES_REQUESTED** [review]
Probably should merge #6622 instead 🙏 Only thing missing in that one is the sorting.

**Review by timneutkens — APPROVED** [review]
Let's take this in if it works well, I don't want to hold off on shipping it, considering all tests pass 👍

**Comment by Timer** [comment]
I don't think this is operating quite as expected. Please do not merge yet.

**Pull request closed without merging**
