### PR TITLE
New error log when developing with pnpm dev

### PR DESCRIPTION
**Pull request by sahils0**
While following the [developing ](https://github.com/vercel/next.js/blob/canary/contributing/core/developing.md)guideline I ran the pnpm dev and new errors got generated in errors.js file in package/next

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 9fa9b3d19e7244ba396cff7259c7dc35ff88655b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| buildDuration | 19.4s | 18.5s | N/A |
| buildDurationCached | 14.7s | 12.6s | N/A |
| nodeModulesSize | 410 MB | 410 MB | N/A |
| nextStartRea..uration (ms) | 470ms | 478ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 50.9 kB | 50.8 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 539 B | 537 B | N/A |
| withRouter.html gzip | 519 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 204 kB | 203 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 672 B | 667 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| 523-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 523.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 323 kB | 323 kB | N/A |
| app-page-exp..prod.js gzip | 127 kB | 127 kB | N/A |
| app-page-tur..prod.js gzip | 140 kB | 140 kB | N/A |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | N/A |
| app-page.run...dev.js gzip | 314 kB | 313 kB | N/A |
| app-page.run..prod.js gzip | 123 kB | 123 kB | N/A |
| app-route-ex...dev.js gzip | 37.4 kB | 37.3 kB | N/A |
| app-route-ex..prod.js gzip | 25.5 kB | 25.3 kB | N/A |
| app-route-tu..prod.js gzip | 25.5 kB | 25.4 kB | N/A |
| app-route-tu..prod.js gzip | 25.3 kB | 25.2 kB | N/A |
| app-route.ru...dev.js gzip | 39 kB | 38.9 kB | N/A |
| app-route.ru..prod.js gzip | 25.3 kB | 25.2 kB | N/A |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.67 kB | N/A |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | N/A |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.67 kB | N/A |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | N/A |
| pages.runtim...dev.js gzip | 27.4 kB | 27.4 kB | N/A |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | N/A |
| server.runti..prod.js gzip | 916 kB | 916 kB | N/A |
| Overall change | 636 B | 636 B | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Sahil4883/next.js new-errors.json | Change |
| - | - | - | - |
| 0.pack gzip | 2.06 MB | 2.05 MB | N/A |
| index.pack gzip | 71.8 kB | 72.5 kB | ⚠️ +624 B |
| Overall change | 71.8 kB | 72.5 kB | ⚠️ +624 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>1187-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-api.ru..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 9fa9b3d19e7244ba396cff7259c7dc35ff88655b

**Comment by Sahil4883** [comment]
@eps1lon Yes I'm still getting the error when I'm running pnpm dev in the terminal

**Comment by eps1lon** [comment]
Could you rebase this branch to resolve merge conflicts to confirm with CI this is indeed an issue?

**Comment by Sahil4883** [comment]
@eps1lon will it be ok if I make a commit with a new branch as I'm finding it difficult to rebase?

**Comment by gaojude** [comment]
> @eps1lon Yes I'm still getting the error when I'm running pnpm dev in the terminal

What OS are you using?

**Comment by Sahil4883** [comment]
Windows 10

**Comment by gaojude** [comment]
> Windows 10

@Sahil4883 
See https://github.com/vercel/next.js/pull/73981

**Comment by gaojude** [comment]
> > Windows 10
> 
> 
> 
> @Sahil4883 
> 
> See https://github.com/vercel/next.js/pull/73981

Merged

**Comment by Sahil4883** [comment]
> > > Windows 10
> > 
> > 
> > @Sahil4883
> > See #73981
> 
> Merged

Now there's no error when I run pnpm dev... Thanks

**Pull request closed without merging**
