### PR TITLE
docs(next.config.js Options): Remove experimental mdxRs feature from pageExtensions

### PR DESCRIPTION
**Pull request by onahmed**
### What?
Removed experimental  [mdxRs](https://nextjs.org/docs/app/api-reference/next-config-js/mdxRs) from [pageExtensions](https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions)

### Why?
The pageExtensions setting demonstrates how to allow other extensions like .md and .mdx. The inclusion of the experimental Rust MDX compiler is unnecessary and can lead to confusion.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: cacd9414b2cec86a9845bd26b5d1f7f6fbe1d363

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: cacd9414b2cec86a9845bd26b5d1f7f6fbe1d363

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@alpedia0 Not sure why we would want to remove this—it is laid out correctly in our <picture data-single-emoji=":docs:" title=":docs:">:docs:</picture> → https://nextjs.org/docs/app/building-your-application/configuring/mdx#using-the-rust-based-mdx-compiler-experimental.

I will add more clarification instead!

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
