### PR TITLE
Update next/script docs to clear up confusion around next/head and client-side JS

### LINKED ISSUE #26158: next/script causing runtime error TypeError: Cannot read property 'tagName' of null
### What version of Next.js are you using?

11

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome Version 91.0.4472.77

### What operating system are you using?

macOS Version 11.3

### How are you deploying your application?

next start

### Describe the Bug

Using the new next/script introduced in next 11  instead of <script /> tag causing Uncaught (in promise) TypeError: Cannot read property 'tagName' of null

### Expected Behavior

Should load the script successfully without runtime error

### To Reproduce

```javascript
import Head from "next/head";
import Script from 'next/script';
const Meta = ({
    title,
    keywords,
    description
}) => {
    return (
        <Head>
            <Script src="/example.min.js" strategy="beforeInteractive" /> // <-- causing Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
       </Head>
  )
}

export default Meta;
```
Screenshot 2021-06-16 at 11 26 20 AM

### LINKED ISSUE #26187: next/script not loading anything at all
### What version of Next.js are you using?

11

### What version of Node.js are you using?

15

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

next dev, next build, serverless

### Describe the Bug

Using the new `next/script` tag inside `document.tsx`

```tsx
<Script
  id="gmaps-script"
  src="https://maps.googleapis.com/maps/api/js?libraries=places&key=[KEY]&map_ids=[MAP_ID]"
  strategy="afterInteractive"
/>
```
          
The script is not being loaded

### Expected Behavior

The script should load google maps

### To Reproduce

Create a new project via `create-nextjs-app` and add the snippet above.

### PR DESCRIPTION
**Pull request by timneutkens**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

Fixes #26187
Fixes #26158

- [x] Make sure the linting passes

### CODE REVIEW

**Review by AndreAffonso — APPROVED** [review]

**Review by RajanPalaniya — APPROVED** [review]

**Comment by Vadorequest** [comment]
The doc has changed and I understand better the issue now, but the eslint rule might need to be reviewed, too.

**Comment by timneutkens** [comment]
> The doc has changed and I understand better the issue now, but the eslint rule might need to be reviewed, too.

Can you share what part exactly?

**Comment by Vadorequest** [comment]
@timneutkens If you add a `script` tag within a NextJS `Head` element, it'll warn.

image

Considering the documentation update, this behavior is likely to push devs to use `Script` there instead, although it shouldn't be used there.

**Comment by timneutkens** [comment]
In the case that you're showing you should use `<Script>` with the right strategy 🤔

**Comment by Vadorequest** [comment]
If I do that, I ran into the `Cannot read property 'tagName' of null` error. 

`NextHead` is `next/head` component, maybe that wasn't clear.

**Comment by timneutkens** [comment]
The docs linked show to not wrap `next/head` right 🤔

**Comment by Vadorequest** [comment]
Yes, the doc say not to use `Script` component when wrapping with `next/head`. I'm wrapping with `next/head`, so I shouldn't use the `Script` component, but ESLint will complain if I don't.

**Comment by timneutkens** [comment]
This docs update means don't put it inside of `next/head`, not "if you're using <script> in next/head". In all cases `next/script` is recommended.

**Pull request merged**
