### PR TITLE
docs: add better examples to `next/image` docs.

### PR DESCRIPTION
**Pull request by leerob**
Dependent on merging images. Making it easy to copy/paste.

### CODE REVIEW

**Comment by stefanprobst** [comment]
could you also add an example for fixed-size images? thanks

**Comment by leerob** [comment]
What do you mean by that, exactly?

**Comment by leerob** [comment]
Found myself needing this today, so really happy we'll have these copy/pastable examples 😄 

CleanShot 2023-06-18 at 23 41 24@2x

```jsx
<div className="columns-3 gap-4 my-8">
  <div className="relative h-40 mb-4">
    <Image
      alt="..."
      src={myImage}
      fill
      sizes="33vw"
      className="rounded-lg object-cover"
    />
  </div>
</div>
```

**Comment by stefanprobst** [comment]
> What do you mean by that, exactly?

adding an additional example for images which should always be displayed at a specific width and height, irrespective of viewport size, but taking device pixel ratio into account - basically how to do "layout: fixed" from the legacy image component with the new image component.

**Comment by leerob** [comment]
@stefanprobst can you explain the layout you're trying to build with that image? Trying to understand when you would never want the image to be responsive. Is it a background image of sorts?

**Comment by leerob** [comment]
@stefanprobst going to go ahead and merge this, but we can always add more 😄

**Comment by leerob** [comment]
You would probably still want those images to be responsive when going down to mobile though, right? 

I believe you'd use `sizes` here: https://nextjs.org/docs/app/api-reference/components/image#sizes

**Pull request merged**
