### PR TITLE
Updated the example of with-styled-jsx-plugins to utilize the App Router

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-styled-jsx-plugins example for using the App Router.
Here are the changes that have been made:

- I renamed the "pages" folder and moved it to the "app" folder.
- Added the layout.TSX file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 643ff4c4c985dcfcc357adf4351800ed0d243f30

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@PapatMayuri 

For the future, please double check these examples are working when testing (test `next dev`, `next build`, and deploying).

Let's go ahead and remove these Babel `style-jsx-...` examples. It's getting an error, and it's likely not worth the effort to fix/keep around as an example.

**Comment by PapatMayuri** [comment]
Okay Sure @samcx will update

**Review by vignesh1507 — COMMENTED** [review]
LGTM...i agree with the changes.

**Comment by samcx** [comment]
@PapatMayuri Let me know if you're able to update this!

**Comment by PapatMayuri** [comment]
@samcx  PR is Updated please check.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
