### PR TITLE
refactor: change component to null

### PR DESCRIPTION
**Pull request by taro-shono**
## Overview

I don't wanna this in every components.

```js
dynamic(() => import('/path/to/component'), {
  loading: () => null,
});
```

### CODE REVIEW

**Comment by c0b41** [comment]
@hanagejet yeah default null might be good

**Comment by timneutkens** [comment]
I've wanted to do this for a while, however it's a breaking change

**Comment by hanagejet** [comment]
@timneutkens So should I close this PR??

**Comment by timneutkens** [comment]
No let's just discuss this first

**Comment by hanagejet** [comment]
> however it's a breaking change

**Comment by hanagejet** [comment]
What do we discuss??

I know about breaking change. I think when module will be breaking change, notice by version or RELEASE notes.

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
Thanks for the PR!

**Pull request merged**
