### PR TITLE
Adding experimental config for public file server example.

### PR DESCRIPTION
**Pull request by TimPerry**
Hi,

This might be more of a question and then you can just close this but as far as I can tell you need to add the experimental flag for the public folder to work. If not, feel free to close.

Cheers!

### CODE REVIEW

**Comment by Timer** [comment]
Sorry, but we don't take pull requests against `master`. This example has been removed from the `canary` branch!

**Comment by TimPerry** [comment]
Ah ok, no worries. So that example is wrong then?

**Comment by Timer** [comment]
The example was correct but the feature is experimental, so it's not ready for general consumption.

If you're OK with the experimental feature, you can turn it on!

**Comment by TimPerry** [comment]
Fair enough, thanks!

**Comment by Timer** [comment]
I updated the `master` branch to 9.0.3 which dropped this example 👍

**Pull request closed without merging**
