### PR TITLE
Update typescript.md

### PR DESCRIPTION
**Pull request by cybershang**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
IMHO, the changes do not change anything at all. Would you mind explaining what have you changed and why it is needed?

**Review by timneutkens — CHANGES_REQUESTED** [review]
These changes seem stylistic and not needed 🤔

**Comment by balazsorban44** [comment]
This contradicts our Prettier rules, so the changes aren't needed.

See: https://github.com/vercel/next.js/blob/canary/.prettierrc.json

**Comment by shangcode** [comment]
> IMHO, the changes do not change anything at all. Would you mind explaining what have you changed and why it is needed?

Thank you for your reply.
The code in the doc will bring up a [warning,](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-anonymous-default-export.md) so I feel it may be an update of grammar or what😅.
If not, don't mind.

**Comment by shangcode** [comment]
> IMHO, the changes do not change anything at all. Would you mind explaining what have you changed and why it is needed?

Thank you for your reply.
The code in the doc will bring up a [warning,](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-anonymous-default-export.md) so I feel it may be an update of grammar or what😅.
If not, don't mind.

**Comment by shangcode** [comment]
> These changes seem stylistic and not needed 🤔

Thank you for your reply.
According to this [warning](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-anonymous-default-export.md) I thought it is sort of best practice or what😅.

**Comment by shangcode** [comment]
> This contradicts our Prettier rules, so the changes aren't needed.
> 
> See: https://github.com/vercel/next.js/blob/canary/.prettierrc.json
Thanks!

**Pull request closed without merging**
