### PR TITLE
docs: 📝 Propose a work around for Router Cache opting out

### PR DESCRIPTION
**Pull request by HelpMe-Pls**
My attempt to contribute to [this specific section](https://nextjs.org/docs/app/building-your-application/caching#opting-out-3
) of the docs.

### CODE REVIEW

**Comment by joulev** [comment]
No I don't think this workaround is a good idea. If you make your `page.tsx` a client component, firstly the [metadata API](https://nextjs.org/docs/app/api-reference/functions/generate-metadata) is gone. Secondly you cannot import any server components to this page file anymore if you need to, because all components imported to a client component are rendered as client components.

**Comment by leerob** [comment]
Thank you for the suggestion, but we are going to move forward here without this 🙏 

We're working hard to make the caching documentation as helpful as possible and continuing to listen to feedback.

**Comment by HelpMe-Pls** [comment]
@joulev Ah, for my specific case, the `page.tsx` as a CC is acceptable for the project. But you're right, I should've mentioned the pitfalls of turning a SC into a CC. 

Oh and btw, weren't you the guy with this profile pic on the Discord server ?
image

I'm not trying to be offensive here, but if it's you, thanks for your insight. You helped me a lot on Discord 😃

**Comment by joulev** [comment]
@HelpMe-Pls Ah no, I'm not that guy, he is Alfon. I'll pass your thank to him.

**Pull request closed without merging**
