### PR TITLE
[with-apollo] Use getDataFromTree in browser

### PR DESCRIPTION
**Pull request by jonespen**
Just want to throw this out there to get some feedback. I have tried a lot of different workarounds to the problem with loading data from Apollo in `getInitialProps` for the client, but this seems to be easiest solution.

The apollo examples is using `getDataFromTree` only for the initial server request, then all requests is handled by the client outside of `getInitialProps`. When using apollo for fetching all data, this causes a lot of loading states, and you can't use something like nprogress to show loading progress when navigating client side. To me, this is not an optimal user experience, as it results in the ui being rendered first, then a loading indicator for the content is rendered, then finally the content is rendered.

Fortunatly, with apollo-client 2, [`getDataFromTree` is now available for the browser](https://github.com/apollographql/react-apollo/issues/631)! This means that we can load all the data from the tree also on the client, and wait for the data to load before rendering anything. 

Any obvious things I could have missed? /cc @ads1018? (Pinging you since you created https://github.com/ads1018/next-apollo)

### CODE REVIEW

**Comment by Shalzz** [comment]
Hi!

This works pretty well for me as well and I think should be merged after a rebase.
One thing I think of is suppling the client as a context to getDataFromTree instead of wrapping in ApolloProvider.

**Comment by ads1018** [comment]
Awesome stuff!  Thanks! Nothing immediately jumps out at me that you might have missed. 👍

**Comment by jonespen** [comment]
@Shalzz Yea, I screwed up by making PR from `master` instead of  `canary` 😳 

But I can try do a rebase, if my git fu is big enough ;)

**Review by timneutkens — APPROVED** [review]
This is awesome 🙏

**Comment by skywinston** [comment]
@jonespen Great news about being able to use `getDataFromTree` on the client side.  Are you aware of any examples showing how this works?  Is the resolved promise meant to return JSX in `render`?

**Comment by benzen9113** [comment]
I should have known this earlier. 👍

**Comment by chhuang** [comment]
Is there a reason why this change got reversed in the current `with-apollo` example?

**Pull request merged**
