### PR TITLE
Update docs for `next/future/image` migration guide

### PR DESCRIPTION
**Pull request by styfle**
Follow up to #39270 to make the props collapse to newlines

### CODE REVIEW

**Comment by leerob** [comment]
I'm not sure this would be the issue of how they're displayed on mobile, though. Should we try removing the table instead?

**Comment by styfle** [comment]
@leerob Do you like sections from the original #39270 commit better? 

[See Rendered Markdown →](https://github.com/vercel/next.js/blob/84f885a1122a19b7ada3e0e5d9ec4530ceb3ed08/docs/api-reference/next/future/image.md)

**Comment by leerob** [comment]
I would suggest doing it like this:

### Responsive

```js
// next/image before: <ImageLegacy src={src} layout="responsive" />
// next/image/future after: Use `sizes` and a few styles
<ImageFuture
  src={src}
  sizes="100vw"
  style={{ width: '100%', height: 'auto' }}
/>
```

**Comment by styfle** [comment]
@leerob are you suggesting using comments so the legacy code isn’t highlighted?

**Comment by leerob** [comment]
Correct - my thought is you're going here because you want to copy-paste the new version, so the code comment gives you the only one to reference.

**Comment by styfle** [comment]
Closing in favor of #39421

**Pull request closed without merging**
