### PR TITLE
Add yarn 2 Setup Files to Valid Files for create-next-app

### PR DESCRIPTION
**Pull request by sicarius97**
## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [x] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

When first bootstrapping a next app with yarn 2, a yarn 2 user has to run `yarn set version berry` which creates a `.yarn` directory and the files `.yarnrc.yml package.json`. When running yarn dlx create-next-app, bootstrapping the app will fail due to those initial files and directories being present, even though I don't think they will interfere with any subsequent process. Adding those three files to the validFiles array in this PR, however, did allow me to bootstrap a next app like normal locally. 

Lint tests passed and I can look further into adding testing if necessary.

- [x ] Make sure the linting passes by running `yarn lint`

Fixes #30198

### CODE REVIEW

**Comment by sicarius97** [comment]
@ijjk @timneutkens Has this been reviewed at all yet? I'd be happy to make any necessary improvements. `yarn dlx create-next-app .` is still confirmed broken, I believe this will fix it

**Review by timneutkens — DISMISSED** [review]
Hey! Thanks for this PR. This is missing an integration test for yarn 2 to verify it works, can you add that 🙏

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5a8575716fb257b67e1b3d148bcc14fa6fffb3c9

**test/integration/create-next-app/index.test.js** 
- create next app > non-empty directory

<details>
<summary>Expand output</summary>

  ● create next app › non-empty directory

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      38 |   // TODO: investigate why this test stalls on yarn install when
      39 |   // stdin is piped instead of inherited on windows
    > 40 |   if (process.platform !== 'win32') {
         |                                  ^
      41 |     it('empty directory', async () => {
      42 |       await usingTempDir(async (cwd) => {
      43 |         const projectName = 'empty-directory'

      at integration/create-next-app/index.test.js:40:34
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:29:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| buildDuration | 18.1s | 18.1s | ⚠️ +53ms |
| buildDurationCached | 3.4s | 3.4s | ⚠️ +77ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.975 | 2.986 | ⚠️ +0.01 |
| / avg req/sec | 840.27 | 837.32 | ⚠️ -2.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.341 | 1.371 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1863.91 | 1823.24 | ⚠️ -40.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 30.2 kB | 30.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 74 kB | 74 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| buildDuration | 19.4s | 19.6s | ⚠️ +241ms |
| buildDurationCached | 3.4s | 3.3s | -136ms |
| nodeModulesSize | 350 MB | 350 MB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.882 | 2.908 | ⚠️ +0.03 |
| / avg req/sec | 867.35 | 859.71 | ⚠️ -7.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.361 | 1.351 | -0.01 |
| /error-in-render avg req/sec | 1836.71 | 1850.33 | +13.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 30.3 kB | 30.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 74.3 kB | 74.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 906 B | 906 B | ✓ |
| image-HASH.js gzip | 4.75 kB | 4.75 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sicarius97/next.js fix/using-yarn-dlx | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 5a8575716fb257b67e1b3d148bcc14fa6fffb3c9

**Comment by sicarius97** [comment]
@ijjk The test that you mentioned in your comment does also fail locally for myself, but the test itself seems to display abnormal behavior. It stalls after about 120 seconds on my local machine (running windows) so I am not sure the if logic above it is actually doing anything. (not sure if tests actually can be run conditionally)

The weird thing is that I logged `res.stdout` to console on the process that the `expect(res.exitCode).toBe(0)` is making an assertion against and the stdout displayed the info I would normally expect next to display upon successful setup, not sure what is going on there

**Review by ijjk — APPROVED** [review]

**Pull request merged**
