### PR TITLE
examples with-zustand update to app dir #52858

### LINKED ISSUE #52858: please add app directory for with-zustand example
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
**
```

### Which example does this report relate to?

with-zustand

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

there is no example of Zustand with new next app directory. Can I use Zustand with the new app directory model?

### Expected Behavior

Using zustand with app directory

### To Reproduce

**

### PR DESCRIPTION
**Pull request by mkcy3**
### What?

Updates examples/with-zustand to use the new app directory. 

Fixes #52858

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2d0982a7cae735c64dd50ff2d2daecc896617365

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2d0982a7cae735c64dd50ff2d2daecc896617365

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2d0982a7cae735c64dd50ff2d2daecc896617365

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2d0982a7cae735c64dd50ff2d2daecc896617365

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2d0982a7cae735c64dd50ff2d2daecc896617365

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by leerob — APPROVED** [review]

**Pull request merged**
