### PR TITLE
chore(test): switch a few tests from yarn to pnpm

### PR DESCRIPTION
**Pull request by styfle**
Since yarn@1 is no longer maintained, we shouldn't use it for tests that are not designed specifically for yarn@1

Closes NEXT-2397

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | N/A |
| buildDurationCached | 7s | 5.5s | N/A |
| nodeModulesSize | 318 MB | 318 MB | ✓ |
| nextStartRea..uration (ms) | 437ms | 436ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.7 kB | 29.7 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 237 B | 240 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 501 B | N/A |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.22 kB | 4.21 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.62 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 106 B | 106 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 1.05 kB | 1.05 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 149 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 622 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 47.4 kB | 47.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 1.94 kB | 1.94 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js switch-some-tests-from-yarn-to-npm | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.1 kB | 95.1 kB | ✓ |
| app-page-tur..prod.js gzip | 96.9 kB | 96.9 kB | ✓ |
| app-page-tur..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-page.run...dev.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run..prod.js gzip | 90 kB | 90 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 922 kB | 922 kB | ✓ |

</details>

</details>
Commit: 5045d908c1c033fd68e39793de542ce9938583f1

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 81e12ebab6e33ce360e2d9c402453b4cab3d09ba

`pnpm test-start test/production/jest/remove-react-properties/remove-react-properties-jest.test.ts`
- next/jest > data-testid should be removed in production

<details>
<summary>Expand output</summary>

  ● next/jest › data-testid should be removed in production

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       9 |   let next: NextInstance
      10 |
    > 11 |   beforeAll(async () => {
         |   ^
      12 |     next = await createNext({
      13 |       files: {
      14 |         pages: new FileRef(path.join(appDir, 'pages')),

      at beforeAll (production/jest/remove-react-properties/remove-react-properties-jest.test.ts:11:3)
      at Object.describe (production/jest/remove-react-properties/remove-react-properties-jest.test.ts:8:1)


  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'destroy')

      50 |     })
      51 |   })
    > 52 |   afterAll(() => next.destroy())
         |                       ^
      53 |
      54 |   it('data-testid should be removed in production', async () => {
      55 |     const html = await renderViaHTTP(next.url, '/')

      at Object.destroy (production/jest/remove-react-properties/remove-react-properties-jest.test.ts:52:23)

  ● Test suite failed to run

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      115 |
      116 | if (typeof afterAll === 'function') {
    > 117 |   afterAll(async () => {
          |   ^
      118 |     if (nextInstance) {
      119 |       await nextInstance.destroy()
      120 |       throw new Error(

      at Object.afterAll (lib/e2e-utils.ts:117:3)
      at Object.<anonymous> (production/jest/remove-react-properties/remove-react-properties-jest.test.ts:5:19)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — COMMENTED** [review]
I think these all could use `pnpm` and just had not been migrated yet

**Comment by huozhi** [comment]
If we change to `pnpm`, need to change the copy folder command from `setup` to sth else like `copy`, cause `pnpm setup` will do some extra setup work for pnpm itself in the environment, e.g. writing pnpm paths to your shell rc files

**Review by huozhi — APPROVED** [review]
Nice!

**Pull request merged**
