### PR TITLE
Add npmjs.com as an example website.

### PR DESCRIPTION
**Pull request by vernondegoede**

### CODE REVIEW

**Comment by sedubois** [comment]
There are already other threads to list example websites, e.g https://github.com/zeit/next.js/issues/727, https://github.com/unicodeveloper/awesome-nextjs

**Comment by timneutkens** [comment]
The search page is https://www.npmjs.com/search?q=next&page=1&ranking=optimal

**Comment by sedubois** [comment]
@timneutkens the way I understood it, @vernondegoede means that the whole npmjs.com website is built with next.js...?

**Comment by timneutkens** [comment]
Afaik only the autocomplete is built with Next.js. I know @bcoe worked on it. So maybe he can answer ❤️ cc @bcoe

**Comment by vernondegoede** [comment]
@sedubois @timneutkens Maybe you guys are right. Maybe only search is build with it.

I noticed next.js in the source code when an internal server error occured (looks just like the default errors in Next.js). When you visit https://www.npmjs.com/search?q=slack and look at the source code, you can see this part is built with Next :)

Anyway, should I close this and just add it to https://github.com/unicodeveloper/awesome-nextjs ?

**Comment by timneutkens** [comment]
cc @nkzawa

**Comment by bcoe** [comment]
@timneutkens @sedubois we're currently using `next.js` for the auto-complete search page; thanks for all the hard work 👍

**Comment by timneutkens** [comment]
@bcoe thanks for your answer ❤️

**Comment by timneutkens** [comment]
@vernondegoede could you update to reflect this. `Did you know `https://www.npmjs.com` is running on Next.js as well?`

`[npmjs.com](https://www.npmjs.com/)'s package search is using Next.js as well.`

**Comment by sedubois** [comment]
@tim shouldn't this text rather be added together with other prod examples, as is intended for the 2.0 release?

**Comment by timneutkens** [comment]
Yeah I talked about this on slack. Lets do that.

**Pull request closed without merging**
