### PR TITLE
fix setAssetPrefix when running on NextCustomServer

### LINKED ISSUE #51223: app dir setAssetPrefix not work
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/frosty-yalow-phg76g?file=%2Fnext.config.js%3A3%2C27

### To Reproduce

custom server app dir setAssetPrefix not work in my local server. I don't know how to fix it

### Describe the Bug

custom server app dir setAssetPrefix not work
image

### Expected Behavior

all static asset should with custom prefix like: 'https://www.baidu.com/_next/static/chunk/xxx.js'

### Which browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

custom server (http)

### LINKED ISSUE #59940: Next14. app router with custom sever cannot setAssetPrefix
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/vercel-next-js-reproduction-template-go8s7s

### To Reproduce

1. create a custom app server from `next({ .... })` and express()
2. when app server has prepared, app.setAssetPrefix('https://google.com')

```
const app = next({ dev, hostname, port });
app.prepare().then(() => {
  const server = express();
  server.all("*", async (req, res) => {
    try {
      /** add prefix to assets */
      app.setAssetPrefix("https://www.google.com");
      await handle(req, res, parsedUrl);
    } catch (err) {
      res.statusCode = 500;
      res.end("internal server error");
    }
  });
  server.listen(port, () => {
    console.log(`> Ready on http://${hostname}:${port}`);
  });
});
```

image

### Current vs. Expected behavior

**Current**: when i get 'http://localhost:3000', link scripts's src was like '/_next/static/xxxxxx.js' in the source code, 

**Expected** : it should be like 'https://google.com/_next/static/xxxxxx.js'

**Does Next 14 not support custom server setAssetPrefix in app router?**

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: 7.32.3
Relevant Packages:
  next: 14.0.2
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

latest support version
app router: 13.4.2
pages router: 13.4.12

### Which area(s) are affected? (Select all that apply)

App Router
Page Router

### Additional context

_No response_

### LINKED ISSUE #61383: regression introduced between 13.4.13 - 13.4.15 - appdir + custom server = assetPath issue
### Link to the code that reproduces this issue

https://github.com/morriq/next-cdn-issue/

### To Reproduce

1. clone repository https://github.com/morriq/next-cdn-issue/
2. go to ./apps/app-dir-custom-server
3. pnpm i && pnpm build && pnpm start
4. in browser you should see some assets loaded, some not

### Current vs. Expected behavior

based on reproduction I expect all assets are not loaded. assets are served on different server.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.6.7
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.0.0
  react-dom: 18.0.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local), Other (Deployed)

### Additional context

related issue https://github.com/vercel/next.js/issues/51223

### PR DESCRIPTION
**Pull request by alyahmedaly**
### What?

Fixes `setAssetPrefix` when running on a custom server using next() function

### Why?

Looks like when we run next custom server, there are 2 instances created to handle this case

* main server in `/server/next.ts`
* and Render server `./server/lib/render-server.ts`

The issue mainly happens when calling `setAssetPrefix` it will update only the main server and not render server

``` javascript
  const next = require('next')
  const app = next({ });
    app.setAssetPrefix('my-fancy-cdn/static');
    app.render(); // render server is used instead of the main server
```

### How?

when calling `setAssetPrefix` on the main server also update the render server with the same information.

Fixes: #59940
Fixes: #51223 
Fixes: #61383

### Related Resources

#53523  #49805

https://github.com/vercel/next.js/blob/c9c6ff6d77d3f7b61b955452bd31ec84c5e71cf0/docs/03-pages/01-building-your-application/06-configuring/10-custom-server.mdx

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| buildDuration | 11.9s | 12s | N/A |
| buildDurationCached | 6.2s | 5.6s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +1.67 kB |
| nextStartRea..uration (ms) | 405ms | 408ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.8 kB | 29.8 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 240 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 501 B | N/A |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.19 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 106 B | 106 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 539 B | 538 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 1.05 kB | 1.05 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94.1 kB | N/A |
| page.js gzip | 150 kB | 150 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 622 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 37.7 kB | 37.7 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | alyahmedaly/next.js fix/setAssetPrefix-with-nextCustomServer | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 95.8 kB | 95.8 kB | ✓ |
| app-page-tur..prod.js gzip | 96.4 kB | 96.4 kB | ✓ |
| app-page-tur..prod.js gzip | 91 kB | 91 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 933 kB | 933 kB | ✓ |

</details>

</details>
Commit: df312d4d39dced6d3e61605f2a9cfef52e9396b2

**Review by ijjk — APPROVED** [review]
Thanks for the PR! Went ahead and enabled our custom-server test suite again which ensures we don't regress on this.

**Comment by gaojude** [comment]
Nice - and fwiw, I think it allows us to tap into the internals of the Next server by accessing `app["renderServer"]`!

**Comment by shaunwarman** [comment]
Still seeing next.config.js assetPrefix value coming in for some of the chunks.

https://github.com/vercel/next.js/issues/59940#issuecomment-1928753006

**Comment by ijjk** [comment]
@gaojude just a heads up any internals accessed are not covered by semver only public APIs.

**Comment by gaojude** [comment]
> Still seeing next.config.js assetPrefix value coming in for some of the chunks.
> 
> [#59940 (comment)](https://github.com/vercel/next.js/issues/59940#issuecomment-1928753006)

is it due to the use of https://github.com/vercel/next.js/blob/375d85d95e96df7be09f37eb620f977ae1cfd850/packages/next/src/server/response-cache/index.ts#L17? i have the same issue. most of the links still have the initial asset prefix..

**Comment by ijjk** [comment]
See here https://github.com/vercel/next.js/issues/59940#issuecomment-1930560772 for a deeper explanation why changing the `assetPrefix` during build and runtime can cause isues

**Comment by gaojude** [comment]
> See here [#59940 (comment)](https://github.com/vercel/next.js/issues/59940#issuecomment-1930560772) for a deeper explanation why changing the `assetPrefix` during build and runtime can cause issues

I'm trying to look into a workaround by creating multiple custom servers, each with a distinct hardcoded assetPrefix, and we will tee traffic to each server at runtime. However, I discovered that we did not allow configuring custom server via config object, thus creating this [PR](https://github.com/vercel/next.js/pull/61738) to address it

**Pull request merged**
