### PR TITLE
Add `maxDuration` to typescript plugin allowed exports

### PR DESCRIPTION
**Pull request by AhmedBaset**
According to [docs](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#maxduration) and [tests](https://github.com/vercel/next.js/blob/a3616d33edc40e7717b258f2636f280e30a3bccb/test/e2e/app-dir/with-exported-function-config/app/app-ssr-edge/page.tsx#L6C1-L6C7). `maxDuration` should be a valid export. currently TypeScript plugin throws.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a8d017951d13fd0f31f5b3d6096f2c90e4881f05

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a8d017951d13fd0f31f5b3d6096f2c90e4881f05

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by lilianchisca** [comment]
@A7med3bdulBaset mate you closed this one, but I still have that issue... I use export const maxDuration in some of the app page.tsx files where I needed that maxDuration higher, and vercel picks it up... but I'm still getting that typescript error that it's not a const that can be exported for those files.

**Comment by A7med3bdulBaset** [comment]
I thought https://github.com/vercel/next.js/pull/55918 that was merged in 14.0.4 addresses this. I just double-checked, It doesn't resolve the TS plugin

reopening...

**Comment by RJWadley** [comment]
fixes #59753

@A7med3bdulBaset you should also add a hint and a validator for this, similar to the one `revalidate` has earlier in the file:
```
    isValid: (value: string) => {
      return Number(value.replace(/_/g, '')) > 0
    },
    getHint: (value: any) => {
      return `Limits execution time to \`${value}\` seconds.`
    },
```

**Comment by qoobes** [comment]
What's blocking this in the end? I'm still getting the error.

**Review by huozhi — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 50a1a3dca199bf2cdf7b67828cd0841cf71f8009

`pnpm test test/unit/web-runtime/next-response.test.ts`
-  > can be cloned

<details>
<summary>Expand output</summary>

  ● can be cloned

    TypeError: fetch failed

      at Object.processResponse (eval at requireWithFakeGlobalScope (../node_modules/.pnpm/@edge-runtime+primitives@4.0.2/node_modules/@edge-runtime/primitives/dist/load.js:65:3), <anonymous>:11454:27)
      at eval (eval at requireWithFakeGlobalScope (../node_modules/.pnpm/@edge-runtime+primitives@4.0.2/node_modules/@edge-runtime/primitives/dist/load.js:65:3), <anonymous>:11791:42)

    Cause:
    ConnectTimeoutError: Connect Timeout Error

      at onConnectTimeout (eval at requireWithFakeGlobalScope (../node_modules/.pnpm/@edge-runtime+primitives@4.0.2/node_modules/@edge-runtime/primitives/dist/load.js:65:3), <anonymous>:9145:28)
      at eval (eval at requireWithFakeGlobalScope (../node_modules/.pnpm/@edge-runtime+primitives@4.0.2/node_modules/@edge-runtime/primitives/dist/load.js:65:3), <anonymous>:9101:50)
      at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (../node_modules/.pnpm/@edge-runtime+primitives@4.0.2/node_modules/@edge-runtime/primitives/dist/load.js:65:3), <anonymous>:9133:13)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.6s | N/A |
| buildDurationCached | 6.3s | 5.6s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +1.53 kB |
| nextStartRea..uration (ms) | 425ms | 436ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.8 kB | 29.8 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 240 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 502 B | ✓ |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.18 kB | 4.18 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 608 B | 608 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 149 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 622 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 37.6 kB | 37.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | A7med3bdulBaset/next.js patch-8 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 95.6 kB | 95.6 kB | ✓ |
| app-page-tur..prod.js gzip | 96.3 kB | 96.3 kB | ✓ |
| app-page-tur..prod.js gzip | 90.9 kB | 90.9 kB | ✓ |
| app-page.run...dev.js gzip | 142 kB | 142 kB | ✓ |
| app-page.run..prod.js gzip | 90.2 kB | 90.2 kB | ✓ |
| app-route-ex...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| app-route.ru...dev.js gzip | 21.6 kB | 21.6 kB | ✓ |
| app-route.ru..prod.js gzip | 14.5 kB | 14.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.42 kB | 9.42 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.42 kB | 9.42 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

</details>
Commit: 50a1a3dca199bf2cdf7b67828cd0841cf71f8009

**Pull request merged**
