### PR TITLE
fix: pass `nonce` to `next/script` with `afterInteractive` strategy

### PR DESCRIPTION
**Pull request by kevva**
### What?

This fixes an issue where the `nonce` attribute isn't set on `next/script` elements that has the `afterInteractive` (the default) strategy resulting in `<link rel="preload" as="script"/>` tags without a nonce.

### Why?

For apps that uses 3rd party scripts (or any script) with a nonce loaded via `next/script` this is necessary unless you want them all to use `beforeInteractive` which isn't super nice for performance.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6a4372a2ebdaa9a94c78fa71c62444c318f8364d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by SukkaW — APPROVED** [review]
LGTM, as `ReactDOMFloat` does have `nonce` (https://github.com/facebook/react/blob/6db7f4209e6f32ebde298a0b7451710dd6aa3e19/packages/react-dom/src/shared/ReactDOMFloat.js#L129) supports.

**Comment by kevva** [comment]
@SukkaW, anything else you need from me?

**Comment by kevva** [comment]
@timneutkens @ijjk, sorry for the ping but any chance we can get this reviewed and merged :)?

**Review by timneutkens — DISMISSED** [review]
Looking at these it seems there is another case that is missing the nonce on preload 🤔 https://github.com/vercel/next.js/pull/56995/files#diff-d7794cd766752e9cdff323db1f142a20fc6ac348eb399d0ec5f600ed122d4b0eR346-R348

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.5s | N/A |
| buildDurationCached | 5.9s | 6s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +276 B |
| nextStartRea..uration (ms) | 402ms | 401ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| 199-HASH.js gzip | 29.1 kB | 29.1 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | N/A |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 46.9 kB | 46.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 506 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.3 kB | 4.3 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.65 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| _buildManifest.js gzip | 486 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| index.html gzip | 527 B | 527 B | ✓ |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 524 B | 521 B | N/A |
| Overall change | 527 B | 527 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.5 kB | 92.5 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 624 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | ✓ |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 26.7 kB | 26.7 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | kevva/next.js fix-after-interactive-nonce | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | ✓ |
| app-page-exp..prod.js gzip | 93.2 kB | 93.2 kB | ✓ |
| app-page-tur..prod.js gzip | 93.9 kB | 93.9 kB | ✓ |
| app-page-tur..prod.js gzip | 88.5 kB | 88.5 kB | ✓ |
| app-page.run...dev.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run..prod.js gzip | 87.9 kB | 87.9 kB | ✓ |
| app-route-ex...dev.js gzip | 23.8 kB | 23.8 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| server.runti..prod.js gzip | 48.8 kB | 48.8 kB | ✓ |
| Overall change | 922 kB | 922 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 21a5e90b26cda67f894e832a4c0f0e1a0ab97059

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 21a5e90b26cda67f894e832a4c0f0e1a0ab97059

`pnpm test-dev test/e2e/app-dir/app-compilation/index.test.ts` 
- app dir > HMR > should not cause error when removing loading.js

<details>
<summary>Expand output</summary>

  ● app dir › HMR › should not cause error when removing loading.js

    TIMED OUT: hello from new page

    hello from slow page

    undefined

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (e2e/app-dir/app-compilation/index.test.ts:44:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by kevva** [comment]
> Looking at these it seems there is anothr case that is missing the nonce on preload 🤔 [#56995 (files)](https://github.com/vercel/next.js/pull/56995/files#diff-d7794cd766752e9cdff323db1f142a20fc6ac348eb399d0ec5f600ed122d4b0eR346-R348)

Not sure they're needed if `nonce` exist on their script tags which [it does](https://github.com/kevva/next.js/blob/21a5e90b26cda67f894e832a4c0f0e1a0ab97059/packages/next/src/client/script.tsx#L333).

**Comment by karlhorky** [comment]
> Not sure they're needed if nonce exist on their script tags which [it does](https://github.com/kevva/next.js/blob/21a5e90b26cda67f894e832a4c0f0e1a0ab97059/packages/next/src/client/script.tsx#L333).

@kevva The `nonce` attribute is also on the other failing `<script>` tag (the `afterInteractive` one) and there it also requires the nonce on preload.

So I guess it's required, and the suggestion from @timneutkens should be implemented?

Cc @leerob @ijjk @gnoff @danieltott   this is currently causing strict CSPs to fail when using `next/script` (`<Script>` component). The `<link rel="preload">` that is generated with `ReactDOM.preload()` does not have the `nonce` attribute.

**Comment by kevva** [comment]
@timneutkens, I addressed the `beforeInteractive` case.

**Comment by lynettelopez** [comment]
@timneutkens @karlhorky My team is hoping this PR will be merged in soon. It's currently blocking our transition from Pages Router to App Router because of the CSP requirement our broader org sets. This feels like it's close to the finish line—anything I can do to speed this up?

**Review by ijjk — APPROVED** [review]
Added change and test look good just expanded it a bit, thanks for the PR!

**Pull request merged**
