### PR TITLE
Use prettier-standard

### PR DESCRIPTION
**Pull request by bensalilijames**
In an attempt to move towards [Prettier](https://prettier.io/), I ran the whole codebase through `prettier-standard`! 🎉 

The only non-automated changes are in `package.json`, which adds `prettier-standard` to the `devDependencies` and also to the commit hook.

The rest of the commit's changes are all automatically made using `prettier-standard '**/*.js'`.

Let me know what you think 🙂

### CODE REVIEW

**Comment by timneutkens** [comment]
I'd love to move to prettier + eslint-config-airbnb, but let's switch to it for only the examples right now

**Comment by timneutkens** [comment]
I'd love to move to prettier + eslint-config-airbnb, but let's switch to it for only the examples right now

**Comment by timneutkens** [comment]
I'd love to move to prettier + eslint-config-airbnb, but let's switch to it for only the examples right now

**Comment by timneutkens** [comment]
I'd love to move to prettier + eslint-config-airbnb, but let's switch to it for only the examples right now

**Comment by timneutkens** [comment]
I'd love to move to prettier + eslint-config-airbnb, but let's switch to it for only the examples right now

**Comment by benhjames** [comment]
Superceded by #5528.

**Pull request closed without merging**
