### PR TITLE
Update `with-redux` example to match the guide in Redux Toolkit docs

### PR DESCRIPTION
**Pull request by aryaemami59**
### What?

Update `with-redux` example.

### Why?

`with-redux` example currently:

- does not follow the folder structure recommended by Redux Toolkit
- does not create unique store instances per request as recommended by Redux Toolkit
- adds the Redux Logger middleware by default which is not necessary and has type compatibility issues with Redux Toolkit v2
- contains some outdated packages

### How?

This PR:

- [x] Overhauls the folder structure to match the recommended folder structure
- [x] Creates unique store instances per request as recommended by Redux Toolkit
- [x] Removes the Redux Logger middleware
- [x] Updates outdated packages

#### Relevant Information

https://redux-toolkit.js.org/usage/migrating-rtk-2#nextjs-setup-guide
https://redux.js.org/usage/nextjs#folder-structure

### CODE REVIEW

**Comment by markerikson** [comment]
And for the record, I maintain Redux and Redux Toolkit, and I requested these changes to the example :)

/cc @leerob 

Actual review feedback: 

- could we move those thunks from `counter/thunks.ts` into `counter/counterSlice.ts`?  Don't see a reason for them to be split out
- the README phrasing about RTK seems a bit awkward.  Can we update that text for grammar, spelling, and phrasing?
- for some reason I thought we had RTK Query set up in the Redux CRA/Vite templates, but apparently we don't.  Wonder if it's worth adding that here at all, or not.

**Comment by aryaemami59** [comment]
- [X] Moved contents of `counter/thunks.ts` into `counter/counterSlice.ts`. Do you think I should maybe move `createAppAsyncThunk` into `store.ts` and maybe inline `fetchIdentityCount` to reduce some of the extra complexity?
- [X] Tweaked `README`. Is there anything else I need to add?
- [X] Added an RTK Query example, but not feeling too great about it, not sure it does RTK Query enough justice. I'm definitely going to need some feedback on this one.

**Review by EskiMojo14 — COMMENTED** [review]
just noting a couple of pieces of feedback that haven't been actioned yet so they're easier to keep track of :)

overall this looks great, thanks for being open to showcasing the new features of RTK 2.0!

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/53817#issuecomment-1879756438

**Comment by aryaemami59** [comment]
@EskiMojo14 @markerikson @phryneas @leerob I made the improvements that were suggested, does this need anything else?

**Comment by EskiMojo14** [comment]
I'm happy with it :)

**Review by leerob — APPROVED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8637c48dea3e5598eaec56009096c0eda6a96968

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8637c48dea3e5598eaec56009096c0eda6a96968

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by markerikson** [comment]
Awesome, thank you!

**Pull request merged**
