### PR TITLE
chore(logging): Disable info logging of critters in production

### PR DESCRIPTION
**Pull request by jonluca**
Critters uses the `info` logLevel by default. This means that when you enable the experimental `optimizeCss` property, your production logs will be polluted with their logs

This sets the log level to warn by default in production, and allows configuration via an environment variable 

CleanShot 2024-03-02 at 18 12 46@2x

### CODE REVIEW

**Comment by jonluca** [comment]
@ijjk @timneutkens this is a small change but one that would be a great quality of life for us (and anyone that uses tailwind + SSR + nextjs) to clean up our production logging. Would appreciate a review, or any comments

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Looks good to me to land 👍

**Comment by timneutkens** [comment]
Probably important to know: that experimental flag was discontinued and is no longer being worked on, it'll likely be removed in the near future.

**Comment by jonluca** [comment]
Thanks!

Really? That flag is what enables SSR to work properly for tailwind apps in pages mode. You get a flash of unstyled content otherwise. Is there a preferred way of solving that? 

I opened this discussion https://github.com/vercel/next.js/discussions/62777 to ask if there was some way of doing this in userland pre response but I don't think there is.

**Review by ijjk — APPROVED** [review]

**Pull request merged**
