### PR TITLE
Fix `revalidateTag()` behaviour when invoked in server components (#70446)

### LINKED ISSUE #70403: revalidateTag() not functioning as expected in versions above 14.2.10 when used directly in page.tsx
### Link to the code that reproduces this issue

https://github.com/JesperCph/revalidate-tag-issues-reproduction

### To Reproduce

1. Build and start the app using `pnpm build` & `pnpm start`
2. Open the app at `http://localhost:3000/`
3. Time is fetched from `/api/time`, displayed on the landing page, and cached for 60 seconds with the tag `time`.
4. Navigate to the "Revalidate (page)" using the link, which triggers `revalidateTag('time')`.
5. Navigate back to the "Home" page ('/'), should fetch the updated time from `/api/time` and display the new value.

**Issue**
This workflow works as expected in `next@14.2.10` and below, but in versions above `14.2.10,` including `next@15`, the tag "time" is not revalidated on visiting `/revalidate/page.tsx` 

Callen revalideTag() within a POST server action, works as exspexted. This can be tested by clicking 
`Revalidate (Form Action)` from the home page, which updates the time.

### Current vs. Expected behavior

**Current**:
The time on the home page `/` is not updated when navigating back and forth between `/revalidate` and `/` using the links.

**Expected**:
The time on the home page `/` should update with the value from `/api/time` when navigating back and forth between `/revalidate` and `/` using the links, as the `revalidateTag('time')` function is called from `/revalidate/page.tsx`.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15813
  Available CPU cores: 20
Binaries:
  Node: 19.9.0
  npm: 9.6.3
  Yarn: 1.22.22
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: 14.2.13
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

- The bug was introduced in next@14.2.11.
- When calling `revalidateTag()` within a POST server action, the time is revalidated as expected.

### PR DESCRIPTION
**Pull request by ijjk**
This backports #70446 to 14-2-1

Fixes #70403

### What?
When `revalidateTag()` is called directly in server components, the cache is not purged for the corresponding tags. Reproduction steps available in #70403

### How?
Check
[app-render.tsx](https://github.com/vercel/next.js/compare/canary...abhi12299:fix-revalidatetag-rsc?expand=1#diff-a3e2e024db1faa1b501e0dd6040eaaf0d931cb9878ae0fb0f4c3658daa982768) This issue was introduced in #65296 in this file:
[revalidate.ts](https://github.com/vercel/next.js/pull/65296/files#diff-7f0cb5bb30d44b9153d724e31c25859b9aab6cc258b35563a1d9464cd0688283). The lines removed from the file resulted in the revalidation checks to be skipped when there is an RSC request.

Also fixed checks on `pendingRevalidates` to also check for `revalidatedTags`.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: fec85a2d1a8e773e78b79f095698cab02618bd17

`TURBOPACK=1 pnpm test-dev test/development/basic/node-builtins.test.ts` (turbopack)
- node builtins > should support node.js builtins in server component
- node builtins > should support node.js builtins prefixed by node: in server component

<details>
<summary>Expand output</summary>

  ● node builtins › should support node.js builtins in server component

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      124 |
      125 |       const data = $('#node-browser-polyfills').text()
    > 126 |       const parsedData = JSON.parse(data)
          |                               ^
      127 |
      128 |       expect(parsedData.vm).toBe(105)
      129 |       expect(parsedData.hash).toBe(

      at Object.parse (development/basic/node-builtins.test.ts:126:31)

  ● node builtins › should support node.js builtins prefixed by node: in server component

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      149 |
      150 |       const data = $('#node-browser-polyfills').text()
    > 151 |       const parsedData = JSON.parse(data)
          |                               ^
      152 |
      153 |       expect(parsedData.vm).toBe(105)
      154 |       expect(parsedData.hash).toBe(

      at Object.parse (development/basic/node-builtins.test.ts:151:31)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| buildDuration | 16.2s | 15.2s | N/A |
| buildDurationCached | 8.2s | 6.5s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ⚠️ +27.2 kB |
| nextStartRea..uration (ms) | 405ms | 407ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| 1103-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| 1a9f679d-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 335-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| 7953.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 44.9 kB | 44.9 kB | ✓ |
| main-app-HASH.js gzip | 243 B | 243 B | ✓ |
| main-HASH.js gzip | 32.3 kB | 32.3 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 50.3 kB | 50.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| _app-HASH.js gzip | 195 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 501 B | 506 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 1.82 kB | 1.82 kB | N/A |
| edge-ssr-HASH.js gzip | 259 B | 258 B | N/A |
| head-HASH.js gzip | 350 B | 352 B | N/A |
| hooks-HASH.js gzip | 372 B | 371 B | N/A |
| image-HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| index-HASH.js gzip | 259 B | 258 B | N/A |
| link-HASH.js gzip | 2.68 kB | 2.68 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 315 B | N/A |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 311 B | 310 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 4.9 kB | 4.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 483 B | ✓ |
| Overall change | 483 B | 483 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| index.html gzip | 528 B | 529 B | N/A |
| link.html gzip | 542 B | 541 B | N/A |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 525 B | 525 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 659 B | 659 B | ✓ |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 1.65 kB | 1.65 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | N/A |
| app-page-exp..prod.js gzip | 98.1 kB | 98.2 kB | N/A |
| app-page-tur..prod.js gzip | 99.8 kB | 99.9 kB | N/A |
| app-page-tur..prod.js gzip | 94.1 kB | 94.2 kB | N/A |
| app-page.run...dev.js gzip | 145 kB | 145 kB | N/A |
| app-page.run..prod.js gzip | 92.6 kB | 92.7 kB | N/A |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 15.5 kB | 15.5 kB | ✓ |
| app-route-tu..prod.js gzip | 15.5 kB | 15.5 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.58 kB | 9.58 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.85 kB | 9.85 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.57 kB | 9.57 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| pages.runtim..prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| server.runti..prod.js gzip | 51.5 kB | 51.5 kB | ✓ |
| Overall change | 254 kB | 254 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js 14-2-1  | ijjk/next.js ijjk/backport-revalidate-tag | Change |
| - | - | - | - |
| 0.pack gzip | 1.61 MB | 1.6 MB | N/A |
| index.pack gzip | 113 kB | 113 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: fec85a2d1a8e773e78b79f095698cab02618bd17

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b07cc344ce98fb039bff52697788231c087fa451

`TURBOPACK=1 pnpm test-dev test/e2e/app-dir/asset-prefix/asset-prefix.test.ts` (turbopack)

<details>
<summary>Expand output</summary>



  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/app_layout_21271e.js failed, reason: read ECONNRESET

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/_ed9c4a._.js failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/bb758_next_dist_esm_build_templates_app-page_d21cea.js failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/bb758_next_dist_esm_build_templates_app-page_441a85.js failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/[turbopack]_dev_client_hmr-client_ts_4e66b4._.js failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/90481_%40swc_helpers_cjs_e55b81._.js failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/_ff8ab2._.js failed, reason: read ECONNRESET

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/app_page_987d4b.js failed, reason: read ECONNRESET

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● Test suite failed to run

    FetchError: request to http://localhost:46777/custom-asset-prefix/_next/static/chunks/bb758_next_dist_compiled_react_bc4f0f._.js failed, reason: read ECONNRESET

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c01346a9327ac9a54ee28693f9171aa50117aa85

`pnpm test-dev test/development/basic/hmr.test.ts`
- basic HMR, nextConfig: { basePath: '', assetPrefix: '' } > Error Recovery > should recover after loader parse error in an imported file
- basic HMR, nextConfig: { basePath: '/docs', assetPrefix: '' } > Error Recovery > should recover after loader parse error in an imported file

<details>
<summary>Expand output</summary>

  ● basic HMR, nextConfig: { basePath: '', assetPrefix: '' } › Error Recovery › should recover after loader parse error in an imported file

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR, nextConfig: { basePath: '', assetPrefix: '' } Error Recovery should recover after loader parse error in an imported file 1`

    - Snapshot  - 8
    + Received  + 8

      ./components/parse-error.js
      Error: 
        x Expression expected
    -   ,-[./components/parse-error.js:1:1]
    +    ,-[./components/parse-error.js:1:1]
    - 1 | This
    +  1 | This
    - 2 | is
    +  2 | is
    - 3 | }}}
    +  3 | }}}
    -   : ^
    +    : ^
    - 4 | invalid
    +  4 | invalid
    - 5 | js
    +  5 | js
    -   
    +

      928 |
      929 |             expect(next.normalizeTestDirContent(redboxSource))
    > 930 |               .toMatchInlineSnapshot(`
          |                ^
      931 |                 "./components/parse-error.js
      932 |                 Error: 
      933 |                   x Expression expected

      at Object.toMatchInlineSnapshot (development/basic/hmr.test.ts:930:16)

  ● basic HMR, nextConfig: { basePath: '/docs', assetPrefix: '' } › Error Recovery › should recover after loader parse error in an imported file

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR, nextConfig: { basePath: '/docs', assetPrefix: '' } Error Recovery should recover after loader parse error in an imported file 1`

    - Snapshot  - 8
    + Received  + 8

      ./components/parse-error.js
      Error: 
        x Expression expected
    -   ,-[./components/parse-error.js:1:1]
    +    ,-[./components/parse-error.js:1:1]
    - 1 | This
    +  1 | This
    - 2 | is
    +  2 | is
    - 3 | }}}
    +  3 | }}}
    -   : ^
    +    : ^
    - 4 | invalid
    +  4 | invalid
    - 5 | js
    +  5 | js
    -   
    +

      928 |
      929 |             expect(next.normalizeTestDirContent(redboxSource))
    > 930 |               .toMatchInlineSnapshot(`
          |                ^
      931 |                 "./components/parse-error.js
      932 |                 Error: 
      933 |                   x Expression expected

      at Object.toMatchInlineSnapshot (development/basic/hmr.test.ts:930:16)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 6047f262c27fe731ffb9dae210b89cdd90c5b39f

`TURBOPACK=1 pnpm test-dev test/e2e/prerender.test.ts` (turbopack)
- Prerender > should log error in console and browser in development mode

<details>
<summary>Expand output</summary>

  ● Prerender › should log error in console and browser in development mode

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#after-change')

      425 |     return this.chain(() => {
      426 |       return page
    > 427 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      428 |         .then(async (el) => {
      429 |           // it seems selenium waits longer and tests rely on this behavior
      430 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:427:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by sebmarkbage** [comment]
This should actually throw and not revalidate because it's a side-effect in render. `cookies().set()` too.

Other than just breaking The Rules of React in general, and being bad practice since there's no guarantee when it's called - if it's called - how many times it is called. It's also not possible to send invalidations to the client at this point so if you do it for example after render a Server Action, the client won't be invalidated as a result.

**Pull request merged**
