### PR TITLE
Re-add Partytown custom configuration to `Script` component documentation

### LINKED ISSUE #68943: Docs: Missing custom Partytown configuration for `Script` with `strategy="worker"`
### What is the documentation issue?

Next.js is missing documentation about Partytown configuration for its usage with the `Script` component.

### Is there any context that might help us understand?

The [`Script`](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts) component with the `strategy` prop set to `worker` uses [Partytown](https://partytown.builder.io/) under the hood.

Users may need to customize [Partytown options](https://partytown.builder.io/configuration) such as `forward`, `loadScriptsOnMainThread`, and `resolveUrl`, to allow for third party scripts such as Segment and Google Tag Manager to work properly.

Next.js allows customizing Partytown options by specifying a `script` tag with `data-partytown-config` inside `Head`:

```jsx
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <script
          data-partytown-config
          dangerouslySetInnerHTML={{
            __html: `
              partytown = {
                lib: "/_next/static/~partytown/",
                debug: true
              };
            `,
          }}
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
```

This used to be documented on `docs/basic-features/script.md`, as you can see on the [pull request that originally introduced the `worker` strategy](https://github.com/vercel/next.js/pull/34244/files#diff-62dbdb4bc703f7997ea259ad68d8e823d9fafed1e9571155e01c4de21abb6b47R165-R197), but this doc page was removed (potentially unintendedly) on https://github.com/vercel/next.js/pull/50701, and there's no longer mention of Partytown configuration in Next.js docs.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#strategy

### PR DESCRIPTION
**Pull request by guisehn**
### What?

Add documentation about Partytown configuration on the `Script` documentation page.

### Why?

The [`Script`](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts) component with the `strategy` prop set to `worker` uses [Partytown](https://partytown.builder.io/) under the hood.

Users may need to customize [Partytown options](https://partytown.builder.io/configuration) such as `forward`, `loadScriptsOnMainThread`, and `resolveUrl`, to allow for third party scripts such as Segment and Google Tag Manager to work properly.

This used to be documented on `docs/basic-features/script.md`, as you can see on the [pull request that originally introduced the `worker` strategy](https://github.com/vercel/next.js/pull/34244/files#diff-62dbdb4bc703f7997ea259ad68d8e823d9fafed1e9571155e01c4de21abb6b47R165-R197), but this doc page was removed (potentially unintendedly) on https://github.com/vercel/next.js/pull/50701, and there's no longer mention of Partytown configuration in Next.js docs.

### How?

Adding back the documentation text originally written by @housseindjirdeh in his pull request https://github.com/vercel/next.js/pull/34244

Fixes https://github.com/vercel/next.js/issues/68943

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 229339955d0e2a184e958b3d762a1bb073a3cfbc

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@guisehn Let's wrap the new section with `<PagesOnly>`, as it only works in Pages Router. We don't have a `<Head>` component since it is incompatible with streaming in App Router.

**Comment by guisehn** [comment]
@samcx Sounds good. I've added `<PagesOnly>` on https://github.com/vercel/next.js/pull/68946/commits/5c9ef5c7fb5e656f376221bbcb9a30114f691662

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
