### PR TITLE
add experimental.urlImports option

### PR DESCRIPTION
**Pull request by sokra**
add a test case
add documentation

```
experimental: {
  urlImports: [
    "https://example.com/modules/"
  ]
}
```

### CODE REVIEW

**Comment by sokra** [comment]
blocked by https://github.com/webpack/webpack/pull/14543

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 16s | 15.5s | -505ms |
| buildDurationCached | 3.4s | 3s | -444ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +1.32 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.802 | 3.776 | -0.03 |
| / avg req/sec | 657.51 | 662.06 | +4.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.004 | 2.035 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1247.55 | 1228.66 | ⚠️ -18.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 6.6s | 6.7s | ⚠️ +90ms |
| buildDurationCached | 2.9s | 3s | ⚠️ +99ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +1.32 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.352 | 3.384 | ⚠️ +0.03 |
| / avg req/sec | 745.75 | 738.84 | ⚠️ -6.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.771 | 1.757 | -0.01 |
| /error-in-render avg req/sec | 1411.75 | 1423.05 | +11.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 4fb0c194189bbebb81b4656fc3fc8563239fc788

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 17.1s | 16.9s | -179ms |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +48ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +1.32 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.051 | 4.284 | ⚠️ +0.23 |
| / avg req/sec | 617.13 | 583.62 | ⚠️ -33.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.175 | 2.19 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1149.63 | 1141.73 | ⚠️ -7.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 7.3s | 7.6s | ⚠️ +333ms |
| buildDurationCached | 3.5s | 3.9s | ⚠️ +326ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +1.32 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.793 | 3.727 | -0.07 |
| / avg req/sec | 659.03 | 670.74 | +11.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.046 | 1.976 | -0.07 |
| /error-in-render avg req/sec | 1222.18 | 1265.26 | +43.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: e834e0bdc180b2665e43d01d2d67efb68d754f84

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.9s | ⚠️ +489ms |
| buildDurationCached | 3.3s | 3s | -267ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +1.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.803 | 2.887 | ⚠️ +0.08 |
| / avg req/sec | 891.88 | 865.94 | ⚠️ -25.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.382 | 1.437 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1809 | 1739.48 | ⚠️ -69.52 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-a993820..123b.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 530 B | 530 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| buildDuration | 6.2s | 6s | -202ms |
| buildDurationCached | 2.8s | 2.7s | -42ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +1.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.786 | 2.724 | -0.06 |
| / avg req/sec | 897.2 | 917.85 | +20.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.362 | 1.424 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1836.19 | 1755.16 | ⚠️ -81.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-17a5f65..3805.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-e04a..a1b5.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 477 B | 477 B | ✓ |
| Overall change | 477 B | 477 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js url-imports | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: d685e38c34c2935502395283209dc213b0563ea7

**Review by molebox — CHANGES_REQUESTED** [review]

**Review by timneutkens — APPROVED** [review]

**Review by molebox — APPROVED** [review]
lgtm

**Pull request merged**
