### PR TITLE
Upgrade Node.js to fix repro templates (16 -> LTS)

### PR DESCRIPTION
**Pull request by karlhorky**
### What?

Upgrade Node.js version from 16 to LTS in CodeSandbox reproduction templates for both App Router and Pages Router

### Why?

Currently the reproduction templates linked in the GitHub issues template is broken. This causes users reporting bugs to not be able to create reproductions.

([Next.js v14 has a minimum Node.js version of 18.17](https://nextjs.org/blog/next-14#:~:text=%5BBreaking%5D%20Minimum%20Node.js%20version%20is%20now%2018.17))

Reproduction steps:

1. Open either reproduction template on CodeSandbox, eg. the Pages Router reproduction template: https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages
2. Delete the outdated `yarn.lock` file to get the latest canary version (this I fixed separately in https://github.com/vercel/next.js/pull/57895 and https://github.com/vercel/next.js/pull/57896 )
3. Open a new terminal and run `yarn` to install latest canary version
4. The latest canary cannot be installed, because of the CodeSandbox Node.js version of `16.17.0`

```bash
$ yarn
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error next@14.0.2-canary.5: The engine "node" is incompatible with this module. Expected version ">=18.17.0". Got "16.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Screenshot 2023-11-01 at 15 31 31

### How?

Change the base image to Node.js LTS bullseye image, using Dev Containers

CodeSandbox Demo of a fixed sandbox which applies this change: https://codesandbox.io/p/sandbox/zealous-ellis-t599tx?file=%2Fapp%2Fpage.tsx%3A4%2C2

Screenshot 2023-11-01 at 17 10 14

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f2baaf9f6c09d9892e25cc16c5db0f006930ad51

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f2baaf9f6c09d9892e25cc16c5db0f006930ad51

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: f2baaf9f6c09d9892e25cc16c5db0f006930ad51

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — COMMENTED** [review]
I think this should not be required, rather we should rely on the fact that CodeSandbox has this by default. (I pinged them about it).

Also, the reproduction template might not be used in CodeSandbox, so it doesn't feel correct to add this file.

**Comment by karlhorky** [comment]
> we should rely on the fact that CodeSandbox has this by default

Agree that this would be ideal! However, this could take months or years though, judging by how slow Replit updated Node.js. It may be in a critical part of infrastructure that is not easy to change.

In the meantime, the reproduction template is broken for users trying to report a bug, which is in my opinion very important to fix immediately.

> Also, the reproduction template might not be used in CodeSandbox, so it doesn't feel correct to add this file.

If it would be preferable to have it in `.devcontainers`, apparently this works too:

Screenshot 2023-11-01 at 15 24 13

**Comment by karlhorky** [comment]
@balazsorban44 I added reproduction steps and a screenshot to show the breakage, since that may have been unclear.

**Comment by karlhorky** [comment]
> If it would be preferable to have it in `.devcontainers`, apparently this works too:

@balazsorban44 I switched this PR to Dev Containers.

**Comment by karlhorky** [comment]
> If it would be preferable to have it in `.devcontainers`, apparently this works too:

@balazsorban44 I switched this PR to Dev Containers, which are not CodeSandbox-specific (and which already exist in various places in the Next.js repo).

**Comment by karlhorky** [comment]
I chatted a bit with @CompuIves, and my current solution with Dev Containers would also be a preferable solution for CodeSandbox.

@balazsorban44 the CodeSandbox reproductions are currently broken for users. How about going ahead with the Dev Containers version? (instead of waiting until some future point in time when CodeSandbox upgrades beyond v16)

Another benefit with the Dev Containers version: it allows for the Next.js reproduction examples to specify the best specific Node.js version to run them on.

**Comment by balazsorban44** [comment]
Ideally, we should not need to add any additional files here. Awaiting response from our chat with the CodeSandbox team.

**Comment by balazsorban44** [comment]
CodeSandbox now defaults to Node.js 20 on new sandboxes, so this is not necessary anymore!

**Comment by karlhorky** [comment]
Ok, thanks.

In future this may come back again (eg. CodeSandbox is behind on Node.js versions and Next.js has already upgraded to a minimum beyond the CodeSandbox version), but I guess maintainers will revisit it then.

**Pull request closed without merging**
