### PR TITLE
Fix with-styled-jsx-postcss example

### PR DESCRIPTION
**Pull request by giuseppeg**
Fixes Fixes zeit/next.js#964

### CODE REVIEW

**Comment by giuseppeg** [comment]
see giuseppeg/styled-jsx-postcss/issues/10

**Review by timneutkens — APPROVED** [review]
👍

**Comment by giuseppeg** [comment]
@timneutkens not sure what's up with node 4, tests pass locally. Can you try to restart the build before I debug?

**Comment by timneutkens** [comment]
Already did. It's not your code.

**Pull request merged**
