### PR TITLE
Ie11 polyfills

### LINKED ISSUE #12713: Object.keys non-object coercion not working in IE 11
# Bug report

## Describe the bug

The argument passed to the `Object.keys` method should be coerced to an object from ES2015 onward. 
As illustrated in the example taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys.
```
// In ES5
Object.keys('foo');  // TypeError: "foo" is not an object 

// In ES2015+
Object.keys('foo');  // ["0", "1", "2"]     
```

However, this behaviour is not pollyfilled in Next.js for IE 11.

## To Reproduce

1. Download the reproduction available at https://github.com/tomdohnal/object-keys-ie-repro
2. Use `yarn dev` or `npm run dev` to start the development server
3. Open the page in IE 11 and it crashes.

## Expected behavior

It should coerce the argument passed to Object.keys to object and not crash.

## System information

- OS: [Windows 10]
- Browser [e.g. IE 11]
- Version of Next.js: [e.g. 9.3.6]
- Version of Node.js: [e.g. 12.14.0]

### PR DESCRIPTION
**Pull request by tomdohnal**
This resolves https://github.com/vercel/next.js/issues/12713 and https://github.com/vercel/next.js/issues/12722

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| buildDuration | 13.2s | 12.7s | -462ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.275 | 2.2 | -0.07 |
| / avg req/sec | 1098.88 | 1136.32 | ⚠️ +37.44 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.395 | 1.548 | ⚠️ +0.15 |
| /error-in-render avg req/sec | 1792.18 | 1614.84 | -177.34 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.4 kB | ⚠️ +94 B |
| Overall change | 26.3 kB | 26.4 kB | ⚠️ +94 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| index.html gzip | 924 B | 924 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -78,7 +78,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-eaf5488e20ec921d713f.js"
+      src="/_next/static/runtime/polyfills-e88dfbb0e4353a54b76a.js"
     ></script>
     <script
       async=""
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -83,7 +83,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-eaf5488e20ec921d713f.js"
+      src="/_next/static/runtime/polyfills-e88dfbb0e4353a54b76a.js"
     ></script>
     <script
       async=""
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -78,7 +78,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-eaf5488e20ec921d713f.js"
+      src="/_next/static/runtime/polyfills-e88dfbb0e4353a54b76a.js"
     ></script>
     <script
       async=""
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.4s | -478ms |
| nodeModulesSize | 66 MB | 66 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.4 kB | ⚠️ +94 B |
| Overall change | 26.3 kB | 26.4 kB | ⚠️ +94 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _error.js | 878 kB | 878 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 879 kB | 879 kB | ✓ |
| link.js | 916 kB | 916 kB | ✓ |
| routerDirect.js | 909 kB | 909 kB | ✓ |
| withRouter.js | 909 kB | 909 kB | ✓ |
| Overall change | 4.5 MB | 4.5 MB | ✓ |

</details>

</details>

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.5s | -236ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.936 | 1.889 | -0.05 |
| / avg req/sec | 1291.35 | 1323.51 | +32.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.195 | 1.135 | -0.06 |
| /error-in-render avg req/sec | 2091.37 | 2201.98 | +110.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.4 kB | ⚠️ +93 B |
| Overall change | 26.3 kB | 26.4 kB | ⚠️ +93 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| index.html gzip | 954 B | 954 B | ✓ |
| link.html gzip | 959 B | 958 B | -1 B |
| withRouter.html gzip | 946 B | 945 B | -1 B |
| Overall change | 2.86 kB | 2.86 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -78,7 +78,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-e77205bd3f87781c0279.js"
+      src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
       src="/_next/static/runtime/main-a402689d595ce1baa2c7.js"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -83,7 +83,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-e77205bd3f87781c0279.js"
+      src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
       src="/_next/static/runtime/main-a402689d595ce1baa2c7.js"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -78,7 +78,7 @@
     <script
       crossorigin="anonymous"
       nomodule=""
-      src="/_next/static/runtime/polyfills-e77205bd3f87781c0279.js"
+      src="/_next/static/runtime/polyfills-fa968511391ff096b874.js"
     ></script>
     <script
       src="/_next/static/runtime/main-a402689d595ce1baa2c7.js"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.3s | -325ms |
| nodeModulesSize | 66.1 MB | 66.1 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..18e4.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | ✓ |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.09 kB | 7.09 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.4 kB | ⚠️ +93 B |
| Overall change | 26.3 kB | 26.4 kB | ⚠️ +93 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 268 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tomdohnal/next.js ie11-polyfills | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 876 kB | 876 kB | ✓ |
| link.js | 915 kB | 915 kB | ✓ |
| routerDirect.js | 908 kB | 908 kB | ✓ |
| withRouter.js | 908 kB | 908 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>
Commit: 84ebb6abe1797d6cf587f1b34676fd90d1a5f305

**Comment by StevenMatchett** [comment]
🙌

**Pull request merged**
