### PR TITLE
with-global-stylesheet-scoped example

### PR DESCRIPTION
**Pull request by pencilcheck**

### CODE REVIEW

**Comment by timneutkens** [comment]
We already have an example like this https://github.com/zeit/next.js/tree/v3-beta/examples/with-scoped-stylesheets-and-postcss

**Comment by pencilcheck** [comment]
The example you mention is completely different from this example I'm trying to commit. That example does className namespacing directly, and mangling existing class names. I want one where you can easily import a library and continue using it without having to know the new mangled class name is and scope that to a component that uses that stylesheet.

Let me know if that is still confusing.

Btw, I'm very close in finding out how to do SSR and hot reloading, expect some more updates soon.

**Comment by pencilcheck** [comment]
Yep, I think it is good to pull now.

**Comment by timneutkens** [comment]
@pencilcheck can you check the travis errors, mostly linting errors. Try `npm run lint -- --fix` first and fix the rest of the issues 😄

**Comment by timneutkens** [comment]
Going to close this for inactivity

**Pull request closed without merging**
