### PR TITLE
Update with web worker example to utilize the App Router

### PR DESCRIPTION
**Pull request by Sam-Phillemon9493**
This PR updates the with-web-worker example to use the App Router. Here are the changes that have been made:

- Renamed the `pages` folder to the `app` folder.
- Updated the routing for `/` files to align with the App Router.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

The following actions were performed as part of this PR:
- Ran `pnpm prettier-check` with no issues found.
- Executed the `pnpm check-examples` script.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7a640440b702d4eeebb4d362fa12bf5fe589f179

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Sam-Phillemon9493** [comment]
> This PR updates the with-web-worker example to use the App Router. Here are the changes that have been made:
> 
> * Renamed the `pages` folder to the `app` folder.
> * Updated the routing for `/` files to align with the App Router.
> * Added the layout.tsx file as part of the App Router.
> * Updated the package.json file.
> 
> The following actions were performed as part of this PR:
> 
> * Ran `pnpm prettier-check` with no issues found.
> * Executed the `pnpm check-examples` script.

@samcx I recall you mentioned in my previous [PR](https://github.com/vercel/next.js/pull/69960) that I should add you as a reviewer directly instead of tagging you in the description. However, I don’t have the necessary permissions to do so. Could you assist with adjusting the access rights or advise me on how to add reviewers?

**Comment by samcx** [comment]
> However, I don’t have the necessary permissions to do so. Could you assist with adjusting the access rights or advise me on how to add reviewers?

Oh interesting, I didn't know that was the case. In that case, feel free to CC me instead.

**Review by samcx — APPROVED** [review]

**Comment by samcx** [comment]
@Sam-Phillemon9493 Thank you for submitting a PR!

Only thing I changed to be up-to-date is the `tsconfig.json` file (copied from `create-next-app@canary`).

**Pull request merged**
