### PR TITLE
Add new example for Adeira SX Design

### PR DESCRIPTION
**Pull request by mrtnzlml**
This PR adds a new minimal example for Adeira [SX Design](https://github.com/adeira/sx-design). It showcases basic components as well as automatic dark mode styles:

Screen Shot 2021-08-14 at 21 06 24

See: https://github.com/adeira/sx-design

## Documentation / Examples

- [x] Make sure the linting passes

### CODE REVIEW

**Comment by mrtnzlml** [comment]
I rebased the changes on top of `canary` and fixed some CI issues.

**Comment by mrtnzlml** [comment]
Hola @ijjk! 👋 I see you already approved the CI runs once but there was an issue and I had to fix it (which dismissed your approval). Could you please have a look again? Thanks! 😎

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Hi @mrtnzlml, could you make sure this PR aligns with our [examples guidelines](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)?

If you don't pursue getting this merged anymore, that is also understandable, let's close it for now then! Thanks for the work either way! :pray: :green_heart:

**Comment by balazsorban44** [comment]
I'll close this for now, but if you want to work on it, please feel free to reopen it at any time! Thank you!

**Pull request closed without merging**
