### PR TITLE
Example/app dir sentry

### PR DESCRIPTION
**Pull request by mayank1513**
### Adding Sentry App Directory Example

- The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

### What?
Added Sentry app directory example.

### Why?
To demonstrate how to use Sentry with Next.js app directory.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d28d0ec08015d8d2333f27335ec9c4fcc2036f6e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by mayank1513** [comment]
Some tests are expected to fail for Sentry examples

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Instead of adding a separate example, let's update the existing one here: https://github.com/vercel/next.js/tree/canary/examples/with-sentry

The `pnpm-lock.yaml` changes should be reverted too.

**Comment by mayank1513** [comment]
> Instead of adding a separate example, let's update the existing one here: https://github.com/vercel/next.js/tree/canary/examples/with-sentry
> 
> The `pnpm-lock.yaml` changes should be reverted too.

Thanks for the comment. Are you sure you don't want to keep example with pages router?

**Comment by balazsorban44** [comment]
It can co-exist, as Next.js supports having both the Pages and App Router in the same app.

**Comment by leerob** [comment]
Have you tested all of these are working with Sentry?

**Comment by mayank1513** [comment]
Hey, thanks for the comment. I had tested the sentry example in a separate example for app-dir. It worked well. However, I have merged the 2 examples as requested @balazsorban44

> It can co-exist, as Next.js supports having both the Pages and App Router in the same app.

I was not able to mark this PR as draft.

It fails when you visit any path rendered by app-dir and come back to path rendered by pages directory. Linked Issue - https://github.com/getsentry/sentry-javascript/issues/8180#issuecomment-1719376022

**Pull request closed without merging**
