### PR TITLE
Fix issues with apollo cache data merging and restoration

### PR DESCRIPTION
**Pull request by matthewlilley**
This PR fixes issues in two apollo examples where cached queries are lost, and cached data is merged incorrectly.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.5s | -51ms |
| nodeModulesSize | 63.2 MB | 63.2 MB | -10 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.283 | 2.295 | ⚠️ +0.01 |
| / avg req/sec | 1094.98 | 1089.48 | ⚠️ -5.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.203 | 1.242 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2077.35 | 2012.29 | ⚠️ -65.06 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e5f5aee..31e1.js gzip | 7.17 kB | 7.17 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ff4dea7..dule.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 996 B | 996 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.2s | -461ms |
| nodeModulesSize | 63.2 MB | 63.2 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e5f5aee..31e1.js gzip | 7.17 kB | 7.17 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ff4dea7..dule.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _error.js | 1.05 MB | 1.05 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.05 MB | 1.05 MB | ✓ |
| link.js | 1.1 MB | 1.1 MB | ✓ |
| routerDirect.js | 1.09 MB | 1.09 MB | ✓ |
| withRouter.js | 1.09 MB | 1.09 MB | ✓ |
| Overall change | 5.4 MB | 5.4 MB | ✓ |

</details>

</details>
Commit: af576963c33341a21e0c98f04e2e500c321168db

**Review by HaNdTriX — DISMISSED** [review]

**Review by Timer — DISMISSED** [review]
Thanks!

**Review by Timer — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| buildDuration | 14s | 14.4s | ⚠️ +410ms |
| nodeModulesSize | 87 MB | 87 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.629 | 2.55 | -0.08 |
| / avg req/sec | 951.06 | 980.45 | +29.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.418 | 1.439 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1762.76 | 1737.61 | ⚠️ -25.15 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-5b72373..17dd.js gzip | 7.37 kB | 7.37 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-2d01f96..dule.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 996 B | 996 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| buildDuration | 16.6s | 16.1s | -465ms |
| nodeModulesSize | 87 MB | 87 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-5b72373..17dd.js gzip | 7.37 kB | 7.37 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-2d01f96..dule.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | matthewlilley/next.js apollo-fixes | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.49 MB | 5.49 MB | ✓ |

</details>

</details>
Commit: c249524c80b88bdf633ed3e1f975330c209e0240

**Comment by shufflemattdev** [comment]
@matthewlilley thank you for this I am still trying to wrap my head around how the merging works with Apollo cache and how it interacts with SSG so this was very helpful . One thing I am having issues with is data with nested arrays of objects - by default deepmerge concatenates the two arrays on merge.  So for a simple example..

```javascript
const initialState = {
  id: 123,
  articles: [{ id: 1 }, { id: 2 }]
};
const existingCache = { id: 456, articles: [{ id: 1 }, { id: 2 }] };
```
When performing this merge using deepmerge... 

```javascript
merge(initialState, existingCache)
```
Results in this ... 

```javascript 
{
  id: 456,
  articles: [{ id: 1 }, { id: 2 }, { id: 1 }, { id: 2 }],
};
```
So when transitioning client side pages with next/link, I am getting duplicate values in my arrays each transition. So if I started with 10 in my initial array, when I transition back and forth between data fetching pages on the client it would add 10 duplicates each transition. I am investigating using the [overwriteMerge ](https://www.npmjs.com/package/deepmerge#arraymerge-example-overwrite-target-array) setting of deepmerge like so : 
```javascript
  const data = merge(initialState, existingCache, {
      arrayMerge: overwriteMerge,
    });
```

It seems to solve it, but I am still testing to see if this would cause any issues with Apollo cache etc. I can report back here with more of my findings, once I use this a bit more

**Comment by lfades** [comment]
@shufflemattdev Feel free to open a PR once you're done 🙏

**Comment by matthewlilley** [comment]
> @shufflemattdev Feel free to open a PR once you're done 🙏

I'm pretty sure I did a couple of months ago :)

**Comment by matthewlilley** [comment]
> @matthewlilley thank you for this I am still trying to wrap my head around how the merging works with Apollo cache and how it interacts with SSG so this was very helpful . One thing I am having issues with is data with nested arrays of objects - by default deepmerge concatenates the two arrays on merge. So for a simple example..
> 
> ```js
> const initialState = {
>   id: 123,
>   articles: [{ id: 1 }, { id: 2 }]
> };
> const existingCache = { id: 456, articles: [{ id: 1 }, { id: 2 }] };
> ```
> 
> When performing this merge using deepmerge...
> 
> ```js
> merge(initialState, existingCache)
> ```
> 
> Results in this ...
> 
> ```js
> {
>   id: 456,
>   articles: [{ id: 1 }, { id: 2 }, { id: 1 }, { id: 2 }],
> };
> ```
> 
> So when transitioning client side pages with next/link, I am getting duplicate values in my arrays each transition. So if I started with 10 in my initial array, when I transition back and forth between data fetching pages on the client it would add 10 duplicates each transition. I am investigating using the [overwriteMerge ](https://www.npmjs.com/package/deepmerge#arraymerge-example-overwrite-target-array) setting of deepmerge like so :
> 
> ```js
> const overwriteMerge = (destinationArray, sourceArray, options) => sourceArray;
> 
>   const data = merge(initialState, existingCache, {
>       arrayMerge: overwriteMerge,
>     });
> ```
> 
> It seems to solve it, but I am still testing to see if this would cause any issues with Apollo cache etc. I can report back here with more of my findings, once I use this a bit more

No problem, took me a while to figure out what was happening. I used lodash merge because I'm familiar with that and it works perfectly fine, but I think there was some reservations about including it here.

**Comment by yousefcisco** [comment]
We found an issue with this PR because it changed the order of properties as they merge. Previously it was merging `initialState` into `existingCache`, overwriting any data that exists in both from the latest version in `initialState`. This PR changed that behaviour so it was merging `existingCache` into `initialState` meaning that any duplicate items would be overridden with stale data from `existingCache` and not the latest data coming from `getServerSideProps` or `getStatisProps`.

I'm going to submit a PR to swap the order, please let me know if you see any issues with this solution.
```
const data = merge(existingCache, initialState ...
```

**Pull request merged**
