### PR TITLE
Fix: Use `boolean` instead of `false` for experimental logging config

### PR DESCRIPTION
**Pull request by Fredkiss3**
This PR changes the type for the config `experimental.logging.fullURL` from `false` to `boolean`, i tested it and this config can accept both true and false and will work as expected, it is just the types that are wrong.

### CODE REVIEW

**Review by huozhi — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d9e6f01566609be9f14eb8a94c3a115aad48c16c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d9e6f01566609be9f14eb8a94c3a115aad48c16c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d9e6f01566609be9f14eb8a94c3a115aad48c16c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
