### PR TITLE
Update reactStrictMode.mdx enabled since 13.5.1

### LINKED ISSUE #70559: Docs:  reactStrictMode.mdx enabled since 13.5.1 not 13.4
### What is the documentation issue?

Spent over 2 hours checking why with 13.4.19 components didn't mount twice as the docs says "Good to know: Since Next.js 13.4, Strict Mode is true by default with app router".

But it's enabled by default in [13.5.1](https://github.com/vercel/next.js/releases/tag/v13.5.1).

Version [13.5.0](https://github.com/vercel/next.js/releases/tag/v13.5.0) has no changelog?

Maybe reactStrictMode it's enabled by default since 13.5.0 instead 13.5.1 ?

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode

### PR DESCRIPTION
**Pull request by Luk-z**
Spent over 2 hours checking why with 13.4.19 components didn't mount twice as the docs says "Good to know: Since Next.js 13.4, Strict Mode is true by default with app router".

But it's enabled by default in [13.5.1](https://github.com/vercel/next.js/releases/tag/v13.5.1).

Version [13.5.0](https://github.com/vercel/next.js/releases/tag/v13.5.0) has no changelog? 

Maybe reactStrictMode it's enabled by default since 13.5.0 instead 13.5.1 ?

Fixes: https://github.com/vercel/next.js/issues/70559

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5903ed3ddc74b0ce680101d65013e98452fdd6dd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5903ed3ddc74b0ce680101d65013e98452fdd6dd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Luk-z** [comment]
fix 70559

**Review by ijjk — APPROVED** [review]
Good catch, thanks!

**Pull request merged**
