### PR TITLE
Add page transitions example

### PR DESCRIPTION
**Pull request by OutThisLife**
Based on issue #88, showing a way to do it

### CODE REVIEW

**Comment by mattfysh** [comment]
Does this animate the entire viewable area, or does it leave things like header/footer/nav/etc in place?

**Comment by OutThisLife** [comment]
Just the `#container` element. So header, footer, anything outside of it will stay put unless you wanted to animate those too leveraging the `.loading` class.

**Review by timneutkens — APPROVED** [review]
This is extremely cool, thanks @OutThisLife ❤️

**Comment by frol** [comment]
@OutThisLife Thank you for the complete and working example!

@timneutkens I am really sorry, yet I am a bit taken aback that this became a part of the official examples list given that the built-in Next.js routing system is thrown away...

**Comment by nickrobillard** [comment]
Considering the state of #88, I decided to go this route in order to achieve a soundcloud like continuous audio playing feature. This solution is less than ideal, but I really like Next.js and I've more or less accomplished what I needed.

However, when I test a prod build (`next build` and `next start`), server generated sub-pages return 404. This is easily reproducible with this example.

**Steps to reproduce:**

1. Follow installation instructions here - https://github.com/zeit/next.js/tree/v3-beta/examples/page-transitions
2. Run commands `next build` followed by `next start`
3. Navigate to either `/about` or `/contact`
4. Refresh page and observe 404

I haven't done a deep dive into what `next build` is actually doing. Any ideas what the problem is?

**Comment by nickrobillard** [comment]
Ok this is my bad. I should have been using `npm run start` or `yarn start` to start the prod server. Issue resolved.

**Pull request merged**
