### PR TITLE
improve getStaticProps error message

### LINKED ISSUE #34025: Inaccurate error message when getStaticProps exported from page without a page component
### Run `next info` (available from version 12.0.8 and up)

```
/bin/sh: 1: pnpm: not found

    Operating System:
      Platform: linux
      Arch: x64
      Version: #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.6
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.11-canary.6

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next dev

### Describe the Bug

When you have a page file which has a `getStaticProps` function exported, but no default export for a page component:
```js
export const getStaticProps = async (context) => ({
    redirect: {
        destination: "https://example.com",
        permanent: false
    }
});
```
You get this server error:
> Error: page /pageName getStaticProps can not be attached to a page's component and must be exported from the page. See more info here: https://nextjs.org/docs/messages/gssp-component-member

Even though the `getStaticProps` is correctly exported from the page.

### Expected Behavior

Ideally having no page component export would be allowed and not cause an error (it's useful in cases where you'd only ever return a redirect or an error), but if this isn't supported the error message should say something like
> Error: page /pageName does not have a default export page component. If the page won't ever render, export a function that returns null.

### To Reproduce

1. Create a page that has a getStaticProps function but no default page component export, like the example in the "describe the bug" section
2. Run `next dev`
3. Navigate to the page in your browser

### PR DESCRIPTION
**Pull request by stmtk1**
## Bug

- [x] fixes #34025

## I checked
- [x] run test `should show error for getStaticProps as component member`
- [x] run test `should show error for getServerSideProps as component member`
- [x] run test `should show error for getStaticPaths as component member`
- [x] run `yarn build`
- [x] run `yarn lint`
 
## Changes that must be reviewed
- [ ] could you check other related tests. I don't know which are other related tests.

## Documentation / Examples
- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, I don't think we want to tweak the error message here as this is meant to only show when `Component.getStaticProps` is used. 

It seems this error is incorrectly showing because we fallback to treating the entire module as the component when `module.default` doesn't exist related handling:
https://github.com/vercel/next.js/blob/8a5e1ceb866ad36ec628635d67ca49eb4045c971/packages/next/lib/interop-default.ts#L2

It might be good to move [this check](https://github.com/vercel/next.js/blob/8a5e1ceb866ad36ec628635d67ca49eb4045c971/packages/next/server/render.tsx#L409-L419) after [the component check](https://github.com/vercel/next.js/blob/8a5e1ceb866ad36ec628635d67ca49eb4045c971/packages/next/server/render.tsx#L600-L604) instead to ensure the correct error message is shown and add a new test case for this.

**Comment by stmtk1** [comment]
@ijjk So I have to do is
- revert previous commit
- add conditional branch when there is no default export.

is it OK?

**Comment by ijjk** [comment]
@stmtk1 Yeah reverting the commits and then moving [this block of code](https://github.com/vercel/next.js/blob/8a5e1ceb866ad36ec628635d67ca49eb4045c971/packages/next/server/render.tsx#L552-L562) to [this line](https://github.com/vercel/next.js/blob/8a5e1ceb866ad36ec628635d67ca49eb4045c971/packages/next/server/render.tsx#L605) and then adding a test for the no default export case sounds good 👍

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b11e93b22471452e894153c5b4e73cd5908cd1a8

`yarn testheadless test/development/watch-config-file/index.test.ts` 
- watch-config-file > should output config file change

<details>
<summary>Expand output</summary>

  ● watch-config-file › should output config file change

    TIMED OUT: /Found a change in next.config.js. Restart the server to see the changes in effect./

    yarn run v1.22.18
    $ node --trace-deprecation --enable-source-maps packages/next/dist/bin/next /tmp/next-install-1653254699359
    ready - started server on 0.0.0.0:39743, url: http://localhost:39743
    info  - Using locally built binary of @next/swc
    wait  - compiling...
    event - compiled client and server successfully in 2.1s (115 modules)

      498 |
      499 |   if (hardError) {
    > 500 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      501 |   }
      502 |   return false
      503 | }

      at Object.check (lib/next-test-utils.js:500:11)
      at Object.<anonymous> (development/watch-config-file/index.test.ts:44:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.8s | ⚠️ +89ms |
| buildDurationCached | 6.4s | 6.4s | ⚠️ +25ms |
| nodeModulesSize | 479 MB | 479 MB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.888 | 3.908 | ⚠️ +0.02 |
| / avg req/sec | 643.02 | 639.69 | ⚠️ -3.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.341 | 1.36 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1864.88 | 1838.51 | ⚠️ -26.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.2 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.65 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| buildDuration | 18.4s | 18.4s | -26ms |
| buildDurationCached | 6.4s | 6.4s | -57ms |
| nodeModulesSize | 479 MB | 479 MB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.932 | 3.887 | -0.04 |
| / avg req/sec | 635.82 | 643.1 | +7.28 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.346 | 1.355 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1857.4 | 1844.82 | ⚠️ -12.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.7 kB | 42.7 kB | ✓ |
| main-HASH.js gzip | 29.6 kB | 29.6 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 74 kB | 74 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.89 kB | 2.89 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.82 kB | 5.82 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | stmtk1/next.js improve_error_message | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 327ae72ecd258449b03b431aa6b825b1338f7f28

**Review by ijjk — APPROVED** [review]

**Pull request merged**
