### PR TITLE
Fixes #66597: Update tailwind template installation logic

### LINKED ISSUE #66597: Tailwindcss "content" when using src directory
### Link to the code that reproduces this issue

https://github.com/yaviskokakola/next.js-tailwind

### To Reproduce

1. npx create-next-app@rc --empty --tailwind --typescript --app --src-dir

### Current vs. Expected behavior

Current:
```ts
import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx,mdx}"],
  theme: {},
  plugins: [],
};
export default config;
```
Expected:
```ts
import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx,mdx}"],
  theme: {},
  plugins: [],
};
export default config;
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)
  Available memory (MB): 15338
  Available CPU cores: 8
Binaries:
  Node: 22.2.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.2.0
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lain67**
### What?

updated the tailwindcss configuration file "content" replacing logic when using src directory

### Why?

previous logic caused the pattern to don't match

### How?

added logic updating updated urls according to the current mode

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2934c07f72c792a23fe68ecb0a07e10b36fe34b7

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@yaviskokakola Shouldn't we not assuming that they may not have a JS file as well when they're using TS?

**Comment by yaviskokakola** [comment]
> @yaviskokakola Shouldn't we not assuming that they may not have a JS file as well when they're using TS?

It was the only difference I saw between the rc and the stable version. Besides, I don't think anyone will ever used typescript inside the javascript project and javascript in the typescript project, and if they will, they could add it in the configuration file anytime. And thanks for your response

**Comment by samcx** [comment]
@yaviskokakola Noted. There are probably other minor things we should improve as well, such as not needing this line → https://github.com/vercel/next.js/blob/4539e33d9694c599a55950e160bbd7ea4fc7b6c3/packages/create-next-app/templates/app-tw/js/tailwind.config.js#L4

**Pull request closed without merging**
