### PR TITLE
Update .dockerignore

### PR DESCRIPTION
**Pull request by HoseinHabibiyan**
first line ignored Dockerfile

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
This seems correct already as it is valid to exclude the `Dockerfile` in `.dockerignore`. Related docker documentation here https://docs.docker.com/engine/reference/builder/#dockerignore-file specifically this note:

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

**Comment by raiiinyman** [comment]
> This seems correct already as it is valid to exclude the `Dockerfile` in `.dockerignore`. Related docker documentation here https://docs.docker.com/engine/reference/builder/#dockerignore-file specifically this note:
> 
> > You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

But putting the Dockerfile in the dockergnore is not necessary at all and still ignored the dockerfile and forces me to change it ...

**Comment by ijjk** [comment]
> But putting the Dockerfile in the dockergnore is not necessary at all and still ignored the dockerfile and forces me to change it

Are you saying the docker documentation linked is incorrect and the `Dockerfile` is not being picked up/built by the daemon unless you change this line?

**Comment by raiiinyman** [comment]
> > But putting the Dockerfile in the dockergnore is not necessary at all and still ignored the dockerfile and forces me to change it
> 
> Are you saying the docker documentation linked is incorrect and the `Dockerfile` is not being picked up/built by the daemon unless you change this line?

In my experience this happened and I really had this problem
There is no reason at all When supposed to Daemon is going to pickup. Let's put this line in Docker Ignore again.

**Pull request closed without merging**
