### PR TITLE
[WIP] Webpack 4

### PR DESCRIPTION
**Pull request by timneutkens**
**Don't merge**

Lets try to get next/router to function properly first before moving on to adding chunks etc.

Code that doesn't use `next/link` / `next/router` runs fine.

### CODE REVIEW

**Comment by timneutkens** [comment]
Added a vendor chunk, holding react-dom and react + next.js specific files like the router, also in dev. But it didn't solve the singleton router issue.

**Comment by rashidul0405** [comment]
@timneutkens for vendor chunks, can we expose a settings override - may be an entry on `next.config.js`? sensible defaults with override feature?

**Comment by timneutkens** [comment]
@rashidul0405 I don't understand what you're asking 🤔. You can just use the `webpack` function to extend the webpack config.

**Comment by rashidul0405** [comment]
@timneutkens Talking about this one: https://github.com/facebook/create-react-app/issues/2206. In order to achieve this, we will need to override whole [`splitChunks`](https://github.com/zeit/next.js/pull/4108/files#diff-0f2f34c098f5954f99483c9bd61e439d) settings?

**Comment by rashidul0405** [comment]
just ability to pass which modules should end up into `vendor.js` chunk.

**Comment by rashidul0405** [comment]
@timneutkens please ignore my comments, I was checking server bundles and commented based on that. client side bundles are fine for now (all node_modules to main.js).

**Pull request closed without merging**
