### PR TITLE
feat: custom public env prefix

### PR DESCRIPTION
**Pull request by Netail**
> [!NOTE]  
> This is a proposal, wondering what you guys think about this idea

### What?

Set custom public env variable prefix

### Why?

Sometimes the prefix `NEXT_PUBLIC_` can be a little confusing, so a way to set a custom prefix could help improving DX?

Idea from https://github.com/vercel/next.js/discussions/66458, also kind of related to https://github.com/vercel/next.js/discussions/56093

### How?

Experimental option for a custom prefix

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c7ecd50d9235758f404eafca87724e450b41e54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by kachkaev** [comment]
There may be npm libraries who expect public vars prefixed as `NEXT_PUBLIC_`. If an app is configured with different prefix, these libraries won't work correctly. Even though `NEXT_PUBLIC_` is somewhat verbose, it’s not confusing because it’s the same for everyone. Customisation can bring more confusion and complexity IMHO.

**Comment by Netail** [comment]
> There may be npm libraries who expect public vars prefixed as `NEXT_PUBLIC_`. If an app is configured with different prefix, these libraries won't work correctly. Even though `NEXT_PUBLIC_` is somewhat verbose, it’s not confusing because it’s the same for everyone. Customisation can bring more confusion and complexity IMHO.

What about allowing multiple prefixes?

**Comment by igo** [comment]
Confusion begins when you ship your app built on top of Next.js, and users have no idea what `NEXT_PUBLIC_` is. For that reason, there should be a way to rename it to something like `MYAPP_PUBLIC_`. Libraries that rely on hardcoded NEXT_PUBLIC_ will have to be updated. Indeed, this can be a breaking change, but that should not stop us from merging it.

**Pull request closed without merging**
