### PR TITLE
[don't merge] next on preact

### PR DESCRIPTION
**Pull request by matthewmueller**
**DON'T MERGE**

This is an implementation of Next.js using preact (the 3kb version, no preact-compat).

It should give an idea of the scope involved in making Next.js work with different frameworks. I think to make this work and still support React, we'd need access to the webpack config (coming soon) + a separate preact client-side bundle.

Missing from this build is the glamor stuff and react-hot-loader state stuff (HMR still works though).

### CODE REVIEW

**Comment by rauchg** [comment]
If you look at the Roadmap  (https://github.com/zeit/next.js/wiki/Roadmap), we'll be moving Glamor into userland, by shipping custom `<Document />` support (#251), so don't worry about that.

It would be cool to make sure `styled-jsx` works on Preact out of the box tho. cc @developit

**Comment by developit** [comment]
I'm on it! :)

**Comment by developit** [comment]
Confirmed, it works fine :)

Source: https://github.com/developit/preact-styled-jsx-demo
Demo: https://preact-styled-jsx-demo.now.sh/

**Comment by rauchg** [comment]
Example added :) Let's aim for only needing to add the compat modules to webpack in `next.config.js` :)

**Pull request closed without merging**
