### PR TITLE
Add `--use-bun` to `create-next-app`

### PR DESCRIPTION
**Pull request by colinhacks**
This adds support for `--use-bun` to `create-next-app` to use `bun install` when bootstrapping a new project.

```
npx create-next-app --use-bun
```

As with Yarn and pnpm, it reads from `npm_config_user_agent` to determine if the user ran `bunx create-next-app`. If so, it defaults to using Bun.

```sh
bunx create-next-app
```

### Improving Documentation

- [x] Run `pnpm prettier-fix`
- [x] `pnpm build && pnpm lint` 
- [x] Added test to `test/integration/create-next-app/package-manager.test.ts`

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 3e088e97d5a51daf1906e7e67db97b6dd717679f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Duplicate of https://github.com/vercel/next.js/pull/44581. I can close that one out if we want to continue here.

**Comment by colinhacks** [comment]
> Duplicate of #44581. I can close that one out if we want to continue here.

Ah, sorry about that. We can go with this PR - it adds tests for inferring Bun based on `npm_config_user_agent` and will save you handling the merge conflicts on the other PR 👍 Thanks Lee!

**Review by leerob — APPROVED** [review]
If tests pass, LGTM!

**Review by styfle — APPROVED** [review]
LGTM, thanks!

**Review by ztanner — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 60ae49dc7ea3dc5d08c1e4c03553481f1271fd14

`pnpm testheadless test/e2e/app-dir/app-static/app-static-custom-handler.test.ts` 
- app-dir static/dynamic handling > should correctly include headers instance in cache key

<details>
<summary>Expand output</summary>

  ● app-dir static/dynamic handling › should correctly include headers instance in cache key

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not ""

      57 |       const data1 = $('#page-data').text()
      58 |       const data2 = $('#page-data2').text()
    > 59 |       expect(data1).not.toBe(data2)
         |                         ^
      60 |
      61 |       expect(data1).toBeTruthy()
      62 |       expect(data2).toBeTruthy()

      at Object.<anonymous> (e2e/app-dir/app-static/app-static.test.ts:59:25)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Pull request merged**
