### PR TITLE
Fix Example with-firebase-hosting-and-typescript

### PR DESCRIPTION
**Pull request by fnwiya**
Try to deploy this example, I have https://github.com/zeit/next.js/issues/5912 .

ref: https://github.com/zeit/next.js/pull/6331

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.4s | -82ms |
| nodeModulesSize | 52.6 MB | 52.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.13 kB | 5.13 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e781.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.13 kB | 4.13 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _app.js gzip | 1.15 kB | 1.15 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.68 kB | 9.68 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _app.module.js gzip | 576 B | 576 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.22 kB | 7.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| index.html gzip | 1.03 kB | 1.03 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 3.11 kB | 3.11 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.1s | -28ms |
| nodeModulesSize | 52.6 MB | 52.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.13 kB | 5.13 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e781.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.13 kB | 4.13 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _app.js gzip | 1.15 kB | 1.15 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.68 kB | 9.68 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _app.module.js gzip | 576 B | 576 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.22 kB | 7.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | fnwiya/next.js fix-example-with-firebase-hosting-and-typescript | Change |
| - | - | - | - |
| _error.js gzip | 46.6 kB | 46.6 kB | ✓ |
| 404.html gzip | 1.45 kB | 1.45 kB | ✓ |
| hooks.html gzip | 1.08 kB | 1.08 kB | ✓ |
| index.js gzip | 46.7 kB | 46.7 kB | ✓ |
| link.js gzip | 72.6 kB | 72.6 kB | ✓ |
| routerDirect.js gzip | 70.8 kB | 70.8 kB | ✓ |
| withRouter.js gzip | 70.6 kB | 70.6 kB | ✓ |
| Overall change | 310 kB | 310 kB | ✓ |

</details>

</details>


Commit: 92ca46644ae916598e9bdbc5f34769c69aac0dfd

**Comment by lfades** [comment]
@afuggini @oBusk Can you review this change 🙏

**Comment by oBusk** [comment]
While the change I suggested back then still looks sensible, there has been more changes to the example since I've looked at it, and `npm run deploy` won't work for me, with or without this change.

There's seems to be linting added but the code is not following that linting... but even after fixing that slight lint-issue. I'm getting;

```
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at findPagesDir (C:\Users\oBusk\Desktop\temp\with-firebase-hosting-and-typescript-app\dist\functions\node_modules\next\dist\lib\find-pages-dir.js:3:170)
    at new DevServer (C:\Users\oBusk\Desktop\temp\with-firebase-hosting-and-typescript-app\dist\functions\node_modules\next\dist\server\next-dev-server.js:1:3748)
    at Object.createServer [as default] (C:\Users\oBusk\Desktop\temp\with-firebase-hosting-and-typescript-app\dist\functions\node_modules\next\dist\server\next.js:2:105)
    at Object.<anonymous> (C:\Users\oBusk\Desktop\temp\with-firebase-hosting-and-typescript-app\dist\functions\index.js:16:27)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

Getting same issue both with `master` and this PR

@fnwiya Is this the only change needed for your `npm run deploy` to go through?

**Comment by Timer** [comment]
Closing as another user confirmed this does not fix the example for them.
Thanks for the PR!

**Comment by rainy-me** [comment]
I just encountered this issue and had to run with the environment value`NODE_ENV=production firebase deploy`. Both this PR and the merged fix in `with-firebase-hosting`( #6331) can fix #5912

**Pull request closed without merging**
