### PR TITLE
Downgrade `strip-ansi` to 3.0.1

### PR DESCRIPTION
**Pull request by jwillem**
See: https://github.com/facebookincubator/create-react-app/pull/2692

### CODE REVIEW

**Comment by jwillem** [comment]
solves #2747 at least for now.

**Review by timneutkens — APPROVED** [review]
Thanks! We talked about it in the issue. Seems alright to merge this for now.

**Comment by jwillem** [comment]
thx :)

**Comment by jwillem** [comment]
As the `next` step follows a further release and version bump, right?.  How long would it take to release this fix?

**Comment by timneutkens** [comment]
@arunoda has to do a release 👌

**Comment by oliviertassinari** [comment]
@jwillem Happy to see this fix :).

**Pull request merged**
