### PR TITLE
Remove with-global-stylesheet example

### LINKED ISSUE #4902: Canary: with-global-stylesheet does not work with the latest canary version
# Examples bug report
[with-global-stylesheet](https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheet)

## Example name
with-global-stylesheet

## Describe the bug
When you try to open the page you will get this
```
./styles/index.scss
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/emit-file-loader.js):
TypeError: Cannot read property 'context' of undefined
```
## To Reproduce
Just try to run the project after installing the latest Canary version.

## Screenshots
screen shot 2018-08-06 at 1 58 35 pm

## System information
 - OS: macOS
 - Version of Next.js: [6.1.1-canary.4]

### PR DESCRIPTION
**Pull request by HaNdTriX**
Use [@zeit/next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css) instead.

* [Example](https://github.com/zeit/next.js/tree/canary/examples/with-next-css)
* [Documentation](https://github.com/zeit/next-plugins/tree/master/packages/next-css)

CLOSE: #4902

### CODE REVIEW

**Comment by HaNdTriX** [comment]
Should we remove [examples/with-global-stylesheet-simple](https://github.com/zeit/next.js/tree/canary/examples/with-global-stylesheet-simple) as well?

**Comment by timneutkens** [comment]
@HaNdTriX yes we should! Let's keep the folder and add a readme linking to the alternative though. As issues might be linking to the example.

**Comment by HaNdTriX** [comment]
Good point! Done.

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Awesome thank you!

**Pull request merged**
