### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Boby900**
that extra period was creating confusion and I was adding two periods which was throwing an error.

Screenshot (456)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e051dc45eee8a6a01d0c5b19e7f1095dea89afd8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e051dc45eee8a6a01d0c5b19e7f1095dea89afd8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e051dc45eee8a6a01d0c5b19e7f1095dea89afd8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Boby900 I think this is fine because it's outside the code snippet (there's a period after for the line below as well).

**Pull request closed without merging**
