### PR TITLE
Docs: Update server actions link to point at server actions page

### PR DESCRIPTION
**Pull request by srkirkland**
In the authentication section, React's "Server Actions" are mentioned and linked to server-components.  I think that's wrong and the link was intended to go to the "Server Actions and Mutations" page.  This fixes the issue.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: eb80e89a1e5b4e9f6aceef4264dbfb6131768015

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: eb80e89a1e5b4e9f6aceef4264dbfb6131768015

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: eb80e89a1e5b4e9f6aceef4264dbfb6131768015

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR! Looks good to me.

**Pull request merged**
