### PR TITLE
Check for the user's home directory in the build output

### PR DESCRIPTION
**Pull request by Timer**
This pull request should fail on all builds.

### CODE REVIEW

**Comment by Timer** [comment]
If this pull request fails as expected it'll be merged into https://github.com/zeit/next.js/pull/6659.

**Review by ijjk — DISMISSED** [review]
LGTM

**Comment by Timer** [comment]
CircleCI:
```
  ● Production Usage › With Security Related Issues › should not leak the user's home directory into the build

    Found the user's home directory in: /pages/about.js

      54 |         const content = readFileSync(join(readPath, buildFile), 'utf8')
      55 |         if (content.includes(homeDir)) {
    > 56 |           throw new Error(`Found the user's home directory in: ${buildFile}`)
         |                 ^
      57 |         }
      58 |       })
      59 |     })
```

**Comment by Timer** [comment]
Travis:
```
  ● Production Usage › With Security Related Issues › should not leak the user's home directory into the build
    Found the user's home directory in: /pages/about.js
      54 |         const content = readFileSync(join(readPath, buildFile), 'utf8')
      55 |         if (content.includes(homeDir)) {
    > 56 |           throw new Error(`Found the user's home directory in: ${buildFile}`)
         |                 ^
      57 |         }
      58 |       })
      59 |     })
```

Just need this to work on Azure now!

**Comment by Timer** [comment]
OK, all tests are failing -- if I merge with `canary` now that https://github.com/zeit/next.js/pull/6659 has landed, tests should pass.

**Review by ijjk — APPROVED** [review]

**Pull request merged**
