### PR TITLE
#1757 Relay Modern Example

### PR DESCRIPTION
**Pull request by petrvlcek**
I've taken a working solution of SSR with Relay Modern from @steida [(contributed here)](https://github.com/zeit/next.js/issues/1757#issuecomment-318819465) and compiled it into more lightweight example.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Very nice!

**Comment by steida** [comment]
It's should probably have been merged to master, no?

**Comment by petrvlcek** [comment]
Hi, @timneutkens, since 3.0 has been officialy released, this PR would probably belong to `master` branch. I'm not sure what is going to happen with `v3-beta` branch but I gues it is obsolete now.

**Comment by timneutkens** [comment]
Definitely should be added to master, I'll merge it whenever I find the time 👍 Or you could create a new PR and i'll merge it 😄 ❤️

**Comment by petrvlcek** [comment]
@timneutkens OK, a new PR is here: #2773 👍

**Pull request merged**
