### PR TITLE
add google-signin example

### PR DESCRIPTION
**Pull request by MaxAst**
I was working on adding Googe Sign-In to a SaaS application I'm building with next.js, so I thought I'd share it here. This PR includes three different strategies you can do with Google Sign In. Hope people will find this useful!

Happy Easter 🐰

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.9s | ⚠️ +553ms |
| nodeModulesSize | 61 MB | 61 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e3d8.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.78 kB | 6.78 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.5 kB | 51.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| index.html gzip | 917 B | 917 B | ✓ |
| link.html gzip | 926 B | 926 B | ✓ |
| withRouter.html gzip | 915 B | 915 B | ✓ |
| Overall change | 2.76 kB | 2.76 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.6s | -285ms |
| nodeModulesSize | 61 MB | 61 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e3d8.js gzip | 10.2 kB | 10.2 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.3 kB | 56.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.78 kB | 6.78 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.5 kB | 51.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | MaxAst/next.js google-signin | Change |
| - | - | - | - |
| _error.js gzip | 233 kB | 233 kB | -1 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 956 B | 956 B | ✓ |
| index.js gzip | 233 kB | 233 kB | ✓ |
| link.js gzip | 243 kB | 243 kB | ⚠️ +353 B |
| routerDirect.js gzip | 241 kB | 241 kB | ⚠️ +63 B |
| withRouter.js gzip | 241 kB | 241 kB | -45 B |
| Overall change | 1.19 MB | 1.19 MB | ⚠️ +370 B |

</details>

</details>

**Comment by waptik** [comment]
> I was working on adding Googe Sign-In to a SaaS application I'm building with next.js, so I thought I'd share it here. This PR includes three different strategies you can do with Google Sign In. Hope people will find this useful!
> 
> Happy Easter

Thanks for this example and I hope it gets merge.
Can you please add a demo link in the readme file? It'll be great to see it in action before playing with it.
Thanks

**Comment by MaxAst** [comment]
> > I was working on adding Googe Sign-In to a SaaS application I'm building with next.js, so I thought I'd share it here. This PR includes three different strategies you can do with Google Sign In. Hope people will find this useful!
> > Happy Easter
> 
> Thanks for this example and I hope it gets merge.
> Can you please add a demo link in the readme file? It'll be great to see it in action before playing with it.
> Thanks

there's instructions in the README for how to set up an example. You need to provide config from one of your own projects in the Google Developer Console.

**Comment by MaxAst** [comment]
@Timer @lfades thoughts on this?

**Comment by lfades** [comment]
Hi @MaxAst sorry for the late review, this looks like quite a big PR, overall I like it, specially the first method, could we choose only one to remove the complexity of the example? I'm not sure about what are the use case differences between the 3 but we have to choose the most secure one and remove the others, wdyt?

**Comment by lfades** [comment]
@MaxAst Passport is a very good option, you could use our current [Passport example](https://github.com/zeit/next.js/tree/canary/examples/with-passport) and add [passport-google-oauth2](https://github.com/jaredhanson/passport-google-oauth2).

**Comment by MaxAst** [comment]
@lfades okay sounds good, I'll get to it this week! The idea was to have an example that doesn't rely on passportjs because it feels like passportjs is more at home in a monolithic expressjs setup than a nextjs serverless one. I'm gonna reduce the example to the third strategy because I think it's the one that adds the most value (allowing devs to make server-side Google API requests on behalf of the user)

**Comment by lfades** [comment]
@MaxAst I'm 100% okay with adding one or both. Make sure that whatever you do is very secure, reliable and ideally easy to understand (it's an example at the end of the day). Our passport example uses a secure and encrypted cookie, if you need to set a cookie check the implementation there 👍

**Comment by lfades** [comment]
Hi there @MaxAst Do you have any update on the status of the example?

**Comment by MaxAst** [comment]
Hi @lfades, sorry for the late reply! I've actually moved my own project to firebase auth and find it a lot easier and better than this approach here, so I'm just going to close this

**Pull request closed without merging**
