### PR TITLE
Update 01-vitest.mdx to include module path auto-configuration

### PR DESCRIPTION
**Pull request by i0n-**
Modules are part of core of nextJs, so I updated the Vitest documentation file to work with modules by just copy the sample provided here.

And save time as usual ;-)

Changes based on [Vitest official documentation](https://vitest.dev/guide/common-errors#cannot-find-module-relative-path)

### CODE REVIEW

**Comment by samcx** [comment]
@i0n- To clarify, this is true even if you don't have a `tsconfig.json` in your <picture data-single-emoji=":nextjs:" title=":nextjs:">:nextjs:</picture> project?

**Comment by i0n-** [comment]
@samcx  will work without failure, but will fail to found modules that use the prefix (like `@`) because the file `tsconfig.json` to define it is not there.

**Comment by samcx** [comment]
@i0n- Would that not be the expected behavior (e.g., you should not use path prefixes without a `tsconfig.json`)?

**Comment by i0n-** [comment]
@samcx Right, but it works because vitest is capable to work without the `tsconfig.json` file.

**Comment by samcx** [comment]
@i0n- I don't believe this should be added then, as our example is more so a minimal example that doesn't take into consideration of other options, such as using a path prefix. We do have a link to the Vitest docs, so that should suffice!

**Comment by i0n-** [comment]
0k, I was feel that the intention of nextJs is a productive solution out-of-the-box and the documentation too, then I waste some time to figure it how make the `vitest` to work as the rest of the framework  handling the user created modules.

**Pull request closed without merging**
