### PR TITLE
Update Docker examples to support Bun runtime

### PR DESCRIPTION
**Pull request by maxproske**
Updates the Docker examples to:
- Support the [Bun](https://bun.sh/) runtime, based on the detection of the `bun.lockb` file.
- Use the [App Router](https://nextjs.org/docs/app) and TypeScript.
- Support multiple envs (I am planning to deprecate the `with-docker-multi-env` example in a separate PR as it's unnecessary now and uses the non-standard Makefile).
- Unify changes from recent PRs across all Dockerfiles (musl libc fix, prerender cache permissions fix, etc.).

### Steps to test `with-docker` example with Bun:

1. `cd examples/with-docker`
1. Run `bun install` to generate bun lockfile.
1. Run `docker build -t nextjs-docker .`
1. Run `docker run -p 3000:3000 nextjs-docker`
1. Visit http://localhost:3000

### Steps to test `with-docker-compose` example with Bun:

1. `cd examples/with-docker-compose`
1. Run `bun install` to generate bun lockfile.
1. Run `docker compose -f docker-compose.dev.yml up`
1. Visit http://localhost:3000
1. Edit `index.tsx`, Hot Reloading works
1. Run `docker compose -f docker-compose.prod-without-multistage.yml up`
1. Visit http://localhost:3000
1. Run `docker compose -f docker-compose.prod.yml up`
1. Visit http://localhost:3000

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 47d4687a9e0cfeec868862778e4db2bece025fec

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 47d4687a9e0cfeec868862778e4db2bece025fec

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by maxproske** [comment]
Removed hostname, as per https://github.com/vercel/next.js/pull/55450#pullrequestreview-1633152791

**Review by leerob — COMMENTED** [review]
Looking good, thank you!

**Comment by maxproske** [comment]
Hey @leerob I saw you reviewed but might've missed hitting approve. Could you please take another look? Thanks!

**Comment by kalicki** [comment]
Hey @maxproske, how did you build with bun? I'm getting an error that seems to be common

image

Ref: https://github.com/oven-sh/bun/issues/4795

**Comment by maxproske** [comment]
@leerob Looks like this was approved. Hopefully I'm not creating extra pressure by asking when this PR will be merged.

**Comment by shahryarjb** [comment]
Is there any option to support nextjs 14 app directory? @maxproske

**Comment by leerob** [comment]
Hey @maxproske, sorry we didn't get to this faster. There are now quite a few merge conflicts that must be addressed before this could be merged. I cannot push to your fork. If you are still interested in contributing here, could you please open a new PR and reference this after you've addressed the conflicts? Thank you 🙏

**Pull request closed without merging**
