### PR TITLE
docs: correct TypeScript spelling on the home page

### PR DESCRIPTION
**Pull request by matepapp**
### What?
Changing the word TypeScript with an uppercase S.

### Why?
- Because that's the official recommendation from TypeScript. (Reference: [typescriptlang.org](https://www.typescriptlang.org))
- The docs already uses this format (e.g. [TypeScript page](https://nextjs.org/docs/app/building-your-application/configuring/typescript)) so it's just a matter of consistency.

### CODE REVIEW

**Review by manovotny — APPROVED** [review]

**Comment by manovotny** [comment]
Thanks @matepapp! 🙏

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: eaf6fb2442a6692ab7b271eb05965fe9580eb60b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by matepapp** [comment]
sorry @ijjk, I wasn't aware of this requirement

**Comment by manovotny** [comment]
@matepapp nothing to apologize about here. It's an automated message for me as a maintainer. You've done your part. 😊

**Pull request merged**
