### PR TITLE
docs: Update Route Handlers AI example code snippet

### PR DESCRIPTION
**Pull request by dominiksipowicz**
changing AI example model from `text-davinci-003` to `gpt-3.5-turbo` which is in a `chat/route.ts` format.

The alternative but with "completition" style would be a bit longer code like:

```
// app/api/completion/route.ts

import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, StreamingTextResponse } from 'ai'

export const runtime = 'edge'

const apiConfig = new Configuration({
  apiKey: process.env.OPENAI_API_KEY!,
})

const openai = new OpenAIApi(apiConfig)

function buildPrompt(prompt: string) {
  return prompt.split('\n').map((message) => ({
    role: 'user',
    content: message,
  }));
}

export async function POST(req: Request) {
  
  // Extract the `prompt` from the body of the request
  const { prompt } = await req.json();

  // Request the OpenAI API for the response based on the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: buildPrompt(prompt),
    max_tokens: 500,
    temperature: 0.7,
    top_p: 1,
    frequency_penalty: 1,
    presence_penalty: 1,
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)

  // Respond with the stream
  return new StreamingTextResponse(stream)
}

```

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: dc07b6cbfadd3f727b98cbea91d421a36fd3b6a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: dc07b6cbfadd3f727b98cbea91d421a36fd3b6a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: dc07b6cbfadd3f727b98cbea91d421a36fd3b6a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by leerob — COMMENTED** [review]
Could we synchronize the changes here as well?

https://sdk.vercel.ai/docs/getting-started#create-an-api-route 🙏

**Comment by masterkain** [comment]
I'm testing out the library a bit but I can't find `messages` in `createChatCompletion`, there is `prompt`

**Review by leerob — DISMISSED** [review]

**Review by ijjk — APPROVED** [review]

**Pull request merged**
