### PR TITLE
Disabling /_next/webpack/ prefix in production

### PR DESCRIPTION
**Pull request by glemiere**
Fix for https://github.com/zeit/next.js/issues/1926

### CODE REVIEW

**Comment by glemiere** [comment]
Any idea why the tests are failing ?

**Comment by arunoda** [comment]
This PR is incorrect. We need `${assetPrefix}/_next/webpack/` to have in both production and dev.

**Comment by arunoda** [comment]
And the `assetPrefix` is the place all the assets should lives in Next.js and it should prefix with `_next`. That's a design decision.

**Comment by arunoda** [comment]
But I assume there's another way to solve the original problem you had.

**Comment by glemiere** [comment]
Sure! I’ll look into this when I have more time ;)

**Pull request closed without merging**
