### PR TITLE
Make hostname in `next start` match hostname the server is listening on

### PR DESCRIPTION
**Pull request by Tenzer**
This is only a problem when using the default value for the hostname, as that
will make the server output `> Ready on http://localhost:3000` to the console
while the server actually is listening on all IPv4 and IPv6 addresses, as
that's the default for the Node.js HTTP server when no hostname is provided.

### CODE REVIEW

**Comment by iamstarkov** [comment]
I don't understand why is this needed

**Comment by Tenzer** [comment]
It's in order to make the output of the `next start` command match what it's actually doing.

If I start a server with the default options, I get this output:
```
$ next start
> Ready on http://localhost:3000
```

So, based on that I would expect the server to be listening on `localhost:3000`, or `127.0.0.1:3000`, but when I check with netstat it actually listens on all IP addresses, not just localhost:
```
$ netstat -an | grep .3000
tcp46      0      0  *.3000                 *.*                    LISTEN
```

If I however specify 'localhost' as the hostname to listen on, like this:
```
$ next start --hostname localhost
> Ready on http://localhost:3000
```

then the server correctly listens on the localhost IP address, 127.0.0.1:
```
$ netstat -an | grep .3000
tcp4       0      0  127.0.0.1.3000         *.*                    LISTEN
```

This PR changes the default listen address so it matches what the command outputs.

**Comment by iamstarkov** [comment]
@timneutkens should it be closed then?

**Comment by timneutkens** [comment]
Yeah let's close this PR.

Thanks for taking the time to create a PR though 🙏 🙌

**Pull request closed without merging**
