### PR TITLE
 Add `cms-umbraco` example

### PR DESCRIPTION
**Pull request by kjac**
This PR adds a sample blog powered by [Umbraco CMS](https://umbraco.com/products/umbraco-cms/). 

Umbraco CMS v12 ([released June 29](https://our.umbraco.com/download/releases/1200)) adds headless capabilities directly to the Umbraco core. This PR showcases how a blog can be built using Umbraco CMS as backing content source.

This example is not to be mistaken with the [Umbraco Heartcore](https://github.com/vercel/next.js/tree/canary/examples/cms-umbraco-heartcore) example. Umbraco Heartcore is a SaaS platform built on top of Umbraco CMS.

A demo of this example can be found at https://nextjs-umbraco-sample-blog.vercel.app/.

- [x] The "examples guidelines" are followed from the contributing docs (see https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)
- [x] The linting passes (running `pnpm build && pnpm lint`, see https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md)

### CODE REVIEW

**Comment by kjac** [comment]
Hi @ijjk,

Is there anything I can do to ease the review of this PR? If it helps anything I can setup an Umbraco site with a publicly available API for testing.

**Comment by nul800sebastiaan** [comment]
For what it's worth, I've tried this one out and it works as expected (disclaimer: I work with Kenn, but didn't get any help from him, I'm not even a frontend developer so this was all new to me!).

**Comment by kjac** [comment]
I'm really sorry to be poking you out of the blue here, @balazsorban44, but this example PR has been waiting more than two months with apparently only automated responses.

The Umbraco community is looking forward to playing around with this one.  I can see you've been merging other examples as of late... maybe you could point me in the direction of whom to ask for help in getting this one merged?

**Review by leerob — COMMENTED** [review]
This is looking good! Could we have it use the App Router + Draft Mode, similar to the updated `cms-wordpress` example? 🙏

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 798c238a5420aae6580a8d12f8d9c81f9764d3e6

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 798c238a5420aae6580a8d12f8d9c81f9764d3e6

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 798c238a5420aae6580a8d12f8d9c81f9764d3e6

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by kjac** [comment]
Hi @leerob,

I can't entirely figure out what it is you'd like me to update 🙈 the example does use draft mode, though. And it is essentially a copy of the `cms-wordpress` example. Or, at least that was the intent 😄 

I did spot a few missing TypeScript rewrites in the preview API handling, so I have fixed those now. And I also did a re-linting to keep the example up-to-date with the current style preferences.

Please let me know if you need me to do further updates to this 👍

**Comment by hjaltedaniel-umbraco** [comment]
Hi Vercel/Next.js team (ping @leerob)
What's the status on this one? Been talking to quite a few customers that could be customers of both front-end hosting from Vercel and CMS hosting from Umbraco, who'd be interested in seeing this PR merged in.

**Comment by leerob** [comment]
CleanShot 2024-08-15 at 11 59 07@2x

**Comment by leerob** [comment]
Following up - do you want to address the lint errors so we can get this merged?

**Comment by kjac** [comment]
Hi @leerob 👋 thanks for following up. I'll have a look at fixing the linter errors this week - hopefully one of the next few days.

**Comment by kjac** [comment]
@leerob should be good to go now 👍

**Comment by leerob** [comment]
CleanShot 2024-08-28 at 14 26 56@2x
Could you run the check-examples script as well? CI is still red

**Comment by kjac** [comment]
@leerob aha! Looks like the link in `next-env.d.ts` was out of date (ref #68534).

I've updated the link now.

**Pull request merged**
