### PR TITLE
Link tags must be added manually for amp pages

### PR DESCRIPTION
**Pull request by c0b41**
So right now nextjs adding multiple link tags also blocking #6568

### CODE REVIEW

**Comment by Timer** [comment]
Why do these tags need to be added manually?

**Comment by Timer** [comment]
I believe your train of thought here is that users need to add these attributes because a page may not be AMP ready.

However, https://github.com/zeit/next.js/issues/6568 will make these fields be optionally injected depending on if the page is an AMP page or not.

If this isn't the case, please let me know and we can discuss it more!

**Comment by c0b41** [comment]
@Timer sorry for the delay.

Some reasons

- Cannocial tag and amphtml tag not support full or custome server path, only using router pathname 

- Custome cannocial amd amphtml tag not working correctly, nextjs adding extra tag.

- Sending all pages to amp search crawler, i think this bad idea, must be manualy or wait the #6568 feature

**Comment by Timer** [comment]
Let's please wait until #6558, I'll tag you in it so we can talk about this again!

**Pull request closed without merging**
