### PR TITLE
fix pageKey and compiling output for on-demand-entries

### PR DESCRIPTION
**Pull request by sokra**
shows `compiling /_error...` instead of `compiling /next/dist/pages/_error...`

### CODE REVIEW

**Review by ijjk — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: fcd9bccab13e84bac02e04ae4e68a2721084c6f6

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should recover from 404 after a page has been added
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover from 404 after a page has been added

    expect(received).toContain(expected) // indexOf

    Expected substring: "compiling /_error..."
    Received string:    "wait  - compiling...
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    wait  - compiling...
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    wait  - compiling /hmr/new-page...
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    wait  - compiling...
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    wait  - compiling...
    warn  - ./components/hmr/dynamic.js
    Anonymous arrow functions cause Fast Refresh to not preserve local component state.
    Please add a name to your function, for example:·
    Before
    export default () => <div />;·
    After
    const Named = () => <div />;
    export default Named;·
    A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
    "

      330 |           'compiling /hmr/new-page...'
      331 |         )
    > 332 |         expect(next.cliOutput.slice(start)).toContain('compiling /_error...')
          |                                             ^
      333 |       } catch (err) {
      334 |         await next.deleteFile(newPage)
      335 |         throw err

      at Object.<anonymous> (development/basic/hmr.test.ts:332:45)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      618 |         await next.patchFile(aboutPage, aboutContent)
      619 |
    > 620 |         if (browser) {
          |                       ^
      621 |           await check(
      622 |             () => getBrowserBodyText(browser),
      623 |             /This is the about page/

      at Object.<anonymous> (development/basic/hmr.test.ts:620:23)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.6s | -138ms |
| buildDurationCached | 3.3s | 3.3s | -65ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.367 | 3.315 | -0.05 |
| / avg req/sec | 742.41 | 754.13 | +11.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.571 | 1.587 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1591.19 | 1575.29 | ⚠️ -15.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 7s | 7.2s | ⚠️ +125ms |
| buildDurationCached | 3.2s | 3.3s | ⚠️ +97ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.338 | 3.35 | ⚠️ +0.01 |
| / avg req/sec | 748.94 | 746.2 | ⚠️ -2.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.533 | 1.552 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1631.25 | 1610.37 | ⚠️ -20.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 066ca44180660153516c52e1fff4d8d0a4e31356

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 16.2s | 15.9s | -229ms |
| buildDurationCached | 3.7s | 3.7s | ⚠️ +37ms |
| nodeModulesSize | 195 MB | 195 MB | -11 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.916 | 3.779 | -0.14 |
| / avg req/sec | 638.34 | 661.54 | +23.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.031 | 2.053 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1231.05 | 1217.59 | ⚠️ -13.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 7.6s | 7.7s | ⚠️ +53ms |
| buildDurationCached | 3.5s | 3.5s | -2ms |
| nodeModulesSize | 195 MB | 195 MB | -11 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.799 | 3.869 | ⚠️ +0.07 |
| / avg req/sec | 658.09 | 646.22 | ⚠️ -11.87 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.963 | 2.117 | ⚠️ +0.15 |
| /error-in-render avg req/sec | 1273.31 | 1180.65 | ⚠️ -92.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 1703c2abb00bfd7e7f6c5d20acb2f7225f068f45

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1703c2abb00bfd7e7f6c5d20acb2f7225f068f45

**test/e2e/basepath.test.ts** 
- basePath > should navigate to nested index page with getStaticProps

<details>
<summary>Expand output</summary>

  ● basePath › should navigate to nested index page with getStaticProps

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#prop"
    ============================================================

      201 |     return this.chain(() => {
      202 |       return page
    > 203 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      204 |         .then(async (el) => {
      205 |           // it seems selenium waits longer and tests rely on this behavior
      206 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:203:10

</details>

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 14.9s | 14.7s | -166ms |
| buildDurationCached | 3.5s | 3.4s | -73ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +305 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.788 | 3.665 | -0.12 |
| / avg req/sec | 659.9 | 682.16 | +22.26 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.964 | 1.955 | -0.01 |
| /error-in-render avg req/sec | 1272.63 | 1279.06 | +6.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-a993820..123b.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 530 B | 530 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| buildDuration | 6.9s | 7.1s | ⚠️ +209ms |
| buildDurationCached | 3s | 3.1s | ⚠️ +75ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +305 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.43 | 3.704 | ⚠️ +0.27 |
| / avg req/sec | 728.76 | 674.87 | ⚠️ -53.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.88 | 1.925 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1330.01 | 1299.03 | ⚠️ -30.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-17a5f65..3805.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-e04a..a1b5.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| _buildManifest.js gzip | 477 B | 477 B | ✓ |
| Overall change | 477 B | 477 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js bugfix/correct-page-key | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 777a81a458304e67ed823b5fc0e7435d54082170

**Pull request merged**
