### PR TITLE
docs: Remove superfluous <PagesOnly> tags in api-reference/components/link.mdx

### PR DESCRIPTION
**Pull request by zhuyedev**
Within the document [docs/02-app/02-api-reference/01-components/link.mdx](https://github.com/zhuyedev/next.js/blob/canary/docs/02-app/02-api-reference/01-components/link.mdx#L327), there is an unnecessary set of `<PagesOnly>` tags, which prevents a few sections from being displayed correctly.This issue particularly affects the section starting with "### If the child is a custom component that wraps an <a> tag" (in line 327) and ending just before "### Middleware" (in line 458).

### CODE REVIEW

**Review by kampitojha — CHANGES_REQUESTED** [review]
## Custom Components and `<Link />`

When using the `<Link />` component with a custom component that wraps an `<a>` tag, ensure that the behavior aligns with your expectations. Below is an example:

```jsx
<AppOnly>
  <!-- Your custom component content here -->
</AppOnly>

// The default behavior of `Link` is to scroll to the top of the page.
<Link href="/some-page">
  <!-- Link content here -->
</Link>
`


Middleware is commonly employed for tasks such as authentication or user redirection to different pages. When using Middleware and <Link /> together, it's important to consider prefetching links to avoid unnecessary fetches. Provide both the display URL and the prefetch URL to Next.js, as demonstrated below:


// Middleware Usage Example
import Link from 'next/link';

// In your component
<Link href="/some-page" as="/custom-route" prefetch>
  <!-- Link content here -->
</Link>
``

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8f8d5e3f0633b9d169236fccf95841d6f9326955

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8f8d5e3f0633b9d169236fccf95841d6f9326955

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Pull request merged**
