### PR TITLE
updates styled-jsx to fix issues and bugs

### PR DESCRIPTION
**Pull request by khrome83**
upgrades styled-jsx version to resolve pseudo issue caused by styled-jsx

### CODE REVIEW

**Comment by sedubois** [comment]
I wonder why greenkeeper doesn't take care of this?

**Comment by khrome83** [comment]
@sedubois - what is greenkeeper?

**Comment by pungggi** [comment]
https://greenkeeper.io

**Comment by timneutkens** [comment]
@sedubois cause it only runs on your default branch (v3-beta in this case).

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
@khrome83 thank you *very much* for this. @arunoda we should do a new patch release.

**Comment by arunoda** [comment]
Published: `2.4.4`.

**Comment by timneutkens** [comment]
Thaaaaaanks!

**Pull request merged**
