### PR TITLE
Normalize trailing slash

### LINKED ISSUE #5214: trailing slash in link for legit page works for client side navigation but leads to not found bundle and 404 on hard refresh (ssr)
trailing slash in link for legit page works for client side navigation but leads to not found bundle and 404 on hard refresh (ssr)

# Bug report

## Describe the bug

let me know if title needs further clarification.

[all relevant issues](https://github.com/zeit/next.js/issues?q=is%3Aissue+trailing+slash+is%3Aclosed) has been closed with reasoning that its been fixed in 6-canary (I believe it is not) or by improved serve (which is true only in perhaps production static export).

I'm rewriting my existing blog to next.js and i previously used trailing slashes. Latest `serve` can help with it once i build my next.js powered blog. But in order to fix dev env i need either to get rid of trailing slashes and utilize `301 Moved Permanently` in prod; or live with broken trailing slash support in dev.

## To Reproduce

Here is minimal reproducible case (link to repro repo is below snippet):

```js
// pages/index.js
import Link from "next/link";

export default () => (
  <Link href="/about/">
    <a>About</a>
  </Link>
);

// pages/index.js
export default () => "about";
```

Minimal reproducible repo https://github.com/iamstarkov/next.js-trailing-slash-bug-demo

1. clone repo  `git clone https://github.com/iamstarkov/next.js-trailing-slash-bug-demo`
1. change directory `cd next.js-trailing-slash-bug-demo`
1. install deps `yarn`
1. run dev: `yarn dev`
1. open http://localhost:3000/
1. open devtools' network tab
1. observe `http://localhost:3000/_next/static/development/pages/about.js` being 200ed
1. observe `http://localhost:3000/_next/on-demand-entries-ping?page=/about/` being 200ed
1. observe `http://localhost:3000/about/` being 404ed
1. observe persistent attempts to resolve `http://localhost:3000/about/`
1. observe in the terminal `Client pings, but there's no entry for page: /about/`
1. refresh the page
1. observe 404 page.
1. remove trailing slash in the url or click http://localhost:3000/about 
1. observe page being 200ed
1. to ensure error persistence repeat steps 5-15 once.

## Expected behavior

1. `/about/` shouldnt be resolved as `404 not found`
1. `/about/` should be resolved as `200 ok`
1. Server should not print `Client pings, but there's no entry for page: /about/`
1. both `/about` and `/about/` should work the same way

## Screenshots
N/A

## System information
 - OS: macOS High Sierra 10.13.6 (17G65)
 - Browser (should not matter, but can repro'ed in chrome 69.0.3497.100 and safari Version 12.0 (13606.2.11) (was the same for safari 11)
 - Version of Next.js: 7.0.0 (could repro on 5.x and 6.x)

## Additional context

If you change this code in https://github.com/zeit/next.js/blob/459c1c13d054b37442126889077b7056269eeb35/server/on-demand-entry-handler.js#L242-L249

or `node_modules/next/dist/server/on-demand-entry-handler.js` locally

```diff
          const { query } = parse(req.url, true)
          const page = normalizePage(query.page)
+         console.log('query.page', query.page);
+         console.log('page', page);
+         console.log('Object.keys(entries)', Object.keys(entries));
          const entryInfo = entries[page]

          // If there's no entry.
          // Then it seems like an weird issue.
          if (!entryInfo) {
            const message = `Client pings, but there's no entry for page: ${page}`
```

and restart `next dev` and open http://localhost:3000/ and click about link then:
* for `/about`
  ```
  query.page /about
  page /about
  Object.keys(entries) [ '/', '/about' ]
  ```
* for `/about/`:
  ```
  query.page /about/
  page /about/
  Object.keys(entries) [ '/', '/about' ]
  Client pings, but there's no entry for page: /about/
  ```

I think the problem (at least part of it) is in inability of onDemandEntryHandler's middleware to find page in entries if page has trailing slash.

I hope my 2 hours of investigation and preparation can help with fixing this issue.

### LINKED ISSUE #6277: Sub-directory index page route hangs, emits no response
# Bug report
Hi!

I'm evaluating Next.js for potential use with some e-commerce sites. While it's easy to set up and looks pretty nice, there's this completely basic yet crazy thing that's happening when I run the "getting started" example with a small alteration -- a subdirectory route with an index.js file in it.

## Describe the bug

Create a subdirectory within `pages` folder, let's call it `subdir`. Put an `index.js` file in it (with a page component). Navigate to `http://host/subdir/` with a **trailing slash** at the end of the URL. There is no response from the server, the connection just hangs (until some timeout)! Other routes like `http://host`, `http://host/`, and `http://host/subdir` work fine. Happens with both Next.js 7 and 8.

Here's a repo that shows the setup, but it's really just that -- `pages/subdir/index.js` file.

https://github.com/atis--/nextjs-subdir-index-bug

## System information
 - OS: Ubuntu 14.04
 - Browser: chrome, firefox, curl, anything
 - Version of Next.js: 7.0.2, 8.0.0

### PR DESCRIPTION
**Pull request by Janpot**
fix https://github.com/zeit/next.js/issues/5214
fix https://github.com/zeit/next.js/issues/6277

linking to urls with trailing slashes works on the client-side. Directly navigating to them resulted in errors though. Both in production and dev mode. removing the trailing slash in a few places fixes the issue.

I had to change some tests since the error behavior serverside was "expected" according to the tests, the client side wasn't covered by tests. For now I changed the behavior to tolerate trailing slashes and basically treat them the same as trailing `/index`. I added a test to cover client-side and updated the serverside tests.
Alternatively the behavior could be restricted (although one could ask the question to restrict the `/index` case as well). in that case the serverside tests need to be reverted and the client test needs to be changed to return an error instead. Though IMO, the way I implemented it now makes most sense and is most consistent.

### CODE REVIEW

**Comment by Janpot** [comment]
Flakey test?

**Comment by Janpot** [comment]
🤔  I should probably add a production test here as well, just like the `/index/index.js` PR.

**Comment by timneutkens** [comment]
@Janpot yeah definitely, however I still think this needs to be discussed more, it's technically a breaking change to allow it I think 🤔

**Comment by timneutkens** [comment]
@Janpot btw sorry for hijacking the PR branch update, I wanted to see if the new github action works 💯

**Comment by Janpot** [comment]
IMO, the only scenario where this really is a breaking change is when you were relying on client and server behaving differently.

**Comment by Janpot** [comment]
@timneutkens Added production tests. Didn't have to change any test in production. So I guess the only "breaking change" here is in development mode, on the server side. Not super breaking I'd say.

**Comment by timneutkens** [comment]
This also solves #619 right?

**Comment by Janpot** [comment]
I wasn't aware of that issue. I guess at least part of it is solved. [This](https://github.com/zeit/next.js/issues/619#issuecomment-270854528) is the intended behavior?

**Comment by timneutkens** [comment]
Nah I think this behavior is fine, no need to make it more complex 👍

**Comment by Janpot** [comment]
@timneutkens Just as a check, I went ahead and encoded the proposed behavior of https://github.com/zeit/next.js/issues/619#issuecomment-270854528 in some tests. These are my findings:

1. several failures were fixed in this PR in a sense that now most of these links resolve to something instead of erroring out.
2. client-side behavior: all cases seem to resolve to something. one case, where both `./folder.js` and `./folder/index.js` exist seems to always favor `./folder.js`, even when linking to `/folder/index`.
3. server-side there are still two cases that error out and thus are inconsistent with the client.

I'd say, the most important thing is to make client and server behavior consistent, even if it differs from node resolution. Although parity with node resolution would be quite nice as well.

**Comment by Janpot** [comment]
Added the same tests for production.

development:
```
    page resolution
      client side
        ✓ should resolve to js file when no slash (2021ms)
        ✕ should resolve to folder index when slash (1014ms)
        ✕ should resolve to folder index when index (950ms)
        ✓ should resolve to folder when no slash and no js file (1488ms)
        ✓ should resolve to folder index when slash and no js file (999ms)
        ✓ should resolve to folder index when index and no js file (1011ms)
      server side 
        ✓ should resolve to js file when no slash (890ms)
        ✕ should resolve folder index when slash (857ms)
        ✕ should resolve folder index when index (945ms)
        ✓ should resolve to js file when no slash and no js file (770ms)
        ✓ should resolve to js file when slash and no js file (801ms)
        ✓ should resolve folder index when index and no js file (871ms)
```
production:
```
    page resolution
      client side
        ✕ should resolve to js file when no slash (2551ms)
        ✓ should resolve to folder index when slash (839ms)
        ✓ should resolve to folder index when index (872ms)
        ✓ should resolve to folder when no slash and no js file (727ms)
        ✓ should resolve to folder index when slash and no js file (753ms)
        ✓ should resolve to folder index when index and no js file (732ms)
      server side 
        ✕ should resolve to js file when no slash (709ms)
        ✓ should resolve folder index when slash (691ms)
        ✓ should resolve folder index when index (731ms)
        ✓ should resolve to js file when no slash and no js file (652ms)
        ✓ should resolve to js file when slash and no js file (655ms)
        ✓ should resolve folder index when index and no js file (691ms)
```
So half of the production tests are in line with node resolution, and half of development tests are. Unfortunately it's different halves 😄.

**Comment by Janpot** [comment]
@dav-is FYI: I added these failing tests but haven't had time to figure out a fix for them yet. My time to work on this is very sparse so feel free to take a stab at it if you want. These last 12 tests I added are meant to replicate how node.js require works in the next page resolution. Each piece of functionality seems to works somewhere (dev/prod) but nowhere does it all work.

**Comment by timneutkens** [comment]
Probably good to note that

> Nah I think the behavior you implemented is fine, no need to make it more complex 👍

meant I didn't want to replicate Node.js require behavior.

**Comment by Janpot** [comment]
but it makes sense to define "some" behavior for these edge cases and make them consistent across server/client and development/production, right?

**Comment by timneutkens** [comment]
Yep!

**Comment by Janpot** [comment]
Ok, so I guess it's a matter of filling in the blanks then

```
/pages
  /subfolder.js
```

1. `/subfolder` => `/pages/subfolder.js`
2. `/subfolder/` => ?
3. `/subfolder/index` => ?

```
/pages
  /subfolder
    /index.js
  /subfolder.js
```

4. `/subfolder` => ?
5. `/subfolder/` => ?
6. `/subfolder/index` => ?

```
/pages
  /subfolder
    /index.js
```
7. `/subfolder` => `/pages/subfolder/index.js`
8. `/subfolder/` => `/pages/subfolder/index.js`
9. `/subfolder/index` => `/pages/subfolder/index.js`

**Comment by timneutkens** [comment]
So imo we should for "one or the other" and not allow both. Meaning:

`pages/index.js` => `/`
`pages/index/index.js` => `/`

But don't allow both to exist

`pages/about.js` => `/about` / `/about/`
`pages/about/index.js` => `/about` / `/about/`

But don't allow both to exist. Also don't allow `/about/index`.

Does that make sense?

**Comment by Janpot** [comment]
So what you say is that the
```
/pages
  /subfolder
    /index.js
  /subfolder.js
```
situation should throw a build error? That would eliminate 4. 5. and 6.
and then for 2. and 3.

2. `/subfolder/` => `/pages/subfolder.js`
3. `/subfolder/index` => `404`

That makes sense to me. But it's going to be a breaking change.

**Comment by Janpot** [comment]
[This is my proposal](https://github.com/zeit/next.js/pull/6421#issuecomment-472414075). Will close until there is any kind of consensus on what behavior is desired.

**Comment by ellej16** [comment]
@Janpot 's proposal sounds good enough. Are there any other concerns that blocks the merging of this feature / fix @timneutkens ?

We could include a `strict` prop to do the `one or the other` scenario, but still give the devs flexibility on which they want?

**Comment by kjs3** [comment]
Seems like this should be merged. Is there something specific holding this back? Is there a lack of support or consensus on this behavior?

**Comment by Janpot** [comment]
Ok, nevermind, this is too far behind.

**Pull request closed without merging**
