### PR TITLE
feat: add placeholder to next image as optional prop

### PR DESCRIPTION
**Pull request by smakosh**
## What's new?
- Added `placeholder` prop to Next image that is optional and will be rendered while the image is being loaded

## Example
Demo: https://next-image-unsplash.vercel.app/
Source: https://github.com/smakosh/next-image-unsplash

## Edge cases
I wasn't able to compute the width/height and keeping the ratio as it's done with Next image to the placeholder, looking forward on your feedback and suggestions to implement that

### CODE REVIEW

**Comment by timneutkens** [comment]
This change should go through a proper RFC, please write one first so that it can be discussed as it could potentially affect performance negatively by allowing this replacements.

**Comment by smakosh** [comment]
> This change should go through a proper RFC, please write one first so that it can be discussed as it could potentially affect performance negatively by allowing this replacements.

Sure @timneutkens can we keep it open and change the status until we hear back from the community?

**Comment by timneutkens** [comment]
With almost 200 open PRs I'd rather not to ensure what is open is actually being worked on / landed and needs a review.

**Comment by smakosh** [comment]
Got it, I started the discussion here: https://github.com/vercel/next.js/discussions/16832#discussioncomment-114326

**Pull request closed without merging**
