### PR TITLE
Update Ant Design with Less example

### PR DESCRIPTION
**Pull request by nezdemkovski**
Current `with-ant-design-less` example quite differs from `with-ant-design` so I made them look the same + updated `@zeit/next-less` plugin and removed `transform-decorators-legacy`.

### CODE REVIEW

**Comment by Enalmada** [comment]
@yakovlevyuri Hey, when I add a few more pages to the with-ant-design-less example I get this webpack error using latest next.js. Since you are making changes to the ant example I figured I would see if you have any idea?  I would like to get this sorted before any new users come along and hit a brick wall trying to extend the example:  

https://github.com/zeit/next.js/pull/5212

**Comment by yakovlevyuri** [comment]
@Enalmada hm, I've added few more pages and everything seems fine, no errors/warnings.
What OS/node version do you have?
I use macos 10.13.6, node 10.10.0

**Comment by Enalmada** [comment]
@yakovlevyuri Just to confirm...you have a few more pages each with different antd components not from the original page and clicking the pages all work fine?  OMG that is so unfair!  I am on Windows 10 with node 10.9 and also tried 10.11.0 with same issue.  I also tried WSL Ubuntu with node 10.10.0.   Kudos though...trying newer node was a good idea.  I will try macos now to rule that out.

If I remove the "import" plugin from .babelrc I no longer get the error but my browser file sizes are obviously massive without the modular import.  If I hit refresh after the error everything actually seems to work fine...I can click around.  It also seems like it might be a dev only issue...I tried build/start with NODE_ENV=production and can't get the error.

**Comment by Enalmada** [comment]
@yakovlevyuri Side note...I also noticed that the antd component colors are different in dev and production settings.   Does that happen to you too?
dev
image
prod
image

**Comment by Enalmada** [comment]
You are right that the problem is more than just any components on multiple pages...I don't get the issue at all with some components and I get it more frequently with others like calendar (List, Tooltip, Table also caused the crash consistently as I added them but it is unclear if it is the raw components or the interaction with stuff on the index page).  

@yakovlevyuri Could you humor me and try adding a page with a calendar and another page with a card exactly like my example?  Restart development mode from homepage and click the calendar link.

**Comment by yakovlevyuri** [comment]
@Enalmada I have a side project and I'm getting the same warnings/errors using `@zeit/next-css` as well. I'm going to have a deeper look into this on weekend.

**Review by HaNdTriX — CHANGES_REQUESTED** [review]

**Comment by Enalmada** [comment]
@yakovlevyuri Interesting...thanks for letting me know.  I was feeling crazy.  If you can figure out how to or who could help fix it the next.js/antd community is in your debt.  I tried my best but it is way over my head at the moment.  

A workaround might be to have a different .babelrc in dev (without the import) and build with it only.  In my more advanced example though on Next 7 I can't click on any link pointing to a page that imports less.  I can hit the page manually though so server side rendering of it works.  I am hoping the root cause is similar.  Something is funny with next 7 and less/css. :(

**Comment by timneutkens** [comment]
I'm going to close this as the PR is stale and has merge conflicts. Thank you very much for your contribution 🙏:pray:

**Pull request closed without merging**
