### PR TITLE
Update styled jsx

### PR DESCRIPTION
**Pull request by giuseppeg**
please check the yarn.lock file

### CODE REVIEW

**Comment by giuseppeg** [comment]
woops need to fix my fork :)

**Comment by arunoda** [comment]
Send this PR against master.

**Comment by giuseppeg** [comment]
Will do tomorrow, there are two bugs in Stylis (a dependency of styled-jsx) which should be fixed in the meantime, I'll then have to release 1.0.1.

Also before we merge you may probably want to think about watch mode and hot reloading. If I am not mistaken modules outside of `pages` don't trigger a rebuild right?

**Comment by timneutkens** [comment]
Closing this #2095 @giuseppeg could you create an issue for watching the external files.

**Pull request closed without merging**
