### PR TITLE
docs: Fix table rendering issue in Image component

### PR DESCRIPTION
**Pull request by ryo-manba**
### What?
Added a line break to fix the table display issue in the Image component documentation.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7c146370ef5f905d5ce93f1ac77024dbfde88202

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7c146370ef5f905d5ce93f1ac77024dbfde88202

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by mayank1513 — APPROVED** [review]
👌

**Comment by leerob** [comment]
Duplicate, this has been fixed now, thank you regardless 🙏

**Pull request closed without merging**
