### PR TITLE
fix: check if static file directory

### LINKED ISSUE #20408: Exception happened when export directory is named 'static'
# Bug report

## Describe the bug

Could not export output into a directory named `static`

## To Reproduce

Go to your nextjs project,  then `mkdir static` and `next build && next export -o static`

```
npm run build

> learn-starter@0.1.0 build /Users/minhuang/projects/giki/nextjs-blog
> next build && next export -o static

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Page                                                           Size     First Load JS
┌ ○ /                                                          10.4 kB        81.2 kB
├   └ css/66da66fb2c34490d64fa.css                             1.79 kB
├   /_app                                                      0 B            70.9 kB
├ ○ /404                                                       2.75 kB        73.6 kB
└ ○ /posts/first-post                                          1.63 kB        72.5 kB
+ First Load JS shared by all                                  70.9 kB
  ├ chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.bd1365.js  6.57 kB
  ├ chunks/commons.93a9e8.js                                   3.2 kB
  ├ chunks/fad5b6fe3657428a9611bc5c5609d8f456c75c77.5d8831.js  10.3 kB
  ├ chunks/framework.9ec1f7.js                                 39.9 kB
  ├ chunks/main.6fd8c3.js                                      6.23 kB
  ├ chunks/pages/_app.ca2459.js                                3.92 kB
  ├ chunks/webpack.e06743.js                                   751 B
  └ css/7ef9bd81cf95a32cd30e.css                               1.14 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

info  - using build directory: /Users/minhuang/projects/giki/nextjs-blog/build
info  - Copying "static" directory
[Error: ENAMETOOLONG: name too long, mkdir '/Users/minhuang/projects/giki/nextjs-blog/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static'] {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'mkdir',
  path: '/Users/minhuang/projects/giki/nextjs-blog/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! learn-starter@0.1.0 build: `next build && next export -o static`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the learn-starter@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/minhuang/.npm/_logs/2020-12-23T00_19_41_678Z-debug.log
```

## Expected behavior

All static files should be generated in `/static` directory.

## System information

```
$ uname -a
Darwin FVFXG11WHV2J 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by tarunama**
fixes #20408

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.9s | ⚠️ +69ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +10.9 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.055 | 2.152 | ⚠️ +0.1 |
| / avg req/sec | 1216.69 | 1161.93 | ⚠️ -54.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.409 | 1.482 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1773.97 | 1686.66 | ⚠️ -87.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 13.3s | 12.7s | -668ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +10.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 3a163c319a7df01de866df4fd7f38026272fc544

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.7s | ⚠️ +48ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +773 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.386 | 2.289 | -0.1 |
| / avg req/sec | 1047.66 | 1092 | +44.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.638 | 1.613 | -0.02 |
| /error-in-render avg req/sec | 1526.58 | 1549.87 | +23.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.8s | ⚠️ +142ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +773 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 8f2a54ae4072b314ada223e030703abb4a1624a9

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 9s | 9.1s | ⚠️ +86ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +773 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.756 | 1.779 | ⚠️ +0.02 |
| / avg req/sec | 1423.52 | 1405.36 | ⚠️ -18.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.108 | -0.07 |
| /error-in-render avg req/sec | 2118.94 | 2257.31 | +138.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.5s | -243ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +773 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-dba4ec1..27c0.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/avoid-duplicated-dir-name | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: f50d0e4f43c13b447ac6d2e74964beaa866dfd6c

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f50d0e4f43c13b447ac6d2e74964beaa866dfd6c

**test/integration/image-component/custom-resolver/test/index.test.js** 
- Custom Resolver Tests > Client-side Custom Loader Tests > Should use a custom resolver for image URL
- Custom Resolver Tests > Client-side Custom Loader Tests > should add a srcset based on the custom resolver
- Custom Resolver Tests > Client-side Custom Loader Tests > should support the unoptimized attribute

<details>
<summary>Expand output</summary>

  ● Custom Resolver Tests › Client-side Custom Loader Tests › Should use a custom resolver for image URL

    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=87.0.4280.88)

      14 | function runTests() {
      15 |   it('Should use a custom resolver for image URL', async () => {
    > 16 |     expect(await browser.elementById('basic-image').getAttribute('src')).toBe(
         |            ^
      17 |       'https://customresolver.com/foo.jpg?w~~1024,q~~60'
      18 |     )
      19 |   })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/image-component/custom-resolver/test/index.test.js:16:12)

  ● Custom Resolver Tests › Client-side Custom Loader Tests › should add a srcset based on the custom resolver

    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=87.0.4280.88)

      14 | function runTests() {
      15 |   it('Should use a custom resolver for image URL', async () => {
    > 16 |     expect(await browser.elementById('basic-image').getAttribute('src')).toBe(
         |            ^
      17 |       'https://customresolver.com/foo.jpg?w~~1024,q~~60'
      18 |     )
      19 |   })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/image-component/custom-resolver/test/index.test.js:16:12)

  ● Custom Resolver Tests › Client-side Custom Loader Tests › should support the unoptimized attribute

    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=87.0.4280.88)

      14 | function runTests() {
      15 |   it('Should use a custom resolver for image URL', async () => {
    > 16 |     expect(await browser.elementById('basic-image').getAttribute('src')).toBe(
         |            ^
      17 |       'https://customresolver.com/foo.jpg?w~~1024,q~~60'
      18 |     )
      19 |   })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/image-component/custom-resolver/test/index.test.js:16:12)

</details>

**Comment by timneutkens** [comment]
Opened a new PR here: https://github.com/vercel/next.js/pull/20969 as I realized last week that we already check for `public`, just not `static`.

Thanks for the PR @tarunama!

**Pull request closed without merging**
