### PR TITLE
feat: integration testing helper

### PR DESCRIPTION
**Pull request by bcoe**
## What is this?

Creates an integration testing helper that's exposed via `next/test/helper`. This is useful for upstream apps that would like to test next.js using an integration server.

_why?_ I'm OCD about unit-testing, and as far as I can tell existing tools like Enzyme don't work perfectly for next.js, since next.js' rendering helpers have quite a bit of magic (good magic, mind you):

```js
  const doc = createElement(Document, {
    __NEXT_DATA__: {
      component,
      errorComponent,
      props,
      pathname,
      query,
      err: (err && dev) ? errorToJSON(err) : null
    },
    dev,
    staticMarkup,
    ...docProps
  })
```

## The API

**async setup():**

Sets up the integration testing application.

`SKIP_BUILD=1` can be provided, to avoid building an application between test runs -- this can be useful when you're adding unit-tests to an existing codebase.

**async teardown():**

Cleanup the integration testing application.

**async render(path, query, req, res, opts):**

Helper for rendering application:

The order of arguments is different than `render`/`renderToHTML`, to better server the most common use-case:

`render('/some-path', {q: 'some params'})`

The `query-string` module is used to magically populate `req.url`.

### CODE REVIEW

**Comment by nkzawa** [comment]
👍   I wonder if this helper can be a different library.

**Comment by rauchg** [comment]
same

**Comment by bcoe** [comment]
@nkzawa if so, want to have dibs and create something in the zeit org?

**Comment by rauchg** [comment]
@bcoe done, check your notifications. Closing for now

**Comment by bcoe** [comment]
@rauchg awesome, I'll get a repo stubbed out tomorrow.

**Pull request closed without merging**
