### PR TITLE
Fix custom document compilation

### PR DESCRIPTION
**Pull request by nkzawa**
Fixes https://github.com/zeit/next.js/issues/521 #538

This PR change the compilation of `pages/_document.js` to use webpack.
It's a bit weird to use webpack for transpiling server codes, but so that we don't have to reimplement the followings:

- recursively detect dependencies.
- transpile files with babel
- watch files

### CODE REVIEW

**Comment by ryancole** [comment]
Might want to try using a `Link` from within `_document.js`. Not sure if it's my project itself, or using `Link` from with `_document.js` that is causing this issue. The issue is that `Link` used within `_document.js` causes a full page reload.

**Comment by rauchg** [comment]
We ought to make it clear in documentation that `_document` is not meant as a substitute for using layouts (through higher order components) in pages, which is a much neater solution (more explicit!)

**Comment by ericf** [comment]
I ran into an issue with this change when I tried to use `fs` inside `pages/_document.js`: https://github.com/zeit/next.js/issues/860#issuecomment-277859684

**Comment by odrzutowiec** [comment]
I found a solution/workaround here: https://github.com/zeit/next.js/issues/1091#issuecomment-279248065

**Comment by timneutkens** [comment]
The build error thing is solved in latest `next@canary`.

**Pull request merged**
