### PR TITLE
Replace server chunk handling in outputPath with chunkFilename

### LINKED ISSUE #29485: Plain with-webassembly example doesn't build
### What example does this report relate to?

with-webassembly

### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Immediately after bootstrapping the example with `create-next-app`, `yarn build` fails with the following error:

image

`yarn dev` still appears to work ok and the browser displays the correct number

### Expected Behavior

Next.js would build the example successfully

### To Reproduce

```shell
create-next-app --example with-webassembly with-webassembly-app
cd ./with-webassembly-app
yarn build
```

### PR DESCRIPTION
**Pull request by brhx**
Fixes #29485 #29362

### The problem

Using `chunks` in the `output.path` directory and then using `../` to recurse up a directory for ordinary files breaks `webassemblyModuleFilename`, as it outputs into the `chunks` directory but then looks for the webpack module at the root of `server`. This renders it unable to find the file.

### The fix

Use the `chunkFilename` to handle the `chunks` subdirectory instead, and replace the relative path handlers introduced with what they had before

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b417ded4f12464e70dfbd4b1899677963ad7618a

**test/e2e/prerender.test.ts** 
- Prerender > should output traces

<details>
<summary>Expand output</summary>

  ● Prerender › should output traces

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      1380 |               routeKeys: {
      1381 |                 lang: 'lang',
    > 1382 |               },
           |                 ^
      1383 |             },
      1384 |             {
      1385 |               namedDataRouteRegex: `^/_next/data/${escapeRegex(

      at Object.<anonymous> (e2e/prerender.test.ts:1382:24)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| buildDuration | 14.8s | 15s | ⚠️ +227ms |
| buildDurationCached | 3.8s | 3.7s | -50ms |
| nodeModulesSize | 183 MB | 183 MB | -739 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.33 | 3.259 | -0.07 |
| / avg req/sec | 750.74 | 767.08 | +16.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.552 | 1.586 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1610.72 | 1576.1 | ⚠️ -34.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 26.9 kB | 26.9 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.15 kB | 4.15 kB | ✓ |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 494 B | 494 B | ✓ |
| Overall change | 494 B | 494 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| buildDuration | 7.8s | 7.7s | -84ms |
| buildDurationCached | 3.9s | 3.7s | -145ms |
| nodeModulesSize | 183 MB | 183 MB | -739 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.165 | 3.261 | ⚠️ +0.1 |
| / avg req/sec | 789.96 | 766.61 | ⚠️ -23.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.471 | 1.552 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1699.07 | 1610.57 | ⚠️ -88.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| Overall change | 101 kB | 101 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | sam3d/next.js wasm-chunks-fix | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: b417ded4f12464e70dfbd4b1899677963ad7618a

**Comment by sam3d** [comment]
@sokra I believe you originally made the change for this in 445dba12b4e3fa063bb862aae1f4fefa8f4f466a, is it expected that the `webassemblyModuleFilename` will no longer pull from the real directory?

**Comment by sokra** [comment]
The ../ is a workaround for node-file-trace to only include files in the chunks directory.
There work towards improving that by moving node-file-trace into next.js, which would make that workaround unnecessary.
Maybe we can disable the workaround when the experimental flag is enabled? cc @ijjk

**Comment by sam3d** [comment]
@sokra or @ijjk is there anything I can do or help with to expedite this process?

**Comment by sam3d** [comment]
@ijjk considering that #43677 has been merged, is there anything further we can do here?

**Comment by sam3d** [comment]
Closing due to inactivity.

**Pull request closed without merging**
