### PR TITLE
fix: Respect TransitionOptions.scroll when replacing a hash

### PR DESCRIPTION
**Pull request by RobbyUitbeijerse**
In some scenarios it's nice to have the option to replace a hash in the url without enforcing a scroll. The TransitionsOptions already allow you to set the scroll option as false, but currently the `scrollToHash` method doesn't respect it.

[Related discussion #13804](https://github.com/vercel/next.js/discussions/13804)

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

### CODE REVIEW

**Comment by RobbyUitbeijerse** [comment]
Somehow, someway, the browser still enforces scrolling towards the hash even though it seems like it shouldn't do that (history.replaceState shouldn't trigger a forced scroll afaik), I'll try to resolve it but at this time don't have the slightest clue what's happening

**Comment by RobbyUitbeijerse** [comment]
> Somehow, someway, the browser still enforces scrolling towards the hash even though it seems like it shouldn't do that (history.replaceState shouldn't trigger a forced scroll afaik), I'll try to resolve it but at this time don't have the slightest clue what's happening

Nevermind, this was actually one of our other dependencies doing something similar, the change should actually work as expected.

**Review by dejanstrancar — APPROVED** [review]

**Comment by tjleing** [comment]
In our use case, we needed not only this change but also commenting out the `scrollToHash()` call in `componentDidUpdate()` in [`packages/next/client/index.tsx`](https://github.com/vercel/next.js/blob/fa01a1593e4ba56357c04bcb506e5e41b038d836/packages/next/client/index.tsx), as mentioned in [this discussion #13804](https://github.com/vercel/next.js/discussions/13804).

Use case: when scrolling past a heading, we wanted to update the URL to display the currently active section (without scrolling).  However, calling `router.replace()` was triggering both the `scrollToHash()` call in this change as well as the one in `componentDidUpdate()` -- this behavior could be typical or unique to our implementation.

Not sure if this change should also happen in this PR or even if it should happen at all, but I thought it would be important to know that this fix may not resolve all issues here.

**Comment by emadabdulrahim** [comment]
Look forward to this merging to be able to prevent scroll when URL hash change in some scenarios.

**Comment by cnrad** [comment]
hi i want this

**Pull request closed without merging**
