### PR TITLE
Fix file path overflowing in error popup

### LINKED ISSUE #27170: Error popup file path overflowing if very long
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next

### Describe the Bug

The error file path is very long and is overflowing.

Screenshot from 2021-07-05 14-29-42

### Expected Behavior

For the file path to break onto the new line without overflowing out of the box.

### To Reproduce

Create a deeply nested file and cause an error in it.

### PR DESCRIPTION
**Pull request by AkiraTsuboi**
## Bug

- [x] Related issues linked using `fixes #number`

fixes #27170

### Before
before

### After
after

### CODE REVIEW

**Review by timneutkens — DISMISSED** [review]
Could you make this scroll horizontally instead? That was it does not take up extra space

**Comment by AkiraTsuboi** [comment]
@timneutkens 
Thanks for checking.

> Could you make this scroll horizontally instead? That was it does not take up extra space

I fixed it.

### Before
before

### After
after

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| buildDuration | 11.9s | 12s | ⚠️ +95ms |
| buildDurationCached | 3.1s | 3.1s | -17ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +226 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.323 | 2.323 | ✓ |
| / avg req/sec | 1076.04 | 1076.18 | +0.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.25 | 1.239 | -0.01 |
| /error-in-render avg req/sec | 2000.33 | 2017.9 | +17.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| buildDuration | 9.8s | 9.8s | -27ms |
| buildDurationCached | 4.1s | 4.1s | -21ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +226 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.387 | 2.383 | 0 |
| / avg req/sec | 1047.14 | 1049.22 | +2.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.258 | 1.273 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1987.26 | 1964.21 | ⚠️ -23.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | AkiraTsuboi/next.js fix-file-path-overflowing | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 399da1c19319274b0868ae17169275e5a6a9aebe

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 399da1c19319274b0868ae17169275e5a6a9aebe

**test/integration/required-server-files/test/index.test.js** 
- Required Server Files > should output required-server-files manifest correctly
- Required Server Files > should render SSR page correctly
- Required Server Files > should render dynamic SSR page correctly
- Required Server Files > should render fallback page correctly
- Required Server Files > should render SSR page correctly with x-matched-path
- Required Server Files > should render dynamic SSR page correctly with x-matched-path
- Required Server Files > should render fallback page correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path
- Required Server Files > should render fallback optional catch-all route correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path for optional catch-all route
- Required Server Files > should not apply trailingSlash redirect
- Required Server Files > should normalize catch-all rewrite query values correctly
- Required Server Files > should bubble error correctly for gip page
- Required Server Files > should bubble error correctly for gssp page
- Required Server Files > should bubble error correctly for gsp page
- Required Server Files > should bubble error correctly for API page
- Required Server Files > should normalize optional values correctly for SSP page
- Required Server Files > should normalize optional values correctly for SSG page
- Required Server Files > should normalize optional values correctly for SSG page with encoded slash
- Required Server Files > should normalize optional values correctly for API page
- Required Server Files > should match the index page correctly
- Required Server Files > should match the root dyanmic page correctly

<details>
<summary>Expand output</summary>

  ● Required Server Files › should output required-server-files manifest correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback optional catch-all route correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path for optional catch-all route

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should not apply trailingSlash redirect

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize catch-all rewrite query values correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gip page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gssp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gsp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSP page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page with encoded slash

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the index page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the root dyanmic page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

</details>

**Review by ijjk — APPROVED** [review]

**Review by styfle — APPROVED** [review]

**Pull request merged**
