### PR TITLE
chore: support progressive jpg with sharp

### PR DESCRIPTION
**Pull request by nil1511**
### What?
Use Progressive JPG when optimizing images using Sharp with Sqooush we are already using [progressive jpg](https://github.com/vercel/next.js/blob/9b2f29ebaf5add67cec0cac7296f9e64567b3fb4/packages/next/src/server/lib/squoosh/codecs.ts#L232)

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Thanks!

Can you share the before/after image of this change?

Better yet, can you add a test here?

https://github.com/vercel/next.js/blob/canary/test/integration/image-optimizer/test/index.test.ts

**Comment by nil1511** [comment]
[input image](https://github.com/vercel/next.js/assets/2058170/2c59e4db-4691-4930-a9c5-8f1adc2209f3)  ~769 kb
[before](https://github.com/vercel/next.js/assets/2058170/1c302fbe-5d27-4476-ba23-8c7849f2072c) | it was generating baseline jpeg  ~432kb
[after](https://github.com/vercel/next.js/assets/2058170/279c8148-c314-4d85-a9cb-9320ddc7ea8a) | as progressive ~417kb

Since almost all browser supports webp and fallback to apng (on explicitly passing empty formats on next.config.js), the condition to get jpeg as a response is rare, so we can close this PR if needed.

**Review by styfle — APPROVED** [review]
> Since almost all browser supports webp, the condition to get jpeg as a response is rare

Agreed, currently 96.68% of browsers support webp https://caniuse.com/webp

> Squoosh we are already using [progressive jpg](https://github.com/vercel/next.js/blob/9b2f29ebaf5add67cec0cac7296f9e64567b3fb4/packages/next/src/server/lib/squoosh/codecs.ts#L232)

Good point, these should behave the same so I think we should land this PR. I also confirmed that cloud providers like imgix will default to progressive jpeg.

https://docs.imgix.com/apis/rendering/format/fm#jpg

> Note: In most cases, images rendered in imgix as JPEGs will use progressive encoding. This is because progressive JPEGs are preferable to baseline JPEGs in terms of size and display speed, though in some cases (such as smaller images), baseline will be better. 

Thanks for the PR! 🎉

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.2s | ⚠️ +106ms |
| buildDurationCached | 6.1s | 6.1s | N/A |
| nodeModulesSize | 173 MB | 173 MB | ⚠️ +248 B |
| nextStartRea..uration (ms) | 529ms | 531ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.5 kB | 27.5 kB | ✓ |
| 3f784ff6-HASH.js gzip | 53.1 kB | 53.1 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 253 B | 252 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 126 kB | 126 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.35 kB | 4.35 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 530 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 523 B | 525 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 154 kB | 154 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | nil1511/next.js patch-2 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 622 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.5 kB | 22.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 51bd30da0e3d64e59673531cc488b407ed1ae617

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 51bd30da0e3d64e59673531cc488b407ed1ae617

`pnpm test test/integration/edge-runtime-configurable-guards/test/index.test.js` 
- Edge runtime configurable guards > Multiple functions with different configurations > warns in dev for allowed code

<details>
<summary>Expand output</summary>

  ● Edge runtime configurable guards › Multiple functions with different configurations › warns in dev for allowed code

    expect(received).toContain(expected) // indexOf

    Expected substring: "Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Edge Runtime"
    Received string:    " ⨯ Middleware cannot be used with \"output: export\". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
     ⨯ API Routes cannot be used with \"output: export\". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
      ▲ Next.js 13.5.6-canary.0
      - Local:        http://localhost:36037·
     ✓ Ready in 2.1s
     ✓ Compiled / in 680ms (189 modules)
    "

      84 |       await waitFor(500)
      85 |       expect(res.status).toBe(200)
    > 86 |       expect(context.logs.output).toContain(
         |                                   ^
      87 |         `Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Edge Runtime`
      88 |       )
      89 |     })

      at Object.<anonymous> (integration/edge-runtime-configurable-guards/test/index.test.js:86:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
