### PR TITLE
[WIP] Improve test setup

### PR DESCRIPTION
**Pull request by arunoda**
Experimenting ways to reduce random test failures.

### CODE REVIEW

**Review by timneutkens — COMMENTED** [review]
Awesome 👍

**Comment by arunoda** [comment]
Here's the major issue.

Sometimes, webdriver takes so long to start the browser. In that case, we need to close it and start a new browser. 
Now we start a browser with a 5000ms timeout. If that fails we re-try it. We do retries for 5 times before marking the test as a failure.

**Comment by rauchg** [comment]
@arunoda I wonder if we can somehow use the new chromium headless mode? Should be more reliable

**Comment by arunoda** [comment]
@rauchg I don't think that's the case. It's between the webdriver and our test code.
Anyway, I tried phantomJS didn't work pretty well with Next.(Not sure about the exact issue though)

**Pull request merged**
