### PR TITLE
Render as a concatenation of streams

### PR DESCRIPTION
**Pull request by devknoll**
Return the `RenderResult` as a concatenation of streams, rather than a concatenation of strings.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3fe5f547c81b1612f4cf2a82b8e329cef7546a42

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    expect(received).toMatch(expected)

    Expected pattern: /background:(.*|)#ff69b4/
    Received string:  "p.jsx-4074723171{font-size:16.4px;}html { background: hotpink; }"

      37 |     const $ = cheerio.load(html)
      38 |     const styles = $('style[amp-custom]').text()
    > 39 |     expect(styles).toMatch(/background:(.*|)#ff69b4/)
         |                    ^
      40 |     expect(styles).toMatch(/font-size:(.*|)16\.4px/)
      41 |   })
      42 | })

      at Object.<anonymous> (integration/amphtml-fragment-style/test/index.test.js:39:20)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| buildDuration | 18s | 12.3s | -5.7s |
| buildDurationCached | 2.9s | 2.5s | -409ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +5.96 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.282 | 2.326 | ⚠️ +0.04 |
| / avg req/sec | 1095.74 | 1074.93 | ⚠️ -20.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.256 | 1.31 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1990.71 | 1908.99 | ⚠️ -81.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.1 kB | 23.1 kB | ✓ |
| webpack-HASH.js gzip | 1.5 kB | 1.5 kB | ✓ |
| Overall change | 67 kB | 67 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _app-HASH.js gzip | 980 B | 980 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 904 B | 904 B | ✓ |
| image-HASH.js gzip | 4.13 kB | 4.13 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 12.8 kB | 12.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.1s | -409ms |
| buildDurationCached | 4.1s | 3.7s | -442ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +5.96 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.321 | 2.382 | ⚠️ +0.06 |
| / avg req/sec | 1077.18 | 1049.42 | ⚠️ -27.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.286 | 1.289 | 0 |
| /error-in-render avg req/sec | 1943.81 | 1939.5 | ⚠️ -4.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| 17.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14 kB | 14 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.6 kB | 10.6 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.9 kB | 67.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _app-HASH.js gzip | 965 B | 965 B | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 2.95 kB | 2.95 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.7 kB | 17.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _buildManifest.js gzip | 498 B | 498 B | ✓ |
| Overall change | 498 B | 498 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| index.html gzip | 577 B | 578 B | ⚠️ +1 B |
| link.html gzip | 589 B | 591 B | ⚠️ +2 B |
| withRouter.html gzip | 569 B | 570 B | ⚠️ +1 B |
| Overall change | 1.74 kB | 1.74 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
</details>
Commit: 3fe5f547c81b1612f4cf2a82b8e329cef7546a42

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1afd0918c628a86f36a02d287966fcf6782ddd4e

**test/integration/amphtml-custom-optimizer/test/index.test.js** 
- AMP Custom Optimizer > should build and start for static page
- AMP Custom Optimizer > should build and start for dynamic page

<details>
<summary>Expand output</summary>

  ● AMP Custom Optimizer › should build and start for static page

    command failed with code 1

      157 |         code !== 0
      158 |       ) {
    > 159 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      160 |       }
      161 |
      162 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:159:23)

  ● AMP Custom Optimizer › should build and start for dynamic page

    command failed with code 1

      157 |         code !== 0
      158 |       ) {
    > 159 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      160 |       }
      161 |
      162 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:159:23)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | -32ms |
| buildDurationCached | 2.9s | 2.9s | -34ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +6.93 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.27 | 2.344 | ⚠️ +0.07 |
| / avg req/sec | 1101.52 | 1066.61 | ⚠️ -34.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.264 | 1.266 | 0 |
| /error-in-render avg req/sec | 1977.78 | 1974.85 | ⚠️ -2.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.1 kB | 23.1 kB | ✓ |
| webpack-HASH.js gzip | 1.5 kB | 1.5 kB | ✓ |
| Overall change | 67 kB | 67 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _app-HASH.js gzip | 980 B | 980 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 904 B | 904 B | ✓ |
| image-HASH.js gzip | 4.13 kB | 4.13 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 12.8 kB | 12.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.4s | ⚠️ +89ms |
| buildDurationCached | 4.1s | 4s | -54ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +6.93 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.323 | 2.317 | -0.01 |
| / avg req/sec | 1076.4 | 1078.93 | +2.53 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.277 | 1.266 | -0.01 |
| /error-in-render avg req/sec | 1957.76 | 1974.8 | +17.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| 17.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14 kB | 14 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.6 kB | 10.6 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 67.9 kB | 67.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _app-HASH.js gzip | 965 B | 965 B | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 2.95 kB | 2.95 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.7 kB | 17.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| _buildManifest.js gzip | 498 B | 498 B | ✓ |
| Overall change | 498 B | 498 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-chunked-body-new | Change |
| - | - | - | - |
| index.html gzip | 577 B | 578 B | ⚠️ +1 B |
| link.html gzip | 589 B | 591 B | ⚠️ +2 B |
| withRouter.html gzip | 569 B | 570 B | ⚠️ +1 B |
| Overall change | 1.74 kB | 1.74 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -1,4 +1,4 @@
-<!DOCTYPE html>
+<!DOCTYPE html><!DOCTYPE html>
 <html>
   <head>
     <meta charset="utf-8" />
```
</details>
</details>
Commit: c811f7a438e2922c86cb2a5f7424cfa768a71afd

**Review by shuding — APPROVED** [review]

**Pull request merged**
