### PR TITLE
Incorporate  styled-jsx

### PR DESCRIPTION
**Pull request by nkzawa**
This PR adds `styled-jsx` support.
~~It's almost ready but need to wait the fix of https://github.com/zeit/styled-jsx/issues/41~~

### CODE REVIEW

**Comment by nkzawa** [comment]
Done

**Comment by nkzawa** [comment]
I think we want to fix https://github.com/zeit/styled-jsx/issues/22 before releasing the feature.

**Comment by gajus** [comment]
Shame I was not aware of this PR. Would have proposed https://github.com/gajus/babel-plugin-react-css-modules. It incorporates CSS modules and it could be used to inline the styles (https://github.com/gajus/babel-plugin-react-css-modules/issues/2).

Would there be any interest for a PR?

**Comment by rauchg** [comment]
@gajus how do you keep track of detaching styles in a situation like this:

```
import React from 'react';
import styles from './table.css';

export default class Table extends React.Component {
  render () {
    return <div className={styles.table}>
      <div className={styles.row}>
        <div className={styles.cell}>A0</div>
        <div className={styles.cell}>B0</div>
      </div>
    </div>;
  }
}
```

?

**Comment by gajus** [comment]
> @gajus how do you keep track of detaching styles in a situation like this:

Please provide more details. Not sure of the implications of the above code example to https://github.com/gajus/babel-plugin-react-css-modules.

The above example would be written as the following using `babel-plugin-react-css-modules`:

```js
import React from 'react';
import './table.css';

export default () => {
  return <div styleName='table'>
    <div styleName='row'>
      <div styleName='cell'>A0</div>
      <div styleName='cell'>B0</div>
      <div styleName='cell'>C0</div>
    </div>
  </div>;
};

```

or as:

```js
import React from 'react';
import table from './table.css';

export default () => {
  return <div styleName='table.table'>
    <div styleName='table.row'>
      <div styleName='table.cell'>A1</div>
      <div styleName='table.cell'>B1</div>
      <div styleName='table.cell'>C1</div>
    </div>
  </div>;
};

```

Depending on user preference.

**Comment by rauchg** [comment]
@gajus

If the component is not included in the page, doesn't the CSS live on, attached to the `<head>` of the page?

Since Next is designed around lazy-loading any number of pages throughout a user's session, `styled-jsx` was designed around the constraint that if the component gets detached, the styles get detached. 

We use a technique similar to _reference counting_ to ensure there's at most one style present per component, and that it disappears if the component ceases to exist.

**Comment by gajus** [comment]
Oh, I see what you are referring to.

There is no such attempt being made at the moment. It isn't even possible. Style names can be generated dynamically, e.g. `<div styleName={Math.random() > 0.5 ? 'a' : 'b'}>C1</div>`. If we'd remove the dynamic style resolution, then it would be do-able. However, a lot of people do use [runtime style resolution](https://github.com/gajus/babel-plugin-react-css-modules#runtime-stylename-resolution).

Is that a big problem though?

**Pull request merged**
