### PR TITLE
chore: update pnpm@9.0.5

### PR DESCRIPTION
**Pull request by ryota-murakami**
Here are the release notes for PNPM from v9.0.0 to v9.0.5:
Notable change of v9  is Corepack enable by default.  
So we can ensure all package manage/resolved exact same version of pnpm.

- [**v9.0.0**](https://github.com/pnpm/pnpm/releases/tag/v9.0.0): Discontinued support for Node.js v16 and introduced Corepack compatibility checks. New configuration updates include enabling `dedupe-injected-deps` and changing the lockfile to version 9, with better readability and resistance to Git conflicts.

- [**v9.0.1**](https://github.com/pnpm/pnpm/releases/tag/v9.0.1): Resolved issues with `pnpm install --frozen-lockfile`, allowing it to work with lockfiles generated by PNPM v8 if no updates are required.

- [**v9.0.2**](https://github.com/pnpm/pnpm/releases/tag/v9.0.2): Addressed a bug where optional dependencies were not linked into dependent's `node_modules`. Fixed some other minor bugs.

- [**v9.0.3**](https://github.com/pnpm/pnpm/releases/tag/v9.0.3): Implemented changes to address the `script-shell` option erroring on Windows with `.bat` or `.cmd` files. Also fixed issues with `package-manager-strict` checks and added more completion command support.

- [**v9.0.4**](https://github.com/pnpm/pnpm/releases/tag/v9.0.4): Fixed aliased dependencies resolution on repeated installs with existing lockfiles and addressed issues with `engines.pnpm` field in package.json being ignored

- [v9.0.5](https://github.com/pnpm/pnpm/releases/tag/v9.0.5)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4bf847ee93a412acf16da145d2f60aa138418407

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4bf847ee93a412acf16da145d2f60aa138418407

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 4bf847ee93a412acf16da145d2f60aa138418407

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@ryota-murakami Looks like there is a conflict with the lock file <picture data-single-emoji=":blob_bowing:" title=":blob_bowing:">:blob_bowing:</picture>

**Comment by ryota-murakami** [comment]
@samcx Yeah, but got ` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@next%2Fswc: Not Found - 404` after merge canary branch.
The package use to other registry?

Screenshot 2024-04-23 at 9 31 14

**Comment by samcx** [comment]
@ryota-murakami I just created a new <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture> since it seems that `@next/swc` is not a registered package, so creating a new lock file was not possible. → https://github.com/vercel/next.js/pull/64945

**Pull request closed without merging**
