### PR TITLE
Update example with-mongodb to add both Pages & App examples

### PR DESCRIPTION
**Pull request by codeSTACKr**
Updated all dependencies and added an app route to demonstrate both pages an app directories.

### CODE REVIEW

**Review by delbaoliveira — DISMISSED** [review]
Thank you for updating this example Jesse and Justin! 🙏🏼 

Could you please resolve the merge conflict?

**Comment by codeSTACKr** [comment]
Thank you for checking this out @delbaoliveira. I've addressed the conflicts and proceeded to merge. Please let me know if there is anything else needed.

**Comment by samcx** [comment]
@codeSTACKr Let's actually just keep only the App Router version in this example, to align with what we've been doing with a lot of other examples. <picture data-single-emoji=":blob_bowing:" title=":blob_bowing:">:blob_bowing:</picture>

**Review by samcx — APPROVED** [review]

**Comment by samcx** [comment]
@codeSTACKr 

It looks like the lint is mad about your HEAD being detached → https://github.com/vercel/next.js/actions/runs/10085328885/job/27885936674?pr=64130.

```
HEAD detached at pull/64130/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   examples/with-mongodb/next-env.d.ts
```

**Comment by codeSTACKr** [comment]
@samcx All changes are committed, please try again. Thanks!

**Comment by samcx** [comment]
Giving the same issue... hmmm

**Comment by samcx** [comment]
@codeSTACKr I'm not sure if our CI is not happy because you're trying to merge your fork's canary to our canary. Can you try using a different branch?

**Comment by codeSTACKr** [comment]
@samcx Ok, I'll give that a try.

**Comment by codeSTACKr** [comment]
@samcx just created a new PR: https://github.com/vercel/next.js/pull/68461

**Pull request closed without merging**
