### PR TITLE
Example: Improve ReasonML example

### PR DESCRIPTION
**Pull request by nrako**
This improve the example for ReasonML `with-reasonml`.

While trying to run this example, I run into different issues, this PR is meant to fix them. While at it, this also upgrade some dependencies, including upgrading to next.js v3. And make some other improvements, [enable nicer error msgs](https://reasonml.github.io/community/blog/#way-way-waaaay-nicer-error-messages) and update the example to use the new recommended `ReasonReact.reducerComponent` instead of `ReasonReact.statefulComponent` - more read about this [here](https://github.com/reasonml/reason-react/blob/master/HISTORY.md#024).

Note: I believe that the `package-lock.json` should be versioned in the examples, especially for theses kind of example which use "bleeding edge" stuff prone to break at any new deps update. However, #2623 ignore them, not sure why, so I didn't add the file.

### CODE REVIEW

**Comment by nrako** [comment]
@mike-engel since you first pushed the initial example for ReasonML/ReactReason, I'd love to have your input on this. I'm just starting with ReasonML.

**Review by mike-engel — APPROVED** [review]
👍 LGTM

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks guys!

**Comment by nrako** [comment]
With pleasure!

**Comment by hsavit1** [comment]
please upgrade to reasonml 3

**Pull request merged**
