### PR TITLE
Update example of using external CSS

### PR DESCRIPTION
**Pull request by GarrisonD**
Hey folks and @guidiego!

I've updated `next`, `react` and other dependencies to the latest versions.

I also noticed that it does not work as expected. Can anybody help me with debugging? @guidiego?)

### CODE REVIEW

**Comment by GarrisonD** [comment]
Sorry for such a stupid question, but is it a huge problem to use webpack on server side too? Can I read about it any where?

**Comment by guidiego** [comment]
@GarrisonD next use webpack too make a lot of good stuff, unfortunately, some stuff breaks server-side experience. For that reason people using more babel-plugins than other webpack modules :) Isn't a stupid question bro hahaha

**Comment by GarrisonD** [comment]
@guidiego it's stupid not to use webpack layer on server-side :slightly_frowning_face:

**Comment by GarrisonD** [comment]
@guidiego can you help me with upgrading this example? because, i have no idea how to debug it :slightly_frowning_face:

**Comment by guidiego** [comment]
I'm stuck in work to debug it, let me try to figure out one possibility:

```
 -      ["css-modules-transform", {
 -        "extensions": [".css", ".sass"],
 -        "append": [ "postcss-cssnext" ],		
 -        "extractCss": "./static/css/bundle.css",		
 -        "preprocessCss": "./pre-processor.js"		
 -      }		
 -    ]
```

Why you remove all these guys? I guess that you need  "extensions" in it.

**Comment by GarrisonD** [comment]
@guidiego before making it work with `sass`, `postcss`, etc. i want to make it running with simple css. everything works but only one time when i run it the first time, after that any changes to `index.css` are ignored and i can't figure out why.

**Comment by guidiego** [comment]
I didnt rember excatly when `postcss` was added, but I think that this was added to remove this problem @GarrisonD. 

@nahue did you remember something about this issue that Garrison report?

**Comment by GarrisonD** [comment]
@guidiego sorry, but i didn't understand about webpack **DEV** stuff, can you provide me an example or a link where I can read about it?

**Comment by GarrisonD** [comment]
@guidiego what do you think about react-starter-kit approach for building universal React apps?

**Pull request closed without merging**
