### PR TITLE
Ignore no-anonymous-default-export babel plugin for node_modules

### PR DESCRIPTION
**Pull request by jeroensak**
Hello! 
For issue [15696](https://github.com/vercel/next.js/issues/15696) I'd like to submit this pull request.
As discussed in the issue I am preventing the warnings for any node_modules.

I am unclear of if this would be a bug, fix, or feature. I would declare this a linting improvement 😅 . I also haven't found tests for your babel plugins, nor documentation. Let me now if I've just been blind or if I should improve this PR in any way.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for this change? The code change looks fine 👍

**Comment by jeroensak** [comment]
Thanks for the response! I've been trying to create a small test to get started for now, but I'm running into a babel issue.

Maybe you or anyone else could shine some light on this as I'm not yet all too familiar with the complete setup.

This is the test file:

```
/* eslint-env jest */
import { transform } from '@babel/core'

const trim = (s) => s.join('\n').trim().replace(/^\s+/gm, '')

const mockOnWarning = jest.fn();

// avoid generating __source annotations in JSX during testing:
const plugin = require('next/dist/build/babel/plugins/no-anonymous-default-export')

const babel = (code, esm = true, pluginOptions = {}) =>
  transform(code, {
    filename: 'noop.js',
    presets: [['@babel/preset-react', { development: true, pragma: '__jsx' }]],
    plugins: [[plugin, pluginOptions]],
    babelrc: false,
    configFile: false,
    sourceType: 'module',
    compact: true,
    caller: {
      name: 'tests',
      supportsStaticESM: esm,
      onWarning: mockOnWarning // <--- just trying to set any function
    },
  }).code

describe('babel plugin (no-anonymous-default-export)', () => {
  it('should trigger on a default export anonymous arrow function', () => {
    babel(trim`
        export default () => {
          return 'hello'
        }
      `,)
    expect(mockOnWarning).toHaveBeenCalled();
  })
})
```

But when running this I get an error stating `.caller["onWarning"] must be null, undefined, a boolean, a string, or a number.`. I've checked the [documentation of babel](https://babeljs.io/docs/en/options#caller) and this error does make sense, the caller property should only be used to set flags. However, in `next-babel-loader.js line 105` we are actually setting a function on that property and I'm not sure if that should be an issue or not. I'd expect it to throw during the build, but somehow it doesn't.

When setting the property `onWarning` to a string, the property is passed correctly into the custom plugin, so I'm doing the right thing there. It just won't accept a function. The test is also passing when disabling the line in the babel `option-assertions.js` that checks for the typeof `onWarning`.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 15b87a6bb7bcb40e8c960667c8dcde5d8aef8405

**test/unit/babel-plugin-no-anonymous-default-export.unit.test.js** 
- babel plugin (no-anonymous-default-export) > ArrowFunctionExpression > should trigger on a default export anonymous arrow function
- babel plugin (no-anonymous-default-export) > ArrowFunctionExpression > should not trigger on a named default export arrow function
- babel plugin (no-anonymous-default-export) > FunctionDeclaration > should trigger on a default export anonymous function
- babel plugin (no-anonymous-default-export) > FunctionDeclaration > should not trigger on a named default export function

<details>
<summary>Expand output</summary>

  ● babel plugin (no-anonymous-default-export) › ArrowFunctionExpression › should trigger on a default export anonymous arrow function

    .caller["onWarning"] must be null, undefined, a boolean, a string, or a number.

      at assertCallerMetadata (../node_modules/@babel/core/lib/config/validation/option-assertions.js:114:15)
      at ../node_modules/@babel/core/lib/config/validation/options.js:118:5
          at Array.forEach (<anonymous>)
      at validateNested (../node_modules/@babel/core/lib/config/validation/options.js:94:21)
      at validate (../node_modules/@babel/core/lib/config/validation/options.js:85:10)
      at loadPrivatePartialConfig (../node_modules/@babel/core/lib/config/partial.js:78:50)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (../node_modules/@babel/core/lib/config/full.js:55:46)
          at loadFullConfig.next (<anonymous>)
      at Function.transform (../node_modules/@babel/core/lib/transform.js:23:45)

  ● babel plugin (no-anonymous-default-export) › ArrowFunctionExpression › should not trigger on a named default export arrow function

    .caller["onWarning"] must be null, undefined, a boolean, a string, or a number.

      at assertCallerMetadata (../node_modules/@babel/core/lib/config/validation/option-assertions.js:114:15)
      at ../node_modules/@babel/core/lib/config/validation/options.js:118:5
          at Array.forEach (<anonymous>)
      at validateNested (../node_modules/@babel/core/lib/config/validation/options.js:94:21)
      at validate (../node_modules/@babel/core/lib/config/validation/options.js:85:10)
      at loadPrivatePartialConfig (../node_modules/@babel/core/lib/config/partial.js:78:50)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (../node_modules/@babel/core/lib/config/full.js:55:46)
          at loadFullConfig.next (<anonymous>)
      at Function.transform (../node_modules/@babel/core/lib/transform.js:23:45)

  ● babel plugin (no-anonymous-default-export) › FunctionDeclaration › should trigger on a default export anonymous function

    .caller["onWarning"] must be null, undefined, a boolean, a string, or a number.

      at assertCallerMetadata (../node_modules/@babel/core/lib/config/validation/option-assertions.js:114:15)
      at ../node_modules/@babel/core/lib/config/validation/options.js:118:5
          at Array.forEach (<anonymous>)
      at validateNested (../node_modules/@babel/core/lib/config/validation/options.js:94:21)
      at validate (../node_modules/@babel/core/lib/config/validation/options.js:85:10)
      at loadPrivatePartialConfig (../node_modules/@babel/core/lib/config/partial.js:78:50)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (../node_modules/@babel/core/lib/config/full.js:55:46)
          at loadFullConfig.next (<anonymous>)
      at Function.transform (../node_modules/@babel/core/lib/transform.js:23:45)

  ● babel plugin (no-anonymous-default-export) › FunctionDeclaration › should not trigger on a named default export function

    .caller["onWarning"] must be null, undefined, a boolean, a string, or a number.

      at assertCallerMetadata (../node_modules/@babel/core/lib/config/validation/option-assertions.js:114:15)
      at ../node_modules/@babel/core/lib/config/validation/options.js:118:5
          at Array.forEach (<anonymous>)
      at validateNested (../node_modules/@babel/core/lib/config/validation/options.js:94:21)
      at validate (../node_modules/@babel/core/lib/config/validation/options.js:85:10)
      at loadPrivatePartialConfig (../node_modules/@babel/core/lib/config/partial.js:78:50)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (../node_modules/@babel/core/lib/config/full.js:55:46)
          at loadFullConfig.next (<anonymous>)
      at Function.transform (../node_modules/@babel/core/lib/transform.js:23:45)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.1s | -136ms |
| buildDurationCached | 3.6s | 3.5s | -106ms |
| nodeModulesSize | 50.4 MB | 50.4 MB | ⚠️ +361 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.872 | 2.941 | ⚠️ +0.07 |
| / avg req/sec | 870.62 | 849.95 | ⚠️ -20.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.823 | 1.808 | -0.01 |
| /error-in-render avg req/sec | 1371.2 | 1382.94 | +11.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| 359.HASH.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 745.HASH.js gzip | 180 B | 180 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 21 kB | 21 kB | ✓ |
| webpack-HASH.js gzip | 1.53 kB | 1.53 kB | ✓ |
| Overall change | 67.9 kB | 67.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 554 B | 554 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| head-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| image-HASH.js gzip | 5.63 kB | 5.63 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 319 B | 319 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.1 kB | 19.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| _buildManifest.js gzip | 489 B | 489 B | ✓ |
| Overall change | 489 B | 489 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.6s | -101ms |
| buildDurationCached | 4.9s | 4.7s | -209ms |
| nodeModulesSize | 50.4 MB | 50.4 MB | ⚠️ +361 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.829 | 2.952 | ⚠️ +0.12 |
| / avg req/sec | 883.85 | 846.95 | ⚠️ -36.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.81 | 1.852 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1381.04 | 1350.07 | ⚠️ -30.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| 17.HASH.js gzip | 2.98 kB | 2.98 kB | ✓ |
| 18.HASH.js gzip | 185 B | 185 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 8.4 kB | 8.4 kB | ✓ |
| webpack-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| Overall change | 68.5 kB | 68.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| _app-HASH.js gzip | 791 B | 791 B | ✓ |
| _error-HASH.js gzip | 3.76 kB | 3.76 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 2.97 kB | 2.97 kB | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| withRouter-HASH.js gzip | 294 B | 294 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 17.6 kB | 17.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jeroensak/next.js feature/15696_disable_no-anonymous-default-export_for_node-modules | Change |
| - | - | - | - |
| index.html gzip | 577 B | 577 B | ✓ |
| link.html gzip | 588 B | 588 B | ✓ |
| withRouter.html gzip | 569 B | 569 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

</details>
Commit: 15b87a6bb7bcb40e8c960667c8dcde5d8aef8405

**Comment by dsernst** [comment]
Thank you, @jeroensak ! ❤️

This warning was being shown on every fast-refresh on a fresh install of `yarn create next-app --typescript`, complaining about the boilerplate `pages/_app.tsx` even though I haven't touched it and it has no arrow functions. It suggests running a codemod, but the codemod has no effect (all files skipped).

I can confirm that by manually adding this PR's change to my `node_modules/next/dist/build/babel/plugins/no-anonymous-default-export.js` file (using `patch-package`, then restarting `yarn dev`: now that false positive warning is gone 🎉.

Thanks again!


For anyone else that comes across this before the PR is merged, here's what my `patches/next+11.0.1.patch` looks like:

```diff
diff --git a/node_modules/next/dist/build/babel/plugins/no-anonymous-default-export.js b/node_modules/next/dist/build/babel/plugins/no-anonymous-default-export.js
index 3ce2ceb..f57eb0b 100644
--- a/node_modules/next/dist/build/babel/plugins/no-anonymous-default-export.js
+++ b/node_modules/next/dist/build/babel/plugins/no-anonymous-default-export.js
@@ -1,4 +1,4 @@
 "use strict";exports.__esModule=true;exports.default=NoAnonymousDefaultExport;var _chalk=_interopRequireDefault(require("chalk"));function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}function NoAnonymousDefaultExport({types:t,...babel}){let onWarning=null;babel.caller(caller=>{onWarning=caller.onWarning;return'';// Intentionally empty to not invalidate cache
-});if(typeof onWarning!=='function'){return{visitor:{}};}const warn=onWarning;return{visitor:{ExportDefaultDeclaration(path){const def=path.node.declaration;if(!(def.type==='ArrowFunctionExpression'||def.type==='FunctionDeclaration')){return;}switch(def.type){case'ArrowFunctionExpression':{warn([_chalk.default.yellow.bold('Anonymous arrow functions cause Fast Refresh to not preserve local component state.'),'Please add a name to your function, for example:','',_chalk.default.bold('Before'),_chalk.default.cyan('export default () => <div />;'),'',_chalk.default.bold('After'),_chalk.default.cyan('const Named = () => <div />;'),_chalk.default.cyan('export default Named;'),'',`A codemod is available to fix the most common cases: ${_chalk.default.cyan('https://nextjs.link/codemod-ndc')}`].join('\n'));break;}case'FunctionDeclaration':{const isAnonymous=!Boolean(def.id);if(isAnonymous){warn([_chalk.default.yellow.bold('Anonymous function declarations cause Fast Refresh to not preserve local component state.'),'Please add a name to your function, for example:','',_chalk.default.bold('Before'),_chalk.default.cyan('export default function () { /* ... */ }'),'',_chalk.default.bold('After'),_chalk.default.cyan('export default function Named() { /* ... */ }'),'',`A codemod is available to fix the most common cases: ${_chalk.default.cyan('https://nextjs.link/codemod-ndc')}`].join('\n'));}break;}default:{// eslint-disable-next-line @typescript-eslint/no-unused-vars
+});if(typeof onWarning!=='function'){return{visitor:{}};}const warn=onWarning;return{visitor:{ExportDefaultDeclaration(path,state){const filename = state.file.opts.filename;if (filename.includes('/node_modules/')) return;const def = path.node.declaration;if(!(def.type==='ArrowFunctionExpression'||def.type==='FunctionDeclaration')){return;}switch(def.type){case'ArrowFunctionExpression':{warn([_chalk.default.yellow.bold('Anonymous arrow functions cause Fast Refresh to not preserve local component state.'),'Please add a name to your function, for example:','',_chalk.default.bold('Before'),_chalk.default.cyan('export default () => <div />;'),'',_chalk.default.bold('After'),_chalk.default.cyan('const Named = () => <div />;'),_chalk.default.cyan('export default Named;'),'',`A codemod is available to fix the most common cases: ${_chalk.default.cyan('https://nextjs.link/codemod-ndc')}`].join('\n'));break;}case'FunctionDeclaration':{const isAnonymous=!Boolean(def.id);if(isAnonymous){warn([_chalk.default.yellow.bold('Anonymous function declarations cause Fast Refresh to not preserve local component state.'),'Please add a name to your function, for example:','',_chalk.default.bold('Before'),_chalk.default.cyan('export default function () { /* ... */ }'),'',_chalk.default.bold('After'),_chalk.default.cyan('export default function Named() { /* ... */ }'),'',`A codemod is available to fix the most common cases: ${_chalk.default.cyan('https://nextjs.link/codemod-ndc')}`].join('\n'));}break;}default:{// eslint-disable-next-line @typescript-eslint/no-unused-vars
 const _=def;}}}}};}
 //# sourceMappingURL=no-anonymous-default-export.js.map
\ No newline at end of file
```

**Comment by spion** [comment]
Why not move this whole rule to the eslint plugin? The main reason this is a problem is because transpiling and linting are different things and we have different expectations of them (while we might want to transpile other libraries. we definitely are mainly concerned about linting our own code)

**Review by ijjk — COMMENTED** [review]
Hi, it looks like we can close this now as this rule was removed in https://github.com/vercel/next.js/pull/32763 and is now being handled as an ESLint rule instead.

**Pull request closed without merging**
