### PR TITLE
Add azure-pipelines

### PR DESCRIPTION
**Pull request by HaNdTriX**
**Image:** `vs2017-win2016`
**Documentation:** https://azure.microsoft.com/en-us/services/devops/pipelines/
**Example:** https://dev.azure.com/nextjs/nextjs-test/_build/results?buildId=4&view=logs
**Github App:** https://github.com/marketplace/azure-pipelines

### CODE REVIEW

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/commit/0b6ecf1fe467e8606033ec3a62300b4ccfdf75f9

**Comment by kaylangan** [comment]
I know this is already closed, but please let me know if you have any questions or suggestions. I'm a Program Manager on Azure Pipelines.

**Comment by kaylangan** [comment]
@HaNdTriX I noticed that you have two pipelines that look very similar: zeit.next.js and zeit.next.js (1). Is that intentional?

**Comment by timneutkens** [comment]
Hey Kayla, @HaNdTriX has removed one of them 👍

**Pull request closed without merging**
