### PR TITLE
Reformat FAQ section

### PR DESCRIPTION
**Pull request by jazzido**
…use normal Markdown headers instead of `summary`/`details` (I didn't notice there were answers for the FAQs until I accidentally clicked on one of the questions)

### CODE REVIEW

**Comment by rauchg** [comment]
It really makes the README too long I think. Maybe links to the Wiki would be better?

**Comment by jazzido** [comment]
Yeah, it gets a bit long. I can't edit the README, but if you add a FAQ page and mover over the questions there, I'll be happy to update this PR.

**Comment by rauchg** [comment]
Added the page

**Comment by rauchg** [comment]
I'll move everything to the wiki! Thanks for the PR

**Pull request closed without merging**
