### PR TITLE
chore(types): update TypeScript interface `NextConfig`

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/zeit/next.js/issues/10254

### CODE REVIEW

**Comment by lfades** [comment]
I don't agree with this change, there's no benefit for the user because `next.config.js` is not supposed to have TypeScript, it can be somehow useful for the internal types, but I still prefer to validate every config manually without depending on types.

**Comment by bluelovers** [comment]
typescript can check .js file

**Comment by Timer** [comment]
Closing as outdated.

**Comment by bgmort** [comment]
I'll put out another request to take another look at this.  Are there any downsides of merging it? The benefits have been laid out well in the related issues. You don't need to be convert next.config.js to benefit from this.  There is still no concise reference for next.config.js.  Having a NextConfig type and using it via JSDoc brings an always-current reference directly into the editor.

**Pull request closed without merging**
