### PR TITLE
Add dev option to Turbopack createProject()

### PR DESCRIPTION
**Pull request by timneutkens**
## What?

Adds the `dev` option to switch between development and production output flags for Turbopack.
Note: This only adds the option, the `false` value (production) doesn't work yet. 

Closes NEXT-2499

### CODE REVIEW

**Comment by timneutkens** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/62083?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* `canary`
  * **#62079** <a href="https://app.graphite.dev/github/pr/vercel/next.js/62079?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **#62083** <a href="https://app.graphite.dev/github/pr/vercel/next.js/62083?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @timneutkens and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 053fbbffd6327b2fffd59cd5b409c87c40504ba7

`pnpm test-dev test/development/basic/next-rs-api.test.ts`
- next.rs api > should detect the correct routes
- next.rs api > should allow to write root page to disk
- next.rs api > should allow to write pages edge api to disk
- next.rs api > should allow to write pages Node.js api to disk
- next.rs api > should allow to write app edge page to disk
- next.rs api > should allow to write app Node.js page to disk
- next.rs api > should allow to write pages edge page to disk
- next.rs api > should allow to write pages Node.js page to disk
- next.rs api > should allow to write app edge route to disk
- next.rs api > should allow to write app Node.js route to disk
- next.rs api > should have working HMR on client-side change on a page 0
- next.rs api > should have working HMR on client-side change on a page 1
- next.rs api > should have working HMR on client-side change on a page 2
- next.rs api > should have working HMR on server-side change on a page 0
- next.rs api > should have working HMR on server-side change on a page 1
- next.rs api > should have working HMR on server-side change on a page 2
- next.rs api > should have working HMR on client and server-side change on a page 0
- next.rs api > should have working HMR on client and server-side change on a page 1
- next.rs api > should have working HMR on client and server-side change on a page 2
- next.rs api > should have working HMR on client-side change on a app page 0
- next.rs api > should have working HMR on client-side change on a app page 1
- next.rs api > should have working HMR on client-side change on a app page 2
- next.rs api > should have working HMR on server-side change on a app page 0
- next.rs api > should have working HMR on server-side change on a app page 1
- next.rs api > should have working HMR on server-side change on a app page 2

<details>
<summary>Expand output</summary>

  ● next.rs api › should detect the correct routes

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write root page to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write pages edge api to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write pages Node.js api to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write app edge page to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write app Node.js page to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write pages edge page to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write pages Node.js page to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write app edge route to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to write app Node.js route to disk

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a page 0

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a page 1

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a page 2

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a page 0

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a page 1

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a page 2

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 0

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 1

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client and server-side change on a page 2

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a app page 0

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a app page 1

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on client-side change on a app page 2

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a app page 0

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a app page 1

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should have working HMR on server-side change on a app page 2

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

  ● next.rs api › should allow to make many HMR updates

    Missing field `dev`

      1142 |   ) {
      1143 |     return new ProjectImpl(
    > 1144 |       await binding.projectNew(
           |                     ^
      1145 |         await rustifyProjectOptions(options),
      1146 |         turboEngineOptions || {}
      1147 |       )

      at Object.projectNew [as createProject] (../packages/next/src/build/swc/index.ts:1144:21)
      at Object.<anonymous> (development/basic/next-rs-api.test.ts:194:15)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| buildDuration | 21.9s | 21.8s | N/A |
| buildDurationCached | 8.3s | 7.9s | N/A |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +16.7 kB |
| nextStartRea..uration (ms) | 437ms | 444ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| 1068-HASH.js gzip | 30.2 kB | 30.2 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4944-HASH.js gzip | 5.04 kB | 5.03 kB | N/A |
| 8423.HASH.js gzip | 181 B | 181 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 243 B | 242 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 47.1 kB | 47.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 196 B | ✓ |
| _error-HASH.js gzip | 184 B | 183 B | N/A |
| amp-HASH.js gzip | 503 B | 504 B | N/A |
| css-HASH.js gzip | 323 B | 324 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.51 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 353 B | 351 B | N/A |
| hooks-HASH.js gzip | 370 B | 370 B | ✓ |
| image-HASH.js gzip | 4.21 kB | 4.2 kB | N/A |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 313 B | 314 B | N/A |
| script-HASH.js gzip | 386 B | 385 B | N/A |
| withRouter-HASH.js gzip | 309 B | 311 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 931 B | 931 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 525 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94.4 kB | 94.4 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 626 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 44.4 kB | 44.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 2.1 kB | 2.1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.5 kB | 95.5 kB | ✓ |
| app-page-tur..prod.js gzip | 97.3 kB | 97.3 kB | ✓ |
| app-page-tur..prod.js gzip | 91.7 kB | 91.7 kB | ✓ |
| app-page.run...dev.js gzip | 136 kB | 136 kB | ✓ |
| app-page.run..prod.js gzip | 90.3 kB | 90.3 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 50 kB | 50 kB | ✓ |
| Overall change | 925 kB | 925 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 02-15-Add_dev_option_to_Turbopack_createProject_ | Change |
| - | - | - | - |
| 0.pack gzip | 1.55 MB | 1.55 MB | ⚠️ +1.43 kB |
| index.pack gzip | 104 kB | 103 kB | N/A |
| Overall change | 1.55 MB | 1.55 MB | ⚠️ +1.43 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 053fbbffd6327b2fffd59cd5b409c87c40504ba7

**Comment by Franetse7** [comment]
Ok thanks
Understant

**Review by sokra — APPROVED** [review]

**Comment by Franetse7** [comment]
C'est bon

Le jeu. 15 févr. 2024, 10:55, Tobias Koppers ***@***.***> a
écrit :

**Pull request merged**
