### PR TITLE
Updated nested-components example to use App Router

### PR DESCRIPTION
**Pull request by Shruthireddy04**
This PR updates the nested-components example to use the App Router. Here are the changes that have been made:

Renamed the "pages" folder to "app" folder.
Updated the file index.tsx to page.tsx to align with App Router.
Added the layout.tsx file as part of the App Router.
Updated the components folder to align with App Router and made components folder private.
Updated package.json to use the latest version.

cc: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ce2f6e2df6b0eb20451ba96eb6e6466ea980b2a2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by samcx** [comment]
@Shruthireddy04 Is there a reason why the `jsx` was removed with the style jsx styles?

**Comment by Shruthireddy04** [comment]
@samcx According to[ docs](https://nextjs.org/docs/app/building-your-application/styling/css-in-js) css in js can be used only in client components but here component is not performing any client operations so instead of making it client component removed jsx.

**Comment by samcx** [comment]
@Shruthireddy04 I switched it to CSS modules because there were hydration issues going on.

**Pull request merged**
