### PR TITLE
[edge] support edge-light exports when bundling edge functions

### PR DESCRIPTION
**Pull request by Schniz**
This PR implements `edge-light` as a main field for bundling edge functions as defined in https://runtime-keys.proposal.wintercg.org

Resolves EC-614

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

### CODE REVIEW

**Review by feedthejim — DISMISSED** [review]

**Review by ijjk — CHANGES_REQUESTED** [review]
Can we add a test for this to ensure it's picked up correctly?

Tests with custom `node_modules` can be seen here https://github.com/vercel/next.js/blob/canary/test/e2e/app-dir/app-external/node_modules_bak/css/package.json

**Comment by Schniz** [comment]
> Can we add a test for this to ensure it's picked up correctly?

<picture data-single-emoji=":will-do:" title=":will-do:">:will-do:</picture> <picture data-single-emoji=":np:" title=":np:">:np:</picture> sorry that it takes time

**Comment by Schniz** [comment]
the test showed that my changes we're not good enough <picture data-single-emoji=":thank-u:" title=":thank-u:">:thank-u:</picture>

**Review by javivelasco — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Review by huozhi — APPROVED** [review]

**Comment by Andarist** [comment]
nit: the PR title suggests that this might be introducing `package.json['edge-light']` support (a main field) but it only introduces an exports condition (which I believe is the correct thing and all, there is just a small mismatch between the PR title and the PR content)

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1a24f2aeb18c20cf1ab49f36fda030970f2b2a88

`pnpm testheadless test/e2e/app-dir/app/index.test.ts` 
- app dir > next/script > should support next/script and render in correct order

<details>
<summary>Expand output</summary>

  ● app dir › next/script › should support next/script and render in correct order

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 0

    @@ -3,7 +3,6 @@
        1.5,
        2,
        2.5,
        "render",
        3,
    -   4,
      ]

      1602 |           await new Promise((resolve) => setTimeout(resolve, 1000))
      1603 |
    > 1604 |           expect(await browser.eval(`window._script_order`)).toStrictEqual([
           |                                                              ^
      1605 |             1,
      1606 |             1.5,
      1607 |             2,

      at Object.<anonymous> (e2e/app-dir/app/index.test.ts:1604:62)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
