### PR TITLE
Add EventSource polyfill to hot-middleware-client

### PR DESCRIPTION
**Pull request by jstcki**
Fixes the dev server not working in IE11.

C.f. https://github.com/glenjamin/webpack-hot-middleware/blob/master/README.md#use-on-browsers-without-eventsource

### CODE REVIEW

**Comment by timneutkens** [comment]
Can be done with https://github.com/zeit/next.js/tree/canary/examples/with-polyfills

Not sure if we want to do this by default 🤔cc @arunoda

**Comment by herrstucki** [comment]
Since this doesn't affect app code IMHO it should be polyfilled by the framework. Also, this only affects dev mode, so no overhead is added to production.

**Review by timneutkens — APPROVED** [review]
Besides my earlier comment, code looks great.

**Comment by arunoda** [comment]
@herrstucki we haven't tested dev mode a lot with IE11 assuming we use it for production and use Chrome/FF for dev.

Anyway, this looks legit to me.

**Comment by herrstucki** [comment]
Thanks @arunoda @timneutkens 🙏 

Another thing: I noticed that next.js uses some features in the framework itself that need to be polyfilled for IE (like `Array.prototype.includes`) – do you expect users to polyfill those (because you don't want to support IE11)? Would you be open to another PR to either include polyfills for framework code or to replace these features with IE11-compatible code (like `indexOf`). Personally, I think it would be great if next.js worked out-of-the-box with IE11, so developers only need to polyfill features they actively use in their code.

**Comment by arunoda** [comment]
@herrstucki a production Next.js app should work on IE11 without any polyfill. If we use include (or any other ES6 feature), babel will use the correct polyfill when compiling Next.js.
(So no need to add it manually)

**Comment by herrstucki** [comment]
@arunoda you're right. I looked again and saw this only in dev mode in IE11. I traced it back to react-hot-loader where it was already fixed in this commit: https://github.com/gaearon/react-hot-loader/commit/a42937402d5ee1dc9b2962ab52cfe0c5543efd20 So if you upgrade RHL to the latest version this should be fixed! 👍

**Pull request merged**
