### PR TITLE
Improve grammar of removable Babel config warning

### PR DESCRIPTION
**Pull request by joulev**
The current warning is

> It looks like there is a custom Babel configuration can be removed .

which in this PR is updated to

> It looks like there is a custom Babel configuration that can be removed.

---

[Original bug found by @protehnica on the Next.js Discord:](https://discord.com/channels/752553802359505017/1148942305194152056)

> On my server I used to have a `.babelrc` file to disable `@next/swc`, because it wouldn't run on CentOS 7.
> Apparently this is no longer needed now in Next.js 13, but the message warning users about it looks extremely unprofessional.
> 
> > "It looks like there is a custom Babel configuration can be removed ."
> 
> Not only is the grammar off, there's also a weird space before the final dot.
> Can someone who's already working on the codebase submit a pull request?
> I would love to do it myself, but I wouldn't know where to start.
> 
> The exact file in the repo containing the message string is:
> ```next.js/packages/next/src/build/babel/loader/get-config.ts```

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ab3e53445514e5a0af57d3171eef3ebac95327c0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ab3e53445514e5a0af57d3171eef3ebac95327c0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — APPROVED** [review]

**Comment by joulev** [comment]
@balazsorban44 Thanks a lot for the approval. Could you please approve CI as well? Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.7s | N/A |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +116ms |
| nodeModulesSize | 175 MB | 175 MB | N/A |
| nextStartRea..uration (ms) | 399ms | 419ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 253 B | 252 B | N/A |
| main-HASH.js gzip | 33.1 kB | 33.1 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.71 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| index.html gzip | 529 B | 527 B | N/A |
| link.html gzip | 540 B | 540 B | ✓ |
| withRouter.html gzip | 523 B | 522 B | N/A |
| Overall change | 540 B | 540 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.4 kB | 96.4 kB | N/A |
| page.js gzip | 141 kB | 141 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | joulev/next.js improve-grammar-of-babel-config-warning | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 627 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 830ded7c35409faa3e79a13882cf5c11c885dfbf

**Pull request merged**
