### PR TITLE
Styled Components example that more closely matches default create-next-app

### PR DESCRIPTION
**Pull request by jamesdh**
I'm just getting started with NextJS, and wanted to use styled-components instead of the default styled-jsx. I thought it would be a useful example for me to make the styled-components example more closely match the default `create-next-app` to hopefully make for a better example to anyone else getting started with this. 

Note, the one thing I deviated a bit from the default `create-next-app` is in putting the global body styling within `_document.js`, based on [this spectrum discussion](https://spectrum.chat/next-js/general/ssr-global-styles-with-styled-components-v4~605fa241-b194-4c6b-b071-1816fb96074b)

### CODE REVIEW

**Comment by jamesdh** [comment]
Any reason this would be complaining about double-quotes when I pulled much of the example straight from the default template (which apparently passes just fine)?

**Comment by lfades** [comment]
Hi @jamesdh thank you for the PR, I think that our examples don't need to match the examples of `create-next-app`, the purpose of this example is just to show that `styled-components` can be easily integrated with Next.js.

cc @kheruc

**Comment by kheruc** [comment]
I agree with @lfades 
Small examples like current "with-styled-components" are preferred because they show how to quickly get started with the integration. 
Many people use the examples as starting points for their projects and having too much boilerplate code that `create-next-app` includes can be confusing, it's not clear what is required and what is optional. 
I also wouldn't recommend including global styles into _document.js, a `Layout` component would be a better place.

**Comment by jamesdh** [comment]
The point of putting certain global styles into _document.js in that way is to avoid causing a flash/blink on reload. Using a Layout component for a global style will continue to do that (hence the link to the Spectrum discussion). 

The reason I created this PR was because I used this example as a starting/learning point for Next.js, but it wasn't very helpful. I ended up having to switch back to the default Next.js example and then get styled-components working from there. You both might be familiar with Next and styled-components, but I'm guessing most users of this example won't be.

**Comment by lfades** [comment]
@jamesdh After going through the conversation in spectrum, [this comment](https://spectrum.chat/next-js/general/ssr-global-styles-with-styled-components-v4~605fa241-b194-4c6b-b071-1816fb96074b?m=MTU0ODQxNzA5MDY3OQ==) does have a point, if that's the fix to the issue then can you just add a `_document.js` showing how to add global styles ? without the noice of adding new components and other logic

**Pull request closed without merging**
