### PR TITLE
docs: add missing quotation marks in exmaple code

### PR DESCRIPTION
**Pull request by dydals3440**
### Improving Documentation

`tsx filename="app/layout.tsx` => `tsx filename="app/layout.tsx"`
`jsx filename="app/layout.js` => `jsx filename="app/layout.jsx"`

### CODE REVIEW

**Comment by JamBalaya56562** [comment]
At #73038, renamed unstable_after.mdx → [after.mdx](https://github.com/vercel/next.js/blob/canary/docs/01-app/03-api-reference/04-functions/after.mdx).
So, could you resolve the conflicts?

**Comment by dydals3440** [comment]
> At #73038, renamed unstable_after.mdx → [after.mdx](https://github.com/vercel/next.js/blob/canary/docs/01-app/03-api-reference/04-functions/after.mdx). So, could you resolve the conflicts?

I resolved the conflicts and updated the docs to match the latest version. Thank you!

**Comment by leerob** [comment]
Could you address the merge conflicts please?

**Comment by dydals3440** [comment]
> Could you address the merge conflicts please?
I've resolved the merge conflicts.

**Review by leerob — APPROVED** [review]

**Pull request merged**
