### PR TITLE
fix: add `x-forwarded-*` headers

### LINKED ISSUE #55942: Forwarded request headers are null
### Link to the code that reproduces this issue

https://github.com/razvanMiu/nextjs-forwarded-headers-issue

### To Reproduce

1. Start application in development (npm run dev)
2. Check logged value of `X-Forwarded-Host` header

### Current vs. Expected behavior

Following the steps from the previous section, I expected the `X-Forwarded-Host` to return the current host but I get `null` instead.
I use `X-Forwarded-Host` to forward the server name of nginx and it worked as expected in nextjs <= 13.4.12

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

The first version that introduced the bug is `13.4.13-canary.0` since reverting to `13.4.12` works as expected

<sub>[NEXT-1663](https://linear.app/vercel/issue/NEXT-1663/forwarded-request-headers-are-null)</sub>

### PR DESCRIPTION
**Pull request by balazsorban44**
### What?

Adding back `x-forwarded-*` headers.

### Why?

Starting with #52492, these headers were lost.

### How?

We can populate these headers before executing a request.

Closes NEXT-1663
Fixes #55942

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.3s | N/A |
| buildDurationCached | 6s | 5.9s | N/A |
| nodeModulesSize | 172 MB | 172 MB | ⚠️ +3.06 kB |
| nextStartRea..uration (ms) | 532ms | 534ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.5 kB | 27.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 50.9 kB | 50.9 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 96.4 kB | 96.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.35 kB | 4.35 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 542 B | 542 B | ✓ |
| withRouter.html gzip | 524 B | 525 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | ✓ |
| page.js gzip | 152 kB | 152 kB | N/A |
| Overall change | 93.8 kB | 93.8 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/x-forwarded-headers | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 627 B | 624 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.9 kB | 22.9 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 8f3001ec5b485a06153ca41b8ae28b75a669f399

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f26ef3fcd0c207bcbc98d7c8872ba67a0d44d5d8

`pnpm test test/integration/api-support/test/index.test.js` 
- API routes > dev support > should handle proxying to self correctly

<details>
<summary>Expand output</summary>

  ● API routes › dev support › should handle proxying to self correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      28 |   it('should handle proxying to self correctly', async () => {
      29 |     const res1 = await fetchViaHTTP(appPort, '/api/proxy-self')
    > 30 |     expect(res1.status).toBe(200)
         |                         ^
      31 |     expect(await res1.text()).toContain('User')
      32 |
      33 |     const buildId = dev

      at Object.<anonymous> (integration/api-support/test/index.test.js:30:25)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by styfle — APPROVED** [review]
Thanks!

This might solve a couple other issues too:

- https://github.com/vercel/next.js/issues/56038
- https://github.com/vercel/next.js/issues/53715

**Review by huozhi — APPROVED** [review]

**Comment by joacub** [comment]
this does not fix completly the issue it does fix for some seconds, after some tries will fail again

**Pull request merged**
