### PR TITLE
Remove extra redirect for index with i18n

### LINKED ISSUE #19405: [i18n + redirects] unnecessary redirect for index page
# Bug report

## Describe the bug

Unnecessary redirect for index page.

i18n config: `{ locales: ['en', 'fr', 'zh'], defaultLocale: 'en' }`
redirects config: `{ source: '/first-page', destination: '/', permanent: true }`

In this case we have three redirects instead of two: `/first-page` -> `/en/` -> `/en`, `/fr/first-page` -> `/fr/` -> `/fr`

## To Reproduce

Described in the `Describe the bug` section.

## Expected behavior

For index page we should redirect only once, from `/first-page` -> `/en`

## System information

- OS: Windows
- Browser: Chrome
- Version of Next.js: 10.0.3-canary.0
- Version of Node.js: 12.16.1
- Deployment: dev, next start, Vercel

### PR DESCRIPTION
**Pull request by ijjk**
This makes sure redirects to the index route properly end with a trailing slash or don't based on the `trailingSlash` config to ensure an additional redirect doesn't need to take place un-necessarily. 

Fixes: https://github.com/vercel/next.js/issues/19405

### CODE REVIEW

**Review by Timer — DISMISSED** [review]
Nice

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| buildDuration | 9s | 8.9s | -143ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.761 | 1.742 | -0.02 |
| / avg req/sec | 1419.52 | 1434.83 | +15.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.124 | 1.092 | -0.03 |
| /error-in-render avg req/sec | 2223.26 | 2289.4 | +66.14 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-abf8a5b..ea50.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.3s | -356ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-abf8a5b..ea50.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +46 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +46 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +46 B |
| routerDirect.js | 1.05 MB | 1.05 MB | ⚠️ +46 B |
| withRouter.js | 1.05 MB | 1.05 MB | ⚠️ +46 B |
| Overall change | 5.16 MB | 5.16 MB | ⚠️ +230 B |

</details>

</details>
Commit: efc97699e5e5151137bf1b13e67c680e7260903c

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5642fdd2f0251f3659c1248bc7482526f0a79e92

**test/integration/i18n-support-base-path/test/index.test.js** 
- i18n Support basePath > dev mode > should apply redirects correctly
- i18n Support basePath > production mode > should apply redirects correctly
- i18n Support basePath > serverless mode > should apply redirects correctly

<details>
<summary>Expand output</summary>

  ● i18n Support basePath › dev mode › should apply redirects correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 307
    Received: 200

      482 |       )
      483 | 
    > 484 |       expect(res.status).toBe(shouldRedirect ? 307 : 200)
          |                          ^
      485 | 
      486 |       if (shouldRedirect) {
      487 |         const parsed = url.parse(res.headers.get('location'), true)

      at Object.<anonymous> (integration/i18n-support/test/shared.js:484:26)
          at runMicrotasks (<anonymous>)

  ● i18n Support basePath › production mode › should apply redirects correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 307
    Received: 200

      482 |       )
      483 | 
    > 484 |       expect(res.status).toBe(shouldRedirect ? 307 : 200)
          |                          ^
      485 | 
      486 |       if (shouldRedirect) {
      487 |         const parsed = url.parse(res.headers.get('location'), true)

      at Object.<anonymous> (integration/i18n-support/test/shared.js:484:26)
          at runMicrotasks (<anonymous>)

  ● i18n Support basePath › serverless mode › should apply redirects correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 307
    Received: 200

      482 |       )
      483 | 
    > 484 |       expect(res.status).toBe(shouldRedirect ? 307 : 200)
          |                          ^
      485 | 
      486 |       if (shouldRedirect) {
      487 |         const parsed = url.parse(res.headers.get('location'), true)

      at Object.<anonymous> (integration/i18n-support/test/shared.js:484:26)
          at runMicrotasks (<anonymous>)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.4s | ⚠️ +118ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.218 | 2.303 | ⚠️ +0.08 |
| / avg req/sec | 1127.12 | 1085.41 | ⚠️ -41.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.639 | 1.719 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1525.33 | 1454.31 | ⚠️ -71.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b7e5569..0ca9.js gzip | 6.55 kB | 6.55 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 618 B | 618 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.4s | ⚠️ +280ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | ⚠️ +264 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-b7e5569..0ca9.js gzip | 6.55 kB | 6.55 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js i18n/rm-extra-redirect | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +46 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +46 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +46 B |
| routerDirect.js | 1.05 MB | 1.05 MB | ⚠️ +46 B |
| withRouter.js | 1.05 MB | 1.05 MB | ⚠️ +46 B |
| Overall change | 5.16 MB | 5.16 MB | ⚠️ +230 B |

</details>

</details>
Commit: 9afee57bad47e3e8bde2b4f605245c151eee09f1

**Review by Timer — APPROVED** [review]

**Pull request merged**
