### PR TITLE
feat: added fallback route params to prerender manifest

### PR DESCRIPTION
**Pull request by wyattjoh**
In order for the root parameters to be added to the cache key within Vercel, we need to include the `rootParams` in the `prerender-manfest.json`.

### CODE REVIEW

**Comment by wyattjoh** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/74004?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#74004** <a href="https://app.graphite.dev/github/pr/vercel/next.js/74004?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/74004?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#73933** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73933?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#73816** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73816?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#73928** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73928?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#72837** <a href="https://app.graphite.dev/github/pr/vercel/next.js/72837?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| buildDuration | 23.6s | 21.8s | N/A |
| buildDurationCached | 20.4s | 17.5s | N/A |
| nodeModulesSize | 410 MB | 410 MB | ⚠️ +267 kB |
| nextStartRea..uration (ms) | 577ms | 577ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 51 kB | 51 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 233 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| index.html gzip | 524 B | 524 B | ✓ |
| link.html gzip | 539 B | 538 B | N/A |
| withRouter.html gzip | 519 B | 520 B | N/A |
| Overall change | 524 B | 524 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 204 kB | 204 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 672 B | 668 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.2 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| 523-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 523.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 323 kB | 323 kB | N/A |
| app-page-exp..prod.js gzip | 127 kB | 127 kB | N/A |
| app-page-tur..prod.js gzip | 140 kB | 140 kB | N/A |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | N/A |
| app-page.run...dev.js gzip | 314 kB | 314 kB | N/A |
| app-page.run..prod.js gzip | 123 kB | 123 kB | N/A |
| app-route-ex...dev.js gzip | 37.4 kB | 37.4 kB | N/A |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | N/A |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | N/A |
| app-route-tu..prod.js gzip | 25.3 kB | 25.3 kB | N/A |
| app-route.ru...dev.js gzip | 39 kB | 39 kB | N/A |
| app-route.ru..prod.js gzip | 25.3 kB | 25.3 kB | N/A |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.4 kB | 27.4 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 1.02 MB | 1.02 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feat/added-fallback-route-params-manifest | Change |
| - | - | - | - |
| 0.pack gzip | 2.05 MB | 2.06 MB | ⚠️ +9.51 kB |
| index.pack gzip | 72.6 kB | 73 kB | ⚠️ +422 B |
| Overall change | 2.13 MB | 2.14 MB | ⚠️ +9.93 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>1187-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: a9389c8ba4b6354a9060ebd89e87f7a3592b0f05

**Review by ztanner — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e1c10323a3d4185ad7e19c77163c3c40cd245d03

`pnpm test-start-turbo test/e2e/app-dir/actions/app-action-form-state.test.ts` (turbopack)
- app-dir action useActionState > should support submitting form state with JS
- app-dir action useActionState > should support submitting form state without JS
- app-dir action useActionState > should support hydrating the app from progressively enhanced form request
- app-dir action useActionState > should send the action to the provided permalink with form state when JS disabled

<details>
<summary>Expand output</summary>

  ● app-dir action useActionState › should support submitting form state with JS

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● app-dir action useActionState › should support submitting form state without JS

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● app-dir action useActionState › should support hydrating the app from progressively enhanced form request

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

  ● app-dir action useActionState › should send the action to the provided permalink with form state when JS disabled

    next build failed with code/signal 1

       98 |           if (code || signal)
       99 |             reject(
    > 100 |               new Error(`next build failed with code/signal ${code || signal}`)
          |               ^
      101 |             )
      102 |           else resolve()
      103 |         })

      at ChildProcess.<anonymous> (lib/next-modes/next-start.ts:100:15)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by wyattjoh** [comment]
### Merge activity

* **Dec 17, 1:47 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/74004).

**Pull request merged**
