### PR TITLE
Remove relative path for babel-runtime

### LINKED ISSUE #2951: Use available babel-runtime, don't resolve it relatively
In the `next/babel.js` the babel-runtime module is aliased to use a local version. This is bad practise, since the build script should use any available version of `babel-runtime`, which allows me to use my own.

- [ ] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

In `dist/server/build/babel/preset.js` on line `:24` there is an alias for `babel-runtime` to relatively resolve it inside of next.js. This should be removed, so any version of `babel-runtime` inside the `node_modules` folder is used, not just the one in `next/node_modules`

## Current Behavior

The build script throws an error, since all `babel-runtime` modules are `undefined`.
Currently generated when building:
`var _regenerator = require('next/node_modules/babel-runtime/regenerator');`
Expected/wanted behaviour when building:
`var _regenerator = require('babel-runtime/regenerator');`

## Steps to Reproduce (for bugs)

1. Have a module (let's call it `module-a`) with `next` as `devDependecy`
1. In `modula-a`, use `next/babel` as babelrc preset
1. Build `module-a` to a lib folder
1. In the generated lib files, `var _regenerator = require('next/node_modules/babel-runtime/regenerator');` is now inserted at the top
1. Use `module-a` in another project (`module-b`) that doesn't have `next` as `dependency`.
1. Build `module-b`
1. The build script throws an error, since all `babel-runtime` modules are `undefined` (`next` is not installed in `module-b`).

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 3.0.6 |

### PR DESCRIPTION
**Pull request by sarovin**
FIX #2951 
@ianwensink Can you test if this solve the problem?

### CODE REVIEW

**Comment by timneutkens** [comment]
This is great, thanks!

**Comment by ilionic** [comment]
@timneutkens just FIY: had 500 issues on Heroku on 4.3.0-canary.1 presumably because of this.
```
[App:server][Err] { Error: Cannot find module '/tmp/build_78af2ccc53825b13ac8b1cb1a1c1f63f/next-72573bfa9be5244f605175b7053b9db5cf85c7ae/node_modules/babel-runtime/core-js/object/get-prototype-of'
```
Switched to `4.2.1` and it's fine.

**Comment by huangbong** [comment]
@timneutkens @ilionic yup, also getting the same issue here on canary. reverting back to 4.2.1 works fine.

```
  5:56:39pm WARN retrying idempotent request stage: staging status: 500 version: 244
  5:56:39pm ERRO { Error: Cannot find module '/root/glade/packages/react/node_modules/babel-runtime/core-js/object/get-prototype-of'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/.next/dist/lib/withData.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' } stage: staging version: 244
  5:56:39pm ERRO { Error: Cannot find module '/root/glade/packages/react/node_modules/babel-runtime/helpers/extends'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/.next/dist/pages/index.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' } stage: staging version: 244
```

**Comment by ilionic** [comment]
@huangbong did you create separate issue by chance? As it could get lost here..

**Comment by sarovin** [comment]
Have you added babel-runtime to your package.json?

**Comment by ilionic** [comment]
Yes, tried `"babel-runtime": "^6.26.0"` Didn't solve the issue.

**Comment by sayuti-daniel** [comment]
Had same issue, reverting back to 4.2.1 solved it

**Comment by ilionic** [comment]
`4.2.1` solves the issue with babel-runtime, but having another issue ( which is solved on canary ) https://github.com/zeit/next.js/issues/3134 so quite a blocker for some time..

**Comment by jasonbarry** [comment]
A problem happened for me as well — I've created https://github.com/zeit/next.js/issues/3543 to track.

Unfortunately I can't roll back to 4.2.1, because I have many .jsx files in my project, support for which was introduced in 4.3.0-canary.1. 

I've created [a fork](https://github.com/jasonbarry/next.js/tree/canary-fix-dist) of 4.3.0-canary.1 with this PR rolled back, and that solved the problem for me. 

I hope this PR gets rolled back, or that the issue gets resolved upstream.

**Comment by timneutkens** [comment]
Created a PR to revert this.

**Pull request merged**
