### PR TITLE
fix(types): allow nonpromise return types for static functions

### LINKED ISSUE #24684: Types of getStaticPaths & getStaticProps needlessly enforce promises
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

unrelated

### Describe the Bug

All code related to typing `getStaticPaths` and `getStaticProps` currently enforce having `async` functions or using the individual types over the convenient `GetStaticProps`/`GetStaticPaths` types.

https://github.com/vercel/next.js/blob/0af3b52640/packages/next/types/index.d.ts#L110
https://github.com/vercel/next.js/blob/0af3b52640/packages/next/types/index.d.ts#L116
https://github.com/vercel/next.js/blob/0af3b52640/packages/next/types/index.d.ts#L132

However, it's a perfectly valid use case to use `getStaticProps` and/or `getStaticPaths` without loading something from external sources, which wouldn't require an async function.

This is of course really just a nitpick.

### Expected Behavior

```ts
import type { GetStaticPaths, GetStaticProps } from 'next';
type Report = null | { id: string };

export const getStaticPaths: GetStaticPaths = () => {
  return {
    fallback: true,
    paths: [],
  };
};

export const getStaticProps: GetStaticProps<{ report: Report }> = (ctx) => {
  if (!ctx.params?.id || !isValidReportId(ctx.params.id)) {
    return {
      props: {
        report: null,
      },
    };
  }

  return {
    props: {
      report: {
        report: ctx.params.id,
      },
    },
  };
};
```
Neither should error, since these work:

```ts
export const getStaticPaths = (): GetStaticPathsResult => {
  return {
    fallback: true,
    paths: [],
  };
};

export const getStaticProps = (
  ctx: GetStaticPropsContext
): GetStaticPropsResult<{ report: Report }> => {
  if (!ctx.params?.id || !isValidReportId(ctx.params.id)) {
    return {
      props: {
        report: null,
      },
    };
  }

  return {
    props: {
      report: {
        report: ctx.params.id,
      },
    },
  };
};
```

### To Reproduce

image
image

### PR DESCRIPTION
**Pull request by ljosberinn**
## Bug

- [x] fixes #24684
- [x] Integration tests added

Intentionally omitted changing the types for `GetServerSideProps` etc. as its imo less reasonable to leverage SSR with a sync `getServerSideProps`. Can of course change the type too if you consider that also a valid case.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test to `test/integration/typescript` for this change 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 15s | 14.9s | -182ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +73ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.683 | 2.666 | -0.02 |
| / avg req/sec | 931.78 | 937.7 | +5.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.531 | 1.571 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1632.97 | 1591.46 | ⚠️ -41.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 556 B | 556 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.4s | ⚠️ +55ms |
| buildDurationCached | 5.3s | 5.1s | -181ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -177ms |
| buildDurationCached | 5.8s | 5.7s | -74ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.774 | 2.814 | ⚠️ +0.04 |
| / avg req/sec | 901.17 | 888.39 | ⚠️ -12.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.587 | 1.643 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1574.82 | 1521.16 | ⚠️ -53.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.25 kB | 7.25 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.38 kB | 9.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: a29b5c9fc10cc40155e2fe9f60657b2a008ab602

**Review by timneutkens — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.9s | ⚠️ +4ms |
| buildDurationCached | 3.9s | 3.8s | -127ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.41 | 2.462 | ⚠️ +0.05 |
| / avg req/sec | 1037.28 | 1015.55 | ⚠️ -21.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.35 | 1.262 | -0.09 |
| /error-in-render avg req/sec | 1851.83 | 1980.89 | +129.06 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| index.html gzip | 561 B | 561 B | ✓ |
| link.html gzip | 569 B | 569 B | ✓ |
| withRouter.html gzip | 556 B | 556 B | ✓ |
| Overall change | 1.69 kB | 1.69 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16s | -204ms |
| buildDurationCached | 5s | 4.8s | -103ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 19.4 kB | 19.4 kB | ✓ |
| webpack-HASH.js gzip | 994 B | 994 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.02 kB | 1.02 kB | ✓ |
| _error-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 331 B | 331 B | ✓ |
| withRouter-HASH.js gzip | 329 B | 329 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 2.42 kB | 2.42 kB | ✓ |
| 500.html | 2.41 kB | 2.41 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.61 kB | 1.61 kB | ✓ |
| css.html | 1.79 kB | 1.79 kB | ✓ |
| hooks.html | 1.67 kB | 1.67 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +105ms |
| buildDurationCached | 5.3s | 5.2s | -40ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.45 | 2.474 | ⚠️ +0.02 |
| / avg req/sec | 1020.37 | 1010.6 | ⚠️ -9.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.249 | 1.311 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 2001.48 | 1907.36 | ⚠️ -94.12 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.25 kB | 7.25 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.74 kB | 3.74 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.38 kB | 9.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ljosberinn/next.js fix/allow-nonpromise-static-paths-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
Commit: d966caa8ca27f1426e5ad2d5794a66805eb9e81d

**Review by TeeBangCo — APPROVED** [review]

**Pull request merged**
