### PR TITLE
Fixed example `with-scoped-stylesheets-and-postcss`: css-modules reload update from files [name].css.json.

### PR DESCRIPTION
**Pull request by watcharakrit**
Hi @thomaslindstrom. require(fileName) is once load file when run next. after that when i change my css, a content <style> on header is change but css-modules that 

`import {classNames} from './styles.css'` 

is not update to a new css on hot reload (it will update when i close and run next again).

i think we can use "fs.readFileSync" instead "require(fileName)". 
`const classNames = fs.readFileSync(fileName, "utf8")`

### CODE REVIEW

**Comment by watcharakrit** [comment]
on Dev environment is ok, but when next build to production. UglifyJS have some Error with 

 **Unexpected character '`'**

and i update to disable uglifyJS for next build in this case that want to use css-modules.

**Review by timneutkens — APPROVED** [review]
@thomaslindstrom I'd love to have you review this 😄

**Comment by thomaslindstrom** [comment]
@timneutkens @watcharkrit Looks very good! 😄

**Comment by timneutkens** [comment]
@thomaslindstrom awesome 👌 merged

**Comment by watcharakrit** [comment]
@thomaslindstrom @timneutkens 👍  Thank you :)

**Pull request merged**
