### PR TITLE
fix: blurred image not positioned correctly when using object-position

### LINKED ISSUE #26309: Blurred image not positioned correctly when using object-position
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Blurred images are not respecting the objectPosition property in Image component

Full image: [Example Image](https://i.schoen.world/cVAqU.png)

**What I see:** 

### Expected Behavior

The blurred placeholder should have the save position as the the later loaded full image.

**What I expect:**

An easy fix for this would be to mirror the `object-position` value to the `background-position` value while loading.

### To Reproduce

Setup:

```jsx
import Image from 'next/image'

import exampleImg from '../data/example.png'

const Page = () => (
  <Image
    src={exampleImg}
    width={1024}
    height={700}
    layout="responsive"
    objectFit="cover"
    objectPosition="center"
    placeholder="blur"
  />
)

export default Page
```

Deployed example: [schoenwaldnils.vercel.app/objectPositionIssue](https://schoen-world-8793xnvzh-schoenwaldnils.vercel.app/objectPositionIssue)

### PR DESCRIPTION
**Pull request by DarkCode01**
## Bug

- [x] Related issues linked using `fixes #26309`

Fixes #26309

display correctly the image when use `objectPosition` and `placeholder="blur"`

### CODE REVIEW

**Comment by atcastle** [comment]
Thanks for the fix! the two next.config.js files don't need to be in the PR, and this could use integration test coverage.

**Comment by schoenwaldnils** [comment]
fixes #26309

**Comment by schoenwaldnils** [comment]
Can be closed. Fixed via #26590

**Comment by timneutkens** [comment]
Thanks @DarkCode01 @schoenwaldnils, I'll close this PR 👍

**Pull request closed without merging**
