### PR TITLE
OpenTelemetry: propagate context to sandbox

### PR DESCRIPTION
**Pull request by dvoytenko**
The sandboxed request processing do not share the same async context with the `BaseServer` and thus the context should be propagated independently.

Notably, the `headers` API is different in `BaseServer` (`Record<string, string | string[]>`) vs in the sandbox (`Headers`), so additionally, we have to use the right `getter`.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: b797ec85c2caf0c4b7ae9414178d7d871063a0b2

`pnpm test-dev test/e2e/edge-can-read-request-body/index.test.ts` 
- Edge can read request body > middleware > reads a JSON body
- Edge can read request body > middleware > reads an URL encoded form data
- Edge can read request body > middleware > reads a multipart form data

<details>
<summary>Expand output</summary>

  ● Edge can read request body › middleware › reads a JSON body

    expect(received).toMatchObject(expected)

    - Expected  -  3
    + Received  + 10

      Object {
        "headers": Object {
    -     "x-req-type": "json",
    -     "x-serialized": "{\"hello\":\"world\"}",
    +     "cache-control": "no-store, must-revalidate",
    +     "connection": "close",
    +     "content-encoding": "gzip",
    +     "content-type": "text/html; charset=utf-8",
    +     "date": "Wed, 22 Nov 2023 20:03:05 GMT",
    +     "etag": "\"dckw2o14wf3sn\"",
    +     "transfer-encoding": "chunked",
    +     "vary": "Accept-Encoding",
    +     "x-powered-by": "Next.js",
        },
    -   "status": 200,
    +   "status": 500,
        "text": StringContaining "ok",
      }

      40 |         }
      41 |       )
    > 42 |       expect(await serialize(response)).toMatchObject({
         |                                         ^
      43 |         text: expect.stringContaining('ok'),
      44 |         status: 200,
      45 |         headers: {

      at Object.toMatchObject (e2e/edge-can-read-request-body/index.test.ts:42:41)

  ● Edge can read request body › middleware › reads an URL encoded form data

    expect(received).toMatchObject(expected)

    - Expected  -  3
    + Received  + 10

      Object {
        "headers": Object {
    -     "x-req-type": "formData",
    -     "x-serialized": "{\"hello\":\"world\"}",
    +     "cache-control": "no-store, must-revalidate",
    +     "connection": "close",
    +     "content-encoding": "gzip",
    +     "content-type": "text/html; charset=utf-8",
    +     "date": "Wed, 22 Nov 2023 20:03:05 GMT",
    +     "etag": "\"fd0np3wfa03sn\"",
    +     "transfer-encoding": "chunked",
    +     "vary": "Accept-Encoding",
    +     "x-powered-by": "Next.js",
        },
    -   "status": 200,
    +   "status": 500,
        "text": StringContaining "ok",
      }

      88 |         }
      89 |       )
    > 90 |       expect(await serialize(response)).toMatchObject({
         |                                         ^
      91 |         text: expect.stringContaining('ok'),
      92 |         status: 200,
      93 |         headers: {

      at Object.toMatchObject (e2e/edge-can-read-request-body/index.test.ts:90:41)

  ● Edge can read request body › middleware › reads a multipart form data

    expect(received).toMatchObject(expected)

    - Expected  -  3
    + Received  + 11

      Object {
        "headers": Object {
    -     "x-req-type": "formData",
    -     "x-serialized": "{\"hello\":\"world\"}",
    +     "cache-control": "no-store, must-revalidate",
    +     "connection": "keep-alive",
    +     "content-encoding": "gzip",
    +     "content-type": "text/html; charset=utf-8",
    +     "date": "Wed, 22 Nov 2023 20:03:05 GMT",
    +     "etag": "\"wijojex4kz3sn\"",
    +     "keep-alive": "timeout=5",
    +     "transfer-encoding": "chunked",
    +     "vary": "Accept-Encoding",
    +     "x-powered-by": "Next.js",
        },
    -   "status": 200,
    +   "status": 500,
        "text": StringContaining "ok",
      }

      108 |       )
      109 |
    > 110 |       expect(await serialize(response)).toMatchObject({
          |                                         ^
      111 |         text: expect.stringContaining('ok'),
      112 |         status: 200,
      113 |         headers: {

      at Object.toMatchObject (e2e/edge-can-read-request-body/index.test.ts:110:41)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.2s | N/A |
| buildDurationCached | 5.9s | 6.5s | ⚠️ +619ms |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +2.85 kB |
| nextStartRea..uration (ms) | 417ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| 199-HASH.js gzip | 28.7 kB | 28.7 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 238 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 501 B | 503 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.28 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| index.html gzip | 527 B | 526 B | N/A |
| link.html gzip | 539 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 521 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.4 kB | 92.4 kB | N/A |
| page.js gzip | 145 kB | 145 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 625 B | ✓ |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 35.6 kB | ⚠️ +10.8 kB |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 27.4 kB | 38.2 kB | ⚠️ +10.8 kB |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | dvoytenko/next.js otel-propagation-worker | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 167 kB | 167 kB | ✓ |
| app-page-exp..prod.js gzip | 93.3 kB | 93.3 kB | ✓ |
| app-page-tur..prod.js gzip | 94 kB | 94 kB | ✓ |
| app-page-tur..prod.js gzip | 88.6 kB | 88.6 kB | ✓ |
| app-page.run...dev.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run..prod.js gzip | 87.9 kB | 87.9 kB | ✓ |
| app-route-ex...dev.js gzip | 23.8 kB | 23.8 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.5 kB | 16.5 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 23.2 kB | 23.2 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.8 kB | 21.8 kB | ✓ |
| server.runti..prod.js gzip | 49.1 kB | 49.1 kB | N/A |
| Overall change | 875 kB | 875 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: b797ec85c2caf0c4b7ae9414178d7d871063a0b2

**Review by timneutkens — CHANGES_REQUESTED** [review]
Seems the resolving for edge is missing `@opentelemetry/api` in https://github.com/vercel/next.js/blob/0cb1c404005de79b8cfbf3eac97e90616d5d4f45/packages/next-swc/crates/next-core/src/next_import_map.rs.

Will ask the Turbopack team to take a look

**Review by ForsakenHarmony — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks Leah!

**Pull request merged**
