### PR TITLE
Update 03-linking-and-navigating.mdx

### PR DESCRIPTION
**Pull request by MuneebStack**
Refactored and optimized section on routing and navigation in Next.js documentation. Moved Soft Navigation concept to Point 3, and introduced subheadings for Partial Rendering and Preserving States under Soft Navigation. Adjusted bullet sizes for better visual consistency. Organized and restructured the content to enhance clarity and readability.

### CODE REVIEW

**Comment by MuneebStack** [comment]
@molebox @ismaelrumzan Can you please look at the pull request? I opened it last month. Thanks.

**Comment by MuneebStack** [comment]
Hi @ijjk @toolmantim 

I kindly request you to take a moment to review the pull request when you have some time. Its been open from more than a month, and no maintainer has responded yet. Thanks

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, I'm not sure we want to change the heading formatting here as that will affect links relying on the previous header text.

**Comment by MuneebStack** [comment]
> Hi, I'm not sure we want to change the heading formatting here as that will affect links relying on the previous header text.

@ijjk  Thanks for responding. I think this information need to be clear in the documentation, because currently its confusing. 

Yes, I do agree, that these changes need to be done in other parts of the documentation also, where the previous links are attached. 

So, what's the best solution here? Should I go through the documentation and trace where the previous links are used??? So, we can replace them??

**Comment by leerob** [comment]
Thanks for the suggestion, but I believe it is okay structured as is 🙏

**Comment by MuneebStack** [comment]
Oky @leerob. Thank you.

**Pull request closed without merging**
