### PR TITLE
Add explicit support for custom server instance

### PR DESCRIPTION
**Pull request by sheerun**
This pull request introduces explicit support for custom server, but is much more than this.

1. Makes package.json scripts for custom server the same as for normal server
2. Gives back next.js control over custom server execution e.g. possiblity to:
    a) properly setup process.env from next.config.js before custom server code is even required (so hacks like in [with-sentry](https://github.com/zeit/next.js/blob/54f21e984dda51b77ecc5e5d1b051c50427a021f/examples/with-sentry/package.json#L4-L8) example are not needed)
    b) decorate custom server code with plugins (it can radically reduce complexity of examples)
3. Allows now.sh next launcher to easily support custom server
4. Allows easily running next with `@now/node` builder because custom server doesn't do `.listen()`
6. Potentially allows for writing custom server in es6 and bundling it for production
7. Simpler custom server code (no need reading PORT or calling .listen())
8. Custom server code can be imported directly into tests

And probably more nice things I haven't thought of. This change is 100% backward compatible especially it doesn't use `server.js` name you often used but "reserved" `next.server.js`

Before:

```
  "scripts": {
    "dev": "node next.server.js",
    "build": "next build",
    "start": "NODE_ENV=production node next.server.js"
  },
```

After:

```
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
```

Example `next.server.js`:

```es6
const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

module.exports = createServer((req, res) => {
  const parsedUrl = parse(req.url, true)
  const { pathname, query } = parsedUrl

  if (pathname === '/a') {
    app.render(req, res, '/a', query)
  } else if (pathname === '/b') {
    app.render(req, res, '/b', query)
  } else {
    handle(req, res, parsedUrl)
  }
})
```

### CODE REVIEW

**Comment by sheerun** [comment]
I've also updated custom-server example. If you like this solution I can update other examples

**Comment by sheerun** [comment]
Also for reference, here's example `now.json` that can be used to deploy such custom server app:

```json
{
  "version": 2,
  "builds": [{ "src": "next.server.js", "use": "@now/node" }],
  "routes": [{ "src": "/(.*)", "dest": "/" }]
}
```

Plus extra script in package.json:

```json
{
  "scripts": {
    "now-build": "next build"
  }
}
```

**Comment by sheerun** [comment]
Because in development .prepare() script needs to be called, I've added auto-preparing of server for first request. This way custom server code can be as described above (without prepare).

**Comment by sheerun** [comment]
I'm thinking about renaming next.server.js to index.js because that's what now expects (https://zeit.co/docs/v2/routing/directory-listing)

**Comment by MarchWorks** [comment]
There is many failing test. I think that this PR can be used to solve https://github.com/zeit/next.js/issues/6317

**Comment by timneutkens** [comment]
We're not pursuing adding custom server support to the `next` cli. Instead we're going to handle all cases for custom server inside of Next.js.

**Comment by sheerun** [comment]
My use case entirely depends on having custom server as-is without splitting application into serverless function that handle different pages..

**Comment by timneutkens** [comment]
> My use case entirely depends on having custom server as-is

Could you explain why? I'd like to know if I'm missing something.

**Comment by sheerun** [comment]
I need to handle fairly advanced use cases that can be handled easily only in custom server like i18n custom routing, handling legacy routes and redirects, doing proxy to different API services, normalizing routes to canonical urls, A/B testing setup, auto-redirecting to correct language given Accept-Language header, rendering "please upgrade" screen for legacy browsers, assigning session id cookie for each user, performing compression, rendering pre-rendered versions of page for different device types (phone, tablet, desktop), safeguards against DOS attacks, etc. etd.

Sorry but there's simple no way we can deploy our app without custom server and because we're trying to migrate to serverless we cannot use stack now provides (`@now/next`) but rather try to run next.js on top of `@now/node` build stack which works only if you don't need to do `.prepare()` for custom server.

**Pull request closed without merging**
