### PR TITLE
Migrated svg-components to App-router

### PR DESCRIPTION
**Pull request by Hemanshu-Upadhyay**
Hello! This PR Contains the Following Changes

=> svg-components Example Migrated to App-Router
=> Added the layout.tsx file as part of the App Router.
=> Folder Structure Updated to support APP-Router convention
=> File Convention updated to Support the APP-Router convention
=> Npm package got updated "@svgr/webpack": "^6.2.1", to "@svgr/webpack": "^6.5.1",

CC- @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 183c3bb1cee992486d8da936e3f670918c6c2d54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@Hemanshu-Upadhyay Have you tried upgrading all the packages to the latest (e.g., https://github.com/gregberge/svgr/releases/tag/v8.1.0)?

**Comment by Hemanshu-Upadhyay** [comment]
Updated All the Packages
CC - @samcx

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

:lfgtm

**Pull request merged**
