### PR TITLE
Adding time-slicing with `startTransition` to prevent hydration from blocking the main thread for too long for those users who immediately scroll.

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hi,

This is updated/corrected version of https://github.com/vercel/next.js/pull/38698 .

_Extremely sorry if there are any mistakes :(_

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Closing as it appears the build is failing here and as mentioned in [previous PRs](https://github.com/vercel/next.js/pull/39333#pullrequestreview-1062519541) it'd be good to open a discussion thread for changes like this first! 

Note this is also being handled differently in the new router already.

**Comment by sanjaiyan-dev** [comment]
> Closing as it appears the build is failing here and as mentioned in [previous PRs](https://github.com/vercel/next.js/pull/39333#pullrequestreview-1062519541) it'd be good to open a discussion thread for changes like this first!
> 
> Note this is also being handled differently in the new router already.

Sorry 😞💪🙌

**Comment by sanjaiyan-dev** [comment]
> Closing as it appears the build is failing here and as mentioned in [previous PRs](https://github.com/vercel/next.js/pull/39333#pullrequestreview-1062519541) it'd be good to open a discussion thread for changes like this first!
> 
> Note this is also being handled differently in the new router already.

Can we use new router currently?!

**Comment by ijjk** [comment]
Not yet, the related RFC for it can be seen here https://github.com/vercel/next.js/discussions/37136

**Comment by sanjaiyan-dev** [comment]
> Not yet, the related RFC for it can be seen here #37136

Okay, Thanks 🙏

**Comment by sanjaiyan-dev** [comment]
> Not yet, the related RFC for it can be seen here #37136

Sorry,

Then `experimental.appDir = true` is for any other feature?! 🥺

**Comment by sanjaiyan-dev** [comment]
> > Not yet, the related RFC for it can be seen here #37136
> 
> Sorry,
> 
> Then `experimental.appDir = true` is for any other feature ?🥺

**Pull request closed without merging**
