### PR TITLE
fix: should allow nullable param for res.end

### LINKED ISSUE #28693: unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

After upgrading to `next` 11.1.0, I started getting this error:

```js
error - unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined    at Function.byteLength (buffer.js:727:11)
    at ServerResponse.apiRes.end (C:\path-to-project\node_modules\next\dist\server\api-utils.js:73:41)
    at writeend (C:\path-to-project\node_modules\express-session\index.js:262:22)
    at ontouch (C:\path-to-project\node_modules\express-session\index.js:353:11)
    at C:\path-to-project\node_modules\connect-mongo\build\main\lib\MongoStore.js:339:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
```

The code below found in `server/api-utils.ts` is not accounting for the possibility of the first parameter `args[0]` being `undefined`. Since the if condition does not cover such scenario, calling `Buffer.byteLength` with `undefined` will result in an error because `args[0]` type is not a supported type ([supported types are: `String`, `Buffer`, `TypedArray`, `DataView`, `ArrayBuffer`](https://nodejs.org/dist./v6.3.0/docs/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding)).

```js
  apiRes.end = (...args: any[2]) => {
    if (args.length && typeof args[0] !== 'function') {
      contentLength += Buffer.byteLength(args[0])
    }
```

### Expected Behavior

No error should happen

### To Reproduce

I was able to reproduce this in my app in development that uses:
- `next` 11.1.0
- `express-session` 
- `connect-mongo` session store
- `passport`
- `next-connect`

After logging in and navigating around.

With `next` 11.0.1, this error does not occur.

### PR DESCRIPTION
**Pull request by huozhi**
## Bug
Fixes #28693

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.3s | -43ms |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +14ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.99 | 2.974 | -0.02 |
| / avg req/sec | 836.1 | 840.75 | +4.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.849 | 1.832 | -0.02 |
| /error-in-render avg req/sec | 1352.23 | 1364.66 | +12.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.1s | -320ms |
| buildDurationCached | 5.6s | 5.7s | ⚠️ +72ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.052 | 3.012 | -0.04 |
| / avg req/sec | 819.24 | 829.88 | +10.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.827 | 1.856 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1368.35 | 1346.7 | ⚠️ -21.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | huozhi/next.js fix/override-send | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 3c230b8bce3f04454cfa581034f4c742e193514b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3c230b8bce3f04454cfa581034f4c742e193514b

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > logbox: can recover from a syntax error without losing state
-  > <Link> component props errors

<details>
<summary>Expand output</summary>

  ● logbox: can recover from a syntax error without losing state

    expect(received).toBe(expected) // Object.is equality

    Expected: "Count: 1"
    Received: "1"

      46 |       import { useCallback, useState } from 'react'
      47 |
    > 48 |       export default function Index() {
         |        ^
      49 |         const [count, setCount] = useState(0)
      50 |         const increment = useCallback(() => setCount(c => c + 1), [setCount])
      51 |         return (

      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:48:8)

  ● <Link> component props errors

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      845 |   expect(await session.hasRedbox(true)).toBe(true)
      846 |   const source = await session.getRedboxSource()
    > 847 |   expect(source).toMatch('./index.module.css:1:1')
          |                                       ^
      848 |   expect(source).toMatch('Syntax error: ')
      849 |   expect(source).toMatch('Unclosed block')
      850 |   expect(source).toMatch('> 1 | .button {')

      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:847:39)

</details>

**Review by timneutkens — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by mariohmol** [comment]
Hi there!! Thanks for it!

Getting this error in production, I made this change directly on node_modules and it worked!!

Can you tell me when this will be released?

thanks!

**Comment by styfle** [comment]
You can try it out today on the canary channel with “yarn add next@canary”

**Pull request merged**
