### PR TITLE
[with-apollo] simplify apolloState prop

### PR DESCRIPTION
**Pull request by klujanrosas**
As seen on `with-apollo-auth` there are some things that need to be addressed here too.

* #4554 remove useless `apolloState` from App props on `getDataFromTree`
* #4563 simplify `apolloState` prop

Let me know if further changes/fixes are needed. 
Thank you :tada:

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]
lgtm

**Review by Skaronator — APPROVED** [review]
LGTM, works fine!

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks!

**Pull request merged**
