### PR TITLE
Add Ready component to handle loading across pages.

### LINKED ISSUE #238: Add a loading indicator between <Link /> navigations
When we click on a link it might take a time to load. I just peek through the code and it seems to do two async ops mainly:

* Fetch the code
* Fetch data

So, we need to show a loading indicator between that time.
This is my suggestion.

```js
import React from 'react';
import Ready from 'next/ready';
import Header from '../components/Header';

const Loading = () => (<p>Loading...</p>);

export default () => (
  <div>
    /* Render all links */
    <Header onLoading={Loading}/>
    <Ready>
      <p>Hello Home Page</p>
    </Ready>
  </div>
);
```

If there's a link navigation request, Ready component will show the Loading component.

What do you guys think?

### EDIT 2

I'm working on a new PR with just using `<Link />`: https://github.com/zeit/next.js/pull/250

### EDIT 1

Here's the solution for this issue: https://github.com/zeit/next.js/pull/242

### PR DESCRIPTION
**Pull request by arunoda**
Fixes #238 

Basically this allows us to show a loading screen when switching between pages.
Here's how to use this:

```jsx
import React from 'react';
import Ready from 'next/ready';
import Header from '../components/header.js';

const Loading = () => (<p>It's coming...</p>);

export default () => (
  <div>
    <Header />
    <Ready loadingHandler={Loading}>
      <p>Hello Next!</p>
    </Ready>
  </div>
);
```

### CODE REVIEW

**Comment by mattapperson** [comment]
It would be great if this assisted in animations between pages too...

**Comment by rauchg** [comment]
From the original issue:

```
When we click on a link it might take a time to load. I just peek through the code and it seems to do two async ops mainly:

Fetch the code
Fetch data
```

Keep in mind that the "fetch the data" part is optional. One can go ahead and do:

```
getInitialProps({ req }) {
```

**Comment by rauchg** [comment]
In other words, maybe we have to make `onLink` more powerful by adding more events (currently it doesn't have `onClick` even)

**Comment by arunoda** [comment]
Okay. Basically, you mean loading stuff is out of the scope of Next.
I get your point with doing something with doing something similar with `<Link />`

Let' say we have a lot of Links elements on the page. Then we have to add hooks for many links.

Practically, I'd like to add this loading capability into a layout in my app.
So, it's better to control this from a central API.

May be we could expose a `Router` instance and emit these events.

**Comment by mattapperson** [comment]
@arunoda in that instance couldn't you just create a new component that just wraps `<Link>`?

**Comment by rauchg** [comment]
@arunoda the problem of adding hooks to many links is very trivially solved:

```
import Link from './my-link'
export default () => (
  <p>Hi there, my fancy <Link><a>here</a></Link></p>
)
```

this link could do a lot of interesting things that are shared across pages. Not least of which is showing a spinner or Medium-style bar for transitions between pages:

https://twitter.com/rauchg/status/797577535370317825

for which I would love to have an example on the wiki.

**Comment by rauchg** [comment]
I suspect that creating that example would force us to design the proper hooks on `<Link>`

**Comment by arunoda** [comment]
Okay guys, yep. I got the way we need to this via `<Link />`.

In order to do that, I hope we need one last feature for Link (or a way to to get it from somewhere else in a nice way).
That's a way to know the page switching has been completed.

We can do it by hooking into the History API, or React components. But adding good API with links makes sense a lot.

Here's an suggestion:

```jsx
const startLoading = () => console.log("Start Loading");
const stopLoading = () => console.log("Stop Loading");
<Link onClick={startLoading} onStop={stopLoading}/>
```

**Comment by arunoda** [comment]
Guys, I think we could close this PR.
I'm working on this new PR: https://github.com/zeit/next.js/pull/250

**Comment by timneutkens** [comment]
As you can see you're commenting on a closed pull-request, not a merged one. So this proposal was never added to Next.js.

You're probably looking for https://github.com/zeit/next.js#3-with-no-ssr

**Pull request closed without merging**
