### PR TITLE
Update example middleware file redirect

### PR DESCRIPTION
**Pull request by maslowivan**
The current example contains the redirect loop bug when it throws you to /en// first, then /en/ then /en

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 30d9e244592b37cff15ce75fc6b8aa3f6300988f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 30d9e244592b37cff15ce75fc6b8aa3f6300988f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 30d9e244592b37cff15ce75fc6b8aa3f6300988f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — COMMENTED** [review]
Closing as this has already been updated in a separate PR, thanks though!

**Pull request closed without merging**
