### PR TITLE
Bugfix: Babel targets value can be a String

### LINKED ISSUE #8255: nextjs v9 babel config doesn't allow for certain browserlist queries
# Bug report

when upgrading from nextjs 8.x to 9.0.3 something about browserslist support inside the babel preset changed

## Describe the bug

This error manifests: `Cannot use 'in' operator to search for 'node' in >1% in US and not ie 11` for this babel config:

```js
module.exports = {
  presets: [
    [
      'next/babel',
      {
        'preset-env': {
          targets: '>1% in US and not ie 11',
          modules: false,
        },
      },
    ],
  ],
};
```

## To Reproduce

Create a nextjs project with the above babel config

## Expected behavior

The app compiles successfully

## Screenshots

n/a

## System information

- OS: macOS latest stable
- Browser (if applies) n/a
- Version of Next.js: 9.0.3

### PR DESCRIPTION
**Pull request by developit**
Fix modern SSR build when Babel configuration uses a String value for "targets". Fixes #8255.

### CODE REVIEW

**Comment by timneutkens** [comment]
Might make sense to add a test

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 20.8s | 20.8s | -26ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.7 kB | 59.7 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.39 kB | 5.39 kB | ✓ |
| Client `main` Modern Size | 12.7 kB | 12.7 kB | ✓ |
| Client `main` Modern gzip Size | 4.77 kB | 4.77 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `commons` Modern Size | 168 kB | 168 kB | ✓ |
| Client `commons` Modern gzip Size | 54.9 kB | 54.9 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.38 MB | 1.38 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 21.8s | 22.1s | ⚠️  +266ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.7 kB | 59.7 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.39 kB | 5.39 kB | ✓ |
| Client `main` Modern Size | 12.7 kB | 12.7 kB | ✓ |
| Client `main` Modern gzip Size | 4.77 kB | 4.77 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `commons` Modern Size | 168 kB | 168 kB | ✓ |
| Client `commons` Modern gzip Size | 54.9 kB | 54.9 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 253 kB | 253 kB | ✓ |
| Serverless `pages/link` gzip Size | 68.1 kB | 68.1 kB | -1 B |
| Serverless `pages/index` Size | 246 kB | 246 kB | ✓ |
| Serverless `pages/index` gzip Size | 65.9 kB | 65.9 kB | -1 B |
| Serverless `pages/_error` Size | 246 kB | 246 kB | ✓ |
| Serverless `pages/_error` gzip Size | 65.7 kB | 65.7 kB | -2 B |
| Serverless `pages/routerDirect` Size | 247 kB | 247 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 65.9 kB | 65.9 kB | -1 B |
| Serverless `pages/withRouter` Size | 247 kB | 247 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66 kB | 66 kB | -1 B |
| Build Dir Size | 2.58 MB | 2.58 MB | ✓ |

</details>

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 22.2s | 22.5s | ⚠️  +273ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 23.7s | 23.6s | -63ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ✓ |
| Serverless `pages/link` gzip Size | 68.6 kB | 68.6 kB | ⚠️  +2 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +2 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.1 kB | ⚠️  +2 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +2 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +2 B |
| Build Dir Size | 2.59 MB | 2.59 MB | ✓ |

</details>

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 24.9s | 24.9s | -7ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | developit/next.js bugfix/server-browserslist | Change |
| - | - | - | - |
| Build Duration | 26.7s | 27.3s | ⚠️  +626ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +140 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ✓ |
| Serverless `pages/link` gzip Size | 68.6 kB | 68.6 kB | -1 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | -1 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.1 kB | ✓ |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.3 kB | ✓ |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.4 kB | -2 B |
| Build Dir Size | 2.59 MB | 2.59 MB | ✓ |

</details>

**Comment by developit** [comment]
(note: tests passing on Node 10, failing on 8 same as `canary`)

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Thanks!

**Pull request merged**
