### PR TITLE
fix: multi zone hmr

### LINKED ISSUE #32634: with-zones example causes WebSocket connection fail (HMR) when visiting proxied path
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

Following the instructions in the "with-zones" example and navigating to `/blog` will case the repeating warning to be displayed:
```
WebSocket connection to 'ws://localhost:3000/blog/_next/webpack-hmr' failed: WebSocket is closed before the connection is established.
```
Also because of this HMR is not working when editing files in the `blog` Next.js app.

### Expected Behavior

The HMR client should probably reconnect to the proxied apps HMR server automatically?

### To Reproduce

Clone https://github.com/vercel/next.js/tree/canary/examples/with-zones and follow the instructions to start both Next.js apps in dev mode (`next dev`). Open `http://localhost:3000` in a browser and navigate to `blog`. Wait on the WebSocket connection fail warning to display in the console.

### PR DESCRIPTION
**Pull request by teovillanueva**
## Bug

- [x] Related issues linked using fixes #32634

### CODE REVIEW

**Comment by sioquim** [comment]
Would be good to see this merged soon. We have the same issue with multizones and we can't upgrade to version 12 😢

**Comment by filipe-gomes** [comment]
We are in the same boat. Would love to see this released

**Comment by teovillanueva** [comment]
🙃

**Review by ijjk — COMMENTED** [review]
Hi, it looks like we may want to instead handle proxying WebSocket requests for rewrites as this will only work for very specific rewrites, it would also be good to have a test case for this as well.

**Comment by rszemplinski** [comment]
So the problem with not allowing something like this through is that you advertise `app zoning` which is awesome except you can't enjoy the `HMR` features cause the websocket requests can't be proxied "out-of-the-box". If you decide to go with this route which is totally fine, I recommend on your docs to add a side note saying that `HMR` doesn't work and a code snippet showing the workaround using a custom server.

**Comment by rszemplinski** [comment]
Is it possible to let the user handle websocket requests inside middleware in the future?

**Review by ijjk — COMMENTED** [review]
Hi, thanks for the PR, to handle this more verbosely I opened an alternative PR here https://github.com/vercel/next.js/pull/39463 which will ensure we handle rewriting WebSocket requests regardless of the `source` used.

**Pull request closed without merging**
