### PR TITLE
Updated staticMarkup usage on Head and NextScript

### PR DESCRIPTION
**Pull request by EugeneKostrikov**
Sets up #5054 for version 6.x.x

### CODE REVIEW

**Comment by timneutkens** [comment]
We only merge into the canary branch.

**Comment by EugeneKostrikov** [comment]
Ah ok, fine. Will migrate then.

**Comment by jepser** [comment]
@EugeneKostrikov is this going to implemented, and could you guide me how? I can't find any docs about this @timneutkens

**Comment by linweigao** [comment]
Is this feature released? I am looking for exactly this feature.

**Comment by goldo** [comment]
@EugeneKostrikov @linweigao same here! 
has anyone found out ? I tried this without success: 
```
// next.config.js
module.exports = {
  exportPathMap: defaultPathMap => ({
    '/': { page: '/', staticMarkup: true },
  }),
}
```

**Pull request closed without merging**
