### PR TITLE
Update 02-dynamic-routes.mdx

### PR DESCRIPTION
**Pull request by Heidar-An**
grammatical mistake

### What?
Small grammatical mistake on https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes

### CODE REVIEW

**Review by ztanner — APPROVED** [review]

**Comment by Heidar-An** [comment]
what does this check failure mean?

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 75aa43aec30bd0ead7573e5ab113426507979e50

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by Heidar-An** [comment]
why are these tests all failing?

**Comment by ztanner** [comment]
@Heidar-An no worries, nothing you need to fix! Thank you for the PR

**Pull request merged**
