### PR TITLE
[WIP] refactor: replace ajv with zod

### PR DESCRIPTION
**Pull request by SukkaW**
This is an **ongoing** PR that replaces Next.js' `ajv` based config validation with the Zod (which is already a dependency of Next.js).

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c87e9b654e2fe69dabdcd9c0a05b96db57ba357a

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by feedthejim** [comment]
One thing to note is that I'm working on bundling the parts of Next.js into split bundles for perf reasons. Zod is a deps, but only for the app router layer at the moment. This would bring it to the build/server layer I think, which is probably fine, just flagging.

Is AJV much worse than zod in terms of size/perf?

**Comment by SukkaW** [comment]
> One thing to note is that I'm working on bundling the parts of Next.js into split bundles for perf reasons. Zod is a deps, but only for the app router layer at the moment. This would bring it to the build/server layer I think, which is probably fine, just flagging.
> 
> Is AJV much worse than zod in terms of size/perf?

My initial idea is to reduce the `node_modules` installation size, and having two libraries (both `ajv` and `zod`) doing the same validation thing is not ideal.

Besides, Zod's schema is much easier to write and maintain compares to ajv's schema, and the typescript support is also much better.

**Comment by belgattitude** [comment]
Worth to share https://github.com/moltar/typescript-runtime-type-benchmarks for impact. Zod is probably the most convenient.

**Pull request closed without merging**
