### PR TITLE
Update Koa example for Koa 2 with async/await

### LINKED ISSUE #1314: Update Koa example for Koa 2
Example code can be found here:
#1303

### PR DESCRIPTION
**Pull request by aranajhonny**
Fixes #1314

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Thank you very much! 👍

**Comment by timneutkens** [comment]
Ran lint locally since travis doesn't have logs atm 😥 . No errors.

**Comment by aranajhonny** [comment]
travis failed because AWS s3 is down.

**Comment by timneutkens** [comment]
Yeah I guessed so 😄

**Pull request merged**
