### PR TITLE
Add experimental caseSensitiveRoutes config

### PR DESCRIPTION
**Pull request by ijjk**
This adds an experimental `caseSensitiveRoutes` config that currently applies for `rewrites`, `redirects`, and `headers` to change the default of case-insensitive. 

x-ref: [slack thread](https://vercel.slack.com/archives/C02K2HCH5V4/p1686080359514479?thread_ts=1686077053.623389&cid=C02K2HCH5V4)
x-ref: [slack thread](https://vercel.slack.com/archives/C057RG6Q9MX/p1686078875948069?thread_ts=1686077882.133609&cid=C057RG6Q9MX)
x-ref: https://github.com/vercel/next.js/issues/21498

### CODE REVIEW

**Review by huozhi — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: cb17eb924a49c6fdf1cd71b04aacffc24d8b8471

`pnpm testheadless test/integration/css-modules/test/index.test.js` 

<details>
<summary>Expand output</summary>

  ● Test suite failed to run

    The name `source-map` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or exclude files until there remains only one of these:

      * `/root/actions-runner/_work/next.js/next.js/packages/next/src/compiled/source-map/package.json` (package)
      * `/root/actions-runner/_work/next.js/next.js/test/integration/app-dir-export/.next/standalone/packages/next/dist/compiled/source-map/package.json` (package)

      at ModuleMap._assertNoDuplicates (../node_modules/.pnpm/jest-haste-map@27.5.1/node_modules/jest-haste-map/build/ModuleMap.js:230:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by pkellner — COMMENTED** [review]
I have a proxy server running in front of my nextjs (<13) because https://../Sessions is currently treated differently then https://../sessions. I would think that would be sensative defaulting to true and it looks to me like the default here is false (not true)

**Comment by ijjk** [comment]
The default isn't changed here as that's a potential breaking change. If `Sessions` is a filesystem path and you are hosting on a case-sensitive file-system then that is already case-sensitive this is specifically for rewrites/redirects/headers case-sensitivity.

**Comment by pkellner** [comment]
@ijjk My issue has always been around doing my dev work on a non-case sensitive file system, and then deploying to case sensitive (and the other way when going from developing on linux a long time ago to deploy on docker/linux).  AT one point, I tried putting in thousands of redirects for things like `https://www.siliconvalley-codecamp.com/Session/2019/Evolution-of-JavaScript-Modules` to always go to `https://www.siliconvalley-codecamp.com/Session/2019/evolution-of-javascript-modules` but that caused a world of hurt for me.

I'm hoping you are covering the case of taking whatever comes into a web site and lowercasing what gets interpreted by routing. I know I'm not alone with this issue.  My node proxy server I put in front of my site does that for me, but it would be nice not to have to do that.  Am I making sense? happy to explain more if not.

**Pull request merged**
