### PR TITLE
Fully static export

### PR DESCRIPTION
**Pull request by jepser**
Enable fully static export by adding the property to the configuration object.

``` js
module.exports = {
  staticMarkup: true
}
```

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
> Have in mind that `getInitialProps` won't be called

What's the reasoning behind this? Can't it be run during export?

**Comment by jepser** [comment]
Probably I need to be clearer, @sebastiandedey by setting `staticMarkup` to true, instead of `renderToString` in the export, it will run `renderToStaticMarkup`, so if you do client routing, it won't work as expected (running `getInitalProps`).

**Comment by timneutkens** [comment]
So there are a few things that come to mind:

- This PR only implements `staticMarkup` for `next export`, it should also work in development / production mode
- `staticMarkup` doesn't make it immediately clear what this option does

```
> Have in mind that `getInitialProps` won't be called and all React bindings won't work. This will be a only html/css export.
```

Instead of saying getInitialProps won't be called, which is not completely true as we call it on `next export`, this would probably be a better explanation:

> When enabling `staticMarkup` mode no script tags will be included in the rendered HTML, this is useful when creating a completely static application with no runtime.

**Comment by jepser** [comment]
@timneutkens that makes sense, let me update the PR.

**Comment by pengshaosu** [comment]
> So there are a few things that come to mind:
> 
> * This PR only implements `staticMarkup` for `next export`, it should also work in development / production mode
> * `staticMarkup` doesn't make it immediately clear what this option does
> 
> ```
> > Have in mind that `getInitialProps` won't be called and all React bindings won't work. This will be a only html/css export.
> ```
> Instead of saying getInitialProps won't be called, which is not completely true as we call it on `next export`, this would probably be a better explanation:
> 
> > When enabling `staticMarkup` mode no script tags will be included in the rendered HTML, this is useful when creating a completely static application with no runtime.

if only disable getInitialProps call on SSR, the client side still working. how can configure?

**Comment by pengshaosu** [comment]
@

> Enable fully static export by adding the property to the configuration object.
> 
> ```js
> module.exports = {
>   staticMarkup: true
> }
> ```
this useful function is still not working/ok now?

**Comment by jepser** [comment]
Sure, I'm working on that, HMR breaks as removing some scripts that are not needed when removing React, so I'm still working on solving that issue.

I saw `staticMarkup` property is under [`next-server`](https://github.com/zeit/next.js/blob/canary/packages/next-server/server/next-server.ts#L24) as a flag, do you know that served the same purpose because I don't see any example? @timneutkens

**Comment by goldo** [comment]
I'm also looking for a feature like this! 
For now I've forked next.js only for something that looks a bit like:
https://github.com/zeit/next.js/pull/5102

@timneutkens can you tell me more about your idea ? I'd love to help and make a PR!

**Pull request closed without merging**
