### PR TITLE
Fix hydration issue in the switchable runtime tests

### PR DESCRIPTION
**Pull request by shuding**
In this test we are mainly focusing on the SSR'd result so hydration is't critical, but it will definitely help to get rid of these hydration errors.

## Bug

- [ ] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 003f9547402174f9c854f300fb86ba2669e4c390

`yarn testheadless test/integration/react-streaming-and-server-components/test/switchable-runtime.test.js` 
- Without global runtime configuration > should build /static as a static page with the nodejs runtime
- Without global runtime configuration > should build /node as a static page with the nodejs runtime
- Without global runtime configuration > should build /node-ssr as a dynamic page with the nodejs runtime
- Without global runtime configuration > should build /node-ssg as a static page with the nodejs runtime
- Without global runtime configuration > should build /node-rsc as a static page with the nodejs runtime
- Without global runtime configuration > should build /node-rsc-ssr as a dynamic page with the nodejs runtime
- Without global runtime configuration > should build /node-rsc-ssg as a static page with the nodejs runtime
- Without global runtime configuration > should build /edge as a dynamic page with the edge runtime
- Without global runtime configuration > should build /edge-rsc as a dynamic page with the edge runtime

<details>
<summary>Expand output</summary>

  ● Without global runtime configuration › should build /static as a static page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:49:5)

  ● Without global runtime configuration › should build /node as a static page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:56:5)

  ● Without global runtime configuration › should build /node-ssr as a dynamic page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:63:5)

  ● Without global runtime configuration › should build /node-ssg as a static page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:70:5)

  ● Without global runtime configuration › should build /node-rsc as a static page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:77:5)

  ● Without global runtime configuration › should build /node-rsc-ssr as a dynamic page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:84:5)

  ● Without global runtime configuration › should build /node-rsc-ssg as a static page with the nodejs runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:91:5)

  ● Without global runtime configuration › should build /edge as a dynamic page with the edge runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:98:5)

  ● Without global runtime configuration › should build /edge-rsc as a dynamic page with the edge runtime

    TypeError: Cannot read property '1' of null

      16 | async function testRoute(appPort, url, { isStatic, isEdge }) {
      17 |   const html1 = await renderViaHTTP(appPort, url)
    > 18 |   const renderedAt1 = +html1.match(/Time: (\d+)/)[1]
         |                                   ^
      19 |   expect(html1).toContain(`Runtime: ${isEdge ? 'Edge' : 'Node.js'}`)
      20 |
      21 |   const html2 = await renderViaHTTP(appPort, url)

      at testRoute (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:18:35)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:105:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.8s | ⚠️ +276ms |
| buildDurationCached | 6.1s | 6.1s | ⚠️ +82ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.091 | 3.107 | ⚠️ +0.02 |
| / avg req/sec | 808.84 | 804.56 | ⚠️ -4.28 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.371 | 1.357 | -0.01 |
| /error-in-render avg req/sec | 1824.11 | 1842.59 | +18.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 19s | 18.9s | -59ms |
| buildDurationCached | 6.1s | 6.1s | -3ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.092 | 3.085 | -0.01 |
| / avg req/sec | 808.47 | 810.32 | +1.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.347 | 1.345 | 0 |
| /error-in-render avg req/sec | 1855.58 | 1858.31 | +2.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 003f9547402174f9c854f300fb86ba2669e4c390

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.4s | ⚠️ +99ms |
| buildDurationCached | 6.3s | 6.8s | ⚠️ +469ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.306 | 3.27 | -0.04 |
| / avg req/sec | 756.27 | 764.52 | +8.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.436 | 1.455 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1741.33 | 1718.52 | ⚠️ -22.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 20.1s | 20.1s | -17ms |
| buildDurationCached | 6.2s | 6.2s | -16ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.305 | 3.269 | -0.04 |
| / avg req/sec | 756.43 | 764.8 | +8.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.462 | 1.455 | -0.01 |
| /error-in-render avg req/sec | 1710.28 | 1717.79 | +7.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 04641f3cc490c402e48f064f8ad022d173e1a096

**Review by huozhi — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 21.6s | 21.8s | ⚠️ +201ms |
| buildDurationCached | 8.3s | 8.2s | -28ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.668 | 4.58 | -0.09 |
| / avg req/sec | 535.56 | 545.86 | +10.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.354 | 2.173 | -0.18 |
| /error-in-render avg req/sec | 1061.84 | 1150.66 | +88.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| buildDuration | 26.3s | 26.2s | -93ms |
| buildDurationCached | 8.3s | 8.2s | -72ms |
| nodeModulesSize | 467 MB | 467 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.643 | 4.688 | ⚠️ +0.04 |
| / avg req/sec | 538.47 | 533.24 | ⚠️ -5.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.253 | 2.29 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1109.77 | 1091.91 | ⚠️ -17.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1670 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 7f1478e31e239eba399d4f48f8102ade081c9067

**Pull request merged**
