### PR TITLE
Minimal dep upgrade - avoid alpha/beta, use the latest minor

### PR DESCRIPTION
**Pull request by chulkilee**
- Remove mkdirp (closes #17042)
- [@ampproject/toolbox-optimizer](https://github.com/ampproject/amp-toolbox/releases): 2.7.3=> 2.7.3
- [browserslist](https://github.com/browserslist/browserslist/blob/main/CHANGELOG.md): 4.14.6 => 4.16.1
- [sass-loader](https://github.com/webpack-contrib/sass-loader/releases): 10.0.5 => 10.1.1
- [watchpack](https://github.com/webpack/watchpack/releases): 2.0.0-beta.13 => 2.1.0
- [chokidar](https://github.com/paulmillr/chokidar/releases): 3.4.3 => 3.5.1
- [styled-jsx](https://github.com/vercel/styled-jsx/releases): 3.3.2 => 3.4.1
- [postcss](https://github.com/postcss/postcss/releases): 8.1.7 => 8.2.4

(see links for changelog / releases)

I ran `yarn && ./check-pre-compiled.sh` after updating deps. Let me know if I need to something else!

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| buildDuration | 9.9s | 10.3s | ⚠️ +401ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | -38 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.977 | 2.037 | ⚠️ +0.06 |
| / avg req/sec | 1264.67 | 1227.21 | ⚠️ -37.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.227 | 1.261 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2037.1 | 1982.59 | ⚠️ -54.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.2s | -411ms |
| nodeModulesSize | 82.6 MB | 82.6 MB | -38 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: 3c115605d58d24296089d6342e9cb097a758f72d

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f4cade91c208623638093b8405db3d20b05ceded

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      316 | 
      317 | export async function stopApp(server) {
    > 318 |   if (server.__app) {
          |              ^
      319 |     await server.__app.close()
      320 |   }
      321 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:318:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| buildDuration | 8.5s | 8.4s | -93ms |
| nodeModulesSize | 77.6 MB | 77.8 MB | ⚠️ +212 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.683 | 1.666 | -0.02 |
| / avg req/sec | 1485.2 | 1500.43 | +15.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.15 | 1.039 | -0.11 |
| /error-in-render avg req/sec | 2174.37 | 2406.87 | +232.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9e3e4e6..2023.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| polyfills-af..9390.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| buildDuration | 9.9s | 9.6s | -253ms |
| nodeModulesSize | 77.6 MB | 77.8 MB | ⚠️ +212 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9e3e4e6..2023.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| polyfills-af..9390.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.5s | ⚠️ +322ms |
| nodeModulesSize | 77.6 MB | 77.8 MB | ⚠️ +222 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.69 | 1.666 | -0.02 |
| / avg req/sec | 1479.38 | 1500.79 | +21.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.047 | 1.033 | -0.01 |
| /error-in-render avg req/sec | 2387.27 | 2420.26 | +32.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| 597-3bd7d6bd..868b.js gzip | 13 kB | 13 kB | ✓ |
| 778-d412f8e7..3ee1.js gzip | 6.56 kB | 6.56 kB | ✓ |
| 838-adcbad39..6e83.js gzip | 31.1 kB | 31.1 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-6a6a792..6877.js gzip | 96 B | 96 B | ✓ |
| webpack-e302..54e9.js gzip | 954 B | 954 B | ✓ |
| Overall change | 91 kB | 91 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| polyfills-a0..538c.js gzip | 88 B | 88 B | ✓ |
| Overall change | 88 B | 88 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | chulkilee/next.js dep-upgrade-minimal | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "LdsUt9VGnfSFoS4lAgwON",
+        "buildId": "lS4B0j-pAfLzAhhA1ZRz9",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_buildManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_ssgManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "LdsUt9VGnfSFoS4lAgwON",
+        "buildId": "lS4B0j-pAfLzAhhA1ZRz9",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_buildManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_ssgManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "LdsUt9VGnfSFoS4lAgwON",
+        "buildId": "lS4B0j-pAfLzAhhA1ZRz9",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_buildManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/LdsUt9VGnfSFoS4lAgwON/_ssgManifest.js"
+      src="/_next/static/lS4B0j-pAfLzAhhA1ZRz9/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: f4cade91c208623638093b8405db3d20b05ceded

**Review by theoludwig — CHANGES_REQUESTED** [review]
Great! It seems like the tests, and CI are failing unfortunately but I can't help...
I mostly interested in `styled-jsx` update.

**Comment by timneutkens** [comment]
Going to close this as it's stale, feel free to open a new PR and I'll review it!

**Pull request closed without merging**
