### PR TITLE
add effect packages into the optimized-by-default list

### PR DESCRIPTION
**Pull request by datner**
### What?

Adding packages from the Effect ecosystem to the list of optimized-by-default imports

### Why?

Effect usage includes very liberal use of `import * as Module from "effect/Module"` and `import { Module } from "effect"`. This is usually trees-shaken but in nextjs we must declare it to be optimized to be have this way. To provide a better experience to users I added all the packages in the ecosystem to the list that are possibly relevant. I don't expect all of them to get in, but the proposal should start from the full set of possible candidates. Not included are `/cli`, `/printer`, `/printer-ansi`, and `/vitest`.

At the very least `effect` and `/schema` should be added for their prevalence, but even if there is hesitance I recommend adding `/platform` and `/platform-node` since it's natural for effect usage to grow into benefitting from these quickly enough.

Related issue in the effect repo 
https://github.com/Effect-TS/effect/issues/2701

cited source for taken action:
[the vercel blog](https://vercel.com/blog/how-we-optimized-package-imports-in-next-js)

### How?

Adding strings to a set

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: aefe288b40e6fc2e5b9b87d3c9f0c28370dbcd02

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by datner** [comment]
How can I progress this? It's not a big complicated change..

**Comment by datner** [comment]
please

**Review by ijjk — APPROVED** [review]

**Review by shuding — APPROVED** [review]

**Comment by datner** [comment]
Thank you ❤️ 🙏🏻

**Pull request merged**
