### PR TITLE
backport: create-next-app updates

### PR DESCRIPTION
**Pull request by lubieowoce**
- #65803
- #66043
- #66233
- #66145
- #66374
- #67146
- #52845
- #69021
- #66931
- #67425
---
- #64478
- #68534
- #68899
Note: these ignored all changes in `--empty` templates, because `--empty` wasn't backported

### TODO:
- [x] The CSS changes need to be confirmed visually, i didn't check if it looks right

### CODE REVIEW

**Comment by lubieowoce** [comment]
The CSS changes need to be confirmed visually, i didn't check if it looks right

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5deda4839a8750159bf10d4ac48612c831acc82b

`TURBOPACK=1 pnpm test-start test/e2e/middleware-rewrites/test/index.test.ts` (turbopack)
- Middleware Rewrite > should opt out of prefetch caching for dynamic routes

<details>
<summary>Expand output</summary>

  ● Middleware Rewrite › should opt out of prefetch caching for dynamic routes

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      384 |
      385 |         await retry(async () => {
    > 386 |           expect(hasResolvedPrefetch).toBe(true)
          |                                       ^
      387 |         })
      388 |
      389 |         await browser.elementByCss("[href='/dynamic-no-cache/1']").click()

      at toBe (e2e/middleware-rewrites/test/index.test.ts:386:39)
      at fn (lib/next-test-utils.ts:742:20)
      at Object.<anonymous> (e2e/middleware-rewrites/test/index.test.ts:385:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by samcx** [comment]
@lubieowoce This came in recently, we should backport this too → https://github.com/vercel/next.js/pull/68899

**Review by samcx — APPROVED** [review]
<picture data-single-emoji=":lfgtm-intense:" title=":lfgtm-intense:">:lfgtm-intense:</picture>

**Pull request merged**
