### PR TITLE
Support viewport export via TS Plugin

### LINKED ISSUE #57680: Meta theme-color is missing in the html, while meta viewport value is incorrect
### Link to the code that reproduces this issue

https://github.com/Senbonzakura1234/debug-metadata

### To Reproduce

1/ run `next dev`

### Current vs. Expected behavior

- log show
```powershell
 ⚠ Unsupported metadata themeColor is configured in metadata export. Please move it to viewport export instead.
 ⚠ Unsupported metadata viewport is configured in metadata export. Please move it to viewport export instead.
```
those 2 meta field didn't rendered to the html

- change the code move themeColor and viewport option to viewport export:
```ts
export const viewport: Viewport = {
  themeColor: '#996c254d',
  width: '1024'
}
```

those 2 meta field rendered to the html, but getting `"viewport" is not a valid Next.js entry export value` error message in vscode.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: 14.0.1-canary.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

ESLint (eslint-config-next), Metadata (metadata, generateMetadata, next/head)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dakdevs**
### What?

The Next.js TS Plugin generally supports the named exports for the pages and layouts.
Currently the TS Plugin doesn't support the new viewport export.

See: https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

### How?

Added the `viewport` export to the `constants.ts`.

Closes #57680

### CODE REVIEW

**Comment by Vinlock** [comment]
Let me know if I'm missing any additional requirements to get the PR merged! Thanks!

**Review by huozhi — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.3s | N/A |
| buildDurationCached | 6.1s | 6s | N/A |
| nodeModulesSize | 175 MB | 175 MB | ⚠️ +200 B |
| nextStartRea..uration (ms) | 398ms | 397ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| 199-HASH.js gzip | 32.3 kB | 32.4 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 251 B | N/A |
| main-HASH.js gzip | 35.3 kB | 35.4 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | ✓ |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 316 B | 318 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.99 kB | 3.99 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| index.html gzip | 529 B | 530 B | N/A |
| link.html gzip | 542 B | 542 B | ✓ |
| withRouter.html gzip | 524 B | 525 B | N/A |
| Overall change | 542 B | 542 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96 kB | 96 kB | N/A |
| page.js gzip | 140 kB | 140 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | Vinlock/next.js support-viewport-export | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 25.8 kB | 25.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 1d5d1290b042cdd37032bf4084fc18e5ef19d0bd

**Review by boxman0617 — APPROVED** [review]
LGTM!

**Review by joulev — APPROVED** [review]
Could you maybe merge from `canary` to trigger a new CI so the bot can merge this PR?

**Comment by huozhi** [comment]
Thanks for the fix!

**Comment by joulev** [comment]
@davegomez You have a typo. It’s `viewport` not `viewpor`.

**Pull request merged**
