### PR TITLE
Add example with redux-wrapper and material-ui

### PR DESCRIPTION
**Pull request by joaopaulomoraes**

### CODE REVIEW

**Review by timneutkens — COMMENTED** [review]
There is no specific use for this example right, it's a combination of with-redux and with-material-ui 🤔

**Comment by timneutkens** [comment]
I think it would make sense to have it's own repository and add it to https://github.com/unicodeveloper/awesome-nextjs

**Comment by joaopaulomoraes** [comment]
I thought it was a good combination and it would be interesting to have an example of use. Thanks for the feedback!

**Comment by joaopaulomoraes** [comment]
No problem, I understand. Even though it is not possible, I hope I have helped with something. 😬

**Comment by timneutkens** [comment]
@joaopaulomoraes Definitely! Thank you very much for your contribution 🙏 I'd definitely put this into a repository and add it to awesome-nextjs though, it might help someone trying to do the same!

**Pull request closed without merging**
