### PR TITLE
examples: remove `next-offline` example

### PR DESCRIPTION
**Pull request by JamBalaya56562**
## What?

Remove [`next-offline` example](https://github.com/vercel/next.js/tree/canary/examples/next-offline).

## Why?

[`next-offline`](https://github.com/hanford/next-offline) package hasn't been maintained in 3 years.

### Adding or Updating Examples

- [x] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- [x] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: a9354183d0eb45841d722b06146b49e3f5bc1c92

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@JamBalaya56562 We can try creating a new example as a follow-up that follows this → https://nextjs.org/docs/app/building-your-application/configuring/progressive-web-apps!

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by JamBalaya56562** [comment]
> @JamBalaya56562 We can try creating a new example as a follow-up that follows this → https://nextjs.org/docs/app/building-your-application/configuring/progressive-web-apps!

Sounds nice!
To be honest, it might be good to update the existing [pregressive-web-app example](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app).

**Comment by samcx** [comment]
@JamBalaya56562 That sounds good to me!

**Pull request merged**
