### PR TITLE
Polish turbopack start logging

### PR DESCRIPTION
**Pull request by huozhi**
Bring a tiny util to get a `(turbo)` label after next.js info for turbopack dev-server logging and also remove the disclaimer of "thank you for trying".

### After

image

### Before

image

* Fixes the bad dim color
* Colorize the `Next.js (turbo)` label
* Move the learning link down after start message
* Use Log util to format logs
* Remove "v13" related text

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3b8c7a9a8710306e4d30bb3263b0a95944c50bff

`pnpm test test/integration/turbopack-unsupported-log/index.test.ts` 
- turbopack unsupported features log > should not warn by default
- turbopack unsupported features log > should not warn with empty next.config.js
- turbopack unsupported features log > should warn with next.config.js with unsupported field

<details>
<summary>Expand output</summary>

  ● turbopack unsupported features log › should not warn by default

    expect(received).toContain(expected) // indexOf

    Expected substring: "Thank you for trying Next.js v13 with Turbopack!"
    Received string:    "  ▲ Next.js 13.5.7-canary.14 (turbo)
      - Local:        http://localhost:36855·
     ✓ Ready in 445ms
    "

      20 |
      21 |       try {
    > 22 |         expect(output).toContain(
         |                        ^
      23 |           'Thank you for trying Next.js v13 with Turbopack!'
      24 |         )
      25 |         expect(output).not.toContain(

      at Object.toContain (integration/turbopack-unsupported-log/index.test.ts:22:24)

  ● turbopack unsupported features log › should not warn with empty next.config.js

    expect(received).toContain(expected) // indexOf

    Expected substring: "Thank you for trying Next.js v13 with Turbopack!"
    Received string:    "  ▲ Next.js 13.5.7-canary.14 (turbo)
      - Local:        http://localhost:39591·
     ✓ Ready in 453ms
    "

      47 |
      48 |       try {
    > 49 |         expect(output).toContain(
         |                        ^
      50 |           'Thank you for trying Next.js v13 with Turbopack!'
      51 |         )
      52 |         expect(output).not.toContain(

      at Object.toContain (integration/turbopack-unsupported-log/index.test.ts:49:24)

  ● turbopack unsupported features log › should warn with next.config.js with unsupported field

    expect(received).toContain(expected) // indexOf

    Expected substring: "Thank you for trying Next.js v13 with Turbopack!"
    Received string:    "  ▲ Next.js 13.5.7-canary.14 (turbo)
      - Local:        http://localhost:43225
      - Experiments (use at your own risk):
         · urlImports·
     ✓ Ready in 441ms
    "

      82 |
      83 |       try {
    > 84 |         expect(output).toContain(
         |                        ^
      85 |           'Thank you for trying Next.js v13 with Turbopack!'
      86 |         )
      87 |         expect(output).toContain(

      at Object.toContain (integration/turbopack-unsupported-log/index.test.ts:84:24)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.2s | N/A |
| buildDurationCached | 6.1s | 6.2s | N/A |
| nodeModulesSize | 174 MB | 174 MB | ⚠️ +31.9 kB |
| nextStartRea..uration (ms) | 496ms | 497ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.6 kB | 27.6 kB | ✓ |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 251 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 126 kB | 126 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.36 kB | 4.36 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| index.html gzip | 527 B | 530 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 524 B | 525 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.8 kB | 93.8 kB | N/A |
| page.js gzip | 155 kB | 155 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js turbo-remove-disclimar | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 623 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.9 kB | 22.9 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 3b8c7a9a8710306e4d30bb3263b0a95944c50bff

**Comment by shuding** [comment]
> Colorize the Next.js (turbo) label

I think it feels lacking of contrast on that gray CLI background.

**Comment by huozhi** [comment]
@shuding I simplfied it to leverage the same styling of the banner

**Review by sokra — APPROVED** [review]

**Pull request merged**
