### PR TITLE
fix metadata-related typo in MDX documentation

### PR DESCRIPTION
**Pull request by BrennanColberg**
The docs at https://nextjs.org/docs/pages/building-your-application/configuring/mdx currently advise you to set metadata manually by writing, for instance:

```ts
export const meta = {
```

But this does nothing, because in reality this should be "metadata":

```ts
export const metadata = {
```

according to this other documentation https://nextjs.org/docs/app/api-reference/functions/generate-metadata and my experience

### CODE REVIEW

**Review by huozhi — APPROVED** [review]
Thanks!

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c0896edcc1841ab6b7b9a16fd88bcbf5da4b5a35

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c0896edcc1841ab6b7b9a16fd88bcbf5da4b5a35

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by BrennanColberg** [comment]
@huozhi CI checks are failing at the "Set up runner" step with this error:
```
Job unable able to validate for BrennanColberg
```
I am unable to locate the source of this error in the codebase, find relevant instruction in any contributor guides, or otherwise diagnose it. Could you please advise?

**Comment by huozhi** [comment]
@BrennanColberg it was CI flaky issue, fixed and merged 🙏 thanks

**Pull request merged**
