### PR TITLE
Add support for tsconfig 'nodenext' | 'node16'

### LINKED ISSUE #37525: Support `"module": "nodenext"` in `tsconfig.json`
### Describe the feature you'd like to request

With [TypeScript 4.7 providing ECMAScript Module Support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js), we can now set this in our `tsconfig.json` file for the [`module`](https://www.typescriptlang.org/tsconfig#module) option:

```json
{
  "compilerOptions": {
    "module": "nodenext",
  }
}
```

However, Next.js [rejects this value](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/packages/next/lib/typescript/writeConfigurationDefaults.ts#L43-L54), and overwrites it with `"esnext"`.

#36189 did add support for `"moduleResolution": "nodenext"`, but not `"module": "nodenext"`.

### Describe the solution you'd like

Add `"nodenext"` and `"node16"` to [`module.parsedValues`](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/packages/next/lib/typescript/writeConfigurationDefaults.ts#L46-L51):

```ts
parsedValues: [
  ts.ModuleKind.ES2020,
  ts.ModuleKind.ESNext,
  ts.ModuleKind.NodeNext,
  ts.ModuleKind.Node16,
  ts.ModuleKind.CommonJS,
  ts.ModuleKind.AMD,
]
```

I figure there may be other changes necessary to make this work, and that the [TypeScript version](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/package.json#L193) should be bumped to 4.7+ with it.

### Describe alternatives you've considered

I edited [`writeConfigurationDefaults.js`](https://github.com/vercel/next.js/blob/canary/packages/next/lib/typescript/writeConfigurationDefaults.ts) directly in my `node_modules` for a local project, and it seemed to work.

Relevant aside: I think the discussion at #32237 is a bug that needs to be resolved before this can work as expected. I still haven't been able to import files with the `.js` extension.

### LINKED ISSUE #41961: Module not found: Fully Specified ESM Imports (with `.js` extension) in TypeScript
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
 
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 3.8.1
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

Hi there, first of all, thanks so much for the hard work on Next.js 🙌 13 is looking great!

Importing a file using the fully-specified ESM-style imports with `.js` leads to a `Module not found` error:

`pages/index.tsx`

```tsx
import Component from "../components/Component.js";

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return <Component />
}
```

`components/Component.tsx`:

```tsx
export default function Component() {
  return <div>asdf</div>;
}
```

Error message:

```
wait  - compiling /_error (client and server)...
error - ./pages/index.tsx:1:0
Module not found: Can't resolve '../components/Component.js'
> 1 | import Component from "../components/Component.js";
  2 | 
  3 | /** Add your relevant code here for the issue to reproduce */
  4 | export default function Home() {
```

This does not match the behavior of the TypeScript compiler, which will resolve these files. See https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855 for more details.

**experimental.fullySpecified config option**

This also happens while using the `experimental.fullySpecified: true` option in the Next.js config:

`next.config.mjs`

```js
/** @type {import('next').NextConfig} */
const config = {
  experimental: {
    fullySpecified: true,
  },
  reactStrictMode: true,
}
export default config;
```

**Workaround 1: `resolve.extensionAlias` configuration option**

webpack does have a `resolve.extensionAlias` configuration as of `5.74.0`:

```js
/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  webpack: (
    webpackConfig,
    { webpack },
  ) => {
    webpackConfig.resolve.extensionAlias = {
      '.js': ['.ts', '.tsx', '.js', '.jsx'],
      '.mjs': ['.mts', '.mjs'],
      '.cjs': ['.cts', '.cjs'],
    };
    return webpackConfig;
  },
};

export default config;
```

But this should be zero-config.

Related issue in webpack: https://github.com/webpack/webpack/issues/13252

**Workaround 2: `webpack.NormalModuleReplacementPlugin` configuration option**

Configure the `NormalModuleReplacementPlugin` inside your webpack config

`next.config.mjs`

```js
/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
  webpack: (
    webpackConfig,
    { webpack },
  ) => {
    webpackConfig.plugins.push(
      new webpack.NormalModuleReplacementPlugin(new RegExp(/\.js$/), function (
        /** @type {{ request: string }} */
        resource,
      ) {
        resource.request = resource.request.replace('.js', '');
      }),
    );
    return webpackConfig;
  },
};

export default config;
```

Also, this should be zero-config.

### Expected Behavior

Fully-specified ESM-style imports with `.js` extensions should resolve to the respective TypeScript files out of the box (as TSC does it), without any further webpack / Turbopack configuration necessary.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-y6faeb?file=components%2FComponent.tsx,pages%2Findex.tsx,next.config.js

### To Reproduce

1. Use TypeScript
2. Import another TypeScript / TSX file with fully-specified `.js` 
3. Observe error message

### PR DESCRIPTION
**Pull request by loettz**
## ESM: support module option for tsconfig.json 

- fixes #37525
- fixes #41961

With [TypeScript 4.7 providing ECMAScript Module Support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js), we can now set this in our tsconfig.json file for the [module](https://www.typescriptlang.org/tsconfig#module) option.

Webpack added "extensionAlias" to solve importing ts files with .js extension -> https://github.com/webpack/enhanced-resolve/pull/351

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
We need to add the extension when using `node16` module resolution. Since we can't use `.ts` extension in ts, we need to use `.js` and iirc nextjs can't resolve files with the `.js` extension when the actual file is a `.tsx` file.

**Comment by kachkaev** [comment]
Somewhat related: https://github.com/microsoft/TypeScript/issues/50058

**Comment by loettz** [comment]
> We need to add the extension when using `node16` module resolution. Since we can't use `.ts` extension in ts, we need to use `.js` and iirc nextjs can't resolve files with the `.js` extension when the actual file is a `.tsx` file.

In my last commit I added the extensionAlias option in webpack.config (https://github.com/webpack/enhanced-resolve/pull/351). Tested with my current repository thats using next and that solved the issue.

**Review by ijjk — DISMISSED** [review]
Changes and added test look good for the `tsconfig` change, can you also add a test related to the `extensionAlias` change?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| buildDuration | 51.7s | 50.8s | -886ms |
| buildDurationCached | 21.1s | 13.5s | -7.6s |
| nodeModulesSize | 95.2 MB | 95.2 MB | ✓ |
| nextStartRea..uration (ms) | 391ms | 380ms | -11ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| 152-HASH.js gzip | 64.5 kB | 64.5 kB | ✓ |
| 53.HASH.js gzip | 182 B | 182 B | ✓ |
| main-app-HASH.js gzip | 204 B | 205 B | ⚠️ +1 B |
| main-HASH.js gzip | 79.2 kB | 79.2 kB | ✓ |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 146 kB | 146 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 484 B | 484 B | ✓ |
| css-HASH.js gzip | 804 B | 804 B | ✓ |
| dynamic-HASH.js gzip | 2.27 kB | 2.27 kB | ✓ |
| edge-ssr-HASH.js gzip | 255 B | 255 B | ✓ |
| head-HASH.js gzip | 827 B | 827 B | ✓ |
| hooks-HASH.js gzip | 848 B | 848 B | ✓ |
| image-HASH.js gzip | 4.3 kB | 4.3 kB | ✓ |
| index-HASH.js gzip | 252 B | 252 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | ✓ |
| routerDirect..HASH.js gzip | 782 B | 782 B | ✓ |
| script-HASH.js gzip | 857 B | 857 B | ✓ |
| withRouter-HASH.js gzip | 781 B | 781 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 482 B | 482 B | ✓ |
| Overall change | 482 B | 482 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| index.html gzip | 489 B | 489 B | ✓ |
| link.html gzip | 504 B | 504 B | ✓ |
| withRouter.html gzip | 485 B | 485 B | ✓ |
| Overall change | 1.48 kB | 1.48 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 110 kB | 110 kB | ✓ |
| page.js gzip | 98.4 kB | 98.4 kB | ✓ |
| Overall change | 209 kB | 209 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | loettz/next.js tsconfig-module-nodenext-node16 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 581 B | 582 B | ⚠️ +1 B |
| middleware-r..fest.js gzip | 145 B | 145 B | ✓ |
| middleware.js gzip | 27.1 kB | 27.1 kB | ✓ |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ⚠️ +1 B |

</details>

</details>
Commit: a2c7e1e745d6219780d10fe0f6aca8a6e9c04914

**Comment by loettz** [comment]
> 

i added the test for extensionAlias in webpack config

**Review by styfle — APPROVED** [review]
Great work, thanks! 🎉

**Review by ijjk — APPROVED** [review]
Looks good, thanks!

**Comment by karlhorky** [comment]
@loettz thanks for this! Looking at [the diff for ](https://github.com/vercel/next.js/pull/44177/files#diff-5f441142eb8ba9bcba515aa36fbc420a113307bd191e54a4e9e6c43529fc2613R885-R887) (also copied below), I guess this doesn't support `.mts`, `.cjs`, `.mtsx`, `.cjsx` (and any other) extensions, right?

```diff
    extensions: isNodeServer
      ? ['.js', '.mjs', '.tsx', '.ts', '.jsx', '.json', '.wasm']
      : ['.mjs', '.js', '.tsx', '.ts', '.jsx', '.json', '.wasm'],
+    extensionAlias: {
+      '.js': ['.ts', '.tsx', '.js', '.jsx'],
+    },
    modules: [
      'node_modules',
```

I included these in [Workaround 1 in #41961](https://github.com/vercel/next.js/issues/41961#:~:text=Workaround%201%3A%20resolve.extensionAlias%20configuration%20option)

Maybe these extensions don't make sense in the context of a Next.js app?

**Comment by GabenGar** [comment]
Meme extensions only make sense as a stopgap for migrating the codebase from CJS to ESM, otherwise the module system of the user code should be decided by `"type"` field in `package.json`.

**Pull request merged**
