### PR TITLE
Example with next-routes

### PR DESCRIPTION
**Pull request by fridays**
This example shows how you can use [next-routes](https://github.com/fridays/next-routes)

### CODE REVIEW

**Review by sedubois — COMMENTED** [review]
👍 Considering there's already the `parameterized-routing` example, should that one rather be updated, or could it at least refer to this one and vice-versa? Also at the moment users won't find this example by searching for keyword "parameterized" and "dynamic".

**Review by timneutkens — APPROVED** [review]
Looks good 👍

**Comment by fridays** [comment]
I added a link to the parameterized routing example and more keywords. I am not sure what I can do to repair the tests

**Comment by timneutkens** [comment]
I wonder if we should call it `with-next-routes`?

**Comment by fridays** [comment]
Done! 👍

**Pull request merged**
