### PR TITLE
Using developit/unfetch as the Fetch API polyfill

### LINKED ISSUE #1241: Use developit/unfetch as our fetch implementation
See: https://github.com/developit/unfetch

### PR DESCRIPTION
**Pull request by impronunciable**
Move to https://github.com/developit/unfetch
Fixes #1241

### CODE REVIEW

**Comment by developit** [comment]
(test failure appears to be unrelated)

**Comment by rauchg** [comment]
SGreatTM

**Comment by arunoda** [comment]
Guys this breaks our production build with some uglifyjs error.
@developit could you check the travis error logs.
I'm gonna revert this PR for now.

**Comment by developit** [comment]
If you are using Webpack 2, it's likely `2.0.0` was giving you untranspiled ES2015 (in this case arrow functions).  I've already fixed that, it was published as [2.1.0](https://github.com/developit/unfetch/releases/tag/2.1.0).

Is there a way for me to check this again?

**Comment by developit** [comment]
I applied this patch and confirmed that the test failures go away with `unfetch@2.1.0`.

**Comment by rauchg** [comment]
Thanks @developit. Reverting the revert

**Comment by rauchg** [comment]
(and bumping)

**Comment by developit** [comment]
<3

**Comment by rauchg** [comment]
While we're on the subject, I don't think next should polyfill. It should ponyfill.

**Comment by developit** [comment]
makes sense - if it's just being used for internal data fetching then ponyfill avoids people relying on `window.fetch` being there without explicitly putting it there themselves.

The default entrypoint for `unfetch` is a ponyfill:

```
import fetch from 'unfetch';

// fetch will be window.fetch || function unfetch() { .. }
```

**Pull request merged**
