### PR TITLE
Add shadow-dom polyfill in dev mode to fix IE11 error

### LINKED ISSUE #13231: IE11, development, HMR: Object doesn't support property or method 'attachShadow'.
# Bug report

## Describe the bug

Basically the nextjs page bugs in IE11 development with the following message.
```
Object doesn't support property or method 'attachShadow'
``` 
It seems related to development hot module reloading. Somehow the `/_next/webpack-hmr` route is caught by express. I have by the way seen similar bugs when using custom routes in pure nextjs pages previously. Unsure if this is related.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install the `custom-server-express` example.
2. Add this snippet in `server.js`:
```
  server.get('/:one/:two', (req, res) => {
    console.log("Parameters", req.params)
    return res.redirect('/a')
  })
```
3. Open `localhost:3000` in Internet Explorer 11.
4. The page flashes the actual content before going white.
5. Open the console (F12) and the `attachShadow` message flashes indefinitely.
6. In the command window, read the message `Parameters { one: '_next', two: 'webpack-hmr' }`

## Expected behavior

I expected to see my content. I would have also expected that `attachShadow` was either added as a built-in polyfill in nextjs, or that the function was avoided. I believe it can be traced to this location: `@next\react-dev-overlay\lib\internal\components\ShadowPortal.js`. In other locations in the next package you have an if-test to avoid this - it seems to me.

## Screenshots

image

## System information

- OS: Windows 10
- Browser: IE 11
- Version of Next.js: latest (as per today, using the custom-server-express example)
- Version of Node.js: 10.16.0

## Additional context

I came across this while updating a production package. I wanted to debug the polyfills and find out whether I still need to add polyfills for IE11 after next 9.3. This was a major roadblock.

The real problem here is probably using attachShadow in IE11.

I will try to recreate it without an express server...

### PR DESCRIPTION
**Pull request by bartlangelaan**
This adds a polyfill to remove an error in IE11.

Fixes #13231 based on this comment: https://github.com/vercel/next.js/issues/13231#issuecomment-638129714.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | ✓ |
| nodeModulesSize | 62.9 MB | 62.9 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.395 | 2.363 | -0.03 |
| / avg req/sec | 1043.9 | 1058 | +14.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.414 | 1.439 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1768.31 | 1736.76 | ⚠️ -31.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e3dd5fc..bc67.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f4d7a25..dule.js gzip | 6.23 kB | 6.23 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 996 B | 996 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +180ms |
| nodeModulesSize | 62.9 MB | 62.9 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e3dd5fc..bc67.js gzip | 7.16 kB | 7.16 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f4d7a25..dule.js gzip | 6.23 kB | 6.23 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | bartlangelaan/next.js ie11-shadow-dom-polyfill | Change |
| - | - | - | - |
| _error.js | 1.05 MB | 1.05 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.05 MB | 1.05 MB | ✓ |
| link.js | 1.1 MB | 1.1 MB | ✓ |
| routerDirect.js | 1.09 MB | 1.09 MB | ✓ |
| withRouter.js | 1.09 MB | 1.09 MB | ✓ |
| Overall change | 5.4 MB | 5.4 MB | ✓ |

</details>

</details>
Commit: 5aae35a6ad5ef5358cddcac934b89663a9e325e9

**Comment by weyert** [comment]
Any way we can progress this PR? Would be nice to be able to test/debug in IE11

**Review by timneutkens — CHANGES_REQUESTED** [review]
This PR is missing integration tests. Can you add an integration test to ensure it works in IE11?

**Comment by weyert** [comment]
> This PR is missing integration tests. Can you add an integration test to ensure it works in IE11?

I understand that you are using Browserstack for such tests. Personally, I don't have access to Browserstack, any way to use it locally. I had a look but I could find any integration tests specially targeting IE11. Do you have an example of this? Do I need to do anything special to ensure it will be part of the checks?

**Comment by timneutkens** [comment]
We currently run it on a Windows machine that has IE11. Not using browserstack in this case. https://github.com/vercel/next.js/blob/canary/azure-pipelines.yml#L7-L28

You'll probably want to add an extra line there to also run `test/integration/basic` and `test/acceptance` suites as those test for development editing and error overlay 👍

**Comment by haydnhkim** [comment]
Please check my comment. Adding `@webcomponents/shadydom` has side effects for users using `#container`.
https://github.com/vercel/next.js/issues/13231#issuecomment-697637376

I sent a PR to circumvent the issue with a simple code correction.
https://github.com/vercel/next.js/pull/18552

**Comment by timneutkens** [comment]
Going to close this as it's stale.

**Comment by bartlangelaan** [comment]
Hey @timneutkens, does this mean that no IE11 fixes will be merged until the integration tests are enabled?

I'm not familiar with the test suite of Next.. Can enabling more IE11 tests be done in a separate MR (which probably comes with its own problems)?

-----

For people that have this problem and need this fix, you can [download the patch](https://github.com/vercel/next.js/pull/17418.patch) and use [the patch-page npm module](https://www.npmjs.com/package/patch-package) to enable this fix in the meantime.

**Comment by timneutkens** [comment]
> does this mean that no IE11 fixes will be merged until the integration tests are enabled?

Correct we do not merge PRs without integration tests / clear path to integration tests being added.

**Pull request closed without merging**
