### PR TITLE
Allow `viewport` & `generateViewport` exports

### PR DESCRIPTION
**Pull request by AhmedBaset**
This PR fixes `"viewport" is not a valid Next.js entry export value.` as well as `"generateViewport" is not a valid Next.js entry export value.` in the custom TypeScript version.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7182a1f1bbb2c8aef8610bf00fc28ac9f743fe38

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 7182a1f1bbb2c8aef8610bf00fc28ac9f743fe38

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by imranbarbhuiya** [comment]
duplicate of #57554

**Comment by A7med3bdulBaset** [comment]
@imranbarbhuiya thanks for letting me know

**Pull request closed without merging**
