### PR TITLE
Updates to with-supertokens example 

### PR DESCRIPTION
**Pull request by rishabhpoddar**
The example app is now changed to use the new app dir structure.

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
There may be linting issues. i tried to run `npm i` in the `next.js` root, but that failed with the following error:
```
 ✘  next.js   canary  npm i --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @next/react-dev-overlay@13.5.6-canary.7
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.2" from @next/react-dev-overlay@13.5.6-canary.7
npm WARN packages/react-dev-overlay
npm WARN   @next/react-dev-overlay@13.5.6-canary.7
npm WARN   node_modules/@next/react-dev-overlay
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17.0.2" from @next/react-dev-overlay@13.5.6-canary.7
npm WARN   packages/react-dev-overlay
npm WARN     @next/react-dev-overlay@13.5.6-canary.7
npm WARN     node_modules/@next/react-dev-overlay
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @next/react-dev-overlay@13.5.6-canary.7
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^17.0.2" from @next/react-dev-overlay@13.5.6-canary.7
npm WARN packages/react-dev-overlay
npm WARN   @next/react-dev-overlay@13.5.6-canary.7
npm WARN   node_modules/@next/react-dev-overlay
npm WARN
npm WARN Conflicting peer dependency: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^17.0.2" from @next/react-dev-overlay@13.5.6-canary.7
npm WARN   packages/react-dev-overlay
npm WARN     @next/react-dev-overlay@13.5.6-canary.7
npm WARN     node_modules/@next/react-dev-overlay
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @testing-library/jest-dom@6.1.2
npm WARN Found: @types/jest@27.4.1
npm WARN node_modules/@types/jest
npm WARN   dev @types/jest@"27.4.1" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional @types/jest@">= 28" from @testing-library/jest-dom@6.1.2
npm WARN node_modules/@testing-library/jest-dom
npm WARN   dev @testing-library/jest-dom@"6.1.2" from the root project
npm WARN
npm WARN Conflicting peer dependency: @types/jest@29.5.6
npm WARN node_modules/@types/jest
npm WARN   peerOptional @types/jest@">= 28" from @testing-library/jest-dom@6.1.2
npm WARN   node_modules/@testing-library/jest-dom
npm WARN     dev @testing-library/jest-dom@"6.1.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @testing-library/jest-dom@6.1.2
npm WARN Found: jest@27.0.6
npm WARN node_modules/jest
npm WARN   dev jest@"27.0.6" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional jest@">= 28" from @testing-library/jest-dom@6.1.2
npm WARN node_modules/@testing-library/jest-dom
npm WARN   dev @testing-library/jest-dom@"6.1.2" from the root project
npm WARN
npm WARN Conflicting peer dependency: jest@29.7.0
npm WARN node_modules/jest
npm WARN   peerOptional jest@">= 28" from @testing-library/jest-dom@6.1.2
npm WARN   node_modules/@testing-library/jest-dom
npm WARN     dev @testing-library/jest-dom@"6.1.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dom@17.0.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom-17@17.0.2
npm WARN node_modules/react-dom-17
npm WARN   dev react-dom-17@"npm:react-dom@17.0.2" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"17.0.2" from react-dom-17@17.0.2
npm WARN   node_modules/react-dom-17
npm WARN     dev react-dom-17@"npm:react-dom@17.0.2" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dom@18.3.0-canary-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"18.3.0-canary-a41957507-20231017" from react-dom-builtin@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-dom-builtin
npm WARN   dev react-dom-builtin@"npm:react-dom@18.3.0-canary-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"18.3.0-canary-a41957507-20231017" from react-dom-builtin@18.3.0-canary-a41957507-20231017
npm WARN   node_modules/react-dom-builtin
npm WARN     dev react-dom-builtin@"npm:react-dom@18.3.0-canary-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-dom@0.0.0-experimental-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-a41957507-20231017" from react-dom-experimental-builtin@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-dom-experimental-builtin
npm WARN   dev react-dom-experimental-builtin@"npm:react-dom@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-a41957507-20231017" from react-dom-experimental-builtin@0.0.0-experimental-a41957507-20231017
npm WARN   node_modules/react-dom-experimental-builtin
npm WARN     dev react-dom-experimental-builtin@"npm:react-dom@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"18.3.0-canary-a41957507-20231017" from react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-server-dom-turbopack
npm WARN   dev react-server-dom-turbopack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"18.3.0-canary-a41957507-20231017" from react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN   node_modules/react-server-dom-turbopack
npm WARN     dev react-server-dom-turbopack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"18.3.0-canary-a41957507-20231017" from react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-server-dom-turbopack
npm WARN   dev react-server-dom-turbopack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react-dom@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"18.3.0-canary-a41957507-20231017" from react-server-dom-turbopack@18.3.0-canary-a41957507-20231017
npm WARN   node_modules/react-server-dom-turbopack
npm WARN     dev react-server-dom-turbopack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-a41957507-20231017" from react-server-dom-turbopack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-server-dom-turbopack-experimental
npm WARN   dev react-server-dom-turbopack-experimental@"npm:react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-a41957507-20231017" from react-server-dom-turbopack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN   node_modules/react-server-dom-turbopack-experimental
npm WARN     dev react-server-dom-turbopack-experimental@"npm:react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"0.0.0-experimental-a41957507-20231017" from react-server-dom-turbopack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-server-dom-turbopack-experimental
npm WARN   dev react-server-dom-turbopack-experimental@"npm:react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react-dom@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"0.0.0-experimental-a41957507-20231017" from react-server-dom-turbopack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN   node_modules/react-server-dom-turbopack-experimental
npm WARN     dev react-server-dom-turbopack-experimental@"npm:react-server-dom-turbopack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"18.3.0-canary-a41957507-20231017" from react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-server-dom-webpack
npm WARN   dev react-server-dom-webpack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"18.3.0-canary-a41957507-20231017" from react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN   node_modules/react-server-dom-webpack
npm WARN     dev react-server-dom-webpack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"18.3.0-canary-a41957507-20231017" from react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-server-dom-webpack
npm WARN   dev react-server-dom-webpack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react-dom@18.3.0-canary-a41957507-20231017
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"18.3.0-canary-a41957507-20231017" from react-server-dom-webpack@18.3.0-canary-a41957507-20231017
npm WARN   node_modules/react-server-dom-webpack
npm WARN     dev react-server-dom-webpack@"18.3.0-canary-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-a41957507-20231017
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-a41957507-20231017" from react-server-dom-webpack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-server-dom-webpack-experimental
npm WARN   dev react-server-dom-webpack-experimental@"npm:react-server-dom-webpack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-a41957507-20231017" from react-server-dom-webpack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN   node_modules/react-server-dom-webpack-experimental
npm WARN     dev react-server-dom-webpack-experimental@"npm:react-server-dom-webpack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-a41957507-20231017
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"0.0.0-experimental-a41957507-20231017" from react-server-dom-webpack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-server-dom-webpack-experimental
npm WARN   dev react-server-dom-webpack-experimental@"npm:react-server-dom-webpack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN
npm WARN Conflicting peer dependency: react-dom@0.0.0-experimental-a41957507-20231017
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"0.0.0-experimental-a41957507-20231017" from react-server-dom-webpack-experimental@0.0.0-experimental-a41957507-20231017
npm WARN   node_modules/react-server-dom-webpack-experimental
npm WARN     dev react-server-dom-webpack-experimental@"npm:react-server-dom-webpack@0.0.0-experimental-a41957507-20231017" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-ssr-prepass@1.0.8
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-ssr-prepass@1.0.8
npm WARN node_modules/react-ssr-prepass
npm WARN   dev react-ssr-prepass@"1.0.8" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.8.0" from react-ssr-prepass@1.0.8
npm WARN   node_modules/react-ssr-prepass
npm WARN     dev react-ssr-prepass@"1.0.8" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtualized@9.22.3
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   dev react@"18.2.0" from the root project
npm WARN   9 more (@emotion/react, next, @next/third-parties, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/react-virtualized
npm WARN   dev react-virtualized@"9.22.3" from the root project
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN   node_modules/react-virtualized
npm WARN     dev react-virtualized@"9.22.3" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-virtualized@9.22.3
npm WARN Found: react-dom@18.2.0
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"18.2.0" from the root project
npm WARN   3 more (@testing-library/react, next, styled-components)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN node_modules/react-virtualized
npm WARN   dev react-virtualized@"9.22.3" from the root project
npm WARN
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm WARN   node_modules/react-virtualized
npm WARN     dev react-virtualized@"9.22.3" from the root project
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@firebase%2fremote-config-types: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in: /Users/rishabhpoddar/.npm/_logs/2023-10-19T08_20_03_719Z-debug-0.log
```

Due to which i cannot run the linting command.

**Comment by rishabhpoddar** [comment]
Anyone to help merge this please?

**Comment by leerob** [comment]
Can you rebase to get rid of all the extra commits here? There are merge conflicts as well.

**Comment by rishabhpoddar** [comment]
> Can you rebase to get rid of all the extra commits here? There are merge conflicts as well.

Done @leerob. At the time I created the original PR, the merge conflict was resolved. Odd that it happened again. I also did the rebase, and the older commits are gone now.

**Review by leerob — COMMENTED** [review]
Please keep a README and ensure you run Prettier and linting checks.

**Comment by rishabhpoddar** [comment]
I have added the readme. I am unable to run the linter because i can't setup the dev env on my machine (see stack trace of error above)

**Comment by rishabhpoddar** [comment]
Closed this PR in favour of https://github.com/vercel/next.js/pull/58346

**Pull request closed without merging**
