### PR TITLE
fix(next): use moduleGraph.getIssuer to avoid deprecation warning (#36329)

### LINKED ISSUE #36329: [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
$ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 14.19.0
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: 7.0.0-alpha.2
    Relevant packages:
      next: 12.1.6-canary.4
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

Version 100.0.4896.127 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

The deprecation warning for webpack appears when there is a compilation error:
Pasted Graphic copy

image

### Expected Behavior

It should be possible to use webpack's `moduleGraph` API to avoid the warning

### To Reproduce

1. `npx create-next-app@latest test-next-warning`
2. `cd test-next-warning`
3. modify `pages/index.js` to manually add some syntax errors
4. `yarn dev`
5. visit `localhost:3000` and you should see the warning in the terminal

### PR DESCRIPTION
**Pull request by await-ovo**
fix: #36329 

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
The change looks good, since a reproduction is available could you add a test for this behavior: https://github.com/vercel/next.js/blob/canary/test/readme.md

**Comment by await-ovo** [comment]
> The change looks good, since a reproduction is available could you add a test for this behavior: https://github.com/vercel/next.js/blob/canary/test/readme.md

Okay, I will add the related test cases :)

**Comment by await-ovo** [comment]
> The change looks good, since a reproduction is available could you add a test for this behavior: https://github.com/vercel/next.js/blob/canary/test/readme.md

Test cases have been added.

**Review by ijjk — APPROVED** [review]
Thanks!

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| buildDuration | 19s | 19.5s | ⚠️ +450ms |
| buildDurationCached | 7.5s | 7.5s | ⚠️ +18ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +226 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.896 | 3.87 | -0.03 |
| / avg req/sec | 641.75 | 646.07 | +4.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.741 | 1.625 | -0.12 |
| /error-in-render avg req/sec | 1435.72 | 1538.21 | +102.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.04 kB | 3.04 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.74 kB | 5.74 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 461 B | 461 B | ✓ |
| Overall change | 461 B | 461 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| buildDuration | 21.5s | 21.6s | ⚠️ +66ms |
| buildDurationCached | 7.4s | 7.5s | ⚠️ +103ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +226 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.923 | 3.937 | ⚠️ +0.01 |
| / avg req/sec | 637.23 | 635.03 | ⚠️ -2.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.661 | 1.7 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1505.28 | 1470.98 | ⚠️ -34.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.9 kB | 28.9 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.8 kB | 72.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.79 kB | 5.79 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.44 kB | 2.44 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-webpack-issuer-warning | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 1d02177e250e4ad051168339656d6435f215d6fa

**Pull request merged**
