### PR TITLE
Fixes a typo

### PR DESCRIPTION
**Pull request by JaimeObregon**
Fixes a typo which might lead to accidentally commit the local secrets file.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
The current docs look correct, what is the behavior you're seeing?

**Comment by JaimeObregon** [comment]
Thank you for reviewing this, @timneutkens. I am new to Next.js and was just reading the docs when I realized `.env.local` wouldn't be `.gitignore`'d by `.env.*.local`. Am I wrong?

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
Looks correct what @JaimeObregon is suggesting. The `.*.` patter would not match `.env.local` since it only has a single `.` in the middle.

**Comment by balazsorban44** [comment]
This is actually a duplicate of #32647 I suggest @JaimeObregon you follow that, and if the author does not respond to the review, we can go ahead with this PR. Otherwise, I kindly ask you to close it.

**Comment by balazsorban44** [comment]
The other PR has been merged, so I am closing this. Thanks anyway! :pray:

**Pull request closed without merging**
