### PR TITLE
Update features links in index.mdx

### PR DESCRIPTION
**Pull request by iafsh**
### What?
The links in ##Main Features were not updated and were shown as 404 unfound in the browser.

### How?
The old links have been replaced with new links to the documentation.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 41be493d157bec9b42de5471995229f0cd640a69

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 41be493d157bec9b42de5471995229f0cd640a69

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@iafsh I'm not experiencing any `404`'s with these links, and these updates would also be incorrect too (we don't link back to GitHub).

**Comment by iafsh** [comment]
@samcx I was talking about opening the links on GitHub. They were fine at [here](https://nextjs.org/docs). But when I try to open them [here](https://github.com/vercel/next.js/blob/canary/docs/index.mdx) it shows 404 page not found. Am I misinterpreting this? Are these links even supposed to work on GitHub?

**Comment by samcx** [comment]
@iafsh They're not supposed to work in GitHub because they are just relative links (relative to `next.org/...`), so it's fine if they `404` on GitHub.

**Pull request closed without merging**
