### PR TITLE
Include dynamic.js in published files

### LINKED ISSUE #2385: Unable to resolve module 'next/dynamic'
`dynamic.js` is not included in published npm package.

```js
// broken
import dynamic from 'next/dynamic'

// workaround
import dynamic from 'next/dist/lib/dynamic'
```

### PR DESCRIPTION
**Pull request by bmealhouse**
closes #2385

### CODE REVIEW

**Comment by arunoda** [comment]
Oh thanks. But, I'm pretty not sure how it works in all these days :)

**Comment by bmealhouse** [comment]
Thank you!

I was wondering how it has been working for so long as well.  Maybe `npm link`?

**Comment by arunoda** [comment]
Not sure.
We were using it in production as well.

**Comment by arunoda** [comment]
May be because we use `yarn`.

**Pull request merged**
