### PR TITLE
fix(#32562): Adding documentation relating to app.renderError

### LINKED ISSUE #32562: Docs: app.renderError
### What is the improvement or update you wish to see?

Custom servers should use app.renderError to render error pages in an error handler. This is currently undocumented.

### Is there any context that might help us understand?

https://github.com/fastify/fastify-nextjs/issues/435

https://github.com/fastify/fastify-nextjs/pull/436

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/custom-server

### PR DESCRIPTION
**Pull request by MasonJason23**
Closes #32562

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by leerob** [comment]
Could you share some more context around this update?

**Comment by MasonJason23** [comment]
> Could you share some more context around this update?

#32562

**Comment by stefee** [comment]
Congrats on the PR @MasonJason23! 🎉 

For context @leerob, I’ve been giving some advice on this previously via email to help out with their course.

Here are some initial pointers from me:

- This sentence isn’t quite right: “This is in case of an unhandled server exception, where a 404 error page will be loaded rather than a custom error page” - the renderError function can be used to render things other than 404. Also, a 404 page is for Not Found whereas an unhandled exception should result in a 500 Internal Server Error page instead. 
- I think sometimes less is more when it comes to detail. Bear in mind that the code is changing and so you shouldn’t document things which are likely to become out of date over time.
- I would probably not include the list of error pages, and instead link to the error page docs.
- I would drop the source code entirely - this isn’t necessary.

What would be useful instead would be to show an example of how to use the method in a practical - but not overly specific - context. I understand this is tricky because you most-likely haven’t encountered a practical use case yourself since this is just an exercise.

I wonder if you have any other thoughts @leerob? Thanks.

**Comment by stefee** [comment]
I’d like to just add (although this isn’t useful for this PR) I think the structure of the custom server docs is not great overall. 

The lack of a API doc for `app` is a problem, because it makes additions like this PR harder than it needs to be.

Would it be worth adding a better doc structure for the `app` methods @leerob?

**Comment by leerob** [comment]
Which methods would you like to see documented? I think they could be subheadings inside of an API section in this page.

**Comment by leerob** [comment]
I'm going to close this one out, since the documentation has changed since this was originally made. Further, we do not recommend using ejected servers moving forward (all use cases should be covered by using Middleware, including when self-hosting on Node.js servers).

**Comment by stefee** [comment]
@leerob 

> all use cases should be covered by using Middleware, including when self-hosting on Node.js servers

Is the plan to support the Node.js runtime in middleware in future?

**Pull request closed without merging**
