### PR TITLE
New Image component example - How to contain Image

### PR DESCRIPTION
**Pull request by danielolaviobr**
This new example will show how it is possible to contain a Image component inside of an another component, while providing the image dimensions.

This was something that I struggled in the past few days before figuring it out

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | -40ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +1.29 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.153 | 2.095 | -0.06 |
| / avg req/sec | 1161.14 | 1193.54 | +32.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.109 | 1.084 | -0.02 |
| /error-in-render avg req/sec | 2253.89 | 2306.14 | +52.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.1s | -59ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +1.29 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _error.js | 1.35 MB | 1.35 MB | -2 B |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.35 MB | 1.35 MB | -2 B |
| link.js | 1.4 MB | 1.4 MB | ✓ |
| routerDirect.js | 1.4 MB | 1.4 MB | ✓ |
| withRouter.js | 1.4 MB | 1.4 MB | ✓ |
| Overall change | 6.91 MB | 6.91 MB | -4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.9s | -225ms |
| nodeModulesSize | 46.7 MB | 46.7 MB | ⚠️ +1.29 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.125 | 2.111 | -0.01 |
| / avg req/sec | 1176.5 | 1184.26 | +7.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.103 | 1.118 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2267.48 | 2236.66 | ⚠️ -30.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| 597-3f457946..288d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-6834d41c..48a9.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _app-5cc66b2..6f03.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-55112..054d.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-89a5460c..567f.js gzip | 558 B | 558 B | ✓ |
| hooks-8c2e74..be37.js gzip | 924 B | 924 B | ✓ |
| index-fec729..83b2.js gzip | 243 B | 243 B | ✓ |
| link-dd34d9b..0ade.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..5759.js gzip | 336 B | 336 B | ✓ |
| withRouter-1..98bf.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Joonpark13/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 617 B | 617 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "3cQYb_SDTGq_-l8zW8hUN",
+        "buildId": "9cOrGkb6QIvj1EWTczQY_",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_buildManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_ssgManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -53,7 +53,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "3cQYb_SDTGq_-l8zW8hUN",
+        "buildId": "9cOrGkb6QIvj1EWTczQY_",
         "isFallback": false,
         "gip": true
       }
@@ -91,11 +91,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_buildManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_ssgManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "3cQYb_SDTGq_-l8zW8hUN",
+        "buildId": "9cOrGkb6QIvj1EWTczQY_",
         "isFallback": false,
         "gip": true
       }
@@ -86,11 +86,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_buildManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/3cQYb_SDTGq_-l8zW8hUN/_ssgManifest.js"
+      src="/_next/static/9cOrGkb6QIvj1EWTczQY_/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 1d3861b6cb11282117c9ae5c229a095c157c1859

**Comment by atcastle** [comment]
@danielolaviobr Could you give a little more context about what the desired behavior is, that this example is demonstrating? Specifically could you explain why you want to give an image a specific size if it's constrained inside a fixed-size parent element? I'd like to understand why `layout="fill"` plus an object-fit property doesn't work here.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: bb973be201b22b3c59c0fdfdcb7f95779cb85c36

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 822797309f46157138cc192e6db794b7ec015ac4

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 5142c0e542f88e98cc61c33aad939129b50126e4

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2a9e29f635086d61cced2b133b8b6f22fcc16f96

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should detect changes and refresh an AMP page
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect changes and refresh an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "I'm an AMP page!"
    Received: "replaced it!"

      361 |         browser = await webdriver(dynamicAppPort, '/hmr/amp')
      362 |         const text = await browser.elementByCss('p').text()
    > 363 |         expect(text).toBe(`I'm an AMP page!`)
          |                      ^
      364 |
      365 |         const hmrTestPagePath = join(__dirname, '../', 'pages', 'hmr', 'amp.js')
      366 |

      at Object.<anonymous> (integration/amphtml/test/index.test.js:363:22)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    TIMED OUT: /I'm an AMP page!/

    replaced it!

      399 |
      400 |   if (hardError) {
    > 401 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      402 |   }
      403 |   return false
      404 | }

      at check (lib/next-test-utils.js:401:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:409:9)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 98acfaf8ccd21e6965dc5c9ca38d15c454848838

**test/integration/config-devtool-dev/test/index.test.js** 
- devtool set in development mode in next config > should warn and revert when a devtool is set in development mode

<details>
<summary>Expand output</summary>

  ● devtool set in development mode in next config › should warn and revert when a devtool is set in development mode

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      17 |
      18 | describe('devtool set in development mode in next config', () => {
    > 19 |   it('should warn and revert when a devtool is set in development mode', async () => {
         |   ^
      20 |     let stderr = ''
      21 |
      22 |     const appPort = await findPort()

      at integration/config-devtool-dev/test/index.test.js:19:3
      at Object.<anonymous> (integration/config-devtool-dev/test/index.test.js:18:1)

</details>

**Review by ijjk — COMMENTED** [review]
Hi, I think our existing example page here https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/layout-fill.js covers this, if not please reply with additional info and we can investigate further!

**Pull request closed without merging**
