### PR TITLE
Support generating multi-meta tags for metadata api other prop

### LINKED ISSUE #57051: Unable to add multiple meta tags with the same name (app directory)
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/staging-firefly-cf45hv

### To Reproduce

it's easy to reproduce, create a new next project, using the app directory 

use generateMetadata other field to add meta tags that require multiple ones with the same name

### Current vs. Expected behavior

I want to add multiple meta tags with the same name, **example** _music:song, citation_author..._

I was checking the `metadata-interface.d.ts` file 
`    other?: {
        [name: string]: string | number | Array<string | number>;
    } & DeprecatedMetadataFields;
`
using the `generateMetadata` function
```
export async function generateMetadata() {
  return {
    other: {
     'music:song:track': ['1','2','3']
    }
  };
}
```
is resulting in 
```
<meta name="music:song:track" content="1,2,3">
```
instead of 
```
<meta name="music:song:track" content="1">
<meta name="music:song:track" content="2">
<meta name="music:song:track" content="3">
```

And adding `<meta />` tags in  next `<head />` is not rendering too

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Additional context

_No response_

<sub>[NEXT-1746](https://linear.app/vercel/issue/NEXT-1746/unable-to-add-multiple-meta-tags-with-the-same-name-app-directory)</sub>

### PR DESCRIPTION
**Pull request by huozhi**
Give flexibility to generate multiple same-key metadata k-v

```js
export const metadata = {
  other: {
    'my-own-meta-name': ['1','2']
  }
}
```

#### Before
```html
<meta key="my-own-meta-name" value="1,2">
```

#### Now
```html
<meta key="my-own-meta-name" value="1">
<meta key="my-own-meta-name" value="2">
```

When you want to have the array joined like value, you can do it when you pass the value down to `other` property. And if you want multiple one, you could specify array to generate them

Closes #57051 
Closes NEXT-1746

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c98a29070e53d72148abfea266fc487855c54dba

`pnpm test-dev test/development/app-hmr/hmr.test.ts` 
- app-dir-hmr > filesystem changes > should not break when renaming a folder

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should not break when renaming a folder

    TIMED OUT: success

    undefined

    Error: elementHandle.innerText: Element is not attached to the DOM

      626 |
      627 |   if (hardError) {
    > 628 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content + '\n\n' + lastErr)
          |           ^
      629 |   }
      630 |   return false
      631 | }

      at check (lib/next-test-utils.ts:628:11)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:44:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.5s | ⚠️ +148ms |
| buildDurationCached | 5.8s | 6.6s | ⚠️ +783ms |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +5.12 kB |
| nextStartRea..uration (ms) | 422ms | 423ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.7 kB | 30.7 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 494.HASH.js gzip | 180 B | 181 B | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 241 B | 239 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 501 B | 503 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | ✓ |
| edge-ssr-HASH.js gzip | 253 B | 255 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.61 kB | 2.6 kB | N/A |
| routerDirect..HASH.js gzip | 311 B | 311 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.17 kB | 3.17 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| index.html gzip | 528 B | 526 B | N/A |
| link.html gzip | 538 B | 541 B | N/A |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| edge-ssr.js gzip | 92.6 kB | 92.6 kB | N/A |
| page.js gzip | 146 kB | 146 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 626 B | ✓ |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 35.7 kB | 35.7 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.55 kB | 2.55 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js metadata/multi-others | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 93.7 kB | 93.7 kB | N/A |
| app-page-tur..prod.js gzip | 94.5 kB | 94.5 kB | N/A |
| app-page-tur..prod.js gzip | 89 kB | 89 kB | N/A |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.4 kB | 88.4 kB | N/A |
| app-route-ex...dev.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route-ex..prod.js gzip | 16.8 kB | 16.8 kB | ✓ |
| app-route-tu..prod.js gzip | 16.9 kB | 16.9 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route.ru...dev.js gzip | 23.6 kB | 23.6 kB | ✓ |
| app-route.ru..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.6 kB | 22.6 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.3 kB | 49.3 kB | ✓ |
| Overall change | 564 kB | 564 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-tur..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: c98a29070e53d72148abfea266fc487855c54dba

**Comment by feedthejim** [comment]
should we edit the doc for that?

**Review by feedthejim — APPROVED** [review]

**Comment by huozhi** [comment]
@feedthejim Added the docs in [43a5240](https://github.com/vercel/next.js/pull/59106/commits/43a524000c0860de67e321e5306059e2599dcc65)

**Pull request merged**
