### PR TITLE
docs: add `Ory` to the list of auth libraries

### PR DESCRIPTION
**Pull request by aeneasr**
Ory: https://www.ory.sh/docs/getting-started/integrate-auth/nextjs
Ory GitHub: https://github.com/ory

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: b5df0a2cc1347a39bd3e857cd6ad6a32aaa25032

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by devjiwonchoi** [comment]
Hi, please change the base branch to `canary` (this PR is pointing `main`). Thank you!

**Comment by aeneasr** [comment]
@devjiwonchoi done! :)

**Comment by devjiwonchoi** [comment]
Thank you for the PR! FYI I've updated the title and description for future readers.
Could you wait for a bit to get this merged? We are trying to send RC 2-related commits to canary for easier tracking.
Will get this merged around early November. How does that sound?

**Review by devjiwonchoi — APPROVED** [review]

**Comment by aeneasr** [comment]
Sounds good, thank you! :)

**Review by ijjk — APPROVED** [review]

**Pull request merged**
