### PR TITLE
Add warning when LCP image is missing `priority` prop

### PR DESCRIPTION
**Pull request by styfle**
This will warn when Next.js detected an image as the LCP element but its missing the `priority` prop.

- Related to #30218

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: aa083de7da80a590c2f4b7746e5a1e35e629dff0

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:424:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after exporting an invalid page 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about5"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      487 |
      488 |         expect(await hasRedbox(browser)).toBe(true)
    > 489 |         expect(await getRedboxHeader(browser)).toMatchInlineSnapshot(`
          |                                                ^
      490 |           " 1 of 1 unhandled error
      491 |           Server Error
      492 |

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:489:48)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:613:8)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| buildDuration | 17.2s | 17.3s | ⚠️ +181ms |
| buildDurationCached | 3.6s | 3.4s | -177ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +2.93 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.096 | 3.112 | ⚠️ +0.02 |
| / avg req/sec | 807.48 | 803.45 | ⚠️ -4.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.726 | 1.63 | -0.1 |
| /error-in-render avg req/sec | 1448.43 | 1533.92 | +85.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| 450.126dd8f7..9662.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-4c83cbc..5816.js gzip | 27.7 kB | 27.7 kB | ✓ |
| webpack-7ed4..c253.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| _app-e2cfdd4..f20e.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-6679c..c50e.js gzip | 194 B | 194 B | ✓ |
| amp-e55eb6be..a860.js gzip | 312 B | 312 B | ✓ |
| css-3561b6c4..ef9e.js gzip | 327 B | 327 B | ✓ |
| dynamic-3814..830e.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-0b292cc..7d7c.js gzip | 350 B | 350 B | ✓ |
| hooks-a534e8..efa1.js gzip | 635 B | 635 B | ✓ |
| image-07bccd..d945.js gzip | 4.44 kB | 4.44 kB | ⚠️ +3 B |
| index-d12b47..75f9.js gzip | 263 B | 263 B | ✓ |
| link-a8a0a12..1f88.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..6a79.js gzip | 321 B | 321 B | ✓ |
| script-e1458..a8d4.js gzip | 383 B | 383 B | ✓ |
| withRouter-b..6929.js gzip | 318 B | 318 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| index.html gzip | 536 B | 536 B | ✓ |
| link.html gzip | 548 B | 548 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-c60c37af3228a150.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-ec5f7654a3bab5fa.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-c60c37..f3228a150.js</strong></summary>

```diff
@@ -172,6 +172,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var allImgs = new Map();
+      var perfObserver;
       var emptyDataURL =
         "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (false) {
@@ -619,6 +621,9 @@
           });
         }
         var srcString = src;
+        if (false) {
+          var fullUrl;
+        }
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.6s | -25ms |
| buildDurationCached | 3.5s | 3.4s | -29ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +2.93 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.071 | 3.138 | ⚠️ +0.07 |
| / avg req/sec | 813.96 | 796.78 | ⚠️ -17.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.657 | 1.599 | -0.06 |
| /error-in-render avg req/sec | 1508.31 | 1563.11 | +54.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-30a0900..79fc.js gzip | 36.1 kB | 36.1 kB | ✓ |
| webpack-9f86..1988.js gzip | 1.57 kB | 1.57 kB | ✓ |
| Overall change | 88.6 kB | 88.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-de3d..5a68.js gzip | 2.72 kB | 2.72 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-17d548..6bf2.js gzip | 5.11 kB | 5.11 kB | ⚠️ +5 B |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-b0ce9b3..48f4.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 14.6 kB | 14.6 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 458 B | -1 B |
| Overall change | 459 B | 458 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js automatically-detect-lcp-image-and-warn | Change |
| - | - | - | - |
| index.html gzip | 536 B | 536 B | ✓ |
| link.html gzip | 548 B | 548 B | ✓ |
| withRouter.html gzip | 530 B | 530 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-c60c37af3228a150.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-ec5f7654a3bab5fa.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-c60c37..f3228a150.js</strong></summary>

```diff
@@ -172,6 +172,8 @@
         return target;
       }
       var loadedImageURLs = new Set();
+      var allImgs = new Map();
+      var perfObserver;
       var emptyDataURL =
         "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";
       if (false) {
@@ -619,6 +621,9 @@
           });
         }
         var srcString = src;
+        if (false) {
+          var fullUrl;
+        }
         return /*#__PURE__*/ _react.default.createElement(
           "span",
           {
```
</details>
</details>
Commit: 3e2032ebd663902b5df96644cbe6752ef38434c8

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3e2032ebd663902b5df96644cbe6752ef38434c8

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should recover after a bad return from the render function
- basic HMR > Error Recovery > should recover after undefined exported as default
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:557:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:613:8)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    TIMED OUT: /an-expected-error-in-gip/

    null

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:495:17)

</details>

**Review by molebox — APPROVED** [review]
very-good

**Review by timneutkens — APPROVED** [review]

**Review by kara — APPROVED** [review]
LGTM

**Review by ijjk — APPROVED** [review]

**Pull request merged**
