### PR TITLE
fix(#36435): apply correct fix

### PR DESCRIPTION
**Pull request by SukkaW**
## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

The PR is to supersede #36435 by applying a correct fix for #36183.

### CODE REVIEW

**Comment by SukkaW** [comment]
cc @ijjk @Brooooooklyn 

The swc can automatically apply the transpilation for `default interop export`:

```js
// next/dist/client/link.js, next/dist/client/script.js
if (typeof exports.default === 'function' || (typeof exports.default === 'object' && exports.default !== null)) {
  Object.assign(exports.default, exports);
  module.exports = exports.default;
}
```

The reason `next/link` and `next/script` is unaffected, is the `interopClientDefaultExport` flag is enabled for `client/**/*.+(js|ts|tsx)`.

https://github.com/vercel/next.js/blob/26efcc5ded3485b996a3652407924c157112ee07/packages/next/taskfile.js#L1836

However, `next/head` and `next/dynamic` are reexported from `shared/lib`, where `interopClientDefaultExport` flag is not enabled:

https://github.com/vercel/next.js/blob/26efcc5ded3485b996a3652407924c157112ee07/packages/next/taskfile.js#L1926

The PR apply the correct fix by enabling the  `interopClientDefaultExport` flag.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a5b966a14a698861c50cfe0acfc99a54219bac12

`yarn testheadless test/integration/app-document/test/index.test.js` 
- Document and App > should not have any missing key warnings
- Document and App > Client side > should detect the changes to pages/_app.js and display it
- Document and App > Client side > should detect the changes to pages/_document.js and display it
- Document and App > Client side > should keep state between page navigations
- Document and App > Client side > It should share module state with pages
- Document and App > Rendering via HTTP > _app > It shows a custom tag
- Document and App > Rendering via HTTP > _app > It should share module state with pages
- Document and App > Rendering via HTTP > _app > It should show valid error when thrown in _app getInitialProps
- Document and App > Rendering via HTTP > _document > It has a custom html class
- Document and App > Rendering via HTTP > _document > It has a custom body class
- Document and App > Rendering via HTTP > _document > It injects custom head tags
- Document and App > Rendering via HTTP > _document > It passes props from Document.getInitialProps to Document
- Document and App > Rendering via HTTP > _document > It adds nonces to all scripts and preload links
- Document and App > Rendering via HTTP > _document > It adds crossOrigin to all scripts and preload links
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhancer correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp correctly
- Document and App > Rendering via HTTP > _document > It renders ctx.renderPage with enhanceApp and enhanceComponent correctly
- Document and App > Rendering via HTTP > _document > It adds a timestamp to link tags with preload attribute to invalidate the cache (DEV only)
- Document and App > With CSP enabled > should load inline script by hash
- Document and App > With CSP enabled > should load inline script by nonce

<details>
<summary>Expand output</summary>

  ● Document and App › should not have any missing key warnings

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It has a custom html class

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It has a custom body class

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It injects custom head tags

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It passes props from Document.getInitialProps to Document

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It adds nonces to all scripts and preload links

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It adds crossOrigin to all scripts and preload links

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhancer correctly

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceComponent correctly

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp correctly

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It renders ctx.renderPage with enhanceApp and enhanceComponent correctly

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _document › It adds a timestamp to link tags with preload attribute to invalidate the cache (DEV only)

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _app › It shows a custom tag

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _app › It should share module state with pages

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Rendering via HTTP › _app › It should show valid error when thrown in _app getInitialProps

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Client side › should detect the changes to pages/_app.js and display it

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Client side › should detect the changes to pages/_document.js and display it

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Client side › should keep state between page navigations

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › Client side › It should share module state with pages

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › With CSP enabled › should load inline script by hash

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● Document and App › With CSP enabled › should load inline script by nonce

    FetchError: request to http://localhost:36197/ failed, reason: connect ECONNREFUSED 127.0.0.1:36197

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      403 | // Kill a launched app
      404 | export async function killApp(instance) {
    > 405 |   await killProcess(instance.pid)
          |                              ^
      406 | }
      407 |
      408 | export async function startApp(app) {

      at Object.killApp (lib/next-test-utils.js:405:30)
      at integration/app-document/test/index.test.js:40:41

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.1s | -135ms |
| buildDurationCached | 6.4s | 6.3s | -137ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +726 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.368 | 3.441 | ⚠️ +0.07 |
| / avg req/sec | 742.32 | 726.57 | ⚠️ -15.75 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.436 | 1.536 | ⚠️ +0.1 |
| /error-in-render avg req/sec | 1740.48 | 1627.15 | ⚠️ -113.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ⚠️ +1 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.04 kB | 3.08 kB | ⚠️ +40 B |
| head-HASH.js gzip | 378 B | 357 B | -21 B |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.63 kB | 2.63 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 531 B | -2 B |
| link.html gzip | 546 B | 544 B | -2 B |
| withRouter.html gzip | 526 B | 525 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -2,15 +2,15 @@ self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
   "/": ["static\u002Fchunks\u002Fpages\u002Findex-a49797fad5e5a39b.js"],
   "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-5d03de5a43fe90da.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-3eb62f36e98a75e2.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-c7cbac1df9ead194.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
     "static\u002Fchunks\u002Fpages\u002Fcss-f8d6ff68a6e8b080.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-2fc05fc466ebee90.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-7fda0a7b63c06ef1.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-b3f5cd04a41e9ce4.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-ae8daed8e1e5c446.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-4ebd299a1253d245.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5b526b867abc83fc.js"],
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -47,6 +47,9 @@
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
         9135
       );
+      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
+        next_amp__WEBPACK_IMPORTED_MODULE_0__
+      );
 
       var config = {
         amp: "hybrid"
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -18,13 +18,8 @@
       /***/
     },
 
-    /***/ 7645: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 7645: /***/ function(module, exports, __webpack_require__) {
       "use strict";
-      var __webpack_unused_export__;
 
       function _defineProperty(obj, key, value) {
         if (key in obj) {
@@ -67,11 +62,11 @@
         }
         return target;
       }
-      __webpack_unused_export__ = {
+      Object.defineProperty(exports, "__esModule", {
         value: true
-      };
+      });
       exports["default"] = dynamic;
-      __webpack_unused_export__ = noSSR;
+      exports.noSSR = noSSR;
       var _react = _interopRequireDefault(__webpack_require__(7294));
       var _loadable = _interopRequireDefault(__webpack_require__(4588));
       function dynamic(dynamicOptions, options) {
@@ -160,6 +155,13 @@
             timedOut: false
           });
         };
+      }
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
       } //# sourceMappingURL=dynamic.js.map
 
       /***/
@@ -586,9 +588,11 @@
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
         5152
       );
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
+        next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+      );
 
-      var DynamicHello = (0,
-      next_dynamic__WEBPACK_IMPORTED_MODULE_1__["default"])(
+      var DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         function() {
           return __webpack_require__
             .e(/* import() */ 925)
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -76,9 +76,7 @@
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      var head = __webpack_require__(3121);
-      Object.assign(head.default, head);
-      module.exports = head.default;
+      module.exports = __webpack_require__(3121);
 
       /***/
     }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3681,11 +3681,7 @@
       /***/
     },
 
-    /***/ 1686: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 1686: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -3718,6 +3714,13 @@
         return isInAmpMode(
           _react.default.useContext(_ampContext.AmpStateContext)
         );
+      }
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
       } //# sourceMappingURL=amp.js.map
 
       /***/
@@ -3771,11 +3774,7 @@
       /***/
     },
 
-    /***/ 3121: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 3121: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       function _defineProperty(obj, key, value) {
@@ -4020,7 +4019,14 @@
         );
       }
       var _default = Head;
-      exports["default"] = _default; //# sourceMappingURL=head.js.map
+      exports["default"] = _default;
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=head.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| buildDuration | 19s | 18.4s | -599ms |
| buildDurationCached | 6.5s | 6.3s | -266ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +726 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.486 | 3.357 | -0.13 |
| / avg req/sec | 717.26 | 744.63 | +27.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.468 | 1.417 | -0.05 |
| /error-in-render avg req/sec | 1703.44 | 1763.88 | +60.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | -1 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.02 kB | 3.08 kB | ⚠️ +59 B |
| head-HASH.js gzip | 385 B | 359 B | -26 B |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.78 kB | 5.78 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.74 kB | 2.74 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.4 kB | 16.5 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 456 B | 458 B | ⚠️ +2 B |
| Overall change | 456 B | 458 B | ⚠️ +2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SukkaW/next.js fix-36435 | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 542 B | 541 B | -1 B |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -2,15 +2,15 @@ self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
   "/": ["static\u002Fchunks\u002Fpages\u002Findex-a49797fad5e5a39b.js"],
   "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-5d03de5a43fe90da.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-3eb62f36e98a75e2.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-c7cbac1df9ead194.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
     "static\u002Fchunks\u002Fpages\u002Fcss-f8d6ff68a6e8b080.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-2fc05fc466ebee90.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-7fda0a7b63c06ef1.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-b3f5cd04a41e9ce4.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-ae8daed8e1e5c446.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-9dfe734f583d4926.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-4ebd299a1253d245.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5b526b867abc83fc.js"],
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -47,6 +47,9 @@
       /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
         9135
       );
+      /* harmony import */ var next_amp__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
+        next_amp__WEBPACK_IMPORTED_MODULE_0__
+      );
 
       var config = {
         amp: "hybrid"
```
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -18,13 +18,8 @@
       /***/
     },
 
-    /***/ 7645: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 7645: /***/ function(module, exports, __webpack_require__) {
       "use strict";
-      var __webpack_unused_export__;
 
       function _defineProperty(obj, key, value) {
         if (key in obj) {
@@ -67,11 +62,11 @@
         }
         return target;
       }
-      __webpack_unused_export__ = {
+      Object.defineProperty(exports, "__esModule", {
         value: true
-      };
+      });
       exports["default"] = dynamic;
-      __webpack_unused_export__ = noSSR;
+      exports.noSSR = noSSR;
       var _react = _interopRequireDefault(__webpack_require__(7294));
       var _loadable = _interopRequireDefault(__webpack_require__(4588));
       function dynamic(dynamicOptions, options) {
@@ -160,6 +155,13 @@
             timedOut: false
           });
         };
+      }
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
       } //# sourceMappingURL=dynamic.js.map
 
       /***/
@@ -586,9 +588,11 @@
       /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(
         5152
       );
+      /* harmony import */ var next_dynamic__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/ __webpack_require__.n(
+        next_dynamic__WEBPACK_IMPORTED_MODULE_1__
+      );
 
-      var DynamicHello = (0,
-      next_dynamic__WEBPACK_IMPORTED_MODULE_1__["default"])(
+      var DynamicHello = next_dynamic__WEBPACK_IMPORTED_MODULE_1___default()(
         function() {
           return __webpack_require__
             .e(/* import() */ 925)
```
</details>
<details>
<summary>Diff for <strong>head-HASH.js</strong></summary>

```diff
@@ -76,9 +76,7 @@
       __unused_webpack_exports,
       __webpack_require__
     ) {
-      var head = __webpack_require__(3121);
-      Object.assign(head.default, head);
-      module.exports = head.default;
+      module.exports = __webpack_require__(3121);
 
       /***/
     }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -3681,11 +3681,7 @@
       /***/
     },
 
-    /***/ 1686: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 1686: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -3718,6 +3714,13 @@
         return isInAmpMode(
           _react.default.useContext(_ampContext.AmpStateContext)
         );
+      }
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
       } //# sourceMappingURL=amp.js.map
 
       /***/
@@ -3771,11 +3774,7 @@
       /***/
     },
 
-    /***/ 3121: /***/ function(
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) {
+    /***/ 3121: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
       function _defineProperty(obj, key, value) {
@@ -4020,7 +4019,14 @@
         );
       }
       var _default = Head;
-      exports["default"] = _default; //# sourceMappingURL=head.js.map
+      exports["default"] = _default;
+      if (
+        typeof exports.default === "function" ||
+        (typeof exports.default === "object" && exports.default !== null)
+      ) {
+        Object.assign(exports.default, exports);
+        module.exports = exports.default;
+      } //# sourceMappingURL=head.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-281ff28f99ec8d26.js"
+      src="/_next/static/chunks/main-fce01dd8f1599e4c.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 47b967bb89192e1d8945228d31808fe20f9a3140

**Review by Brooooooklyn — COMMENTED** [review]
I'm wondering if https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/loaders/utils.ts#L3 should also add `amp` `config` `constants`, `dynamic`.

It's better to add some specs into `test/e2e/type-module-interop/index.test.ts` to verify it.

**Comment by SukkaW** [comment]
@Brooooooklyn The test cases for `next/dynamic` and `next/amp` is added.

**Review by Brooooooklyn — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Pull request merged**
