### PR TITLE
pass webpack-bundle-analyzer options to next-bundle-analyzer

### PR DESCRIPTION
**Pull request by rashidul0405**
This pull request adds the ability to pass `webpack-bundle-analyzer` options to `next-bundle-analyzer`

Use case:
Sometimes we don't want to open the analyzer by default, so used to write as below:
```js
new BundleAnalyzerPlugin({
  analyzerMode: "static",
  openAnalyzer: false,
  reportFilename: isServer
      ? "../server-bundle-analysis.html"
      : "./client-bundle-analysis.html"
})
```
this implementation will provide the ability to pass bundle-analyzer config as below:
```js
const withBundleAnalyzer = require("@next/bundle-analyzer")({ 
  enabled: process.env.ANALYZE === "true",
  analyzerOptions: {
    openAnalyzer: false
  } 
});
```

### CODE REVIEW

**Review by lfades — APPROVED** [review]

**Review by timneutkens — COMMENTED** [review]
I don't think options should be added. Instead it should have good defaults.

**Comment by rashidul0405** [comment]
@timneutkens I think next (considering `next.config.js`) believe this idea: _super defaults with a sensible and obvious override/extension strategy_ (https://twitter.com/kentcdodds/status/942177631981649921)

**Comment by rashidul0405** [comment]
So should we ignore(close) this or you want to consider this? @timneutkens @lfades

**Comment by lfades** [comment]
@rashidul0405 For me this is okay, but @timneutkens  is also right, if we add this we should also add documentation for it and we don't need to if we have good defaults, if there're better defaults you can change that.

**Comment by jondavidjohn** [comment]
I built a tool to help you analyze webpack bundles for size regressions, and report them directly to GitHub PRs. It's free for open source, so it _might_ be worth checking out instead of building an in house tool

[https://packtracker.io](https://packtracker.io/?utm_campaign=links&utm_source=github&utm_medium=issueprcomment)

image

**Comment by rashidul0405** [comment]
@lfades I also added documentation as part of this pull requests. Or are you saying different way to document?

**Comment by rashidul0405** [comment]
@lfades I’m also good with better defaults, whatever you guys prefer as you know better.

**Comment by timneutkens** [comment]
I think we should not have these options exposed. Instead it shouldn't open a new window by default and should log out a message saying where the files are available so that the user can open them.

**Pull request closed without merging**
