### PR TITLE
Link to `with-docker-multi-env` example.

### PR DESCRIPTION
**Pull request by leerob**
Based on feedback from Twitter to surface this more. A small improvement before improving the deployment docs further 😄

### CODE REVIEW

**Review by styfle — APPROVED** [review]

**Comment by Janpot** [comment]
@leerob Are there any examples on making docker images that contain Next.js apps runtime configurable? Use case is distributing your app for e.g. on-premise installations. I feel like this becomes harder and harder to do as Next.js keeps adding features that are build time configurable only (next.config.js routing options, middleware, env,...)

**Comment by leerob** [comment]
What do you mean by runtime configurable here? Sounds like you want something like [Vault](https://www.vaultproject.io/)?

**Comment by mAAdhaTTah** [comment]
@leerob Having multiple containers per-environment denies us the ability to ship the same container to every environment, which increases confidence that the code is working as expected in lower environments before going to production. We definitely need actual runtime configuration values.

**Comment by leerob** [comment]
Have you explored a solution like Vault? I ask because I've used this in the past with a k8s Next.js setup.

**Comment by mAAdhaTTah** [comment]
@leerob We're on AWS, so we're using Parameter Store.

**Comment by Janpot** [comment]
> What do you mean by runtime configurable here?

@leerob  For example, suppose I'm distributing my app as a docker image, and I'd like users to be able to set environment variables in the container for user/password to enable basic auth. Now I can't implement this through Next.js middleware as there is no way to pass runtime configuration to it.

**Comment by leerob** [comment]
> We're on AWS, so we're using Parameter Store.

And fetching values from Parameter Store isn't working, is that correct? 

https://docs.aws.amazon.com/cdk/v2/guide/get_ssm_value.html

**Comment by leerob** [comment]
To be more clear, the feedback is about the _example_ here and not Next.js then? E.g. you can use Parameter Store or Vault or other similar tools with Next.js - and your feedback is that you want to see the same Docker image promoted through all environments in this example. Correct?

**Comment by Janpot** [comment]
> To be more clear, the feedback is about the example here and not Next.js then?

It's about both:
1. The example is not representative for many people's workflows using docker (distributing Docker images that are configurable using environment variables). It's essentially just the `with-docker` example copied three times over.
2. Next.js increasingly makes new features 'build-time configurable'-only which in turn makes it hard/impossible to use them in such way. Build-time-only configuration makes sense if you host on Vercel's platform, but we need other ways of hosting as well (e.g. I need to distribute a Docker image for on-premise installations).

**Comment by leerob** [comment]
> Build-time-only configuration makes sense if you host on Vercel's platform, but we need other ways of hosting as well (e.g. I need to distribute a Docker image for on-premise installations).

Self-hosted Next.js is the most popular way of deploying Next.js applications, so I think we're just missing a good example here showing how to handle this. When I was running a Docker + K8s + Next.js app we used Vault for runtime config and it worked pretty well 👍 Appreciate the feedback.

**Pull request merged**
