### PR TITLE
Remove `type==="a"` check when setting props

### PR DESCRIPTION
**Pull request by ajacksified**
I ran into an issue when statically exporting a site that used a `<Link>` which wrapped a custom element. The custom element was a wrapper around an `<a>` tag with custom styling - the dom node was just an `<a>` with some text and css - but because the literal _type_ was not `<a>`, the href of the `<a>` tag ended up as `undefined`.

Example:

```javascript
import { Link } from 'next/link';

const CustomLink = ({ href, children }) => (
  <a href={href } style={{ color: '#f00' }}>{children}</a>
);

const routes = { home: "/", docs: "/docs" };

export default () => (
  <div class="toolbar">
    { Object.keys(routes).map(title => (
      <Link href={routes[title]}>
        <CustomLink>{title}</CustomLink>
      </Link>
    ))}
  </div>
); 
```

I've taken the easiest approach - simply removing the `a` check, but leaving the check for `href`. There's a more complicated approach that could be taken, where we clone the element, assign it a ref, and check the dom node; but that seems like it may be overkill.

Using version 3.0.0-beta.8.

### CODE REVIEW

**Comment by timneutkens** [comment]
This wil give issues when someone uses a custom element that has proptypes that don't include `href`. Technically `href` is not required to be set on the custom element cause you might want to create a link that only has an `onClick` handler.

Your use case can be simplified to this:
```
import { Link } from 'next/link';

const CustomLink = ({ href, children }) => (
  <Link href={href}>
      <a style={{ color: '#f00' }}>{children}</a>
  </Link>
);

const routes = { home: "/", docs: "/docs" };

export default () => (
  <div class="toolbar">
    { Object.keys(routes).map(title => (
      <CustomLink href={routes[title]}>{title}</CustomLink>
    ))}
  </div>
); 
```

Also note that using `style={{ color: '#f00' }}` vs using styled-jsx causes every single `CustomLink` component to have `style="color: #f00"` whereas the following example using styled-jsx will only render the styles once, which leads to less html 👌 Also, styled-jsx automatically handles vendor prefixing your styles 👍 

```
import { Link } from 'next/link';

const CustomLink = ({ href, children }) => (
  <Link href={href}>
      <a>{children}</a>
      <style jsx>{`a { color: #f00 }`}</style>
  </Link>
);

const routes = { home: "/", docs: "/docs" };

export default () => (
  <div class="toolbar">
    { Object.keys(routes).map(title => (
      <CustomLink href={routes[title]}>{title}</CustomLink>
    ))}
  </div>
); 
```

To wrap it up I don't feel like we should change the `<Link>` component api any further, it has good defaults and you can basically do anything you want with it when you wrap it into your own component / use the router api directly 👌 

cc @arunoda what do you think?

**Comment by ajacksified** [comment]
My example was pretty contrived- I tried to simplify what was going on. I ran into the issue using a third party library, [rebass](https://rebass-beta.now.sh), where I don't have access to the "CustomLink" element- or, NavItem, in my case, which generates a react element which returns an `a` tag.

> Also note that using...

(For the record, I hate inline styles; I'm well aware of the pitfalls. I was throwing together a simple documentation site, and rebass gave me an easy way to get it shipped quickly. I don't even like styled-jsx, and would rather just use sass, but that's not an argument I want to open here.)

> To wrap it up I don't feel like we should change the <Link> component api any further

I'm not suggesting changing the api, I am suggesting that we fix a bug in the implementation. As implemented currently, it sets the child component's `href` to the value `undefined`, whether the child has an `href` or not, based on whether the child is an `a`. A proper fix would be to actually find the `a` DOM element and set the href on _that_, if `Link` has an `href` and the `a` does not.

Example: if instead of:

```javascript
      <Link href={routes[title]}>
        <CustomLink>{title}</CustomLink>
      </Link>
```

You have:

```javascript
      <Link href={routes[title]}>
        <CustomLink href={routes[title]}>{title}</CustomLink>
      </Link>
```

The rendered `a` tag's `href` is still set to `undefined` instead of the value I'm passing in. I don't even mind having to pass it in twice if I have to, but it shouldn't be overriding the prop to undefined.

I'll also note that this only happens on export, not server mode. ¯\_(ツ)_/¯

**Comment by sedubois** [comment]
I think it's the same issue I was mentioning here: 
https://github.com/zeit/next.js/issues/2082#issuecomment-304517892

There indeed seems to be a bug.

**Comment by arunoda** [comment]
I don't like passing an `href` always since it might violate some propTypes as mentioned by @timneutkens 

```js
<Link href={routes[title]}>
  <CustomLink href={routes[title]}>{title}</CustomLink>
</Link>
```

But ^^^ should work properly on `next export`. I'll have a look at it.

**Comment by ajacksified** [comment]
I don't mind the duplication, although the docs may want to make it clear that you can only avoid duplication on a literal `a` tag.

Another way, although it's a bigger change, is the way we implemented this at [reddit](https://github.com/reddit/node-platform/blob/master/lib/modules/components.js#L155)- we provide both a <Link> (we called it Anchor) element and a <LinkHijacker> element. The former rendered the A tag, while the latter would watch for link clicks and route the href through the router. LinkHijacker was useful when wrapping custom components and also for user-generated content, like links in comment markdown. That gave us both the common usecase and flexibility.

Anyways, that's a big change. I haven't looked yet, but if it's possible to access the router programmatically, I can build my own LinkHijacker to get around it, once the `undefined` bug is killed.

**Comment by timneutkens** [comment]
Documented in #2369

**Pull request closed without merging**
