### PR TITLE
Make WithRouterProps accept the type of the query

### PR DESCRIPTION
**Pull request by felixmosh**
This PR is part of #7797, it allows to define the type of QueryString.

This PR only extends the type, the Query type is optional, if given it extends the type if not, it works the same.
### Without type
image

### With type
image
image

### CODE REVIEW

**Comment by lfades** [comment]
@felixmosh Can you add tests for the new types in `test/integration/typescript` 🙏 . I'm still not too sure about how is this useful 🤔

**Comment by timneutkens** [comment]
For some reason bundle size increased quite a bit.

**Review by timneutkens — CHANGES_REQUESTED** [review]
Bundle size increased quite a bit for a types change, we don't want to increase bundle size for a change like this.

**Comment by felixmosh** [comment]
> Bundle size increased quite a bit for a types change, we don't want to increase bundle size for a change like this.

I'm not sure how this PR increases bundle size, can you help?
The only thing that I've think that may affect this is [re-exporting of WithRouterProps](https://github.com/zeit/next.js/pull/7922/files#diff-480c057ba0f7f11c0139507bbfdfa26fR115) but I'm not sure how this related to bundle size.

**Comment by timneutkens** [comment]
Yeah I'm pretty sure it's related to the re-export. The reason for that is that types are stripped but this is just an export

**Comment by felixmosh** [comment]
> Yeah I'm pretty sure it's related to the re-export. The reason for that is that types are stripped but this is just an export

But there was an import to that file, I've just added a specific import of a type to it :\

**Comment by felixmosh** [comment]
Ping, any updates?

**Comment by lfades** [comment]
Hi @felixmosh I'm still not sure if it's worthed to increase the build size for this, I don't like the test added [here](https://github.com/zeit/next.js/pull/7922/files#diff-a0562181464a778020b40d61d9327b4b), it feels too complicated, I would prefer to do `const query = router.query as { page: string }` instead. Let me know what you think, cc @Timer

**Comment by felixmosh** [comment]
Where do u see bundle size increase? It is only type change 😔
Any way my PR is just alignment of those type with the community one.

**Comment by timneutkens** [comment]
> Where do u see bundle size increase? It is only type change 😔

You can see it here:

https://github.com/zeit/next.js/pull/7922#issuecomment-515757497

Diff is included

**Comment by felixmosh** [comment]
I really want this ability, what I can do ?

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | felixmosh/next.js WithRouter-with-query-type | Change |
| - | - | - | - |
| Build Duration | 22.2s | 21.4s | -746ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +304 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ⚠️  +54 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ⚠️  +16 B |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 182 kB | ⚠️  +54 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ⚠️  +12 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | -1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ⚠️  +2 B |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +54 B |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ⚠️  +15 B |
| Client `commons` Modern Size | 169 kB | 169 kB | ⚠️  +54 B |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ⚠️  +12 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ⚠️  +683 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | felixmosh/next.js WithRouter-with-query-type | Change |
| - | - | - | - |
| Build Duration | 23.1s | 23.1s | ⚠️  +24ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +304 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ⚠️  +54 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ⚠️  +15 B |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 182 kB | ⚠️  +54 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ⚠️  +12 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +54 B |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ⚠️  +15 B |
| Client `commons` Modern Size | 169 kB | 169 kB | ⚠️  +54 B |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ⚠️  +12 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +82 B |
| Serverless `pages/link` gzip Size | 68.5 kB | 68.5 kB | ⚠️  +16 B |
| Serverless `pages/index` Size | 247 kB | 248 kB | ⚠️  +82 B |
| Serverless `pages/index` gzip Size | 66.3 kB | 66.4 kB | ⚠️  +15 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +82 B |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.1 kB | ⚠️  +15 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +82 B |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +16 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +82 B |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +15 B |
| Build Dir Size | 2.59 MB | 2.59 MB | ⚠️  +929 B |

</details>

<details>
        <summary>Diff for <strong>commons.js</strong></summary>

```diff

@@ -6704,7 +6704,7 @@ var _interopRequireDefault = __webpack_require__("KI45");
 exports.__esModule = true;
 exports.useRouter = useRouter;
 exports.makePublicRouterInstance = makePublicRouterInstance;
-exports.createRouter = exports.withRouter = exports["default"] = void 0;
+exports.createRouter = exports.WithRouterProps = exports.withRouter = exports["default"] = void 0;
 
 var _extends2 = _interopRequireDefault(__webpack_require__("htGi"));
 
@@ -6719,9 +6719,10 @@ exports.NextRouter = _router2.NextRouter;
 
 var _routerContext = __webpack_require__("9EOK");
 
-var _withRouter = _interopRequireDefault(__webpack_require__("0Bsm"));
+var _withRouter = _interopRequireWildcard(__webpack_require__("0Bsm"));
 
 exports.withRouter = _withRouter["default"];
+exports.WithRouterProps = _withRouter.WithRouterProps;
 /* global window */
 
 var singletonRouter = {

```
</details>
      


<details>
        <summary>Diff for <strong>commonsModern.js</strong></summary>

```diff

@@ -4850,7 +4850,7 @@ var _interopRequireDefault = __webpack_require__("KI45");
 exports.__esModule = true;
 exports.useRouter = useRouter;
 exports.makePublicRouterInstance = makePublicRouterInstance;
-exports.createRouter = exports.withRouter = exports.default = void 0;
+exports.createRouter = exports.WithRouterProps = exports.withRouter = exports.default = void 0;
 
 var _extends2 = _interopRequireDefault(__webpack_require__("htGi"));
 
@@ -4865,9 +4865,10 @@ exports.NextRouter = _router2.NextRouter;
 
 var _routerContext = __webpack_require__("9EOK");
 
-var _withRouter = _interopRequireDefault(__webpack_require__("0Bsm"));
+var _withRouter = _interopRequireWildcard(__webpack_require__("0Bsm"));
 
 exports.withRouter = _withRouter.default;
+exports.WithRouterProps = _withRouter.WithRouterProps;
 /* global window */
 
 const singletonRouter = {

```
</details>

**Comment by Timer** [comment]
@felixmosh I don't believe we're interested in pursuing this, for a few reasons:

1. It increases bundle sizes.
2. Typing a query is a flawed idea, since it's user-supplied data. The shape of the object **is not known**. If anything, we'd need to force the keys to be optional and have a specific type, which this PR does not.
3. You can always cast the `query` object to an interface within your page.
4. There's no 👍's on this PR, meaning there's not a lot of interest for this addition. 

For these reasons, I'm going to close this PR. We're not interested in having complete compatibility with the old community types, especially in these scenarios.

**Comment by felixmosh** [comment]
1. it increased the bundle with bytes, not sure if this is an issue with your bundle size method or not.
2. your comment is wrong, cause query strings are not defined by users but by dev, yeah, user can change its value, but the field it self defined by dev.
3. casting in TS world it not suggested, and requires to do so in each one of the query usages.
4. This PR is improvement of types, I'm not sure how many Next users are TS users.

Anyway, thank you for your time.

**Pull request closed without merging**
