### PR TITLE
Add canonicalBase config to allow setting absolute URL

### LINKED ISSUE #7261: Next JS producing invalid canonical meta tags in Next JS (according to Lighthouse)
# Bug report

## Describe the bug
Using AMP in next seems to be producing invalid canonical meta tags (at least, according to Google Lighthouse).

I've been working on an AMP app using Next JS, and have been improving performance and SEO with Google Lighthouse. Tonight I noticed a new alert (or maybe it was an old alert and I just now noticed it) at this URL: https://anything-grown-beta.nelsonwebdev.com/market/hibbing-farmers-market

If you go to that URL and run an audit, you'll see I get dinged for SEO:

Screen Shot 2019-05-05 at 8 08 46 PM

I tried putting my own metatag on the page, with an absolute path (I don't know exactly that that's what Google wants but I just wanted to see, and based it off this doc: https://developers.google.com/web/tools/lighthouse/audits/canonical). 

However, as you can probably guess, when I tried to put my own metatag on the page, Next JS got grumpy, albeit it did point me to this doc:

https://github.com/zeit/next.js/blob/master/errors/conflicting-amp-tag.md

What's the solution here? I really want to use AMP in Next JS (because it's awesome), but SEO is obviously a very high concern of mine.

Oh -- I'm on the latest canary, too. `8.1.1-canary.24`

### PR DESCRIPTION
**Pull request by ijjk**
Since Google seems to require an absolute canonical URL or else they ding the SEO score as seen [here](https://github.com/GoogleChrome/lighthouse/blob/24fe98250b81410e7567a9cb379b8fbb19ea3f2d/lighthouse-core/audits/seo/canonical.js#L112), this adds a `amp.canonicalBase` config to allow users to set the absolute URL base we use. 

Fixes: #7261

### CODE REVIEW

**Comment by Janpot** [comment]
@ijjk Would I be able to access this value in my app code?

**Comment by ijjk** [comment]
@Janpot the ideal solution for this is still being discussed, this was an initial approach that doesn't solve other related issues.

**Comment by Janpot** [comment]
The use-case I'm thinking of is the one of [this example](https://github.com/zeit/now-examples/blob/e9975b1485a06953615013976b13da4e64691ac9/monorepo/www/pages/index.js#L174). Here a base url is constructed based on host header. More specific, this approach give me an uneasy feeling because it seems to be a [potential vulnerability ](https://www.acunetix.com/blog/articles/automated-detection-of-host-header-attacks/) (disclaimer: I haven't verified this yet in the context of zeit now, but I've written code in the past that has been attacked with this technique). I'm very hesitant to use user-supplied headers to specify urls that are fetched server-side. That's why I will always prefer to provide this value from my own configuration as an environment variable. Seeing this PR makes me think I could use this value as a "safe" base url instead of the host header.

**Comment by timneutkens** [comment]
@ijjk could you change the option to `amp.canonicalBase` instead of global `canonicalBase`

**Review by Timer — CHANGES_REQUESTED** [review]
spoke at office

**Review by Timer — APPROVED** [review]

**Pull request merged**
