### PR TITLE
Update jest with typescript example

### PR DESCRIPTION
**Pull request by masives**
Remove redundant typescript references from NEXT 8. Update autogenerated configs

### CODE REVIEW

**Comment by huv1k** [comment]
👋 @masives, could you solve the merge conflict and update your branch to canary?

**Comment by masives** [comment]
@huv1k canary merged

**Review by timneutkens — COMMENTED** [review]
`"presets": ["next/babel"]` should be enough 🤔 Any reason for changing this?

**Review by timneutkens — CHANGES_REQUESTED** [review]
Posted a comment 👍

**Comment by timneutkens** [comment]
Thanks for your contribution! Next.js automatically adds this part https://github.com/zeit/next.js/pull/7969/files#diff-3da1d777329378a75956442ede621676R15 when the compiler (jest) does not support esmodules.

**Comment by masives** [comment]
Turns out I had out of date project as removing of unnecessary config was already done by someone else, my bad

**Pull request closed without merging**
