### PR TITLE
Fix: Cannot assign to read only property 'children'

### PR DESCRIPTION
**Pull request by awareness481**
## Bug

- [x] Fixes https://github.com/vercel/next.js/issues/24783
- [x] Integration tests added

## Documentation / Examples

- [x] Make sure the linting passes

The PR is currently unpolished. **If the solution is acceptable** please let me know so I can polish up the PR.

The integration test is built from this [repo](https://github.com/atdrago/repro-24783) which was provided here https://github.com/vercel/next.js/issues/24783#issuecomment-867671953

As far as I understand, taking the code below as an example:
```jsx
          {process.env.NODE_ENV === 'production' ? (
            <>
              <script />
              <script />
            </>
          ) : null}
```
~~The issue here seems to be that the `script` elements will be parsed here whether the `ternary` is true or false. However, if `false` their children will be set to `writable: false`~~ Edit: Not accurate, however the error is caused by trying to modify children that have writable: false

Removing this line https://github.com/vercel/next.js/blob/ca2426185c331104f3d55ea6541a8d822a0a3ef1/packages/next/pages/_document.tsx#L432 from `_document.tsx`  should make the integration test fail

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| buildDuration | 19.5s | 18.9s | -519ms |
| buildDurationCached | 4.3s | 4.2s | -135ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +435 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.544 | 3.606 | ⚠️ +0.06 |
| / avg req/sec | 705.44 | 693.22 | ⚠️ -12.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.416 | 2.269 | -0.15 |
| /error-in-render avg req/sec | 1034.64 | 1101.57 | +66.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 534 B | 534 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| buildDuration | 16s | 15.7s | -254ms |
| buildDurationCached | 6.4s | 6.5s | ⚠️ +21ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +435 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.445 | 3.569 | ⚠️ +0.12 |
| / avg req/sec | 725.71 | 700.41 | ⚠️ -25.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.248 | 2.211 | -0.04 |
| /error-in-render avg req/sec | 1111.97 | 1130.71 | +18.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | awareness481/next.js-1 children_unwritable | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 596 B | 596 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: ca2426185c331104f3d55ea6541a8d822a0a3ef1

**Review by styfle — APPROVED** [review]
Thanks! 🎉

**Comment by odannyc** [comment]
I'm am running into this issue currently. Is there a timeline when this will be merged or if there are current work arounds?

**Comment by styfle** [comment]
Looks like the branch was deleted so I opened a new PR here: #31784

**Pull request closed without merging**
