### PR TITLE
fix(WellKnownErrorsPlugin): avoid compilation warnings array with empty items

### PR DESCRIPTION
**Pull request by luismulinari**
Currently, when a webpack compilation warning is processed by `WellKnownErrorsPlugin` and it's indeed a well know error that should be bypassed, the warning item is simply deleted from the array, which will produce an array with empty items:

Example:
```js
{
  client: {
    loading: false,
    totalModulesCount: 2172,
    errors: null,
    warnings: [ <1 empty item> ]
  },
  server: {
    loading: false,
    totalModulesCount: 2119,
    errors: null,
    warnings: [ <1 empty item> ]
  },
  edgeServer: {
    loading: false,
    totalModulesCount: 58,
    errors: null,
    warnings: null
  },
  trigger: undefined,
  amp: {}
}
```

This array with empty items generates a side effect on the [build output](https://github.com/vercel/next.js/blob/3553c6516d7a9aba98876f9660af0ee7c94dc2a3/packages/next/src/build/output/store.ts#L124), since the `warning` array has empty items:

```
➤ npm run dev

> next dev

   ▲ Next.js 14.0.1-canary.3
   - Local:        http://localhost:3000
   - Environments: .env.development

 ✓ Ready in 2.6s
 ✓ Compiled /middleware in 109ms (58 modules)
 ○ Compiling /(dashboard)/page ...
 ⚠


 ⚠
```
CleanShot 2023-10-30 at 13 20 42@2x

This PR solves this issue by removing the `warning` item using the `Array.prototype.splice`, which removes the item instead of making the array position empty.

Related PR: https://github.com/vercel/next.js/pull/57073

### CODE REVIEW

**Review by feedthejim — DISMISSED** [review]

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: af9fd2644c16539bf56d9fe6c10109ff0a4eb6e9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by luismulinari** [comment]
Hey @feedthejim ! Thanks for your review on this. ❤️ 

Should I do anything else to get this merged?

**Comment by feedthejim** [comment]
let me rerun the cI

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.5s | N/A |
| buildDurationCached | 6s | 6.6s | ⚠️ +646ms |
| nodeModulesSize | 175 MB | 175 MB | N/A |
| nextStartRea..uration (ms) | 403ms | 400ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33.1 kB | 33.1 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.71 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 541 B | 541 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.4 kB | 96.4 kB | N/A |
| page.js gzip | 141 kB | 141 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | luismulinari/next.js fix-wellknown-errors-plugin-warnings-output | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: d713a58c822dc8e146e7216e4105d5825193ca0d

**Comment by luismulinari** [comment]
@feedthejim The CI was failing due to a lint issue that has been resolved: https://github.com/vercel/next.js/pull/57768/commits/1fc30448ecf3a8472996216d0e42a3f04eaf66d3

Sorry about that.

**Review by feedthejim — APPROVED** [review]

**Comment by luismulinari** [comment]
@feedthejim do you mind to rerun the CI?

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1fc30448ecf3a8472996216d0e42a3f04eaf66d3

`pnpm test-dev test/development/acceptance/ReactRefreshLogBox-builtins.test.ts` 
- ReactRefreshLogBox default > Module not found (missing global CSS)

<details>
<summary>Expand output</summary>

  ● ReactRefreshLogBox default › Module not found (missing global CSS)

    expect(received).toContain(expected) // indexOf

    Expected substring: "index page"
    Received string:    "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><meta name=\"next-head-count\" content=\"2\"><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1699442792114\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1699442792114\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1699442792114\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1699442792114\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1699442792114\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body style=\"\"><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1699442792114\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Module not found: Can't resolve './non-existent.css'\\n\\u003e 1 | import './non-existent.css'\\n  2 |\\n  3 | export default function App({ Component, pageProps }) {\\n  4 |   return \\u003cComponent {...pageProps} /\\u003e\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\",\"stack\":\"Error: Module not found: Can't resolve './non-existent.css'\\n\\u001b[0m\\u001b[31m\\u001b[1m\\u003e\\u001b[22m\\u001b[39m\\u001b[90m 1 |\\u001b[39m \\u001b[36mimport\\u001b[39m \\u001b[32m'./non-existent.css'\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 2 |\\u001b[39m\\u001b[0m\\n\\u001b[0m \\u001b[90m 3 |\\u001b[39m \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mfunction\\u001b[39m \\u001b[33mApp\\u001b[39m({ \\u001b[33mComponent\\u001b[39m\\u001b[33m,\\u001b[39m pageProps }) {\\u001b[0m\\n\\u001b[0m \\u001b[90m 4 |\\u001b[39m   \\u001b[36mreturn\\u001b[39m \\u001b[33m\\u003c\\u001b[39m\\u001b[33mComponent\\u001b[39m {\\u001b[33m...\\u001b[39mpageProps} \\u001b[33m/\\u001b[39m\\u001b[33m\\u003e\\u001b[39m\\u001b[0m\\n\\nhttps://nextjs.org/docs/messages/module-not-found\\n\\n    at getNotFoundError (/tmp/next-install-6d82d07bad28a64185dfd0310a3ac158e4526904ce303cf5340a7bbd9878cc46/node_modules/.pnpm/file+..+next-repo-76ba130fec4f5ec8aa99e9a46207f61c741375117eec1b80506e47ac0116d359+packages+n_i4dgj43thkohpea2sbo6wfe6g4/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:120:16)\\n    at async getModuleBuildError (/tmp/next-install-6d82d07bad28a64185dfd0310a3ac158e4526904ce303cf5340a7bbd9878cc46/node_modules/.pnpm/file+..+next-repo-76ba130fec4f5ec8aa99e9a46207f61c741375117eec1b80506e47ac0116d359+packages+n_i4dgj43thkohpea2sbo6wfe6g4/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:102:27)\\n    at async /tmp/next-install-6d82d07bad28a64185dfd0310a3ac158e4526904ce303cf5340a7bbd9878cc46/node_modules/.pnpm/file+..+next-repo-76ba130fec4f5ec8aa99e9a46207f61c741375117eec1b80506e47ac0116d359+packages+n_i4dgj43thkohpea2sbo6wfe6g4/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:29:49\\n    at async Promise.all (index 0)\\n    at async /tmp/next-install-6d82d07bad28a64185dfd0310a3ac158e4526904ce303cf5340a7bbd9878cc46/node_modules/.pnpm/file+..+next-repo-76ba130fec4f5ec8aa99e9a46207f61c741375117eec1b80506e47ac0116d359+packages+n_i4dgj43thkohpea2sbo6wfe6g4/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:27:21\"},\"gip\":true,\"scriptLoader\":[]}</script><div id=\"__next-build-watcher\" style=\"position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;\"></div><next-route-announcer><p aria-live=\"assertive\" id=\"__next-route-announcer__\" role=\"alert\" style=\"border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; top: 0px; width: 1px; white-space: nowrap; overflow-wrap: normal;\"></p></next-route-announcer><nextjs-portal></nextjs-portal></body>"

      182 |     expect(
      183 |       await session.evaluate(() => document.documentElement.innerHTML)
    > 184 |     ).toContain('index page')
          |       ^
      185 |
      186 |     await cleanup()
      187 |   })

      at Object.toContain (development/acceptance/ReactRefreshLogBox-builtins.test.ts:184:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by luismulinari** [comment]
@feedthejim, it looks like `ReactRefreshLogBox default > Module not found (missing global CSS)` is a flaky test.

I can see it failing in other PRs, example: https://github.com/vercel/next.js/pull/58132

**Comment by luismulinari** [comment]
Hey @feedthejim ! I apologize for bothering you again.

Is there anything else I need to do for the PR?

**Pull request merged**
