### PR TITLE
fix: allow "null" to Link prefetch type

### PR DESCRIPTION
**Pull request by OlegLustenko**
In the same way as it default value here
https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx#L279

Thoughts about this change?

### What?
Adding null to prefetch type for Link component

### Why?
We have some components that set `prefetch=true` by default,
However, in some specific cases, we want to enable "soft-prefetch".

To enable soft prefetch, we want to pass "null"

### How?

By adding null to Link prefetch

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 47dc73784bd84a4b14d01804c8fdc745d809cddf

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — CHANGES_REQUESTED** [review]
Thank you. Could you also add a test or highlight an existing one for `<Link prefetch={null} />`?

I suspect it behaves just like `<Link prefetch={false} />` so I'm wondering why you can't do that in your codebase? Adding type overloads for convenience usually makes code both in app code and in the implementation harder for a minor convenience in rare cases.

**Comment by OlegLustenko** [comment]
Thanks for review @eps1lon !

Yeah, I'll add a tests, there is a difference about `false` vs `null`

https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx#L316
It described here
```tsx
    /**
     * The possible states for prefetch are:
     * - null: this is the default "auto" mode, where we will prefetch partially if the link is in the viewport
     * - true: we will prefetch if the link is visible and prefetch the full page, not just partially
     * - false: we will not prefetch if in the viewport at all
     */
    const appPrefetchKind =
      prefetchProp === null ? PrefetchKind.AUTO : PrefetchKind.FULL
```

**Comment by eps1lon** [comment]
This is an implementation detail though. Why can't you use `undefined` instead?

**Comment by OlegLustenko** [comment]
It was fixed in the PR https://github.com/vercel/next.js/pull/67868

with this commit https://github.com/vercel/next.js/commit/025db7df9ae8928fc3b9ce8601f29b7db4e8be84#diff-96efb3e8013ebe2b3d6baefc46f9683fb1f7011d52d81b01be6a45cee47224d6R86

So, I'm closing this PR

Thanks for review!

**Pull request closed without merging**
