### PR TITLE
Dynamic imports failing in Jest tests

### PR DESCRIPTION
**Pull request by umarsenpai**
Jest tests in nextJs are failing with the following error on dynamic imports

`TypeError: require.resolveWeak is not a function`. 

I have been migrating my code to nextJs and it has become a blocker. This issue has been reported and fixed multiple times: 

First fixed here: https://github.com/vercel/next.js/pull/3414
Then again fixed in: https://github.com/vercel/next.js/pull/4208

There is an ongoing discussion here: https://github.com/vercel/next.js/issues/5416 which was closed as apparently this should have been fixed. I have added `typeof require.resolveWeak === 'function'` condition. Tested with my own repo and an example repo here: https://github.com/ellsclytn/next-with-jest and the issue was fixed with this.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.6s | ⚠️ +291ms |
| nodeModulesSize | 67.1 MB | 67.1 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.225 | 2.213 | -0.01 |
| / avg req/sec | 1123.71 | 1129.87 | ⚠️ +6.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.41 | 1.398 | -0.01 |
| /error-in-render avg req/sec | 1773.32 | 1788.85 | ⚠️ +15.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..bcce.js gzip | 10.6 kB | 10.6 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.57 kB | 5.57 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.99 kB | 6.99 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 539 B | 539 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 957 B | 957 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.85 kB | 2.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.7s | ⚠️ +117ms |
| nodeModulesSize | 67.1 MB | 67.1 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..bcce.js gzip | 10.6 kB | 10.6 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.57 kB | 5.57 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.99 kB | 6.99 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 539 B | 539 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ⚠️ +29 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ⚠️ +29 B |
| link.js | 915 kB | 915 kB | ⚠️ +29 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +29 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +29 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +145 B |

</details>

</details>
Commit: 3ac8b4934568587ad5cf938356020a55081cb0c6

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +132ms |
| nodeModulesSize | 67.1 MB | 67.1 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.305 | 2.226 | -0.08 |
| / avg req/sec | 1084.83 | 1123.06 | ⚠️ +38.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.47 | 1.505 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1700.55 | 1660.78 | -39.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..bcce.js gzip | 10.6 kB | 10.6 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.57 kB | 5.57 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.99 kB | 6.99 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 539 B | 539 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 957 B | 957 B | ✓ |
| withRouter.html gzip | 945 B | 945 B | ✓ |
| Overall change | 2.85 kB | 2.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.1s | -87ms |
| nodeModulesSize | 67.1 MB | 67.1 MB | ⚠️ +162 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..bcce.js gzip | 10.6 kB | 10.6 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.57 kB | 5.57 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 6.99 kB | 6.99 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 267 B | 267 B | ✓ |
| _buildManife..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 539 B | 539 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | umarsenpai/next.js resolve-weak-jest-fix | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ⚠️ +29 B |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ⚠️ +29 B |
| link.js | 915 kB | 915 kB | ⚠️ +29 B |
| routerDirect.js | 907 kB | 907 kB | ⚠️ +29 B |
| withRouter.js | 907 kB | 907 kB | ⚠️ +29 B |
| Overall change | 4.49 MB | 4.49 MB | ⚠️ +145 B |

</details>

</details>
Commit: ba83eeb27d5c6aa1fbb44c0ae8019a74902153cc

**Review by timneutkens — CHANGES_REQUESTED** [review]
Please add a test for this behavior 🙏

**Comment by timneutkens** [comment]
Happy to re-open when tests are added 🙏

**Pull request closed without merging**
