### PR TITLE
Don't test image domains in test env

### LINKED ISSUE #21549: Hostname is not configured under images in your `next.config.js` when running tests with Jest
**What version of Next.js are you using?**

10.0.2

**What version of Node.js are you using?**

14.2.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu

**How are you deploying your application?**

next start

**Describe the Bug**

When using Jest to test a component that uses `Image` from `next/image` you will get an error that your src prop hostname is not configured under images in your `next.config.js` even if you have mocked the config to include the domain.

**Expected Behavior**

Jest mocking should work.

**To Reproduce**

Testing this component:

```typescript
import React from "react";
import Image from "next/image";

export const Github: React.FC = () => {
  return (
    <div>
      <Image
        width={800}
        height={600}
        sizes="600px"
        layout="responsive"
        objectFit="cover"
        src={`${process.env.NEXT_PUBLIC_CDN_URL}/hello.jpg`}
      />
      Hello World
    </div>
  );
};
```

with this test:

```typescript
import React from "react";
import { screen, render, waitFor } from "@testing-library/react";
import { Github } from "../../../../components/github";

jest.mock("next/config", () => {
  return () => ({
    publicRuntimeConfig: {
      images: {
        domains: ["cdn.example.com"],
      },
    },
  });
});

describe("github issue reproduction", () => {
  jest.useFakeTimers("modern");
  jest.setSystemTime(new Date(2021, 1, 20, 12, 0, 0, 0));

  it("github issue", async () => {
    render(<Github />);

    await waitFor(() =>
      expect(screen.getByText("Hello World")).toBeInTheDocument()
    );
  });
});
```

with this `jest.config.js`:

```javascript
module.exports = {
  moduleNameMapper: {
    "\\.(css|less)$": "identity-obj-proxy",
  },
  setupFiles: ["<rootDir>/__tests__/setupEnvironment.js"],
};
```

with this `setupEnvironment.js`:

```javascript
process.env.NEXT_PUBLIC_CDN_URL = "https://cdn.example.com";
```

will get you this error:

```
    Invalid src prop (https://cdn.example.com/hello.jpg) on `next/image`, hostname "cdn.example.com" is not configured under images in your `next.config.js`
    See more info: https://err.sh/next.js/next-image-unconfigured-host

      20 |     render(<Github />);
      21 | 
    > 22 |     await waitFor(() =>
         |           ^
      23 |       expect(screen.getByText("Hello World")).toBeInTheDocument()
      24 |     );
      25 |   });
```

### PR DESCRIPTION
**Pull request by atcastle**
This fixes #21549, which was happening because the domains environment property is not populated when the app is being run in the "test" env. The loader still errors as expected when the app is run in dev mode.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.1s | -178ms |
| buildDurationCached | 3.4s | 3.4s | -85ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +138 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.614 | 2.559 | -0.05 |
| / avg req/sec | 956.48 | 976.83 | +20.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.609 | 1.652 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1553.51 | 1513.66 | ⚠️ -39.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 532 B | 532 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| buildDuration | 16s | 16s | ⚠️ +36ms |
| buildDurationCached | 4.6s | 4.6s | -58ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +138 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ⚠️ +2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ⚠️ +2 B |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ⚠️ +4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | -14ms |
| buildDurationCached | 5s | 5s | -9ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +138 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.634 | 2.63 | 0 |
| / avg req/sec | 949.08 | 950.51 | +1.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.568 | 1.561 | -0.01 |
| /error-in-render avg req/sec | 1594.22 | 1601.51 | +7.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.28 kB | 9.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 420 B | 420 B | ✓ |
| Overall change | 420 B | 420 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | atcastle/next.js fix-21549 | Change |
| - | - | - | - |
| index.html gzip | 568 B | 568 B | ✓ |
| link.html gzip | 581 B | 581 B | ✓ |
| withRouter.html gzip | 560 B | 560 B | ✓ |
| Overall change | 1.71 kB | 1.71 kB | ✓ |

</details>

</details>
Commit: 3f8f440f8d05e92bdcbe18bd432a83ffb1392f74

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3f8f440f8d05e92bdcbe18bd432a83ffb1392f74

**test/integration/relay-analytics/test/index.test.js** 
- Analytics relayer > Relays the data to user code

<details>
<summary>Expand output</summary>

  ● Analytics relayer › Relays the data to user code

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      66 |     beacons.sort((a, b) => a.event_name.localeCompare(b.event_name))
      67 |
    > 68 |     expect(beacons.length).toBe(2)
         |                            ^
      69 |     expect(beacons[0]).toMatchObject({
      70 |       dsn: 'test',
      71 |       event_name: 'FCP',

      at Object.<anonymous> (integration/relay-analytics/test/index.test.js:68:28)

</details>

**Review by styfle — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by chenrui333** [comment]
👋  this PR does solve our 10.2.0 and 10.1.x upgrade issue, is there way that I can get this PR ported to 10.2.0 or I should wait for another 11.x.x release? Thanks a lot!

**Comment by styfle** [comment]
@chenrui333 You can use `yarn add next@canary` to try it out today 👍

**Pull request merged**
