### PR TITLE
Pass router in getInitialProps context

### LINKED ISSUE #1653: Singleton router can't be shared in other modules
Right now, it's not really possible to share the router with plugins since the `router` value will be null.

I'm running into this here: https://github.com/matthewmueller/next-redirect

Trying to use `next/router` instead of `document.location.pathname`: https://github.com/matthewmueller/next-redirect/blob/master/index.js#L16

This would hopefully make #1552 a bit nicer to work with.

### PR DESCRIPTION
**Pull request by ijjk**
This allows passing it to other modules in `getInitialProps` since it couldn't be shared before

Closes: #1653

### CODE REVIEW

**Comment by lfades** [comment]
Can you add it to docs too ?

**Comment by ijjk** [comment]
Yup, added

**Comment by dmytro-lymarenko** [comment]
Can this fix https://github.com/zeit/next.js/issues/6042 ?

**Review by lfades — APPROVED** [review]

**Comment by timneutkens** [comment]
I'm still not sure if this is really needed, we should think about it more.

**Comment by timneutkens** [comment]
Going to close this as there's not really a super good use case for it right now. I'd love to hear if there is one from users though. So feel free to reply if you do.

**Pull request closed without merging**
