### PR TITLE
docs(material-ui): move the source code to Material-UI repository

### PR DESCRIPTION
**Pull request by oliviertassinari**

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
👌💯

**Comment by oliviertassinari** [comment]
@timneutkens Thanks

**Comment by albinekb** [comment]
Why 🤔  this is very weird to me.

**Comment by oliviertassinari** [comment]
@albinekb We are still in beta, things are moving. It's simpler for us to keep it up to date this way.

**Comment by ebrearley** [comment]
Wouldn't adding a brief description and a link to the [new home for this code](https://github.com/callemall/material-ui/tree/v1-beta/examples/nextjs) in the example's readme be important since this is essentially leaving the nextjs example completely gutted - with no reason as to why?

**Comment by timneutkens** [comment]
@ebrearley I don't follow, it's documented here https://github.com/zeit/next.js/tree/master/examples/with-material-ui-next added in this PR

**Comment by ebrearley** [comment]
@timneutkens  No, not really. The example readme mentions that the material-ui library is undergoing a rewrite from scratch with the `curl` pointed to the example in callemall's material-ui repository. There is no code in that directory, nor is there any link to where the code can now be found. There is also no mention as to why the example had been moved, I only found that out in this PR, found by exploring the last commit to that readme.

As somebody who looks through the example's code (which I think is the beauty of the examples) in GitHub, I found this example rather odd because there is now no actual example code. Cloning the example into a new directory on my machine is a lot of overhead if I just want to see how the example looks.

I just think that readme should contain a link to where the code now lives, with a short sentence saying something like:
> "this example can be found in [callemall's material-ui repository](https://github.com/callemall/material-ui/tree/v1-beta/examples/nextjs) to ensure the most up to date code as it's currently undergoing a complete rewrite.

**Comment by oliviertassinari** [comment]
@timneutkens Looks all good on my end.

**Comment by timneutkens** [comment]
Last sentence is: > ⚠️ The source code is hosted on the Material-UI repository.
🤔

**Pull request merged**
