### PR TITLE
Add a sw-precache example

### PR DESCRIPTION
**Pull request by cdwmyk**
Here's an example of how I've been generating Service Worker files using `sw-precache`, figured it'd be useful to share with others.

Any suggestions on alternatives to achieve this are more than welcome.

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Wow amazing Chris!

**Comment by arunoda** [comment]
@timneutkens please don't take PR with failing tests.

**Comment by chrisdwheatley** [comment]
Oops, what did I break? I can take a look & fix shortly if required.

**Comment by arunoda** [comment]
Ah. No issues. 
I just fixed it.

**Pull request merged**
