### PR TITLE
fix(examples/cms-contentful): add correct Content-Type + missing closing tag for html

### PR DESCRIPTION
**Pull request by gfortaine**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by gfortaine** [comment]
cc @leerob @ijjk

**Comment by leerob** [comment]
Could you share more about this issue?

**Comment by gfortaine** [comment]
This PR tries to fix 2 issues with the current implementation:

• missing content-type for response

• missing html closing tag

Indeed, we have encountered these bugs by copy-pasting the example

**Review by ijjk — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
