### PR TITLE
test: fix next-sass test

### PR DESCRIPTION
**Pull request by samcx**
## Why?

This [PR](https://github.com/vercel/next.js/pull/73548) updated the directory of an example (it's now `examples/with-sass`), and it broke a test.

### CODE REVIEW

**Comment by samcx** [comment]
* **#73633** <a href="https://app.graphite.dev/github/pr/vercel/next.js/73633?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/vercel/next.js/73633?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by gaojude — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 122ab38666db3d972db22c40ecf4e25327f08649

`pnpm test-dev test/e2e/yarn-pnp/test/with-sass.test.ts`
- yarn PnP > should compile and serve the index page correctly with-sass

<details>
<summary>Expand output</summary>

  ● yarn PnP › should compile and serve the index page correctly with-sass

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      69 |     it(`should compile and serve the index page correctly ${example}`, async () => {
      70 |       const res = await fetchViaHTTP(next.url, testPath)
    > 71 |       expect(res.status).toBe(200)
         |                          ^
      72 |
      73 |       const text = await res.text()
      74 |

      at Object.toBe (e2e/yarn-pnp/test/utils.ts:71:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| buildDuration | 26.3s | 24.8s | N/A |
| buildDurationCached | 23.2s | 20.9s | N/A |
| nodeModulesSize | 409 MB | 409 MB | ✓ |
| nextStartRea..uration (ms) | 592ms | 584ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 50.2 kB | 50.2 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.3 kB | 5.3 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 232 B | 235 B | N/A |
| main-HASH.js gzip | 33.8 kB | 33.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 513 B | 511 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.44 kB | 4.43 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| index.html gzip | 523 B | 522 B | N/A |
| link.html gzip | 536 B | 537 B | N/A |
| withRouter.html gzip | 518 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 203 kB | 203 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 666 B | 666 B | ✓ |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31 kB | 31 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 1.51 kB | 1.51 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| 797-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 797.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 322 kB | 322 kB | ✓ |
| app-page-exp..prod.js gzip | 127 kB | 127 kB | ✓ |
| app-page-tur..prod.js gzip | 140 kB | 140 kB | ✓ |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run...dev.js gzip | 312 kB | 312 kB | ✓ |
| app-page.run..prod.js gzip | 122 kB | 122 kB | ✓ |
| app-route-ex...dev.js gzip | 37.1 kB | 37.1 kB | ✓ |
| app-route-ex..prod.js gzip | 25.1 kB | 25.1 kB | ✓ |
| app-route-tu..prod.js gzip | 25.1 kB | 25.1 kB | ✓ |
| app-route-tu..prod.js gzip | 24.9 kB | 24.9 kB | ✓ |
| app-route.ru...dev.js gzip | 38.7 kB | 38.7 kB | ✓ |
| app-route.ru..prod.js gzip | 24.9 kB | 24.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.56 kB | 9.56 kB | ✓ |
| pages-turbo...prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| pages.runtim...dev.js gzip | 27 kB | 27 kB | ✓ |
| pages.runtim..prod.js gzip | 21.3 kB | 21.3 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.35 MB | 2.35 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sam/examples/with-sass | Change |
| - | - | - | - |
| 0.pack gzip | 2.04 MB | 2.04 MB | N/A |
| index.pack gzip | 146 kB | 146 kB | ⚠️ +512 B |
| Overall change | 146 kB | 146 kB | ⚠️ +512 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 122ab38666db3d972db22c40ecf4e25327f08649

**Comment by samcx** [comment]
### Merge activity

* **Dec 6, 7:41 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/73633).

**Pull request merged**
