### PR TITLE
Add note about beforeFiles continuing

### LINKED ISSUE #26795: Rewrites in beforeFiles result in 404 errors when a afterFiles also contains a matching rewrite.
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows, MacOS

### How are you deploying your application?

next start

### Describe the Bug

If `beforeFiles` and `afterFiles` are both supplied, and a route could match both, rewrites will result in 404 pages instead of rewriting to the correct page.
Removing the `afterFiles` rewrite causes the `beforeFiles` rewrites to work again (at the expense of losing that functionality).

This occurs in latest, and started with `10.2.3-canary.1`.

### Expected Behavior

`beforeFiles` rewrites continue to work as expected when they match, and are not affected by `afterFiles`.

### To Reproduce

https://github.com/threehams/static-site-feature-flags/tree/before-files-after

### PR DESCRIPTION
**Pull request by ijjk**
This adds a note explaining that `beforeFiles` continue instead of checking the filesystem/dynamic routes immediately like they do in `afterFiles` and `fallback`. 

## Documentation / Examples

- [x] Make sure the linting passes

Closes: https://github.com/vercel/next.js/issues/26795

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by threehams** [comment]
https://github.com/vercel/next.js/issues/26795 is about rewrites looping through all `beforeFiles`, then continuing on to match `afterFiles` despite already hitting a match. Is this intended? It complicates the approach used in https://github.com/vercel/next.js/discussions/12848 to support white-label sites (requires additional rewrites for ambiguous routes), and doesn't seem to match the documentation added in this PR.

**Comment by ijjk** [comment]
@threehams looking at the reproduction provided in the mentioned issue the `beforeFiles` rewrite will not match before the `afterFiles` rewrites due to the destination in `beforeFiles` pointing to a dynamic route and dynamic routes aren't checked right after `beforeFiles`. 

I added this note to mention the continuing behavior of `beforeFiles`, if there's anything we could add to make this more clear let me know. Potentially we could give more examples of when things are matched/checked 🤔

**Comment by threehams** [comment]
Let me see if I can get you a better reproduction. Should I comment on the same issue or open a new one?

**Comment by ijjk** [comment]
The existing reproduction explains the issue correctly, it's not a bug and is meant to match that way for a dynamic route. If you were to set [this line](https://github.com/threehams/static-site-feature-flags/blob/d4846fc8679a6c7fa85541cf4179d2114e33cf20/next.config.js#L17) to `fallback` rewrites instead it would work as `fallback` rewrites are run after checking dynamic routes and all Next.js paths, `afterFiles` comes before dynamic routes are checked. 

If you were to change [this line](https://github.com/threehams/static-site-feature-flags/blob/d4846fc8679a6c7fa85541cf4179d2114e33cf20/next.config.js#L7) to point to a non-dynamic page instead it would also work since non-dynamic pages are checked before `afterFiles` rewrites. 

Let me see if I can tweak this doc to explain this order a bit more

**Comment by ijjk** [comment]
@threehams I opened an additional PR [here](https://github.com/vercel/next.js/pull/27247) adding some additional context, let me know if this helps clear it up some more or if it could use some more information to help make this more clear

**Pull request merged**
