### PR TITLE
Add with-ie11 example

### LINKED ISSUE #975: Create example for using Next.js with IE11
Hi everyone,

I am currently evaluating next.js for one of my client projects. While playing around with the Redux sample under https://github.com/zeit/next.js/tree/master/examples/with-redux I noticed that it throws the following error under IE11:

```
ReferenceError: 'Promise' is undefined
   at updateOnClient (http://172.16.102.1:3000/_next/-/commons.js:8875:3)
   at mount (http://172.16.102.1:3000/_next/-/commons.js:8853:3)
   at componentWillMount (http://172.16.102.1:3000/_next/-/commons.js:8794:7)
   at Anonymous function (http://172.16.102.1:3000/_next/-/main.js:16691:11)
   at measureLifeCyclePerf (http://172.16.102.1:3000/_next/-/main.js:16418:5)
   at ReactCompositeComponent.performInitialMount (http://172.16.102.1:3000/_next/-/main.js:16690:9)
   at ReactCompositeComponent.mountComponent (http://172.16.102.1:3000/_next/-/main.js:16601:7)
   at ReactReconciler.mountComponent (http://172.16.102.1:3000/_next/-/main.js:1496:5)
   at ReactMultiChild.Mixin.mountChildren (http://172.16.102.1:3000/_next/-/main.js:21084:11)
   at ReactDOMComponent.Mixin._createContentMarkup (http://172.16.102.1:3000/_next/-/main.js:18021:9)
```

The other examples that I've tried don't seem to throw this error and they also make use of Promise inside of commons.js. Does anyone have any pointers on how to resolve this?

Regards,
Sven

### PR DESCRIPTION
**Pull request by timneutkens**
Shows how to add IE11 support.

Fixes #975

@developit, @rauchg mentioned you know a 1kb Promise polyfill. Could you point out which one has your preference? :heart:

### CODE REVIEW

**Comment by developit** [comment]
@timneutkens This is the one: https://github.com/taylorhakes/promise-polyfill

**Comment by arunoda** [comment]
@timneutkens We don't need to add a specific polyfill. 
For our code, it's added by babel.
We need to find the root and fix it.

So, no one need to use the polyfill.

**Comment by arunoda** [comment]
Closing in favor of: https://github.com/zeit/next.js/pull/1344

**Comment by timneutkens** [comment]
Okay, that would allow it to be removed on zeit.co too 👍

**Pull request closed without merging**
