### PR TITLE
with-dotenv example

### PR DESCRIPTION
**Pull request by pencilcheck**
I hope this helps people when dealing with deployment and multiple envs

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
This is cool! Thanks!

**Comment by JeromeFitz** [comment]
@pencilcheck I forked your example as I wasn't able to get the `.env.production` file to work in the build.

At first, I wanted to add a check for `process.env.NOW_URL` if you need the URL you are running off of (and cheating a bit by setting that variable in `.env.*` if you are not hosting with now).

Then since I couldn't get this to work locally, I reworked it a bit to utilize one `.env` and use cases if you are using `now` or `heroku`.

`dotenv` looks to the server first, then an existing `.env` file. In keeping the `.env` file as a singular entity, we can rework how `nextjs` passes variables by slightly altering the babel-plugins selected in a `config.js` file using `transform-define`.

This may go away from your original intent.

I did try to only add `NOW_URL` initially to enhance the example. Feel free to leave this as a one-off fork in a one-off branch if this complicates things from your perspective.

Or if you'd prefer to see first how we get `.env.production` working alone (without adding three paragraphs in the README).

Thanks for this, as a lot of users will be looking to using their environment variables!

**Comment by pencilcheck** [comment]
Yup. Go ahead and make changes that make sense to you. I'm glad this pull request is helping people.

Hm, i'm not sure why it doesn't work locally for you though, perhaps dotenv is not running locally from the bable plugin properly? Perhaps your custom .babelrc file is having conflict?

The example is meant that so nextjs can grab and babel from different sources in different envs. So .env.production is actually not used at all, in my assumption you will be using something like `heroku config:push -f .env.production` if you are on heroku, where envs are already present on the production instances when you push. Therefore no .env* files will present on any version control systems nor production system. I do understand that nextjs now uploads all files (even if they are outside git for example), but this is assuming you are not using .env* at all in production systems.

**Comment by JeromeFitz** [comment]
Thanks for clarifying about `.env.production`.

I will be offline until mid-next week and I'll hop back on then and will see about revamping what I did to match what you shared along with [env-and-secrets](https://zeit.co/docs/features/env-and-secrets)

Thanks @pencilcheck

**Comment by tronghiep92** [comment]
@pencilcheck 
In environment development, After the first time, it works.
But I'm changed value in file `.env` but it cannot update new value :(

**Comment by pencilcheck** [comment]
Sometimes you need to clear out the cache in
node_modules/babel-loader/.cache for your app to update.

I usually use a npm package called rimraf and put it in package.json before
you start dev server.

I hope this helps.

**Comment by tronghiep92** [comment]
@pencilcheck thank you very much.
Clear out cache in `node_modules/.cache`

**Pull request merged**
