### PR TITLE
Simplify export statement

### PR DESCRIPTION
**Pull request by rojvv**

### CODE REVIEW

**Review by styfle — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d2ada241739b07185abbf6c5f6f8500e17f7261c

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover from errors in the render function
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after a bad return from the render function
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:425:9)

  ● basic HMR › Error Recovery › should recover from errors in the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:455:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after exporting an invalid page 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about5"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      488 |
      489 |         expect(await hasRedbox(browser)).toBe(true)
    > 490 |         expect(await getRedboxHeader(browser)).toMatchInlineSnapshot(`
          |                                                ^
      491 |           " 1 of 1 unhandled error
      492 |           Server Error
      493 |

      at Object.<anonymous> (development/basic/hmr.test.ts:490:48)

  ● basic HMR › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:558:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      600 |         await next.patchFile(aboutPage, aboutContent)
      601 |
    > 602 |         if (browser) {
          |                       ^
      603 |           await check(
      604 |             () => getBrowserBodyText(browser),
      605 |             /This is the about page/

      at Object.<anonymous> (development/basic/hmr.test.ts:602:23)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 51068d3d7c07261083a8f0ae96bc0703c39697f1

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:425:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:614:8)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 16.4s | 16.5s | ⚠️ +38ms |
| buildDurationCached | 3.8s | 3.8s | ⚠️ +48ms |
| nodeModulesSize | 195 MB | 195 MB | -59 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.918 | 3.879 | -0.04 |
| / avg req/sec | 638.07 | 644.52 | +6.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.003 | 1.997 | -0.01 |
| /error-in-render avg req/sec | 1248.15 | 1251.79 | +3.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 3.02 kB | ✓ |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 25 kB | ✓ |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| amp-HASH.js gzip | 553 B | 553 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.73 kB | 2.73 kB | ✓ |
| head-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.89 kB | ✓ |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 8.1s | 8s | -24ms |
| buildDurationCached | 3.8s | 3.8s | -56ms |
| nodeModulesSize | 195 MB | 195 MB | -59 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.897 | 3.835 | -0.06 |
| / avg req/sec | 641.55 | 651.87 | +10.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.967 | 1.919 | -0.05 |
| /error-in-render avg req/sec | 1270.69 | 1303.08 | +32.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.9 kB | 13.9 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-HASH.js gzip | 35.2 kB | 35.2 kB | ✓ |
| webpack-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| Overall change | 102 kB | 102 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-HASH.js gzip | 355 B | 355 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 555 B | 555 B | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 532 B | 532 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: 51068d3d7c07261083a8f0ae96bc0703c39697f1

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.1s | ⚠️ +22ms |
| buildDurationCached | 3.4s | 3.4s | -32ms |
| nodeModulesSize | 195 MB | 195 MB | -51 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.418 | 3.546 | ⚠️ +0.13 |
| / avg req/sec | 731.46 | 704.96 | ⚠️ -26.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.758 | 1.681 | -0.08 |
| /error-in-render avg req/sec | 1422.13 | 1486.94 | +64.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | 2.96 kB | ✓ |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-45201df..96b4.js gzip | 26.1 kB | 26.1 kB | ✓ |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.47 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | 979 B | ✓ |
| _error-d828d..2954.js gzip | 3.06 kB | 3.06 kB | ✓ |
| amp-5388d1f5..4ce9.js gzip | 551 B | 551 B | ✓ |
| css-10424225..367a.js gzip | 329 B | 329 B | ✓ |
| dynamic-9821..3cd4.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-1df323b..d261.js gzip | 2.32 kB | 2.32 kB | ✓ |
| hooks-ab0016..b093.js gzip | 917 B | 917 B | ✓ |
| image-c3cc30..4e2a.js gzip | 5.87 kB | 5.87 kB | ✓ |
| index-95c8cb..6970.js gzip | 260 B | 260 B | ✓ |
| link-05c99e7..35ec.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..6659.js gzip | 319 B | 319 B | ✓ |
| script-d94ba..ed05.js gzip | 386 B | 386 B | ✓ |
| withRouter-7..8b2e.js gzip | 317 B | 317 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.8 kB | 19.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 537 B | 537 B | ✓ |
| link.html gzip | 549 B | 549 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 7.3s | 7.3s | -8ms |
| buildDurationCached | 3.5s | 3.4s | -123ms |
| nodeModulesSize | 195 MB | 195 MB | -51 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.451 | 3.577 | ⚠️ +0.13 |
| / avg req/sec | 724.47 | 698.9 | ⚠️ -25.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.579 | 1.66 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1583.71 | 1506.38 | ⚠️ -77.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| 450.fd3ad245..022b.js gzip | 179 B | 179 B | ✓ |
| 675-f623fa2a..036a.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework-13..70b0.js gzip | 50.8 kB | 50.8 kB | ✓ |
| main-1e4b9db..ad07.js gzip | 36.5 kB | 36.5 kB | ✓ |
| webpack-a7f2..2650.js gzip | 1.63 kB | 1.63 kB | ✓ |
| Overall change | 103 kB | 103 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _app-ae91bc3..d985.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error-273ac..9ef0.js gzip | 180 B | 180 B | ✓ |
| amp-5f9a7694..99ce.js gzip | 315 B | 315 B | ✓ |
| css-3a1b2477..df1e.js gzip | 330 B | 330 B | ✓ |
| dynamic-8d0e..e365.js gzip | 2.79 kB | 2.79 kB | ✓ |
| head-7f600d0..daa3.js gzip | 356 B | 356 B | ✓ |
| hooks-bd8c02..0730.js gzip | 638 B | 638 B | ✓ |
| image-16df09..4584.js gzip | 555 B | 555 B | ✓ |
| index-80be94..e89f.js gzip | 262 B | 262 B | ✓ |
| link-4ee1ea7..8745.js gzip | 2.22 kB | 2.22 kB | ✓ |
| routerDirect..c4aa.js gzip | 325 B | 325 B | ✓ |
| script-67da0..49e6.js gzip | 390 B | 390 B | ✓ |
| withRouter-2..2409.js gzip | 322 B | 322 B | ✓ |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 476 B | 476 B | ✓ |
| Overall change | 476 B | 476 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | rojserbest/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 4782bedf97f046189c638def13479550b15fc3b8

**Pull request merged**
