### PR TITLE
docs: clarify opt-in of page vs. app

### PR DESCRIPTION
**Pull request by leerob**
This code snippet would not opt the entire application into dynamic rendering – you could still have other pages which are statically generated or that use ISR.

### CODE REVIEW

**Comment by jacobweber** [comment]
I think you're using "dynamic rendering" rather than "server-side rendering" elsewhere in the app router docs.

But it's not clear to me why this would force the page to be dynamic....it's not using one of the [dynamic functions](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-functions), and it's not calling fetch with no-cache....what other conditions would force dynamic rendering?

**Comment by leerob** [comment]
While I like dynamic rendering (which is accurate), I'm also trying to bridge the knowledge gap with where people are currently at (server-side rendering). Until PPR is stable, there isn't really a mixed static/dynamic world yet. When that arrives, dynamic rendering of a component makes more sense than SSR, because SSR implies the entire page.

Calling your database or any other Promise in the RSC render is a dynamic piece of code. We're working on some ways to better educate on this, but the general mental model should be that if you use any dynamic I/O in your application, that component (and currently page) will be dynamically rendered.

**Comment by jacobweber** [comment]
Hmm, but if I do something like this, and build the app, it's built as a static/prerendered page. Same with awaiting a file read/write. I'm using next 14.2.6:
```
import { sql } from '@vercel/postgres';

async function getFromDatabase() {
  const data = await sql<any>`SELECT * FROM posts`;
  return data.rows;
}

export default async function Page() {
  let allPosts = await getFromDatabase();
  return (
    <ul>
      {allPosts.map((post) => (
        <li key={post.id}>{post.title}</li>
      ))}
    </ul>
  )
}
```

**Comment by leerob** [comment]
Under the hood, that package uses `fetch`. A previous version did not modify the `fetch` config, so it could be prerendered during the build. Since then, it now includes `no-store` on the `fetch`, to ensure it's consistent with other dynamic I/O like things, such as using an ORM.

**Comment by jacobweber** [comment]
I see. So that example only applies to vercel DB packages or other libraries that use `fetch`. Maybe that could be mentioned here...that's what confused me. But if there's some larger intention to make this apply to all promises or I/O, that's definitely not documented yet.

**Review by ijjk — CHANGES_REQUESTED** [review]
Lets land https://github.com/vercel/next.js/pull/69695 instead as it seems to stress the behavior better

**Comment by leerob** [comment]
I was wrong 😄 Sorry for the confusion here. https://github.com/vercel/next.js/pull/69702

**Pull request closed without merging**
