### PR TITLE
Add/link replace

### LINKED ISSUE #1418: Support <Link replace />
Basically, this will call `Router.replaceState` instead of `Router.pushState` inside the `<Link>` component.

> Invented by @rauchg  :)

### PR DESCRIPTION
**Pull request by impronunciable**
Adds a `replace` prop to the `<Link>` component. Fixes #1418

### CODE REVIEW

**Comment by arunoda** [comment]
It's nice to have a test case here in `test/integration/basic`. Using the actual browser.

**Comment by impronunciable** [comment]
@arunoda good call, adding them

**Comment by impronunciable** [comment]
Added an integration test :)

**Review by timneutkens — APPROVED** [review]
👍 👍 👍

**Comment by arunoda** [comment]
@impronunciable This is awesome.

**Pull request merged**
