### PR TITLE
Add prefetch header for data prefetching

### LINKED ISSUE #17758: Enormous number of API requests using Incremental Static Generation with revalidation
# Bug report

## Describe the bug

On two websites, I have revalidation set ranging from 5 minutes to 1 hour. However, enabling any revalidation time leads to an astonishingly high number of requests to my API, with very low traffic.

## To Reproduce

A typical `getStaticProps` in my apps might look like this:

```
export async function getStaticProps(context) {
  const navigationResponse = await fetchAPI(fetchNavigation);
  const response = await fetchAPI(fetchHomepage);
  const eventsResponse = await fetchAPI(fetchEvents, {
    limit: 12,
    orderBy: 'startDateTime ASC',
  });

  return {
    props: {
      page: response.page,
      navigation: navigationResponse,
      events: eventsResponse.events,
    },
    revalidate: 300,
  };
}
```

`fetchAPI` is a common API function that looks like this: 

```
const fetchAPI = async (query, variables = {}, token = null) => {
  const url = token
    ? `${process.env.NEXT_PUBLIC_API_URL}?token=${token}`
    : `${process.env.NEXT_PUBLIC_API_URL}`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_GRAPHQL_TOKEN}`,
      },
      body: JSON.stringify({
        query,
        variables,
      }),
    });

    const json = await res.json();

    if (json.errors) {
      console.error(json.errors);
      throw new Error(json.errors);
    }

    return json.data;
  } catch (error) {
    console.error(error);
    throw new Error(error);
  }
};
```

With revalidation enabled, and with hardly 10 visitors per hour, I'm seeing the API be hit almost 20,000 times per hour (!).

With revaliation disabled, my API is hit 0 times per hour. 

## Expected behavior

I'd expect the number of times my API hit with revalidation set to 300 seconds, be close to zero.

## System information

- Version of Next.js: 9.5.4

### PR DESCRIPTION
**Pull request by ijjk**
This ensures we don't un-necessarily revalidate paths when they are being prefetched but not being navigated to as this can cause a lot of extra requests which currently requires disabling automatic prefetching to workaround. 

Fixes: https://github.com/vercel/next.js/issues/17758
x-ref: https://github.com/vercel/next.js/discussions/20521
x-ref: [slack thread](https://vercel.slack.com/archives/C031QM96T0A/p1645129445819139?thread_ts=1645124478.067049&cid=C031QM96T0A)

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.1s | ⚠️ +10ms |
| buildDurationCached | 6.1s | 5.9s | -207ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +619 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.989 | 2.98 | -0.01 |
| / avg req/sec | 836.41 | 838.86 | +2.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.173 | 1.161 | -0.01 |
| /error-in-render avg req/sec | 2131.16 | 2153.09 | +21.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +27 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.6 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 5.05 kB | 5.05 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 527 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4581,7 +4581,12 @@
           // > receiving cookies, always supply the `credentials: 'same-origin'`
           // > option instead of relying on the default.
           // https://github.com/github/fetch#caveats
-          credentials: "same-origin"
+          credentials: "same-origin",
+          headers: opts.isPrefetch
+            ? {
+                "x-nextjs-prefetch": "1"
+              }
+            : {}
         }).then(function(res) {
           if (!res.ok) {
             if (attempts > 1 && res.status >= 500) {
@@ -4607,7 +4612,8 @@
         isServerRender,
         text,
         inflightCache,
-        persistCache
+        persistCache,
+        isPrefetch
       ) {
         var ref = new URL(dataHref, window.location.href),
           cacheKey = ref.href;
@@ -4618,7 +4624,8 @@
           dataHref,
           isServerRender ? 3 : 1,
           {
-            text: text
+            text: text,
+            isPrefetch: isPrefetch
           }
         )
           .catch(function(err) {
@@ -5884,7 +5891,8 @@
                                     _this.isSsr,
                                     false,
                                     __N_SSG ? _this.sdc : _this.sdr,
-                                    !!__N_SSG && !isPreview
+                                    !!__N_SSG && !isPreview,
+                                    false
                                   )
                                 : _this.getInitialProps(Component, {
                                     pathname: pathname,
@@ -6174,6 +6182,7 @@
                                       false,
                                       false,
                                       _this.sdc,
+                                      true,
                                       true
                                     )
                                   : false;
@@ -6273,14 +6282,19 @@
             key: "_getFlightData",
             value: function _getFlightData(dataHref) {
               // Do not cache RSC flight response since it's not a static resource
-              return fetchNextData(dataHref, true, true, this.sdc, false).then(
-                function(serialized) {
-                  return {
-                    fresh: true,
-                    data: serialized
-                  };
-                }
-              );
+              return fetchNextData(
+                dataHref,
+                true,
+                true,
+                this.sdc,
+                false,
+                false
+              ).then(function(serialized) {
+                return {
+                  fresh: true,
+                  data: serialized
+                };
+              });
             }
           },
           {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| buildDuration | 18.6s | 18.2s | -332ms |
| buildDurationCached | 6.1s | 5.9s | -134ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +619 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.959 | 2.949 | -0.01 |
| / avg req/sec | 844.98 | 847.82 | +2.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.181 | 1.154 | -0.03 |
| /error-in-render avg req/sec | 2116.04 | 2166.35 | +50.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.1 kB | 42.1 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +27 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 5.08 kB | 5.08 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.28 kB | 2.28 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.7 kB | 14.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 526 B | -1 B |
| Overall change | 1.61 kB | 1.61 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4581,7 +4581,12 @@
           // > receiving cookies, always supply the `credentials: 'same-origin'`
           // > option instead of relying on the default.
           // https://github.com/github/fetch#caveats
-          credentials: "same-origin"
+          credentials: "same-origin",
+          headers: opts.isPrefetch
+            ? {
+                "x-nextjs-prefetch": "1"
+              }
+            : {}
         }).then(function(res) {
           if (!res.ok) {
             if (attempts > 1 && res.status >= 500) {
@@ -4607,7 +4612,8 @@
         isServerRender,
         text,
         inflightCache,
-        persistCache
+        persistCache,
+        isPrefetch
       ) {
         var ref = new URL(dataHref, window.location.href),
           cacheKey = ref.href;
@@ -4618,7 +4624,8 @@
           dataHref,
           isServerRender ? 3 : 1,
           {
-            text: text
+            text: text,
+            isPrefetch: isPrefetch
           }
         )
           .catch(function(err) {
@@ -5884,7 +5891,8 @@
                                     _this.isSsr,
                                     false,
                                     __N_SSG ? _this.sdc : _this.sdr,
-                                    !!__N_SSG && !isPreview
+                                    !!__N_SSG && !isPreview,
+                                    false
                                   )
                                 : _this.getInitialProps(Component, {
                                     pathname: pathname,
@@ -6174,6 +6182,7 @@
                                       false,
                                       false,
                                       _this.sdc,
+                                      true,
                                       true
                                     )
                                   : false;
@@ -6273,14 +6282,19 @@
             key: "_getFlightData",
             value: function _getFlightData(dataHref) {
               // Do not cache RSC flight response since it's not a static resource
-              return fetchNextData(dataHref, true, true, this.sdc, false).then(
-                function(serialized) {
-                  return {
-                    fresh: true,
-                    data: serialized
-                  };
-                }
-              );
+              return fetchNextData(
+                dataHref,
+                true,
+                true,
+                this.sdc,
+                false,
+                false
+              ).then(function(serialized) {
+                return {
+                  fresh: true,
+                  data: serialized
+                };
+              });
             }
           },
           {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-688a8db042e02e1b.js"
+      src="/_next/static/chunks/main-a3ab501ba2dde866.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: b2c85adcd64f5e7ac01601f229eca75829cdb61f

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16.2s | ⚠️ +116ms |
| buildDurationCached | 6.4s | 6.2s | -132ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.138 | 3.194 | ⚠️ +0.06 |
| / avg req/sec | 796.56 | 782.7 | ⚠️ -13.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.37 | 1.396 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1825.08 | 1791 | ⚠️ -34.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 27.9 kB | 27.9 kB | ⚠️ +31 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.5 kB | 71.6 kB | ⚠️ +31 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.06 kB | 5.06 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.8 kB | 14.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4632,7 +4632,12 @@
           // > receiving cookies, always supply the `credentials: 'same-origin'`
           // > option instead of relying on the default.
           // https://github.com/github/fetch#caveats
-          credentials: "same-origin"
+          credentials: "same-origin",
+          headers: opts.isPrefetch
+            ? {
+                "x-nextjs-prefetch": "1"
+              }
+            : {}
         }).then(function(res) {
           if (!res.ok) {
             if (attempts > 1 && res.status >= 500) {
@@ -4658,7 +4663,8 @@
         isServerRender,
         text,
         inflightCache,
-        persistCache
+        persistCache,
+        isPrefetch
       ) {
         var ref = new URL(dataHref, window.location.href),
           cacheKey = ref.href;
@@ -4669,7 +4675,8 @@
           dataHref,
           isServerRender ? 3 : 1,
           {
-            text: text
+            text: text,
+            isPrefetch: isPrefetch
           }
         )
           .catch(function(err) {
@@ -5933,7 +5940,8 @@
                                     _this.isSsr,
                                     false,
                                     __N_SSG ? _this.sdc : _this.sdr,
-                                    !!__N_SSG && !isPreview
+                                    !!__N_SSG && !isPreview,
+                                    false
                                   )
                                 : _this.getInitialProps(Component, {
                                     pathname: pathname,
@@ -6223,6 +6231,7 @@
                                       false,
                                       false,
                                       _this.sdc,
+                                      true,
                                       true
                                     )
                                   : false;
@@ -6322,14 +6331,19 @@
             key: "_getFlightData",
             value: function _getFlightData(dataHref) {
               // Do not cache RSC flight response since it's not a static resource
-              return fetchNextData(dataHref, true, true, this.sdc, false).then(
-                function(serialized) {
-                  return {
-                    fresh: true,
-                    data: serialized
-                  };
-                }
-              );
+              return fetchNextData(
+                dataHref,
+                true,
+                true,
+                this.sdc,
+                false,
+                false
+              ).then(function(serialized) {
+                return {
+                  fresh: true,
+                  data: serialized
+                };
+              });
             }
           },
           {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| buildDuration | 19.2s | 19.3s | ⚠️ +29ms |
| buildDurationCached | 6.3s | 6.3s | ⚠️ +8ms |
| nodeModulesSize | 372 MB | 372 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.19 | 3.175 | -0.02 |
| / avg req/sec | 783.81 | 787.51 | +3.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.405 | 1.428 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1779.18 | 1750.16 | ⚠️ -29.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.1 kB | 28.2 kB | ⚠️ +43 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.2 kB | 5.2 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.9 kB | 14.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/prefetch-header | Change |
| - | - | - | - |
| index.html gzip | 530 B | 531 B | ⚠️ +1 B |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4632,7 +4632,12 @@
           // > receiving cookies, always supply the `credentials: 'same-origin'`
           // > option instead of relying on the default.
           // https://github.com/github/fetch#caveats
-          credentials: "same-origin"
+          credentials: "same-origin",
+          headers: opts.isPrefetch
+            ? {
+                "x-nextjs-prefetch": "1"
+              }
+            : {}
         }).then(function(res) {
           if (!res.ok) {
             if (attempts > 1 && res.status >= 500) {
@@ -4658,7 +4663,8 @@
         isServerRender,
         text,
         inflightCache,
-        persistCache
+        persistCache,
+        isPrefetch
       ) {
         var ref = new URL(dataHref, window.location.href),
           cacheKey = ref.href;
@@ -4669,7 +4675,8 @@
           dataHref,
           isServerRender ? 3 : 1,
           {
-            text: text
+            text: text,
+            isPrefetch: isPrefetch
           }
         )
           .catch(function(err) {
@@ -5933,7 +5940,8 @@
                                     _this.isSsr,
                                     false,
                                     __N_SSG ? _this.sdc : _this.sdr,
-                                    !!__N_SSG && !isPreview
+                                    !!__N_SSG && !isPreview,
+                                    false
                                   )
                                 : _this.getInitialProps(Component, {
                                     pathname: pathname,
@@ -6223,6 +6231,7 @@
                                       false,
                                       false,
                                       _this.sdc,
+                                      true,
                                       true
                                     )
                                   : false;
@@ -6322,14 +6331,19 @@
             key: "_getFlightData",
             value: function _getFlightData(dataHref) {
               // Do not cache RSC flight response since it's not a static resource
-              return fetchNextData(dataHref, true, true, this.sdc, false).then(
-                function(serialized) {
-                  return {
-                    fresh: true,
-                    data: serialized
-                  };
-                }
-              );
+              return fetchNextData(
+                dataHref,
+                true,
+                true,
+                this.sdc,
+                false,
+                false
+              ).then(function(serialized) {
+                return {
+                  fresh: true,
+                  data: serialized
+                };
+              });
             }
           },
           {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-d899d849ecf228ef.js"
+      src="/_next/static/chunks/main-25873de3a23095c3.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 80109478ee4844754fbb2241ae7bb8529b89e61f

**Review by Timer — COMMENTED** [review]
I'm not sure this change should be made without a more formal RFC process first. I could see it argued both ways.

**Comment by ijjk** [comment]
Closing in favor of fresh PR

**Pull request closed without merging**
