### PR TITLE
fix: cookies() .set() reflect priority attribute into set-cookie

### LINKED ISSUE #56848: Cookies() does not reflect .set() priority attribute into `set-cookie`
### Link to the code that reproduces this issue

https://github.com/renchris/next.js/blob/fix-cookies-attributes/test/unit/web-runtime/next-response-cookies.test.ts

### To Reproduce

1. Build the `renchris/next.js` application with command `pnpm build`
2. Remove the fix changes from `packages/next/src/compiled/@edge-runtime/cookies/index.js`
3. Run the unit test `'reflect .set into set-cookie'` in the `next-response-cookies.test.ts` file
- cd into test directory with command `cd test/unit/web-runtime` 
- run the test from the test file with command ```pnpm testheadless "./next-response-cookies.test.ts -t \"reflect .set option attributes into `set-cookie` ```

Or copy and paste the unit test `'reflect .set into set-cookie'` from the `next-response-cookies.test.ts` file into the next.js project repository without the fix changes in vercel/next.js instead of in renchris/next.js

```
it('reflect .set all options attributes into `set-cookie`', async () => {
  const response = new NextResponse()
  const options = {
    domain: 'custom-domain',
    path: 'custom-path',
    secure: true,
    sameSite: 'strict' as 'strict' | 'lax' | 'none',
    expires: new Date(2100, 0, 1, 12, 0, 0),
    httpOnly: true,
    maxAge: 0,
    priority: 'high' as 'low' | 'medium' | 'high',
  }
  response.cookies.set('first-name', 'first-value', options)
  const cookiesInHeaders = Object.fromEntries(response.headers.entries())[
    'set-cookie'
  ]
  expect(cookiesInHeaders).toBe(
    'first-name=first-value; Path=custom-path; Expires=Fri, 01 Jan 2100 12:00:00 GMT; Max-Age=0; Domain=custom-domain; Secure; HttpOnly; SameSite=strict; Priority=high'
  )
})
```

### Current vs. Expected behavior

The type definition of the cookie option attributes is of type `ResponseCookie` being
```
type ResponseCookie = CookieListItem & Pick<CookieSerializeOptions, 'httpOnly' | 'maxAge' | 'priority'>;

interface CookieListItem extends Pick<CookieSerializeOptions, 'domain' | 'path' | 'secure' | 'sameSite'> {
    /** A string with the name of a cookie. */
    name: string;
    /** A string containing the value of the cookie. */
    value: string;
    /** A number of milliseconds or Date interface containing the expires of the cookie. */
    expires?: number | CookieSerializeOptions['expires'];
}

interface CookieSerializeOptions {
    /**
     * Specifies the value for the {@link https://tools.ietf.org/html/rfc6265#section-5.2.3|Domain Set-Cookie attribute}. By default, no
     * domain is set, and most clients will consider the cookie to apply to only
     * the current domain.
     */
    domain?: string | undefined;

    /**
     * Specifies a function that will be used to encode a cookie's value. Since
     * value of a cookie has a limited character set (and must be a simple
     * string), this function can be used to encode a value into a string suited
     * for a cookie's value.
     *
     * The default function is the global `encodeURIComponent`, which will
     * encode a JavaScript string into UTF-8 byte sequences and then URL-encode
     * any that fall outside of the cookie range.
     */
    encode?(value: string): string;

    /**
     * Specifies the `Date` object to be the value for the {@link https://tools.ietf.org/html/rfc6265#section-5.2.1|`Expires` `Set-Cookie` attribute}. By default,
     * no expiration is set, and most clients will consider this a "non-persistent cookie" and will delete
     * it on a condition like exiting a web browser application.
     *
     * *Note* the {@link https://tools.ietf.org/html/rfc6265#section-5.3|cookie storage model specification}
     * states that if both `expires` and `maxAge` are set, then `maxAge` takes precedence, but it is
     * possible not all clients by obey this, so if both are set, they should
     * point to the same date and time.
     */
    expires?: Date | undefined;
    /**
     * Specifies the boolean value for the {@link https://tools.ietf.org/html/rfc6265#section-5.2.6|`HttpOnly` `Set-Cookie` attribute}.
     * When truthy, the `HttpOnly` attribute is set, otherwise it is not. By
     * default, the `HttpOnly` attribute is not set.
     *
     * *Note* be careful when setting this to true, as compliant clients will
     * not allow client-side JavaScript to see the cookie in `document.cookie`.
     */
    httpOnly?: boolean | undefined;
    /**
     * Specifies the number (in seconds) to be the value for the `Max-Age`
     * `Set-Cookie` attribute. The given number will be converted to an integer
     * by rounding down. By default, no maximum age is set.
     *
     * *Note* the {@link https://tools.ietf.org/html/rfc6265#section-5.3|cookie storage model specification}
     * states that if both `expires` and `maxAge` are set, then `maxAge` takes precedence, but it is
     * possible not all clients by obey this, so if both are set, they should
     * point to the same date and time.
     */
    maxAge?: number | undefined;
    /**
     * Specifies the value for the {@link https://tools.ietf.org/html/rfc6265#section-5.2.4|`Path` `Set-Cookie` attribute}.
     * By default, the path is considered the "default path".
     */
    path?: string | undefined;
    /**
     * Specifies the `string` to be the value for the [`Priority` `Set-Cookie` attribute][rfc-west-cookie-priority-00-4.1].
     *
     * - `'low'` will set the `Priority` attribute to `Low`.
     * - `'medium'` will set the `Priority` attribute to `Medium`, the default priority when not set.
     * - `'high'` will set the `Priority` attribute to `High`.
     *
     * More information about the different priority levels can be found in
     * [the specification][rfc-west-cookie-priority-00-4.1].
     *
     * **note** This is an attribute that has not yet been fully standardized, and may change in the future.
     * This also means many clients may ignore this attribute until they understand it.
     */
    priority?: 'low' | 'medium' | 'high' | undefined;
    /**
     * Specifies the boolean or string to be the value for the {@link https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7|`SameSite` `Set-Cookie` attribute}.
     *
     * - `true` will set the `SameSite` attribute to `Strict` for strict same
     * site enforcement.
     * - `false` will not set the `SameSite` attribute.
     * - `'lax'` will set the `SameSite` attribute to Lax for lax same site
     * enforcement.
     * - `'strict'` will set the `SameSite` attribute to Strict for strict same
     * site enforcement.
     *  - `'none'` will set the SameSite attribute to None for an explicit
     *  cross-site cookie.
     *
     * More information about the different enforcement levels can be found in {@link https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7|the specification}.
     *
     * *note* This is an attribute that has not yet been fully standardized, and may change in the future. This also means many clients may ignore this attribute until they understand it.
     */
    sameSite?: true | false | 'lax' | 'strict' | 'none' | undefined;
    /**
     * Specifies the boolean value for the {@link https://tools.ietf.org/html/rfc6265#section-5.2.5|`Secure` `Set-Cookie` attribute}. When truthy, the
     * `Secure` attribute is set, otherwise it is not. By default, the `Secure` attribute is not set.
     *
     * *Note* be careful when setting this to `true`, as compliant clients will
     * not send the cookie back to the server in the future if the browser does
     * not have an HTTPS connection.
     */
    secure?: boolean | undefined;
}
```

Which results in the final type of

`'domain' | 'path' | 'secure' | 'sameSite' | 'name' | 'value' | 'expires' | 'httpOnly' | 'maxAge' | 'priority'`

The current behavior is that cookies() does not reflect .set() the `priority` attribute into `set-cookie`.

The expected behavior would be that the `priority` attribute would be reflected in `set-cookies`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #14~22.04.1-Ubuntu SMP Wed Sep 13 16:15:26 UTC 2023
Binaries:
  Node: 16.20.0
  npm: 8.19.4
  Yarn: 1.22.19
  pnpm: 8.9.0
Relevant Packages:
  next: 13.5.5-canary.11
  eslint-config-next: 13.5.5-canary.11
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

I ran the next.js repository in codespaces to build, run the tests that failed the expected behavior, create the fix changes, build, and run the tests that now pass the expected behavior

### PR DESCRIPTION
**Pull request by renchris**
Closes https://github.com/vercel/next.js/issues/56848

This PR provides the fix for cookies() .set() to reflect the `priority` attribute into `set-cookie`

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks for the PR, the `@edge-runtime/cookies` package is an upstream dependency, meaning it should be addressed there first, could you open these changes there, so we can bump the package here to incorporate it?

See https://github.com/vercel/edge-runtime/blob/main/packages/cookies/src/serialize.ts#L16

**Comment by renchris** [comment]
> Thanks for the PR, the `@edge-runtime/cookies` package is an upstream dependency, meaning it should be addressed there first, could you open these changes there, so we can bump the package here to incorporate it?
> 
> See https://github.com/vercel/edge-runtime/blob/main/packages/cookies/src/serialize.ts#L16

Okay, I have opened the changes there at `@edge-runtime/cookies` with this Pull Request: https://github.com/vercel/edge-runtime/pull/640

**Comment by Kikobeats** [comment]
Since the issue is fixed at edge-runtime dependency (thanks to @renchris) I created https://github.com/vercel/next.js/pull/56856 🙂

**Review by sumit639-code — APPROVED** [review]

**Comment by balazsorban44** [comment]
Superseded by https://github.com/vercel/next.js/pull/56856, thanks for the PR on `edge-runtime`!

**Pull request closed without merging**
