### PR TITLE
Dynamic component support with multiple modules

### PR DESCRIPTION
**Pull request by arunoda**
> This is a backward compatible change to our existing `next/dynamic` API.

Sometimes we need to import a few modules at once. And select some components based on props.
This new API makes it simple.

Here's the basic usage:

```js
import dynamic from 'next/dynamic'

const HelloBundle = dynamic({
  modules: (props) => {
    const components {
      Hello1: import('../components/hello1'),
      Hello2: import('../components/hello2')
    }

    // Add remove components based on props

    return components
  },
  render: (props, { Hello1, Hello2 }) => (
    <div>
      <h1>{props.title}</h1>
      <Hello1 />
      <Hello2 />
    </div>
  )
})

export default () => (
  <HelloBundle title="Dynamic Bundle"/>
)
```

But with the prop changes, you can make this very powerful.
[See this example](https://github.com/zeit/next.js/pull/2235/files#diff-33c76b614bc2ba4411701614eb59a5c7)

### CODE REVIEW

**Comment by timneutkens** [comment]
@arunoda this is really cool 😲

**Comment by arunoda** [comment]
Don't take this in yet.

**Comment by timneutkens** [comment]
Yeah I thought so 😄

**Comment by arunoda** [comment]
This is working pretty well.

**Pull request merged**
