### PR TITLE
With styled components ssr

### PR DESCRIPTION
**Pull request by Grokling**
Enables SSR style rendering for Styled Components via babel-plugin-styled-components and babel-plugin-stage0. All thanks go to @spencersmb for doing the legwork and figuring out the solution.

### CODE REVIEW

**Comment by timneutkens** [comment]
Merging this in after discussing on slack.

**Comment by SBoudrias** [comment]
Why is babel stage-0 required in this case?

**Comment by Grokling** [comment]
@SBoudrias Good question.

The example seems to run just fine without it. I suspect it was to do with attempts to get an earlier (non-beta) version of styled-components to work in preference to using the beta version, and never got cleaned up.

Seems to me like babel-plugin-stage-0 could be removed.

**Comment by timneutkens** [comment]
@Grokling @SBoudrias fixed in #1959

**Pull request merged**
