### PR TITLE
fix: directory flag prompt

### LINKED ISSUE #62494: Non-interactive `create-next-app ` with `--src-dir` or `--app` flag still toggles question
### Link to the code that reproduces this issue

https://github.com/nattui/next.js

### To Reproduce

**Case 1**: Source directory flag
```bash
# Note the `--src-dir` flag
npx create-next-app@latest my-app --typescript --tailwind --eslint --import-alias "@/*" --src-dir
```
Would you like to use App Router? (recommended) › No / Yes
 
The terminal asks the user to use app directory and it defaults to `Yes` when `--src-dir` flag exist.

---

**Case 2**: App directory flag 
```bash
# Note the `--app` flag
npx create-next-app@latest my-app --typescript --tailwind --eslint --import-alias "@/*" --app
```
Would you like to use `src/` directory? › No / Yes
 
The terminal asks the user to use source directory and it defaults to `No` when `--app` flag exist.

### Current vs. Expected behavior

**Current behavior**:
The terminal asks the user to use app directory and it defaults to `Yes` when `--src-dir` flag exist. Also, the terminal asks the user to use source directory and it defaults to `No` when `--app` flag exist.

**Expected behavior**:
When `--app`, `--no-app`, `--src-dir`, and `--no-src-dir` flag is included with `create-next-app`, the question about which directory to use should be skipped.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 21.6.2
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nattstack**
Fix non-interactive `create-next-app` with `--src-dir` or `--app` flag still prompts question 

Fixes #62494

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thanks, could you add a test case for this under https://github.com/vercel/next.js/blob/canary/packages/create-next-app/index.ts?

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c1f6c9661b89f37eb87fd3860749863b2c3f156e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c1f6c9661b89f37eb87fd3860749863b2c3f156e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by nattui** [comment]
Thank you for the review @balazsorban44! I added test cases for `/packages/create-next-app/index.ts` upon your suggestion.

**Pull request closed without merging**
