### PR TITLE
example: example stylex

### PR DESCRIPTION
**Pull request by bysxx**
# StyleX + Next App Dir (Simple)

### Dev
```
npm run dev
```

### Prod
```
npm run build
npm run start
```

## Link:
- https://stylexjs.com/

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
I would strongly against this example personally.

This setup disables Next.js built-in swc compiler with `.babelrc.js` . Though the stylx itself requires babel to be present, there is no need to disable the swc entirely.

**Comment by leerob** [comment]
Yeah I agree it would be nice to keep SWC if possible. Also, we can make this a very minimal, hello world example.

**Comment by bysxx** [comment]
> I would strongly against this example personally.
> 
> This setup disables Next.js built-in swc compiler with `.babelrc.js` . Though the stylx itself requires babel to be present, there is no need to disable the swc entirely.

I agree with this, but this is the best way because Meta doesn't support SWC at the moment.
I will update the code if Vercel changes it or Meta changes it for compatibility in the future

**Comment by bysxx** [comment]
I agree with your opinion, but this is the best way because Meta doesn't support SWC at the moment.
I will update the code if Vercel changes it or Meta changes it for compatibility in the future

**Comment by SukkaW** [comment]
> I agree with this, but this is the best way because Meta doesn't support SWC at the moment. I will update the code if Vercel changes it or Meta changes it for compatibility in the future
> 
> [facebook/stylex#70](https://github.com/facebook/stylex/issues/70)

I am strongly against this because I know it is possible to use the Babel transform plugin without disabling the Next.js built-in swc compiler. I know it is possible because people have done this before. See https://github.com/SukkaW/style9-webpack, https://github.com/SukkaW/forgetti-loader and https://github.com/johanholmerin/style9.

**Comment by bysxx** [comment]
I'm not sure, all the sources you've shown are quite impressive, but for now, I think the best approach would be to add code that can be applied in this manner and later update it to a method that is officially supported.

**Pull request closed without merging**
