### PR TITLE
ci: flake detection should run in both bundlers

### PR DESCRIPTION
**Pull request by ztanner**
We run flake detection on PRs to help catch flaky tests before they hit canary, but we currently only run flaky test detection in Webpack and not Turbopack. This is problematic because there's sufficient forking logic in tests for the different bundlers & we've seen a high likelihood of a test to flake more frequently in one bundler vs another due to things like differing compilation speeds and differing implementation of core features. 

This will add some additional time to this CI job to account for needing to run the tests 6 times, but will hopefully catch things before they become a problem later. I think we could also consider reducing the number of times per bundler to be 2 if it turns out to be adding too much time. 

This updates the flake detection job to run the tests multiple times in Turbopack as well. 

CI run: https://github.com/vercel/next.js/actions/runs/11822662639/job/32940264160?pr=72773

### CODE REVIEW

**Comment by ztanner** [comment]
* **#72773** <a href="https://app.graphite.dev/github/pr/vercel/next.js/72773?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ijjk — APPROVED** [review]
Do we need to parallelize more to avoid these being slow?

**Review by gaojude — APPROVED** [review]

**Comment by ztanner** [comment]
> Do we need to parallelize more to avoid these being slow?

I think we'll need to see how it goes -- I picked a beefier test to modify and it finished in dev/start flake detection before prod tests finished. I think the current parallelization often goes under utilized because we typically only see a few changes per PR, so if this causes problems I'd probably want to split the Turbopack flake detection into a separate job

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 108d0278f11796b595c2784acc59732d234f93d6

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/development/app-hmr/hmr.test.ts` (PPR)
- app-dir-hmr > filesystem changes > should update server components after navigating to a page with a different runtime

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should update server components after navigating to a page with a different runtime

    expect(received).toBe(expected) // Object.is equality

    Expected: "ipad"
    Received: "mac"

      65 |       await next.patchFile(envFile, 'MY_DEVICE="ipad"', async () => {
      66 |         await retry(async () => {
    > 67 |           expect(await browser.elementByCss('p').text()).toBe('ipad')
         |                                                          ^
      68 |         })
      69 |
      70 |         const logs = await browser.log()

      at toBe (development/app-hmr/hmr.test.ts:67:58)
      at retry (lib/next-test-utils.ts:806:14)
      at development/app-hmr/hmr.test.ts:66:9
      at NextDevInstance.patchFile (lib/next-modes/base.ts:522:9)
      at NextDevInstance.patchFile (lib/next-modes/next-dev.ts:195:16)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:65:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
