### PR TITLE
Handle thrown values that aren't `Error` instances in App router

### PR DESCRIPTION
**Pull request by eps1lon**
Noticed unsound access of `error.digest` when debugging. Test and explainer of refactor will follow. Need the opinion of CI first.

### CODE REVIEW

**Comment by eps1lon** [comment]
* **#71151** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71151?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @eps1lon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8cfa2f8142daab316c3f7951adc15f2e1f1cfa33

`pnpm test-dev test/e2e/opentelemetry/client-trace-metadata/client-trace-metadata.test.ts`
- clientTraceMetadata > app router > should inject propagation data for a dynamically server-side-rendered page
- clientTraceMetadata > app router > hard loading a dynamic page twice should yield different dynamic trace data
- clientTraceMetadata > app router > should only insert the client trace metadata once
- clientTraceMetadata > app router > next dev only > should inject propagation data for a statically server-side-rendered page
- clientTraceMetadata > app router > next dev only > soft navigating to a dynamic page should not transform previous propagation data
- clientTraceMetadata > app router > next dev only > soft navigating to a static page should not transform previous propagation data
- clientTraceMetadata > pages router > should inject propagation data for a dynamically server-side-rendered page
- clientTraceMetadata > pages router > hard loading a dynamic page twice should yield different dynamic trace data
- clientTraceMetadata > pages router > next dev only > should inject propagation data for a statically server-side-rendered page
- clientTraceMetadata > pages router > next dev only > soft navigating to a dynamic page should not transform previous propagation data
- clientTraceMetadata > pages router > next dev only > soft navigating to a static page should not transform previous propagation data

<details>
<summary>Expand output</summary>

  ● clientTraceMetadata › app router › should inject propagation data for a dynamically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › hard loading a dynamic page twice should yield different dynamic trace data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › should only insert the client trace metadata once

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › should inject propagation data for a statically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › soft navigating to a dynamic page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › soft navigating to a static page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › should inject propagation data for a dynamically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › hard loading a dynamic page twice should yield different dynamic trace data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › should inject propagation data for a statically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › soft navigating to a dynamic page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › soft navigating to a static page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by darthmaim** [comment]
I've tried upgrading one of my apps to `15.0.0-canary.185`, but I keep getting this error on all pages:

```raw
 ⨯ next/dist/src/server/app-render/create-error-handler.tsx (164:20) @ stringHash
 ⨯ TypeError: Cannot create property 'digest' on string 'This object has been omitted by React in the console log to avoid sending too much data from the server. Try logging smaller or more specific objects.'
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
digest: "3978771934"
  162 |       }
  163 |     } else {
> 164 |       err.digest = stringHash(
      |                    ^
  165 |         err.message + (errorInfo?.componentStack || err.stack || '')
  166 |       ).toString()
  167 |     }
 ⨯ next/dist/src/server/app-render/create-error-handler.tsx (164:20) @ stringHash
 ⨯ TypeError: Cannot create property 'digest' on string 'This object has been omitted by React in the console log to avoid sending too much data from the server. Try logging smaller or more specific objects.'
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
digest: "3692328984"
  162 |       }
  163 |     } else {
> 164 |       err.digest = stringHash(
      |                    ^
  165 |         err.message + (errorInfo?.componentStack || err.stack || '')
  166 |       ).toString()
  167 |     }
 GET / 500 in 1959ms
 ```
 
I guess this error is at least partially related to this PR, even though the underlaying issue might be caused by something else.

Do you think this PR will fix this issue or should I spent some time trying to create a reproduction and open a new issue for it?

**Comment by eps1lon** [comment]
Replaced by https://github.com/vercel/next.js/pull/71210

**Pull request closed without merging**
