### PR TITLE
Add crossOrigin via props to _document Head and NextScript

### LINKED ISSUE #3630: Add crossorigin attribute to NextScript
I'm using `assetPrefix` to serve my javascripts from a different domain. I need to add `crossorigin="anonymous"` attribute to these script tags in [NextScript](https://github.com/zeit/next.js/blob/4.2.3/server/document.js#L119) for error tracking. Otherwise, error details will not provided because of security reason.

I read the source code, seems no way to do that with `next.config.js`.

### PR DESCRIPTION
**Pull request by Enalmada**
This alternative implementation of https://github.com/zeit/next.js/pull/5150 follows @timneutkens suggestion of using props.

Fixes #5150 
Fixes #3630

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
The PR looks great! The only thing missing is a test for this new behavior.

**Comment by timneutkens** [comment]
You can add this test to `test/integration/app-document` by checking the HTML response

**Comment by Enalmada** [comment]
Ah yes, good idea.  Thanks for telling me which one, that was very helpful.  Tests do not seem to work on windows for me but I was able to WSL them following this: https://github.com/zeit/next.js/blob/canary/contributing.md

image

**Comment by Enalmada** [comment]
Thanks for your help.  I will spend some time figuring out how to get my tests working right.

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
Great PR @Enalmada!

**Comment by timneutkens** [comment]
@jclem didn't know you were running into this at GitHub 😄 Feel free to DM me on spectrum/twitter if you run into specific issues.

**Pull request merged**
