### PR TITLE
Set cache-control public (again) 

### PR DESCRIPTION
**Pull request by jonespen**
Trying again, https://github.com/zeit/next.js/pull/4224

### CODE REVIEW

**Comment by jonespen** [comment]
Any feedback here @timneutkens?

**Review by timneutkens — APPROVED** [review]
Looks good, thank you very much 😌🙏🙌

**Comment by bringking** [comment]
@jonespen @timneutkens it seems this change is breaking our CDN because even 404s for the main chunk return a `public, max-age=31536000, immutable` cache header. This is unlike the other static files which return `no-cache` when they 404

**Comment by jonespen** [comment]
Ouch, that doesn't sound right. You should probably create a new issue for this @bringking

**Comment by bringking** [comment]
@jonespen, yeah I will do that today. Got a temporary fix in place 👌

**Comment by denniswebb** [comment]
@bringking What temporary fix did you use? We have hit this same bug.

**Comment by bringking** [comment]
@denniswebb we went with something like this - 

```javascript
import pathToRegExp from 'path-to-regexp';
import path from 'path';
import fs from 'fs';

const app = nextjs({ dev });

const cacheFixHandlerFactory = (pathRegex, pathFn) => (req, res, next) => {
  // Match the path
  const re = pathToRegExp(pathRegex);
  const result = re.exec(req.url);
  if (!result) return next();

  // Build the path to the static file and check its existence
  const p = pathFn(app.distDir, result);
  fs.access(p, fs.constants.F_OK, err => {
    // TODO This fixes a bug in NextJS 6.1.1
    // Original reference - https://github.com/zeit/next.js/pull/4322
    // We want to ensure if dev or if the file doesn't exist e.g. 404, that
    // cache control will be set to no cache. Otherwise, long caching is desired
    if (err || dev) {
      res.set('Cache-Control', 'no-store, must-revalidate');
    } else {
      res.set('Cache-Control', 'public, max-age=31536000, immutable');
    }
    // After setting the correct headers, delegate to NextJS internal static server
    return app.serveStatic(req, res, p);
  });
};

//...

expressApp
  .use(
    cacheFixHandlerFactory(
      '/_next/webpack/chunks/:chunk(.+).js',
      (distDir, matchResults) =>
        path.join(distDir, 'chunks', `${matchResults[1]}.js`),
    ),
  )
  .use(
    cacheFixHandlerFactory(
      '/_next/static/commons/main-:hash(.+).js',
      (distDir, matchResults) =>
        path.join(distDir, 'static', `commons/main-${matchResults[1]}.js`),
    ),
  )
```

**Pull request merged**
