### PR TITLE
Improve Next.js Link component performance

### PR DESCRIPTION
**Pull request by fuma-nama**
Simplify the logic in the Link component to improve performance.

Remove unnecessary `useEffect` for intersection observer: React.js officially recommended `useState` instead of `useEffect` to detect change of states and props (i.e. `isVisible` from `useIntersection`)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 300e06ccbec56b6c02b5487fdc8b07b609f1d75e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — CHANGES_REQUESTED** [review]
Each of these items in the PR description should be a separate PR. The types-only changes should also be a separate PR were possible.

**Comment by fuma-nama** [comment]
I see, reverted some changes about types

**Comment by fuma-nama** [comment]
The latest commits from canary removed some legacy checks, I've merged these changes

**Pull request closed without merging**
