### PR TITLE
docs/functions/generate-metadata

### PR DESCRIPTION
**Pull request by onahmed**
### What?
- Added the metadata object **abstract** from [metadata-interface.ts](https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/metadata/types/metadata-interface.ts) to [docs/functions/generate-metadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata)
- Added the metadata object **classification** from [metadata-interface.ts](https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/metadata/types/metadata-interface.ts) to [docs/functions/generate-metadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata)

### Why?
Those two metadata objects are included in the metadata-interface.d.ts file, but not in the Next.js docs

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 9896890f77aa4fd53058065bf9ea2f8a8bd7b156

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 9896890f77aa4fd53058065bf9ea2f8a8bd7b156

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by samcx** [comment]
@alpedia0 Should we move this next to [description](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#description) since they're closely related?

**Comment by alpedia0** [comment]
> @alpedia0 Should we move this next to [description](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#description) since they're closely related?

Good suggestion, i just refactored the code and moved **abstract** closer to [description](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#description)

**Comment by samcx** [comment]
@alpedia0 Can we also add more info around classification (e.g., I believe it's not as common as a use-case)?

**Pull request closed without merging**
