### PR TITLE
Expose RouterContext

### LINKED ISSUE #35: Officially expose RouterContext in Next
In order to make this lib more robust, Next should expose the RouterContext officially.

That would require a PR to Next directly, but I open it here because that's probably the best place to track it.

### PR DESCRIPTION
**Pull request by eric-burel**
This is needed by third party apps that setup their own router context, useful for instance the Storybook Next Router Plugin, see https://github.com/lifeiscontent/storybook-addon-next-router/issues/35

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [X] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [X] Documentation added => this is an internal API for third party library developers so maybe better left undocumented
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

Close https://github.com/lifeiscontent/storybook-addon-next-router/issues/35

### CODE REVIEW

**Comment by devknoll** [comment]
I'm a bit hesitant of this being exposed. Could you by chance use `useRouter` and export it under your own context object? Another benefit of that approach is that it would be compatible with more versions of Next.js and you wouldn't need the extra instructions.

**Comment by eric-burel** [comment]
I am not sure that would work because that mean creating a new, different context. Then the `useRouter` deeper in the tree would stop working, as [it uses Next `RouterContext`](https://github.com/vercel/next.js/blob/2e8dafcba3e7b3b0c91d033e5f4ff7aa8668fbb5/packages/next/client/router.ts#L133). 

This PR is meant for testing frameworks so we cannot alter the source code, yet we need to emulate a valid Next.js environment.

**Comment by devknoll** [comment]
Ah, thanks for the additional context.

**Comment by eric-burel** [comment]
Hi, small up on this PR, in Next 12 the export has moved again (now `next/dist/shared/lib/router-context`), breaking the Storybook setup. I confirm exposing the RouterContext would be useful.

**Comment by richard-wiser** [comment]
I second the need for this. We also use `RouterContext` not just in our storybook, but to wrap components in test setups as well - this mitigates the need to mock `Link` components. Having it exported would help us not rely on fragile implementation details.

**Review by ijjk — COMMENTED** [review]
Hi, I'm not sure we want to expose this as even with a consistent import location this could break across versions and the values provided to the `RouterContext` are meant to be internal implementation details and with the new router for layouts knowing which context to leverage when will get more complex leaning towards this being discouraged more so. 

I'm gonna close this for now but we can discuss this further on an idea/request thread!

**Comment by eric-burel** [comment]
This router context is still used by most common Storybook integrations "next addon"' and "next router addon" though:
- https://github.dev/RyanClementsHax/storybook-addon-next/tree/main/src
- and https://github.com/lifeiscontent/storybook-addon-next-router (see Readme)

So if this evolve with incoming release of Next you might want to take Storybook/Jest mocking into account early on to avoid breaking setups

**Pull request closed without merging**
