### PR TITLE
Migrate amp-toolbox-optimizer to @ampproject/toolbox-optimizer

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | sebastianbenz/next.js toolbox-1.0 | Change |
| - | - | - | - |
| Build Duration | 23s | 21.9s | -1.1s |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +19.8 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ⚠️  +1 B |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | -1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ⚠️  +2 B |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | sebastianbenz/next.js toolbox-1.0 | Change |
| - | - | - | - |
| Build Duration | 24.3s | 23.9s | -391ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +19.8 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | -1 B |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ⚠️  +1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | -2 B |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +8 B |
| Serverless `pages/link` gzip Size | 68.5 kB | 68.5 kB | ⚠️  +16 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +8 B |
| Serverless `pages/index` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +11 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +8 B |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.1 kB | ⚠️  +21 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +8 B |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +19 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +8 B |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +18 B |
| Build Dir Size | 2.59 MB | 2.59 MB | ⚠️  +40 B |

</details>

**Comment by ijjk** [comment]
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | sebastianbenz/next.js toolbox-1.0 | Change |
| - | - | - | - |
| Build Duration | 23.1s | 22.8s | -233ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +19.8 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | sebastianbenz/next.js toolbox-1.0 | Change |
| - | - | - | - |
| Build Duration | 24.6s | 24.2s | -370ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +19.8 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 181 kB | 181 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ✓ |
| Client `main` gzip Size | 5.46 kB | 5.46 kB | ✓ |
| Client `main` Modern Size | 12.8 kB | 12.8 kB | ✓ |
| Client `main` Modern gzip Size | 4.83 kB | 4.83 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ✓ |
| Client `commons` Modern Size | 169 kB | 169 kB | ✓ |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +8 B |
| Serverless `pages/link` gzip Size | 68.5 kB | 68.5 kB | ⚠️  +14 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +8 B |
| Serverless `pages/index` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +10 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +8 B |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.1 kB | ⚠️  +18 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +8 B |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +19 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +8 B |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +19 B |
| Build Dir Size | 2.59 MB | 2.59 MB | ⚠️  +40 B |

</details>

**Review by ijjk — APPROVED** [review]
The windows validation failures seem to be related to #8277 not this, so looks good 👍

**Comment by Timer** [comment]
Thanks @sebastianbenz!

**Pull request merged**
