### PR TITLE
chore: add math functions from core-js

### LINKED ISSUE #11714: IE11 polyfills: missing Math.trunc
# Bug report

## Describe the bug

`Math.trunc` is not available in IE11. Seeing errors show up in bugsnag for this one.

## Expected behavior

`Math.trunc` should be polyfilled in the IE11 polyfill bundle.

## System information

- OS: all
- Browser (if applies) IE 11
- Version of Next.js: latest

### PR DESCRIPTION
**Pull request by tarunama**
Fixes #11714

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.5s | ⚠️ +225ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +4.64 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.024 | 2.052 | ⚠️ +0.03 |
| / avg req/sec | 1235.47 | 1218.12 | ⚠️ -17.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.321 | 1.274 | -0.05 |
| /error-in-render avg req/sec | 1892.09 | 1962.6 | +70.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1fee81a..2bb3.js gzip | 6.62 kB | 6.62 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 32.8 kB | ⚠️ +1.66 kB |
| Overall change | 31.2 kB | 32.8 kB | ⚠️ +1.66 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 618 B | 619 B | ⚠️ +1 B |
| withRouter.html gzip | 605 B | 606 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-ae..7af5f55f8.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -50,7 +50,7 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
+      src="/_next/static/chunks/polyfills-5ad1813c388a3e3956c0.js"
     ></script>
     <script
       src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -55,7 +55,7 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
+      src="/_next/static/chunks/polyfills-5ad1813c388a3e3956c0.js"
     ></script>
     <script
       src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -50,7 +50,7 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
+      src="/_next/static/chunks/polyfills-5ad1813c388a3e3956c0.js"
     ></script>
     <script
       src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.3s | ⚠️ +158ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +4.64 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1fee81a..2bb3.js gzip | 6.62 kB | 6.62 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | N/A | N/A |
| polyfills-2b..3da5.js gzip | N/A | 32.8 kB | N/A |
| Overall change | 31.2 kB | 32.8 kB | ⚠️ +1.66 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js chore/add-core-js-math | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: ac57919c7fd29e8dc52673dd7f0de69ebd9045fa

**Comment by ijjk** [comment]
## Failing test suites 
Commit: ac57919c7fd29e8dc52673dd7f0de69ebd9045fa

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeCloseTo(expected, precision)

    Expected: 282.6
    Received: 287.0791015625

    Expected precision:    0
    Expected difference: < 0.5
    Received difference:   4.479101562499977

      82 | 
      83 |     // Expected difference: < 0.5
    > 84 |     expect(delta).toBeCloseTo(282.6, 0)
         |                   ^
      85 |   })
      86 | })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

</details>

**Review by Timer — CHANGES_REQUESTED** [review]
These polyfills should strictly be added when used, not unconditionally!

https://github.com/vercel/next.js/issues/11714#issuecomment-610415901

You'll need to write a Babel plugin to apply this.

**Comment by tarunama** [comment]
I see. I"ll write babel plugin.

**Pull request closed without merging**
