### PR TITLE
 Allow filtering of props sent to browser

### PR DESCRIPTION
**Pull request by jesstelford**
With a custom Document renderer, `filterProps` can be passed to `NextScript`, which is passed the result of `getInitialProps()`. Enables more complex usecases such as referring to `ctx.req.cookie` on server, but `document.cookie` on client.

For exmaple, imagine this scenario:

```javascript
class About extends React.Component {
  static getInitialProps({ req }) {
    return { req }; // Normally this would cause a serialization error
  }

  render() {
    return <Header req={this.req} />;
  }
}

class Header extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      // A contrived example, but imagine a component that handles its own cookies, which isn't the page-level component
      loggedIn: parseCookie(props.req ? props.req.cookie : document.cookie),
    };
  }
  render() {
    return <div>{this.state.loggedIn ? 'Logged in' : 'Logged out'}</div>;
  }
}

export default class MyDocument extends Document {
  render() {
    return (
      <html lang="en-AU">
        <Head />
        <body>
          <Main />
          {/* Drop `req` so it never gets to the browser */}
          <NextScriptFilter filterProps={filterOutReq} />
        </body>
      </html>
    );
  }
}

function filterOutReq(props) {
  return {
    ...props,
    req: undefined,
  }
}
```

---

Until merged, my current workaround involves the following:

```javascript
class NextScriptFilter extends React.Component {
  static propTypes = {
    filterProps: propTypes.func,
  };

  static defaultProps = {
    filterProps: p => p,
  };

  static contextTypes = {
    _documentProps: propTypes.any,
  };

  static childContextTypes = {
    _documentProps: propTypes.any,
  };

  getChildContext() {
    /* eslint-disable no-underscore-dangle */
    return {
      _documentProps: {
        ...this.context._documentProps,
        __NEXT_DATA__: {
          ...this.context._documentProps.__NEXT_DATA__,
          props: this.props.filterProps(this.context._documentProps.__NEXT_DATA__.props),
        },
      },
    };
    /* eslint-enable no-underscore-dangle */
  }

  render() {
    return <NextScript />;
  }
}
```

### CODE REVIEW

**Comment by sergiodxa** [comment]
You can create a HOC to wrap your pages and filter the props, something like this:

```js
function filterProps(filter) {
  return Page => {
    return class extends React.Component {
      static async getInitialProps(ctx) {
        if (!Page.getInitialProps) return {}
        const props = await Page.getInitialProps(ctx);
        return filter(props); // remove any prop you want here
      }
    }
  }
}
```

And then you use it this way:

```js
class About extends React.Component {
  static async getInitialProps({ req }) {
    return { req }; // Normally this would cause a serialization error
  }

  render() {
    return <Header req={this.props.req} />;
  }
}

function filterOutReq(props) {
  return {
    ...props,
    req: undefined,
  }
}

// here you apply the filter
export default filterProps(filterOutReq)(About)
```

This way you can compose your filters, e.g. you can have `filterReq` and `filterRes` functions and use:

```js
export default compose(
  filterProps(filterReq),
  filterProps(filterRes)
)(About)
```

And you can apply the prop filters you want per page instead of defining a global one, also this can work either server and client side instead of only server side like a change to `NextScript`.

**Comment by jesstelford** [comment]
@sergiodxa that would filter the props on both server and client before it ever got to the component.

ie;

```
class About extends React.Component {
  static async getInitialProps({ req }) {
    return { req };
  }

  render() {
    // this.props.req is undefined
    return <Header req={this.props.req} />;
  }
}
function filterOutReq(props) {
  return {
    ...props,
    req: undefined,
  }
}

export default filterProps(filterOutReq)(About)
```

The goal here is to provide certain props during the server render, but to remove / filter those props so they never make it to the client. 

Can be useful for other things also, such as passing a `logger` function in as a prop which uses information from `ctx.req` as part of its output. But this `logger` function shouldn't be passed to the browser as a prop, instead it should be filtered out and the react components have logic like `this.props.logger && this.props.logger('Hello world')`.

**Comment by jesstelford** [comment]
Perhaps a different mechanism is required for this? Maybe a `static getInitialServerProps()` which defaults to `getInitialProps()` when not defined? However, that would mean both `getInitialServerProps()` and `getIntialProps()` must be executed for each page load, doubling the render time.

**Comment by jesstelford** [comment]
To clarify, the original renderin pipeline goes:

```
const props = getInitialProps() -> renderServer(props) -> renderDocument({ __NEXT__: { props }}) -> browser
```
This PR introduces a new (optional) step:

```
const props = getInitialProps() -> renderServer(props) -> props = filterProps(props) -> renderDocument({ __NEXT__: { props }}) -> browser
```

Note that the new step ` props = filterProps(props)` comes _after _ the `renderServer()` call, but before they're embedded into the response sent to the browser.

**Comment by thealjey** [comment]
@jesstelford thank you so much, you are a life saver!
I hope this gets merged, but for now your temporary solution is just perfect for me.

**Comment by timneutkens** [comment]
I'm going to close this in favor of the new rendering pipeline I'm working on, I'll try to keep this case in mind. For the initially provided context around the issue, I'd make the case that components shouldn't be aware of `req` or `res`, instead `getInitialProps` should hand the view all the data it needs. Providing the cookie to all pages is very trivial now that we have the custom _app.js component.

**Comment by thealjey** [comment]
@timneutkens I think you're right about this not being needed anymore
in the latest version of Next `_app.js` and `withRoute` give me everything I needed this feature for and more, and in a much cleaner way
Next.js is super awesome, btw!

**Comment by timneutkens** [comment]
Great! That's what I thought 🙌

**Comment by jesstelford** [comment]
Great outcome! 🎉

**Pull request closed without merging**
