### PR TITLE
Implement tslint for core files

### LINKED ISSUE #5845: Implement tslint for core files
# Feature request

## Is your feature request related to a problem? Please describe.

`eslint` has a parser for typescript but it proves to be insufficient for all cases of typescript, so implement tslint is the way to go.

## Describe the solution you'd like

Implement `tslint` for both `next` and `next-server`, but keep standardjs/eslint for the `.js` files that are still there, we're gradually migrating to Typescript.

## Additional context

Feel free to reach out under this issue with questions if needed, I'd be happy to give advice.

### PR DESCRIPTION
**Pull request by andersonleite**
Fixes #5845 

Implement tslint for core files

**What is this?**
Implements tslint for both next and next-server, but keeps standardjs/eslint for the .js files that are still there, we're gradually migrating to Typescript.

**How does it work?**
Before every commit (pre-commit) we execute the following `tslint` command:
`tslint -c tslint.json 'packages/**/*.ts`

**TSLint Rules**
In order to avoid as much changes as possible I marked some rules as false. This way we can improve the linter but making sure this step will not break things. (see tslint.json)

**Note**
After merging this PR, you'll need to update your dependencies since it adds tslint to package.json

### CODE REVIEW

**Comment by andersonleite** [comment]
@timneutkens 

Question: When we run `tslint` it will complain about some typescript styles guide definitions that are not applied yet:

`ERROR: packages/next/bin/next-build.ts:2:10 - Named imports must be alphabetized.
ERROR: packages/next/bin/next-build.ts:2:31 - ' should be "
ERROR: packages/next/bin/next-build.ts:2:37 - Missing semicolon
ERROR: packages/next/bin/next-build.ts:3:1 - Import sources within a group must be alphabetized.
ERROR: packages/next/bin/next-build.ts:3:28 - ' should be "
ERROR: packages/next/bin/next-build.ts:3:32 - Missing semicolon
ERROR: packages/next/bin/next-build.ts:4:1 - Import sources within a group must be alphabetized.
ERROR: packages/next/bin/next-build.ts:4:17 - ' should be "
ERROR: packages/next/bin/next-build.ts:4:22 - Missing semicolon
ERROR: packages/next/bin/next-build.ts:5:19 - ' should be "
ERROR: packages/next/bin/next-build.ts:5:29 - Missing semicolon
ERROR: packages/next/bin/next-build.ts:6:30 - ' should be "
ERROR: packages/next/bin/next-build.ts:6:51 - Missing semicolon`

Should I clean up everything with this PR? Or can I do it in a separate PR?

**Comment by timneutkens** [comment]
Could we run tslint over all `.js` files in `packages` too? I assume that would work fine since JS is valid TS 🤔 Then let's drop standardjs from the core files as a start.

**Comment by andersonleite** [comment]
It works.

```
    "*.js": [
      "tslint -c tslint.json 'packages/**/*.js'",
      "git add"
    ],
    "*.ts": [
      "tslint -c tslint.json 'packages/**/*.ts'",
      "git add"
    ],
```

We will have more files to clean up, for example:

ERROR: packages/next/pages/_app.js:31:9 - Spaces before function parens are disallowed
ERROR: packages/next/pages/_app.js:32:20 - Shadowed name: 'Component'
ERROR: packages/next/pages/_app.js:32:54 - Missing semicolon
ERROR: packages/next/pages/_app.js:33:34 - Missing semicolon
ERROR: packages/next/pages/_app.js:36:17 - Missing semicolon
ERROR: packages/next/pages/_app.js:41:20 - Spaces before function parens are disallowed

**Comment by timneutkens** [comment]
@andersonleite let's keep standardjs for `.js` files then and gradually implement 🙏

**Comment by andersonleite** [comment]
@timneutkens I believe tslint is configured for the core files now.
I added more info to the description. Basically, on pre-commit, stardard is removed and tslint will be executed for the core files. 
I've updated the ts files on /packages to be conformant with tslint rules. 

Let me know if that's ok.

About coveralls, I'm not sure why coverage decreased 3.7%

**Comment by dav-is** [comment]
We're going to start using semicolons and double quotes? 😬

**Comment by andersonleite** [comment]
haha I was in doubt about semicolons and double quotes @dav-is  ... but since is the default for TSLint, I assumed yes and to avoid bikeshedding I didn't ask and just updated.

I like trailing comas too. Other TSLint rules:

- Import sources within a group must be alphabetized.
- Spaces before function parens are disallowed.
- Declaration of public instance method not allowed after declaration of private instance method. Instead, this should come after constructors.

How do you think we should proceed? We can start a discussion or I can just remove this two rules (semicolons and double quotes) and update the files. Let me know how to proceed!

^ @timneutkens

**Comment by dav-is** [comment]
I do think some of the ones youve disabled would be helpful like `object-literal-sort-keys`, so maybe we need a discussion. I try to avoid the huge diffs that come with changing style guides (which mess with PRs). I think we should make this change once and stick with it.

**Comment by timneutkens** [comment]
Let's keep single quotes and no-semicolons if possible, this will make the change way smaller 👍

**Comment by andersonleite** [comment]
Added 
    "semicolon": false,
    "quotemark": false,
to TSLint, so we don't need to update it.

I'm keeping the following rules cause I think they are helpful:
- Missing trailing comma
- Spaces before function parens are disallowed

Let me know if you all think it's ok.

**Review by timneutkens — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
