### PR TITLE
Rename `root-layout-missing-tags-error.tsx` to pascal case

### PR DESCRIPTION
**Pull request by devjiwonchoi**
Changed filename `root-layout-missing-tags-error.tsx` to `RootLayoutMissingTagsError.tsx`. Synced with old UI also.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| buildDuration | 18s | 15.9s | N/A |
| buildDurationCached | 15s | 12.7s | N/A |
| nodeModulesSize | 416 MB | 416 MB | ⚠️ +15.4 kB |
| nextStartRea..uration (ms) | 472ms | 473ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| 1187-HASH.js gzip | 52.4 kB | 52.4 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.36 kB | 5.36 kB | N/A |
| bccd1874-HASH.js gzip | 53 kB | 53 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 233 B | 235 B | N/A |
| main-HASH.js gzip | 34.1 kB | 34.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 746 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| index.html gzip | 523 B | 524 B | N/A |
| link.html gzip | 538 B | 538 B | ✓ |
| withRouter.html gzip | 519 B | 521 B | N/A |
| Overall change | 538 B | 538 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 205 kB | 205 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 668 B | 669 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.3 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 356 kB | 356 kB | ⚠️ +436 B |
| app-page-exp..prod.js gzip | 129 kB | 129 kB | ✓ |
| app-page-tur..prod.js gzip | 142 kB | 142 kB | ✓ |
| app-page-tur..prod.js gzip | 137 kB | 137 kB | ✓ |
| app-page.run...dev.js gzip | 346 kB | 347 kB | ⚠️ +446 B |
| app-page.run..prod.js gzip | 125 kB | 125 kB | ✓ |
| app-route-ex...dev.js gzip | 37.5 kB | 37.5 kB | ✓ |
| app-route-ex..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.5 kB | 25.5 kB | ✓ |
| app-route-tu..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| app-route.ru...dev.js gzip | 39.1 kB | 39.1 kB | ✓ |
| app-route.ru..prod.js gzip | 25.3 kB | 25.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.7 kB | 21.7 kB | ✓ |
| server.runti..prod.js gzip | 916 kB | 916 kB | ✓ |
| Overall change | 2.43 MB | 2.43 MB | ⚠️ +882 B |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 12-19-rename_root-layout-missing-tags-error.tsx_to_pascal_case | Change |
| - | - | - | - |
| 0.pack gzip | 2.08 MB | 2.08 MB | N/A |
| index.pack gzip | 74.8 kB | 74.8 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-page-exp..ntime.dev.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>app-page.runtime.dev.js</strong></summary>

```diff
failed to diff
```
</details>

</details>

</details>
Commit: 0d409c2de68341d9fafa000b7fe3a8d1f089c470

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7c7ec93972cfd327e5b3d886561fbcae45ab9942

`pnpm test-dev test/e2e/opentelemetry/client-trace-metadata/client-trace-metadata.test.ts`
- clientTraceMetadata > app router > should inject propagation data for a dynamically server-side-rendered page
- clientTraceMetadata > app router > hard loading a dynamic page twice should yield different dynamic trace data
- clientTraceMetadata > app router > should only insert the client trace metadata once
- clientTraceMetadata > app router > next dev only > should inject propagation data for a statically server-side-rendered page
- clientTraceMetadata > app router > next dev only > soft navigating to a dynamic page should not transform previous propagation data
- clientTraceMetadata > app router > next dev only > soft navigating to a static page should not transform previous propagation data
- clientTraceMetadata > pages router > should inject propagation data for a dynamically server-side-rendered page
- clientTraceMetadata > pages router > hard loading a dynamic page twice should yield different dynamic trace data
- clientTraceMetadata > pages router > next dev only > should inject propagation data for a statically server-side-rendered page
- clientTraceMetadata > pages router > next dev only > soft navigating to a dynamic page should not transform previous propagation data
- clientTraceMetadata > pages router > next dev only > soft navigating to a static page should not transform previous propagation data

<details>
<summary>Expand output</summary>

  ● clientTraceMetadata › app router › should inject propagation data for a dynamically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › hard loading a dynamic page twice should yield different dynamic trace data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › should only insert the client trace metadata once

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › should inject propagation data for a statically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › soft navigating to a dynamic page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › app router › next dev only › soft navigating to a static page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › should inject propagation data for a dynamically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › hard loading a dynamic page twice should yield different dynamic trace data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › should inject propagation data for a statically server-side-rendered page

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › soft navigating to a dynamic page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

  ● clientTraceMetadata › pages router › next dev only › soft navigating to a static page should not transform previous propagation data

    Failed to start server after 10000ms, waiting for this log pattern: / ✓ Ready in /

      347 |     return setTimeout(() => {
      348 |       reject(
    > 349 |         new Error(
          |         ^
      350 |           `Failed to start server after ${ms}ms, waiting for this log pattern: ${this.serverReadyPattern}`
      351 |         )
      352 |       )

      at Timeout._onTimeout (lib/next-modes/base.ts:349:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ijjk — APPROVED** [review]

**Comment by devjiwonchoi** [comment]
### Merge activity

* **Dec 19, 4:02 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/74089).

**Review by huozhi — COMMENTED** [review]
We were intended to use all files with lower cases and dashes to avoid the inconsistence behavior across platform. Ideall all should rename to lower case instead of pascal case

**Pull request merged**
