### PR TITLE
Added nodeFileTraceResolve option for next.config.js

### PR DESCRIPTION
**Pull request by iivankin**
@vercel/nft has a `resolve` hook in the options [here](https://github.com/vercel/nft/blob/main/src/types.ts#L51)
It was very useful for customizing module resolution for advanced use cases like https://github.com/vercel/next.js/issues/34592
It would be cool if we could use this in Next.js as well. A very small change.

### CODE REVIEW

**Review by timneutkens — CHANGES_REQUESTED** [review]
This is leaking the underlying implementation which we have to avoid in order to ensure a faster solution can be implemented in the future. It seems that you want to add this only to support Yarn PnP so that should probably be fixed instead of allowing for this option to be passed.

**Comment by iivankin** [comment]
The problem itself is not with nextjs, but with @vercel/nft. There was already an attempt to fix it [here](https://github.com/vercel/nft/pull/152) which just resulted in the `resolve` hook, which is what I'm trying to use in next, because there is simply no other option.

**Comment by iivankin** [comment]
Any chance?

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, I don't think we want to expose this method as it's internal and could break between versions. Instead it would be good to ensure we can handle the case mentioned in the issue without users having to customize this handling.

I'm gonna close this PR and discussion can continue on the linked issue

**Pull request closed without merging**
