### PR TITLE
Flush style updates before DOM mutations

### LINKED ISSUE #17086: Page renders before styles are loaded in the page on client side navigation
# Bug report

## Describe the bug
When navigating between pages on **client side** (prod build) the page get's rendered **before** the styles are loaded.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create page 1 with a link to page 2
2. on page 2 make a component that measures the width on `componentDidMount` hook
3. Make the component width to `100px` by using css
4. Print the value from the measurement of `componentDidMount`
5. The value won't be 100px.

## Expected behavior

The page must render after the styles are loaded.

## Screenshots

image
image
The carousel in this image is uses the width of the item which is calculated in `componentDidMount`

## System information

- OS: macOS, Windows
- Browser (if applies) chrome, safari
- Version of Next.js:  9.5.3
- Version of Node.js: 12

## Additional context
[This repo](https://github.com/felixmosh/next-bug-17086) reproduces the issue constantly.

Run
1. `yarn`
2. `yarn build && yarn start`
3. open `localhost:3000`
4. open console, and click the `about link`.

In the console you will see **wrong** measurement.

### Notes
1. It reproduces only in `production` mode
2. It reproduces only when the component which measure itself is a **class component** (not sure why)
3. Probably related to https://github.com/vercel/next.js/pull/16581

### PR DESCRIPTION
**Pull request by devknoll**
Closes #17120
Fixes #17086

---

Previously, we would flush `<style>` changes via `useLayoutEffect`. This is too late, because it's run *after* the DOM has already been mutated, and lifecycles like `componentDidMount` have been called, leading to a difference in behavior in initial render and client navigation.

Instead, we should make sure to flush stylesheet changes immediately before React commits DOM mutations. Currently, the only lifecycle exposed for this is `getSnapshotBeforeUpdate`, so we use that.

cc @Timer @timneutkens @ijjk

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8a109cbe429af426fc18b2a82f98a721d8f989e0

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.09999999999999432

       96 | 
       97 |       // should be no bigger than 60.8 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 61.2).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | ⚠️ +21ms |
| nodeModulesSize | 91.3 MB | 91.3 MB | ⚠️ +1.48 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.836 | 2.811 | -0.02 |
| / avg req/sec | 881.6 | 889.34 | +7.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.68 | 1.738 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1487.96 | 1438.23 | ⚠️ -49.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-2bc1e97..bed6.js gzip | 7.35 kB | 7.41 kB | ⚠️ +68 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.4 kB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | 7.03 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-8cad9cc..dule.js gzip | 6.33 kB | 6.4 kB | ⚠️ +65 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +65 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 995 B | 995 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-3f60440..e2.module.js</strong></summary>

```diff
@@ -782,7 +782,7 @@
           return true;
         }
 
-        function onCommit() {
+        function onBeforeCommit() {
           if (
             // We use `style-loader` in development, so we don't need to do anything
             // unless we're in production:
@@ -841,14 +841,17 @@
 
             getComputedStyle(document.body, "height");
           }
+        }
 
+        function onCommit() {
           resolvePromise();
         }
 
         var elem = /*#__PURE__*/ _react.default.createElement(
           Root,
           {
-            callback: onCommit
+            onCommit: onCommit,
+            onBeforeCommit: onBeforeCommit
           },
           /*#__PURE__*/ _react.default.createElement(
             AppContainer,
@@ -864,11 +867,11 @@
       }
 
       function Root(_ref9) {
-        var { callback, children } = _ref9;
+        var { onBeforeCommit, onCommit, children } = _ref9;
 
         // We use `useLayoutEffect` to guarantee the callback is executed
         // as soon as React flushes the update.
-        _react.default.useLayoutEffect(() => callback(), [callback]);
+        _react.default.useLayoutEffect(() => onCommit(), [onCommit]);
 
         if (undefined) {
           // eslint-disable-next-line react-hooks/rules-of-hooks
@@ -884,9 +887,31 @@
 
         _react.default.useEffect(() => {
           (0, _performanceRelayer.default)(onPerfEntry);
-        }, []);
+        }, []); // TODO: React doesn't currently expose any hooks for the before mutation
+        // phase, so we need to use a class component with `getSnapshotBeforeUpdate`.
+
+        return /*#__PURE__*/ _react.default.createElement(
+          BeforeCommit,
+          {
+            onBeforeCommit: onBeforeCommit
+          },
+          children
+        );
+      }
+
+      class BeforeCommit extends _react.default.PureComponent {
+        getSnapshotBeforeUpdate() {
+          this.props.onBeforeCommit();
+          return null;
+        }
+
+        componentDidUpdate() {
+          // noop
+        }
 
-        return children;
+        render() {
+          return this.props.children;
+        }
       }
 
       /***/
```
</details>
<details>
<summary>Diff for <strong>main-79b6335..62a786f3d.js</strong></summary>

```diff
@@ -1052,7 +1052,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
           return true;
         }
 
-        function onCommit() {
+        function onBeforeCommit() {
           if (
             // We use `style-loader` in development, so we don't need to do anything
             // unless we're in production:
@@ -1115,14 +1115,17 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
             getComputedStyle(document.body, "height");
           }
+        }
 
+        function onCommit() {
           resolvePromise();
         }
 
         var elem = /*#__PURE__*/ _react["default"].createElement(
           Root,
           {
-            callback: onCommit
+            onCommit: onCommit,
+            onBeforeCommit: onBeforeCommit
           },
           /*#__PURE__*/ _react["default"].createElement(
             AppContainer,
@@ -1138,16 +1141,17 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       }
 
       function Root(_ref11) {
-        var callback = _ref11.callback,
+        var onBeforeCommit = _ref11.onBeforeCommit,
+          onCommit = _ref11.onCommit,
           children = _ref11.children;
 
         // We use `useLayoutEffect` to guarantee the callback is executed
         // as soon as React flushes the update.
         _react["default"].useLayoutEffect(
           function() {
-            return callback();
+            return onCommit();
           },
-          [callback]
+          [onCommit]
         );
 
         if (undefined) {
@@ -1164,11 +1168,54 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
         _react["default"].useEffect(function() {
           (0, _performanceRelayer["default"])(onPerfEntry);
-        }, []);
+        }, []); // TODO: React doesn't currently expose any hooks for the before mutation
+        // phase, so we need to use a class component with `getSnapshotBeforeUpdate`.
 
-        return children;
+        return /*#__PURE__*/ _react["default"].createElement(
+          BeforeCommit,
+          {
+            onBeforeCommit: onBeforeCommit
+          },
+          children
+        );
       }
 
+      var BeforeCommit = /*#__PURE__*/ (function(_react$default$PureCo) {
+        _inherits(BeforeCommit, _react$default$PureCo);
+
+        var _super2 = _createSuper(BeforeCommit);
+
+        function BeforeCommit() {
+          _classCallCheck(this, BeforeCommit);
+
+          return _super2.apply(this, arguments);
+        }
+
+        _createClass(BeforeCommit, [
+          {
+            key: "getSnapshotBeforeUpdate",
+            value: function getSnapshotBeforeUpdate() {
+              this.props.onBeforeCommit();
+              return null;
+            }
+          },
+          {
+            key: "componentDidUpdate",
+            value: function componentDidUpdate() {
+              // noop
+            }
+          },
+          {
+            key: "render",
+            value: function render() {
+              return this.props.children;
+            }
+          }
+        ]);
+
+        return BeforeCommit;
+      })(_react["default"].PureComponent);
+
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      href="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -85,13 +85,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-79b63357e0e62a786f3d.js"
+      src="/_next/static/chunks/main-66184cfbb41f8ae25a5d.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      src="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      href="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -90,13 +90,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-79b63357e0e62a786f3d.js"
+      src="/_next/static/chunks/main-66184cfbb41f8ae25a5d.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      src="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -6,7 +6,7 @@
     <noscript data-n-css="true"></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      href="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -85,13 +85,13 @@
       src="/_next/static/chunks/polyfills-f73ba3fc145972ef83e9.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-79b63357e0e62a786f3d.js"
+      src="/_next/static/chunks/main-66184cfbb41f8ae25a5d.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/main-3f60440b32685c6d43e2.module.js"
+      src="/_next/static/chunks/main-6e8c906ca50217336423.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| buildDuration | 16.7s | 17.2s | ⚠️ +494ms |
| nodeModulesSize | 91.3 MB | 91.3 MB | ⚠️ +1.48 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| 677f882d2ed8..3aa9.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-2bc1e97..bed6.js gzip | 7.35 kB | N/A | N/A |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| main-4b0d9e4..c208.js gzip | N/A | 7.41 kB | N/A |
| Overall change | 58.3 kB | 58.4 kB | ⚠️ +68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.03 kB | 7.03 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-8cad9cc..dule.js gzip | 6.33 kB | N/A | N/A |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| main-39e61b2..dule.js gzip | N/A | 6.4 kB | N/A |
| Overall change | 53.1 kB | 53.1 kB | ⚠️ +65 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-41ceea0..6b62.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-2d41a89..dule.js gzip | 1.31 kB | 1.31 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.4 kB | 5.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js fix-styles-rendering | Change |
| - | - | - | - |
| _error.js | 1.06 MB | 1.06 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.06 MB | 1.06 MB | ✓ |
| link.js | 1.11 MB | 1.11 MB | ✓ |
| routerDirect.js | 1.1 MB | 1.1 MB | ✓ |
| withRouter.js | 1.1 MB | 1.1 MB | ✓ |
| Overall change | 5.43 MB | 5.43 MB | ✓ |

</details>

</details>
Commit: 8a109cbe429af426fc18b2a82f98a721d8f989e0

**Comment by devknoll** [comment]
After chatting with the React team, it sounds like this isn't the approach we'll want to take either.

**Comment by felixmosh** [comment]
@devknoll why in your opinion this should be bound somehow to react lifecycle?

In my pr I’ve just extracted the code that handles styles to run before the entire render call.
I’ve tested it in my app, this solved the measuring bug.

**Comment by devknoll** [comment]
@felixmosh The issue is: that approach doesn’t generally work with React Concurrent Mode, which can have a delay between the render phase and commit phase. The result is that you could end up removing styles from elements while they’re still on the screen, or while React is running other commit hooks, leading to the same problem we’re trying to fix in the first place.

**Comment by felixmosh** [comment]
Any updates?

BTW, I've thought about it, there is no reason for supporting React Concurrent Mode because of the fact that the code that is responsible for style changes is related only to **page navigation**, which at this scenario Next render an entire page from scratch.
I'm not sure that it's true, but from what I've understood from the code, it looks like it is true.
WDYT?

BTW, this bug is a critical one, since because of it, I can't update to 9.5.4 which solves a security issue, can you some how promote it? looks like there are many open issues which related to the same piece of code. 
(I think that it should be revered to the way it works in `9.5.2`)

**Pull request closed without merging**
