### PR TITLE
fix(Link): Do not ignore onMouseEnter prop with absolute href

### LINKED ISSUE #22733: next/link: onMouseEnter etc. not called on inner <a> tag when href is external
### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next build - currently running locally

### Describe the Bug

When using next/link's `<Link/>` to wrap an anchor tag with an onMouseEnter prop, this is only fired when the href is a local link such as "/" or "/messages", and not when the href is external like "https://google.com" or "mailto:helpme@nextpeople.js".

### Expected Behavior

I expected onMouseEnter calls to fire regardless of the nature of the href link. This affects intended features like hover effects, etc.

### To Reproduce

```
<Link href="https://google.com">
        <a onMouseEnter={() => console.log('External link - onMouseEnter')}>External</a>
</Link>
```
                    
```
<Link href="/">
        <a onMouseEnter={() => console.log('Local link - onMouseEnter')}>Local</a>
</Link>
```

Have a hover around - you'll only see 'Local link - onMouseEnter' in the logs. Tie mouseEnter/mouseLeave etc. state to opacity and only the local link will change opacity.

### PR DESCRIPTION
**Pull request by ericmatthys**
Fixes #22733

Regardless of whether it's recommended that Link be used with external href values or not, they can be used and `onMouseEnter` being swallowed with an external href value is unexpected behavior.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Hi, can you add a test for this? It can go in [this test suite](https://github.com/vercel/next.js/blob/canary/test/integration/client-navigation/test/index.test.js)

**Comment by ericmatthys** [comment]
@ijjk I added a test. I wasn't sure where exactly it fit best since there weren't others like it, but let me know if it should be moved.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| buildDuration | 26.3s | 26.5s | ⚠️ +171ms |
| buildDurationCached | 4.7s | 4.6s | -116ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.267 | 4.342 | ⚠️ +0.07 |
| / avg req/sec | 585.88 | 575.83 | ⚠️ -10.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.325 | 2.204 | -0.12 |
| /error-in-render avg req/sec | 1075.37 | 1134.35 | +58.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | -4 B |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | -4 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 545 B | -1 B |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -13,7 +13,7 @@ self.__BUILD_MANIFEST = {
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b57fa5abc6a43d15.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -255,13 +255,14 @@
           }
         };
         childProps.onMouseEnter = function(e) {
-          if (!(0, _router).isLocalURL(href)) return;
           if (child.props && typeof child.props.onMouseEnter === "function") {
             child.props.onMouseEnter(e);
           }
-          prefetch(router, href, as, {
-            priority: true
-          });
+          if ((0, _router).isLocalURL(href)) {
+            prefetch(router, href, as, {
+              priority: true
+            });
+          }
         };
         // If child is an <a> tag and doesn't have a href attribute, or if the 'passHref' property is
         // defined, we specify the current 'href', so that repetition is not needed by the user
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-678af336607f5345.js"
+      src="/_next/static/chunks/pages/link-b57fa5abc6a43d15.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| buildDuration | 28.6s | 28.2s | -326ms |
| buildDurationCached | 4.7s | 4.7s | -8ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +25 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.374 | 4.284 | -0.09 |
| / avg req/sec | 571.53 | 583.55 | +12.02 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.324 | 2.245 | -0.08 |
| /error-in-render avg req/sec | 1075.81 | 1113.79 | +37.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.9 kB | -2 B |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | -2 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ericmatthys/next.js external-link-mouse-enter | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -13,7 +13,7 @@ self.__BUILD_MANIFEST = {
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
   "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-f207079640969086.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-678af336607f5345.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-b57fa5abc6a43d15.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>link-HASH.js</strong></summary>

```diff
@@ -255,13 +255,14 @@
           }
         };
         childProps.onMouseEnter = function(e) {
-          if (!(0, _router).isLocalURL(href)) return;
           if (child.props && typeof child.props.onMouseEnter === "function") {
             child.props.onMouseEnter(e);
           }
-          prefetch(router, href, as, {
-            priority: true
-          });
+          if ((0, _router).isLocalURL(href)) {
+            prefetch(router, href, as, {
+              priority: true
+            });
+          }
         };
         // If child is an <a> tag and doesn't have a href attribute, or if the 'passHref' property is
         // defined, we specify the current 'href', so that repetition is not needed by the user
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,7 +27,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-678af336607f5345.js"
+      src="/_next/static/chunks/pages/link-b57fa5abc6a43d15.js"
       defer=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" defer=""></script>
```
</details>
</details>
Commit: b86fb43099ca0d6876cb08c1e27465379514c7f0

**Review by ijjk — APPROVED** [review]
Change and test look good, thanks for the PR!

**Pull request merged**
