### PR TITLE
Fix `node_modules` detections

### LINKED ISSUE #19739: `next build` crashes when there is a `node_modules` folder somewhere in the absolute path of the app
# Bug report

## Describe the bug

The `next build` command crashes when the app is located under a `node_modules` folder or even a subfolder. Examples:

- `/tmp/test/node_modules/my-app`
- `/tmp/test/node_modules/foo/my-app`
- `/tmp/test/node_modules/foo/bar/my-app`

It crashes with this Webpack error:

```bash
➜  /tmp/test/node_modules/my-app git:(main) yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build  
Failed to compile.

./pages/_app.js 4:9
Module parse failed: Unexpected token (4:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| function MyApp({ Component, pageProps }) {
>   return <Component {...pageProps} />
| }
|


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/tmp/test/node_modules/my-app/node_modules/next/dist/build/index.js:15:918)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Apparently, Webpack is not able to find a suitable loader for JSX anymore.

## To Reproduce

```bash
mkdir -p /tmp/test/node_modules && cd /tmp/test/node_modules
npx create-next-app my-app
cd my-app
yarn build
```

## Expected behavior

Next.js should work normally, even if the app is located under a `node_modules` folder or subfolder.

## System information

- OS: Ubuntu 18.04
- Version of Next.js: 10.0.3 (also tested with 9.5.5 and 9.0.4: it seems that this bug always existed)
- Version of Node.js: 14.15.1 (also tested with 12.18.3)

## Additional context

This use case may seem very unusual but it happens when you want to embed a Next.js app inside an NPM package that you want to distribute.
I agree this is not conventional, but it helps me a lot to use Next.js under the hood in my [Log4brains project](https://github.com/thomvaill/log4brains/) to provide the local preview web UI and the static site generation features.

Of course, I totally understand that this bug will likely not have a high priority.
But it would really help me if someone could at least provide me some hints on what could possibly cause this issue? And a possible workaround?
I've already checked the generated Webpack configs, which seem to be OK. But I don't know where to further look at now :(

Thanks a lot! 🙏

### PR DESCRIPTION
**Pull request by thomvaill**
This PR fixes https://github.com/vercel/next.js/issues/19739
The example given in the issue now passes.

As this is my first PR, please forgive me for these (maybe) stupid questions:

- I ran some integrations tests locally, they pass. But it takes way too much time to run them all locally with `yarn testheadless`. Am doing something wrong?
- Do I have to create a new integration test for this specific case? If so, what is the best test example to start from?

Thanks a lot! 🙏

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.9s | ⚠️ +231ms |
| nodeModulesSize | 82.3 MB | 82.3 MB | ⚠️ +1.1 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.986 | 1.963 | -0.02 |
| / avg req/sec | 1258.91 | 1273.28 | +14.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.292 | 1.248 | -0.04 |
| /error-in-render avg req/sec | 1934.6 | 2003.78 | +69.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3c9ff84..1d7c.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12.1s | ⚠️ +228ms |
| nodeModulesSize | 82.3 MB | 82.3 MB | ⚠️ +1.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3c9ff84..1d7c.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _error.js | 997 kB | 997 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 998 kB | 998 kB | ✓ |
| link.js | 1.05 MB | 1.05 MB | ✓ |
| routerDirect.js | 1.04 MB | 1.04 MB | ✓ |
| withRouter.js | 1.04 MB | 1.04 MB | ✓ |
| Overall change | 5.14 MB | 5.14 MB | ✓ |

</details>

</details>
Commit: 7c1a8a9ccaec83fb51f82b9d29b4824ac56da298

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1068300f2da6dbcaf27b838e64423cc5ddbe71d9

**test/integration/dist-dir/test/index.test.js** 
- distDir > should handle null/undefined distDir

<details>
<summary>Expand output</summary>

  ● distDir › should handle null/undefined distDir

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 88

      63 |     await fs.writeFile(nextConfig, origNextConfig)
      64 | 
    > 65 |     expect(stderr.length).toBe(0)
         |                           ^
      66 |   })
      67 | })
      68 | 

      at Object.<anonymous> (integration/dist-dir/test/index.test.js:65:27)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| buildDuration | 9.3s | 9s | -263ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +1.1 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.804 | 1.77 | -0.03 |
| / avg req/sec | 1385.64 | 1412.46 | +26.82 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.175 | 1.123 | -0.05 |
| /error-in-render avg req/sec | 2127.62 | 2226.75 | +99.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11s | ⚠️ +74ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +1.1 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.2s | ⚠️ +98ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +1.1 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.819 | 1.787 | -0.03 |
| / avg req/sec | 1374.1 | 1398.74 | +24.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.36 | 1.176 | -0.18 |
| /error-in-render avg req/sec | 1837.63 | 2126.48 | +288.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| 597-c48889ef..1870.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | thomvaill/next.js fix-node-modules-detections | Change |
| - | - | - | - |
| index.html gzip | 588 B | 588 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "G_m5onicO0Sh0L5s6Dg-Z",
+        "buildId": "w6GO5WO7c1w0yX2w3Xseb",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_buildManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_ssgManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "G_m5onicO0Sh0L5s6Dg-Z",
+        "buildId": "w6GO5WO7c1w0yX2w3Xseb",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_buildManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_ssgManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "G_m5onicO0Sh0L5s6Dg-Z",
+        "buildId": "w6GO5WO7c1w0yX2w3Xseb",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_buildManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/G_m5onicO0Sh0L5s6Dg-Z/_ssgManifest.js"
+      src="/_next/static/w6GO5WO7c1w0yX2w3Xseb/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 1068300f2da6dbcaf27b838e64423cc5ddbe71d9

**Review by timneutkens — CHANGES_REQUESTED** [review]
This will need an integration test indeed. You'll probably want to use `test/integration/image-component` as a starting point for adding tests as it runs tests in both development and production mode.

**Comment by timneutkens** [comment]
Going to close this PR as it's missing integration tests. Happy to review when tests are added 👍

**Pull request closed without merging**
