### PR TITLE
Remove `binary-cache` check in `id: binary-cache`

### PR DESCRIPTION
**Pull request by matamatanot**
```
>> npx node-actionlint
.github/workflows/build_test_deploy.yml:965:17 property "binary-cache" is not defined in object type {docs-change: {conclusion: string; outcome: string; outputs: {string => string}}}
```

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| buildDuration | 17.5s | 16.4s | -1s |
| buildDurationCached | 3.5s | 3.6s | ⚠️ +42ms |
| nodeModulesSize | 294 MB | 294 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.66 | 2.597 | -0.06 |
| / avg req/sec | 939.89 | 962.56 | +22.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.298 | 1.244 | -0.05 |
| /error-in-render avg req/sec | 1926.67 | 2009.24 | +82.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| buildDuration | 18.1s | 17.7s | -368ms |
| buildDurationCached | 3.7s | 3.6s | -105ms |
| nodeModulesSize | 294 MB | 294 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.834 | 2.623 | -0.21 |
| / avg req/sec | 882.14 | 953.18 | +71.04 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.339 | 1.251 | -0.09 |
| /error-in-render avg req/sec | 1867.25 | 1997.9 | +130.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| index.html gzip | 535 B | 535 B | ✓ |
| link.html gzip | 548 B | 548 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 6a6e3dfcf364d50c07a3b2eae19debe6a631543e

**Review by ijjk — CHANGES_REQUESTED** [review]
Instead of removing this check can we ensure the `binary-cache` step from other jobs is present on this one as well?

**Comment by matamatanot** [comment]
@ijjk 
Checking for binary-cache within id:binary-cache is meaningless. It is necessary that id:binary-cache is declared in the previous step.

**Comment by ijjk** [comment]
Ah I see, was looking at the wrong step locally this change makes sense 👍

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| buildDuration | 20s | 19.5s | -519ms |
| buildDurationCached | 3.9s | 4.2s | ⚠️ +266ms |
| nodeModulesSize | 293 MB | 293 MB | -1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.953 | 3.04 | ⚠️ +0.09 |
| / avg req/sec | 846.55 | 822.31 | ⚠️ -24.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.456 | 1.438 | -0.02 |
| /error-in-render avg req/sec | 1716.89 | 1739.1 | +22.21 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| buildDuration | 21.7s | 21.8s | ⚠️ +118ms |
| buildDurationCached | 4.3s | 4.4s | ⚠️ +108ms |
| nodeModulesSize | 293 MB | 293 MB | -1 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.119 | 3.177 | ⚠️ +0.06 |
| / avg req/sec | 801.63 | 786.79 | ⚠️ -14.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.466 | 1.523 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1705.4 | 1640.97 | ⚠️ -64.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | matamatanot/next.js remove-unnecessary-binary-cache-check | Change |
| - | - | - | - |
| index.html gzip | 535 B | 535 B | ✓ |
| link.html gzip | 548 B | 548 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 9f1d30387b4b110d850cca59578cb7a2f0c098c6

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9f1d30387b4b110d850cca59578cb7a2f0c098c6

**test/integration/create-next-app/index.test.js** 
- create next app > should support typescript flag
- create next app > should fall back to default template
- create next app > should allow an example named default
- create next app > should ask the user for a name for the project if none supplied

<details>
<summary>Expand output</summary>

  ● create next app › should support typescript flag

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       99 |   })
      100 |
    > 101 |   it('should support typescript flag', async () => {
          |   ^
      102 |     await usingTempDir(async (cwd) => {
      103 |       const projectName = 'typescript'
      104 |       const res = await run([projectName, '--typescript'], { cwd })

      at integration/create-next-app/index.test.js:101:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should fall back to default template

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      238 |   // stdin is piped instead of inherited on windows
      239 |   if (process.platform !== 'win32') {
    > 240 |     it('should fall back to default template', async () => {
          |     ^
      241 |       await usingTempDir(async (cwd) => {
      242 |         const projectName = 'fail-example'
      243 |         const res = await run(

      at integration/create-next-app/index.test.js:240:5
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should allow an example named default

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      263 |   }
      264 |
    > 265 |   it('should allow an example named default', async () => {
          |   ^
      266 |     await usingTempDir(async (cwd) => {
      267 |       const projectName = 'default-example'
      268 |       const res = await run([projectName, '--example', 'default'], { cwd })

      at integration/create-next-app/index.test.js:265:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should ask the user for a name for the project if none supplied

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      330 |   })
      331 |
    > 332 |   it('should ask the user for a name for the project if none supplied', async () => {
          |   ^
      333 |     await usingTempDir(async (cwd) => {
      334 |       const projectName = 'test-project'
      335 |       const res = await run([], { cwd, input: `${projectName}\n` })

      at integration/create-next-app/index.test.js:332:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

</details>

**Pull request merged**
