### PR TITLE
Rename withRoute to withRouter to be consistent

### PR DESCRIPTION
**Pull request by brikou**

### CODE REVIEW

**Comment by timneutkens** [comment]
We talked about this in the PR. It doesn't expose the router, only the current route. So ihmo it should be named after that 😄

**Comment by brikou** [comment]
@timneutkens so to be really `withRouter` should be rename to `withRoute` and `router` props to `route`.

I guess it is too late :) but WDYT

**Comment by brikou** [comment]
Anyway not a big deal, feel free to close this PR :)

**Comment by timneutkens** [comment]
Interesting, arunoda deviced to call it with-router 👌 fine either way 😄

**Comment by arunoda** [comment]
Thanks @brikou 

@timneutkens Actually, there's no reason not to expose the full router API. In that way, a user can simply use the router instance comes with props to do anything.

**Comment by timneutkens** [comment]
@arunoda okay 👌

**Pull request merged**
