### PR TITLE
Do not clear the console

### LINKED ISSUE #6525: Disable stdout clearing
(There may be a way to do this currently, but after asking a few times on Spectrum and looking through the changes for adding Webpackbar I haven't found anything)

## Is your feature request related to a problem? Please describe.
When running Next in something like docker-compose the refreshing output constantly clears and mangles the log output.

## Describe the solution you'd like
I'd like a way to disable this so that log output is just a stream and not constantly rerendered.

Edit: This includes local development as well.

### PR DESCRIPTION
**Pull request by justinmchase**
Its common to run in docker where multiple processes are sharing the same stdout, it can cause a loss of important logs of other processes to clear the console.

Fixes #6525

### CODE REVIEW

**Comment by timneutkens** [comment]
@timer is going to review this.

**Comment by Timer** [comment]
@justinmchase thanks for the PR! Could you please adjust the output to not re-emit if the state hasn't changed? You may need to do a deep comparison for this.

**Review by Timer — CHANGES_REQUESTED** [review]
@justinmchase thanks for the PR! Could you please adjust the output to not re-emit if the state hasn't changed? You may need to do a deep comparison for this.

**Comment by justinmchase** [comment]
@Timer is that a different feature?

Is there a ticket for it because I'm not sure how to duplicate the condition you are referring to.

**Comment by justinmchase** [comment]
@Timer After looking into it some I believe what you are asking for is out of scope for this change. It sounds like an unrelated feature, which appears to be a code change in a different library (e.g. redux) as that is where the store that is emitting the change events that triggers this output is located.

This PR simply addresses the issue where the cli for next.js is sending console clear signals when it should not be. It can end up clearing important output from other processes sharing the same stdout stream.

**Comment by Timer** [comment]
> This PR simply addresses the issue where the cli for next.js is sending console clear signals when it should not be.

Next.js is behaving as it should in this scenario. We are clearing the console intentionally -- the old output is supposed to be erased.

If we want the old output to stay around, the output deduping must be solved before we can remove this.

---

> It can end up clearing important output from other processes sharing the same stdout stream.

From this POV, I would consider this a bug in how we are clearing output. In which case, we shouldn't disable clearing output, but fix it instead.

**Comment by justinmchase** [comment]
> We are clearing the console intentionally -- the old output is supposed to be erased.

I know this was intentional but with all due respect it is problematic and very impolite as it causes critical output from other processes to be erased as well. There is no good reason to erase old output, it is a misguided cli aesthetic.

The console already supports clearing behavior automatically, you just print more and the old information scrolls up above the fold. The terminal will buffer and eventually it will be erased automatically. Please don't manually erase information, unless you are actually running as an interactive mainframe terminal or app such as vi.

The output is not duplicated and there is no need to address deduping because it is not duplicated. The logged events happened multiple times and that is important information. Please don't manage the console like this, simply print out pertinent information and the console will scroll as its designed to do as new input streams in.

**Comment by SpectralKH** [comment]
@justinmchase I can see clearing the console being fine if all you're doing is running Next. The problem is when you have other stuff that Next deletes. If it's an option to disable the clearing, that would at least work.

**Comment by justinmchase** [comment]
@SpectralKH I agree an option would be fine, but imo, not clearing at all is more correct and simpler. If someone were to add the `--no-clear` flag I would certainly use it.

**Comment by justinmchase** [comment]
Ok, @Timer I was hoping to avoid doing this because its kind of a hot mess of console.log's everywhere but I did a little deduping and pretty formatting.

I'm not at all invested in the formatting if you say "make it look like this" I will, I don't really care. But here is a visual of a couple scenarios with the code as it exists today:

# Clean Startup
Screen Shot 2019-03-26 at 4 20 43 PM

# Initial Load
Screen Shot 2019-03-26 at 4 21 10 PM

# Syntax Error
Screen Shot 2019-03-26 at 4 21 36 PM

# Runtime Error
Screen Shot 2019-03-26 at 4 22 02 PM

**Comment by justinmchase** [comment]
In an ideal world, there would not be any `console.log/error` calls throughout the code but instead it would emit structured events or update its own state such that a CLI or other interface would be able to visualize, that's a pretty big refactor though but just something to think about for the future.

**Comment by justinmchase** [comment]
I can't really tell whats going on with these errors but as far as I can tell, they're not related to the changes made.

Do you know, are these intermittent failures? Or coming from the main branch or are my changes literally causing this issue? As far as I know the only changes made were to print out different things to the console only and no functional changes were made at all.

**Comment by justinmchase** [comment]
@Timer Hey, can we get some escalation on this? I would be happy to make more changes with some feedback.

This issue is becoming a real problem, I have to try all of my test scenarios multiple times as next.js is continually erasing all of my debug output.

**Comment by Timer** [comment]
@justinmchase Sorry, we're really busy right now. I'll look at fixing the tests and merging this tomorrow.

Thanks for the ping!

**Comment by justinmchase** [comment]
I understand! Thanks for bearing with me. Let me know if there's anything more I can do.

**Review by Timer — APPROVED** [review]

**Comment by Timer** [comment]
Thanks @justinmchase!

**Comment by timneutkens** [comment]
Amazing work @justinmchase 😲

**Comment by maerzhase** [comment]
sorry for pooping the party but: How do you disable the clearing? I can't find any documentation on it... thanks in advance.

**Comment by timneutkens** [comment]
Try out `next@canary`

**Comment by justinmchase** [comment]
@maerzhase I believe in the latest versions its simple always disabled. For older versions, there is no known way sadly.

**Pull request merged**
