### PR TITLE
Updated/Migrated next-css example to the  App Router

### PR DESCRIPTION
**Pull request by Shruthireddy04**
This PR updates the next-css example to use the App Router. Here are the changes that have been made:

Renamed the "pages" folder to "app" folder.
Updated the file index.tsx to page.tsx to align with App Router.
Updated the file _app.tsx to layout.tsx to align with App Router.
Updated the  components folder to align with App Router and made components folder private. 
Updated package.json to use the latest version.

cc: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5576c85a499452afad2ac5baabcb93c7da91ab85

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 5576c85a499452afad2ac5baabcb93c7da91ab85

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
