### PR TITLE
Fix non-concurrent function _document

### LINKED ISSUE #31593: 12.0.4 breaks metatags
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.17.4

### What browser are you using?

Brave (Chromium)

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel (next build)

### Describe the Bug

After updating NextJS to v `12.0.4`, my dynamic metatags have stopped working.

This is how my metatags look after updating:
Shot 2021-11-18 at 18-27-36@2x

### Expected Behavior

My website metatags should look like this:
Shot 2021-11-18 at 18-26-55@2x

### To Reproduce

Here's my repository with the last working commit: [jahirfiquitiva/jahir.dev@90bdc2e](https://github.com/jahirfiquitiva/jahir.dev/tree/90bdc2e7e0f84e9571fe49b007aea8c97f297cb9)

- Last working build (on Vercel): https://vercel.com/jahirfiquitiva/website/8dshERTVaVAZ46ErpHmi95meZA5M
- Last working build url: https://website-h26vjkuvu-jahirfiquitiva.vercel.app/

This is the same repository with the commit that broke metatags: [jahirfiquitiva/jahir.dev@2478454](https://github.com/jahirfiquitiva/jahir.dev/tree/2478454002a295baf997b5c8bf67c9f9dbf4c54e)

- First build where metatags stopped working (on Vercel): https://vercel.com/jahirfiquitiva/website/5hoTrJXKXK5Dv2CS81Eno2Fe3N1s
- First not-working build url: https://website-43n1fdd3v-jahirfiquitiva.vercel.app/

I am using [metatags.io](https://metatags.io/) to preview the sites metatags.

I can confirm it was due to NextJS 12.0.4, because this commmit reverting to 12.0.3 makes metatags work as expected again:

- Commit: https://github.com/jahirfiquitiva/jahir.dev/commit/1cb28891e4077afccebcc8173b194fbbcaf31fbe
- Vercel build: https://vercel.com/jahirfiquitiva/website/5obW37bWwMbbQDsmPRRWikJ1adfa
- Build url: https://website-lmobi22a8-jahirfiquitiva.vercel.app/

### PR DESCRIPTION
**Pull request by ijjk**
This ensures functional `_document` is rendered correctly when not using concurrent mode. 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

Fixes: https://github.com/vercel/next.js/issues/31593
x-ref: https://github.com/vercel/next.js/pull/30156

### CODE REVIEW

**Review by shuding — DISMISSED** [review]

**Review by pacocoursey — DISMISSED** [review]

**Review by huozhi — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: d967c9920915feab5cfa14c225aff029da038327

**test/integration/document-functional-render-prop/tests/index.test.js** 
- Functional Custom Document > development mode > supports render props

<details>
<summary>Expand output</summary>

  ● Functional Custom Document › development mode › supports render props

    expect(received).toMatch(expected)

    Expected pattern: /<span>from render prop<\/span>/
    Received string:  "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1637346028679\"></script><script src=\"/_next/static/chunks/webpack.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/chunks/main.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/index.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1637346028679\" defer=\"\"></script><script src=\"/_next/static/development/_middlewareManifest.js?ts=1637346028679\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\" data-reactroot=\"\"><span></span></div><script src=\"/_next/static/chunks/react-refresh.js?ts=1637346028679\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/\",\"query\":{},\"buildId\":\"development\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      15 |     })
      16 |
    > 17 |     afterAll(() => killApp(app))
         |                          ^
      18 |
      19 |     it('supports render props', async () => {
      20 |       const html = await renderViaHTTP(appPort, '/')

      at Object.<anonymous> (integration/document-functional-render-prop/tests/index.test.js:17:26)

</details>

**Review by shuding — DISMISSED** [review]

**Review by timneutkens — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 491dcf5de12c3c3c966d78cebfe36b89520f3410

**test/integration/document-functional-render-prop/tests/index.test.js** 
- Functional Custom Document > development mode > supports render props

<details>
<summary>Expand output</summary>

  ● Functional Custom Document › development mode › supports render props

    expect(received).toMatch(expected)

    Expected pattern: /<span>from render prop<\/span>/
    Received string:  "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1637346903412\"></script><script src=\"/_next/static/chunks/webpack.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/chunks/main.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/index.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1637346903412\" defer=\"\"></script><script src=\"/_next/static/development/_middlewareManifest.js?ts=1637346903412\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\" data-reactroot=\"\"><span></span></div><script src=\"/_next/static/chunks/react-refresh.js?ts=1637346903412\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/\",\"query\":{},\"buildId\":\"development\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script></body></html>"

      15 |     })
      16 |
    > 17 |     afterAll(() => killApp(app))
         |                          ^
      18 |
      19 |     it('supports render props', async () => {
      20 |       const html = await renderViaHTTP(appPort, '/')

      at Object.<anonymous> (integration/document-functional-render-prop/tests/index.test.js:17:26)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| buildDuration | 20.8s | 20.6s | -150ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +67ms |
| nodeModulesSize | 339 MB | 339 MB | ⚠️ +619 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.381 | 3.35 | -0.03 |
| / avg req/sec | 739.51 | 746.22 | +6.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.604 | 1.533 | -0.07 |
| /error-in-render avg req/sec | 1558.69 | 1630.72 | +72.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| buildDuration | 21.8s | 22.2s | ⚠️ +449ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +89ms |
| nodeModulesSize | 339 MB | 339 MB | ⚠️ +619 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.429 | 3.407 | -0.02 |
| / avg req/sec | 729.01 | 733.69 | +4.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.658 | 1.628 | -0.03 |
| /error-in-render avg req/sec | 1507.46 | 1535.26 | +27.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 491dcf5de12c3c3c966d78cebfe36b89520f3410

**Review by huozhi — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| buildDuration | 23.2s | 23.7s | ⚠️ +518ms |
| buildDurationCached | 4.4s | 4.6s | ⚠️ +173ms |
| nodeModulesSize | 339 MB | 339 MB | ⚠️ +1.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.925 | 4.018 | ⚠️ +0.09 |
| / avg req/sec | 637.01 | 622.21 | ⚠️ -14.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.001 | 2.098 | ⚠️ +0.1 |
| /error-in-render avg req/sec | 1249.27 | 1191.49 | ⚠️ -57.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| buildDuration | 24.8s | 25.1s | ⚠️ +298ms |
| buildDurationCached | 4.5s | 4.5s | -3ms |
| nodeModulesSize | 339 MB | 339 MB | ⚠️ +1.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.007 | 3.897 | -0.11 |
| / avg req/sec | 623.86 | 641.45 | +17.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.064 | 2.055 | -0.01 |
| /error-in-render avg req/sec | 1211.17 | 1216.5 | +5.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/non-concurrent-document | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 3c256defa4d7ea7fcb339cc8827b0cbd0caaff88

**Pull request merged**
