### PR TITLE
FIX: typo in 13-internationalization.mdx

### PR DESCRIPTION
**Pull request by hydRAnger**
As our intention is:

```markdown
  // e.g. incoming request is /products
  // The new URL is now /en-US/products
```
So it seems to be a typo, right?

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 98e57cf99fe1c4016a01e85ead51f4386659aa54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 98e57cf99fe1c4016a01e85ead51f4386659aa54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 98e57cf99fe1c4016a01e85ead51f4386659aa54

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
I believe this is correct, per the linked example.

**Comment by hydRAnger** [comment]
> I believe this is correct, per the linked example.

@leerob  

Do you mean that ```locale```'s more intuitive value is ```en-US/```, not ```en-US```?

**Pull request closed without merging**
