### PR TITLE
Removed duplicated cn function declaration from lib dir

### LINKED ISSUE #73942: Supabase example has duplicate utils for cn.ts
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
bunx next info
/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 19:00:33 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8122
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```
```


### Which example does this report relate to?

with-supabase

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

There is duplication of code for the classNames utility. It currently exists in 2 places with this example. Both in `lib/utils.ts` and in `utils/cn.ts` when creating a new project using `bunx create-next-app -e with-supabase`.

### Expected Behavior

It should only be declared in one location.

### To Reproduce

Create a new project using `bunx create-next-app -e with-supabase` and check the 2 locations shared in the description.

### PR DESCRIPTION
**Pull request by damiensedgwick**
This pull request removes duplication of a utility function within the `with-supabase` example as mentioned in the following issue  #73942 - I removed the duplicated code from the `utils` directory as when shadcn installs a new component, that component will look for the helper function in `lib/utils.ts` and forcing users to update every component after installation or modify any config files for shadcn seems like a worse DX.

- Fixes https://github.com/vercel/next.js/issues/73942

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: cc16cfb80ed4e1a043f001460abd626f80fc0358

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by damiensedgwick** [comment]
@samcx Hey, here is the pr as discussed. it feels a little wrong leaving an empty `lib` directory but given the approach of using a Data Access Layer going forward, I think it makes sense. I can always add a placeholder file or `README.md` in there if we feel like it would be beneficial?

**Comment by samcx** [comment]
@damiensedgwick Can you make sure to update the path imports? Also seeing an issue with the Tailwind CSS.

You can test this locally with `pnpm next-with-deps examples/with-supabase` or manually start it up locally with changes via Create Next App.

**Comment by damiensedgwick** [comment]
> @damiensedgwick Can you make sure to update the path imports? Also seeing an issue with the Tailwind CSS.
> 
> You can test this locally with `pnpm next-with-deps examples/with-supabase` or manually start it up locally with changes via Create Next App.

Fixed the issue with component imports. I actually realised that I removed the wrong instance at first so that has been corrected.

Regarding tailwind, this is a weird error because I have not touched anything Tailwind related but also, the error I am getting

> Syntax error: /Users/damien/.personal/next.js/examples/with-supabase/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.

Does not make sense because the class is within a layer directive as we can see here:

```css
@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
```

So I am not entirely sure what you would like me to do here. This is exactly how the css file is setup within every project using shad that I have seen.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
