### PR TITLE
Prepare for webpack 5 upgrade

### PR DESCRIPTION
**Pull request by timneutkens**
Tweaked the config that can already be updated a bit.

### CODE REVIEW

**Review by Timer — APPROVED** [review]
LGTM if tests pass

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from red to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from blue to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      271 | export async function killApp(instance) {
      272 |   await new Promise((resolve, reject) => {
    > 273 |     treeKill(instance.pid, (err) => {
          |                       ^
      274 |       if (err) {
      275 |         if (
      276 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:273:23
      at killApp (lib/next-test-utils.js:272:9)
      at integration/css-client-nav/test/index.test.js:190:11

</details>

**Comment by ijjk** [comment]
## Failing test suites 

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from red to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from blue to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      271 | export async function killApp(instance) {
      272 |   await new Promise((resolve, reject) => {
    > 273 |     treeKill(instance.pid, (err) => {
          |                       ^
      274 |       if (err) {
      275 |         if (
      276 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:273:23
      at killApp (lib/next-test-utils.js:272:9)
      at integration/css-client-nav/test/index.test.js:190:11

</details>

**Review by Timer — CHANGES_REQUESTED** [review]
Tests are not happy!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.3s | ⚠️ +108ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +2.02 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.96 | 2.007 | ⚠️ +0.05 |
| / avg req/sec | 1275.73 | 1245.58 | -30.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.129 | 1.15 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2214.97 | 2174.27 | -40.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| index.html gzip | 953 B | 953 B | ✓ |
| link.html gzip | 960 B | 960 B | ✓ |
| withRouter.html gzip | 947 B | 947 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.3s | -103ms |
| nodeModulesSize | 67 MB | 67 MB | ⚠️ +2.02 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4dd5.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/webpack-5-prep | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 906 kB | 906 kB | ✓ |
| withRouter.js | 906 kB | 906 kB | ✓ |
| Overall change | 4.48 MB | 4.48 MB | ✓ |

</details>

</details>

**Review by Timer — APPROVED** [review]

**Pull request merged**
