### PR TITLE
Speed up build && remove ignore plugin

### PR DESCRIPTION
**Pull request by berezovyy**
During the review of the build flow I have noticed that ignorePlugin from webpack take a lot of time:

image

And I think there are no needs for this two ignore plugins calls, so I propose to remove them in case to speed up build time:

1)`/(precomputed)/, /node_modules.+(elliptic)/` - It was added almost 1 year ago and I think it was added to prevent adding elliptic module to prod build. This `elliptic` is going from webpack so there are no ways when it will be added to build files. https://github.com/zeit/next.js/blame/202ceca1af1baeab5f61d2812ec48b019c80919d/server/build/webpack.js#L108

2)`/prop-types-exact/.test(resource)` - there is only one component where in next.js used `prop-types-exact` - in Link component. But it adds `prop-types-exact` only in dev mode. So as a result `prop-types-exact` skipped in prod version and it just waste time during the build trying to find this module. That's why I propose to remove it and allow to add it manually who is really needed it, because not all projects add this module.

After removing these rows, there is no increase of bundle size or something like this. Only speed up of build time. Here is a difference based on my project.
1) Before:
image
2)After: 
image

### CODE REVIEW

**Review by HaNdTriX — APPROVED** [review]
lgtm! Nice! Thanks! 

Waiting for @timneutkens to confirm, though.

**Comment by timneutkens** [comment]
Pretty sure removing prop-types-exact here will just put it back into the bundle, increasing bundle size by 10Kb

**Comment by berezovyy** [comment]
@timneutkens Sorry, just want to understand how it will be added to the bundle. There is only one place where it used - https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/link.js#L159
But it will be added only if `process.env.NODE_ENV === 'development'` - am I wrong?

**Comment by berezovyy** [comment]
First of all, thanks for the review @timneutkens !
I didn't see any changes with bundle size after removing ignorePlugins. The bundle sizes is the same. Also, I want to highlight few things:
1)It will not be added to the bundle even without ignore plugin because of this condition: https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/link.js#L155
2)  `prop-types-exact` weight ~1.5kb, it can't be 10kb.
image
(here I have manually included `prop-types-exact` to the bundle )

It will not increase bundle size.

Please, let me know if I miss something.

**Comment by berezovyy** [comment]
@tusbar all this dependencies is already in the bundle, so they will not be duplicated and they will not increase bundle size. From bundlephobia you can see that here will be used only `self` part(1.49kb).

The main point from @timneutkens why it's not merged if I understood correctly that it will increase bundle size bu 10kb. But that will not happen because of:
1)`prop-types-exact` will not load at all to the prod bundle because of the condition
2) even if `prop-types-exact` will be added to the bundle it will increase bundle only by 1kb.

My thought that reduce build time by 30% will be really cool. Especially if it's building in the cloud and take a lot of time.

To test if it's not increase bundle size you can do next:
1)Open hello world example(it contains <LInk> component)
2)Add webpack bundle analyzer
3)Clone current version of next.js
4)Build next.js
5)Create link
6)Build hello world example / change bundle size
7)Removed ignore plugin/build next.js
8)Again build hello world example / change bundle size

It will be the same. I have checked few times with my project and hello world.

**Comment by timneutkens** [comment]
I'm going to check this PR out in a bit, just to be 100% sure 🙏 I can believe your results though

**Comment by HaNdTriX** [comment]
I just ran these changes agains the size limit test from #5339.
I could not detect an increase of the bundle size (from the client perspective).

**Pull request merged**
