### PR TITLE
fix(next): `Metadata.openGraph` values not resolving basic values when `type` is set

### LINKED ISSUE #63415: OpenGraphMetadata type is weird
### Link to the code that reproduces this issue

https://github.com/lnuvy/opengraph-error

### To Reproduce

1. Cloning the above github project
2. Go to /post/[postId] page
3. You will see the `r.map is not a function` error

### Current vs. Expected behavior

Common emails in `type OpenGraphMetadata` are colliding when type is an "article"

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), Other (Deployed)

### Additional context

According to the type of built-in openGraph in next.js, when the openGraph type is "article", it doesn't matter if you put an email property.

However, `r.map is not a function` Error occurs due to emails properties when type is not a "website" type.

I found that the same problem occurred in the AWS deployment environment of the other project, as well as in the local area, and the page was not drawn.

I've built a similar environment on the link above. Thank you!

### PR DESCRIPTION
**Pull request by devjiwonchoi**
### What?

The string value of `Metadata.openGraph.emails` throws error:

```tsx
export const metadata = {
  openGraph: {
    type: 'article',
    emails: 'author@vercel.com',
  },
};
```

Error:

```sh
r.map is not a function
```

The type is:

```tsx
type OpenGraphMetadata = {
  // ...
  emails?: string | Array<string>
}
```

### Why?

Basic values such as `emails` and `phoneNumbers` were not included when `ogType` was set while resolving the values.

### How?

Include basic values when resolving the metadata.

Fixes #63415

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 320544e77dc1942f2c3a7fff0bf990fa3a20233d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 320544e77dc1942f2c3a7fff0bf990fa3a20233d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2c3f5b03a38a4d6432aa730369d6c8104559cda6

`TURBOPACK=1 pnpm test-start test/e2e/app-dir/not-found/multi-root-layout/index.test.ts` (turbopack)
- not-found-multi-root-layout > should render root not-found for uncaught routes

<details>
<summary>Expand output</summary>

  ● not-found-multi-root-layout › should render root not-found for uncaught routes

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      16 |   })
      17 |
    > 18 |   it('should render root not-found for uncaught routes', async () => {
         |   ^
      19 |     const browser = await next.browser('/404')
      20 |     expect(await browser.elementByCss('h1').text()).toBe('Root Not Found')
      21 |   })

      at it (e2e/app-dir/not-found/multi-root-layout/index.test.ts:18:3)
      at Object.describe (e2e/app-dir/not-found/multi-root-layout/index.test.ts:3:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]
Thanks!

**Pull request merged**
