### PR TITLE
Switch to .cjs PostCSS config

### PR DESCRIPTION
**Pull request by karlhorky**
### What?

Prevent confusing error messages when changing to `"type": "module"` in `package.json`

```
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./src/styles/index.css
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/my/repo/components/postcss.config.js from /path/to/my/repo/components/node_modules/next/dist/lib/find-config.js not supported.
Instead change the require of postcss.config.js in /path/to/my/repo/components/node_modules/next/dist/lib/find-config.js to a dynamic import() which is available in all CommonJS modules.
```

### Why?

Even though PostCSS itself [supports ESM and TypeScript configuration files](https://github.com/postcss/postcss-load-config/issues/230), Next.js itself does not (because of `next/lib/find-config`):

- https://github.com/vercel/next.js/issues/34448

### How?

By switching to `.cjs`, the config will stay recognized as CommonJS even after switching to `"type": "module"` in `package.json`

cc @balazsorban44

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d590e3f2904111b28162060add03311bb0330948

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by samcx** [comment]
@karlhorky I think we just need to handle the conflicts and we'll good to <picture data-single-emoji=":merged:" title=":merged:">:merged:</picture>

**Comment by karlhorky** [comment]
@samcx thanks for the review and approval! Just merged in canary, it should be ready for merging now.

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4a3723b40c02e2ad6584760555f11f9cc4fa9312

`TURBOPACK=1 pnpm test test/integration/create-next-app/templates-app.test.ts` (turbopack)
- create-next-app --app > should create Tailwind CSS appDir projects with --tailwind

<details>
<summary>Expand output</summary>

  ● create-next-app --app › should create Tailwind CSS appDir projects with --tailwind

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      80 |   for (const file of files) {
      81 |     try {
    > 82 |       expect(existsSync(resolve(projectRoot, file))).toBe(true)
         |                                                      ^
      83 |     } catch (err) {
      84 |       require('console').error(
      85 |         `missing expected file ${file}`,

      at toBe (integration/create-next-app/lib/utils.ts:82:54)
      at projectFilesShouldExist (integration/create-next-app/lib/utils.ts:132:3)
      at integration/create-next-app/templates-app.test.ts:183:30
      at useTempDir (lib/use-temp-dir.ts:24:5)
      at Object.<anonymous> (integration/create-next-app/templates-app.test.ts:163:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by karlhorky** [comment]
@samcx seems like one test is timing out here, is it easy to re-run it?

Or if it's an unrelated test flake, should the PR just be merged by hand?

**Comment by samcx** [comment]
@karlhorky I was looking into the test—could just be a flaky cache issue, so I was looking into it. No worries about merging the latest canary—I'm still taking a look!

**Comment by karlhorky** [comment]
@samcx thanks for the review and merge!

I can confirm that this is working with `create-next-app@canary` 🎉 :

```bash
➜  p mkdir aa
➜  p cd aa
➜  aa pnpm create next-app@canary . --app --no-eslint --no-src-dir --import-alias @/\* --tailwind

.../Library/pnpm/store/v3/tmp/dlx-77997  |   +1 +
.../Library/pnpm/store/v3/tmp/dlx-77997  | Progress: resolved 1, reused 0, downloaded 1, added 1, done
✔ Would you like to use TypeScript? … No / Yes
Creating a new Next.js app in /Users/k/p/aa.

Using pnpm.

Initializing project with template: app-tw


Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- postcss
- tailwindcss

Progress: resolved 85, reused 74, downloaded 0, added 0
Downloading registry.npmjs.org/next/14.2.0-canary.23: 20.49 MB/20.49 MB, done
Packages: +124
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/@next/swc-darwin-arm64/14.2.0-canary.23: 36.71 MB/36.71 MB, done
Progress: resolved 132, reused 121, downloaded 3, added 124, done

dependencies:
+ next 14.2.0-canary.23
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ postcss 8.4.35
+ tailwindcss 3.4.1

Done in 7.5s
Initialized a git repository.

Success! Created aa at /Users/k/p/aa

➜  aa git:(main) ls -al
total 120
drwxr-xr-x  14 k  staff    448 Mar 15 11:02 .
drwxr-xr-x  63 k  staff   2016 Mar 15 11:02 ..
drwxr-xr-x  12 k  staff    384 Mar 15 11:02 .git
-rw-r--r--   1 k  staff    391 Mar 15 11:02 .gitignore
-rw-r--r--   1 k  staff   1382 Mar 15 11:02 README.md
drwxr-xr-x   6 k  staff    192 Mar 15 11:02 app
-rw-r--r--   1 k  staff     73 Mar 15 11:02 jsconfig.json
-rw-r--r--   1 k  staff     92 Mar 15 11:02 next.config.mjs
drwxr-xr-x  10 k  staff    320 Mar 15 11:02 node_modules
-rw-r--r--   1 k  staff    358 Mar 15 11:02 package.json
-rw-r--r--   1 k  staff  32753 Mar 15 11:02 pnpm-lock.yaml
-rw-r--r--   1 k  staff     61 Mar 15 11:02 postcss.config.cjs
drwxr-xr-x   4 k  staff    128 Mar 15 11:02 public
-rw-r--r--   1 k  staff    469 Mar 15 11:02 tailwind.config.js

➜  aa git:(main) pnpm dev

> aa@0.1.0 dev /Users/k/p/aa
> next dev

   ▲ Next.js 14.2.0-canary.23
   - Local:        http://localhost:3000

 ✓ Ready in 2.4s
 ○ Compiling / ...
 ✓ Compiled / in 3.2s (523 modules)
```

**Comment by samcx** [comment]
@karlhorky It would in the next stable patch release → `14.1.4`!

**Comment by karlhorky** [comment]
Nice, thanks!

Because @phanect added ESM support in https://github.com/vercel/next.js/pull/63109, I have opened another PR with almost identical changes to switch to a proper ESM config with `.mjs` extension:

- https://github.com/vercel/next.js/pull/63380

**Pull request merged**
