### PR TITLE
fix node externals resolving

### PR DESCRIPTION
**Pull request by sokra**
### What?

Various fixes in handling of externals in node.js

* add extensions to builtin externals to allow node.js ESM to work
* improve the auto-externals logic to detect more edge cases
* prepare for `esmExternals` support, but that's blocked by client manifest missing the async flag
* currently only `esmExternals: false` is supported

### Turbopack Changes

* https://github.com/vercel/turbo/pull/6531 
* https://github.com/vercel/turbo/pull/6530

### CODE REVIEW

**Review by timneutkens — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.6s | N/A |
| buildDurationCached | 6s | 6.7s | ⚠️ +670ms |
| nodeModulesSize | 175 MB | 175 MB | ✓ |
| nextStartRea..uration (ms) | 398ms | 400ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| 199-HASH.js gzip | 30.4 kB | 30.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.2 kB | 53.2 kB | ✓ |
| 494.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.5 kB | 45.5 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 33 kB | 33 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.9 kB | 98.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| _app-HASH.js gzip | 205 B | 205 B | ✓ |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 505 B | 507 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.59 kB | 2.59 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 259 B | N/A |
| head-HASH.js gzip | 348 B | 347 B | N/A |
| hooks-HASH.js gzip | 369 B | 368 B | N/A |
| image-HASH.js gzip | 4.38 kB | 4.38 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.71 kB | 2.7 kB | N/A |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 319 B | 320 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 885 B | 885 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| index.html gzip | 529 B | 526 B | N/A |
| link.html gzip | 542 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| edge-ssr.js gzip | 96.8 kB | 96.8 kB | N/A |
| page.js gzip | 151 kB | 151 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 626 B | N/A |
| middleware-r..fest.js gzip | 148 B | 151 B | N/A |
| middleware.js gzip | 24.8 kB | 24.8 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/fix-node-externals | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 165 kB | 165 kB | ✓ |
| app-page-exp..prod.js gzip | 92.2 kB | 92.2 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page-tur..prod.js gzip | 87.7 kB | 87.7 kB | ✓ |
| app-page.run...dev.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run..prod.js gzip | 87 kB | 87 kB | ✓ |
| app-route-ex...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route-ex..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16.4 kB | 16.4 kB | ✓ |
| app-route-tu..prod.js gzip | 16 kB | 16 kB | ✓ |
| app-route.ru...dev.js gzip | 22.9 kB | 22.9 kB | ✓ |
| app-route.ru..prod.js gzip | 16 kB | 16 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 48.5 kB | 48.5 kB | ✓ |
| Overall change | 913 kB | 913 kB | ✓ |

</details>

</details>
Commit: 34896be6fdaf446c5a893ba02a559d6622320f1b

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 34896be6fdaf446c5a893ba02a559d6622320f1b

`pnpm test-dev test/e2e/getserversideprops/test/index.test.ts` 
- getServerSideProps > should navigate between pages successfully
- getServerSideProps > should allow POST request for getServerSideProps page
- getServerSideProps > should SSR normal page correctly
- getServerSideProps > should have gssp in __NEXT_DATA__
- getServerSideProps > should navigate to a normal page and back
- getServerSideProps > should pass query for data request on navigation
- getServerSideProps > should reload page on failed data request
- getServerSideProps > should dedupe server data requests
- getServerSideProps > should show error for invalid JSON returned from getStaticProps on CST

<details>
<summary>Expand output</summary>

  ● getServerSideProps › should navigate between pages successfully

    expect(received).toMatch(expected)

    Expected pattern: /hello.*?world/
    Received string:  ""

      211 |     const browser = await webdriver(next.url, '/')
      212 |     let text = await browser.elementByCss('p').text()
    > 213 |     expect(text).toMatch(/hello.*?world/)
          |                  ^
      214 |
      215 |     // hydration
      216 |     await waitFor(2500)

      at Object.toMatch (e2e/getserversideprops/test/index.test.ts:213:18)

  ● getServerSideProps › should allow POST request for getServerSideProps page

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      295 |       method: 'POST',
      296 |     })
    > 297 |     expect(res.status).toBe(200)
          |                        ^
      298 |     expect(await res.text()).toMatch(/hello.*?world/)
      299 |   })
      300 |

      at Object.toBe (e2e/getserversideprops/test/index.test.ts:297:24)

  ● getServerSideProps › should SSR normal page correctly

    expect(received).toMatch(expected)

    Expected pattern: /hello.*?world/
    Received string:  "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script src=\"/_next/static/chunks/0c25d_next_6d40bd._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/c8460_react_7630c8._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/4e99c_react-dom_cjs_react-dom_development_c0b264.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/4e99c_react-dom_55c180._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/node_modules__pnpm_f68e6b._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Broot%20of%20the%20server%5D__b4543c._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/0c25d_next_dist_pages_17744e._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_be8247._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_7fc694._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/0c25d_next_d00b73._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/c8460_react_5333d4._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Broot%20of%20the%20server%5D__45a3e3._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/0c25d_next_dist_pages_1e73a3._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_82d504._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/%5Bnext%5D_entry_page-loader_ts_13f380._.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_error.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1699357324234\" defer=\"\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1699357324234\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"appProps\":{\"url\":\"/\",\"query\":{},\"pathname\":\"/_error\",\"asPath\":\"/\"},\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted\",\"stack\":\"Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted\\n    at Object.useRouter (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/client/router.js:146:15)\\n    at RouterComp (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/.next/server/chunks/_eb8954._.js:22:78)\\n    at renderWithHooks (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)\\n    at renderIndeterminateComponent (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5735:15)\\n    at renderElement (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)\\n    at renderNodeDestructiveImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)\\n    at renderNodeDestructive (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)\\n    at renderNode (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)\\n    at renderChildrenArray (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)\\n    at renderNodeDestructiveImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)\\n    at renderNodeDestructive (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)\\n    at renderContextProvider (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5924:3)\\n    at renderElement (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6021:11)\\n    at renderNodeDestructiveImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)\\n    at renderNodeDestructive (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)\\n    at retryTask (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)\\n    at performWork (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)\\n    at /tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12\\n    at scheduleWork (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)\\n    at startWork (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6903:3)\\n    at renderToStringImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6977:3)\\n    at Object.renderToString (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7065:10)\\n    at getServerSideProps (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/.next/server/chunks/_eb8954._.js:54:76)\\n    at /tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:250\\n    at /tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/lib/trace/tracer.js:131:36\\n    at NoopContextManager.with (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)\\n    at ContextAPI.with (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)\\n    at NoopTracer.startActiveSpan (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)\\n    at ProxyTracer.startActiveSpan (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)\\n    at /tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/lib/trace/tracer.js:120:103\\n    at NoopContextManager.with (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)\\n    at ContextAPI.with (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)\\n    at NextTracerImpl.trace (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/lib/trace/tracer.js:120:28)\\n    at e8 (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:149)\\n    at async doRender (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:1379:30)\\n    at async cacheEntry.responseCache.get.routeKind (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:1569:28)\\n    at async DevServer.renderToResponseWithComponentsImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:1477:28)\\n    at async DevServer.renderPageComponent (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:1833:24)\\n    at async DevServer.renderToResponseImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:1871:32)\\n    at async DevServer.pipeImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:901:25)\\n    at async NextNodeServer.handleCatchallRenderRequest (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/next-server.js:266:17)\\n    at async DevServer.handleRequestImpl (/tmp/next-install-90453b32e332974c7020ae3374f2a4b9919a865a81fff7c70788e0d7acc426c7/node_modules/.pnpm/file+..+next-repo-5d53eadb99e768059fed4b9be2d8e6777912f50d4c31d76ff0f1cc224d372712+packages+n_xxpjyi5nsxg6bnyhqaxrgqjccm/node_modules/next/dist/server/base-server.js:797:17)\"},\"gip\":true,\"appGip\":true,\"scriptLoader\":[]}</script></body></html>"

      357 |   it('should SSR normal page correctly', async () => {
      358 |     const html = await renderViaHTTP(next.url, '/')
    > 359 |     expect(html).toMatch(/hello.*?world/)
          |                  ^
      360 |   })
      361 |
      362 |   it('should SSR getServerSideProps page correctly', async () => {

      at Object.toMatch (e2e/getserversideprops/test/index.test.ts:359:18)

  ● getServerSideProps › should have gssp in __NEXT_DATA__

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: undefined

      381 |     const html = await renderViaHTTP(next.url, '/')
      382 |     const $ = cheerio.load(html)
    > 383 |     expect(JSON.parse($('#__NEXT_DATA__').text()).gssp).toBe(true)
          |                                                         ^
      384 |   })
      385 |
      386 |   it('should not have gssp in __NEXT_DATA__ for non-GSSP page', async () => {

      at Object.toBe (e2e/getserversideprops/test/index.test.ts:383:57)

  ● getServerSideProps › should navigate to a normal page and back

    expect(received).toMatch(expected)

    Expected pattern: /hello.*?world/
    Received string:  ""

      574 |     const browser = await webdriver(next.url, '/')
      575 |     let text = await browser.elementByCss('p').text()
    > 576 |     expect(text).toMatch(/hello.*?world/)
          |                  ^
      577 |
      578 |     await browser.elementByCss('#normal').click()
      579 |     await browser.waitForElementByCss('#normal-text')

      at Object.toMatch (e2e/getserversideprops/test/index.test.ts:576:18)

  ● getServerSideProps › should pass query for data request on navigation

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#something-query')
    ============================================================

      362 |     return this.chain(() => {
      363 |       return page
    > 364 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      365 |         .then(async (el) => {
      366 |           // it seems selenium waits longer and tests rely on this behavior
      367 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:364:10)
      at Object.<anonymous> (e2e/getserversideprops/test/index.test.ts:616:5)

  ● getServerSideProps › should reload page on failed data request

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#broken-post')
    ============================================================

      362 |     return this.chain(() => {
      363 |       return page
    > 364 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      365 |         .then(async (el) => {
      366 |           // it seems selenium waits longer and tests rely on this behavior
      367 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:364:10)
      at Object.<anonymous> (e2e/getserversideprops/test/index.test.ts:629:5)

  ● getServerSideProps › should dedupe server data requests

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#slow')
    ============================================================

      362 |     return this.chain(() => {
      363 |       return page
    > 364 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      365 |         .then(async (el) => {
      366 |           // it seems selenium waits longer and tests rely on this behavior
      367 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:364:10)

  ● getServerSideProps › should show error for invalid JSON returned from getStaticProps on CST

    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('#non-json')
    ============================================================

      362 |     return this.chain(() => {
      363 |       return page
    > 364 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      365 |         .then(async (el) => {
      366 |           // it seems selenium waits longer and tests rely on this behavior
      367 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:364:10)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by ForsakenHarmony — DISMISSED** [review]

**Comment by HofmannZ** [comment]
@sokra - What's blocking this PR from being merged? 🙂

**Comment by sokra** [comment]
> What's blocking this PR from being merged? 🙂

The CI doesn't like me...

**Review by timneutkens — DISMISSED** [review]

**Review by ForsakenHarmony — DISMISSED** [review]

**Review by ForsakenHarmony — DISMISSED** [review]

**Review by timneutkens — APPROVED** [review]

**Review by kwonoj — APPROVED** [review]

**Review by wbinnssmith — APPROVED** [review]

**Pull request merged**
