### PR TITLE
Fix bug in with-apollo example leading to cached lists being duplicated.

### LINKED ISSUE #19759: Bug: List items duplication in the with-Apollo example setup using GetStaticProps
# Bug report

## Describe the bug

The Apollo Client's cache arrays get filled with duplicated items when using the setup provided in `examples/with-Apollo`, leading to my website displaying lists with twice (or even 3, 4... etc) times each item (and getting the infamous react duplicated key error, obviously 🙂).

## To Reproduce

1. Implement the `examples/with-Apollo` setup in a project where the schema has an array of items (a Relay connection field for example).
2. On a Next.js page (Page 1), make an apollo `useQuery` fetch the list of items and display it.
3. Add a GetStaticProps to the page, following exactly the with-Apollo example
4. In another page of the project (Page 2), create a link navigating to this page.
5. Run the project, go to Page 2. Click the button that takes you to Page 1.
6. Navigate back to Page 2 with back arrow of your browser. Open your console.
7. Navigate forward to Page 1 again. See the duplicated items and error messages about duplicate keys in your console.
8. If you repeat this operation x times, you will see the items repeated x times.

```jsx
HOSTING_SEARCH_HOSTING_PROVIDERS = gql`
query HostingSearchHostingProviders {
    bookableHostingProviders {
      edges {
        node {
          id
          name
        }
      }
    }

const Page = ()=> {
  const { data, error, loading } = useQuery(HOSTING_SEARCH_HOSTING_PROVIDERS);

  return <>{data.bookableHostingProviders.edges.map(edge => <div key=>{edge.node.name} {edge.node.id}</div>)}</>
}

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: HOSTING_SEARCH_HOSTING_PROVIDERS,
  });

  return addApolloState(apolloClient, {
    props: {},
    revalidate: 20,
  });
};

export default Page
```

## Expected behavior

The elements of the array are not duplicated and I don't see duplicated key error messages in my console.

## Screenshots

image

## System information

- OS: macOS
- Browser: all
- Version of Next.js: 10.0.0
- Version of Node.js: 12.16.2
- Deployment: Vercel and `next dev`

## Likely solution

I **think** that the problem comes from the fact that the official example uses [deepmerge](https://github.com/TehShrike/deepmerge) in a way that is not OK for the use case (the use case being to merge the client cache into the server cache).
By default, and as used in the `with-apollo` example, `deepmerge` concatenates arrays when trying to merge 2 arrays at the same key of an object (this is why, when I repeat the manipulation x times, the list has been concatenated x times).
I **guess** that the expected behaviour here would be that the array coming from the client cache would *overwrite* the array from the server cache, but I'm really not sure as I'm not expert enough in terms of the apollo internals here.

`deepmerge` has a way to overwrite instead of concatenating in their docs so I guess this is quite common:

image

So, moving the use of `deepmerge` from 

```ts
if (initialState) {
    // Get existing cache, loaded during client side data fetching
    const existingCache = _apolloClient.extract();

    // Merge the existing cache into data passed from getStaticProps/getServerSideProps
    const data = merge(initialState, existingCache);

    // Restore the cache with the merged data
    _apolloClient.cache.restore(data);
  }
```

to

```ts
if (initialState) {
    // Get existing cache, loaded during client side data fetching
    const existingCache = _apolloClient.extract();

    // Merge the existing cache into data passed from getStaticProps/getServerSideProps
    const data = merge(initialState, existingCache, {
      arrayMerge: (destinationArray, sourceArray) => sourceArray,
    });

    // Restore the cache with the merged data
    _apolloClient.cache.restore(data);
  }
```

in the `with-apollo` example code fixes the issue for me. However I struggle to understand if this is going to have adverse consequences for other use cases.

Could someone that had something to do with the `with-apollo` example examine this and give me their thoughts please?

Thanks a lot! ❤️

### PR DESCRIPTION
**Pull request by felixmeziere**
Closes https://github.com/vercel/next.js/issues/19759

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.1s | -336ms |
| nodeModulesSize | 82.4 MB | 82.4 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.119 | 2.026 | -0.09 |
| / avg req/sec | 1179.99 | 1234.21 | +54.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.29 | 1.288 | 0 |
| /error-in-render avg req/sec | 1938.2 | 1940.5 | +2.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3c9ff84..1d7c.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 12.2s | 11.9s | -308ms |
| nodeModulesSize | 82.4 MB | 82.4 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..8b6e.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-3c9ff84..1d7c.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _error.js | 997 kB | 997 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 998 kB | 998 kB | ✓ |
| link.js | 1.05 MB | 1.05 MB | ✓ |
| routerDirect.js | 1.04 MB | 1.04 MB | ✓ |
| withRouter.js | 1.04 MB | 1.04 MB | ✓ |
| Overall change | 5.14 MB | 5.14 MB | ✓ |

</details>

</details>
Commit: f5fc1c690b53421306c9959b1fdf787ffe67e63c

**Comment by felixmeziere** [comment]
Updated PR as per @stephent comment on the related issue https://github.com/vercel/next.js/issues/19759

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.8s | ⚠️ +330ms |
| nodeModulesSize | 82.5 MB | 82.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.378 | 2.313 | -0.06 |
| / avg req/sec | 1051.23 | 1080.95 | +29.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.22 | 1.233 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2048.54 | 2027.29 | ⚠️ -21.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..34b9.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-899eb31..d9d9.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-01375..90b6.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..fd29.js gzip | 303 B | 303 B | ✓ |
| withRouter-b..76ae.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| Overall change | 322 B | 322 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11s | -63ms |
| nodeModulesSize | 82.5 MB | 82.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..34b9.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-899eb31..d9d9.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-01375..90b6.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..fd29.js gzip | 303 B | 303 B | ✓ |
| withRouter-b..76ae.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| Overall change | 322 B | 322 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: 12410bc9ea7756cbb0a823f2288780f15a3bfb6c

**Review by lfades — APPROVED** [review]
@felixmeziere 👋 Thank you for the PR!

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 9.3s | 10.3s | ⚠️ +980ms |
| nodeModulesSize | 82.5 MB | 82.5 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.284 | 2.467 | ⚠️ +0.18 |
| / avg req/sec | 1094.38 | 1013.42 | ⚠️ -80.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.289 | 1.489 | ⚠️ +0.2 |
| /error-in-render avg req/sec | 1939.31 | 1679.17 | ⚠️ -260.14 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..34b9.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-899eb31..d9d9.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-01375..90b6.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..fd29.js gzip | 303 B | 303 B | ✓ |
| withRouter-b..76ae.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| Overall change | 322 B | 322 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.5s | -413ms |
| nodeModulesSize | 82.5 MB | 82.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| 677f882d2ed8..34b9.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-899eb31..d9d9.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-01375..90b6.js gzip | 3.69 kB | 3.69 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-db223d9..dbd7.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..fd29.js gzip | 303 B | 303 B | ✓ |
| withRouter-b..76ae.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| Overall change | 322 B | 322 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | felixmeziere/next.js fix-with-apollo-list-duplication | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.16 MB | 5.16 MB | ✓ |

</details>

</details>
Commit: ef2a1e71352755052bac0fba48783dd202b9111c

**Comment by mpoisot** [comment]
Is there a way to get notified of changes to a specific example folder like this one, so I can be sure not to miss important bug fixes like this? I just happened to read through the latest Next.js changelog and click through to this subtle bug fix.

Also, I think this approach will lose any cached paginated data. I've only read about paginating with Apollo so I'm not deeply familiar with it.

**Pull request merged**
