### PR TITLE
do not use window.history if inside iframe

### PR DESCRIPTION
**Pull request by hankmander**
This checks if next.js is run inside an iframe in which case it does not use window.history. I do not see how history makes sense in the context of being embedded in another site anyway.

Fixes this crash that prevented next.js from working at all in an iframe: https://github.com/zeit/next.js/issues/3118

### CODE REVIEW

**Review by arunoda — CHANGES_REQUESTED** [review]
Good catch.

In this case of inside a frame, Next's history based routing won't work.
So, user should not use Next's routing inside a frame. 

Yes we should not throw an error. But we should warn the user in the dev mode.

(use [execOnce and warn](https://github.com/zeit/next.js/blob/canary/lib/utils.js#L1-L15) for this)

**Comment by hankmander** [comment]
Hi again! I just now added the warning using execOnce as you suggested.

**Comment by timneutkens** [comment]
Thank you very much @hankmander 🙏

**Comment by hankmander** [comment]
Thank you guys for being responsive to requests and maintaining an awesome project! :smile:

**Comment by timneutkens** [comment]
❤️

**Comment by tomsoderlund** [comment]
@timneutkens It says above "timneutkens merged commit b8f189f into zeit:canary on 4 Feb” but it seems this is not in Next.js 7.0.2?

**Pull request merged**
