### PR TITLE
support customizing content encoding

### LINKED ISSUE #3194: Server does not set 'charset` in 'Content-Type' response header
The server response doesn't set `charset` in `content-type` header. This might be a limitation that some website needs some some special encoding.

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
By default `content-type` response header should be `text/html; charset=utf-8`
Also there should also be an option to override the default charset in `next.config.js`
```js
// next.config.js
module.exports = {
  encoding: 'iso-8859-1'
}
```
## Current Behavior
The `content-type` is hard-coded as `text/html`

### PR DESCRIPTION
**Pull request by liweinan0423**
Resolves #3194

### CODE REVIEW

**Comment by liweinan0423** [comment]
anyone could help review this PR?

**Comment by sergiodxa** [comment]
You can just set the encoding with `<meta charSet="encoding" />` why do you want that extra config key? Or is something I'm missing?

**Comment by liweinan0423** [comment]
@sergiodxa I am not sure if there might be any issue when `content-type` is set without charset, as I see most websites have `charset` in the `content-type` header.

**Comment by howks** [comment]
I spent the whole day searching for why I had bad character encoding in polish language (next ssr with custom express server). Setting `<meta charSet="encoding" />` is not enough for correct encoding. Must be set correctly http header content-type with charset but currently it is hardcoded `text/html` in sendHTML function (default should be `text/html; charset=utf-8`)

Merge this great commit quickly :)

**Comment by dsingleton** [comment]
I originally raised this issue in the Next.js Slack - thanks to @liweinan0423 for raising a PR so quickly. To add our context:

We (@deliveroo) ran into a specific encoding bug. The character `×` becomes `Ã—`, which is a common encoding error as seen here: http://www.i18nqa.com/debug/bug-utf-8-latin1.html. We have already `utf-8` encoding set in `<head>` meta tag (as the default Next `<head>` does). The NextSSR response  only sets `Content-Type: 'text/html'`- without an encoding.

To fix the encoding bug we want to set `Content-Type: 'text/html; charset=utf-8'` in the hope that it would resolve the issue. We're using Next with Express and tried overriding it in Express, but Next sets the `Content-Type` header immediately ends the response. Which prevents us modifying the header.

The PR here would fix the issue for us and we'd be happy to see it merged. But I think a more general solution - that would allow different encodings per page - would be to no overwrite the `Content-Type` header if it has already been set on the response. This would allow a Next user to set an encoding in an HTTP server, or within `getInitialProps` (where `res` is available).

**Comment by timneutkens** [comment]
@dsingleton 

> The PR here would fix the issue for us and we'd be happy to see it merged. But I think a more general solution - that would allow different encodings per page - would be to no overwrite the Content-Type header if it has already been set on the response. This would allow a Next user to set an encoding in an HTTP server, or within getInitialProps (where res is available).

I like this 👌 allows you to specify the content type in getInitialProps too, even without a custom server.

Created a PR #3242 with tests 👌

**Pull request closed without merging**
