### PR TITLE
completed demo with material, redux, custom server, data fetching and dynamic import

### PR DESCRIPTION
**Pull request by davidnguyen11**
I created this example with:
+ dynamic import
+ material-ui
+ data fetching
+ custom server route
+ next routes
+ using gulp to mange css in production

This demo structure is currently using in our team to develop products. I would like to share this

### CODE REVIEW

**Comment by plxel** [comment]
@nndung179 
nice example
it would be great if you add there some another page and demonstrate sync store with browser history

**Comment by nndung179** [comment]
@plxel I updated this example. Now it has only 1 page. But I change the way it navigate and filter. For example:

+ localhost:3000/top => listing all top news
+ localhost:3000/latest => listing all latest news

**Comment by frol** [comment]
@nndung179 Nice example, indeed! I have just a few comments here:

1. `app.css` seems to be auto-generated, so there is no need to include it into the repo.
2. Is there a way to use `bootstrap-grid.scss` from a module instead of vendoring it into the repo?

**Comment by nndung179** [comment]
Hi @frol 

+ 1. `app.css` I will remove it from commit
+ 2. I decided not to use bootstrap as a module bundle. Because It is kind of hard to implement. It will increase the size of bundle file. I want to delegate some heavy jobs to css. In my current project, I use a whole src code of bootstrap 4. Then setting needed module to be bundled. It is good so far for us. If there is better way I will fix it :)

**Comment by frol** [comment]
@nndung179 I mean that you could simply install `bootstrap-sass-grid` NPM package and refer to the `node_modules/bootstrap-sass-grid/sass/bootstrap-sass-grid.scss` file with no need to vendor the file into the repo.

**Comment by nndung179** [comment]
@frol Good point. But I think the demo should be as small as posible. And you can custom it by ur self.

**Comment by timneutkens** [comment]
First of all, this example is cool 👌 👍 great job! I'm just not sure if we want this type of examples or that it's better for you to release it as a repository. cc @arunoda

**Pull request closed without merging**
