### PR TITLE
Reload the page if asked to change the current URL

### PR DESCRIPTION
**Pull request by arunoda**
Fixes https://github.com/zeit/next.js/issues/1137

> This is not location.reload(), but reload the internal Next.js state.

### CODE REVIEW

**Review by nkzawa — APPROVED** [review]
LGTM 👍

**Comment by timneutkens** [comment]
👍

**Comment by fridays** [comment]
@arunoda This is great! Is there a method to trigger a reload of the current page without rebuilding the pathname & querystring? I am using custom server and routing, this works but doesn't look so well:

```javascript
Router.push(
  `${Router.pathname}?${querystring.stringify(Router.query)}`,
  window.location.pathname
)
```

**Comment by arunoda** [comment]
@fridays this seems like the way it is right now.
@nkzawa Shall we introduce a public `.reload()` method?

**Pull request merged**
