### PR TITLE
Remove `native-url`

### PR DESCRIPTION
**Pull request by Timer**
`native-url` is currently broken, let's disable it for now.

x-ref: #10108
x-ref: #10103 
x-ref: #10102

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Looks like we need to revert the size-limit test changes also

Screen Shot 2020-01-20 at 13 31 53

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.9s | ⚠️ +409ms |
| nodeModulesSize | 48.9 MB | 48.8 MB | -149 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..fffc.js gzip | 13.7 kB | 16.3 kB | ⚠️ +2.54 kB |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 70 kB | ⚠️ +2.54 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 15.1 kB | N/A |
| Overall change | 62.1 kB | 64.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.js gzip | 1.34 kB | 1.34 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ⚠️ +1 B |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.module.js gzip | 769 B | 769 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.42 kB | 7.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | -1 B |
| withRouter.html gzip | 1.01 kB | 1.02 kB | ⚠️ +1 B |
| Overall change | 3.06 kB | 3.06 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -441,7 +441,7 @@
 
       var _map = _interopRequireDefault(__webpack_require__('LX0d'))
 
-      var _url = __webpack_require__('QmWs')
+      var _url = __webpack_require__('CxY0')
 
       var _react = _interopRequireWildcard(__webpack_require__('q1tI'))
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -316,7 +316,7 @@
 
       var _map = _interopRequireDefault(__webpack_require__('LX0d'))
 
-      var _url = __webpack_require__('QmWs')
+      var _url = __webpack_require__('CxY0')
 
       var _react = _interopRequireWildcard(__webpack_require__('q1tI'))
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..91f4552b5.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..48.module.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -151,13 +151,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -156,13 +156,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -151,13 +151,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.8s | ⚠️ +426ms |
| nodeModulesSize | 48.9 MB | 48.8 MB | -149 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..fffc.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..c512.js gzip | N/A | 16.3 kB | N/A |
| Overall change | 67.5 kB | 70 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 15.1 kB | N/A |
| Overall change | 62.1 kB | 64.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.js gzip | 1.34 kB | 1.34 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ⚠️ +1 B |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.module.js gzip | 769 B | 769 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.42 kB | 7.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _error.js gzip | 70.9 kB | 70.9 kB | -1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 71.3 kB | 71.3 kB | -1 B |
| link.js gzip | 80.6 kB | 80.6 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.2 kB | 78.2 kB | ✓ |
| withRouter.js gzip | 78.3 kB | 78.3 kB | ✓ |
| Overall change | 380 kB | 380 kB | -1 B |

</details>

</details>


Commit: de92cf85999841c20a6e69ceb118aabfea6402f7

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| buildDuration | 13.7s | 14s | ⚠️ +303ms |
| nodeModulesSize | 48.9 MB | 48.8 MB | -149 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..fffc.js gzip | 13.7 kB | 16.3 kB | ⚠️ +2.54 kB |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 70 kB | ⚠️ +2.54 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 15.1 kB | N/A |
| Overall change | 62.1 kB | 64.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.js gzip | 1.34 kB | 1.34 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ⚠️ +1 B |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.module.js gzip | 769 B | 769 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.42 kB | 7.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | -1 B |
| withRouter.html gzip | 1.01 kB | 1.02 kB | ⚠️ +1 B |
| Overall change | 3.06 kB | 3.06 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -441,7 +441,7 @@
 
       var _map = _interopRequireDefault(__webpack_require__('LX0d'))
 
-      var _url = __webpack_require__('QmWs')
+      var _url = __webpack_require__('CxY0')
 
       var _react = _interopRequireWildcard(__webpack_require__('q1tI'))
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -316,7 +316,7 @@
 
       var _map = _interopRequireDefault(__webpack_require__('LX0d'))
 
-      var _url = __webpack_require__('QmWs')
+      var _url = __webpack_require__('CxY0')
 
       var _react = _interopRequireWildcard(__webpack_require__('q1tI'))
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..91f4552b5.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..48.module.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -151,13 +151,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -156,13 +156,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -39,7 +39,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -151,13 +151,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.329e15c764091f4552b5.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9d13a4f99d1b35e11fb4.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.a0d7d22cc5017428eb48.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.494ccc4c3d846ffaa4a8.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.5s | ⚠️ +362ms |
| nodeModulesSize | 48.9 MB | 48.8 MB | -149 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..fffc.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..c512.js gzip | N/A | 16.3 kB | N/A |
| Overall change | 67.5 kB | 70 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 15.1 kB | N/A |
| Overall change | 62.1 kB | 64.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.js gzip | 1.34 kB | 1.34 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ⚠️ +1 B |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _app.module.js gzip | 769 B | 769 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.42 kB | 7.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js remove/native-url | Change |
| - | - | - | - |
| _error.js gzip | 70.9 kB | 70.9 kB | -1 B |
| hooks.html gzip | 1.05 kB | 1.05 kB | ✓ |
| index.js gzip | 71.3 kB | 71.3 kB | -1 B |
| link.js gzip | 80.6 kB | 80.6 kB | ⚠️ +1 B |
| routerDirect.js gzip | 78.2 kB | 78.2 kB | ✓ |
| withRouter.js gzip | 78.3 kB | 78.3 kB | ✓ |
| Overall change | 380 kB | 380 kB | -1 B |

</details>

</details>


Commit: e0686ac8976350ccd0e3b80e6964178064abf268

**Comment by rscotten** [comment]
@Timer I'm currently getting this error when trying to run `yarn dev` on `9.2.1-canary.6`

`Error: Cannot find module 'native-url'`

Is it related?

**Comment by rscotten** [comment]
Update: I installed `native-url` in my local app and was able to build.  Seems like a dependency bug though.

**Comment by Timer** [comment]
Another one: #10186

**Pull request merged**
