### PR TITLE
Skip warnings for Image not rendered to the dom

### PR DESCRIPTION
**Pull request by wnr**
Some libraries, like react-slick, render their content to a detached element before attaching it to the dom. If the content of such libraries is Image components, they will report warnings because the display/position properties are undefined. This PR squelch the warnings for such cases.

### CODE REVIEW

**Review by styfle — APPROVED** [review]
Looks good if existing tests pass 👍

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 21.5s | 21.3s | -200ms |
| buildDurationCached | 3.9s | 3.9s | ⚠️ +41ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +283 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.68 | 3.72 | ⚠️ +0.04 |
| / avg req/sec | 679.31 | 672.06 | ⚠️ -7.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.954 | 1.92 | -0.03 |
| /error-in-render avg req/sec | 1279.51 | 1302.37 | +22.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 23.3s | 23.2s | -56ms |
| buildDurationCached | 3.9s | 3.8s | -43ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +283 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.604 | 3.609 | 0 |
| / avg req/sec | 693.67 | 692.7 | ⚠️ -0.97 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.942 | 1.93 | -0.01 |
| /error-in-render avg req/sec | 1287.6 | 1295.01 | +7.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: e8ac720dde84bf16361304e41ca1b4ca66392765

**Comment by ijjk** [comment]
## Failing test suites 
Commit: e8ac720dde84bf16361304e41ca1b4ca66392765

**test/integration/image-component/base-path/test/static.test.js** 
- Static Image Component Tests for basePath > dev mode > Should allow an image with a static src to omit height and width
- Static Image Component Tests for basePath > dev mode > Should use immutable cache-control header for static import
- Static Image Component Tests for basePath > dev mode > Should automatically provide an image height and width
- Static Image Component Tests for basePath > dev mode > Should allow provided width and height to override intrinsic
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests for basePath › dev mode › Should allow an image with a static src to omit height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should use immutable cache-control header for static import

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should automatically provide an image height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should allow provided width and height to override intrinsic

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported jpg

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported png

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:36535/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

</details>

**Comment by wnr** [comment]
Okay great 👍

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 18s | 18.1s | ⚠️ +126ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +7ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +267 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.906 | 2.931 | ⚠️ +0.02 |
| / avg req/sec | 860.16 | 852.96 | ⚠️ -7.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.33 | 1.329 | 0 |
| /error-in-render avg req/sec | 1879.04 | 1880.5 | +1.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 19.5s | 19.5s | ⚠️ +11ms |
| buildDurationCached | 3.3s | 3.3s | -20ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +267 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.907 | 2.954 | ⚠️ +0.05 |
| / avg req/sec | 859.98 | 846.38 | ⚠️ -13.6 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.319 | 1.31 | -0.01 |
| /error-in-render avg req/sec | 1895.75 | 1908.74 | +12.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wnr/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 74b3c8610f35f791c87897755630354849fe45b7

**Pull request merged**
