### PR TITLE
fix(examples/with-docker): remove not needed files from docker context

### PR DESCRIPTION
**Pull request by floriangosse**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6eebb83bda7f359118083383008e866c943e222e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
Are you sure these lines aren't needed? There isn't any information provided in the PR description.

**Comment by floriangosse** [comment]
I've tested it on my machine because I was curious why they were even added. The Next.js application will be build during the build process of the Docker image shouldn't need any build output from the host and it doesn't even contain any instructions that use the `.next/static` or `.next/standalone` from the host system.

If you want I can put this into the description.

**Review by ijjk — APPROVED** [review]
This makes sense to me as these assets are generated during the build inside of the docker context where `.dockerignore` isn't applied.

**Pull request merged**
