### PR TITLE
Webpack rule to block importing images into _document

### PR DESCRIPTION
**Pull request by Perry-Olsson**
This PR adds a Webpack rule that disallows any static importing of images into the custom _document file.

related/fixes issue #28307

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Errors have helpful link attached, see `contributing.md`
- [x] Integration tests added

### CODE REVIEW

**Review by ScriptedAlchemy — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.6s | ⚠️ +143ms |
| buildDurationCached | 3.5s | 3.5s | ⚠️ +17ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +4.63 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.946 | 2.975 | ⚠️ +0.03 |
| / avg req/sec | 848.53 | 840.29 | ⚠️ -8.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.833 | 1.902 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1363.84 | 1314.14 | ⚠️ -49.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 534 B | 534 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| buildDuration | 13s | 12.7s | -296ms |
| buildDurationCached | 5.7s | 5.4s | -280ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +4.63 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.004 | 3.016 | ⚠️ +0.01 |
| / avg req/sec | 832.34 | 828.94 | ⚠️ -3.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.949 | 1.864 | -0.08 |
| /error-in-render avg req/sec | 1282.63 | 1340.94 | +58.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 598 B | 598 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 4d87db45eaa3939660d0b2ee19330658044c8b42

**Comment by Perry-Olsson** [comment]
I tried to run the tests that failed CI locally but they pass. Any suggestions on what to change? Thanks!

**Review by styfle — COMMENTED** [review]
Thanks!

We also need to add an integration test fixture to ensure this is working properly

**Comment by Perry-Olsson** [comment]
Awesome, just pushed a test to make sure the build fails.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.4s | -157ms |
| buildDurationCached | 3.9s | 3.9s | ⚠️ +38ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +4.5 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.039 | 3.015 | -0.02 |
| / avg req/sec | 822.64 | 829.24 | +6.6 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.801 | 1.804 | 0 |
| /error-in-render avg req/sec | 1388.07 | 1386.18 | ⚠️ -1.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.4s | ⚠️ +63ms |
| buildDurationCached | 5.2s | 5.1s | -105ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +4.5 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.129 | 3.045 | -0.08 |
| / avg req/sec | 798.87 | 821.14 | +22.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.828 | 1.81 | -0.02 |
| /error-in-render avg req/sec | 1367.69 | 1380.94 | +13.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Perry-Olsson/next.js iss#28307 | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: c532f4d9ae6fe049cdf190e401a89db0420f635e

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c532f4d9ae6fe049cdf190e401a89db0420f635e

**test/integration/required-server-files/test/index.test.js** 
- Required Server Files > should output required-server-files manifest correctly
- Required Server Files > should render SSR page correctly
- Required Server Files > should render dynamic SSR page correctly
- Required Server Files > should render fallback page correctly
- Required Server Files > should render SSR page correctly with x-matched-path
- Required Server Files > should render dynamic SSR page correctly with x-matched-path
- Required Server Files > should render fallback page correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path
- Required Server Files > should render fallback optional catch-all route correctly with x-matched-path and routes-matches
- Required Server Files > should return data correctly with x-matched-path for optional catch-all route
- Required Server Files > should not apply trailingSlash redirect
- Required Server Files > should normalize catch-all rewrite query values correctly
- Required Server Files > should bubble error correctly for gip page
- Required Server Files > should bubble error correctly for gssp page
- Required Server Files > should bubble error correctly for gsp page
- Required Server Files > should bubble error correctly for API page
- Required Server Files > should normalize optional values correctly for SSP page
- Required Server Files > should normalize optional values correctly for SSG page
- Required Server Files > should normalize optional values correctly for SSG page with encoded slash
- Required Server Files > should normalize optional values correctly for API page
- Required Server Files > should match the index page correctly
- Required Server Files > should match the root dyanmic page correctly

<details>
<summary>Expand output</summary>

  ● Required Server Files › should output required-server-files manifest correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render dynamic SSR page correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback page correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should render fallback optional catch-all route correctly with x-matched-path and routes-matches

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should return data correctly with x-matched-path for optional catch-all route

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should not apply trailingSlash redirect

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize catch-all rewrite query values correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gip page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gssp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for gsp page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should bubble error correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSP page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for SSG page with encoded slash

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should normalize optional values correctly for API page

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the index page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

  ● Required Server Files › should match the root dyanmic page correctly

    Command failed with exit code 1 (EPERM): yarn install

      42 |     await fs.writeFile(
      43 |       join(workDir, 'package.json'),
    > 44 |       JSON.stringify({
         |         ^
      45 |         dependencies: {
      46 |           next: packagePath,
      47 |           react: 'latest',

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at integration/required-server-files/test/index.test.js:44:9

</details>

**Pull request merged**
