### PR TITLE
Keep some buffered pages, that won't be disposed. Fix #1939

### LINKED ISSUE #1939: Don't dispose previous pages in dev mode
In dev mode, when navigating from e.g index page to page B, it will then after a while destroy the index page: `Disposing inactive page(s): /`. Why not keeping it in memory, at least as long as there aren't too many pages built?

Rather than disposing on timeout, it appears better to me to dispose pages when there are too many of them in memory.

This would allow to then have fast client-side transitions (after the first load), which allows to have a feel of these transitions without needing to deploy to prod.

### PR DESCRIPTION
**Pull request by AugustinLF**
Implementation of @arunoda's suggestion of letting the user decide how many page should be kept in memory before disposing them.

@sedubois made his point for not over disposing built pages, so I won't repeat him, but I think he has a point:
> This would allow to then have fast client-side transitions (after the first load), which allows to have a feel of these transitions without needing to deploy to prod.

The implementation is pretty naive, `pagesBuffer` works as a queue (first in, first out) of max length two (or whatever the user set), we keep in the buffer the last requested pages. If you'd like me to encapsulate the pagesBuffer logic in, do not hesitate, I didn't want to add any non needed abstraction :)

### CODE REVIEW

**Comment by arunoda** [comment]
I really like the concept behind this PR. But I suggest to change it like this.

Check this: https://github.com/zeit/next.js/blob/v3-beta/server/on-demand-entry-handler.js#L20

It keeps tracks of pages we've accessed. Currently it only keep a single entry. Initialize that with the `pageBufferLength ` count.

Then do a include check here: https://github.com/zeit/next.js/blob/v3-beta/server/on-demand-entry-handler.js#L237

**Comment by AugustinLF** [comment]
I managed to get a working version of it, but I have a problem with the tests! The way the `lastAccessPages` is handled is through the middleware and the `on-demand-entries-ping`, which is not used in the test. Should I try to add the corresponding pings in the test suite?

**Comment by AugustinLF** [comment]
@arunoda I went around the issues I had with the tests, and manage to make it work following your suggestion (or at least, I believed it's closer from what you envisioned).

**Comment by AugustinLF** [comment]
Hey @arunoda, is this feature still something you're interested in? Would you like me to change anything? I know that with the 3.0 release, you had a pretty busy time :)

**Review by timneutkens — APPROVED** [review]
I'm going to merge this in 👌

**Comment by AugustinLF** [comment]
Thanks a lot :)

**Comment by timneutkens** [comment]
It's released under @beta 👍

**Comment by marbemac** [comment]
Sweet, any notes or additions to the readme on how to change pagesBufferLength from the default?

**Comment by AugustinLF** [comment]
@marbemac My bad, [here](https://github.com/zeit/next.js/pull/3030) is the PR!

**Pull request merged**
