### PR TITLE
Remove traces of glamor

### LINKED ISSUE #989: Glamor present even when not used
I have next@2.0.0-beta.23 and don't refer to glamor anywhere in [my code](https://github.com/relatenow/relate), and yet I see that glamor is in my yarn.lock, even after `yarn install --force`.

### LINKED ISSUE #1108: Preserving glamor rehydration
I’ve seen that glamor is deprecated, but I’d like to continue using it because I prefer its interface to styled-jsx. I notice that in next 2 glamor is still available, in particular there’s rehydration of glamor IDs in the client startup code.

Is glamor support going to be preserved? Or, if it’s removed, will there be a hook to apply rehydration before components are imported?

### PR DESCRIPTION
**Pull request by timneutkens**
As talked about with @rauchg. Glamor takes up around 60KB of the bundle (pre-gzip). Since styled-jsx is the way to go now and we support adding glamor by the user we should remove it as dependency cause it is bundled even when not used.

Added rehydration to the example, since we did that in our code.

There is only one thing I'm not sure about and want to discuss:
what should we do with `next/css`. Right now I added a throw for when it is imported. I'm not sure if we should do that / some other way to notify the user it has been removed. The reasoning behind the throw is that when we would do a console.warn the user would see `css.default.<X>` not found because we don't have the glamor dependency anymore.

Fixes #989
Fixes #1108

### CODE REVIEW

**Comment by albinekb** [comment]
I thought we were gonna release 2.0 with the deprecation then soon after 3.0 without glamor? :thinking_face:

**Comment by rauchg** [comment]
@albinekb yeah but we've done enough betas to let people migrate at this point, and we didn't realize that the glamor bundle was just as big as the next.js bundle before :(

**Comment by albinekb** [comment]
LGTM @rauchg, yeah sounds right. I think most users are on beta now 😄

**Comment by timneutkens** [comment]
Ready for merge.

**Comment by arunoda** [comment]
Great work @timneutkens as always.

**Comment by timneutkens** [comment]
@arunoda ❤️ ❤️ ❤️

**Pull request merged**
