### PR TITLE
fixes #48040 missing request body on middleware rewrite

### LINKED ISSUE #48040: [NEXT-1104] NextResponse.rewrite is not forwarding the request body to external hosts in dev
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 19.6.1
      npm: 9.4.0
      Yarn: N/A
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.5-canary.33
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/dbk91/nextresponse-defect

### To Reproduce

Steps to reproduce specific to the linked repo:

1. Spin up a server on `http://localhost:4000` where you can log or inspect the body of a request.
2. Run `next dev` to start the development server for Next.js
3. Load the home page.
4. A POST request to `http://localhost:4000/test` should happen on component mount with a JSON body of `{"hello": 123}`

### Describe the Bug

The log shows no output of the JSON body.

### Expected Behavior

The server should receive `{"hello":123}` in the request body.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1104](https://linear.app/vercel/issue/NEXT-1104/nextresponserewrite-is-not-forwarding-the-request-body-to-external)</sub>

### PR DESCRIPTION
**Pull request by Xetoxyc**
Rewrite is missing body as proxy is never called for the rewrite. The error exists since 13.2.5-canary.27 caused by the changes made in #47208

fixes #48040 
link NEXT-1104

### CODE REVIEW

**Comment by timneutkens** [comment]
Thanks for this PR! I've double checked the changes against #49416 and the test is still failing after these changes. Might be additional places where body is read.

**Comment by Xetoxyc** [comment]
Thanks for the quick reply, i just checked your test and i do not understand how i failes for me with an socket hangup error on both tests (GET and POST)

```
Failed to proxy https://eolmr5jlg1hnlc2.m.pipedream.net/test Error: socket hang up
    at connResetException (node:internal/errors:711:14)
    at TLSSocket.socketCloseListener (node:_http_client:461:25)
    at TLSSocket.emit (node:events:525:35)
    at node:net:298:12
    at TCP.done (node:_tls_wrap:587:7) {
  code: 'ECONNRESET'
}
Error: socket hang up
    at connResetException (node:internal/errors:711:14)
    at TLSSocket.socketCloseListener (node:_http_client:461:25)
    at TLSSocket.emit (node:events:525:35)
    at node:net:298:12
    at TCP.done (node:_tls_wrap:587:7) {
  code: 'ECONNRESET'
}
```

I do not understand how the test should work, even

`curl -X "POST" "https://eolmr5jlg1hnlc2.m.pipedream.net/test" -H 'Content-Type: application/json'`

returns

```
{
   "about":"Pipedream is the fastest way to connects APIs. Build and run workflows with code-level control when you need it — and no code when you don't.",
   "event_id":"2PTxeizNHnPQyB6QA1R0H6gTsZl",
   "workflow_id":"p_KwCMJrz",
   "owner_id":"o_78IrO4E",
   "deployment_id":"d_QAsbN9El",
   "timestamp":"2023-05-07T21:29:29.669Z",
   "inspect":"https://pipedream.com/@/p_KwCMJrz",
   "quickstart":"https://pipedream.com/quickstart/"
}
```

which should pass the test

**Comment by Xetoxyc** [comment]
As just commented to the Test PR for me it seems like its more like an invalid test here.
Would be great if u can give this further investigation

**Comment by Xetoxyc** [comment]
@timneutkens @ijjk i just re checked everything. Seems like it was some edge case thing. Sometimes my test passed sometimes it failed. I just refactored the next-server middleware part which should now archive the same but more optimal behaviour as before. Also cleaned some code duplications.

Sorry for the confusion.

I added the e2e tests of @timneutkens to this pull request for easier testing.

**Pull request closed without merging**
