### PR TITLE
feat(with-react): Example with react redux sagas and mongodb stitch a…

### PR DESCRIPTION
**Pull request by DemidovVladimir**
This example is using: mongodb stitch + aws s3 service + react + redux + redux-saga + custom api

### CODE REVIEW

**Comment by lfades** [comment]
@DemidovVladimir Why do you think this example is required ? looks huge to me and most of the stuff is already available in other examples

**Comment by DemidovVladimir** [comment]
@lfades As far as I saw users have a lot of problems with mongodb-stitch cdk in the isomorphic app(nextjs). So this is the example of how to use all of the functionality of the Mongodb Cloud, plus it is using redux-saga, but I guess you have that already.

**Comment by lfades** [comment]
@DemidovVladimir Can it be only about `mongodb stitch` then ?, there are 10 examples that already include `redux` in their name.

**Comment by DemidovVladimir** [comment]
Sure, that is the main feature of that example.

**Pull request closed without merging**
