### PR TITLE
Ensure optional params are normalized correctly in minimal mode

### PR DESCRIPTION
**Pull request by ijjk**
Follow-up for https://github.com/vercel/next.js/pull/36463 this fixes an issue with optional catch-all params not being normalized correctly which was caught by the runtimes tests. 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: dddc1f0efb26681fefce1f2e45099f1afac9a487

`yarn testheadless test/e2e/yarn-pnp/test/with-styled-components-babel.test.ts` 
- yarn PnP > should compile and serve the index page correctly with-styled-components-babel

<details>
<summary>Expand output</summary>

  ● yarn PnP › should compile and serve the index page correctly with-styled-components-babel

    FetchError: request to http://localhost:41635/ failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| buildDuration | 20.6s | 20.6s | -57ms |
| buildDurationCached | 7.7s | 7.9s | ⚠️ +243ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.567 | 4.607 | ⚠️ +0.04 |
| / avg req/sec | 547.44 | 542.65 | ⚠️ -4.79 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.07 | 2.091 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1207.48 | 1195.4 | ⚠️ -12.08 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.63 kB | 2.63 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| buildDuration | 22.7s | 23.3s | ⚠️ +652ms |
| buildDurationCached | 7.7s | 7.8s | ⚠️ +151ms |
| nodeModulesSize | 481 MB | 481 MB | ⚠️ +21 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.49 | 4.511 | ⚠️ +0.02 |
| / avg req/sec | 556.74 | 554.23 | ⚠️ -2.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.147 | 2.153 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1164.28 | 1161.08 | ⚠️ -3.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.78 kB | 5.78 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.74 kB | 2.74 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.4 kB | 16.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| _buildManifest.js gzip | 456 B | 456 B | ✓ |
| Overall change | 456 B | 456 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/optional-revalidate-params | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: dddc1f0efb26681fefce1f2e45099f1afac9a487

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 7b6621fa4546d45ed3ed5775f683f8deb976b93f

`yarn testheadless test/integration/cli/test/index.test.js` 
- CLI Usage > info > should print output

<details>
<summary>Expand output</summary>

  ● CLI Usage › info › should print output

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "warn  - Latest canary version not detected, detected: \"12.1.6-canary.9\", newest: \"12.1.6-canary.10\".
            Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
            Read more - https://nextjs.org/docs/messages/opening-an-issue
    "

      496 |       // warning will show so skip this check for the stable release
      497 |       if (pkg.version.includes('-canary')) {
    > 498 |         expect(info.stderr || '').toBe('')
          |                                   ^
      499 |       }
      500 |       expect(info.stdout).toMatch(
      501 |         new RegExp(`

      at Object.<anonymous> (integration/cli/test/index.test.js:498:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8968cb16737361785b9c7f3c8a35f43f79e8deb1

`yarn testheadless test/e2e/yarn-pnp/test/with-styled-components-babel.test.ts` 
- yarn PnP > should compile and serve the index page correctly with-styled-components-babel

<details>
<summary>Expand output</summary>

  ● yarn PnP › should compile and serve the index page correctly with-styled-components-babel

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      21 |     let next: NextInstance
      22 |
    > 23 |     beforeAll(async () => {
         |     ^
      24 |       const srcDir = join(__dirname, '../../../../examples', example)
      25 |       const srcFiles = await fs.readdir(srcDir)
      26 |

      at Object.runTests (e2e/yarn-pnp/test/utils.ts:23:5)
      at e2e/yarn-pnp/test/with-styled-components-babel.test.ts:4:43
      at Object.<anonymous> (e2e/yarn-pnp/test/with-styled-components-babel.test.ts:3:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by timneutkens — APPROVED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8968cb16737361785b9c7f3c8a35f43f79e8deb1

`yarn testheadless test/e2e/yarn-pnp/test/with-styled-components-babel.test.ts` 
- yarn PnP > should compile and serve the index page correctly with-styled-components-babel

<details>
<summary>Expand output</summary>

  ● yarn PnP › should compile and serve the index page correctly with-styled-components-babel

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      21 |     let next: NextInstance
      22 |
    > 23 |     beforeAll(async () => {
         |     ^
      24 |       const srcDir = join(__dirname, '../../../../examples', example)
      25 |       const srcFiles = await fs.readdir(srcDir)
      26 |

      at Object.runTests (e2e/yarn-pnp/test/utils.ts:23:5)
      at e2e/yarn-pnp/test/with-styled-components-babel.test.ts:4:43
      at Object.<anonymous> (e2e/yarn-pnp/test/with-styled-components-babel.test.ts:3:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
