### PR TITLE
<Link>: Added deprecation message when adding an extra anchor

### LINKED ISSUE #796: Deprecate automatic insertion of <a> for <Link>
It's an anti-pattern. I'd like `<Link>` to only be an abstract higher-order component that decorates whatever is inside

### PR DESCRIPTION
**Pull request by impronunciable**
Fixes #796

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
I wonder if the usage without `<a>` is used somewhere in the docs / examples 🤔 @impronunciable

**Comment by impronunciable** [comment]
Let me do a pass

**Comment by timneutkens** [comment]
@impronunciable there's one here https://github.com/zeit/next.js#with-link-1

**Comment by impronunciable** [comment]
@timneutkens Cool, I'll change all of them in another pr

**Comment by timneutkens** [comment]
Great, thanks 🙌

**Comment by impronunciable** [comment]
@timneutkens https://github.com/zeit/next.js/pull/798

**Pull request merged**
