### PR TITLE
Adds `Note` to `Good to know` consistency

### PR DESCRIPTION
**Pull request by manovotny**
* Changes all `Note` → `Good to know`
* Consistently puts the colon on the outside of bold text
* Documents singe and multi-line styles in contribution guide

Let me know if you're good with this, @delbaoliveira.

### CODE REVIEW

**Comment by delbaoliveira** [comment]
What do you think about eliminating `Note:` to remove the ambiguity? Then you can have a one line or listed `Good to know:`

**Comment by manovotny** [comment]
@delbaoliveira I am fine with using `Good to know` in all cases, but we'll need to fix up the codebase. I'll do that this weekend and on this same PR.

**Review by leerob — DISMISSED** [review]

**Comment by manovotny** [comment]
@delbaoliveira I took a pass and updated the original description above. LMK what you think.

**Review by delbaoliveira — DISMISSED** [review]
Looks good IMO!

**Review by mayank1513 — APPROVED** [review]

**Comment by manovotny** [comment]
I'll need new approvals due to merging conflicts. 🫤

**Review by styfle — COMMENTED** [review]
Personally, I prefer Note because its shorter. Also "Good" implies that the note is good but sometimes its more like a Caveat which is closer to bad than good.

**Comment by delbaoliveira** [comment]
@styfle for caveats, we previously had **warning**, and sometimes **caveats**. But if phrased incorrectly, it can come across as a negative or a limitation of the feature. **Good to know** felt more neutral, like "here are the things that are helpful to know if you're using this feature", even it is not immediately relevant to the reader, but may be in the future. 

I was also reluctant people might start littering the docs with warnings.

**Review by delbaoliveira — DISMISSED** [review]

**Comment by mayank1513** [comment]
> Personally, I prefer Note because its shorter. Also "Good" implies that the note is good but sometimes its more like a Caveat which is closer to bad than good.

True! Note seems much better.

**Review by leerob — APPROVED** [review]

**Pull request merged**
