### PR TITLE
Fix code splitting and build target for the server-web build

### PR DESCRIPTION
**Pull request by shuding**
- Code splitting should be disabled for the server-web build. Done via `ServerlessPlugin`.
- ~Target can't be `web`, `webworker` is better.~ Using `web` and `es6` for now, still not ideal.
- https://github.com/acornjs/acorn/issues/970

## Bug

- [ ] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by huozhi — DISMISSED** [review]

**Comment by huozhi** [comment]
Looks like we can also removing the workaround `webpackMode: eager` in the previous react-18 tests?

**Review by ijjk — DISMISSED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 22s | 22.2s | ⚠️ +208ms |
| buildDurationCached | 4.4s | 4.4s | -9ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +70 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.766 | 3.705 | -0.06 |
| / avg req/sec | 663.84 | 674.73 | +10.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.052 | 2.052 | ✓ |
| /error-in-render avg req/sec | 1218.59 | 1218.09 | ⚠️ -0.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 24.2s | 24s | -177ms |
| buildDurationCached | 4.4s | 4.4s | ⚠️ +45ms |
| nodeModulesSize | 332 MB | 332 MB | ⚠️ +70 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.825 | 3.852 | ⚠️ +0.03 |
| / avg req/sec | 653.58 | 649.09 | ⚠️ -4.49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.985 | 2.065 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1259.29 | 1210.88 | ⚠️ -48.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 9adf6944bf85fefe3b4c3e468ea6f240c4195c29

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9adf6944bf85fefe3b4c3e468ea6f240c4195c29

**test/integration/react-streaming-and-server-components/test/index.test.js** 
- CSS dev > should include global styles under `concurrentFeatures: true`
- CSS dev > should include global styles with `serverComponents: true`
- CSS prod > should include global styles under `concurrentFeatures: true`
- CSS prod > should include global styles with `serverComponents: true`
- concurrentFeatures - dev > should render the correct html
- concurrentFeatures - dev > should suspense next/link on server side
- concurrentFeatures - dev > should suspense next/image on server side
- concurrentFeatures - dev > should support React.lazy and dynamic imports
- concurrentFeatures - dev > should support multi-level server component imports
- document dev > should error when custom _document has getInitialProps method
- document prod > should error when custom _document has getInitialProps method

<details>
<summary>Expand output</summary>

  ● concurrentFeatures - dev › should render the correct html

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      227 |   })
      228 |   
    > 229 |   it('should support multi-level server component imports', async () => {
          |   ^
      230 |     const html = await renderViaHTTP(context.appPort, '/multi')
      231 |     expect(html).toContain('bar.server.js:')
      232 |     expect(html).toContain('foo.client')

      at runBasicTests (integration/react-streaming-and-server-components/test/index.test.js:229:3)
      at integration/react-streaming-and-server-components/test/index.test.js:188:3
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:136:1)

  ● concurrentFeatures - dev › should suspense next/link on server side

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      236 | function runSuite(suiteName, env, { runTests, before, after }) {
      237 |   const context = { appDir }
    > 238 |   describe(`${suiteName} ${env}`, () => {
          |   ^
      239 |     if (env === 'prod') {
      240 |       beforeAll(async () => {
      241 |         before?.()

      at runBasicTests (integration/react-streaming-and-server-components/test/index.test.js:238:3)
      at integration/react-streaming-and-server-components/test/index.test.js:188:3
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:136:1)

  ● concurrentFeatures - dev › should suspense next/image on server side

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      187 | async function runBasicTests(context) {
      188 |   it('should render the correct html', async () => {
    > 189 |     const homeHTML = await renderViaHTTP(context.appPort, '/')
          |     ^
      190 |
      191 |     // dynamic routes
      192 |     const dynamicRouteHTML1 = await renderViaHTTP(

      at runBasicTests (integration/react-streaming-and-server-components/test/index.test.js:189:5)
      at integration/react-streaming-and-server-components/test/index.test.js:188:3
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:136:1)

  ● concurrentFeatures - dev › should support React.lazy and dynamic imports

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      193 |       context.appPort,
      194 |       '/routes/dynamic1'
    > 195 |     )
          |     ^
      196 |     const dynamicRouteHTML2 = await renderViaHTTP(
      197 |       context.appPort,
      198 |       '/routes/dynamic2'

      at runBasicTests (integration/react-streaming-and-server-components/test/index.test.js:195:5)
      at integration/react-streaming-and-server-components/test/index.test.js:188:3
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:136:1)

  ● concurrentFeatures - dev › should support multi-level server component imports

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      197 |       context.appPort,
      198 |       '/routes/dynamic2'
    > 199 |     )
          |     ^
      200 |
      201 |     expect(homeHTML).toContain('thisistheindexpage.server')
      202 |     expect(homeHTML).toContain('foo.client')

      at runBasicTests (integration/react-streaming-and-server-components/test/index.test.js:199:5)
      at integration/react-streaming-and-server-components/test/index.test.js:188:3
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:136:1)

  ● CSS dev › should include global styles under `concurrentFeatures: true`

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:39737/global-styles", waiting until "load"
    ============================================================

      111 |       this.activeTrace = encodeURIComponent(url)
      112 |     }
    > 113 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      114 |   }
      115 |
      116 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:113:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:83:3)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/css.js:6:21)

  ● CSS dev › should include global styles with `serverComponents: true`

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:39737/global-styles-rsc", waiting until "load"
    ============================================================

      111 |       this.activeTrace = encodeURIComponent(url)
      112 |     }
    > 113 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      114 |   }
      115 |
      116 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:113:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:83:3)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/css.js:13:21)

  ● CSS prod › should include global styles under `concurrentFeatures: true`

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:33881/global-styles", waiting until "load"
    ============================================================

      111 |       this.activeTrace = encodeURIComponent(url)
      112 |     }
    > 113 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      114 |   }
      115 |
      116 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:113:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:83:3)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/css.js:6:21)

  ● CSS prod › should include global styles with `serverComponents: true`

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:33881/global-styles-rsc", waiting until "load"
    ============================================================

      111 |       this.activeTrace = encodeURIComponent(url)
      112 |     }
    > 113 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      114 |   }
      115 |
      116 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:113:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:83:3)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/css.js:13:21)

  ● document dev › should error when custom _document has getInitialProps method

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      208 |   it('should suspense next/link on server side', async () => {
      209 |     const linkHTML = await renderViaHTTP(context.appPort, '/next-api/link')
    > 210 |     const $ = cheerio.load(linkHTML)
          |     ^
      211 |     const linkText = $('div[hidden] > a[href="/"]').text()
      212 |
      213 |     expect(linkText).toContain('go home')

      at runTests (integration/react-streaming-and-server-components/test/index.test.js:210:5)
      at integration/react-streaming-and-server-components/test/index.test.js:228:9
      at runSuite (integration/react-streaming-and-server-components/test/index.test.js:209:5)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:170:1)

  ● document prod › should error when custom _document has getInitialProps method

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      208 |   it('should suspense next/link on server side', async () => {
      209 |     const linkHTML = await renderViaHTTP(context.appPort, '/next-api/link')
    > 210 |     const $ = cheerio.load(linkHTML)
          |     ^
      211 |     const linkText = $('div[hidden] > a[href="/"]').text()
      212 |
      213 |     expect(linkText).toContain('go home')

      at runTests (integration/react-streaming-and-server-components/test/index.test.js:210:5)
      at integration/react-streaming-and-server-components/test/index.test.js:228:9
      at runSuite (integration/react-streaming-and-server-components/test/index.test.js:209:5)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/index.test.js:171:1)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 17.1s | 16.8s | -354ms |
| buildDurationCached | 3.5s | 3.7s | ⚠️ +202ms |
| nodeModulesSize | 332 MB | 332 MB | -220 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.758 | 2.695 | -0.06 |
| / avg req/sec | 906.56 | 927.5 | +20.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.307 | 1.333 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1913.04 | 1874.86 | ⚠️ -38.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 18.5s | 17.7s | -823ms |
| buildDurationCached | 3.7s | 3.4s | -246ms |
| nodeModulesSize | 332 MB | 332 MB | -220 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.891 | 2.714 | -0.18 |
| / avg req/sec | 864.72 | 921.13 | +56.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.351 | 1.268 | -0.08 |
| /error-in-render avg req/sec | 1850.12 | 1971.13 | +121.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 3cefd3414573b7665475599987b7a4d09fb154ed

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 22.6s | 22.1s | -486ms |
| buildDurationCached | 4.4s | 4.7s | ⚠️ +259ms |
| nodeModulesSize | 332 MB | 332 MB | -217 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.875 | 3.811 | -0.06 |
| / avg req/sec | 645.22 | 656.06 | +10.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.111 | 1.971 | -0.14 |
| /error-in-render avg req/sec | 1184.08 | 1268.28 | +84.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| buildDuration | 24.7s | 26.6s | ⚠️ +1.9s |
| buildDurationCached | 4.8s | 4.8s | -13ms |
| nodeModulesSize | 332 MB | 332 MB | -217 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.885 | 3.966 | ⚠️ +0.08 |
| / avg req/sec | 643.54 | 630.37 | ⚠️ -13.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.042 | 2.051 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1224.07 | 1218.74 | ⚠️ -5.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/e706 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 62737aab39fbadb553fd4cea3d7f1a23bcdc47c9

**Pull request merged**
