### PR TITLE
Make sure to render styles fragments as well in amp

### LINKED ISSUE #7856: with-typescript-styled-components doesn't work with amp
# Bug report

## Describe the bug

I'm getting errors when I try to add AMP support to the `with-typescript-styled-components` example.

```
TypeError: Cannot read property '__html' of undefined
    at /Users/janpot/Desktop/with-typescript-app/.next/server/static/development/pages/_document.js:1228:56
    at Array.map (<anonymous>)
    at Head.render (/Users/janpot/Desktop/with-typescript-app/.next/server/static/development/pages/_document.js:1227:29)
    at processChild (/Users/janpot/Desktop/with-typescript-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
    at resolve (/Users/janpot/Desktop/with-typescript-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/janpot/Desktop/with-typescript-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/janpot/Desktop/with-typescript-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at Object.renderToStaticMarkup (/Users/janpot/Desktop/with-typescript-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at renderDocument (/Users/janpot/Desktop/with-typescript-app/node_modules/next-server/dist/server/render.js:94:18)
    at Object.renderToHTML (/Users/janpot/Desktop/with-typescript-app/node_modules/next-server/dist/server/render.js:274:16)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `yarn create next-app --example with-typescript-styled-components with-typescript-app`
2. Add `export const config = { amp: true };` to index.tsx
3. `yarn dev`

## Expected behavior

No error, AMP page for the `with-typescript-styled-components` example

## System information

- OS: macOS
- Version of Next.js: 9.0.0

## Additional context

The example also emits a react warning:

```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in Fragment
    in Head
    in html
    in Html
    in MyDocument
    in Context.Provider
```

### PR DESCRIPTION
**Pull request by Janpot**
Attempts to close https://github.com/zeit/next.js/issues/7856
This should also make it possible to accept a wider variety of content in `styles`, like:

```tsx
        styles: [
          initialProps.styles,
          sheet.getStyleElement(),
        ],
```
and even
```tsx
        styles: <style>{`
          body {
            background: green;
          }
        `}</style>,
```

Also, we might as well change
```tsx
export type DocumentInitialProps = RenderPageResult & {
  styles?: React.ReactElement[] | React.ReactFragment
}
```
into
```tsx
export type DocumentInitialProps = RenderPageResult & {
  styles?: React.ReactNode
}
```
because you could just wrap any react node in a fragment.

### CODE REVIEW

**Comment by timneutkens** [comment]
I don't think this change is needed, especially adding `renderToStaticMarkup` for this seems incorrect 🤔

**Comment by Janpot** [comment]
@timneutkens If you allow fragments in `.styles` then they need to be flattened in order to be able to `.map` over them.
`renderToStaticMarkup` is not strictly necessary, just cleaner, will update.

**Comment by Janpot** [comment]
@timneutkens Mind you that next.js [tries to be backwards compatible here](https://github.com/zeit/next.js/issues/7784). IMO it would make more sense to require `.styles` to strictly be an array of style elements so that one can just do:
```js
styles: [
  ...initialProps.styles,
  sheet.getStyleElement()
],
```
But that would be a breaking change ofcourse.

**Review by Timer — CHANGES_REQUESTED** [review]
Hey @Janpot!

Thanks for the PR, but the type signature is correct in this case.

We only want `styles` to support `React.ReactElement[]` (suggested) or `React.ReactFragment` (backwards compatibility) -- this PR attempts to go the rest of the way and support arrays containing Fragments, etc.

The example is wrong in this case. Can you please update this PR to fix the example?

**Comment by Janpot** [comment]
@Timer Did you have this pattern in mind?
```js
styles: [ initialProps.styles, sheet.getStyleElement() ],
```
And if so, since `initialProps.styles` can be a fragment or an array, doesn't that mean that we could have nested fragments/arrays in the `styles` we return? Hence the reason why I created the flattening function.

We could require the user to make sure the array is flat, but it's not very ergonomic, because the following fails to compile because `initialProps.styles` can be `undefined`:
```js
styles: [
  ...initialProps.styles,
  sheet.getStyleElement(),
],
```
as well as this because it can be a fragment (not iterable):
```js
styles: [
  ...(initialProps.styles || []),
  sheet.getStyleElement(),
],
```

**Comment by Timer** [comment]
@Janpot it seems `ReactElement` inadvertently includes `ReactFragment`, that was not our intention -- we only want style tags.

Maybe the type should be `styles?: React.ReactComponentElement<'style'>[] | React.ReactFragment`?

**Comment by Janpot** [comment]
@Timer @timneutkens Are you waiting for my input to proceed on this? Because in that case it's not entirely clear to me where you'd like to go with this PR.

**Comment by Janpot** [comment]
ok, this issue is clearly not a priority

**Pull request closed without merging**
