### PR TITLE
Updated the example of with-draft-js to utilize the App Router.

### PR DESCRIPTION
**Pull request by PapatMayuri**
This PR updates the with-draft-js example for using the App Router. 
Here are the changes that have been made:

- Renamed the "pages" folder to the "app" folder.
- Added the layout.tsx file as part of the App Router.
- Updated the package.json file.

CC: @samcx

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2afc6584546e296db5e182e640faf4c0f298bb89

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 2afc6584546e296db5e182e640faf4c0f298bb89

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by PapatMayuri** [comment]
@samcx  Any changes needed for this PR?

**Comment by samcx** [comment]
@PapatMayuri Let's delete this example. The package `draft-js` has been archived for a while → https://github.com/facebookarchive/draft-js.

**Comment by PapatMayuri** [comment]
@samcx  I have deleted the example and updated PR please check.

**Review by samcx — APPROVED** [review]
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Pull request merged**
