### PR TITLE
Improve Fela example

### PR DESCRIPTION
**Pull request by steida**
- add webPreset
- cleaner code
- add key for style
- demonstrate Fela composition

### CODE REVIEW

**Comment by steida** [comment]
cc @rofrischmann

**Comment by rofrischmann** [comment]
Wow, that's amazing. Thank you @steida!

**Comment by timneutkens** [comment]
@steida Could you fix the linting errors? Thaaaaaaaanks! ❤️

**Comment by steida** [comment]
I can't this week :-/

**Comment by timneutkens** [comment]
@steida if you could give me push rights I'll fix it 👍 💯

**Comment by steida** [comment]
"Allow edits from maintainers." is checked. Thank you.

**Comment by timneutkens** [comment]
@steida fixed 👌👌

**Pull request merged**
