### PR TITLE
Add authentication docs for app router

### PR DESCRIPTION
**Pull request by StephDietz**
This PR add documentation for adding authentication for an app router project.

- [x]  Create a new route for authentication
- [x]  Discuss what authentication, session management, and authorization are
- [x]  Add guides for some popular authentication solutions
    - [x]  Auth0
    - [x]  Clerk
    - [x]  NextAuth.js
    - [x]  Supabase
    - [ ]  Stych
- [x]  Briefly discuss adding session management to your project
    - [x]  Built-In Session Management in Authentication Libraries
    - [x]  next-session
    - [x]  iron-session

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c8b9539e778ff194f1054e71326f51452b0a2d90

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c8b9539e778ff194f1054e71326f51452b0a2d90

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c8b9539e778ff194f1054e71326f51452b0a2d90

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by leerob** [comment]
We can link to this example now! https://github.com/vercel/next.js/pull/56914

**Pull request closed without merging**
