### PR TITLE
fix(next-flight-loader): add `export` only if `ref` is truthy

### LINKED ISSUE #72358: `next-flight-loader` fails to produce valid JS when module has no exports
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/zen-bas-rxwhwt?file=%2Fapp%2Fpage.tsx%3A2%2C1

### To Reproduce

1. Start the dev server
2. Observe the error - `Module parse failed: Unexpected token...`

### Current vs. Expected behavior

I would expect that `next-flight-loader` produces JS that is valid

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: N/A
  react: 19.0.0-beta-04b058868c-20240508
  react-dom: 19.0.0-beta-04b058868c-20240508
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module Resolution, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kristian240**
### What?

It is possible that `next-flight-loader` produces a module that is not valid JS if a module inside a `node_modules` has a module without `export` or with `export {}` statement.

### Why?

If an original module has no exports, the `ref` will be empty and the following code will be produced

```js
export const  = // ...
```

Notice that the variable name is missing.

### How?

Add guard that will check if `ref` is valid

Fixes #72358

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: bc31bf7d86952fbbd0453043e8a90cfcc622151b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by kristian240** [comment]
Hi @unstubbable! Seems like you did changes in this part of the codebase last week so I would like to get some help with writing an e2e test for this case.

**Comment by unstubbable** [comment]
> Hi @unstubbable! Seems like you did changes in this part of the codebase last week so I would like to get some help with writing an e2e test for this case.

Thanks for raising this issue! I think we need a slightly different fix though: #72404

**Comment by kristian240** [comment]
@unstubbable thanks for reply! Should we close this PR then?

**Pull request closed without merging**
