### PR TITLE
Add dependencies of _app.js to commons

### PR DESCRIPTION
**Pull request by robertvansteen**
Since `_app.js` is used on every page it makes sense to move it's dependencies to the `commons.js` so that if you require a dependency in `_app.js` and in one of your pages it is not included twice in your bundles. 

This PR modifies the `CommonsChunkPlugin` to move every module that is used in `_app.js` and at least in one other bundle.

### CODE REVIEW

**Comment by Ilaiwi** [comment]
Hi, is this intended to solve #4194? because I tried it and it didn't work

**Comment by rovansteen** [comment]
@Ilaiwi no this PR has nothing to do with that.

@timneutkens I didn't spot any tests related to the bundles & contents of the chunks. I don't think I know enough of `next.js` to set something up from scratch but if there are already some related tests I'd be happy to add one that checks this behaviour.

**Comment by Ilaiwi** [comment]
@rovansteen My bad. Thank oyu

**Review by timneutkens — APPROVED** [review]
Lets get this in 👍

**Comment by onufriievkyrylo** [comment]
@rovansteen I'm actualy have an issue with _app and pages. When I'm initialize module on the _app getInitialProps, and after import the same module to the page component, my module initialize again. Should it solve my issue?

**Comment by rovansteen** [comment]
@onufriievkyrylo I’m not sure if I know enough of Webpack to answer your question but it would make sense as before this PR that module could be in two bundles. Maybe @timneutkens can answer that question?

**Comment by timneutkens** [comment]
See #4194

**Comment by kachkaev** [comment]
Does this trick still apply? I just noticed this odd duplication in my Next 7.0.2 project:

screenshot 2018-12-08 at 21 40 24

I can share the source if this sounds like a bug.

**Comment by rovansteen** [comment]
I believe this specific code was removed in a later version of next when they upgraded to webpack 4. Don't know if the functionality remained since I'm not using next.js anymore.

**Comment by kachkaev** [comment]
I re-built the app again. Not sure what I changed, but apollo-client moved into commons. If anyone faces the same problem again, might be worth opening a new issue.

**Pull request merged**
