### PR TITLE
Add support for Fragments in Head

### LINKED ISSUE #3399: Fragments not supported in <Head />
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Considering the following snippet:

```jsx
<Head>
  {title ? (
    <React.Fragment>
      <title>{title} | Cool site</title>
      <meta property='og:title' content={title} />
    </React.Fragment>
  ) : (
    <title>Cool site</title>
  )}

  {/* … */}
</Head>
```

When `title` is defined, I would expect `<title>foo | Cool site</tite>` to be rendered.

## Current Behavior

An empty `<title />` is rendered.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.4     |
| node    |   8.9.1      |

### PR DESCRIPTION
**Pull request by Sekhmet**
This PR adds support for React Fragments (16.2.0) in `<Head />`.

Fixes #3399.

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks. Can we have a test case for this?

**Comment by Sekhmet** [comment]
Currently canary targets `react@16.0.0` - Fragments has been added in 16.2.0. How can I handle this?

**Comment by arunoda** [comment]
@Sekhmet you've checked for `React.Fragment` in this PR changes.
For the devDevelopment, update React to the latest.

**Review by arunoda — APPROVED** [review]
This looks really great.

**Comment by kylealwyn** [comment]
🙏

**Pull request merged**
