### PR TITLE
Update custom-error-page.md

### PR DESCRIPTION
**Pull request by nbouvrette**
Adding more clarity around being able to use directories for custom error pages

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Hi, I don't think we want to encourage this pattern in the docs as ideally only `pages/404.ext` or `pages/500.ext` is used for consistency.

**Comment by nbouvrette** [comment]
Is there a reason for this because if you are planing to have CSS files, its a good practice to have related files under the same folder to avoid crowding the root of your project.

**Comment by ijjk** [comment]
If we encourage folders be used here then users may accidentally think it's alright to add `pages/404/another/path` which isn't advised as well. We also don't encourage this in the docs for `_app`, `_document`, or `_error`.

**Comment by nbouvrette** [comment]
I didn't think `pages/_app/index` would work, but you are right.

Would you say this is even discouraged (e.g. if people do this there is a risk it will break)?

I find this practical on my end but if this is an unsupported feature, it's probably better to stop using it.

**Comment by ijjk** [comment]
Yeah I'd say this is more so discouraged as we don't have test coverage for it and isn't documented mentioning it's expected to work.

**Pull request closed without merging**
