### PR TITLE
Avoid destructuring in ReadOnly type props to prevent unintended modifications

### LINKED ISSUE #67290: TypeScript Templates: Confusion around ReadOnly
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.48 // Latest available version is detected (15.0.0-canary.48).
  eslint-config-next: 15.0.0-canary.48
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.5.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

packages/create-next-app/templates/app-tw/ts/app/layout.tsx and packages/create-next-app/templates/app/ts/app/layout.tsx

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

TypeScript template's read-only props added in #58845 doesn't type check correctly.

As mentioned [here](https://github.com/vercel/next.js/commit/f60c609bdb8ad17b2f15c3dbba89a987be1078d5#commitcomment-142979798), when you destructure props, new variables are created.
[TypeScript does not consider the 'children' variable as readonly](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChSkAPSWOAEyUxQFcAbLZgOw2Ak8QgQYAGRQBPCMxgAKAN6k4cNAAtgrOkU4AaUgF8AXIlR0+rMQB55ilWo1JOh5OhgA6JxgByEBnoB8ASjh5BSVVdU04AF44czpgADdfcwB6OMSAbjhk5LgAFVUAZzhgIpRWVggAdyQ6eiQCsGAYJCMUE04zckUiGGYofmkQxXNlGBBWOFYUTgBzSPx7fF8hxRiAI28xX1kbcPtdFI26LZWU0fHlxX89IA).

Therefore, using ReadOnly with destructuring props can cause confusion.

### Expected Behavior

TypeScript templates should not enforce read-only props.

### To Reproduce

1. Run the `npx create-next-app@latest`
2. Check the `src/app/layout.tsx`

### PR DESCRIPTION
**Pull request by jinmayamashita**
### Why?

Fixes #67290

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6af7e82afa87223091e016ac6c1677fdbb52f980

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — CHANGES_REQUESTED** [review]
Need to confirm the issue first: https://github.com/vercel/next.js/issues/67290#issuecomment-2233334093

**Review by eps1lon — CHANGES_REQUESTED** [review]
The existing code is fine. The discussion in the issue should highlight this: https://github.com/vercel/next.js/issues/67290#issuecomment-2233334093

**Comment by ijjk** [comment]
Closing per-above as this is valid as is.

**Pull request closed without merging**
