### PR TITLE
JSX extension support

### PR DESCRIPTION
**Pull request by CompuIves**
Response to https://github.com/zeit/next.js/issues/161 in case we want to support `.jsx` files.

### CODE REVIEW

**Comment by Alfredo2519** [comment]
I dont really no wut to do here im new at this lol

**Comment by rauchg** [comment]
What's the advantage of supporting `.jsx` if we already support jsx in `.js`? Isn't it confusing to have two?

**Comment by skhavari** [comment]
typescript is a use case to support this.  typescript will product jsx files if you want babel to compile JSX and not typescript.

**Comment by arunoda** [comment]
@rauchg beside what @skhavari mentioned, some still love to use `.jsx` extension for React.
Here's the discussion in CRA: https://github.com/facebookincubator/create-react-app/issues/87

If this helps to someone, adding `.jsx` support make no harm.
But we should not document it.

**Comment by rauchg** [comment]
I support this since JSX is not a standard feature, and I understand that some might want to make this explicit.

**Comment by giacomorebonato** [comment]
how to understand the conflict in `webpack.js` ?

**Comment by rauchg** [comment]
Can you elaborate?

**Comment by giacomorebonato** [comment]
I would like to help with this PR, but I don't know how to understand what the conflict on `webpacks.js` is about.  
Should I checkout this branch e run the tests?

**Review by giacomorebonato — APPROVED** [review]

**Comment by rauchg** [comment]
Closing this for the time being as we haven't heard much. @CompuIves wouldn't it be nicer to incorporate typescript support through babel / webpack decoration, rather than a separate pipeline that outputs JSX?

**Comment by CompuIves** [comment]
@rauchg I agree, I now see that I also edited the gulp file which wasn't necessary at all 😅 . After we support the Webpack config PR people can just add this themselves, we could also maybe document it somewhere or create helper methods (something like `addJSXSupport(webpackConfig)`).

**Pull request closed without merging**
