### PR TITLE
Fix onError prop-type warning in Link

### PR DESCRIPTION
**Pull request by oliviertassinari**
The warning

> Warning: Failed prop type: Link: unknown props found: onError

can happen in this case:

```tsx
import * as React from 'react';
import NextLink, { LinkProps as NextLinkProps } from 'next/link';

type NextComposedProps = React.AnchorHTMLAttributes<HTMLAnchorElement> & NextLinkProps;

const NextComposed = React.forwardRef<HTMLAnchorElement, NextComposedProps>((props, ref) => {
  const { as, href, replace, scroll, passHref, shallow, prefetch, onError, ...other } = props;

  return (
    <NextLink
      href={href}
      prefetch={prefetch}
      as={as}
      replace={replace}
      scroll={scroll}
      shallow={shallow}
      passHref={passHref}
      onError={onError}
    >
      <a ref={ref} {...other} />
    </NextLink>
  );
});
```

*Taken from Material-UI Next.js integration example*

### CODE REVIEW

**Comment by timneutkens** [comment]
I wonder if this is really needed, it seems to never trigger / would cause other issues 🤔 Might make more sense to remove the property (as it would error out anyway in dev currently, so it must have been for multiple majors).

**Comment by oliviertassinari** [comment]
My initial motivation was to sync the TypeScript defintions with the prop-types. I don't have enough specific knowledge to respond on what direction should be taken.

**Comment by timneutkens** [comment]
Great! My main question was if you needed it for anything specific. Seems like you don't 👍💯

**Comment by oliviertassinari** [comment]
No, I don't need anything specific with this prop, I have never used it.

So I will remove the onError prop spread from the Material-UI + Next.js integration example. Do you want me to update the pull request to remove the prop?

**Comment by lfades** [comment]
@oliviertassinari You can update this PR or close it and create a new one 👍

**Review by Timer — APPROVED** [review]

**Pull request merged**
