### PR TITLE
Use uglify-es for minification

### PR DESCRIPTION
**Pull request by jesstelford**
Given [this project setup](https://gist.github.com/jesstelford/cf55626a1560252b77fcb6f79570847d), UglifyJS will error out with:

> ❯ yarn build
> yarn run v1.1.0
> $ NODE_ENV=production next build
> > Using external babel configuration
> > Location: "/home/teddy/dev/next-uglify-example/.babelrc"
> > Failed to build on /tmp/96fe3fc3-fa8c-49de-9ef2-165276bed0e9
> { Error: commons.js from UglifyJs
> Unexpected token operator «*», expected punc «(» [commons.js:9310,57]
>     at /home/teddy/dev/next-uglify-example/node_modules/next/dist/server/build/index.js:182:21
>     at emitRecords.err (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:269:13)
>     at Compiler.emitRecords (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:375:38)
>     at emitAssets.err (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:262:10)
>     at applyPluginsAsyncSeries1.err (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:368:12)
>     at next (/home/teddy/dev/next-uglify-example/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/home/teddy/dev/next-uglify-example/node_modules/tapable/lib/Tapable.js:222:13)
>     at Compiler.afterEmit (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:365:9)
>     at require.forEach.err (/home/teddy/dev/next-uglify-example/node_modules/webpack/lib/Compiler.js:354:15)
>   errors: 
>    [ 'commons.js from UglifyJs\nUnexpected token operator «*», expected punc «(» [commons.js:9310,57]' ],
>   warnings: [] }
> error Command failed with exit code 1.

(The main motivation is to remove the regenerator runtime from my bundles and only support [modern browsers](https://caniuse.com/#feat=es6-generators))

### CODE REVIEW

**Comment by jesstelford** [comment]
The AppVeyor build failure isn't related to this PR:

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by timneutkens** [comment]
@jesstelford is the going to affect performance too (for the better)?

**Comment by jesstelford** [comment]
There could be! The `parallel` flag should provide a bit of reduction in minification times for large projects, but I didn't see any significant change when running against my smallish project.

**Comment by jesstelford** [comment]
Any update on getting this branch merged?

**Review by timneutkens — APPROVED** [review]
The new uglify version works really well. I haven't been able to detect a major spike in performance though. Even though you've added the parallel flag

**Comment by timneutkens** [comment]
After CI passes I'll merge 👍

**Comment by ilionic** [comment]
Having some issues related to `Production build not minified`, hope this PR would fix it?

**Comment by jesstelford** [comment]
🎉

**Comment by timneutkens** [comment]
Planning to do a new canary release soon 👍

**Comment by nickdima** [comment]
I have a similar issue but I'm not sure where it comes from as I don't have any custom babel or next configuration. I also tried updating to `4.2.0-canary.1` but still no luck.

```
> next build

> Failed to build on /var/folders/s0/gqb6p67d3r12_tcw97lthmwm0000gn/T/f94db614-b9eb-4ecc-bffa-83dfa2eba794
{ Error: commons.js from UglifyJs
Unexpected token: keyword (const) [commons.js:54208,5]
    at /my-next-js-app/node_modules/next/dist/server/build/index.js:188:21
    at emitRecords.err (/my-next-js-app/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/my-next-js-app/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/my-next-js-app/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/my-next-js-app/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/my-next-js-app/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/my-next-js-app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/my-next-js-app/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/my-next-js-app/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/my-next-js-app/node_modules/webpack/lib/Compiler.js:354:15)
  errors:
   [ 'commons.js from UglifyJs\nUnexpected token: keyword (const) [commons.js:54208,5]',
     'app.js from UglifyJs\nUnexpected token: keyword (const) [app.js:54363,5]',
     'app.js from UglifyJs\nUnexpected token: keyword (const) [app.js:54363,5]',
     'app.js from UglifyJs\nUnexpected token: keyword (const) [app.js:54363,5]',
     'app.js from UglifyJs\nUnexpected token: keyword (const) [app.js:54363,5]' ],
  warnings: [] }
```

Any advice?

**Comment by Flaque** [comment]
@nickdima Getting a similar error on 4.2.0-canary.1 and 4.1.4:

```
{ Error: commons.js from UglifyJs
Unexpected token: operator (>) [commons.js:10209,25]
    at /Users/Flaque/Projects/vote-with-letters/node_modules/next/dist/server/build/index.js:182:21
    at emitRecords.err (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/Flaque/Projects/vote-with-letters/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/Flaque/Projects/vote-with-letters/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:354:15)
  errors:
   [ 'commons.js from UglifyJs\nUnexpected token: operator (>) [commons.js:10209,25]' ],
  warnings:
   [ './node_modules/keyv/src/index.js\n18:14-40 Critical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compilation.js:694:24)\n    at Compilation.finish (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compilation.js:552:9)\n    at applyPluginsParallel.err (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/Compiler.js:506:17)\n    at /Users/Flaque/Projects/vote-with-letters/node_modules/tapable/lib/Tapable.js:289:11\n    at Promise.all.then (/Users/Flaque/Projects/vote-with-letters/node_modules/webpack/lib/DynamicEntryPlugin.js:45:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' ] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Reproducible (but not minimal 😰) environment [here.](https://github.com/gu-app-club/save-the-net)

### Steps to reproduce 
1. Clone that project
2. Run `yarn`
3. Run `yarn build`
4. Watch it crash

**Comment by maxchehab** [comment]
@nickdima I am a developer working alongside @Flaque, I was able to resolve this problem by disabling `UglyifyJsPlugin` in the `next.config.js`

For example:

```javascript
//next.config.js
module.exports = {
  webpack: config => {
    config.plugins = config.plugins.filter(plugin => {
      if (plugin.constructor.name === "UglifyJsPlugin") {
        return false;
      } else {
        return true;
      }
    });
    return config;
  }
};

```

**Comment by nickdima** [comment]
@maxchehab wouldn't it be a bad idea deploying without minifying the code?

**Comment by Flaque** [comment]
@nickdima Probably

**Comment by jesstelford** [comment]
Interesting! It appears that the something changed in the `uglifyjs-webpack-plugin` module since I opened the PR. However, the latest version `1.1.1` appears to be working correctly.

I've opened a new PR to bump the version here: https://github.com/zeit/next.js/pull/3329

**Comment by jesstelford** [comment]
Until that PR is merged, you can use this workaround:

```
npm install uglifyjs-webpack-plugin@latest
```

```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
  webpack: (config) => {
    for (let index = 0; index < config.plugins.length; index += 1) {
      if (config.plugins[index].constructor.name === "UglifyJsPlugin") {
        // Delete the UglifyJS plugin
        // And add uglify-es plugin (https://github.com/webpack-contrib/uglifyjs-webpack-plugin)
        config.plugins.splice(index, 1, new UglifyJSPlugin({
          sourceMap: false,
          parallel: true,
        }));
        break;
      }
    }
    return config;
  },
};
```

**Comment by psycura** [comment]
I`m tried this variant, but get an error on deploy:
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^
Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.fork (child_process.js:103:10)
    at fork (/home/nowuser/src/node_modules/worker-farm/lib/fork.js:12:35)
    at Farm.startChild (/home/nowuser/src/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/nowuser/src/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.<anonymous> (/home/nowuser/src/node_modules/worker-farm/lib/farm.js:97:21)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! visual_proposal@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the visual_proposal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nowuser/.npm/_logs/2017-11-24T13_22_44_573Z-debug.log

**Comment by harriha** [comment]
@jesstelford @timneutkens Hmm, shouldn't the `uglifyjs-webpack-plugin` be in `dependencies` rather than in `devDependencies`? Now when adding dep only to `next` I get version 0.4.6 of that plugin via webpack 3.6.0:

```
xx@xx MSYS ~/repos/tmp-next
$ npm init -y
// ..snip..
$ npm install --save next@canary
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date wi
th respect to npm

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\hhal\repos\tmp-next\node_modules\uglifyjs-webpack-p
lugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN next@4.3.0-canary.1 requires a peer of react@^16.0.0 but none is installed. You must install pe
er dependencies yourself.
npm WARN next@4.3.0-canary.1 requires a peer of react-dom@^16.0.0 but none is installed. You must instal
l peer dependencies yourself.
npm WARN styled-jsx@2.2.1 requires a peer of react@15.x.x || 16.x.x but none is installed. You must inst
all peer dependencies yourself.
npm WARN redbox-react@1.5.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0 but n
one is installed. You must install peer dependencies yourself.
npm WARN redbox-react@1.5.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0 b
ut none is installed. You must install peer dependencies yourself.
npm WARN tmp-next@1.0.0 No description
npm WARN tmp-next@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"dar
win","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ next@4.3.0-canary.1
added 839 packages in 46.415s

xx@xx MSYS ~/repos/tmp-next
$ npm ll uglifyjs-webpack-plugin
tmp-next@1.0.0
| C:\Users\hhal\repos\tmp-next
|
`-- next@4.3.0-canary.1
  | Minimalistic framework for server-rendered React applications
  | git+https://github.com/zeit/next.js.git
  | https://github.com/zeit/next.js
  `-- webpack@3.6.0
    | Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, w
hich can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... a
nd your custom stuff.
    | git+https://github.com/webpack/webpack.git
    | https://github.com/webpack/webpack
    `-- uglifyjs-webpack-plugin@0.4.6
        UglifyJS plugin for webpack
        git+https://github.com/webpack-contrib/uglifyjs-webpack-plugin.git
        https://github.com/webpack-contrib/uglifyjs-webpack-plugin

```

**Pull request merged**
