### PR TITLE
Created tailwind and typescript starter

### PR DESCRIPTION
**Pull request by kumard3**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Let's just convert this one instead:

https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

**Comment by kumard3** [comment]
> Let's just convert this one instead:
> 
> https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

So do I have to use tailwind css starter and add typescript to it and then add a PR ?

**Comment by balazsorban44** [comment]
Going forward, we will prefer TypeScript examples over plain JS, and instead of adding new ones, the existing ones should be rewritten.

https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

**Comment by kumard3** [comment]
> Going forward, we will prefer TypeScript examples over plain JS, and instead of adding new ones, the existing ones should be rewritten.
> 
> https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

Ok so you want me to 

> Going forward, we will prefer TypeScript examples over plain JS, and instead of adding new ones, the existing ones should be rewritten.
> 
> https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

Ok , so I am closing this pr and adding to the existing tailwind one.

**Comment by kumard3** [comment]
> Going forward, we will prefer TypeScript examples over plain JS, and instead of adding new ones, the existing ones should be rewritten.
> 
> https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

Ok , so I am closing this pr and adding to the existing tailwind one.

**Pull request closed without merging**
