### PR TITLE
Turbopack: app externals test case improvements

### PR DESCRIPTION
**Pull request by sokra**
### What?

* rename test case
* improve error message and handle edge case for require resolving
* fix test case actually testing externals (webpack was silently bundling, Turbopack showed error that helped to find the broken test case)
* fix order of resolving plugins to handle shared-runtime before externals

### How?

Closes PACK-2662

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 0c4f10df75c8ba4410d56ecc9dee8891fc5336ad

`TURBOPACK=1 pnpm test test/integration/jsconfig-paths-wildcard/test/index.test.js` (turbopack)
- jsconfig paths wildcard > default behavior > should resolve a wildcard alias
- jsconfig paths without baseurl wildcard > default behavior > should resolve a wildcard alias

<details>
<summary>Expand output</summary>

  ● jsconfig paths wildcard › default behavior › should resolve a wildcard alias

    expect(received).toMatch(expected)

    Expected pattern: /world/
    Received string:  "{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Failed to load external module mypackage/myfile: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/node_modules/mypackage/myfile' imported from /root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js\\nDid you mean to import mypackage/myfile.js?\",\"stack\":\"Error: Failed to load external module mypackage/myfile: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/node_modules/mypackage/myfile' imported from /root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js\\nDid you mean to import mypackage/myfile.js?\\n    at externalImport (/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js:312:15)\"},\"gip\":true,\"scriptLoader\":[]}"

      32 |     it('should resolve a wildcard alias', async () => {
      33 |       const $ = await get$('/wildcard-alias')
    > 34 |       expect($('body').text()).toMatch(/world/)
         |                                ^
      35 |     })
      36 |   })
      37 | }

      at Object.toMatch (integration/jsconfig-paths-wildcard/test/index.test.js:34:32)

  ● jsconfig paths without baseurl wildcard › default behavior › should resolve a wildcard alias

    expect(received).toMatch(expected)

    Expected pattern: /world/
    Received string:  "{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Error\",\"source\":\"server\",\"message\":\"Failed to load external module mypackage/myfile: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/node_modules/mypackage/myfile' imported from /root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js\\nDid you mean to import mypackage/myfile.js?\",\"stack\":\"Error: Failed to load external module mypackage/myfile: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/node_modules/mypackage/myfile' imported from /root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js\\nDid you mean to import mypackage/myfile.js?\\n    at externalImport (/root/actions-runner/_work/next.js/next.js/test/integration/jsconfig-paths-wildcard/.next/server/chunks/[turbopack]_runtime.js:312:15)\"},\"gip\":true,\"scriptLoader\":[]}"

      32 |     it('should resolve a wildcard alias', async () => {
      33 |       const $ = await get$('/wildcard-alias')
    > 34 |       expect($('body').text()).toMatch(/world/)
         |                                ^
      35 |     })
      36 |   })
      37 | }

      at Object.toMatch (integration/jsconfig-paths-wildcard/test/index.test.js:34:32)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.7s | N/A |
| buildDurationCached | 7.4s | 6.3s | N/A |
| nodeModulesSize | 198 MB | 198 MB | ⚠️ +5.89 kB |
| nextStartRea..uration (ms) | 429ms | 431ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.2 kB | 30.2 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 243 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 45.4 kB | 45.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.2 kB | 4.2 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.56 kB | 6.56 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| index.html gzip | 530 B | 530 B | ✓ |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.05 kB | 1.05 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95 kB | 95 kB | N/A |
| page.js gzip | 3.06 kB | 3.08 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 96.7 kB | 96.7 kB | ✓ |
| app-page-tur..prod.js gzip | 98.5 kB | 98.5 kB | ✓ |
| app-page-tur..prod.js gzip | 92.9 kB | 92.9 kB | ✓ |
| app-page.run...dev.js gzip | 150 kB | 150 kB | ✓ |
| app-page.run..prod.js gzip | 91.4 kB | 91.4 kB | ✓ |
| app-route-ex...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route-ex..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 20.9 kB | 20.9 kB | ✓ |
| app-route.ru..prod.js gzip | 14.7 kB | 14.7 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.51 kB | 9.51 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.79 kB | 9.79 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.51 kB | 9.51 kB | ✓ |
| pages-turbo...prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| pages.runtim...dev.js gzip | 23 kB | 23 kB | ✓ |
| pages.runtim..prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| server.runti..prod.js gzip | 50.6 kB | 50.6 kB | ✓ |
| Overall change | 950 kB | 950 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js sokra/app-externals | Change |
| - | - | - | - |
| 0.pack gzip | 1.56 MB | 1.56 MB | ⚠️ +2.33 kB |
| index.pack gzip | 105 kB | 106 kB | ⚠️ +743 B |
| Overall change | 1.66 MB | 1.66 MB | ⚠️ +3.07 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>2453-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 0c4f10df75c8ba4410d56ecc9dee8891fc5336ad

**Review by timneutkens — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]

**Comment by sokra** [comment]
This `NextRouter was not mounted.` error is weird... Maybe it's really broken...

**Comment by timneutkens** [comment]
The PR is failing on this test suite: `TURBOPACK=1 pnpm test-dev test/e2e/getserversideprops/test/index.test.ts`

```
 page error Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
        at useRouter (file:///private/var/folders/sk/pyr4sjxd7bg5dn69d5f_4bsh0000gn/T/next-install-4df8c5dd887386753de664497700ce53fc00b3c42387ec0038229e40ed9e2494/.next/server/chunks/node_modules__pnpm_f99805._.js:8954:15)
        at RouterComp (file:///private/var/folders/sk/pyr4sjxd7bg5dn69d5f_4bsh0000gn/T/next-install-4df8c5dd887386753de664497700ce53fc00b3c42387ec0038229e40ed9e2494/.next/server/chunks/pages_9225a2._.js:65:276)
```

**Pull request merged**
