### PR TITLE
Upgrade dependencies

### LINKED ISSUE #2993: Question about dependencies
(I searched for duplicates, apologies if this has been discussed before.)

The package.json files in [Next.js](https://github.com/zeit/next.js/blob/094bb1f7b95f10c84a9e98d4ec76abfd03f8c60d/package.json#L49-L105) and [styled-jsx](https://github.com/zeit/styled-jsx/blob/296526dc43212aa4244932b138791a7fe908bd96/package.json#L56-L67) omit the conventional `^` on dependency versions.

Why is this? I'm guessing it's intentional, as it seems to be this way on multiple Zeit projects, and you obviously know what you're doing.

Why it causes a problem for me: I'm making a Next.js website. I found a bug coming from [Stylis](https://github.com/thysultan/stylis.js) the other night, and it got fixed by @thysultan quickly. But then I had to wait for styled-jsx to be republished, which happened the next day. And Next.js is still not republished (at time of writing), so I'm still blocked until that happens.

If it's a defence against regressions in dependencies, FWIW, it seems like opting out of automatic patches does more harm than good. I know patch releases can sometimes introduce regressions, but they fix bugs more often. The approach would make sense to me if you had an automated nightly test-and-republish system to ensure you pick up patches quickly, but this doesn't seem to be in place – for example, until a few hours ago, styled-jsx was fixed to a two-month-old Stylis version (3.2.8), from July 24. Stylis has released 10 patches over that time, and none of them made it into styled-jsx until 5 hours ago. (And they're still not in Next.js.) On balance, wouldn't it make more sense to use `^`?

### PR DESCRIPTION
**Pull request by timneutkens**
Huge upgrade, get all deps to their latest version :ok_hand:

Fixes #2993

### CODE REVIEW

**Comment by michael-ar** [comment]
hello

am failing CI on a project due to an [nsp warning](https://nodesecurity.io/advisories/526) which would be fixed by this PR

let me know if you want any help testing prior to this being merged 😀

**Comment by timneutkens** [comment]
@michael-ar if you want to test it against your project that'd be great! Thanks ❤️

**Comment by michael-ar** [comment]
tested against my project locally and all working correctly

thanks for all the work on next!

**Comment by timneutkens** [comment]
Since all tests pass I'm going to merge this in 👍

**Comment by timneutkens** [comment]
@michael-ar thanks for checking against your project ❤️ Much appreciated!

**Comment by timneutkens** [comment]
Feel free to join zeit.chat btw 👌

**Pull request merged**
