### PR TITLE
feat(next/image): reduce byte waste for 3x screens

### PR DESCRIPTION
**Pull request by Timer**
https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/capping-image-fidelity-on-ultra-high-resolution-devices.html

> This means that most OLED screens that say they are 3x resolution, are actually 3x in the green color, but only 1.5x in the red and blue colors. Showing a 3x resolution image in the app vs a 2x resolution image will be visually the same, though the 3x image takes significantly more data. Even true 3x resolution screens are wasteful as the human eye cannot see that level of detail without something like a magnifying glass.

> image

Even the iPhone doesn't have true 3x DPI!

related: #18756

### CODE REVIEW

**Review by styfle — DISMISSED** [review]
Nice find! 💯 

We'll also need to update the test 👍 

Also see [Apple's Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/) for more info about DPI.

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.9s | ⚠️ +231ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.919 | 1.987 | ⚠️ +0.07 |
| / avg req/sec | 1302.88 | 1258.2 | ⚠️ -44.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.193 | 1.257 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 2096.31 | 1989.26 | ⚠️ -107.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-29e0222..8425.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.6s | ⚠️ +139ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-29e0222..8425.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: c895f8ea48b915e57a27c1e28868b13cb11ff471

**Comment by ijjk** [comment]
## Failing test suites 
Commit: c895f8ea48b915e57a27c1e28868b13cb11ff471

**test/integration/image-component/default/test/index.test.js** 
- Image Component Tests > dev mode > should load the images
- Image Component Tests > server mode > should load the images
- Image Component Tests > serverless mode > should load the images

<details>
<summary>Expand output</summary>

  ● Image Component Tests › dev mode › should load the images

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      104 |           `http://localhost:${appPort}/_next/image?url=%2Ftest.jpg&w=1200&q=75`
      105 |         )
    > 106 |       ).toBe(true)
          |         ^
      107 |     } finally {
      108 |       if (browser) {
      109 |         await browser.close()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:106:9)

  ● Image Component Tests › server mode › should load the images

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      104 |           `http://localhost:${appPort}/_next/image?url=%2Ftest.jpg&w=1200&q=75`
      105 |         )
    > 106 |       ).toBe(true)
          |         ^
      107 |     } finally {
      108 |       if (browser) {
      109 |         await browser.close()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:106:9)

  ● Image Component Tests › serverless mode › should load the images

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      104 |           `http://localhost:${appPort}/_next/image?url=%2Ftest.jpg&w=1200&q=75`
      105 |         )
    > 106 |       ).toBe(true)
          |         ^
      107 |     } finally {
      108 |       if (browser) {
      109 |         await browser.close()

      at Object.<anonymous> (integration/image-component/default/test/index.test.js:106:9)
          at runMicrotasks (<anonymous>)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 9.2s | 9.5s | ⚠️ +309ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.954 | 1.947 | -0.01 |
| / avg req/sec | 1279.27 | 1283.89 | +4.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.238 | 1.202 | -0.04 |
| /error-in-render avg req/sec | 2019.29 | 2079.81 | +60.52 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a6ce971..96b9.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.3s | ⚠️ +210ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a6ce971..96b9.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: 4a8f7aa5a6404e0414a97c166b14764b889533fe

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 4a8f7aa5a6404e0414a97c166b14764b889533fe

**test/integration/image-component/basic/test/index.test.js** 
- Image Component Tests > Client-side Image Component Tests > should use imageSizes when width matches, not deviceSizes from next.config.js
- Image Component Tests > Client-side Lazy Loading Tests > should load the fifth image eagerly, without scrolling
- Image Component Tests > SSR Image Component Tests > should use imageSizes when width matches, not deviceSizes from next.config.js
- Image Component Tests > SSR Lazy Loading Tests > should load the fifth image eagerly, without scrolling

<details>
<summary>Expand output</summary>

  ● Image Component Tests › SSR Image Component Tests › should use imageSizes when width matches, not deviceSizes from next.config.js

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.com/myaccount/icon.png?auto=format&fit=max&w=48"
    Received: "https://example.com/myaccount/icon.png?auto=format&fit=max&w=32"

      61 |   })
      62 |   it('should use imageSizes when width matches, not deviceSizes from next.config.js', async () => {
    > 63 |     expect(await browser.elementById('icon-image-16').getAttribute('src')).toBe(
         |                                                                            ^
      64 |       'https://example.com/myaccount/icon.png?auto=format&fit=max&w=48'
      65 |     )
      66 |     expect(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:63:76)

  ● Image Component Tests › Client-side Image Component Tests › should use imageSizes when width matches, not deviceSizes from next.config.js

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.com/myaccount/icon.png?auto=format&fit=max&w=48"
    Received: "https://example.com/myaccount/icon.png?auto=format&fit=max&w=32"

      61 |   })
      62 |   it('should use imageSizes when width matches, not deviceSizes from next.config.js', async () => {
    > 63 |     expect(await browser.elementById('icon-image-16').getAttribute('src')).toBe(
         |                                                                            ^
      64 |       'https://example.com/myaccount/icon.png?auto=format&fit=max&w=48'
      65 |     )
      66 |     expect(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:63:76)

  ● Image Component Tests › SSR Lazy Loading Tests › should load the fifth image eagerly, without scrolling

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=1600"
    Received: "https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=2000"

      182 | 
      183 |   it('should load the fifth image eagerly, without scrolling', async () => {
    > 184 |     expect(await browser.elementById('eager-loading').getAttribute('src')).toBe(
          |                                                                            ^
      185 |       'https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=1600'
      186 |     )
      187 |     expect(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:184:76)

  ● Image Component Tests › Client-side Lazy Loading Tests › should load the fifth image eagerly, without scrolling

    expect(received).toBe(expected) // Object.is equality

    Expected: "https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=1600"
    Received: "https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=2000"

      182 | 
      183 |   it('should load the fifth image eagerly, without scrolling', async () => {
    > 184 |     expect(await browser.elementById('eager-loading').getAttribute('src')).toBe(
          |                                                                            ^
      185 |       'https://example.com/myaccount/foo5.jpg?auto=format&fit=max&w=1600'
      186 |     )
      187 |     expect(

      at Object.<anonymous> (integration/image-component/basic/test/index.test.js:184:76)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 9s | 8.7s | -232ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.76 | 1.76 | ✓ |
| / avg req/sec | 1420.63 | 1420.54 | ⚠️ -0.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.109 | 1.107 | 0 |
| /error-in-render avg req/sec | 2253.29 | 2257.42 | +4.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a6ce971..96b9.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 622 B | 622 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.4s | -246ms |
| nodeModulesSize | 83 MB | 83 MB | ⚠️ +1.28 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| 677f882d2ed8..769b.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-a6ce971..96b9.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.1 kB | 59.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _app-6220e08..9a40.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-4b0b5..2c91.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-5f309a..7282.js gzip | 887 B | 887 B | ✓ |
| index-57f580..c562.js gzip | 227 B | 227 B | ✓ |
| link-21c7af4..bddc.js gzip | 1.6 kB | 1.6 kB | ✓ |
| routerDirect..bd82.js gzip | 303 B | 303 B | ✓ |
| withRouter-2..e384.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.04 kB | 8.04 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _buildManifest.js gzip | 320 B | 320 B | ✓ |
| Overall change | 320 B | 320 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | Timer/next.js feat/reduce-byte-waste | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.17 MB | 5.17 MB | ✓ |

</details>

</details>
Commit: 54a2700ce9c68c91abfe43e00b10c3c16b179c3b

**Review by ijjk — APPROVED** [review]

**Pull request merged**
