### PR TITLE
Fix edge workers being re-used unexpectedly

### PR DESCRIPTION
**Pull request by ijjk**
This ensures we don't re-use edge workers locally as they are meant to be isolated. 

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

Fixes: [slack thread](https://vercel.slack.com/archives/C035J346QQL/p1665708744315109)

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a09d9ee1c083b0e5afcc8e504f2c9986c3caac69

`pnpm testheadless test/e2e/middleware-rewrites/test/index.test.ts` 
- Middleware Rewrite > should handle shallow navigation correctly (dynamic page)

<details>
<summary>Expand output</summary>

  ● Middleware Rewrite › should handle shallow navigation correctly (dynamic page)

    TIMED OUT: world

    undefined

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (e2e/middleware-rewrites/test/index.test.ts:444:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — DISMISSED** [review]

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 6b8cbc0b511046b8518f977b2212c643fced1fe8

`pnpm testheadless test/e2e/middleware-rewrites/test/index.test.ts` 
- Middleware Rewrite > should handle shallow navigation correctly (dynamic page)

<details>
<summary>Expand output</summary>

  ● Middleware Rewrite › should handle shallow navigation correctly (dynamic page)

    TIMED OUT: world

    undefined

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (e2e/middleware-rewrites/test/index.test.ts:444:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: f31a7b4cd9c722391e24541f280d5d7e42442db0

`pnpm testheadless test/e2e/middleware-rewrites/test/index.test.ts` 
- Middleware Rewrite > should handle shallow navigation correctly (dynamic page)

<details>
<summary>Expand output</summary>

  ● Middleware Rewrite › should handle shallow navigation correctly (dynamic page)

    TIMED OUT: success

    {
      "router": {
        "sdc": {},
        "isFirstPopStateEvent": true,
        "_key": "c819esz1",
        "components": {
          "/fallback-true-blog/[slug]": {
            "styleSheets": [],
            "__N_SSG": true,
            "props": {
              "pageProps": {
                "params": {
                  "slug": "first"
                },
                "time": 1665722341437
              },
              "__N_SSG": true
            },
            "route": "/fallback-true-blog/[slug]",
            "query": {
              "slug": "first"
            },
            "resolvedAs": "/fallback-true-blog/first"
          },
          "/_app": {
            "styleSheets": []
          }
        },
        "events": {},
        "pageLoader": {
          "routeLoader": {},
          "buildId": "development",
          "assetPrefix": "",
          "promisedSsgManifest": {},
          "promisedMiddlewareMatchers": {},
          "promisedDevPagesManifest": {}
        },
        "basePath": "",
        "clc": null,
        "isSsr": false,
        "isLocaleDomain": false,
        "isReady": true,
        "locales": [
          "en",
          "ja",
          "fr",
          "es"
        ],
        "defaultLocale": "en",
        "state": {
          "route": "/fallback-true-blog/[slug]",
          "pathname": "/fallback-true-blog/[slug]",
          "query": {
            "slug": "first"
          },
          "asPath": "/fallback-true-blog/first",
          "isPreview": false,
          "locale": "en",
          "isFallback": false
        },
        "_initialMatchesMiddlewarePromise": {},
        "_shallow": false,
        "_inFlightRoute": "/fallback-true-blog/first?hello=world"
      },
      "href": "http://localhost:43259/fallback-true-blog/first"
    }

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (e2e/middleware-rewrites/test/index.test.ts:444:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a5d89e5fbfb7b95d3fda13d05852a8a49d8d5ccc

`pnpm testheadless test/e2e/middleware-rewrites/test/index.test.ts` 
- Middleware Rewrite > should handle shallow navigation correctly (dynamic page)

<details>
<summary>Expand output</summary>

  ● Middleware Rewrite › should handle shallow navigation correctly (dynamic page)

    TIMED OUT: success

    {
      "router": {
        "sdc": {},
        "isFirstPopStateEvent": true,
        "_key": "j4017esa",
        "components": {
          "/fallback-true-blog/[slug]": {
            "styleSheets": [],
            "__N_SSG": true,
            "props": {
              "pageProps": {
                "params": {
                  "slug": "first"
                },
                "time": 1665724093097
              },
              "__N_SSG": true
            },
            "route": "/fallback-true-blog/[slug]",
            "query": {
              "slug": "first"
            },
            "resolvedAs": "/fallback-true-blog/first"
          },
          "/_app": {
            "styleSheets": []
          }
        },
        "events": {},
        "pageLoader": {
          "routeLoader": {},
          "buildId": "development",
          "assetPrefix": "",
          "promisedSsgManifest": {},
          "promisedMiddlewareMatchers": {},
          "promisedDevPagesManifest": {}
        },
        "basePath": "",
        "clc": null,
        "isSsr": false,
        "isLocaleDomain": false,
        "isReady": true,
        "locales": [
          "en",
          "ja",
          "fr",
          "es"
        ],
        "defaultLocale": "en",
        "state": {
          "route": "/fallback-true-blog/[slug]",
          "pathname": "/fallback-true-blog/[slug]",
          "query": {
            "slug": "first"
          },
          "asPath": "/fallback-true-blog/first",
          "isPreview": false,
          "locale": "en",
          "isFallback": false
        },
        "_initialMatchesMiddlewarePromise": {},
        "_shallow": false,
        "_inFlightRoute": "/fallback-true-blog/first?hello=world"
      },
      "href": "http://localhost:37279/fallback-true-blog/first"
    }

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (e2e/middleware-rewrites/test/index.test.ts:431:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 22453b495990b7f5d95e33b49bd4e0d42544195b

`pnpm testheadless test/integration/amphtml/test/index.test.js` 
- AMP Usage > AMP dev mode > should detect changes and refresh an AMP page
- AMP Usage > AMP dev mode > should detect changes to component and refresh an AMP page
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect changes and refresh an AMP page

    TIMED OUT: /replaced it!/

    I'm an AMP page!1665725907764AMP Power!!!{"props":{"pageProps":{}},"page":"/hmr/amp","query":{},"buildId":"development","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:375:9)

  ● AMP Usage › AMP dev mode › should detect changes to component and refresh an AMP page

    TIMED OUT: /hello/

    hi

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:388:7)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    TIMED OUT: /I'm an AMP page!/

    replaced it!

      519 |
      520 |   if (hardError) {
    > 521 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      522 |   }
      523 |   return false
      524 | }

      at check (lib/next-test-utils.js:521:11)
      at Object.<anonymous> (integration/amphtml/test/index.test.js:410:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Pull request merged**
