### PR TITLE
feat(create-next-app): let users create TS projects using prompt; enhance tests

### PR DESCRIPTION
**Pull request by ctjlewis**
I added the `--ts, --typescript` flag to create-next-app in #24655, and since then I have seen it used very frequently, including in recent issues (such as #33314).

This PR originally updated `create-next-app` to generate TypeScript projects by default, with an escape hatch for legacy functionality via `--js, --javascript`, but this implementation was rejected. Instead the flow will be:

1. `create-next-app --js, --javascript` for JS
2. `create-next-app --ts, --typescript` for TS
3. `create-next-app` (no args) prompts the user to choose either JS or TS, with TS selected by default.

https://user-images.githubusercontent.com/1657236/185043921-29c8e494-ad77-47e1-a792-42f4521d8623.mov

## Feature

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Documentation added
- [ ] Telemetry added. 
  *Note: This requires additional work and a separate PR. The Telemetry logic relies on compiled types specific to `packages/next`.*
- [x] Errors have helpful link attached, see `contributing.md`

## Tests

Tests were added for all of this behavior. 

The addition of another prompt to the flow required refactoring most of the tests for this package and there are now standardized utilities for verifying `create-next-app` output.

Checking emitted files:

- `projectFilesShouldExist({ cwd, projectName, files })`
- `projectFilesShouldNotExist({ cwd, projectName, files })`

Checking package.json deps:

- `projectDepsShouldBe({ cwd, projectName, type, deps })`

Two higher-level checks that combine the files and dependencies checks to verify a successfully emitted JS or TS project:

- `shouldBeJavascriptProject({ cwd, projectName })`
- `shouldBeTypescriptProject({ cwd, projectName })`

These utils are in `test/integration/create-next-app/lib/utils`. A global testing utility called `useTempDir()` was also added in `test/`, which can be reused throughout other package tests if needed. 

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 9e5b5e571dfa91da5c67fc63e525d8fc63133cb8

**test/integration/create-next-app/index.test.js** 
- create next app > empty directory
- create next app > should allow an example named default
- create next app > should create a project in the current directory
- create next app > should ask the user for a name for the project if none supplied
- create next app > should use npm as the package manager on supplying --use-npm

<details>
<summary>Expand output</summary>

  ● create next app › empty directory

    expect(received).toBeTruthy()

    Received: false

      55 |         ).toBeTruthy()
      56 |         expect(
    > 57 |           fs.existsSync(path.join(cwd, projectName, 'node_modules/next'))
         |                                                                          ^
      58 |         ).toBe(true)
      59 |       })
      60 |     })

      at integration/create-next-app/index.test.js:57:109
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:48:13)

  ● create next app › should allow an example named default

    expect(received).toBeTruthy()

    Received: false

      188 |     it('should fall back to default template', async () => {
      189 |       await usingTempDir(async (cwd) => {
    > 190 |         const projectName = 'fail-example'
          |                                           ^
      191 |         const res = await run(
      192 |           [projectName, '--example', '__internal-testing-retry'],
      193 |           {

      at integration/create-next-app/index.test.js:190:105
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:179:9)

  ● create next app › should create a project in the current directory

    expect(received).toBeTruthy()

    Received: false

      240 |     })
      241 |   })
    > 242 |
          | ^
      243 |   it('should exit if the folder is not writable', async () => {
      244 |     await usingTempDir(async (cwd) => {
      245 |       const projectName = 'not-writable'

      at integration/create-next-app/index.test.js:242:102
          at Array.forEach (<anonymous>)
      at integration/create-next-app/index.test.js:242:19
          at runMicrotasks (<anonymous>)
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:228:9)

  ● create next app › should ask the user for a name for the project if none supplied

    expect(received).toBeTruthy()

    Received: false

      259 |     }, 0o500)
      260 |   })
    > 261 |
          | ^
      262 |   it('should create a project in the current directory', async () => {
      263 |     await usingTempDir(async (cwd) => {
      264 |       const res = await run(['.'], { cwd })

      at integration/create-next-app/index.test.js:261:115
          at Array.forEach (<anonymous>)
      at integration/create-next-app/index.test.js:261:19
          at runMicrotasks (<anonymous>)
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:247:9)

  ● create next app › should use npm as the package manager on supplying --use-npm

    expect(received).toBeTruthy()

    Received: false

      281 |     await usingTempDir(async (cwd) => {
      282 |       const projectName = 'test-project'
    > 283 |       const res = await run([], { cwd, input: `${projectName}\n` })
          |                                                                    ^
      284 |       expect(res.exitCode).toBe(0)
      285 |
      286 |       const files = [

      at integration/create-next-app/index.test.js:283:115
          at Array.forEach (<anonymous>)
      at integration/create-next-app/index.test.js:283:19
          at runMicrotasks (<anonymous>)
      at usingTempDir (integration/create-next-app/index.test.js:22:9)
      at Object.<anonymous> (integration/create-next-app/index.test.js:266:9)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.2s | -214ms |
| buildDurationCached | 3.2s | 3.2s | -26ms |
| nodeModulesSize | 352 MB | 352 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.926 | 2.904 | -0.02 |
| / avg req/sec | 854.38 | 860.77 | +6.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.299 | 1.325 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1925 | 1886.13 | ⚠️ -38.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.2 kB | 27.2 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71 kB | 71 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.7 kB | 4.7 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.13 kB | 2.13 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.7s | -5ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +63ms |
| nodeModulesSize | 352 MB | 352 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.87 | 2.931 | ⚠️ +0.06 |
| / avg req/sec | 871.07 | 852.86 | ⚠️ -18.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.34 | 1.312 | -0.03 |
| /error-in-render avg req/sec | 1866.28 | 1905.27 | +38.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.73 kB | 4.73 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ctjlewis/next.js typescript-default | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 9e5b5e571dfa91da5c67fc63e525d8fc63133cb8

**Comment by balazsorban44** [comment]
Thank you @ctjlewis! We do like to upgrade most of our examples to TypeScript-first, so this change would make sense.

To build on this (not saying it should be part of this PR, maybe a feature request/idea), we could grab the opportunity here and use SWC, when someone opens an example PR, we could transform the example to JS that only strips down the types (.ts -> .js, remove tsconfig, .d.ts, etc.) so people not comfortable with TS for any reason would still have an option.

cc @leerob

**Comment by timneutkens** [comment]
What we talked about on Discord: it would make sense to ask what language to use as a question in the CLI and then use the selected option to download the JS or TS, that would allow both cases to be covered

**Comment by arifali123** [comment]
> What we talked about on Discord: it would make sense to ask what language to use as a question in the CLI and then use the selected option to download the JS or TS, that would allow both cases to be covered

what if we used a package like inquirer.js to choose between typescript or javascript

**Comment by ctjlewis** [comment]
Will need help in a separate PR adding telemetry information, `packages/create-next-app` throws due to `next/dist/compiled` types in `next/telemetry`.

**Comment by ctjlewis** [comment]
hate to ping manually @timneutkens - have come to find this feature is used quite frequently, and these changes would be a UX win.

`create-next-app` does not get as much attention as it should, would be good to add telemetry, just can't figure out how to get it to work outside of `packages/next`

**Comment by ctjlewis** [comment]
thanks @jescalan - any thoughts on telemetry?

**Comment by ctjlewis** [comment]
This team stepped on a year's worth of my TS-related contributions without caring to drop a line or allowing me to contribute on the autoinstall feature. I have also been trying to get this PR merged for close to a year now.

I will close this accordingly. Thanks for the big middle finger everyone!

cc @timneutkens @ijjk @jescalan 

https://github.com/vercel/next.js/pull/39838

**Pull request closed without merging**
