### PR TITLE
Fixed `getStaticPaths` example in `basic-features/pages` page

### PR DESCRIPTION
**Pull request by iNishant**

### CODE REVIEW

**Review by lfades — CHANGES_REQUESTED** [review]
This is not a fix and I actually like having one example of `getStaticPaths` around that shows the usage with a path.

**Comment by iNishant** [comment]
@lfades is there any documentation for this syntax? Do the params, in this case `id` automatically get passed to `getStaticProps`?

**Comment by lfades** [comment]
@iNishant Is not documented but it has been possible since the initial implementation

**Comment by iNishant** [comment]
@lfades I'll leave it to you guys to decide if it's a good idea to mention it in the docs or not 😃  I did confirm the syntax, it works as you mentioned.

**Pull request closed without merging**
