### PR TITLE
Add endpoint for SSG cache clear

### PR DESCRIPTION
**Pull request by adrianos10**
Hi, SSG and ISG are great features, but what is holding us from implementing them in our ecommerce solution is that we can't force refresh content of the pages after any changes are made in CMS. I was wondering if I can set up an endpoint which can handle this. Could you please verify if this approach makes any sense or am I missing something? I haven't tested dynamic routes yet but in general it seems to be working properly.

Here is an example of cURL request for this new endpoint:
`curl --location --request POST 'http://localhost:3000/api/clear-ssg-cache' \
--header 'Content-Type: application/json' \
--data-raw '{
    "pagesToRefresh": [
        "index",
        "login",
        "nest1/nest2
    ],
    "locales": [
        "en-US",
        "fr",
        "nl-NL"
    ]
}'`

Edit: I've added support for locales.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -72ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +8.02 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.079 | 2.112 | ⚠️ +0.03 |
| / avg req/sec | 1202.75 | 1183.84 | ⚠️ -18.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.322 | 1.271 | -0.05 |
| /error-in-render avg req/sec | 1890.89 | 1966.53 | +75.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| index.html gzip | 612 B | 612 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.1s | -115ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +8.02 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ⚠️ +28 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ⚠️ +28 B |
| link.js | 1.08 MB | 1.08 MB | ⚠️ +28 B |
| routerDirect.js | 1.07 MB | 1.07 MB | ⚠️ +28 B |
| withRouter.js | 1.07 MB | 1.07 MB | ⚠️ +28 B |
| Overall change | 5.27 MB | 5.27 MB | ⚠️ +140 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -117ms |
| nodeModulesSize | 42.7 MB | 42.7 MB | ⚠️ +8.02 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.042 | 2.058 | ⚠️ +0.02 |
| / avg req/sec | 1224.24 | 1214.73 | ⚠️ -9.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.304 | 1.344 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1916.92 | 1859.89 | ⚠️ -57.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 597-74632e79..1d47.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.6 kB | 6.6 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60.1 kB | 60.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 593 B | 593 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "PkEQjGZo9jnhikTLcoQ8X",
+        "buildId": "dKtWw8S_2YXWUjJwlwnFs",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_buildManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_ssgManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "PkEQjGZo9jnhikTLcoQ8X",
+        "buildId": "dKtWw8S_2YXWUjJwlwnFs",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_buildManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_ssgManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "PkEQjGZo9jnhikTLcoQ8X",
+        "buildId": "dKtWw8S_2YXWUjJwlwnFs",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_buildManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/PkEQjGZo9jnhikTLcoQ8X/_ssgManifest.js"
+      src="/_next/static/dKtWw8S_2YXWUjJwlwnFs/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 6573be4b1cd02c24e2f647a2d177bc85c33fec25

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.2s | -126ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +9.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.934 | 1.971 | ⚠️ +0.04 |
| / avg req/sec | 1292.49 | 1268.25 | ⚠️ -24.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.182 | 1.196 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2114.8 | 2090.77 | ⚠️ -24.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 13.3s | 12.8s | -423ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +9.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ⚠️ +28 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.5 kB | 10.5 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ⚠️ +28 B |
| link.js | 1.08 MB | 1.08 MB | ⚠️ +28 B |
| routerDirect.js | 1.07 MB | 1.07 MB | ⚠️ +28 B |
| withRouter.js | 1.07 MB | 1.07 MB | ⚠️ +28 B |
| Overall change | 5.27 MB | 5.27 MB | ⚠️ +140 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.3s | ⚠️ +56ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +9.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.988 | 2.014 | ⚠️ +0.03 |
| / avg req/sec | 1257.63 | 1241.47 | ⚠️ -16.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.258 | 1.266 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1986.97 | 1974.57 | ⚠️ -12.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| 597-74632e79..1d47.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.6 kB | 6.6 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60.1 kB | 60.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 326 B | 326 B | ✓ |
| Overall change | 326 B | 326 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrianos10/next.js feature/ssg-cache-cleanup | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 581 B | 581 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "aOhlfCJ3uPqshAvGpMo24",
+        "buildId": "EHp1EamrROJSVoSuQdJlu",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_buildManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_ssgManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -48,7 +48,7 @@
         "props": { "pageProps": {} },
         "page": "/link",
         "query": {},
-        "buildId": "aOhlfCJ3uPqshAvGpMo24",
+        "buildId": "EHp1EamrROJSVoSuQdJlu",
         "isFallback": false,
         "gip": true
       }
@@ -82,11 +82,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_buildManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_ssgManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/withRouter",
         "query": {},
-        "buildId": "aOhlfCJ3uPqshAvGpMo24",
+        "buildId": "EHp1EamrROJSVoSuQdJlu",
         "isFallback": false,
         "gip": true
       }
@@ -77,11 +77,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_buildManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_buildManifest.js"
       async=""
     ></script>
     <script
-      src="/_next/static/aOhlfCJ3uPqshAvGpMo24/_ssgManifest.js"
+      src="/_next/static/EHp1EamrROJSVoSuQdJlu/_ssgManifest.js"
       async=""
     ></script>
   </body>
```
</details>
</details>
Commit: 26439ef78e023280b892f8097d4441f3c3cd87c0

**Comment by DennieMello** [comment]
As I understand it, it would be preferable to do a second revalidation than to clear the cache.

**Comment by FSaldanha** [comment]
Maybe you'd want to check this discussion out: #22384

There, we're proposing to forcefully make cache data entry stale, rather than deleting it.

**Review by ijjk — COMMENTED** [review]
Hi, this should now be resolved by the on-demand ISR support! https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta

**Pull request closed without merging**
