### PR TITLE
Example for static hosting on hostinger

### PR DESCRIPTION
**Pull request by mayank1513**
Added example for static hosting on hostinger and similar services also provides work around for dynamic routes

### CODE REVIEW

**Comment by mayank1513** [comment]
Hi @ijjk, thanks for adding the label. I am not able to assign this to myself. Can you please assign this PR to me and also add any other fields, e.g., project, which might be required?

Thanks!

**Review by ijjk — COMMENTED** [review]
Hi, I don't think this example is needed as it's just showing a static build which most examples are already capable of, thanks though!

**Comment by mayank1513** [comment]
Thanks for the response. However, there are no examples showing how to
support dynamic routes while generating static export.

**Comment by ijjk** [comment]
The workaround being shown for dynamic routes isn't ideal, instead a rewrite should be configured on the static host to handle dynamic routing at that level.

**Comment by mayank1513** [comment]
Thanks. I do understand this is not ideal but many static hosts don't
support rewrite with dynamic routes or charges extra for that.

**Comment by mayank1513** [comment]
Extra cost come from turning up cloud functions to support dynamic routes.

**Pull request closed without merging**
