### PR TITLE
Add syntax highlighting to debug error page

### LINKED ISSUE #191: Syntax Highlight compilation errors
Code frame of babel compilation errors includes ansi colors, so we'd like to add syntax highlight instead of just stripping it.
We can use https://www.npmjs.com/package/ansi-html

### PR DESCRIPTION
**Pull request by dstreet**
Fixes #191.
Also addresses #123, with comments from PR #124 to make ansi colors easier to see.

image

### CODE REVIEW

**Comment by nkzawa** [comment]
Awesome, thank you!!!

**Comment by nkzawa** [comment]
@dstreet I'm sorry, but I didn't know that our team was preparing for a new color scheme for this page. So revert it for now.

**Comment by dstreet** [comment]
@nkzawa you need me to revert that commit, or are you going to revert the merge?

**Comment by sedubois** [comment]
@dstreet it has been reverted: https://github.com/zeit/next.js/pull/197

**Comment by nkzawa** [comment]
@dstreet I already did. 

We reverted it for releasing 1.1.0, but will reapply your commits and update the color scheme soon. Thanks again for your great work!

**Pull request merged**
