### PR TITLE
Fix _document and getInitialProps with React 18

### LINKED ISSUE #35711: _document.js does not work for React.JS v18
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.2
      react: 18.0.0
      react-dom: 18.0.0
```

### Describe the Bug

`_document.js` does not work for React.JS `v18`

### Expected Behavior

`_document.js` and components such as `next/head` should work for React.JS v18

### To Reproduce

create a basic next.js project and create a `_document.js` file in `/pages`.

### PR DESCRIPTION
**Pull request by shuding**
Fixes #35711

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 87f9569a5ac485fe0a168a85f6061d85415aa0a4

`yarn testheadless test/e2e/next-head/index.test.ts` 
- should set-up next > should have correct head tags in initial document
- should set-up next > should have correct head tags after hydration

<details>
<summary>Expand output</summary>

  ● should set-up next › should have correct head tags in initial document

    TypeError: Cannot read properties of undefined (reading 'content')

      28 |
      29 |     for (let i = 1; i < 5; i++) {
    > 30 |       expect($(`meta[name="test-head-${i}"]`).attr()['content']).toBe('hello')
         |                                                   ^
      31 |     }
      32 |   })
      33 |

      at Object.<anonymous> (e2e/next-head/index.test.ts:30:51)

  ● should set-up next › should have correct head tags after hydration

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "meta[name="test-head-1"]"
    ============================================================

      304 |     return this.chain(() => {
      305 |       return page
    > 306 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      307 |         .then(async (el) => {
      308 |           // it seems selenium waits longer and tests rely on this behavior
      309 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:306:10

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
## Failing test suites 
Commit: a5fd1d7e58463b8dd92df111bc2ae71a34224ad1

`yarn testheadless test/integration/async-modules/test/index.test.js` 
- Async modules > production mode > can render async AMP pages

<details>
<summary>Expand output</summary>

  ● Async modules › production mode › can render async AMP pages

    TIMED OUT: just now

    11 seconds ago

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/async-modules/test/index.test.js:85:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| buildDuration | 21.2s | 21s | -199ms |
| buildDurationCached | 8.3s | 8.1s | -142ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +2.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.567 | 4.405 | -0.16 |
| / avg req/sec | 547.35 | 567.51 | +20.16 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.344 | 2.391 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1066.37 | 1045.66 | ⚠️ -20.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| buildDuration | 27.7s | 26.1s | -1.6s |
| buildDurationCached | 8.2s | 8.1s | -136ms |
| nodeModulesSize | 467 MB | 467 MB | ⚠️ +2.31 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.577 | 4.614 | ⚠️ +0.04 |
| / avg req/sec | 546.19 | 541.78 | ⚠️ -4.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.338 | 2.329 | -0.01 |
| /error-in-render avg req/sec | 1069.45 | 1073.25 | +3.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.56 kB | 2.56 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js shu/1508 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: a5fd1d7e58463b8dd92df111bc2ae71a34224ad1

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 00f408b7733647f95de852d252a69f3f5e7d15dd

`yarn testheadless test/integration/async-modules/test/index.test.js` 
- Async modules > production mode > can render async AMP pages

<details>
<summary>Expand output</summary>

  ● Async modules › production mode › can render async AMP pages

    TIMED OUT: just now

    11 seconds ago

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/async-modules/test/index.test.js:85:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Review by huozhi — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by kachkaev** [comment]
I still need to investigate this, but it seems that `styled-components` example is now broken in Next.js `12.1.2` and `12.1.3` (using React `18.0.0`, but I’m not sure if this is relevant).

Here is the code:

https://github.com/vercel/next.js/blob/9f9214abe58079e92cb42d50f537587d364e58f3/examples/with-styled-components/pages/_document.js#L5-L29

For some reason, server-side styles are no longer generated, so the page looks unstyled till it is hydrated on the client. Reverting to `12.1.1` helps. Does anyone see the same issue?

**Pull request merged**
