### PR TITLE
Config circleci build

### PR DESCRIPTION
**Pull request by ghost**
This PR update node version for circleci regarding https://github.com/zeit/next.js/pull/5490.

Details: 
* https://github.com/nodejs/Release#end-of-life-releases
* https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions

image

### CODE REVIEW

**Comment by timneutkens** [comment]
Can we run tests on 2 node versions?

**Comment by noelyoo** [comment]
@timneutkens Sure, Which one will those versions be?
i) `9.10.0` and`10` 
ii) `8`and `10`

**Comment by noelyoo** [comment]
With `node:10-browsers` the circleci test fails. I will share the log that different between node v8 and v10. Would anyone shed some lights on?

### Log (node v10: failing)
``` 
SyntaxError: /home/circleci/repo/test/integration/basic/pages/hmr/about.js: Unterminated JSX contents (6:10)

  4 |       <p>
  5 |         This is the about page.
> 6 |       </p>
    |           ^
  7 |     div
  8 |   )
  9 | }
    at _class.raise (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3939:15)
    at _class.jsxReadToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3271:16)
    at _class.readToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3644:21)
    at _class.nextToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4141:12)
    at _class.next (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4077:10)
    at _class.eat (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4082:12)
    at _class.expect (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5236:10)
    at _class.jsxParseClosingElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3550:12)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3569:39)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3573:34)
    at _class.jsxParseElement (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3626:19)
    at _class.parseExprAtom (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3633:21)
    at _class.parseExprSubscripts (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5924:21)
    at _class.parseMaybeUnary (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5903:21)
    at _class.parseExprOps (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5812:21)
    at _class.parseMaybeConditional (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5784:21)
    at runLoaders (/home/circleci/repo/node_modules/webpack/lib/NormalModule.js:286:20)
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.err (/home/circleci/repo/node_modules/babel-loader/lib/index.js:45:103)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ModuleBuildError: Module build failed (from /home/circleci/repo/packages/next/dist/build/webpack/loaders/next-babel-loader.js):
SyntaxError: /home/circleci/repo/test/integration/basic/pages/hmr/about.js: Unterminated JSX contents (6:10)

  4 |       <p>
  5 |         This is the about page.
> 6 |       </p>
    |           ^
  7 |     div
  8 |   )
  9 | }
    at _class.raise (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3939:15)
    at _class.jsxReadToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3271:16)
    at _class.readToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3644:21)
    at _class.nextToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4141:12)
    at _class.next (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4077:10)
    at _class.eat (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4082:12)
    at _class.expect (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5236:10)
    at _class.jsxParseClosingElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3550:12)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3569:39)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3573:34)
    at _class.jsxParseElement (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3626:19)
    at _class.parseExprAtom (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3633:21)
    at _class.parseExprSubscripts (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5924:21)
    at _class.parseMaybeUnary (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5903:21)
    at _class.parseExprOps (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5812:21)
    at _class.parseMaybeConditional (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5784:21)
    at runLoaders (/home/circleci/repo/node_modules/webpack/lib/NormalModule.js:286:20)
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.err (/home/circleci/repo/node_modules/babel-loader/lib/index.js:45:103)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  console.log test/lib/next-webdriver.js:16
    > Complete loading browser with url: http://localhost:37336/hmr/about

 WAIT  Compiling...

  console.log test/lib/next-webdriver.js:9
    > Start loading browser with url: http://localhost:37336/hmr/about

[11:55:29 AM] Compiling server
[11:55:29 AM] Compiling client
[11:55:30 AM] Compiled client in 186ms
 DONE  Compiled successfully in 210ms

[11:55:30 AM] Compiled server in 372ms
  console.log test/lib/next-webdriver.js:16
    > Complete loading browser with url: http://localhost:37336/hmr/about

 WAIT  Compiling...

  console.log test/lib/next-webdriver.js:9
    > Start loading browser with url: http://localhost:37336/hmr/contact
```

### Log (node v8: passing)
```
SyntaxError: /home/circleci/repo/test/integration/basic/pages/hmr/about.js: Unterminated JSX contents (6:10)

  4 |       <p>
  5 |         This is the about page.
> 6 |       </p>
    |           ^
  7 |     div
  8 |   )
  9 | }
    at _class.raise (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3939:15)
    at _class.jsxReadToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3271:16)
    at _class.readToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3644:21)
    at _class.nextToken (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4141:12)
    at _class.next (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4077:10)
    at _class.eat (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:4082:12)
    at _class.expect (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5236:10)
    at _class.jsxParseClosingElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3550:12)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3569:39)
    at _class.jsxParseElementAt (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3573:34)
    at _class.jsxParseElement (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3626:19)
    at _class.parseExprAtom (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:3633:21)
    at _class.parseExprSubscripts (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5924:21)
    at _class.parseMaybeUnary (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5903:21)
    at _class.parseExprOps (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5812:21)
    at _class.parseMaybeConditional (/home/circleci/repo/node_modules/@babel/parser/lib/index.js:5784:21)
    at runLoaders (/home/circleci/repo/node_modules/webpack/lib/NormalModule.js:286:20)
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/repo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.err (/home/circleci/repo/node_modules/babel-loader/lib/index.js:45:103)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
 WAIT  Compiling...

  console.log test/lib/next-webdriver.js:9
    > Start loading browser with url: http://localhost:38586/hmr/contact
```

**Comment by noelyoo** [comment]
@timneutkens I added ci test with `node-10-browsers` but the ci test failed at `should detect syntax errors and recover`. I think this can be fixed in another PR.

**Comment by timneutkens** [comment]
Thank you very much @noelyoo!

**Pull request merged**
