### PR TITLE
WIP: Using React.createContext instead of ChildContext

### PR DESCRIPTION
**Pull request by chrislloyd**
This is in respose to #5716. I'm tackling some of the smaller instances first just to get a sense of the project, coding style, tests etc.

It seemed like there was a little discussion about whether this change would alienate Preact and Inferno users however that's a decision for somebody else to make - I for one would prefer to take advantage of the latest and greatest React features.

The test plan is pretty simple - it's a refactoring so existing tests shouldn't break. Also completion milestone is removing `prop-types` as a dependency.

### TODO

- [x] `headManager`
- [ ] `loadable`
- [ ] `router`
- [x] `_documentProps`

Note: I'm going to ignore the usage of legacy `contextTypes` in the examples as they don't add directly to Next's bundle size and I'm sure that each example library will have different best practices on how to update to React 17.

### CODE REVIEW

**Comment by chrislloyd** [comment]
Great yeah - seeing as `headManager` and `documentProps` are quite simple will keep this together (unless you feel strongly) but happy to create separate PRs for both loadable and router (which I suspect will be more involved). Thanks for the review!

**Comment by chrislloyd** [comment]
Also, is there a way to run the integration tests easily locally? They've been grinding my laptop to a halt because they spawn a tonne of Chrome processes.

**Comment by timneutkens** [comment]
>  seeing as headManager and documentProps are quite simple will keep this together (unless you feel strongly)

I'd like to split them for the reason that we can then compare bundle size / if everything is bundled correctly

**Comment by chrislloyd** [comment]
Closing in favor of #5945. Again, thanks for the review @timneutkens!

**Pull request closed without merging**
