### PR TITLE
(Example) Remove redirects plugin from Sitecore XM Cloud example

### PR DESCRIPTION
**Pull request by ah100101**
### What?

This PR removes the `plugins/redirects.ts` file from the Sitecore XM Cloud example project.

### Why?

The redirects plugin performs a middleware fetch to the Sitecore Delivery API for Sitecore-managed redirects. This adds unnecessary latency to all user requests. The Sitecore XM Cloud demo does not use these redirects.

### How?

Removing this middleware plugin removes the fetch. In order to perform optimized redirect look ups from Sitecore, consider pushing redirect data from Sitecore via webhook to Vercel Edge Config.

Below are links to related Sitecore and Vercel documentation:

- [Sitecore XM Cloud Webhooks](https://doc.sitecore.com/xmc/en/developers/xm-cloud/webhooks.html)
- [Vercel Edge Config](https://vercel.com/docs/storage/edge-config)

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 76d40eff1e3f7a99e1e57a5e55d1b023541e1905

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by eps1lon — COMMENTED** [review]
> Removing this middleware plugin removes the fetch.

How is this file used in the first place? I don't see it referenced in the example

**Comment by ah100101** [comment]
> > Removing this middleware plugin removes the fetch.
> 
> How is this file used in the first place? I don't see it referenced in the example

Hey @eps1lon - Sitecore's XM Cloud accelerator's build runs a bootstrap script which creates the plugins in `temp/middleware-plugins` which is then imported into middleware. Removing the redirects plugin from `lib` removes it from being included.

**Comment by eps1lon** [comment]
So they were used but that's no longer the recommended pattern?

**Comment by ah100101** [comment]
> So they were used but that's no longer the recommended pattern?

Correct. Particularly within the context of this example, there are no redirects stored in a new XM Cloud instance and having this middleware included by default means that a fetch is being performed to Sitecore for no data.

**Review by eps1lon — APPROVED** [review]

**Pull request merged**
