### PR TITLE
Use nonce attribute for all scripts and preloads if provided

### PR DESCRIPTION
**Pull request by novascreen**
When implementing a strict CSP with nonces and `strict-dynamic`, every script and preload requires a nonce.

https://csp.withgoogle.com/docs/strict-csp.html

### CODE REVIEW

**Comment by jlecomte** [comment]
LGTM. Can we get this in soon? Because of this bug, I currently have to add `unsafe-inline` to the `script-src` section of my CSP policy, which makes the entire policy somewhat useless... Thanks!

**Review by jlecomte — APPROVED** [review]

**Review by timneutkens — CHANGES_REQUESTED** [review]
Can you add a test for this in test/integration/app-document?

**Comment by novascreen** [comment]
@timneutkens i added a test, i believe it tests all instances except for the dynamic chunks, not sure how to test those inside of the app-document test suite

**Comment by timneutkens** [comment]
@novascreen that's fine, no worries 👍

**Review by timneutkens — APPROVED** [review]

**Review by timneutkens — APPROVED** [review]

**Comment by joaovieira** [comment]
This is great. But there is no documentation at all. I believe everyone should be doing this, so an example in the docs would be much appreciated. Thanks.

**Comment by novascreen** [comment]
@joaovieira there are some details in the README and an example now:
https://github.com/zeit/next.js/tree/canary/examples/with-strict-csp

**Pull request merged**
