### PR TITLE
Add "postpone" prop to NextScript

### PR DESCRIPTION
**Pull request by callumlocke**
## Overview

```jsx
<NextScript postpone />
```

With `postpone` enabled, clientside Next scripts will **not** be loaded automatically on page load. Instead, a global function `__NEXT_START` is exported. It's up to the developer to call `__NEXT_START()` whenever they are ready.

## Why would someone want this?

It allows precise control of page bootstrapping at runtime. You can now write custom clientside JS to decide **when and if** to hydrate your React app. For example you might want to polyfill some features first (asynchronously, if necessary), or otherwise prepare the environment in some way. Or you might even choose to opt out of clientside Next entirely (and fall back to static HTML) based on feature detection.

## Implementation notes

Scripts are now injected dynamically, using the same bulletproof approach used by the Google Analytics snippet.

I believe this is a non-breaking change. Although the bootstrap snippet has changed, the default behaviour should be the same as before.

Implements #2787.

### CODE REVIEW

**Comment by callumlocke** [comment]
Is there any interest in this PR, if I fix the new conflict?

**Comment by callumlocke** [comment]
I have rewritten this PR. It's now based on the `canary` branch. I've also improved the naming (changed `inactive` to `postpone`, which is clearer imo).

**Comment by sventschui** [comment]
Can we expect this to be merged soon?

**Comment by arunoda** [comment]
This is a good question and needed by some users.
We don't like to introduce more API like this. It makes the Next.js core a bit bloated with these small API.

So, here's my suggestion.
User our custom document feature. Instead of using our [NextScript](https://github.com/zeit/next.js/blob/canary/server/document.js#L119) use a custom NextScript (or extend the our one)

If needed, you can publish ^^^ custom NextScript to NPM as well.

**Pull request closed without merging**
