### PR TITLE
chore(docs): refactor README.md

### PR DESCRIPTION
**Pull request by Marukome0743**
# Summary
Remove redundant html element and css.
Add alt text to images.
Both old and new README.md have the same appearance. 

## Description
I changed some parts.

### 1. Insert `align="center"` into only top `<div>` tag
The all of logo, title, and badges are center.
Then it doesn't need to call at every element.

### 2. Move `<h1>` tag outside `<a>` tag
The title doesn't have link even if inside `<a>` tag when it's wrapped heading element.
So put it out for the readability.

### 3. Use image alt text instead of aria-label
Alt text is displayed on the page if the images can't be loaded.
That's why I prefer alt text to aria-label.
In addition, the screen reader still reads the same words after updating.

### Improving Documentation

- [x] Run `pnpm prettier-fix` to fix formatting issues before opening the PR.
- [x] Read the Docs Contribution Guide to ensure your contribution follows the docs guidelines: https://nextjs.org/docs/community/contribution-guide

x-ref: [\: The Image Embed element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) | mdn web docs

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 6e67a5d958546ff32c8b6f2783af81a5467a272f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by ijjk — CHANGES_REQUESTED** [review]
It looks like this doesn't apply as expected. 

CleanShot 2024-10-01 at 10 58 44@2x

**Comment by Marukome0743** [comment]
> It looks like this doesn't apply as expected.

As you say, GitHub `Display the rich diff` shows left align items.
However, the output results are correctly center align because `align="center"` parse `text-align: -webkit-center` css.

I'm not sure why GitHub rich diff shows different preview.
But `text-align: -webkit-center` affects the every child elements.

**Review by ijjk — APPROVED** [review]
Ah yea looks like a quirk of the diff view, seems fine in full view

**Pull request merged**
