### PR TITLE
Update @types/node everywhere to >= 14.18.16, >= 16.11.15.

### PR DESCRIPTION
**Pull request by tjni**
I'm interested in basing work off of the following commit:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57620

Note: This also requires updating `tar` and `@types/tar`.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| buildDuration | 15.1s | 14.9s | -188ms |
| buildDurationCached | 6.1s | 6.1s | ⚠️ +51ms |
| nodeModulesSize | 463 MB | 463 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.453 | 3.461 | ⚠️ +0.01 |
| / avg req/sec | 724.08 | 722.43 | ⚠️ -1.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.142 | 1.15 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2189.03 | 2174.16 | ⚠️ -14.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ⚠️ +6 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.71 kB | 5.71 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.64 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 526 B | 528 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -7215,7 +7215,7 @@
             value.forEach(function(item) {
               return result.append(key, stringifyUrlQueryParam(item));
             });
-          } else {
+          } else if (value !== undefined) {
             result.set(key, stringifyUrlQueryParam(value));
           }
         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| buildDuration | 16.9s | 16.8s | -66ms |
| buildDurationCached | 6s | 6s | -6ms |
| nodeModulesSize | 463 MB | 463 MB | ⚠️ +300 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.465 | 3.467 | 0 |
| / avg req/sec | 721.49 | 721.15 | ⚠️ -0.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.151 | 1.143 | -0.01 |
| /error-in-render avg req/sec | 2171.15 | 2188.16 | +17.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | -3 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.9 kB | 72.9 kB | -3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.76 kB | 5.76 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.76 kB | 2.76 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.5 kB | 16.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tjni/next.js update-node-types | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 543 B | 542 B | -1 B |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -7215,7 +7215,7 @@
             value.forEach(function(item) {
               return result.append(key, stringifyUrlQueryParam(item));
             });
-          } else {
+          } else if (value !== undefined) {
             result.set(key, stringifyUrlQueryParam(value));
           }
         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-ac58a1e29dd8158c.js"
+      src="/_next/static/chunks/main-058499fbe967054a.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
Commit: 0351bfa7873567941f16938fe360fcd64ee2231f

**Comment by tjni** [comment]
I opened [a discussion](https://github.com/vercel/next.js/discussions/36663) to ask about the type issue. In the meantime, I added a commit to ignore those couple of type errors. Would a maintainer be willing to start the workflows?

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8467d60f5f35c58210e1eaf35f16021eda791544

`yarn testheadless test/integration/cli/test/index.test.js` 
- CLI Usage > info > should print output

<details>
<summary>Expand output</summary>

  ● CLI Usage › info › should print output

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "warn  - Latest canary version not detected, detected: \"12.1.7-canary.1\", newest: \"12.1.7-canary.3\".
            Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
            Read more - https://nextjs.org/docs/messages/opening-an-issue
    "

      496 |       // warning will show so skip this check for the stable release
      497 |       if (pkg.version.includes('-canary')) {
    > 498 |         expect(info.stderr || '').toBe('')
          |                                   ^
      499 |       }
      500 |       expect(info.stdout).toMatch(
      501 |         new RegExp(`

      at Object.<anonymous> (integration/cli/test/index.test.js:498:35)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by tjni** [comment]
I do not have the time to work on this.

**Pull request closed without merging**
