### PR TITLE
Add redux code splitting example

### PR DESCRIPTION
**Pull request by HaNdTriX**
## Issue 

In a more complex app there might be two kinds of states.

### 1. global-state

This state will persist even when a user changes routes. One example could be the some jwt reducer, that manages the authentication token of our app.

### 2. local-state

This state is route specific. We only need it for a specific route. One example could be a form reducer that manages a contact form on the contact page.

Next.js already solves code splitting on route basis pretty well. Since local-state reducer are only needed on a specific route it makes sense to add them to the global redux state on demand.

## Solution

This example uses an advanced higher order component ([`withRedux`](https://github.com/HaNdTriX/next.js/blob/master/examples/with-redux-code-splitting/hocs/withRedux.js)), that merges reducers on demand. After decorating the PageComponent with this hoc you can use the static method (`getLocalReducers`) to add reducers to the redux store.

**Example:**

```javascript
class IndexPage extends React.Component {

  static getLocalReducers () {
    return {
      localReducer1,
      localReducer2,
      ...
    }
  }

  static getInitialProps ({ store }) {
    ...
  }

  render () {
    ...
  }
}
```

[more info](https://github.com/HaNdTriX/next.js/tree/master/examples/with-redux-code-splitting)

## Todo:

Before we merge this PR we should be clear about the following questions:

- [ ] Are there better ways than adding a new API (`getLocalReducers`) to the `PageComponents`?
- [ ]  Should we improve the documentation?
- [ ]  Should we move [`withRedux.js`](https://github.com/HaNdTriX/next.js/blob/master/examples/with-redux-code-splitting/hocs/withRedux.js) into a separate package? 
- [ ] Should we update the [with-redux](https://github.com/zeit/next.js/tree/master/examples/with-redux) example instead of creating a new one?
- [ ] Should we keep local reducers instead of removing them from the store?

### CODE REVIEW

**Comment by HaNdTriX** [comment]
@huzidaha & @kirill-konshin feel free to add this functionality to your wrapper packages.

* [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper)
* [next-connect-redux](https://github.com/huzidaha/next-connect-redux)

**Comment by HaNdTriX** [comment]
After working with this approach I believe we should change this PR.

* Just keep focus on extending the global store
* We should persist a reducer once it has been applied to the store
* Rename localReducers to async asyncReducers

Since I don't have time I'll close this PR until people showed interest in this topic.

**Comment by flipxfx** [comment]
I think this example is more useful than the current `with-redux-code-splitting` example as it uses straight redux rather than "fast-redux".

**Comment by kirill-konshin** [comment]
@flipxfx PR is welcome :) or else you can create a separate ticket with detailed explanation what has to be done.

**Pull request closed without merging**
