### PR TITLE
Make sure routes are always lowercase

### LINKED ISSUE #139: Next provides two URLs with different behaviors when page names are capitalized
E.g if `pages/index.js` is renamed to `pages/Index.js`, it seems HMR doesn't work any more.

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #139. I like the idea of only having lower cased routes, even if the file has a different casing. Also, we might want to do a 301 redirect from the url with uppercasing to the lowercase version.

cc @sedubois

### CODE REVIEW

**Review by sedubois — APPROVED** [review]
👍

**Comment by frol** [comment]
What is the point? If one likes to name files in camelCase, one would love to see them in camelCase in the routes... If I have my page named as an abbreviation, I would still like it to have it in the routes as an abbreviation. Don't make this to be the default behaviour, please!

**Comment by arunoda** [comment]
May be this is related. See: https://github.com/zeit/next.js/pull/697/files

I think I agree with @frol here. What we need to serve is the using the actual filename in filesystem.

**Comment by timneutkens** [comment]
btw, in my tests `pages/About.js` would only serve on `/About` and not on `/about`, so it could be that the mentioned PR fixes the double pages behaviour mentioned in the ticket @arunoda.

**Comment by timneutkens** [comment]
@sedubois in that case, would you mind not having all lowercase routes?

**Comment by sedubois** [comment]
@timneutkens as long as https://github.com/zeit/next.js/issues/139 is fixed, I don't mind. At the moment I'm not using uppercase in my `pages/` directory.

**Comment by timneutkens** [comment]
Lets close this then 👍

**Comment by Pkmmte** [comment]
Does this also apply to query parameters? I can't seem to get case-sensitive parameters. 

In my case, I'm expecting a short Base64 token being passed for email confirmation, which is not possible with all lowercase.

**Pull request closed without merging**
