### PR TITLE
fix: `<Script>` with `beforeInteractive` strategy ignores additional attributes in App Router

### LINKED ISSUE #49830: [NEXT-1304] <Script> with `beforeInteractive` strategy ignores additional attributes in app router
_Note: Updated on August 24, 2023, with latest version of Next.js._

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Script optimization (next/script)

### Link to the code that reproduces this issue

https://github.com/victorandree/next-script-before-interactive-attributes-app-dir

### To Reproduce

Setup a project with the app directory and in the root layout, use `<Script>` with `strategy="beforeInteractive"` and pass additional attributes. The additional attributes are not included in the resulting script tag.

### Describe the Bug

When using the `<Script>` tag from `next/script` in the root layout of the app directory, additional attributes are not included if you use `strategy="beforeInteractive"`:

```jsx
import Script from 'next/script';

export default function RootLayout({ children }) {
  return (
    <html>
      <head />
      <body>
        {children}
        <Script
          strategy="beforeInteractive"
          src="https://example.com/script.js"
          id="example-script"
          nonce="XUENAJFW"
          data-test="script"
        />
      </body>
    </html>
  );
}
```

A second point is that the `<script>` tag is not part of the HTML from the server, but is only added as (1) a `<link rel="preload">` tag and (2) to a `self.__next_s` array and (3) as part of server component 'chunks', before it's rendered into the DOM. 

Including such a script tag in `pages/_document` will render it with additional attributes (not reproduced) and as a script tag "directly". This issue therefore only affects the app directory.

A possible workaround is to include the `script` tags directly in `head` of your root layout:

```jsx
export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <script
          src="https://example.com/script.js"
          id="example-script"
          nonce="XUENAJFW"
          data-test="script"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
```

For visibility, I encountered this while trying to install the OneTrust cookie consent snippet on a Next.js site, which requires passing an identifier as `data-domain-script` to a `script` tag.

### Expected Behavior

The documented behavior of the `<Script>` tag is that it includes additional attributes (see ["Additional Attributes" on the "Script Optimization" page of the App router documentation](https://nextjs.org/docs/app/building-your-application/optimizing/scripts#additional-attributes)).

I also think it's a bit strange that the script tag is not rendered directly to the HTML from the server, since "before interactive" scripts are typically used for consent management (that's the example use case provided by the documentation), where it's important that they're inserted early.

I'd expect additional attributes to be included, even if I use it in the app directory.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

<sub>[NEXT-1304](https://linear.app/vercel/issue/NEXT-1304/script-with-beforeinteractive-strategy-ignores-additional-attributes)</sub>

### PR DESCRIPTION
**Pull request by zbauman3**
### What?

Currently, `next/script` in the App Router does not behave as the docs describe in the [Additional Attributes](https://nextjs.org/docs/app/building-your-application/optimizing/scripts#additional-attributes) section – it does not pass on all additional attributes when `strategy="beforeInteractive"` ([#49830](https://github.com/vercel/next.js/issues/49830)). 

### Why?

The props from the `<Script>` component were not passed on to the underlying script loader (`self.__next_s`).

### How?

I've added the missing props to the object that is `push`ed to `self.__next_s`.

NEXT-1304
Fixes #49830

### CODE REVIEW

**Comment by zbauman3** [comment]
Hey @timneutkens, @ijjk, @shuding, @huozhi, @feedthejim, @ztanner, @wyattjoh 👋 

I was wondering if I could get a review on this PR? This fixes a bug in the App Router when using `<Script>` with `beforeInteractive`. See https://github.com/vercel/next.js/issues/49830

**Review by huozhi — COMMENTED** [review]
Hi, can you add a test for testing the additional attributes

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e923551c9080b84af7901ee083eef8904fd35c80

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: e923551c9080b84af7901ee083eef8904fd35c80

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.9s | N/A |
| buildDurationCached | 7.2s | 6.1s | N/A |
| nodeModulesSize | 202 MB | 202 MB | ⚠️ +900 B |
| nextStartRea..uration (ms) | 407ms | 431ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.4 kB | 28.5 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 541 B | 540 B | N/A |
| withRouter.html gzip | 524 B | 522 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.8 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | zbauman3/next.js patch-3 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.38 kB | 9.38 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.65 kB | 9.65 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: e923551c9080b84af7901ee083eef8904fd35c80

**Review by huozhi — APPROVED** [review]
Thanks!

**Comment by zbauman3** [comment]
@huozhi

No prob – thank you for the speedy response!

**Pull request merged**
