### PR TITLE
feat(cna): standardize viewport sizing

### PR DESCRIPTION
**Pull request by ctjlewis**
Original fix from #28096 was overwritten in #43482.

### Goal

Our goal is to set the starter pages up so that they behave predictably with respect to viewport size. The rule is:

**The page container should be *at least as tall* as the viewport.** 

In CSS:

```css
/** <html> and <body> are always page containers. */
html,
body,
/** #__next wraps rendered pages. */
#__next,
/** Pages should wrap content with <main> in order to fill the viewport. */
main {
  width: 100%;
  min-height: 100vh;
}
```

See:
  - https://twitter.com/rauchg/status/1716226300602655119
  - https://twitter.com/ctjlewis/status/1716227338835489027

Discussion regarding units (Jhey - is `svh` preferable to `vh` here?):

> @rauchg: Isn’t 100dvh what you’d most likely want now?

> @ctjlewis: i think using dynamic could cause the viewport to resize as you scroll. we just want to properly size the viewport to be “at least as tall as the device screen,” so “min-height: 100vh” is the canonical approach i usually use.

> @jh3y: Totally right 🤙 The dynamic unit will adapt as UA UI resizes and tucks away on devices (where applicable). Using a min of 100svh is sometimes a safe option depending on if any sticky header/nav/footer elements exist.

cc @jh3y @leerob @rauchg 

---

The template logic strayed far from grace with #46927: Rather than utilizing the default template for files common to all templates, the same CSS update had to be applied *8 times* here. 

**This is a big mistake** - the default-override template pattern is meant to prevent duplicate copies of template files from diverging over time, a problem that was originally devastating for AWS Amplify CLI (https://github.com/aws-amplify/amplify-cli/pull/7219), which is why I brought the pattern here via #42012.  I'm owning the oversight though because I missed it somehow when I reviewed Balázs's rewrite. **Be _especially_ careful updating template files that touch starter logic/config while this redundancy exists!**

I may tack on a massive simplification of the templating logic ad hoc to this PR, unless we think it's ready to rapid-merge or something in which case I'd just do it in a separate one. In general though it would be better to not push 12 changes to update two core files.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c23afe197662bd9e1b176e303a3a462537a8ee9d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c23afe197662bd9e1b176e303a3a462537a8ee9d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: c23afe197662bd9e1b176e303a3a462537a8ee9d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ctjlewis** [comment]
Closed in favor of a discussion at #57787.

**Pull request closed without merging**
