### PR TITLE
chore: replace var with let

### PR DESCRIPTION
**Pull request by li-jia-nan**
chore: replace var with let

### CODE REVIEW

**Comment by timneutkens** [comment]
@li-jia-nan please stop these pull requests **immediately**, otherwise we'll have to ban your account from the repository.

**Comment by li-jia-nan** [comment]
> @li-jia-nan please stop these pull requests **immediately**, otherwise we'll have to ban your account from the repository.

Sorry for the trouble, I just want to split the changes in #49396 into multiple PRs, I will not submit again, I apologize again. sorry

image

**Comment by li-jia-nan** [comment]
@timneutkens Sorry for the trouble, I just want to split the changes in https://github.com/vercel/next.js/pull/49396 into multiple PRs, I will not submit again, I apologize again. sorry.
image

**Comment by timneutkens** [comment]
@li-jia-nan thanks for getting back here, the reason I brought up having to ban is that these seemed to come in as if it was an automated attack to hog CI resources. You trigged 34 separate CI runs in less than 5 minutes, effectively blocking all other PRs from running CI. We won't have to ban your account as the PRs stopped 👍

**Comment by li-jia-nan** [comment]
@timneutkens Sorry, I didn't know CI would be taken before this, now I do, I won't do it again, sorry.

**Comment by timneutkens** [comment]
Thank you 🙏

**Pull request closed without merging**
