### PR TITLE
NODE_OPTIONS updates

### LINKED ISSUE #47083: [NEXT-1176] Debugging with non-localhost address stopped working
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  3 17:29:44 UTC 2023
    Binaries:
      Node: 17.9.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

### To Reproduce

NODE_OPTIONS=--inspect=0.0.0.0:9229 next dev

### Describe the Bug

NodeJS's `--inspect` switch takes an optional address as a parameter that isn't being honored by Next. Next crashes when that is present.
spec: `--inspect[=[host:]port]`
https://nodejs.org/api/cli.html#--inspecthostport

In order to be able to expose a debugger from inside a Docker container, it has to listen on `0.0.0.0` instead of the default `127.0.0.1`. To do that, we have to specify `--inspect=0.0.0.0:9229`.

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

assumes the parameter is an integer: `parseInt(debugPortStr, 10)`, but `debugPortStr` could be e.g. `0.0.0.0:9229`

https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-dev.ts#L524
then does
`--inspect${isDebuggingWithBrk ? '-brk' : ''}=${debugPort + 1}`

which crashes:
```
warn  - the --inspect option was detected, the Next.js server should be inspected at port 1.
/usr/bin/node:  must be 0 or in range 1024 to 65535.
```

### Expected Behavior

Next should parse out and honor the address part of the --inspect switch.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

Docker for local dev, Vercel for hosting

<sub>[NEXT-1176](https://linear.app/vercel/issue/NEXT-1176/debugging-with-non-localhost-address-stopped-working)</sub>

### LINKED ISSUE #50489: Upgrade next from 13.4.3 to 13.4.4 startup crash, because of websocket error in dev mode due to NODE_OPTIONS='--inspect'
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/julianklumpers/reproduction-app

### To Reproduce

- yarn dev
- npm run dev
- pnpm dev

### Describe the Bug

In the release log of 13.4.4 is a commit that says `NODE_OPTIONS='--inspect'` is fixed, see: 
- fix: NODE_OPTIONS='--inspect' in next dev for debugging: https://github.com/vercel/next.js/pull/48019

Passing `NODE_OPTIONS='--inspect'` causes a websocket error and the app cannot start.

### Expected Behavior

Running dev with NODE_OPTIONS='--inspect' starts the app without websocket error and inspect mode works correctly.

### Which browser are you using? (if relevant)

Google Chrome Version 113.0.5672.92

### How are you deploying your application? (if relevant)

Digital Ocean

### LINKED ISSUE #53127: Debugging with NODE_OPTIONS='--inspect=0.0.0.0' next dev causes errors
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:22 +0000
    Binaries:
      Node: 20.3.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

### To Reproduce

NODE_OPTIONS='--inspect=0.0.0.0' next dev

### Describe the Bug

NodeJS's --inspect switch takes an optional address as a parameter that isn't being honored by Next. Next crashes when that is present.
spec: --inspect[=[host:]port]
https://nodejs.org/api/cli.html#--inspecthostport

In order to be able to expose a debugger from inside a Docker container, it has to listen on 0.0.0.0 instead of the default 127.0.0.1. To do that, we have to specify --inspect=0.0.0.0:9229.

The result of doing this is:
```
- info the --inspect option was detected, the Next.js proxy server should be inspected at port 0.
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info the --inspect option was detected, the Next.js routing server should be inspected at port 1.
/usr/local/bin/node:  must be 0 or in range 1024 to 65535.
```

This **and the root cause** has been clearly described earlier in: https://github.com/vercel/next.js/issues/47083 but not fixed, as mentioned by gregmartyn in https://github.com/vercel/next.js/issues/47083#issuecomment-1572453046

This has also been described in (and presumably fixed but not accepted) in https://github.com/vercel/next.js/pull/47671

### Expected Behavior

Start node debugger on 0.0.0.0 and default ports 9232 & 9233 instead of parsing "0.0.0.0" as a port only integer.
Honor the node --inspect switch parameters.

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### LINKED ISSUE #53757: Debugging with non-localhost address doesn't work
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages

### To Reproduce

set dev script to

"NODE_OPTIONS='--inspect=0.0.0.0:9229' next dev"

### Describe the Bug

https://github.com/vercel/next.js/issues/47083 is not fixed

When debugging in docker i need to set --inspect host to be 0.0.0.0 to reach it from the outside. When i do this next crashes because it interprets 0.0.0.0:9229 as only the port. See better explaination in linked issue. The issue is wrongly marked as fixed.

### Expected Behavior

Debugger starts but uses 0.0.0.0 instead of 127.0.0.1

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

Docker (developing)

### PR DESCRIPTION
**Pull request by wyattjoh**
### What?

Previously, parsing and managing the `NODE_OPTIONS` was performed using a series of regular expressions. These were prone to bugs, and have already caused a few issues. This moves us over to the standard `parseArgs` ([docs](https://nodejs.org/docs/latest/api/util.html#utilparseargsconfig)):

```js
import { parseArgs } from "node:utils"
```

### Why?

This simplifies the argument parser dramatically, removing the need for any special patterns or accommodations. No need to maintain all these patterns when there's a lightweight built-in parser already available.

Fixes https://github.com/vercel/next.js/issues/53127
Fixes https://github.com/vercel/next.js/issues/53757
Fixes https://github.com/vercel/next.js/issues/47083
Fixes https://github.com/vercel/next.js/issues/50489
Closes https://github.com/vercel/next.js/pull/60919 
Closes https://github.com/vercel/next.js/pull/59410
Closes NEXT-3219

### CODE REVIEW

**Comment by wyattjoh** [comment]
* **#65006** <a href="https://app.graphite.dev/github/pr/vercel/next.js/65006?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wyattjoh and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 51ab986597ade9097fbf16ada6bc8002d6ee16ed

`pnpm test test/unit/get-node-options-without-inspect.test.ts`
- getNodeOptionsWithoutInspect > removes --inspect option
- getNodeOptionsWithoutInspect > removes --inspect option at end of line
- getNodeOptionsWithoutInspect > removes --inspect option with parameters
- getNodeOptionsWithoutInspect > removes --inspect-brk option
- getNodeOptionsWithoutInspect > removes --inspect-brk option with parameters
- getNodeOptionsWithoutInspect > ignores unrelated options starting with --inspect-

<details>
<summary>Expand output</summary>

  ● getNodeOptionsWithoutInspect › removes --inspect option

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      11 |   it('removes --inspect option', () => {
      12 |     process.env.NODE_OPTIONS = '--other --inspect --additional'
    > 13 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      14 |
      15 |     expect(result).toBe('--other --additional')
      16 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:13:48)

  ● getNodeOptionsWithoutInspect › removes --inspect option at end of line

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      18 |   it('removes --inspect option at end of line', () => {
      19 |     process.env.NODE_OPTIONS = '--other --inspect'
    > 20 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      21 |
      22 |     expect(result).toBe('--other ')
      23 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:20:48)

  ● getNodeOptionsWithoutInspect › removes --inspect option with parameters

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      25 |   it('removes --inspect option with parameters', () => {
      26 |     process.env.NODE_OPTIONS = '--other --inspect=0.0.0.0:1234 --additional'
    > 27 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      28 |
      29 |     expect(result).toBe('--other --additional')
      30 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:27:48)

  ● getNodeOptionsWithoutInspect › removes --inspect-brk option

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      32 |   it('removes --inspect-brk option', () => {
      33 |     process.env.NODE_OPTIONS = '--other --inspect-brk --additional'
    > 34 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      35 |
      36 |     expect(result).toBe('--other --additional')
      37 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:34:48)

  ● getNodeOptionsWithoutInspect › removes --inspect-brk option with parameters

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      39 |   it('removes --inspect-brk option with parameters', () => {
      40 |     process.env.NODE_OPTIONS = '--other --inspect-brk=0.0.0.0:1234 --additional'
    > 41 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      42 |
      43 |     expect(result).toBe('--other --additional')
      44 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:41:48)

  ● getNodeOptionsWithoutInspect › ignores unrelated options starting with --inspect-

    TypeError: (0 , _utils.getNodeOptionsWithoutInspect) is not a function

      47 |     process.env.NODE_OPTIONS =
      48 |       '--other --inspect-port=0.0.0.0:1234 --additional'
    > 49 |     const result = getNodeOptionsWithoutInspect()
         |                                                ^
      50 |
      51 |     expect(result).toBe('--other --inspect-port=0.0.0.0:1234 --additional')
      52 |   })

      at Object.<anonymous> (unit/get-node-options-without-inspect.test.ts:49:48)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| buildDuration | 19.7s | 17.5s | N/A |
| buildDurationCached | 9.3s | 8s | N/A |
| nodeModulesSize | 238 MB | 238 MB | ⚠️ +34.7 kB |
| nextStartRea..uration (ms) | 431ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.5 kB | 31.5 kB | N/A |
| 3304.HASH.js gzip | 169 B | 169 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.09 kB | 5.09 kB | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 228 B | 228 B | ✓ |
| main-HASH.js gzip | 31.5 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.64 kB | 1.65 kB | N/A |
| Overall change | 50.7 kB | 50.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 194 B | N/A |
| _error-HASH.js gzip | 193 B | 191 B | N/A |
| amp-HASH.js gzip | 510 B | 510 B | ✓ |
| css-HASH.js gzip | 342 B | 343 B | N/A |
| dynamic-HASH.js gzip | 2.51 kB | 2.52 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 365 B | 364 B | N/A |
| hooks-HASH.js gzip | 389 B | 391 B | N/A |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 269 B | 268 B | N/A |
| link-HASH.js gzip | 2.68 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 326 B | N/A |
| script-HASH.js gzip | 395 B | 397 B | N/A |
| withRouter-HASH.js gzip | 323 B | 323 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.2 kB | 1.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| _buildManifest.js gzip | 482 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| index.html gzip | 529 B | 528 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 541 B | 541 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| edge-ssr.js gzip | 108 kB | 108 kB | N/A |
| page.js gzip | 3.05 kB | 3.04 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 623 B | 625 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 27.8 kB | 27.8 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 839 B | 839 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 97.6 kB | 97.6 kB | ✓ |
| app-page-tur..prod.js gzip | 99.4 kB | 99.4 kB | ✓ |
| app-page-tur..prod.js gzip | 93.6 kB | 93.6 kB | ✓ |
| app-page.run...dev.js gzip | 145 kB | 145 kB | ✓ |
| app-page.run..prod.js gzip | 92.1 kB | 92.1 kB | ✓ |
| app-route-ex...dev.js gzip | 21.5 kB | 21.5 kB | ✓ |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.2 kB | 21.2 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.4 kB | 21.4 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.4 kB | 21.4 kB | ✓ |
| server.runti..prod.js gzip | 65.3 kB | 65.3 kB | ✓ |
| Overall change | 960 kB | 960 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js wyattjohnson/node-options-cleanup | Change |
| - | - | - | - |
| 0.pack gzip | 1.61 MB | 1.61 MB | ⚠️ +1.86 kB |
| index.pack gzip | 107 kB | 107 kB | ⚠️ +420 B |
| Overall change | 1.72 MB | 1.72 MB | ⚠️ +2.28 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [8358],
   {
-    /***/ 1552: /***/ (
+    /***/ 4070: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(5237);
+          return __webpack_require__(396);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 2016: /***/ (module, exports, __webpack_require__) => {
+    /***/ 8490: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,15 +40,15 @@
         __webpack_require__(422)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6074)
+        __webpack_require__(2457)
       );
-      const _getimgprops = __webpack_require__(9571);
-      const _imageconfig = __webpack_require__(6567);
-      const _imageconfigcontextsharedruntime = __webpack_require__(419);
-      const _warnonce = __webpack_require__(4486);
-      const _routercontextsharedruntime = __webpack_require__(162);
+      const _getimgprops = __webpack_require__(7932);
+      const _imageconfig = __webpack_require__(5706);
+      const _imageconfigcontextsharedruntime = __webpack_require__(9483);
+      const _warnonce = __webpack_require__(9035);
+      const _routercontextsharedruntime = __webpack_require__(4829);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6996)
+        __webpack_require__(7240)
       );
       // This is replaced by webpack define plugin
       const configEnv = {
@@ -379,7 +379,7 @@
       /***/
     },
 
-    /***/ 9571: /***/ (
+    /***/ 7932: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -395,9 +395,9 @@
           return getImgProps;
         },
       });
-      const _warnonce = __webpack_require__(4486);
-      const _imageblursvg = __webpack_require__(133);
-      const _imageconfig = __webpack_require__(6567);
+      const _warnonce = __webpack_require__(9035);
+      const _imageblursvg = __webpack_require__(2642);
+      const _imageconfig = __webpack_require__(5706);
       const VALID_LOADING_VALUES =
         /* unused pure expression or super */ null && [
           "lazy",
@@ -772,7 +772,7 @@
       /***/
     },
 
-    /***/ 133: /***/ (__unused_webpack_module, exports) => {
+    /***/ 2642: /***/ (__unused_webpack_module, exports) => {
       "use strict";
       /**
        * A shared function, used on both client and server, to generate a SVG blur placeholder.
@@ -827,7 +827,7 @@
       /***/
     },
 
-    /***/ 4085: /***/ (
+    /***/ 503: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -854,10 +854,10 @@
         },
       });
       const _interop_require_default = __webpack_require__(7456);
-      const _getimgprops = __webpack_require__(9571);
-      const _imagecomponent = __webpack_require__(2016);
+      const _getimgprops = __webpack_require__(7932);
+      const _imagecomponent = __webpack_require__(8490);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(6996)
+        __webpack_require__(7240)
       );
       function getImageProps(imgProps) {
         const { props } = (0, _getimgprops.getImgProps)(imgProps, {
@@ -889,7 +889,7 @@
       /***/
     },
 
-    /***/ 6996: /***/ (__unused_webpack_module, exports) => {
+    /***/ 7240: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -924,7 +924,7 @@
       /***/
     },
 
-    /***/ 5237: /***/ (
+    /***/ 396: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -941,8 +941,8 @@
 
       // EXTERNAL MODULE: ./node_modules/.pnpm/react@18.2.0/node_modules/react/jsx-runtime.js
       var jsx_runtime = __webpack_require__(1527);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/image.js
-      var next_image = __webpack_require__(1577);
+      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@18.2.0_react@18.2.0/node_modules/next/image.js
+      var next_image = __webpack_require__(73);
       var image_default = /*#__PURE__*/ __webpack_require__.n(next_image); // CONCATENATED MODULE: ./pages/nextjs.png
       /* harmony default export */ const nextjs = {
         src: "/_next/static/media/nextjs.cae0b805.png",
@@ -972,12 +972,8 @@
       /***/
     },
 
-    /***/ 1577: /***/ (
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) => {
-      module.exports = __webpack_require__(4085);
+    /***/ 73: /***/ (module, __unused_webpack_exports, __webpack_require__) => {
+      module.exports = __webpack_require__(503);
 
       /***/
     },
@@ -987,7 +983,7 @@
     /******/ var __webpack_exec__ = (moduleId) =>
       __webpack_require__((__webpack_require__.s = moduleId));
     /******/ __webpack_require__.O(0, [2888, 9774, 179], () =>
-      __webpack_exec__(1552)
+      __webpack_exec__(4070)
     );
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>2453-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 51ab986597ade9097fbf16ada6bc8002d6ee16ed

**Review by lubieowoce — APPROVED** [review]

**Comment by eps1lon** [comment]
What's our policy on minimal Node.js version support and is parseArgs available in those versions?

**Review by timneutkens — APPROVED** [review]

**Comment by timneutkens** [comment]
https://nodejs.org/api/util.html#utilparseargsconfig
> Added in: v18.3.0, v16.17.0

https://nextjs.org/blog/next-14#other-changes

> Minimum Node.js version is now 18.17

Should be good 👍

**Comment by SatsAllDay** [comment]
Apologies in advance if this question has been answered elsewhere, at least in spirit. I am not familiar with next's release strategy.

It looks like this was first included in https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.23 Does that mean this change will only be in versions 14.3+? Are changes like this ever back-ported to previous major releases such as 13.x, for example? I'm guessing not, but I wanted to confirm. The codebase in which I am eager to consume this change is using 13.x right now, so I am trying to figure out what kind of version bump will be required to leverage these updates.

Thank you in advance!

**Comment by timneutkens** [comment]
We cherry-pick commits from the canary branch to do patch releases on the 14.2 line, we don't backport these changes to 13.x currently.

You should be able to upgrade to Next.js 14, the only hard-breaking change we added in Next.js 14 is updating the minimum required Node.js version, which you should already be using Node.js 18 because 16 is end of life anyway.

**Pull request merged**
