### PR TITLE
Update page.tsx - Fixing hydration error

### PR DESCRIPTION
**Pull request by abdulhaseeb-com**
#Hydration Error Fixed

Added div tag around p tags to fix hydration error.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 67844bf59362ca865361645cf31675ffd4f88965

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by abdulhaseeb-codes** [comment]
hydration error fixed in i18n-app example

**Comment by samcx** [comment]
@abdulhaseeb-codes Can you provide evidence in the PR's description that this is causing a hydration error?

**Comment by abdulhaseeb-codes** [comment]
You can run it locally.

**Comment by samcx** [comment]
@abdulhaseeb-codes Yes that's true, but we expect the description to be descriptive and share the findings you've found—it's why we require [issues](https://github.com/vercel/next.js/issues) to include a <picture data-single-emoji=":repro:" title=":repro:">:repro:</picture>.

We cannot test every <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture> and issue ourselves, so it's best we require this from our OS community, in order for us to get through these as efficiently as possible.

**Comment by abdulhaseeb-codes** [comment]
Thank you, I was just trying to stop this error for other beginners like me

**Review by leerob — APPROVED** [review]

**Pull request merged**
