### PR TITLE
Update `swc_core` to `v0.87.10`

### LINKED ISSUE #56144: Wrong import with prisma client and nextJest config
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/thirsty-joji-tgpmz4

### To Reproduce

1. Install dependencies
2. Run `yarn test`

### Current vs. Expected behavior

Fails with the following error, reporting an import from `./client/client`, while the source file only has `./client`;
image

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 3.6.0
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: standalone
```

### Which area(s) are affected? (Select all that apply)

Jest (next/jest), SWC transpilation

### Additional context
- Same setup was working before I upgraded next from 13.1.6
- Overriding the transform in jest config fixes the issue

<sub>[WEB-1682](https://linear.app/vercel/issue/WEB-1682/wrong-import-with-prisma-client-and-nextjest-config)</sub>

### PR DESCRIPTION
**Pull request by kdy1**
### What?

Update SWC crates

### Why?

It's required to fix some next.js isssues

### How?

Closes PACK-2174
Turbopack counterpart: https://github.com/vercel/turbo/pull/6843

---

# Turbopack

* https://github.com/vercel/turbo/pull/6737 
* https://github.com/vercel/turbo/pull/6494 
* https://github.com/vercel/turbo/pull/6778 
* https://github.com/vercel/turbo/pull/6807 
* https://github.com/vercel/turbo/pull/6809 
* https://github.com/vercel/turbo/pull/6838 
* https://github.com/vercel/turbo/pull/6845 
* https://github.com/vercel/turbo/pull/6843

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.7s | ⚠️ +135ms |
| buildDurationCached | 7.1s | 6.1s | N/A |
| nodeModulesSize | 200 MB | 200 MB | ✓ |
| nextStartRea..uration (ms) | 429ms | 423ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| 193.HASH.js gzip | 181 B | 182 B | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 433-HASH.js gzip | 28.2 kB | 28.3 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 31.7 kB | 31.7 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 98.5 kB | 98.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 183 B | 181 B | N/A |
| amp-HASH.js gzip | 504 B | 502 B | N/A |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 253 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.28 kB | 4.28 kB | N/A |
| index-HASH.js gzip | 255 B | 256 B | N/A |
| link-HASH.js gzip | 2.61 kB | 2.61 kB | ✓ |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 383 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.4 kB | 3.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| index.html gzip | 528 B | 527 B | N/A |
| link.html gzip | 540 B | 539 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 523 B | 523 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.7 kB | 93.7 kB | N/A |
| page.js gzip | 147 kB | 147 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 37.4 kB | 37.4 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 2.07 kB | 2.07 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/issue-1682 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 168 kB | 168 kB | ✓ |
| app-page-exp..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page-tur..prod.js gzip | 94.9 kB | 94.9 kB | ✓ |
| app-page-tur..prod.js gzip | 89.4 kB | 89.4 kB | ✓ |
| app-page.run...dev.js gzip | 138 kB | 138 kB | ✓ |
| app-page.run..prod.js gzip | 88.7 kB | 88.7 kB | ✓ |
| app-route-ex...dev.js gzip | 24.1 kB | 24.1 kB | ✓ |
| app-route-ex..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.7 kB | 16.7 kB | ✓ |
| app-route-tu..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| app-route.ru...dev.js gzip | 23.5 kB | 23.5 kB | ✓ |
| app-route.ru..prod.js gzip | 16.3 kB | 16.3 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.64 kB | 9.64 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.37 kB | 9.37 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| pages.runtim...dev.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.9 kB | 21.9 kB | ✓ |
| server.runti..prod.js gzip | 49.4 kB | 49.4 kB | ✓ |
| Overall change | 932 kB | 932 kB | ✓ |

</details>

</details>
Commit: c77eb6cf1fcfd73c1cbac4e850ffe08c66f6c809

**Comment by ijjk** [comment]
## Failing test suites 
Commit: acc53fcbd9aa9f308dbce78164ba2ca0eddafb8e

`pnpm test test/integration/invalid-href/test/index.test.js` 
- Invalid hrefs > production mode > does not show error in production when mailto: is used as href on Link
- Invalid hrefs > production mode > does not show error in production when https://google.com is used as href on Link
- Invalid hrefs > production mode > does not show error when internal href is used with external as
- Invalid hrefs > production mode > doesn't fail on invalid url

<details>
<summary>Expand output</summary>

  ● Invalid hrefs › production mode › does not show error in production when mailto: is used as href on Link

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 1
    Received array:  ["Uncaught TypeError: n is not a function"]

      78 |     }
      79 |     const caughtErrors = await browser.eval(`window.caughtErrors`)
    > 80 |     expect(caughtErrors).toHaveLength(0)
         |                          ^
      81 |   } finally {
      82 |     await browser.close()
      83 |   }

      at toHaveLength (integration/invalid-href/test/index.test.js:80:26)
      at Object.<anonymous> (integration/invalid-href/test/index.test.js:96:7)

  ● Invalid hrefs › production mode › does not show error in production when https://google.com is used as href on Link

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 1
    Received array:  ["Uncaught TypeError: n is not a function"]

      78 |     }
      79 |     const caughtErrors = await browser.eval(`window.caughtErrors`)
    > 80 |     expect(caughtErrors).toHaveLength(0)
         |                          ^
      81 |   } finally {
      82 |     await browser.close()
      83 |   }

      at toHaveLength (integration/invalid-href/test/index.test.js:80:26)
      at Object.<anonymous> (integration/invalid-href/test/index.test.js:100:7)

  ● Invalid hrefs › production mode › does not show error when internal href is used with external as

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 1
    Received array:  ["Uncaught TypeError: n is not a function"]

      78 |     }
      79 |     const caughtErrors = await browser.eval(`window.caughtErrors`)
    > 80 |     expect(caughtErrors).toHaveLength(0)
         |                          ^
      81 |   } finally {
      82 |     await browser.close()
      83 |   }

      at toHaveLength (integration/invalid-href/test/index.test.js:80:26)
      at Object.<anonymous> (integration/invalid-href/test/index.test.js:104:7)

  ● Invalid hrefs › production mode › doesn't fail on invalid url

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 1
    Received array:  ["Uncaught TypeError: n is not a function"]

      78 |     }
      79 |     const caughtErrors = await browser.eval(`window.caughtErrors`)
    > 80 |     expect(caughtErrors).toHaveLength(0)
         |                          ^
      81 |   } finally {
      82 |     await browser.close()
      83 |   }

      at toHaveLength (integration/invalid-href/test/index.test.js:80:26)
      at Object.<anonymous> (integration/invalid-href/test/index.test.js:132:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by kdy1** [comment]
The test failure seems like a regression, and the relevant commit range is https://github.com/swc-project/swc/compare/0bde652b5c2e028eda60f44f074a7de4d29d3784...37bb0e3bde97f96bc79771e9d15cc1f130566a50

**Comment by kdy1** [comment]
The problematic PR is https://github.com/swc-project/swc/pull/8399

**Review by sokra — APPROVED** [review]

**Pull request merged**
