### PR TITLE
Downgrade strip-ansi to support IE11/Google Fetch

### PR DESCRIPTION
**Pull request by i8ramin**
A few discussions:
https://github.com/zeit/next.js/issues/2747
https://github.com/zeit/next.js/issues/3126

### CODE REVIEW

**Review by timneutkens — APPROVED** [review]
Thanks!

**Comment by rauchg** [comment]
Thanks a lot @i8ramin !

**Comment by i8ramin** [comment]
If anyone finds this via google search, this other thread has some useful info
https://github.com/zeit/next.js/issues/3205#issuecomment-350612939

**Comment by aksharbonu** [comment]
I'm on 4.4.0-canary.3 but Google fetch still doesn't seem to be working. Is it likely that another package is causing this conflict?

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.nomzplz.com%2F&tab=desktop

**Pull request merged**
