### PR TITLE
fix: disable source map on production mode

### PR DESCRIPTION
**Pull request by helloyou2012**
`postcss-loader` will generate css source map with absolute path. It will cause the contentHash to be different for different project path. So css source map should be disabled on production mode.

related: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/533

### CODE REVIEW

**Comment by timneutkens** [comment]
@helloyou2012 can you add a test for this to `test/integration`?

**Review by Timer — CHANGES_REQUESTED** [review]
This is done intentionally so that users who enable source maps in webpack don't need to jump through extra hoops.
See the few failing tests that show why this is a breaking change!

The webpack pipeline already ignores these source maps if a devtool isn't present.

Disabling them within the loader (when no devtool) should be an optimization handled by the loader itself.

---

Seems this is better fixed upstream than being disabled here.

**Comment by helloyou2012** [comment]
> Seems this is better fixed upstream than being disabled here.

@Timer Yes, I know. But now how does it make sure that the content hash is correct?

**Comment by helloyou2012** [comment]
https://github.com/vercel/next.js/issues/9469

**Comment by Timer** [comment]
Please PR `css-loader` to ensure the source maps use relative paths.

**Comment by Timer** [comment]
Closing as this is the intentional behavior per tests. Please PR this upstream.

**Comment by unnKoel** [comment]
Now, There is a temporay resolution, by customizing webpack configuration in `next.config.js` file to close sourcemap on production environment. The configuration is as following:

`
module.exports = {
  webpack: (config, { dev }) => {
    if (!dev) {
      const oneOfIndex = config.module.rules.findIndex(rule => !!rule.oneOf);
      const rulesFromOneOf = config.module.rules[oneOfIndex].oneOf;

      config.module.rules[oneOfIndex].oneOf = rulesFromOneOf.map(
        ({ use, ...others }) => {
          if (use) {
            let newUse = use;
            if (_.isArray(use)) {
              newUse = use.map(({ loader, options }) => {
                if (
                  /css-loader/.test(loader) ||
                  /postcss-loader/.test(loader)
                ) {
                  return {
                    loader,
                    options: {
                      ...options,
                      sourceMap: false
                    }
                  };
                }
                return {
                  loader,
                  options
                };
              });
            } else {
              const { loader, options } = use;
              if (/css-loader/.test(loader) || /postcss-loader/.test(loader)) {
                newUse = {
                  loader,
                  options: {
                    ...options,
                    sourceMap: false
                  }
                };
              }
            }
            return {
              use: newUse,
              ...others
            };
          }
          return {
            ...others
          };
        }
      );
    }
    return config;
  }
}
`

**Pull request closed without merging**
