### PR TITLE
Add CONFIG_FILE constant, add types for server/config.js

### PR DESCRIPTION
**Pull request by timneutkens**
This was pulled from #4518, it can already be merged so it's easier to get it in.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
@timneutkens Any idea when this will end up in the `canary` build? The `cache.set/get` that is currently in the canary/master builds is particularly painful when executing different next builds as part of a test suite as we cannot change the configuration on the fly because of it.

**Comment by timneutkens** [comment]
A new canary version is out now 👍

**Comment by 3rd-Eden** [comment]
Works like a charm 👍

**Comment by timneutkens** [comment]
🙌

**Pull request merged**
