### PR TITLE
Add configuration to specify `assetDirectory`

### PR DESCRIPTION
**Pull request by gcpantazis**
(Related to #936; this is the more important bit for us at Thumbtack,
but doing this enables me to restart work on #936 so I wanted to get
it in for review.)

Currently the output static assets are stored in `/_next`, but this
may not be ideal. At Thumbtack, we need to let the reverse proxies route
traffic to several servers, including several Next servers eventually,
so it's important that we're able to be very specific about where
the static files are stored. This enables us to say:

`assetDirectory: '/assets/fe/service-foo`

in one app, and...

`assetDirectory: '/assets/fe/service-bar`

in another, and afterwards point traffic for those folders from the
reverse proxies to the appropriate server. I'm sure others may have
other use-cases for specifying the output directory, but this is our
immediate need.

As mentioned above, this is related to the configuration update in
PR #936, and merging this in enables us to move forward with restarting
that task.

### CODE REVIEW

**Comment by gcpantazis** [comment]
Pointed this to the v3 branch instead.

**Comment by rgbkrk** [comment]
Is this able to be configured at runtime or does it have to be set in the nextjs config?

**Comment by gcpantazis** [comment]
@rgbkrk In nextjs config: https://github.com/gcpantazis/next.js/blob/e0720a2c0d132aad6a8e856f2f8a820b8c497c3f/server/config.js#L12

**Comment by timneutkens** [comment]
Same as #936, lets move this into an issue if it's still relevant

**Pull request closed without merging**
