### PR TITLE
Follow best SEO practices for 404 page

### PR DESCRIPTION
**Pull request by oliviertassinari**
We are running https://www.onepixel.com/ through an SEO audit, I have learned that it's best practice to add a **noindex** on 404 pages.

### CODE REVIEW

**Comment by Enalmada** [comment]
I am fairly confident that is not a best practice...Google will never index 404 and I would be interested in any evidence you have to the contrary.  The only example of needing noindex would be on a "soft 404" page that is a success code 200 but represents "not found":  
https://support.google.com/webmasters/answer/181708?hl=en

**Comment by oliviertassinari** [comment]
@Enalmade The audit is performed by https://www.elephate.com/. I have no skills in this area.

**Comment by Enalmada** [comment]
Perhaps you could ask them to elaborate on what could happen without out this.  I tried to do some searching for official recommendations or benefit this could provide and couldn't find anything.

**Comment by oliviertassinari** [comment]
Here is their motivation 

> just in case, as generally, 404 page won't be indexed by itself

So it's lap belt and shoulder harness... I'm happy to close the pull request.

**Comment by Enalmada** [comment]
Thanks for following up...I was really curious if they could make a stronger case based on something they have seen.  I have certainly done plenty of things in my code "just in case" so I get where they are coming from.  It is my understanding that 404 status code for all intents and purposes is equivalent to "noindex" but there is also little harm.

**Comment by Janpot** [comment]
Google won't index 404/410 pages. You can add `noindex` "just to be on the safe side" but it won't make a  difference.

**Pull request closed without merging**
