### PR TITLE
Update typescript.md

### PR DESCRIPTION
**Pull request by rwieruch**
Searched about how to add additional types in `next-env.d.ts` but couldn't find any information about it. Thought it would be great to have little example in place.

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 11s | 10.9s | -95ms |
| nodeModulesSize | 52 MB | 52 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.1 kB | 5.1 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..d57b.js gzip | 16.1 kB | 16.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 69.8 kB | 69.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.09 kB | 4.09 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 15 kB | 15 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 64.5 kB | 64.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _app.js gzip | 1.15 kB | 1.15 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.68 kB | 9.68 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _app.module.js gzip | 576 B | 576 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.22 kB | 7.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ✓ |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.07 kB | 3.07 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.8s | ⚠️ +159ms |
| nodeModulesSize | 52 MB | 52 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.1 kB | 5.1 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..d57b.js gzip | 16.1 kB | 16.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 69.8 kB | 69.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.09 kB | 4.09 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 15 kB | 15 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 64.5 kB | 64.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _app.js gzip | 1.15 kB | 1.15 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.68 kB | 9.68 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _app.module.js gzip | 576 B | 576 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.22 kB | 7.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | rwieruch/next.js patch-2 | Change |
| - | - | - | - |
| _error.js gzip | 46.2 kB | 46.2 kB | ✓ |
| hooks.html gzip | 1.06 kB | 1.06 kB | ✓ |
| index.js gzip | 46.4 kB | 46.4 kB | ✓ |
| link.js gzip | 71.9 kB | 71.9 kB | ✓ |
| routerDirect.js gzip | 69.9 kB | 69.9 kB | ✓ |
| withRouter.js gzip | 69.9 kB | 69.9 kB | ✓ |
| Overall change | 305 kB | 305 kB | ✓ |

</details>

</details>


Commit: be2efba0778956d2b1dd7744986d70436930a01b

**Comment by chibicode** [comment]
Hi @rwieruch, thank you so much for the PR!

I believe `next-env.d.ts` should just be limited to Next-specific typings, as the name suggests.

If you wanted to add additional types, I think it's better to create *separate* `d.ts` files that are named accordingly. For example, if you want to import `mdx` files, you should create a file called `mdx.d.ts` (this is suggested by [the official MDX doc](https://mdxjs.com/advanced/typescript)).

The question is where to add this file, but this `.d.ts` can be added **anywhere** in the project directory because Next.js’s tsconfig by default [includes all files ending in `.ts`](https://github.com/zeit/next.js/blob/5bcd33fccbb771d8004a568b67e6e03b301c5764/packages/next/lib/verifyTypeScriptSetup.ts#L281) in the compile pipeline. So `mdx.d.ts` can be added to the top-level along with `next-env.d.ts` or under `types` directory, for example.

Of course, this is not clear in the documentation. What do you think about changing it like this?

---

A file named `next-env.d.ts` will be created in the root of your project. This file ensures Next.js types are picked up by the TypeScript compiler. **You cannot remove it**, and you shouldn’t need to edit it.

If you need to add custom type declarations, you can create a `[any-name].d.ts` file and place it anywhere in the project directory (it will automatically be picked up by the TS compiler). For instance, if you’re using [next-mdx](https://github.com/zeit/next.js/tree/canary/packages/next-mdx) and want to import `mdx` files, create a `mdx.d.ts` file anywhere in the project directory and [follow this guide](https://mdxjs.com/advanced/typescript) from the MDX docs.

---

- I added the wording: "you shouldn’t need to edit it"
- I changed syntax highlighting from `js` to `ts`)
- I also used the wording "if you need to add custom type...." instead of "but doesn't offer TypeScript support" because sometimes you can just use [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
- I used the mdx example because it already has a documentation page with the code sample - so no need to include the code here.

Let me know what you think!

**Review by lfades — CHANGES_REQUESTED** [review]
I agree with @chibicode , please update the PR with his suggestions 🙏

**Comment by rwieruch** [comment]
Thanks for the thorough explanation @chibicode I agree with everything you said 👍 Would you replace this PR with your suggestions?

**Comment by kachkaev** [comment]
Putting all declarations in `next-env.d.ts` does not scale well. In my projects, I keep declarations in paths like

```
declarations/package-name.d.ts
declarations/@scoped/package-name.d.ts
```

The compiler picks them well, the folder structure scales perfectly too 👍

**Review by Timer — CHANGES_REQUESTED** [review]
Closing per PR comments. Thanks for the PR!

**Comment by Flandre-X** [comment]
Not sure if this is the place to leave this, but I can't find info about it anywhere.

I'm trying to add the line `declare const __DEV__: boolean;` so that typescript knows that `__DEV__` is a global constant. Adding the line to `next-env.d.ts` works, but adding it to `global.d.ts` doesn't. My other declarations in `global.d.ts` work just fine. I don't want to add it to `next-env.d.ts` because it's not Next-specific.

Here's my entire `global.d.ts` for reference:

```ts
import 'styled-components';
import { Theme } from '@material-ui/core/styles';

declare module 'styled-components' {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface DefaultTheme extends Theme {}
}

// Has no effect
declare const __DEV__: boolean;

```

**Pull request closed without merging**
