### PR TITLE
Fallback to <script> loading behavior when preload is not supported

### PR DESCRIPTION
**Pull request by timneutkens**
Based on https://github.com/zeit/next.js/pull/5737#discussion_r236059295

This will cause a warning in chrome/safari after 3s

### CODE REVIEW

**Comment by yoavweiss** [comment]
> This will cause a warning in chrome/safari after 3s

Regarding the warning, its purpose is to avoid cases where people excessively preload content and do not use it afterwards. Happy to consider alternatives that would still maintain this goal, while enabling the use-case of same page speculative preloading.

**Comment by timneutkens** [comment]
@yoavweiss, so the way this currently works in terms of scripts:

- Next.js runtime / router / etc
- Commons chunk, if a module is used in 50% of all pages it's considered commons
- Script bundle per page

Now on server-side render we add `<link rel="preload">` for these 3 scripts, they are all needed to instantiate the interactive page (React hydration)


Then there is `<Link href="/path/to/route" prefetch>` which is a preloading mechanism built into our router. That feature is what this PR is about.

Previously we would inject `<script async src="/pages/something.js">` which kept the spinner going until the page was loaded because all async scripts are waited for like that.

So this PR changes it to inject only the `<link rel="preload">` when supported, so that the spinner is not blocked.

**Comment by timneutkens** [comment]
I think showing the warning makes sense in a way, since it forces users to think about what they're prefetching.

**Review by rauchg — APPROVED** [review]

**Comment by timneutkens** [comment]
Going to ship this to canary

**Pull request merged**
