### PR TITLE
Fixing ios10 issue with webpack-uglify plugin

### PR DESCRIPTION
**Pull request by Yuripetusko**
Fixing this issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/92

### CODE REVIEW

**Review by ilionic — COMMENTED** [review]
Tested this in production with own fork. All works fine.

**Review by timneutkens — APPROVED** [review]
Seems reasonable to add this

**Comment by ilionic** [comment]
@timneutkens looks like it's missing in latest canary branch ( after webpack 4 update ). So ios10 breaks again. Is it possible to re-add it?

**Comment by timneutkens** [comment]
We use webpack's default, you can set up your own minimizer config I guess.

**Pull request merged**
