### PR TITLE
Remove "yarn jest" from Next.js repo scripts

### LINKED ISSUE #32031: Running test locally always fails
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

yarn test

### Describe the Bug

Everytime I try to run the tests I get the error below.

I have been running a single test using `node ./node_modules/.bin/jest -- test/development/acceptance/ReactRefreshLogBox.test.ts` and writing `.only` for a single test.

```
...
    > Loading browser with http://localhost:58844/

      at Object.webdriver [as default] (lib/next-webdriver.ts:58:13)

error - ./node_modules/next/dist/client/dev/amp-dev.js
TypeError: Cannot read property 'error' of undefined
(node:29703) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
error - ./node_modules/next/dist/client/dev/amp-dev.js
TypeError: Cannot read property 'error' of undefined
error - Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.loadDefaultErrorComponents (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/dev/next-dev-server.js:679:43)
    at async DevServer.renderErrorToResponse (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1730:40)
    at async pipe.req.req (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1670:30)
    at async DevServer.pipe (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1148:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next'
  ]
}
error - Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
  console.log
    browser log: Failed to load resource: the server responded with a status of 500 (Internal Server Error)
...
```

### Expected Behavior

Tests to pass

### To Reproduce

> Clone rep
> yarn

> yarn test
or
> node ./node_modules/.bin/jest -- test/development/acceptance/ReactRefreshLogBox.test.ts

### PR DESCRIPTION
**Pull request by timneutkens**
Removes `yarn test` from the scripts as it has the wrong options. `yarn testonly` or `yarn testheadless` are the way to run tests. Fixes #32031

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24.3s | ⚠️ +336ms |
| buildDurationCached | 4.3s | 4.3s | ⚠️ +25ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.006 | 4.077 | ⚠️ +0.07 |
| / avg req/sec | 624.08 | 613.12 | ⚠️ -10.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.091 | 2.038 | -0.05 |
| /error-in-render avg req/sec | 1195.53 | 1226.99 | +31.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| buildDuration | 26.1s | 25.4s | -696ms |
| buildDurationCached | 4.4s | 4.3s | -54ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.11 | 4.123 | ⚠️ +0.01 |
| / avg req/sec | 608.21 | 606.39 | ⚠️ -1.82 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.183 | 2.263 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1145.41 | 1104.79 | ⚠️ -40.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 525 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 1d5e95a3b1f353b7c53734ba3a833943a319a3eb

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 1d5e95a3b1f353b7c53734ba3a833943a319a3eb

**test/integration/image-component/base-path/test/static.test.js** 
- Static Image Component Tests for basePath > dev mode > Should allow an image with a static src to omit height and width
- Static Image Component Tests for basePath > dev mode > Should use immutable cache-control header for static import
- Static Image Component Tests for basePath > dev mode > Should automatically provide an image height and width
- Static Image Component Tests for basePath > dev mode > Should allow provided width and height to override intrinsic
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests for basePath > dev mode > Should add a blur placeholder to statically imported png
- Static Image Component Tests for basePath > production mode > Should allow an image with a static src to omit height and width
- Static Image Component Tests for basePath > production mode > Should use immutable cache-control header for static import
- Static Image Component Tests for basePath > production mode > Should use immutable cache-control header even when unoptimized
- Static Image Component Tests for basePath > production mode > Should automatically provide an image height and width
- Static Image Component Tests for basePath > production mode > Should allow provided width and height to override intrinsic
- Static Image Component Tests for basePath > production mode > Should add a blur placeholder to statically imported jpg
- Static Image Component Tests for basePath > production mode > Should add a blur placeholder to statically imported png

<details>
<summary>Expand output</summary>

  ● Static Image Component Tests for basePath › production mode › Should allow an image with a static src to omit height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should use immutable cache-control header for static import

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should use immutable cache-control header even when unoptimized

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should automatically provide an image height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should allow provided width and height to override intrinsic

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should add a blur placeholder to statically imported jpg

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › production mode › Should add a blur placeholder to statically imported png

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:42829/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:78:23

  ● Static Image Component Tests for basePath › dev mode › Should allow an image with a static src to omit height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should use immutable cache-control header for static import

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should automatically provide an image height and width

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should allow provided width and height to override intrinsic

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported jpg

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

  ● Static Image Component Tests for basePath › dev mode › Should add a blur placeholder to statically imported png

    page.goto: Timeout 30000ms exceeded.
    =========================== logs ===========================
    navigating to "http://localhost:41261/docs/static-img", waiting until "load"
    ============================================================

      106 |               .evaluate(`console.log('received ws message ${frame.payload}')`)
      107 |               .catch(() => {})
    > 108 |           }
          |            ^
      109 |         }
      110 |       })
      111 |     })

      at Playwright.loadPage (lib/browsers/playwright.ts:108:20)
      at Object.webdriver [as default] (lib/next-webdriver.ts:59:5)
      at integration/image-component/base-path/test/static.test.js:90:23

</details>

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| buildDuration | 23.9s | 23.8s | -36ms |
| buildDurationCached | 4.3s | 4.2s | -72ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.843 | 4.037 | ⚠️ +0.19 |
| / avg req/sec | 650.56 | 619.32 | ⚠️ -31.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.066 | 2.083 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1210.35 | 1200.07 | ⚠️ -10.28 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.49 kB | 4.49 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| buildDuration | 26.2s | 25.9s | -275ms |
| buildDurationCached | 4.2s | 4.4s | ⚠️ +205ms |
| nodeModulesSize | 347 MB | 347 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.974 | 3.969 | -0.01 |
| / avg req/sec | 629.13 | 629.85 | +0.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.072 | 2.059 | -0.01 |
| /error-in-render avg req/sec | 1206.69 | 1214.36 | +7.67 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.53 kB | 4.53 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/remove-test-command-repo | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 6a00b86d86f020c3e4d081ef2a9564281a358a8f

**Review by ijjk — APPROVED** [review]

**Comment by chentsulin** [comment]
How about the `testall` command?

https://github.com/timneutkens/next.js/blob/21bae2b71bd596bce14e0cb3daa21503aa8001dc/package.json#L18

Should it be moved too? It refers to the dead `yarn test` command.

**Pull request merged**
