### PR TITLE
with apollo and redux saga example: Update deps

### PR DESCRIPTION
**Pull request by crutchcorn**
Updates packages for apollo and redux saga example. The major update to `next-redux-wrapper` included a breaking change that required a tiny bit of work to fix up

### CODE REVIEW

**Review by lfades — CHANGES_REQUESTED** [review]
Hi @crutchcorn thank you for the PR, can you please run the linter ?, then I'll merge 🙏

**Comment by crutchcorn** [comment]
I'm waiting on !6732 before doing so @lfades, that way the potential for merge conflicts is lowered. Once that is merged, I'll fix this up with linter fixes

**Comment by crutchcorn** [comment]
Linting ran, should be good to go @lfades

**Review by lfades — APPROVED** [review]

**Comment by lfades** [comment]
@crutchcorn Thank you 💯

**Pull request merged**
