### PR TITLE
Fix/upgrade examples with zustand 21 sep 23

### PR DESCRIPTION
**Pull request by mayank1513**

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d20eefee9d1afe4e3e8d8003096d2f681f7f78a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d20eefee9d1afe4e3e8d8003096d2f681f7f78a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: d20eefee9d1afe4e3e8d8003096d2f681f7f78a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
see https://github.com/vercel/next.js/pull/55793#issuecomment-1731313327

**Pull request closed without merging**
