### PR TITLE
fix(next-core): add Array.toReversed, toSpliced, toSorted, with polyfills

### LINKED ISSUE #58242: Array.toSorted, toSliced, toReversed polyfills missing
### Link to the code that reproduces this issue

https://github.com/MonstraG/toSorted-polyfill-missing-nextjs

### To Reproduce

1. In reproduction template, update typescript to latest - 5.2.2
2. Put following in the Home file:
```
return [3,1,2,4].toSorted().toSpliced(1, 2).toReversed().map(x => <div key={x}>{x}</div>)
```
3. run app and open it in Safari 15.6

### Current vs. Expected behavior

Expected: 
```
4
1
```
on the screen

Actual:
Exception: `.toSorted is not a function`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Wed Oct 25 13:06:34 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.2-canary.25
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

See also https://github.com/vercel/next.js/discussions/44148.
Without this, [claim of supporting safari 12](https://nextjs.org/docs/architecture/supported-browsers) is invalid. 
There may be additional polyfills missing.

### PR DESCRIPTION
**Pull request by RaenonX**
Fixes https://github.com/vercel/next.js/issues/58242.

See also https://github.com/vercel/next.js/pull/44436.

Continuation of https://github.com/vercel/next.js/pull/58421.

### CODE REVIEW

**Comment by RaenonX** [comment]
@timneutkens @ijjk @shuding @huozhi @feedthejim @ztanner @wyattjoh
Sorry for the mass ping, but can we have anyone to take a quick look and merge this? The change is only 4 lines, and it helps increasing the compatibility of the apps built on next.js since some older devices (especially iPhone) can't use these APIs unless Apple updates it.

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| buildDuration | 17.1s | 15.5s | N/A |
| buildDurationCached | 9.7s | 8.1s | N/A |
| nodeModulesSize | 360 MB | 360 MB | ⚠️ +3.06 kB |
| nextStartRea..uration (ms) | 418ms | 422ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| 139-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| 2478adb3-HASH.js gzip | 53.5 kB | 53.5 kB | N/A |
| 4967-HASH.js gzip | 5.1 kB | 5.1 kB | N/A |
| 6701.HASH.js gzip | 168 B | 168 B | ✓ |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 228 B | 225 B | N/A |
| main-HASH.js gzip | 31.6 kB | 31.6 kB | N/A |
| webpack-HASH.js gzip | 1.65 kB | 1.64 kB | N/A |
| Overall change | 45.3 kB | 45.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 193 B | N/A |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 510 B | 510 B | ✓ |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 2.51 kB | 2.52 kB | N/A |
| edge-ssr-HASH.js gzip | 266 B | 265 B | N/A |
| head-HASH.js gzip | 365 B | 362 B | N/A |
| hooks-HASH.js gzip | 391 B | 390 B | N/A |
| image-HASH.js gzip | 4.32 kB | 4.32 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 393 B | 395 B | N/A |
| withRouter-HASH.js gzip | 323 B | 323 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.73 kB | 1.73 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 484 B | 484 B | ✓ |
| Overall change | 484 B | 484 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 528 B | 528 B | ✓ |
| link.html gzip | 540 B | 541 B | N/A |
| withRouter.html gzip | 523 B | 523 B | ✓ |
| Overall change | 1.05 kB | 1.05 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| edge-ssr.js gzip | 108 kB | 108 kB | N/A |
| page.js gzip | 3.05 kB | 3.05 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 622 B | 625 B | N/A |
| middleware-r..fest.js gzip | 155 B | 154 B | N/A |
| middleware.js gzip | 27.9 kB | 27.9 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 839 B | 839 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 98.4 kB | 98.4 kB | ✓ |
| app-page-tur..prod.js gzip | 99.9 kB | 99.9 kB | ✓ |
| app-page-tur..prod.js gzip | 94.2 kB | 94.2 kB | ✓ |
| app-page.run...dev.js gzip | 157 kB | 157 kB | ✓ |
| app-page.run..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.4 kB | 21.5 kB | N/A |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | N/A |
| pages.runtim..prod.js gzip | 21.4 kB | 21.5 kB | N/A |
| server.runti..prod.js gzip | 65.3 kB | 65.3 kB | ✓ |
| Overall change | 910 kB | 910 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jonluca/next.js canary | Change |
| - | - | - | - |
| 0.pack gzip | 1.61 MB | 1.62 MB | ⚠️ +1.67 kB |
| index.pack gzip | 111 kB | 113 kB | ⚠️ +1.28 kB |
| Overall change | 1.72 MB | 1.73 MB | ⚠️ +2.95 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: f0eeccdb9410bcb1a95c4c4dddadb3f0673b75ec

**Review by timneutkens — CHANGES_REQUESTED** [review]
This change does not look correct to me.
The intent of next-polyfill-module and next-polyfill-nomodule is to ensure compat with the supported browsers: https://nextjs.org/docs/architecture/supported-browsers.
These browsers are specifically chosen as they're the cutoff point of `module`/`nomodule` support (ES Modules support). So the built-in polyfill that are loaded in all browsers, and the polyfills that are only loaded in browsers that don't support ES Modules, are specifically tuned to support the APIs that the ES Modules browsers had at the time, not to load all polyfills, as that would mean Next.js will forever keep increasing the polyfill size whenever new browser features are added, that's not something we want, i.e. we don't want to have to load a polyfill for `toReversed` in all browsers because the older version of ES Modules browsers also doesn't have it.

Our recommendation for these newer features is to pull in the polyfills as you need them / want to use them. In this case you need to load the `toReversed` polyfill for all browsers, even ones that support it, as there is no way to conditionally load it like `nomodule`.

Hope that clarifies 🙏

**Comment by RaenonX** [comment]
> This change does not look correct to me. The intent of next-polyfill-module and next-polyfill-nomodule is to ensure compat with the supported browsers: https://nextjs.org/docs/architecture/supported-browsers. These browsers are specifically chosen as they're the cutoff point of `module`/`nomodule` support (ES Modules support). So the built-in polyfill that are loaded in all browsers, and the polyfills that are only loaded in browsers that don't support ES Modules, are specifically tuned to support the APIs that the ES Modules browsers had at the time, not to load all polyfills, as that would mean Next.js will forever keep increasing the polyfill size whenever new browser features are added, that's not something we want, i.e. we don't want to have to load a polyfill for `toReversed` in all browsers because the older version of ES Modules browsers also doesn't have it.
> 
> Our recommendation for these newer features is to pull in the polyfills as you need them / want to use them. In this case you need to load the `toReversed` polyfill for all browsers, even ones that support it, as there is no way to conditionally load it like `nomodule`.
> 
> Hope that clarifies 🙏

Thanks for responding. To make sure I understand it correctly, since these `to*()` methods are only available post-module era and we don't want next.js to grow its polyfill size permanently whenever there are new API available, it would rather be better for us to create custom polyfilling? 

If so, I can understand that although it's ambiguous to say that next.js supports Chrome 64+ with zero-config, we still need to polyfill `to*()` to actually use them to prevent polyfilling size to grow indefinitely.

However, this leads to another issue: in https://nextjs.org/docs/architecture/supported-browsers#custom-polyfills, it says `In this case, you should add a top-level import for the specific polyfill you need in your Custom <App> or the individual component.` But with App router `/app`, there's no `<App>`. How do we do custom polyfill in this case? I have tried the following commits in my repo, but none of them works:
- https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/d4ce3c1862ed5cef7ddcb1e83b37ece66ab0300a
- https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/2440e74979ba8a621bd6c2e5bf42151fc3e890f0
- https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/6607658c6065bad0731725e11f73f9cdcaa6cd21

**Comment by timneutkens** [comment]
Have you tried adding `import '../my-polyfills'` to `app/layout.tsx`?

**Comment by RaenonX** [comment]
> > Have you tried adding `import '../my-polyfills'` to `app/layout.tsx`?
> 
> Not exactly because I wasn't importing it at the root level. [RaenonX-PokemonSleep/pokemon-sleep-ui@6607658](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/6607658c6065bad0731725e11f73f9cdcaa6cd21)
> 
> > as there's no export.
> 
> So for this file [RaenonX-PokemonSleep/pokemon-sleep-ui@d4ce3c1#diff-30f135108dde64f0b8b9f0df3f0e69a4a547b48557a13bd682797cfc54128f4f](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/d4ce3c1862ed5cef7ddcb1e83b37ece66ab0300a#diff-30f135108dde64f0b8b9f0df3f0e69a4a547b48557a13bd682797cfc54128f4f), I actually need to export these polyfills? Or simply importing them here is fine?
> 
> > Potentially you have to add `export default function PolyfillPlaceholder({children}) { return children }` and then always render that.
> 
> So it's custom wrapper component? Does this `<PolyfillPlaceholder/>` wrapper needs to be `'use client';` or no? I guess I can wrap it at https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/main/src/app/layout.ts so it applies to all the pages.

@timneutkens Thanks for the suggestion about that `<PolyfillPlaceholder/>` usage. It worked by making these changes https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/b9fb52339a085f7ed632688dd5fb9278e8f862eb

Is it OK to close this PR since next.js will not add these polyfills if I understand it correctly?

**Comment by timneutkens** [comment]
Yeah let's close the PR as I don't think we'll want to land this as-is 👍

**Pull request closed without merging**
