### PR TITLE
Fix data URL with root-catchall and basePath

### LINKED ISSUE #15747: Inconsistent url (prefetch/fetch) for .json data file on link click (next/link) when using SSG + basePath
# Bug report

## Describe the bug

Using both SSG and basePath, when next.js tries to get the .json data file that corresponds to the page data (instead of doing full reload), the url that is fetched does not correspond to the location where the file has been physically generated during build/export

## To Reproduce

1. clone: https://github.com/oecd/next-link-basepath-bug
2. npm install
3. npm run build-n-export
4. host the content of the "out" folder so that app is served from "/folder" by any random web server
5. browse http://localhost/folder/home
6. check network tab: http://localhost/folder/_next/data/xxxxxx/another-page.json gives 200
7. click on the "go to another page.." link
8. check network tab: http://localhost/folder/_next/data/xxxxxx/folder/another-page.json gives 404

...so a full reload occurs.

It should be noted that using next.js server (npm run start), the inconsistency in urls are still there but both urls give 200!
There must be some magic somewhere! ;)

## Expected behavior

Both prefetch and fetch should use the same url and that url should correspond to the location where the files are generated.

## System information

- OS: Windows
- Browser: all
- Version of Next.js: 9.5.0

## Additional context

I was already using basePath when it was "experimental" without any problem.

### PR DESCRIPTION
**Pull request by ijjk**
This fixes the incorrect `/_next/data` URL being generated on client transition due to the `as` value passed to `getRouteInfo` having the `basePath` which is used while interpolating the values for dynamic routes, specifically root catch-all routes. A regression test has also been added to ensure this is working

Closes: https://github.com/vercel/next.js/issues/15747

### CODE REVIEW

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.5s | ⚠️ +683ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.498 | 2.485 | -0.01 |
| / avg req/sec | 1000.71 | 1006.21 | +5.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.491 | 1.462 | -0.03 |
| /error-in-render avg req/sec | 1677.26 | 1710.43 | +33.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..2585.js gzip | 10.2 kB | 10.2 kB | ⚠️ +2 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8c9d3f7..4367.js gzip | 6.72 kB | 6.72 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 56.7 kB | 56.7 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.07 kB | 6.08 kB | ⚠️ +2 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e89c24f..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 51.6 kB | 51.6 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-00b8972..6e4e.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.7 kB | 7.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-72c64d9..dule.js gzip | 1.27 kB | 1.27 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| index.html gzip | 947 B | 948 B | ⚠️ +1 B |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html gzip | 940 B | 941 B | ⚠️ +1 B |
| Overall change | 2.84 kB | 2.84 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..3c.module.js</strong></summary>

```diff
@@ -1178,7 +1178,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                   pathname,
                   query
                 }),
-                as,
+                delBasePath(as),
                 __N_SSG
               );
             }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..846419646.js</strong></summary>

```diff
@@ -1630,7 +1630,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                   pathname: pathname,
                                   query: query
                                 }),
-                                as,
+                                delBasePath(as),
                                 __N_SSG
                               );
                             }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| buildDuration | 15s | 14.9s | -77ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..2585.js gzip | 10.2 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8c9d3f7..4367.js gzip | 6.72 kB | 6.72 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..b4e6.js gzip | N/A | 10.2 kB | N/A |
| Overall change | 56.7 kB | 56.7 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.07 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e89c24f..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..dule.js gzip | N/A | 6.08 kB | N/A |
| Overall change | 51.6 kB | 51.6 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-00b8972..6e4e.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.7 kB | 7.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-72c64d9..dule.js gzip | 1.27 kB | 1.27 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ⚠️ +13 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +13 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +13 B |
| Overall change | 5.27 MB | 5.27 MB | ⚠️ +39 B |

</details>

</details>
Commit: 0df8c2c246f4a4f29b570218ab2cbd9a96c62137

**Review by Timer — CHANGES_REQUESTED** [review]
s/poarts/parts/

How did the test pass with this typo?

image

**Review by Timer — APPROVED** [review]
LGTM

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| buildDuration | 12s | 12.2s | ⚠️ +200ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.202 | 2.161 | -0.04 |
| / avg req/sec | 1135.55 | 1157.02 | +21.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.187 | 1.186 | 0 |
| /error-in-render avg req/sec | 2105.52 | 2107.85 | +2.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..2585.js gzip | 10.2 kB | 10.2 kB | ⚠️ +2 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8c9d3f7..4367.js gzip | 6.72 kB | 6.72 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 56.7 kB | 56.7 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.07 kB | 6.08 kB | ⚠️ +2 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e89c24f..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 51.6 kB | 51.6 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-00b8972..6e4e.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.7 kB | 7.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-72c64d9..dule.js gzip | 1.27 kB | 1.27 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| index.html gzip | 947 B | 948 B | ⚠️ +1 B |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html gzip | 940 B | 941 B | ⚠️ +1 B |
| Overall change | 2.84 kB | 2.84 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..3c.module.js</strong></summary>

```diff
@@ -1178,7 +1178,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                   pathname,
                   query
                 }),
-                as,
+                delBasePath(as),
                 __N_SSG
               );
             }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..846419646.js</strong></summary>

```diff
@@ -1630,7 +1630,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                   pathname: pathname,
                                   query: query
                                 }),
-                                as,
+                                delBasePath(as),
                                 __N_SSG
                               );
                             }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c4ee795a228846419646.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.fedf4a6cbf46e2c5bf9e.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5020e365fe246cfb523c.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.897f5e72583be4f5895d.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.4s | -106ms |
| nodeModulesSize | 57.6 MB | 57.6 MB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..2585.js gzip | 10.2 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-8c9d3f7..4367.js gzip | 6.72 kB | 6.72 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..b4e6.js gzip | N/A | 10.2 kB | N/A |
| Overall change | 56.7 kB | 56.7 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.07 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e89c24f..dule.js gzip | 5.79 kB | 5.79 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..dule.js gzip | N/A | 6.08 kB | N/A |
| Overall change | 51.6 kB | 51.6 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-1464c..a26f.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-00b8972..6e4e.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.7 kB | 7.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-e550f..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-72c64d9..dule.js gzip | 1.27 kB | 1.27 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/root-catch-all-data-url | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.82 kB | 3.82 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.07 MB | 1.07 MB | ⚠️ +13 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +13 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +13 B |
| Overall change | 5.27 MB | 5.27 MB | ⚠️ +39 B |

</details>

</details>
Commit: f55c8f962c779186adab1da6f907ef82fd3381f6

**Pull request merged**
