### PR TITLE
Adjust execution queue 

### LINKED ISSUE #6462: Scroll reset happens at end of `Link` routing rather than beginning
# Bug report

## Describe the bug

The next.js `Router` resets the scroll position to 0,0 at the end of navigation if it is navigating to a href without a fragment via the included `Link` tag. However, because of the late timing of the reset, the incoming page renders and begins its lifecycle with the viewport position at the point it was at on the previous page before being reset to the new value. This can cause confusing errors when components on the new page use scroll position to trigger behaviors and events.

## To Reproduce

1. In any next site using the default Router with two pages... we'll call one `A` and one `B`.
2. Add an override in `B` of `componentDidMount` that calls `console.log(window.scrollY)`
3. Go to `A` and scroll so that you are no longer at scroll position (0,0).
4. Click a `Link` element to navigate to `B`. Notice that your log will log a value other than 0, though the page will then reset to the top.

## Expected behavior
I would expect this to mirror the behavior found with "true http routing". If you perform the navigation using normal `<a>` tags instead of `<Link>` elements, the viewport is reset to (0, 0) before the React elements receive their call to `componentDidMount`.

## System information
 - OS: Mac OS
 - Browser (if applies) Firefox (I'm assuming this applies to all browsers, though)
 - Version of Next.js: 8.0.1

## Additional context

I was able to fix this problem for my code using the following snippet (in typescript):
```typescript
let hasAttachedRouteListener: boolean = false;

export function attachListener() {
  // Only actually attach once
  if (hasAttachedRouteListener) {
    return;
  }
  hasAttachedRouteListener = true;

  // This event fires before the incoming route is loaded or rendered,
  // so by resetting the viewport without animation at this point we avoid
  // the incoming route getting the incorrect viewport at any point.
  const handleRouteChange = () => {
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: "auto"
    });
  };

  Router.events.on("routeChangeStart", handleRouteChange);
}
```

### PR DESCRIPTION
**Pull request by nblthree**
fixes [#6462](https://github.com/zeit/next.js/issues/6462)

### CODE REVIEW

**Comment by MarchWorks** [comment]
this issue [#6025](https://github.com/zeit/next.js/issues/6025) can be solved too by changing 

```
this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo

        if (error && error.cancelled) {
          return resolve(false)
        }

        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)

        // @ts-ignore pathname is always defined
        this.set(route, pathname, query, as, { ...routeInfo, hash })

        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }

        Router.events.emit('routeChangeComplete', as)
        return resolve(true)
      }, reject)
```

to

```
this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo

        if (error && error.cancelled) {
          return resolve(false)
        }

        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)

        // @ts-ignore pathname is always defined
        this.set(route, pathname, query, as, { ...routeInfo, hash })

        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }

        setTimeout(() => {
            Router.events.emit('routeChangeComplete', as)
        }, 0)
        return resolve(true)
      }, reject)
```
but it feel strange to solve both of them in the same way

**Comment by MarchWorks** [comment]
I realized that there is no `setTimeout` in the base code so maybe I will rewrite the code without `setTimeout` but that won't be soon

**Comment by timneutkens** [comment]
This doesn't look like the correct solution for the mentioned issue, I'd have to take a deeper look at the issue to see what the correct one is, but I'll close this PR for now 🙏

**Comment by MarchWorks** [comment]
@timneutkens this time I am sure that I found the right solution. but I don't want to make a new PR until I get your opinion.

Let's start by diagnosing the problems.

First for the scroll issue #6462 I created a simple [Jsfiddle](https://jsfiddle.net/48y016sb/) to demonstrate the problem. Here is the equivalent code in the code base 

[link.js](https://github.com/zeit/next.js/blob/canary/packages/next/client/link.js#L88-L98)
```
    Router[this.props.replace ? 'replace' : 'push'](href, as, { shallow: this.props.shallow })
      .then((success) => {
        if (!success) return
        if (scroll) {
          window.scrollTo(0, 0)
          document.body.focus()
        }
      })
      .catch((err) => {
        if (this.props.onError) this.props.onError(err)
      })
```
With
[router.ts](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.ts#L193-L261)
```
      this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo


        if (error && error.cancelled) {
          return resolve(false)
        }


        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)


        // @ts-ignore pathname is always defined
        this.set(route, pathname, query, as, { ...routeInfo, hash })


        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }


        Router.events.emit('routeChangeComplete', as)
        return resolve(true)
      }, reject)
```

To solve this I passed a function to `resolve` like this

```
this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo

        if (error && error.cancelled) {
          return resolve(false)
        }

        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)

        // @ts-ignore pathname is always defined
        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }
        return resolve(()=>{
	    this.set(route, pathname, query, as, { ...routeInfo, hash })
            Router.events.emit('routeChangeComplete', as)
        })
      }, reject)
```
and then we execute it in [link.js](https://github.com/zeit/next.js/blob/canary/packages/next/client/link.js#L88-L98)
Like this 
```
Router[this.props.replace ? 'replace' : 'push'](href, as, { shallow: this.props.shallow })
      .then((success) => {
        if (!success) return
        if (scroll) {
          window.scrollTo(0, 0)
          document.body.focus()
          success()
        }
      })
      .catch((err) => {
        if (this.props.onError) this.props.onError(err)
      })
```

The second issue is much more simpler, the problem is that `Router.events.emit('routeChangeComplete', as)` get triggered before `this.set(route, pathname, query, as, { ...routeInfo, hash })` finish to solve this I created a new promise like this

```
new Promise((resolve, reject)=>{
        this.set(route, pathname, query, as, { ...routeInfo, hash }, resolve)
}).then(()=>{
	Router.events.emit('routeChangeComplete', as)
})
```
then I pass `resolve` to the `notify` method and execute it after `this.subscriptions.forEach((fn) => fn({ ...data, App }))`.
if we merge this two solution we get the following

```
this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo

        if (error && error.cancelled) {
          return resolve(false)
        }

        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)

        // @ts-ignore pathname is always defined
        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }
        resolve(()=>{
        	new Promise((resolve, reject)=>{
	        	this.set(route, pathname, query, as, { ...routeInfo, hash }, resolve)
	        }).then(()=>{
		        Router.events.emit('routeChangeComplete', as)
	        })
        })
      }, reject)
```
I think that the second solution can be writing in a more clean way so what do you say about all this

**Comment by MarchWorks** [comment]
For the second solution I think that returning a promise from the `notify` method is better
```
this.set(route, pathname, query, as, { ...routeInfo, hash }).then(()=>{
    Router.events.emit('routeChangeComplete', as)
})
```

**Comment by MarchWorks** [comment]
@timneutkens after thinking more about the second solution I think that it's not the right one so I will make a new PR that contain the first only

**Pull request closed without merging**
