### PR TITLE
Update test timings endpoint

### PR DESCRIPTION
**Pull request by ijjk**
This updates to leverage a more new endpoint for our test timings.

### CODE REVIEW

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 38a7fda3213e73c6ba84cd006638df7af6a2d233

**test/integration/app-document-remove-hmr/test/index.test.js** 
- _app removal HMR > should HMR when _app is removed
- _app removal HMR > should HMR when _document is removed

<details>
<summary>Expand output</summary>

  ● _app removal HMR › should HMR when _app is removed

    TIMED OUT: success

    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="next-head-count" content="2"><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1632774783118"></script><script src="/_next/static/chunks/webpack.js?ts=1632774783118" defer=""></script><script src="/_next/static/chunks/main.js?ts=1632774783118" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1632774783118" defer=""></script><script src="/_next/static/chunks/pages/index.js?ts=1632774783118" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1632774783118" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1632774783118" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><p>custom _document</p><div id="__next"><p>index page updated</p></div><script src="/_next/static/chunks/react-refresh.js?ts=1632774783118"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"development","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script><div id="__next-build-watcher" style="position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;"></div><next-route-announcer><p aria-live="assertive" id="__next-route-announcer__" role="alert" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; width: 1px; white-space: nowrap; overflow-wrap: normal;"></p></next-route-announcer></body>

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (integration/app-document-remove-hmr/test/index.test.js:66:6)

  ● _app removal HMR › should HMR when _document is removed

    TIMED OUT: success

    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="next-head-count" content="2"><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1632774814868"></script><script src="/_next/static/chunks/webpack.js?ts=1632774814868" defer=""></script><script src="/_next/static/chunks/main.js?ts=1632774814868" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1632774814868" defer=""></script><script src="/_next/static/chunks/pages/index.js?ts=1632774814868" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1632774814868" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1632774814868" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body style="overflow: hidden;"><div id="__next"></div><script src="/_next/static/chunks/react-refresh.js?ts=1632774814868"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"development","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script><div id="__next-build-watcher" style="position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;"></div><next-route-announcer><p aria-live="assertive" id="__next-route-announcer__" role="alert" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; width: 1px; white-space: nowrap; overflow-wrap: normal;"></p></next-route-announcer><nextjs-portal></nextjs-portal></body>

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (integration/app-document-remove-hmr/test/index.test.js:92:7)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.6s | -16ms |
| buildDurationCached | 3.5s | 3.4s | -96ms |
| nodeModulesSize | 182 MB | 182 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.017 | 2.943 | -0.07 |
| / avg req/sec | 828.67 | 849.34 | +20.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.46 | 1.51 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1712.79 | 1656.04 | ⚠️ -56.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.15 kB | 4.15 kB | ✓ |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 494 B | 494 B | ✓ |
| Overall change | 494 B | 494 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| buildDuration | 7s | 7s | ⚠️ +44ms |
| buildDurationCached | 3.5s | 3.4s | -34ms |
| nodeModulesSize | 182 MB | 182 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.952 | 2.956 | 0 |
| / avg req/sec | 846.91 | 845.88 | ⚠️ -1.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.394 | 1.462 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1793.13 | 1710.3 | ⚠️ -82.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: 3548435a8e81087cc37a21f7ce51e61013dd0055

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 3548435a8e81087cc37a21f7ce51e61013dd0055

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should recover from errors in the render function
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover from errors in getInitialProps in client
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover from errors in the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:455:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:510:9)

  ● basic HMR › Error Recovery › should recover from errors in getInitialProps in client

    TIMED OUT: /Hello/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:659:8)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      701 |
      702 |         throw err
    > 703 |       } finally {
          |                  ^
      704 |         if (browser) {
      705 |           await browser.close()
      706 |         }

      at Object.<anonymous> (development/basic/hmr.test.ts:703:18)

</details>

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.1s | -408ms |
| buildDurationCached | 3.7s | 3.6s | -119ms |
| nodeModulesSize | 182 MB | 182 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.119 | 3.108 | -0.01 |
| / avg req/sec | 801.59 | 804.4 | +2.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.556 | 1.496 | -0.06 |
| /error-in-render avg req/sec | 1607 | 1671.64 | +64.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27 kB | 27 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 70.8 kB | 70.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 977 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.15 kB | 4.15 kB | ✓ |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 494 B | 494 B | ✓ |
| Overall change | 494 B | 494 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 550 B | 550 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| buildDuration | 7.4s | 7.4s | ⚠️ +25ms |
| buildDurationCached | 3.6s | 3.6s | ⚠️ +23ms |
| nodeModulesSize | 182 MB | 182 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.108 | 3.1 | -0.01 |
| / avg req/sec | 804.3 | 806.54 | +2.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.507 | 1.512 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1658.82 | 1653 | ⚠️ -5.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| 675-HASH.js gzip | 13.8 kB | 13.8 kB | ✓ |
| 770.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 50.7 kB | 50.7 kB | ✓ |
| main-HASH.js gzip | 34.9 kB | 34.9 kB | ✓ |
| webpack-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| Overall change | 101 kB | 101 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 315 B | 315 B | ✓ |
| css-HASH.js gzip | 331 B | 331 B | ✓ |
| dynamic-HASH.js gzip | 2.8 kB | 2.8 kB | ✓ |
| head-HASH.js gzip | 356 B | 356 B | ✓ |
| hooks-HASH.js gzip | 637 B | 637 B | ✓ |
| image-HASH.js gzip | 573 B | 573 B | ✓ |
| index-HASH.js gzip | 262 B | 262 B | ✓ |
| link-HASH.js gzip | 2.2 kB | 2.2 kB | ✓ |
| routerDirect..HASH.js gzip | 326 B | 326 B | ✓ |
| script-HASH.js gzip | 393 B | 393 B | ✓ |
| withRouter-HASH.js gzip | 322 B | 322 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 10.1 kB | 10.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 511 B | 511 B | ✓ |
| Overall change | 511 B | 511 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/test-timings | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
Commit: 8a0208e6e46e535f2db8e68303a7d466491bc7da

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8a0208e6e46e535f2db8e68303a7d466491bc7da

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    TIMED OUT: /Hello/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:489:17)

</details>

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 8a0208e6e46e535f2db8e68303a7d466491bc7da

**test/integration/app-document-remove-hmr/test/index.test.js** 
- _app removal HMR > should HMR when _document is removed

<details>
<summary>Expand output</summary>

  ● _app removal HMR › should HMR when _document is removed

    TIMED OUT: success

    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="next-head-count" content="2"><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1632787420299"></script><script src="/_next/static/chunks/webpack.js?ts=1632787420299" defer=""></script><script src="/_next/static/chunks/main.js?ts=1632787420299" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1632787420299" defer=""></script><script src="/_next/static/chunks/pages/index.js?ts=1632787420299" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1632787420299" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1632787420299" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"><p>custom _app</p><p>index page updated</p></div><script src="/_next/static/chunks/react-refresh.js?ts=1632787420299"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"development","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script><div id="__next-build-watcher" style="position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;"></div><next-route-announcer><p aria-live="assertive" id="__next-route-announcer__" role="alert" style="border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; width: 1px; white-space: nowrap; overflow-wrap: normal;"></p></next-route-announcer></body>

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (integration/app-document-remove-hmr/test/index.test.js:123:7)

</details>

**Review by styfle — APPROVED** [review]

**Pull request merged**
