### PR TITLE
(example/with-react-relay-network-modern) Fix example

### LINKED ISSUE #7565: with-react-relay-network-modern - non-functional example
# Examples bug report

## Describe the bug
At first the data is there but then it disappears and is null thus throwing this error. 

```bash
TypeError: Cannot read property 'modern' of undefined
    at getNode (/Users/devionvillegas/Developer/NEXTGEN/with-react-relay-network-modern-app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:25:71) ...
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. download the example with `npx create-next-app`
2. run `npm run schema`
3. run `npm run relay`
4. console.log props inside the BlogPosts.js component
5. run `npm run dev`
6.  error is thrown along with two console.log outputs 
Screen Shot 2019-06-12 at 10 17 37 PM

## Expected behavior

You can see that on the first render, the data is there which means something else is triggering a re-render and making the array null. I can't exactly figure it out as I'm used to using apollo and this was my first time trying to see what relay was about. Hopefully the other examples work. Was hoping it would be trivial to use relay with nextjs.

### PR DESCRIPTION
**Pull request by HsuTing**
Fix #7565

### CODE REVIEW

**Comment by lfades** [comment]
Hi @HsuTing thank you for the PR. I get this when I run `yarn relay`: 
image
Can you confirm that it's not happening to you too please 🙏

**Comment by HsuTing** [comment]
@lfades I did not get that error, and I search the `wheels` with `grep -rin "wheels" . --exclude=**/node_modules/** --exclude=**/.next/**`. I did not get any code using `wheels`. I think this is not an error in this example.

**Comment by lfades** [comment]
@HsuTing It has to be, the example using your update, but don't worry, I'll try to debug it a little more and if I don't find the error then I'll merge because it may be related to me using Windows.

**Review by lfades — APPROVED** [review]
The example without your changes doesn't work in my windows laptop either, your changes are okay and shouldn't be related. Thank you 👍

**Pull request merged**
