### PR TITLE
[with-apollo] Enable Server-Side Rendering of queries

### PR DESCRIPTION
**Pull request by brunocrosier**
While the current branch does support `useQuery` and `useMutation` hooks, everything is being rendered on the client side. Hence, we see a flash of "loading" before the content of `<PostList>` is shown.

This pull request enables server-side rendering of queries, which provides SEO benefits (this is one of the best features of Next.js after all)

Link to example on CodeSandBox, which has been viewed 2.5k + times : https://codesandbox.io/s/with-apollo-o221g

### CODE REVIEW

**Comment by lfades** [comment]
@rafaelalmeidatk thoughts on this?

**Comment by ijjk** [comment]
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| buildDuration | 27.4s | 27.3s | -141ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 849 B | 852 B | ⚠️ +3 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 839 B | 844 B | ⚠️ +5 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 837 B | 839 B | ⚠️ +2 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| buildDuration | 29.5s | 27.8s | -1.7s |
| nodeModulesSize | 41.3 MB | 41.3 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | brunocrosier/next.js canary | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.3 kB | ✓ |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 865 B | 866 B | ⚠️ +1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.6 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.8 kB | 68.8 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>

**Comment by rafaelalmeidatk** [comment]
I am confused because it seems to remove all the changes I made on my last commit, even the ones that are not related to hooks at all. The example on canary already has SSR (the `apolloState` on `__NEXT_DATA__` is populated without client-side rendering).

@brunocrosier can you double-check the latest changes to the example, please?

**Comment by brunocrosier** [comment]
Hmm I'm not quite sure what you mean. However, this is what the current with-apollo-auth looks like: https://codesandbox.io/s/github/zeit/next.js/tree/canary/examples/with-apollo

You will notice there is a flash of "loading" while the query is running on the client side (as opposed to server side)

https://streamable.com/uqx8b

On my PR this does not happen. The query gets rendered on the server side and therefore there is no "loading"

**Comment by lfades** [comment]
@brunocrosier The current example doesn't have a loading state either, are you sure you have the exampled updated?

**Comment by rafaelalmeidatk** [comment]
I checked the link and the code (`getDataFromTree`, to be more precise) is indeed failing inside CodeSandbox when running on the server, so the posts are fetched in the client afterward, and you see the Loading indicator.

But I can't see what is the exact change that you made to solve this problem since I literally copied and pasted your code and it was still failing. Maybe it is a CodeSandbox thing?

**Comment by brunocrosier** [comment]
to fix your version on codesandbox you can copy and paste my `init-apollo.js` , `with-apollo-client.js` and `package.json` and then restart the container, and it should work

**Comment by rafaelalmeidatk** [comment]
I started receiving this error on my own project, updating the dependencies solved the issue.

**Comment by lfades** [comment]
@rafaelalmeidatk What do you think of the PR now? ignore the changes from the linter that make the build break, I can fix those.

**Comment by rafaelalmeidatk** [comment]
@lfades the core files (`init-apollo.js` and `with-apollo-client.js`) only have linter diffs, so they are the same as the files in `canary`. The other files are undoing the changes on `canary` with a different implementation but it is bringing back some bugs that aren't related with the hooks.

I think this can be closed or be changed to be just an update of package.json (or it may be another PR, idk).

**Comment by lfades** [comment]
@rafaelalmeidatk I agree, I'm closing the PR because the current example is already working as expected.

**Pull request closed without merging**
