### PR TITLE
fix: remove antd from default modularizeImports

### PR DESCRIPTION
**Pull request by MadCcc**
### Fixing a bug

Fix for https://github.com/ant-design/ant-design/issues/46053
Noticed that next server in app-router will import antd from 'antd/es' by default, and this PR https://github.com/vercel/next.js/pull/57968 was commited. 
And in nextjs@14.0.3 it doesn't work in pages-router again because next server could not import antd from 'antd/es' - it should be cjs module.

So it differs in app-router and pages-router, and we cannot specify where to import components from antd, either from 'antd/es' or from 'antd/lib' will break.

The best way is to remove this optimization for antd.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 8b5ec7cfee2bd25733732ff39b02888079e922e4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by vitalijalbu** [comment]
i also have this error

**Comment by w20k** [comment]
Hey @ijjk, apologies for the direct message, but I'm hoping you or a member of your team can assist with antd related issue - current fix might be a solution, but seems like needs to be changes/sync with the latest source. 

Hey @MadCcc, apologies for bothering you too, but I'm hoping you could help again 😊 The code has been updated in the master/develop branch. When you get a chance (or if you'd have a minute), could you take a look and see might be there is a different option to make it work again. Thanks in advance! 😊

I hope I'm not alone in struggling to get antd and the latest version of Next.js to work seamlessly. 😊

**Comment by li-jia-nan** [comment]
mark

**Comment by liuyib** [comment]
has been solved in: https://github.com/vercel/next.js/pull/59294/files

**Comment by w20k** [comment]
Doesn't seem to work with [refine.dev](https://refine.dev) library that I use. 
I will give it another try with a clean project 👍 Thanks a lot @liuyib and a have great upcoming celebrations!

**Comment by timneutkens** [comment]
Going to close this PR as `antd` is no longer in the `modularizeImports` config, it's using the newer `optimizePackageImports` that is more resilient to multiple types of re-exports.

**Comment by khanakia** [comment]
Still getting the error i am using below latest version

I think it's related to `ant-design/icons`

```json
"next": "14.0.4",
"antd": "^5.12.8"
```

```sh
➜  dash git:(main) ✗ yarn dev
yarn run v1.22.19
$ next dev -p 2521
   ▲ Next.js 14.0.4
   - Local:        http://localhost:2521
   - Environments: .env.development.local, .env

 ✓ Ready in 871ms
 ○ Compiling / ...
 ✓ Compiled / in 4.3s (2777 modules)
 ⨯ /Users/lego/myapp/node_modules/@ant-design/icons/es/components/Context.js:1
import { createContext } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/Users/lego/myapp/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at @ant-design/icons/es/components/Context (/Users/lego/myapp/packages/dash/.next/server/pages/_app.js:446:18)
    at __webpack_require__ (/Users/lego/myapp/packages/dash/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/antd/es/config-provider/index.js:16:97)
    at ../../node_modules/antd/es/config-provider/index.js (/Users/lego/myapp/packages/dash/.next/server/vendor-chunks/antd.js:770:1)
    at __webpack_require__ (/Users/lego/myapp/packages/dash/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../node_modules/antd/es/app/index.js:9:74)
 ⨯ /Users/lego/myapp/node_modules/@ant-design/icons/es/components/Context.js:1
import { createContext } from 'react';
^^^^^^
```

**Pull request closed without merging**
