### PR TITLE
Working example for building forms with Next.js

### PR DESCRIPTION
**Pull request by MaedahBatool**
## Feature

- [x] Related issues linked using #32525
- [x] Documentation added

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

### CODE REVIEW

**Comment by leerob** [comment]
It looks like you committed a submodule - could you add the files directly here? 🙏

**Comment by MaedahBatool** [comment]
> It looks like you committed a submodule - could you add the files directly here? 🙏

@leerob Actually the original folder was on my GitHub profile and I cloned it directly in the `examples` folder.  I think that's the issue. Let me fix this. 🙈

**Comment by MaedahBatool** [comment]
[next-forms.zip](https://github.com/vercel/next.js/files/7727145/next-forms.zip)

Here are files.

**Comment by leerob** [comment]
> Actually the original folder was on my GitHub profile and I cloned it directly in the examples folder. I think that's the issue.

Could you update this PR to have the files committed directly, instead of the submodule where you cloned to? 

Then, you should be able to see the files changed in the "Files changed" tab after this 😄

**Comment by MaedahBatool** [comment]
> > Actually the original folder was on my GitHub profile and I cloned it directly in the examples folder. I think that's the issue.
> 
> Could you update this PR to have the files committed directly, instead of the submodule where you cloned to?
> 
> Then, you should be able to see the files changed in the "Files changed" tab after this 😄

Ok makes sense. Thanks for the help. I just need to revise the code files a bit and once that's done I'll commit the final version here. :)

**Comment by MaedahBatool** [comment]
I've submitted a new PR for that: https://github.com/vercel/next.js/pull/32669

**Pull request closed without merging**
