### PR TITLE
Fix statically exported pages from hanging

### PR DESCRIPTION
**Pull request by cloudkite**
When viewing a statically exported page and you click a next `<Link />` if the script fails to load no error is reported.

Looks like the route is mutated to be `${route}/index.js` so if the script fails to load the error is not reported as `pageRegisterEvents.emit` is being called with `${route}/index.js` instead of `route`

### CODE REVIEW

**Comment by cloudkite** [comment]
@timneutkens @arunoda Sorry for pinging you directly, but is there any chance of getting this into v4? This can cause exported pages to hang when loading through a link

**Comment by liweinan0423** [comment]
@cloudkite could you share a repo that can reproduce your issue then we can help investigate?

**Comment by cloudkite** [comment]
@liweinan0423 its a bit hard to reproduce since I ran across this when cache is stale. Here is a scenario in which this happens

Browser has loaded a page from cache but this bundle is now stale since a new one has been published in the meantime, therefore clicking a <Link/> will attempt to load an incorrect bundle (wrong assetPrefix).

This is only an issue in exported pages since `pageRegisterEvents.emit` is being called correctly in (non exported pages) and a therefore the page does a full refresh

**Comment by cloudkite** [comment]
the relevant code is later in the code when it does `this.pageRegisterEvents.emit(route, { error })` because `route` is mutated when the page is exported the event is emitted with the wrong route and the corresponding listener never receives a error event and hence no reload

**Comment by liweinan0423** [comment]
@cloudkite I didn't read through the source code you provided. But off the top of my head, if you published new files, old files should be kept as well so that the opened pages that are on old version  can fetch the old resources correctly

**Review by timneutkens — APPROVED** [review]
Thanks!

**Pull request merged**
