### PR TITLE
fix some issues on examples/app-dir-i18n-routing

### PR DESCRIPTION
**Pull request by cxa**

### CODE REVIEW

**Review by shuding — APPROVED** [review]

**Comment by milovangudelj** [comment]
Was the error catching really necessary?

I was having issues with that code cause `Negotiator` was returning an asterisk (`['*']`) from the `Negotiator.languages()` call, but I solved it by passing it `i18n.locales` as a parameter like so:
```ts
// @ts-ignore locales are readonly
const locales: string[] = i18n.locales;

// Use negotiator and intl-localematcher to get best locale
let languages = new Negotiator({ headers: negotiatorHeaders }).languages(
  locales
);
```

After this everything went back to working as expected. I mentioned this in #51712.

**Comment by cxa** [comment]
I don't realize that `Negotiator` can accept available locales before you mention it. Your method seems more elegant than catching error, just make a PR!

**Comment by milovangudelj** [comment]
Thanks! Will do 😁

**Comment by milovangudelj** [comment]
Opened #51786

**Pull request merged**
