### PR TITLE
Add a viewport meta tag by default

### PR DESCRIPTION
**Pull request by developit**
This implements #6698, adding a conservative but useful viewport meta tag by default.

### CODE REVIEW

**Review by timneutkens — DISMISSED** [review]
Looks it's breaking with AMP support 🤔

**Comment by developit** [comment]
Yup! It's the duplicate viewport tag, fixing.

**Review by dav-is — DISMISSED** [review]
We should probably remove this too 
https://github.com/zeit/next.js/blob/17806e2bb2c8f17aeec5137e050d874116991eb9/packages/next/pages/_error.js#L29

**Comment by timneutkens** [comment]
Good catch @dav-is!

**Comment by developit** [comment]
Good call @dav-is, just updated.

**Review by ijjk — APPROVED** [review]

**Review by Timer — APPROVED** [review]

**Comment by timneutkens** [comment]
Awesome! 💯

**Comment by cesarvarela** [comment]
I think this caused #6919

**Pull request merged**
