### PR TITLE
(example/with-styled-components) Add createGlobalStyle to example

### PR DESCRIPTION
**Pull request by KyleLawson16**
Adds optional styled-components createGlobalStyle method to the example by adding the global stylesheet into the collectStyles method. https://www.styled-components.com/docs/api#createglobalstyle

### CODE REVIEW

**Comment by timneutkens** [comment]
This should be done in _app I think 🤔

**Comment by KyleLawson16** [comment]
@timneutkens I may be mistaken, but when placed in _app, global styles wouldn't load on first paint but would appear after a page refresh. With them included in _document, they are server rendered and ready on first page load?

**Comment by lfades** [comment]
@KyleLawson16 How is this different from creating a global styles component in the same way and adding it to `_app`, or to a page. ?

> global styles wouldn't load on first paint but would appear after a page refresh

All styles should always be included, even global ones.

**Comment by KyleLawson16** [comment]
@lfades I believe the issue has to do with including any kind of font-face declarations or any other declarations that would cause a repaint. Placing these declarations in _document ensures that only the server compiles the style-tags and that they're not recreated when the _app component is re-rendered, preventing buggy styling flashes.

**Comment by lfades** [comment]
@KyleLawson16 I'm closing this because I don't think this is the right solution, if [createGlobalStyle](https://www.styled-components.com/docs/api#createglobalstyle) works as expected then it should be a pure component that doesn't update unless necessary and therefore you can use it anywhere, if that's not the case then wrap it up inside a pure component. If you don't want to re-add it on page navigations use `_app` as @timneutkens said.

**Comment by rwieruch** [comment]
I was looking for the `createGlobalStyle` use case in the with-styled-components-example, but I couldn't find it there. If `_app.js` is a good common sense for adding globals style via styled-components, it may be worth to add it in the example 👍

**Comment by RyanMan56** [comment]
`_app.js` or `_document.js` this should definitely be added to the `with-styled-components` example. I've just moved to NextJS from React and ended up spending a lot of time tonight trying to figure out the best place to include `createGlobalStyle`

**Comment by lcnogueira** [comment]
Hi there, I've just started using next.js:

I decided to do this way:

```js
import App from 'next/app';
import React from 'react';
mport { createGlobalStyle } from 'styled-components';

const GlobalStyle =  createGlobalStyle`
     //my global styles here...
`;

export default class MyApp extends App {
	render() {
		const { Component, pageProps } = this.props;
		return (
			<>
				<Component {...pageProps} />;
				<GlobalStyle />
			</>
		);
	}
}
```

This decision was based on some links of the documentation:
* https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet;
* https://github.com/zeit/next.js/tree/canary/examples/with-styled-components

@lfades is this a good approach?

@rwieruch, do you have any example in your blog?

**Pull request closed without merging**
