### PR TITLE
Update default.mdx

### PR DESCRIPTION
**Pull request by IvoBiaus**
At [File conventions](https://nextjs.org/docs/app/api-reference/file-conventions/default):

Corrected the indicated URLs, since based on the image it's referring to, there is no "dashboard" parent folder around settings.
Image of reference:
image

At [Parallel routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes):
Also corrected the indicated URLs, since based on the referenced images, there is no "dashboard" parent folder.

### CODE REVIEW

**Review by samcx — CHANGES_REQUESTED** [review]
Good catch!

Can you apply the same to https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#defaultjs as well?

**Review by samcx — APPROVED** [review]
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:">:pr:</picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:">:lgtm:</picture>

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ef98fd43838191e7829b78726bcef4eadfad4f5b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ef98fd43838191e7829b78726bcef4eadfad4f5b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by IvoBiaus** [comment]
> Good catch!
> 
> Can you apply the same to https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#defaultjs as well?

Note: at the subsection for "**Conditional Routes**" I didn't removed the "dashboard" because it was not very implied that the location of `@admin` and `@user` was right inside the `app` folder. Also because if i would have changed the file path from "app/dashboard/layout.tsx" to "`app/layout.tsx`" that would be an incorrect "root" layout file. It was better just to keep it that way. If there is a mistake in that section, it might be better to fix the referenced image.

**Pull request merged**
