### PR TITLE
Skip client-side data-fetching after ssr error 

### LINKED ISSUE #47978: Undesirable custom error page behaviour (output + re-fetching data client-side)
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.30
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/tills13/nextjs-error-behaviour-reproduction

### To Reproduce

1. pull repo
2. configure node / npm (I have provided a .nvmrc)
3. run `NODE_ENV=production npx next build && npx next start`
4. navigate to `/`
5. view HTML flashing, console output

### Describe the Bug

1. undesirable console output in production

image

2. error page re-runs `getIntialProps` client-side on the initial render resulting in a mismatch between server HTML and client HTML. This behaviour is different from other pages. Additionally, the `err` received by gIP client-side is different from the error received server-side. I recognize that it cannot be the same instance / class / whatever due to it needing to be serialized. This is more of a nit than anything as the desirable solution would be to just not re-run gIP client-side (see Expected Behaviour)
Re-running gIP client-side also means that long running `getInitialProps` prevents JavaScript from running client-side until `getInitialProps` resolves. I have left some commented code in `_error` to demonstrate this.

### Expected Behavior

1. no output in the console. If I need console output to [instruct users](https://github.com/vercel/next.js/blob/df9de3debb1681f1e99143c8c5ae092860ffa6d5/packages/next/src/client/index.tsx#L373-L377) in production, I will do it myself.
2. ideally the error page would not re-run `getIntialProps` client-side for a server-side error. I'm not too upset about this as our app gIP is fast, but it _can_ result in the server HTML flashing before the client HTML settles.  

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next start

### PR DESCRIPTION
**Pull request by tills13**
Fixes: #47978

When an error occurs in getInitialProps, the error page's getInitialProps is run server-side and returned in `__NEXT_DATA__`. Following, there's no need to re-run `getInitialProps` client-side on the hydrate pass.

### CODE REVIEW

**Review by ijjk — CHANGES_REQUESTED** [review]
Hi, this still should be logged depending on the case. The initial case you mentioned where it's a server-side error in production and the client doesn't have access to it seems like a fair case to not log it but should remain for runtime exceptions and others.

**Comment by tills13** [comment]
@ijjk thanks for the response. The new solution fixes both aspects of the linked issue -- they turned out to be more closely related than I had originally thought. 

If a server-side error occurs (e.g. throwing in getInitialProps or during render) the error is logged in its entirety on the server. I will leave this unchanged though that might not be desirable for people using a structured logger / log parser (Insights, for example).

The _error page is rendered server-side, so for the hydration pass, the only thing that needs to happen is hydration whereas before, the error page component would be fetched (no-op, already available from the initial request) and re-ran.

**Review by ijjk — COMMENTED** [review]
Could we add tests cases for the above to ensure it's behaving as expected?

**Comment by tills13** [comment]
@ijjk any further feedback on this?

**Comment by tills13** [comment]
@ijjk sorry for the repeated bumps but any update on this? Or anything I can do to get this moving along? The JIRA ticket I have assigned to myself at work is looking a little sad / abandoned.

**Comment by TasukuUno** [comment]
@ijjk Hi, I am also waiting for this change to be shipped. I would be happy if you could review it.

**Comment by TasukuUno** [comment]
@ijjk Hi, any updates about this?

**Comment by ijjk** [comment]
## Failing test suites 
Commit: 2fa566dbbb6195e78ae6db451127f34941591ede

`pnpm test test/integration/render-error-on-top-level-error/with-get-initial-props/test/index.test.js`
- Top Level Error > production mode > should render error page with getInitialProps

<details>
<summary>Expand output</summary>

  ● Top Level Error › production mode › should render error page with getInitialProps

    expect(received).toBe(expected) // Object.is equality

    Expected: "Error Rendered with: top level error"
    Received: "Error Rendered with: Cannot read properties of undefined (reading 'Component')"

      31 |       try {
      32 |         const text = await browser.waitForElementByCss('#error-p').text()
    > 33 |         expect(text).toBe('Error Rendered with: top level error')
         |                      ^
      34 |       } finally {
      35 |         await browser.close()
      36 |       }

      at Object.toBe (integration/render-error-on-top-level-error/with-get-initial-props/test/index.test.js:33:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

**Comment by ijjk** [comment]
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| buildDuration | 11s | 10.9s | N/A |
| buildDurationCached | 5.9s | 5.4s | N/A |
| nodeModulesSize | 318 MB | 318 MB | ⚠️ +1.86 kB |
| nextStartRea..uration (ms) | 426ms | 429ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| 3f784ff6-HASH.js gzip | 53.4 kB | 53.4 kB | ✓ |
| 423.HASH.js gzip | 185 B | 181 B | N/A |
| 68-HASH.js gzip | 29.7 kB | 29.7 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 238 B | 242 B | N/A |
| main-HASH.js gzip | 31.8 kB | 31.8 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| Overall change | 100 kB | 100 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 195 B | N/A |
| _error-HASH.js gzip | 182 B | 181 B | N/A |
| amp-HASH.js gzip | 502 B | 501 B | N/A |
| css-HASH.js gzip | 320 B | 322 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 255 B | 256 B | N/A |
| head-HASH.js gzip | 350 B | 349 B | N/A |
| hooks-HASH.js gzip | 368 B | 369 B | N/A |
| image-HASH.js gzip | 4.22 kB | 4.21 kB | N/A |
| index-HASH.js gzip | 257 B | 256 B | N/A |
| link-HASH.js gzip | 2.62 kB | 2.61 kB | N/A |
| routerDirect..HASH.js gzip | 310 B | 311 B | N/A |
| script-HASH.js gzip | 384 B | 383 B | N/A |
| withRouter-HASH.js gzip | 306 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 106 B | 106 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| index.html gzip | 527 B | 527 B | ✓ |
| link.html gzip | 539 B | 539 B | ✓ |
| withRouter.html gzip | 522 B | 521 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| edge-ssr.js gzip | 94 kB | 94 kB | N/A |
| page.js gzip | 149 kB | 149 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 621 B | 624 B | N/A |
| middleware-r..fest.js gzip | 151 B | 149 B | N/A |
| middleware.js gzip | 47.4 kB | 47.4 kB | ✓ |
| edge-runtime..pack.js gzip | 1.94 kB | 1.94 kB | ✓ |
| Overall change | 49.3 kB | 49.3 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | tills13/next.js remove-error-page-debug | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 166 kB | 166 kB | ✓ |
| app-page-exp..prod.js gzip | 95.1 kB | 95.1 kB | ✓ |
| app-page-tur..prod.js gzip | 96.9 kB | 96.9 kB | ✓ |
| app-page-tur..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-page.run...dev.js gzip | 135 kB | 135 kB | ✓ |
| app-page.run..prod.js gzip | 90 kB | 90 kB | ✓ |
| app-route-ex...dev.js gzip | 22 kB | 22 kB | ✓ |
| app-route-ex..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route-tu..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| app-route.ru...dev.js gzip | 21.7 kB | 21.7 kB | ✓ |
| app-route.ru..prod.js gzip | 14.6 kB | 14.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.7 kB | 9.7 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.43 kB | 9.43 kB | ✓ |
| pages-turbo...prod.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim...dev.js gzip | 22.7 kB | 22.7 kB | ✓ |
| pages.runtim..prod.js gzip | 22 kB | 22 kB | ✓ |
| server.runti..prod.js gzip | 49.7 kB | 49.7 kB | ✓ |
| Overall change | 922 kB | 922 kB | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 2fa566dbbb6195e78ae6db451127f34941591ede

**Review by ijjk — COMMENTED** [review]
Hi, sorry for the delay here, re-triggered the test suite and it seems we have some failing cases. We need to ensure a breaking change isn't occurring here.

**Comment by tills13** [comment]
I will take a look right now.

**Comment by tills13** [comment]
not done yet, just unable to run tests on my machine. Syncing with another machine through Github.

**Comment by tills13** [comment]
Hey @ijjk re: https://github.com/vercel/next.js/pull/45185 -- seems like Yarn is still needed for e2e tests here: https://github.com/vercel/next.js/blob/canary/test/lib/next-modes/next-dev.ts#L31-L36

The tests / gh actions install yarn here (I believe): https://github.com/vercel/next.js/blob/canary/.github/workflows/build_reusable.yml#L125

**Comment by tills13** [comment]
ready for a re-review

**Review by ijjk — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
